Macaulay2 Engine: ConcreteVectorArithmetic::elementArray
elementArray()
template<typename RingType > ElementArrayContainer* ConcreteVectorArithmetic< RingType >::elementArray (const ElementArray & f) const inline private
Definition at line 100 of file VectorArithmetic.hpp.
   {
     return reinterpret_cast<ElementArrayContainer*>(f.getValue());
   }
References ElementArray::getValue().
Referenced by ConcreteVectorArithmetic< RingType >::appendToContainer(), ConcreteVectorArithmetic< RingType >::copyElementArray(), ConcreteVectorArithmetic< RingType >::deallocateElementArray(), ConcreteVectorArithmetic< RingType >::denseCancelFromSparse(), ConcreteVectorArithmetic< RingType >::denseNextNonzero(), ConcreteVectorArithmetic< RingType >::denseToSparse(), ConcreteVectorArithmetic< RingType >::displayAsDenseArray(), ConcreteVectorArithmetic< RingType >::displayElement(), ConcreteVectorArithmetic< RingType >::displayElementArray(), ConcreteVectorArithmetic< RingType >::elementArrayFromContainer(), ConcreteVectorArithmetic< RingType >::elementArrayFromContainerOfLongs(), ConcreteVectorArithmetic< RingType >::fillDenseArray(), ConcreteVectorArithmetic< RingType >::from_ring_elem(), ConcreteVectorArithmetic< RingType >::makeMonic(), ConcreteVectorArithmetic< RingType >::pushBackElement(), ConcreteVectorArithmetic< RingType >::pushBackMinusOne(), ConcreteVectorArithmetic< RingType >::pushBackNegatedElement(), ConcreteVectorArithmetic< RingType >::pushBackOne(), ConcreteVectorArithmetic< RingType >::ringElemFromElementArray(), ConcreteVectorArithmetic< RingType >::safeDenseToSparse(), ConcreteVectorArithmetic< RingType >::setZeroInRange(), and ConcreteVectorArithmetic< RingType >::size().