Macaulay2 Engine: ConcreteVectorArithmetic::fillDenseArray
fillDenseArray()
template<typename RingType > void ConcreteVectorArithmetic< RingType >::fillDenseArray (ElementArray & dense, const ElementArray & sparse, const Range< const int > & comps) const inline
Definition at line 164 of file VectorArithmetic.hpp.
   {
     // Note: this function simply fills in the values coming from '(sparse, comps)'.
     //   Other values are not touched.
     // In our intended uses, the input `dense` is the vector consisting of all zeros.
     auto& dvec = * elementArray(dense);
     auto& svec = * elementArray(sparse);
     assert(comps.size() == svec.size());
     assert(comps[comps.size()-1] < dvec.size());
     auto len = comps.size();
     for (ComponentIndex i = 0; i < len; i++) mRing->set(dvec[comps[i]],svec[i]);
   }
References dvec(), ConcreteVectorArithmetic< RingType >::elementArray(), ConcreteVectorArithmetic< RingType >::mRing, and Range< T >::size().