Macaulay2 Engine: ConcreteVectorArithmetic::displayAsDenseArray
displayAsDenseArray()
template<typename RingType > std::ostream & ConcreteVectorArithmetic< RingType >::displayAsDenseArray (std::ostream & o, size_t len, const ElementArray & v, const Range< const int > & comps) const inline
Definition at line 426 of file VectorArithmetic.hpp.
  {
    auto& vec = * elementArray(v);
    auto i = comps.cbegin();
    auto c = vec.cbegin();
    o << "[(" << vec.size() << ") ";
    for (auto j = 0; j < len; ++j)
      {
        if (i == comps.cend() or *i != j)
          o << ". ";
        else
          {
            buffer b;
            mRing->elem_text_out(b, *c, true, true, true);
            o << b.str() << " ";
            ++i;
            ++c;
          }
      }
    o << "]" << std::endl;
    return o;
  }
References Range< T >::cbegin(), Range< T >::cend(), ConcreteVectorArithmetic< RingType >::elementArray(), ConcreteVectorArithmetic< RingType >::mRing, and buffer::str().