Macaulay2 Engine: ConcreteVectorArithmetic::allocateElementArray
allocateElementArray()
template<typename RingType , typename ElementArrayType = ElementArray> ElementArrayType ConcreteVectorArithmetic< RingType, ElementArrayType >::allocateElementArray (ComponentIndex nelems) const inline
Definition at line 87 of file VectorArithmetic.hpp.
   {
     auto tempPtr = new ElementArrayContainer(nelems);
     for (auto& d : *tempPtr)
       {
     mRing->init(d);
     mRing->set_zero(d);
       }
     return ElementArrayType {tempPtr};
   }
References ConcreteVectorArithmetic< RingType, ElementArrayType >::mRing.
Referenced by ConcreteVectorArithmetic< RingType, ElementArrayType >::denseToSparse(), ConcreteVectorArithmetic< RingType, ElementArrayType >::elementArrayFromContainer(), and ConcreteVectorArithmetic< RingType, ElementArrayType >::safeDenseToSparse().