Macaulay2 Engine: ConcreteVectorArithmetic::denseCancelFromSparse
denseCancelFromSparse() [1/2]
template<typename RingType > void ConcreteVectorArithmetic< RingType >::denseCancelFromSparse (ElementArray & dense, const ElementArray & sparse, const Range< const int > & comps) const inline
Definition at line 182 of file VectorArithmetic.hpp.
   {
     // ASSUMPTION: svec[0] == 1.
     auto& dvec = * elementArray(dense);
     auto& svec = * elementArray(sparse);
     typename RingType::Element a(*mRing,dvec[comps[0]]);
     for (int i=1; i < comps.size(); ++i)
       mRing->subtract_multiple(dvec[comps[i]], a, svec[i]);
     mRing->set_zero(dvec[comps[0]]);
   }
References dvec(), ConcreteVectorArithmetic< RingType >::elementArray(), ConcreteVectorArithmetic< RingType >::mRing, and Range< T >::size().