Macaulay2 Engine: ConcreteVectorArithmetic::elementArray
elementArray()
template<typename RingType , typename ElementArrayType = ElementArray> ElementArrayContainer* ConcreteVectorArithmetic< RingType, ElementArrayType >::elementArray (const ElementArrayType & f) const inline private
Definition at line 62 of file VectorArithmetic.hpp.
   {
     return reinterpret_cast<ElementArrayContainer*>(f.getValue());
   }
Referenced by ConcreteVectorArithmetic< RingType, ElementArrayType >::appendToContainer(), ConcreteVectorArithmetic< RingType, ElementArrayType >::copyElementArray(), ConcreteVectorArithmetic< RingType, ElementArrayType >::deallocateElementArray(), ConcreteVectorArithmetic< RingType, ElementArrayType >::denseCancelFromSparse(), ConcreteVectorArithmetic< RingType, ElementArrayType >::denseNextNonzero(), ConcreteVectorArithmetic< RingType, ElementArrayType >::denseToSparse(), ConcreteVectorArithmetic< RingType, ElementArrayType >::displayElementArray(), ConcreteVectorArithmetic< RingType, ElementArrayType >::elementArrayFromContainer(), ConcreteVectorArithmetic< RingType, ElementArrayType >::fillDenseArray(), ConcreteVectorArithmetic< RingType, ElementArrayType >::makeMonic(), ConcreteVectorArithmetic< RingType, ElementArrayType >::pushBackElement(), ConcreteVectorArithmetic< RingType, ElementArrayType >::pushBackMinusOne(), ConcreteVectorArithmetic< RingType, ElementArrayType >::pushBackNegatedElement(), ConcreteVectorArithmetic< RingType, ElementArrayType >::pushBackOne(), ConcreteVectorArithmetic< RingType, ElementArrayType >::ringElemFromElementArray(), ConcreteVectorArithmetic< RingType, ElementArrayType >::safeDenseToSparse(), ConcreteVectorArithmetic< RingType, ElementArrayType >::setZeroInRange(), and ConcreteVectorArithmetic< RingType, ElementArrayType >::size().