Macaulay2 Engine: ConcreteVectorArithmetic::safeDenseToSparse
safeDenseToSparse()
template<typename RingType > template<typename LockType > void ConcreteVectorArithmetic< RingType >::safeDenseToSparse (ElementArray & dense, ElementArray & sparse, Range< int > & comps, int first, int last, MemoryBlock & monomialSpace, LockType & lock) const inline
Definition at line 262 of file VectorArithmetic.hpp.
   {
     auto& dvec = * elementArray(dense);
     int len = 0;
     // first can be -1 if the row is zero.  in this case, we should
     // not be accessing dense[i] for i negative.
     for (int i = first; i >= 0 and i <= last; i++)
     if (not mRing->is_zero(dvec[i])) len++;
     comps = monomialSpace.safeAllocateArray<int,LockType>(len,lock);
     deallocateElementArray(sparse);
     sparse = allocateElementArray(len);
     auto& svec = * elementArray(sparse);
     int next = 0;
     for (int i = first; i >= 0 and i <= last; i++)
       if (not mRing->is_zero(dvec[i]))
     {
       mRing->set(svec[next],dvec[i]);
       comps[next] = i;
       ++next;
       mRing->set_zero(dvec[i]);
     }
   }
References ConcreteVectorArithmetic< RingType >::allocateElementArray(), ConcreteVectorArithmetic< RingType >::deallocateElementArray(), dvec(), ConcreteVectorArithmetic< RingType >::elementArray(), ConcreteVectorArithmetic< RingType >::mRing, and MemoryBlock::safeAllocateArray().