Macaulay2 Engine: ConcreteVectorArithmetic::deallocateElementArray
deallocateElementArray()
template<typename RingType > void ConcreteVectorArithmetic< RingType >::deallocateElementArray (ElementArray & coeffs) const inline
Definition at line 145 of file VectorArithmetic.hpp.
   {
     auto& svec = * elementArray(coeffs);
     for (auto& e : svec) {
       mRing->clear(e);
     }
     delete &svec;
     coeffs.setValue(nullptr);
   }
References ConcreteVectorArithmetic< RingType >::elementArray(), ConcreteVectorArithmetic< RingType >::mRing, and ElementArray::setValue().
Referenced by ConcreteVectorArithmetic< RingType >::safeDenseToSparse().