Macaulay2 Engine: ConcreteVectorArithmetic::denseCancelFromSparse
denseCancelFromSparse() [2/2]
template<typename RingType > void ConcreteVectorArithmetic< RingType >::denseCancelFromSparse (ElementArray & dense, const ElementArray & sparse, const Range< const int > & comps, ElementArray & result_multiplier) const inline
Definition at line 196 of file VectorArithmetic.hpp.
   {
     // ASSUMPTION: svec[0] == 1, comps.size() >= 1
     auto& dvec = * elementArray(dense);
     auto& svec = * elementArray(sparse);
     auto& mults = * elementArray(result_multiplier);
     FieldElement b;
     mRing->init(b);
     mRing->set(b, dvec[comps[0]]);
     FieldElement one;
     mRing->init(one);
     mRing->set_from_long(one, 1);
     if (not mRing->is_equal(svec[0], one))  // should be minus_one
       mRing->negate(b, b);
     for (int i=1; i < comps.size(); ++i)
       {
         mRing->subtract_multiple(dvec[comps[i]], b, svec[i]);
         mStats.incrementNumAdditions();
       }
     mRing->set_zero(dvec[comps[0]]);
     mRing->negate(b, b);
     mults.push_back(b); // this transfers ownership of b.
   }
References dvec(), ConcreteVectorArithmetic< RingType >::elementArray(), VectorArithmeticStats::incrementNumAdditions(), ConcreteVectorArithmetic< RingType >::mRing, ConcreteVectorArithmetic< RingType >::mStats, and Range< T >::size().