Macaulay2 Engine: ConcreteVectorArithmetic::denseToSparse
denseToSparse() [1/2]
template<typename RingType , typename ElementArrayType = ElementArray> void ConcreteVectorArithmetic< RingType, ElementArrayType >::denseToSparse (ElementArrayType & dense, ElementArrayType & sparse, int *& comps, int first, int last, F4Vec & f4Vec) const inline
Definition at line 216 of file VectorArithmetic.hpp.
   {
     auto& dvec = * elementArray(dense);
     int len = 0;
     // first can be -1 if the row is zero.  in this case, we should
     // not be accessing dense[i] for i negative.
     for (int i = first; i >= 0 and i <= last; i++)
     if (not mRing->is_zero(dvec[i])) len++;
     comps = f4Vec.allocate(len);
     sparse = allocateElementArray(len);
     auto& svec = * elementArray(sparse);
     int next = 0;
     for (int i = first; i >= 0 and i <= last; i++)
       if (not mRing->is_zero(dvec[i]))
     {
       mRing->set(svec[next],dvec[i]);
       comps[next] = i;
       ++next;
       mRing->set_zero(dvec[i]);
     }
   }
References F4Vec::allocate(), ConcreteVectorArithmetic< RingType, ElementArrayType >::allocateElementArray(), dvec(), ConcreteVectorArithmetic< RingType, ElementArrayType >::elementArray(), and ConcreteVectorArithmetic< RingType, ElementArrayType >::mRing.