Macaulay2 Engine: QRingInfo::QRingInfo
QRingInfo() [1/2]
QRingInfo::QRingInfo (const PolyRing * R) protected
Definition at line 18 of file qring.cpp.
                                              : R(ambientR)
 {
   exp_size = EXPONENT_BYTE_SIZE(R->n_vars());
   monom_size = MONOMIAL_BYTE_SIZE(R->getMonoid()->monomial_size());
 }
References exp_size, EXPONENT_BYTE_SIZE, PolynomialRing::getMonoid(), monom_size, MONOMIAL_BYTE_SIZE, Monoid::monomial_size(), PolynomialRing::n_vars(), and R.