Macaulay2 Engine: QRingInfo::gbvector_normal_form
gbvector_normal_form() [1/2]
virtual void QRingInfo::gbvector_normal_form (const FreeModule * F, gbvector *& f) const inline virtual
Reimplemented in QRingInfo_ZZ, QRingInfo_field_QQ, and QRingInfo_field_basic.
Definition at line 49 of file qring.hpp.
 {}
Referenced by gbvector_normal_form(), gbA::new_gen(), gbA::process_spair(), ReducedGB_Field::remainder(), and ReducedGB_ZZ::remainder().