Macaulay2 Engine: QRingInfo::n_quotients
n_quotients()
int QRingInfo::n_quotients () const inline
Definition at line 41 of file qring.hpp.
 { return INTSIZE(quotient_ideal); }
References INTSIZE, and quotient_ideal.
Referenced by PolynomialRing::n_quotients(), QRingInfo_field::QRingInfo_field(), and QRingInfo_ZZ::QRingInfo_ZZ().