Macaulay2 Engine: QRingInfo::quotient_gbvector
quotient_gbvector()
const gbvector * QRingInfo::quotient_gbvector (int i) const inline
Definition at line 43 of file qring.hpp.
  {
    return quotient_gbvectors[i];
  }
References quotient_gbvectors.
Referenced by QRingInfo_field_basic::gbvector_normal_form(), QRingInfo_field_QQ::gbvector_normal_form(), QRingInfo_field_QQ::gbvector_normal_form(), and PolynomialRing::quotient_gbvector().