Macaulay2 Engine: QRingInfo::destroy
destroy()
void QRingInfo::destroy (GBRing * GR) virtual
Reimplemented in QRingInfo_ZZ, and QRingInfo_field.
Definition at line 24 of file qring.cpp.
 {
   // remove the gbvector's as they are stashed in gbrings.
   // WARNING: these need to be deleted only if the gbring is non-NULL.
   if (GR == nullptr) return;
   for (int i = 0; i < quotient_gbvectors.size(); i++)
     GR->gbvector_remove(quotient_gbvectors[i]);
 }
References GBRing::gbvector_remove(), and quotient_gbvectors.
Referenced by PolynomialRing::clear(), QRingInfo_field::destroy(), and QRingInfo_ZZ::destroy().