Macaulay2 Engine: F4Mem::show
show()
void F4Mem::show ()
Definition at line 42 of file f4-mem.cpp.
 {
   fprintf(stderr,
           "class\tnalloc\tndealloc\thighwater\ttotal\tfreed\tcurrent\n");
   fprintf(stderr,
           "monom\t%ld\t%ld\t\t%ld\t\t%ld\t%ld\t%ld\n",
           monom_alloc,
           monom_dealloc,
           monom_highwater,
           monom_total,
           monom_freed,
           monom_current);
   components.show();
   coefficients.show();
 }
References coefficients, components, monom_alloc, monom_current, monom_dealloc, monom_freed, monom_highwater, monom_total, and F4Vec::show().
Referenced by F4GB::clear_matrix(), and F4Computation::show().