Macaulay2 Engine: SkewMultiplication::n_skew_vars
n_skew_vars()
int SkewMultiplication::n_skew_vars () const inline
Definition at line 20 of file skew.hpp.
 { return _n_skew; }
References _n_skew.
Referenced by GBRingSkew::GBRingSkew(), GBRing::is_skew_commutative(), GBRing::n_skew_commutative_vars(), and PolynomialRing::n_skew_commutative_vars().