Macaulay2 Engine: SkewMultiplication::mult_sign
mult_sign() [2/2]
int SkewMultiplication::mult_sign (const long * exp1, const long * exp2) const
Definition at line 100 of file skew.cpp.
 {
   exponents_t SKEW1 = ALLOCATE_EXPONENTS(skew_byte_size);
   exponents_t SKEW2 = ALLOCATE_EXPONENTS(skew_byte_size);
   int a = skew_vars(exp1, SKEW1);
   int b = skew_vars(exp2, SKEW2);
   return sort_sign(a, SKEW1, b, SKEW2);
 }
References ALLOCATE_EXPONENTS, mpfr::exp2(), skew_byte_size, skew_vars(), and sort_sign().