Macaulay2 Engine: SkewMultiplication::diff
diff()
int SkewMultiplication::diff (const int * exp1, const int * exp2, int * result) const
Definition at line 109 of file skew.cpp.
 {
   for (int i = 0; i < _n_vars; i++)
     {
       int cmp = exp2[i] - exp1[i];
       if (cmp < 0) return 0;
       result[i] = cmp;
     }
   exponents_t SKEW1 = ALLOCATE_EXPONENTS(skew_byte_size);
   exponents_t SKEW2 = ALLOCATE_EXPONENTS(skew_byte_size);
   int a = skew_vars(result, SKEW1);
   int b = skew_vars(exp1, SKEW2);
   int sign = sort_sign(a, SKEW1, b, SKEW2);
   int c = b % 4;
   if (c == 2 || c == 3) sign = -sign;
   return sign;
 }
References ALLOCATE_EXPONENTS, mpfr::exp2(), and sort_sign().
Referenced by PolyRing::diff_term().