Macaulay2 Engine: SkewMultiplication::skew_variable
skew_variable()
int SkewMultiplication::skew_variable (int i) const inline
Definition at line 22 of file skew.hpp.
 { return _skew_list[i]; }
References _skew_list.
Referenced by GBRingSkew::GBRingSkew(), GBRing::skew_variable(), and PolynomialRing::skew_variable().