Macaulay2 Engine: SkewMultiplication::mult_sign
mult_sign() [1/2]
int SkewMultiplication::mult_sign (const int * exp1, const int * exp2) const
Definition at line 91 of file skew.cpp.
 {
   exponents_t SKEW1 = ALLOCATE_EXPONENTS(skew_byte_size);
   exponents_t SKEW2 = ALLOCATE_EXPONENTS(skew_byte_size);
   int a = skew_vars(exp1, SKEW1);
   int b = skew_vars(exp2, SKEW2);
   return sort_sign(a, SKEW1, b, SKEW2);
 }
References ALLOCATE_EXPONENTS, mpfr::exp2(), skew_byte_size, skew_vars(), and sort_sign().
Referenced by GBRing::find_reduction_coeffs(), GBRing::find_reduction_coeffs_ZZ(), GBRing::gbvector_cancel_lead_terms(), GBRing::gbvector_combine_lead_terms_ZZ(), Matrix::koszul_monomials(), GBRingSkew::mult_by_term1(), QRingInfo_field_basic::reduce_lead_term_basic_field(), QRingInfo_field_QQ::reduce_lead_term_QQ(), MonomialInfo::skew_mult_sign(), ResMonoidDense::skew_mult_sign(), and ResMonoidSparse::skew_mult_sign().