Macaulay2 Engine: SkewMultiplication::skew_vars
skew_vars() [1/2]
int SkewMultiplication::skew_vars (const int * exp, int * result) const
Definition at line 61 of file skew.cpp.
 {
   int i;
   int next = 0;
   for (i = 0; i < _n_skew; i++)
     {
       int v = _skew_list[i];
       if (exp[v] > 0) result[next++] = v;
     }
   return next;
 }
References mpfr::exp().
Referenced by mult_sign(), MonomialInfo::skew_vars(), ResMonoidDense::skew_vars(), and ResMonoidSparse::skew_vars().