Macaulay2 Engine: BIBasis::JanetTree::NonMulti
NonMulti()
template<typename MonomType > std::set< typename MonomType::Integer > BIBasis::JanetTree< MonomType >::NonMulti (const Triple< MonomType > * triple) const
Definition at line 524 of file janettree.hpp.
     {
         std::set<typename MonomType::Integer> result;
         if (triple && Root)
         {
             ConstIterator nodeIterator(Root);
             typename MonomType::Integer var = 0;
             do
             {
                 while (nodeIterator.GetDegree() < triple->GetPolynomLm()[var])
                 {
                     nodeIterator.StepNextDegree();
                 }
                 if (nodeIterator.HasNextDegree())
                 {
                     result.insert(var);
                 }
                 ++var;
                 if (nodeIterator.HasNextVariable())
                 {
                     nodeIterator.StepNextVariable();
                 }
                 else
                 {
                     break;
                 }
             } while(true);
         }
         return result;
     }
References BIBasis::JanetTree< MonomType >::ConstIterator::GetDegree(), BIBasis::Triple< MonomType >::GetPolynomLm(), BIBasis::JanetTree< MonomType >::ConstIterator::HasNextDegree(), BIBasis::JanetTree< MonomType >::ConstIterator::HasNextVariable(), BIBasis::JanetTree< MonomType >::ConstIterator::StepNextDegree(), and BIBasis::JanetTree< MonomType >::ConstIterator::StepNextVariable().