Macaulay2 Engine: BIBasis::JanetTree::Delete
Delete()
template<typename MonomType > void BIBasis::JanetTree< MonomType >::Delete (const Triple< MonomType > * triple)
Definition at line 390 of file janettree.hpp.
     {
         if (!triple)
         {
             return;
         }
         Iterator nodeIterator = Root;
         //count bifurcations
         typename MonomType::Integer var = 0;
         unsigned bifurcations = 0;
         if (nodeIterator.HasNextDegree() && nodeIterator.HasNextVariable())
         {
             ++bifurcations;
         }
         do
         {
             while(nodeIterator.GetDegree() < triple->GetPolynomLm()[var])
             {
                 nodeIterator.StepNextDegree();
                 if (nodeIterator.HasNextDegree() && nodeIterator.HasNextVariable())
                 {
                     ++bifurcations;
                 }
             }
             if (nodeIterator.HasNextVariable())
             {
                 ++var;
                 nodeIterator.StepNextVariable();
                 if (nodeIterator.HasNextDegree() && nodeIterator.HasNextVariable())
                 {
                     ++bifurcations;
                 }
             }
             else
             {
                 break;
             }
         } while(true);
         //deletion
         nodeIterator = Root;
         var = 0;
         bool varDirection = false;
         if (nodeIterator.HasNextDegree() && nodeIterator.HasNextVariable())
         {
             --bifurcations;
         }
         if (!bifurcations)
         {
             if (nodeIterator.GetDegree() < triple->GetPolynomLm()[var])
             {
                 nodeIterator.StepNextDegree();
             }
             else
             {
                 varDirection = true;
             }
         }
         while (bifurcations > 0)
         {
             while(nodeIterator.GetDegree() < triple->GetPolynomLm()[var] && bifurcations > 0)
             {
                 nodeIterator.StepNextDegree();
                 if (nodeIterator.HasNextDegree() && nodeIterator.HasNextVariable())
                 {
                     --bifurcations;
                 }
             }
             if (!bifurcations)
             {
                 if (nodeIterator.GetDegree() < triple->GetPolynomLm()[var])
                 {
                     nodeIterator.StepNextDegree();
                     break;
                 }
                 else
                 {
                     varDirection = true;
                     break;
                 }
             }
             ++var;
             nodeIterator.StepNextVariable();
             if (nodeIterator.HasNextDegree() && nodeIterator.HasNextVariable())
             {
                 --bifurcations;
             }
             if (!bifurcations)
             {
                 if (nodeIterator.GetDegree() < triple->GetPolynomLm()[var])
                 {
                     nodeIterator.StepNextDegree();
                     break;
                 }
                 else
                 {
                     varDirection = true;
                     break;
                 }
             }
         }
         if (varDirection)
         {
             Iterator tmpIterator = nodeIterator;
             tmpIterator.StepNextVariable();
             tmpIterator.Clear();
             nodeIterator.Delete();
         }
         else
         {
             nodeIterator.Clear();
         }
     }
References BIBasis::JanetTree< MonomType >::Iterator::Clear(), BIBasis::JanetTree< MonomType >::Iterator::Delete(), BIBasis::JanetTree< MonomType >::Iterator::GetDegree(), BIBasis::Triple< MonomType >::GetPolynomLm(), BIBasis::JanetTree< MonomType >::Iterator::HasNextDegree(), BIBasis::JanetTree< MonomType >::Iterator::HasNextVariable(), BIBasis::JanetTree< MonomType >::Iterator::StepNextDegree(), and BIBasis::JanetTree< MonomType >::Iterator::StepNextVariable().
Referenced by BIBasis::JanetTree< MonomType >::Iterator::Clear().