Macaulay2 Engine: BIBasis::JanetTree::Find
Find()
template<typename MonomType > const Triple< MonomType > * BIBasis::JanetTree< MonomType >::Find (const MonomType & monom) const
Definition at line 303 of file janettree.hpp.
    {
        const Triple<MonomType>* triple = 0;
        if (Root)
        {
            ConstIterator nodeIterator = Root;
            typename MonomType::Integer degree = monom.Degree();
            typename MonomType::Integer var = 0;
            do
            {
                if (nodeIterator.GetDegree() != monom[var] && nodeIterator.HasNextDegree())
                {
                    nodeIterator.StepNextDegree();
                }
                if (nodeIterator.GetDegree() != monom[var])
                {
                    break;
                }
                else if (nodeIterator.HasNextVariable())
                {
                    degree -= monom[var];
                    if (!degree)
                    {
                        break;
                    }
                    ++var;
                    nodeIterator.StepNextVariable();
                }
                else
                {
                    triple = nodeIterator.GetTriple();
                    break;
                }
            } while(true);
        }
        return triple;
    }
References BIBasis::JanetTree< MonomType >::ConstIterator::GetDegree(), BIBasis::JanetTree< MonomType >::ConstIterator::GetTriple(), BIBasis::JanetTree< MonomType >::ConstIterator::HasNextDegree(), BIBasis::JanetTree< MonomType >::ConstIterator::HasNextVariable(), BIBasis::JanetTree< MonomType >::ConstIterator::StepNextDegree(), and BIBasis::JanetTree< MonomType >::ConstIterator::StepNextVariable().