Macaulay2 Engine: BIBasis::JanetTree::Insert
Insert()
template<typename MonomType > void BIBasis::JanetTree< MonomType >::Insert (Triple< MonomType > * triple)
Definition at line 344 of file janettree.hpp.
     {
         if (!triple)
         {
             return;
         }
         typename MonomType::Integer degree = triple->GetPolynomLm().Degree();
         typename JanetTree<MonomType>::Iterator nodeIterator(Root);
         if (!Root)
         {
             nodeIterator.Build(degree, 0, triple);
         }
         else
         {
             typename MonomType::Integer var = 0;
             do
             {
                 while(nodeIterator.GetDegree() < triple->GetPolynomLm()[var] && nodeIterator.HasNextDegree())
                 {
                     nodeIterator.StepNextDegree();
                 }
                 if (nodeIterator.GetDegree() > triple->GetPolynomLm()[var])
                 {
                     nodeIterator.Build(degree, var, triple);
                     break;
                 }
                 else if (nodeIterator.GetDegree() == triple->GetPolynomLm()[var])
                 {
                     degree -= triple->GetPolynomLm()[var];
                     ++var;
                     nodeIterator.StepNextVariable();
                 }
                 else
                 {
                     nodeIterator.StepNextDegree();
                     nodeIterator.Build(degree, var, triple);
                     break;
                 }
             } while(true);
         }
     }
References BIBasis::JanetTree< MonomType >::Iterator::Build(), BIBasis::JanetTree< MonomType >::Iterator::GetDegree(), BIBasis::Triple< MonomType >::GetPolynomLm(), BIBasis::JanetTree< MonomType >::Iterator::HasNextDegree(), BIBasis::JanetTree< MonomType >::Iterator::StepNextDegree(), and BIBasis::JanetTree< MonomType >::Iterator::StepNextVariable().