Macaulay2 Engine: ResMonomialSorter::toMonomial
toMonomial()
void ResMonomialSorter::toMonomial (res_packed_monomial mon, std::pair< int *, int * > resultAlreadyAllocateds) inline private
Definition at line 130 of file res-monomial-sorter.hpp.
   {
     int comp, comp2;
     int nvars = mMonoid.n_vars();
     std::pair<int*, int*> exp = mArena.allocArrayNoCon<int>(nvars);
     std::pair<int*, int*> exp2 = mArena.allocArrayNoCon<int>(nvars);
     mResMonoid.to_expvector(mon, exp.first, comp);
     mResMonoid.to_expvector(mSchreyerOrder.mTotalMonom[comp], exp2.first, comp2);
     exponents::mult(nvars, exp.first, exp2.first, exp2.first);
     auto p = resultAlreadyAllocateds.first;
     *p++ = mSchreyerOrder.mTieBreaker[comp];
     *p++ = comp2;
     mMonoid.from_expvector(exp2.first, p);
     mArena.freeTop(exp2.first); // note: can only pop one at a time from an mt::Arena!
     mArena.freeTop(exp.first);
   }
References mpfr::exp(), mpfr::exp2(), Monoid::from_expvector(), mArena, mMonoid, mResMonoid, mSchreyerOrder, ResSchreyerOrder::mTieBreaker, ResSchreyerOrder::mTotalMonom, ExponentVector< E, OC >::mult(), Monoid::n_vars(), p, and ResMonoidDense::to_expvector().
Referenced by setMonoms().