Macaulay2 Engine: ResMonomialSorter::setMonoms
setMonoms()
void ResMonomialSorter::setMonoms () inline
Definition at line 89 of file res-monomial-sorter.hpp.
   {
     for (int i=0; i<mColumns.size(); i++)
       {
         std::pair<int*, int*> mon = mArena.allocArrayNoCon<int>(mMonoid.monomial_size() + 2);
         toMonomial(mColumns[i], mon);
         mMonoms.push_back(mon.first);
       }
   }
References mArena, mColumns, mMonoid, mMonoms, Monoid::monomial_size(), and toMonomial().
Referenced by ordered(), and sort().