Macaulay2 Engine: ResMonomialSorter::sort
sort()
std::vector<int> ResMonomialSorter::sort () inline
Definition at line 110 of file res-monomial-sorter.hpp.
   {
     setMonoms();
     std::vector<int> result;
     for (int i=0; i<mColumns.size(); i++)
       result.push_back(i);
     MonomialSorterObject C(mMonoid, mMonoms);
     C.resetNumComparisons();
     std::stable_sort(result.begin(), result.end(), C);
     mNumComparisons = C.numComparisons();
     return result;
   }
References mColumns, mMonoid, mMonoms, mNumComparisons, MonomialSorterObject::numComparisons(), MonomialSorterObject::resetNumComparisons(), and setMonoms().