Macaulay2 Engine: M2FreeAlgebra::lift
lift()
bool M2FreeAlgebra::lift (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 143 of file M2FreeAlgebra.cpp.
 {
   // R is the target ring
   // f1 is an element of 'this'.
   // set result to be the "lift" of f in the ring R, return true if this is possible.
   // otherwise return false.
   // case: R is the coefficient ring of 'this'.
   std::cout << "called lift NC case" << std::endl;
   if (R == coefficientRing())
     {
       auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
       if (f->numTerms() != 1) return false;
       auto i = f->cbegin();
       if (monoid().is_one(i.monom()))
         {
           result = coefficientRing()->copy(i.coeff());
           return true;
         }
     }
   // at this point, we can't lift it.
   return false;
 }
References coefficientRing(), Ring::copy(), ring_elem::get_Poly(), FreeMonoid::is_one(), and monoid().