Macaulay2 Engine: M2FreeAlgebra::lead_coefficient
lead_coefficient() [1/2]
ring_elem M2FreeAlgebra::lead_coefficient (const Ring * coeffRing, const Poly * f) const
Definition at line 382 of file M2FreeAlgebra.cpp.
 {
   if (coeffRing != coefficientRing())
     {
       throw exc::engine_error("unexpected coefficient ring");
     }
   if (f->numTerms() == 0) return coeffRing->zero();
   return *(f->cbeginCoeff());
 }
References coefficientRing(), and Ring::zero().
Referenced by invert(), RingElement::lead_coeff(), M2FreeAlgebraQuotient::lead_coefficient(), and lead_coefficient().