Macaulay2 Engine: M2FreeAlgebra::n_terms
n_terms()
long M2FreeAlgebra::n_terms (const ring_elem f) const
Definition at line 174 of file M2FreeAlgebra.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
   return freeAlgebra().n_terms(*f);
 }
References freeAlgebra(), ring_elem::get_Poly(), and FreeAlgebra::n_terms().
Referenced by is_zero(), and RingElement::n_terms().