Macaulay2 Engine: M2FreeAlgebra::get_terms
get_terms() [1/2]
Poly * M2FreeAlgebra::get_terms (const Poly * f, int lo, int hi) const
Definition at line 390 of file M2FreeAlgebra.cpp.
{
  auto result = new Poly;
  auto& outcoeff = result->getCoeffInserter();
  auto& outmonom = result->getMonomInserter();
  int which = 0;
  for(auto i=f->cbegin(); i != f->cend() and which <= hi; ++i, ++which)
    {
      if (which < lo) continue;
      outcoeff.push_back(i.coeff());
      monoid().copy(i.monom(), outmonom);
    }
  return result;
}
References FreeMonoid::copy(), and monoid().
Referenced by M2FreeAlgebraQuotient::get_terms(), get_terms(), M2FreeAlgebraQuotient::get_terms(), and RingElement::get_terms().