Macaulay2 Engine: M2FreeAlgebra::index_of_var
index_of_var()
int M2FreeAlgebra::index_of_var (const ring_elem a) const virtual
Reimplemented from Ring.
Definition at line 85 of file M2FreeAlgebra.cpp.
 {
   // This function is needed at top level to be able to determine if a ring element is a variable
   //const Poly* f = reinterpret_cast<Poly*>(a.poly_val);
   auto f = reinterpret_cast<const Poly*>(a.get_Poly());
   // f is a variable iff: #terms is 1, monomial is [3,1,v], coeff is 1
   if (f->numTerms() != 1) return -1;
   auto i = f->cbegin();
   if (!coefficientRing()->is_equal(coefficientRing()->one(), i.coeff())) return -1;
   return monoid().index_of_variable(i.monom());
 }
References coefficientRing(), ring_elem::get_Poly(), FreeMonoid::index_of_variable(), Ring::is_equal(), monoid(), and Ring::one().
Referenced by M2FreeAlgebraQuotient::index_of_var().