Macaulay2 Engine: M2FreeAlgebra::eval
eval()
ring_elem M2FreeAlgebra::eval (const RingMap * map, const ring_elem f, int first_var) const virtual
Implements Ring.
Definition at line 334 of file M2FreeAlgebra.cpp.
 {
   // map: R --> S, this = R.
   // f is an ele ment in R
   // return an element of S.
   auto f = reinterpret_cast<const Poly*>(ff.get_Poly());
   return freeAlgebra().eval(map, *f, first_var);
 }
References FreeAlgebra::eval(), freeAlgebra(), and ring_elem::get_Poly().