Macaulay2 Engine: M2FreeAlgebra::negate
negate()
ring_elem M2FreeAlgebra::negate (const ring_elem f) const virtual
Implements Ring.
Definition at line 208 of file M2FreeAlgebra.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
   Poly* result = new Poly;
   freeAlgebra().negate(*result, *f);
   return ring_elem(reinterpret_cast<void *>(result));
 }
References freeAlgebra(), ring_elem::get_Poly(), and FreeAlgebra::negate().