Macaulay2 Engine: M2FreeAlgebra::compare_elems
compare_elems()
int M2FreeAlgebra::compare_elems (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 190 of file M2FreeAlgebra.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
   auto g = reinterpret_cast<const Poly*>(g1.get_Poly());
   return freeAlgebra().compare_elems(*f,*g);
 }
References FreeAlgebra::compare_elems(), freeAlgebra(), and ring_elem::get_Poly().