Macaulay2 Engine: M2FreeAlgebra::support
support()
M2_arrayint M2FreeAlgebra::support (const ring_elem a) const virtual
Reimplemented from Ring.
Definition at line 407 of file M2FreeAlgebra.cpp.
 {
   const Poly* f = reinterpret_cast<const Poly*>(a.get_Poly());
   return freeAlgebra().support(*f);
 }
References freeAlgebra(), ring_elem::get_Poly(), and FreeAlgebra::support().