Macaulay2 Engine: M2FreeAlgebra::list_form
list_form()
engine_RawArrayPairOrNull M2FreeAlgebra::list_form (const Ring * coeffR, const ring_elem f) const virtual
Definition at line 343 of file M2FreeAlgebra.cpp.
 {
   // Either coeffR should be the actual coefficient ring (possible a "toField"ed ring)
   // or a polynomial ring.  If not, NULL is returned and an error given
   // In the latter case, the last set of variables are part of
   // the coefficients.
   auto f = reinterpret_cast<const Poly*>(ff.get_Poly());
   if (coeffR != coefficientRing())
     {
       ERROR("expected coefficient ring");
       return nullptr;
     }
   int nterms = static_cast<int>(f->numTerms());
   engine_RawMonomialArray monoms = GETMEM(engine_RawMonomialArray, sizeofarray(monoms,nterms));
   engine_RawRingElementArray coeffs = GETMEM(engine_RawRingElementArray, sizeofarray(coeffs,nterms));
   engine_RawArrayPair result = newitem(struct engine_RawArrayPair_struct);
   monoms->len = nterms;
   coeffs->len = nterms;
   result->monoms = monoms;
   result->coeffs = coeffs;
   // fill result
   std::vector<int> vp;
   int next = 0;
   for (auto i=f->cbegin(); i != f->cend(); ++i, ++next)
     {
       ring_elem c = coefficientRing()->copy(i.coeff());
       vp.resize(0);
       monoid().getMonomialReversed(i.monom(), vp); // should this instead reverse the monomial?
       coeffs->array[next] = RingElement::make_raw(coeffR, c);
       monoms->array[next] = EngineMonomial::make(vp); // reverses the monomial
     }
   return result;
 }
References coefficientRing(), Ring::copy(), ERROR(), ring_elem::get_Poly(), GETMEM, FreeMonoid::getMonomialReversed(), EngineMonomial::make(), RingElement::make_raw(), monoid(), newitem, and sizeofarray.
Referenced by IM2_RingElement_list_form(), and M2FreeAlgebraQuotient::list_form().