Macaulay2 Engine: M2FreeAlgebra::add
add()
ring_elem M2FreeAlgebra::add (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 218 of file M2FreeAlgebra.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
   auto g = reinterpret_cast<const Poly*>(g1.get_Poly());
   auto result = new Poly;
   freeAlgebra().add(*result,*f,*g);
   return ring_elem(reinterpret_cast<void *>(result));
 }
References FreeAlgebra::add(), freeAlgebra(), and ring_elem::get_Poly().