Macaulay2 Engine: M2FreeAlgebra::coefficientRing
coefficientRing()
const Ring* M2FreeAlgebra::coefficientRing () const inline virtual
Implements M2FreeAlgebraOrQuotient.
Definition at line 76 of file M2FreeAlgebra.hpp.
 { return freeAlgebra().coefficientRing(); }
References FreeAlgebra::coefficientRing(), and freeAlgebra().
Referenced by M2FreeAlgebraQuotient::coefficientRing(), M2FreeAlgebraQuotient::create(), debug_display(), from_int(), from_long(), from_rational(), index_of_var(), invert(), lead_coefficient(), lift(), list_form(), promote(), and text_out().