Macaulay2 Engine: M2FreeAlgebra::power
power() [2/2]
ring_elem M2FreeAlgebra::power (const ring_elem f, mpz_srcptr n) const virtual
Reimplemented from Ring.
Definition at line 245 of file M2FreeAlgebra.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
   auto result = new Poly;
   freeAlgebra().power(*result,*f,n);
   return ring_elem(reinterpret_cast<void *>(result));
 }
References freeAlgebra(), ring_elem::get_Poly(), and FreeAlgebra::power().