Macaulay2 Engine: M2FreeAlgebra::debug_display
debug_display() [1/2]
void M2FreeAlgebra::debug_display (const Poly * f) const
Definition at line 287 of file M2FreeAlgebra.cpp.
{
  std::cout << "coeffs: ";
  for (auto i=f->cbeginCoeff(); i != f->cendCoeff(); ++i)
    {
      buffer o;
      coefficientRing()->elem_text_out(o, *i);
      std::cout << o.str() << " ";
    }
  std::cout << std::endl  << "  monoms: ";
  for (auto i=f->cbeginMonom(); i != f->cendMonom(); ++i)
    {
      std::cout << (*i) << " ";
    }
  std::cout << std::endl;
}
References coefficientRing(), Ring::elem_text_out(), and buffer::str().
Referenced by debug_display().