Macaulay2 Engine: M2FreeAlgebra::subtract
subtract()
ring_elem M2FreeAlgebra::subtract (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 227 of file M2FreeAlgebra.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
   auto g = reinterpret_cast<const Poly*>(g1.get_Poly());
   auto result = new Poly;
   freeAlgebra().subtract(*result,*f,*g);
   return ring_elem(reinterpret_cast<void *>(result));
 }
References freeAlgebra(), ring_elem::get_Poly(), and FreeAlgebra::subtract().