Macaulay2 Engine: M2FreeAlgebra::divide
divide()
ring_elem M2FreeAlgebra::divide (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 271 of file M2FreeAlgebra.cpp.
 {
   ring_elem ginv = invert(g); // this will throw an error unless g is invertible in the coeff ring
   return mult(ginv, f);
 }
References invert(), and mult().
Referenced by M2FreeAlgebraQuotient::divide().