Macaulay2 Engine: M2FreeAlgebra::from_coefficient
from_coefficient()
ring_elem M2FreeAlgebra::from_coefficient (const ring_elem a) const virtual
Implements M2FreeAlgebraOrQuotient.
Definition at line 96 of file M2FreeAlgebra.cpp.
 {
   auto result = new Poly;
   freeAlgebra().from_coefficient(*result, a);
   return ring_elem(reinterpret_cast<void *>(result));
 }
References freeAlgebra(), and FreeAlgebra::from_coefficient().
Referenced by from_int(), from_long(), from_rational(), invert(), and promote().