Macaulay2 Engine: M2FreeAlgebra::elem_text_out
elem_text_out()
void M2FreeAlgebra::elem_text_out (buffer & o, const ring_elem f, bool p_one, bool p_plus, bool p_parens) const virtual
Implements Ring.
Definition at line 326 of file M2FreeAlgebra.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(ff.get_Poly());
   freeAlgebra().elem_text_out(o,*f,p_one,p_plus,p_parens);
 }
References FreeAlgebra::elem_text_out(), freeAlgebra(), and ring_elem::get_Poly().