Macaulay2 Engine: M2FreeAlgebra::create
create()
M2FreeAlgebra * M2FreeAlgebra::create (const Ring * K, const std::vector< std::string > & names, const PolynomialRing * degreeRing, const std::vector< int > & degrees, const std::vector< int > & wtvecs, const std::vector< int > & heftVector) static
Definition at line 44 of file M2FreeAlgebra.cpp.
 {
   assert(K != nullptr);
   auto F = std::unique_ptr<FreeAlgebra>(FreeAlgebra::create(K, names, degreeRing, degrees, wtvecs, heftVector));
   M2FreeAlgebra* result = new M2FreeAlgebra(std::move(F));
   result->initialize_ring(K->characteristic(), degreeRing, nullptr);
   result->zeroV = result->from_long(0);
   result->oneV = result->from_long(1);
   result->minus_oneV = result->from_long(-1);
   return result;
 }
References Ring::characteristic(), FreeAlgebra::create(), degreeRing(), from_long(), Ring::initialize_ring(), M2FreeAlgebra(), Ring::minus_oneV, Ring::oneV, and Ring::zeroV.
Referenced by rawRingM2FreeAlgebra().