Macaulay2 Engine: M2FreeAlgebra::freeAlgebra
freeAlgebra()
const FreeAlgebra& M2FreeAlgebra::freeAlgebra () const inline virtual
Implements M2FreeAlgebraOrQuotient.
Definition at line 73 of file M2FreeAlgebra.hpp.
 { return *mFreeAlgebra; }
References mFreeAlgebra.
Referenced by add(), coefficientRing(), compare_elems(), copyMatrixToVector(), M2FreeAlgebraQuotient::create(), elem_text_out(), eval(), M2FreeAlgebraQuotient::freeAlgebra(), from_coefficient(), is_equal(), is_homogeneous(), is_unit(), make_SumCollector(), monoid(), mult(), multi_degree(), n_terms(), negate(), power(), rawNCBasis(), rawNCGroebnerBasisTwoSided(), rawNCReductionTwoSided(), subtract(), support(), and var().