Macaulay2 Engine: M2FreeAlgebra::text_out
text_out()
void M2FreeAlgebra::text_out (buffer & o) const virtual
Implements Ring.
Definition at line 66 of file M2FreeAlgebra.cpp.
 {
   coefficientRing()->text_out(o);
   o << "{";
   for (int i = 0; i < monoid().variableNames().size(); i++)
     {
       if (i > 0) o << ",";
       o << monoid().variableNames()[i];
     }
   o << "}";
 }
References coefficientRing(), monoid(), Ring::text_out(), and FreeMonoid::variableNames().
Referenced by M2FreeAlgebraQuotient::text_out().