Macaulay2 Engine: M2FreeAlgebra::monoid
monoid()
const FreeMonoid& M2FreeAlgebra::monoid () const inline
Definition at line 72 of file M2FreeAlgebra.hpp.
 { return freeAlgebra().monoid(); }
References freeAlgebra(), and FreeAlgebra::monoid().
Referenced by degreeMonoid(), M2FreeAlgebraQuotient::degreeMonoid(), degreeRing(), get_terms(), index_of_var(), lift(), list_form(), makeTerm(), M2FreeAlgebraQuotient::monoid(), numVars(), and text_out().