Macaulay2 Engine: M2FreeAlgebra::invert
invert()
ring_elem M2FreeAlgebra::invert (const ring_elem f) const virtual
Implements Ring.
Definition at line 261 of file M2FreeAlgebra.cpp.
 {
   if (not is_unit(f))
     throw exc::engine_error("attempting to divide by a non-unit");
   ring_elem cf = lead_coefficient(coefficientRing(), f);
   // At this point, f should be an element of the coefficient ring, times the monomial 1.
   // The following will throw an error if it cannot invert the element.
   ring_elem finv = coefficientRing()->invert(cf);
   return from_coefficient(finv);
 }
References coefficientRing(), from_coefficient(), Ring::invert(), is_unit(), and lead_coefficient().
Referenced by divide(), and M2FreeAlgebraQuotient::invert().