Macaulay2 Engine: main
main()
int main ()
Definition at line 376 of file franzi-brp-test.cpp.
 {
   cout << "Hello Testing Friends!" << endl;
   testEquality0();
   testEquality1();
   testEquality();
   testAddition();
   testAddition2();
   testAddition3();
   testAddition4();
   testMultiplication();
   testDivide();
   testLT();
   testIsLeadingReducibleBy();
   testRemainder();
   testIsRelativelyPrime();
   testOrder();
 }
References testAddition(), testAddition2(), testAddition3(), testAddition4(), testDivide(), testEquality(), testEquality0(), testEquality1(), testIsLeadingReducibleBy(), testIsRelativelyPrime(), testLT(), testMultiplication(), testOrder(), and testRemainder().