Macaulay2 Engine: testIsRelativelyPrime
testIsRelativelyPrime()
void testIsRelativelyPrime ()
Definition at line 343 of file franzi-brp-test.cpp.
{
  BRP f = BRP(2) * BRP(8) + BRP(7);
  if (BRP::isRelativelyPrime(f.LT(), BRP(8).LT()))
    {
      cout << "error" << endl;
    }
  if (BRP::isRelativelyPrime(BRP(8).LT(), f.LT()))
    {
      cout << "error" << endl;
    }
  if (BRP::isRelativelyPrime(BRP(2).LT(), f.LT()))
    {
      cout << "error" << endl;
    }
  if (!BRP::isRelativelyPrime(f.LT(), BRP(1).LT()))
    {
      cout << "error" << endl;
    }
  if (!BRP::isRelativelyPrime(BRP(1).LT(), f.LT()))
    {
      cout << "error" << endl;
    }
  if (!BRP::isRelativelyPrime(BRP(1).LT(), BRP(0).LT()))
    {  // x, 1
      cout << "error" << endl;
    }
  if (!BRP::isRelativelyPrime(f.LT(), BRP(0).LT()))
    {  // f, 1
      cout << "error" << endl;
    }
}
References BRP::isRelativelyPrime(), BRP::LT(), and LT.
Referenced by main().