Macaulay2 Engine: GBRing::GBRing
GBRing()
GBRing::GBRing (const Ring * K0, const Monoid * M0) protected
Definition at line 55 of file gbring.cpp.
     : _schreyer_encoded(true),
       M(M0),
       K(K0),
       _coeffs_ZZ(false),  // set below
       zzp(nullptr),
       _nvars(M->n_vars()),
       _up_order(false),
       _is_skew(false),
       _skew(),
       _skew_monoms(nullptr),
       is_weyl(false),
       weyl(nullptr),
       is_solvable(false),
       solvable(nullptr),
       _one(K->from_long(1))
 {
   exp_size = EXPONENT_BYTE_SIZE(_nvars + 2);
   monom_size = MONOMIAL_BYTE_SIZE(M->monomial_size());
   gbvector_size = sizeofgbvector(((gbvector *)nullptr), M->monomial_size());
   mem = new stash("gbvector", gbvector_size);
   const Z_mod *Kp = K->cast_to_Z_mod();
   if (Kp != nullptr) zzp = Kp->get_CoeffRing();
   if (K == globalQQ) K = globalZZ;
   if (K == globalZZ) _coeffs_ZZ = true;
 }
References _coeffs_ZZ, _nvars, Ring::cast_to_Z_mod(), exp_size, EXPONENT_BYTE_SIZE, gbvector_size, Z_mod::get_CoeffRing(), globalQQ, globalZZ, K, M, mem, monom_size, MONOMIAL_BYTE_SIZE, Monoid::monomial_size(), sizeofgbvector, and zzp.