Macaulay2 Engine: GBRing::exponents_delete
exponents_delete()
void GBRing::exponents_delete (exponents_t e)
Definition at line 44 of file gbring.cpp.
 { freemem(e); }
References freemem().
Referenced by ReducedGB_ZZ::find_divisor(), ReducedGB_Field_Local::minimalize(), ReducedGB_Field::minimalize(), and ReducedGB_Field_Local::remainder().