Macaulay2 Engine: GBRing::gbvector_auto_reduce
gbvector_auto_reduce()
void GBRing::gbvector_auto_reduce (const FreeModule * F, const FreeModule * Fsyz, gbvector *& f, gbvector *& fsyz, const gbvector * g, const gbvector * gsyz)
Definition at line 1419 of file gbring.cpp.
 {
   const gbvector *t;
   if ((t = find_coeff(F, f, g)) != 0)
     {
       ring_elem u, v;
       K->syzygy(t->coeff, g->coeff, u, v);
       if (!K->is_equal(u, _one))
         {
           gbvector_mult_by_coeff_to(f, u);
           gbvector_mult_by_coeff_to(fsyz, u);
         }
       gbvector *g1 = gbvector_mult_by_coeff(g, v);
       gbvector *gsyz1 = gbvector_mult_by_coeff(gsyz, v);
       gbvector_add_to(F, f, g1);
       gbvector_add_to(Fsyz, fsyz, gsyz1);
       gbvector_remove_content(f, fsyz);
       if (M2_gbTrace == 10)
         {
           buffer o;
           o << "auto reducing by ";
           gbvector_text_out(o, F, g);
           o << "\n  --  giving ";
           gbvector_text_out(o, F, f);
           emit_line(o.str());
         }
     }
 }
References _one, gbvector::coeff, emit_line(), find_coeff(), gbvector_add_to(), gbvector_mult_by_coeff(), gbvector_mult_by_coeff_to(), gbvector_remove_content(), gbvector_text_out(), Ring::is_equal(), K, M2_gbTrace, buffer::str(), and Ring::syzygy().
Referenced by gbA::auto_reduce_by(), GB_comp::auto_reduce_step(), gbA::do_computation(), and gb2_comp::gb_insert().