Macaulay2 Engine: GBRing::gbvector_compare
gbvector_compare()
int GBRing::gbvector_compare (const FreeModule * F, const gbvector * f, const gbvector * g) const
Definition at line 407 of file gbring.cpp.
 {
   int cmp;
   const SchreyerOrder *S = F->get_schreyer_order();
   if (S)
     {
       if (_schreyer_encoded)
         cmp = S->schreyer_compare_encoded(
             f->monom, f->comp - 1, g->monom, g->comp - 1);
       else
         cmp = S->schreyer_compare(f->monom, f->comp - 1, g->monom, g->comp - 1);
     }
   else
     {
       // At this point F doesn't have a Schreyer order
       if (_up_order)
         cmp = M->compare(f->monom, -f->comp, g->monom, -g->comp);
       else
         cmp = M->compare(f->monom, f->comp, g->monom, g->comp);
     }
   return cmp;
 }
References SchreyerOrder::schreyer_compare(), and SchreyerOrder::schreyer_compare_encoded().
Referenced by SPolySorter::compare(), GB_comp::gb_sort_partition(), gbvector_add_to(), gbvector_add_to_zzp(), gbvectorHeap::get_lead_term(), ReducedGB_Field_Local_sorter::operator()(), ReducedGB_Field_sorter::operator()(), MarkedGB_sorter::operator()(), and ReducedGB_ZZ_sorter::operator()().