Macaulay2 Engine: GBRing::gbvector_add_to_zzp
gbvector_add_to_zzp()
void GBRing::gbvector_add_to_zzp (const FreeModule * F, gbvector *& f, gbvector *& g)
Definition at line 582 of file gbring.cpp.
 {
   if (g == NULL) return;
   if (f == NULL)
     {
       f = g;
       g = NULL;
       return;
     }
   gbvector head;
   gbvector *result = &head;
   while (1)
     {
       int compare_result = gbvector_compare(F, f, g);
       if (compare_result == LT)
         {
           result->next = g;
           result = result->next;
           g = g->next;
           if (g == NULL)
             {
               result->next = f;
               f = head.next;
               return;
             }
         }
       else if (compare_result == GT)
         {
           result->next = f;
           result = result->next;
           f = f->next;
           if (f == NULL)
             {
               result->next = g;
               f = head.next;
               g = NULL;
               return;
             }
         }
       else
         {
           gbvector *tmf = f;
           gbvector *tmg = g;
           f = f->next;
           g = g->next;
           CoefficientRingZZp::elem result_coeff;
           zzp->init(result_coeff);
           zzp->add(result_coeff, tmf->coeff.get_int(), tmg->coeff.get_int());
           tmf->coeff = ring_elem(result_coeff);
           if (zzp->is_zero(tmf->coeff.get_int()))
             {
               gbvector_remove_term(tmf);
             }
           else
             {
               result->next = tmf;
               result = result->next;
             }
           gbvector_remove_term(tmg);
           if (g == NULL)
             {
               result->next = f;
               f = head.next;
               return;
             }
           if (f == NULL)
             {
               result->next = g;
               f = head.next;
               g = NULL;
               return;
             }
         }
     }
 }
References CoefficientRingZZp::add(), gbvector::coeff, gbvector_compare(), gbvector_remove_term(), ring_elem::get_int(), GT, CoefficientRingZZp::init(), CoefficientRingZZp::is_zero(), LT, gbvector::next, and zzp.
Referenced by gbvector_add_to().