Macaulay2 Engine: GBRing::gbvector_term
gbvector_term() [2/2]
gbvector * GBRing::gbvector_term (const FreeModule * F, ring_elem coeff, int comp)
Definition at line 294 of file gbring.cpp.
 {
   gbvector *v = new_raw_term();
   v->coeff = coeff;
   v->comp = comp;
   v->next = 0;
   M->one(v->monom);
   const SchreyerOrder *S;
   if (comp > 0 && _schreyer_encoded && (S = F->get_schreyer_order()) != 0)
     S->schreyer_up(v->monom, comp - 1, v->monom);
   return v;
 }
References _schreyer_encoded, gbvector::coeff, gbvector::comp, FreeModule::get_schreyer_order(), M, gbvector::monom, new_raw_term(), gbvector::next, Monoid::one(), and SchreyerOrder::schreyer_up().
Referenced by gb2_comp::calc_gb(), gbA::new_gen(), GB_comp::new_gen(), GBinhom_comp::new_gen(), gb2_comp::receive_generator(), PolyRing::translate_gbvector_from_ringelem(), PolyRing::translate_gbvector_from_ringelem_QQ(), PolyRing::translate_gbvector_from_vec(), and PolyRing::translate_gbvector_from_vec_QQ().