Macaulay2 Engine: GBRing::reduce_lead_term_heap
reduce_lead_term_heap()
void GBRing::reduce_lead_term_heap (const FreeModule * F, const FreeModule * Fsyz, const gbvector * fcurrent_lead, const_exponents exp, gbvector * flead, gbvectorHeap & f, gbvectorHeap & fsyz, const gbvector * g, const gbvector * gsyz)
Definition at line 1668 of file gbring.cpp.
 {
   reduce_marked_lead_term_heap(
       F, Fsyz, fcurrent_lead, exp, flead, f, fsyz, g, g, gsyz);
 }
References mpfr::exp(), and reduce_marked_lead_term_heap().
Referenced by GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), and gb2_comp::gb_geo_reduce().