Macaulay2 Engine: GBRing::reduce_marked_lead_term_heap
reduce_marked_lead_term_heap()
void GBRing::reduce_marked_lead_term_heap (const FreeModule * F, const FreeModule * Fsyz, const gbvector * fcurrent_lead, const_exponents exp, gbvector * flead, gbvectorHeap & f, gbvectorHeap & fsyz, const gbvector * marked_in_g, const gbvector * g, const gbvector * gsyz)
Definition at line 1631 of file gbring.cpp.
 {
   int comp;
   ring_elem u, v;
   monomial MONOM1 = ALLOCATE_MONOMIAL(monom_size);
   find_reduction_coeffs(F, fcurrent_lead, marked_in_g, u, v);
   find_reduction_monomial(F, fcurrent_lead, marked_in_g, comp, MONOM1);
   if (!K->is_equal(u, _one))
     {
       gbvector_mult_by_coeff_to(flead, u);
       f.mult_by_coeff(u);
       fsyz.mult_by_coeff(u);
     }
   gbvector *result1 = mult_by_term(F, g, v, MONOM1, comp);
   f.add(result1);
   if (gsyz != 0)
     {
       gbvector *result_syz1 = mult_by_term(Fsyz, gsyz, v, MONOM1, comp);
       fsyz.add(result_syz1);
     }
 }
References _one, gbvectorHeap::add(), ALLOCATE_MONOMIAL, find_reduction_coeffs(), find_reduction_monomial(), gbvector_mult_by_coeff_to(), Ring::is_equal(), K, monom_size, gbvectorHeap::mult_by_coeff(), and mult_by_term().
Referenced by MarkedGB::geo_remainder(), and reduce_lead_term_heap().