Macaulay2 Engine: GBRing::gbvector_raw_term
gbvector_raw_term()
gbvector * GBRing::gbvector_raw_term (ring_elem coeff, const int * monom, int comp)
Definition at line 310 of file gbring.cpp.
 {
   gbvector *v = new_raw_term();
   v->coeff = coeff;
   v->comp = comp;
   v->next = 0;
   M->copy(monom, v->monom);
   return v;
 }
References gbvector::coeff, gbvector::comp, Monoid::copy(), M, gbvector::monom, new_raw_term(), and gbvector::next.
Referenced by gbvector_term().