Macaulay2 Engine: GBRing::gbvector_remove_term
gbvector_remove_term()
void GBRing::gbvector_remove_term (gbvector * f) protected
Definition at line 273 of file gbring.cpp.
 {
   // It is not clear whether we should try to free elements of K
   f->next = nullptr;
   f->coeff = ZERO_RINGELEM;
   mem->delete_elem(f);
   // GC_FREE(reinterpret_cast<char *>(f));
 }
References gbvector::coeff, stash::delete_elem(), mem, gbvector::next, and ZERO_RINGELEM.
Referenced by gbvector_add_to(), gbvector_add_to_zzp(), and gbvector_remove().