Macaulay2 Engine: GBRing::gbvector_lead_term
gbvector_lead_term()
gbvector * GBRing::gbvector_lead_term (int n, const FreeModule * F, const gbvector * f)
Definition at line 434 of file gbring.cpp.
 {
 #ifdef DEVELOPMENT
 #warning "Schreyer order question"
 #endif
   if (v == nullptr) return nullptr;
   if (nparts < 0)
     {
       return gbvector_copy_term(v);
     }
   else
     {
       int nslots = M->n_slots(nparts);
       gbvector head;
       gbvector *result = &head;
       for (const gbvector *t = v; t != nullptr; t = t->next)
         {
           if (M->compare(nslots, t->monom, v->monom) != 0) break;
           result->next = gbvector_copy_term(t);
           result = result->next;
         }
       result->next = nullptr;
       return head.next;
     }
 }
References Monoid::compare(), gbvector_copy_term(), M, gbvector::monom, Monoid::n_slots(), and gbvector::next.
Referenced by ReducedGB_Field_Local::find_good_divisor(), GB_comp::get_initial(), MarkedGB::get_initial(), ReducedGB::get_initial(), and gb2_comp::initial_matrix().