Macaulay2 Engine: GBRing::gbvector_get_lead_monomial
gbvector_get_lead_monomial()
void GBRing::gbvector_get_lead_monomial (const FreeModule * F, const gbvector * f, int * result)
Definition at line 520 of file gbring.cpp.
 {
   const SchreyerOrder *S;
   if (_schreyer_encoded && (S = F->get_schreyer_order()) != 0 && f->comp > 0)
     S->schreyer_down(f->monom, f->comp - 1, result);
   else
     M->copy(f->monom, result);
 }
References _schreyer_encoded, gbvector::comp, Monoid::copy(), FreeModule::get_schreyer_order(), M, gbvector::monom, and SchreyerOrder::schreyer_down().
Referenced by gb2_comp::compute_s_pair(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), GB_comp::gb_insert(), gb2_comp::gb_insert(), GBinhom_comp::gb_insert(), gbvector_multidegree(), PolyRing::translate_gbvector_to_vec(), and PolyRing::translate_gbvector_to_vec_QQ().