Macaulay2 Engine: GBRing::gbvector_n_terms
gbvector_n_terms()
int GBRing::gbvector_n_terms (const gbvector * f) const
Definition at line 386 of file gbring.cpp.
 {
   int result = 0;
   for (; v != nullptr; v = v->next) result++;
   return result;
 }
References gbvector::next.
Referenced by gbvectorHeap::add(), ReducedGB_Field_Local::find_good_divisor(), ResF4toM2Interface::from_M2_vec(), F4toM2Interface::from_M2_vec(), gbA::gbelem_make(), gbA::gbelem_ring_make(), ReducedGB_Field_Local::minimalize(), GBKernelComputation::reduce(), ReducedGB_Field_Local::ReducedGB_Field_Local(), gbA::show_mem_usage(), gb2_comp::stats(), ReducedGB_Field_Local::store_in_table(), and gb2_comp::text_out().