Macaulay2 Engine: GBRing::gbvector_remove_content_ZZ
gbvector_remove_content_ZZ()
void GBRing::gbvector_remove_content_ZZ (gbvector * f, gbvector * fsyz, bool use_denom, ring_elem & denom) const protected
Definition at line 1306 of file gbring.cpp.
 {
   // This routine assumes that the coeff ring is ZZ (originally QQ).
   gbvector *g = f;
   gbvector *gsyz = fsyz;
   mpz_t content;
   int leadsign;
   if (g != nullptr)
     {
       leadsign = mpz_sgn(g->coeff.get_mpz());
       mpz_init_set(content, g->coeff.get_mpz());
       g = g->next;
     }
   else if (gsyz != nullptr)
     {
       leadsign = mpz_sgn(gsyz->coeff.get_mpz());
       mpz_init_set(content, gsyz->coeff.get_mpz());
       gsyz = gsyz->next;
     }
   else
     return;
   lower_content_ZZ(g, content);
   lower_content_ZZ(gsyz, content);
   mpz_abs(content, content);
   if (mask_mpz_cmp_si(content, 1) == 0)
     {
       mpz_clear(content);
       if (leadsign < 0)
         {
           gbvector_negate_to(f);
           gbvector_negate_to(fsyz);
         }
       return;
     }
   if (leadsign < 0) mpz_neg(content, content);
   divide_coeff_exact_to_ZZ(f, content);
   divide_coeff_exact_to_ZZ(fsyz, content);
   if (use_denom)
     {
       denom = globalZZ->mult(denom, ring_elem(content));
     }
   mpz_clear(content);
 }
References gbvector::coeff, ring_elem::get_mpz(), globalZZ, mask_mpz_cmp_si(), RingZZ::mult(), and gbvector::next.
Referenced by gbvector_remove_content().