Macaulay2 Engine: GBRing::divide_exponents
divide_exponents()
void GBRing::divide_exponents (const int * exp1, const int * exp2, int * result) const protected
Definition at line 798 of file gbring.cpp.
 {
   for (int i = 0; i < _nvars; i++) *result++ = *exp1++ - *exp2++;
 }
References _nvars, and mpfr::exp2().
Referenced by find_reduction_coeffs(), and find_reduction_coeffs_ZZ().