Macaulay2 Engine: GBRing::memstats
memstats()
void GBRing::memstats ()
Definition at line 21 of file gbring.cpp.
 {
   buffer o;
   mem->stats(o);
   emit(o.str());
 }
References emit(), mem, stash::stats(), and buffer::str().