Macaulay2 Engine: GBRing::gbvector_auto_reduce_ZZ
gbvector_auto_reduce_ZZ()
void GBRing::gbvector_auto_reduce_ZZ (const FreeModule * F, const FreeModule * Fsyz, gbvector *& f, gbvector *& fsyz, const gbvector * g, const gbvector * gsyz)
Definition at line 1458 of file gbring.cpp.
 {
   assert(globalZZ == K);
   const gbvector *t;
   if ((t = find_coeff(F, f, g)) != 0)
     {
       ring_elem v = globalZZ->quotient(t->coeff, g->coeff);
       if (globalZZ->is_zero(v)) return;
       v = globalZZ->negate(v);
       gbvector *g1 = gbvector_mult_by_coeff(g, v);
       gbvector *gsyz1 = gbvector_mult_by_coeff(gsyz, v);
       gbvector_add_to(F, f, g1);
       gbvector_add_to(Fsyz, fsyz, gsyz1);
       if (M2_gbTrace == 10)
         {
           buffer o;
           o << "auto reducing by ";
           gbvector_text_out(o, F, g);
           o << "\n  --  giving ";
           gbvector_text_out(o, F, f);
           emit_line(o.str());
         }
     }
 }
References gbvector::coeff, emit_line(), find_coeff(), gbvector_add_to(), gbvector_mult_by_coeff(), gbvector_text_out(), globalZZ, RingZZ::is_zero(), K, M2_gbTrace, RingZZ::negate(), RingZZ::quotient(), and buffer::str().
Referenced by gbA::auto_reduce_by(), and gbA::do_computation().