Macaulay2 Engine: GBRing::gbvector_replace_2by2_ZZ
gbvector_replace_2by2_ZZ()
void GBRing::gbvector_replace_2by2_ZZ (const FreeModule * F, const FreeModule * Fsyz, gbvector *& f, gbvector *& fsyz, gbvector *& g, gbvector *& gsyz)
Definition at line 1105 of file gbring.cpp.
 {
   // ASSUMPTIONS: coefficient ring is ZZ
   //  lead monomial of f and g are the same (with possibly different coeffs)
   // If u * leadcoeff(f) + v * leadcoeff(g) = gd is the gcd,
   // then:
   //  g <-- u * f + v * g
   //  f <-- c * f - d * g, where c = leadcoeff(g)//gd, d = leadcoeff(f)//gd
   mpz_t u, v, gd;
   mpz_init(u);
   mpz_init(v);
   mpz_init(gd);
   mpz_gcdext(gd, u, v, f->coeff.get_mpz(), g->coeff.get_mpz());
   gbvector *new_g = 0;
   gbvector *g2 = 0;
   gbvector *new_gsyz = 0;
   gbvector *gsyz2 = 0;
   if (mpz_sgn(v) != 0)
     {
       g2 = gbvector_mult_by_coeff(g, ring_elem(v));
       gsyz2 = gbvector_mult_by_coeff(gsyz, ring_elem(v));
     }
   if (mpz_sgn(u) != 0)
     {
       new_g = gbvector_mult_by_coeff(f, ring_elem(u));
       new_gsyz = gbvector_mult_by_coeff(fsyz, ring_elem(u));
     }
   gbvector_add_to(F, new_g, g2);
   gbvector_add_to(Fsyz, new_gsyz, gsyz2);
   mpz_fdiv_q(u, g->coeff.get_mpz(), gd);
   mpz_fdiv_q(v, f->coeff.get_mpz(), gd);
   mpz_neg(v, v);
   gbvector *new_f = gbvector_mult_by_coeff(f, ring_elem(u));
   gbvector *new_fsyz = gbvector_mult_by_coeff(fsyz, ring_elem(u));
   gbvector *f2 = gbvector_mult_by_coeff(g, ring_elem(v));
   gbvector *fsyz2 = gbvector_mult_by_coeff(gsyz, ring_elem(v));
   gbvector_add_to(F, new_f, f2);
   gbvector_add_to(Fsyz, new_fsyz, fsyz2);
   f = new_f;
   fsyz = new_fsyz;
   g = new_g;
   gsyz = new_gsyz;
   mpz_clear(u);
   mpz_clear(v);
   mpz_clear(gd);
 }
References gbvector::coeff, gbvector_add_to(), gbvector_mult_by_coeff(), and ring_elem::get_mpz().
Referenced by gbA::reduce_ZZ().