Macaulay2 Engine: GBRing::gbvector_is_zero
gbvector_is_zero()
bool GBRing::gbvector_is_zero (const gbvector * f) const inline
Definition at line 238 of file gbring.hpp.
 { return f == nullptr; }
Referenced by GB_comp::gen_step(), MarkedGB::marked_remainder(), gbA::new_gen(), GB_comp::new_gen(), GBinhom_comp::new_gen(), gbA::process_spair(), gbA::reduce_kk(), gbA::reduce_ZZ(), MarkedGB::remainder(), ReducedGB_Field_Local::remainder(), ReducedGB_Field::remainder(), ReducedGB_ZZ::remainder(), gbA::remainder_non_ZZ(), gbA::remainder_ZZ(), GB_comp::s_pair_step(), GBinhom_comp::s_pair_step(), and gbA::tail_remainder_ZZ().