Macaulay2 Engine: GBRing::get_flattened_coefficients
get_flattened_coefficients()
const Ring* GBRing::get_flattened_coefficients () const inline
Definition at line 171 of file gbring.hpp.
 { return K; }
References K.
Referenced by GBDeclared::GBDeclared(), GBKernelComputation::geo_reduce(), GB_comp::initialize0(), ReducedGB::matrix_lift(), GBKernelComputation::new_pairs(), gbres_comp::reduce(), GBKernelComputation::reduce(), GBinhom_comp::set_up0(), and gb2_comp::setup().