Macaulay2 Engine: GBRing::gbvector_reduce_lead_term_ZZ
gbvector_reduce_lead_term_ZZ()
bool GBRing::gbvector_reduce_lead_term_ZZ (const FreeModule * F, const FreeModule * Fsyz, gbvector *& f, gbvector *& fsyz, const gbvector * g, const gbvector * gsyz)
Definition at line 1018 of file gbring.cpp.
 {
   int comp;
   ring_elem v;
   monomial MONOM1 = ALLOCATE_MONOMIAL(monom_size);
   bool result = find_reduction_coeffs_ZZ(F, f, g, v);
   if (K->is_zero(v)) return false;
   find_reduction_monomial(F, f, g, comp, MONOM1);
   gbvector *result1 = mult_by_term(F, g, v, MONOM1, comp);
   gbvector_add_to(F, f, result1);
   if (gsyz != 0)
     {
       gbvector *result_syz1 = mult_by_term(Fsyz, gsyz, v, MONOM1, comp);
       gbvector_add_to(Fsyz, fsyz, result_syz1);
     }
   return result;
 }
References ALLOCATE_MONOMIAL, find_reduction_coeffs_ZZ(), find_reduction_monomial(), gbvector_add_to(), Ring::is_zero(), K, monom_size, and mult_by_term().
Referenced by QRingInfo_ZZ::gbvector_normal_form(), gbA::reduce_ZZ(), ReducedGB_ZZ::remainder(), gbA::remainder_ZZ(), and gbA::tail_remainder_ZZ().