Macaulay2 Engine: GBRing::mult_by_term
mult_by_term()
gbvector * GBRing::mult_by_term (const FreeModule * F, const gbvector * f, ring_elem u, const int * monom, int comp) protected
Definition at line 830 of file gbring.cpp.
 {
   gbvector *result = mult_by_term1(F, f, u, monom, comp);
   const SchreyerOrder *S;
   if (comp > 0 && _schreyer_encoded && (S = F->get_schreyer_order()) != nullptr)
     {
       for (gbvector *t = result; t != nullptr; t = t->next)
         S->schreyer_up(t->monom, comp - 1, t->monom);
     }
   return result;
 }
References _schreyer_encoded, FreeModule::get_schreyer_order(), mult_by_term1(), gbvector::next, and SchreyerOrder::schreyer_up().
Referenced by gbvector_apply(), gbvector_cancel_lead_terms(), gbvector_combine_lead_terms_ZZ(), gbvector_mult_by_term(), gbvector_reduce_lead_term(), gbvector_reduce_lead_term_ZZ(), gbvector_reduce_with_marked_lead_term(), GBKernelComputation::geo_reduce(), GBKernelComputation::reduce(), reduce_marked_lead_term_heap(), and GBKernelComputation::s_pair().