Macaulay2 Engine: GBRing::n_vars
n_vars()
int GBRing::n_vars () const inline
Definition at line 172 of file gbring.hpp.
 { return _nvars; }
References _nvars.
Referenced by GBWeight::GBWeight(), gbA::initialize(), MarkedGB::MarkedGB(), ReducedGB_Field::ReducedGB_Field(), ReducedGB_ZZ::ReducedGB_ZZ(), ReducedGB_Field_Local::remainder(), and GBKernelComputation::wipe_unneeded_terms().