Macaulay2 Engine: GBRing::get_flattened_monoid
get_flattened_monoid()
const Monoid* GBRing::get_flattened_monoid () const inline
Definition at line 170 of file gbring.hpp.
 { return M; }
References M.
Referenced by GBWeight::GBWeight(), gbA::initialize(), GB_comp::initialize0(), gbA::insert_gb(), GBWeight::monomial_weight(), ReducedGB_Field_Local_sorter::ReducedGB_Field_Local_sorter(), GBinhom_comp::set_up0(), and gb2_comp::setup().