Macaulay2 Engine: GBRing::is_skew_commutative
is_skew_commutative()
bool GBRing::is_skew_commutative () const inline
Definition at line 180 of file gbring.hpp.
 { return _skew.n_skew_vars() > 0; }
References _skew, and SkewMultiplication::n_skew_vars().
Referenced by GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), find_reduction_coeffs(), find_reduction_coeffs_ZZ(), gbvector_cancel_lead_terms(), gbvector_combine_lead_terms_ZZ(), and gbA::update_pairs().