Macaulay2 Engine: GBRing::gbvector_reduce_lead_term
gbvector_reduce_lead_term() [2/2]
void GBRing::gbvector_reduce_lead_term (const FreeModule * F, const FreeModule * Fsyz, gbvector * flead, gbvector *& f, gbvector *& fsyz, const gbvector * g, const gbvector * gsyz, bool use_denom, ring_elem & denom)
Definition at line 935 of file gbring.cpp.
 {
   int comp;
   ring_elem u, v;
   monomial MONOM1 = ALLOCATE_MONOMIAL(monom_size);
   find_reduction_coeffs(F, f, g, u, v);
   find_reduction_monomial(F, f, g, comp, MONOM1);
   if (!K->is_equal(u, _one))
     {
       gbvector_mult_by_coeff_to(f, u);  // modifies f
       gbvector_mult_by_coeff_to(flead, u);
       gbvector_mult_by_coeff_to(fsyz, u);
       if (use_denom) K->mult_to(denom, u);
     }
   gbvector *result1 = mult_by_term(F, g, v, MONOM1, comp);
   gbvector_add_to(F, f, result1);
   if (gsyz != 0)
     {
       gbvector *result_syz1 = mult_by_term(Fsyz, gsyz, v, MONOM1, comp);
       gbvector_add_to(Fsyz, fsyz, result_syz1);
     }
 }
References _one, ALLOCATE_MONOMIAL, find_reduction_coeffs(), find_reduction_monomial(), gbvector_add_to(), gbvector_mult_by_coeff_to(), Ring::is_equal(), K, monom_size, mult_by_term(), and Ring::mult_to().
Referenced by GB_comp::compute_s_pair(), GBinhom_comp::compute_s_pair(), gb2_comp::compute_s_pair(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), QRingInfo_field_basic::gbvector_normal_form(), QRingInfo_field_QQ::gbvector_normal_form(), gbvector_reduce_lead_term(), gbA::reduce_kk(), ReducedGB_Field_Local::remainder(), ReducedGB_Field::remainder(), and gbA::remainder_non_ZZ().