Macaulay2 Engine: GBRing::find_reduction_monomial
find_reduction_monomial()
void GBRing::find_reduction_monomial (const FreeModule * F, const gbvector * f, const gbvector * g, int & comp, int *& monom)
Definition at line 913 of file gbring.cpp.
 {
   M->divide(f->monom, g->monom, monom);
   if (g->comp == 0)
     {
       comp = f->comp;
       const SchreyerOrder *S;
       if (_schreyer_encoded && (S = F->get_schreyer_order()) != 0)
         S->schreyer_down(monom, comp - 1, monom);
     }
   else
     {
       comp = 0;
     }
 }
References _schreyer_encoded, gbvector::comp, Monoid::divide(), FreeModule::get_schreyer_order(), M, gbvector::monom, and SchreyerOrder::schreyer_down().
Referenced by gbvector_reduce_lead_term(), gbvector_reduce_lead_term_ZZ(), gbvector_reduce_with_marked_lead_term(), and reduce_marked_lead_term_heap().