Macaulay2 Engine: GBRing::exponent_syzygy
exponent_syzygy()
void GBRing::exponent_syzygy (const int * exp1, const int * exp2, int * exp3, int * exp4) protected
Definition at line 805 of file gbring.cpp.
 {
   for (int i = 0; i < _nvars; i++)
     {
       int a = exp1[i] - exp2[i];
       if (a > 0)
         {
           exp3[i] = 0;
           exp4[i] = a;
         }
       else
         {
           exp3[i] = -a;
           exp4[i] = 0;
         }
     }
 }
References _nvars, and mpfr::exp2().
Referenced by gbvector_cancel_lead_terms(), and gbvector_combine_lead_terms_ZZ().