Macaulay2 Engine: GBRing::skew_variable
skew_variable()
int GBRing::skew_variable (int i) const inline
Definition at line 182 of file gbring.hpp.
 { return _skew.skew_variable(i); }
References _skew, and SkewMultiplication::skew_variable().
Referenced by GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), gbA::spair_make_skew(), and gbA::update_pairs().