Macaulay2 Engine: GBRing::gbvector_parallel_lead_terms
gbvector_parallel_lead_terms()
gbvector * GBRing::gbvector_parallel_lead_terms (M2_arrayint w, const FreeModule * F, const gbvector * leadv, const gbvector * v)
Definition at line 488 of file gbring.cpp.
 {
   if (v == nullptr) return nullptr;
   // loop through every term of v.  Keep those t that satisfy: exp(leadv) -
   // exp(t)
   // is a multiple of w
   //
   exponents_t lead = ALLOCATE_EXPONENTS(exp_size);
   exponents_t e = ALLOCATE_EXPONENTS(exp_size);
   M->to_expvector(leadv->monom, lead);
   gbvector head;
   gbvector *result = &head;
   for (const gbvector *t = v; t != nullptr; t = t->next)
     {
       M->to_expvector(t->monom, e);
       if (leadv == t || isparallel(w, lead, e))
         {
           result->next = gbvector_copy_term(t);
           result = result->next;
         }
     }
   result->next = nullptr;
   return head.next;
 }
References ALLOCATE_EXPONENTS, exp_size, gbvector_copy_term(), isparallel(), M, gbvector::monom, gbvector::next, and Monoid::to_expvector().
Referenced by GB_comp::get_parallel_lead_terms(), MarkedGB::get_parallel_lead_terms(), and ReducedGB::get_parallel_lead_terms().