Macaulay2 Engine: GBRing::exponents_make
exponents_make()
exponents_t GBRing::exponents_make ()
Definition at line 38 of file gbring.cpp.
 {
   int *e = newarray_atomic(int, _nvars + 2);  // length is nvars
   return e;
 }
References _nvars, and newarray_atomic.
Referenced by MarkedGB::add_marked_elems(), ReducedGB_ZZ::find_divisor(), ReducedGB_Field_Local::minimalize(), ReducedGB_Field::minimalize(), and ReducedGB_Field_Local::remainder().