Macaulay2 Engine: GBRing::gbvector_text_out
gbvector_text_out()
void GBRing::gbvector_text_out (buffer & o, const FreeModule * F, const gbvector * f, int nterms = -1) const
Definition at line 771 of file gbring.cpp.
 {
   if (v == NULL)
     {
       o << "0";
       return;
     }
   bool p_one = false;
   bool p_plus = false;
   bool p_parens = false;
   int count = nterms;
   const gbvector *t;
   for (t = v; t != NULL && count != 0; t = t->next, count--)
     {
       int isone = (M == NULL || M->is_one(t->monom));
       K->elem_text_out(o, t->coeff, p_one, p_plus, p_parens);
       if (!isone) M->elem_text_out(o, t->monom, p_one);
       if (t->comp >= 1) o << "<" << t->comp << ">";
       p_plus = true;
     }
   if (t != NULL) o << "+...";
 }
References gbvector::coeff, gbvector::comp, Ring::elem_text_out(), Monoid::elem_text_out(), Monoid::is_one(), K, M, gbvector::monom, and gbvector::next.
Referenced by gbA::collect_syzygy(), gbA::compute_s_pair(), dgbvec(), displayElements(), ReducedGB_Field_Local::find_good_divisor(), ResF4toM2Interface::from_M2_vec(), gb2_comp::gb_insert(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), gbA::gbelem_text_out(), gbvector_auto_reduce(), gbvector_auto_reduce_ZZ(), gbA::insert_gb(), gbA::reduce_kk(), gbA::reduce_ZZ(), ReducedGB_ZZ::remainder(), ReducedGB_Field_Local::remainder(), gbA::remainder_non_ZZ(), gbA::remainder_ZZ(), gbA::replace_gb_element_ZZ(), GB_comp::s_pair_step(), GBinhom_comp::s_pair_step(), Interreducer::showElem(), gbA::spair_text_out(), GBinhom_comp::stats(), gb2_comp::stats(), gbA::tail_remainder_ZZ(), gbA::text_out(), ReducedGB::text_out(), and gb2_comp::text_out().