Macaulay2 Engine: GBRing::find_reduction_coeffs
find_reduction_coeffs()
void GBRing::find_reduction_coeffs (const FreeModule * F, const gbvector * f, const gbvector * g, ring_elem & u, ring_elem & v)
Definition at line 863 of file gbring.cpp.
 {
   const ring_elem a = f->coeff;
   const ring_elem b = g->coeff;
   K->syzygy(a, b, u, v);  // If possible, u==1, anyway, u>0
   if (is_skew_commutative())
     {
       exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
       exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
       exponents_t EXP3 = ALLOCATE_EXPONENTS(exp_size);
       gbvector_get_lead_exponents(F, f, EXP1);  // Removes the Schreyer part
       gbvector_get_lead_exponents(F, g, EXP2);  // Removes the Schreyer part
       divide_exponents(EXP1, EXP2, EXP3);
       if (_skew.mult_sign(EXP3, EXP2) < 0) K->negate_to(v);
     }
 }
References _skew, ALLOCATE_EXPONENTS, gbvector::coeff, divide_exponents(), exp_size, gbvector_get_lead_exponents(), is_skew_commutative(), K, SkewMultiplication::mult_sign(), Ring::negate_to(), and Ring::syzygy().
Referenced by gbvector_reduce_lead_term(), gbvector_reduce_with_marked_lead_term(), and reduce_marked_lead_term_heap().