Macaulay2 Engine: GBRing::gbvector_combine_lead_terms_ZZ
gbvector_combine_lead_terms_ZZ()
void GBRing::gbvector_combine_lead_terms_ZZ (const FreeModule * F, const FreeModule * Fsyz, const gbvector * f, const gbvector * fsyz, const gbvector * g, const gbvector * gsyz, gbvector *& result, gbvector *& result_syz)
Definition at line 1165 of file gbring.cpp.
 {
   int comp;
   const ring_elem a = f->coeff;
   const ring_elem b = g->coeff;
   mpz_t gab, u1, v1;
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
   exponents_t EXP3 = ALLOCATE_EXPONENTS(exp_size);
   exponents_t EXP4 = ALLOCATE_EXPONENTS(exp_size);
   monomial MONOM1 = ALLOCATE_MONOMIAL(monom_size);
   monomial MONOM2 = ALLOCATE_MONOMIAL(monom_size);
   mpz_init(gab);
   mpz_init(u1);
   mpz_init(v1);
   mpz_gcdext(gab, u1, v1, a.get_mpz(), b.get_mpz());
   mpz_clear(gab);
   //these ring_elem must not escape the function, because they aren't allocated on
   //the gc heap
   ring_elem u = ring_elem(u1);
   ring_elem v = ring_elem(v1);
   if (globalZZ->is_zero(u) || globalZZ->is_zero(v))
     {
       result = nullptr;
       result_syz = nullptr;
       mpz_clear(u1);
       mpz_clear(v1);
       return;
     }
   gbvector_get_lead_exponents(F, f, EXP1);  // Removes the Schreyer part
   gbvector_get_lead_exponents(F, g, EXP2);  // Removes the Schreyer part
   exponent_syzygy(EXP1, EXP2, EXP3, EXP4);
   if (g->comp == 0)
     comp = f->comp;
   else
     comp = 0;
   if (is_skew_commutative())
     {
       // Note that EXP3 * EXP1 = EXP4 * EXP2 up to sign
       if (_skew.mult_sign(EXP3, EXP1) != _skew.mult_sign(EXP4, EXP2))
         K->negate_to(v);
     }
   M->from_expvector(EXP3, MONOM1);
   M->from_expvector(EXP4, MONOM2);
   result = mult_by_term(F, f, u, MONOM1, 0);
   gbvector *result1 = mult_by_term(F, g, v, MONOM2, comp);
   gbvector_add_to(F, result, result1);
   if (fsyz == nullptr && gsyz == nullptr)
     result_syz = nullptr;
   else
     {
       result_syz = mult_by_term(Fsyz, fsyz, u, MONOM1, 0);
       gbvector *result_syz1 = mult_by_term(Fsyz, gsyz, v, MONOM2, comp);
       gbvector_add_to(Fsyz, result_syz, result_syz1);
     }
   mpz_clear(u1);
   mpz_clear(v1);
 }
References _skew, ALLOCATE_EXPONENTS, ALLOCATE_MONOMIAL, gbvector::coeff, gbvector::comp, exp_size, exponent_syzygy(), Monoid::from_expvector(), gbvector_add_to(), gbvector_get_lead_exponents(), ring_elem::get_mpz(), globalZZ, is_skew_commutative(), RingZZ::is_zero(), K, M, monom_size, mult_by_term(), SkewMultiplication::mult_sign(), and Ring::negate_to().
Referenced by gbA::compute_s_pair(), and gbA::spair_set_lead_spoly().