Macaulay2 Engine: GBRing::gbvector_multidegree
gbvector_multidegree()
void GBRing::gbvector_multidegree (const FreeModule * F, const gbvector * f, int *& result_degree)
Definition at line 393 of file gbring.cpp.
 {
   /* Return the multi degree of the first term of f */
   monomial MONOM1 = ALLOCATE_MONOMIAL(monom_size);
   gbvector_get_lead_monomial(F, f, MONOM1);
   result_degree = M->degree_monoid()->make_one();
   M->multi_degree(MONOM1, result_degree);
   M->degree_monoid()->mult(
       result_degree, F->degree(f->comp - 1), result_degree);
 }
References ALLOCATE_MONOMIAL, gbvector::comp, FreeModule::degree(), Monoid::degree_monoid(), gbvector_get_lead_monomial(), M, Monoid::make_one(), monom_size, Monoid::mult(), and Monoid::multi_degree().
Referenced by gb2_comp::schreyer_append().