Macaulay2 Engine: GBRing::gbvector_mult_by_coeff
gbvector_mult_by_coeff()
gbvector * GBRing::gbvector_mult_by_coeff (const gbvector * f, ring_elem u)
Definition at line 559 of file gbring.cpp.
 {
   gbvector head;
   gbvector *result = &head;
   for (const gbvector *t = v; t != nullptr; t = t->next)
     {
       result->next = gbvector_copy_term(t);
       result = result->next;
       K->mult_to(result->coeff, u);
     }
   result->next = nullptr;
   return head.next;
 }
References gbvector::coeff, gbvector_copy_term(), K, Ring::mult_to(), and gbvector::next.
Referenced by gbvector_auto_reduce(), gbvector_auto_reduce_ZZ(), gbvector_replace_2by2_ZZ(), and PolyRing::translate_gbvector_to_vec_denom().