Macaulay2 Engine: GBRing::gbvector_reduce_with_marked_lead_term
gbvector_reduce_with_marked_lead_term()
void GBRing::gbvector_reduce_with_marked_lead_term (const FreeModule * F, const FreeModule * Fsyz, gbvector * flead, gbvector *& f, gbvector *& fsyz, const gbvector * ginitial, const gbvector * g, const gbvector * gsyz, bool use_denom, ring_elem & denom)
Definition at line 970 of file gbring.cpp.
 {
   int comp;
   ring_elem u, v;
   monomial MONOM1 = ALLOCATE_MONOMIAL(monom_size);
   find_reduction_coeffs(F, f, ginitial, u, v);
   find_reduction_monomial(F, f, ginitial, comp, MONOM1);
   if (!K->is_equal(u, _one))
     {
       gbvector_mult_by_coeff_to(f, u);  // modifies f
       gbvector_mult_by_coeff_to(flead, u);
       gbvector_mult_by_coeff_to(fsyz, u);
       if (use_denom) K->mult_to(denom, u);
     }
   gbvector *result1 = mult_by_term(F, g, v, MONOM1, comp);
   gbvector_add_to(F, f, result1);
   if (gsyz != nullptr)
     {
       gbvector *result_syz1 = mult_by_term(Fsyz, gsyz, v, MONOM1, comp);
       gbvector_add_to(Fsyz, fsyz, result_syz1);
     }
 }
References _one, ALLOCATE_MONOMIAL, find_reduction_coeffs(), find_reduction_monomial(), gbvector_add_to(), gbvector_mult_by_coeff_to(), Ring::is_equal(), K, monom_size, mult_by_term(), and Ring::mult_to().
Referenced by MarkedGB::marked_remainder(), and MarkedGB::remainder().