Macaulay2 Engine: GBRing::gbvector_remove
gbvector_remove()
void GBRing::gbvector_remove (gbvector * f)
Definition at line 282 of file gbring.cpp.
 {
   // It is not clear whether we should try to free elements of K
   gbvector *f = f0;
   while (f != 0)
     {
       gbvector *g = f;
       f = f->next;
       gbvector_remove_term(g);
     }
 }
References gbvector_remove_term(), and gbvector::next.
Referenced by gbA::compute_s_pair(), GB_comp::contains(), ReducedGB::contains(), QRingInfo::destroy(), ReducedGB_Field_Local::find_good_divisor(), ResF4toM2Interface::from_M2_vec(), GB_comp::gen_step(), ReducedGB::get_initial(), gbvectorHeap::get_lead_term(), ReducedGB::get_parallel_lead_terms(), gb2_comp::initial_matrix(), ReducedGB::matrix_lift(), ReducedGB::matrix_remainder(), gb2_comp::receive_generator(), gbA::remove_gb(), GB_comp::remove_pair(), GBinhom_comp::remove_pair(), GB_comp::s_pair_step(), gb2_comp::s_pair_step(), GBinhom_comp::s_pair_step(), gbA::spair_delete(), gbA::spair_set_lead_spoly(), PolyRing::translate_gbvector_to_vec_denom(), GBKernelComputation::wipe_unneeded_terms(), gb2_comp::~gb2_comp(), and ReducedGB::~ReducedGB().