Macaulay2 Engine: GBRing::gbvector_get_lead_exponents
gbvector_get_lead_exponents()
void GBRing::gbvector_get_lead_exponents (const FreeModule * F, const gbvector * f, int * result)
Definition at line 533 of file gbring.cpp.
 {
   const SchreyerOrder *S;
   if (_schreyer_encoded && (S = F->get_schreyer_order()) != nullptr && f->comp > 0)
     {
       monomial MONOM1 = ALLOCATE_MONOMIAL(monom_size);
       S->schreyer_down(f->monom, f->comp - 1, MONOM1);
       M->to_expvector(MONOM1, result);
     }
   else
     M->to_expvector(f->monom, result);
 }
References _schreyer_encoded, ALLOCATE_MONOMIAL, gbvector::comp, FreeModule::get_schreyer_order(), M, gbvector::monom, monom_size, SchreyerOrder::schreyer_down(), and Monoid::to_expvector().
Referenced by MarkedGB::add_marked_elems(), ReducedGB_ZZ::find_divisor(), find_reduction_coeffs(), find_reduction_coeffs_ZZ(), GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), gbA::gbelem_make(), gbA::gbelem_ring_make(), gbvector_cancel_lead_terms(), gbvector_combine_lead_terms_ZZ(), QRingInfo_field_basic::gbvector_normal_form(), QRingInfo_field_QQ::gbvector_normal_form(), QRingInfo_ZZ::gbvector_normal_form(), GBWeight::gbvector_term_weight(), MarkedGB::geo_remainder(), MarkedGB::marked_remainder(), ReducedGB_Field_Local::minimalize(), ReducedGB_Field::minimalize(), GBRingSkew::mult_by_term1(), gbA::reduce_kk(), gbA::reduce_ZZ(), MarkedGB::remainder(), ReducedGB_Field_Local::remainder(), ReducedGB_Field::remainder(), ReducedGB_ZZ::remainder(), gbA::remainder_non_ZZ(), gbA::remainder_ZZ(), gbA::spair_make_gen(), gbA::tail_remainder_ZZ(), and GBKernelComputation::wipe_unneeded_terms().