Macaulay2 Engine: GBRing::gbvector_term
gbvector_term() [1/2]
gbvector * GBRing::gbvector_term (const FreeModule * F, ring_elem coeff, const int * monom, int comp)
Definition at line 323 of file gbring.cpp.
 {
   gbvector *v = gbvector_raw_term(coeff, monom, comp);
   const SchreyerOrder *S;
   if (comp > 0 && _schreyer_encoded && (S = F->get_schreyer_order()) != nullptr)
     S->schreyer_up(v->monom, comp - 1, v->monom);
   return v;
 }
References _schreyer_encoded, gbvector_raw_term(), FreeModule::get_schreyer_order(), gbvector::monom, and SchreyerOrder::schreyer_up().