Macaulay2 Engine: GBRing::gbvector_add_to
gbvector_add_to()
void GBRing::gbvector_add_to (const FreeModule * F, gbvector *& f, gbvector *& g)
Definition at line 660 of file gbring.cpp.
 {
   if (g == NULL) return;
   if (f == NULL)
     {
       f = g;
       g = NULL;
       return;
     }
   if (zzp)
     {
       gbvector_add_to_zzp(F, f, g);
       return;
     }
   gbvector head;
   gbvector *result = &head;
   while (1) switch (gbvector_compare(F, f, g))
       {
         case LT:
           result->next = g;
           result = result->next;
           g = g->next;
           if (g == NULL)
             {
               result->next = f;
               f = head.next;
               return;
             }
           break;
         case GT:
           result->next = f;
           result = result->next;
           f = f->next;
           if (f == NULL)
             {
               result->next = g;
               f = head.next;
               g = NULL;
               return;
             }
           break;
         case EQ:
           gbvector *tmf = f;
           gbvector *tmg = g;
           f = f->next;
           g = g->next;
           K->add_to(tmf->coeff, tmg->coeff);
 #if 0
 //      if (R->is_ZZ_quotient)
 //        {
 //          ring_elem t = K->remainder(tmf->coeff, R->ZZ_quotient_value);
 //          K->remove(tmf->coeff);
 //          tmf->coeff = t;
 //        }
 #endif
           if (K->is_zero(tmf->coeff))
             {
               gbvector_remove_term(tmf);
             }
           else
             {
               result->next = tmf;
               result = result->next;
             }
           gbvector_remove_term(tmg);
           if (g == NULL)
             {
               result->next = f;
               f = head.next;
               return;
             }
           if (f == NULL)
             {
               result->next = g;
               f = head.next;
               g = NULL;
               return;
             }
           break;
       }
 }
References Ring::add_to(), gbvector::coeff, EQ, gbvector_add_to_zzp(), gbvector_compare(), gbvector_remove_term(), GT, Ring::is_zero(), K, LT, gbvector::next, and zzp.
Referenced by gbvectorHeap::add(), gbvectorHeap::current_value(), gbvector_apply(), gbvector_auto_reduce(), gbvector_auto_reduce_ZZ(), gbvector_cancel_lead_terms(), gbvector_combine_lead_terms_ZZ(), gbvector_reduce_lead_term(), gbvector_reduce_lead_term_ZZ(), gbvector_reduce_with_marked_lead_term(), gbvector_replace_2by2_ZZ(), gbvector_sort(), GBKernelComputation::reduce(), GBKernelComputation::s_pair(), and gbvectorHeap::value().