Macaulay2 Engine: GBRing::find_reduction_coeffs_ZZ
find_reduction_coeffs_ZZ()
bool GBRing::find_reduction_coeffs_ZZ (const FreeModule * F, const gbvector * f, const gbvector * g, ring_elem & v)
Definition at line 885 of file gbring.cpp.
 {
   const ring_elem a = f->coeff;
   const ring_elem b = g->coeff;
   ring_elem rem;
   assert(globalZZ == K);
   rem = globalZZ->remainderAndQuotient(a, b, v);
   if (globalZZ->is_zero(v)) return false;
   v = globalZZ->negate(v);
   if (is_skew_commutative())
     {
       exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
       exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
       exponents_t EXP3 = ALLOCATE_EXPONENTS(exp_size);
       gbvector_get_lead_exponents(F, f, EXP1);  // Removes the Schreyer part
       gbvector_get_lead_exponents(F, g, EXP2);  // Removes the Schreyer part
       divide_exponents(EXP1, EXP2, EXP3);
       if (_skew.mult_sign(EXP3, EXP2) < 0) K->negate_to(v);
     }
   return globalZZ->is_zero(rem);
 }
References _skew, ALLOCATE_EXPONENTS, gbvector::coeff, divide_exponents(), exp_size, gbvector_get_lead_exponents(), globalZZ, is_skew_commutative(), RingZZ::is_zero(), K, SkewMultiplication::mult_sign(), RingZZ::negate(), Ring::negate_to(), mpfr::rem(), and RingZZ::remainderAndQuotient().
Referenced by gbvector_reduce_lead_term_ZZ().