Macaulay2 Engine: GBRing::gbvector_remove_content
gbvector_remove_content() [2/2]
void GBRing::gbvector_remove_content (gbvector * f, gbvector * fsyz, bool use_denom, ring_elem & denom)
Definition at line 1360 of file gbring.cpp.
 {
   if (_coeffs_ZZ)
     {
       gbvector_remove_content_ZZ(f, fsyz, use_denom, denom);
       return;
     }
   // At this point, our coefficient ring is a field (What about
   // finite extensions of ZZ?)
   ring_elem c, cinv;
   if (f != nullptr)
     c = f->coeff;
   else if (fsyz != nullptr)
     c = fsyz->coeff;
   else
     return;
   cinv = K->invert(c);
   gbvector_mult_by_coeff_to(f, cinv);
   gbvector_mult_by_coeff_to(fsyz, cinv);
   if (use_denom) K->mult_to(denom, c);
 }
References _coeffs_ZZ, gbvector::coeff, gbvector_mult_by_coeff_to(), gbvector_remove_content_ZZ(), Ring::invert(), K, and Ring::mult_to().
Referenced by MarkedGB::add_marked_elems(), GB_comp::gb_insert(), gb2_comp::gb_insert(), GBinhom_comp::gb_insert(), gbvector_auto_reduce(), gbvector_remove_content(), gbA::insert_gb(), ReducedGB_Field_Local::minimalize(), ReducedGB_Field::minimalize(), gb2_comp::receive_generator(), gbA::remainder_non_ZZ(), and gbA::replace_gb_element_ZZ().