Macaulay2 Engine: GBRing::gbvector_copy_term
gbvector_copy_term()
gbvector * GBRing::gbvector_copy_term (const gbvector * t) protected
Definition at line 360 of file gbring.cpp.
 {
   gbvector *v = new_raw_term();
   v->next = 0;
   v->coeff = t->coeff;
   v->comp = t->comp;
   M->copy(t->monom, v->monom);
   return v;
 }
References gbvector::coeff, gbvector::comp, Monoid::copy(), M, gbvector::monom, new_raw_term(), and gbvector::next.
Referenced by gbvector_copy(), gbvector_lead_term(), gbvector_mult_by_coeff(), gbvector_parallel_lead_terms(), and GBKernelComputation::strip_gb().