Macaulay2 Engine: GBRing::gbvector_sort
gbvector_sort()
void GBRing::gbvector_sort (const FreeModule * F, gbvector *& f)
Definition at line 742 of file gbring.cpp.
{
  // Divide f into two lists of equal length, sort each,
  // then add them together.  This allows the same monomial
  // to appear more than once in 'f'.
  if (f == nullptr || f->next == nullptr) return;
  gbvector *f1 = nullptr;
  gbvector *f2 = nullptr;
  while (f != nullptr)
    {
      gbvector *t = f;
      f = f->next;
      t->next = f1;
      f1 = t;
      if (f == nullptr) break;
      t = f;
      f = f->next;
      t->next = f2;
      f2 = t;
    }
  gbvector_sort(F, f1);
  gbvector_sort(F, f2);
  gbvector_add_to(F, f1, f2);
  f = f1;
}
References gbvector_add_to(), gbvector_sort(), and gbvector::next.
Referenced by gbvector_sort(), MarkedGB::geo_remainder(), MarkedGB::marked_remainder(), and MarkedGB::remainder().