Macaulay2 Engine: GBRing::one
one()
const ring_elem GBRing::one () inline
Definition at line 207 of file gbring.hpp.
{ return _one; }  // the element '1' in the base K.
References _one.
Referenced by GB_comp::compute_s_pair(), GBinhom_comp::compute_s_pair(), gb2_comp::compute_s_pair(), gbA::compute_s_pair(), gb2_comp::end_degree(), gb2_comp::receive_generator(), gb2_comp::s_pair_step(), and gbA::spair_set_lead_spoly().