Macaulay2 Engine: GBRing::gbvector_term_exponents
gbvector_term_exponents()
gbvector * GBRing::gbvector_term_exponents (const FreeModule * F, ring_elem coeff, const int * exp, int comp)
Definition at line 339 of file gbring.cpp.
 {
   gbvector *v = new_raw_term();
   v->coeff = coeff;
   v->comp = comp;
   v->next = nullptr;
   M->from_expvector(exp, v->monom);
   const SchreyerOrder *S;
   if (comp > 0 && _schreyer_encoded && (S = F->get_schreyer_order()) != nullptr)
     S->schreyer_up(v->monom, comp - 1, v->monom);
   return v;
 }
References _schreyer_encoded, gbvector::coeff, gbvector::comp, mpfr::exp(), Monoid::from_expvector(), FreeModule::get_schreyer_order(), M, gbvector::monom, new_raw_term(), gbvector::next, and SchreyerOrder::schreyer_up().