Macaulay2 Engine: rawARingTower2
rawARingTower2()
const Ring* rawARingTower2 (const Ring * R1, M2_ArrayString new_names)
Definition at line 321 of file aring.cpp.
 {
   try
     {
       const M2::ConcreteRing<M2::ARingTower> *K =
           dynamic_cast<const M2::ConcreteRing<M2::ARingTower> *>(R1);
       if (K == nullptr)
         {
           ERROR("expected a tower ring");
           return nullptr;
         }
       const M2::ARingTower &A = K->ring();
       auto new_varnames = M2_ArrayString_to_stdvector(new_names);
       M2::ARingTower *T = M2::ARingTower::create(A, new_varnames);
       return M2::ConcreteRing<M2::ARingTower>::create(
           std::unique_ptr<M2::ARingTower>(T));
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References M2::ARingTower::create(), M2::ConcreteRing< RingType >::create(), ERROR(), M2_ArrayString_to_stdvector(), M2::ConcreteRing< RingType >::ring(), and T.