Macaulay2 Engine: rawTowerRing2
rawTowerRing2()
const Ring* rawTowerRing2 (const Ring * R1, M2_ArrayString new_names)
Definition at line 509 of file ring.cpp.
 {
   try
     {
       const Tower *R = R1->cast_to_Tower();
       if (R == nullptr)
         {
           ERROR("expected a tower coefficient ring");
           return nullptr;
         }
       return Tower::create(R, new_names);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Ring::cast_to_Tower(), Tower::create(), and ERROR().