Macaulay2 Engine: IM2_Ring_quotient
IM2_Ring_quotient()
const Ring* IM2_Ring_quotient (const Ring * R, const Matrix * I)
Definition at line 379 of file ring.cpp.
 {
   try
     {
       if (I->get_ring() != R)
         {
           ERROR("expected matrix to be over the same ring");
         }
       if (I->n_rows() != 1)
         {
           ERROR("expected a one row matrix of quotient elements");
           return 0;
         }
       const PolynomialRing *P = R->cast_to_PolynomialRing();
       if (P != nullptr)
         {
           PolynomialRing *result = PolynomialRing::create_quotient(P, I);
           intern_polyring(result);
           return result;
         }
       const M2FreeAlgebra *A = R->cast_to_M2FreeAlgebra();
       if (A != nullptr)
         {
           auto result = M2FreeAlgebraQuotient::create(*A, I, -1);
           return result;
         }
       ERROR("expected a polynomial ring or free algebra");
       return nullptr;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References Ring::cast_to_M2FreeAlgebra(), Ring::cast_to_PolynomialRing(), M2FreeAlgebraQuotient::create(), PolynomialRing::create_quotient(), ERROR(), Matrix::get_ring(), intern_polyring(), and Matrix::n_rows().