Macaulay2 Engine: rawAmbientRing
rawAmbientRing()
const Ring* rawAmbientRing (const Ring * R)
Definition at line 579 of file ring.cpp.
 {
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P == 0)
     {
       ERROR("expected polynomial ring");
       return 0;
     }
   return P->getAmbientRing();
 }
References Ring::cast_to_PolynomialRing(), ERROR(), and PolynomialRing::getAmbientRing().