Macaulay2 Engine: IM2_Ring_frac
IM2_Ring_frac()
const Ring * IM2_Ring_frac (const Ring * R)
Definition at line 302 of file ring.cpp.
{
  try
    {
      if (R == globalZZ) return globalQQ;
      const PolyRingFlat *P = R->cast_to_PolyRingFlat();
      if (P == nullptr)
        {
          ERROR("expected polynomial ring");
          return nullptr;
        }
      if (P->getMonoid()->numNonTermOrderVariables() > 0)
        {
          ERROR(
              "cannot currently make fraction field over a polynomial ring "
              "with a non-global monomial order");
          return nullptr;
        }
      if (P->getMonoid()->numInvertibleVariables() > 0)
        {
          ERROR(
              "cannot currently make fraction field over a polynomial ring "
              "with Laurent variables, i.e. Inverses=>true set");
          return nullptr;
        }
      if (R->get_precision() > 0)
        {
          ERROR("cannot make fraction field over approximate field base");
          return nullptr;
        }
      if (P->getCoefficients()->cast_to_FractionField() != nullptr)
        {
          ERROR(
              "fraction fields over other fraction fields not yet implemented");
          return nullptr;
        }
      if (P->getCoefficients()->cast_to_LocalRing() != nullptr)
        {
          ERROR("fraction fields over other local rings not yet implemented");
          return nullptr;
        }
      return FractionField::create(P);
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References Ring::cast_to_FractionField(), Ring::cast_to_LocalRing(), Ring::cast_to_PolyRingFlat(), FractionField::create(), ERROR(), Ring::get_precision(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), globalQQ, globalZZ, Monoid::numInvertibleVariables(), and Monoid::numNonTermOrderVariables().