Macaulay2 Engine: rawTowerRing3
rawTowerRing3()
const Ring * rawTowerRing3 (const Ring * R1, engine_RawRingElementArray eqns)
Definition at line 528 of file ring.cpp.
{
  try
    {
      const Tower *R = R1->cast_to_Tower();
      if (R == nullptr)
        {
          ERROR("expected a tower coefficient ring");
          return nullptr;
        }
      VECTOR(ring_elem) extensions;
      for (int i = 0; i < eqns->len; i++)
        {
          const RingElement *f = eqns->array[i];
          if (f->get_ring() != R1)
            {
              ERROR("extension element has incorrect base ring");
              return nullptr;
            }
          extensions.push_back(f->get_value());
        }
      return Tower::create(R, extensions);
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References Ring::cast_to_Tower(), Tower::create(), ERROR(), RingElement::get_ring(), RingElement::get_value(), and VECTOR.