Macaulay2 Engine: IM2_Ring_solvable_algebra
IM2_Ring_solvable_algebra()
const Ring* IM2_Ring_solvable_algebra (const Ring * R, const Matrix * Q)
Definition at line 194 of file ring.cpp.
 {
   try
     {
       const PolynomialRing *P = R->cast_to_PolynomialRing();
       if (P == nullptr)
         {
           ERROR("expected a polynomial ring");
           return nullptr;
         }
       SolvableAlgebra *result = SolvableAlgebra::create(P, Q);
       intern_polyring(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Ring::cast_to_PolynomialRing(), SolvableAlgebra::create(), ERROR(), and intern_polyring().