Macaulay2 Engine: IM2_Ring_localization
IM2_Ring_localization()
const Ring* IM2_Ring_localization (const Ring * R, Computation * P)
Definition at line 350 of file ring.cpp.
 {
   try
     {
       const PolyRing *PR = R->cast_to_PolyRing(); // FIXME should this get a PolyRing or Ring?
       GBComputation *P = C->cast_to_GBComputation();
       if (PR == nullptr)
         {
           ERROR("expected a polynomial ring");
           return nullptr;
         }
       if (P == nullptr)
         {
           ERROR("expected a Grobner basis computation");
           return nullptr;
         }
       if (P->get_ring() != PR)
         {
           ERROR("expected matrix to be over the same ring");
           return nullptr;
         }
       return LocalRing::create(PR, P);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References Computation::cast_to_GBComputation(), Ring::cast_to_PolyRing(), LocalRing::create(), ERROR(), and GBComputation::get_ring().