Macaulay2 Engine: rawRingM2FreeAlgebraQuotient
rawRingM2FreeAlgebraQuotient()
const Ring* rawRingM2FreeAlgebraQuotient (const Matrix * GB, int maxdeg)
Definition at line 276 of file ring.cpp.
 {
   const Ring* A = GB->get_ring();
   try {
     if (A == nullptr)
       {
         ERROR("internal error: expected non-null Ring!");
         return nullptr;
       }
     const M2FreeAlgebra* P = A->cast_to_M2FreeAlgebra();
     if (P == nullptr)
       {
         ERROR("expected a free algebra");
         return nullptr;
       }
     const M2FreeAlgebraQuotient* result = M2FreeAlgebraQuotient::create(* P, GB, maxdeg);
     return result;
   }
   catch (exc::engine_error& e) {
     ERROR(e.what());
     return NULL;
   }
 }
References Ring::cast_to_M2FreeAlgebra(), M2FreeAlgebraQuotient::create(), ERROR(), and Matrix::get_ring().