Macaulay2 Engine: ModuleMonom::sizeOfCorrespondingModuleMonom
sizeOfCorrespondingModuleMonom()
static int ModuleMonom::sizeOfCorrespondingModuleMonom (const Monom & m) inline static
Definition at line 69 of file Polynomial.hpp.
   {
     return m.size() + 3;
   }
References Monom::size().
Referenced by IntsSet< Configuration >::find(), IntsSet< Configuration >::insert(), and monomToModuleMonom().