Macaulay2 Engine: TEST
TEST() [2/4]
TEST (PolyRing , createDegreesRing)
Definition at line 21 of file PolyRingTest.cpp.
{
  const Ring* DR = degreeRing(1);
  EXPECT_FALSE(error());
  EXPECT_TRUE(DR != nullptr);
  buffer o;
  DR->text_out(o);
  std::cout << "ring is " << o.str() << std::endl;
}
References degreeRing(), error(), buffer::str(), and Ring::text_out().