Macaulay2 Engine: TEST
TEST() [1/4]
TEST (PolyRing , create1)
Definition at line 43 of file PolyRingTest.cpp.
 {
   // Creaating a polynomial ring from C++.
   // Plan: this should be a simple constructor call!
   // Create coefficient ring
   const Ring* kk = rawARingZZpFlint(101); // or IM2_Ring_ZZ(), IM2_Ring_QQ(), and others...
   EXPECT_TRUE(kk != nullptr);
   // Now create the monomial order.  This one is a pain in the butt!
   std::vector<std::string> varnames { "a", "b", "c", "d" };
   std::vector<int> degs {1,1,1,1};
   std::vector<int> heft {1};
   MonomialOrdering* mo = rawGRevLexMonomialOrdering(stdvector_to_M2_arrayint(degs), 32);
   const Monoid* M = Monoid::create(
                              mo,
                              degreeRing(1),
                              varnames,
                              degs,
                              heft
                              );
   EXPECT_TRUE(M != nullptr);
   const Ring* R = PolyRing::create(kk, M);
   EXPECT_TRUE(R != nullptr);
   buffer o;
   R->text_out(o);
   std::cout << "ring is " << o.str() << std::endl;
 }
References Monoid::create(), PolyRing::create(), degreeRing(), rawARingZZpFlint(), rawGRevLexMonomialOrdering(), stdvector_to_M2_arrayint(), buffer::str(), and Ring::text_out().