Macaulay2 Engine: TEST
TEST() [3/4]
TEST (PolyRing , createDegreesRing2)
Definition at line 32 of file PolyRingTest.cpp.
 {
   const Ring* DR = degreeRing({"t1", "t2"});
   EXPECT_FALSE(error());
   EXPECT_TRUE(DR != nullptr);
   buffer o;
   DR->text_out(o);
   std::cout << "ring is " << o.str() << std::endl;
 }
References degreeRing(), error(), buffer::str(), and Ring::text_out().