Macaulay2 Engine: TEST
TEST() [4/4]
TEST (PolyRing , createSimple)
Definition at line 75 of file PolyRingTest.cpp.
 {
   // Creaating a polynomial ring from C++.
   // Plan: this should be a simple constructor call!
   // Create coefficient ring
   const Ring* R = simplePolynomialRing(101, { "a", "b", "c", "d" });
   EXPECT_TRUE(R != nullptr);
   buffer o;
   R->text_out(o);
   std::cout << "ring is " << o.str() << std::endl;
 }
References simplePolynomialRing(), buffer::str(), and Ring::text_out().