Macaulay2 Engine: LocalRing::is_unit
is_unit()
bool LocalRing::is_unit (const ring_elem f) const virtual
Implements Ring.
Definition at line 172 of file localring.cpp.
{
  // TODO: make sure f is a local ring element
  return (!is_in_prime(f.get_local_elem()->numer));
}
References ring_elem::get_local_elem(), is_in_prime(), and local_elem::numer.
Referenced by divide(), invert(), power(), power(), and rawIsLocalUnit().