Macaulay2 Engine: LocalRing::copy
copy()
ring_elem LocalRing::copy (const ring_elem f) const virtual
Implements Ring.
Definition at line 466 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   local_elem *g = new_local_elem();
   g->numer = mRing->copy(f->numer);
   g->denom = mRing->copy(f->denom);
   return ring_elem(g);
 }
References PolyRing::copy(), local_elem::denom, ring_elem::get_local_elem(), mRing, new_local_elem(), and local_elem::numer.
Referenced by term().