Macaulay2 Engine: LocalRing::simplify
simplify()
void LocalRing::simplify (local_elem * f) const private
Definition at line 73 of file localring.cpp.
 {
   ring_elem x, y;
   if (use_gcd_simplify)
     {
       y = f->denom;
       if (mRing->is_equal(y, mRing->one())) return;
       x = f->numer;
       const RingElement *a = RingElement::make_raw(mRing, x);
       const RingElement *b = RingElement::make_raw(mRing, y);
       const RingElement *c = rawGCDRingElement(a, b, NULL, false);
 #if 0
       // Debugging code
             buffer o;
             o << newline;
             o << "a = ";
             a->text_out(o);
             o << "  b = ";
             b->text_out(o);
             o << " gcd = ";
             c->text_out(o);
             o << newline;
             emit(o.str());
 #endif
       if (!mRing->is_equal(c->get_value(), mRing->one()))
         {
           f->numer = mRing->divide(f->numer, c->get_value());
           f->denom = mRing->divide(f->denom, c->get_value());
         }
       // Now, let's take the content of the denominator, and divide the
       // numerator
       // and denominator by this value.
       ring_elem ct = mRing->content(
           f->denom, f->numer);  // result is in mRing->getCoefficients()
 #if 0
             o.reset();
             o << "f->numer = ";
             mRing->elem_text_out(o,f->numer);
             o << "  f->denom = ";
             mRing->elem_text_out(o,f->denom);
             o << " ass= ";
             mRing->getCoefficients()->elem_text_out(o,ct);
             o << newline;
             emit(o.str());
 #endif
       if (!mRing->getCoefficients()->is_equal(ct,
                                               mRing->getCoefficients()->one()))
         {
           f->numer = mRing->divide_by_given_content(f->numer, ct);
           f->denom = mRing->divide_by_given_content(f->denom, ct);
         }
     }
   else
     {
       mRing->syzygy(f->numer, f->denom, x, y);
       if (mRing->is_zero(x))
         {
           mRing->remove(x);
           set_non_unit_frac(f->denom);
           f->numer = mRing->zero();
           f->denom = mRing->one();
           return;
         }
       mRing->negate_to(y);
       mRing->remove(f->numer);
       mRing->remove(f->denom);
       f->numer = y;
       f->denom = x;
     }
 }
References PolyRing::content(), local_elem::denom, PolyRing::divide(), PolyRing::divide_by_given_content(), PolyRing::elem_text_out(), Ring::elem_text_out(), emit(), RingElement::get_value(), PolynomialRing::getCoefficients(), PolyRing::is_equal(), Ring::is_equal(), PolyRing::is_zero(), RingElement::make_raw(), mRing, Ring::negate_to(), newline, local_elem::numer, Ring::one(), rawGCDRingElement(), PolyRing::remove(), buffer::reset(), set_non_unit_frac(), buffer::str(), PolyRing::syzygy(), RingElement::text_out(), use_gcd_simplify, x, and Ring::zero().
Referenced by make_elem().