Macaulay2 Engine: LocalRing::power
power() [1/2]
ring_elem LocalRing::power (const ring_elem f, int n) const virtual
Reimplemented from Ring.
Definition at line 542 of file localring.cpp.
{
  const local_elem *f = a.get_local_elem();
  ring_elem top, bottom;
  if (n >= 0)
    {
      top = mRing->power(f->numer, n);
      bottom = mRing->power(f->denom, n);
      if (mRing->is_zero(bottom)) return set_non_unit_frac(f->denom);
    }
  else
    {
      if (is_unit(a))
        {
          top = mRing->power(f->denom, -n);
          bottom = mRing->power(f->numer, -n);
        }
      else
        {
          throw exc::engine_error("attempt to divide by a non-unit");
        }
      if (mRing->is_zero(bottom)) return set_non_unit_frac(f->numer);
    }
  return ring_elem(make_elem(top, bottom));
}
References local_elem::denom, ring_elem::get_local_elem(), is_unit(), PolyRing::is_zero(), make_elem(), mRing, local_elem::numer, PolyRing::power(), and set_non_unit_frac().