Macaulay2 Engine: LocalRing::lift_up
lift_up()
void LocalRing::lift_up (const Ring * R, const Matrix * m, Matrix *& result) const virtual
Definition at line 227 of file localring.cpp.
 {
   const RingElement *a, *b, *d;
   MatrixConstructor mat(mRing->make_FreeModule(m->n_rows()), m->n_cols());
   Matrix::column_iterator i(m), end(m);
   for (int c = 0; c < m->n_cols(); c++)
     {
       // TODO: make this into a routine for vector LCM
       a = RingElement::make_raw(mRing, mRing->from_long(1));
       for (i = Matrix::column_iterator(m, c); i != end; ++i)
         {
           const local_elem * f = ((*i)->coeff).get_local_elem();
           b = RingElement::make_raw(mRing, f->denom);
           d = rawGCDRingElement(a, b, NULL, false);
 #if 0 // FIXME: GCD(8,2)=1 apparently ...
           // see https://github.com/Macaulay2/M2/issues/1958
           drelem(a);
           std::cout<<" ";
           drelem(b);
           std::cout<<" ";
           drelem(d);
           std::cout<<std::endl;
 #endif
           d = *b / *d;
           a = *a * *d;
         }
       for (i = Matrix::column_iterator(m, c); i != end; ++i)
         {
           const local_elem * f = ((*i)->coeff).get_local_elem();
           mat.set_entry(
               (*i)->comp,
               c,
               mRing->mult(f->numer, mRing->divide(a->get_value(), f->denom)));
         }
     }
   mat.compute_column_degrees();
   result = mat.to_matrix();
 }
References MatrixConstructor::compute_column_degrees(), local_elem::denom, PolyRing::divide(), drelem(), PolyRing::from_long(), RingElement::get_value(), Ring::make_FreeModule(), RingElement::make_raw(), mRing, PolyRing::mult(), Matrix::n_cols(), Matrix::n_rows(), local_elem::numer, rawGCDRingElement(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by rawLiftLocalMatrix().