Macaulay2 Engine: LocalRing::index_of_var
index_of_var()
int LocalRing::index_of_var (const ring_elem a) const virtual
Reimplemented from Ring.
Definition at line 351 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   if (!mRing->is_unit(f->denom))
     // If so, a cannot be a variable, otherwise, by 'simplify', f->denom == 1.
     return -1;
   return mRing->index_of_var(f->numer);
 }
References local_elem::denom, ring_elem::get_local_elem(), PolyRing::index_of_var(), PolyRing::is_unit(), mRing, and local_elem::numer.