Macaulay2 Engine: LocalRing::is_in_prime
is_in_prime()
bool LocalRing::is_in_prime (const ring_elem f) const private
Definition at line 63 of file localring.cpp.
 {
   MatrixConstructor mat(mRing->make_FreeModule(1), 1);
   mat.set_entry(0, 0, f);
   Matrix *M = mat.to_matrix();
   bool res = (mPrime->contains(M) == -1);
   delete M;
   return res;
 }
References GBComputation::contains(), Ring::make_FreeModule(), mPrime, mRing, MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by is_unit().