Macaulay2 Engine: LocalRing::is_equal
is_equal()
bool LocalRing::is_equal (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 183 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   const local_elem *g = b.get_local_elem();
   if (mRing->is_equal(f->denom, g->denom))
     {
       return mRing->is_equal(f->numer, g->numer);
     }
   else
     {
       ring_elem h = subtract(a, b);
       bool result = is_zero(h);
       remove(h);
       return result;
     }
 }
References local_elem::denom, ring_elem::get_local_elem(), PolyRing::is_equal(), is_zero(), mRing, local_elem::numer, remove(), and subtract().