Macaulay2 Engine: LocalRing::create
create()
LocalRing * LocalRing::create (const PolyRing * R, GBComputation * P) static
Definition at line 18 of file localring.cpp.
 {
   LocalRing *result = new LocalRing;
   result->initialize_local(R, P);
   return result;
 }
References initialize_local(), and LocalRing().
Referenced by IM2_Ring_localization().