Macaulay2 Engine: LocalRing::lift
lift()
bool LocalRing::lift (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 266 of file localring.cpp.
 {
   // Rg = R ---> frac R
   // f is an element of frac R.
   ring_elem
       hdenom;  // used in the case when the denominator can be a unit, but not 1
                // e.g. when this = frac (QQ[x,y,z]).  Is an element of
   if (Rg == mRing)
     {
       const local_elem *h = f.get_local_elem();
       if (mRing->is_equal(h->denom, mRing->one()))
         {
           result = mRing->copy(h->numer);
           return true;
         }
       else
         {
           if (mRing->is_field())
             {
               // XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               // try to lift denominator.  If can, can lift, otherwise not.
               if (mRing->lift(mRing, h->denom, hdenom))
                 {
                   ring_elem hinv = mRing->invert(hdenom);
                   result = mRing->mult(hinv, h->numer);
                   return true;
                 }
             }
         }
     }
   return false;
 }
References PolyRing::copy(), local_elem::denom, ring_elem::get_local_elem(), PolyRing::invert(), PolyRing::is_equal(), Ring::is_field(), PolyRing::lift(), mRing, PolyRing::mult(), local_elem::numer, and Ring::one().