Macaulay2 Engine: LocalRing::promote
promote()
bool LocalRing::promote (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 300 of file localring.cpp.
 {
   // Rf = R ---> frac R
   if (Rf == mRing)
     {
       local_elem *g = new_local_elem();
       g->numer = mRing->copy(f);
       g->denom = mRing->from_long(1);
       result = ring_elem(g);
       return true;
     }
   return false;
 }
References PolyRing::copy(), local_elem::denom, PolyRing::from_long(), mRing, new_local_elem(), and local_elem::numer.