Macaulay2 Engine: LocalRing::homogenize
homogenize() [1/2]
ring_elem LocalRing::homogenize (const ring_elem f, int v, const std::vector< int > & wts) const virtual
Reimplemented from Ring.
Definition at line 455 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   ring_elem top = mRing->homogenize(f->numer, v, wts);
   ring_elem bottom = mRing->homogenize(f->denom, v, wts);
   local_elem *result = make_elem(top, bottom);
   return ring_elem(result);
 }
References local_elem::denom, ring_elem::get_local_elem(), PolyRing::homogenize(), make_elem(), mRing, and local_elem::numer.