Macaulay2 Engine: LocalRing::multi_degree
multi_degree()
bool LocalRing::multi_degree (const ring_elem f, monomial d) const virtual
Reimplemented from Ring.
Definition at line 410 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   bool tophom = mRing->multi_degree(f->numer, d);
   monomial e = degree_monoid()->make_one();
   bool bottomhom = mRing->multi_degree(f->denom, e);
   degree_monoid()->divide(d, e, d);
   degree_monoid()->remove(e);
   return tophom && bottomhom;
 }
References Ring::degree_monoid(), local_elem::denom, Monoid::divide(), ring_elem::get_local_elem(), Monoid::make_one(), mRing, PolyRing::multi_degree(), local_elem::numer, and Monoid::remove().