Macaulay2 Engine: LocalRing::lower_content
lower_content()
void LocalRing::lower_content (ring_elem & c, const ring_elem g) const virtual
Reimplemented from Ring.
Definition at line 372 of file localring.cpp.
 {
   if (!use_gcd_simplify) return;
   if (is_zero(c))
     {
       c = g;
       return;
     }
   const local_elem *cf = c.get_local_elem();
   const local_elem *gf = g.get_local_elem();
   const RingElement *c1 = RingElement::make_raw(mRing, cf->numer);
   const RingElement *c2 = RingElement::make_raw(mRing, cf->denom);
   const RingElement *g1 = RingElement::make_raw(mRing, gf->numer);
   const RingElement *g2 = RingElement::make_raw(mRing, gf->denom);
   c1 = rawGCDRingElement(c1, g1, nullptr, false);
   const RingElement *cc2 = rawGCDRingElement(c2, g2, nullptr, false);
   const RingElement *cc3 = (*c2) * (*g2);
   const RingElement *cc4 = (*cc3) / (*cc2);
   local_elem *result = new_local_elem();
   result->numer = c1->get_value();
   result->denom = cc4->get_value();
   c = ring_elem(result);
 }
References local_elem::denom, ring_elem::get_local_elem(), RingElement::get_value(), is_zero(), RingElement::make_raw(), mRing, new_local_elem(), local_elem::numer, rawGCDRingElement(), and use_gcd_simplify.