Macaulay2 Engine: LocalRing::get_ring
get_ring()
const PolyRing* LocalRing::get_ring () const inline
Definition at line 42 of file localring.hpp.
 { return mRing; }
References mRing.
Referenced by RingElement::denominator(), RingElement::fraction(), RingElement::numerator(), and rawLiftLocalMatrix().