Macaulay2 Engine: LocalRing::eval
eval()
ring_elem LocalRing::eval (const RingMap * map, const ring_elem f, int first_var) const virtual
Implements Ring.
Definition at line 649 of file localring.cpp.
 {
   ring_elem top, bottom, result;
   const Ring *S = map->get_ring();
   const local_elem *f = a.get_local_elem();
   top = mRing->eval(map, f->numer, first_var);
   if (S->is_zero(top)) return top;
   bottom = mRing->eval(map, f->denom, first_var);
   if (S->is_unit(bottom))
     result = S->divide(top, bottom);
   else
     {
       throw exc::engine_error("attempt to divide by a non-unit");
     }
   S->remove(top);
   S->remove(bottom);
   return result;
 }
References local_elem::denom, Ring::divide(), PolyRing::eval(), ring_elem::get_local_elem(), RingMap::get_ring(), Ring::is_unit(), Ring::is_zero(), mRing, local_elem::numer, and Ring::remove().