Macaulay2 Engine: LocalRing::elem_text_out
elem_text_out()
void LocalRing::elem_text_out (buffer & o, const ring_elem f, bool p_one = true, bool p_plus = false, bool p_parens = false) const virtual
Implements Ring.
Definition at line 706 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   int denom_one = mRing->is_equal(f->denom, mRing->one());
   p_one = p_one || !denom_one;
   p_parens = p_parens || !denom_one;
   mRing->elem_text_out(o, f->numer, p_one, p_plus, p_parens);
   if (!denom_one)
     {
       o << "/";
       p_plus = false;
       mRing->elem_text_out(o, f->denom, p_one, p_plus, p_parens);
     }
 }
References local_elem::denom, PolyRing::elem_text_out(), ring_elem::get_local_elem(), PolyRing::is_equal(), mRing, local_elem::numer, and Ring::one().