Macaulay2 Engine: LocalRing::homogenize
homogenize() [1/2]
ring_elem LocalRing::homogenize (const ring_elem f, int v, int deg, M2_arrayint wts) const virtual
Reimplemented from Ring.
Definition at line 441 of file localring.cpp.
 {
   int d1, d2, lo1, lo2;
   ring_elem top, bottom;
   const local_elem *f = a.get_local_elem();
   mRing->degree_weights(f->numer, wts, lo1, d1);
   mRing->degree_weights(f->denom, wts, lo2, d2);
   if (deg >= d1 - d2)
     {
       top = mRing->homogenize(f->numer, v, deg + d2, wts);
       bottom = mRing->homogenize(f->denom, v, d2, wts);
     }
   else
     {
       top = mRing->homogenize(f->numer, v, d1, wts);
       bottom = mRing->homogenize(f->denom, v, -deg + d1, wts);
     }
   local_elem *result = make_elem(top, bottom);
   return ring_elem(result);
 }
References PolyRing::degree_weights(), local_elem::denom, ring_elem::get_local_elem(), PolyRing::homogenize(), make_elem(), mRing, and local_elem::numer.