Macaulay2 Engine: LocalRing::set_non_unit_frac
set_non_unit_frac()
ring_elem LocalRing::set_non_unit_frac (ring_elem top) const private
Definition at line 147 of file localring.cpp.
{
  // Sets the non unit to be top/1 (which flags an error)
  // flags an error
  // returns 0/1
  std::cout << "set_non_unit_frac is called!" << std::endl;
  local_elem *f = new_local_elem();
  f->numer = top;
  f->denom = mRing->one();
  set_non_unit(ring_elem(f));
  return zero();
}
References local_elem::denom, mRing, new_local_elem(), local_elem::numer, Ring::one(), Ring::set_non_unit(), and Ring::zero().
Referenced by add(), mult(), power(), power(), simplify(), and subtract().