Macaulay2 Engine: LocalRing::is_homogeneous
is_homogeneous()
bool LocalRing::is_homogeneous (const ring_elem f) const virtual
Reimplemented from Ring.
Definition at line 401 of file localring.cpp.
 {
   if (is_zero(a)) return true;
   const local_elem *f = a.get_local_elem();
   if (!mRing->is_homogeneous(f->numer) || !mRing->is_homogeneous(f->denom))
     return false;
   return true;
 }
References local_elem::denom, ring_elem::get_local_elem(), PolyRing::is_homogeneous(), is_zero(), mRing, and local_elem::numer.