Macaulay2 Engine: LocalRing::support
support()
M2_arrayint LocalRing::support (const ring_elem a) const virtual
Reimplemented from Ring.
Definition at line 360 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   M2_arrayint result1 = mRing->support(f->numer);
   M2_arrayint result2 = mRing->support(f->denom);
   M2_arrayint result = M2_makearrayint(result1->len + result2->len);
   for (int i = 0; i < result1->len; i++) result->array[i] = result1->array[i];
   for (int i = 0; i < result2->len; i++)
     result->array[result1->len + i] = result2->array[i];
   return result;
 }
References local_elem::denom, ring_elem::get_local_elem(), M2_makearrayint(), mRing, local_elem::numer, and PolyRing::support().