Macaulay2 Engine: LocalRing::subtract
subtract()
ring_elem LocalRing::subtract (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 517 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   const local_elem *g = b.get_local_elem();
   ring_elem top, bottom;
   if (mRing->is_equal(f->denom, g->denom))
     {
       top = mRing->subtract(f->numer, g->numer);
       bottom = mRing->copy(f->denom);
     }
   else
     {
       top = mRing->mult(f->numer, g->denom);
       ring_elem tmp = mRing->mult(f->denom, g->numer);
       mRing->subtract_to(top, tmp);
       bottom = mRing->mult(f->denom, g->denom);
       if (mRing->is_zero(bottom)) return set_non_unit_frac(f->denom);
     }
   local_elem *result = make_elem(top, bottom);
   return ring_elem(result);
 }
References PolyRing::copy(), local_elem::denom, ring_elem::get_local_elem(), PolyRing::is_equal(), PolyRing::is_zero(), make_elem(), mRing, PolyRing::mult(), local_elem::numer, set_non_unit_frac(), PolyRing::subtract(), and Ring::subtract_to().
Referenced by is_equal().