Macaulay2 Engine: LocalRing::new_local_elem
new_local_elem()
local_elem * LocalRing::new_local_elem () const private
Definition at line 61 of file localring.cpp.
 { return newitem(local_elem); }
References newitem.
Referenced by copy(), from_int(), from_long(), from_rational(), lower_content(), make_elem(), negate(), promote(), set_non_unit_frac(), and var().