Macaulay2 Engine: LocalRing::random
random()
ring_elem LocalRing::random () const virtual
Reimplemented from Ring.
Definition at line 637 of file localring.cpp.
 {
   ring_elem a = mRing->random();
   ring_elem b = mRing->random();
   if (mRing->is_zero(b))
     {
       mRing->remove(b);
       b = mRing->from_long(1);
     }
   return ring_elem(make_elem(a, b));
 }
References PolyRing::from_long(), PolyRing::is_zero(), make_elem(), mRing, PolyRing::random(), and PolyRing::remove().