Macaulay2 Engine: LocalRing::from_rational
from_rational()
bool LocalRing::from_rational (mpq_srcptr n, ring_elem & result) const virtual
Implements Ring.
Definition at line 317 of file localring.cpp.
 {
   local_elem *f = new_local_elem();
   f->numer = mRing->from_int(mpq_numref(n));
   f->denom = mRing->from_int(mpq_denref(n));
   bool ok = not mRing->is_zero(f->denom);
   if (ok) result = ring_elem(f);
   return ok;
 }
References local_elem::denom, PolyRing::from_int(), PolyRing::is_zero(), mRing, new_local_elem(), and local_elem::numer.