Macaulay2 Engine: LocalRing::fraction
fraction()
ring_elem LocalRing::fraction (const ring_elem top, const ring_elem bottom) const
Definition at line 221 of file localring.cpp.
 {
   return ring_elem(make_elem(mRing->copy(top), mRing->copy(bottom)));
 }
References PolyRing::copy(), make_elem(), and mRing.
Referenced by RingElement::fraction().