Macaulay2 Engine: LocalRing::divide
divide()
ring_elem LocalRing::divide (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 618 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   const local_elem *g = b.get_local_elem();
   ring_elem top, bottom;
   if (is_unit(b))
     {
       top = mRing->mult(f->numer, g->denom);
       bottom = mRing->mult(f->denom, g->numer);
     }
   else
     {
       throw exc::engine_error("attempt to divide by a non-unit");
     }
   return ring_elem(make_elem(top, bottom));
 }
References local_elem::denom, ring_elem::get_local_elem(), is_unit(), make_elem(), mRing, PolyRing::mult(), and local_elem::numer.
Referenced by syzygy().