Macaulay2 Engine: LocalRing::invert
invert()
ring_elem LocalRing::invert (const ring_elem f) const virtual
Implements Ring.
Definition at line 598 of file localring.cpp.
 {
   const local_elem *f = a.get_local_elem();
   if (mRing->is_zero(f->numer) || !is_unit(a))
     {
       throw exc::engine_error("attempt to invert a non-unit");
     }
   ring_elem top = mRing->copy(f->denom);
   ring_elem bottom = mRing->copy(f->numer);
   return ring_elem(make_elem(top, bottom));
 }
References PolyRing::copy(), local_elem::denom, ring_elem::get_local_elem(), is_unit(), PolyRing::is_zero(), make_elem(), mRing, and local_elem::numer.