Macaulay2 Engine: LocalRing::numerator
numerator()
ring_elem LocalRing::numerator (ring_elem f) const
Definition at line 209 of file localring.cpp.
 {
   const local_elem *g = f.get_local_elem();
   return mRing->copy(g->numer);
 }
References PolyRing::copy(), ring_elem::get_local_elem(), mRing, and local_elem::numer.
Referenced by RingElement::numerator().