Macaulay2 Engine: DPoly::is_one
is_one()
bool DPoly::is_one (int level, const TowerPolynomial f) static
Definition at line 595 of file dpoly.cpp.
 {
   if (f == 0) return false;
   if (f->deg != 0) return false;
   if (level == 0)
     return 1 == f->arr.ints[0];
   else
     return is_one(level - 1, f->arr.polys[0]);
 }
Referenced by division_in_place(), elem_text_out(), index_of_var(), invert(), DRing::is_one(), and mult_by_coeff_n().