Macaulay2 Engine: DPoly::copy
copy()
TowerPolynomial DPoly::copy (int level, const TowerPolynomial f) static
Definition at line 483 of file dpoly.cpp.
 {
   if (f == nullptr) return nullptr;
   TowerPolynomial result;
   if (level == 0)
     {
       result = alloc_poly_0(f->deg);
       for (int i = 0; i <= f->deg; i++) result->arr.ints[i] = f->arr.ints[i];
     }
   else
     {
       result = alloc_poly_n(f->deg);
       for (int i = 0; i <= f->deg; i++)
         result->arr.polys[i] = copy(level - 1, f->arr.polys[i]);
     }
   return result;
 }
References alloc_poly_0(), and alloc_poly_n().
Referenced by DRing::add(), add_in_place_0(), add_in_place_n(), DRing::divide(), division_in_place(), division_in_place_monic(), DRing::from_ring_elem(), gcd(), gcd_coefficients(), initialize(), power_mod(), DRing::remainder(), DRing::subtract(), subtract_in_place_0(), subtract_in_place_n(), and DRing::to_ring_elem().