Macaulay2 Engine: DPoly::make_monic
make_monic()
void DPoly::make_monic (int level, TowerPolynomial & f)
Definition at line 921 of file dpoly.cpp.
 {
   if (f == 0) return;
   if (level == 0)
     {
       long not_used;
       make_monic_0(f, not_used);
     }
   else
     {
       TowerPolynomial not_used;
       make_monic_n(level, f, not_used);
       dealloc_poly(not_used);
     }
 }
References dealloc_poly(), make_monic_0(), and make_monic_n().
Referenced by gcd().