Macaulay2 Engine: DPoly::subtract_in_place
subtract_in_place()
void DPoly::subtract_in_place (int level, TowerPolynomial & f, const TowerPolynomial g)
Definition at line 793 of file dpoly.cpp.
 {
   if (level == 0)
     subtract_in_place_0(f, g);
   else
     subtract_in_place_n(level, f, g);
 }
References subtract_in_place_0(), and subtract_in_place_n().
Referenced by division_in_place(), division_in_place_monic(), DRing::subtract(), subtract_in_place_n(), and DRing::subtract_multiple().