Macaulay2 Engine: DPoly::lowerP
lowerP()
TowerPolynomial DPoly::lowerP (int level, const TowerPolynomial f)
Definition at line 1413 of file dpoly.cpp.
 {
   int i, j;
   TowerPolynomial result;
   if (f == 0) return 0;
   int charac_as_int = static_cast<int>(charac);
   int newdeg = f->deg / charac_as_int;  // should be exact...
   if (level == 0)
     {
       result = alloc_poly_0(newdeg);
       // In this situation, we just need to grab every p*i coeff...
       for (i = 0, j = 0; i <= newdeg; i++, j += charac_as_int)
         result->arr.ints[i] = f->arr.ints[j];
     }
   else
     {
       result = alloc_poly_n(newdeg);
       mpz_t order;
       mpz_init(order);
       unsigned long extdeg = 1;
       for (i = 0; i < level; i++) extdeg *= degree_of_extension(i);
       mpz_ui_pow_ui(order, charac_as_int, extdeg - 1);
       for (i = 0, j = 0; i <= newdeg; i++, j += charac_as_int)
         {
           // need p-th roots of the coefficients.  So we take p^(n-1)
           // power (if coefficients are in field of size p^n)
           TowerPolynomial a = f->arr.polys[j];
           TowerPolynomial b = power_mod(level - 1, a, order, extensions[level - 1]);
           result->arr.polys[i] = b;
         }
       mpz_clear(order);
     }
   return result;
 }
References alloc_poly_0(), alloc_poly_n(), charac, degree_of_extension(), extensions, and power_mod().
Referenced by DRing::lowerP().