Macaulay2 Engine: DPoly::mult_0
mult_0()
TowerPolynomial DPoly::mult_0 (const TowerPolynomial f, const TowerPolynomial g, bool reduce_by_extension) private
Definition at line 801 of file dpoly.cpp.
 {
   if (f == nullptr || g == nullptr) return nullptr;
   TowerPolynomial result = alloc_poly_0(f->deg + g->deg);
   for (int i = 0; i <= f->deg; i++)
     {
       long a = f->arr.ints[i];
       for (int j = 0; j <= g->deg; j++)
         ZZp_APXY(charac, result->arr.ints[i + j], a, g->arr.ints[j]);
     }
   if (reduce_by_extension && extensions[0] != nullptr)
     remainder(0, result, extensions[0]);
   return result;
 }
References alloc_poly_0(), charac, extensions, remainder(), and ZZp_APXY().
Referenced by mult().