Macaulay2 Engine: DPoly::to_string
to_string()
char * DPoly::to_string (int level, const TowerPolynomial f) static
Definition at line 417 of file dpoly.cpp.
{
  std::ostringstream o;
  append_to_stream(o, level, f);
  o << '\0';
  size_t n = o.str().length();
  char *result = new char[n + 1];
  memcpy(result, o.str().c_str(), n);
  return result;
}
References append_to_stream().
Referenced by gcd(), and gcd_coefficients().