Macaulay2 Engine: DPoly::add_term
add_term()
void DPoly::add_term (int level, TowerPolynomial & result, long coeff, exponents_t exp) const
Definition at line 648 of file dpoly.cpp.
 {
   // modifies result.
   // exp is an array [0..level-1] of exponent values for each variable
   // 0..level-1
   // the outer variable is at index 0.
   // coeff is an already normalized coefficient, and is not 0.
   int e = exp[0];
   if (result == nullptr)
     result = alloc_poly_n(e, nullptr);
   else if (result->deg < e)
     increase_size_n(e, result);
   if (level == 0)
     ZZp_ADD_TO(charac, result->arr.ints[e], coeff);
   else
     add_term(level - 1, result->arr.polys[e], coeff, exp + 1);
 }
References alloc_poly_n(), charac, mpfr::exp(), increase_size_n(), and ZZp_ADD_TO().
Referenced by DRing::add_term().