Macaulay2 Engine: DPoly::initialize
initialize()
void DPoly::initialize (long p, int nvars0, const TowerPolynomial * ext0) private
Definition at line 80 of file dpoly.cpp.
 {
   charac = p;
   nvars = nvars0;
   nlevels = nvars0;
   extensions = newarray(TowerPolynomial, nlevels);
   if (ext0 == 0)
     for (int i = 0; i < nlevels; i++) extensions[i] = 0;
   else
     for (int i = 0; i < nlevels; i++)
       {
         extensions[i] = copy(nlevels - 1, ext0[i]);
         down_level(i, nlevels - 1, extensions[i]);
       }
 }
References charac, copy(), down_level(), extensions, newarray, nlevels, nvars, and p.
Referenced by DPoly().