Macaulay2 Engine: DPoly::mult_by_int_0
mult_by_int_0()
TowerPolynomial DPoly::mult_by_int_0 (long c, const TowerPolynomial f) private
Definition at line 1284 of file dpoly.cpp.
 {
   TowerPolynomial result = alloc_poly_0(f->deg);
   for (int i = 0; i <= f->deg; i++)
     {
       long c = f->arr.ints[i];
       if (c != 0)
         {
           ZZp_MULT(charac, c, a);
           result->arr.ints[i] = c;
         }
     }
   reset_degree_0(result);
   return result;
 }
References alloc_poly_0(), charac, reset_degree_0(), and ZZp_MULT().
Referenced by mult_by_int().