Macaulay2 Engine: DPoly::dealloc_poly
dealloc_poly()
void DPoly::dealloc_poly (TowerPolynomial & f) static
Definition at line 292 of file dpoly.cpp.
 {
   if (f == 0) return;
   freemem(f->arr.polys);
   delete f;
   f = 0;
 }
References freemem().
Referenced by add_in_place_n(), DRing::divide(), down_level(), gcd_coefficients(), invert(), make_monic(), make_monic3(), mult_by_coeff_0(), mult_by_coeff_n(), mult_n(), remainder(), reset_degree_0(), reset_degree_n(), subtract_in_place_0(), and subtract_in_place_n().