Macaulay2 Engine: DPoly::append_to_stream
append_to_stream()
std::ostream & DPoly::append_to_stream (std::ostream & o, int level, const TowerPolynomial f) static
Definition at line 389 of file dpoly.cpp.
{
  if (f == nullptr)
    o << "0";
  else if (level == 0)
    {
      long *p = f->arr.ints;
      o << "[";
      for (int i = 0; i <= f->deg; i++)
        {
          if (i > 0) o << ",";
          if (p[i] != 0) o << p[i];
        }
      o << "]";
    }
  else
    {
      TowerPolynomial *p = f->arr.polys;
      o << "[";
      for (int i = 0; i <= f->deg; i++)
        {
          if (i > 0) o << ",";
          if (p[i] != nullptr) append_to_stream(o, level - 1, p[i]);
        }
      o << "]";
    }
  return o;
}
References append_to_stream(), and p.
Referenced by append_to_stream(), and to_string().