Macaulay2 Engine: DPoly::add_in_place
add_in_place()
void DPoly::add_in_place (int level, TowerPolynomial & f, const TowerPolynomial g)
Definition at line 721 of file dpoly.cpp.
 {
   if (level == 0)
     add_in_place_0(f, g);
   else
     add_in_place_n(level, f, g);
 }
References add_in_place_0(), and add_in_place_n().
Referenced by DRing::add(), add_in_place_n(), gcd_coefficients(), and mult_n().