Macaulay2 Engine: DPoly::gcd
gcd()
TowerPolynomial DPoly::gcd (int level, const TowerPolynomial f, const TowerPolynomial g)
Definition at line 1118 of file dpoly.cpp.
 {
   TowerPolynomial F = copy(level, f);
   TowerPolynomial G = copy(level, g);
   if (G == 0)
     {
       G = F;
       F = 0;
     }
   for (;;)
     {
 #ifdef DEBUGGCD
       printf("G = %s\n", to_string(level, G));
 #endif
       make_monic(level, G);
       if (G == 0) return 0;  // failed
 #ifdef DEBUGGCD
       printf("monic G = %s\n", to_string(level, G));
       printf("F       = %s\n", to_string(level, F));
 #endif
       remainder(level, F, G);  // modifies F
       if (F == 0) return G;
 #ifdef DEBUGGCD
       printf("F mod G     = %s\n", to_string(level, F));
 #endif
       swap_poly(F, G);
     }
 }
References copy(), make_monic(), remainder(), swap_poly(), and to_string().
Referenced by DRing::gcd().