Macaulay2 Engine: DPoly::degrees_of_vars
degrees_of_vars()
void DPoly::degrees_of_vars (int level, const TowerPolynomial f, std::vector< int > & result_max_degs) const
Definition at line 1469 of file dpoly.cpp.
{
  // Set the values of result_maxdegs at indices: 0..level
  result_maxdegs[level] = std::max(result_maxdegs[level], f->deg);
  if (level == 0) return;
  for (int i = 0; i <= f->deg; i++)
    if (f->arr.polys[i] != nullptr)
      degrees_of_vars(level - 1, f->arr.polys[i], result_maxdegs);
}
References degrees_of_vars().
Referenced by DRing::degrees_of_vars(), and degrees_of_vars().