Macaulay2 Engine: DPoly::read_poly_n
read_poly_n()
TowerPolynomial DPoly::read_poly_n (char *& str, int level) static private
Definition at line 301 of file dpoly.cpp.
 {
   int len = 0;
   TowerPolynomial *elems = newarray(TowerPolynomial, 100);
   TowerPolynomial this_elem = nullptr;
   if (*str != '[')
     {
       fprintf(stderr, "expected '[', got %s\n", str);
       exit(1);
     }
   str++;
   // Now loop
   while (*str != ']')
     {
       while (isspace(*str)) str++;
       if (*str == ',')
         {
           str++;
         }
       else if (*str == '[')
         {
           this_elem = read_poly(str, level - 1);  // eats ]
           while (isspace(*str)) str++;
           if (*str == ',') str++;
         }
       else
         {
           fprintf(stderr, "expected , or [, but got %s\n", str);
           exit(1);
         }
       elems[len++] = this_elem;
       this_elem = nullptr;
     }
   // the only way to get here is if *str == ']'.  Eat that char.
   str++;
   TowerPolynomial result = DPoly::alloc_poly_n(len - 1, elems);
   freemem(elems);
   return result;
 }
References alloc_poly_n(), freemem(), newarray, and read_poly().
Referenced by read_poly().