Macaulay2 Engine: DPoly::remainder
remainder()
void DPoly::remainder (int level, TowerPolynomial & f, const TowerPolynomial g)
Definition at line 1088 of file dpoly.cpp.
 {
   if (g == nullptr) return;
   TowerPolynomial quot = nullptr;
   division_in_place(level, f, g, quot);
   dealloc_poly(quot);
 }
References dealloc_poly(), and division_in_place().
Referenced by gcd(), mult_0(), mult_n(), power_mod(), and DRing::remainder().