Macaulay2 Engine: DPoly::power_mod
power_mod()
TowerPolynomial DPoly::power_mod (int level, const TowerPolynomial f, mpz_srcptr n, const TowerPolynomial g)
Definition at line 1367 of file dpoly.cpp.
 {
   // We assume that m > 0. THIS IS NOT CHECKED!!
   mpz_t n;
   mpz_init_set(n, m);
   TowerPolynomial prod = from_long(level, 1);
   TowerPolynomial base = copy(level, f);
   TowerPolynomial tmp;
   for (;;)
     {
       //      fprintf(stdout, "prod = ");
       //      dpoly(level,prod);
       //      fprintf(stdout, "\nbase = ");
       //      dpoly(level,base);
       //      fprintf(stdout, "\n");
       if (RingZZ::mod_ui(n, 2) == 1)
         {
           tmp = mult(level, prod, base, false);
           remainder(level, tmp, g);
           // TODO: free prod
           prod = tmp;
         }
       mpz_tdiv_q_2exp(n, n, 1);
       if (mpz_sgn(n) == 0)
         {
           mpz_clear(n);
           //      fprintf(stdout, "final prod = ");
           //      dpoly(level,prod);
           //              fprintf(stdout, "\nbase = ");
           //              dpoly(level,base);
           //              fprintf(stdout, "\n");
           // TODO: free base
           return prod;
         }
       else
         {
           tmp = mult(level, base, base, false);
           remainder(level, tmp, g);
           // TODO: free base
           base = tmp;
         }
     }
 }
References base, copy(), from_long(), RingZZ::mod_ui(), mult(), and remainder().
Referenced by lowerP(), and DRing::power_mod().