Macaulay2 Engine: DPoly::subtract_in_place_0
subtract_in_place_0()
void DPoly::subtract_in_place_0 (TowerPolynomial & f, const TowerPolynomial g) private
Definition at line 729 of file dpoly.cpp.
 {
   int i;
   if (g == nullptr) return;
   if (f == nullptr)
     {
       f = copy(0, g);
       negate_in_place(0, f);
       return;
     }
   int fdeg = f->deg;
   int gdeg = g->deg;
   increase_size_0(g->deg, f);
   for (i = 0; i <= gdeg; i++)
     ZZp_SUBTRACT_TO(charac, f->arr.ints[i], g->arr.ints[i]);
   if (gdeg > fdeg)
     f->deg = gdeg;
   else if (gdeg == fdeg)
     {
       // need to change the degree
       for (int j = fdeg; j >= 0; --j)
         if (f->arr.ints[j] != 0)
           {
             f->deg = j;
             return;
           }
       // at this point, everything is 0!
       dealloc_poly(f);
     }
 }
References charac, copy(), dealloc_poly(), increase_size_0(), negate_in_place(), and ZZp_SUBTRACT_TO().
Referenced by subtract_in_place().