Macaulay2 Engine: DPoly::mult_by_int
mult_by_int()
TowerPolynomial DPoly::mult_by_int (int level, long c, const TowerPolynomial f)
Definition at line 1311 of file dpoly.cpp.
{
  if (f == nullptr) return nullptr;
  if (level == 0) return mult_by_int_0(a, f);
  return mult_by_int_n(level, a, f);
}
References mult_by_int_0(), and mult_by_int_n().
Referenced by diff_n(), and mult_by_int_n().