Macaulay2 Engine: DPoly::negate_in_place
negate_in_place()
void DPoly::negate_in_place (int level, TowerPolynomial & f)
Definition at line 604 of file dpoly.cpp.
{
  if (f == nullptr) return;
  if (level == 0)
    {
      int deg = f->deg;
      long *p = f->arr.ints;
      for (int i = 0; i <= deg; i++)
        if (p[i] != 0) ZZp_NEGATE(charac, p[i]);
    }
  else
    {
      int deg = f->deg;
      TowerPolynomial *p = f->arr.polys;
      for (int i = 0; i <= deg; i++)
        if (p[i] != nullptr) negate_in_place(level - 1, p[i]);
    }
}
References charac, negate_in_place(), p, and ZZp_NEGATE().
Referenced by gcd_coefficients(), negate_in_place(), subtract_in_place_0(), and subtract_in_place_n().