Macaulay2 Engine: DPoly::make_monic_n
make_monic_n()
void DPoly::make_monic_n (int level, TowerPolynomial & f, TowerPolynomial & result_multiplier) private
Definition at line 911 of file dpoly.cpp.
 {
   if (f == nullptr) return;
   TowerPolynomial *p = f->arr.polys;
   TowerPolynomial a = p[f->deg];
   TowerPolynomial b = invert(level - 1, a);
   mult_by_coeff_n(level, f, b);
   result_multiplier = b;
 }
References invert(), mult_by_coeff_n(), and p.
Referenced by make_monic(), and make_monic3().