Macaulay2 Engine: DPoly::make_monic_0
make_monic_0()
void DPoly::make_monic_0 (TowerPolynomial & f, long & result_multiplier) private
Definition at line 901 of file dpoly.cpp.
 {
   if (f == nullptr) return;
   long *p = f->arr.ints;
   long a = p[f->deg];
   long b;
   ZZp_INVERT(charac, b, a);
   mult_by_coeff_0(f, b);
   result_multiplier = b;
 }
References charac, mult_by_coeff_0(), p, and ZZp_INVERT().
Referenced by make_monic(), and make_monic3().