Macaulay2 Engine: DPoly::mult_by_int_n
mult_by_int_n()
TowerPolynomial DPoly::mult_by_int_n (int level, long c, const TowerPolynomial f) private
Definition at line 1299 of file dpoly.cpp.
 {
   TowerPolynomial result = alloc_poly_n(f->deg);
   for (int i = 0; i <= f->deg; i++)
     {
       TowerPolynomial c = f->arr.polys[i];
       if (c != 0) result->arr.polys[i] = mult_by_int(level - 1, a, c);
     }
   reset_degree_n(level, result);
   return result;
 }
References alloc_poly_n(), mult_by_int(), and reset_degree_n().
Referenced by mult_by_int().