Macaulay2 Engine: DPoly::random
random() [2/2]
TowerPolynomial DPoly::random (int level, int deg)
Definition at line 549 of file dpoly.cpp.
 {
   if (deg < 0) deg = 0;  // Take a random element of degree 0.
   if (level == 0) return random_0(deg);
   return random_n(level, deg);
 }
References random_0(), and random_n().
Referenced by random(), random_n(), and DRing::set_random().