Macaulay2 Engine: DPoly::alloc_poly_0
alloc_poly_0()
TowerPolynomial DPoly::alloc_poly_0 (int deg, long * elems = 0) static
Definition at line 279 of file dpoly.cpp.
 {
   TowerPolynomial result = new TowerPolynomialStruct;
   result->arr.ints = newarray_atomic(long, deg + 1);
   result->deg = deg;
   result->len = deg + 1;
   if (elems == 0)
     for (int i = 0; i <= deg; i++) result->arr.ints[i] = 0;
   else
     for (int i = 0; i <= deg; i++) result->arr.ints[i] = elems[i];
   return result;
 }
References TowerPolynomial::arr, TowerPolynomial::ints, and newarray_atomic.
Referenced by copy(), diff_0(), diff_n(), from_long(), lowerP(), mult_0(), mult_by_int_0(), random_0(), read_poly_0(), and var().