Macaulay2 Engine: DPoly::invert
invert()
TowerPolynomial DPoly::invert (int level, const TowerPolynomial a)
Definition at line 854 of file dpoly.cpp.
 {
   // plan: compute the extended gcd of a and extensions[level]
   //   as univariate polynomials (at level 'level').
   // either return 0, if the gcd returned was not 1, or return
   // result_u.
   TowerPolynomial u, v;
   TowerPolynomial g = gcd_coefficients(level, a, extensions[level], u, v);
   if (!is_one(level, g))
     {
       dealloc_poly(u);
     }
   dealloc_poly(g);
   dealloc_poly(v);
   return u;
 }
References dealloc_poly(), extensions, gcd_coefficients(), and is_one().
Referenced by division_in_place(), DRing::invert(), and make_monic_n().