Macaulay2 Engine: DPoly::mult
mult()
TowerPolynomial DPoly::mult (int level, const TowerPolynomial f, const TowerPolynomial g, bool reduce_by_extension)
Definition at line 845 of file dpoly.cpp.
 {
   if (level == 0) return mult_0(f, g, reduce_by_extension);
   return mult_n(level, f, g, reduce_by_extension);
 }
References mult_0(), and mult_n().
Referenced by division_in_place(), division_in_place_monic(), gcd_coefficients(), DRing::mult(), mult_by_coeff_n(), mult_n(), power_mod(), and DRing::subtract_multiple().