Macaulay2 Engine: DPoly::add_in_place_0
add_in_place_0()
void DPoly::add_in_place_0 (TowerPolynomial & f, const TowerPolynomial g) private
Definition at line 669 of file dpoly.cpp.
 {
   int i;
   if (g == 0) return;
   if (f == 0)
     {
       f = copy(0, g);
       return;
     }
   int fdeg = f->deg;
   int gdeg = g->deg;
   increase_size_0(g->deg, f);
   for (i = 0; i <= gdeg; i++)
     ZZp_ADD_TO(charac, f->arr.ints[i], g->arr.ints[i]);
   if (gdeg > fdeg)
     f->deg = gdeg;
   else if (gdeg == fdeg)
     reset_degree_0(f);
 }
References charac, copy(), increase_size_0(), reset_degree_0(), and ZZp_ADD_TO().
Referenced by add_in_place().