Macaulay2 Engine: DPoly::diff_0
diff_0()
TowerPolynomial DPoly::diff_0 (const TowerPolynomial f) private
Definition at line 1318 of file dpoly.cpp.
 {
   if (f == nullptr || f->deg == 0) return nullptr;
   TowerPolynomial result = alloc_poly_0(f->deg - 1);
   for (int i = 1; i <= f->deg; i++)
     {
       long c = f->arr.ints[i];
       if (c != 0)
         {
           ZZp_MULT(charac, c, i);
           result->arr.ints[i - 1] = c;
         }
     }
   reset_degree_0(result);
   return result;
 }
References alloc_poly_0(), charac, reset_degree_0(), and ZZp_MULT().
Referenced by diff().