Macaulay2 Engine: DPoly::reset_degree_0
reset_degree_0()
void DPoly::reset_degree_0 (TowerPolynomial & f) private
Definition at line 623 of file dpoly.cpp.
 {
   int fdeg = f->deg;
   for (int j = fdeg; j >= 0; --j)
     if (f->arr.ints[j] != 0)
       {
         f->deg = j;
         return;
       }
   // at this point, everything is 0!
   dealloc_poly(f);  // sets f to 0
 }
References dealloc_poly().
Referenced by add_in_place_0(), diff_0(), division_in_place(), division_in_place_monic(), mult_by_int_0(), and random_0().