Macaulay2 Engine: DPoly::random_n
random_n()
TowerPolynomial DPoly::random_n (int level, int deg) private
Definition at line 541 of file dpoly.cpp.
 {
   if (deg < 0) deg = 3;  // Take a random element of degree 0.
   TowerPolynomial f = alloc_poly_n(deg);
   for (int i = 0; i <= deg; i++) f->arr.polys[i] = random(level - 1);
   reset_degree_n(level, f);  // possibly modifies f, if it is zero.
   return f;
 }
References alloc_poly_n(), random(), and reset_degree_n().
Referenced by random().