Macaulay2 Engine: DPoly::from_long
from_long()
TowerPolynomial DPoly::from_long (int level, long c) static
Definition at line 501 of file dpoly.cpp.
 {
   if (c == 0) return 0;
   TowerPolynomial result = alloc_poly_0(0);
   result->arr.ints[0] = c;
   for (int i = 1; i <= level; i++)
     {
       TowerPolynomial a = result;
       result = alloc_poly_n(0);
       result->arr.polys[0] = a;
     }
   return result;
 }
References alloc_poly_0(), and alloc_poly_n().
Referenced by gcd_coefficients(), power_mod(), DRing::set_from_int(), DRing::set_from_long(), and DRing::set_from_mpq().