Macaulay2 Engine: DPoly::degree_of_extension
degree_of_extension()
int DPoly::degree_of_extension (int level)
Definition at line 100 of file dpoly.cpp.
 {
   // if negative, then that variable is transcendental over lower vars
   if (level < 0 || level >= nlevels) return -1;
   TowerPolynomial f = extensions[level];
   if (f == nullptr) return -1;
   return f->deg;
 }
References extensions, and nlevels.
Referenced by DRing::extension_degree(), lowerP(), and random().