Macaulay2 Engine: DPoly::diff_n
diff_n()
TowerPolynomial DPoly::diff_n (int level, int whichvar, const TowerPolynomial f) private
Definition at line 1335 of file dpoly.cpp.
 {
   TowerPolynomial result;
   if (whichvar == 0)
     {
       result = alloc_poly_0(f->deg - 1);
       for (int i = 1; i <= f->deg; i++)
         {
           TowerPolynomial c = f->arr.polys[i];
           if (c != 0) result->arr.polys[i - 1] = mult_by_int(level - 1, i, c);
         }
     }
   else
     {
       result = alloc_poly_0(f->deg);
       for (int i = 0; i <= f->deg; i++)
         {
           TowerPolynomial c = f->arr.polys[i];
           if (c != 0) result->arr.polys[i] = diff(level - 1, whichvar - 1, c);
         }
     }
   reset_degree_n(level, result);
   return result;
 }
References alloc_poly_0(), diff(), mult_by_int(), and reset_degree_n().
Referenced by diff().