Macaulay2 Engine: DPoly::subtract_in_place_n
subtract_in_place_n()
void DPoly::subtract_in_place_n (int level, TowerPolynomial & f, const TowerPolynomial g) private
Definition at line 761 of file dpoly.cpp.
 {
   int i;
   if (g == nullptr) return;
   if (f == nullptr)
     {
       f = copy(level, g);
       negate_in_place(level, f);
       return;
     }
   int fdeg = f->deg;
   int gdeg = g->deg;
   increase_size_n(g->deg, f);
   for (i = 0; i <= gdeg; i++)
     subtract_in_place(level - 1, f->arr.polys[i], g->arr.polys[i]);
   if (gdeg > fdeg)
     f->deg = gdeg;
   else if (gdeg == fdeg)
     {
       // need to change the degree
       for (int j = fdeg; j >= 0; --j)
         if (f->arr.polys[j] != nullptr)
           {
             f->deg = j;
             return;
           }
       // at this point, everything is 0!
       dealloc_poly(f);
     }
 }
References copy(), dealloc_poly(), increase_size_n(), negate_in_place(), and subtract_in_place().
Referenced by subtract_in_place().