Macaulay2 Engine: DPoly::reset_degree_n
reset_degree_n()
void DPoly::reset_degree_n (int level, TowerPolynomial & f) private
Definition at line 635 of file dpoly.cpp.
 {
   int fdeg = f->deg;
   for (int j = fdeg; j >= 0; --j)
     if (f->arr.polys[j] != nullptr)
       {
         f->deg = j;
         return;
       }
   // at this point, everything is 0!
   dealloc_poly(f);  // sets f to 0
 }
References dealloc_poly().
Referenced by diff_n(), division_in_place(), division_in_place_monic(), mult_by_int_n(), and random_n().