Macaulay2 Engine: DPoly::mult_n
mult_n()
TowerPolynomial DPoly::mult_n (int level, const TowerPolynomial f, const TowerPolynomial g, bool reduce_by_extension) private
Definition at line 817 of file dpoly.cpp.
 {
   if (f == nullptr || g == nullptr) return nullptr;
   TowerPolynomial result = alloc_poly_n(f->deg + g->deg);
   for (int i = 0; i <= f->deg; i++)
     {
       TowerPolynomial a = f->arr.polys[i];
       if (a != nullptr)
         for (int j = 0; j <= g->deg; j++)
           {
             TowerPolynomial b = g->arr.polys[j];
             TowerPolynomial c = mult(level - 1, a, b, true);
             if (c != nullptr)
               {
                 add_in_place(level - 1, result->arr.polys[i + j], c);
                 dealloc_poly(c);
               }
           }
     }
   if (reduce_by_extension && extensions[level] != nullptr)
     remainder(level, result, extensions[level]);
   return result;
 }
References add_in_place(), alloc_poly_n(), dealloc_poly(), extensions, mult(), and remainder().
Referenced by mult().