Macaulay2 Engine: DPoly::read_poly_0
read_poly_0()
TowerPolynomial DPoly::read_poly_0 (char *& str) static private
Definition at line 341 of file dpoly.cpp.
 {
   int len = 0;
   long *elems = newarray_atomic(long, 100);
   long this_elem = 0;
   if (*str != '[')
     {
       fprintf(stderr, "expected '[', got %s\n", str);
       exit(1);
     }
   str++;
   // Now loop
   while (*str != ']')
     {
       while (isspace(*str)) str++;
       if (*str == ',')
         {
           str++;
         }
       else if (isdigit(*str))
         {
           char *end;
           this_elem = strtol(str, &end, 10);
           str = end;
           while (isspace(*str)) str++;
           if (*str == ',') str++;
         }
       else
         {
           fprintf(stderr, "expected , or [, but got %s\n", str);
           exit(1);
         }
       elems[len++] = this_elem;
       this_elem = 0;
     }
   // the only way to get here is if *str == ']'.  Eat that char.
   str++;
   TowerPolynomial result = DPoly::alloc_poly_0(len - 1, elems);
   freemem(elems);
   return result;
 }
References alloc_poly_0(), end(), freemem(), and newarray_atomic.
Referenced by read_poly().