Macaulay2 Engine: DPoly::make_monic3
make_monic3()
bool DPoly::make_monic3 (int level, TowerPolynomial & u1, TowerPolynomial & u2, TowerPolynomial & u3) private
Definition at line 937 of file dpoly.cpp.
 {
   if (u3 == 0) return true;
   if (level == 0)
     {
       long c = 0;
       make_monic_0(u3, c);
       if (c == 0) return false;
       mult_by_coeff_0(u1, c);
       mult_by_coeff_0(u2, c);
     }
   else
     {
       TowerPolynomial c = 0;
       make_monic_n(level, u3, c);
       if (c == 0) return false;
       mult_by_coeff_n(level, u1, c);
       mult_by_coeff_n(level, u2, c);
       dealloc_poly(c);
     }
   return true;
 }
References dealloc_poly(), make_monic_0(), make_monic_n(), mult_by_coeff_0(), and mult_by_coeff_n().
Referenced by gcd_coefficients().