Macaulay2 Engine: DPoly::increase_size_0
increase_size_0()
void DPoly::increase_size_0 (int newdeg, TowerPolynomial & f) static
Definition at line 233 of file dpoly.cpp.
 {
   assert(f != 0);
   if (f->len <= newdeg)
     {
       long *newelems = newarray_atomic(long, newdeg + 1);
       long *fp = f->arr.ints;
       for (int i = 0; i <= f->deg; i++) newelems[i] = fp[i];
       for (int i = f->deg + 1; i < newdeg + 1; i++) newelems[i] = 0;
       freemem(fp);
       f->arr.ints = newelems;
       f->len = newdeg + 1;
       f->deg = newdeg;
     }
 }
References freemem(), and newarray_atomic.
Referenced by add_in_place_0(), and subtract_in_place_0().