Macaulay2 Engine: DPoly::division_in_place_monic
division_in_place_monic()
TowerPolynomial DPoly::division_in_place_monic (int level, TowerPolynomial & f, const TowerPolynomial g)
Definition at line 965 of file dpoly.cpp.
 {
   // ASSUMPTION: g is MONIC, non-zero
   if (f == 0) return 0;
   if (f->deg < g->deg)
     {
       return 0;
     }
   int shift = f->deg - g->deg;
   TowerPolynomial quot = alloc_poly_n(shift);
   if (level == 0)
     {
       long *p = f->arr.ints;
       long *q = g->arr.ints;
       for (int d = f->deg; shift >= 0; d--, shift--)
         {
           long a = p[d];
           if (a != 0)
             {
               quot->arr.ints[shift] = a;
               ZZp_NEGATE(charac, a);
               for (int j = 0; j <= g->deg; j++)
                 ZZp_APXY(charac, p[shift + j], a, q[j]);
             }
         }
       reset_degree_0(f);
     }
   else
     {
       TowerPolynomial *p = f->arr.polys;
       TowerPolynomial *q = g->arr.polys;
       for (int d = f->deg; shift >= 0; d--, shift--)
         {
           TowerPolynomial a = p[d];
           if (a != 0)
             {
               quot->arr.polys[shift] = copy(level - 1, a);
               for (int j = 0; j <= g->deg; j++)
                 {
                   TowerPolynomial b = mult(level - 1, a, q[j], true);
                   subtract_in_place(level - 1, p[j + shift], b);
                 }
             }
         }
       reset_degree_n(level, f);
     }
   return quot;
 }
References alloc_poly_n(), charac, copy(), mult(), p, reset_degree_0(), reset_degree_n(), subtract_in_place(), ZZp_APXY(), and ZZp_NEGATE().
Referenced by gcd_coefficients().