Macaulay2 Engine: DPoly::increase_size_n
increase_size_n()
void DPoly::increase_size_n (int newdeg, TowerPolynomial & f) static
Definition at line 249 of file dpoly.cpp.
 {
   assert(f != 0);
   if (f->len <= newdeg)
     {
       TowerPolynomial *newelems = newarray(TowerPolynomial, newdeg + 1);
       TowerPolynomial *fp = f->arr.polys;
       for (int i = 0; i <= f->deg; i++) newelems[i] = fp[i];
       for (int i = f->deg + 1; i < newdeg + 1; i++) newelems[i] = 0;
       freemem(fp);
       f->arr.polys = newelems;
       f->len = newdeg + 1;
       f->deg = newdeg;
     }
 }
References freemem(), and newarray.
Referenced by add_in_place_n(), add_term(), and subtract_in_place_n().