Macaulay2 Engine: VECTOR
VECTOR()
typedef VECTOR (gbelem *)
Referenced by MonomialIdeal::borel(), F4SPairSet::construct_pairs(), Tower::create(), PolynomialRing::create_quotient(), F4MonomialLookupTableT< Key >::debug_check(), ResF4MonomialLookupTableT< Key >::debug_check(), F4MonomialLookupTableT< Key >::debug_out(), ResF4MonomialLookupTableT< Key >::debug_out(), MonomialIdeal::erase(), res2_comp::find_divisor(), GBKernelComputation::find_divisor(), ReducedGB_ZZ::find_divisor(), gbA::find_good_divisor(), ReducedGB_Field_Local::find_good_divisor(), gbA::find_good_monomial_divisor_ZZ(), gbA::find_good_term_divisor_ZZ(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), MonomialTableZZ::find_strong_generators(), MonomialTableZZ::find_weak_generators(), M2::GaloisFieldTable::GaloisFieldTable(), GBDeclared::GBDeclared(), ReducedGB::get_change(), ReducedGB::get_gb(), ReducedGB::get_initial(), gbA::get_mingens(), gbA::get_syzygies(), GF::initialize_GF(), MonomialIdeal::intersect(), iquotient_and_sum(), SchurRing2::is_equal(), Matrix::koszul_monomials(), SLP< Field >::make(), res2_comp::make_minimal(), res_comp::make_minimal(), MonomialTable::make_minimal(), Matrix::make_monideal(), makemonideal(), ReducedGB_Field_Local::minimalize(), ReducedGB_Field::minimalize(), MonomialTable::minimalize(), gbA::minimalize_gb(), GBinhom_comp::minimalize_gb(), gbA::minimalize_pairs_ZZ(), minimalize_res_varpower_monomials(), SchurRing2::mult_by_coefficient(), SchurRing2::negate(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), MonomialIdeal::operator*(), MonomialIdeal::operator+(), MonomialIdeal::quotient(), MonomialIdeal::radical(), rawConvolve(), rawMutableComplex(), rawPruningMorphism(), rawTowerRing3(), F4GB::reorder_rows(), res_comp::skeleton(), res_comp::skeleton_pairs(), GBKernelComputation::strip_gb(), Ring::sub_vector(), F4MonomialLookupTableT< Key >::text_out(), ResF4MonomialLookupTableT< Key >::text_out(), F4MonomialLookupTableT< Key >::~F4MonomialLookupTableT(), and ResF4MonomialLookupTableT< Key >::~ResF4MonomialLookupTableT().