Macaulay2 Engine: M2::ARingCC::invert
invert()
void M2::ARingCC::invert (ElementType & res, const ElementType & a) const inline
Definition at line 180 of file aring-CC.hpp.
   {
     ElementType result;
     if (fabs(a.re) >= fabs(a.im))
       {
         double p = a.im / a.re;
         double denom = a.re + p * a.im;
         result.re = 1.0 / denom;
         result.im = -p / denom;
       }
     else
       {
         double p = a.re / a.im;
         double denom = a.im + p * a.re;
         result.re = p / denom;
         result.im = -1.0 / denom;
       }
     set(res, result);
   }
References mpfr::fabs(), cc_doubles_struct::im, p, cc_doubles_struct::re, and set().
Referenced by power().