Macaulay2 Engine: M2::ARingCC::abs
abs()
void M2::ARingCC::abs (ARingRR::ElementType & result, const ElementType & a) const inline
Definition at line 302 of file aring-CC.hpp.
   {
     result = sqrt(a.re * a.re + a.im * a.im);
   }
References cc_doubles_struct::im, cc_doubles_struct::re, and mpfr::sqrt().
Referenced by almostEqual(), and increase_norm().