Macaulay2 Engine: M2::ARingCC::toBigComplex
toBigComplex()
gmp_CC M2::ARingCC::toBigComplex (const ElementType & a) const inline
Definition at line 383 of file aring-CC.hpp.
   {
     gmp_CCmutable result = getmemstructtype(gmp_CCmutable);
     result->re = getmemstructtype(mpfr_ptr);
     result->im = getmemstructtype(mpfr_ptr);
     mpfr_init2(result->re, get_precision());
     mpfr_init2(result->im, get_precision());
     mpfr_set_d(result->re, a.re, MPFR_RNDN);
     mpfr_set_d(result->im, a.im, MPFR_RNDN);
     return moveTo_gmpCC(result);
   }
References get_precision(), getmemstructtype, cc_doubles_struct::im, moveTo_gmpCC(), and cc_doubles_struct::re.
Referenced by elem_text_out().