Macaulay2 Engine: M2::ARingCC::eval
eval()
void M2::ARingCC::eval (const RingMap * map, ElementType & f, int first_var, ring_elem & result) const inline
Definition at line 376 of file aring-CC.hpp.
   {
     if (!map->get_ring()->from_complex_double(f.re, f.im, result))
       {
         result = map->get_ring()->from_long(0);
         if (not error()) ERROR("cannot coerce CC value to ring type");
       }
   }
References error(), ERROR(), Ring::from_complex_double(), Ring::from_long(), RingMap::get_ring(), cc_doubles_struct::im, and cc_doubles_struct::re.