Macaulay2 Engine: M2::ARingCC::power
power()
void M2::ARingCC::power (ElementType & result, const ElementType & a, int n) const inline
Definition at line 307 of file aring-CC.hpp.
   {
     ElementType curr_pow;
     init(curr_pow);
     set_from_long(result, 1);
     if (n == 0)
       {
       }
     else if (n < 0)
       {
         n = -n;
         invert(curr_pow, a);
       }
     else
       {
         set(curr_pow, a);
       }
     while (n > 0)
       {
         if (n % 2)
           {
             mult(result, result, curr_pow);
           }
         n = n / 2;
         mult(curr_pow, curr_pow, curr_pow);
       }
     clear(curr_pow);
   }
References clear(), init(), invert(), mult(), set(), and set_from_long().
Referenced by power_mpz(), and TEST().