Macaulay2 Engine: M2::ARingCC::subtract_multiple
subtract_multiple()
void M2::ARingCC::subtract_multiple (ElementType & result, const ElementType & a, const ElementType & b) const inline
Definition at line 239 of file aring-CC.hpp.
   {
     // result -= a*b
     ElementType ab;
     mult(ab, a, b);
     subtract(result, result, ab);
   }
References mult(), and subtract().
Referenced by TEST().