Macaulay2 Engine: M2::ARingCC::subtract
subtract()
void M2::ARingCC::subtract (ElementType & res, const ElementType & a, const ElementType & b) const inline
Definition at line 229 of file aring-CC.hpp.
   {
     ElementType result;
     result.re = a.re - b.re;
     result.im = a.im - b.im;
     set(res, result);
   }
References cc_doubles_struct::im, cc_doubles_struct::re, and set().
Referenced by almostEqual(), subtract_multiple(), and TEST().