Macaulay2 Engine: M2::ARingCC::set
set()
void M2::ARingCC::set (ElementType & result, const ElementType & a) const inline
Definition at line 109 of file aring-CC.hpp.
 { result = a; }
Referenced by add(), addMultipleTo(), copy(), divide(), invert(), M2::mylift(), M2::mypromote(), power(), subtract(), and syzygy().