Macaulay2 Engine: int_bag::basis_ptr
basis_ptr()
void* int_bag::basis_ptr () const inline
Definition at line 32 of file int-bag.hpp.
 { return val.b_ptr; }
References val.
Referenced by GB_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GB_comp::gb_reduce(), gb2_comp::gb_reduce(), res_comp::reduce(), res_comp::reduce_gen(), and res_comp::reduce_level_one().