Macaulay2 Engine: int_bag::monom
monom() [1/2]
gc_vector< int > & int_bag::monom () inline
Definition at line 25 of file int-bag.hpp.
{ return mon; }
References mon.
Referenced by MonomialIdeal::alexander_dual(), MinimalPrimes::alg1_grab_prime(), AssociatedPrimes::ass_prime_generator(), MinimalPrimes::ass_prime_generator(), borel1(), MyIdealConsumer::consume(), MonomialIdeal::erase(), MonomialIdeal::insert(), MonomialIdeal::insert1(), MonomialIdeal::intersect(), MonomialIdeal::intersect(), iquotient_and_sum(), Matrix::make_monideal(), makemonideal(), MonomialIdeal::MonomialIdeal(), MonomialIdeal::MonomialIdeal(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), MonomialIdeal::operator*(), partition_table::partition(), MonomialIdeal::quotient(), MonomialIdeal::quotient(), MonomialIdeal::radical(), MonomialIdeal::sat(), res_comp::skeleton_pairs(), and varpower_monideal().