Macaulay2 Engine: int_bag::monom
monom() [1/2]
gc_vector<int>& int_bag::monom () inline
Definition at line 25 of file int-bag.hpp.
 { return mon; }
References mon.
Referenced by MonomialIdeal::alexander_dual(), MinimalPrimes::alg1_grab_prime(), AssociatedPrimes::ass_prime_generator(), MinimalPrimes::ass_prime_generator(), MonomialIdeal::borel(), borel1(), MonomialIdeal::computeHashValue(), MyIdealConsumer::consume(), MonomialIdeal::erase(), MonomialIdeal::insert(), MonomialIdeal::insert1(), MonomialIdeal::intersect(), iquotient_and_sum(), MonomialIdeal::is_borel(), MonomialIdeal::lcm(), Matrix::make_monideal(), makemonideal(), MonomialIdeal::MonomialIdeal(), MonomialIdeal::n_pure_powers(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), MonomialIdeal::operator*(), MonomialIdeal::operator-(), partition_table::partition(), MonomialIdeal::quotient(), MonomialIdeal::radical(), MonomialIdeal::sat(), res_comp::skeleton_pairs(), MonomialIdeal::text_out(), and varpower_monideal().