Macaulay2 Engine: dRRR
dRRR()
void dRRR (gmp_RR a)
Definition at line 145 of file debug.cpp.
 {
   buffer o;
   o << M2_tocharstar((*gmp_tostringRRpointer)(a)) << newline;
   emit(o.str());
 }
References emit(), gmp_tostringRRpointer, M2_tocharstar(), newline, and buffer::str().