Macaulay2 Engine: drelem
drelem()
void drelem (const RingElement * f)
Definition at line 39 of file debug.cpp.
 {
   buffer o;
   f->text_out(o);
   emit(o.str());
 }
References emit(), buffer::str(), and RingElement::text_out().
Referenced by LocalRing::lift_up().