Macaulay2 Engine: dvec
dvec()
void dvec (const Ring * R, const vec v)
Definition at line 88 of file debug.cpp.
 {
   buffer o;
   R->vec_text_out(o, v);
   emit_line(o.str());
 }
References emit_line(), buffer::str(), and Ring::vec_text_out().
Referenced by ConcreteVectorArithmetic< RingType, ElementArrayType >::denseCancelFromSparse(), ConcreteVectorArithmetic< RingType, ElementArrayType >::denseNextNonzero(), ConcreteVectorArithmetic< RingType, ElementArrayType >::denseToSparse(), ConcreteVectorArithmetic< RingType, ElementArrayType >::fillDenseArray(), ConcreteVectorArithmetic< RingType, ElementArrayType >::safeDenseToSparse(), and ConcreteVectorArithmetic< RingType, ElementArrayType >::setZeroInRange().