Macaulay2 Engine: MatrixStream::appendPolynomialDone
appendPolynomialDone()
void MatrixStream::appendPolynomialDone ()
Definition at line 60 of file matrix-stream.cpp.
 {
   // Time to append a polynomial
   //  ring().sort(mCurrentPoly);  // This is just in case the elements come in
   //  out of order
   vec v = ring().make_vec_from_array(mFreeModule->rank(), mCurrentColumn);
   mMatrixConstructor.append(v);
   for (int i = 0; i < mFreeModule->rank(); i++)
     {
       mCurrentColumn[i] = nullptr;
       mLastTerms[i] = nullptr;
     }
 }
References MatrixConstructor::append(), Ring::make_vec_from_array(), mCurrentColumn, mFreeModule, mLastTerms, mMatrixConstructor, FreeModule::rank(), and ring().