Macaulay2 Engine: MatrixStream::MatrixStream
MatrixStream()
MatrixStream::MatrixStream (const FreeModule * F)
Definition at line 3 of file matrix-stream.cpp.
     : mFreeModule(F), mMatrixConstructor(F, 0), mValue(nullptr), mCurrentComponent(0)
 {
   mPolyRing = F->get_ring()->cast_to_PolyRing();
   assert(mPolyRing != 0);
   mCurrentExponents = newarray_clear(Exponent, mPolyRing->n_vars());
   mCurrentColumn = newarray_clear(Nterm*, F->rank());
   mLastTerms = newarray_clear(Nterm*, F->rank());
 }
References Ring::cast_to_PolyRing(), FreeModule::get_ring(), mCurrentColumn, mCurrentExponents, mLastTerms, mPolyRing, PolynomialRing::n_vars(), newarray_clear, and FreeModule::rank().