Macaulay2 Engine: MatrixStream::appendTermDone
appendTermDone()
void MatrixStream::appendTermDone (Coefficient coefficient)
Definition at line 41 of file matrix-stream.cpp.
 {
   // Now we need to create an Nterm, and attach it at mCurrentComponent
   Nterm* t = ring().new_term();
   ring().getMonoid()->from_expvector(mCurrentExponents, t->monom);
   t->coeff = ring().getCoefficients()->from_long(coefficient);
   t->next = nullptr;
   if (mLastTerms[mCurrentComponent] == nullptr)
     {
       mCurrentColumn[mCurrentComponent] = t;
       mLastTerms[mCurrentComponent] = t;
     }
   else
     {
       mLastTerms[mCurrentComponent]->next = t;
       mLastTerms[mCurrentComponent] = t;
     }
   for (size_t i = 0; i < ring().n_vars(); i++) mCurrentExponents[i] = 0;
 }
References Nterm::coeff, Monoid::from_expvector(), Ring::from_long(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), mCurrentColumn, mCurrentComponent, mCurrentExponents, mLastTerms, Nterm::monom, PolynomialRing::n_vars(), PolyRing::new_term(), Nterm::next, and ring().