Macaulay2 Engine: TEST
TEST() [2/3]
TEST (ARingGFFlint , create)
Definition at line 62 of file ARingGFTest.cpp.
 {
   M2::ARingGFFlint R(5, 3);
   EXPECT_EQ(ringName(R), "GF(5,3,Flint)");
   EXPECT_EQ(R.cardinality(), 125);
   EXPECT_EQ(R.characteristic(), 5);
   M2_arrayint gen_modpoly = R.getModPolynomialCoeffs();
   std::cout << "minimal polynomial = ";
   dintarray(gen_modpoly);
   std::cout << std::endl;
   M2_arrayint gen_coeffs = R.getGeneratorCoeffs();
   std::cout << "generator polynomial = ";
   dintarray(gen_coeffs);
   std::cout << std::endl;
   // Check what values integers go to
   M2::ARingGFFlint::ElementType a;
   R.init(a);
   //    for (int i=-5; i<R.characteristic(); i++)
   for (int i = -130; i < 130; i++)
     {
       R.set_from_long(a, i);
       M2_arrayint coeffs = R.fieldElementToM2Array(a);
       EXPECT_EQ(coeffs->len, 3);
       int imodp = i % 5;
       if (imodp < 0) imodp += 5;
       EXPECT_EQ(coeffs->array[0], imodp);
       for (int j = 1; j < 3; j++) EXPECT_EQ(coeffs->array[j], 0);
       //        std::cout << i << " = ";
       //        dintarray(coeffs);
       //        std::cout << std::endl;
     }
   R.clear(a);
   testSomeMore(R);
 }
References M2::ARingGFFlint::characteristic(), M2::ARingGFFlint::clear(), dintarray(), M2::ARingGFFlint::init(), ringName(), M2::ARingGFFlint::set_from_long(), and testSomeMore().