Macaulay2 Engine: TEST
TEST() [3/3]
TEST (ARingGFFlint , random)
Definition at line 102 of file ARingGFTest.cpp.
 {
   M2::ARingGFFlint R(7, 2);
   M2::ARingGFFlint::ElementType a;
   R.init(a);
   int counts[49];
   for (int i = 0; i < 49; i++) counts[i] = 0;
   for (int i = 0; i < 49 * 200; i++)
     {
       R.random(a);
       EXPECT_TRUE(a >= 0);
       EXPECT_TRUE(a < 49);
       counts[a]++;
     }
 #if 0
     double sum = 0;
     for (int i=0; i<49; i++)
       {
         std::cout << i << "  " << counts[i] << std::endl;
         sum += (counts[i]-200)^2;
       }
     sum /= (49*200);
     std::cout << "chi = " << sum << std::endl;
     for (int i=0; i<49; i++)
       {
         a = i;
         M2_arrayint f = R.fieldElementToM2Array(a);
         dintarray(f);
         std::cout << std::endl;
       }
 #endif
   R.clear(a);
 }
References M2::ARingGFFlint::clear(), dintarray(), M2::ARingGFFlint::init(), M2::ARingGFFlint::random(), and mpfr::sum().