Macaulay2 Engine: getElement< M2::ARingGFFlint >
getElement< M2::ARingGFFlint >()
template<> void getElement< M2::ARingGFFlint > (const M2::ARingGFFlint & R, int index, M2::ARingGFGivaro::ElementType & result)
Definition at line 48 of file ARingGFTest.cpp.
 {
   M2::ARingGFFlint::ElementType gen;
   R.init(gen);
   R.getGenerator(gen);
   if (index >= nelements)
     R.power(result, gen, rawRandomInt(static_cast<int32_t>(R.cardinality())));
   else
     R.power(result, gen, randomVals[index]);
   R.clear(gen);
 }
References M2::ARingGFFlint::clear(), M2::ARingGFFlint::getGenerator(), M2::ARingGFFlint::init(), nelements, M2::ARingGFFlint::power(), randomVals, and rawRandomInt().