Macaulay2 Engine: WordWithDataTable::isPrefixOf
isPrefixOf()
bool WordWithDataTable::isPrefixOf (WordWithData word1, WordWithData word2) static private
Definition at line 344 of file WordTable.cpp.
 {
   if (word2.size() < word1.size()) return false;
   bool match = true;
   for (auto k = 0; k < word1.size(); ++k)
     if (word1.begin()[k] != word2.begin()[k])
       {
         match = false;
         break;
       }
   return match;
 }
References WordWithData::begin(), and WordWithData::size().
Referenced by isPrefix().