Macaulay2 Engine: WordWithDataTable::overlaps
overlaps()
void WordWithDataTable::overlaps (WordWithData word1, WordWithData word2, std::vector< int > & result_overlaps) static private
Definition at line 477 of file WordTable.cpp.
 {
   if (word1.size() <= 1) return;
   for (int i = word1.size() - 1; i > 0 and i + word2.size() > word1.size(); --i)
     {
       // below, we are disregarding ecart degree for overlap detection/generation
       Word suffix(word1.begin() + i, word1.end());
       Word prefix(word2.begin(), word2.begin() + word1.size() - i); // indices should be in range.
       if (suffix == prefix)
         result_overlaps.push_back(i);
     }
 }
References WordWithData::begin(), WordWithData::end(), prefix(), WordWithData::size(), and suffix().
Referenced by leftOverlaps().