Macaulay2 Engine: WordWithDataTable::subwordPositions
subwordPositions()
void WordWithDataTable::subwordPositions (WordWithData word1, WordWithData word2, std::vector< int > & result_start_indices) static private
Definition at line 294 of file WordTable.cpp.
 {
   if (word2.size() < word1.size()) return;
   if (word2.ecartDegree() < word1.ecartDegree()) return;
   for (auto j = 0; j <= word2.size() - word1.size(); ++j)
     {
       bool match = true;
       for (auto k = 0; k < word1.size(); ++k)
         if (word1.begin()[k] != word2.begin()[j+k])
           {
             match = false;
             break;
           }
       if (match) result_start_indices.push_back(j);
     }
 }
References WordWithData::begin(), WordWithData::ecartDegree(), and WordWithData::size().
Referenced by subwords(), and superwords().