Macaulay2 Engine: WordWithDataTable::isSuffixOf
isSuffixOf()
bool WordWithDataTable::isSuffixOf (WordWithData word1, WordWithData word2) static private
Definition at line 358 of file WordTable.cpp.
{
  auto word1size = word1.size();
  auto word2size = word2.size();
  if (word2size < word1size) return false;
  // at this point if word2.size() == 0, then word2 (and hence word1) are both empty
  if (word2size == 0) return false;
  bool match = true;
  for (auto k = 0; k < word1size; ++k)
    if (word1.begin()[word1size-1-k] != word2.begin()[word2size-1-k])
      {
        match = false;
        break;
      }
  return match;
}
References WordWithData::begin(), and WordWithData::size().
Referenced by isSuffix().