Macaulay2 Engine: WordWithDataTable::subwordPosition
subwordPosition()
bool WordWithDataTable::subwordPosition (WordWithData word1, WordWithData word2, int & result_start_index) static private
Definition at line 316 of file WordTable.cpp.
 {
   if (word2.size() < word1.size()) return false;
   if (word2.ecartDegree() < word1.ecartDegree()) return false;
   for (auto j = 0; j <= word2.size() - word1.size(); ++j)
     {
       bool match = true;
       for (auto k = 0; k < word1.size(); ++k)
         if (word1.begin()[k] != word2.begin()[j+k])
           {
             match = false;
             break;
           }
       if (match)
         {
           result_start_index = j;
           return true;
         }
     }
   return false;
 }
References WordWithData::begin(), WordWithData::ecartDegree(), and WordWithData::size().
Referenced by subword().