Macaulay2 Engine: WeylAlgebra::power
power() [2/2]
ring_elem WeylAlgebra::power (const ring_elem f, mpz_srcptr n) const virtual
Reimplemented from PolyRing.
Definition at line 597 of file weylalg.cpp.
{
  std::pair<bool, int> n1 = RingZZ::get_si(n);
  if (n1.first)
    return power(f, n1.second);
  else
    throw exc::engine_error("exponent too large");
}
References RingZZ::get_si(), and power().
Referenced by power().