Macaulay2 Engine: WeylAlgebra::diff_coefficients
diff_coefficients()
ring_elem WeylAlgebra::diff_coefficients (const ring_elem c, const int * derivatives, const_exponents exp) const protected
Definition at line 307 of file weylalg.cpp.
 {
   ring_elem result = K_->copy(c);
   for (int i = 0; i < _nderivatives; i++)
     {
       if (derivatives[i] == 0) continue;
       if (exp[i] <= diffcoeffstop)
         {
           ring_elem g =
               K_->from_long(diffcoeffstable[exp[i]][derivatives[i]]);
           ring_elem h = K_->mult(result, g);
           K_->remove(g);
           K_->remove(result);
           result = h;
           if (K_->is_zero(result)) return result;
         }
       else
         for (int j = derivatives[i] - 1; j >= 0; j--)
           {
             ring_elem g = K_->from_long(exp[i] - j);
             ring_elem h = K_->mult(result, g);
             K_->remove(g);
             K_->remove(result);
             result = h;
             if (K_->is_zero(result)) return result;
           }
     }
   return result;
 }
References _nderivatives, Ring::copy(), diffcoeffstable, diffcoeffstop, mpfr::exp(), Ring::from_long(), Ring::is_zero(), PolynomialRing::K_, Ring::mult(), and Ring::remove().