Macaulay2 Engine: WeylAlgebra::multinomial
multinomial() [2/2]
ring_elem WeylAlgebra::multinomial (const ring_elem a, const int * exptop, const int * expbottom) const protected
Definition at line 247 of file weylalg.cpp.
 {
   // Assumed: top[i] >= bottom[i] for all i.
   ring_elem result = K_->copy(c);
   for (int i = 0; i < _nderivatives; i++)
     if (bottom[i] > 0)
       {
         ring_elem a = binomial(top[i], bottom[i]);
         ring_elem b = K_->mult(a, result);
         K_->remove(a);
         K_->remove(result);
         result = b;
       }
   return result;
 }
References _nderivatives, binomial(), Ring::copy(), PolynomialRing::K_, Ring::mult(), and Ring::remove().