Macaulay2 Engine: WeylAlgebra::multinomial
multinomial() [2/2]
ring_elem WeylAlgebra::multinomial (const_exponents exptop, const_exponents exp) const
Definition at line 576 of file weylalg.cpp.
 {
   ring_elem result = K_->from_long(1);
   for (int i = 0; i < nvars_; i++)
     if (exptop[i] > 0)
       {
         for (int j = exptop[i]; j > exp[i]; j--)
           {
             ring_elem c = K_->from_long(j);
             ring_elem d = K_->from_long(exptop[i] - j + 1);
             K_->mult_to(result, c);
             ring_elem e = K_->divide(result, d);  // exact
             K_->remove(c);
             K_->remove(d);
             K_->remove(result);
             result = e;
           }
       }
   return result;
 }
References Ring::divide(), mpfr::exp(), Ring::from_long(), PolynomialRing::K_, Ring::mult_to(), PolynomialRing::nvars_, and Ring::remove().