Macaulay2 Engine: WeylAlgebra::gbvector_mult_by_term
gbvector_mult_by_term()
gbvector * WeylAlgebra::gbvector_mult_by_term (gbvectorHeap & result, const gbvector * f, const ring_elem c, const_monomial m, int comp) const
Definition at line 541 of file weylalg.cpp.
 {
   int *top_derivative = newarray_atomic(int, _nderivatives);
   int *current_derivative = newarray_atomic_clear(int, _nderivatives);
   exponents_t expf = newarray_atomic(int, nvars_);
   GBRing *GR = result.get_gb_ring();
   const FreeModule *F = result.get_freemodule();
   M_->to_expvector(m, expf);
   extractDerivativePart(expf, top_derivative);
   // Loop over each current_derivative <= top_derivative.
   do
     {
       ring_elem d =
           multinomial(c, top_derivative, current_derivative);  // in K_
       gbvector *h =
           gbvector_weyl_diff(GR, d, comp, expf, current_derivative, F, f);
       K_->remove(d);
       result.add(h);
     }
   while (increment(current_derivative, top_derivative));
   freemem(expf);
   freemem(top_derivative);
   freemem(current_derivative);
   return result.value();
 }
References freemem(), newarray_atomic, and newarray_atomic_clear.
Referenced by GBRingWeyl::mult_by_term1(), and GBRingWeylZZ::mult_by_term1().