Macaulay2 Engine: WeylAlgebra::initialize_weyl
initialize_weyl()
bool WeylAlgebra::initialize_weyl (M2_arrayint derivs, M2_arrayint comms, int homog_var) private
Definition at line 10 of file weylalg.cpp.
 {
   if (homog_var >= nvars_)
     {
       ERROR("Weyl algebra homogenizing variable out of range");
       return false;
     }
   if (homog_var < 0) _homog_var = -1;
   if (derivs->len != comms->len)
     {
       ERROR("Weyl algebra: expected arrays of the same length");
       return false;
     }
   for (unsigned int i = 0; i < derivs->len; i++)
     {
       if (derivs->array[i] < 0 || derivs->array[i] >= nvars_)
         {
           ERROR("Weyl algebra: variable out of range");
           return false;
         }
       if (comms->array[i] < 0 || comms->array[i] >= nvars_)
         {
           ERROR("Weyl algebra: variable out of range");
           return false;
         }
     }
   this->_nderivatives = derivs->len;
   this->_homogeneous_weyl_algebra = (homog_var >= 0);
   this->_homog_var = homog_var;
   this->_derivative = newarray_atomic(int, _nderivatives);
   this->_commutative = newarray_atomic(int, _nderivatives);
   for (int i = 0; i < _nderivatives; i++)
     {
       this->_derivative[i] = derivs->array[i];
       this->_commutative[i] = comms->array[i];
     }
   // Now set whether this ring is graded.  This will be the case iff
   // deg(x_i) + deg(D_i) = 2 deg(h), for every i.
   if (_homog_var < 0)
     {
       bool isgraded = true;
       const Monoid *D = degree_monoid();
       monomial degxD = D->make_one();
       for (int j = 0; j < _nderivatives; j++)
         {
           const_monomial degx = M_->degree_of_var(_commutative[j]);
           const_monomial degD = M_->degree_of_var(_derivative[j]);
           D->mult(degx, degD, degxD);
           if (not D->is_one(degxD))
             {
               isgraded = false;
               break;
             }
         }
       this->setIsGraded(isgraded);
     }
   else
     {
       this->setIsGraded(true);
       const Monoid *D = degree_monoid();
       const_monomial degh = M_->degree_of_var(_homog_var);
       monomial deg2h = D->make_one();
       monomial degxD = D->make_one();
       D->mult(degh, degh, deg2h);
       for (int j = 0; j < _nderivatives; j++)
         {
           const_monomial degx = M_->degree_of_var(_commutative[j]);
           const_monomial degD = M_->degree_of_var(_derivative[j]);
           D->mult(degx, degD, degxD);
           if (D->compare(deg2h, degxD) != EQ)
             {
               ERROR("Weyl algebra: failed to create homogeneous Weyl algebra");
               return false;
             }
         }
     }
   // Now initialize the tables
   initialize1();
   return true;
 }
References _commutative, _derivative, _homog_var, _homogeneous_weyl_algebra, _nderivatives, Monoid::compare(), Ring::degree_monoid(), Monoid::degree_of_var(), EQ, ERROR(), initialize1(), Monoid::is_one(), PolynomialRing::M_, Monoid::make_one(), Monoid::mult(), newarray_atomic, PolynomialRing::nvars_, and PolynomialRing::setIsGraded().
Referenced by create().