Macaulay2 Engine: WeylAlgebra::create
create()
WeylAlgebra * WeylAlgebra::create (const Ring * K, const Monoid * M, M2_arrayint derivs, M2_arrayint comms, int homog_var) static
Definition at line 99 of file weylalg.cpp.
 {
   WeylAlgebra *result = new WeylAlgebra;
   result->initialize_poly_ring(K, M);
   if (!result->initialize_weyl(derivs, comms, homog_var)) return 0;
 #ifdef DEVELOPMENT
 #warning "hack for ZZ and QQ coeffs in Weyl algebra: clean it up?"
 #endif
   WeylAlgebra *weyl = result;
   if (K->is_QQ())
     {
       weyl = WeylAlgebra::create(globalZZ, M, derivs, comms, homog_var);
     }
   result->gb_ring_ = GBRing::create_WeylAlgebra(K, M, weyl);
   return result;
 }
References GBRing::create_WeylAlgebra(), PolynomialRing::gb_ring_, globalZZ, PolyRing::initialize_poly_ring(), initialize_weyl(), Ring::is_QQ(), and WeylAlgebra().
Referenced by IM2_Ring_weyl_algebra().