Macaulay2 Engine: WeylAlgebra::mult_by_term
mult_by_term()
ring_elem WeylAlgebra::mult_by_term (const ring_elem f, const ring_elem c, const_monomial m) const virtual
Reimplemented from PolyRing.
Definition at line 420 of file weylalg.cpp.
 {
   int *top_derivative = newarray_atomic(int, _nderivatives);
   int *current_derivative = newarray_atomic_clear(int, _nderivatives);
   exponents_t expf = newarray_atomic(int, nvars_);
   polyheap result(this);
   M_->to_expvector(m, expf);
   extractDerivativePart(expf, top_derivative);
   // Loop over each current_derivative <= top_derivative.
   do
     {
       ring_elem d = multinomial(c, top_derivative, current_derivative);
       Nterm *h = weyl_diff(d, expf, current_derivative, f);
       K_->remove(d);
       result.add(h);
     }
   while (increment(current_derivative, top_derivative));
   freemem(expf);
   freemem(top_derivative);
   freemem(current_derivative);
   return result.value();
 }
References polyheap::add(), freemem(), newarray_atomic, newarray_atomic_clear, and polyheap::value().