Macaulay2 Engine: WeylAlgebra::binomial
binomial()
ring_elem WeylAlgebra::binomial (int top, int bottom) const protected
Definition at line 227 of file weylalg.cpp.
 {
   // This should be located elsewhere
   // Assumption: bottom <= top, top >= 0, bottom >= 0.
   if (bottom == 0) return K_->from_long(1);
   if (bottom == 1) return K_->from_long(top);
   if (top <= binomtop) return K_->from_long(binomtable[top][bottom]);
   ring_elem result = K_->from_long(1);
   for (int a = 0; a < bottom; a++)
     {
       ring_elem b = K_->from_long(top - a);
       ring_elem result1 = K_->mult(result, b);
       K_->remove(result);
       K_->remove(b);
       ring_elem c = K_->from_long(a + 1);
       result = K_->divide(result1, c);  // exact
       K_->remove(c);
     }
   return result;
 }
References binomtable, binomtop, Ring::divide(), Ring::from_long(), PolynomialRing::K_, Ring::mult(), and Ring::remove().