Macaulay2 Engine: varpower::copy
copy()
int * varpower::copy (const int * vp, intarray & result) static
Definition at line 152 of file varpower.cpp.
 {
   return result.copy(*vp, vp);
 }
References intarray::copy().
Referenced by find_pivot(), iquotient_and_sum(), and Monomial::Monomial().