Macaulay2 Engine: varpower::is_equal
is_equal()
bool varpower::is_equal (const int * a, const int * b) static
Definition at line 97 of file varpower.cpp.
 {
   if (*a != *b++) return false;
   int len = *a++;
   for (int i = 1; i < len; i++)
     if (*a++ != *b++) return false;
   return true;
 }
Referenced by EngineMonomial::is_equal(), MonomialIdeal::is_equal(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), and res_comp::skeleton_pairs().