Macaulay2 Engine: varpower::divides
divides()
bool varpower::divides (const int * a, const int * b) static
Definition at line 302 of file varpower.cpp.
 {
   index_varpower i = a;
   index_varpower j = b;
   int va = (i.valid() ? i.var() : -1);
   int vb = (j.valid() ? j.var() : -1);
   for (;;)
     {
       if (va > vb)
         {
           ++i;
           va = (i.valid() ? i.var() : -1);
         }
       else if (va < vb)
         return false;
       else
         {
           if (va == -1) return true;
           int ea = i.exponent();
           int eb = j.exponent();
           if (ea < eb) return false;
           ++i;
           ++j;
           va = (i.valid() ? i.var() : -1);
           vb = (j.valid() ? j.var() : -1);
         }
     }
 }
References index_varpower::exponent(), index_varpower::valid(), and index_varpower::var().
Referenced by iquotient_and_sum().