Macaulay2 Engine: varpower::elem_text_out
elem_text_out() [1/2]
void varpower::elem_text_out (buffer & o, const int * a, bool p_one = true) static
Definition at line 41 of file varpower.cpp.
 {
   index_varpower i = a;
   if (!i.valid())
     {
       if (p_one) o << "1";
     }
   else
     for (; i.valid(); ++i)
       {
         int v = i.var();
         int e = i.exponent();
         if (v < 26)
           o << char('a' + v);
         else if (v < 52)
           o << char('A' + v - 26);
         else
           o << "x[" << v << "]";
         if (e > 1)
           o << e;
         else if (e < 0)
           o << "^(" << e << ")";
       }
 }
References index_varpower::exponent(), index_varpower::valid(), and index_varpower::var().
Referenced by MonomialIdeal::do_node(), and Monomial::text_out().