Macaulay2 Engine: varpower::mult
mult()
void varpower::mult (const int * a, const int * b, intarray & result) static
Definition at line 193 of file varpower.cpp.
 {
   int len = *a + *b;  // potential length
   int *result_vp = result.alloc(len);
   int *orig_result_vp = result_vp;
   result_vp++;
   index_varpower i = a;
   index_varpower j = b;
   // merge the two varpowers to staticVP
   int va = (i.valid() ? i.var() : -1);
   int vb = (j.valid() ? j.var() : -1);
   for (;;)
     {
       if (va > vb)
         {
           *result_vp++ = va;
           *result_vp++ = i.exponent();
           ++i;
           va = (i.valid() ? i.var() : -1);
         }
       else if (vb > va)
         {
           *result_vp++ = vb;
           *result_vp++ = j.exponent();
           ++j;
           vb = (j.valid() ? j.var() : -1);
         }
       else
         {
           if (va == -1) break;
           int z = safe::add(i.exponent(), j.exponent());
           if (z != 0)
             {
               *result_vp++ = va;
               *result_vp++ = z;
             }
           ++i;
           ++j;
           va = (i.valid() ? i.var() : -1);
           vb = (j.valid() ? j.var() : -1);
         }
     }
   int newlen = static_cast<int>(result_vp - orig_result_vp);
   *orig_result_vp = newlen;
   result.shrink(newlen);
 }
References safe::add(), intarray::alloc(), index_varpower::exponent(), intarray::shrink(), index_varpower::valid(), and index_varpower::var().
Referenced by Monomial::operator*(), and MonomialIdeal::operator*().