Macaulay2 Engine: varpower::from_expvector
from_expvector()
void varpower::from_expvector (int n, const_exponents a, intarray & result) static
Definition at line 168 of file varpower.cpp.
 {
   int len = 0;
   for (int i = 0; i < n; i++)
     if (a[i] != 0) len++;
   int result_len = 2 * len + 1;
   int *result_vp = result.alloc(result_len);
   *result_vp++ = result_len;
   for (int i = n - 1; i >= 0; i--)
     if (a[i] != 0)
       {
         *result_vp++ = i;
         *result_vp++ = a[i];
       }
 }
References intarray::alloc().
Referenced by MinimalPrimes::alg1_grab_prime(), AssociatedPrimes::ass_prime_generator(), MinimalPrimes::ass_prime_generator(), borel1(), MyIdealConsumer::consume(), RingElement::lead_monom(), PolyRing::list_form(), binomial_ring::monomial_out(), Monoid::to_varpower(), and TowerEvaluator::viewTerm().