Macaulay2 Engine: varpower::erase
erase()
void varpower::erase (const int * a, const int * b, intarray & result) static
Definition at line 481 of file varpower.cpp.
 {
   int *result_vp = result.alloc(*a);
   int *orig_result_vp = result_vp;
   result_vp++;
   index_varpower i = a;
   index_varpower j = b;
   int va = (i.valid() ? i.var() : -1);
   int vb = (j.valid() ? j.var() : -1);
   for (;;)
     {
       if (va > vb)
         {
           *result_vp++ = va;
           *result_vp++ = i.exponent();
           ++i;
           va = (i.valid() ? i.var() : -1);
         }
       else if (vb > va)
         {
           ++j;
           vb = (j.valid() ? j.var() : -1);
         }
       else
         {
           if (va == -1) break;
           ++i;
           ++j;
           va = (i.valid() ? i.var() : -1);
           vb = (j.valid() ? j.var() : -1);
         }
     }
   *orig_result_vp = static_cast<int>(result_vp - orig_result_vp);
 }
References intarray::alloc(), index_varpower::exponent(), index_varpower::valid(), and index_varpower::var().
Referenced by MonomialIdeal::erase(), and Monomial::erase().