Macaulay2 Engine: varpower::radical
radical()
void varpower::radical (const int * a, intarray & result) static
Definition at line 520 of file varpower.cpp.
 {
   // length of result is the same as that of a
   int *result_vp = result.alloc(*a);
   *result_vp++ = *a;
   for (index_varpower i = a; i.valid(); ++i)
     {
       *result_vp++ = i.var();  // var
       *result_vp++ = 1;        // exponent
     }
 }
References intarray::alloc(), and index_varpower::valid().
Referenced by MonomialIdeal::radical(), and Monomial::radical().