Macaulay2 Engine: varpower::to_ntuple
to_ntuple()
void varpower::to_ntuple (int n, const int * a, int * result_exponents) static
Definition at line 157 of file varpower.cpp.
 {
   int *t = result_exponents;
   for (int j = 0; j < n; j++) t[j] = 0;
   for (index_varpower i = a; i.valid(); ++i)
     {
       int v = i.var();
       int e = i.exponent();
       if (v < n) t[v] = e;
     }
 }
References index_varpower::valid().
Referenced by MonomialIdeal::borel(), FrobbyAlexanderDual(), Monoid::from_varpower(), PolyRing::get_coeff(), IM2_RingElement_term(), MonomialIdeal::is_borel(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), MonomialIdeal::search(), and res_comp::skeleton_pairs().