Macaulay2 Engine: varpower::from_arrayint
from_arrayint()
void varpower::from_arrayint (M2_arrayint m, intarray & result) static
Definition at line 128 of file varpower.cpp.
 {
   int *result_vp = result.alloc(m->len + 1);
   *result_vp++ = m->len + 1;
   int *melems = m->array;
   for (int i = 0; i < m->len; i += 2)
     {
       int v = *melems++;
       int e = *melems++;
       check_var(v, e);
       *result_vp++ = v;
       *result_vp++ = e;
     }
 }
References intarray::alloc(), and check_var().
Referenced by EngineMonomial::EngineMonomial().