Macaulay2 Engine: varpower::computeHashValue
computeHashValue()
unsigned int varpower::computeHashValue (const int * vp) static
Definition at line 11 of file varpower.cpp.
 {
   unsigned int hashval = *vp;
   index_varpower i = vp;
   for (; i.valid(); ++i)
     {
       int v = i.var();
       int e = i.exponent();
       hashval = 4624296 * hashval + 2341 * v + e;
     }
   return hashval;
 }
References index_varpower::exponent(), index_varpower::valid(), and index_varpower::var().
Referenced by MonomialIdeal::computeHashValue().