Macaulay2 Engine: M2::ARingZZ::invert
invert()
void M2::ARingZZ::invert (ElementType & result, const ElementType & a) const inline
Definition at line 125 of file aring-zz-flint.hpp.
   {
     if (is_unit(a))
       set(result, a);
     else
       set_zero(result);
   }
References is_unit(), set(), and set_zero().