Macaulay2 Engine: getElement< RingQQ >
getElement< RingQQ >()
template<> ring_elem getElement< RingQQ > (const RingQQ & R, int index)
Definition at line 12 of file RingQQTest.cpp.
 {
   if (index < 50) return R.from_long(index - 25);
   if (!maxH_initialized)
     {
       maxH_initialized = true;
       mpz_init(maxH);
       mpz_set_str(maxH, "100000000000", 10);
     }
   gmp_QQ a1 = rawRandomQQ(maxH);
   ring_elem result;
   EXPECT_TRUE(R.from_rational(a1, result));
   return result;
 }
References M2::ConcreteRing< RingType >::from_long(), M2::ConcreteRing< RingType >::from_rational(), maxH, maxH_initialized, and rawRandomQQ().