Macaulay2 Engine: ring_elem::get_Poly
get_Poly()
const void* ring_elem::get_Poly () const inline
Definition at line 84 of file ringelem.hpp.
 { return mPolyVal; }
References mPolyVal.
Referenced by M2FreeAlgebra::add(), M2FreeAlgebraQuotient::add(), SumCollectorFreeAlgebraHeap::add(), M2FreeAlgebra::compare_elems(), M2FreeAlgebraQuotient::compare_elems(), copyMatrixToVector(), M2FreeAlgebra::debug_display(), M2FreeAlgebraQuotient::debug_display(), M2FreeAlgebra::elem_text_out(), M2FreeAlgebraQuotient::elem_text_out(), M2FreeAlgebra::eval(), M2FreeAlgebraQuotient::eval(), M2FreeAlgebra::get_terms(), M2FreeAlgebra::index_of_var(), M2FreeAlgebra::is_equal(), M2FreeAlgebraQuotient::is_equal(), M2FreeAlgebra::is_homogeneous(), M2FreeAlgebraQuotient::is_homogeneous(), M2FreeAlgebra::is_unit(), M2FreeAlgebraQuotient::is_unit(), M2FreeAlgebra::lead_coefficient(), M2FreeAlgebraQuotient::lead_coefficient(), M2FreeAlgebra::lift(), M2FreeAlgebraQuotient::lift(), M2FreeAlgebra::list_form(), matrixToPolyList(), M2FreeAlgebra::mult(), M2FreeAlgebraQuotient::mult(), M2FreeAlgebra::multi_degree(), M2FreeAlgebraQuotient::multi_degree(), M2FreeAlgebra::n_terms(), M2FreeAlgebraQuotient::n_terms(), M2FreeAlgebra::negate(), M2FreeAlgebraQuotient::negate(), M2FreeAlgebra::power(), M2FreeAlgebraQuotient::power(), M2FreeAlgebraQuotient::promote(), M2FreeAlgebra::subtract(), M2FreeAlgebraQuotient::subtract(), M2FreeAlgebra::support(), and M2FreeAlgebraOrQuotient::toPoly().