Macaulay2 Engine: ring_elem::get_int
get_int()
int ring_elem::get_int () const inline
Definition at line 80 of file ringelem.hpp.
 { return int_val; }
References int_val.
Referenced by GF::add(), Z_mod::add(), Z_mod::coerceToLongInteger(), Z_mod::compare_elems(), GF::compare_elems(), GF::computeHashValue(), Z_mod::computeHashValue(), GF::discrete_log(), Z_mod::discreteLog(), GF::divide(), Z_mod::divide(), GF::elem_text_out(), Z_mod::elem_text_out(), GF::eval(), Z_mod::eval(), Z_mod::from_rational(), CoefficientRingZZp::from_ring_elem(), M2::ARingGFFlint::from_ring_elem(), M2::ARingGFGivaro::from_ring_elem(), M2::ARingGFM2::from_ring_elem(), M2::ARingZZpFFPACK::from_ring_elem(), M2::ARingZZp::from_ring_elem(), M2::ARingGFFlint::from_ring_elem_const(), M2::ARingGFGivaro::from_ring_elem_const(), M2::ARingGFM2::from_ring_elem_const(), M2::ARingZZpFFPACK::from_ring_elem_const(), M2::ARingZZp::from_ring_elem_const(), GBRing::gbvector_add_to_zzp(), GF::getRepresentation(), GF::invert(), Z_mod::invert(), GF::is_equal(), Z_mod::is_equal(), GF::is_unit(), Z_mod::is_unit(), GF::is_zero(), Z_mod::is_zero(), GF::lift(), Z_mod::lift(), GF::mult(), Z_mod::mult(), GF::negate(), Z_mod::negate(), GF::power(), Z_mod::power(), GF::promote(), GF::subtract(), Z_mod::subtract(), GF::syzygy(), and Z_mod::syzygy().