Macaulay2 Engine: ring_elem::get_mpfi
get_mpfi()
mpfi_srcptr ring_elem::get_mpfi () const inline
Definition at line 87 of file ringelem.hpp.
 { return mpfi_val; }
References mpfi_val.
Referenced by M2::ARingRRi::from_ring_elem(), M2::ARingRRi::from_ring_elem_const(), and IM2_RingElement_to_Interval().