Macaulay2 Engine: ring_elem::get_mpfr
get_mpfr()
mpfr_srcptr ring_elem::get_mpfr () const inline
Definition at line 89 of file ringelem.hpp.
 { return mpfr_val; }
References mpfr_val.
Referenced by almostEqual(), M2::ARingRRR::from_ring_elem(), and IM2_RingElement_to_BigReal().