Macaulay2 Engine: ring_elem::get_mpz
get_mpz()
mpz_srcptr ring_elem::get_mpz () const inline
Definition at line 83 of file ringelem.hpp.
 { return mpz_val; }
References mpz_val.
Referenced by RingZZ::add(), LLLoperations::checkThreshold(), M2::ConcreteRing< RingType >::coerceToLongInteger(), RingZZ::coerceToLongInteger(), RingZZ::compare_elems(), RingZZ::computeHashValue(), RingZZ::copy(), ChineseRemainder::CRA(), RingZZ::divide(), GBRing::divide_coeff_exact_to_ZZ(), RingZZ::elem_text_out(), RingZZ::eval(), ReducedGB_ZZ::find_divisor(), fp_LLL(), M2::RingQQ::fraction(), M2::ARingZZ::from_ring_elem(), M2::ARingZZGMP::from_ring_elem(), M2::ARingZZ::from_ring_elem_const(), M2::ARingZZGMP::from_ring_elem_const(), GBRing::gbvector_combine_lead_terms_ZZ(), GBRing::gbvector_remove_content_ZZ(), GBRing::gbvector_replace_2by2_ZZ(), RingZZ::gcd(), RingZZ::gcd_extended(), getElement< Z_mod >(), IM2_RingElement_to_Integer(), gbA::insert_gb(), RingZZ::is_equal(), RingZZ::is_positive(), RingZZ::is_unit(), RingZZ::is_zero(), LLLoperations::Lovasz(), RingZZ::lower_associate_divisor(), gbA::minimalize_pairs_ZZ(), RingZZ::mult(), mutableMatrix_to_NTL_mat_ZZ(), RingZZ::negate(), ReducedGB_ZZ_sorter::operator()(), RingZZ::power(), RingZZ::preferred_associate(), Z_mod::promote(), M2::ARingQQFlint::promote(), M2::ConcreteRing< RingType >::promote(), QRingInfo_ZZ::QRingInfo_ZZ(), ChineseRemainder::ratConversion(), rawFourierMotzkin(), rawHilbertBasis(), rawSchurDimension(), LLLoperations::REDI(), gbA::remainder_ZZ(), RingZZ::remainderAndQuotient(), gbA::replace_gb_element_ZZ(), RingZZ::subtract(), LLLoperations::SWAPI(), RingZZ::syzygy(), gbA::tail_remainder_ZZ(), and PolyRing::translate_gbvector_from_vec_QQ().