Macaulay2 Engine: ring_elem::get_mpq
get_mpq()
mpq_srcptr ring_elem::get_mpq () const inline
Definition at line 88 of file ringelem.hpp.
 { return mpq_val; }
References mpq_val.
Referenced by M2::ARingQQFlint::from_ring_elem(), M2::ARingQQGMP::from_ring_elem(), M2::ARingQQFlint::from_ring_elem_const(), M2::ARingQQGMP::from_ring_elem_const(), and IM2_RingElement_to_rational().