Macaulay2 Engine: GBWeight::monomial_weight
monomial_weight()
int GBWeight::monomial_weight (const_monomial m, int comp) const
Definition at line 99 of file gbweight.cpp.
 {
   exponents_t EXP = ALLOCATE_EXPONENTS(exp_size);
   R_->get_flattened_monoid()->to_expvector(monom, EXP);
   return exponents_weight(EXP, comp);
 }
References ALLOCATE_EXPONENTS, exp_size, exponents_weight(), GBRing::get_flattened_monoid(), R_, and Monoid::to_expvector().
Referenced by GB_comp::new_ring_pair(), GBinhom_comp::new_ring_pair(), GB_comp::new_s_pair(), and GBinhom_comp::new_s_pair().