Macaulay2 Engine: GBWeight::gbvector_term_weight
gbvector_term_weight()
int GBWeight::gbvector_term_weight (const gbvector * f) const
Definition at line 65 of file gbweight.cpp.
 {
   if (f == nullptr) return 0;
   exponents_t EXP = ALLOCATE_EXPONENTS(exp_size);
   R_->gbvector_get_lead_exponents(F_, f, EXP);
   return exponents_weight(EXP, f->comp);
 }
References ALLOCATE_EXPONENTS, gbvector::comp, exp_size, exponents_weight(), F_, GBRing::gbvector_get_lead_exponents(), and R_.
Referenced by gbA::gbelem_make(), and gbvector_weight().