Macaulay2 Engine: GBWeight::exponents_weight
exponents_weight()
int GBWeight::exponents_weight (const int * exponent_vector, int comp) const
Definition at line 57 of file gbweight.cpp.
 {
   long sum = 0;
   for (int i = 0; i < nvars_; i++) sum += e[i] * wts_->array[i];
   if (use_component_degrees_ && comp > 0) sum += Fdegs_[comp];
   return static_cast<int>(sum);
 }
References Fdegs_, nvars_, mpfr::sum(), use_component_degrees_, and wts_.
Referenced by gbA::find_good_divisor(), ReducedGB_Field_Local::find_good_divisor(), gbA::find_good_monomial_divisor_ZZ(), gbA::find_good_term_divisor_ZZ(), gbvector_term_weight(), and monomial_weight().