Macaulay2 Engine: GBWeight::gbvector_weight
gbvector_weight() [1/2]
int GBWeight::gbvector_weight (const gbvector * f) const
Definition at line 93 of file gbweight.cpp.
{
  int not_used;
  return gbvector_weight(f, not_used);
}
References gbvector_weight().
Referenced by gbA::gbelem_make(), gbA::gbelem_ring_make(), gbvector_weight(), ReducedGB_Field_Local::minimalize(), GB_comp::new_gen(), GBinhom_comp::new_gen(), gbA::reduce_kk(), gbA::reduce_ZZ(), ReducedGB_Field_Local::ReducedGB_Field_Local(), ReducedGB_Field_Local::remainder(), ReducedGB_Field_Local::remainder(), and gbA::spair_make_gen().