Macaulay2 Engine: GBWeight::GBWeight
GBWeight()
GBWeight::GBWeight (const FreeModule * F, M2_arrayint wts)
Definition at line 7 of file gbweight.cpp.
                                                         : F_(F)
 {
   // If wts has length 0 or is NULL:
   // Use the primary degrees, if they are positive.
   // For each that is negative, use "1"
   // If the wt vector is not part of the degrees, then set
   // use_component_degrees to false.
   const PolynomialRing *A = F->get_ring()->cast_to_PolynomialRing();
   assert(A != 0);
   R_ = A->get_gb_ring();
   const Monoid *M = R_->get_flattened_monoid();
   nvars_ = R_->n_vars();
   wts_ = M2_makearrayint(nvars_);
   if (!wts0 || wts0->len != nvars_)
     {
       use_component_degrees_ = true;
       for (int i = 0; i < nvars_; i++)
         {
           int d = M->primary_degree_of_var(i);
           wts_->array[i] = (d > 0 ? d : 1);
           if (d <= 0) use_component_degrees_ = false;
         }
     }
   else
     {
       // Use the provided wt vector
       use_component_degrees_ = false;
       for (int i = 0; i < nvars_; i++)
         {
           int d = wts0->array[i];
           wts_->array[i] = (d > 0 ? d : 1);
         }
     }
   exp_size = EXPONENT_BYTE_SIZE(nvars_);
   if (use_component_degrees_)
     {
       Fdegs_ = newarray_atomic(long, F->rank() + 1);
       Fdegs_[0] = 0;
       for (int j = 0; j < F->rank(); j++) Fdegs_[j + 1] = F->primary_degree(j);
     }
   else
     Fdegs_ = nullptr;
 }
References Ring::cast_to_PolynomialRing(), exp_size, EXPONENT_BYTE_SIZE, Fdegs_, GBRing::get_flattened_monoid(), PolynomialRing::get_gb_ring(), FreeModule::get_ring(), M2_makearrayint(), GBRing::n_vars(), newarray_atomic, nvars_, FreeModule::primary_degree(), Monoid::primary_degree_of_var(), R_, FreeModule::rank(), use_component_degrees_, and wts_.