Macaulay2 Engine: GBWeight::exponents_weight
exponents_weight()
int GBWeight::exponents_weight (const_exponents e, int comp) const
Definition at line 58 of file gbweight.cpp.
 {
   int sum = exponents::weight(nvars_, e, wts_);
   if (use_component_degrees_ && comp > 0) sum += Fdegs_[comp];
   return sum;
 }
References Fdegs_, nvars_, mpfr::sum(), use_component_degrees_, ExponentVector< E, OC >::weight(), and wts_.
Referenced by gbA::find_good_divisor(), ReducedGB_Field_Local::find_good_divisor(), gbA::find_good_monomial_divisor_ZZ(), gbA::find_good_term_divisor_ZZ(), gbvector_term_weight(), and monomial_weight().