Macaulay2 Engine: rawARingGaloisField
rawARingGaloisField()
const Ring* rawARingGaloisField (int prime, int dimension)
Todo:
why parameters are ints and not longs or mpz's? is an overflow possible?
check prime for primality (probably at top of Macaulay2)
ARingGFGivaro uses tables and may consume a huge amount of memory - pass therefore a 'MaxMemoryConsumption' parameter and if the value is overstepped by ARingGFGivaro, create polynomial representation?
the check if in general polynomial representation is needed cost some additional work, similar to linbox/field/givaro-gfq.h. Use GivaroGfq instead of Givaro::GFqDom in ARingGFGivaro?
return Macaulay Galois field in some cases.
Definition at line 136 of file aring.cpp.
 {
   if (dimension < 0)
     {
       ERROR(" givaroGF/FFPACK: help, dimension is negative ! ");
       return nullptr;
     }
   try
     {
 #if 1
       if (prime <= 1)
         {
           ERROR("givaroGF/FFPACK: expected a prime number p ");
           return nullptr;
         }
       //-- NEED_POLYNOMIAL_REPRESENTATION is not usable(namespace problems) and
       // is not correct, because the answer depends on the template used for
       // Givaro::GFqDom.
       /*if (Givaro::NEED_POLYNOMIAL_REPRESENTATION(prime,dimension) )
       {
           ERROR("givaro Galois Field: polynomial representation is needed  -
       todo ");
           return 0;
       }*/
       if (dimension == 1 && M2::ARingZZpFFPACK::getMaxModulus() > prime)
         {
           // std::cout << "maximum modulus = " <<
           // M2::ARingZZpFFPACK::getMaxModulus() << std::endl;
           return M2::ConcreteRing<M2::ARingZZpFFPACK>::create(prime);
         }
       if (dimension == 1)
         {
           ERROR("maximum modulus = %f\n", M2::ARingZZpFFPACK::getMaxModulus());
           return nullptr;
         }
       #if 0
       return M2::ConcreteRing<M2::ARingGFGivaro>::create(prime, dimension);
       #endif
       ERROR("calling rawARingGaloisField with no longer allowed values, givaro is no longer available");
       return nullptr;
 #else
       ERROR("add --enable-fflas-ffpack --enable-givaro when building M2");
       return 0;
 #endif
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References M2::ConcreteRing< RingType >::create(), ERROR(), and M2::ARingZZpFFPACK::getMaxModulus().