Macaulay2 Engine: MutableMat::set_entry
set_entry()
template<typename Mat > virtual bool MutableMat< Mat >::set_entry (size_t r, size_t c, const ring_elem a) inline virtual
Implements MutableMatrix.
Definition at line 291 of file mutablemat-defs.hpp.
   {
     if (error_row_bound(r, n_rows())) return false;
     if (error_column_bound(c, n_cols())) return false;
     const ElementType& b = mat.ring().from_ring_elem_const(a);
     MatOps::setEntry(mat, r, c, b);
     return true;
   }
References error_column_bound(), error_row_bound(), MutableMat< Mat >::mat, MutableMat< Mat >::n_cols(), and MutableMat< Mat >::n_rows().