Macaulay2 Engine: MutableMat::eigenvectors
eigenvectors()
template<typename T > bool MutableMat< T >::eigenvectors (MutableMatrix * eigenvals, MutableMatrix * eigenvecs, bool is_symm_or_hermitian) const virtual
Implements MutableMatrix.
Definition at line 245 of file mutablemat-imp.hpp.
 {
   if (!is_dense())
     throw exc::engine_error(
         "'eigenvalues' is only implemented for dense matrices");
   if (is_symm_or_hermitian)
     {
       DMat<HermitianEigenvalueType>* E1 =
           eigenvals->coerce<DMat<HermitianEigenvalueType> >();
       DMat<HermitianEigenvectorType>* evecs1 =
           eigenvecs->coerce<DMat<HermitianEigenvectorType> >();
       if (E1 == 0 or evecs1 == 0)
         throw exc::engine_error(
             "eigenvalue/vector matrix is of the wrong type/ring");
       return MatrixOps::eigenvectorsHermitian(mat, *E1, *evecs1);
     }
   else
     {
       DMat<EigenvalueType>* E1 = eigenvals->coerce<DMat<EigenvalueType> >();
       DMat<EigenvectorType>* evecs1 =
           eigenvecs->coerce<DMat<EigenvectorType> >();
       if (E1 == 0 or evecs1 == 0)
         throw exc::engine_error(
             "eigenvalue/vector matrix is of the wrong type/ring");
       return MatrixOps::eigenvectors(mat, *E1, *evecs1);
     }
 }
References MutableMatrix::coerce(), MatrixOps::eigenvectors(), and MatrixOps::eigenvectorsHermitian().