Macaulay2 Engine: MutableMat::n_cols
n_cols()
template<typename Mat > virtual size_t MutableMat< Mat >::n_cols () const inline virtual
Implements MutableMatrix.
Definition at line 229 of file mutablemat-defs.hpp.
{ return mat.numColumns(); }
References MutableMat< Mat >::mat.
Referenced by MutableMat< Mat >::add(), MutableMat< Mat >::column2by2(), MutableMat< Mat >::column_op(), MutableMat< Mat >::delete_columns(), MutableMat< Mat >::divide_column(), MutableMat< Mat >::dot_product(), MutableMat< Mat >::get_entry(), MutableMat< Mat >::insert_columns(), MutableMat< Mat >::interchange_columns(), MutableMat< Mat >::scale_column(), MutableMat< Mat >::set_entry(), MutableMat< Mat >::submatrix(), MutableMat< Mat >::submatrix(), MutableMat< Mat >::subtract(), and MutableMat< Mat >::transpose().