Macaulay2 Engine: MutableMat::subtract
subtract()
template<typename Mat > virtual MutableMat * MutableMat< Mat >::subtract (const MutableMatrix * B) const inline virtual
Implements MutableMatrix.
Definition at line 596 of file mutablemat-defs.hpp.
  {
    const Mat* B1 = B->coerce_const<Mat>();
    if (B1 == NULL)
      {
        ERROR("expected matrices with the same ring and sparsity");
        return NULL;
      }
    if (B->get_ring() != get_ring())
      {
        ERROR("expected matrices with the same ring");
        return NULL;
      }
    if (B1->numRows() != n_rows() || B1->numColumns() != n_cols())
      {
        ERROR("expected matrices of the same shape");
        return NULL;
      }
    MutableMat* result = clone();
    MatrixOps::subtractInPlace(result->getMat(), *B1);
    return result;
  }
References MutableMat< Mat >::clone(), MutableMatrix::coerce_const(), ERROR(), MutableMat< Mat >::get_ring(), MutableMat< Mat >::getMat(), MutableMat< Mat >::n_cols(), MutableMat< Mat >::n_rows(), and MatrixOps::subtractInPlace().