Macaulay2 Engine: MutableMat::getMat
getMat() [1/2]
template<typename Mat > Mat& MutableMat< Mat >::getMat () inline
Definition at line 206 of file mutablemat-defs.hpp.
 { return mat; }
References MutableMat< Mat >::mat.
Referenced by MutableMat< Mat >::add(), SLEvaluatorConcrete< RT >::evaluate(), getRealVector(), MutableMat< Mat >::is_equal(), MutableMat< Mat >::is_zero(), MutableMat< Mat >::negate(), MutableMat< Mat >::submatrix(), MutableMat< Mat >::subtract(), HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track(), and MutableMat< Mat >::transpose().