Macaulay2 Engine: MutableMat::eigenvalues
eigenvalues()
template<typename T > bool MutableMat< T >::eigenvalues (MutableMatrix * eigenvals, bool is_symm_or_hermitian) const virtual
Implements MutableMatrix.
Definition at line 222 of file mutablemat-imp.hpp.
 {
   if (!is_dense())
     throw exc::engine_error(
         "'eigenvalues' is only implemented for dense matrices");
   if (is_symm_or_hermitian)
     {
       auto E1 = eigenvals->coerce<DMat<HermitianEigenvalueType> >();
       if (E1 == 0)
         throw exc::engine_error("eigenvalue matrix is of the wrong type/ring");
       return MatrixOps::eigenvaluesHermitian(mat, *E1);
     }
   else
     {
       auto E1 = eigenvals->coerce<DMat<EigenvalueType> >();
       if (E1 == 0)
         throw exc::engine_error("eigenvalue matrix is of the wrong type/ring");
       return MatrixOps::eigenvalues(mat, *E1);
     }
 }
References MutableMatrix::coerce(), MatrixOps::eigenvalues(), and MatrixOps::eigenvaluesHermitian().