Macaulay2 Engine: MutableMat::n_rows
n_rows()
template<typename Mat > virtual size_t MutableMat< Mat >::n_rows () const inline virtual
Implements MutableMatrix.
Definition at line 228 of file mutablemat-defs.hpp.
{ return mat.numRows(); }
References MutableMat< Mat >::mat.
Referenced by MutableMat< Mat >::add(), MutableMat< Mat >::delete_rows(), MutableMat< Mat >::divide_row(), MutableMat< Mat >::get_entry(), MutableMat< Mat >::insert_rows(), MutableMat< Mat >::interchange_rows(), rawLinAlgMinPoly(), MutableMat< Mat >::row2by2(), MutableMat< Mat >::row_op(), MutableMat< Mat >::scale_row(), MutableMat< Mat >::set_entry(), MutableMat< Mat >::submatrix(), MutableMat< Mat >::subtract(), and MutableMat< Mat >::transpose().