Macaulay2 Engine: MutableMat::mult
mult() [2/2]
template<typename Mat > virtual MutableMat * MutableMat< Mat >::mult (const RingElement * f) const inline virtual
Implements MutableMatrix.
Definition at line 621 of file mutablemat-defs.hpp.
  {
    if (f->get_ring() != get_ring())
      {
        ERROR("expected same ring");
        return 0;
      }
    const ElementType& a = mat.ring().from_ring_elem_const(f->get_value());
    MutableMat* result = clone();
    MatrixOps::scalarMultInPlace(result->mat, a);
    return result;
  }
References MutableMat< Mat >::clone(), ERROR(), MutableMat< Mat >::get_ring(), MutableMat< Mat >::mat, and MatrixOps::scalarMultInPlace().