Macaulay2 Engine: MutableMat::submatrix
submatrix() [2/2]
template<typename Mat > virtual MutableMatrix * MutableMat< Mat >::submatrix (M2_arrayint rows, M2_arrayint cols) const inline virtual
Implements MutableMatrix.
Definition at line 506 of file mutablemat-defs.hpp.
  {
    for (size_t r = 0; r < rows->len; r++)
      if (rows->array[r] < 0 || rows->array[r] >= n_rows())
        {
          ERROR(
              "row index %d out of bounds 0..%d", rows->array[r], n_rows() - 1);
          return 0;
        }
    for (size_t c = 0; c < cols->len; c++)
      if (cols->array[c] < 0 || cols->array[c] >= n_cols())
        {
          ERROR("column index %d out of bounds 0..%d",
                cols->array[c],
                n_cols() - 1);
          return 0;
        }
    MutableMat* result =
        new MutableMat(*this);  // zero matrix, over the same ring
    MatOps::setFromSubmatrix(getMat(), rows, cols, result->getMat());
    return result;
  }
References ERROR(), MutableMat< Mat >::getMat(), MutableMat< Mat >::MutableMat(), MutableMat< Mat >::n_cols(), and MutableMat< Mat >::n_rows().