Macaulay2 Engine: MutableMat::least_squares
least_squares()
template<typename T > bool MutableMat< T >::least_squares (const MutableMatrix * b, MutableMatrix * x, bool assume_full_rank) const virtual
Implements MutableMatrix.
Definition at line 276 of file mutablemat-imp.hpp.
 {
   const T* B1 = B->coerce_const<T>();
   T* X1 = X->coerce<T>();
   if (B1 == 0 or X1 == 0)
     throw exc::engine_error("expected matrices of the same type");
   bool retval = MatrixOps::leastSquares(mat, *B1, *X1, assume_full_rank);
   return retval;
 }
References MutableMatrix::coerce(), MutableMatrix::coerce_const(), MatrixOps::leastSquares(), and T.