Macaulay2 Engine: MutableMat::delete_rows
delete_rows()
template<typename Mat > virtual bool MutableMat< Mat >::delete_rows (size_t i, size_t j) inline virtual
Implements MutableMatrix.
Definition at line 492 of file mutablemat-defs.hpp.
   {
     size_t nrows = n_rows();
     if (error_row_bound(i, nrows) || error_row_bound(j, nrows))
       {
         ERROR("row index out of range");
         return false;
       }
     MatOps::delete_rows(mat, i, j);
     return true;
   }
References ERROR(), error_row_bound(), MutableMat< Mat >::mat, and MutableMat< Mat >::n_rows().