Macaulay2 Engine: MutableMat::makeZeroMatrix
makeZeroMatrix()
template<typename Mat > MutableMat * MutableMat< Mat >::makeZeroMatrix (size_t nrows, size_t ncols) const inline
Definition at line 199 of file mutablemat-defs.hpp.
  {
    return new MutableMat(get_ring(), &mat.ring(), nrows, ncols);
  }
References MutableMat< Mat >::get_ring(), MutableMat< Mat >::mat, and MutableMat< Mat >::MutableMat().
Referenced by MutableMat< Mat >::transpose().