Macaulay2 Engine: MutableMat::copy
copy()
template<typename Mat > virtual MutableMat * MutableMat< Mat >::copy (bool prefer_dense) const inline virtual
Implements MutableMatrix.
Definition at line 232 of file mutablemat-defs.hpp.
  {
#if 0
    MutableMat *result = new MutableMat;
    Mat *m = mat.copy();
    result->mat.grab(m);
    return result;
#endif
    return clone();
  }
References MutableMat< Mat >::clone(), MutableMat< Mat >::copy(), MutableMat< Mat >::mat, and MutableMat< Mat >::MutableMat().
Referenced by MutableMat< Mat >::copy().