Macaulay2 Engine: MutableMat::solveInvertible
solveInvertible()
template<typename T > MutableMatrix * MutableMat< T >::solveInvertible (const MutableMatrix * B) const virtual
Implements MutableMatrix.
Definition at line 96 of file mutablemat-imp.hpp.
 {
   const T* B1 = B->coerce_const<T>();
   if (B1 == 0) throw exc::engine_error("expected matrices of the same type");
   if (B->get_ring() != get_ring())
     throw exc::engine_error("expected same ring");
   if (n_rows() != n_cols()) throw exc::engine_error("expected a square matrix");
   if (B->n_rows() != n_rows())
     throw exc::engine_error("expected matrices with same number of rows");
   MutableMat<T>* solns = makeZeroMatrix(0, 0);
   bool retval = MatrixOps::solveInvertible(mat, *B1, solns->mat);
   if (retval) return solns;
   delete solns;
   return NULL;
 }
References MutableMatrix::coerce_const(), MutableMatrix::get_ring(), MutableMat< Mat >::mat, MutableMatrix::n_rows(), MatrixOps::solveInvertible(), and T.