Macaulay2 Engine: MutableMat::transpose
transpose()
template<typename Mat > virtual MutableMat* MutableMat< Mat >::transpose () const inline virtual
Implements MutableMatrix.
Definition at line 637 of file mutablemat-defs.hpp.
References MutableMat< Mat >::getMat(), MutableMat< Mat >::makeZeroMatrix(), MutableMat< Mat >::n_cols(), MutableMat< Mat >::n_rows(), and MatrixOps::transpose().