Macaulay2 Engine: MutableMat::get_Mat
get_Mat() [1/2]
template<typename Mat > Mat* MutableMat< Mat >::get_Mat () inline
Definition at line 204 of file mutablemat-defs.hpp.
 { return &mat; }
References MutableMat< Mat >::mat.
Referenced by MutableMatrix::coerce(), MutableMatrix::coerce_const(), rawLinAlgCharPoly(), and rawLinAlgMinPoly().