Macaulay2 Engine: LUUtil::computePivotColumns
computePivotColumns()
template<class RingType > void LUUtil< RingType >::computePivotColumns (const Mat & LU, std::vector< size_t > & result_columns) static
Definition at line 429 of file dmat-lu-inplace.hpp.
 {
   result_columns.clear();
   size_t thiscol = 0;
   size_t thisrow = 0;
   while (thisrow < LU.numRows() and thiscol < LU.numColumns())
     {
       if (not LU.ring().is_zero(LU.entry(thisrow, thiscol)))
         {
           result_columns.push_back(thiscol);
           thisrow++;
         }
       thiscol++;
     }
 }
References MatrixOps::LU().
Referenced by DMatLinAlg< M2::ARingZZpFlint >::columnRankProfile(), DMatLUinPlace< RT >::computeLU(), and DMatLinAlg< M2::ARingZZpFlint >::solve().