Macaulay2 Engine: LUUtil::setUpperLower
setUpperLower()
template<class RingType > void LUUtil< RingType >::setUpperLower (const Mat & LU, Mat & lower, Mat & upper) static
Definition at line 414 of file dmat-lu-inplace.hpp.
 {
   size_t min = std::min(LU.numRows(), LU.numColumns());
   lower.resize(LU.numRows(), min);
   upper.resize(min, LU.numColumns());
   // At this point, lower and upper should be zero matrices.
   assert(MatrixOps::isZero(lower));
   assert(MatrixOps::isZero(upper));
   for (size_t c = 0; c < LU.numColumns(); c++)
     {
       if (c < min) LU.ring().set_from_long(lower.entry(c, c), 1);
       for (size_t r = 0; r < LU.numRows(); r++)
         {
           if (r <= c)
             LU.ring().set(upper.entry(r, c), LU.entry(r, c));
           else if (c < lower.numRows())
             {
               LU.ring().set(lower.entry(r, c), LU.entry(r, c));
             }
         }
     }
 }
References DMat< ACoeffRing >::entry(), MatrixOps::isZero(), MatrixOps::LU(), mpfr::min(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::resize().
Referenced by DMatLinAlg< M2::ARingZZpFFPACK >::matrixPLU(), and DMatLinAlg< M2::ARingZZpFlint >::matrixPLU().