Macaulay2 Engine: monomialOrderEncodeFromActualExponents
monomialOrderEncodeFromActualExponents()
void monomialOrderEncodeFromActualExponents (const MonomialOrder * mo, const_exponents expon, monomial result_psums)
Definition at line 410 of file imonorder.cpp.
 {
   if (mo == 0) return;
   int *tmpexp = static_cast<int *>(alloca((mo->nvars + 1) * sizeof(int)));
   int i, j, nvars, s;
   int *p1;
   deg_t *degs;
   struct mo_block *b = mo->blocks;
   int nblocks = mo->nblocks;
   const int *e = expon;
   int *p = result_psums;
   for (i = nblocks; i > 0; --i, b++) switch (b->typ)
       {
         case MO_LEX:
         case MO_LAURENT:
           nvars = b->nvars;
           for (j = 0; j < nvars; j++) *p++ = *e++;
           break;
         case MO_REVLEX:
         case MO_LAURENT_REVLEX:
           nvars = b->nvars;
           for (j = 0; j < nvars; j++) *p++ = safe::minus(*e++);
           break;
         case MO_GREVLEX:
           nvars = b->nvars;
           p += b->nslots;
           p1 = p;
           *--p1 = *e++;
           for (j = 1; j < nvars; j++)
             {
               --p1;
               *p1 = safe::add(*e++, p1[1]);
             }
           break;
         case MO_GREVLEX_WTS:
           nvars = b->nvars;
           degs = mo->degs + b->first_exp;
           p += b->nslots;
           p1 = p;
           *--p1 = safe::mult(*e++, *degs++);
           for (j = 1; j < nvars; j++)
             {
               --p1;
               int tmp = safe::mult(*e++, *degs++);
               *p1 = safe::add(tmp, p1[1]);
             }
           break;
         case MO_GREVLEX4:
           nvars = b->nvars;
           p1 = tmpexp + b->nvars;
           *--p1 = *e++;
           for (j = 1; j < nvars; j++)
             {
               --p1;
               *p1 = safe::add(*e++, p1[1]);
             }
           MO_pack4(nvars, p1, p);
           p += b->nslots;
           break;
         case MO_GREVLEX4_WTS:
           nvars = b->nvars;
           degs = mo->degs + b->first_exp;
           p1 = tmpexp + b->nvars;
           *--p1 = safe::mult(*e++, *degs++);
           for (j = 1; j < nvars; j++)
             {
               --p1;
               int tmp = safe::mult(*e++, *degs++);
               *p1 = safe::add(tmp, p1[1]);
             }
           MO_pack4(nvars, p1, p);
           p += b->nslots;
           break;
         case MO_GREVLEX2:
           nvars = b->nvars;
           p1 = tmpexp + b->nvars;
           *--p1 = *e++;
           for (j = 1; j < nvars; j++)
             {
               --p1;
               *p1 = safe::add(*e++, p1[1]);
             }
           MO_pack2(nvars, p1, p);
           p += b->nslots;
           break;
         case MO_GREVLEX2_WTS:
           nvars = b->nvars;
           degs = mo->degs + b->first_exp;
           p1 = tmpexp + b->nvars;
           *--p1 = safe::mult(*e++, *degs++);
           for (j = 1; j < nvars; j++)
             {
               --p1;
               int tmp = safe::mult(*e++, *degs++);
               *p1 = safe::add(tmp, p1[1]);
             }
           MO_pack2(nvars, p1, p);
           p += b->nslots;
           break;
         case MO_LEX4:
           nvars = b->nvars;
           MO_pack4(nvars, e, p);
           p += b->nslots;
           e += nvars;
           break;
         case MO_LEX2:
           nvars = b->nvars;
           MO_pack2(nvars, e, p);
           p += b->nslots;
           e += nvars;
           break;
         case MO_WEIGHTS:
           if (b->nweights == 0)
             {
               s = 0;
             }
           else
             {
               s = safe::mult(b->weights[0], expon[0]);
               for (j = 1; j < b->nweights; j++)
                 s = safe::add(s, safe::mult(b->weights[j], expon[j]));
             }
           *p++ = s;
           break;
         case MO_POSITION_UP:
         case MO_POSITION_DOWN:
           /* nothing to do here */
           break;
         case MO_NC_LEX:
           /* nothing to do here */
           break;
       }
 }
References safe::add(), mo_block::first_exp, safe::minus(), MO_GREVLEX, MO_GREVLEX2, MO_GREVLEX2_WTS, MO_GREVLEX4, MO_GREVLEX4_WTS, MO_GREVLEX_WTS, MO_LAURENT, MO_LAURENT_REVLEX, MO_LEX, MO_LEX2, MO_LEX4, MO_NC_LEX, MO_pack2(), MO_pack4(), MO_POSITION_DOWN, MO_POSITION_UP, MO_REVLEX, MO_WEIGHTS, safe::mult(), mo_block::nslots, mo_block::nvars, mon_part::nvars, mo_block::nweights, p, p1, mo_block::typ, and mo_block::weights.
Referenced by Monoid::from_expvector().