Macaulay2 Engine: monomialOrderDecodeToActualExponents
monomialOrderDecodeToActualExponents()
void monomialOrderDecodeToActualExponents (const MonomialOrder * mo, const_monomial psums, exponents_t expon)
Definition at line 548 of file imonorder.cpp.
 {
   if (mo == nullptr) return;
   int *tmpexp = static_cast<int *>(alloca((mo->nvars + 1) * sizeof(int)));
   int i, j, nvars;
   deg_t *degs = mo->degs;
   deg_t *d;
   struct mo_block *b = mo->blocks;
   int nblocks = mo->nblocks;
   int *e = expon;
   const int *p = psums;
   for (i = nblocks; i > 0; --i, b++) switch (b->typ)
       {
         case MO_LEX:
         case MO_LAURENT:
           nvars = b->nvars;
           p = psums + b->first_slot;
           e = expon + b->first_exp;
           for (j = 0; j < nvars; j++) *e++ = *p++;
           break;
         case MO_REVLEX:
         case MO_LAURENT_REVLEX:
           nvars = b->nvars;
           p = psums + b->first_slot;
           e = expon + b->first_exp;
           for (j = 0; j < nvars; j++) *e++ = safe::minus(*p++);
           break;
         case MO_GREVLEX:
           nvars = b->nvars;
           p = psums + b->first_slot + nvars - 1;
           e = expon + b->first_exp;
           *e++ = *p--;
           for (j = nvars - 1; j >= 1; --j, --p) *e++ = safe::sub(*p, p[1]);
           break;
         case MO_GREVLEX_WTS:
           nvars = b->nvars;
           d = degs + b->first_exp;
           p = psums + b->first_slot + nvars - 1;
           e = expon + b->first_exp;
           *e++ = *p-- / *d++;
           for (j = nvars - 1; j >= 1; --j, --p)
             *e++ = safe::sub(*p, p[1]) / *d++;
           break;
         case MO_GREVLEX4:
           nvars = b->nvars;
           MO_unpack4(nvars, psums + b->first_slot, tmpexp);
           p = tmpexp + nvars - 1;
           e = expon + b->first_exp;
           *e++ = *p--;
           for (j = nvars - 1; j >= 1; --j, --p) *e++ = safe::sub(*p, p[1]);
           break;
         case MO_GREVLEX4_WTS:
           nvars = b->nvars;
           d = degs + b->first_exp;
           MO_unpack4(nvars, psums + b->first_slot, tmpexp);
           p = tmpexp + nvars - 1;
           e = expon + b->first_exp;
           *e++ = *p-- / *d++;
           for (j = nvars - 1; j >= 1; --j, --p)
             *e++ = safe::sub(*p, p[1]) / *d++;
           break;
         case MO_GREVLEX2:
           nvars = b->nvars;
           MO_unpack2(nvars, psums + b->first_slot, tmpexp);
           p = tmpexp + nvars - 1;
           e = expon + b->first_exp;
           *e++ = *p--;
           for (j = nvars - 1; j >= 1; --j, --p) *e++ = safe::sub(*p, p[1]);
           break;
         case MO_GREVLEX2_WTS:
           nvars = b->nvars;
           d = degs + b->first_exp;
           MO_unpack2(nvars, psums + b->first_slot, tmpexp);
           p = tmpexp + nvars - 1;
           e = expon + b->first_exp;
           *e++ = *p-- / *d++;
           for (j = nvars - 1; j >= 1; --j, --p)
             *e++ = safe::sub(*p, p[1]) / *d++;
           break;
         case MO_LEX4:
           nvars = b->nvars;
           e = expon + b->first_exp;
           MO_unpack4(nvars, psums + b->first_slot, e);
           break;
         case MO_LEX2:
           nvars = b->nvars;
           e = expon + b->first_exp;
           MO_unpack2(nvars, psums + b->first_slot, e);
           break;
         case MO_WEIGHTS:
           break;
         case MO_POSITION_UP:
         case MO_POSITION_DOWN:
           /* should not occur, but do nothing in any case */
           break;
         case MO_NC_LEX:
           /* nothing to do here */
           break;
       }
 }
References mo_block::first_exp, mo_block::first_slot, safe::minus(), MO_GREVLEX, MO_GREVLEX2, MO_GREVLEX2_WTS, MO_GREVLEX4, MO_GREVLEX4_WTS, MO_GREVLEX_WTS, MO_LAURENT, MO_LAURENT_REVLEX, MO_LEX, MO_LEX2, MO_LEX4, MO_NC_LEX, MO_POSITION_DOWN, MO_POSITION_UP, MO_REVLEX, MO_unpack2(), MO_unpack4(), MO_WEIGHTS, mo_block::nvars, p, safe::sub(), and mo_block::typ.
Referenced by Monoid::to_expvector().