Macaulay2 Engine: TrivialPolynomialHeap::addPolynomial
addPolynomial() [2/2]
TrivialPolynomialHeap & TrivialPolynomialHeap::addPolynomial (ring_elem coeff, Word left, Word right, const Poly & poly) inline override virtual
Implements PolynomialHeap.
Definition at line 156 of file NCReduction.cpp.
  {
    mRing.setZero(f);
    mRing.setZero(g);
    // Create f = coeff * left * poly * right;
    mRing.mult_by_term_left_and_right(f, poly, coeff, left, right);
    mRing.add(g, mIter, mValue.cend(), f.cbegin(), f.cend());
    std::swap(g, mValue);
    mIter = mValue.cbegin();
    return *this;
  }
References FreeAlgebra::add(), f, g, mIter, mRing, FreeAlgebra::mult_by_term_left_and_right(), mValue, FreeAlgebra::setZero(), and std::swap().