Macaulay2 Engine: emit
emit()
void emit (const char * s)
Definition at line 41 of file text-io.cpp.
 {
   fputs(s, stdout);
   fflush(stdout);
 }
Referenced by MinimalPrimes::alg1_min_primes(), GBKernelComputation::calc(), NCGroebner::computeHomogeneous(), NCGroebner::computeInhomogeneous(), binomialGB::debug_display(), F4MonomialLookupTableT< Key >::debug_out(), MonomialIdeal::debug_out(), ResF4MonomialLookupTableT< Key >::debug_out(), GBinhom_comp::debug_out(), gb2_comp::debug_out(), GBinhom_comp::debug_pairs(), GBinhom_comp::debug_pairs_out(), dfree(), dgbvec(), dhermite(), dintarray(), displayCF(), displayMat(), dmatrix(), dmonideal(), dmutablemat(), dNterm(), res2_comp::do_auto_reductions(), LLLoperations::doLLL(), drelem(), drespoly(), drespoly2(), dringelem(), dRRR(), dstash(), dvector(), res2_poly::elem_text_out(), res_poly::elem_text_out(), res2_comp::find_divisor(), GBKernelComputation::find_divisor(), ReducedGB_Field_Local::find_good_divisor(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), ResF4toM2Interface::from_M2_vec(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_insert(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), res_comp::gens(), res2_comp::handle_pair_by_level(), res2_comp::initialize(), GBRing::memstats(), binomialGB::n_masks(), res2_comp::new_pairs(), res_comp::new_pairs(), pring(), NCF4::process(), binomialGB_comp::process_pair(), gbA::reduce_kk(), gbA::reduce_ZZ(), ReducedGB_ZZ::remainder(), ReducedGB_Field_Local::remainder(), GB_comp::s_pair_step(), GBinhom_comp::s_pair_step(), F4Computation::show(), F4GB::show_gb_array(), F4GB::show_matrix(), F4GB::show_new_rows_matrix(), Interreducer::showElem(), FractionField::simplify(), LocalRing::simplify(), res_comp::skeleton_pairs(), res_comp::skeleton_stats(), GaussElimComputation::start_computation(), GB_comp::start_computation(), GBinhom_comp::start_computation(), res2_comp::start_computation(), gbres_comp::start_computation(), GBinhom_comp::stats(), binomial_s_pair_set::stats(), binomialGB_comp::stats(), res2_comp::stats(), res_comp::stats(), gb2_comp::stats(), test_over_RR_or_CC(), res2_comp::text_out(), res_comp::text_out(), and doubling_stash::~doubling_stash().