Macaulay2 Engine: emit_line
emit_line()
void emit_line (const char * s)
Definition at line 46 of file text-io.cpp.
 {
   while (*s != 0)
     {
       while (*s != '\n' && *s != 0) putchar(*s++);
       putchar('\n');
       if (*s != 0) s++;
       fputs(wrapping_prefix, stdout);
     }
   fflush(stdout);
 }
References wrapping_prefix.
Referenced by alexDual(), gbA::auto_reduce_by(), ResolutionComputation::choose_res(), gbA::collect_syzygy(), gbA::compute_s_pair(), NCGroebner::computeHomogeneous(), NCGroebner::computeInhomogeneous(), gbA::debug_spair(), gbA::do_computation(), F4MonomialLookupTableT< Key >::do_node(), ResF4MonomialLookupTableT< Key >::do_node(), MonomialIdeal::do_node(), dvec(), gbA::find_good_divisor(), GBinhom_comp::find_pairs(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), GBRing::gbvector_auto_reduce(), GBRing::gbvector_auto_reduce_ZZ(), GBKernelComputation::geo_reduce(), gbA::insert_gb(), GBinhom_comp::mark_pair(), gbA::minimalize_pairs_non_ZZ(), gbA::minimalize_pairs_ZZ(), NCGroebner::NCGroebner(), MonomialSorterObject::operator()(), binomialGB_comp::process_pair(), range_safe_add(), rawStartComputation(), GBKernelComputation::reduce(), gbA::reduce_kk(), gbA::reduce_ZZ(), gbA::remainder_non_ZZ(), gbA::remainder_ZZ(), gbA::remove_unneeded_pairs(), gbA::replace_gb_element_ZZ(), GBinhom_comp::s_pair_step(), gbA::show(), gbA::show_mem_usage(), gbA::spair_set_defer(), gbA::spair_set_next(), gbA::start_computation(), GB_comp::start_computation(), GBinhom_comp::start_computation(), gbres_comp::stats(), and gbA::tail_remainder_ZZ().