Macaulay2 Engine: BasicPoly::display
display() [2/2]
void BasicPoly::display (std::ostream & o, const std::vector< std::string > & varnames, bool print_one, bool print_plus, bool print_parens) const
Definition at line 69 of file BasicPoly.cpp.
 {
   if (termCount() == 0)
     {
       o << '0';
       return;
     }
   bool more_than_one_term = (termCount() >= 2);
   int needs_parens = print_parens && more_than_one_term;
   if (needs_parens)
     {
       if (print_plus) o << '+';
       o << '(';
       print_plus = false;
     }
   const int* monom_loc = mMonomials.data();
   for (int i=0; i<termCount(); ++i)
     {
       bool monom_is_one = (*monom_loc == 1); // TODO: do *not* hand code this determination in!
       print_parens = !monom_is_one;
       bool p_one_this = (monom_is_one && needs_parens) || (monom_is_one && print_one);
       displayCoefficient(o, mCoefficients[i], print_plus, p_one_this);
       if (!monom_is_one)
         {
           if (mCoefficients[i] != 1 and mCoefficients[i] != -1)
             o << '*';
           newf4::MonomialView::display(o, varnames, newf4::MonomialView(const_cast<int*>(monom_loc)));
         }
       print_plus = true;
       monom_loc += *monom_loc;
     }
   if (needs_parens) o << ')';
 }
References newf4::MonomialView::display(), displayCoefficient(), mCoefficients, mMonomials, and termCount().
Referenced by display(), and toString().