Macaulay2 Engine: rawFourierMotzkin
rawFourierMotzkin()
const Matrix* rawFourierMotzkin (const Matrix * C)
Cone interface routines
Definition at line 23 of file cone.cpp.
 {
   try
     {
       // TODO: generalize the input type, in particular to allow lineality space
       const Ring *R = C->get_ring();
       const size_t c = C->n_cols();  // rank of ambient lattice
       const size_t r = C->n_rows();  // number of cone inequalities
       auto ineqs = libnormaliz::Matrix<Integer>(r, c);
       for (size_t i = 0; i < r; i++)
         for (size_t j = 0; j < c; j++)
       // libnormaliz uses A*x >= 0, Macaulay2 uses A*x <= 0
           ineqs[i][j] = (-1) * static_cast<Integer>(C->elem(i, j).get_mpz());
       auto cone = libnormaliz::Cone<Integer>(libnormaliz::Type::inequalities, ineqs);
       auto rays = cone.getExtremeRays();
       size_t n = rays.size();  // number of extremal rays
       MatrixConstructor mat(R->make_FreeModule(n), c);
       for (size_t i = 0; i < n; i++)
         for (size_t j = 0; j < c; j++)
           {
             mpz_ptr z = newitem(__mpz_struct);
             mpz_init_set(z, rays[i][j].get_mpz_t());
             mpz_reallocate_limbs(z);
             mat.set_entry(i, j, ring_elem(z));
           }
       return mat.to_matrix();
   } catch (const exc::engine_error &e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Matrix::elem(), ERROR(), ring_elem::get_mpz(), Matrix::get_ring(), Ring::make_FreeModule(), mpz_reallocate_limbs(), Matrix::n_cols(), Matrix::n_rows(), newitem, MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().