Macaulay2 Engine: WordTable::insert
insert() [1/2]
size_t WordTable::insert (Word w)
Definition at line 17 of file WordTable.cpp.
{
  // we are making a copy of the word, since the pointers
  // to the GB elements may change during autoreduction.
  auto newW = mMonomialSpace.allocateArray<int>(w.size());
  std::copy(w.begin(),w.end(),newW.first);
  mMonomials.push_back(Word(newW.first,newW.second));
  return mMonomials.size();
}
References MemoryBlock::allocateArray(), Word::begin(), Word::end(), mMonomials, mMonomialSpace, and Word::size().
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), NCF4::updateOverlaps(), and NCGroebner::updateOverlaps().