Macaulay2 Engine: WordTable::overlaps
overlaps()
void WordTable::overlaps (Word word1, Word word2, std::vector< int > & result_overlaps) static private
Definition at line 213 of file WordTable.cpp.
 {
   if (word1.size() <= 1) return;
   for (int i = word1.size() - 1; i > 0 and i + word2.size() > word1.size(); --i)
     {
       Word suffix(word1.begin() + i, word1.end());
       Word prefix(word2.begin(), word2.begin() + word1.size() - i); // indices should be in range.
       if (suffix == prefix)
         result_overlaps.push_back(i);
     }
 }
References Word::begin(), Word::end(), prefix(), Word::size(), and suffix().
Referenced by leftOverlaps().