Macaulay2 Engine: WordTable::subwordPositions
subwordPositions()
void WordTable::subwordPositions (Word word1, Word word2, std::vector< int > & result_start_indices) static
Definition at line 38 of file WordTable.cpp.
 {
   if (word2.size() < word1.size()) return;
   for (auto j = 0; j <= word2.size() - word1.size(); ++j)
     {
       bool match = true;
       for (auto k = 0; k < word1.size(); ++k)
         if (word1.begin()[k] != word2.begin()[j+k])
           {
             match = false;
             break;
           }
       if (match) result_start_indices.push_back(j);
     }
 }
References Word::begin(), and Word::size().
Referenced by NCF4::checkOldOverlaps(), and superwords().