Macaulay2 Engine: WordTable::leftOverlaps
leftOverlaps()
void WordTable::leftOverlaps (std::vector< Overlap > & newLeftOverlaps) const
Definition at line 227 of file WordTable.cpp.
 {
   // word here is the last word in the dictionary.
   // For left overlap: dictword is a word in the dictionary NOT word.
   // For right overlap: dictword is any word in the dictionary.
   // A left overlap: suffix(dictword) == prefix(word)
   // A right overlap: prefix(dictword) == suffix(word).
   //   if dictword == word, a match will be a right overlap, NOT a left overlap.
   // A returned triple:
   //   (left overlap):
   int word_index = mMonomials.size()-1;
   std::vector<int> overlap_indices;
   for (int i=0; i<word_index; ++i)
     {
       overlap_indices.clear();
       overlaps(mMonomials[i], mMonomials[word_index], overlap_indices);
       for (auto j : overlap_indices)
         newLeftOverlaps.push_back(std::make_tuple(i, j, word_index,true));
     }
   // triples will be <dict word index, index into dict word where suffix starts, word_index>.
 }
References mMonomials, and overlaps().
Referenced by TEST(), NCF4::updateOverlaps(), and NCGroebner::updateOverlaps().