Macaulay2 Engine: WordTable::subwordPosition
subwordPosition()
bool WordTable::subwordPosition (Word word1, Word word2, int & result_start_index) static private
Definition at line 59 of file WordTable.cpp.
 {
   if (word2.size() < word1.size()) return false;
   for (auto j = 0; j <= word2.size() - word1.size(); ++j)
     {
       bool match = true;
       for (auto k = 0; k < word1.size(); ++k)
         if (word1.begin()[k] != word2.begin()[j+k])
           {
             match = false;
             break;
           }
       if (match)
         {
           result_start_index = j;
           return true;
         }
     }
   return false;
 }
References Word::begin(), and Word::size().
Referenced by subword().