Macaulay2 Engine: PathTracker::refine
refine()
Matrix * PathTracker::refine (const Matrix * sols, gmp_RR tolerance, int max_corr_steps_refine = 100)
Definition at line 1978 of file NAG.cpp.
References C, cast_to_CCC(), Matrix::elem(), ERROR(), evaluate_slpHxH(), freemem(), from_doubles(), Matrix::get_ring(), complex::getimaginary(), complex::getreal(), Ring::make_FreeModule(), Matrix::n_cols(), n_coords, Matrix::n_rows(), n_sols, newarray_atomic, MatrixConstructor::set_entry(), solve_via_lapack_without_transposition(), MatrixConstructor::to_matrix(), and toBigComplex().
Referenced by rawRefinePT().