Macaulay2 Engine: PathTracker::make
make() [1/3]
PathTracker * PathTracker::make (const Matrix * HH) static
Definition at line 1516 of file NAG.cpp.
References cast_to_CCC(), Ring::cast_to_PolyRing(), Matrix::elem(), ERROR(), Matrix::get_ring(), PolynomialRing::getCoefficients(), StraightLineProgram::make(), Matrix::n_cols(), Matrix::n_rows(), p, and PathTracker().
Referenced by rawPathTracker(), rawPathTrackerPrecookedSLPs(), and rawPathTrackerProjective().