Macaulay2 Engine: PathTracker::evaluate_slpHxtH
evaluate_slpHxtH()
void PathTracker::evaluate_slpHxtH (int n, const complex * x0t0, complex * HxtH) inline private
Definition at line 604 of file NAG.hpp.
  {
    if (is_projective)
      ERROR("not implemented");
    else
      slpHxtH->evaluate(n + 1, x0t0, HxtH);
  }
References ERROR(), StraightLineProgram::evaluate(), is_projective, and slpHxtH.
Referenced by track().