Macaulay2 Engine: PathTracker::make
make() [2/3]
PathTracker * PathTracker::make (const Matrix * S, const Matrix * T, gmp_RR productST) static
Definition at line 1436 of file NAG.cpp.
     {
       StraightLineProgram* slp = StraightLineProgram::make(R, T->elem(0, i));
       if (p->slpT == nullptr)
         p->slpT = slp;
       else
         {
           StraightLineProgram* t = p->slpT->concatenate(slp);
           delete slp;
           delete p->slpT;
           p->slpT = t;
         }
     }
   p->slpTx = p->slpT->jacobian(false, p->slpHxH /*not used*/, true, p->slpTxT);
   return p;
 }
References mpfr::acos(), cast_to_CCC(), Ring::cast_to_PolyRing(), degree_ring_elem(), Matrix::elem(), ERROR(), Matrix::get_ring(), StraightLineProgram::make(), Matrix::n_cols(), Matrix::n_rows(), newarray_atomic, p, PathTracker(), productST, FreeModule::R, S, mpfr::sqrt(), and T.