Macaulay2 Engine: PathTracker::evaluate_slpHxt
evaluate_slpHxt()
void PathTracker::evaluate_slpHxt (int n, const complex * x0t0, complex * Hxt) inline private
Definition at line 567 of file NAG.hpp.
   {
     if (is_projective)
       {
         complex* SxS = newarray_atomic(complex, (n + 1) * (n - 1));
         complex* TxT = newarray_atomic(complex, (n + 1) * (n - 1));
         const complex *x0 = x0t0, *t0 = x0t0 + n;
         const double t = (*(double*)t0) * bigT;  // t0 should be real
         slpSxS->evaluate(n, x0, SxS);
         slpTxT->evaluate(n, x0, TxT);
         double c = cos(t), s = sin(t),
                sqrt_one_minus_productST_2 = sqrt(1 - productST * productST);
         double mS = c - productST * s / sqrt_one_minus_productST_2;
         double mT = s / sqrt_one_minus_productST_2;
         int j, i;
         for (j = 0; j < n - 1; j++)
           for (i = 0; i < n; i++)
             *(Hxt + i * n + j) =
                 *(SxS + i * (n - 1) + j) * mS + *(TxT + i * (n - 1) + j) * mT;
         j = n - 1;  // last column
         for (i = 0; i < n; i++) *(Hxt + i * n + j) = (x0 + i)->getconjugate();
         i = n;  // last row = H_t
         mS = -s - productST * c / sqrt_one_minus_productST_2;
         mT = c / sqrt_one_minus_productST_2;
         for (j = 0; j < n - 1; j++)
           {
             complex tt =
                 *(SxS + i * (n - 1) + j) * mS + *(TxT + i * (n - 1) + j) * mT;
             *(Hxt + i * n + j) = tt;
           }
         *(Hxt + n * n + n - 1) = complex(0.);  // last row and column
         freemem(SxS);
         freemem(TxT);
       }
     else
       slpHxt->evaluate(n + 1, x0t0, Hxt);
   }
References bigT, mpfr::cos(), StraightLineProgram::evaluate(), freemem(), is_projective, newarray_atomic, productST, mpfr::sin(), slpHxt, slpSxS, slpTxT, and mpfr::sqrt().
Referenced by track().