Macaulay2 Engine: PathTracker::getSolutionRcond
getSolutionRcond()
gmp_RRorNull PathTracker::getSolutionRcond (int solN)
Definition at line 2149 of file NAG.cpp.
 {
   if (solN < 0 || solN >= n_sols) return nullptr;
   gmp_RRmutable result = getmemstructtype(gmp_RRmutable);
   mpfr_init2(result, C->get_precision());
   mpfr_set_d(result, raw_solutions[solN].cond, MPFR_RNDN);
   return moveTo_gmpRR(result);
 }
References C, M2::ConcreteRing< RingType >::get_precision(), getmemstructtype, moveTo_gmpRR(), n_sols, and raw_solutions.
Referenced by rawGetSolutionRcondPT().