Macaulay2 Engine: PathTracker::getSolution
getSolution()
Matrix * PathTracker::getSolution (int solN)
Definition at line 2074 of file NAG.cpp.
References C, from_doubles(), complex::getimaginary(), complex::getreal(), Ring::make_FreeModule(), n_coords, n_sols, raw_solutions, MatrixConstructor::set_entry(), MatrixConstructor::to_matrix(), and Solution::x.
Referenced by rawGetSolutionPT().