Macaulay2 Engine: MyIdealConsumer::consume
consume()
virtual void MyIdealConsumer::consume (mpz_ptr * exponentVector) inline virtual
Definition at line 301 of file monomial-ideal.cpp.
   {
     // insert into J.  This is a minimal generator of J
     for (int i = 0; i < nv; i++)
       exp[i] = static_cast<int>(mpz_get_si(
           exponentVector[i]));  // overflow should not occur, as input fit
     if (M2_gbTrace >= 5)
       {
         fprintf(stderr, "got ");
         for (int j = 0; j < nv; j++) fprintf(stderr, "%d ", exp[j]);
         fprintf(stderr, "\n");
       }
     Bag *b = new Bag();
     varpower::from_expvector(nv, exp, b->monom());
     J->insert_minimal(b);
   }
References exp, ExponentList< E, L >::from_expvector(), MonomialIdeal::insert_minimal(), J, M2_gbTrace, int_bag::monom(), and nv.