Macaulay2 Engine: norm2
norm2()
template<typename RT > void norm2 (const DMat< RT > & M, size_t n, typename RT::RealElementType & result) inline
Definition at line 299 of file SLP-imp.hpp.
 {
   const auto& C = M.ring();
   const auto& R = C.real_ring();
   typename RT::RealRingType::Element c(R);
   R.set_zero(result);
   for (size_t i = 0; i < n; i++)
     {
       C.abs_squared(c, M.entry(0, i));
       R.add(result, result, c);
     }
 }
References DMat< ACoeffRing >::entry(), and DMat< ACoeffRing >::ring().
Referenced by HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track().