Macaulay2 Engine: NCResComputation::get_free
get_free()
const FreeModule * NCResComputation::get_free (int level) inline protected virtual
Implements ResolutionComputation.
Definition at line 48 of file nc-res-computation.hpp.
References Matrix::cols(), Matrix::get_ring(), Ring::make_FreeModule(), mInputModuleGB, and Matrix::rows().
Referenced by get_matrix().