Macaulay2 Engine: ffpackInterface::rank
rank() [2/2]
size_t ffpackInterface::rank (const DMatZZpFFPACK & A)
Referenced by FreeModule::direct_sum(), FreeModule::exterior(), SchreyerOrder::exterior(), IM2_FreeModule_make(), IM2_FreeModule_make_degs(), SchreyerOrder::is_equal(), Lapack::least_squares_deficient(), Matrix::operator+(), Matrix::operator-(), DMatLinAlg< M2::ARingZZpFFPACK >::rank(), gb2_comp::receive_generator(), FreeModule::shift(), DMatLinAlg< RingType >::solveInvertible(), FreeModule::tensor(), and SchreyerOrder::tensor().