Macaulay2 Engine: rawMonomialMinimalPrimes
rawMonomialMinimalPrimes()
const MonomialIdeal* rawMonomialMinimalPrimes (const MonomialIdeal * I, int codim_limit, int count)
Definition at line 230 of file monomial-ideal.cpp.
 {
   try
     {
       MinimalPrimes ap(I);
       MonomialIdeal *result = ap.alg1_min_primes(codim_limit, count);
       intern_monideal(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References MinimalPrimes::alg1_min_primes(), ERROR(), and intern_monideal().