Macaulay2 Engine: rawColonMonomialIdeal2
rawColonMonomialIdeal2()
const MonomialIdeal* rawColonMonomialIdeal2 (const MonomialIdeal * I, const MonomialIdeal * J)
Definition at line 136 of file monomial-ideal.cpp.
 {
   try
     {
       if (I->get_ring() != J->get_ring())
         {
           ERROR("expected ideals in the same ring");
           return nullptr;
         }
       MonomialIdeal *result = I->quotient(*J);
       intern_monideal(result);
       if (M2_gbTrace >= 1) dstash();
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References dstash(), ERROR(), MonomialIdeal::get_ring(), intern_monideal(), M2_gbTrace, and MonomialIdeal::quotient().