Macaulay2 Engine: IM2_MonomialIdeal_make
IM2_MonomialIdeal_make()
engine_RawMonomialIdealOrNull IM2_MonomialIdeal_make (const Matrix * m, int n)
MonomialIdeal interface routines
A MonomialIdeal is an immutable object, having a base ring. The base ring should be a polynomial ring or quotient of one. In case a quotient is given, the monomial ideal is considered to be in the commutative quotient ring whose quotient elements are the lead terms of the quotient polynomials. Each monomial ideal is represented by its minimal generators only
Definition at line 25 of file monomial-ideal.cpp.
 {
   try
     {
       MonomialIdeal *result = m->make_monideal(n);
       intern_monideal(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References ERROR(), intern_monideal(), and Matrix::make_monideal().