Macaulay2 Engine: IM2_MonomialIdeal_borel
IM2_MonomialIdeal_borel()
const MonomialIdeal* IM2_MonomialIdeal_borel (const MonomialIdeal * I)
Definition at line 196 of file monomial-ideal.cpp.
 {
   try
     {
       MonomialIdeal *result = I->borel();
       intern_monideal(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References MonomialIdeal::borel(), ERROR(), and intern_monideal().