Macaulay2 Engine: IM2_MonomialIdeal_intersect
IM2_MonomialIdeal_intersect()
const MonomialIdeal* IM2_MonomialIdeal_intersect (const MonomialIdeal * I, const MonomialIdeal * J)
Definition at line 97 of file monomial-ideal.cpp.
 {
   try
     {
       if (I->get_ring() != J->get_ring())
         {
           ERROR("expected ideals in the same ring");
           return nullptr;
         }
       MonomialIdeal *result = I->intersect(*J);
       intern_monideal(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References ERROR(), MonomialIdeal::get_ring(), intern_monideal(), and MonomialIdeal::intersect().