Macaulay2 Engine: rawRadicalMonomialIdeal
rawRadicalMonomialIdeal()
const MonomialIdeal* rawRadicalMonomialIdeal (const MonomialIdeal * I)
Definition at line 81 of file monomial-ideal.cpp.
 {
   try
     {
       MonomialIdeal *result = I->radical();
       intern_monideal(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References ERROR(), intern_monideal(), and MonomialIdeal::radical().