Macaulay2 Engine: DegreeZeroMapGenerator::numNonzero
numNonzero()
long DegreeZeroMapGenerator::numNonzero () const inline
Definition at line 421 of file res-f4-m2-interface.cpp.
   {
     long nnonzeros = 0;
     auto& thislevel = mSchreyerFrame.level(mLevel);
     for (auto p = thislevel.begin(); p != thislevel.end(); ++p)
       {
         if (p->mDegree != mDegree) continue;
         auto& f = p->mSyzygy;
         auto end = ResPolynomialIterator(mSchreyerFrame.ring(), f, 1);
         auto i = ResPolynomialIterator(mSchreyerFrame.ring(), f);
         for (; i != end; ++i)
           {
             auto comp = mSchreyerFrame.monoid().get_component(i.monomial());
             if (mComponentTranslation[comp] >= 0)
               nnonzeros++;
           }
       }
     return nnonzeros;
   }
References end(), ResMonoidDense::get_component(), SchreyerFrame::level(), mComponentTranslation, mDegree, mLevel, SchreyerFrame::monoid(), mSchreyerFrame, p, and SchreyerFrame::ring().
Referenced by SchreyerFrame::rank().