Macaulay2 Engine: NaiveDedupPolynomialHeap::value
value()
template<template< typename > class Queue> Poly * NaiveDedupPolynomialHeap< Queue >::value () inline override virtual
Implements PolynomialHeap.
Definition at line 526 of file NCReduction.cpp.
  {
    Poly* f = new Poly;
    while (not isZero())
      {
        auto tm = viewLeadTerm();
        mRing.add_to_end(*f, tm.second, tm.first);
        removeLeadTerm();
      }
    addPolynomial(*f);
    return f;
  }
References FreeAlgebra::add_to_end(), NaiveDedupPolynomialHeap< Queue >::addPolynomial(), NaiveDedupPolynomialHeap< Queue >::isZero(), NaiveDedupPolynomialHeap< Queue >::mRing, NaiveDedupPolynomialHeap< Queue >::removeLeadTerm(), and NaiveDedupPolynomialHeap< Queue >::viewLeadTerm().