Macaulay2 Engine: NaiveDedupPolynomialHeap::addPolynomial
addPolynomial() [1/2]
template<template< typename > class Queue> NaiveDedupPolynomialHeap & NaiveDedupPolynomialHeap< Queue >::addPolynomial (const Poly & poly) inline override virtual
Implements PolynomialHeap.
Definition at line 480 of file NCReduction.cpp.
  {
    for (auto i = poly.cbegin(); i != poly.cend(); ++i)
      {
        auto rg = mMonomialSpace.allocateArray<int>(i.monom().size());
        std::copy(i.monom().begin(), i.monom().end(), rg.first);
        mQueue.push(Entry(Monom(rg.first), i.coeff()));
      }
    return *this;
  }
References MemoryBlock::allocateArray(), NaiveDedupPolynomialHeap< Queue >::mMonomialSpace, and NaiveDedupPolynomialHeap< Queue >::mQueue.
Referenced by NaiveDedupPolynomialHeap< Queue >::addPolynomial(), and NaiveDedupPolynomialHeap< Queue >::value().