Macaulay2 Engine: NaiveDedupPolynomialHeap::isZero
isZero()
template<template< typename > class Queue> bool NaiveDedupPolynomialHeap< Queue >::isZero () inline override virtual
Implements PolynomialHeap.
Definition at line 502 of file NCReduction.cpp.
   {
     // idempotent function.
     while (not mQueue.empty())
       {
         Entry e = mQueue.top();
         if (mRing.coefficientRing()->is_zero(e.second))
           mQueue.pop();
         else
           return false;
       }
     return true;
   }
References FreeAlgebra::coefficientRing(), Ring::is_zero(), NaiveDedupPolynomialHeap< Queue >::mQueue, and NaiveDedupPolynomialHeap< Queue >::mRing.
Referenced by NaiveDedupPolynomialHeap< Queue >::value().