Macaulay2 Engine: schur_poly_heap::value
value()
ring_elem schur_poly_heap::value () inline
Definition at line 59 of file schur-poly-heap.hpp.
 {
   ring_elem result = S->zero();
   for (int i = 0; i <= top_of_heap; i++)
     {
       if (S->size(heap[i]) == 0) continue;
       add_to(result, heap[i]);
     }
   top_of_heap = -1;
   return result;
 }
References add_to(), heap, S, SchurRing2::size(), top_of_heap, and Ring::zero().
Referenced by SchurRing2::mult(), and SchurRing2::skew_schur().