Macaulay2 Engine: schur_poly_heap::add_to
add_to()
void schur_poly_heap::add_to (ring_elem & a, ring_elem & b) inline private
Definition at line 29 of file schur-poly-heap.hpp.
 {
   ring_elem c = S->add(a, b);
   a = c;
   b = S->zero();
 }
References SchurRing2::add(), S, and Ring::zero().
Referenced by add(), and value().