Macaulay2 Engine: M2::ARingRR::eval
eval()
void M2::ARingRR::eval (const RingMap * map, ElementType & f, int first_var, ring_elem & result) const inline
Definition at line 224 of file aring-RR.hpp.
   {
     if (!map->get_ring()->from_double(f, result))
       {
         result = map->get_ring()->from_long(0);
         ERROR("cannot map double to ring type");
       }
   }
References ERROR(), Ring::from_double(), Ring::from_long(), and RingMap::get_ring().