Macaulay2 Engine: M2::ARingRR::power
power()
void M2::ARingRR::power (ElementType & result, const ElementType & a, int n) const inline
Definition at line 180 of file aring-RR.hpp.
   {
     result = pow(a, n);
   }
References mpfr::pow().
Referenced by power_mpz(), and TEST().