Macaulay2 Engine: M2::ARingTower::reset_degree
reset_degree()
void M2::ARingTower::reset_degree (ARingPolynomial & f) const private
Definition at line 116 of file aring-tower.cpp.
 {
   if (f == nullptr) return;
   int fdeg = f->deg;
   for (int j = fdeg; j >= 0; --j)
     if (f->polys[j] != nullptr)
       {
         f->deg = j;
         return;
       }
   // at this point, everything is 0!
   dealloc_poly(f);  // sets f to 0
 }
References dealloc_poly(), M2::ARingPolynomialStruct::deg, and M2::ARingPolynomialStruct::polys.
Referenced by add_in_place(), and subtract_in_place().