Macaulay2 Engine: M2::ARingTower::subtract_in_place
subtract_in_place()
void M2::ARingTower::subtract_in_place (int level, ARingPolynomial & f, const ARingPolynomial g) const private
Definition at line 372 of file aring-tower.cpp.
 {
   if (g == nullptr) return;
   if (f == nullptr)
     {
       f = copy(level, g);
       negate_in_place(level, f);
       return;
     }
   int fdeg = f->deg;
   int gdeg = g->deg;
   increase_capacity(g->deg, f);
   if (level == 0)
     for (int i = 0; i <= gdeg; i++)
       mBaseRing.subtract(f->coeffs[i], f->coeffs[i], g->coeffs[i]);
   else
     for (int i = 0; i <= gdeg; i++)
       subtract_in_place(level - 1, f->polys[i], g->polys[i]);
   if (gdeg > fdeg)
     f->deg = gdeg;
   else if (gdeg == fdeg)
     reset_degree(f);
 }
References M2::ARingPolynomialStruct::coeffs, copy(), M2::ARingPolynomialStruct::deg, increase_capacity(), mBaseRing, negate_in_place(), M2::ARingPolynomialStruct::polys, reset_degree(), and M2::ARingZZpFFPACK::subtract().
Referenced by subtract().