Macaulay2 Engine: M2::ARingTower::add_in_place
add_in_place()
void M2::ARingTower::add_in_place (int level, ARingPolynomial & f, const ARingPolynomial g) const private
Definition at line 331 of file aring-tower.cpp.
 {
   if (g == nullptr) return;
   if (f == nullptr)
     {
       f = copy(level, g);
       return;
     }
   int fdeg = f->deg;
   int gdeg = g->deg;
   increase_capacity(g->deg, f);
   if (level == 0)
     for (int i = 0; i <= gdeg; i++)
       mBaseRing.add(f->coeffs[i], f->coeffs[i], g->coeffs[i]);
   else
     for (int i = 0; i <= gdeg; i++)
       add_in_place(level - 1, f->polys[i], g->polys[i]);
   if (gdeg > fdeg)
     f->deg = gdeg;
   else if (gdeg == fdeg)
     reset_degree(f);
 }
References M2::ARingZZpFFPACK::add(), M2::ARingPolynomialStruct::coeffs, copy(), M2::ARingPolynomialStruct::deg, increase_capacity(), mBaseRing, M2::ARingPolynomialStruct::polys, and reset_degree().
Referenced by add().