Macaulay2 Engine: M2::ARingTower::mult_by_coeff
mult_by_coeff() [2/2]
void M2::ARingTower::mult_by_coeff (int level, ARingPolynomial & f, const BaseCoefficientType & b) const private
Definition at line 398 of file aring-tower.cpp.
{
  assert(!mBaseRing.is_zero(b));
  if (f == nullptr) return;
  long deg = f->deg;
  if (level == 0)
    {
      for (int i = 0; i <= deg; i++)
        if (f->coeffs[i] != 0) mBaseRing.mult(f->coeffs[i], f->coeffs[i], b);
    }
  else
    {
      for (int i = 0; i <= deg; i++)
        if (f->polys[i] != nullptr) mult_by_coeff(level - 1, f->polys[i], b);
    }
}
References M2::ARingPolynomialStruct::coeffs, M2::ARingPolynomialStruct::deg, M2::ARingZZpFFPACK::is_zero(), mBaseRing, M2::ARingZZpFFPACK::mult(), mult_by_coeff(), and M2::ARingPolynomialStruct::polys.