Macaulay2 Engine: M2::ARingTower::create
create() [1/3]
ARingTower * M2::ARingTower::create (const ARingTower & R, const std::vector< ElementType > & extensions) static
Definition at line 55 of file aring-tower.cpp.
 {
   // TODO: check that 'extensions' has the correct form for R.
   //  if not: throw an exception
   //  else:
   return new ARingTower(R.baseRing(), R.varNames(), extensions);
 }
References ARingTower(), baseRing(), and varNames().