Macaulay2 Engine: M2::ARingTower::mult_by_coeff
mult_by_coeff() [1/2]
void M2::ARingTower::mult_by_coeff (ARingPolynomial & f, const BaseCoefficientType & b) const
Definition at line 418 of file aring-tower.cpp.
 {
   if (f == 0) return;
   if (mBaseRing.is_zero(b))
     {
       clear(f);
       return;
     }
   // TODO: add this line one is_one is implemented in ZZpFFPACK: if
   // (mBaseRing.is_one(b)) return;
   mult_by_coeff(mStartLevel, f, b);
 }
References clear(), M2::ARingZZpFFPACK::is_zero(), mBaseRing, and mStartLevel.
Referenced by mult_by_coeff().