Macaulay2 Engine: M2::ARingTower::copy
copy() [1/2]
void M2::ARingTower::copy (elem & result, elem a) const inline
Definition at line 189 of file aring-tower.hpp.
 { result = copy(mStartLevel, a); }
References copy(), and mStartLevel.
Referenced by add(), add_in_place(), copy(), negate(), subtract(), and subtract_in_place().