Macaulay2 Engine: M2::ARingTower::create
create() [3/3]
ARingTower * M2::ARingTower::create (const BaseRingType & baseRing, const std::vector< std::string > & names) static
Definition at line 41 of file aring-tower.cpp.
{
  std::vector<ElementType> extensions;
  return new ARingTower(baseRing, names, extensions);
}
References baseRing().
Referenced by rawARingTower1(), rawARingTower2(), and rawARingTower3().