Macaulay2 Engine: dmatrix
dmatrix()
void dmatrix (const Matrix * M)
Definition at line 52 of file debug.cpp.
 {
   buffer o;
   M->text_out(o);
   emit(o.str());
 }
References emit(), buffer::str(), and Matrix::text_out().