Macaulay2 Engine: dstash
dstash()
void dstash ()
Definition at line 118 of file debug.cpp.
 {
   buffer o;
   stash::stats(o);
   emit(o.str());
 }
References emit(), stash::stats(), and buffer::str().
Referenced by rawColonMonomialIdeal2().