Macaulay2 Engine: dintarray
dintarray()
void dintarray (M2_arrayint a)
Definition at line 19 of file debug.cpp.
 {
   buffer o;
   o << "[";
   for (int i = 0; i < a->len; i++)
     {
       if (i > 0) o << ", ";
       o << a->array[i];
     }
   o << "]";
   emit(o.str());
 }
References emit(), and buffer::str().
Referenced by TEST().