Macaulay2 Engine: schur_poly::append
append()
void schur_poly::append (iterator & first, iterator & last)
Definition at line 122 of file schur2.cpp.
 {
   for (; first != last; ++first)
     appendTerm(first.getCoefficient(), first.getMonomial());
 }
References appendTerm(), schur_poly_iterator::getCoefficient(), and schur_poly_iterator::getMonomial().
Referenced by SchurRing2::add().