Macaulay2 Engine: schur_poly::appendTerm
appendTerm()
void schur_poly::appendTerm (ring_elem coeff, const_schur_partition monom)
Definition at line 117 of file schur2.cpp.
 {
   coeffs.push_back(coeff);
   for (int i = 0; i < monom[0]; i++) monoms.push_back(monom[i]);
 }
References coeffs, and monoms.
Referenced by SchurRing2::add(), append(), SchurRing2::lift_coeffs(), SchurRing2::promote_coeffs(), SchurRing2::SMappendTerm(), and SchurRing2::truncate().