Macaulay2 Engine: schur_poly::end
end()
schur_poly::iterator schur_poly::end () const inline
Definition at line 98 of file schur2.hpp.
 {
   return iterator(*this, 1);
 }
Referenced by SchurRing2::add(), SchurRing2::compare_elems(), SchurRing2::elem_text_out(), SchurRing2::lift_coeffs(), SchurRing2::mult(), SchurRing2::promote_coeffs(), and SchurRing2::truncate().