Macaulay2 Engine: SuffixTree::subwords
subwords() [1/2]
auto SuffixTree::subwords (const Word & w, std::vector< std::pair< int, int > > & output, bool onlyFirst) const -> bool
Definition at line 477 of file SuffixTree.cpp.
{
  // this command returns a pair (i,j) where word i in the table appears
  // in position j of word.
  auto cLocus = mRoot;
  auto beta = Word();
  Word tmpLabel = w;
  int pos = 0;
  bool retval = false;
  std::cout << *(this->mRoot) << std::endl;
  std::cout << w << std::endl;
  while (tmpLabel.size() != 0)
    {
      SubwordsType swType;
      if (cLocus == mRoot)
        swType = subwordsStepD(mRoot,tmpLabel);
      else
        swType = subwordsStepC(cLocus->suffixLink(),beta,tmpLabel);
      auto newcLocus = std::get<0>(swType);
      auto newbeta = std::get<1>(swType);
      auto leaf = std::get<2>(swType);
      auto wasPattern = std::get<3>(swType);
      //if (wasPattern && isPatternPrefix(leaf->label(),tmpLabel,newcLocus->label().size()+newbeta.size()))
      if (wasPattern && isPatternPrefix(Word(leaf->label()),tmpLabel))
        {
          std::cout << Word(leaf->label()) << " " << tmpLabel << std::endl << std::flush;
          auto tmp = std::make_pair(leaf->getPatternNumber(),pos);
          output.push_back(tmp);
          retval = true;
          if (onlyFirst) return true;
        }
      pos++;
      cLocus = newcLocus;
      beta = newbeta;
      tmpLabel = suffix(tmpLabel,1);
      std::cout << *cLocus << " " << tmpLabel << std::endl;
    }
  return retval;
}
References isPatternPrefix(), Word::size(), and suffix().