Macaulay2 Engine: PointArray::lookup
lookup()
int PointArray::lookup (const RealVector & a) const inline
Definition at line 84 of file NAG.hpp.
  {
    Weight w = weight(a);
    auto le = left(w);
    auto ri = right(w);
    for (auto i = le; i != ri; ++i)
      if (are_same(mPoints[i->second], a)) return i->second;
    return -1;
  }
References are_same(), left(), mPoints, right(), and weight().
Referenced by lookup_or_append(), and rawPointArrayLookup().