Macaulay2 Engine: M2::ARingQQFlint::elem_text_out
elem_text_out()
void M2::ARingQQFlint::elem_text_out (buffer & o, const ElementType & a, bool p_one = true, bool p_plus = false, bool p_parens = false) const
Definition at line 37 of file aring-qq-flint.cpp.
 {
   char s[1000];
   char* str;
   bool is_neg = (fmpq_sgn(&a) == -1);
   bool one = is_pm_one(a);
   size_t size = fmpz_sizeinbase(fmpq_numref(&a), 10) +
                 fmpz_sizeinbase(fmpq_denref(&a), 10) + 3;
   char* allocstr = (size > 1000 ? newarray_atomic(char, size) : s);
   // std::cout << "size = " << size << std::endl;
   if (!is_neg && p_plus) o << '+';
   if (one)
     {
       if (is_neg) o << '-';
       if (p_one) o << '1';
     }
   else
     {
       str = fmpq_get_str(allocstr, 10, &a);
       o << str;
     }
   // std::cout << "output = " << o.str() << std::endl;
   if (size > 1000) freemem(allocstr);
 }
References freemem(), is_pm_one(), and newarray_atomic.
Referenced by TEST().