Macaulay2 Engine: M2::ARingQQFlint::syzygy
syzygy()
void M2::ARingQQFlint::syzygy (const ElementType & a, const ElementType & b, ElementType & x, ElementType & y) const
Definition at line 70 of file aring-qq-flint.cpp.
 {
   assert(!is_zero(b));
   set_from_long(x, 1);
   divide(y, a, b);
   negate(y, y);
 }
References divide(), is_zero(), negate(), set_from_long(), and x.