Macaulay2 Engine: M2::ARingQQFlint::promote
promote()
bool M2::ARingQQFlint::promote (const Ring * Rf, const ring_elem f, ElementType & result) const inline
Definition at line 252 of file aring-qq-flint.hpp.
   {
     // printf("ARingQQFlint::calling promote\n");
     // Rf = ZZ ---> QQ
     if (Rf->is_ZZ())
       {
         set_from_mpz(result, f.get_mpz());
         return true;
       }
     return false;
   }
References ring_elem::get_mpz(), Ring::is_ZZ(), and set_from_mpz().