Macaulay2 Engine: GBinhom_comp::debug_pairs_out
debug_pairs_out() [2/2]
void GBinhom_comp::debug_pairs_out (gb_elem * p) const
Definition at line 978 of file gb-sugarless.cpp.
{
  buffer o;
  debug_pairs_out(o, p);
  emit(o.str());
}
References debug_pairs_out(), emit(), p, and buffer::str().
Referenced by debug_pairs(), and debug_pairs_out().