Macaulay2 Engine: GBinhom_comp::get_mingens
get_mingens()
const Matrix * GBinhom_comp::get_mingens () virtual
Implements GBComputation.
Definition at line 895 of file gb-sugarless.cpp.
 {
   MatrixConstructor mat(F, 0);
   for (gb_elem *q = gb->next; q != NULL; q = q->next)
     if (q->is_min & MINGEN_MASK)
       mat.append(originalR->translate_gbvector_to_vec(F, q->f));
   return mat.to_matrix();
 }
References MatrixConstructor::append(), F, gb, MINGEN_MASK, gb_elem::next, originalR, MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().