Macaulay2 Engine: GBinhom_comp::gb_reduce
gb_reduce()
int GBinhom_comp::gb_reduce (gbvector *& f, gbvector *& fsyz) private
Definition at line 459 of file gb-sugarless.cpp.
 {
   if ((strategy & STRATEGY_LONGPOLYNOMIALS) != 0) return gb_geo_reduce(f, fsyz);
   gbvector head;
   gbvector *result = &head;
   result->next = 0;
   gb_elem *q;
   exponents_t div_totalexp = newarray_atomic(int, M->n_vars());
   int count = 0;
   if (M2_gbTrace == 10)
     {
       buffer o;
       o << "reducing ";
       GR->gbvector_text_out(o, F, f);
       emit_line(o.str());
     }
   while (f != NULL)
     {
       GR->gbvector_get_lead_exponents(F, f, div_totalexp);
 #ifdef DEVELOPMENT
 #warning "quotient ring stuff"
 #endif
       Bag *b;
       if (originalR->is_quotient_ring() &&
           originalR->get_quotient_monomials()->search_expvector(div_totalexp,
                                                                 b))
         {
           const gbvector *g = originalR->quotient_gbvector(b->basis_elem());
           GR->gbvector_reduce_lead_term(F, Fsyz, head.next, f, fsyz, g, 0);
           count++;
         }
       else if (search(div_totalexp, f->comp, q))
         {
           GR->gbvector_reduce_lead_term(
               F, Fsyz, head.next, f, fsyz, q->f, q->fsyz);
           count++;
         }
       else
         {
           result->next = f;
           f = f->next;
           result = result->next;
           result->next = 0;
         }
     }
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << "." << count;
       emit(o.str());
     }
   f = head.next;
   freemem(div_totalexp);
   return 1;
 }
References int_bag::basis_elem(), gbvector::comp, emit(), emit_line(), F, gb_elem::f, freemem(), Fsyz, gb_elem::fsyz, gb_geo_reduce(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_reduce_lead_term(), GBRing::gbvector_text_out(), PolynomialRing::get_quotient_monomials(), GR, PolynomialRing::is_quotient_ring(), M, M2_gbTrace, Monoid::n_vars(), newarray_atomic, gbvector::next, originalR, PolynomialRing::quotient_gbvector(), search(), MonomialIdeal::search_expvector(), buffer::str(), strategy, and STRATEGY_LONGPOLYNOMIALS.
Referenced by s_pair_step().