Macaulay2 Engine: GBinhom_comp::minimalize_gb
minimalize_gb()
void GBinhom_comp::minimalize_gb () private
Definition at line 835 of file gb-sugarless.cpp.
 {
   if (minimal_gb_valid) return;
   VECTOR(POLY) polys;
   for (gb_elem *q = gb->next_min; q != NULL; q = q->next_min)
     {
       POLY g;
       g.f = q->f;
       g.fsyz = q->fsyz;
       polys.push_back(g);
     }
   minimal_gb->minimalize(polys);
   minimal_gb_valid = true;
 }
References POLY::f, POLY::fsyz, gb, minimal_gb, minimal_gb_valid, ReducedGB::minimalize(), gb_elem::next_min, and VECTOR().
Referenced by contains(), get_change(), get_gb(), get_initial(), get_parallel_lead_terms(), matrix_lift(), and matrix_remainder().