Macaulay2 Engine: GBinhom_comp::add_gens
add_gens()
void GBinhom_comp::add_gens (int lo, int hi, const Matrix * m)
Definition at line 86 of file gb-sugarless.cpp.
 {
   // MES
   // First incorporate the new generators.
   // 2. inter-reduce them, so they have different lead terms
   // 3. insert them into gb, gbLarge
   // 4. each insertion will also call find_pairs.
   // MES: should we inter-reduce these first?  Does it matter?
   for (int i = hi; i >= lo; i--)
     {
       ring_elem denom;
       gbvector *f = originalR->translate_gbvector_from_vec(F, (*m)[i], denom);
       s_pair *p = new_gen(i, f, denom);
       if (p != NULL) spairs->insert(p);
       n_pairs++;
     }
 }
References F, s_pair_heap::insert(), n_pairs, new_gen(), originalR, p, spairs, and PolynomialRing::translate_gbvector_from_vec().
Referenced by set_up().