Macaulay2 Engine: GBinhom_comp::search
search()
int GBinhom_comp::search (const int * exp, int comp, gb_elem *& result) private
Definition at line 593 of file gb-sugarless.cpp.
 {
   int nvars = M->n_vars();
   int *exp2;
   for (gb_elem *p = gbLarge->next; p != NULL; p = p->next)
     {
       if (p->f->comp != comp) continue;
       exp2 = p->lead_exp;
       int is_div = 1;
       for (int i = 0; i < nvars; i++)
         if (exp2[i] > exp[i])
           {
             is_div = 0;
             break;
           }
       if (is_div)
         {
           result = p;
           return 1;
         }
     }
   return 0;
 }
References mpfr::exp(), mpfr::exp2(), gbLarge, M, Monoid::n_vars(), gb_elem::next, and p.
Referenced by gb_geo_reduce(), and gb_reduce().