Macaulay2 Engine: GBinhom_comp::debug_pairs
debug_pairs() [2/2]
void GBinhom_comp::debug_pairs (buffer & o) const
Definition at line 1003 of file gb-sugarless.cpp.
 {
   for (gb_elem *p = gbLarge->next; p != nullptr; p = p->next)
     debug_pairs_out(o, p);
   for (int i = 0; i < NHEAP; i++)
     {
       s_pair *q = spairs->debug_list(i);
       if (q == nullptr) continue;
       o << "---- pairs in bin " << i << " -----" << newline;
       int n = 0;
       for (; q != nullptr; q = q->next)
         {
           debug_out(o, q);
           n++;
           if (n % 10 == 0) o << newline;
         }
       o << newline;
     }
 }
References s_pair_heap::debug_list(), debug_out(), debug_pairs_out(), gbLarge, newline, gb_elem::next, s_pair::next, NHEAP, p, and spairs.