Macaulay2 Engine: GBinhom_comp::create
create()
GBinhom_comp * GBinhom_comp::create (const Matrix * m, M2_bool collect_syz, int n_rows_to_keep, M2_arrayint gb_weights, int strategy, M2_bool use_max_degree, int max_degree) static
Definition at line 105 of file gb-sugarless.cpp.
 {
   const PolynomialRing *P = m->get_ring()->cast_to_PolynomialRing();
   if (P == nullptr || P->getCoefficients()->is_ZZ())
     {
       ERROR("expected polynomial ring over a field");
       return nullptr;
     }
   GBinhom_comp *result =
       new GBinhom_comp(m, collect_syz, n_rows_to_keep, gb_weights, strategy);
   return result;
 }
References Ring::cast_to_PolynomialRing(), collect_syz, ERROR(), GBinhom_comp(), Matrix::get_ring(), PolynomialRing::getCoefficients(), Ring::is_ZZ(), and strategy.
Referenced by GBComputation::choose_gb().