Macaulay2 Engine: GBinhom_comp::remove_pair
remove_pair()
void GBinhom_comp::remove_pair (s_pair *& p) private
Definition at line 133 of file gb-sugarless.cpp.
 {
   GR->gbvector_remove(p->f);
   GR->gbvector_remove(p->fsyz);
   p->first = nullptr;
   p->second = nullptr;
   p->next = nullptr;
   M->remove(p->lcm);
   freemem(p);
   p = nullptr;
 }
References freemem(), GBRing::gbvector_remove(), GR, M, p, and Monoid::remove().
Referenced by find_pairs(), and s_pair_step().