Macaulay2 Engine: GBinhom_comp::s_pair_step
s_pair_step()
int GBinhom_comp::s_pair_step (s_pair * p) private
Definition at line 674 of file gb-sugarless.cpp.
 {
   n_computed++;
   if (M2_gbTrace >= 8)
     {
       buffer o;
       o << "--- computing pair ";
       debug_out(o, p);
       o << " ----" << newline;
       emit(o.str());
     }
   int minlevel = (p->syz_type == SPAIR_GEN);
   int compute_pair = (p->compare_num >= 0);  // MES: change field name
   if (compute_pair)
     {
       compute_s_pair(p);
       if (!gb_reduce(p->f, p->fsyz)) return SPAIR_DEFERRED;
     }
   gbvector *f = p->f;
   gbvector *fsyz = p->fsyz;
   p->f = NULL;
   p->fsyz = NULL;
   if (p->first != NULL)
     {
       // Then 'p' should be the first element on the p->first->pair_list
       assert(p->first->pair_list == p);
       p->first->pair_list = p->next_same;
     }
   remove_pair(p);
   if (!compute_pair) return SPAIR_REMOVED;
   if (!GR->gbvector_is_zero(f))
     {
       gb_insert(f, fsyz, minlevel);
       if (M2_gbTrace >= 8)
         {
           buffer o;
           o << "  gb " << last_gb_num - 1 << " = ";
           GR->gbvector_text_out(o, F, f);
           emit_line(o.str());
         }
       return SPAIR_GB;
     }
   if (!GR->gbvector_is_zero(fsyz))
     {
       if (M2_gbTrace >= 8)
         {
           buffer o;
           o << "  syz = ";
           GR->gbvector_text_out(o, Fsyz, fsyz);
           emit_line(o.str());
         }
       if (collect_syz)
         {
           vec fsyzvec = originalR->translate_gbvector_to_vec(Fsyz, fsyz);
           n_syz++;
           syz.append(fsyzvec);
           return SPAIR_SYZ;
         }
       else
         GR->gbvector_remove(fsyz);
     }
   return SPAIR_ZERO;
 }
References MatrixConstructor::append(), collect_syz, compute_s_pair(), debug_out(), emit(), emit_line(), F, Fsyz, gb_insert(), gb_reduce(), GBRing::gbvector_is_zero(), GBRing::gbvector_remove(), GBRing::gbvector_text_out(), GR, last_gb_num, M2_gbTrace, n_computed, n_syz, newline, originalR, p, remove_pair(), SPAIR_DEFERRED, SPAIR_GB, SPAIR_GEN, SPAIR_REMOVED, SPAIR_SYZ, SPAIR_ZERO, buffer::str(), syz, and PolynomialRing::translate_gbvector_to_vec().
Referenced by start_computation().