Macaulay2 Engine: GBinhom_comp::start_computation
start_computation()
void GBinhom_comp::start_computation () virtual
Implements GBComputation.
Definition at line 764 of file gb-sugarless.cpp.
 {
   ComputationStatusCode is_done = COMP_COMPUTING;
   for (;;)
     {
       if (system_interrupted())
         {
           is_done = COMP_INTERRUPTED;
           break;
         }
       if (need_resize)
         {
           is_done = COMP_NEED_RESIZE;
           break;
         }
       is_done = computation_complete();
       if (is_done != COMP_COMPUTING) break;
       if (error())
         {
           is_done = COMP_ERROR;
           break;
         }
       s_pair *p = spairs->remove();
       if (p == NULL)
         {
           is_done = COMP_DONE;
           break;
         }
       int stype = s_pair_step(p);
       if (M2_gbTrace >= 3 && M2_gbTrace <= 7) switch (stype)
           {
             case SPAIR_GB:
               emit_wrapped("m");
               break;
             case SPAIR_SYZ:
               emit_wrapped("z");
               break;
             case SPAIR_ZERO:
               emit_wrapped("o");
               break;
             case SPAIR_REMOVED:
               emit_wrapped("r");
               break;
             default:
               emit_wrapped("ERROR");
               break;
           }
     }
   // MES: complete the reduction of the GB here
   if (M2_gbTrace >= 1) emit_line("");
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << "Number of pairs             = " << n_pairs << newline;
       o << "Number of gb elements       = " << n_gb << newline;
       o << "Number of gcd=1 pairs       = " << n_saved_gcd << newline;
       o << "Number of gcd tails=1 pairs = " << n_saved_lcm << newline;
       o << "Number of pairs computed    = " << n_computed << newline;
       emit(o.str());
     }
   set_status(is_done);
 }
References COMP_COMPUTING, COMP_DONE, COMP_ERROR, COMP_INTERRUPTED, COMP_NEED_RESIZE, computation_complete(), emit(), emit_line(), emit_wrapped(), error(), M2_gbTrace, n_computed, n_gb, n_pairs, n_saved_gcd, n_saved_lcm, need_resize, newline, p, s_pair_heap::remove(), s_pair_step(), Computation::set_status(), SPAIR_GB, SPAIR_REMOVED, SPAIR_SYZ, SPAIR_ZERO, spairs, buffer::str(), and system_interrupted().