Macaulay2 Engine: GBinhom_comp::mark_pair
mark_pair()
int GBinhom_comp::mark_pair (gb_elem * p, gb_elem * q) const private
Definition at line 234 of file gb-sugarless.cpp.
 {
   s_pair *r;
   for (r = p->pair_list; r != nullptr; r = r->next_same)
     if (r->second == q)
       {
         if (r->compare_num >= 0)
           {
             r->compare_num = -1;
             if (M2_gbTrace >= 8)
               {
                 buffer o;
                 o << "---- removed pair ";
                 debug_out(o, r);
                 emit_line(o.str());
               }
             return 1;
           }
         else
           return 0;
       }
   for (r = q->pair_list; r != nullptr; r = r->next_same)
     if (r->second == p)
       {
         if (r->compare_num >= 0)
           {
             r->compare_num = -1;
             if (M2_gbTrace >= 8)
               {
                 buffer o;
                 o << "---- removed pair ";
                 debug_out(o, r);
                 emit_line(o.str());
               }
             return 1;
           }
         else
           return 0;
       }
   return 0;
 }
References s_pair::compare_num, debug_out(), emit_line(), M2_gbTrace, s_pair::next_same, p, gb_elem::pair_list, s_pair::second, and buffer::str().
Referenced by find_pairs().