Macaulay2 Engine: GBinhom_comp::new_gen
new_gen()
s_pair * GBinhom_comp::new_gen (int i, gbvector * f, ring_elem denom) private
Definition at line 199 of file gb-sugarless.cpp.
 {
   gbvector *fsyz;
   if (i < n_comps_per_syz)
     fsyz = GR->gbvector_term(Fsyz, denom, i + 1);
   else
     fsyz = GR->gbvector_zero();
   if (GR->gbvector_is_zero(f))
     {
       if (!GR->gbvector_is_zero(fsyz))
         {
           vec fsyzvec = originalR->translate_gbvector_to_vec(Fsyz, fsyz);
           n_syz++;
           syz.append(fsyzvec);
         }
       return nullptr;
     }
   s_pair *result = new s_pair;
   result->next = nullptr;
   result->syz_type = SPAIR_GEN;
   result->degree = weightInfo_->gbvector_weight(f);
   result->compare_num = 0;
   result->first = nullptr;
   result->second = nullptr;
   result->f = f; /* NOTE THAT WE GRAB f */
   result->fsyz = fsyz;
   result->lcm = M->make_new(result->f->monom);
   return result;
 }
References MatrixConstructor::append(), s_pair::compare_num, s_pair::degree, s_pair::f, s_pair::first, Fsyz, s_pair::fsyz, GBRing::gbvector_is_zero(), GBRing::gbvector_term(), GBWeight::gbvector_weight(), GBRing::gbvector_zero(), GR, s_pair::lcm, M, Monoid::make_new(), gbvector::monom, n_comps_per_syz, n_syz, s_pair::next, originalR, s_pair::second, SPAIR_GEN, syz, s_pair::syz_type, PolynomialRing::translate_gbvector_to_vec(), and weightInfo_.
Referenced by add_gens().