Macaulay2 Engine: GBinhom_comp::debug_out
debug_out() [1/2]
void GBinhom_comp::debug_out (buffer & o, s_pair * q) const
Definition at line 945 of file gb-sugarless.cpp.
 {
   if (q == nullptr) return;
   monomial m = M->make_one();
   o << "(";
   if (q->first != nullptr)
     o << q->first->me;
   else
     o << ".";
   o << " ";
   if (q->second != nullptr)
     o << q->second->me;
   else
     o << ".";
   o << " ";
   if (q->first != nullptr)
     {
       M->divide(q->lcm, q->first->f->monom, m);
       M->elem_text_out(o, m);
       o << ' ';
     }
   if (q->second != nullptr)
     {
       M->divide(q->lcm, q->second->f->monom, m);
       M->elem_text_out(o, m);
       o << ' ';
     }
   M->elem_text_out(o, q->lcm);
   M->remove(m);
   if (q->compare_num < 0) o << " marked";
   o << ") ";
 }
References s_pair::compare_num, Monoid::divide(), Monoid::elem_text_out(), gb_elem::f, s_pair::first, s_pair::lcm, M, Monoid::make_one(), gb_elem::me, gbvector::monom, Monoid::remove(), and s_pair::second.