Macaulay2 Engine: GBinhom_comp::stats
stats()
void GBinhom_comp::stats () const
Definition at line 1023 of file gb-sugarless.cpp.
 {
   spairs->stats();
   buffer o;
   if (M2_gbTrace >= 5 && M2_gbTrace % 2 == 1)
     {
       int i = 0;
       for (gb_elem *q = gb->next_min; q != nullptr; q = q->next_min)
         {
           o << i << '\t';
           i++;
           GR->gbvector_text_out(o, F, q->f);
           o << newline;
         }
     }
   emit(o.str());
 }
References emit(), F, gb, GBRing::gbvector_text_out(), GR, M2_gbTrace, newline, gb_elem::next_min, spairs, s_pair_heap::stats(), and buffer::str().