Macaulay2 Engine: GBinhom_comp::compute_s_pair
compute_s_pair()
void GBinhom_comp::compute_s_pair (s_pair * p) private
Definition at line 443 of file gb-sugarless.cpp.
 {
   if (p->f == nullptr)
     {
       monomial s = M->make_one();
       M->divide(p->lcm, p->first->f->monom, s);
       GR->gbvector_mult_by_term(
           F, Fsyz, GR->one(), s, p->first->f, p->first->fsyz, p->f, p->fsyz);
       if (p->syz_type == SPAIR_PAIR)
         GR->gbvector_reduce_lead_term(
             F, Fsyz, nullptr, p->f, p->fsyz, p->second->f, p->second->fsyz);
       M->remove(s);
     }
 }
References Monoid::divide(), F, Fsyz, GBRing::gbvector_mult_by_term(), GBRing::gbvector_reduce_lead_term(), GR, M, Monoid::make_one(), GBRing::one(), p, Monoid::remove(), and SPAIR_PAIR.
Referenced by s_pair_step().