Macaulay2 Engine: GBinhom_comp::gb_insert
gb_insert()
void GBinhom_comp::gb_insert (gbvector * f, gbvector * fsyz, int minlevel) private
Definition at line 616 of file gb-sugarless.cpp.
 {
   monomial f_m = M->make_one();
   minlevel = (minlevel == 0 ? MINGB_MASK : MINGEN_MASK | MINGB_MASK);
   gb_elem *p = new gb_elem(f, fsyz, minlevel);
   p->me = last_gb_num++;
   p->lead_exp = newarray_atomic(int, M->n_vars());
   GR->gbvector_get_lead_monomial(F, p->f, f_m);
   GR->gbvector_remove_content(p->f, p->fsyz);
   M->to_expvector(f_m, p->lead_exp);
   if (M->in_subring(1, f_m)) n_subring++;
   // Next determine the new s pairs.  This also deletes unneeded pairs
   find_pairs(p);
   // Insert into the Groebner basis
   minimal_gb_valid = false;
   gb_elem *q = gbLarge;
   gb_elem *prevmin = gb;
   for (;;)
     {
       if (q->next == nullptr || compare(p, q->next) == LT)
         {
           p->next = q->next;
           q->next = p;
           n_gb++;
           // Now place into the minimal list as well
           p->next_min = prevmin->next_min;
           prevmin->next_min = p;
           break;
         }
       else if (q->next->is_min & MINGB_MASK)
         prevmin = q->next;
       q = q->next;
     }
   M->remove(f_m);
   // At this point 'p' has been inserted.  Now we need to remove the
   // non-minimal elements.
   q = p;
   while (q->next_min != nullptr)
     // MES: this loop would be a good place to put in auto-reduction?
     if (p->f->comp == q->next_min->f->comp &&
         M->divides(p->f->monom, q->next_min->f->monom))
       {
         gb_elem *tmp = q->next_min;
         q->next_min = tmp->next_min;
         tmp->next_min = nullptr;
         tmp->is_min ^= MINGB_MASK;  // I.e. not in the minimal GB
         n_gb--;
       }
     else
       q = q->next_min;
 }
References gbvector::comp, compare(), Monoid::divides(), F, gb_elem::f, find_pairs(), gb, gbLarge, GBRing::gbvector_get_lead_monomial(), GBRing::gbvector_remove_content(), GR, Monoid::in_subring(), gb_elem::is_min, last_gb_num, LT, M, Monoid::make_one(), MINGB_MASK, MINGEN_MASK, minimal_gb_valid, gbvector::monom, n_gb, n_subring, Monoid::n_vars(), newarray_atomic, gb_elem::next, gb_elem::next_min, p, Monoid::remove(), and Monoid::to_expvector().
Referenced by s_pair_step().