Macaulay2 Engine: GBinhom_comp::set_up
set_up()
void GBinhom_comp::set_up (const Matrix * m, int csyz, int nsyz, M2_arrayint gb_weights, int strategy) private
Definition at line 62 of file gb-sugarless.cpp.
 {
   strategy = strat;
   set_up0(m, csyz, nsyz, gb_weights);
   Fsyz = m->cols()->sub_space(n_comps_per_syz);
   minimal_gb = ReducedGB::create(originalR, F, Fsyz);
   minimal_gb_valid = true;
   syz = MatrixConstructor(Fsyz, 0);
   n_syz = 0;
   add_gens(0, m->n_cols() - 1, m);
 }
References add_gens(), Matrix::cols(), ReducedGB::create(), F, Fsyz, minimal_gb, minimal_gb_valid, Matrix::n_cols(), n_comps_per_syz, n_syz, originalR, set_up0(), strategy, FreeModule::sub_space(), and syz.
Referenced by GBinhom_comp().