Macaulay2 Engine: GBinhom_comp::set_up0
set_up0()
void GBinhom_comp::set_up0 (const Matrix * m, int csyz, int nsyz, M2_arrayint gb_weights) private
Definition at line 19 of file gb-sugarless.cpp.
 {
   int i;
   const PolynomialRing *R = m->get_ring()->cast_to_PolynomialRing();
   if (R == NULL)
     {
       ERROR("ring is not a polynomial ring");
       // MES: throw an error here.
       assert(0);
     }
   originalR = R;
   GR = R->get_gb_ring();
   weightInfo_ = new GBWeight(m->rows(), gb_weights);
   M = GR->get_flattened_monoid();
   K = GR->get_flattened_coefficients();
   spairs = new s_pair_heap(M);
   gb = gbLarge = new gb_elem;  // List head for the GB computed so far
   gb->next = NULL;             // (both minimal, and large GB's)
   gb->next_min = NULL;
   if (nsyz < 0 || nsyz > m->n_cols()) nsyz = m->n_cols();
   n_comps_per_syz = nsyz;
   F = m->rows();
   n_gb = n_subring = 0;
   n_pairs = n_computed = 0;
   last_gb_num = 0;
   n_saved_gcd = n_saved_lcm = 0;
   collect_syz = csyz;
   is_ideal = (F->rank() == 1 && csyz == 0);
   if (GR->is_weyl_algebra()) is_ideal = false;
   need_resize = 0;
   for (i = 0; i < F->rank(); i++) monideals.push_back(new MonomialIdeal(R));
 }
References Ring::cast_to_PolynomialRing(), collect_syz, ERROR(), F, gb, gbLarge, GBRing::get_flattened_coefficients(), GBRing::get_flattened_monoid(), PolynomialRing::get_gb_ring(), Matrix::get_ring(), GR, is_ideal, GBRing::is_weyl_algebra(), K, last_gb_num, M, monideals, Matrix::n_cols(), n_comps_per_syz, n_computed, n_gb, n_pairs, n_saved_gcd, n_saved_lcm, n_subring, need_resize, gb_elem::next, gb_elem::next_min, originalR, FreeModule::rank(), Matrix::rows(), spairs, and weightInfo_.
Referenced by set_up().