var annotated_dup =
[
    [ "BIBasis", "de/d30/namespace_b_i_basis.html", [
      [ "FastAllocator", "d1/df2/class_b_i_basis_1_1_fast_allocator.html", "d1/df2/class_b_i_basis_1_1_fast_allocator" ],
      [ "BooleanInvolutiveBasis", "d7/d7e/class_b_i_basis_1_1_boolean_involutive_basis.html", "d7/d7e/class_b_i_basis_1_1_boolean_involutive_basis" ],
      [ "JanetTree", "d2/d19/class_b_i_basis_1_1_janet_tree.html", "d2/d19/class_b_i_basis_1_1_janet_tree" ],
      [ "Launcher", "d7/d07/class_b_i_basis_1_1_launcher.html", "d7/d07/class_b_i_basis_1_1_launcher" ],
      [ "Monom", "d4/d58/class_b_i_basis_1_1_monom.html", "d4/d58/class_b_i_basis_1_1_monom" ],
      [ "MonomDL", "dd/d51/class_b_i_basis_1_1_monom_d_l.html", "dd/d51/class_b_i_basis_1_1_monom_d_l" ],
      [ "MonomDRL", "d0/da6/class_b_i_basis_1_1_monom_d_r_l.html", "d0/da6/class_b_i_basis_1_1_monom_d_r_l" ],
      [ "MonomLex", "d7/dc5/class_b_i_basis_1_1_monom_lex.html", "d7/dc5/class_b_i_basis_1_1_monom_lex" ],
      [ "PointerLessComparator", "db/d78/class_b_i_basis_1_1_pointer_less_comparator.html", "db/d78/class_b_i_basis_1_1_pointer_less_comparator" ],
      [ "PointerMoreComparator", "d1/d63/class_b_i_basis_1_1_pointer_more_comparator.html", "d1/d63/class_b_i_basis_1_1_pointer_more_comparator" ],
      [ "Polynom", "d9/d02/class_b_i_basis_1_1_polynom.html", "d9/d02/class_b_i_basis_1_1_polynom" ],
      [ "QSet", "df/d3f/class_b_i_basis_1_1_q_set.html", "df/d3f/class_b_i_basis_1_1_q_set" ],
      [ "SettingsManager", "dd/dbf/class_b_i_basis_1_1_settings_manager.html", "dd/dbf/class_b_i_basis_1_1_settings_manager" ],
      [ "Triple", "da/d09/class_b_i_basis_1_1_triple.html", "da/d09/class_b_i_basis_1_1_triple" ],
      [ "TSet", "d3/d5c/class_b_i_basis_1_1_t_set.html", "d3/d5c/class_b_i_basis_1_1_t_set" ]
    ] ],
    [ "exc", "dd/d7b/namespaceexc.html", [
      [ "engine_error", "da/dbb/structexc_1_1engine__error.html", "da/dbb/structexc_1_1engine__error" ],
      [ "overflow_exception", "db/df5/structexc_1_1overflow__exception.html", "db/df5/structexc_1_1overflow__exception" ],
      [ "division_by_zero_error", "d1/daf/structexc_1_1division__by__zero__error.html", "d1/daf/structexc_1_1division__by__zero__error" ],
      [ "internal_error", "d1/d91/structexc_1_1internal__error.html", "d1/d91/structexc_1_1internal__error" ]
    ] ],
    [ "M2", "d7/d82/namespace_m2.html", [
      [ "ARingCC", "d1/dfa/class_m2_1_1_a_ring_c_c.html", "d1/dfa/class_m2_1_1_a_ring_c_c" ],
      [ "ARingCCC", "d6/de1/class_m2_1_1_a_ring_c_c_c.html", "d6/de1/class_m2_1_1_a_ring_c_c_c" ],
      [ "ARingGFFlintBig", "d8/d7a/class_m2_1_1_a_ring_g_f_flint_big.html", "d8/d7a/class_m2_1_1_a_ring_g_f_flint_big" ],
      [ "ARingGFFlint", "d5/d5f/class_m2_1_1_a_ring_g_f_flint.html", "d5/d5f/class_m2_1_1_a_ring_g_f_flint" ],
      [ "ARingGFGivaro", "d6/d8d/class_m2_1_1_a_ring_g_f_givaro.html", "d6/d8d/class_m2_1_1_a_ring_g_f_givaro" ],
      [ "ConcreteRing", "d0/d99/class_m2_1_1_concrete_ring.html", "d0/d99/class_m2_1_1_concrete_ring" ],
      [ "RingQQ", "d4/d85/class_m2_1_1_ring_q_q.html", "d4/d85/class_m2_1_1_ring_q_q" ],
      [ "GaloisFieldTable", "d5/dab/class_m2_1_1_galois_field_table.html", "d5/dab/class_m2_1_1_galois_field_table" ],
      [ "ARingGFM2", "dd/df1/class_m2_1_1_a_ring_g_f_m2.html", "dd/df1/class_m2_1_1_a_ring_g_f_m2" ],
      [ "ARingQQFlint", "dd/d1b/class_m2_1_1_a_ring_q_q_flint.html", "dd/d1b/class_m2_1_1_a_ring_q_q_flint" ],
      [ "ARingQQGMP", "d9/dec/class_m2_1_1_a_ring_q_q_g_m_p.html", "d9/dec/class_m2_1_1_a_ring_q_q_g_m_p" ],
      [ "ARingRR", "d0/d48/class_m2_1_1_a_ring_r_r.html", "d0/d48/class_m2_1_1_a_ring_r_r" ],
      [ "ARingRRi", "dd/d78/class_m2_1_1_a_ring_r_ri.html", "dd/d78/class_m2_1_1_a_ring_r_ri" ],
      [ "ARingRRR", "dd/d9e/class_m2_1_1_a_ring_r_r_r.html", "dd/d9e/class_m2_1_1_a_ring_r_r_r" ],
      [ "ARingPolynomialStruct", "db/d05/struct_m2_1_1_a_ring_polynomial_struct.html", "db/d05/struct_m2_1_1_a_ring_polynomial_struct" ],
      [ "ARingTower", "da/d48/class_m2_1_1_a_ring_tower.html", "da/d48/class_m2_1_1_a_ring_tower" ],
      [ "RElementWrap", "d1/da0/class_m2_1_1_r_element_wrap.html", "d1/da0/class_m2_1_1_r_element_wrap" ],
      [ "AConcreteRing", "d3/dd1/class_m2_1_1_a_concrete_ring.html", "d3/dd1/class_m2_1_1_a_concrete_ring" ],
      [ "ARingZZ", "d4/dea/class_m2_1_1_a_ring_z_z.html", "d4/dea/class_m2_1_1_a_ring_z_z" ],
      [ "ARingZZGMP", "db/d2e/class_m2_1_1_a_ring_z_z_g_m_p.html", "db/d2e/class_m2_1_1_a_ring_z_z_g_m_p" ],
      [ "ARingZZpFFPACK", "da/d73/class_m2_1_1_a_ring_z_zp_f_f_p_a_c_k.html", "da/d73/class_m2_1_1_a_ring_z_zp_f_f_p_a_c_k" ],
      [ "ARingZZpFlint", "d1/d21/class_m2_1_1_a_ring_z_zp_flint.html", "d1/d21/class_m2_1_1_a_ring_z_zp_flint" ],
      [ "ARingZZp", "d6/d13/class_m2_1_1_a_ring_z_zp.html", "d6/d13/class_m2_1_1_a_ring_z_zp" ],
      [ "RingInterface", "db/d1a/class_m2_1_1_ring_interface.html", null ],
      [ "ElementImpl", "d2/d8c/class_m2_1_1_element_impl.html", "d2/d8c/class_m2_1_1_element_impl" ],
      [ "SimpleARing", "de/db5/class_m2_1_1_simple_a_ring.html", [
        [ "Element", "d7/d87/class_m2_1_1_simple_a_ring_1_1_element.html", "d7/d87/class_m2_1_1_simple_a_ring_1_1_element" ],
        [ "ElementArray", "d2/dae/class_m2_1_1_simple_a_ring_1_1_element_array.html", "d2/dae/class_m2_1_1_simple_a_ring_1_1_element_array" ]
      ] ],
      [ "DummyRing", "d5/d2d/class_m2_1_1_dummy_ring.html", "d5/d2d/class_m2_1_1_dummy_ring" ],
      [ "Reader", "db/dc5/class_m2_1_1_reader.html", "db/dc5/class_m2_1_1_reader" ]
    ] ],
    [ "mpfr", "d1/d02/namespacempfr.html", [
      [ "internal", "df/d50/namespacempfr_1_1internal.html", [
        [ "result_type", "d2/dbe/structmpfr_1_1internal_1_1result__type.html", null ],
        [ "result_type< mpreal >", "d3/d4a/structmpfr_1_1internal_1_1result__type_3_01mpreal_01_4.html", "d3/d4a/structmpfr_1_1internal_1_1result__type_3_01mpreal_01_4" ],
        [ "result_type< mpz_t >", "d2/db6/structmpfr_1_1internal_1_1result__type_3_01mpz__t_01_4.html", "d2/db6/structmpfr_1_1internal_1_1result__type_3_01mpz__t_01_4" ],
        [ "result_type< mpq_t >", "d9/d6c/structmpfr_1_1internal_1_1result__type_3_01mpq__t_01_4.html", "d9/d6c/structmpfr_1_1internal_1_1result__type_3_01mpq__t_01_4" ],
        [ "result_type< long double >", "d0/d3e/structmpfr_1_1internal_1_1result__type_3_01long_01double_01_4.html", "d0/d3e/structmpfr_1_1internal_1_1result__type_3_01long_01double_01_4" ],
        [ "result_type< double >", "d8/da4/structmpfr_1_1internal_1_1result__type_3_01double_01_4.html", "d8/da4/structmpfr_1_1internal_1_1result__type_3_01double_01_4" ],
        [ "result_type< unsigned long int >", "dc/db2/structmpfr_1_1internal_1_1result__type_3_01unsigned_01long_01int_01_4.html", "dc/db2/structmpfr_1_1internal_1_1result__type_3_01unsigned_01long_01int_01_4" ],
        [ "result_type< unsigned int >", "d5/df9/structmpfr_1_1internal_1_1result__type_3_01unsigned_01int_01_4.html", "d5/df9/structmpfr_1_1internal_1_1result__type_3_01unsigned_01int_01_4" ],
        [ "result_type< long int >", "da/ddd/structmpfr_1_1internal_1_1result__type_3_01long_01int_01_4.html", "da/ddd/structmpfr_1_1internal_1_1result__type_3_01long_01int_01_4" ],
        [ "result_type< int >", "d4/d9d/structmpfr_1_1internal_1_1result__type_3_01int_01_4.html", "d4/d9d/structmpfr_1_1internal_1_1result__type_3_01int_01_4" ],
        [ "result_type< long long >", "d5/d5e/structmpfr_1_1internal_1_1result__type_3_01long_01long_01_4.html", "d5/d5e/structmpfr_1_1internal_1_1result__type_3_01long_01long_01_4" ],
        [ "result_type< unsigned long long >", "db/df4/structmpfr_1_1internal_1_1result__type_3_01unsigned_01long_01long_01_4.html", "db/df4/structmpfr_1_1internal_1_1result__type_3_01unsigned_01long_01long_01_4" ]
      ] ],
      [ "mpreal", "d6/df7/classmpfr_1_1mpreal.html", "d6/df7/classmpfr_1_1mpreal" ],
      [ "conversion_overflow", "d3/d03/classmpfr_1_1conversion__overflow.html", "d3/d03/classmpfr_1_1conversion__overflow" ]
    ] ],
    [ "newf4", "da/db5/namespacenewf4.html", [
      [ "Basis", "d9/d73/classnewf4_1_1_basis.html", "d9/d73/classnewf4_1_1_basis" ],
      [ "GBF4Computation", "d1/dc4/classnewf4_1_1_g_b_f4_computation.html", "d1/dc4/classnewf4_1_1_g_b_f4_computation" ],
      [ "GBF4Interface", "d6/d99/classnewf4_1_1_g_b_f4_interface.html", "d6/d99/classnewf4_1_1_g_b_f4_interface" ],
      [ "MacaulayMatrix", "d5/d59/classnewf4_1_1_macaulay_matrix.html", "d5/d59/classnewf4_1_1_macaulay_matrix" ],
      [ "Column", "d7/db8/structnewf4_1_1_column.html", null ],
      [ "Row", "d6/d54/structnewf4_1_1_row.html", null ],
      [ "MonomialHashFunction", "d5/dd0/classnewf4_1_1_monomial_hash_function.html", "d5/dd0/classnewf4_1_1_monomial_hash_function" ],
      [ "HashTableStats", "dd/db9/structnewf4_1_1_hash_table_stats.html", "dd/db9/structnewf4_1_1_hash_table_stats" ],
      [ "MonomialHashTable", "d1/d1e/classnewf4_1_1_monomial_hash_table.html", "d1/d1e/classnewf4_1_1_monomial_hash_table" ],
      [ "MonomialInfo", "da/d7e/structnewf4_1_1_monomial_info.html", "da/d7e/structnewf4_1_1_monomial_info" ],
      [ "MonomialLookupTable", "db/d90/classnewf4_1_1_monomial_lookup_table.html", "db/d90/classnewf4_1_1_monomial_lookup_table" ],
      [ "MonomialView", "da/d80/classnewf4_1_1_monomial_view.html", "da/d80/classnewf4_1_1_monomial_view" ],
      [ "PolynomialList", "d2/d47/classnewf4_1_1_polynomial_list.html", "d2/d47/classnewf4_1_1_polynomial_list" ],
      [ "Polynomial", "d4/d1b/classnewf4_1_1_polynomial.html", "d4/d1b/classnewf4_1_1_polynomial" ],
      [ "PolynomialListStreamCollector", "d7/d35/classnewf4_1_1_polynomial_list_stream_collector.html", "d7/d35/classnewf4_1_1_polynomial_list_stream_collector" ],
      [ "SPair", "db/dd1/structnewf4_1_1_s_pair.html", "db/dd1/structnewf4_1_1_s_pair" ],
      [ "SPairSet", "d2/d40/classnewf4_1_1_s_pair_set.html", "d2/d40/classnewf4_1_1_s_pair_set" ]
    ] ],
    [ "SchreyerFrameTypes", "de/d8e/namespace_schreyer_frame_types.html", [
      [ "FrameElement", "d8/df1/struct_schreyer_frame_types_1_1_frame_element.html", "d8/df1/struct_schreyer_frame_types_1_1_frame_element" ],
      [ "PreElement", "d9/d02/struct_schreyer_frame_types_1_1_pre_element.html", "d9/d02/struct_schreyer_frame_types_1_1_pre_element" ]
    ] ],
    [ "std", null, [
      [ "numeric_limits< mpfr::mpreal >", "d6/dba/classstd_1_1numeric__limits_3_01mpfr_1_1mpreal_01_4.html", "d6/dba/classstd_1_1numeric__limits_3_01mpfr_1_1mpreal_01_4" ]
    ] ],
    [ "AllocLogger", "d4/d6d/class_alloc_logger.html", "d4/d6d/class_alloc_logger" ],
    [ "ARing", "d1/d7e/class_a_ring.html", null ],
    [ "ARingElement", "d9/d84/class_a_ring_element.html", "d9/d84/class_a_ring_element" ],
    [ "ARingElementGenerator", "df/dc2/class_a_ring_element_generator.html", "df/dc2/class_a_ring_element_generator" ],
    [ "AssociatedPrimes", "d5/dc8/class_associated_primes.html", "d5/dc8/class_associated_primes" ],
    [ "auto_reduce_node", "d6/dd2/structauto__reduce__node.html", "d6/dd2/structauto__reduce__node" ],
    [ "BasicPoly", "d3/d9f/class_basic_poly.html", "d3/d9f/class_basic_poly" ],
    [ "BasicPolyListStreamCollector", "de/d95/class_basic_poly_list_stream_collector.html", "de/d95/class_basic_poly_list_stream_collector" ],
    [ "BettiDisplay", "d6/d45/class_betti_display.html", "d6/d45/class_betti_display" ],
    [ "BettiHashAndEq", "d7/d37/class_betti_hash_and_eq.html", "d7/d37/class_betti_hash_and_eq" ],
    [ "binomial", "de/df1/structbinomial.html", "de/df1/structbinomial" ],
    [ "binomial_gb_elem", "d7/d61/structbinomial__gb__elem.html", "d7/d61/structbinomial__gb__elem" ],
    [ "binomial_ring", "dd/d3a/classbinomial__ring.html", "dd/d3a/classbinomial__ring" ],
    [ "binomial_s_pair", "de/d61/structbinomial__s__pair.html", "de/d61/structbinomial__s__pair" ],
    [ "binomial_s_pair_set", "d1/d7e/classbinomial__s__pair__set.html", "d1/d7e/classbinomial__s__pair__set" ],
    [ "binomialGB", "d6/d05/classbinomial_g_b.html", "d6/d05/classbinomial_g_b" ],
    [ "binomialGB_comp", "da/d1d/classbinomial_g_b__comp.html", "da/d1d/classbinomial_g_b__comp" ],
    [ "BRP", "db/d1b/class_b_r_p.html", "db/d1b/class_b_r_p" ],
    [ "buffer", "da/d40/classbuffer.html", "da/d40/classbuffer" ],
    [ "cc_doubles_struct", "db/dae/structcc__doubles__struct.html", "db/dae/structcc__doubles__struct" ],
    [ "CC_struct", "d3/d66/struct_c_c__struct.html", "d3/d66/struct_c_c__struct" ],
    [ "cc_struct", "de/d31/structcc__struct.html", "de/d31/structcc__struct" ],
    [ "CCmutable_struct", "d6/ddb/struct_c_cmutable__struct.html", "d6/ddb/struct_c_cmutable__struct" ],
    [ "ChineseRemainder", "d0/d4e/class_chinese_remainder.html", "d0/d4e/class_chinese_remainder" ],
    [ "coefficient_matrix", "d8/dce/structcoefficient__matrix.html", "d8/dce/structcoefficient__matrix" ],
    [ "CoefficientRingR", "d1/d34/class_coefficient_ring_r.html", "d1/d34/class_coefficient_ring_r" ],
    [ "CoefficientRingType", "db/dc3/struct_coefficient_ring_type.html", "db/dc3/struct_coefficient_ring_type" ],
    [ "CoefficientRingZZp", "dd/dd5/class_coefficient_ring_z_zp.html", "dd/dd5/class_coefficient_ring_z_zp" ],
    [ "column_elem", "d3/d69/structcolumn__elem.html", "d3/d69/structcolumn__elem" ],
    [ "ColumnsSorter", "d9/d05/class_columns_sorter.html", "d9/d05/class_columns_sorter" ],
    [ "complex", "d6/d3b/classcomplex.html", "d6/d3b/classcomplex" ],
    [ "ComplexField", "d5/d7d/class_complex_field.html", "d5/d7d/class_complex_field" ],
    [ "Computation", "d6/dea/class_computation.html", "d6/dea/class_computation" ],
    [ "ConcreteVectorArithmetic", "d7/d23/class_concrete_vector_arithmetic.html", "d7/d23/class_concrete_vector_arithmetic" ],
    [ "ConstZipIterator", "da/dfd/class_const_zip_iterator.html", "da/dfd/class_const_zip_iterator" ],
    [ "DegreeZeroMapGenerator", "de/df3/class_degree_zero_map_generator.html", "de/df3/class_degree_zero_map_generator" ],
    [ "DetComputation", "d7/d9a/class_det_computation.html", "d7/d9a/class_det_computation" ],
    [ "DMat", "da/dc3/class_d_mat.html", "da/dc3/class_d_mat" ],
    [ "DMat< M2::ARingGFFlint >", "d3/d1d/class_d_mat_3_01_m2_1_1_a_ring_g_f_flint_01_4.html", "d3/d1d/class_d_mat_3_01_m2_1_1_a_ring_g_f_flint_01_4" ],
    [ "DMat< M2::ARingGFFlintBig >", "d1/dbb/class_d_mat_3_01_m2_1_1_a_ring_g_f_flint_big_01_4.html", "d1/dbb/class_d_mat_3_01_m2_1_1_a_ring_g_f_flint_big_01_4" ],
    [ "DMat< M2::ARingQQFlint >", "d6/de7/class_d_mat_3_01_m2_1_1_a_ring_q_q_flint_01_4.html", "d6/de7/class_d_mat_3_01_m2_1_1_a_ring_q_q_flint_01_4" ],
    [ "DMat< M2::ARingZZ >", "d2/da8/class_d_mat_3_01_m2_1_1_a_ring_z_z_01_4.html", "d2/da8/class_d_mat_3_01_m2_1_1_a_ring_z_z_01_4" ],
    [ "DMat< M2::ARingZZpFlint >", "d6/d70/class_d_mat_3_01_m2_1_1_a_ring_z_zp_flint_01_4.html", "d6/d70/class_d_mat_3_01_m2_1_1_a_ring_z_zp_flint_01_4" ],
    [ "DMatConstIterator", "d6/d9a/class_d_mat_const_iterator.html", "d6/d9a/class_d_mat_const_iterator" ],
    [ "DMatIterator", "df/d28/class_d_mat_iterator.html", "df/d28/class_d_mat_iterator" ],
    [ "DMatLinAlg", "d8/df6/class_d_mat_lin_alg.html", "d8/df6/class_d_mat_lin_alg" ],
    [ "DMatLinAlg< M2::ARingQQ >", "d7/d2b/class_d_mat_lin_alg_3_01_m2_1_1_a_ring_q_q_01_4.html", "d7/d2b/class_d_mat_lin_alg_3_01_m2_1_1_a_ring_q_q_01_4" ],
    [ "DMatLinAlg< M2::ARingZZpFFPACK >", "dc/d87/class_d_mat_lin_alg_3_01_m2_1_1_a_ring_z_zp_f_f_p_a_c_k_01_4.html", "dc/d87/class_d_mat_lin_alg_3_01_m2_1_1_a_ring_z_zp_f_f_p_a_c_k_01_4" ],
    [ "DMatLinAlg< M2::ARingZZpFlint >", "d1/d10/class_d_mat_lin_alg_3_01_m2_1_1_a_ring_z_zp_flint_01_4.html", "d1/d10/class_d_mat_lin_alg_3_01_m2_1_1_a_ring_z_zp_flint_01_4" ],
    [ "DMatLUinPlace", "df/d1c/class_d_mat_l_uin_place.html", "df/d1c/class_d_mat_l_uin_place" ],
    [ "doubling_stash", "da/d01/classdoubling__stash.html", "da/d01/classdoubling__stash" ],
    [ "DPoly", "d3/d42/class_d_poly.html", "d3/d42/class_d_poly" ],
    [ "DPolyTraverser", "d4/d61/class_d_poly_traverser.html", "d4/d61/class_d_poly_traverser" ],
    [ "DRing", "d6/de6/class_d_ring.html", "d6/de6/class_d_ring" ],
    [ "EigenTypes", "da/dfe/struct_eigen_types.html", "da/dfe/struct_eigen_types" ],
    [ "EigenTypes< M2::ARingCC >", "dd/dfb/struct_eigen_types_3_01_m2_1_1_a_ring_c_c_01_4.html", "dd/dfb/struct_eigen_types_3_01_m2_1_1_a_ring_c_c_01_4" ],
    [ "EigenTypes< M2::ARingCCC >", "de/d33/struct_eigen_types_3_01_m2_1_1_a_ring_c_c_c_01_4.html", "de/d33/struct_eigen_types_3_01_m2_1_1_a_ring_c_c_c_01_4" ],
    [ "EigenTypes< M2::ARingRR >", "d9/dc6/struct_eigen_types_3_01_m2_1_1_a_ring_r_r_01_4.html", "d9/dc6/struct_eigen_types_3_01_m2_1_1_a_ring_r_r_01_4" ],
    [ "EigenTypes< M2::ARingRRR >", "dd/dbb/struct_eigen_types_3_01_m2_1_1_a_ring_r_r_r_01_4.html", "dd/dbb/struct_eigen_types_3_01_m2_1_1_a_ring_r_r_r_01_4" ],
    [ "ElementArray", "d5/d94/class_element_array.html", "d5/d94/class_element_array" ],
    [ "EngineMonomial", "d7/def/class_engine_monomial.html", "d7/def/class_engine_monomial" ],
    [ "EngineObject", "d4/d3f/class_engine_object.html", "d4/d3f/class_engine_object" ],
    [ "enter_factory", "db/d86/structenter__factory.html", "db/d86/structenter__factory" ],
    [ "EntryConfig", "d4/de5/class_entry_config.html", "d4/de5/class_entry_config" ],
    [ "exponent_table", "d7/db5/structexponent__table.html", "d7/db5/structexponent__table" ],
    [ "ExponentList", "d1/d39/class_exponent_list.html", "d1/d39/class_exponent_list" ],
    [ "ExponentListIterator", "dc/d51/class_exponent_list_iterator.html", "dc/d51/class_exponent_list_iterator" ],
    [ "ExponentVector", "d1/d42/class_exponent_vector.html", "d1/d42/class_exponent_vector" ],
    [ "F4Computation", "d8/d5d/class_f4_computation.html", "d8/d5d/class_f4_computation" ],
    [ "F4GB", "d9/d4a/class_f4_g_b.html", "d9/d4a/class_f4_g_b" ],
    [ "F4Mem", "d5/d43/class_f4_mem.html", "d5/d43/class_f4_mem" ],
    [ "F4MemoryBlock", "d8/d75/class_f4_memory_block.html", "d8/d75/class_f4_memory_block" ],
    [ "F4MonomialLookupTableT", "d6/d10/class_f4_monomial_lookup_table_t.html", "d6/d10/class_f4_monomial_lookup_table_t" ],
    [ "F4Res", "d0/dd7/class_f4_res.html", "d0/dd7/class_f4_res" ],
    [ "F4ResComputation", "d6/d1e/class_f4_res_computation.html", "d6/d1e/class_f4_res_computation" ],
    [ "F4SPairSet", "d9/d22/class_f4_s_pair_set.html", "d9/d22/class_f4_s_pair_set" ],
    [ "F4toM2Interface", "d5/df9/class_f4to_m2_interface.html", "d5/df9/class_f4to_m2_interface" ],
    [ "F4Vec", "df/de1/class_f4_vec.html", "df/de1/class_f4_vec" ],
    [ "FF_LUComputation", "d7/db4/class_f_f___l_u_computation.html", "d7/db4/class_f_f___l_u_computation" ],
    [ "FixedPrecisionHomotopyAlgorithm", "d9/ddd/class_fixed_precision_homotopy_algorithm.html", null ],
    [ "FlintQQMat", "d2/d11/class_flint_q_q_mat.html", "d2/d11/class_flint_q_q_mat" ],
    [ "FlintZZMat", "d9/d3a/class_flint_z_z_mat.html", "d9/d3a/class_flint_z_z_mat" ],
    [ "frac_elem", "d6/d62/structfrac__elem.html", "d6/d62/structfrac__elem" ],
    [ "FractionField", "d6/d42/class_fraction_field.html", "d6/d42/class_fraction_field" ],
    [ "FreeAlgebra", "de/dbd/class_free_algebra.html", "de/dbd/class_free_algebra" ],
    [ "FreeAlgebraElement", "dc/d2e/class_free_algebra_element.html", "dc/d2e/class_free_algebra_element" ],
    [ "FreeAlgebraHeap", "d4/d31/class_free_algebra_heap.html", "d4/d31/class_free_algebra_heap" ],
    [ "FreeAlgebraQuotient", "d0/d77/class_free_algebra_quotient.html", "d0/d77/class_free_algebra_quotient" ],
    [ "FreeAlgebraQuotientElement", "d2/d58/class_free_algebra_quotient_element.html", "d2/d58/class_free_algebra_quotient_element" ],
    [ "FreeModule", "d6/df0/class_free_module.html", "d6/df0/class_free_module" ],
    [ "FreeModule_symm", "da/d99/struct_free_module__symm.html", "da/d99/struct_free_module__symm" ],
    [ "FreeMonoid", "dc/da6/class_free_monoid.html", "dc/da6/class_free_monoid" ],
    [ "FreeMonoidLogger", "d0/dc7/class_free_monoid_logger.html", "d0/dc7/class_free_monoid_logger" ],
    [ "FunctionPair", "d2/d44/class_function_pair.html", "d2/d44/class_function_pair" ],
    [ "GaussElimComputation", "d3/d16/class_gauss_elim_computation.html", "d3/d16/class_gauss_elim_computation" ],
    [ "gb2_comp", "dd/df7/classgb2__comp.html", "dd/df7/classgb2__comp" ],
    [ "GB_comp", "d8/dfa/class_g_b__comp.html", "d8/dfa/class_g_b__comp" ],
    [ "gb_elem", "dc/d9c/structgb__elem.html", "dc/d9c/structgb__elem" ],
    [ "gb_emitter", "df/d2c/classgb__emitter.html", "df/d2c/classgb__emitter" ],
    [ "gb_node", "dc/d99/classgb__node.html", "dc/d99/classgb__node" ],
    [ "gbA", "d0/d91/classgb_a.html", "d0/d91/classgb_a" ],
    [ "GBComputation", "de/ded/class_g_b_computation.html", "de/ded/class_g_b_computation" ],
    [ "GBDeclared", "d8/d26/class_g_b_declared.html", "d8/d26/class_g_b_declared" ],
    [ "gbelem", "dc/dc0/structgbelem.html", "dc/dc0/structgbelem" ],
    [ "GBF4Polynomial", "d5/d39/struct_g_b_f4_polynomial.html", "d5/d39/struct_g_b_f4_polynomial" ],
    [ "GBinhom_comp", "d6/dfe/class_g_binhom__comp.html", "d6/dfe/class_g_binhom__comp" ],
    [ "GBKernelComputation", "d7/d37/class_g_b_kernel_computation.html", "d7/d37/class_g_b_kernel_computation" ],
    [ "GBMatrix", "d7/d14/struct_g_b_matrix.html", "d7/d14/struct_g_b_matrix" ],
    [ "GBProxy", "d1/dd3/class_g_b_proxy.html", "d1/dd3/class_g_b_proxy" ],
    [ "gbres_comp", "d6/dce/classgbres__comp.html", "d6/dce/classgbres__comp" ],
    [ "GBRing", "d8/d73/class_g_b_ring.html", "d8/d73/class_g_b_ring" ],
    [ "GBRingPoly", "d5/d09/class_g_b_ring_poly.html", "d5/d09/class_g_b_ring_poly" ],
    [ "GBRingSkew", "dd/de7/class_g_b_ring_skew.html", "dd/de7/class_g_b_ring_skew" ],
    [ "GBRingSolvable", "d5/d5c/class_g_b_ring_solvable.html", "d5/d5c/class_g_b_ring_solvable" ],
    [ "GBRingWeyl", "d3/dd1/class_g_b_ring_weyl.html", "d3/dd1/class_g_b_ring_weyl" ],
    [ "GBRingWeylZZ", "d3/d48/class_g_b_ring_weyl_z_z.html", "d3/d48/class_g_b_ring_weyl_z_z" ],
    [ "gbvector", "d7/d40/structgbvector.html", "d7/d40/structgbvector" ],
    [ "gbvectorHeap", "dc/d58/classgbvector_heap.html", "dc/d58/classgbvector_heap" ],
    [ "GBWalker", "df/dab/class_g_b_walker.html", "df/dab/class_g_b_walker" ],
    [ "GBWeight", "d5/d82/class_g_b_weight.html", "d5/d82/class_g_b_weight" ],
    [ "geobucket", "d5/d03/classgeobucket.html", "d5/d03/classgeobucket" ],
    [ "GF", "d1/d35/class_g_f.html", "d1/d35/class_g_f" ],
    [ "gm_elem", "d0/dd0/structgm__elem.html", "d0/dd0/structgm__elem" ],
    [ "HermiteComputation", "d8/d76/class_hermite_computation.html", "d8/d76/class_hermite_computation" ],
    [ "hilb_comp", "de/dfb/classhilb__comp.html", "de/dfb/classhilb__comp" ],
    [ "hilb_step", "d3/de1/structhilb__step.html", "d3/de1/structhilb__step" ],
    [ "HilbertController", "dd/dc6/class_hilbert_controller.html", "dd/dc6/class_hilbert_controller" ],
    [ "hm_elem", "db/dde/structhm__elem.html", "db/dde/structhm__elem" ],
    [ "Homotopy", "de/d9d/class_homotopy.html", "de/d9d/class_homotopy" ],
    [ "HomotopyAlgorithm", "d6/d19/struct_homotopy_algorithm.html", "d6/d19/struct_homotopy_algorithm" ],
    [ "HomotopyAlgorithm< M2::ARingCC >", "dd/d40/struct_homotopy_algorithm_3_01_m2_1_1_a_ring_c_c_01_4.html", "dd/d40/struct_homotopy_algorithm_3_01_m2_1_1_a_ring_c_c_01_4" ],
    [ "HomotopyAlgorithm< M2::ARingCCC >", "d4/ddf/struct_homotopy_algorithm_3_01_m2_1_1_a_ring_c_c_c_01_4.html", "d4/ddf/struct_homotopy_algorithm_3_01_m2_1_1_a_ring_c_c_c_01_4" ],
    [ "HomotopyConcrete", "d9/dc8/class_homotopy_concrete.html", "d9/dc8/class_homotopy_concrete" ],
    [ "HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >", "d2/d78/class_homotopy_concrete_3_01_r_t_00_01_fixed_precision_homotopy_algorithm_01_4.html", "d2/d78/class_homotopy_concrete_3_01_r_t_00_01_fixed_precision_homotopy_algorithm_01_4" ],
    [ "IdentifierHash", "da/d49/class_identifier_hash.html", "da/d49/class_identifier_hash" ],
    [ "indent", "d2/dd2/structindent.html", "d2/dd2/structindent" ],
    [ "int_bag", "df/d8c/classint__bag.html", "df/d8c/classint__bag" ],
    [ "Interreducer", "d5/d51/class_interreducer.html", "d5/d51/class_interreducer" ],
    [ "IntsSet", "dc/dd8/class_ints_set.html", "dc/dd8/class_ints_set" ],
    [ "KBasis", "d9/dd1/class_k_basis.html", "d9/dd1/class_k_basis" ],
    [ "Lapack", "df/dd6/class_lapack.html", "df/dd6/class_lapack" ],
    [ "lex", "d2/dfa/structlex.html", "d2/dfa/structlex" ],
    [ "LLLoperations", "d8/d7d/class_l_l_loperations.html", "d8/d7d/class_l_l_loperations" ],
    [ "local_elem", "d4/d20/structlocal__elem.html", "d4/d20/structlocal__elem" ],
    [ "LocalRing", "d6/dfd/class_local_ring.html", "d6/dfd/class_local_ring" ],
    [ "LUUtil", "df/dcd/class_l_u_util.html", "df/dcd/class_l_u_util" ],
    [ "M2FreeAlgebra", "dc/dc0/class_m2_free_algebra.html", "dc/dc0/class_m2_free_algebra" ],
    [ "M2FreeAlgebraOrQuotient", "de/dd2/class_m2_free_algebra_or_quotient.html", "de/dd2/class_m2_free_algebra_or_quotient" ],
    [ "M2FreeAlgebraQuotient", "db/d22/class_m2_free_algebra_quotient.html", "db/d22/class_m2_free_algebra_quotient" ],
    [ "M2Homotopy", "dc/de6/class_m2_homotopy.html", "dc/de6/class_m2_homotopy" ],
    [ "M2PointArray", "d2/dd0/class_m2_point_array.html", "d2/dd0/class_m2_point_array" ],
    [ "M2SLEvaluator", "db/d7c/class_m2_s_l_evaluator.html", "db/d7c/class_m2_s_l_evaluator" ],
    [ "M2SLProgram", "d8/d3a/class_m2_s_l_program.html", "d8/d3a/class_m2_s_l_program" ],
    [ "MapPolynomialHeap", "d3/d6a/class_map_polynomial_heap.html", "d3/d6a/class_map_polynomial_heap" ],
    [ "MarkedGB", "d2/d89/class_marked_g_b.html", "d2/d89/class_marked_g_b" ],
    [ "MarkedGB_sorter", "d4/d5b/struct_marked_g_b__sorter.html", "d4/d5b/struct_marked_g_b__sorter" ],
    [ "MatElementaryOps", "db/d2e/class_mat_elementary_ops.html", null ],
    [ "MatElementaryOps< DMat< RT > >", "d1/ddf/class_mat_elementary_ops_3_01_d_mat_3_01_r_t_01_4_01_4.html", "d1/ddf/class_mat_elementary_ops_3_01_d_mat_3_01_r_t_01_4_01_4" ],
    [ "MatElementaryOps< SMat< RT > >", "d3/db3/class_mat_elementary_ops_3_01_s_mat_3_01_r_t_01_4_01_4.html", "d3/db3/class_mat_elementary_ops_3_01_s_mat_3_01_r_t_01_4_01_4" ],
    [ "Matrix", "d6/d3f/class_matrix.html", "d6/d3f/class_matrix" ],
    [ "MatrixConstructor", "d3/d7a/class_matrix_constructor.html", "d3/d7a/class_matrix_constructor" ],
    [ "MatrixSorter", "da/d1d/class_matrix_sorter.html", "da/d1d/class_matrix_sorter" ],
    [ "MatrixStream", "d6/d02/class_matrix_stream.html", "d6/d02/class_matrix_stream" ],
    [ "MatrixWindow", "df/d6c/struct_matrix_window.html", "df/d6c/struct_matrix_window" ],
    [ "MemoryBlock", "d3/d57/class_memory_block.html", "d3/d57/class_memory_block" ],
    [ "MGBCallback", "df/df8/class_m_g_b_callback.html", "df/df8/class_m_g_b_callback" ],
    [ "MinimalPrimes", "db/d26/class_minimal_primes.html", "db/d26/class_minimal_primes" ],
    [ "mo_block", "dd/dbb/structmo__block.html", "dd/dbb/structmo__block" ],
    [ "ModuleMonom", "d9/d8a/class_module_monom.html", "d9/d8a/class_module_monom" ],
    [ "ModuleMonomDefaultConfig", "d0/df9/class_module_monom_default_config.html", "d0/df9/class_module_monom_default_config" ],
    [ "ModuleMonomDefaultConfigOrig", "dd/d04/class_module_monom_default_config_orig.html", "dd/d04/class_module_monom_default_config_orig" ],
    [ "ModuleMonomEq", "d7/dd4/class_module_monom_eq.html", "d7/dd4/class_module_monom_eq" ],
    [ "ModuleMonomHash", "d7/df6/class_module_monom_hash.html", "d7/df6/class_module_monom_hash" ],
    [ "ModuleMonomLessThan", "db/dd2/class_module_monom_less_than.html", "db/dd2/class_module_monom_less_than" ],
    [ "mon_part", "d3/de9/structmon__part__rec__.html", "d3/de9/structmon__part__rec__" ],
    [ "monideal_pair", "d7/de9/structmonideal__pair.html", "d7/de9/structmonideal__pair" ],
    [ "Monoid", "d9/db1/class_monoid.html", "d9/db1/class_monoid" ],
    [ "Monom", "dd/d21/struct_monom.html", "dd/d21/struct_monom" ],
    [ "monom_int_list", "d4/d08/classmonom__int__list.html", "d4/d08/classmonom__int__list" ],
    [ "MonomEq", "d7/d79/class_monom_eq.html", "d7/d79/class_monom_eq" ],
    [ "MonomHash", "d0/da5/class_monom_hash.html", "d0/da5/class_monom_hash" ],
    [ "MonomHashEqual", "dc/dd6/class_monom_hash_equal.html", "dc/dd6/class_monom_hash_equal" ],
    [ "MonomialCollectionFixedSize", "d6/dd5/class_monomial_collection_fixed_size.html", "d6/dd5/class_monomial_collection_fixed_size" ],
    [ "MonomialCollectionVarSize", "d4/d7c/class_monomial_collection_var_size.html", "d4/d7c/class_monomial_collection_var_size" ],
    [ "MonomialHashAndEqFixedSize", "d8/da4/class_monomial_hash_and_eq_fixed_size.html", "d8/da4/class_monomial_hash_and_eq_fixed_size" ],
    [ "MonomialHashAndEqVarSize", "d2/d70/class_monomial_hash_and_eq_var_size.html", "d2/d70/class_monomial_hash_and_eq_var_size" ],
    [ "MonomialHashTable", "d0/d1f/class_monomial_hash_table.html", "d0/d1f/class_monomial_hash_table" ],
    [ "MonomialIdeal", "df/ddb/class_monomial_ideal.html", "df/ddb/class_monomial_ideal" ],
    [ "MonomialInfo", "dd/dab/class_monomial_info.html", "dd/dab/class_monomial_info" ],
    [ "MonomialMemorySpace", "d3/d43/class_monomial_memory_space.html", "d3/d43/class_monomial_memory_space" ],
    [ "MonomialOrder", "d0/d87/struct_monomial_order__rec.html", "d0/d87/struct_monomial_order__rec" ],
    [ "MonomialOrdering", "dd/d53/struct_monomial_ordering.html", "dd/d53/struct_monomial_ordering" ],
    [ "MonomialOrderings", "d7/d7c/class_monomial_orderings.html", "d7/d7c/class_monomial_orderings" ],
    [ "MonomialOrderMatrix", "d5/d82/class_monomial_order_matrix.html", "d5/d82/class_monomial_order_matrix" ],
    [ "MonomialSetFixedSize", "d4/d11/class_monomial_set_fixed_size.html", "d4/d11/class_monomial_set_fixed_size" ],
    [ "MonomialSetVarSize", "da/d9e/class_monomial_set_var_size.html", "da/d9e/class_monomial_set_var_size" ],
    [ "MonomialsIgnoringComponent", "da/d64/class_monomials_ignoring_component.html", "da/d64/class_monomials_ignoring_component" ],
    [ "MonomialSorterObject", "dd/d94/class_monomial_sorter_object.html", "dd/d94/class_monomial_sorter_object" ],
    [ "MonomialsWithComponent", "d9/db6/class_monomials_with_component.html", "d9/db6/class_monomials_with_component" ],
    [ "MonomialTable", "d9/d3b/class_monomial_table.html", "d9/d3b/class_monomial_table" ],
    [ "MonomialTableZZ", "da/da3/class_monomial_table_z_z.html", "da/da3/class_monomial_table_z_z" ],
    [ "MonomSort", "de/dff/struct_monom_sort.html", "de/dff/struct_monom_sort" ],
    [ "montable_sorter_ZZ", "d9/d6a/structmontable__sorter___z_z.html", "d9/d6a/structmontable__sorter___z_z" ],
    [ "MutableComplex", "dc/d43/class_mutable_complex.html", "dc/d43/class_mutable_complex" ],
    [ "MutableEngineObject", "d3/d7b/class_mutable_engine_object.html", "d3/d7b/class_mutable_engine_object" ],
    [ "MutableMat", "d6/db0/class_mutable_mat.html", "d6/db0/class_mutable_mat" ],
    [ "MutableMatrix", "dc/db8/class_mutable_matrix.html", "dc/db8/class_mutable_matrix" ],
    [ "MyIdealConsumer", "d8/d5c/class_my_ideal_consumer.html", "d8/d5c/class_my_ideal_consumer" ],
    [ "NaiveDedupPolynomialHeap", "d8/ded/class_naive_dedup_polynomial_heap.html", "d8/ded/class_naive_dedup_polynomial_heap" ],
    [ "NaiveDedupQueueConfiguration", "dd/dc4/class_naive_dedup_queue_configuration.html", "dd/dc4/class_naive_dedup_queue_configuration" ],
    [ "NaivePolynomialHeap", "d1/dc6/class_naive_polynomial_heap.html", "d1/dc6/class_naive_polynomial_heap" ],
    [ "NaiveQueueConfiguration", "d0/d65/class_naive_queue_configuration.html", "d0/d65/class_naive_queue_configuration" ],
    [ "NCBasis", "d9/d29/class_n_c_basis.html", "d9/d29/class_n_c_basis" ],
    [ "NCF4", "d0/d92/class_n_c_f4.html", "d0/d92/class_n_c_f4" ],
    [ "NCGroebner", "d8/d79/class_n_c_groebner.html", "d8/d79/class_n_c_groebner" ],
    [ "NCResComputation", "da/dc1/class_n_c_res_computation.html", "da/dc1/class_n_c_res_computation" ],
    [ "Nmi_node", "d0/d1b/class_nmi__node.html", "d0/d1b/class_nmi__node" ],
    [ "Nterm", "d0/dbc/struct_nterm.html", "d0/dbc/struct_nterm" ],
    [ "our_gc_cleanup", "d3/d31/classour__gc__cleanup.html", "d3/d31/classour__gc__cleanup" ],
    [ "our_new_delete", "da/dcc/structour__new__delete.html", "da/dcc/structour__new__delete" ],
    [ "OurNode", "d5/dec/struct_our_node.html", "d5/dec/struct_our_node" ],
    [ "OurQueueConfiguration", "d1/d7c/class_our_queue_configuration.html", "d1/d7c/class_our_queue_configuration" ],
    [ "OurQueueConfiguration1", "d4/d77/class_our_queue_configuration1.html", "d4/d77/class_our_queue_configuration1" ],
    [ "OverlapTable", "de/d48/class_overlap_table.html", "de/d48/class_overlap_table" ],
    [ "Pair", "d2/d49/class_pair.html", "d2/d49/class_pair" ],
    [ "PairRange", "df/d71/class_pair_range.html", "df/d71/class_pair_range" ],
    [ "parsing_error", "d8/d84/structparsing__error.html", "d8/d84/structparsing__error" ],
    [ "part_elem", "d4/d27/structpart__elem.html", "d4/d27/structpart__elem" ],
    [ "partition_table", "dc/d6e/classpartition__table.html", "dc/d6e/classpartition__table" ],
    [ "PathTracker", "de/db9/class_path_tracker.html", "de/db9/class_path_tracker" ],
    [ "PfaffianComputation", "dc/df6/class_pfaffian_computation.html", "dc/df6/class_pfaffian_computation" ],
    [ "PointArray", "d2/dbf/class_point_array.html", "d2/dbf/class_point_array" ],
    [ "PointsComputation", "d2/d6c/class_points_computation.html", "d2/d6c/class_points_computation" ],
    [ "POLY", "d0/d03/struct_p_o_l_y.html", "d0/d03/struct_p_o_l_y" ],
    [ "polyheap", "d3/d5a/classpolyheap.html", "d3/d5a/classpolyheap" ],
    [ "Polynomial", "d6/db7/class_polynomial.html", "d6/db7/class_polynomial" ],
    [ "PolynomialHeap", "d7/d5e/class_polynomial_heap.html", "d7/d5e/class_polynomial_heap" ],
    [ "PolynomialRing", "d5/d58/class_polynomial_ring.html", "d5/d58/class_polynomial_ring" ],
    [ "PolyRing", "d3/dfc/class_poly_ring.html", "d3/dfc/class_poly_ring" ],
    [ "PolyRingFlat", "de/dba/class_poly_ring_flat.html", "de/dba/class_poly_ring_flat" ],
    [ "PolyRingQuotient", "dd/dc9/class_poly_ring_quotient.html", "dd/dc9/class_poly_ring_quotient" ],
    [ "pre_spair", "d1/deb/structpre__spair.html", "d1/deb/structpre__spair" ],
    [ "PreSPairSorter", "d0/de8/class_pre_s_pair_sorter.html", "d0/de8/class_pre_s_pair_sorter" ],
    [ "PriorityQueuePolynomialHeap", "de/d49/class_priority_queue_polynomial_heap.html", "de/d49/class_priority_queue_polynomial_heap" ],
    [ "QRingInfo", "d2/da2/class_q_ring_info.html", "d2/da2/class_q_ring_info" ],
    [ "QRingInfo_field", "d5/d13/class_q_ring_info__field.html", "d5/d13/class_q_ring_info__field" ],
    [ "QRingInfo_field_basic", "da/d22/class_q_ring_info__field__basic.html", "da/d22/class_q_ring_info__field__basic" ],
    [ "QRingInfo_field_QQ", "d2/d56/class_q_ring_info__field___q_q.html", "d2/d56/class_q_ring_info__field___q_q" ],
    [ "QRingInfo_ZZ", "dc/d6c/class_q_ring_info___z_z.html", "dc/d6c/class_q_ring_info___z_z" ],
    [ "QuickSorter", "d5/d18/class_quick_sorter.html", "d5/d18/class_quick_sorter" ],
    [ "Range", "dc/d37/class_range.html", "dc/d37/class_range" ],
    [ "ReducedGB", "d9/d3f/class_reduced_g_b.html", "d9/d3f/class_reduced_g_b" ],
    [ "ReducedGB_Field", "db/dbc/class_reduced_g_b___field.html", "db/dbc/class_reduced_g_b___field" ],
    [ "ReducedGB_Field_Local", "dd/dcb/class_reduced_g_b___field___local.html", "dd/dcb/class_reduced_g_b___field___local" ],
    [ "ReducedGB_Field_Local_sorter", "da/da4/struct_reduced_g_b___field___local__sorter.html", "da/da4/struct_reduced_g_b___field___local__sorter" ],
    [ "ReducedGB_Field_sorter", "db/dd8/struct_reduced_g_b___field__sorter.html", "db/dd8/struct_reduced_g_b___field__sorter" ],
    [ "ReducedGB_ZZ", "d5/ddb/class_reduced_g_b___z_z.html", "d5/ddb/class_reduced_g_b___z_z" ],
    [ "ReducedGB_ZZ_sorter", "d8/d0a/struct_reduced_g_b___z_z__sorter.html", "d8/d0a/struct_reduced_g_b___z_z__sorter" ],
    [ "RElement", "d5/de8/class_r_element.html", null ],
    [ "res2_comp", "db/d31/classres2__comp.html", "db/d31/classres2__comp" ],
    [ "res2_level", "d7/dcd/structres2__level.html", "d7/dcd/structres2__level" ],
    [ "res2_pair", "d0/d5c/structres2__pair.html", "d0/d5c/structres2__pair" ],
    [ "res2_poly", "d8/da3/classres2__poly.html", "d8/da3/classres2__poly" ],
    [ "res2term", "d2/dbf/structres2term.html", "d2/dbf/structres2term" ],
    [ "res_comp", "d5/d17/classres__comp.html", "d5/d17/classres__comp" ],
    [ "res_degree", "dd/d86/classres__degree.html", "dd/d86/classres__degree" ],
    [ "res_level", "d1/d07/classres__level.html", "d1/d07/classres__level" ],
    [ "res_pair", "dc/d2a/classres__pair.html", "dc/d2a/classres__pair" ],
    [ "res_poly", "d6/dac/classres__poly.html", "d6/dac/classres__poly" ],
    [ "ResF4MonomialLookupTableT", "da/d5f/class_res_f4_monomial_lookup_table_t.html", "da/d5f/class_res_f4_monomial_lookup_table_t" ],
    [ "ResF4toM2Interface", "d2/d32/class_res_f4to_m2_interface.html", "d2/d32/class_res_f4to_m2_interface" ],
    [ "ResMemoryBlock", "d9/d2f/class_res_memory_block.html", "d9/d2f/class_res_memory_block" ],
    [ "ResMonoidDense", "dc/d0d/class_res_monoid_dense.html", "dc/d0d/class_res_monoid_dense" ],
    [ "ResMonoidSparse", "d5/df9/class_res_monoid_sparse.html", "d5/df9/class_res_monoid_sparse" ],
    [ "ResMonomialsIgnoringComponent", "d1/dac/class_res_monomials_ignoring_component.html", "d1/dac/class_res_monomials_ignoring_component" ],
    [ "ResMonomialSorter", "d8/d9c/class_res_monomial_sorter.html", "d8/d9c/class_res_monomial_sorter" ],
    [ "ResMonomialsWithComponent", "d8/d28/class_res_monomials_with_component.html", "d8/d28/class_res_monomials_with_component" ],
    [ "ResolutionComputation", "dd/d51/class_resolution_computation.html", "dd/d51/class_resolution_computation" ],
    [ "ResPolynomial", "db/d8e/class_res_polynomial.html", "db/d8e/class_res_polynomial" ],
    [ "ResPolynomialConstructor", "d7/d3d/class_res_polynomial_constructor.html", "d7/d3d/class_res_polynomial_constructor" ],
    [ "ResPolynomialIterator", "df/db4/class_res_polynomial_iterator.html", "df/db4/class_res_polynomial_iterator" ],
    [ "ResPolyRing", "d1/d4c/class_res_poly_ring.html", "d1/d4c/class_res_poly_ring" ],
    [ "ResSchreyerOrder", "df/de7/struct_res_schreyer_order.html", "df/de7/struct_res_schreyer_order" ],
    [ "resterm", "d9/d1b/structresterm.html", "d9/d1b/structresterm" ],
    [ "Ring", "dd/dcf/class_ring.html", "dd/dcf/class_ring" ],
    [ "ring_elem", "d5/d64/unionring__elem.html", "d5/d64/unionring__elem" ],
    [ "RingElement", "d6/de2/class_ring_element.html", "d6/de2/class_ring_element" ],
    [ "RingElementGenerator", "df/d9f/class_ring_element_generator.html", "df/d9f/class_ring_element_generator" ],
    [ "RingMap", "d6/d6a/class_ring_map.html", "d6/d6a/class_ring_map" ],
    [ "RingZZ", "d8/d2b/class_ring_z_z.html", "d8/d2b/class_ring_z_z" ],
    [ "row_elem", "dc/d50/structrow__elem.html", "dc/d50/structrow__elem" ],
    [ "s_pair", "d8/d45/structs__pair.html", "d8/d45/structs__pair" ],
    [ "s_pair_heap", "db/d49/classs__pair__heap.html", "db/d49/classs__pair__heap" ],
    [ "sagbi", "dc/d5a/classsagbi.html", "dc/d5a/classsagbi" ],
    [ "SchreyerFrame", "dd/d1a/class_schreyer_frame.html", "dd/d1a/class_schreyer_frame" ],
    [ "SchreyerOrder", "d4/d92/class_schreyer_order.html", "d4/d92/class_schreyer_order" ],
    [ "SchreyerOrder_symm", "dc/d2a/struct_schreyer_order__symm.html", "dc/d2a/struct_schreyer_order__symm" ],
    [ "schur_poly", "d9/d25/classschur__poly.html", "d9/d25/classschur__poly" ],
    [ "schur_poly_heap", "d7/d0c/classschur__poly__heap.html", "d7/d0c/classschur__poly__heap" ],
    [ "schur_poly_iterator", "d7/d11/classschur__poly__iterator.html", "d7/d11/classschur__poly__iterator" ],
    [ "SchurRing", "dd/ddb/class_schur_ring.html", "dd/ddb/class_schur_ring" ],
    [ "SchurRing2", "df/da2/class_schur_ring2.html", "df/da2/class_schur_ring2" ],
    [ "SchurSnRing", "d7/d6f/class_schur_sn_ring.html", "d7/d6f/class_schur_sn_ring" ],
    [ "SkewMultiplication", "d0/d29/class_skew_multiplication.html", "d0/d29/class_skew_multiplication" ],
    [ "SkewPolynomialRing", "dc/d98/class_skew_polynomial_ring.html", "dc/d98/class_skew_polynomial_ring" ],
    [ "slab", "dc/d02/classslab.html", "dc/d02/classslab" ],
    [ "SLEvaluator", "d0/d4e/class_s_l_evaluator.html", "d0/d4e/class_s_l_evaluator" ],
    [ "SLEvaluatorConcrete", "d2/dbe/class_s_l_evaluator_concrete.html", "d2/dbe/class_s_l_evaluator_concrete" ],
    [ "SLP", "da/d22/class_s_l_p.html", "da/d22/class_s_l_p" ],
    [ "SLProgram", "d3/dd3/class_s_l_program.html", "d3/dd3/class_s_l_program" ],
    [ "SMat", "da/de0/class_s_mat.html", "da/de0/class_s_mat" ],
    [ "Solution", "da/dc2/struct_solution.html", "da/dc2/struct_solution" ],
    [ "SolvableAlgebra", "db/daa/class_solvable_algebra.html", "db/daa/class_solvable_algebra" ],
    [ "sorter", "df/d8a/structsorter.html", "df/d8a/structsorter" ],
    [ "spair", "d5/dc0/structspair.html", "d5/dc0/structspair" ],
    [ "sparse_row", "df/d30/structsparse__row.html", "df/d30/structsparse__row" ],
    [ "SPolySorter", "d7/df0/class_s_poly_sorter.html", "d7/df0/class_s_poly_sorter" ],
    [ "stash", "d1/d5b/classstash.html", "d1/d5b/classstash" ],
    [ "StatsAllocator", "d9/dd2/class_stats_allocator.html", "d9/dd2/class_stats_allocator" ],
    [ "StopConditions", "d6/d5d/struct_stop_conditions.html", "d6/d5d/struct_stop_conditions" ],
    [ "StraightLineProgram", "d5/df6/class_straight_line_program.html", "d5/df6/class_straight_line_program" ],
    [ "SubMatrix", "d3/da1/struct_sub_matrix.html", "d3/da1/struct_sub_matrix" ],
    [ "Subsets", "da/d91/class_subsets.html", "da/d91/class_subsets" ],
    [ "SuffixTree", "d7/df2/class_suffix_tree.html", "d7/df2/class_suffix_tree" ],
    [ "SuffixTreeNode", "dc/dad/class_suffix_tree_node.html", "dc/dad/class_suffix_tree_node" ],
    [ "SumCollector", "da/d60/class_sum_collector.html", "da/d60/class_sum_collector" ],
    [ "SumCollectorDefault", "d0/de7/class_sum_collector_default.html", "d0/de7/class_sum_collector_default" ],
    [ "SumCollectorFreeAlgebraHeap", "d3/d26/class_sum_collector_free_algebra_heap.html", "d3/d26/class_sum_collector_free_algebra_heap" ],
    [ "SumCollectorPolyHeap", "d8/d2f/class_sum_collector_poly_heap.html", "d8/d2f/class_sum_collector_poly_heap" ],
    [ "SymmMatrix", "db/d15/class_symm_matrix.html", "db/d15/class_symm_matrix" ],
    [ "Table_T", "d6/d47/struct_table___t.html", "d6/d47/struct_table___t" ],
    [ "tableau", "d8/dee/classtableau.html", "d8/dee/classtableau" ],
    [ "tableau2", "dd/d69/classtableau2.html", "dd/d69/classtableau2" ],
    [ "TermIterator", "d9/d6d/struct_term_iterator.html", "d9/d6d/struct_term_iterator" ],
    [ "Tower", "d2/dcb/class_tower.html", "d2/dcb/class_tower" ],
    [ "TowerEvaluator", "dc/d52/class_tower_evaluator.html", "dc/d52/class_tower_evaluator" ],
    [ "TowerPolynomial", "da/dd1/struct_tower_polynomial_struct.html", "da/dd1/struct_tower_polynomial_struct" ],
    [ "TrivialHomotopyAlgorithm", "d5/da7/class_trivial_homotopy_algorithm.html", null ],
    [ "TrivialPolynomialHeap", "d4/d7a/class_trivial_polynomial_heap.html", "d4/d7a/class_trivial_polynomial_heap" ],
    [ "VariablePrecisionHomotopyAlgorithm", "d4/d16/class_variable_precision_homotopy_algorithm.html", null ],
    [ "vec", "d6/ddd/structvecterm.html", "d6/ddd/structvecterm" ],
    [ "vecHeap", "d1/d2c/classvec_heap.html", "d1/d2c/classvec_heap" ],
    [ "VectorArithmetic", "d1/df6/class_vector_arithmetic.html", "d1/df6/class_vector_arithmetic" ],
    [ "VectorArithmeticStats", "d6/d59/class_vector_arithmetic_stats.html", "d6/d59/class_vector_arithmetic_stats" ],
    [ "WeylAlgebra", "dd/dc2/class_weyl_algebra.html", "dd/dc2/class_weyl_algebra" ],
    [ "Word", "d3/da0/class_word.html", "d3/da0/class_word" ],
    [ "WordTable", "d6/def/class_word_table.html", "d6/def/class_word_table" ],
    [ "WordWithData", "d2/d05/class_word_with_data.html", "d2/d05/class_word_with_data" ],
    [ "WordWithDataTable", "dd/d60/class_word_with_data_table.html", "dd/d60/class_word_with_data_table" ],
    [ "Z_mod", "d7/d1a/class_z__mod.html", "d7/d1a/class_z__mod" ],
    [ "ZipIterator", "d3/def/class_zip_iterator.html", "d3/def/class_zip_iterator" ]
];