var dir_8587dbd6c5a5c081f70c427936cccafd =
[
    [ "aring.cpp", "d6/d92/interface_2aring_8cpp.html", "d6/d92/interface_2aring_8cpp" ],
    [ "aring.h", "d7/d9e/aring_8h.html", "d7/d9e/aring_8h" ],
    [ "computation.h", "d3/d00/computation_8h.html", "d3/d00/computation_8h" ],
    [ "cra.cpp", "dd/d31/interface_2cra_8cpp.html", "dd/d31/interface_2cra_8cpp" ],
    [ "cra.h", "d2/d24/cra_8h.html", "d2/d24/cra_8h" ],
    [ "factory.cpp", "d2/dc2/factory_8cpp.html", "d2/dc2/factory_8cpp" ],
    [ "factory.h", "de/d06/factory_8h.html", "de/d06/factory_8h" ],
    [ "flint.cpp", "d8/de6/flint_8cpp.html", "d8/de6/flint_8cpp" ],
    [ "flint.h", "d0/d97/flint_8h.html", "d0/d97/flint_8h" ],
    [ "freemodule.cpp", "d8/d14/freemodule_8cpp.html", "d8/d14/freemodule_8cpp" ],
    [ "freemodule.h", "d6/d6e/freemodule_8h.html", "d6/d6e/freemodule_8h" ],
    [ "gmp-util.h", "d0/d41/gmp-util_8h.html", "d0/d41/gmp-util_8h" ],
    [ "groebner.cpp", "d2/dc8/groebner_8cpp.html", "d2/dc8/groebner_8cpp" ],
    [ "groebner.h", "d0/d7a/groebner_8h.html", "d0/d7a/groebner_8h" ],
    [ "matrix.cpp", "d3/d2d/interface_2matrix_8cpp.html", "d3/d2d/interface_2matrix_8cpp" ],
    [ "matrix.h", "dd/df4/matrix_8h.html", "dd/df4/matrix_8h" ],
    [ "monoid.cpp", "d3/df2/interface_2monoid_8cpp.html", "d3/df2/interface_2monoid_8cpp" ],
    [ "monoid.h", "d8/da8/monoid_8h.html", "d8/da8/monoid_8h" ],
    [ "monomial-ideal.cpp", "d9/db6/monomial-ideal_8cpp.html", "d9/db6/monomial-ideal_8cpp" ],
    [ "monomial-ideal.h", "d9/d92/monomial-ideal_8h.html", "d9/d92/monomial-ideal_8h" ],
    [ "monomial-ordering.cpp", "d1/df6/monomial-ordering_8cpp.html", "d1/df6/monomial-ordering_8cpp" ],
    [ "monomial-ordering.h", "de/daf/monomial-ordering_8h.html", "de/daf/monomial-ordering_8h" ],
    [ "mutable-matrix.cpp", "d3/dc5/mutable-matrix_8cpp.html", "d3/dc5/mutable-matrix_8cpp" ],
    [ "mutable-matrix.h", "df/d3c/mutable-matrix_8h.html", "df/d3c/mutable-matrix_8h" ],
    [ "NAG.h", "d3/db7/_n_a_g_8h.html", "d3/db7/_n_a_g_8h" ],
    [ "polyroots.cpp", "d1/df6/polyroots_8cpp.html", "d1/df6/polyroots_8cpp" ],
    [ "random.cpp", "de/daa/random_8cpp.html", "de/daa/random_8cpp" ],
    [ "random.h", "d1/d79/random_8h.html", "d1/d79/random_8h" ],
    [ "ring.cpp", "d6/da2/interface_2ring_8cpp.html", "d6/da2/interface_2ring_8cpp" ],
    [ "ring.h", "d0/d6d/ring_8h.html", "d0/d6d/ring_8h" ],
    [ "ringelement.cpp", "d2/d37/ringelement_8cpp.html", "d2/d37/ringelement_8cpp" ],
    [ "ringelement.h", "d1/d1d/ringelement_8h.html", "d1/d1d/ringelement_8h" ],
    [ "ringmap.cpp", "d9/d39/interface_2ringmap_8cpp.html", "d9/d39/interface_2ringmap_8cpp" ],
    [ "ringmap.h", "df/da3/ringmap_8h.html", "df/da3/ringmap_8h" ]
];