var dir_64a5a84e685b0d343f77bbf9741b61a7 =
[
    [ "comp-gb-declared.cpp", "d0/db1/comp-gb-declared_8cpp.html", null ],
    [ "comp-gb-declared.hpp", "d3/d11/comp-gb-declared_8hpp.html", null ],
    [ "comp-gb-proxy.cpp", "d8/da2/comp-gb-proxy_8cpp.html", null ],
    [ "comp-gb-proxy.hpp", "d3/db4/comp-gb-proxy_8hpp.html", null ],
    [ "comp-gb.cpp", "da/d4d/comp-gb_8cpp.html", "da/d4d/comp-gb_8cpp" ],
    [ "comp-gb.hpp", "d7/ddf/comp-gb_8hpp.html", "d7/ddf/comp-gb_8hpp" ],
    [ "gb-default.cpp", "d5/dd0/gb-default_8cpp.html", "d5/dd0/gb-default_8cpp" ],
    [ "gb-default.hpp", "d0/dd0/gb-default_8hpp.html", "d0/dd0/gb-default_8hpp" ],
    [ "gb-homog2.cpp", "d1/d54/gb-homog2_8cpp.html", null ],
    [ "gb-homog2.hpp", "d7/d0a/gb-homog2_8hpp.html", "d7/d0a/gb-homog2_8hpp" ],
    [ "gb-sugarless.cpp", "d6/db9/gb-sugarless_8cpp.html", "d6/db9/gb-sugarless_8cpp" ],
    [ "gb-sugarless.hpp", "d1/d91/gb-sugarless_8hpp.html", null ],
    [ "gb-toric.cpp", "db/d5c/gb-toric_8cpp.html", "db/d5c/gb-toric_8cpp" ],
    [ "gb-toric.hpp", "de/d75/gb-toric_8hpp.html", "de/d75/gb-toric_8hpp" ],
    [ "gb-walk.cpp", "d2/d4d/gb-walk_8cpp.html", "d2/d4d/gb-walk_8cpp" ],
    [ "gb-walk.hpp", "db/d5c/gb-walk_8hpp.html", null ],
    [ "gbring.cpp", "d0/d29/gbring_8cpp.html", "d0/d29/gbring_8cpp" ],
    [ "gbring.hpp", "d8/d11/gbring_8hpp.html", "d8/d11/gbring_8hpp" ],
    [ "gbweight.cpp", "d8/d1f/gbweight_8cpp.html", null ],
    [ "gbweight.hpp", "d8/d2a/gbweight_8hpp.html", "d8/d2a/gbweight_8hpp" ],
    [ "reducedgb-field-local.cpp", "df/dea/reducedgb-field-local_8cpp.html", "df/dea/reducedgb-field-local_8cpp" ],
    [ "reducedgb-field-local.hpp", "da/da2/reducedgb-field-local_8hpp.html", "da/da2/reducedgb-field-local_8hpp" ],
    [ "reducedgb-field.cpp", "d5/d3a/reducedgb-field_8cpp.html", "d5/d3a/reducedgb-field_8cpp" ],
    [ "reducedgb-field.hpp", "dc/db2/reducedgb-field_8hpp.html", "dc/db2/reducedgb-field_8hpp" ],
    [ "reducedgb-marked.cpp", "d0/dbf/reducedgb-marked_8cpp.html", "d0/dbf/reducedgb-marked_8cpp" ],
    [ "reducedgb-marked.hpp", "df/dc8/reducedgb-marked_8hpp.html", "df/dc8/reducedgb-marked_8hpp" ],
    [ "reducedgb-ZZ.cpp", "db/d16/reducedgb-_z_z_8cpp.html", "db/d16/reducedgb-_z_z_8cpp" ],
    [ "reducedgb-ZZ.hpp", "dc/d1d/reducedgb-_z_z_8hpp.html", "dc/d1d/reducedgb-_z_z_8hpp" ],
    [ "reducedgb.cpp", "d3/d7c/reducedgb_8cpp.html", null ],
    [ "reducedgb.hpp", "d9/deb/reducedgb_8hpp.html", "d9/deb/reducedgb_8hpp" ],
    [ "sagbi.cpp", "d0/de2/sagbi_8cpp.html", null ],
    [ "sagbi.hpp", "d0/d56/sagbi_8hpp.html", "d0/d56/sagbi_8hpp" ],
    [ "spair.cpp", "d9/d52/spair_8cpp.html", "d9/d52/spair_8cpp" ],
    [ "spair.hpp", "d6/daf/spair_8hpp.html", "d6/daf/spair_8hpp" ]
];