var dir_8ed8434bc3d991323934987a3489e746 =
[
    [ "f4-computation.cpp", "db/d5f/f4-computation_8cpp.html", "db/d5f/f4-computation_8cpp" ],
    [ "f4-computation.hpp", "d2/def/f4-computation_8hpp.html", "d2/def/f4-computation_8hpp" ],
    [ "f4-m2-interface.cpp", "d3/d1e/f4-m2-interface_8cpp.html", null ],
    [ "f4-m2-interface.hpp", "dc/dbd/f4-m2-interface_8hpp.html", "dc/dbd/f4-m2-interface_8hpp" ],
    [ "f4-mem.cpp", "dc/d3a/f4-mem_8cpp.html", "dc/d3a/f4-mem_8cpp" ],
    [ "f4-mem.hpp", "d1/db6/f4-mem_8hpp.html", "d1/db6/f4-mem_8hpp" ],
    [ "f4-monlookup.cpp", "d8/d46/f4-monlookup_8cpp.html", "d8/d46/f4-monlookup_8cpp" ],
    [ "f4-monlookup.hpp", "db/da3/f4-monlookup_8hpp.html", "db/da3/f4-monlookup_8hpp" ],
    [ "f4-spairs.cpp", "db/de6/f4-spairs_8cpp.html", "db/de6/f4-spairs_8cpp" ],
    [ "f4-spairs.hpp", "d0/dbe/f4-spairs_8hpp.html", "d0/dbe/f4-spairs_8hpp" ],
    [ "f4-types.hpp", "d7/dfc/f4-types_8hpp.html", "d7/dfc/f4-types_8hpp" ],
    [ "f4.cpp", "d3/de5/f4_8cpp.html", null ],
    [ "f4.hpp", "d5/d35/f4_8hpp.html", "d5/d35/f4_8hpp" ],
    [ "hilb-fcn.cpp", "d0/dc6/hilb-fcn_8cpp.html", null ],
    [ "hilb-fcn.hpp", "d7/df6/hilb-fcn_8hpp.html", "d7/df6/hilb-fcn_8hpp" ],
    [ "memblock.hpp", "db/d74/memblock_8hpp.html", "db/d74/memblock_8hpp" ],
    [ "monhashtable.cpp", "d0/d42/monhashtable_8cpp.html", "d0/d42/monhashtable_8cpp" ],
    [ "monhashtable.hpp", "dd/dfe/monhashtable_8hpp.html", "dd/dfe/monhashtable_8hpp" ],
    [ "moninfo.cpp", "de/d97/moninfo_8cpp.html", null ],
    [ "moninfo.hpp", "d5/d0a/moninfo_8hpp.html", "d5/d0a/moninfo_8hpp" ],
    [ "ntuple-monomial.hpp", "d5/d04/ntuple-monomial_8hpp.html", "d5/d04/ntuple-monomial_8hpp" ],
    [ "varpower-monomial.hpp", "d6/dac/varpower-monomial_8hpp.html", "d6/dac/varpower-monomial_8hpp" ]
];