var dir_6d3e1fc03a2c0fe268d053df8b4dd308 =
[
    [ "allocator.cpp", "d6/d89/allocator_8cpp.html", "d6/d89/allocator_8cpp" ],
    [ "allocator.hpp", "d5/d61/allocator_8hpp.html", "d5/d61/allocator_8hpp" ],
    [ "bibasis.cpp", "d9/db0/bibasis_8cpp.html", "d9/db0/bibasis_8cpp" ],
    [ "bibasis.hpp", "d8/df2/bibasis_8hpp.html", null ],
    [ "involutive.hpp", "dd/d24/involutive_8hpp.html", "dd/d24/involutive_8hpp" ],
    [ "janettree.hpp", "df/de3/janettree_8hpp.html", "df/de3/janettree_8hpp" ],
    [ "launcher.cpp", "d0/db5/launcher_8cpp.html", null ],
    [ "launcher.hpp", "dc/da0/launcher_8hpp.html", "dc/da0/launcher_8hpp" ],
    [ "monom.cpp", "db/db2/monom_8cpp.html", null ],
    [ "monom.hpp", "d6/d95/monom_8hpp.html", "d6/d95/monom_8hpp" ],
    [ "monomDL.cpp", "d1/d1e/monom_d_l_8cpp.html", null ],
    [ "monomDL.hpp", "db/d81/monom_d_l_8hpp.html", "db/d81/monom_d_l_8hpp" ],
    [ "monomDRL.cpp", "d4/d75/monom_d_r_l_8cpp.html", null ],
    [ "monomDRL.hpp", "de/d41/monom_d_r_l_8hpp.html", "de/d41/monom_d_r_l_8hpp" ],
    [ "monomLex.cpp", "db/df1/monom_lex_8cpp.html", null ],
    [ "monomLex.hpp", "d2/d9f/monom_lex_8hpp.html", "d2/d9f/monom_lex_8hpp" ],
    [ "pcomparator.hpp", "d8/dec/pcomparator_8hpp.html", "d8/dec/pcomparator_8hpp" ],
    [ "polynom.hpp", "dc/d7e/polynom_8hpp.html", "dc/d7e/polynom_8hpp" ],
    [ "qset.hpp", "d2/d09/qset_8hpp.html", "d2/d09/qset_8hpp" ],
    [ "settings-manager.cpp", "d9/d86/settings-manager_8cpp.html", "d9/d86/settings-manager_8cpp" ],
    [ "settings-manager.hpp", "d0/ddb/settings-manager_8hpp.html", "d0/ddb/settings-manager_8hpp" ],
    [ "triple.hpp", "d6/d7a/triple_8hpp.html", "d6/d7a/triple_8hpp" ],
    [ "tset.hpp", "d7/d76/tset_8hpp.html", "d7/d76/tset_8hpp" ]
];