var dir_208df166e208656f2e3436240a4845e8 =
[
    [ "res-dep-graph.cpp", "d2/df0/res-dep-graph_8cpp.html", null ],
    [ "res-dep-graph.hpp", "d9/db9/res-dep-graph_8hpp.html", null ],
    [ "res-f4-computation.cpp", "d8/dff/res-f4-computation_8cpp.html", "d8/dff/res-f4-computation_8cpp" ],
    [ "res-f4-computation.hpp", "d0/d2f/res-f4-computation_8hpp.html", "d0/d2f/res-f4-computation_8hpp" ],
    [ "res-f4-m2-interface.cpp", "dc/d4f/res-f4-m2-interface_8cpp.html", "dc/d4f/res-f4-m2-interface_8cpp" ],
    [ "res-f4-m2-interface.hpp", "d6/db7/res-f4-m2-interface_8hpp.html", "d6/db7/res-f4-m2-interface_8hpp" ],
    [ "res-f4-monlookup.cpp", "d3/d2d/res-f4-monlookup_8cpp.html", "d3/d2d/res-f4-monlookup_8cpp" ],
    [ "res-f4-monlookup.hpp", "d1/d79/res-f4-monlookup_8hpp.html", "d1/d79/res-f4-monlookup_8hpp" ],
    [ "res-f4.cpp", "de/dd9/res-f4_8cpp.html", "de/dd9/res-f4_8cpp" ],
    [ "res-f4.hpp", "db/d0d/res-f4_8hpp.html", "db/d0d/res-f4_8hpp" ],
    [ "res-memblock.hpp", "d1/d36/res-memblock_8hpp.html", "d1/d36/res-memblock_8hpp" ],
    [ "res-moninfo-dense.cpp", "d8/dd0/res-moninfo-dense_8cpp.html", null ],
    [ "res-moninfo-dense.hpp", "d0/d58/res-moninfo-dense_8hpp.html", "d0/d58/res-moninfo-dense_8hpp" ],
    [ "res-moninfo-sparse.cpp", "d0/d4e/res-moninfo-sparse_8cpp.html", null ],
    [ "res-moninfo-sparse.hpp", "d5/d3f/res-moninfo-sparse_8hpp.html", "d5/d3f/res-moninfo-sparse_8hpp" ],
    [ "res-moninfo.cpp", "d9/d62/res-moninfo_8cpp.html", null ],
    [ "res-moninfo.hpp", "d5/db7/res-moninfo_8hpp.html", "d5/db7/res-moninfo_8hpp" ],
    [ "res-monomial-sorter.cpp", "df/dc4/res-monomial-sorter_8cpp.html", null ],
    [ "res-monomial-sorter.hpp", "da/d4a/res-monomial-sorter_8hpp.html", "da/d4a/res-monomial-sorter_8hpp" ],
    [ "res-monomial-types.hpp", "d7/d0a/res-monomial-types_8hpp.html", "d7/d0a/res-monomial-types_8hpp" ],
    [ "res-poly-ring.cpp", "d4/dd3/res-poly-ring_8cpp.html", "d4/dd3/res-poly-ring_8cpp" ],
    [ "res-poly-ring.hpp", "da/d96/res-poly-ring_8hpp.html", "da/d96/res-poly-ring_8hpp" ],
    [ "res-schreyer-frame.cpp", "d0/d16/res-schreyer-frame_8cpp.html", null ],
    [ "res-schreyer-frame.hpp", "df/dd9/res-schreyer-frame_8hpp.html", "df/dd9/res-schreyer-frame_8hpp" ],
    [ "res-schreyer-order.hpp", "d5/d7b/res-schreyer-order_8hpp.html", "d5/d7b/res-schreyer-order_8hpp" ],
    [ "res-tasking-example.cpp", "d0/dfb/res-tasking-example_8cpp.html", "d0/dfb/res-tasking-example_8cpp" ]
];