Macaulay2 Engine: MatrixConstructor::set_column_degree
set_column_degree()
void MatrixConstructor::set_column_degree (int i, const_monomial deg)
Definition at line 69 of file matrix-con.cpp.
 {
   if (cols_frozen)
     {
       INTERNAL_ERROR("trying to append to an immutable free module.");
     }
   FreeModule *mutable_cols = const_cast<FreeModule *>(cols);
   mutable_cols->change_degree(i, deg0);
 }
References FreeModule::change_degree(), cols, cols_frozen, and INTERNAL_ERROR().
Referenced by IM2_Matrix_concat().