Macaulay2 Engine: MatrixConstructor::set_entry
set_entry()
void MatrixConstructor::set_entry (int r, int c, ring_elem a)
Definition at line 54 of file matrix-con.cpp.
{
  R->set_entry(entries[c], r, a);
}
References entries, R, and Ring::set_entry().
Referenced by PolyRingQuotient::ann(), Matrix::content(), DetComputation::DetComputation(), SLP< Field >::evaluate(), FreeModule::get_induced_order(), PathTracker::getAllSolutions(), PathTracker::getSolution(), Matrix::identity(), IM2_Matrix_lift(), IM2_Matrix_promote(), LocalRing::is_in_prime(), Matrix::koszul(), Matrix::koszul(), Matrix::koszul_monomials(), LocalRing::lift_up(), Matrix::make(), Matrix::make(), Matrix::make(), PolyRingQuotient::make_gb(), Matrix::make_sparse_vecs(), matrixFromSparseMatrixGenerator(), NCCoefficientMatrix(), polyListToMatrix(), PolyRingQuotient::quotient(), Matrix::random(), rawFourierMotzkin(), rawHilbertBasis(), PathTracker::refine(), PolyRingQuotient::remainder(), PolyRingQuotient::remainderAndQuotient(), Matrix::reshape(), Matrix::split_off_content(), DetComputation::step(), Matrix::sub_matrix(), sagbi::subduct(), sagbi::subduct(), sagbi::subduct1(), sagbi::subduct1(), PolyRingQuotient::syzygy(), toMatrix(), toMatrix(), Matrix::transpose(), and Matrix::wedge_product().