Macaulay2 Engine: MatrixConstructor::append
append() [1/2]
void MatrixConstructor::append (vec v)
Definition at line 35 of file matrix-con.cpp.
 {
   assert(!cols_frozen);
   monomial d = R->degree_monoid()->make_one();
   if (v != nullptr) R->vec_multi_degree(rows, v, d);
   append(v, d);
   R->degree_monoid()->remove(d);
 }
References append(), cols_frozen, Ring::degree_monoid(), Monoid::make_one(), R, Monoid::remove(), rows, and Ring::vec_multi_degree().
Referenced by append(), MatrixStream::appendPolynomialDone(), BRPStoMatrix(), gb2_comp::change_matrix(), Matrix::coeffs(), Matrix::compress(), DetComputation::DetComputation(), Matrix::divide_by_var(), RingMap::eval(), gb2_comp::gb_matrix(), GaussElimComputation::get_change(), GB_comp::get_change(), HermiteComputation::get_change(), ReducedGB::get_change(), GaussElimComputation::get_gb(), GB_comp::get_gb(), binomialGB_comp::get_gb(), HermiteComputation::get_gb(), ReducedGB::get_gb(), F4Computation::get_gb(), GaussElimComputation::get_initial(), GB_comp::get_initial(), binomialGB_comp::get_initial(), HermiteComputation::get_initial(), MarkedGB::get_initial(), ReducedGB::get_initial(), gbA::get_mingens(), GB_comp::get_mingens(), GBinhom_comp::get_mingens(), binomialGB_comp::get_mingens(), GB_comp::get_parallel_lead_terms(), MarkedGB::get_parallel_lead_terms(), ReducedGB::get_parallel_lead_terms(), GaussElimComputation::get_syzygies(), gbA::get_syzygies(), GB_comp::get_syzygies(), HermiteComputation::get_syzygies(), PolynomialRing::getPresentation(), IM2_Matrix_concat(), gb2_comp::initial_matrix(), KBasis::insert(), gbA::make_lead_term_matrix(), GB_comp::matrix_lift(), Matrix::monomials(), NCMonomialMatrix(), GBinhom_comp::new_gen(), PfaffianComputation::PfaffianComputation(), Matrix::remove_monomial_factors(), Matrix::remove_scalar_multiples(), GBinhom_comp::s_pair_step(), DetComputation::step(), PfaffianComputation::step(), binomialGB_comp::subring(), binomialGB_comp::subringGB(), BIBasis::BooleanInvolutiveBasis< MonomType >::ToMatrix(), and Matrix::top_coefficients().