Macaulay2 Engine: MatrixConstructor::MatrixConstructor
MatrixConstructor() [3/3]
MatrixConstructor::MatrixConstructor (const FreeModule * target, const FreeModule * source, const_monomial deg = nullptr)
Definition at line 23 of file matrix-con.cpp.
     : R(target->get_ring()), rows(target), cols(source), cols_frozen(true)
 {
   entries.reserve(source->rank());
   for (int i = 0; i < source->rank(); i++) entries.push_back(nullptr);
   deg = (deg0 == nullptr ? R->degree_monoid()->make_one()
                    : R->degree_monoid()->make_new(deg0));
 }
References deg, Ring::degree_monoid(), entries, Monoid::make_new(), Monoid::make_one(), R, and FreeModule::rank().