Macaulay2 Engine: MatrixConstructor::compute_column_degree
compute_column_degree()
void MatrixConstructor::compute_column_degree (int i) private
Definition at line 79 of file matrix-con.cpp.
 {
   if (cols_frozen)
     {
       INTERNAL_ERROR("trying to append to an immutable free module.");
     }
   monomial d = R->degree_monoid()->make_one();
   const vec v = entries[i];
   if (v != nullptr) R->vec_multi_degree(rows, v, d);
   FreeModule *mutable_cols = const_cast<FreeModule *>(cols);
   mutable_cols->change_degree(i, d);
   R->degree_monoid()->remove(d);
 }
References FreeModule::change_degree(), cols, cols_frozen, Ring::degree_monoid(), entries, INTERNAL_ERROR(), Monoid::make_one(), R, Monoid::remove(), rows, and Ring::vec_multi_degree().
Referenced by compute_column_degrees().