Macaulay2 Engine: MatrixConstructor::set_column
set_column()
void MatrixConstructor::set_column (int c, vec v)
Definition at line 58 of file matrix-con.cpp.
 { entries[c] = v; }
References entries.
Referenced by Matrix::clean(), Matrix::concat(), ChineseRemainder::CRA(), Matrix::diff(), Matrix::direct_sum(), Matrix::flip(), Matrix::homogenize(), Matrix::lead_term(), res2_comp::make(), res_comp::make(), HilbertController::make_lead_term_matrix(), gb2_comp::make_lead_term_matrix(), res2_comp::make_minimal(), res_comp::make_minimal(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), gb2_comp::min_gens_matrix(), Matrix::module_tensor(), Matrix::mult(), Matrix::operator+(), Matrix::operator-(), rawMatrixRatConversion(), gbres_comp::reduce(), Matrix::remake(), Matrix::remove_content(), Matrix::scalar_mult(), Matrix::split_off_content(), Matrix::sub_matrix(), SymmMatrix::symm1(), Matrix::tensor(), F4toM2Interface::to_M2_matrix(), ResF4toM2Interface::to_M2_matrix(), and GBMatrix::to_matrix().