Macaulay2 Engine: MatrixConstructor::to_matrix
to_matrix()
Matrix * MatrixConstructor::to_matrix ()
Definition at line 94 of file matrix-con.cpp.
 {
   //  if (!will_be_mutable && !cols->is_frozen)
   //    cols->freeze(hashval);
   return new Matrix(rows, cols, deg, entries);
 }
References cols, deg, entries, Matrix, and rows.
Referenced by PolyRingQuotient::ann(), BRPStoMatrix(), gb2_comp::change_matrix(), Matrix::clean(), Matrix::coeffs(), Matrix::compress(), Matrix::concat(), Matrix::content(), ChineseRemainder::CRA(), DetComputation::determinants(), Matrix::diff(), Matrix::direct_sum(), Matrix::divide_by_var(), RingMap::eval(), SLP< Field >::evaluate(), Matrix::flip(), gb2_comp::gb_matrix(), GaussElimComputation::get_change(), GB_comp::get_change(), HermiteComputation::get_change(), ReducedGB::get_change(), GaussElimComputation::get_gb(), GB_comp::get_gb(), binomialGB_comp::get_gb(), HermiteComputation::get_gb(), ReducedGB::get_gb(), F4Computation::get_gb(), FreeModule::get_induced_order(), GaussElimComputation::get_initial(), GB_comp::get_initial(), binomialGB_comp::get_initial(), HermiteComputation::get_initial(), MarkedGB::get_initial(), ReducedGB::get_initial(), NCResComputation::get_matrix(), gbA::get_mingens(), GB_comp::get_mingens(), GBinhom_comp::get_mingens(), binomialGB_comp::get_mingens(), GB_comp::get_parallel_lead_terms(), MarkedGB::get_parallel_lead_terms(), ReducedGB::get_parallel_lead_terms(), GaussElimComputation::get_syzygies(), gbA::get_syzygies(), GB_comp::get_syzygies(), GBinhom_comp::get_syzygies(), HermiteComputation::get_syzygies(), PathTracker::getAllSolutions(), PolynomialRing::getPresentation(), PathTracker::getSolution(), Matrix::homogenize(), MatrixStream::idealDone(), Matrix::identity(), IM2_Matrix_concat(), IM2_Matrix_lift(), IM2_Matrix_promote(), gb2_comp::initial_matrix(), LocalRing::is_in_prime(), Matrix::koszul(), Matrix::koszul_monomials(), Matrix::lead_term(), LocalRing::lift_up(), Matrix::make(), res2_comp::make(), res_comp::make(), PolyRingQuotient::make_gb(), HilbertController::make_lead_term_matrix(), gbA::make_lead_term_matrix(), gb2_comp::make_lead_term_matrix(), res2_comp::make_minimal(), res_comp::make_minimal(), Matrix::make_sparse(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), matrixFromSparseMatrixGenerator(), gb2_comp::min_gens_matrix(), Matrix::module_tensor(), Matrix::monomials(), Matrix::mult(), NCCoefficientMatrix(), NCMonomialMatrix(), Matrix::operator+(), Matrix::operator-(), PfaffianComputation::pfaffians(), polyListToMatrix(), PolyRingQuotient::quotient(), Matrix::random(), rawMatrixRatConversion(), gbres_comp::reduce(), PathTracker::refine(), PolyRingQuotient::remainder(), PolyRingQuotient::remainderAndQuotient(), Matrix::remake(), Matrix::remove_content(), Matrix::remove_monomial_factors(), Matrix::remove_scalar_multiples(), Matrix::reshape(), Matrix::scalar_mult(), Matrix::split_off_content(), Matrix::sub_matrix(), sagbi::subduct(), sagbi::subduct1(), binomialGB_comp::subring(), binomialGB_comp::subringGB(), PolyRingQuotient::syzygy(), Matrix::tensor(), F4toM2Interface::to_M2_matrix(), ResF4toM2Interface::to_M2_matrix(), GBMatrix::to_matrix(), BIBasis::BooleanInvolutiveBasis< MonomType >::ToMatrix(), toMatrix(), Matrix::top_coefficients(), Matrix::transpose(), KBasis::value(), SymmMatrix::value(), Matrix::wedge_product(), and Matrix::zero().