Macaulay2 Engine: MatrixConstructor::MatrixConstructor
MatrixConstructor() [2/3]
MatrixConstructor::MatrixConstructor (const FreeModule * target, int ncols)
Definition at line 12 of file matrix-con.cpp.
     : R(target->get_ring()), rows(target), cols(nullptr), cols_frozen(false), deg(nullptr)
 {
   cols = R->make_FreeModule(ncols);
   entries.reserve(ncols);
   for (int i = 0; i < ncols; i++) entries.push_back(nullptr);
   deg = R->degree_monoid()->make_one();
 }
References cols, deg, Ring::degree_monoid(), entries, Ring::make_FreeModule(), Monoid::make_one(), and R.