Macaulay2 Engine: MatrixConstructor::compute_column_degrees
compute_column_degrees()
void MatrixConstructor::compute_column_degrees ()
Definition at line 59 of file matrix-con.cpp.
{
  if (cols_frozen)
    {
      INTERNAL_ERROR("trying to append to an immutable free module.");
    }
  for (int i = 0; i < cols->rank(); i++) compute_column_degree(i);
}
References cols, cols_frozen, compute_column_degree(), INTERNAL_ERROR(), and FreeModule::rank().
Referenced by Matrix::homogenize(), IM2_Matrix_lift(), IM2_Matrix_promote(), LocalRing::lift_up(), Matrix::make(), Matrix::make(), Matrix::make_sparse(), polyListToMatrix(), Matrix::remake(), toMatrix(), and toMatrix().