Macaulay2 Engine: getmoremem_atomic
getmoremem_atomic()
char* getmoremem_atomic (char * s, size_t old, size_t new)
Definition at line 144 of file M2mem-replacement.c.
{
      void *p;
      p = GC_MALLOC_ATOMIC(new);
      size_t min = old<new ? old : new;
      if (p == NULL) outofmem2(new);
      memcpy(p, s, min);
      GC_FREE(s);
 #    ifndef NDEBUG
      {
        int excess = new - min;
        if (excess > 0) memset((char *)p+min,0xbe,excess); /* fill with 0xbebebebe */
      }
      trapchk(p);
 #    endif
      return p;
      }
References mpfr::min(), outofmem2(), p, and trapchk().