Macaulay2 Engine: trapchk
trapchk()
void trapchk (void * p)
Definition at line 17 of file M2mem-replacement.c.
                       {
      trapcount++;
      if (trapcount == trapset || p == trapaddr || p == (void *)~(intptr_t)trapaddr) trap();
 }
References p, trap(), trapaddr, trapcount, and trapset.
Referenced by freemem(), freememlen(), getmem(), getmem_atomic(), getmem_atomic_clear(), getmem_clear(), getmem_malloc(), getmoremem(), getmoremem1(), and getmoremem_atomic().