Macaulay2 Engine: getmem_atomic
getmem_atomic()
char* getmem_atomic (size_t n)
Definition at line 88 of file M2mem-replacement.c.
 {
   char *p;
   p = GC_MALLOC_ATOMIC(n);
   if (p == NULL) outofmem2(n);
 #ifndef NDEBUG
   memset(p,0xac,n);     /* fill with 0xacacacac ... */
   trapchk(p);
 #endif
   return p;
 }
References outofmem2(), p, and trapchk().
Referenced by M2_join(), M2_makearrayint(), M2_tocharstar(), M2_tostringn(), monomialOrderMake(), mpfr_reallocate_limbs(), mpz_reallocate_limbs(), and M2::ARingGFFlintBig::to_ring_elem().