Macaulay2 Engine: intern_GB
intern_GB()
void intern_GB (GBComputation * G)
Definition at line 112 of file finalize.cpp.
 {
 #ifdef MEMDEBUG
   GC_REGISTER_FINALIZER_IGNORE_SELF(M2_debug_to_outer(G), remove_gb, 0, 0, 0);
 #else
   GC_REGISTER_FINALIZER_IGNORE_SELF(                  G , remove_gb, 0, 0, 0);
 #endif
   AO_t nfinalized = AO_fetch_and_add1(&gbs_nfinalized);
   if (M2_gbTrace >= 3)
     {
       // -- there is no gettid under Solaris
       // int tid = static_cast<int>(syscall(SYS_gettid));
       // fprintf(stderr, "\n   -- thread %d registering gb %zd at %p\n", tid,
       // nfinalized, (void *)G);
       fprintf(
           stderr, "\n   -- registering gb %zd at %p\n", nfinalized, (void *)G);
     }
 }
References AO_fetch_and_add1(), gbs_nfinalized, M2_gbTrace, and remove_gb().
Referenced by GBComputation::choose_gb().