Macaulay2 Engine: intern_polyring
intern_polyring()
void intern_polyring (const PolynomialRing * G)
Definition at line 80 of file finalize.cpp.
 {
   // We are already setting a finalizer for rings in newdelete.hpp,
   // I believe this one is just unsetting that one.
   return;
 // #ifdef MEMDEBUG
 //   GC_REGISTER_FINALIZER_IGNORE_SELF(M2_debug_to_outer(const_cast<PolynomialRing *>(G)), remove_polyring, 0, 0, 0);
 // #else
 //   GC_REGISTER_FINALIZER_IGNORE_SELF(                  const_cast<PolynomialRing *>(G) , remove_polyring, 0, 0, 0);
 // #endif
 //   AO_t nfinalized = AO_fetch_and_add1(&polyrings_nfinalized);
 //   if (M2_gbTrace >= 3)
 //     fprintf(stderr,
 //             "\n   -- registering polynomial ring %zd at %p\n",
 //             nfinalized,
 //             (const void *)G);
 }
Referenced by IM2_Ring_polyring(), IM2_Ring_quotient(), IM2_Ring_quotient1(), IM2_Ring_schur(), IM2_Ring_skew_polyring(), IM2_Ring_solvable_algebra(), IM2_Ring_weyl_algebra(), and rawDividedPowerRing().