Macaulay2 Engine: internMutableMatrix
internMutableMatrix()
MutableMatrix * internMutableMatrix (MutableMatrix * G)
Definition at line 194 of file finalize.cpp.
{
  if (G == nullptr) return nullptr;
#ifdef MEMDEBUG
  GC_REGISTER_FINALIZER(M2_debug_to_outer(G), remove_MutableMatrix, 0, 0, 0);
#else
  GC_REGISTER_FINALIZER(                  G,  remove_MutableMatrix, nullptr, nullptr, nullptr);
#endif
  std::atomic<int> nfinalized = mutablematrices_nfinalized++;
  if (M2_gbTrace >= 3)
    fprintf(stderr,
            "\n   -- registering mutable matrix %d at %p\n",
            nfinalized.load(),
            (void *)G);
  return G;
}
References G, M2_gbTrace, mutablematrices_nfinalized, and remove_MutableMatrix().
Referenced by IM2_MutableMatrix_copy(), IM2_MutableMatrix_from_matrix(), IM2_MutableMatrix_identity(), IM2_MutableMatrix_make(), IM2_MutableMatrix_submatrix(), IM2_MutableMatrix_submatrix1(), rawLinAlgInverse(), rawLinAlgMult(), rawLinAlgNullSpace(), rawLinAlgRREF(), rawLinAlgSolve(), rawLinAlgSolveInvertible(), and rawMutableMatrixTranspose().