Macaulay2 Engine: almostEqual
almostEqual()
bool almostEqual (const M2::ARingCC & C, unsigned long nbits, const M2::ARingCC::ElementType & a, const M2::ARingCC::ElementType & b)
Definition at line 15 of file ARingCCTest.cpp.
{
  M2::ARingRR::ElementType epsilon = pow(2, static_cast<double>(-nbits));
  M2::ARingRR::ElementType d;
  M2::ARingCC::ElementType c;
  C.subtract(c, a, b);
  C.abs(d, c);
  return C.real_ring().compare_elems(d, epsilon) < 0;
}
References M2::ARingCC::abs(), M2::ARingRR::compare_elems(), M2::ARingCC::real_ring(), and M2::ARingCC::subtract().
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().