Macaulay2 Engine: TEST
TEST() [6/7]
TEST (ARingCC , power_and_invert)
Definition at line 214 of file ARingCCTest.cpp.
 {
   M2::ARingCC C;
   auto nbits = C.get_precision();
   ARingElementGenerator<M2::ARingCC> gen(C);
   M2::ARingCC::ElementType a, b, c, d;
   C.init(a);
   C.init(b);
   C.init(c);
   C.init(d);
   mpz_t gmp1;
   mpz_init(gmp1);
   for (int i = 0; i < ntrials; i++)
     {
       gen.nextElement(a);
       // TODO: what should the answer here be?
       // EXPECT_TRUE(R->is_equal(R->power(a, 0), R->one())); // 0^0 == 1 too?
       C.power(b, a, 1);
       EXPECT_TRUE(C.is_equal(b, a));
       int e1 = rawRandomInt(10) + 1;
       int e2 = rawRandomInt(10) + 1;
       C.power(b, a, e1);
       C.power(c, a, e2);
       C.power(d, a, e1 + e2);
       C.mult(c, b, c);
       EXPECT_TRUE(almostEqual(C, nbits - 11, c, d)); /* exponentiation gives
                                                   relatively small number
                                                   of correct digits */
       // Make sure that powers via mpz work (at least for small exponents)
       mpz_set_si(gmp1, e1);
       C.power_mpz(d, a, gmp1);
       EXPECT_TRUE(fabs(d.re - b.re) < 1.e-14);
       EXPECT_TRUE(fabs(d.im - b.im) < 1.e-14);
     }
   mpz_clear(gmp1);
   C.clear(d);
   C.clear(c);
   C.clear(b);
   C.clear(a);
 }
References almostEqual(), M2::ARingCC::clear(), mpfr::fabs(), M2::ARingCC::get_precision(), cc_doubles_struct::im, M2::ARingCC::init(), M2::ARingCC::is_equal(), M2::ARingCC::mult(), ARingElementGenerator< RingType >::nextElement(), ntrials, M2::ARingCC::power(), M2::ARingCC::power_mpz(), rawRandomInt(), and cc_doubles_struct::re.