Macaulay2 Engine: testRingNegateCCC
testRingNegateCCC()
void testRingNegateCCC (const M2::ARingCC & C, int ntrials)
Definition at line 46 of file ARingCCTest.cpp.
 {
   ARingElementGenerator<M2::ARingCC> gen(C);
   M2::ARingCC::ElementType a, b, c;
   C.init(a);
   C.init(b);
   C.init(c);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (-a) + (a) == 0
       gen.nextElement(a);
       C.negate(b, a);
       C.add(c, a, b);
       EXPECT_TRUE(C.is_zero(c));
     }
   C.clear(c);
   C.clear(b);
   C.clear(a);
 }
References M2::ARingCC::add(), M2::ARingCC::clear(), M2::ARingCC::init(), M2::ARingCC::is_zero(), M2::ARingCC::negate(), ARingElementGenerator< RingType >::nextElement(), and ntrials.
Referenced by TEST().