Macaulay2 Engine: TEST
TEST() [2/7]
TEST (ARingCC , axioms)
Definition at line 158 of file ARingCCTest.cpp.
 {
   M2::ARingCC C;
   auto nbits = C.get_precision();
   ARingElementGenerator<M2::ARingCC> gen(C);
   M2::ARingCC::ElementType a, b, c, d, e;
   C.init(a);
   C.init(b);
   C.init(c);
   C.init(d);
   C.init(e);
   for (int i = 0; i < ntrials; i++)
     {
       gen.nextElement(a);
       gen.nextElement(b);
       gen.nextElement(c);
       // Test commutativity
       // test: a*b = b*a
       // test: a+b == b+a
       C.add(d, a, b);
       C.add(e, b, a);
       EXPECT_TRUE(almostEqual(C, nbits - 2, d, e));
       C.mult(d, a, b);
       C.mult(e, b, a);
       EXPECT_TRUE(almostEqual(C, nbits - 2, d, e));
       // Test associativity
       // test: a+(b+c) == (a+b)+c
       // test: a*(b*c) == (a*b)*c
       C.add(e, b, c);
       C.add(d, a, e);  // a+(b+c)
       C.add(e, a, b);
       C.add(e, e, c);  // (a+b)+c
       EXPECT_TRUE(almostEqual(C, nbits - 6, d, e));
       C.mult(e, b, c);
       C.mult(d, a, e);  // a*(b*c)
       C.mult(e, a, b);
       C.mult(e, e, c);  // (a*b)*c
       EXPECT_TRUE(almostEqual(C, nbits - 6, d, e));
       // Test distributivity
       // test: a*(b+c) == a*b + a*c
       C.add(e, b, c);
       C.mult(d, a, e);  // a*(b+c)
       C.mult(b, a, b);
       C.mult(c, a, c);
       C.add(e, b, c);  // a*b + a*c
       EXPECT_TRUE(almostEqual(C, nbits - 6, d, e));
     }
   C.clear(e);
   C.clear(d);
   C.clear(c);
   C.clear(b);
   C.clear(a);
 }
References M2::ARingCC::add(), almostEqual(), M2::ARingCC::clear(), M2::ARingCC::get_precision(), M2::ARingCC::init(), M2::ARingCC::mult(), ARingElementGenerator< RingType >::nextElement(), and ntrials.