Macaulay2 Engine: IM2_FreeModule_make_degs
IM2_FreeModule_make_degs()
const FreeModule* IM2_FreeModule_make_degs (const Ring * R, M2_arrayint degs)
Definition at line 42 of file freemodule.cpp.
 {
   try
     {
       auto D = R->degree_monoid();
       unsigned int eachdeg = D->n_vars();
       if (eachdeg == 0)
         {
           ERROR("rawFreeModule: degree rank 0, but sequence of degrees given");
           return NULL;
         }
       unsigned int rank = degs->len / eachdeg;
       if (rank * eachdeg != degs->len)
         {
           ERROR("inappropriate number of degrees");
           return 0;
         }
       monomial deg = D->make_one();
       FreeModule *F = R->make_FreeModule();
       for (unsigned int i = 0; i < rank; i++)
         {
           D->from_expvector(degs->array + i * eachdeg, deg);
           F->append(deg);
         }
       return F;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References FreeModule::append(), Ring::degree_monoid(), ERROR(), Ring::make_FreeModule(), Monoid::n_vars(), and ffpackInterface::rank().