Macaulay2 Engine: IM2_FreeModule_get_degrees
IM2_FreeModule_get_degrees()
M2_arrayint IM2_FreeModule_get_degrees (const FreeModule * F)
Definition at line 87 of file freemodule.cpp.
 {
   auto D = F->get_ring()->degree_monoid();
   auto n = D->n_vars();
   auto r = F->rank();
   M2_arrayint result = M2_makearrayint(r * n);
   for (int i = 0; i < r; i++)
     D->to_expvector(F->degree(i), result->array + i * n);
   return result;
 }
References FreeModule::degree(), Ring::degree_monoid(), FreeModule::get_ring(), M2_makearrayint(), Monoid::n_vars(), and FreeModule::rank().