Macaulay2 Engine: gb_node::output_free_module
output_free_module()
virtual const FreeModule* gb_node::output_free_module () const pure virtual
Implemented in gb2_comp, and gb_emitter.
Referenced by gbres_comp::betti_minimal(), gbres_comp::free_module(), gbres_comp::reduce(), and gb2_comp::setup().