Macaulay2 Engine: stash::new_elem
new_elem()
void * stash::new_elem () inline
Definition at line 91 of file mem.hpp.
 {
   return newarray_clear(char, element_size);
   acquireSpinLock(&list_spinlock);
   n_allocs++;
   n_inuse++;
   if (n_inuse > highwater) highwater = n_inuse;
   if (free_list == nullptr)
     {
       if (n_per_slab == 0)
         {
           void *result = newarray_clear(char, element_size);
           // allocated_amount += element_size;
           releaseSpinLock(&list_spinlock);
           return result;
         }
       chop_slab();
     }
   assert(free_list != NULL);  // chop_slab should not let this happen.
   void *result = free_list;
   free_list = *(reinterpret_cast<void **>(free_list));
   releaseSpinLock(&list_spinlock);
   return result;
 }
References chop_slab(), element_size, free_list, highwater, list_spinlock, n_allocs, n_inuse, n_per_slab, and newarray_clear.
Referenced by gbA::exponents_make(), gbA::gbelem_copy(), gbA::gbelem_make(), gbA::gbelem_ring_make(), MonomialTable::insert(), MonomialTable::make_list_head(), F4SPairSet::make_spair(), doubling_stash::new_elem(), MonomialIdeal::new_internal_mi_node(), MonomialIdeal::new_leaf_mi_node(), GBRing::new_raw_term(), res_comp::new_res_pair(), res2_poly::new_term(), res_poly::new_term(), and gbA::spair_node().