Macaulay2 Engine: stash::delete_elem
delete_elem()
void stash::delete_elem (void * p) inline
Definition at line 117 of file mem.hpp.
 {
   if (p == nullptr) return;
   freemem(p);
   return;
   //  if (trace_bad_deletes)
   //    {
   //      for (void *q = free_list; q != NULL; q = *(reinterpret_cast<void
   //      **>(q)))
   //    if (q == p)
   //      assert(0);
   //    }
   n_inuse--;
   n_frees++;
   if (n_per_slab == 0)
     {
       //      deleted_amount += element_size;
       char *q = reinterpret_cast<char *>(p);
       freemem(q);
       return;
     }
   acquireSpinLock(&list_spinlock);
   memset(p, 0, element_size);  // we clear this element because it's free, and
                                // it may contain words that look like pointers
                                // to gc
   *(reinterpret_cast<void **>(p)) = free_list;
   free_list = p;
   releaseSpinLock(&list_spinlock);
 }
References element_size, free_list, freemem(), list_spinlock, n_frees, n_inuse, n_per_slab, and p.
Referenced by res2_poly::add_to(), res_poly::add_to(), doubling_stash::delete_elem(), MonomialIdeal::delete_mi_node(), F4SPairSet::delete_spair(), GBRing::gbvector_remove_term(), res2_poly::remove(), res_poly::remove(), gbA::remove_gb(), binomial_ring::remove_monomial(), res_comp::remove_res_pair(), gbA::spair_delete(), and MonomialTable::~MonomialTable().