Macaulay2 Engine: stash::stats
stats()
void stash::stats (buffer & o) static
Definition at line 93 of file mem.cpp.
 {
   //  o << "total space allocated from system = " << engine_allocated << endl;
   //  o << "number of global delete's  = " << engine_dealloc << endl;
   int n = (slab::n_slabs * slab_size) / 1024 +
           (allocated_amount - deleted_amount) / 1024;
   o << "size of each slab = " << sizeof(slab) << newline;
   o << "total engine stash space allocated = " << n << "k" << newline;
   if (n > 0)
     {
       const int N = 200;
       char s[N];
       snprintf(s, N,
               "%16s %10s %10s %10s %10s %10s %10s %10s%s",
               "stash",
               "k total",
               "k in use",
               "size",
               "nalloc",
               "inuse",
               "highwater",
               "freed",
               newline);
       o << s;
     }
 }
References allocated_amount, deleted_amount, slab::n_slabs, newline, and slab_size.
Referenced by dstash(), engineMemory(), GBRing::memstats(), and F4Computation::show().