Macaulay2 Engine: QRingInfo_ZZ::reduce_lead_term_ZZ
reduce_lead_term_ZZ()
bool QRingInfo_ZZ::reduce_lead_term_ZZ (Nterm *& f, const Nterm * g) const private
Definition at line 350 of file qring.cpp.
 {
   const Monoid *M = R->getMonoid();
   const ring_elem a = f->coeff;
   const ring_elem b = g->coeff;
   ring_elem u, v, rem;
   rem = globalZZ->remainderAndQuotient(a, b, v);
   if (globalZZ->is_zero(v)) return false;
   v = globalZZ->negate(v);
   bool result = globalZZ->is_zero(rem);
   monomial MONOM1 = ALLOCATE_MONOMIAL(monom_size);
   M->divide(f->monom, g->monom, MONOM1);
   if (R->is_skew_commutative())
     {
       exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
       exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
       // We need to determine the sign
       M->to_expvector(g->monom, EXP2);
       M->to_expvector(MONOM1, EXP1);
       if (R->getSkewInfo().mult_sign(EXP1, EXP2) < 0)
         R->getCoefficients()->negate_to(v);
     }
   // now mult g to cancel
   ring_elem g1 = const_cast<Nterm *>(g);
   g1 = R->mult_by_term(g1, v, MONOM1);
   ring_elem f1 = f;
   R->internal_add_to(f1, g1);
   f = f1;
   return result;
 }
References ALLOCATE_EXPONENTS, ALLOCATE_MONOMIAL, Monoid::divide(), globalZZ, RingZZ::is_zero(), RingZZ::negate(), mpfr::rem(), RingZZ::remainderAndQuotient(), and Monoid::to_expvector().