Macaulay2 Engine: QRingInfo_ZZ::QRingInfo_ZZ
QRingInfo_ZZ()
QRingInfo_ZZ::QRingInfo_ZZ (const PolyRing * ambientR, const gc_vector< Nterm * > & quotients)
Definition at line 316 of file qring.cpp.
     : QRingInfo(ambientR)
 {
   ringtableZZ = MonomialTableZZ::make(R->n_vars());
   exponents_t exp = newarray_atomic(int, R->n_vars());
   for (int i = 0; i < quotients.size(); i++)
     {
       // Make a varpower element.  See if it is in Rideal.
       // If not, place it into quotient_elements.
       Nterm *f = quotients[i];
       R->getMonoid()->to_expvector(f->monom, exp);
       if (!ringtableZZ->is_strong_member(f->coeff.get_mpz(), exp, 1))
         {
           // The element is part of a minimal GB
           // Also, this grabs exp.
           int index = n_quotients();
           ringtableZZ->insert(f->coeff.get_mpz(), exp, 1, index);
           gbvector *g = R->translate_gbvector_from_ringelem(f);
           appendQuotientElement(f, g);
           exp = newarray_atomic(int, R->n_vars());
           if (f->next == nullptr && R->getMonoid()->is_one(f->monom))
             {
               is_ZZ_quotient_ = true;
               ZZ_quotient_value_ = f->coeff;
             }
         }
     }
   freemem(exp);
 }
References QRingInfo::appendQuotientElement(), Nterm::coeff, mpfr::exp(), freemem(), ring_elem::get_mpz(), PolynomialRing::getMonoid(), MonomialTableZZ::insert(), Monoid::is_one(), MonomialTableZZ::is_strong_member(), is_ZZ_quotient_, MonomialTableZZ::make(), Nterm::monom, QRingInfo::n_quotients(), PolynomialRing::n_vars(), newarray_atomic, Nterm::next, QRingInfo::R, ringtableZZ, Monoid::to_expvector(), PolyRing::translate_gbvector_from_ringelem(), and ZZ_quotient_value_.