Macaulay2 Engine: FreeAlgebraHeap::add
add()
void FreeAlgebraHeap::add (const Poly & f)
Definition at line 40 of file FreeAlgebra.cpp.
 {
   auto len = p.numTerms();
   int i = 0;
   while (len >= heap_size[i]) i++;
   Poly tmp1;
   F.init(tmp1);
   F.add(tmp1, heap[i], p);
   std::swap(heap[i], tmp1);
   F.setZero(tmp1);
   len = heap[i].numTerms();
   while (len >= heap_size[i])
     {
       i++;
       F.add(tmp1, heap[i], heap[i-1]);
       std::swap(heap[i], tmp1);
       F.setZero(tmp1);
       F.setZero(heap[i-1]);
       len = heap[i].numTerms();
     }
   if (i > top_of_heap) top_of_heap = i;
 }
References FreeAlgebra::add(), F, heap, heap_size, FreeAlgebra::init(), p, FreeAlgebra::setZero(), swap, and top_of_heap.
Referenced by SumCollectorFreeAlgebraHeap::add().