Macaulay2 Engine: FreeAlgebraHeap::value
value()
void FreeAlgebraHeap::value (Poly & result)
Definition at line 66 of file FreeAlgebra.cpp.
 {
   Poly tmp1;
   F.init(tmp1);
   for (int i = 0; i <= top_of_heap; i++)
     {
       if (heap[i].numTerms() == 0) continue;
       F.add(tmp1, result, heap[i]);
       std::swap(result, tmp1);
       F.setZero(tmp1);
       F.setZero(heap[i]);
     }
   top_of_heap = -1;
   F.clear(tmp1);
 }
References FreeAlgebra::add(), FreeAlgebra::clear(), F, heap, FreeAlgebra::init(), FreeAlgebra::setZero(), swap, and top_of_heap.
Referenced by SumCollectorFreeAlgebraHeap::getValue().