Macaulay2 Engine: MonomialTableZZ::find_term_divisors
find_term_divisors()
int MonomialTableZZ::find_term_divisors (int max, mpz_srcptr coeff, exponents_t exp, int comp, gc_vector< mon_term * > * result = nullptr) const
Definition at line 145 of file montableZZ.cpp.
 {
   assert(comp >= 1);
   if (comp >= static_cast<int>(_head.size())) return 0;
   mon_term *head = _head[comp];
   mon_term *t;
   int nmatches = 0;
   unsigned long expmask = ~(monomial_mask(_nvars, exp));
   for (t = head->_next; t != head; t = t->_next)
     if ((expmask & t->_mask) == 0)
       {
         bool is_div = 1;
         for (int i = 0; i < _nvars; i++)
           if (exp[i] < t->_lead[i])
             {
               is_div = 0;
               break;
             }
         if (is_div && mpz_divisible_p(coeff, t->_coeff))
           {
             nmatches++;
             if (result != nullptr) result->push_back(t);
             if (max >= 0 && nmatches >= max) break;
           }
       }
   if (M2_gbTrace == 15 && nmatches >= 2)
     {
       buffer o;
       o << "find_term_divisors called on ";
       show_mon_term(o, coeff, exp, comp);
       o << " #matches=" << nmatches << newline;
       if (result != nullptr)
         for (int i = 0; i < result->size(); i++) show_mon_term(o, (*result)[i]);
       o << newline;
     }
   return nmatches;
 }
References MonomialTableZZ::mon_term::_coeff, MonomialTableZZ::mon_term::_lead, MonomialTableZZ::mon_term::_mask, MonomialTableZZ::mon_term::_next, mpfr::exp(), M2_gbTrace, max, monomial_mask(), and newline.
Referenced by ReducedGB_ZZ::find_divisor(), gbA::find_good_term_divisor_ZZ(), and is_strong_member().