Macaulay2 Engine: MonomialTableZZ::find_exact_monomial
find_exact_monomial()
MonomialTableZZ::mon_term * MonomialTableZZ::find_exact_monomial (exponents_t exp, int comp, int first_val) const
Definition at line 351 of file montableZZ.cpp.
 {
   if (comp >= static_cast<int>(_head.size())) return nullptr;
   mon_term *head = _head[comp];
   mon_term *t;
   int i;
   mon_term *result = nullptr;
   int neqs = 0;
   unsigned long expmask = monomial_mask(_nvars, exp);
   for (t = head->_next; t != head; t = t->_next)
     {
       if (t->_val < first_val) continue;
       if (expmask == t->_mask)
         {
           bool is_eq = 1;
           for (i = 0; i < _nvars; i++)
             if (exp[i] != t->_lead[i])
               {
                 is_eq = 0;
                 break;
               }
           if (is_eq)
             {
               if (result == nullptr) result = t;
               neqs++;
             }
         }
     }
   if (neqs > 1)
     {
       printf("number of exact matches: %d\n", neqs);
     }
   return result;
 }
References _head, MonomialTableZZ::mon_term::_lead, MonomialTableZZ::mon_term::_mask, MonomialTableZZ::mon_term::_next, _nvars, MonomialTableZZ::mon_term::_val, mpfr::exp(), and monomial_mask().
Referenced by gbA::reduce_ZZ().