Macaulay2 Engine: MonomialTableZZ::find_monomial_divisors
find_monomial_divisors()
int MonomialTableZZ::find_monomial_divisors (int max, exponents_t exp, int comp, gc_vector< mon_term * > * result = 0) const
Definition at line 281 of file montableZZ.cpp.
 {
   assert(comp >= 1);
   if (comp >= static_cast<int>(_head.size())) return 0;
   mon_term *head = _head[comp];
   mon_term *t;
   int nmatches = 0;
   unsigned long expmask = ~(monomial_mask(_nvars, exp));
   for (t = head->_next; t != head; t = t->_next)
     if ((expmask & t->_mask) == 0)
       {
         bool is_div = 1;
         for (int i = 0; i < _nvars; i++)
           if (exp[i] < t->_lead[i])
             {
               is_div = 0;
               break;
             }
         if (is_div)
           {
             nmatches++;
             if (result != 0) result->push_back(t);
             if (max >= 0 && nmatches >= max) break;
           }
       }
   if (M2_gbTrace == 15 && nmatches >= 2)
     {
       buffer o;
       o << "find_monomial_divisors called on ";
       show_mon_term(o, nullptr, exp, comp);
       o << " #matches=" << nmatches << newline;
       if (result != 0)
         for (int i = 0; i < result->size(); i++) show_mon_term(o, (*result)[i]);
       o << newline;
     }
   return nmatches;
 }
References _head, MonomialTableZZ::mon_term::_lead, MonomialTableZZ::mon_term::_mask, MonomialTableZZ::mon_term::_next, _nvars, mpfr::exp(), M2_gbTrace, max, monomial_mask(), newline, and show_mon_term().
Referenced by gbA::find_good_monomial_divisor_ZZ().