Macaulay2 Engine: MonomialTableZZ::show_mon_term
show_mon_term() [3/3]
void MonomialTableZZ::show_mon_term (FILE * fil, mon_term * t) const
Definition at line 639 of file montableZZ.cpp.
{
  buffer o;
  show_mon_term(o, t);
  fprintf(fil, "%s", o.str());
}
References show_mon_term(), and buffer::str().
Referenced by find_monomial_divisors(), show(), show_mon_term(), and show_mon_term().