Macaulay2 Engine: MonomialTableZZ::insert
insert()
void MonomialTableZZ::insert (mpz_srcptr coeff, exponents_t exp, int comp, int id)
Definition at line 400 of file montableZZ.cpp.
 {
   /* Insert 'exp' into the monomial table.  These are kept sorted in ascending
      order
      in some order (lex order?).  No element is ever removed.
   */
   if (comp >= INTSIZE(_head))
     {
       for (int i = INTSIZE(_head); i <= comp; i++)
         _head.push_back(make_list_head());
     }
   mon_term *head = _head[comp];
   mon_term *t;
   /* Make a new mon_term including exp */
   mon_term *newterm = new mon_term;
   newterm->_lead = exp;
   newterm->_mask = monomial_mask(_nvars, exp);
   newterm->_val = id;
   newterm->_coeff = coeff;
   _count++;
   /* Find where to put it */
   for (t = head; t->_next != head; t = t->_next)
     {
       if (exponents_greater(_nvars, newterm->_lead, t->_next->_lead))
         {
           /* Time to insert newterm, right between t, t->next */
           break;
         }
     }
   /* The actual insertion */
   newterm->_next = t->_next;
   newterm->_prev = t;
   t->_next->_prev = newterm;
   t->_next = newterm;
 }
References MonomialTableZZ::mon_term::_coeff, _count, _head, MonomialTableZZ::mon_term::_lead, MonomialTableZZ::mon_term::_mask, MonomialTableZZ::mon_term::_next, _nvars, MonomialTableZZ::mon_term::_prev, MonomialTableZZ::mon_term::_val, mpfr::exp(), exponents_greater(), INTSIZE, make_list_head(), and monomial_mask().
Referenced by ReducedGB_ZZ::find_divisor(), gbA::insert_gb(), and QRingInfo_ZZ::QRingInfo_ZZ().