Macaulay2 Engine: HermiteComputation::HermiteComputation
HermiteComputation()
HermiteComputation::HermiteComputation (const Matrix * m, int collect_syz, int n_syz)
Definition at line 59 of file hermite.cpp.
     : row(m->n_rows() - 1),
       gens(m),
       GB_list(nullptr),
       n_gb(0),
       collect_syz(collsyz)
 {
   int i;
   for (i = 0; i < m->n_rows(); i++) initial.push_back(nullptr);
   if (nsyz < 0 || nsyz > m->n_cols()) nsyz = m->n_cols();
   n_comps_per_syz = nsyz;
   Fsyz = m->cols()->sub_space(nsyz);
   for (i = 0; i < m->n_cols(); i++)
     {
       hm_elem *p = new_gen(i);
       insert(p);
     }
 }
References Matrix::cols(), Fsyz, initial, insert(), Matrix::n_cols(), n_comps_per_syz, Matrix::n_rows(), new_gen(), p, and FreeModule::sub_space().