Macaulay2 Engine: HermiteComputation::get_gb
get_gb()
const Matrix * HermiteComputation::get_gb () virtual
Implements GBComputation.
Definition at line 316 of file hermite.cpp.
{
  MatrixConstructor mat(gens->rows(), 0);
  for (hm_elem *p = GB_list; p != nullptr; p = p->next)
    mat.append(globalZZ->copy_vec(p->f));
  return mat.to_matrix();
}
References MatrixConstructor::append(), Ring::copy_vec(), GB_list, gens, globalZZ, p, Matrix::rows(), and MatrixConstructor::to_matrix().
Referenced by get_mingens().