Macaulay2 Engine: HermiteComputation::insert
insert()
void HermiteComputation::insert (hm_elem * p) private
Definition at line 42 of file hermite.cpp.
 {
   if (p->f == NULL)
     {
       if (p->fsyz != NULL && collect_syz) syz_list.push_back(p->fsyz);
       mpz_clear(p->lead);
       delete p;
       nfree_hm_elem++;
     }
   else
     {
       int i = p->f->comp;
       p->next = initial[i];
       initial[i] = p;
     }
 }
References collect_syz, initial, nfree_hm_elem, p, and syz_list.
Referenced by HermiteComputation(), merge(), and reduce().