Macaulay2 Engine: HermiteComputation::matrix_lift
matrix_lift()
M2_bool HermiteComputation::matrix_lift (const Matrix * m, const Matrix ** result_remainder, const Matrix ** result_quotient) virtual
Implements GBComputation.
Definition at line 483 of file hermite.cpp.
 {
   if (m->get_ring() != globalZZ)
     {
       ERROR("expected matrix over ZZ");
       *result_remainder = nullptr;
       *result_quotient = nullptr;
       return false;
     }
   if (m->n_rows() != gens->rows()->rank())
     {
       ERROR("expected matrices to have same number of rows");
       *result_remainder = nullptr;
       *result_quotient = nullptr;
       return false;
     }
   MatrixConstructor mat_remainder(m->rows(), m->cols(), m->degree_shift());
   MatrixConstructor mat_quotient(Fsyz, m->cols(), nullptr);
   bool all_zeroes = true;
   for (int i = 0; i < m->n_cols(); i++)
     {
       vec f = globalZZ->copy_vec(m->elem(i));
       vec fsyz = nullptr;
       gb_reduce(f, fsyz);
       if (f != nullptr) all_zeroes = false;
       globalZZ->negate_vec_to(fsyz);
       mat_remainder.set_column(i, f);
       mat_quotient.set_column(i, fsyz);
     }
   *result_remainder = mat_remainder.to_matrix();
   *result_quotient = mat_quotient.to_matrix();
   return all_zeroes;
 }
References Matrix::cols(), Ring::copy_vec(), Matrix::degree_shift(), Matrix::elem(), ERROR(), Fsyz, gb_reduce(), gens, Matrix::get_ring(), globalZZ, Matrix::n_cols(), Matrix::n_rows(), Ring::negate_vec_to(), FreeModule::rank(), Matrix::rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().