Macaulay2 Engine: HermiteComputation::get_syzygies
get_syzygies()
const Matrix * HermiteComputation::get_syzygies () virtual
Implements GBComputation.
Definition at line 338 of file hermite.cpp.
 {
   MatrixConstructor mat(Fsyz, 0);
   for (int i = 0; i < syz_list.size(); i++)
     mat.append(globalZZ->copy_vec(syz_list[i]));
   return mat.to_matrix();
 }
References MatrixConstructor::append(), Ring::copy_vec(), Fsyz, globalZZ, syz_list, and MatrixConstructor::to_matrix().