Macaulay2 Engine: HermiteComputation::contains
contains()
int HermiteComputation::contains (const Matrix * m) virtual
Implements GBComputation.
Definition at line 522 of file hermite.cpp.
 {
   if (m->get_ring() != globalZZ)
     {
       ERROR("expected matrix over ZZ");
       return -1;
     }
   // Reduce each column of m one by one.
   for (int i = 0; i < m->n_cols(); i++)
     {
       vec f = globalZZ->copy_vec(m->elem(i));
       gb_reduce(f);
       if (f != NULL)
         {
           globalZZ->remove_vec(f);
           return i;
         }
     }
   return -1;
 }
References Ring::copy_vec(), Matrix::elem(), ERROR(), gb_reduce(), Matrix::get_ring(), globalZZ, Matrix::n_cols(), and Ring::remove_vec().