Macaulay2 Engine: HermiteComputation::reduce
reduce()
void HermiteComputation::reduce (hm_elem *& p, hm_elem * q) private
Definition at line 209 of file hermite.cpp.
 {
   // compute (u,v) s.t. u lead(p) + v lead(q) = gcd
   // set p <- u*p + v*q;
   // set q <- lead(q)/gcd * p - lead(p)/gcd * q
   // DOn't forget to also reset the 'lead' fields!
   ring_elem u, v;
   ring_elem g = globalZZ->gcd_extended(p->f->coeff, q->f->coeff, u, v);
   ring_elem a = globalZZ->divide(q->f->coeff, g);  // exact
   ring_elem b = globalZZ->divide(p->f->coeff, g);  // exact
   globalZZ->negate_to(b);
   vec p1 = globalZZ->mult_vec(u, p->f);
   vec p2 = globalZZ->mult_vec(v, q->f);
   globalZZ->add_vec_to(p1, p2);
   vec syz1 = globalZZ->mult_vec(u, p->fsyz);
   vec syz2 = globalZZ->mult_vec(v, q->fsyz);
   globalZZ->add_vec_to(syz1, syz2);
   vec q1 = globalZZ->mult_vec(a, p->f);
   vec q2 = globalZZ->mult_vec(b, q->f);
   globalZZ->add_vec_to(q1, q2);
   vec qsyz1 = globalZZ->mult_vec(a, p->fsyz);
   vec qsyz2 = globalZZ->mult_vec(b, q->fsyz);
   globalZZ->add_vec_to(qsyz1, qsyz2);
   globalZZ->remove_vec(p->f);
   globalZZ->remove_vec(q->f);
   globalZZ->remove_vec(p->fsyz);
   globalZZ->remove_vec(q->fsyz);
   globalZZ->remove(a);
   globalZZ->remove(b);
   globalZZ->remove(g);
   globalZZ->remove(u);
   globalZZ->remove(v);
   // Now that the arithmetic has been done, put back into 'p', 'q':
   p->f = p1;
   p->fsyz = syz1;
   mpz_set(p->lead, p->f->coeff.get_mpz());
   q->f = q1;
   q->fsyz = qsyz1;
   if (q->f != nullptr) mpz_abs(q->lead, q->f->coeff.get_mpz());
   insert(q);
 }
References Ring::add_vec_to(), RingZZ::divide(), hm_elem::f, hm_elem::fsyz, RingZZ::gcd_extended(), globalZZ, insert(), hm_elem::lead, Ring::mult_vec(), Ring::negate_to(), p, p1, RingZZ::remove(), and Ring::remove_vec().
Referenced by start_computation().