Macaulay2 Engine: HermiteComputation::start_computation
start_computation()
void HermiteComputation::start_computation () virtual
Implements GBComputation.
Definition at line 259 of file hermite.cpp.
 {
   // ngb = stop[0]
   // nsyz = stop[1]
   // npairs = stop[2]
   if (status() == COMP_DONE) return;
   for (; row >= 0; row--)
     {
       hm_elem *p = initial[row];
       if (p == NULL) continue;
       initial[row] = NULL;
       sort(p);  // This can remove elements, inserting them back
       while (p != NULL && p->next != NULL)
         {
           hm_elem *pnext = p->next->next;
           reduce(p, p->next);  // replaces p1, and re-inserts p2.
           p->next = pnext;
         }
       // At this point, 'p' is the only remaining element with this lead term
       // So insert it into GB_list
       p->next = GB_list;
       GB_list = p;
       n_gb++;
     }
   // At this point, we are done, so reset initial[...] (it is all NULL right
   // now)
   // Now let's auto reduce the result...
   // We will reduce the GB elems
   // one by one, placing them back into the 'initial' table.
   // We use the following: the lead components of elements of GB_list are in
   // increasing order
   for (hm_elem *p = GB_list; p != 0; p = p->next)
     {
       if (!globalZZ->is_positive(p->f->coeff))
         {
           vec f = globalZZ->negate_vec(p->f);
           vec fsyz = globalZZ->negate_vec(p->fsyz);
           globalZZ->remove_vec(p->f);
           globalZZ->remove_vec(p->fsyz);
           p->f = f;
           p->fsyz = fsyz;
         }
       gb_reduce(p->f, p->fsyz);
       initial[p->f->comp] = p;
     }
   //  for (hm_elem *p = GB_list; p != 0; p = p->next)
   //    initial[p->f->comp] = p;
   set_status(COMP_DONE);
 }
References COMP_DONE, GB_list, gb_reduce(), globalZZ, initial, RingZZ::is_positive(), n_gb, Ring::negate_vec(), p, reduce(), Ring::remove_vec(), row, Computation::set_status(), sort(), and Computation::status().