Macaulay2 Engine: HermiteComputation::matrix_remainder
matrix_remainder()
const Matrix * HermiteComputation::matrix_remainder (const Matrix * m) virtual
Implements GBComputation.
Definition at line 459 of file hermite.cpp.
 {
   if (m->get_ring() != globalZZ)
     {
       ERROR("expected matrix over ZZ");
       return nullptr;
     }
   if (m->n_rows() != gens->rows()->rank())
     {
       ERROR("expected matrices to have same number of rows");
       return nullptr;
     }
   MatrixConstructor mat_remainder(m->rows(), m->cols(), m->degree_shift());
   for (int i = 0; i < m->n_cols(); i++)
     {
       vec f = globalZZ->copy_vec(m->elem(i));
       gb_reduce(f);
       mat_remainder.set_column(i, f);
     }
   return mat_remainder.to_matrix();
 }
References Matrix::cols(), Ring::copy_vec(), Matrix::degree_shift(), Matrix::elem(), ERROR(), gb_reduce(), gens, Matrix::get_ring(), globalZZ, Matrix::n_cols(), Matrix::n_rows(), FreeModule::rank(), Matrix::rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().