Macaulay2 Engine: HermiteComputation::merge
merge()
hm_elem * HermiteComputation::merge (hm_elem * f, hm_elem * g) private
Definition at line 124 of file hermite.cpp.
 {
   if (g == NULL) return f;
   if (f == NULL) return g;
   hm_elem head;
   hm_elem *result = &head;
   hm_elem *h;
   while (1) switch (compare_elems(f, g))
       {
         case 1:
           result->next = g;
           result = result->next;
           g = g->next;
           if (g == NULL)
             {
               result->next = f;
               return head.next;
             }
           break;
         case 0:
           // In this case, we remove one, and re-insert:
           if (mpz_cmp(f->f->coeff.get_mpz(), g->f->coeff.get_mpz()) == 0)
             {
               vec f1 = globalZZ->copy_vec(f->f);
               vec f2 = globalZZ->copy_vec(f->fsyz);
               globalZZ->subtract_vec_to(g->f, f1);
               globalZZ->subtract_vec_to(g->fsyz, f2);
             }
           else
             {
               vec f1 = globalZZ->copy_vec(f->f);
               vec f2 = globalZZ->copy_vec(f->fsyz);
               globalZZ->add_vec_to(g->f, f1);
               globalZZ->add_vec_to(g->fsyz, f2);
             }
           h = g;
           // We need to reset the lead term
           if (g->f != NULL) mpz_abs(h->lead, g->f->coeff.get_mpz());
           g = g->next;
           insert(h);
           if (g == NULL)
             {
               result->next = f;
               return head.next;
             }
         // Now fall through to merge f into the result:
         case -1:
           result->next = f;
           result = result->next;
           f = f->next;
           if (f == NULL)
             {
               result->next = g;
               return head.next;
             }
           break;
       }
 }
References Ring::add_vec_to(), compare_elems(), Ring::copy_vec(), hm_elem::f, hm_elem::fsyz, globalZZ, insert(), hm_elem::lead, hm_elem::next, and Ring::subtract_vec_to().
Referenced by sort().