Macaulay2 Engine: HermiteComputation::gb_reduce
gb_reduce() [2/2]
void HermiteComputation::gb_reduce (vec & f, vec & fsyz) const private
Definition at line 421 of file hermite.cpp.
 {
   // Reduce f so that each of its terms are < corresponding initial term
   // (in absolute value).
   vecterm head;
   vecterm *result = &head;
   head.next = nullptr;
   while (f != nullptr)
     {
       int x = f->comp;
       hm_elem *h = initial[x];
       if (h != nullptr)
         {
           ring_elem v;
           ring_elem rem =
               globalZZ->remainderAndQuotient(f->coeff, h->f->coeff, v);
           bool do_reduce = !globalZZ->is_zero(v);
           if (do_reduce)
             {
               v = globalZZ->negate(v);
               vec g = globalZZ->mult_vec(v, h->f);
               globalZZ->add_vec_to(f, g);
               vec gsyz = globalZZ->mult_vec(v, h->fsyz);
               globalZZ->add_vec_to(fsyz, gsyz);
             }
           if (globalZZ->is_zero(rem)) continue;
         }
       // The lead term stays
       result->next = f;
       f = f->next;
       result = result->next;
       result->next = nullptr;
       continue;
     }
   f = head.next;
 }
References Ring::add_vec_to(), hm_elem::f, hm_elem::fsyz, globalZZ, initial, RingZZ::is_zero(), Ring::mult_vec(), RingZZ::negate(), vec::next, mpfr::rem(), RingZZ::remainderAndQuotient(), and x.