Macaulay2 Engine: HermiteComputation::get_initial
get_initial()
const Matrix * HermiteComputation::get_initial (int nparts) virtual
Implements GBComputation.
Definition at line 346 of file hermite.cpp.
 {
   MatrixConstructor mat(gens->rows(), 0);
   for (hm_elem *p = GB_list; p != nullptr; p = p->next)
     {
       vec v = p->f;
       mat.append(globalZZ->make_vec(v->comp, v->coeff));
     }
   return mat.to_matrix();
 }
References MatrixConstructor::append(), GB_list, gens, globalZZ, Ring::make_vec(), p, Matrix::rows(), and MatrixConstructor::to_matrix().