Macaulay2 Engine: mutableMatrix_to_NTL_mat_ZZ
mutableMatrix_to_NTL_mat_ZZ()
NTL::mat_ZZ* mutableMatrix_to_NTL_mat_ZZ (const MutableMatrix * M)
Definition at line 6 of file ntl-interface.cpp.
 {
   // Creates the TRANSPOSE of M
   // We assume or check that the ring is ZZ
   //  const SparseMutableMatrix *A = M->cast_to_SparseMutableMatrix();
   const MutableMatrix *A = M;
   int ncols = static_cast<int>(A->n_rows());
   int nrows = static_cast<int>(A->n_cols());
   NTL::mat_ZZ *X = makeNTLMatrixZZ(nrows, ncols);
   for (int i = 0; i < ncols; i++)
     for (int j = 0; j < nrows; j++)
       {
         ring_elem a;
         if (A->get_entry(i, j, a))
           {
             mat_ZZ_set_entry(X, j, i, a.get_mpz());
           }
       }
   return X;
 }
References MutableMatrix::get_entry(), ring_elem::get_mpz(), makeNTLMatrixZZ(), mat_ZZ_set_entry(), MutableMatrix::n_cols(), and MutableMatrix::n_rows().
Referenced by ntl_LLL().