Macaulay2 Engine: set
set()
set (with_tbb ${WITH_TBB}) final new
Definition at line 6 of file CMakeLists.txt.
               {WITH_TBB}) # for mathicgb
 add_subdirectory(memtailor)
 add_subdirectory(mathic)
 add_subdirectory(mathicgb)
 target_compile_options(mathicgb PRIVATE
   -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-variable -Wno-sign-compare
   -Wno-deprecated-declarations
   )
 if(CMAKE_BUILD_TYPE MATCHES "Debug") # Debugging
   add_compile_definitions(MEMT_DEBUG MATHIC_DEBUG MATHICGB_DEBUG)
 endif()
 ###############################################################################
 ## M2-engine sources
 # TODO: determine the fate of these files
 set(UNDETERMINED
   dmat-ffpack.cpp
   franzi-brp-test.cpp
   overflow-test.cpp
   test.dd
   aring-wrap # both cpp and hpp
   points # both cpp and hpp
   )
 # c files
 # TODO: convert to cpp or simplify if not needed
 # MES TODO:   monordering.c removed this, is that correct?
 set(CFILES
   complex.c
   error.c
   exptable.c
   table.c
   )
 # h files
 set(HFILES
   complex.h
   error.h
   exptable.h
   table.h
   engine.h
   defgroups.h
   mpreal.h
   )
 # these files are include only.
 set(HPPONLYFILES
   MemoryBlock.hpp
   NCAlgebras/Range.hpp
   VectorArithmetic.hpp
   timing.hpp
   SLP-defs.hpp
   SLP-imp.hpp
   aring-glue.hpp
   aring-qq.hpp
   aring-translate.hpp
   dmat-gf-flint-big.hpp
   dmat-gf-flint.hpp
   dmat-lu-inplace.hpp
   dmat-lu-qq.hpp
   dmat-lu-zzp-ffpack.hpp
   dmat-lu-zzp-flint.hpp
   dmat-lu.hpp
   dmat-qq-flint.hpp
   dmat-qq-interface-flint.hpp
   dmat-zz-flint.hpp
   dmat-zzp-flint.hpp
   engine-includes.hpp
   exceptions.hpp
   geobucket.hpp
   geopoly.hpp
   geovec.hpp
   hash.hpp
   mat-arith.hpp
   mat-elem-ops.hpp
   mat-linalg.hpp
   mat-util.hpp
   mutablemat-defs.hpp
   mutablemat-imp.hpp
   mutablemat.hpp
   newdelete.hpp
   ExponentVector.hpp
   res-a0-pair.hpp
   schur-poly-heap.hpp
   smat.hpp
   util.hpp
   style.hpp
   f4/f4-types.hpp
   f4/memblock.hpp
   f4/ntuple-monomial.hpp
   f4/varpower-monomial.hpp
   gb-f4/MonomialTypes.hpp
   PolynomialStream.hpp
   schreyer-resolution/res-memblock.hpp
   schreyer-resolution/res-monomial-types.hpp
   schreyer-resolution/res-schreyer-order.hpp
   )
 # these files have .cpp file, but NOT .hpp file
 set(CPPONLYFILES
   engine.cpp # TODO: find a new home for the contents
   franzi-gb.cpp
   franzi-interface.cpp
   matrix-kbasis.cpp
   matrix-sort.cpp
   matrix-symm.cpp
   ntl-debugio.cpp
   ntl-internal.cpp
   res-a2-gb.cpp
   ring-vecs.cpp
   interface/aring.cpp
   interface/aring.h
   interface/computation.h # no .cpp yet
   interface/cra.cpp
   interface/cra.h
   interface/factory.cpp
   interface/factory.h
   interface/flint.cpp
   interface/flint.h
   interface/freemodule.cpp # TODO: .h
   interface/gmp-util.h # only has inline definitions
   interface/groebner.cpp
   interface/groebner.h
   interface/matrix.cpp
   interface/matrix.h
   interface/monoid.cpp
   interface/monoid.h
   interface/monomial-ideal.cpp
   interface/monomial-ideal.h
   interface/monomial-ordering.cpp
   interface/monomial-ordering.h
   interface/mutable-matrix.cpp
   interface/mutable-matrix.h
   interface/polyroots.cpp # the declarations are in factory.h
   interface/random.cpp
   interface/random.h
   interface/ring.cpp
   interface/ring.h
   interface/ringelement.cpp
   interface/ringelement.h
   interface/ringmap.cpp
   interface/ringmap.h
   )
 # these files all have .hpp and .cpp files
 # MES TODO: put these NCAlgebra files (and friends) into alpha order in list
 set(SRCLIST
   BasicPoly
   BasicPolyList
   BasicPolyListParser
   myalloc
   matrix-ncbasis
   M2FreeAlgebraQuotient
   M2FreeAlgebra
   NCAlgebras/Word
   NCAlgebras/NCReduction
   NCAlgebras/FreeAlgebraQuotient
   NCAlgebras/FreeAlgebra
   NCAlgebras/FreeMonoid
   NCAlgebras/WordTable
   NCAlgebras/SuffixTree
   NCAlgebras/NCGroebner
   NCAlgebras/NCF4
   NCAlgebras/OverlapTable
   NCResolutions/nc-res-computation
   Polynomial
   monomial-collection
   Eschreyer
   GF
   LLL
   NAG # TODO: move raw* functions to e/interface
   SLP
   ZZ
   ZZp
   aring-RRi
   aring-CC
   aring-CCC
   aring-RR
   aring-RRR
   aring-gf-flint-big
   aring-gf-flint
   aring-m2-gf
   aring-qq-flint
   aring-qq-gmp
   aring-tower
   aring-zz-flint
   aring-zz-gmp
   aring-zzp-ffpack
   aring-zzp-flint
   aring-zzp
   aring
   assprime
   betti
   buffer
   coeffrings
   comb
   comp-gb-declared
   comp-gb-proxy
   comp-gb
   comp-res
   comp
   cra
   debug
   det
   dmat
   dpoly
   eigen
   finalize
   fplll-interface
   frac
   fractionfreeLU
   franzi-brp
   freemod
   gauss
   gb-default
   gb-homog2
   gb-sugarless
   gb-toric
   gb-walk
   gbring
   gbweight
   hermite
   hilb
   imonorder
   int-bag
   interreduce
   interrupted
   lapack
   localring
   mat
   matrix-con
   matrix-stream
   matrix
   mem
   memory-status
   monideal-minprimes
   monideal
   monoid
   monomial-sets
   monomial
   monsort
   montable
   montableZZ
   mutablecomplex
   ntl-interface
   overflow
   pfaff
   poly
   polyquotient
   polyring
   qring
   reader
   reducedgb-ZZ
   reducedgb-field-local
   reducedgb-field
   reducedgb-marked
   reducedgb
   relem
   res-a0-poly
   res-a0
   res-a1-poly
   res-a1
   res-a2
   ring
   ringelem
   ringmap
   sagbi
   schorder
   schur
   schur2
   schurSn
   skew
   skewpoly
   solvable
   spair
   text-io
   tower # TODO: move rawTowerTranslatePoly to e/interface
   ExponentList
   weylalg
   # Faugère's F4 Algorithm
   gb-f4/Basis
   gb-f4/GBF4Computation
   gb-f4/GBF4Interface
   gb-f4/MacaulayMatrix
   gb-f4/MonomialHashTable
   gb-f4/MonomialLookupTable
   gb-f4/MonomialView
   gb-f4/PolynomialList
   gb-f4/SPairs
   f4/f4-computation
   f4/f4-m2-interface
   f4/f4-mem
   f4/f4-monlookup
   f4/f4-spairs
   f4/f4
   f4/hilb-fcn
   f4/monhashtable
   f4/moninfo
   # Schreyer resolution a la Linear algebra (F4 Faugere style)
   schreyer-resolution/res-f4-computation
   schreyer-resolution/res-f4-m2-interface
   schreyer-resolution/res-f4-monlookup
   schreyer-resolution/res-f4
   schreyer-resolution/res-moninfo-dense
   schreyer-resolution/res-moninfo-sparse
   schreyer-resolution/res-moninfo
   schreyer-resolution/res-monomial-sorter
   schreyer-resolution/res-poly-ring
   schreyer-resolution/res-schreyer-frame
   schreyer-resolution/res-dep-graph
   # Boolean Involutive Gröbner Bases
   bibasis/bibasis
   bibasis/allocator
   bibasis/launcher
   bibasis/monom
   bibasis/monomDL
   bibasis/monomDRL
   bibasis/monomLex
   bibasis/settings-manager
   )
 list(TRANSFORM SRCLIST APPEND .cpp OUTPUT_VARIABLE CPPFILES)
 list(TRANSFORM SRCLIST APPEND .hpp OUTPUT_VARIABLE HPPFILES)
 set(SOURCES ${CPPONLYFILES} ${CPPFILES} ${CFILES})
Referenced by BIBasis::TSet< MonomType >::CollectNonMultiProlongations(), BIBasis::BooleanInvolutiveBasis< MonomType >::Construct(), BIBasis::BooleanInvolutiveBasis< MonomType >::FindDivisor(), BIBasis::BooleanInvolutiveBasis< MonomType >::Reduce(), and gbA::remove_spair_list().