Macaulay2 Engine: FreeModule::direct_sum
direct_sum()
FreeModule * FreeModule::direct_sum (const FreeModule * G) const
Definition at line 237 of file freemod.cpp.
 {
   int i;
   if (get_ring() != G->get_ring())
     {
       ERROR("expected free modules over the same ring");
       return 0;
     }
   FreeModule *result = new_free();
   for (i = 0; i < rank(); i++) result->append(degree(i));
   for (i = 0; i < G->rank(); i++) result->append(G->degree(i));
   //  if (schreyer != NULL && G->schreyer != NULL)
   //    result->schreyer = schreyer->direct_sum(G->schreyer);
   return result;
 }
References append(), ERROR(), and ffpackInterface::rank().
Referenced by Matrix::concat(), Matrix::direct_sum(), and IM2_FreeModule_sum().