Macaulay2 Engine: FreeModule::change_degree
change_degree()
void FreeModule::change_degree (int i, const int * deg)
Definition at line 142 of file freemod.cpp.
 {
   // WARNING: this modifies the degree, and should only be used during
   // the construction of a free module (or matrix).
   assert(i >= 0);
   assert(i < rank());
   degree_monoid()->copy(deg, components[i]);
 }
References components, Monoid::copy(), degree_monoid(), and rank().
Referenced by MatrixConstructor::compute_column_degree(), and MatrixConstructor::set_column_degree().