Macaulay2 Engine: FreeModule::exterior
exterior()
FreeModule * FreeModule::exterior (int p) const
Definition at line 288 of file freemod.cpp.
 {
   FreeModule *result;
   if (pp == 0)
     return get_ring()->make_FreeModule(1);
   else
     result = new_free();
   int rk = rank();
   if (pp > rk || pp < 0) return result;
   size_t p = static_cast<size_t>(pp);
   Subset a(p, 0);
   for (size_t i = 0; i < p; i++) a[i] = i;
   monomial deg = degree_monoid()->make_one();
   do
     {
       degree_monoid()->one(deg);
       for (size_t r = 0; r < p; r++)
         degree_monoid()->mult(deg, degree(static_cast<int>(a[r])), deg);
       result->append(deg);
     }
   while (Subsets::increment(rk, a));
   degree_monoid()->remove(deg);
   if (schreyer != NULL) result->schreyer = schreyer->exterior(pp);
   return result;
 }
References append(), SchreyerOrder::exterior(), Subsets::increment(), p, ffpackInterface::rank(), and schreyer.
Referenced by DetComputation::DetComputation(), IM2_FreeModule_exterior(), Matrix::koszul(), and Matrix::wedge_product().