Macaulay2 Engine: FreeModule::rank
rank()
int FreeModule::rank () const inline
Definition at line 55 of file freemod.hpp.
 { return components.size(); }
References components.
Referenced by MatrixStream::appendPolynomialDone(), gbres_comp::betti_minimal(), gb2_comp::calc_gb(), change_degree(), MatrixStream::comCount(), MatrixConstructor::compute_column_degrees(), computeHashValue(), ChineseRemainder::CRA(), Matrix::diff(), gb2_comp::find_pairs(), Matrix::flip(), GBWeight::GBWeight(), get_induced_order(), highest_primary_degree(), gb2_comp::hilbertNumerator(), Matrix::identity(), IM2_FreeModule_get_degrees(), IM2_FreeModule_rank(), IM2_Matrix_concat(), IM2_RingMap_eval_matrix(), gbA::initialize(), GB_comp::initialize0(), is_equal(), lowest_primary_degree(), Matrix::make(), Matrix::make_sparse(), Matrix::make_sparse_vecs(), Matrix::Matrix(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), MatrixConstructor::MatrixConstructor(), MatrixStream::MatrixStream(), Matrix::n_cols(), Matrix::n_rows(), Matrix::operator+(), Matrix::operator-(), rawMatrixCRA(), rawMatrixRatConversion(), gbres_comp::reduce(), Matrix::remake(), gb2_comp::schreyer_append(), select_by_degrees(), GBinhom_comp::set_up0(), gb2_comp::setup(), GBKernelComputation::strip_gb(), sub_space(), FreeModule_symm::symm1(), text_out(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), transpose(), and Matrix::wedge_product().