Macaulay2 Engine: FreeModule::FreeModule
FreeModule()
FreeModule::FreeModule (const Ring * R, int n, bool has_schreyer_order) private
Definition at line 31 of file freemod.cpp.
 {
   initialize(RR);
   monomial deg = degree_monoid()->make_one();
   for (int i = 0; i < n; i++) append(deg);
   degree_monoid()->remove(deg);
   if (has_schreyer_order)
     {
       const PolynomialRing *P = RR->cast_to_PolynomialRing();
       assert(P != 0);
       assert(n == 0);
       schreyer = SchreyerOrder::create(P->getMonoid());
     }
   else
     schreyer = 0;
 }
References append(), Ring::cast_to_PolynomialRing(), SchreyerOrder::create(), degree_monoid(), PolynomialRing::getMonoid(), initialize(), Monoid::make_one(), Monoid::remove(), and schreyer.