Macaulay2 Engine: FreeModule::degree
degree()
const int* FreeModule::degree (int i) const inline
Definition at line 55 of file freemod.hpp.
 { return components[i]; }
References components.
Referenced by Matrix::compress(), KBasis::compute(), computeHashValue(), direct_sum_to(), GBRing::gbvector_multidegree(), IM2_FreeModule_get_degrees(), IM2_Matrix_concat(), is_equal(), make_schreyer(), res2_comp::multi_degree(), res_comp::multi_degree(), primary_degree(), select_by_degrees(), gbres_comp::setup(), hilb_comp::step(), sub_space(), FreeModule_symm::symm1(), text_out(), ResF4toM2Interface::to_M2_freemodule(), transpose(), and Ring::vec_is_homogeneous().