Macaulay2 Engine: FreeModule::lowest_primary_degree
lowest_primary_degree()
int FreeModule::lowest_primary_degree () const
Definition at line 434 of file freemod.cpp.
 {
   if (rank() == 0) return 0;
   int result = primary_degree(0);
   for (int i = 1; i < rank(); i++)
     {
       int a = primary_degree(i);
       if (a < result) result = a;
     }
   return result;
 }
References primary_degree(), and rank().
Referenced by gbres_comp::betti_minimal(), gb_emitter::gb_emitter(), gbA::initialize(), GB_comp::initialize0(), and gbres_comp::setup().