Macaulay2 Engine: FreeModule::get_induced_order
get_induced_order()
Matrix * FreeModule::get_induced_order () const
Definition at line 97 of file freemod.cpp.
 {
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (!schreyer || P == 0) return Matrix::zero(R->make_FreeModule(0), this);
   const SchreyerOrder *S = schreyer;
   int i;
   int maxtie = 0;
   for (i = 0; i < rank(); i++)
     if (S->compare_num(i) > maxtie) maxtie = S->compare_num(i);
   const FreeModule *F = R->make_FreeModule(maxtie + 1);
   MatrixConstructor mat(F, this, 0);
   for (i = 0; i < rank(); i++)
     {
       ring_elem f = P->make_flat_term(P->getCoefficients()->from_long(1),
                                       S->base_monom(i));
       mat.set_entry(S->compare_num(i), i, f);
     }
   return mat.to_matrix();
 }
References SchreyerOrder::base_monom(), Ring::cast_to_PolynomialRing(), SchreyerOrder::compare_num(), Ring::from_long(), PolynomialRing::getCoefficients(), PolynomialRing::make_flat_term(), Ring::make_FreeModule(), R, rank(), schreyer, MatrixConstructor::set_entry(), MatrixConstructor::to_matrix(), and Matrix::zero().
Referenced by IM2_FreeModule_get_schreyer().