Macaulay2 Engine: FreeModule::is_equal
is_equal()
bool FreeModule::is_equal (const FreeModule * F) const
Definition at line 151 of file freemod.cpp.
 {
   int i;
   if (this == F) return true;
   if (this->get_ring() != F->get_ring()) return false;
   if (rank() != F->rank()) return false;
   const Monoid *D = degree_monoid();
   if (D->n_vars() > 0)
     for (i = 0; i < rank(); i++)
       if (0 != D->compare(degree(i), F->degree(i))) return false;
   if (schreyer != NULL) return schreyer->is_equal(F->schreyer);
   if (F->schreyer != NULL) return false;
   return true;
 }
References Monoid::compare(), degree(), degree_monoid(), get_ring(), SchreyerOrder::is_equal(), Monoid::n_vars(), rank(), and schreyer.
Referenced by ChineseRemainder::CRA(), and IM2_FreeModule_is_equal().