Macaulay2 Engine: FreeModule::transpose
transpose()
FreeModule * FreeModule::transpose () const
Definition at line 221 of file freemod.cpp.
 {
   FreeModule *result = new_free();
   monomial deg = degree_monoid()->make_one();
   for (int i = 0; i < rank(); i++)
     {
       degree_monoid()->power(degree(i), -1, deg);
       result->append(deg);
     }
   // result has no schreyer order
   degree_monoid()->remove(deg);
   return result;
 }
References append(), degree(), degree_monoid(), Monoid::make_one(), new_free(), Monoid::power(), rank(), and Monoid::remove().
Referenced by Matrix::diff(), IM2_FreeModule_dual(), and Matrix::transpose().