Macaulay2 Engine: FreeModule::sub_space
sub_space() [1/2]
FreeModule * FreeModule::sub_space (int n) const
Definition at line 197 of file freemod.cpp.
{
  if (n < 0 || n > rank())
    {
      ERROR("subfreemodule: index out of bounds");
      return nullptr;
    }
  FreeModule *result = new_free();
  for (int i = 0; i < n; i++) result->append(degree(i));
  if (schreyer != nullptr) result->schreyer = schreyer->sub_space(n);
  return result;
}
References append(), degree(), ERROR(), new_free(), rank(), schreyer, and SchreyerOrder::sub_space().
Referenced by GaussElimComputation::GaussElimComputation(), HermiteComputation::HermiteComputation(), IM2_FreeModule_submodule(), gbA::initialize(), GB_comp::initialize(), GBinhom_comp::set_up(), Matrix::sub_matrix(), and Matrix::sub_matrix().