Macaulay2 Engine: FreeModule::make_schreyer
make_schreyer() [1/2]
FreeModule * FreeModule::make_schreyer (const GBMatrix * m) static
Definition at line 73 of file freemod.cpp.
 {
   const FreeModule *F = m->get_free_module();
   const PolynomialRing *R = F->get_ring()->cast_to_PolynomialRing();
   if (R == nullptr)
     {
       ERROR("expected a polynomial ring");
       return nullptr;
     }
   FreeModule *G = R->make_FreeModule();
   int rk = INTSIZE(m->elems);
   if (rk == 0) return G;
   auto D = R->degree_monoid();
   for (int i = 0; i < rk; i++)
     {
       monomial deg = D->make_one();
       gbvector *v = m->elems[i];
       if (v != nullptr) R->get_gb_ring()->gbvector_multidegree(F, v, deg);
       G->append(deg);
     }
   G->schreyer = SchreyerOrder::create(m);
   return G;
 }
References Ring::cast_to_PolynomialRing(), SchreyerOrder::create(), Ring::degree_monoid(), GBMatrix::elems, ERROR(), G, GBMatrix::get_free_module(), get_ring(), INTSIZE, Ring::make_FreeModule(), Monoid::make_one(), and R.