Macaulay2 Engine: FreeModule::append
append()
void FreeModule::append (const_monomial d)
Definition at line 127 of file freemod.cpp.
 {
   assert(schreyer == 0);
   monomial p = degree_monoid()->make_new(d);
   components.push_back(p);
 }
References components, degree_monoid(), Monoid::make_new(), p, and schreyer.
Referenced by MatrixConstructor::append(), direct_sum(), direct_sum_to(), exterior(), FreeModule(), IM2_FreeModule_make_degs(), make_schreyer(), res_comp::minimal_free_of(), shift(), sub_space(), FreeModule_symm::symm1(), tensor(), and transpose().