Macaulay2 Engine: FreeModule::sub_space
sub_space() [2/2]
FreeModule * FreeModule::sub_space (M2_arrayint a) const
Definition at line 205 of file freemod.cpp.
 {
   FreeModule *result = new_free();
   for (unsigned int i = 0; i < a->len; i++)
     if (a->array[i] >= 0 && a->array[i] < rank())
       result->append(degree(a->array[i]));
     else
       {
         ERROR("subfreemodule: index out of bounds");
         freemem(result);
         return NULL;
       }
   if (schreyer != NULL) result->schreyer = schreyer->sub_space(a);
   return result;
 }
References append(), degree(), ERROR(), freemem(), new_free(), rank(), schreyer, and SchreyerOrder::sub_space().