Macaulay2 Engine: FreeModule::text_out
text_out()
void FreeModule::text_out (buffer & o) const
Definition at line 450 of file freemod.cpp.
 {
   int i;
   int rk = rank();
   o << "free(rank " << rk << " degrees = {";
   for (i = 0; i < rk; i++)
     {
       if (i != 0) o << ", ";
       degree_monoid()->elem_text_out(o, degree(i));
     }
   o << "}";
   if (schreyer != NULL) schreyer->text_out(o);
   o << ')';
 }
References degree(), degree_monoid(), Monoid::elem_text_out(), rank(), schreyer, and SchreyerOrder::text_out().
Referenced by dfree(), IM2_FreeModule_to_string(), and gb2_comp::stats().