Macaulay2 Engine: FreeModule::select_by_degrees
select_by_degrees()
M2_arrayintOrNull FreeModule::select_by_degrees (M2_arrayintOrNull lo, M2_arrayintOrNull hi) const
Definition at line 393 of file freemod.cpp.
 {
   const Ring *R = get_ring();
   const Monoid *D = R->degree_monoid();
   std::vector<size_t> result;
   int ndegrees = D->n_vars();
   exponents_t exp = newarray_atomic(int, ndegrees);
   for (int i = 0; i < rank(); i++)
     {
       D->to_expvector(degree(i), exp);
 #if 0
       for (int i=0; i<ndegrees; i++)
         printf("%d ", exp[i]);
       if (degree_in_box(ndegrees, exp, lo, hi))
         printf("yes\n");
       else
         printf("no\n");
 #endif
       if (degree_in_box(ndegrees, exp, lo, hi)) result.push_back(i);
     }
   M2_arrayint selection = stdvector_to_M2_arrayint(result);
   freemem(exp);
   return selection;
 }
References degree(), degree_in_box(), Ring::degree_monoid(), mpfr::exp(), freemem(), get_ring(), Monoid::n_vars(), newarray_atomic, R, rank(), stdvector_to_M2_arrayint(), and Monoid::to_expvector().
Referenced by rawFreeModuleSelectByDegrees().