Macaulay2 Engine: FreeModule::computeHashValue
computeHashValue()
unsigned int FreeModule::computeHashValue () const protected virtual
Implements EngineObject.
Definition at line 22 of file freemod.cpp.
 {
   unsigned int hashval = 13;
   if (R->degree_monoid()->n_vars() == 0)
     hashval += rank();
   else
     for (int i = 0; i < rank(); i++) hashval = 14535 * hashval + degree(i)[0];
   return hashval;
 }
References degree(), Ring::degree_monoid(), Monoid::n_vars(), R, and rank().