Macaulay2 Engine: FreeModule::tensor
tensor()
FreeModule * FreeModule::tensor (const FreeModule * G) const
Definition at line 264 of file freemod.cpp.
 {
   if (get_ring() != G->get_ring())
     {
       ERROR("expected free modules over the same ring");
       return nullptr;
     }
   FreeModule *result = new_free();
   monomial deg = degree_monoid()->make_one();
   for (int i = 0; i < rank(); i++)
     for (int j = 0; j < G->rank(); j++)
       {
         degree_monoid()->mult(degree(i), G->degree(j), deg);
         result->append(deg);
       }
   degree_monoid()->remove(deg);
   if (schreyer != nullptr && G->schreyer != nullptr)
     result->schreyer = schreyer->tensor(G->schreyer);
   return result;
 }
References append(), ERROR(), ffpackInterface::rank(), schreyer, and SchreyerOrder::tensor().
Referenced by Matrix::diff(), Matrix::flip(), IM2_FreeModule_tensor(), Matrix::module_tensor(), Matrix::tensor(), and Matrix::wedge_product().