Macaulay2 Engine: FreeModule::make_schreyer
make_schreyer() [2/2]
FreeModule * FreeModule::make_schreyer (const Matrix * m) static
Definition at line 53 of file freemod.cpp.
 {
   int i;
   const PolynomialRing *R = m->get_ring()->cast_to_PolynomialRing();
   if (R == nullptr)
     {
       ERROR("expected a polynomial ring");
       return nullptr;
     }
   FreeModule *F = R->make_FreeModule();
   int rk = m->n_cols();
   if (rk == 0) return F;
   for (i = 0; i < rk; i++) F->append(m->cols()->degree(i));
   F->schreyer = SchreyerOrder::create(m);
   return F;
 }
References append(), Ring::cast_to_PolynomialRing(), Matrix::cols(), SchreyerOrder::create(), degree(), ERROR(), Matrix::get_ring(), Ring::make_FreeModule(), Matrix::n_cols(), R, and schreyer.
Referenced by GBKernelComputation::GBKernelComputation(), IM2_FreeModule_make_schreyer(), and GBMatrix::to_matrix().