Macaulay2 Engine: FreeModule::new_free
new_free()
FreeModule * FreeModule::new_free () const protected virtual
Definition at line 125 of file freemod.cpp.
 { return R->make_FreeModule(); }
References Ring::make_FreeModule(), and R.
Referenced by sub_space(), and transpose().