Macaulay2 Engine: FreeModule::symm
symm()
FreeModule * FreeModule::symm (int p) const
Definition at line 380 of file freemod.cpp.
 {
   FreeModule_symm SF(this, n);
   FreeModule *result = SF.value();
   if (schreyer != NULL) result->schreyer = schreyer->symm(n);
   return result;
 }
References schreyer, SchreyerOrder::symm(), and FreeModule_symm::value().
Referenced by IM2_FreeModule_symm(), and SymmMatrix::SymmMatrix().