Macaulay2 Engine: FreeModule::get_schreyer_order
get_schreyer_order()
const SchreyerOrder* FreeModule::get_schreyer_order () const inline
Definition at line 54 of file freemod.hpp.
 { return schreyer; }
References schreyer.
Referenced by SchreyerOrder::create(), GBRing::find_reduction_monomial(), GBKernelComputation::GBKernelComputation(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_get_lead_monomial(), GBRing::gbvector_term(), GBRing::gbvector_term_exponents(), res_comp::initialize(), and GBRing::mult_by_term().