Macaulay2 Engine: FreeModule::primary_degree
primary_degree()
int FreeModule::primary_degree (int i) const
Definition at line 419 of file freemod.cpp.
 {
   int result =
       degree_monoid()->degree_weights(degree(i), get_ring()->get_heft_vector());
   return result;
 }
References degree(), degree_monoid(), Monoid::degree_weights(), and get_ring().
Referenced by gbres_comp::betti_minimal(), res_comp::degree(), GBWeight::GBWeight(), highest_primary_degree(), res2_comp::initialize(), res_comp::initialize(), lowest_primary_degree(), MatrixSorter::MatrixSorter(), res2_comp::new_base_res2_pair(), res2_comp::new_res2_pair(), gb2_comp::new_ring_pair(), gb2_comp::new_s_pair(), gb_emitter::start_degree(), and Ring::vec_degree_weights().