Macaulay2 Engine: FreeModule::append_schreyer
append_schreyer()
void FreeModule::append_schreyer (const_monomial d, const_monomial base_monom, int compare_num)
Definition at line 137 of file freemod.cpp.
 {
   assert(schreyer != 0);
   monomial p = R->degree_monoid()->make_new(d);
   components.push_back(p);
   schreyer->append(compare_num, base);
 }
References SchreyerOrder::append(), base, components, Ring::degree_monoid(), Monoid::make_new(), p, R, and schreyer.
Referenced by res2_comp::free_of(), res_comp::free_of(), res2_comp::minimal_free_of(), gb2_comp::schreyer_append(), gbres_comp::setup(), and ResF4toM2Interface::to_M2_freemodule().