Macaulay2 Engine: FreeModule::shift
shift()
FreeModule * FreeModule::shift (const_monomial d) const
Definition at line 173 of file freemod.cpp.
 {
   FreeModule *result = new_free();
   monomial deg = degree_monoid()->make_one();
   for (int i = 0; i < rank(); i++)
     {
       degree_monoid()->mult(degree(i), d, deg);
       result->append(deg);
     }
   if (schreyer != NULL) result->schreyer = schreyer->copy();
   degree_monoid()->remove(deg);
   return result;
 }
References append(), SchreyerOrder::copy(), ffpackInterface::rank(), SchreyerOrder::remove(), and schreyer.