Macaulay2 Engine: FreeModule::degree_monoid
degree_monoid()
const Monoid* FreeModule::degree_monoid () const inline
Definition at line 53 of file freemod.hpp.
 { return R->degree_monoid(); }
References Ring::degree_monoid(), and R.
Referenced by append(), append_schreyer(), change_degree(), computeHashValue(), FreeModule(), is_equal(), primary_degree(), text_out(), and transpose().