Macaulay2 Engine: FreeModule::get_ring
get_ring()
const Ring* FreeModule::get_ring () const inline
Definition at line 52 of file freemod.hpp.
 { return R; }
References R.
Referenced by coeffs_of_vec(), SchreyerOrder::create(), Matrix::flip(), gbres_comp::free_module(), ResF4toM2Interface::from_M2_vec(), F4toM2Interface::from_M2_vec(), GBKernelComputation::GBKernelComputation(), GBMatrix::GBMatrix(), GBWeight::GBWeight(), Matrix::get_ring(), HilbertController::HilbertController(), Matrix::identity(), IM2_FreeModule_get_degrees(), IM2_FreeModule_ring(), IM2_Matrix_concat(), IM2_Matrix_lift(), IM2_Matrix_promote(), is_equal(), Matrix::koszul(), Matrix::koszul_monomials(), Matrix::make(), make_schreyer(), Matrix::make_sparse(), Matrix::make_sparse_vecs(), MatrixStream::MatrixStream(), NCMonomialMatrix(), Matrix::remake(), gb2_comp::setup(), F4GB::show_gb_array(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), GBMatrix::to_matrix(), Matrix::transpose(), FreeModule_symm::value(), Matrix::wedge_product(), and Matrix::zero().