Macaulay2 Engine: M2::ARingGFGivaro::representationToM2Array
representationToM2Array() [2/2]
M2_arrayint M2::ARingGFGivaro::representationToM2Array (UTT representation, long coeffNum, UTT charac) static private
Definition at line 273 of file aring-gf-givaro.cpp.
 {
 #ifdef DEBUG_GF
   std::cerr << "representationToM2Array:\n";
 #endif
   M2_arrayint polynomialCoeffs = M2_makearrayint(static_cast<int>(coeffNum));
 #ifdef DEBUG_GF
   std::cerr << "coeffNum" << coeffNum << std::endl;
   std::cerr << "charac" << charac << std::endl;
   std::cerr << "representation" << representation << std::endl;
 #endif
   long exp = 0;
   while (representation != 0)
     {
       assert(exp < coeffNum);
       UTT remainder = representation % charac;
       representation = representation / charac;
       polynomialCoeffs->array[exp] = static_cast<int>(remainder);
 #ifdef DEBUG_GF
       // debug:
       if (exp > 0) std::cerr << " + ";
       std::cerr << remainder << "*"
                 << "X^" << exp;
 // end debug
 #endif
       exp++;
     }
   assert(representation == 0);
   for (; exp < coeffNum; exp++)
     {
       assert(exp < coeffNum);
       polynomialCoeffs->array[exp] = 0;
     }
 #ifdef DEBUG_GF
   std::cerr << "\n";
 #endif
   return polynomialCoeffs;
 }
References mpfr::exp(), M2_makearrayint(), and mpfr::remainder().