Macaulay2 Engine: M2::ARingGFGivaro::power
power()
void M2::ARingGFGivaro::power (elem & result, const elem a, const STT n) const
Todo Jakob:
overflow can occur due to multiplication. use exact mpz for multiply and modulo operation instead!
Definition at line 553 of file aring-gf-givaro.cpp.
 {
   if (givaroField.isnzero(a))
     {
       mpz_t mpz_a;
       mpz_t mpz_n;
       mpz_t mpz_tmp;
       mpz_init(mpz_a);
       mpz_init(mpz_n);
       mpz_init(mpz_tmp);
       mpz_set_si(mpz_n, n);
       mpz_set_ui(mpz_a, a);
       // std::cerr << "a = " << a << std::endl;
       // std::cerr << "mpz_a = " << mpz_a << std::endl;
       // std::cerr << "n = " << n << std::endl;
       // std::cerr << "mpz_n = " << mpz_n << std::endl;
       mpz_fdiv_r_ui(mpz_tmp, mpz_n, givaroField.cardinality() - 1);
       mpz_mul(mpz_n, mpz_a, mpz_tmp);
       STT tmp =
           static_cast<STT>(mpz_fdiv_ui(mpz_n, givaroField.cardinality() - 1));
       if (tmp == 0)
         {
           tmp += givaroField.cardinality() - 1;
           // result=givaroField.one;
         }
       // std::cerr << "tmp = " << tmp << std::endl;
       assert(tmp >= 0);  // tmp<0 should never occur
       if (tmp < 0) tmp += givaroField.cardinality() - 1;
       result = tmp;
       mpz_clear(mpz_a);
       mpz_clear(mpz_n);
       mpz_clear(mpz_tmp);
     }
   else
     {
       if (n < 0) ERROR(" division by zero");
       result = 0;
     }
 }
References ERROR(), and givaroField.
Referenced by power_mpz(), and promote().