Macaulay2 Engine: M2::ARingGFGivaro::lift_to_original_ring
lift_to_original_ring()
void M2::ARingGFGivaro::lift_to_original_ring (ring_elem & result, const ElementType & f) const
Definition at line 681 of file aring-gf-givaro.cpp.
 {
   // This code needs review, and tests.  See git issue #612
   if (f == givaroField.zero)
     result = mOriginalRing->from_long(0);
   else if (f == givaroField.one)
     result = mOriginalRing->from_long(1);
   else
     {
       result = mOriginalRing->power(mPrimitiveElement, static_cast<int>(f));
     }
 }
References Ring::from_long(), givaroField, mOriginalRing, mPrimitiveElement, and Ring::power().
Referenced by lift().