Macaulay2 Engine: M2::ARingGFGivaro::set_from_mpq
set_from_mpq()
bool M2::ARingGFGivaro::set_from_mpq (elem & result, mpq_srcptr a) const
Definition at line 490 of file aring-gf-givaro.cpp.
 {
   ElementType n, d;
   set_from_mpz(n, mpq_numref(a));
   set_from_mpz(d, mpq_denref(a));
   if (is_zero(d)) return false;
   divide(result, n, d);
   return true;
 }
References divide(), is_zero(), and set_from_mpz().