Macaulay2 Engine: M2::ARingGFGivaro::promote
promote()
bool M2::ARingGFGivaro::promote (const Ring * Rf, const ring_elem f, ElementType & result) const
Definition at line 648 of file aring-gf-givaro.cpp.
 {
   if (mOriginalRing != Rf) return false;
   result = givaroField.zero;
   int exp[1];
   ElementType genRep;
   givaroField.generator(genRep);
 #ifdef DEBUG_GF
   std::cerr << "genRep " << genRep << std::endl;
 #endif
   for (Nterm *t = f; t != NULL; t = t->next)
     {
       elem a, b;
       std::pair<bool, long> res =
           mOriginalRing->getCoefficientRing()->coerceToLongInteger(t->coeff);
       assert(res.first);
       set_from_long(a, res.second);
       mOriginalRing->getMonoid()->to_expvector(t->monom, exp);
       // exp[0] is the variable we want.  Notice that since the ring is a
       // quotient,
       // this degree is < n (where Q_ = P^n).
       power(b, genRep, exp[0]);
       mult(a, a, b);
       add(result, result, a);
     }
   return true;
 }
References add(), Ring::coerceToLongInteger(), mpfr::exp(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), givaroField, mOriginalRing, mult(), power(), set_from_long(), and Monoid::to_expvector().