Macaulay2 Engine: res_poly::copy
copy()
resterm * res_poly::copy (const resterm * f) const
Definition at line 60 of file res-a1-poly.cpp.
 {
   resterm head;
   resterm *result = &head;
   for (const resterm *tm = f; tm != nullptr; tm = tm->next)
     {
       result->next = new_term();
       result = result->next;
       result->comp = tm->comp;
       result->coeff = K->copy(tm->coeff);
       M->copy(tm->monom, result->monom);
     }
   result->next = nullptr;
   return head.next;
 }
References resterm::coeff, resterm::comp, Ring::copy(), Monoid::copy(), K, M, resterm::monom, new_term(), and resterm::next.