Macaulay2 Engine: res_poly::elem_text_out
elem_text_out() [1/2]
void res_poly::elem_text_out (buffer & o, const resterm * f) const
Definition at line 236 of file res-a1-poly.cpp.
 {
   if (f == NULL)
     {
       o << "0";
       return;
     }
   bool p_one = false;
   bool p_parens = true;
   bool p_plus = false;
   for (const resterm *t = f; t != NULL; t = t->next)
     {
       int isone = M->is_one(t->monom);
       K->elem_text_out(o, t->coeff, p_one, p_parens, p_plus);
       if (!isone) M->elem_text_out(o, t->monom, p_one);
       o << "<" << t->comp->me << ">";
       p_plus = true;
     }
 }
References Ring::elem_text_out(), Monoid::elem_text_out(), Monoid::is_one(), K, M, and resterm::next.
Referenced by drespoly(), elem_text_out(), and res_comp::text_out().