Macaulay2 Engine: res_poly::remove
remove()
void res_poly::remove (resterm *& f) const
Definition at line 75 of file res-a1-poly.cpp.
 {
   while (f != nullptr)
     {
       resterm *tmp = f;
       f = f->next;
       K->remove(tmp->coeff);
       resterm_stash->delete_elem(tmp);
     }
 }
References resterm::coeff, stash::delete_elem(), K, resterm::next, Ring::remove(), and resterm_stash.
Referenced by res_comp::remove_res_pair().