Macaulay2 Engine: res_poly::ring_subtract_multiple_to
ring_subtract_multiple_to()
void res_poly::ring_subtract_multiple_to (resterm *& f, ring_elem c, const int * m, res_pair * x, const ring_elem g) const
Definition at line 210 of file res-a1-poly.cpp.
 {
   ring_elem minus_c = K->negate(c);
   resterm *h = ring_mult_by_term(g, minus_c, m, x);
   add_to(f, h);
   K->remove(minus_c);
 }
References safe::add_to(), and x.
Referenced by res_comp::reduce(), res_comp::reduce_gen(), and res_comp::reduce_level_one().