Macaulay2 Engine: res_poly::to_vector
to_vector()
vec res_poly::to_vector (const resterm * f, const FreeModule * F, int to_minimal = 0) const
Definition at line 257 of file res-a1-poly.cpp.
 {
   vecHeap H(F);
   monomial mon = M->make_one();
   for (const resterm *tm = f; tm != NULL; tm = tm->next)
     {
       //    int x = (to_minimal ? tm->comp->minimal_me : tm->comp->me);
       int x =
           tm->comp
               ->minimal_me;  // MES: Currently used for non-minimal as well...
       M->divide(tm->monom, tm->comp->base_monom, mon);
       ring_elem a = R->make_flat_term(tm->coeff, mon);
       vec tmp = R->make_vec(x, a);
       H.add(tmp);
     }
   M->remove(mon);
   return H.value();
 }
References vecHeap::add(), Monoid::divide(), M, PolynomialRing::make_flat_term(), Monoid::make_one(), Ring::make_vec(), resterm::next, R, Monoid::remove(), vecHeap::value(), and x.
Referenced by res_comp::make(), and res_comp::make_minimal().