Macaulay2 Engine: res_poly::mult_by_term
mult_by_term()
resterm * res_poly::mult_by_term (const resterm * f, ring_elem c, const int * m) const
Definition at line 86 of file res-a1-poly.cpp.
 {
   resterm head;
   resterm *result = &head;
   for (const resterm *tm = f; tm != nullptr; tm = tm->next)
     {
       result->next = new_term();
       result = result->next;
       result->comp = tm->comp;
       result->coeff = K->mult(c, tm->coeff);
       M->mult(tm->monom, m, result->monom);
     }
   result->next = nullptr;
   return head.next;
 }
References resterm::coeff, resterm::comp, K, M, resterm::monom, Ring::mult(), Monoid::mult(), new_term(), and resterm::next.