Macaulay2 Engine: res_poly::ring_mult_by_term
ring_mult_by_term()
resterm * res_poly::ring_mult_by_term (const ring_elem f, ring_elem c, const int * m, res_pair * x) const
Definition at line 103 of file res-a1-poly.cpp.
 {
   resterm head;
   resterm *result = &head;
   for (Nterm& tm : f)
     {
       result->next = new_term();
       result = result->next;
       result->comp = x;
       result->coeff = K->mult(c, tm.coeff);
       M->mult(tm.monom, m, result->monom);
     }
   result->next = NULL;
   return head.next;
 }
References resterm::coeff, resterm::comp, K, M, resterm::monom, Ring::mult(), Monoid::mult(), new_term(), resterm::next, and x.