Macaulay2 Engine: res_poly::subtract_multiple_to
subtract_multiple_to()
void res_poly::subtract_multiple_to (resterm *& f, ring_elem c, const int * m, const resterm * g) const
Definition at line 199 of file res-a1-poly.cpp.
 {
   ring_elem minus_c = K->negate(c);
   resterm *h = mult_by_term(g, minus_c, m);
   add_to(f, h);
   K->remove(minus_c);
 }
References safe::add_to().
Referenced by res_comp::reduce(), res_comp::reduce_gen(), res_comp::reduce_level_one(), and res_comp::reduce_minimal().