Macaulay2 Engine: res_poly::new_term
new_term() [1/2]
resterm * res_poly::new_term () const private
Definition at line 28 of file res-a1-poly.cpp.
 {
   resterm *result = reinterpret_cast<resterm *>(resterm_stash->new_elem());
   result->next = nullptr;
   return result;
 }
References stash::new_elem(), resterm::next, and resterm_stash.
Referenced by copy(), from_vector(), mult_by_monomial(), mult_by_term(), res_comp::reduce(), res_comp::reduce_level_one(), ring_mult_by_term(), and strip().