Macaulay2 Engine: res_poly::make_monic
make_monic()
void res_poly::make_monic (resterm *& f) const
Definition at line 122 of file res-a1-poly.cpp.
 {
   if (f == nullptr) return;
   ring_elem c_inv = K->invert(f->coeff);
   for (resterm *tm = f; tm != nullptr; tm = tm->next) K->mult_to(tm->coeff, c_inv);
   K->remove(c_inv);
 }
References resterm::coeff, Ring::invert(), K, Ring::mult_to(), resterm::next, and Ring::remove().
Referenced by res_comp::handle_gen(), and res_comp::handle_pair().