Macaulay2 Engine: res_poly::from_vector
from_vector()
resterm * res_poly::from_vector (const gc_vector< res_pair * > & base, const vec v) const
Definition at line 279 of file res-a1-poly.cpp.
 {
   resterm head;
   resterm *result = &head;
   for (vecterm *w = v; w != nullptr; w = w->next)
     for (Nterm& t : w->coeff)
       {
         result->next = new_term();
         result = result->next;
         result->comp = base[w->comp];
         result->coeff = t.coeff;
         M->copy(t.monom, result->monom);
         M->mult(result->monom, result->comp->base_monom, result->monom);
       }
   result->next = nullptr;
   // Now we must sort these
   sort(head.next);
   return head.next;
 }
References base, res_pair::base_monom, resterm::coeff, Nterm::coeff, resterm::comp, Monoid::copy(), M, resterm::monom, Nterm::monom, Monoid::mult(), new_term(), resterm::next, vec::next, and sort().
Referenced by res_comp::new_res_pair().