Macaulay2 Engine: res_poly::add_to
add_to()
void res_poly::add_to (resterm *& f, resterm *& g) const
Definition at line 132 of file res-a1-poly.cpp.
 {
   if (g == NULL) return;
   if (f == NULL)
     {
       f = g;
       g = NULL;
       return;
     }
   resterm head;
   resterm *result = &head;
   while (1) switch (compare(f, g))
       {
         case -1:
           result->next = g;
           result = result->next;
           g = g->next;
           if (g == NULL)
             {
               result->next = f;
               f = head.next;
               return;
             }
           break;
         case 1:
           result->next = f;
           result = result->next;
           f = f->next;
           if (f == NULL)
             {
               result->next = g;
               f = head.next;
               g = NULL;
               return;
             }
           break;
         case 0:
           resterm *tmf = f;
           resterm *tmg = g;
           f = f->next;
           g = g->next;
           K->add_to(tmf->coeff, tmg->coeff);
           if (K->is_zero(tmf->coeff))
             resterm_stash->delete_elem(tmf);
           else
             {
               result->next = tmf;
               result = result->next;
             }
           resterm_stash->delete_elem(tmg);
           if (g == NULL)
             {
               result->next = f;
               f = head.next;
               return;
             }
           if (f == NULL)
             {
               result->next = g;
               f = head.next;
               g = NULL;
               return;
             }
           break;
       }
 }
References Ring::add_to(), resterm::coeff, compare(), stash::delete_elem(), Ring::is_zero(), K, resterm::next, and resterm_stash.
Referenced by sort().