Macaulay2 Engine: res_poly::mult_by_monomial
mult_by_monomial()
resterm * res_poly::mult_by_monomial (const resterm * f, const int * m) const
Definition at line 44 of file res-a1-poly.cpp.
 {
   resterm head;
   resterm *result = &head;
   for (const resterm *tm = f; tm != nullptr; tm = tm->next)
     {
       result->next = new_term();
       result = result->next;
       result->comp = tm->comp;
       result->coeff = K->copy(tm->coeff);
       M->mult(tm->monom, m, result->monom);
     }
   result->next = nullptr;
   return head.next;
 }
References resterm::coeff, resterm::comp, Ring::copy(), K, M, resterm::monom, Monoid::mult(), new_term(), and resterm::next.