Macaulay2 Engine: BIBasis::Launcher::CheckMatrix
CheckMatrix()
bool BIBasis::Launcher::CheckMatrix (const Matrix * matrix) const private
Definition at line 50 of file launcher.cpp.
     {
         if (!matrix)
         {
             ERROR("BIBasis::CheckMatrix(): no input matrix.");
             return false;
         }
         const Ring* matrixRing = matrix->get_ring();
         if (!matrixRing)
         {
             ERROR("BIBasis::CheckMatrix(): failed to get input matrix ring.");
             return false;
         }
         if (matrixRing->characteristic() != 2)
         {
             ERROR("BIBasis::CheckMatrix(): input matrix ring is not ZZ/2.");
             return false;
         }
         const PolynomialRing* polynomialRing = matrixRing->cast_to_PolynomialRing();
         if (!polynomialRing)
         {
             ERROR("BIBasis::CheckMatrix(): failed to cast matrix ring to polynomial ring.");
             return false;
         }
         const Ring* coefficientRing = polynomialRing->getCoefficientRing();
         if (!coefficientRing)
         {
             ERROR("BIBasis::CheckMatrix(): failed to get coefficient ring.");
             return false;
         }
         if (!coefficientRing->isFinitePrimeField())
         {
             ERROR("BIBasis::CheckMatrix(): coefficient ring is not ZZ/2.");
             return false;
         }
         const Monoid* monoid = polynomialRing->getMonoid();
         if (!monoid)
         {
             ERROR("BIBasis::CheckMatrix(): failed to get monoid.");
             return false;
         }
         const MonomialOrdering* monomialOrdering = monoid->getMonomialOrdering();
         if (!monomialOrdering)
         {
             ERROR("BIBasis::CheckMatrix(): failed to get monomial ordering.");
             return false;
         }
         if (!monomialOrdering->array[0])
         {
             ERROR("BIBasis::CheckMatrix(): monomial ordering is unknown.");
             return false;
         }
         switch(monomialOrdering->array[0]->type)
         {
             case MO_LEX:
                 GetSettingsManager().SetMonomialOrder(Monom::Lex);
                 break;
             case MO_GREVLEX:
                 GetSettingsManager().SetMonomialOrder(Monom::DegRevLex);
                 break;
             case MO_WEIGHTS:
                 GetSettingsManager().SetMonomialOrder(Monom::DegLex);
                 break;
             default:
                 ERROR("BIBasis::CheckMatrix(): monomial ordering is unsupported: %d.", monomialOrdering->array[0]->type);
                 return false;
         }
         GetSettingsManager().SetNumberOfVariables(static_cast<BIBasis::Monom::Integer>(polynomialRing->n_vars()));
         return true;
     }
References MonomialOrdering::array, Ring::cast_to_PolynomialRing(), Ring::characteristic(), BIBasis::Monom::DegLex, BIBasis::Monom::DegRevLex, ERROR(), Matrix::get_ring(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), Monoid::getMonomialOrdering(), BIBasis::GetSettingsManager(), Ring::isFinitePrimeField(), BIBasis::Monom::Lex, MO_GREVLEX, MO_LEX, MO_WEIGHTS, PolynomialRing::n_vars(), BIBasis::SettingsManager::SetMonomialOrder(), and BIBasis::SettingsManager::SetNumberOfVariables().
Referenced by GetBIBasisMatrix().