Macaulay2 Engine: BIBasis::Launcher::GetBIBasisMatrix
GetBIBasisMatrix()
const Matrix * BIBasis::Launcher::GetBIBasisMatrix (const Matrix * matrix, int toGroebner) const
Definition at line 21 of file launcher.cpp.
     {
         if (!CheckMatrix(matrix))
         {
             return NULL;
         }
         switch(GetSettingsManager().GetMonomialOrder())
         {
             case Monom::Lex:
                 {
                     BooleanInvolutiveBasis<MonomLex> basis(matrix, toGroebner);
                     return basis.ToMatrix();
                 }
             case Monom::DegLex:
                 {
                     BooleanInvolutiveBasis<MonomDL> basis(matrix, toGroebner);
                     return basis.ToMatrix();
                 }
             case Monom::DegRevLex:
                 {
                     BooleanInvolutiveBasis<MonomDRL> basis(matrix, toGroebner);
                     return basis.ToMatrix();
                 }
             default:
                 return 0;
         };
     }
References CheckMatrix(), BIBasis::Monom::DegLex, BIBasis::Monom::DegRevLex, BIBasis::GetSettingsManager(), BIBasis::Monom::Lex, and BIBasis::BooleanInvolutiveBasis< MonomType >::ToMatrix().
Referenced by rawBIBasis().