Macaulay2 Engine: F4SPairSet::insert_generator
insert_generator()
void F4SPairSet::insert_generator (int deg, packed_monomial lcm, int column)
Definition at line 62 of file f4-spairs.cpp.
 {
   spair *p = make_spair(F4_SPAIR_GEN, deg, col, -1);
   M->copy(lcm, p->lcm);
   p->next = heap;
   heap = p;
 }
References MonomialInfo::copy(), F4_SPAIR_GEN, heap, M, make_spair(), and p.
Referenced by F4GB::new_generators().