Macaulay2 Engine: F4SPairSet::insert_spair
insert_spair()
void F4SPairSet::insert_spair (pre_spair * p, int me)
Definition at line 46 of file f4-spairs.cpp.
 {
   int j = p->j;
   int deg = p->deg1 + gb[me]->deg;
   // int me_component = M->get_component(gb[me]->f.monoms);
   spair *result = make_spair(F4_SPAIR_SPAIR, deg, me, j);
   M->from_varpower_monomial(p->quot, 0, result->lcm);
   M->unchecked_mult(result->lcm, gb[me]->f.monoms, result->lcm);
   result->next = heap;
   heap = result;
 }
References F4_SPAIR_SPAIR, MonomialInfo::from_varpower_monomial(), gb, heap, spair::lcm, M, make_spair(), spair::next, p, and MonomialInfo::unchecked_mult().
Referenced by construct_pairs().