Macaulay2 Engine: F4SPairSet::remove_unneeded_pairs
remove_unneeded_pairs()
int F4SPairSet::remove_unneeded_pairs () private
Definition at line 78 of file f4-spairs.cpp.
 {
   // Loop through every spair, determine if it can be jettisoned
   // and do so.  Return the number removed.
   // MES: Check the ones in this_set? Probably not needed...
   spair head;
   spair *p = &head;
   gbelem *m = gb[gb.size() - 1];
   int nremoved = 0;
   head.next = heap;
   while (p->next != nullptr)
     if (pair_not_needed(p->next, m))
       {
         nremoved++;
         spair *tmp = p->next;
         p->next = tmp->next;
         tmp->next = nullptr;
         delete_spair(tmp);
       }
     else
       p = p->next;
   heap = head.next;
   return nremoved;
 }
References delete_spair(), gb, heap, spair::next, p, and pair_not_needed().
Referenced by find_new_pairs().