Macaulay2 Engine: F4SPairSet::construct_pairs
construct_pairs()
int F4SPairSet::construct_pairs (bool remove_disjoints) private
Definition at line 245 of file f4-spairs.cpp.
 {
   if (gb.size() == 0) return 0;
   VP.reset();
   PS.reset();
   gbelem *me = gb[gb.size() - 1];
   int me_component = static_cast<int>(M->get_component(me->f.monoms));
   typedef VECTOR(pre_spair *) spairs;
   VECTOR(VECTOR(pre_spair *)) bins;
   // Loop through each element of gb, and create the pre_spair
   for (int i = 0; i < gb.size() - 1; i++)
     {
       if (gb[i]->minlevel == ELEM_NON_MIN_GB) continue;
       if (me_component != M->get_component(gb[i]->f.monoms)) continue;
       pre_spair *p = create_pre_spair(i);
       insert_pre_spair(bins, p);
     }
   // Now minimalize the set //
   MonomialLookupTable *montab = new MonomialLookupTable(M->n_vars());
   PreSPairSorter C;
   int n_new_pairs = 0;
   for (int i = 0; i < bins.size(); i++)
     {
       if (bins[i].size() == 0) continue;
       // First sort the monomials of this degree
       std::stable_sort(bins[i].begin(), bins[i].end(), C);
       // Loop through each degree and potentially insert...
       spairs::iterator first = bins[i].begin();
       spairs::iterator next = first;
       spairs::iterator end = bins[i].end();
       for (; first != end; first = next)
         {
           next = first + 1;
           pre_spair *chosen = *first;
           while (next != end)
             {
               pre_spair *p = *next;
               if (!varpower_monomials::is_equal(chosen->quot, p->quot)) break;
               next++;
             }
           /* At this point: [first,next) is the range of equal monomials */
           int32_t junk;
           bool inideal = montab->find_one_divisor_vp(0, chosen->quot, junk);
           if (!inideal)
             {
               // MES: Maybe choose another of the equal monomials...
               montab->insert_minimal_vp(0, chosen->quot, 0);
               // The following condition is that gcd is not one
               if (!remove_disjoints || !chosen->are_disjoint)
                 {
                   insert_spair(chosen, INTSIZE(gb) - 1);
                   n_new_pairs++;
                 }
             }
         }
     }
   delete montab;
   return n_new_pairs;
 }
References pre_spair::are_disjoint, begin(), create_pre_spair(), ELEM_NON_MIN_GB, end(), gbelem::f, F4MonomialLookupTableT< Key >::find_one_divisor_vp(), gb, MonomialInfo::get_component(), F4MonomialLookupTableT< Key >::insert_minimal_vp(), insert_pre_spair(), insert_spair(), INTSIZE, ExponentList< E, L >::is_equal(), M, GBF4Polynomial::monoms, MonomialInfo::n_vars(), p, PS, pre_spair::quot, F4MemoryBlock< T, NSLAB >::reset(), VECTOR(), and VP.
Referenced by find_new_pairs().