Macaulay2 Engine: F4SPairSet::pair_not_needed
pair_not_needed()
bool F4SPairSet::pair_not_needed (spair * p, gbelem * m) private
Definition at line 70 of file f4-spairs.cpp.
 {
   if (p->type != F4_SPAIR_SPAIR && p->type != F4_SPAIR_RING) return false;
   if (M->get_component(p->lcm) != M->get_component(m->f.monoms)) return false;
   return M->unnecessary(
       m->f.monoms, gb[p->i]->f.monoms, gb[p->j]->f.monoms, p->lcm);
 }
References gbelem::f, F4_SPAIR_RING, F4_SPAIR_SPAIR, gb, MonomialInfo::get_component(), M, GBF4Polynomial::monoms, p, and MonomialInfo::unnecessary().
Referenced by remove_unneeded_pairs().