Macaulay2 Engine: F4SPairSet::make_spair
make_spair()
spair * F4SPairSet::make_spair (spair_type type, int deg, int i, int j) private
Definition at line 35 of file f4-spairs.cpp.
 {
   spair *result = reinterpret_cast<spair *>(spair_stash->new_elem());
   result->next = 0;
   result->type = type;
   result->deg = deg;
   result->i = i;
   result->j = j;
   return result;
 }
References spair::deg, spair::i, spair::j, stash::new_elem(), spair::next, spair_stash, and spair::type.
Referenced by insert_generator(), and insert_spair().