Macaulay2 Engine: F4SPairSet::create_pre_spair
create_pre_spair()
pre_spair * F4SPairSet::create_pre_spair (int i) private
Definition at line 217 of file f4-spairs.cpp.
 {
   // Steps:
   //  a. allocate the space for the pre_spair and the varpower monomial
   //  b. compute the quotient and the degree
   pre_spair *result = PS.allocate();
   result->quot = VP.reserve(max_varpower_size);
   result->j = j;
   result->type = F4_SPAIR_SPAIR;
   M->quotient_as_vp(gb[j]->f.monoms,
                     gb[gb.size() - 1]->f.monoms,
                     result->quot,
                     result->deg1,
                     result->are_disjoint);
   int len = static_cast<int>(varpower_monomials::length(result->quot));
   VP.intern(len);
   return result;
 }
References F4MemoryBlock< T, NSLAB >::allocate(), pre_spair::are_disjoint, pre_spair::deg1, F4_SPAIR_SPAIR, gb, F4MemoryBlock< T, NSLAB >::intern(), pre_spair::j, ExponentList< E, L >::length(), M, max_varpower_size, PS, pre_spair::quot, MonomialInfo::quotient_as_vp(), F4MemoryBlock< T, NSLAB >::reserve(), pre_spair::type, and VP.
Referenced by construct_pairs().