Macaulay2 Engine: F4SPairSet::find_new_pairs
find_new_pairs()
int F4SPairSet::find_new_pairs (bool remove_disjoints)
Definition at line 173 of file f4-spairs.cpp.
 {
   nsaved_unneeded += remove_unneeded_pairs();
   int len = construct_pairs(remove_disjoints);
   return len;
 }
References construct_pairs(), nsaved_unneeded, and remove_unneeded_pairs().
Referenced by F4GB::insert_gb_element(), and F4GB::start_computation().