Macaulay2 Engine: solve_via_lapack
solve_via_lapack()
bool solve_via_lapack (int size, complex * A, int bsize, complex * b, complex * x)
Definition at line 1165 of file NAG.cpp.
 {
   bool ret = true;
   int info;
   int* permutation = newarray_atomic(int, size);
   complex* At = newarray_atomic(complex, size * size);
   int i, j;
   for (i = 0; i < size; i++)
     for (j = 0; j < size; j++)  // transpose the matrix: lapack solves A^t x = b
       *(At + i * size + j) = *(A + j * size + i);
   double* copyA = (double*)At;
   copy_complex_array<ComplexField>(size, b, x);
   double* copyb = (double*)x;  // result is stored in copyb
   /*
   printf("-----------(solve)-----------------------------------\ncopyA:\n");
   for (i=0; i<size*size; i++)
     printf("(%lf %lf) ", *(copyA+2*i), *(copyA+2*i+1));
   printf("\nb:\n");
   for (i=0; i<size; i++)
     printf("(%lf %lf) ", *(copyb+2*i), *(copyb+2*i+1));
   */
   zgesv_(&size, &bsize, copyA, &size, permutation, copyb, &size, &info);
   /*
   printf("\nx = b:\n");
   for (i=0; i<size; i++)
     printf("(%lf %lf) ", *(copyb+2*i), *(copyb+2*i+1));
   printf("\n");
   */
   if (info > 0)
     {
       ERROR("according to zgesv, matrix is singular");
       ret = false;
     }
   else if (info < 0)
     {
       ERROR("argument passed to zgesv had an illegal value");
       ret = false;
     }
   freemem(permutation);
   freemem(At);
   return ret;
 }
References ERROR(), freemem(), newarray_atomic, x, and zgesv_().