Macaulay2 Engine: solve_via_lapack_without_transposition
solve_via_lapack_without_transposition()
bool solve_via_lapack_without_transposition (int size, complex * A, int bsize, complex * b, complex * x)
Definition at line 1218 of file NAG.cpp.
 {
   bool ret = true;
   int info;
   int* permutation = newarray_atomic(int, size);
   // int i,j;
   double* copyA = (double*)A;
   copy_complex_array<ComplexField>(size, b, x);
   double* copyb = (double*)x;  // result is stored in copyb
   /*
   printf("-----------(solve)-----------------------------------\ncopyA:\n");
   for (int i=0; i<size*size; i++)
     printf("(%lf %lf) ", *(copyA+2*i), *(copyA+2*i+1));
   printf("\nb:\n");
   for (int i=0; i<size; i++)
     printf("(%lf %lf) ", *(copyb+2*i), *(copyb+2*i+1));
   */
   zgesv_(&size, &bsize, copyA, &size, permutation, copyb, &size, &info);
   /*
   printf("\nx = b:\n");
   for (i=0; i<size; i++)
     printf("(%lf %lf) ", *(copyb+2*i), *(copyb+2*i+1));
   printf("\n");
   */
   if (info > 0)
     {
       // ERROR("according to zgesv, matrix is singular");
       ret = false;
     }
   else if (info < 0)
     {
       ERROR("argument passed to zgesv had an illegal value");
       ret = false;
     }
   freemem(permutation);
   return ret;
 }
References ERROR(), freemem(), newarray_atomic, x, and zgesv_().
Referenced by PathTracker::refine(), and PathTracker::track().