Macaulay2 Engine: norm_of_inverse_via_svd
norm_of_inverse_via_svd()
bool norm_of_inverse_via_svd (int size, complex * A, double & norm)
Definition at line 1339 of file NAG.cpp.
 {
   bool ret = true;
   char doit = 'A';  // other options are 'S' and 'O' for singular vectors only
   int rows = size;
   int cols = size;
   int info;
   int min = (rows <= cols) ? rows : cols;
   if (min == 0)
     {
       ERROR("expected a matrix with positive dimensions");
       return false;
     }
   int max = (rows >= cols) ? rows : cols;
   int wsize = 4 * min + 2 * max;
   double* workspace = newarray_atomic(double, 2 * wsize);
   double* rwork = newarray_atomic(double, 5 * max);
   double* copyA = (double*)A;
   double* u = newarray_atomic(double, 2 * rows * rows);
   double* vt = newarray_atomic(double, 2 * cols * cols);
   double* sigma = newarray_atomic(double, 2 * min);
   zgesvd_(&doit,
           &doit,
           &rows,
           &cols,
           copyA,
           &rows,
           sigma,
           u,
           &rows,
           vt,
           &cols,
           workspace,
           &wsize,
           rwork,
           &info);
   if (info < 0)
     {
       ERROR("argument passed to zgesvd had an illegal value");
       ret = false;
     }
   else if (info > 0)
     {
       ERROR("zgesvd did not converge");
       ret = false;
     }
   else
     {
       if (sigma[size - 1] == 0)
         {
           ERROR("invertible matrix expected");
           ret = false;
         }
       norm = 1 / sigma[size - 1];
     }
   freemem(workspace);
   freemem(rwork);
   // freemem(copyA);
   freemem(u);
   freemem(vt);
   freemem(sigma);
   return ret;
 }
References ERROR(), freemem(), max, mpfr::min(), newarray_atomic, and zgesvd_().
Referenced by PathTracker::track().