Macaulay2 Engine: degree_ring_elem
degree_ring_elem()
int degree_ring_elem (const PolyRing * R, ring_elem re)
Definition at line 2196 of file NAG.cpp.
 {
   RingElement* RE = RingElement::make_raw(R, re);
   M2_arrayint d_array = RE->multi_degree();
   delete RE;
   return d_array->array[0];
 }
References RingElement::make_raw(), RingElement::multi_degree(), and FreeModule::R.
Referenced by PathTracker::make().