Macaulay2 Engine: ReducedGB_ZZ::find_divisor
find_divisor()
enum ReducedGB_ZZ::divisor_type ReducedGB_ZZ::find_divisor (exponents_t exp, int comp, int & result_loc) private
Definition at line 52 of file reducedgb-ZZ.cpp.
 {
   int w = T->find_smallest_coeff_divisor(exp, comp);  // gives smallest coeff
   int r = -1;
   if (ringtableZZ) r = ringtableZZ->find_smallest_coeff_divisor(exp, 1);
   if (r < 0)
     {
       if (w < 0) return DIVISOR_NONE;
       result_loc = w;
       return DIVISOR_MODULE;
     }
   // r >= 0
   if (w < 0)
     {
       result_loc = r;
       return DIVISOR_RING;
     }
   // r >= 0, w >= 0
   mpz_srcptr rc = originalR->quotient_gbvector(r)->coeff.get_mpz();
   mpz_srcptr wc = polys[w].f->coeff.get_mpz();
   if (mpz_cmpabs(rc, wc) > 0)
     {
       result_loc = w;
       return DIVISOR_MODULE;
     }
   result_loc = r;
   return DIVISOR_RING;
 }
References gbvector::coeff, gbvector::comp, GBRing::exponents_delete(), GBRing::exponents_make(), POLY::f, ReducedGB::F, MonomialTableZZ::find_term_divisors(), POLY::fsyz, GBRing::gbvector_copy(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_mult_by_coeff_to(), ring_elem::get_mpz(), globalZZ, MonomialTableZZ::insert(), INTSIZE, Ring::minus_one(), ReducedGB::polys, ReducedGB::R, remainder(), ringtableZZ, T, and VECTOR().
Referenced by remainder().