Macaulay2 Engine: ReducedGB_ZZ::remainder
remainder() [1/2]
void ReducedGB_ZZ::remainder (gbvector *& f, bool use_denom, ring_elem & denom) virtual
Implements ReducedGB.
Definition at line 177 of file reducedgb-ZZ.cpp.
 {
   gbvector *zero = nullptr;
   gbvector head;
   gbvector *frem = &head;
   frem->next = nullptr;
   gbvector *h = f;
   exponents_t EXP = ALLOCATE_EXPONENTS(R->exponent_byte_size());
   gbvector *r;
   POLY g;
   while (!R->gbvector_is_zero(h))
     {
       int w;
       R->gbvector_get_lead_exponents(F, h, EXP);
       int x = h->comp;
       enum divisor_type typ = find_divisor(EXP, x, w);
       switch (typ)
         {
           case DIVISOR_RING:
             r = const_cast<gbvector *>(originalR->quotient_gbvector(w));
             if (R->gbvector_reduce_lead_term_ZZ(F, Fsyz, h, zero, r, zero))
               continue;
             break;
           case DIVISOR_MODULE:
             g = polys[w];
             if (M2_gbTrace >= 4)
               {
                 buffer o;
                 R->gbvector_text_out(o, F, h);
                 o << newline << "  divisor " << w << " is ";
                 R->gbvector_text_out(o, F, g.f);
                 o << newline;
                 emit(o.str());
               }
             if (R->gbvector_reduce_lead_term_ZZ(F, Fsyz, h, zero, g.f, zero))
               continue;
             break;
           case DIVISOR_NONE:
             break;
         }
       frem->next = h;
       frem = frem->next;
       h = h->next;
       frem->next = nullptr;
     }
   h = head.next;
   f = h;
 }
References ALLOCATE_EXPONENTS, gbvector::comp, DIVISOR_MODULE, DIVISOR_NONE, DIVISOR_RING, emit(), GBRing::exponent_byte_size(), POLY::f, ReducedGB::F, find_divisor(), ReducedGB::Fsyz, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), GBRing::gbvector_reduce_lead_term_ZZ(), GBRing::gbvector_text_out(), M2_gbTrace, newline, gbvector::next, ReducedGB::originalR, ReducedGB::polys, PolynomialRing::quotient_gbvector(), ReducedGB::R, buffer::str(), x, and zero.