Macaulay2 Engine: ReducedGB_ZZ::ReducedGB_ZZ
ReducedGB_ZZ()
ReducedGB_ZZ::ReducedGB_ZZ (GBRing * R0, const PolynomialRing * originalR0, const FreeModule * F0, const FreeModule * Fsyz0) private
Definition at line 14 of file reducedgb-ZZ.cpp.
     : ReducedGB(R0, originalR0, F0, Fsyz0),
       T(nullptr),
       ringtableZZ(nullptr)
 {
   T = MonomialTableZZ::make(R0->n_vars());
   if (originalR->is_quotient_ring())
     ringtableZZ = originalR->get_quotient_MonomialTableZZ();
 }
References PolynomialRing::get_quotient_MonomialTableZZ(), PolynomialRing::is_quotient_ring(), MonomialTableZZ::make(), GBRing::n_vars(), ReducedGB::originalR, ringtableZZ, and T.