Macaulay2 Engine: ReducedGB_ZZ::remainder
remainder() [2/2]
void ReducedGB_ZZ::remainder (POLY & f, bool use_denom, ring_elem & denom) virtual
Implements ReducedGB.
Definition at line 134 of file reducedgb-ZZ.cpp.
 {
   gbvector *zero = nullptr;
   gbvector head;
   gbvector *frem = &head;
   frem->next = nullptr;
   POLY h = f;
   exponents_t EXP = ALLOCATE_EXPONENTS(R->exponent_byte_size());
   gbvector *r;
   POLY g;
   while (!R->gbvector_is_zero(h.f))
     {
       int w;
       R->gbvector_get_lead_exponents(F, h.f, EXP);
       int x = h.f->comp;
       enum divisor_type typ = find_divisor(EXP, x, w);
       switch (typ)
         {
           case DIVISOR_RING:
             r = const_cast<gbvector *>(originalR->quotient_gbvector(w));
             if (R->gbvector_reduce_lead_term_ZZ(F, Fsyz, h.f, zero, r, zero))
               continue;
             break;
           case DIVISOR_MODULE:
             g = polys[w];
             if (R->gbvector_reduce_lead_term_ZZ(
                     F, Fsyz, h.f, h.fsyz, g.f, g.fsyz))
               continue;
             break;
           case DIVISOR_NONE:
             break;
         }
       frem->next = h.f;
       frem = frem->next;
       h.f = h.f->next;
       frem->next = nullptr;
     }
   h.f = head.next;
   f.f = h.f;
   originalR->get_quotient_info()->gbvector_normal_form(Fsyz, h.fsyz);
   f.fsyz = h.fsyz;
 }
References ALLOCATE_EXPONENTS, gbvector::comp, DIVISOR_MODULE, DIVISOR_NONE, DIVISOR_RING, GBRing::exponent_byte_size(), POLY::f, ReducedGB::F, find_divisor(), POLY::fsyz, ReducedGB::Fsyz, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), QRingInfo::gbvector_normal_form(), GBRing::gbvector_reduce_lead_term_ZZ(), PolynomialRing::get_quotient_info(), gbvector::next, ReducedGB::originalR, ReducedGB::polys, PolynomialRing::quotient_gbvector(), ReducedGB::R, x, and zero.
Referenced by find_divisor().