Macaulay2 Engine: testRingNegateRR
testRingNegateRR()
void testRingNegateRR (const M2::ARingRR & R, int ntrials)
Definition at line 54 of file ARingRRTest.cpp.
 {
   ARingElementGenerator<M2::ARingRR> gen(R);
   M2::ARingRR::ElementType a, b, c;
   R.init(a);
   R.init(b);
   R.init(c);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (-a) + (a) == 0
       gen.nextElement(a);
       R.negate(b, a);
       R.add(c, a, b);
       EXPECT_TRUE(R.is_zero(c));
     }
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References M2::ARingRR::add(), M2::ARingRR::clear(), M2::ARingRR::init(), M2::ARingRR::is_zero(), M2::ARingRR::negate(), ARingElementGenerator< RingType >::nextElement(), and ntrials.
Referenced by TEST().