Macaulay2 Engine: TEST
TEST() [6/7]
TEST (ARingRR , power_and_invert)
Definition at line 227 of file ARingRRTest.cpp.
 {
   M2::ARingRR R;
   auto nbits = R.get_precision();
   ARingElementGenerator<M2::ARingRR> gen(R);
   M2::ARingRR::ElementType a, b, c, d;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(d);
   mpz_t gmp1;
   mpz_init(gmp1);
   for (int i = 0; i < ntrials; i++)
     {
       gen.nextElement(a);
       // TODO: what should the answer here be?
       // EXPECT_TRUE(R->is_equal(R->power(a, 0), R->one())); // 0^0 == 1 too?
       R.power(b, a, 1);
       EXPECT_TRUE(R.is_equal(b, a));
       int e1 = rawRandomInt(10) + 1;
       int e2 = rawRandomInt(10) + 1;
       R.power(b, a, e1);
       R.power(c, a, e2);
       R.power(d, a, e1 + e2);
       R.mult(c, b, c);
       EXPECT_TRUE(almostEqual(R, nbits - 4, c, d));
       // Make sure that powers via mpz work (at least for small exponents)
       mpz_set_si(gmp1, e1);
       R.power_mpz(d, a, gmp1);
       EXPECT_TRUE(R.is_equal(d, b));
     }
   mpz_clear(gmp1);
   R.clear(d);
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References almostEqual(), M2::ARingRR::clear(), M2::ARingRR::get_precision(), M2::ARingRR::init(), M2::ARingRR::is_equal(), M2::ARingRR::mult(), ARingElementGenerator< RingType >::nextElement(), ntrials, M2::ARingRR::power(), M2::ARingRR::power_mpz(), and rawRandomInt().