Macaulay2 Engine: almostEqual
almostEqual()
bool almostEqual (const M2::ARingRR & R, unsigned long nbits, const M2::ARingRR::ElementType & a, const M2::ARingRR::ElementType & b)
Definition at line 14 of file ARingRRTest.cpp.
{
  M2::ARingRR::ElementType epsilon = pow(2, static_cast<double>(-nbits));
  M2::ARingRR::ElementType c;
  R.subtract(c, a, b);
  // std::cout << "a = " << a << ", b = " << b << ", c = " << c << ", a-b = " <<
  // a-b;
  R.abs(c, c);
  // std::cout << ", |c| = " << c << ", epsilon = " << epsilon  << std::endl;
  return R.compare_elems(c, epsilon) < 0;
}
References M2::ARingRR::abs(), M2::ARingRR::compare_elems(), and M2::ARingRR::subtract().
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().