Macaulay2 Engine: TEST
TEST() [7/7]
TEST (ARingRR , subtract)
Definition at line 107 of file ARingRRTest.cpp.
 {
   M2::ARingRR R;
   auto nbits = R.get_precision();
   ARingElementGenerator<M2::ARingRR> gen(R);
   M2::ARingRR::ElementType a, b, c, e;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(e);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (a-b) + (b) == a
       gen.nextElement(a);
       gen.nextElement(b);
       R.subtract(c, a, b);
       R.add(e, c, b);  // should be a
       EXPECT_TRUE(almostEqual(R, nbits - 2, a, e));
       R.mult(e, a, b);
       // std::cout << e-a*b << " " << e << " " << a << " " << b << std::endl;
       R.subtract_multiple(e, a, b);
       // EXPECT_TRUE(R.is_zero(e)); // this is not necessarily zero (it is with
       // MPFR)
       EXPECT_TRUE(almostEqual(R, nbits - 2, e, 0));
     }
   R.clear(e);
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References M2::ARingRR::add(), almostEqual(), M2::ARingRR::clear(), M2::ARingRR::get_precision(), M2::ARingRR::init(), M2::ARingRR::mult(), ARingElementGenerator< RingType >::nextElement(), ntrials, M2::ARingRR::subtract(), and M2::ARingRR::subtract_multiple().