Macaulay2 Engine: TEST
TEST() [4/7]
TEST (ARingRR , multDivide)
Definition at line 138 of file ARingRRTest.cpp.
 {
   std::cout.precision(30);
   M2::ARingRR R;
   auto nbits = R.get_precision();
   ARingElementGenerator<M2::ARingRR> gen(R);
   M2::ARingRR::ElementType a, b, c, d;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(d);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (a*b) // b == a
       gen.nextElement(a);
       gen.nextElement(b);
       R.mult(c, a, b);
       if (R.is_zero(b))
         EXPECT_TRUE(R.is_zero(c));
       else
         {
           R.divide(d, c, b);
           // std::cout << a << " " << b << " " << c << " " << d << " " << d-a <<
           // std::endl;
           EXPECT_TRUE(almostEqual(R, nbits - 2, d, a));
         }
     }
   R.clear(d);
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References almostEqual(), M2::ARingRR::clear(), M2::ARingRR::divide(), M2::ARingRR::get_precision(), M2::ARingRR::init(), M2::ARingRR::is_zero(), M2::ARingRR::mult(), ARingElementGenerator< RingType >::nextElement(), and ntrials.