Macaulay2 Engine: testRingSubtract
testRingSubtract()
template<typename T > void testRingSubtract (const T * R, int ntrials)
Definition at line 88 of file RingTest.hpp.
{
  RingElementGenerator<T> gen(*R);
  for (int i = 0; i < ntrials; i++)
    {
      // test: (a-b) + (b) == a
      ring_elem a = gen.nextElement();
      ring_elem b = gen.nextElement();
      ring_elem c = R->subtract(a, b);
      ring_elem e = R->add(c, b);
      EXPECT_TRUE(R->is_equal(e, a));
    }
}
References RingElementGenerator< RingType >::nextElement(), and ntrials.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().