Macaulay2 Engine: testRingSyzygy
testRingSyzygy()
template<typename T > void testRingSyzygy (const T * R, int ntrials)
Definition at line 235 of file RingTest.hpp.
{
  RingElementGenerator<T> gen(*R);
  for (int i = 0; i < ntrials; i++)
    {
      ring_elem u, v;
      ring_elem a = gen.nextElement();
      ring_elem b = gen.nextElement();
      if (R->is_zero(b)) continue;
      // special cases (note: b != 0 for rest of routine)
      // syzygy(0,b) returns (1,0)
      R->syzygy(R->zero(), b, u, v);
      EXPECT_TRUE(R->is_equal(u, R->one()));
      EXPECT_TRUE(R->is_equal(v, R->zero()));
      // syzygy(a,1) returns (1,-a)
      R->syzygy(a, R->one(), u, v);
      EXPECT_TRUE(R->is_equal(u, R->one()));
      EXPECT_TRUE(R->is_equal(v, R->negate(a)));
      // syzygy(a,-1) returns (1,a)
      R->syzygy(a, R->minus_one(), u, v);
      EXPECT_TRUE(R->is_equal(u, R->one()));
      EXPECT_TRUE(R->is_equal(v, a));
      R->syzygy(a, b, u, v);
      ring_elem result = R->add(R->mult(a, u), R->mult(b, v));
#if 0
      buffer o;
      o << "a=";
      R->elem_text_out(o,a);
      o << " b=";
      R->elem_text_out(o,b);
      o << " u=";
      R->elem_text_out(o,u);
      o << " v=";
      R->elem_text_out(o,v);
      std::cout << o.str() << std::endl;
#endif
      EXPECT_TRUE(R->is_zero(result));
    }
  // over ZZ:
  // syzygy(a,b) returns (b/c, -a/c), where c = +- gcd(a,b), with same sign as b
}
References RingElementGenerator< RingType >::nextElement(), ntrials, and buffer::str().
Referenced by TEST(), TEST(), TEST(), and TEST().