Macaulay2 Engine: testRingDivide
testRingDivide()
template<typename T > void testRingDivide (const T * R, int ntrials)
Definition at line 102 of file RingTest.hpp.
{
  auto zero = R->zero();
  auto a = R->from_long(3);
  EXPECT_ANY_THROW(R->divide(a, zero));
  RingElementGenerator<T> gen(*R);
  for (int i = 0; i < ntrials; i++)
    {
      // test: (a*b) // b == a
      ring_elem a = gen.nextElement();
      ring_elem b = gen.nextElement();
      ring_elem c = R->mult(a, b);
      if (R->is_zero(b))
        EXPECT_TRUE(R->is_zero(c));
      else
        {
          ring_elem d = R->divide(c, b);
          EXPECT_TRUE(R->is_equal(d, a));
        }
    }
}
References RingElementGenerator< RingType >::nextElement(), ntrials, and zero.
Referenced by TEST(), TEST(), TEST(), and TEST().