Macaulay2 Engine: M2::ARingGFFlintBig::syzygy
syzygy()
void M2::ARingGFFlintBig::syzygy (const ElementType & a, const ElementType & b, ElementType & x, ElementType & y) const inline
Definition at line 345 of file aring-gf-flint-big.hpp.
   {
     assert(not is_zero(a));
     assert(not is_zero(b));
     set_from_long(x, 1);
     divide(y, a, b);
     negate(y, y);
   }
References divide(), is_zero(), negate(), set_from_long(), and x.