Macaulay2 Engine: M2::ARingGFFlintBig::elem_text_out
elem_text_out()
void M2::ARingGFFlintBig::elem_text_out (buffer & o, const ElementType & a, bool p_one = true, bool p_plus = false, bool p_parens = false) const
Definition at line 182 of file aring-gf-flint-big.cpp.
 {
   if (is_zero(a))
     {
       o << "0";
       return;
     }
   ring_elem b;
   lift(&originalRing(), a, b);
   originalRing().elem_text_out(o, b, p_one, p_plus, p_parens);
 }
References Ring::elem_text_out(), is_zero(), lift(), and originalRing().