Macaulay2 Engine: M2::ARingGFFlintBig::set_from_long
set_from_long()
void M2::ARingGFFlintBig::set_from_long (ElementType & result, long a) const inline
Definition at line 193 of file aring-gf-flint-big.hpp.
   {
     long a1 = a % characteristic();
     if (a1 < 0) a1 += characteristic();
     fq_nmod_set_ui(&result, a1, mContext);
   }
References characteristic(), and mContext.
Referenced by set_from_mpz(), set_var(), and syzygy().