Macaulay2 Engine: M2::ARingGFFlintBig::power_mpz
power_mpz()
void M2::ARingGFFlintBig::power_mpz (ElementType & result, const ElementType & a, mpz_srcptr n) const inline
Definition at line 311 of file aring-gf-flint-big.hpp.
   {
     if (mpz_sgn(n) < 0 and is_zero(a))
       throw exc::division_by_zero_error();
     ElementType base;
     init(base);
     if (mpz_sgn(n) < 0)
       invert(base, a);
     else
       copy(base, a);
     mpz_t abs_n;
     mpz_init(abs_n);
     mpz_abs(abs_n, n);
     fmpz_t fn;
     fmpz_init_set_readonly(fn, abs_n);
     fq_nmod_pow(&result, &base, fn, mContext);
     fmpz_clear_readonly(fn);
     mpz_clear(abs_n);
     clear(base);
   }
References base, clear(), copy(), init(), invert(), is_zero(), and mContext.