Macaulay2 Engine: M2::ARingGFFlintBig::copy
copy()
void M2::ARingGFFlintBig::copy (ElementType & result, const ElementType & a) const inline
Definition at line 123 of file aring-gf-flint-big.hpp.
   {
     fq_nmod_set(&result, &a, mContext);
   }
References mContext.
Referenced by from_ring_elem(), getGenerator(), init_set(), power_mpz(), set(), and to_ring_elem().