Macaulay2 Engine: M2::ARingGFFlintBig::to_ring_elem
to_ring_elem()
void M2::ARingGFFlintBig::to_ring_elem (ring_elem & result, const ElementType & a) const inline
Definition at line 92 of file aring-gf-flint-big.hpp.
   {
     ElementType* b = getmemstructtype(ElementType*);
     init(*b);
     copy(*b, a);
     size_t coeffs_size = sizeof(mp_limb_t)*b->alloc;
     mp_ptr coeffs = reinterpret_cast<mp_ptr>(getmem_atomic(coeffs_size));
     memcpy(coeffs,b->coeffs,coeffs_size);
     flint_free(b->coeffs);
     b->coeffs = coeffs;
     result.poly_val = reinterpret_cast<Nterm*>(b);
   }
References copy(), getmem_atomic(), getmemstructtype, init(), and ring_elem::poly_val.