Macaulay2 Engine: M2::ARingGFFlintBig::init_set
init_set()
void M2::ARingGFFlintBig::init_set (ElementType & result, const ElementType & a) const inline
Definition at line 186 of file aring-gf-flint-big.hpp.
   {
     init(result);
     copy(result, a);
   }
References copy(), and init().
Referenced by M2::ARingGFFlintBig::Element::Element().