Macaulay2 Engine: M2::ARingGFFlintBig::set_from_mpz
set_from_mpz()
void M2::ARingGFFlintBig::set_from_mpz (ElementType & result, mpz_srcptr a) const inline
Definition at line 207 of file aring-gf-flint-big.hpp.
   {
     int b = static_cast<int>(mpz_fdiv_ui(a, characteristic()));
     set_from_long(result, b);
   }
References characteristic(), and set_from_long().
Referenced by set_from_mpq().