Macaulay2 Engine: M2::ARingGFFlintBig::subtract_multiple
subtract_multiple()
void M2::ARingGFFlintBig::subtract_multiple (ElementType & result, const ElementType & a, const ElementType & b) const inline
Definition at line 253 of file aring-gf-flint-big.hpp.
   {
     ElementType c;
     init(c);
     mult(c, a, b);
     subtract(result, result, c);
     clear(c);
   }
References clear(), init(), mult(), and subtract().