Macaulay2 Engine: M2::ARingGFFlintBig::fromSmallIntegerCoefficients
fromSmallIntegerCoefficients()
void M2::ARingGFFlintBig::fromSmallIntegerCoefficients (ElementType & result, const std::vector< long > & poly) const
Definition at line 82 of file aring-gf-flint-big.cpp.
{
#if 0
    printf("input = ");
    for (long i=0; i<poly.size(); i++)
      printf("%ld ", poly[i]);
    printf("\n");
#endif
  for (long i = poly.size() - 1; i >= 0; i--)
    {
      long a = poly[i];
      if (a == 0) continue;
      if (a < 0) a += characteristic();
      nmod_poly_set_coeff_ui(&result, i, a);
    }
#if 0
    printf("  result before reduction = ");
    fq_nmod_print_pretty(&result, mContext);
    printf("\n");
#endif
  fq_nmod_reduce(&result, mContext);
#if 0
    printf("  result = ");
    fq_nmod_print_pretty(&result, mContext);
    printf("\n");
#endif
}
References characteristic(), and mContext.
Referenced by promote(), and set_var().