Macaulay2 Engine: M2::ARingGFFlintBig::characteristic
characteristic()
long M2::ARingGFFlintBig::characteristic () const inline
Definition at line 109 of file aring-gf-flint-big.hpp.
 { return mCharacteristic; }
References mCharacteristic.
Referenced by ARingGFFlintBig(), fromSmallIntegerCoefficients(), set_from_long(), set_from_mpz(), and text_out().