Macaulay2 Engine: M2::ARingGFFlintBig::divide
divide()
void M2::ARingGFFlintBig::divide (ElementType & result, const ElementType & a, const ElementType & b) const inline
Definition at line 213 of file aring-gf-flint-big.hpp.
   {
     // We need to handle the case when result is a, or b.
     // This is why we use the temporary value 'c'.
     ElementType c;
     init(c);
 #if 0
       printf("entering divide\n");
       printf("  a = ");
       fq_nmod_print_pretty(&a, mContext);
       printf("\n  b = ");
       fq_nmod_print_pretty(&b, mContext);
 #endif
     invert(c, b);
 #if 0
       printf("\n  1/b = ");
       fq_nmod_print_pretty(&c, mContext);
 #endif
     mult(result, c, a);
 #if 0
       printf("\n  a/b = ");
       fq_nmod_print_pretty(&result, mContext);
       printf("\n");
 #endif
     clear(c);
   }
References clear(), init(), invert(), mContext, and mult().
Referenced by set_from_mpq(), and syzygy().