Macaulay2 Engine: M2::ARingGFFlintBig::eval
eval()
void M2::ARingGFFlintBig::eval (const RingMap * map, const ElementType & f, int first_var, ring_elem & result) const
Definition at line 154 of file aring-gf-flint-big.cpp.
 {
   const Ring* R = map->get_ring();  // the target ring
   result = R->from_long(0);
   if (is_zero(f)) return;
   ring_elem a = map->elem(first_var);
   std::vector<long> poly;
   getSmallIntegerCoefficients(f, poly);
   for (long i = poly.size() - 1; i >= 0; i--)
     {
       if (!R->is_zero(result)) result = R->mult(a, result);
       if (poly[i] != 0)
         {
           ring_elem c = R->from_long(poly[i]);
           result = R->add(result, c);
         }
     }
 }
References Ring::add(), RingMap::elem(), Ring::from_long(), RingMap::get_ring(), getSmallIntegerCoefficients(), is_zero(), Ring::is_zero(), and Ring::mult().