Macaulay2 Engine: M2::ARingGFFlintBig::set_from_mpq
set_from_mpq()
bool M2::ARingGFFlintBig::set_from_mpq (ElementType & result, mpq_srcptr a) const inline
Definition at line 214 of file aring-gf-flint-big.hpp.
   {
     ElementType n, d;
     init(n);
     init(d);
     set_from_mpz(n, mpq_numref(a));
     set_from_mpz(d, mpq_denref(a));
     if (is_zero(d)) return false;
     divide(result, n, d);
     return true;
   }
References divide(), init(), is_zero(), and set_from_mpz().