Macaulay2 Engine: M2::ARingGFFlintBig::flintContext
flintContext()
const fq_nmod_ctx_struct* M2::ARingGFFlintBig::flintContext () const inline
Definition at line 108 of file aring-gf-flint-big.hpp.
 { return mContext; }
References mContext.
Referenced by MatrixOps::addMultipleTo(), MatrixOps::mult(), MatrixOps::rowReducedEchelonForm(), and MatrixOps::subtractMultipleTo().