Macaulay2 Engine: newf4::toMatrix
toMatrix()
const Matrix* newf4::toMatrix (const FreeModule * target, const PolynomialList & Fs) inline
Definition at line 101 of file GBF4Interface.hpp.
 {
   MatrixStream S(target);
   toStream(Fs, S);
   return S.value();
 }
References toStream(), and MatrixStream::value().
Referenced by newf4::GBF4Computation::showInput().