Macaulay2 Engine: newf4::toStream
toStream()
template<typename S > void newf4::toStream (const PolynomialList & Fs, S & str)
Definition at line 262 of file PolynomialList.hpp.
 {
   str.idealBegin(Fs.size());
   for (auto i=0; i<Fs.size(); ++i)
     {
       auto& F = Fs[i];
       str.appendPolynomialBegin(F.mMonomials.size());
       for (auto i=0; i<F.mMonomials.size(); ++i)
         {
           // get monomial
           // write it out here using appendTermBegin, appendExponent, appendTermDone.
           if (F.mComponents.empty())
             str.appendTermBegin(0);
           else
             str.appendTermBegin(F.mComponents[i]);
           MonomialView monom = Fs.monomialHashTable().monomialAt(F.mMonomials[i]);
           for (auto ve = monom.begin(); ve != monom.end(); ++ve)
             {
               str.appendExponent(ve.var(), ve.power());
             }
           long val = Fs.vectorArithmetic().to_modp_long(F.mCoefficients, i);
           str.appendTermDone(val);
         }
       str.appendPolynomialDone();
     }
   str.idealDone();
 }
References newf4::MonomialView::begin(), newf4::MonomialView::end(), newf4::MonomialHashTable::monomialAt(), newf4::PolynomialList::monomialHashTable(), newf4::PolynomialList::size(), VectorArithmetic::to_modp_long(), and newf4::PolynomialList::vectorArithmetic().
Referenced by newf4::GBF4Computation::initializeWithBasicPolyList(), and toMatrix().