Macaulay2 Engine: system_interrupted
system_interrupted()
bool system_interrupted ()
Definition at line 6 of file interrupted.cpp.
 { return interrupted(); }
References interrupted.
Referenced by NCBasis::basis0(), KBasis::basis0_full(), KBasis::basis0_multi_graded(), KBasis::basis0_singly_graded(), FF_LUComputation::calc(), DetComputation::calc(), hilb_comp::calc(), PfaffianComputation::calc(), MGBCallback::call(), KBasis::compute(), gbA::do_computation(), LLLoperations::doLLL(), M2::GaloisFieldTable::GaloisFieldTable(), GF::initialize_GF(), KBasis::k_basis(), DetComputation::make_dynamic_cache(), GaussElimComputation::start_computation(), GB_comp::start_computation(), GBinhom_comp::start_computation(), and binomialGB_comp::start_computation().