Macaulay2 Engine: DMatLinAlg::solveInvertible
solveInvertible()
template<class RingType > bool DMatLinAlg< RingType >::solveInvertible (const Mat & B, Mat & X)
Input: B, a matrix, the right hand side of AX=B A, a square matrix (presumed to be invertible) Output: X, a matrix, solution to the above, if A is invertible returns false iff A is not invertible
Definition at line 499 of file dmat-lu.hpp.
 {
   // printf("in dmat-lu solveInvertible\n");
   // possible TODO: incorporate a faster method if we know matrix is
   // invertible...
   assert(mLUObject.numRows() == mLUObject.numColumns());
   assert(mLUObject.numRows() == B.numRows());
   X.resize(mLUObject.numColumns(), B.numColumns());
   mLUObject.LUinPlace();
   if (rank() < mLUObject.numRows()) return false;
   solve(B, X);
   return true;
 #if 0
   // The following code doesn't really seem to be any faster than the naive code we have
   // at least for sizes less than a few thousand rows/columns.
   Mat B1(ring(), LU.numRows(), LU.numRows()); // square matrix
   printf("in dmat-lu solveInvertible step 3\n");
   permuteRows<Mat>(B, mLUObject.permutation(), B1);
   printf("in dmat-lu solveInvertible step 4\n");
   solveLowerTriangular(LU, B, X);
   printf("in dmat-lu solveInvertible step 5\n");
   solveUpperTriangular(LU, X, X);
   printf("in dmat-lu solveInvertible step 6\n");
   return true;
 #endif
 }
References MatrixOps::LU(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), ffpackInterface::rank(), DMat< ACoeffRing >::resize(), solveLowerTriangular(), and solveUpperTriangular().
Referenced by MatrixOps::solveInvertible().