var searchData=
[
  ['s_5fpair_6532',['s_pair',['../d8/d45/structs__pair.html',1,'']]],
  ['s_5fpair_5fdegree_5flist_6533',['s_pair_degree_list',['../d2/d2f/structbinomial__s__pair__set_1_1s__pair__degree__list.html',1,'binomial_s_pair_set']]],
  ['s_5fpair_5felem_6534',['s_pair_elem',['../d8/db2/structbinomial__s__pair__set_1_1s__pair__elem.html',1,'binomial_s_pair_set']]],
  ['s_5fpair_5fheap_6535',['s_pair_heap',['../db/d49/classs__pair__heap.html',1,'']]],
  ['s_5fpair_5flcm_5flist_6536',['s_pair_lcm_list',['../d0/d2a/structbinomial__s__pair__set_1_1s__pair__lcm__list.html',1,'binomial_s_pair_set']]],
  ['sagbi_6537',['sagbi',['../dc/d5a/classsagbi.html',1,'']]],
  ['schreyerframe_6538',['SchreyerFrame',['../dd/d1a/class_schreyer_frame.html',1,'']]],
  ['schreyerorder_6539',['SchreyerOrder',['../d4/d92/class_schreyer_order.html',1,'']]],
  ['schreyerorder_5fsymm_6540',['SchreyerOrder_symm',['../dc/d2a/struct_schreyer_order__symm.html',1,'']]],
  ['schur_5fpoly_6541',['schur_poly',['../d9/d25/classschur__poly.html',1,'']]],
  ['schur_5fpoly_5fheap_6542',['schur_poly_heap',['../d7/d0c/classschur__poly__heap.html',1,'']]],
  ['schur_5fpoly_5fiterator_6543',['schur_poly_iterator',['../d7/d11/classschur__poly__iterator.html',1,'']]],
  ['schurring_6544',['SchurRing',['../dd/ddb/class_schur_ring.html',1,'']]],
  ['schurring2_6545',['SchurRing2',['../df/da2/class_schur_ring2.html',1,'']]],
  ['schursnring_6546',['SchurSnRing',['../d7/d6f/class_schur_sn_ring.html',1,'']]],
  ['settingsmanager_6547',['SettingsManager',['../dd/dbf/class_b_i_basis_1_1_settings_manager.html',1,'BIBasis']]],
  ['simplearing_6548',['SimpleARing',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringcc_20_3e_6549',['SimpleARing&lt; ARingCC &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringccc_20_3e_6550',['SimpleARing&lt; ARingCCC &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringgfm2_20_3e_6551',['SimpleARing&lt; ARingGFM2 &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringqqflint_20_3e_6552',['SimpleARing&lt; ARingQQFlint &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringqqgmp_20_3e_6553',['SimpleARing&lt; ARingQQGMP &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringrr_20_3e_6554',['SimpleARing&lt; ARingRR &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringrri_20_3e_6555',['SimpleARing&lt; ARingRRi &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringrrr_20_3e_6556',['SimpleARing&lt; ARingRRR &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringzz_20_3e_6557',['SimpleARing&lt; ARingZZ &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringzzgmp_20_3e_6558',['SimpleARing&lt; ARingZZGMP &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringzzp_20_3e_6559',['SimpleARing&lt; ARingZZp &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringzzpffpack_20_3e_6560',['SimpleARing&lt; ARingZZpFFPACK &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20aringzzpflint_20_3e_6561',['SimpleARing&lt; ARingZZpFlint &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20coefficientringzzp_20_3e_6562',['SimpleARing&lt; CoefficientRingZZp &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['simplearing_3c_20dummyring_20_3e_6563',['SimpleARing&lt; DummyRing &gt;',['../de/db5/class_m2_1_1_simple_a_ring.html',1,'M2']]],
  ['skewmultiplication_6564',['SkewMultiplication',['../d0/d29/class_skew_multiplication.html',1,'']]],
  ['skewpolynomialring_6565',['SkewPolynomialRing',['../dc/d98/class_skew_polynomial_ring.html',1,'']]],
  ['slab_6566',['slab',['../d0/dc6/struct_f4_memory_block_1_1slab.html',1,'F4MemoryBlock&lt; T, NSLAB &gt;::slab'],['../d3/d86/struct_res_memory_block_1_1slab.html',1,'ResMemoryBlock&lt; T, NSLAB &gt;::slab'],['../dc/d02/classslab.html',1,'slab']]],
  ['slevaluator_6567',['SLEvaluator',['../d0/d4e/class_s_l_evaluator.html',1,'']]],
  ['slevaluatorconcrete_6568',['SLEvaluatorConcrete',['../d2/dbe/class_s_l_evaluator_concrete.html',1,'']]],
  ['slp_6569',['SLP',['../da/d22/class_s_l_p.html',1,'']]],
  ['slp_3c_20complexfield_20_3e_6570',['SLP&lt; ComplexField &gt;',['../da/d22/class_s_l_p.html',1,'']]],
  ['slprogram_6571',['SLProgram',['../d3/dd3/class_s_l_program.html',1,'']]],
  ['smat_6572',['SMat',['../da/de0/class_s_mat.html',1,'']]],
  ['smat_3c_20coeffring_20_3e_6573',['SMat&lt; CoeffRing &gt;',['../da/de0/class_s_mat.html',1,'']]],
  ['solution_6574',['Solution',['../da/dc2/struct_solution.html',1,'']]],
  ['solvablealgebra_6575',['SolvableAlgebra',['../db/daa/class_solvable_algebra.html',1,'']]],
  ['sorter_6576',['sorter',['../df/d8a/structsorter.html',1,'']]],
  ['spair_6577',['spair',['../df/deb/structgb_a_1_1spair.html',1,'gbA']]],
  ['spair_6578',['SPair',['../db/dd1/structnewf4_1_1_s_pair.html',1,'newf4']]],
  ['spair_6579',['spair',['../d5/dc0/structspair.html',1,'']]],
  ['spairiterator_6580',['SPairIterator',['../d8/d27/classnewf4_1_1_s_pair_set_1_1_s_pair_iterator.html',1,'newf4::SPairSet']]],
  ['spairset_6581',['SPairSet',['../d9/dad/structgb_a_1_1_s_pair_set.html',1,'gbA::SPairSet'],['../d2/d40/classnewf4_1_1_s_pair_set.html',1,'newf4::SPairSet']]],
  ['sparse_5frow_6582',['sparse_row',['../df/d30/structsparse__row.html',1,'']]],
  ['sparsevec_6583',['sparsevec',['../d7/d3d/struct_s_mat_1_1sparsevec.html',1,'SMat']]],
  ['spolysorter_6584',['SPolySorter',['../d7/df0/class_s_poly_sorter.html',1,'']]],
  ['stash_6585',['stash',['../d1/d5b/classstash.html',1,'']]],
  ['statsallocator_6586',['StatsAllocator',['../d9/dd2/class_stats_allocator.html',1,'']]],
  ['stopconditions_6587',['StopConditions',['../d6/d5d/struct_stop_conditions.html',1,'']]],
  ['straightlineprogram_6588',['StraightLineProgram',['../d5/df6/class_straight_line_program.html',1,'']]],
  ['submatrix_6589',['SubMatrix',['../d3/da1/struct_sub_matrix.html',1,'']]],
  ['subsets_6590',['Subsets',['../da/d91/class_subsets.html',1,'']]],
  ['suffixtree_6591',['SuffixTree',['../d7/df2/class_suffix_tree.html',1,'']]],
  ['suffixtreenode_6592',['SuffixTreeNode',['../dc/dad/class_suffix_tree_node.html',1,'']]],
  ['sumcollector_6593',['SumCollector',['../da/d60/class_sum_collector.html',1,'']]],
  ['sumcollectordefault_6594',['SumCollectorDefault',['../d0/de7/class_sum_collector_default.html',1,'']]],
  ['sumcollectorfreealgebraheap_6595',['SumCollectorFreeAlgebraHeap',['../d3/d26/class_sum_collector_free_algebra_heap.html',1,'']]],
  ['sumcollectorpolyheap_6596',['SumCollectorPolyHeap',['../d8/d2f/class_sum_collector_poly_heap.html',1,'']]],
  ['symmmatrix_6597',['SymmMatrix',['../db/d15/class_symm_matrix.html',1,'']]]
];
