Macaulay2 Engine: vecHeap::get_lead_term
get_lead_term()
const vecterm * vecHeap::get_lead_term () inline
Definition at line 90 of file geovec.hpp.
 {
   int lead_so_far = -1;
   for (int i = 0; i <= top_of_heap; i++)
     {
       if (heap[i] == NULL) continue;
       if (lead_so_far < 0)
         {
           lead_so_far = i;
           continue;
         }
       int cmp = compare(heap[lead_so_far], heap[i]);
       if (cmp == GT) continue;
       if (cmp == LT)
         {
           lead_so_far = i;
           continue;
         }
       // At this point we have equality
       K->add_to(heap[lead_so_far]->coeff, heap[i]->coeff);
       vecterm *tmp = heap[i];
       heap[i] = tmp->next;
       tmp->next = NULL;
       K->remove_vec(tmp);
       if (K->is_zero(heap[lead_so_far]->coeff))
         {
           // Remove, and start over
           tmp = heap[lead_so_far];
           heap[lead_so_far] = tmp->next;
           tmp->next = NULL;
           K->remove_vec(tmp);
           lead_so_far = -1;
           i = -1;
         }
     }
   mLead = lead_so_far;
   if (lead_so_far < 0) return NULL;
   vecterm *result = heap[lead_so_far];
   return result;
 }
References Ring::add_to(), vec::coeff, compare(), GT, heap, Ring::is_zero(), K, LT, mLead, vec::next, Ring::remove_vec(), and top_of_heap.
Referenced by remove_lead_term().