Macaulay2 Engine: vecHeap::add
add()
void vecHeap::add (vecterm * p) inline
Definition at line 63 of file geovec.hpp.
 {
   mLead = -1;
   int len = K->n_nonzero_terms(p);
   int i = 0;
   while (len >= heap_size[i]) i++;
   K->add_vec_to(heap[i], p);
   len = K->n_nonzero_terms(heap[i]);
   p = NULL;
   while (len >= heap_size[i])
     {
       i++;
       K->add_vec_to(heap[i], heap[i - 1]);
       len = K->n_nonzero_terms(heap[i]);
       heap[i - 1] = NULL;
     }
   if (i > top_of_heap) top_of_heap = i;
 }
References Ring::add_vec_to(), heap, heap_size, K, mLead, Ring::n_nonzero_terms(), p, and top_of_heap.
Referenced by Ring::tensor(), res2_poly::to_vector(), and res_poly::to_vector().