Macaulay2 Engine: vecHeap::value
value()
vecterm * vecHeap::value () inline
Definition at line 142 of file geovec.hpp.
 {
   vecterm *result = NULL;
   for (int i = 0; i <= top_of_heap; i++)
     {
       if (heap[i] == NULL) continue;
       K->add_vec_to(result, heap[i]);
       heap[i] = NULL;
     }
   top_of_heap = -1;
   return result;
 }
References Ring::add_vec_to(), heap, K, and top_of_heap.
Referenced by Ring::tensor(), res2_poly::to_vector(), and res_poly::to_vector().