Macaulay2 Engine: rawDiff
rawDiff()
const RingElement * rawDiff (int v, const RingElement * f)
Definition at line 952 of file ringelement.cpp.
 {
   const Tower *R = f->get_ring()->cast_to_Tower();
   if (R == nullptr)
     {
       ERROR("not implemented for this ring");
       return nullptr;
     }
   return RingElement::make_raw(R, R->differentiate(v, f->get_value()));
 }
References Ring::cast_to_Tower(), Tower::differentiate(), ERROR(), RingElement::get_ring(), RingElement::get_value(), and RingElement::make_raw().