Macaulay2 Engine: convolve
convolve()
void convolve (const PolyRing * R, const VECTOR(ring_elem) & input_relems, VECTOR(ring_elem) & output_relems, int convolve_type)
Definition at line 632 of file ringelement.cpp.
 {
   const Ring *K = R->getCoefficientRing();
   ring_elem invn;
   size_t n =
       input_relems.size() - 1;  // array is 0..n, with the 0 part being ignored.
   // first set [1, e1] := [1, h1].
   output_relems[0] = input_relems[0];
   for (int i = 1; i <= n; i++)
     {
       // ASSUMPTION: input_relems[i] is either a variable or - of a variable
       ring_elem result = R->copy(input_relems[i]);
       if (convolve_type == 2) R->mult_coeff_to(K->from_long(-i), result);
       for (int j = i - 1; j >= 1; --j)
         {
           ring_elem hr;
           Nterm *g = input_relems[j];
           if (g != 0)
             {
               hr.poly_val =
                   R->mult_by_term(output_relems[i - j], g->coeff, g->monom);
               R->internal_add_to(result, hr);
             }
         }
       if (convolve_type == 1)
         {
           invn = K->invert(K->from_long(i));
           R->mult_coeff_to(invn, result);
         }
       output_relems[i] = result;
     }
 }
References Nterm::coeff, PolyRing::copy(), Ring::from_long(), PolynomialRing::getCoefficientRing(), PolyRing::internal_add_to(), Ring::invert(), Nterm::monom, PolyRing::mult_by_term(), PolyRing::mult_coeff_to(), and ring_elem::poly_val.
Referenced by rawConvolve().