Macaulay2 Engine: rawLowerP
rawLowerP()
const RingElement * rawLowerP (const RingElement * f)
Definition at line 963 of file ringelement.cpp.
{
  const Tower *R = f->get_ring()->cast_to_Tower();
  if (R == nullptr)
    {
      ERROR("not implemented for this ring");
      return nullptr;
    }
  return RingElement::make_raw(R, R->lowerP(f->get_value()));
}
References Ring::cast_to_Tower(), ERROR(), RingElement::get_ring(), RingElement::get_value(), and Tower::lowerP().