Macaulay2 Engine: IM2_RingElement_to_rational
IM2_RingElement_to_rational()
gmp_QQorNull IM2_RingElement_to_rational (const RingElement * a)
Definition at line 114 of file ringelement.cpp.
{
  if (!a->get_ring()->is_QQ())
    {
      ERROR("expected an element of QQ");
      return nullptr;
    }
  return a->get_value().get_mpq();
}
References ERROR(), ring_elem::get_mpq(), RingElement::get_ring(), RingElement::get_value(), and Ring::is_QQ().