Macaulay2 Engine: rawGetPart
rawGetPart()
const RingElement * rawGetPart (const M2_arrayint wts, const RingElement * f, M2_bool lobound_given, M2_bool hibound_given, long lobound, long hibound)
Definition at line 721 of file ringelement.cpp.
 {
   try
     {
       const PolynomialRing *P = f->get_ring()->cast_to_PolynomialRing();
       if (P == nullptr)
         {
           ERROR("expected a polynomial");
           return nullptr;
         }
       ring_elem g = P->get_part(M2_arrayint_to_stdvector<int>(wts),
                                 f->get_value(),
                                 lobound_given,
                                 hibound_given,
                                 lobound,
                                 hibound);
       return RingElement::make_raw(P, g);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Ring::cast_to_PolynomialRing(), ERROR(), PolynomialRing::get_part(), RingElement::get_ring(), RingElement::get_value(), and RingElement::make_raw().