Macaulay2 Engine: IM2_RingElement_is_equal
IM2_RingElement_is_equal()
M2_bool IM2_RingElement_is_equal (const RingElement * a, const RingElement * b)
Definition at line 254 of file ringelement.cpp.
 {
   const Ring *R = a->get_ring();
   if (R != b->get_ring()) return 0;
   return R->is_equal(a->get_value(), b->get_value());
 }
References RingElement::get_ring(), RingElement::get_value(), and Ring::is_equal().