Macaulay2 Engine: rawSchurSnTensorMult
rawSchurSnTensorMult()
const RingElement * rawSchurSnTensorMult (const RingElement * a, const RingElement * b)
Definition at line 876 of file ringelement.cpp.
{
  try
    {
      const SchurSnRing *R = a->get_ring()->cast_to_SchurSnRing();
      if (R == nullptr)
        {
          ERROR("expected a SchurSn ring element");
          return nullptr;
        }
      if (R != b->get_ring())
        {
          ERROR("expected SchurSn ring elements");
          return nullptr;
        }
      ring_elem result = R->tensor_mult(a->get_value(), b->get_value());
      return RingElement::make_raw(R, result);
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References Ring::cast_to_SchurSnRing(), ERROR(), RingElement::get_ring(), RingElement::get_value(), and SchurSnRing::tensor_mult().