Macaulay2 Engine: IM2_RingElement_make_var
IM2_RingElement_make_var()
const RingElement * IM2_RingElement_make_var (const Ring * R, int v)
Definition at line 235 of file ringelement.cpp.
{
  try
    {
      ring_elem a = R->var(v);
      if (error()) return nullptr;
      return RingElement::make_raw(R, a);
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References error(), ERROR(), and Ring::var().