Macaulay2 Engine: IM2_RingElement_to_BigReal
IM2_RingElement_to_BigReal()
gmp_RRorNull IM2_RingElement_to_BigReal (const RingElement * a)
Definition at line 124 of file ringelement.cpp.
 {
   const Ring *R = a->get_ring();
   gmp_RRmutable result;
   const M2::ConcreteRing<M2::ARingRRR> *R1;
   switch (R->ringID())
     {
       case M2::ring_RR:
         result = getmemstructtype(gmp_RRmutable);
         mpfr_init2(result, 53);
         mpfr_set_d(result, a->get_value().get_double(), MPFR_RNDN);
         return moveTo_gmpRR(result);
       case M2::ring_RRR:
         R1 =
             dynamic_cast<const M2::ConcreteRing<M2::ARingRRR> *>(a->get_ring());
         result = getmemstructtype(gmp_RRmutable);
         mpfr_init2(result, R1->get_precision());
         mpfr_set(result, a->get_value().get_mpfr(), MPFR_RNDN);
         return moveTo_gmpRR(result);
       default:
         ERROR("expected an element of RRR");
         return nullptr;
     }
 }
References ERROR(), ring_elem::get_double(), ring_elem::get_mpfr(), M2::ConcreteRing< RingType >::get_precision(), RingElement::get_ring(), RingElement::get_value(), getmemstructtype, moveTo_gmpRR(), M2::ring_RR, M2::ring_RRR, and Ring::ringID().