Macaulay2 Engine: rawFactorBase
rawFactorBase()
void rawFactorBase (const RingElement * g, engine_RawRingElementArrayOrNull * result_factors, M2_arrayintOrNull * result_powers, const RingElement * mipo = NULL)
Definition at line 661 of file factory.cpp.
 {
   bool inExtension = mipo != NULL;
   try
     {
       const PolynomialRing *P = g->get_ring()->cast_to_PolynomialRing();
       *result_factors = 0;
       *result_powers = 0;
       if (P == 0)
         {
           ERROR("expected polynomial ring");
           return;
         }
       struct enter_factory foo(P);
       if (foo.mode == modeError) return;
       CFFList q;
       init_seeds();
       if (foo.mode == modeGF)
         {
           inExtension = true;
           Variable a = set_GF_minimal_poly(P);
           CanonicalForm h = convertToFactory(*g, notInExtension);
           q = factorize(h, a);
         }
       else if (mipo != NULL)
         {
           CanonicalForm mipocf = convertToFactory(*mipo, notInExtension);
           Variable a = rootOf(mipocf, 'a');
           algebraicElement_Fac = a;
           CanonicalForm h = convertToFactory(*g, inExtension);
           // displayCF(P,h);
           q = factorize(h, a);
           algebraicElement_M2 = RingElement::make_raw(
               P, P->var(P->n_vars() - 1));  // the algebraic generator is always
                                             // the last variable in M2, the
                                             // first one in factory
         }
       else
         {
           CanonicalForm h = convertToFactory(*g, inExtension);
           // displayCF(P,h);
           q = factorize(h);
           algebraicElement_M2 = NULL;
         }
       int nfactors = q.length();
       *result_factors = getmemarraytype(engine_RawRingElementArray, nfactors);
       (*result_factors)->len = nfactors;
       *result_powers = M2_makearrayint(nfactors);
       int next = 0;
       for (CFFListIterator i = q; i.hasItem(); i++)
         {
           (*result_factors)->array[next] = convertToM2(P, i.getItem().factor());
           (*result_powers)->array[next++] = i.getItem().exp();
         }
       algebraicElement_M2 = NULL;
       if (error()) *result_factors = NULL, *result_powers = NULL;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return;
   }
 }
References algebraicElement_Fac, algebraicElement_M2, Ring::cast_to_PolynomialRing(), convertToFactory(), convertToM2(), error(), ERROR(), RingElement::get_ring(), getmemarraytype, init_seeds(), M2_makearrayint(), RingElement::make_raw(), enter_factory::mode, modeError, modeGF, PolynomialRing::n_vars(), notInExtension, set_GF_minimal_poly(), and PolynomialRing::var().
Referenced by rawFactor(), and rawFactor2().