Macaulay2 Engine: convertToFactory
convertToFactory() [1/2]
static CanonicalForm convertToFactory (const RingElement & g, bool inExtension) static
Definition at line 418 of file factory.cpp.
 {
   const Ring *R = g.get_ring();
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("expected a polynomial ring");
       return 0;
     }
   const int n = P->n_vars();
   const Monoid *M = P->getMonoid();
   gc_vector<int> vp;
   struct enter_factory foo(P);
   if (foo.mode == modeError) return 0;
   CanonicalForm f = 0;
   for (Nterm *t = g.get_value(); t != nullptr; t = t->next)
     {
       int coef = 0;
       M->to_varpower(t->monom, vp);
       if (foo.mode == modeZn)
         {
           std::pair<bool, long> res = foo.Zn->coerceToLongInteger(t->coeff);
           assert(res.first);
           coef = static_cast<int>(res.second);
         }
       CanonicalForm m =
           (foo.mode == modeZn
                ? CanonicalForm(coef)
                : foo.mode == modeGF
                      ? convertGFToFactory(t->coeff, P)
                      : foo.mode == modeZZ
                            ? convertToFactory(t->coeff.get_mpz())
                            : foo.mode == modeQQ
                                  ? (convertToFactory(
                                         mpq_numref(MPQ_VAL(t->coeff))) /
                                     convertToFactory(
                                         mpq_denref(MPQ_VAL(t->coeff))))
                                  : CanonicalForm(0)  // shouldn't happen
            );
       for (index_varpower l = vp.data(); l.valid(); ++l)
         {
           int index = 1 +
 #if REVERSE_VARIABLES
                       (n - 1) -
 #endif
                       l.var();
           m *= power(index == 1 && inExtension ? algebraicElement_Fac
                                                : Variable(index),
                      l.exponent());
         }
       f += m;
     }
   return f;
 }
References algebraicElement_Fac, Ring::cast_to_PolynomialRing(), Ring::coerceToLongInteger(), convertGFToFactory(), convertToFactory(), ERROR(), RingElement::get_ring(), RingElement::get_value(), PolynomialRing::getMonoid(), enter_factory::mode, modeError, modeGF, modeQQ, modeZn, modeZZ, MPQ_VAL, PolynomialRing::n_vars(), Monoid::to_varpower(), ExponentListIterator< E, L >::valid(), and enter_factory::Zn.