Macaulay2 Engine: rawIdealReorder
rawIdealReorder()
M2_arrayintOrNull rawIdealReorder (const Matrix * M)
Definition at line 752 of file factory.cpp.
{
  const bool inExtension = false;
  try
    {
      init_seeds();
      const PolynomialRing *P = M->get_ring()->cast_to_PolynomialRing();
      if (P == nullptr)
        {
          ERROR("expected polynomial ring");
          return nullptr;
        }
      const int N = P->n_vars();
      struct enter_factory foo(P);
      if (foo.mode == modeError) return nullptr;
      if (foo.mode == modeGF)
        {
          ERROR("not implemented yet");
          return nullptr;
        }
      CFList I;
      int i;
      for (i = 0; i < M->n_rows(); i++)
        {
          for (int j = 0; j < M->n_cols(); j++)
            {
              const RingElement *g;
              {
                g = RingElement::make_raw(P, M->elem(i, j));
              }
              I.append(convertToFactory(*g, inExtension));
            }
        }
      if (I.length() == 0) {
        ERROR("expected at least one generator");
        return nullptr;
      }
      List<int> t = neworderint(I);
      int n = t.length();
      gc_vector<int> u(N);
      ListIterator<int> ii(t);
      for (i = 0; ii.hasItem(); ii++, i++)
        u[i] = (n - 1) - (ii.getItem() - 1);  // REVERSE!
      std::reverse(u.begin(), u.begin() + n);
      for (i = n; i < N; i++) u[i] = i;
      return stdvector_to_M2_arrayint<int>(u);
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References Ring::cast_to_PolynomialRing(), convertToFactory(), Matrix::elem(), ERROR(), Matrix::get_ring(), init_seeds(), enter_factory::mode, modeError, modeGF, Matrix::n_cols(), Matrix::n_rows(), and PolynomialRing::n_vars().