Macaulay2 Engine: set_GF_minimal_poly
set_GF_minimal_poly()
static Variable set_GF_minimal_poly (const PolynomialRing * P) static
Definition at line 345 of file factory.cpp.
 {
   assert(P->getCoefficientRing()->isGaloisField());
   const Ring *kk = P->getCoefficientRing();
   assert(kk != 0);
   RingElement F = RingElement(kk, kk->var(0));
   F.promote(P, algebraicElement_M2);  // sets algebraicElement_M2
   Variable a = rootOf(
       convertToFactory(*kk->getMinimalPolynomial(), notInExtension), 'a');
   algebraicElement_Fac = a;
   return a;
 }
References algebraicElement_Fac, algebraicElement_M2, convertToFactory(), PolynomialRing::getCoefficientRing(), Ring::getMinimalPolynomial(), Ring::isGaloisField(), notInExtension, RingElement::promote(), and Ring::var().
Referenced by rawExtendedGCDRingElement(), rawFactorBase(), rawGCDRingElement(), and rawPseudoRemainder().