Macaulay2 Engine: convertToM2
convertToM2()
static const RingElement* convertToM2 (const PolynomialRing * R, CanonicalForm h) static
Definition at line 214 of file factory.cpp.
 {
   // this seems not to handle polynomials with rational coefficients at all!!
   const int n = R->n_vars();
   if (h.inCoeffDomain())
     {
       if (h.inZ())
         {
           mpz_t x = {toInteger(h)};
           ring_elem ret = R->from_int(x);
           mpz_clear(x);
           return RingElement::make_raw(R, ret);
         }
       else if (h.inQ())
         {
           struct enter_factory c;
           __mpq_struct z = {toInteger(h.num()), toInteger(h.den())};
           ring_elem val;
           bool ok = R->from_rational(&z, val);
           if (not ok)
             {
               std::cout << "internal error: unexpected failure to lift "
                            "rational number to ring"
                         << std::endl;
               val = R->from_long(0);
             }
           RingElement *ret = RingElement::make_raw(R, val);
           mpq_clear(&z);
           return ret;
         }
       else if (h.inFF())
         return RingElement::make_raw(R, R->from_long(h.intval()));
       else if (h.inExtension())
         {
           assert(algebraicElement_M2 != NULL);
           ring_elem result = R->from_long(0);
           for (int j = h.taildegree(); j <= h.degree(); j++)
             {
               const RingElement *r = convertToM2(R, h[j]);
               if (error()) return RingElement::make_raw(R, R->one());
               ring_elem r1 = r->get_value();
               ring_elem v = algebraicElement_M2->get_value();
               v = R->power(v, j);
               r1 = R->mult(r1, v);
               R->add_to(result, r1);
             }
           return RingElement::make_raw(R, result);
         }
       else
         {
           ERROR("conversion from factory over unknown type");
           return RingElement::make_raw(R, R->one());
         }
     }
   ring_elem result = R->from_long(0);
   for (int j = h.taildegree(); j <= h.degree(); j++)
     {
       const RingElement *r = convertToM2(R, h[j]);
       if (error()) return RingElement::make_raw(R, R->one());
       ring_elem r1 = r->get_value();
       int var =
 #if REVERSE_VARIABLES
           (n - 1) -
 #endif
           (h.level() - 1);
       ring_elem v = R->var(var);
       v = R->power(v, j);
       r1 = R->mult(r1, v);
       R->add_to(result, r1);
     }
   return RingElement::make_raw(R, result);
 }
References Ring::add_to(), algebraicElement_M2, error(), ERROR(), Ring::from_int(), Ring::from_long(), Ring::from_rational(), RingElement::get_value(), RingElement::make_raw(), Ring::mult(), PolynomialRing::n_vars(), Ring::one(), Ring::power(), toInteger(), PolynomialRing::var(), and x.
Referenced by displayCF(), rawCharSeries(), rawExtendedGCDRingElement(), rawFactorBase(), rawGCDRingElement(), and rawPseudoRemainder().