Macaulay2 Engine: rawExtendedGCDRingElement
rawExtendedGCDRingElement()
const RingElement* rawExtendedGCDRingElement (const RingElement * f, const RingElement * g, const RingElement ** A, const RingElement ** B)
Definition at line 553 of file factory.cpp.
 {
   const bool inExtension = false;
   const RingElement *ret;
   const PolynomialRing *P = f->get_ring()->cast_to_PolynomialRing();
   const PolynomialRing *P2 = g->get_ring()->cast_to_PolynomialRing();
   *A = NULL;
   *B = NULL;
   if (P == 0)
     {
       if (f->get_ring()->cast_to_Tower() != 0)
         return towerExtendedGCD(f, g, A, B);
       // else we really do have an error:
       ERROR("expected polynomial ring");
       return 0;
     }
   if (P != P2)
     {
       ERROR("encountered different rings");
       return 0;
     }
   if (f->is_zero())
     {
       *A = RingElement::make_raw(P, P->zero());
       *B = RingElement::make_raw(P, P->one());
       return g;
     }
   if (g->is_zero())
     {
       *A = RingElement::make_raw(P, P->one());
       *B = RingElement::make_raw(P, P->zero());
       return f;
     }
   struct enter_factory foo(P);
   if (foo.mode == modeError) return 0;
   if (foo.mode == modeGF)
     {
       set_GF_minimal_poly(P);
     }
   CanonicalForm p = convertToFactory(*f, inExtension);
   CanonicalForm q = convertToFactory(*g, inExtension);
   CanonicalForm a, b;
   CanonicalForm h = extgcd(p, q, a, b);
   ret = convertToM2(P, h);
   if (error())
     {
       algebraicElement_M2 = NULL;
       return NULL;
     }
   *A = convertToM2(P, a);
   if (error())
     {
       algebraicElement_M2 = NULL;
       return NULL;
     }
   *B = convertToM2(P, b);
   if (error())
     {
       algebraicElement_M2 = NULL;
       return NULL;
     }
   algebraicElement_M2 = NULL;
   return ret;
 }
References algebraicElement_M2, Ring::cast_to_PolynomialRing(), Ring::cast_to_Tower(), convertToFactory(), convertToM2(), error(), ERROR(), RingElement::get_ring(), RingElement::is_zero(), RingElement::make_raw(), enter_factory::mode, modeError, modeGF, Ring::one(), p, set_GF_minimal_poly(), towerExtendedGCD(), and Ring::zero().
Referenced by PolyRingQuotient::invert().