Macaulay2 Engine: convertToFactory
convertToFactory() [2/2]
static CanonicalForm convertToFactory (mpz_srcptr p) static
Definition at line 312 of file factory.cpp.
 {
   struct enter_factory foo;
   int size = p->_mp_size;
   int sign = size < 0 ? -1 : 1;
   if (size < 0) size = -size;
   if (!base_set)
     {
       base_set = 1;
       base = 1;
       for (int i = 0; i < mp_bits_per_limb; i++) base *= 2;
     }
   CanonicalForm m = 0;
   for (int i = size - 1; i >= 0; i--)
     {
       mp_limb_t digit = p->_mp_d[i];
       for (int j = mp_bits_per_limb; j > 0;)
         {
           int k = j - 16;
           if (k < 0) k = 0;
           int n = j - k;
           int subbase = 1 << n;
           m = subbase * m + (static_cast<int>(digit >> k) & (subbase - 1));
           j = k;
         }
     }
   m = m * sign;
   return m;
 }
References base, base_set, and p.
Referenced by convertToFactory(), rawCharSeries(), rawExtendedGCDRingElement(), rawFactorBase(), rawGCDRingElement(), rawIdealReorder(), rawPseudoRemainder(), and set_GF_minimal_poly().