Macaulay2 Engine: getGFRepresentation
getGFRepresentation()
static void getGFRepresentation (const Ring * kk1, const ring_elem & a, std::vector< long > & result_rep) static
Definition at line 359 of file factory.cpp.
 {
   assert(kk1->isGaloisField());
   //  const GF* kk = kk1->cast_to_GF();
   //  assert(kk != 0);
   const RingElement *F = kk1->getRepresentation(a);
   //  RingElement F(kk->originalR(), kk->get_rep(a));
   F->getSmallIntegerCoefficients(result_rep);
 }
References Ring::getRepresentation(), RingElement::getSmallIntegerCoefficients(), and Ring::isGaloisField().
Referenced by convertGFToFactory().