Macaulay2 Engine: rawGCDRingElement
rawGCDRingElement()
const RingElement* rawGCDRingElement (const RingElement * f, const RingElement * g, const RingElement * mipo, M2_bool inExtension)
Polynomial GCD and factorization interface routines via Factory and MPSolve
Definition at line 488 of file factory.cpp.
 {
   const RingElement *ret = nullptr;
   const PolynomialRing *P = f->get_ring()->cast_to_PolynomialRing();
   const PolynomialRing *P2 = g->get_ring()->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       if (f->get_ring()->cast_to_Tower() != nullptr) return towerGCD(f, g);
       // else we really do have an error:
       ERROR("expected polynomial ring");
       return nullptr;
     }
   if (P != P2)
     {
       ERROR("encountered different rings");
       return nullptr;
     }
   {
     struct enter_factory foo(P);
     if (foo.mode == modeError)
       {
         algebraicElement_M2 = nullptr;
         return nullptr;
       }
     if (foo.mode == modeGF)
       {
         assert(!inExtension);
         set_GF_minimal_poly(P);
       }
     if (inExtension)
       {
         CanonicalForm minp = convertToFactory(*mipo, false);
         algebraicElement_Fac = rootOf(minp, 'a');
       }
     CanonicalForm p = convertToFactory(*f, inExtension);
     CanonicalForm q = convertToFactory(*g, inExtension);
     CanonicalForm h = gcd(p, q);
     if (inExtension)
       {
         assert(foo.mode != modeGF);
         algebraicElement_M2 = RingElement::make_raw(
             P, P->var(P->n_vars() - 1));  // the algebraic generator is always
                                           // the last variable in M2, the first
                                           // one in factory
       }
     ret = convertToM2(P, h);
     if (error())
       {
         algebraicElement_M2 = nullptr;
         return nullptr;
       }
   }
   if (ret->is_zero()) return ret;
   ring_elem a = P->getNumeratorRing()->preferred_associate_divisor(
       ret->get_value());  // an element in the coeff ring
   ring_elem b = P->getCoefficients()->invert(a);
   ring_elem r = ret->get_value();
   P->mult_coeff_to(b, r);
   algebraicElement_M2 = nullptr;
   return RingElement::make_raw(P, r);
 }
References algebraicElement_Fac, algebraicElement_M2, Ring::cast_to_PolynomialRing(), Ring::cast_to_Tower(), convertToFactory(), convertToM2(), error(), ERROR(), RingElement::get_ring(), RingElement::get_value(), PolynomialRing::getCoefficients(), PolynomialRing::getNumeratorRing(), Ring::invert(), RingElement::is_zero(), RingElement::make_raw(), enter_factory::mode, modeError, modeGF, PolynomialRing::mult_coeff_to(), p, PolyRing::preferred_associate_divisor(), set_GF_minimal_poly(), and towerGCD().
Referenced by LocalRing::lift_up(), FractionField::lower_content(), LocalRing::lower_content(), FractionField::simplify(), and LocalRing::simplify().