Macaulay2 Engine: convertToCFList
convertToCFList()
CFList convertToCFList (const Matrix & M, bool inExtension)
Definition at line 876 of file factory.cpp.
{
  CFList I;
  for (int i = 0; i < M.n_rows(); i++)
    {
      for (int j = 0; j < M.n_cols(); j++)
        {
          const RingElement *g;
          {
            g = RingElement::make_raw(M.get_ring(), M.elem(i, j));
          }
          I.append(convertToFactory(*g, inExtension));
        }
    }
  return I;
}
References convertToFactory(), Matrix::elem(), Matrix::get_ring(), Matrix::n_cols(), and Matrix::n_rows().