Macaulay2 Engine: convertGFToFactory
convertGFToFactory() [1/2]
static CanonicalForm convertGFToFactory (const ring_elem & q, const PolynomialRing * P) static
Definition at line 383 of file factory.cpp.
 {
   std::vector<long> poly;
   getGFRepresentation(P->getCoefficientRing(), q, poly);
   return convertGFToFactory(poly);
 }
References convertGFToFactory(), PolynomialRing::getCoefficientRing(), and getGFRepresentation().