Macaulay2 Engine: init_seeds
init_seeds()
static void init_seeds () static
Definition at line 74 of file factory.cpp.
 {
   NTL::SetSeed(NTL::ZZ::zero());  // NTL
   factoryseed(0);  // factory (which uses NTL, as we've compiled it)
 }
References zero.
Referenced by rawCharSeries(), rawFactorBase(), and rawIdealReorder().