Macaulay2 Engine: emit_wrapped
emit_wrapped() [1/2]
void emit_wrapped (const char * s)
Definition at line 26 of file text-io.cpp.
 {
   // We wish verbose display to wrap at some reasonable length.
   emit_line_len -= static_cast<int>(strlen(s));
   if (emit_line_len <= 0)
     {
       emit_line_len = MAX_LINE_LENGTH;
       fprintf(stdout, "\n");
       fprintf(stdout, wrapping_prefix);
     }
   fputs(s, stdout);
   fflush(stdout);
 }
References emit_line_len, MAX_LINE_LENGTH, and wrapping_prefix.
Referenced by DetComputation::calc(), NCF4::compute(), GB_comp::debug_out(), gbA::do_computation(), emit_wrapped(), ReducedGB_Field_Local::find_good_divisor(), GB_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GB_comp::gb_reduce(), gb2_comp::gb_reduce(), res_comp::gens(), GBKernelComputation::geo_reduce(), res_comp::handle_gen(), res2_comp::handle_pair(), res_comp::handle_pair(), res2_comp::handle_pair_by_degree(), res2_comp::handle_pair_by_level(), NCF4::NCF4(), gbA::process_spair(), GBKernelComputation::reduce(), res2_comp::reduce(), res2_comp::reduce2(), res2_comp::reduce3(), res2_comp::reduce4(), res2_comp::reduce_by_level(), res2_comp::reduce_heap_by_level(), gbA::reduce_kk(), gbA::reduce_ZZ(), ReducedGB_Field_Local::remainder(), gbA::remainder_non_ZZ(), gbA::remainder_ZZ(), gb2_comp::s_pair_step(), gbA::spair_set_defer(), GaussElimComputation::start_computation(), GB_comp::start_computation(), GBinhom_comp::start_computation(), and gbA::tail_remainder_ZZ().