Macaulay2 Engine: clear_emit_size
clear_emit_size()
void clear_emit_size ()
Definition at line 25 of file text-io.cpp.
 { emit_line_len = 0; }
References emit_line_len.
Referenced by IM2_Computation_set_stop(), IM2_GB_contains(), IM2_GB_make(), IM2_GB_matrix_lift(), IM2_GB_set_hilbert_function(), IM2_res_make(), rawGBChangeOfBasis(), rawGBGetLeadTerms(), rawGBGetMatrix(), rawGBGetParallelLeadTerms(), rawGBMatrixRemainder(), rawGBMinimalGenerators(), rawGBSyzygies(), rawResolutionGetFree(), rawResolutionGetMatrix(), rawResolutionGetMatrix2(), rawResolutionGetMutableMatrix2B(), rawResolutionGetMutableMatrixB(), and rawStartComputation().