Macaulay2 Engine: WordWithData::WordWithData
WordWithData() [2/2]
WordWithData::WordWithData (const int * begin, const int * end, int ecartDegree, int heftDegree) inline
Definition at line 60 of file Word.hpp.
                                                                                   :
       mEcartDegree(ecartDegree),
       mHeftDegree(heftDegree)
   {
      mWord.init(begin,end);
   }
References begin(), end(), Word::init(), and mWord.