Macaulay2 Engine: ntuple::divides
divides()
bool ntuple::divides (int nvars, const int * a, const int * b) inline static
Definition at line 115 of file ntuple.hpp.
 {
   for (int i = 0; i < nvars; i++)  // we go upward, because some rings have
                                    // unused variables at the end
     if (a[i] > b[i]) return false;
   return true;
 }
Referenced by Monoid::divides(), Monoid::divides_partial_order(), MonomialTable::find_divisor(), and MonomialTable::find_divisors().