Macaulay2 Engine: ntuple::copy
copy()
void ntuple::copy (int nvars, const int * a, int * result) inline static
Definition at line 146 of file ntuple.hpp.
 {
   memcpy(result, a, nvars * sizeof(int));
 }
Referenced by PolyRing::get_logical_coeff(), KBasis::KBasis(), PolyRing::lead_logical_exponents(), and PolyRing::make_logical_term().