Macaulay2 Engine: ntuple::weight
weight() [2/2]
int ntuple::weight (int nvars, const int * a, M2_arrayint wt) inline static
Definition at line 151 of file ntuple.hpp.
 {
   int top = wt->len;
   if (nvars < top) top = nvars;
   if (top == 0) return 0;
   int sum = safe::mult(a[0], wt->array[0]);
   for (int i = 1; i < top; i++)
     sum = safe::add(sum, safe::mult(a[i], wt->array[i]), "weight overflow");
   return sum;
 }
References safe::add(), safe::mult(), and mpfr::sum().
Referenced by KBasis::compute(), Monoid::degree_weights(), PolyRing::get_part(), KBasis::KBasis(), and Monoid::set_degrees().