Macaulay2 Engine: ntuple::degree
degree()
int ntuple::degree (int nvars, const int * a) inline static
Definition at line 173 of file ntuple.hpp.
 {
   if (nvars == 0) return 0;
   int sum = a[0];
   for (int i = 1; i < nvars; i++) sum = safe::add(sum, a[i], "degree overflow");
   return sum;
 }
References safe::add(), and mpfr::sum().
Referenced by Monoid::simple_degree().