Macaulay2 Engine: ntuple::mask
mask()
unsigned int ntuple::mask (int nvars, const int * a) inline static
Definition at line 124 of file ntuple.hpp.
 {
   unsigned int result = 0, bit = 1;
   for (int i = nvars - 1; i >= 0; i--)
     {
       if (exp[i] > 0) result |= bit;
       bit <<= 1;
       if (bit == 0) bit = 1;
     }
   return result;
 }
References mpfr::exp().
Referenced by MonomialTable::find_exact(), MonomialTable::insert(), and binomial_ring::mask().