Macaulay2 Engine: ntuple::lex_compare
lex_compare()
int ntuple::lex_compare (int nvars, const int * a, const int * b) inline static
Definition at line 136 of file ntuple.hpp.
 {
   for (int i = 0; i < nvars; i++)
     if (a[i] > b[i])
       return GT;
     else if (a[i] < b[i])
       return LT;
   return EQ;
 }
References EQ, GT, and LT.
Referenced by PolyRing::get_coeff(), PolyRing::get_logical_coeff(), PolyRing::get_terms(), PolyRing::n_logical_terms(), and KBasis::try_insert_mg().