Macaulay2 Engine: ntuple::weight
weight() [1/2]
int ntuple::weight (int nvars, const int * a, const std::vector< int > & wt) inline static
Definition at line 162 of file ntuple.hpp.
 {
   int top = wt.size();
   if (nvars < top) top = nvars;
   if (top == 0) return 0;
   int sum = safe::mult(a[0], wt[0]);
   for (int i = 1; i < top; i++)
     sum = safe::add(sum, safe::mult(a[i], wt[i]), "weight overflow");
   return sum;
 }
References safe::add(), safe::mult(), and mpfr::sum().