Macaulay2 Engine: MarkedGB::get_initial
get_initial()
const Matrix * MarkedGB::get_initial (int nparts) virtual
Reimplemented from ReducedGB.
Definition at line 244 of file reducedgb-marked.cpp.
 {
   if (nparts > 0)
     {
       ERROR("Cannot determine given initial monomials");
       return nullptr;
     }
   MatrixConstructor mat(F, 0);
   for (int i = 0; i < polys.size(); i++)
     {
       gbvector *f = R->gbvector_lead_term(-1, F, leadterms[i]);
       mat.append(originalR->translate_gbvector_to_vec(F, f));
     }
   return mat.to_matrix();
 }
References MatrixConstructor::append(), ERROR(), ReducedGB::F, GBRing::gbvector_lead_term(), leadterms, ReducedGB::originalR, ReducedGB::polys, ReducedGB::R, MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().