Macaulay2 Engine: MarkedGB::remainder
remainder() [1/2]
void MarkedGB::remainder (gbvector *& f, bool use_denom, ring_elem & denom) virtual
Implements ReducedGB.
Definition at line 168 of file reducedgb-marked.cpp.
 {
   //  return geo_remainder(f,use_denom,denom);
   gbvector *zero = 0;
   gbvector head;
   gbvector *frem = &head;
   frem->next = 0;
   gbvector *h = f;
   exponents_t EXP = ALLOCATE_EXPONENTS(R->exponent_byte_size());
   while (!R->gbvector_is_zero(h))
     {
       R->gbvector_get_lead_exponents(F, h, EXP);
       int x = h->comp;
       int w = T->find_divisor(EXP, x);
       if (w < 0)
         {
           frem->next = h;
           frem = frem->next;
           h = h->next;
           frem->next = 0;
         }
       else
         {
           POLY g = polys[w];
           R->gbvector_reduce_with_marked_lead_term(F,
                                                    Fsyz,
                                                    head.next,
                                                    h,
                                                    zero,
                                                    leadterms[w],
                                                    g.f,
                                                    zero,
                                                    use_denom,
                                                    denom);
         }
     }
   h = head.next;
   f = h;
   R->gbvector_sort(F, f);
 }
References ALLOCATE_EXPONENTS, gbvector::comp, GBRing::exponent_byte_size(), POLY::f, ReducedGB::F, MonomialTable::find_divisor(), ReducedGB::Fsyz, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), GBRing::gbvector_reduce_with_marked_lead_term(), GBRing::gbvector_sort(), leadterms, gbvector::next, ReducedGB::polys, ReducedGB::R, T, x, and zero.