Macaulay2 Engine: MarkedGB::geo_remainder
geo_remainder()
void MarkedGB::geo_remainder (gbvector *& f, bool use_denom, ring_elem & denom)
Definition at line 210 of file reducedgb-marked.cpp.
 {
   gbvector head;
   gbvector *frem = &head;
   frem->next = nullptr;
   gbvectorHeap fb(R, F);
   gbvectorHeap zero(R, Fsyz);
   fb.add(f);
   const gbvector *lead;
   exponents_t EXP = ALLOCATE_EXPONENTS(R->exponent_byte_size());
   while ((lead = fb.get_lead_term()) != nullptr)
     {
       R->gbvector_get_lead_exponents(F, lead, EXP);
       int x = lead->comp;
       int w = T->find_divisor(EXP, x);
       if (w < 0)
         {
           frem->next = fb.remove_lead_term();
           frem = frem->next;
           frem->next = nullptr;
         }
       else
         {
           POLY g = polys[w];
           R->reduce_marked_lead_term_heap(
               F, Fsyz, lead, EXP, head.next, fb, zero, leadterms[w], g.f, nullptr);
         }
     }
   f = head.next;
   R->gbvector_sort(F, f);
 }
References gbvectorHeap::add(), ALLOCATE_EXPONENTS, gbvector::comp, GBRing::exponent_byte_size(), POLY::f, ReducedGB::F, MonomialTable::find_divisor(), ReducedGB::Fsyz, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_sort(), gbvectorHeap::get_lead_term(), leadterms, gbvector::next, ReducedGB::polys, ReducedGB::R, GBRing::reduce_marked_lead_term_heap(), gbvectorHeap::remove_lead_term(), T, x, and zero.