Macaulay2 Engine: MarkedGB::marked_remainder
marked_remainder()
void MarkedGB::marked_remainder (POLY & f, bool use_denom, ring_elem & denom, gbvector * marked_lead_term)
Definition at line 112 of file reducedgb-marked.cpp.
 {
   gbvector head;
   gbvector *frem = &head;
   frem->next = nullptr;
   POLY h = f;
   exponents_t EXP = ALLOCATE_EXPONENTS(R->exponent_byte_size());
   while (!R->gbvector_is_zero(h.f))
     {
       if (h.f != marked_lead_term)
         {
           R->gbvector_get_lead_exponents(F, h.f, EXP);
           int x = h.f->comp;
           int w = T->find_divisor(EXP, x);
           if (w >= 0)
             {
               POLY g = polys[w];
               R->gbvector_reduce_with_marked_lead_term(F,
                                                        Fsyz,
                                                        head.next,
                                                        h.f,
                                                        h.fsyz,
                                                        leadterms[w],
                                                        g.f,
                                                        g.fsyz,
                                                        use_denom,
                                                        denom);
               continue;
             }
         }
       frem->next = h.f;
       frem = frem->next;
       h.f = h.f->next;
       frem->next = nullptr;
     }
   h.f = head.next;
   f.f = h.f;
   f.fsyz = h.fsyz;
   R->gbvector_sort(F, f.f);
   R->gbvector_sort(Fsyz, f.fsyz);
 }
References ALLOCATE_EXPONENTS, gbvector::comp, GBRing::exponent_byte_size(), POLY::f, ReducedGB::F, MonomialTable::find_divisor(), POLY::fsyz, ReducedGB::Fsyz, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), GBRing::gbvector_reduce_with_marked_lead_term(), GBRing::gbvector_sort(), leadterms, gbvector::next, ReducedGB::polys, ReducedGB::R, T, and x.
Referenced by auto_reduce(), and remainder().