Macaulay2 Engine: MarkedGB::add_marked_elems
add_marked_elems()
void MarkedGB::add_marked_elems (const gc_vector< gbvector * > & leadterms, const gc_vector< POLY > & polys0, bool auto_reduced) virtual
Definition at line 48 of file reducedgb-marked.cpp.
 {
   // First sort these elements via increasing lex order (or monomial order?)
   // Next insert minimal elements into T, and polys
   const Monoid *M = originalR->getMonoid();
   leadterms = newarray(gbvector *, leadterms0.size());
   // Now loop through each element, and see if the lead monomial is in T.
   // If not, add it in , and place element into 'polys'.
   for (int i = 0; i < leadterms0.size(); i++)
     {
       POLY h;
       ring_elem junk;
       gbvector *f = polys0[i].f;
       gbvector *inf = leadterms0[i];
       h.f = R->gbvector_copy(f);
       h.fsyz = R->gbvector_copy(polys0[i].fsyz);
       gbvector *iinf = 0;
       for (gbvector *t = h.f; t != 0; t = t->next)
         if (inf->comp == t->comp && EQ == M->compare(inf->monom, t->monom))
           {
             iinf = t;
             break;
           }
       if (!iinf)
         {
           ERROR("lead term does not appear in the polynomial!");
           iinf = f;
         }
       leadterms[i] = iinf;
       exponents_t e = R->exponents_make();
       R->gbvector_get_lead_exponents(F, iinf, e);
       //      if (auto_reduced)
       //        remainder(h,false,junk); // This auto-reduces h. MES MES!! Maybe
       //        not for marked GB!!
       R->gbvector_remove_content(h.f, h.fsyz);
       T->insert(e, iinf->comp, i);
       polys.push_back(h);
     }
   auto_reduce();
 }
References auto_reduce(), gbvector::comp, Monoid::compare(), EQ, ERROR(), GBRing::exponents_make(), POLY::f, ReducedGB::F, POLY::fsyz, GBRing::gbvector_copy(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_remove_content(), PolynomialRing::getMonoid(), MonomialTable::insert(), leadterms, gbvector::monom, newarray, gbvector::next, ReducedGB::originalR, ReducedGB::polys, ReducedGB::R, and T.
Referenced by GBDeclared::GBDeclared().