Macaulay2 Engine: MarkedGB::MarkedGB
MarkedGB()
MarkedGB::MarkedGB (const PolynomialRing * originalR0, const FreeModule * F0, const FreeModule * Fsyz0) protected
Definition at line 40 of file reducedgb-marked.cpp.
     : ReducedGB(originalR0->get_gb_ring(), originalR0, F0, Fsyz0), T(nullptr)
 {
   T = MonomialTable::make(R->n_vars());
 }
References MonomialTable::make(), GBRing::n_vars(), ReducedGB::R, and T.
Referenced by create().