Macaulay2 Engine: BettiDisplay::entry
entry()
int & BettiDisplay::entry (int deg, int lev)
Definition at line 71 of file betti.cpp.
 {
   if (deg < mLoDegree or deg > mHiDegree or lev < 0 or lev > mHiLength)
     {
       std::cout << "Internal error: (" << deg << "," << lev << ") out of range"
                 << std::endl;
       exit(1);
     }
   return mValues[lev + mNLevels * (deg - mLoDegree)];
 }
References mHiDegree, mHiLength, mLoDegree, mNLevels, and mValues.
Referenced by res2_comp::betti_skeleton(), SchreyerFrame::computeRank(), SchreyerFrame::fillinSyzygies(), SchreyerFrame::getBettiFrame(), resize(), SchreyerFrame::setBettiDisplays(), and SchreyerFrame::start_computation().