Macaulay2 Engine: BettiDisplay::output
output()
void BettiDisplay::output () const
Definition at line 93 of file betti.cpp.
 {
   buffer o;
   displayBetti(o);
   std::cout << o.str() << std::endl;
 }
References displayBetti(), and buffer::str().
Referenced by SchreyerFrame::computeFrame(), and SchreyerFrame::start_computation().