Macaulay2 Engine: BettiDisplay::getBetti
getBetti()
M2_arrayint BettiDisplay::getBetti () const
Definition at line 82 of file betti.cpp.
 {
   return betti_make(mLoDegree, mHiDegree, mHiLength, mValues);
 }
References betti_make(), mHiDegree, mHiLength, mLoDegree, and mValues.
Referenced by res2_comp::betti_skeleton(), displayBetti(), SchreyerFrame::getBetti(), SchreyerFrame::getBettiFrame(), and F4ResComputation::minimal_betti().