Macaulay2 Engine: M2SLProgram::value
value()
SLProgram& M2SLProgram::value () inline
Definition at line 17 of file SLP-defs.hpp.
 { return *mSLProgram; }
References mSLProgram.
Referenced by MutableMat< Mat >::createSLEvaluator(), rawSLPDetGate(), rawSLPDivideGate(), rawSLPInputGate(), rawSLPProductGate(), rawSLProgramToString(), rawSLPsetOutputPositions(), and rawSLPSumGate().