Macaulay2 Engine: MatrixOps::scalarMult
scalarMult()
template<typename RT > void MatrixOps::scalarMult (DMat< RT > & A, MatrixWindow wA, const typename RT::ElementType & c, const DMat< RT > & B, MatrixWindow wB)
Definition at line 334 of file mat-arith.hpp.
 {
   assert(wA.sameSize(wB));
   long rA = wA.begin_row;
   long rB = wB.begin_row;
   for (; rA < wA.end_row; ++rA, ++rB)
     {
       long cA = wA.begin_column;
       long cB = wB.begin_column;
       for (; cA < wA.end_column; ++cA, ++cB)
         {
           A.ring().mult(A.entry(rA, cA), c, B.entry(rB, cB));
         }
     }
 }
References MatrixWindow::begin_column, MatrixWindow::begin_row, MatrixWindow::end_column, MatrixWindow::end_row, DMat< ACoeffRing >::entry(), DMat< ACoeffRing >::ring(), and MatrixWindow::sameSize().