Macaulay2 Engine: MatrixOps::rowReducedEchelonForm
rowReducedEchelonForm() [2/6]
size_t MatrixOps::rowReducedEchelonForm (const DMatGFFlintBig & A, DMatGFFlintBig & result_rref) inline
Definition at line 863 of file mat-linalg.hpp.
{
  DMatGFFlintBig A1(A);
#if __FLINT_RELEASE >= 30100
  long rank = fq_nmod_mat_rref(A1.fq_nmod_mat(), A1.fq_nmod_mat(), A.ring().flintContext());
#else
  long rank = fq_nmod_mat_rref(A1.fq_nmod_mat(), A.ring().flintContext());
#endif
  result_rref.swap(A1);
  return rank;
}
References M2::ARingGFFlintBig::flintContext(), DMat< M2::ARingGFFlintBig >::fq_nmod_mat(), rank(), DMat< M2::ARingGFFlintBig >::ring(), and DMat< M2::ARingGFFlintBig >::swap().