Macaulay2 Engine: MatrixOps::mult
mult() [1/9]
template<typename RT > void MatrixOps::mult (const DMat< RT > & A, const DMat< RT > & B, DMat< RT > & result_product)
Definition at line 327 of file mat-linalg.hpp.
 {
   // printf("entering dmat mult\n");
   typedef typename RT::ElementType ElementType;
   typedef typename DMat<RT>::ConstIterator ConstIterator;
   assert(A.numColumns() == B.numRows());
   assert(A.numRows() == result_product.numRows());
   assert(B.numColumns() == result_product.numColumns());
   ElementType* result = result_product.array();
   typename RT::Element tmp(A.ring());
   // WARNING: this routine expects the result matrix to be in ROW MAJOR ORDER
   for (size_t i = 0; i < A.numRows(); i++)
     for (size_t j = 0; j < B.numColumns(); j++)
       {
         ConstIterator i1 = A.rowBegin(i);
         ConstIterator iend = A.rowEnd(i);
         ConstIterator j1 = B.columnBegin(j);
         while (i1 != iend)
           {
             A.ring().mult(tmp, *i1, *j1);
             A.ring().add(*result, *result, tmp);
             ++i1;
             ++j1;
           }
         result++;
       }
 }
References DMat< ACoeffRing >::array(), DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::ring(), DMat< ACoeffRing >::rowBegin(), and DMat< ACoeffRing >::rowEnd().