Macaulay2 Engine: MatrixOps::addMultipleTo
addMultipleTo() [4/11]
void MatrixOps::addMultipleTo (DMat< ZZpFFPACK > & C, const DMat< ZZpFFPACK > ::ElementType & a, const DMat< ZZpFFPACK > & A, const DMat< ZZpFFPACK > & B)
Definition at line 13 of file dmat.cpp.
 {
   // Compute C := C + a*A*B
   // Both DMat, and FFPACK store dense matrices in row major order.
   // Note that the leading dimension in gemm arguments is #columns,
   // as the matrix is in row-major order
   FFLAS::FFLAS_TRANSPOSE tA = FFLAS::FflasNoTrans;
   FFLAS::FFLAS_TRANSPOSE tB = FFLAS::FflasNoTrans;
   size_t m = A.numRows();
   size_t k = A.numColumns();
   assert(A.numColumns() == B.numRows());
   size_t n = B.numColumns();
   assert(C.numRows() == m);
   assert(C.numColumns() == n);
   DMatZZpFFPACK::ElementType b;
   C.ring().init(b);
   C.ring().set_from_long(b, 1);
   FFLAS::fgemm(C.ring().field(),
                tB,
                tA,
                m,
                n,
                k,
                a,
                A.array(),
                A.numColumns(),
                B.array(),
                B.numColumns(),
                b,
                C.array(),
                C.numColumns());
 }
Referenced by MutableMat< Mat >::addMultipleTo(), addMultipleTo(), mult(), and subtractMultipleTo().