Macaulay2 Engine: MatrixOps::mult
mult() [3/9]
void MatrixOps::mult (const DMatGFFlint & A, const DMatGFFlint & B, DMatGFFlint & result_product) inline
Definition at line 903 of file mat-linalg.hpp.
 {
   //    DMatGFFlint& A1 = const_cast<DMatGFFlint&>(A); // needed because
   //    nmod_mat_mul doesn't declare params const
   //    DMatGFFlint& B1 = const_cast<DMatGFFlint&>(B);
   // The A1 and B1 on the next line are switched because the memory layout
   // expected
   // is the transpose of what we have for DMat.
   fq_zech_mat_mul(result_product.fq_zech_mat(),
                   A.fq_zech_mat(),
                   B.fq_zech_mat(),
                   A.ring().flintContext());
 }
References M2::ARingGFFlint::flintContext(), DMat< M2::ARingGFFlint >::fq_zech_mat(), and DMat< M2::ARingGFFlint >::ring().