Macaulay2 Engine: MatrixOps::subtractMultipleTo
subtractMultipleTo() [5/9]
void MatrixOps::subtractMultipleTo (DMatQQFlint & C, const DMatQQFlint & A, const DMatQQFlint & B) inline
Definition at line 1077 of file mat-linalg.hpp.
 {
   DMatQQFlint D(C.ring(), A.numRows(), B.numColumns());
   fmpq_mat_mul(D.fmpq_mat(), A.fmpq_mat(), B.fmpq_mat());
   fmpq_mat_sub(C.fmpq_mat(), C.fmpq_mat(), D.fmpq_mat());
 }
References DMat< M2::ARingQQFlint >::fmpq_mat(), DMat< M2::ARingQQFlint >::numColumns(), DMat< M2::ARingQQFlint >::numRows(), and DMat< M2::ARingQQFlint >::ring().