Macaulay2 Engine: MatrixOps::inverse
inverse() [3/5]
bool MatrixOps::inverse (const DMatZZ & A, DMatZZ & result_inv) inline
Definition at line 714 of file mat-linalg.hpp.
 {
   DMatZZ::ElementType den;
   A.ring().init(den);
   bool result = fmpz_mat_inv(result_inv.fmpz_mat(), &den, A.fmpz_mat());
   if (!fmpz_is_pm1(&den)) result = false;
   A.ring().clear(den);
   return result;
 }
References M2::ARingZZ::clear(), DMat< M2::ARingZZ >::fmpz_mat(), M2::ARingZZ::init(), and DMat< M2::ARingZZ >::ring().