Macaulay2 Engine: MatrixOps::transpose
transpose() [1/2]
template<typename RT > void MatrixOps::transpose (const DMat< RT > & A, DMat< RT > & result)
Definition at line 240 of file mat-arith.hpp.
 {
   assert(&A != &result);  // these cannot be aliased!
   assert(result.numRows() == A.numColumns());
   assert(result.numColumns() == A.numRows());
   for (size_t c = 0; c < A.numColumns(); ++c)
     {
       auto i = A.columnBegin(c);
       auto j = result.rowBegin(c);
       auto end = A.columnEnd(c);
       for (; i != end; ++i, ++j) A.ring().set(*j, *i);
     }
 }
References DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::columnEnd(), end(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::ring(), and DMat< ACoeffRing >::rowBegin().
Referenced by rankProfile(), and MutableMat< Mat >::transpose().