Macaulay2 Engine: MatrixOps::addInPlace
addInPlace() [2/2]
template<typename RT > void MatrixOps::addInPlace (SMat< RT > & A, const SMat< RT > & B)
Definition at line 403 of file mat-arith.hpp.
 {
   assert(&B.ring() == &A.ring());
   assert(B.numRows() == A.numRows());
   assert(B.numColumns() == A.numColumns());
   A.addInPlace(B);
 }
References SMat< ACoeffRing >::addInPlace(), SMat< ACoeffRing >::numColumns(), SMat< ACoeffRing >::numRows(), and SMat< ACoeffRing >::ring().