Macaulay2 Engine: MatrixOps::addMultipleTo
addMultipleTo() [7/11]
void MatrixOps::addMultipleTo (DMatQQFlint & C, const DMatQQFlint & A, const DMatQQFlint & B) inline
Definition at line 1068 of file mat-linalg.hpp.
{
  DMatQQFlint D(C.ring(), A.numRows(), B.numColumns());
  fmpq_mat_mul(D.fmpq_mat(), A.fmpq_mat(), B.fmpq_mat());
  fmpq_mat_add(C.fmpq_mat(), C.fmpq_mat(), D.fmpq_mat());
}
References DMat< M2::ARingQQFlint >::fmpq_mat(), DMat< M2::ARingQQFlint >::numColumns(), DMat< M2::ARingQQFlint >::numRows(), and DMat< M2::ARingQQFlint >::ring().