Macaulay2 Engine: MatrixOps::addMultipleTo
addMultipleTo() [1/11]
template<typename RT > void MatrixOps::addMultipleTo (DMat< RT > & A, MatrixWindow wA, const typename RT::ElementType & c, const DMat< RT > & B, MatrixWindow wB)
Definition at line 309 of file mat-arith.hpp.
 {
   assert(wA.sameSize(wB));
   typename RT::Element tmp(A.ring());
   long rA = wA.begin_row;
   long rB = wB.begin_row;
   for (; rA < wA.end_row; ++rA, ++rB)
     {
       long cA = wA.begin_column;
       long cB = wB.begin_column;
       for (; cA < wA.end_column; ++cA, ++cB)
         {
           A.ring().mult(tmp, c, B.entry(rB, cB));
           auto& a = A.entry(rA, cA);
           A.ring().add(a, a, tmp);
         }
     }
 }
References MatrixWindow::begin_column, MatrixWindow::begin_row, MatrixWindow::end_column, MatrixWindow::end_row, DMat< ACoeffRing >::entry(), DMat< ACoeffRing >::ring(), and MatrixWindow::sameSize().