Macaulay2 Engine: MatrixOps::SVD
SVD() [1/2]
bool MatrixOps::SVD (const DMatRR & A, DMatRR & Sigma, DMatRR & U, DMatRR & Vt, int strategy) inline
Definition at line 1155 of file mat-linalg.hpp.
 {
 #ifndef NO_LAPACK
   if (strategy == 1) return Lapack::SVD_divide_conquer(&A, &Sigma, &U, &Vt);
   return Lapack::SVD(&A, &Sigma, &U, &Vt);
 #else
   if (strategy == 1) return EigenM2::SVD_divide_conquer(&A, &Sigma, &U, &Vt);
   return EigenM2::SVD(&A, &Sigma, &U, &Vt);
 #endif
 }
References EigenM2::SVD(), Lapack::SVD(), EigenM2::SVD_divide_conquer(), and Lapack::SVD_divide_conquer().