Macaulay2 Engine: MatrixOps::subtractMultipleTo
subtractMultipleTo() [6/9]
void MatrixOps::subtractMultipleTo (DMatZZ & C, const DMatZZ & A, const DMatZZ & B) inline
Definition at line 753 of file mat-linalg.hpp.
 {
   DMatZZ D(C.ring(), A.numRows(), B.numColumns());
   fmpz_mat_mul(D.fmpz_mat(), A.fmpz_mat(), B.fmpz_mat());
   fmpz_mat_sub(C.fmpz_mat(), C.fmpz_mat(), D.fmpz_mat());
 }
References DMat< M2::ARingZZ >::fmpz_mat(), DMat< M2::ARingZZ >::numColumns(), DMat< M2::ARingZZ >::numRows(), and DMat< M2::ARingZZ >::ring().