Macaulay2 Engine: MatrixOps::subtractMultipleTo
subtractMultipleTo() [4/9]
void MatrixOps::subtractMultipleTo (DMatGFFlintBig & C, const DMatGFFlintBig & A, const DMatGFFlintBig & B) inline
Definition at line 832 of file mat-linalg.hpp.
 {
   DMatGFFlintBig D(C.ring(), A.numRows(), B.numColumns());
   fq_nmod_mat_mul(D.fq_nmod_mat(),
                   A.fq_nmod_mat(),
                   B.fq_nmod_mat(),
                   A.ring().flintContext());
   fq_nmod_mat_sub(C.fq_nmod_mat(),
                   C.fq_nmod_mat(),
                   D.fq_nmod_mat(),
                   A.ring().flintContext());
 }
References M2::ARingGFFlintBig::flintContext(), DMat< M2::ARingGFFlintBig >::fq_nmod_mat(), DMat< M2::ARingGFFlintBig >::numColumns(), DMat< M2::ARingGFFlintBig >::numRows(), and DMat< M2::ARingGFFlintBig >::ring().