Macaulay2 Engine: MatrixOps::isEqual
isEqual() [1/2]
template<typename RT > bool MatrixOps::isEqual (const DMat< RT > & A, const DMat< RT > & B)
Definition at line 176 of file mat-arith.hpp.
 {
   assert(&A.ring() == &B.ring());
   if (B.numRows() != A.numRows()) return false;
   if (B.numColumns() != A.numColumns()) return false;
   size_t top = A.numRows() * A.numColumns();
   auto elemsA = A.array();
   auto elemsB = B.array();
   for (size_t i = 0; i < top; i++)
     if (!A.ring().is_equal(*elemsA++, *elemsB++)) return false;
   return true;
 }
References DMat< ACoeffRing >::array(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::ring().
Referenced by NCGroebner::getCoeffOfMonom(), NCF4::getCoeffOfMonom(), and MutableMat< Mat >::is_equal().