Macaulay2 Engine: MatrixOps::subtractMultipleTo
subtractMultipleTo() [8/9]
void MatrixOps::subtractMultipleTo (DMatZZpFlint & C, const DMatZZpFlint & A, const DMatZZpFlint & B) inline
Definition at line 780 of file mat-linalg.hpp.
{
  DMatZZpFlint D(C.ring(), A.numRows(), B.numColumns());
  nmod_mat_mul(D.nmod_mat(), A.nmod_mat(), B.nmod_mat());
  nmod_mat_sub(C.nmod_mat(), C.nmod_mat(), D.nmod_mat());
}
References DMat< M2::ARingZZpFlint >::nmod_mat(), DMat< M2::ARingZZpFlint >::numColumns(), DMat< M2::ARingZZpFlint >::numRows(), and DMat< M2::ARingZZpFlint >::ring().