Macaulay2 Engine: MatrixOps::increase_norm
increase_norm() [2/2]
void MatrixOps::increase_norm (gmp_RRmutable norm, const DMatRR & mat) inline
Definition at line 1174 of file mat-linalg.hpp.
 {
   auto p = mat.array();
   size_t len = mat.numRows() * mat.numColumns();
   for (size_t i = 0; i < len; i++, ++p) mat.ring().increase_norm(norm, *p);
 }
References DMat< ACoeffRing >::array(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), p, and DMat< ACoeffRing >::ring().