Macaulay2 Engine: MatrixOps::nullSpace
nullSpace() [2/5]
size_t MatrixOps::nullSpace (const DMatQQFlint & A, DMatQQFlint & result_nullspace) inline
Definition at line 1029 of file mat-linalg.hpp.
 {
   fmpz_mat_t m1;
   fmpz_mat_t m2;
   fmpz_mat_init(m1, A.numRows(), A.numColumns());
   fmpz_mat_init(m2, A.numColumns(), A.numColumns());
   fmpq_mat_get_fmpz_mat_rowwise(m1, nullptr, A.fmpq_mat());
   // fmpz_mat_print_pretty(m1);
   size_t nullity = fmpz_mat_nullspace(m2, m1);
   // now copy the first 'nullity' columns into result_nullspace
   result_nullspace.resize(A.numColumns(), nullity);
   for (size_t c = 0; c < nullity; c++)
     for (size_t r = 0; r < A.numColumns(); r++)
       fmpz_set(fmpq_numref(&result_nullspace.entry(r, c)),
                fmpz_mat_entry(m2, r, c));
   fmpz_mat_clear(m1);
   fmpz_mat_clear(m2);
   return nullity;
 }
References DMat< M2::ARingQQFlint >::entry(), DMat< M2::ARingQQFlint >::fmpq_mat(), DMat< M2::ARingQQFlint >::numColumns(), DMat< M2::ARingQQFlint >::numRows(), and DMat< M2::ARingQQFlint >::resize().