Macaulay2 Engine: MatrixOps::mult
mult() [4/9]
void MatrixOps::mult (const DMatGFFlintBig & A, const DMatGFFlintBig & B, DMatGFFlintBig & result_product) inline
Definition at line 842 of file mat-linalg.hpp.
 {
   //    DMatGFFlintBig& A1 = const_cast<DMatGFFlintBig&>(A); // needed because
   //    nmod_mat_mul doesn't declare params const
   //    DMatGFFlintBig& B1 = const_cast<DMatGFFlintBig&>(B);
   // The A1 and B1 on the next line are switched because the memory layout
   // expected
   // is the transpose of what we have for DMat.
   fq_nmod_mat_mul(result_product.fq_nmod_mat(),
                   A.fq_nmod_mat(),
                   B.fq_nmod_mat(),
                   A.ring().flintContext());
 }
References M2::ARingGFFlintBig::flintContext(), DMat< M2::ARingGFFlintBig >::fq_nmod_mat(), and DMat< M2::ARingGFFlintBig >::ring().