Macaulay2 Engine: MatrixOps::subtractInPlace
subtractInPlace() [2/2]
template<typename RT > void MatrixOps::subtractInPlace (SMat< RT > & A, const SMat< RT > & B)
Definition at line 413 of file mat-arith.hpp.
 {
   assert(&B.ring() == &A.ring());
   assert(B.numRows() == A.numRows());
   assert(B.numColumns() == A.numColumns());
   A.subtractInPlace(B);
 }
References SMat< ACoeffRing >::numColumns(), SMat< ACoeffRing >::numRows(), SMat< ACoeffRing >::ring(), and SMat< ACoeffRing >::subtractInPlace().