Macaulay2 Engine: MatrixOps::subtractMultipleTo
subtractMultipleTo() [3/9]
void MatrixOps::subtractMultipleTo (DMatGFFlint & C, const DMatGFFlint & A, const DMatGFFlint & B) inline
Definition at line 888 of file mat-linalg.hpp.
 {
   DMatGFFlint D(C.ring(), A.numRows(), B.numColumns());
   fq_zech_mat_mul(D.fq_zech_mat(),
                   A.fq_zech_mat(),
                   B.fq_zech_mat(),
                   A.ring().flintContext());
   fq_zech_mat_sub(C.fq_zech_mat(),
                   C.fq_zech_mat(),
                   D.fq_zech_mat(),
                   A.ring().flintContext());
 }
References M2::ARingGFFlint::flintContext(), DMat< M2::ARingGFFlint >::fq_zech_mat(), DMat< M2::ARingGFFlint >::numColumns(), DMat< M2::ARingGFFlint >::numRows(), and DMat< M2::ARingGFFlint >::ring().