Macaulay2 Engine: MatrixOps::isZero
isZero() [1/2]
template<typename RT > bool MatrixOps::isZero (const DMat< RT > & A)
Definition at line 166 of file mat-arith.hpp.
 {
   size_t len = A.numRows() * A.numColumns();
   if (len == 0) return true;
   for (auto t = A.array() + len - 1; t >= A.array(); t--)
     if (!A.ring().is_zero(*t)) return false;
   return true;
 }
References DMat< ACoeffRing >::array(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::ring().
Referenced by fill_from_lapack_upper(), fill_lower_and_upper(), MutableMat< Mat >::is_zero(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), LUUtil< RT >::setUpperLower(), DMatLinAlg< RingType >::setUpperLower(), and TEST().