Macaulay2 Engine: MatrixOps::rankProfile
rankProfile() [1/5]
template<typename RT > M2_arrayintOrNull MatrixOps::rankProfile (const DMat< RT > & A, bool row_profile) inline
Definition at line 534 of file mat-linalg.hpp.
 {
   std::vector<size_t> profile;
   if (row_profile)
     {
       // First transpose A
       DMat<RT> B(A.ring(), A.numColumns(), A.numRows());
       MatrixOps::transpose(A, B);
       DMatLinAlg<RT> LUdecomp(B);
       LUdecomp.columnRankProfile(profile);
       return stdvector_to_M2_arrayint(profile);
     }
   else
     {
       DMatLinAlg<RT> LUdecomp(A);
       LUdecomp.columnRankProfile(profile);
       return stdvector_to_M2_arrayint(profile);
     }
 }
References DMatLinAlg< RingType >::columnRankProfile(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::ring(), stdvector_to_M2_arrayint(), and transpose().