Macaulay2 Engine: MatrixOps::LU
LU() [3/3]
template<typename Mat > M2_arrayintOrNull MatrixOps::LU (const Mat & A, Mat & L, Mat & U)
Definition at line 238 of file mat-linalg.hpp.
 {
   throw exc::engine_error(
       "'LU' not implemented for this kind of matrix over this ring");
 }
Referenced by DMatLinAlg< M2::ARingZZpFlint >::columnRankProfile(), LUUtil< RT >::computePivotColumns(), DMatLinAlg< RingType >::determinant(), DMatLinAlg< RingType >::inverse(), DMatLinAlg< RingType >::kernel(), MutableMat< Mat >::LU(), LUincremental(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), DMatLinAlg< M2::ARingZZpFFPACK >::matrixPLU(), DMatLinAlg< M2::ARingZZpFlint >::matrixPLU(), DMatLinAlg< RingType >::matrixPLU(), rawLUincremental(), LUUtil< RT >::setUpperLower(), DMatLinAlg< RingType >::setUpperLower(), DMatLinAlg< RingType >::solve(), DMatLinAlg< RingType >::solveInvertible(), solveLowerTriangular< DMatGFFlint >(), solveLowerTriangular< DMatGFFlintBig >(), solveUpperTriangular< DMatGFFlint >(), and solveUpperTriangular< DMatGFFlintBig >().