Macaulay2 Engine: TEST
TEST() [2/7]
TEST (ARingRRR , axioms)
Definition at line 167 of file ARingRRRTest.cpp.
 {
   M2::ARingRRR R(100);
   ARingElementGenerator<M2::ARingRRR> gen(R);
   M2::ARingRRR::ElementType a, b, c, d, e;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(d);
   R.init(e);
   for (int i = 0; i < ntrials; i++)
     {
       gen.nextElement(a);
       gen.nextElement(b);
       gen.nextElement(c);
       // Test commutativity
       // test: a*b = b*a
       // test: a+b == b+a
       R.add(d, a, b);
       R.add(e, b, a);
       EXPECT_TRUE(almostEqual(R, 98, d, e));
       R.mult(d, a, b);
       R.mult(e, b, a);
       EXPECT_TRUE(almostEqual(R, 98, d, e));
       // Test associativity
       // test: a+(b+c) == (a+b)+c
       // test: a*(b*c) == (a*b)*c
       R.add(e, b, c);
       R.add(d, a, e);  // a+(b+c)
       R.add(e, a, b);
       R.add(e, e, c);  // (a+b)+c
       EXPECT_TRUE(almostEqual(R, 94, d, e));
       R.mult(e, b, c);
       R.mult(d, a, e);  // a*(b*c)
       R.mult(e, a, b);
       R.mult(e, e, c);  // (a*b)*c
       EXPECT_TRUE(almostEqual(R, 94, d, e));
       // Test distributivity
       // test: a*(b+c) == a*b + a*c
       R.add(e, b, c);
       R.mult(d, a, e);  // a*(b+c)
       R.mult(b, a, b);
       R.mult(c, a, c);
       R.add(e, b, c);  // a*b + a*c
       EXPECT_TRUE(almostEqual(R, 94, d, e));
     }
   R.clear(e);
   R.clear(d);
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References M2::ARingRRR::add(), almostEqual(), M2::ARingRRR::clear(), M2::ARingRRR::init(), M2::ARingRRR::mult(), ARingElementGenerator< RingType >::nextElement(), and ntrials.