Macaulay2 Engine: TEST
TEST() [7/7]
TEST (ARingRRR , subtract)
Definition at line 111 of file ARingRRRTest.cpp.
 {
   M2::ARingRRR R(100);
   ARingElementGenerator<M2::ARingRRR> gen(R);
   M2::ARingRRR::ElementType a, b, c, e;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(e);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (a-b) + (b) == a
       gen.nextElement(a);
       gen.nextElement(b);
       R.subtract(c, a, b);
       R.add(e, c, b);  // should be a
       EXPECT_TRUE(almostEqual(R, 98, a, e));
       R.mult(e, a, b);
       R.subtract_multiple(e, a, b);
       EXPECT_TRUE(R.is_zero(e));
     }
   R.clear(e);
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References M2::ARingRRR::add(), almostEqual(), M2::ARingRRR::clear(), M2::ARingRRR::init(), M2::ARingRRR::is_zero(), M2::ARingRRR::mult(), ARingElementGenerator< RingType >::nextElement(), ntrials, M2::ARingRRR::subtract(), and M2::ARingRRR::subtract_multiple().