Macaulay2 Engine: almostEqual
almostEqual()
bool almostEqual (const M2::ARingRRR & R, int nbits, const M2::ARingRRR::ElementType & a, const M2::ARingRRR::ElementType & b)
Definition at line 14 of file ARingRRRTest.cpp.
{
  mpfr_t epsilon;
  mpfr_init2(epsilon, R.get_precision());
  mpfr_set_ui_2exp(epsilon, 1, -nbits, MPFR_RNDN);
  M2::ARingRRR::ElementType c;
  R.init(c);
  R.subtract(c, a, b);
  bool ret = mpfr_cmpabs(&c, epsilon) < 0;
  R.clear(c);
  mpfr_clear(epsilon);
  return ret;
}
References M2::ARingRRR::clear(), M2::ARingRRR::get_precision(), M2::ARingRRR::init(), and M2::ARingRRR::subtract().
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().