Macaulay2 Engine: TEST
TEST() [4/7]
TEST (ARingRRR , multDivide)
Definition at line 138 of file ARingRRRTest.cpp.
 {
   M2::ARingRRR R(100);
   ARingElementGenerator<M2::ARingRRR> gen(R);
   M2::ARingRRR::ElementType a, b, c, d;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(d);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (a*b) // b == a
       gen.nextElement(a);
       gen.nextElement(b);
       R.mult(c, a, b);
       if (R.is_zero(b))
         EXPECT_TRUE(R.is_zero(c));
       else
         {
           R.divide(d, c, b);
           EXPECT_TRUE(almostEqual(R, 94, d, a));
         }
     }
   R.clear(d);
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References almostEqual(), M2::ARingRRR::clear(), M2::ARingRRR::divide(), M2::ARingRRR::init(), M2::ARingRRR::is_zero(), M2::ARingRRR::mult(), ARingElementGenerator< RingType >::nextElement(), and ntrials.