Macaulay2 Engine: testRingNegateRRR
testRingNegateRRR()
void testRingNegateRRR (const M2::ARingRRR & R, int ntrials)
Definition at line 58 of file ARingRRRTest.cpp.
 {
   ARingElementGenerator<M2::ARingRRR> gen(R);
   M2::ARingRRR::ElementType a, b, c;
   R.init(a);
   R.init(b);
   R.init(c);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (-a) + (a) == 0
       gen.nextElement(a);
       R.negate(b, a);
       R.add(c, a, b);
       EXPECT_TRUE(R.is_zero(c));
     }
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References M2::ARingRRR::add(), M2::ARingRRR::clear(), M2::ARingRRR::init(), M2::ARingRRR::is_zero(), M2::ARingRRR::negate(), ARingElementGenerator< RingType >::nextElement(), and ntrials.
Referenced by TEST().