Macaulay2 Engine: index_varpower::valid
valid()
int index_varpower::valid () inline
Definition at line 80 of file varpower.hpp.
 { return loc < hi; }
References hi, and loc.
Referenced by MinimalPrimes::alg1_min_primes(), AssociatedPrimes::ass_prime_generator(), MinimalPrimes::ass_prime_generator(), varpower::computeHashValue(), Monoid::degree_of_varpower(), varpower::divides(), varpower::elem_text_out(), varpower::erase(), RingMap::eval_term(), varpower::gcd(), varpower::lcm(), partition_table::merge_in(), varpower::monsyz(), varpower::mult(), popular_var(), varpower::power(), varpower::quotient(), varpower::radical(), reduce_exp(), varpower::simple_degree(), varpower::to_expvector(), and varpower_monideal().