Macaulay2 Engine: index_varpower::var
var()
int index_varpower::var () inline
Definition at line 89 of file varpower.hpp.
 { return *loc; }
References loc.
Referenced by varpower::computeHashValue(), varpower::divides(), varpower::elem_text_out(), varpower::erase(), varpower::gcd(), varpower::lcm(), partition_table::merge_in(), varpower::monsyz(), varpower::mult(), popular_var(), and varpower::quotient().