Macaulay2 Engine: matrixToStream
matrixToStream()
template<typename T > void matrixToStream (const Matrix * M, T & stream)
Definition at line 82 of file matrix-stream.hpp.
 {
   const Ring* R = M->get_ring();
   const PolyRing* P = R->cast_to_PolyRing();
   assert(P != 0);
   const Ring* KK = P->getCoefficientRing();
   size_t nvars = P->n_vars();
   size_t ncols = M->n_cols();
   int charac = static_cast<int>(P->characteristic());
   assert(charac > 0);
   exponents_t exp =
       ALLOCATE_EXPONENTS(EXPONENT_BYTE_SIZE(nvars));  // allocated on stack
   stream.idealBegin(ncols);
   Matrix::iterator i(M);
   for (int c = 0; c < ncols; c++)
     {
       i.set(c);
       // We need the length of this column, in number of monomials
       size_t nterms = 0;
       for (; i.valid(); i.next())
         {
           Nterm* t = i.entry();
           for (Nterm* s = t; s != 0; s = s->next) nterms++;
         }
       stream.appendPolynomialBegin(nterms);
       i.set(c);
       // Now we process each column, sending it to the stream
       for (; i.valid(); i.next())
         {
           Nterm* t = i.entry();
           for (Nterm* s = t; s != 0; s = s->next)
             {
               P->getMonoid()->to_expvector(s->monom, exp);
               stream.appendTermBegin(i.row());
               for (size_t j = 0; j < nvars; j++)
                 if (exp[j] != 0) stream.appendExponent(j, exp[j]);
               std::pair<bool, long> b = KK->coerceToLongInteger(s->coeff);
               assert(b.first);
               int a = static_cast<int>(
                   b.second);  // This will fit, as the charac fits into an int
               if (a < 0) a += charac;
               stream.appendTermDone(a);
             }
         }
       stream.appendPolynomialDone();
     }
   stream.idealDone();
 }
References ALLOCATE_EXPONENTS, Ring::cast_to_PolyRing(), Ring::characteristic(), Ring::coerceToLongInteger(), Matrix::iterator::entry(), mpfr::exp(), EXPONENT_BYTE_SIZE, Matrix::get_ring(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), Matrix::n_cols(), PolynomialRing::n_vars(), Matrix::iterator::next(), Nterm::next, Matrix::iterator::row(), Matrix::iterator::set(), Monoid::to_expvector(), and Matrix::iterator::valid().
Referenced by rawDisplayMatrixStream(), and rawMGB().