Macaulay2 Engine: index_res_varpower_monomial::valid
valid()
bool index_res_varpower_monomial::valid () inline
Definition at line 73 of file res-varpower-monomial.hpp.
 { return loc < hi; }
References hi, and loc.
Referenced by ResMonoidDense::from_varpower_monomial(), ResMonoidSparse::from_varpower_monomial(), and ResF4MonomialLookupTableT< Key >::insert1().