Macaulay2 Engine: M2::ConcreteRing::create
create() [2/2]
template<class RingType > ConcreteRing< RingType > * M2::ConcreteRing< RingType >::create (std::unique_ptr< RingType > R) static
Definition at line 513 of file aring-glue.hpp.
{
  auto characteristic = R->characteristic();
  ConcreteRing<RingType> *result = new ConcreteRing<RingType>(std::move(R));
  result->initialize_ring(characteristic);
  result->declare_field();
  result->zeroV = result->from_long(0);
  result->oneV = result->from_long(1);
  result->minus_oneV = result->from_long(-1);
  return result;
}
References Ring::characteristic(), Ring::declare_field(), M2::ConcreteRing< RingType >::from_long(), Ring::initialize_ring(), Ring::minus_oneV, Ring::oneV, and Ring::zeroV.
Referenced by M2::ConcreteRing< RingType >::create(), IM2_Ring_CCC(), IM2_Ring_RRi(), IM2_Ring_RRR(), rawARingGaloisField(), rawARingGaloisField1(), rawARingGaloisFieldFlintBig(), rawARingGaloisFieldFlintZech(), rawARingQQFlint(), rawARingTower1(), rawARingTower2(), rawARingTower3(), rawARingZZFlint(), rawARingZZp(), rawARingZZpFlint(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().