Macaulay2 Engine: M2::ConcreteRing::promote
promote() [4/4]
template<typename RingType > bool M2::ConcreteRing< RingType >::promote (const Ring * S, const ring_elem f, ring_elem & result) const virtual
If there is a "natural" map S --> R=this, where f is an element of S , then result is set to the image of f, and true is returned. Otherwise, false is returned.
The map must one-step, e.g. for k --> k[x] --> k[x][y], promotion must be done with two consecutive calls to promote(with different arguments). Examples of natural maps: ZZ --> R, for any R QQ --> RR --> CC ZZ --> ZZ/p ZZ/p --> GF(p^n) GF(p^m) --> GF(p^n), where m|n A --> A[vars]/I A[vars]/J --> A[vars]/I (assumption: I contains J).
Implements Ring.
Definition at line 589 of file aring-glue.hpp.
 {
   const Ring *S = this;
   //    fprintf(stderr, "calling promote\n");
   namespace RP = RingPromoter;
   if (R == globalZZ)
     {
       resultS = S->from_int(fR.get_mpz());
       return true;
     }
   if (R == S)
     {
       resultS = copy(fR);
       return true;
     }
   switch (R->ringID())
     {
       case M2::ring_ZZp:
         switch (S->ringID())
           {
             case M2::ring_ZZp:
               return false;
             case M2::ring_ZZpFfpack:
               return RP::promoter<ARingZZp, ARingZZpFFPACK>(R, S, fR, resultS);
             default:
               return false;
           }
         break;
       case M2::ring_ZZpFfpack:
         switch (S->ringID())
           {
             case M2::ring_ZZp:
               return RP::promoter<ARingZZpFFPACK, ARingZZp>(R, S, fR, resultS);
             case M2::ring_ZZpFfpack:
               return RP::promoter<ARingZZpFFPACK, ARingZZpFFPACK>(
                   R, S, fR, resultS);
             default:
               return false;
           }
       case M2::ring_QQ:
         switch (S->ringID())
           {
             case M2::ring_RR:
               return RP::promoter<ARingQQ, ARingRR>(R, S, fR, resultS);
             case M2::ring_RRR:
               return RP::promoter<ARingQQ, ARingRRR>(R, S, fR, resultS);
             case M2::ring_RRi:
               return RP::promoter<ARingQQ, ARingRRi>(R, S, fR, resultS);
             case M2::ring_CC:
               return RP::promoter<ARingQQ, ARingCC>(R, S, fR, resultS);
             case M2::ring_CCC:
               return RP::promoter<ARingQQ, ARingCCC>(R, S, fR, resultS);
             default:
               return false;
           }
       case M2::ring_RR:
         switch (S->ringID())
           {
             case M2::ring_RR:
               return RP::promoter<ARingRR, ARingRR>(R, S, fR, resultS);
             case M2::ring_RRR:
               return RP::promoter<ARingRR, ARingRRR>(R, S, fR, resultS);
             case M2::ring_RRi:
               return RP::promoter<ARingRR, ARingRRi>(R, S, fR, resultS);
             case M2::ring_CC:
               return RP::promoter<ARingRR, ARingCC>(R, S, fR, resultS);
             case M2::ring_CCC:
               return RP::promoter<ARingRR, ARingCCC>(R, S, fR, resultS);
             default:
               return false;
           }
       case M2::ring_RRR:
         switch (S->ringID())
           {
             case M2::ring_RR:
               return RP::promoter<ARingRRR, ARingRR>(R, S, fR, resultS);
             case M2::ring_RRR:
               return RP::promoter<ARingRRR, ARingRRR>(R, S, fR, resultS);
             case M2::ring_RRi:
               return RP::promoter<ARingRRR, ARingRRi>(R, S, fR, resultS);
             case M2::ring_CC:
               return RP::promoter<ARingRRR, ARingCC>(R, S, fR, resultS);
             case M2::ring_CCC:
               return RP::promoter<ARingRRR, ARingCCC>(R, S, fR, resultS);
             default:
               return false;
           }
       case M2::ring_RRi:
         switch (S->ringID())
            {
               case M2::ring_RR:
                 return RP::promoter<ARingRRi, ARingRR>(R, S, fR, resultS);
               case M2::ring_RRR:
                 return RP::promoter<ARingRRi, ARingRRR>(R, S, fR, resultS);
               case M2::ring_RRi:
                 return RP::promoter<ARingRRi, ARingRRi>(R, S, fR, resultS);
               default:
                  return false;
           }
       case M2::ring_CC:
         switch (S->ringID())
           {
             case M2::ring_CC:
               return RP::promoter<ARingCC, ARingCC>(R, S, fR, resultS);
             case M2::ring_CCC:
               return RP::promoter<ARingCC, ARingCCC>(R, S, fR, resultS);
             default:
               return false;
           }
       case M2::ring_CCC:
         switch (S->ringID())
           {
             case M2::ring_CCC:
               return RP::promoter<ARingCCC, ARingCCC>(R, S, fR, resultS);
             case M2::ring_CC:
               return RP::promoter<ARingCCC, ARingCC>(R, S, fR, resultS);
             default:
               return false;
           }
       default:
         break;
     };
   return false;
 }
References Ring::from_int(), ring_elem::get_mpz(), globalZZ, M2::ring_CC, M2::ring_CCC, M2::ring_QQ, M2::ring_RR, M2::ring_RRi, M2::ring_RRR, M2::ring_ZZp, M2::ring_ZZpFfpack, and Ring::ringID().