Macaulay2 Engine: M2::ConcreteRing::is_zero
is_zero()
template<class RingType > virtual bool M2::ConcreteRing< RingType >::is_zero (const ring_elem f) const inline virtual
Implements Ring.
Definition at line 219 of file aring-glue.hpp.
  {
    if (displayArithmeticCalls) fprintf(stderr, "calling is_zero\n");
    const ElementType &a = R->from_ring_elem_const(f);
    bool ret = R->is_zero(a);
    return ret;
  }
References displayArithmeticCalls, and M2::ConcreteRing< RingType >::R.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().