Macaulay2 Engine: M2::ConcreteRing::ring
ring()
template<class RingType > const RingType & M2::ConcreteRing< RingType >::ring () const inline
Definition at line 41 of file aring-glue.hpp.
{ return *R; }
References M2::ConcreteRing< RingType >::R.
Referenced by M2::ConcreteRing< RingType >::computeHashValue(), rawARingTower1(), rawARingTower2(), and rawARingTower3().