Macaulay2 Engine: M2::ConcreteRing::mult
mult()
template<class RingType > virtual ring_elem M2::ConcreteRing< RingType >::mult (const ring_elem f, const ring_elem g) const inline virtual
Implements Ring.
Definition at line 297 of file aring-glue.hpp.
  {
    if (displayArithmeticCalls) fprintf(stderr, "calling mult\n");
    const ElementType &a = R->from_ring_elem_const(f);
    const ElementType &b = R->from_ring_elem_const(g);
    Element c(*R);
    ring_elem result;
    R->mult(c, a, b);
    R->to_ring_elem(result, c);
    return result;
  }
References displayArithmeticCalls, and M2::ConcreteRing< RingType >::R.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().