Macaulay2 Engine: M2::ConcreteRing::from_long
from_long()
template<class RingType > virtual ring_elem M2::ConcreteRing< RingType >::from_long (long n) const inline virtual
Implements Ring.
Definition at line 100 of file aring-glue.hpp.
   {
     if (displayArithmeticCalls) fprintf(stderr, "calling from_long\n");
     ring_elem result;
     Element a(*R);
     R->set_from_long(a, n);
     R->to_ring_elem(result, a);
     return result;
   }
References displayArithmeticCalls, and M2::ConcreteRing< RingType >::R.
Referenced by M2::RingQQ::create(), M2::ConcreteRing< RingType >::create(), getElement< RingCCC >(), getElement< RingQQ >(), getElement< RingRRR >(), and TEST().