Macaulay2 Engine: GaussElimComputation::get_gb
get_gb()
const Matrix * GaussElimComputation::get_gb () virtual
Implements GBComputation.
Definition at line 290 of file gauss.cpp.
 {
   MatrixConstructor mat(gens->rows(), 0);
   for (int i = 0; i < gens->n_rows(); i++)
     if (gb_list[i] != NULL) mat.append(R->copy_vec(gb_list[i]->f));
   return mat.to_matrix();
 }
References MatrixConstructor::append(), Ring::copy_vec(), gm_elem::f, gb_list, gens, Matrix::n_rows(), R, Matrix::rows(), and MatrixConstructor::to_matrix().
Referenced by get_mingens().