Macaulay2 Engine: GaussElimComputation::reduce
reduce() [3/3]
void GaussElimComputation::reduce (vec & f, vec & fsyz, bool tail_only = false) private
Definition at line 179 of file gauss.cpp.
 {
   if (f == 0) return;
   vecterm head;
   vecterm *result = &head;
   if (tail_only)
     {
       // Don't reduce the head term.
       result->next = f;
       f = f->next;
       result = result->next;
     }
   while (f != NULL)
     {
       int r = f->comp;
       if (gb_list[r] != NULL)
         {
           // Reduce w.r.t. this term
           ring_elem c = f->coeff;
           c = R->negate(c);
           vec gsyz = R->mult_vec(c, gb_list[r]->fsyz);
           vec g = R->mult_vec(c, gb_list[r]->f);
           R->add_vec_to(f, g);
           R->add_vec_to(fsyz, gsyz);
         }
       else
         {
           result->next = f;
           f = f->next;
           result = result->next;
         }
     }
   result->next = NULL;
   f = head.next;
 }
References Ring::add_vec_to(), gm_elem::f, gm_elem::fsyz, gb_list, Ring::mult_vec(), Ring::negate(), vec::next, and R.