Macaulay2 Engine: GaussElimComputation::get_change
get_change()
const Matrix * GaussElimComputation::get_change () virtual
Implements GBComputation.
Definition at line 298 of file gauss.cpp.
 {
   MatrixConstructor mat(Fsyz, 0);
   for (int i = 0; i < gens->n_rows(); i++)
     if (gb_list[i] != nullptr) mat.append(R->copy_vec(gb_list[i]->fsyz));
   return mat.to_matrix();
 }
References MatrixConstructor::append(), Ring::copy_vec(), gm_elem::fsyz, Fsyz, gb_list, gens, Matrix::n_rows(), R, and MatrixConstructor::to_matrix().