Macaulay2 Engine: GaussElimComputation::text_out
text_out()
void GaussElimComputation::text_out (buffer & o) const virtual
Reimplemented from Computation.
Definition at line 314 of file gauss.cpp.
{
  o << newline;
  for (int i = 0; i < gens->n_rows(); i++)
    {
      if (gb_list[i] != nullptr)
        {
          o << "--- component " << i << " -----" << newline;
          o << "gb elem = ";
          R->vec_text_out(o, gb_list[i]->f);
          o << newline;
        }
      else if (reduce_list[i] != nullptr)
        o << "--- component " << i << " -----" << newline;
      for (gm_elem *p = reduce_list[i]; p != nullptr; p = p->next)
        {
          o << p->nterms;
          o << " ## ";
          R->vec_text_out(o, p->f);
          o << " ## ";
          R->vec_text_out(o, p->fsyz);
          o << newline;
        }
    }
  o << newline;
  for (int i = 0; i < syz_list.size(); i++) R->vec_text_out(o, syz_list[i]);
  o << newline;
}
References gb_list, gens, Matrix::n_rows(), newline, p, R, reduce_list, syz_list, and Ring::vec_text_out().
Referenced by start_computation().