Macaulay2 Engine: GaussElimComputation::start_computation
start_computation()
void GaussElimComputation::start_computation () virtual
Implements GBComputation.
Definition at line 216 of file gauss.cpp.
 {
   if (status() == COMP_DONE) return;
   for (; row >= 0; row--)
     {
       if (gb_list[row] == nullptr) continue;
       while (reduce_list[row] != nullptr)
         {
           gm_elem *p = reduce_list[row];
           reduce_list[row] = p->next;
           p->next = nullptr;
           reduce(gb_list[row], p);  // replaces p
           if (M2_gbTrace >= 3)
             {
               if (p->f == nullptr)
                 {
                   if (p->fsyz == nullptr)
                     emit_wrapped("o");
                   else
                     emit_wrapped("z");
                 }
               else
                 emit_wrapped("r");
             }
           else
             {
             }
           insert(p);
           n_pairs++;
           if (system_interrupted())
             {
               set_status(COMP_INTERRUPTED);
               return;
             }
           if (n_pairs == stop_.pair_limit)
             {
               set_status(COMP_DONE_PAIR_LIMIT);
               return;
             }
           if (n_syz == stop_.syzygy_limit)
             {
               set_status(COMP_DONE_SYZYGY_LIMIT);
               return;
             }
         }
     }
   // Now auto reduce these
   for (int r = 1; r < gens->n_rows(); r++)
     {
       if (gb_list[r] == nullptr) continue;
       reduce(gb_list[r]->f, gb_list[r]->fsyz, true);
     }
   if (M2_gbTrace >= 10)
     {
       buffer o;
       text_out(o);
       emit(o.str());
     }
   set_status(COMP_DONE);
 }
References COMP_DONE, COMP_DONE_PAIR_LIMIT, COMP_DONE_SYZYGY_LIMIT, COMP_INTERRUPTED, emit(), emit_wrapped(), gm_elem::f, gm_elem::fsyz, gb_list, gens, insert(), M2_gbTrace, n_pairs, Matrix::n_rows(), n_syz, p, StopConditions::pair_limit, reduce(), reduce_list, row, Computation::set_status(), Computation::status(), Computation::stop_, buffer::str(), system_interrupted(), StopConditions::syzygy_limit, and text_out().