Macaulay2 Engine: GaussElimComputation::matrix_remainder
matrix_remainder()
const Matrix * GaussElimComputation::matrix_remainder (const Matrix * m) virtual
Implements GBComputation.
Definition at line 343 of file gauss.cpp.
 {
   if (m->get_ring() != R)
     {
       ERROR("encountered different rings");
       return nullptr;
     }
   if (m->n_rows() != gens->rows()->rank())
     {
       ERROR("expected matrices to have same number of rows");
       return nullptr;
     }
   MatrixConstructor mat_remainder(m->rows(), m->cols(), m->degree_shift());
   for (int i = 0; i < m->n_cols(); i++)
     {
       vec f = R->copy_vec(m->elem(i));
       reduce(f);
       mat_remainder.set_column(i, f);
     }
   return mat_remainder.to_matrix();
 }
References Matrix::cols(), Ring::copy_vec(), Matrix::degree_shift(), Matrix::elem(), ERROR(), gm_elem::f, gens, Matrix::get_ring(), Matrix::n_cols(), Matrix::n_rows(), R, FreeModule::rank(), reduce(), Matrix::rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().