Macaulay2 Engine: GaussElimComputation::remove_gm_elem
remove_gm_elem()
void GaussElimComputation::remove_gm_elem (gm_elem *& p) private
Definition at line 103 of file gauss.cpp.
 {
   if (p != NULL)
     {
       R->remove_vec(p->f);
       R->remove_vec(p->fsyz);
       freemem(p);
       p = NULL;
     }
 }
References freemem(), p, R, and Ring::remove_vec().
Referenced by ~GaussElimComputation().