Macaulay2 Engine: GaussElimComputation::reduce
reduce() [1/3]
void GaussElimComputation::reduce (gm_elem *& p, gm_elem * q) private
Definition at line 130 of file gauss.cpp.
 {
   // MES: rewrite.
   // Reduce q by p.  This is a single step reduction.
   // The element is then inserted further down.
   ring_elem c1 = p->f->coeff;
   ring_elem c2 = q->f->coeff;
   ring_elem d2 = R->negate(c2);
   vec v1 = R->mult_vec(c1, q->f);
   vec v2 = R->mult_vec(d2, p->f);
   vec s1 = R->mult_vec(c1, q->fsyz);
   vec s2 = R->mult_vec(d2, p->fsyz);
   R->remove_vec(q->f);
   R->remove_vec(q->fsyz);
   R->remove(d2);
   R->add_vec_to(v1, v2);
   R->add_vec_to(s1, s2);
   q->f = v1;
   q->fsyz = s1;
 }
References Ring::add_vec_to(), gm_elem::f, gm_elem::fsyz, Ring::mult_vec(), Ring::negate(), p, R, Ring::remove(), and Ring::remove_vec().
Referenced by contains(), matrix_lift(), matrix_remainder(), and start_computation().