Macaulay2 Engine: GaussElimComputation::insert
insert()
void GaussElimComputation::insert (gm_elem * p) private
Definition at line 32 of file gauss.cpp.
 {
   if (p->f == nullptr)
     {
       if (p->fsyz != nullptr && collect_syz)
         {
           syz_list.push_back(p->fsyz);
           n_syz++;
         }
       freemem(p);
     }
   else
     {
       ring_elem leadinv = R->invert(p->f->coeff);
       R->mult_vec_to(p->f, leadinv, false);
       R->mult_vec_to(p->fsyz, leadinv, false);
       p->nterms = R->n_nonzero_terms(p->f);
       int i = p->f->comp;
       if (gb_list[i] == nullptr)
         {
           gb_list[i] = p;
           n_gb++;
         }
       else
         {
           if (p->nterms < gb_list[i]->nterms)
             {
               gm_elem *q = p;
               p = gb_list[i];
               gb_list[i] = q;
             }
           p->next = reduce_list[i];
           reduce_list[i] = p;
         }
     }
 }
References collect_syz, freemem(), gb_list, Ring::invert(), Ring::mult_vec_to(), n_gb, Ring::n_nonzero_terms(), n_syz, gm_elem::nterms, p, R, reduce_list, and syz_list.
Referenced by GaussElimComputation(), and start_computation().