Macaulay2 Engine: GaussElimComputation::reduce
reduce() [2/3]
void GaussElimComputation::reduce (vec & f) private
Definition at line 152 of file gauss.cpp.
 {
   vecterm head;
   vecterm *result = &head;
   while (f != nullptr)
     {
       int r = f->comp;
       if (gb_list[r] != nullptr)
         {
           // Reduce w.r.t. this term
           ring_elem c = f->coeff;
           c = R->negate(c);
           vec g = R->mult_vec(c, gb_list[r]->f);
           R->add_vec_to(f, g);
         }
       else
         {
           result->next = f;
           f = f->next;
           result = result->next;
         }
     }
   result->next = nullptr;
   f = head.next;
 }
References Ring::add_vec_to(), gm_elem::f, gb_list, Ring::mult_vec(), Ring::negate(), vec::next, and R.