Macaulay2 Engine: GaussElimComputation::GaussElimComputation
GaussElimComputation()
GaussElimComputation::GaussElimComputation (const Matrix * m, int collect_syz, int n_syz)
Definition at line 69 of file gauss.cpp.
     : row(m->n_rows() - 1),
       R(m->get_ring()),
       gens(m),
       n_gb(0),
       n_pairs(0),
       n_syz(0),
       collect_syz(collsyz)
 {
   int i;
   typedef struct gm_elem *gm_elem_ptr;
   reduce_list = newarray(gm_elem_ptr, m->n_rows());
   gb_list = newarray(gm_elem_ptr, m->n_rows());
   for (i = 0; i < m->n_rows(); i++)
     {
       reduce_list[i] = nullptr;
       gb_list[i] = nullptr;
     }
   if (nsyz < 0 || nsyz > m->n_cols()) nsyz = m->n_cols();
   n_comps_per_syz = nsyz;
   Fsyz = m->cols()->sub_space(nsyz);
   for (i = 0; i < m->n_cols(); i++)
     {
       gm_elem *p = new_gen(i);
       insert(p);
     }
 }
References Matrix::cols(), Fsyz, gb_list, insert(), Matrix::n_cols(), n_comps_per_syz, Matrix::n_rows(), new_gen(), newarray, p, reduce_list, and FreeModule::sub_space().