Macaulay2 Engine: GaussElimComputation::new_gen
new_gen()
gm_elem * GaussElimComputation::new_gen (int i) private
Definition at line 20 of file gauss.cpp.
 {
   gm_elem *result = new gm_elem;
   result->f = R->copy_vec(gens->elem(i));
   if (i < n_comps_per_syz)
     result->fsyz = R->make_vec(i, R->one());
   else
     result->fsyz = nullptr;
   result->next = nullptr;
   return result;
 }
References Ring::copy_vec(), Matrix::elem(), gm_elem::f, gm_elem::fsyz, gens, Ring::make_vec(), n_comps_per_syz, gm_elem::next, Ring::one(), and R.
Referenced by GaussElimComputation().