Macaulay2 Engine: DRing::add_term
add_term()
void DRing::add_term (elem & result, long coeff, exponents_t exp) const
Definition at line 1548 of file dpoly.cpp.
 {
   long c;
   ZZp_FROM_INT(P, c, coeff);  // puts it into normal form, just in case.
   if (c == 0) return;
   D.add_term(level, result, c, exp);
 }
References DPoly::add_term(), D, mpfr::exp(), level, P, and ZZp_FROM_INT().
Referenced by Tower::translate().