Macaulay2 Engine: DRing::add
add()
void DRing::add (elem & result, elem a, elem b) const inline
Definition at line 222 of file dpoly.hpp.
  {
    if (a == nullptr)
      result = b;
    else if (b == nullptr)
      result = a;
    else
      {
        TowerPolynomial a1 = D.copy(level, a);
        D.add_in_place(level, a1, b);
        result = a1;
      }
  }
References DPoly::add_in_place(), DPoly::copy(), D, and level.
Referenced by Tower::add().