Macaulay2 Engine: DRing::set_zero
set_zero()
void DRing::set_zero (elem & result) const inline
Definition at line 203 of file dpoly.hpp.
 { result = 0; }
Referenced by Tower::add(), Tower::divide(), Tower::invert(), Tower::mult(), Tower::negate(), Tower::random(), Tower::remainder(), and Tower::subtract().