Macaulay2 Engine: DRing::subtract
subtract()
void DRing::subtract (elem & result, elem a, elem b) const inline
Definition at line 236 of file dpoly.hpp.
   {
     TowerPolynomial a1 = D.copy(level, a);
     D.subtract_in_place(level, a1, b);
     result = a1;
   }
References DPoly::copy(), D, level, and DPoly::subtract_in_place().
Referenced by Tower::negate(), and Tower::subtract().