Macaulay2 Engine: DRing::set_from_mpq
set_from_mpq()
bool DRing::set_from_mpq (TowerPolynomial & result, mpq_srcptr r)
Definition at line 1502 of file dpoly.cpp.
 {
   // returns false if r doesn't lift
   mpz_t a;
   mpz_init(a);
   mpz_mod_ui(a, mpq_numref(r), P);
   long ctop = mpz_get_si(a);
   mpz_mod_ui(a, mpq_denref(r), P);
   long cbottom = mpz_get_si(a);
   mpz_clear(a);
   if (ctop < 0) ctop += P;
   if (cbottom < 0) cbottom += P;
   if (cbottom == 0)
     {
       result = 0;
       return false;
     }
   ZZp_INVERT(P, cbottom, cbottom);
   ZZp_MULT(P, ctop, cbottom);
   result = D.from_long(level, ctop);
   return true;
 }
References D, DPoly::from_long(), level, P, ZZp_INVERT(), and ZZp_MULT().
Referenced by Tower::from_rational().