Macaulay2 Engine: createF4GB
createF4GB()
GBComputation * createF4GB (const Matrix * m, M2_bool collect_syz, int n_rows_to_keep, M2_arrayint gb_weights, int strategy, M2_bool use_max_degree, int max_degree)
Definition at line 25 of file f4-computation.cpp.
{
  const PolynomialRing *R = m->get_ring()->cast_to_PolynomialRing();
  const Ring *K = R->getCoefficients();
  F4Mem *Mem = new F4Mem;
  auto vectorArithmetic = new VectorArithmetic(K);
  // TODO: code here used to detect whether R, K is a valid ring here
  GBComputation *G;
  G = new F4Computation(vectorArithmetic,
                        Mem,
                        m,
                        collect_syz,
                        n_rows_to_keep,
                        gb_weights,
                        strategy,
                        use_max_degree,
                        max_degree);
  return G;
}
References Ring::cast_to_PolynomialRing(), G, Matrix::get_ring(), and RingElement::R.
Referenced by GBComputation::choose_gb().