Macaulay2 Engine: minimalize_varpower_monomials
minimalize_varpower_monomials()
void minimalize_varpower_monomials (const VECTOR(varpower_monomial) & elems, VECTOR(int) & result_minimals, stash * mi_stash = 0)
Definition at line 536 of file f4-monlookup.cpp.
 {
   std::vector<std::pair<int, int>> degs_and_indices;
   int count = 0;
   for (auto& b : elems)
     {
       int deg = varpower_monomials::simple_degree(b);
       degs_and_indices.push_back(std::make_pair(deg, count));
       ++count;
     }
   std::stable_sort(degs_and_indices.begin(), degs_and_indices.end());
   F4MonomialLookupTableT<int> M(10, mi_stash); // 10 is simply a suggested value
   for (auto p : degs_and_indices)
     {
       int k; // unused: we only care if there is a divisor, not which index it has
       if (!M.find_one_divisor_vp(0, elems[p.second], k))
         {
           M.insert_minimal_vp(0, elems[p.second], 0);
           result_minimals.push_back(p.second);
         }
     }
 }
References F4MonomialLookupTableT< Key >::find_one_divisor_vp(), F4MonomialLookupTableT< Key >::insert_minimal_vp(), p, and varpower_monomials::simple_degree().