Macaulay2 Engine: rawDisplayMatrixStream
rawDisplayMatrixStream()
void rawDisplayMatrixStream (const Matrix * inputMatrix)
Definition at line 679 of file groebner.cpp.
 {
   const Ring *R = inputMatrix->get_ring();
   const PolyRing *P = R->cast_to_PolyRing();
   if (P == 0)
     {
       ERROR("expected a polynomial ring");
       return;
     }
   if (P->characteristic() > std::numeric_limits<int>::max())
     {
       ERROR("characteristic is too large for mathic gb computation");
       return;
     }
   int charac = static_cast<int>(P->characteristic());
   int nvars = P->n_vars();
   mgb::GroebnerConfiguration configuration(
       charac, nvars, inputMatrix->n_rows());
   mgb::GroebnerInputIdealStream input(configuration);
   std::ostringstream computedStr;
   mgb::IdealStreamLog<> computed(
       computedStr, charac, nvars, inputMatrix->n_rows());
   mgb::IdealStreamChecker<decltype(computed)> checked(computed);
   matrixToStream(inputMatrix, checked);
   std::cout << "result: " << std::endl;
   std::cout << computedStr.str() << std::endl;
 }
References Ring::cast_to_PolyRing(), Ring::characteristic(), ERROR(), Matrix::get_ring(), matrixToStream(), max, Matrix::n_rows(), PolynomialRing::n_vars(), RingMap::nvars, RingMap::P, and RingMap::R.