Macaulay2 Engine: IM2_GB_force
IM2_GB_force()
Computation* IM2_GB_force (const Matrix * m, const Matrix * gb, const Matrix * change, const Matrix * syz)
Definition at line 181 of file groebner.cpp.
 {
   test_over_RR_or_CC(m->get_ring());
   try
     {
       return GBDeclared::create(m, gb, change, syz);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References GBDeclared::create(), ERROR(), gb(), Matrix::get_ring(), and test_over_RR_or_CC().