Macaulay2 Engine: rawNCGroebnerBasisTwoSided
rawNCGroebnerBasisTwoSided()
const Matrix* rawNCGroebnerBasisTwoSided (const Matrix * input, int maxdeg, int strategy)
Definition at line 910 of file groebner.cpp.
 {
   const Ring* R = input->get_ring();
   const M2FreeAlgebra* A = R->cast_to_M2FreeAlgebra();
   if (A != nullptr and input->n_rows() == 1)
     {
       auto elems = matrixToPolyList(A, input);
       bool isF4 = strategy & 16;
       bool isParallel = strategy & 32;
       if (isF4)
         {
           int numthreads = M2_numTBBThreads; // settable from front end.
           // std::cout << "Using numthreads = " << numthreads << std::endl;
           NCF4 G(A->freeAlgebra(), elems, maxdeg, strategy, (isParallel ? numthreads : 1));
           G.compute(maxdeg); // this argument is actually the soft degree limit
           auto result = copyPolyVector(A, G.currentValue());
           return polyListToMatrix(A, result, 1, result.size()); // consumes the Poly's in result
         }
       else
         {
           NCGroebner G(A->freeAlgebra(), elems, maxdeg, strategy);
           G.compute(maxdeg); // this argument is actually the soft degree limit
           auto result = copyPolyVector(A, G.currentValue());
           return polyListToMatrix(A, result, 1, result.size()); // consumes the Poly's in result
         }
     }
   ERROR("expected a one row matrix over a noncommutative algebra");
   return nullptr;
 }
References Ring::cast_to_M2FreeAlgebra(), NCF4::compute(), NCGroebner::compute(), copyPolyVector(), NCF4::currentValue(), NCGroebner::currentValue(), ERROR(), M2FreeAlgebra::freeAlgebra(), Matrix::get_ring(), M2_numTBBThreads, matrixToPolyList(), Matrix::n_rows(), and polyListToMatrix().