Macaulay2 Engine: monomialOrderingToMatrix
monomialOrderingToMatrix()
bool monomialOrderingToMatrix (const struct MonomialOrdering & mo, std::vector< int > & mat, bool & base_is_revlex, int & component_direction, int & component_is_before_row)
Definition at line 861 of file monomial-ordering.cpp.
 {
   // a false return value means an error has occurred.
   int nvars = rawNumberOfVariables(&mo);
   base_is_revlex = true;
   enum LastBlock { LEX, REVLEX, WEIGHTS, NONE };
   LastBlock last = NONE;
   int nwts = 0;  // local var used in MO_WEIGHTS section
   int nrows = 0;
   int firstvar = 0;
   component_direction = 0;
   component_is_before_row =
       -2;                   // what should the default value be?  Probably: -1.
   size_t last_element = 0;  // The vector 'mat' will be resized back to this
                             // value if the last part of the order is lex or
                             // revlex.
   for (int i = 0; i < mo.len; i++)
     {
       mon_part p = mo.array[i];
       switch (p->type)
         {
           case MO_LEX:
           case MO_LEX2:
           case MO_LEX4:
             // printf("lex %d\n", p->nvars);
             last_element = mat.size();
             for (int j = 0; j < p->nvars; j++)
               {
                 write_row(mat, nvars, firstvar + j, 1);
               }
             last = LEX;
             firstvar += p->nvars;
             nrows += p->nvars;
             break;
           case MO_GREVLEX:
           case MO_GREVLEX2:
           case MO_GREVLEX4:
             // printf("grevlex %d %ld\n", p->nvars, p->wts);
             write_weights(mat, nvars, firstvar, p->wts, p->nvars);
             last_element = mat.size();
             for (int j = p->nvars - 1; j >= 1; --j)
               {
                 write_row(mat, nvars, firstvar + j, -1);
               }
             last = REVLEX;
             firstvar += p->nvars;
             nrows += p->nvars;
             break;
           case MO_GREVLEX_WTS:
           case MO_GREVLEX2_WTS:
           case MO_GREVLEX4_WTS:
             // printf("grevlex_wts %d %ld\n", p->nvars, p->wts);
             write_weights(mat, nvars, firstvar, p->wts, p->nvars);
             last_element = mat.size();
             for (int j = p->nvars - 1; j >= 1; --j)
               {
                 write_row(mat, nvars, firstvar + j, -1);
               }
             last = REVLEX;
             firstvar += p->nvars;
             nrows += p->nvars;
             break;
           case MO_REVLEX:
             // printf("revlex %d\n", p->nvars);
             last_element = mat.size();
             for (int j = p->nvars - 1; j >= 0; --j)
               {
                 write_row(mat, nvars, firstvar + j, -1);
               }
             last = REVLEX;
             firstvar += p->nvars;
             nrows += p->nvars;
             break;
           case MO_WEIGHTS:
             // printf("matsize= %d weights %d p->wts=%lu\n", mat.size(),
             // p->nvars, p->wts);
             nwts = (p->nvars > nvars ? nvars : p->nvars);
             write_weights(mat, nvars, 0, p->wts, nwts);
             nrows++;
             last_element = mat.size();
             last = WEIGHTS;
             break;
           case MO_LAURENT:
           case MO_LAURENT_REVLEX:
           case MO_NC_LEX:
             return false;
             break;
           case MO_POSITION_UP:
             component_direction = 1;
             component_is_before_row = nrows;
             break;
           case MO_POSITION_DOWN:
             component_direction = -1;
             component_is_before_row = nrows;
             break;
           default:
             // DO nothing
             break;
         }
     }
   if (last == LEX)
     {
       // last block was lex, so use lex tie-breaker
       mat.resize(last_element);
       if (nrows == component_is_before_row) component_is_before_row = -1;
       base_is_revlex = false;
     }
   else if (last == REVLEX)
     {
       // last block was revlex, so use revlex tie-breaker
       if (nrows == component_is_before_row) component_is_before_row = -1;
       mat.resize(last_element);
     }
   else
     {
       // last block is a weight vector, so use revlex as the tie-breaker.
       // nothing to change here.
     }
   return true;
 }
References MonomialOrdering::array, MonomialOrdering::len, MO_GREVLEX, MO_GREVLEX2, MO_GREVLEX2_WTS, MO_GREVLEX4, MO_GREVLEX4_WTS, MO_GREVLEX_WTS, MO_LAURENT, MO_LAURENT_REVLEX, MO_LEX, MO_LEX2, MO_LEX4, MO_NC_LEX, MO_POSITION_DOWN, MO_POSITION_UP, MO_REVLEX, MO_WEIGHTS, mon_part::nvars, p, rawNumberOfVariables(), write_row(), and write_weights().
Referenced by rawMGB(), and rawMonomialOrderingToMatrix().