Macaulay2 Engine: rawResolutionBetti
rawResolutionBetti()
M2_arrayintOrNull rawResolutionBetti (Computation * C, int type)
Definition at line 585 of file groebner.cpp.
 {
   try
     {
       ResolutionComputation *G = C->cast_to_ResolutionComputation();
       if (G != 0) return G->get_betti(type);
       ERROR("expected resolution computation type");
       return nullptr;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Computation::cast_to_ResolutionComputation(), ERROR(), and ResolutionComputation::get_betti().