Macaulay2 Engine: IM2_Computation_set_stop
IM2_Computation_set_stop()
Computation* IM2_Computation_set_stop (Computation * G, M2_bool always_stop, M2_arrayint degree_limit, int basis_element_limit, int syzygy_limit, int pair_limit, int codim_limit, int subring_limit, M2_bool just_min_gens, M2_arrayint length_limit)
Definition at line 219 of file groebner.cpp.
 {
   try
     {
       clear_emit_size();
       return G->set_stop_conditions(always_stop,
                                     degree_limit,
                                     basis_element_limit,
                                     syzygy_limit,
                                     pair_limit,
                                     codim_limit,
                                     subring_limit,
                                     just_min_gens,
                                     length_limit);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References clear_emit_size(), ERROR(), and Computation::set_stop_conditions().