Macaulay2 Engine: polyListToMatrix
polyListToMatrix()
template<typename PolyL > const Matrix* polyListToMatrix (const M2FreeAlgebraOrQuotient * A, const PolyL & elems, int numrows, int numcols)
Definition at line 891 of file groebner.cpp.
 {
   if (elems.size() != numrows*numcols)
     ERROR("Number of elements in list does not match matrix size.");
   MatrixConstructor mat(A->make_FreeModule(numrows), numcols);
   for (auto i = 0; i < elems.size(); ++i)
     {
       int curCol = i % numcols;
       int curRow = (i - curCol) / numcols;
       ring_elem a = const_cast<Nterm*>(reinterpret_cast<const Nterm*>(elems[i]));
       mat.set_entry(curRow, curCol, a);
     }
   mat.compute_column_degrees();
   return mat.to_matrix();
 }
References MatrixConstructor::compute_column_degrees(), ERROR(), Ring::make_FreeModule(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by rawNCBasis(), rawNCGroebnerBasisTwoSided(), and rawNCReductionTwoSided().