Macaulay2 Engine: rawStartComputation
rawStartComputation()
Computation* rawStartComputation (Computation * C)
Definition at line 262 of file groebner.cpp.
 {
   try
     {
       clear_emit_size();
       C->start_computation();
       if (M2_gbTrace == 15)
         {
           ComputationStatusCode ret = C->status();
           switch (ret)
             {
               case COMP_DONE_DEGREE_LIMIT:
                 emit_line("computation stopped at degree limit");
                 break;
               case COMP_DONE:
                 emit_line("computation of GB completed");
                 break;
               case COMP_DONE_PAIR_LIMIT:
                 emit_line("computation stopped at pair limit");
                 break;
               case COMP_NEED_RESIZE:
               case COMP_ERROR:
               case COMP_INTERRUPTED:
               case COMP_NOT_STARTED:
               case COMP_INITIAL_STOP:
               case COMP_DONE_LENGTH_LIMIT:
               case COMP_DONE_SYZYGY_LIMIT:
               case COMP_DONE_GB_LIMIT:
               case COMP_DONE_SYZ_LIMIT:
               case COMP_DONE_CODIM:
               case COMP_DONE_MIN_GENS:
               case COMP_DONE_STEPS:
               case COMP_DONE_SUBRING_LIMIT:
               case COMP_COMPUTING:
               case COMP_OVERFLOWED:
                 emit_line("computation stopped for some good reason");
                 break;
               default:
                 emit_line("incorrect status code encountered");
                 break;
             }
         }
       return error() ? nullptr : C;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References clear_emit_size(), COMP_COMPUTING, COMP_DONE, COMP_DONE_CODIM, COMP_DONE_DEGREE_LIMIT, COMP_DONE_GB_LIMIT, COMP_DONE_LENGTH_LIMIT, COMP_DONE_MIN_GENS, COMP_DONE_PAIR_LIMIT, COMP_DONE_STEPS, COMP_DONE_SUBRING_LIMIT, COMP_DONE_SYZ_LIMIT, COMP_DONE_SYZYGY_LIMIT, COMP_ERROR, COMP_INITIAL_STOP, COMP_INTERRUPTED, COMP_NEED_RESIZE, COMP_NOT_STARTED, COMP_OVERFLOWED, emit_line(), error(), ERROR(), M2_gbTrace, Computation::start_computation(), and Computation::status().