Macaulay2 Engine: matrixToPolyList
matrixToPolyList()
ConstPolyList matrixToPolyList (const M2FreeAlgebraOrQuotient * A, const Matrix * input)
Definition at line 882 of file groebner.cpp.
 {
   ConstPolyList result;
   result.reserve(input->n_cols() * input->n_rows());
   for (int i=0; i < input->n_rows(); i++)
     {
       for (int j=0; j < input->n_cols(); ++j)
       {
         ring_elem a = input->elem(i,j);
         auto f = reinterpret_cast<const Poly*>(a.get_Poly());
         result.push_back(f);
       }
     }
   return result;
 }
References Matrix::elem(), ring_elem::get_Poly(), Matrix::n_cols(), and Matrix::n_rows().
Referenced by rawNCBasis(), rawNCGroebnerBasisTwoSided(), and rawNCReductionTwoSided().