Macaulay2 Engine: rawResolutionGetMatrix
rawResolutionGetMatrix()
const Matrix* rawResolutionGetMatrix (Computation * C, int level)
Definition at line 474 of file groebner.cpp.
 {
   try
     {
       clear_emit_size();
       ResolutionComputation *G = C->cast_to_ResolutionComputation();
       if (G != 0) return G->get_matrix(level);
       ERROR("expected resolution computation type");
       return 0;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Computation::cast_to_ResolutionComputation(), clear_emit_size(), ERROR(), and ResolutionComputation::get_matrix().