Macaulay2 Engine: IM2_GB_contains
IM2_GB_contains()
int IM2_GB_contains (Computation * C, const Matrix * m)
Definition at line 445 of file groebner.cpp.
 {
   try
     {
       clear_emit_size();
       GBComputation *G = C->cast_to_GBComputation();
       if (G != 0) return G->contains(m);
       ERROR("computation type unknown or not implemented");
       return -2;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return -2;
   }
 }
References Computation::cast_to_GBComputation(), clear_emit_size(), GBComputation::contains(), and ERROR().