Macaulay2 Engine: IM2_res_make
IM2_res_make()
Computation* IM2_res_make (const Matrix * m, M2_bool resolve_cokernel, int max_level, M2_bool use_max_slanted_degree, int max_slanted_degree, int algorithm, int strategy)
Definition at line 122 of file groebner.cpp.
 {
   try
     {
       test_over_RR_or_CC(m->get_ring());
       // Choose the correct computation here.
       clear_emit_size();
       return ResolutionComputation::choose_res(m,
                                                resolve_cokernel,
                                                max_level,
                                                use_max_slanted_degree,
                                                max_slanted_degree,
                                                algorithm,
                                                strategy);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References ResolutionComputation::choose_res(), clear_emit_size(), ERROR(), Matrix::get_ring(), and test_over_RR_or_CC().