Macaulay2 Engine: mpfr::mpreal::mpreal
mpreal() [1/16]
mpfr::mpreal::mpreal () inline
Definition at line 581 of file mpreal.h.
 {
     mpfr_init2(mpfr_ptr(), mpreal::get_default_prec());
     mpfr_set_zero_fast(mpfr_ptr());
     MPREAL_MSVC_DEBUGVIEW_CODE;
 }
References get_default_prec(), mpfr_ptr(), mpfr_set_zero_fast, and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by operator*=(), operator+(), operator+=(), operator-=(), and operator/=().