Macaulay2 Engine: mpfr::mpreal::get_default_rnd
get_default_rnd()
static mp_rnd_t mpfr::mpreal::get_default_rnd () inline static
Definition at line 157 of file mpreal.h.
 {    return (mp_rnd_t)(mpfr_get_default_rounding_mode());       }
Referenced by mpfr::ldexp(), mpreal(), mpfr::negate(), mpfr::operator*(), operator*=(), mpfr::operator+(), operator+=(), operator-(), mpfr::operator-(), operator-=(), mpfr::operator/(), operator/=(), operator<<=(), operator=(), operator>>=(), output(), std::numeric_limits< mpfr::mpreal >::round_error(), and std::numeric_limits< mpfr::mpreal >::round_style().