Macaulay2 Engine: mpfr::mpreal::operator=
operator=() [2/15]
mpreal & mpfr::mpreal::operator= (const double v) inline
Definition at line 977 of file mpreal.h.
 {
 #if (MPREAL_DOUBLE_BITS_OVERFLOW > -1)
     if(fits_in_bits(v, MPREAL_DOUBLE_BITS_OVERFLOW))
     {
         mpfr_set_d(mpfr_ptr(),v,mpreal::get_default_rnd());
     }else
         throw conversion_overflow();
 #else
     mpfr_set_d(mpfr_ptr(),v,mpreal::get_default_rnd());
 #endif
     MPREAL_MSVC_DEBUGVIEW_CODE;
     return *this;
 }
References fits_in_bits(), get_default_rnd(), mpfr_ptr(), MPREAL_DOUBLE_BITS_OVERFLOW, and MPREAL_MSVC_DEBUGVIEW_CODE.