Macaulay2 Engine: mpfr::mpreal::mpfr_srcptr
mpfr_srcptr()
mpfr_srcptr mpfr::mpreal::mpfr_srcptr () const inline
Definition at line 1742 of file mpreal.h.
{ return mp; }
Referenced by mpfr::atan2pi(), mpfr::atan2u(), mpfr::beta(), mpfr::copysign(), mpfr::frexp(), mpfr::gammainc(), get_exp(), get_prec(), getPrecision(), mpreal(), mpfr::operator*(), operator*=(), operator*=(), operator*=(), operator*=(), operator*=(), operator*=(), operator*=(), operator*=(), mpfr::operator+(), operator+=(), operator+=(), operator+=(), operator+=(), operator+=(), operator+=(), operator+=(), operator+=(), operator-(), mpfr::operator-(), operator-=(), operator-=(), operator-=(), operator-=(), operator-=(), operator-=(), operator-=(), operator-=(), mpfr::operator/(), operator/=(), operator/=(), operator/=(), operator/=(), operator/=(), operator/=(), operator/=(), operator/=(), mpfr::operator<(), mpfr::operator<(), mpfr::operator<(), mpfr::operator<(), mpfr::operator<(), mpfr::operator<(), mpfr::operator<(), operator<<=(), operator<<=(), operator<<=(), operator<<=(), mpfr::operator<=(), mpfr::operator<=(), mpfr::operator<=(), mpfr::operator<=(), mpfr::operator<=(), mpfr::operator<=(), mpfr::operator<=(), operator=(), operator=(), operator=(), mpfr::operator==(), mpfr::operator==(), mpfr::operator==(), mpfr::operator==(), mpfr::operator==(), mpfr::operator==(), mpfr::operator==(), mpfr::operator>(), mpfr::operator>(), mpfr::operator>(), mpfr::operator>(), mpfr::operator>(), mpfr::operator>(), mpfr::operator>(), mpfr::operator>=(), mpfr::operator>=(), mpfr::operator>=(), mpfr::operator>=(), mpfr::operator>=(), mpfr::operator>=(), mpfr::operator>=(), operator>>=(), operator>>=(), operator>>=(), operator>>=(), output(), mpfr::powr(), setSign(), toBool(), toDouble(), toFloat(), toLDouble(), toLLong(), toLong(), toString(), toString(), toULLong(), and toULong().