Macaulay2 Engine: mpfr::mpreal::mpfr_ptr
mpfr_ptr() [1/2]
mpfr_ptr mpfr::mpreal::mpfr_ptr () inline
Definition at line 1740 of file mpreal.h.
{ return mp; }
Referenced by mpfr::atan2pi(), mpfr::atan2u(), mpfr::beta(), check_range(), mpfr::compound(), mpfr::copysign(), mpfr::frexp(), mpfr::gammainc(), mpfr::log_ui(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpreal(), mpfr::operator*(), operator*=(), operator*=(), operator*=(), operator*=(), operator*=(), operator*=(), operator*=(), operator*=(), mpfr::operator+(), operator+=(), operator+=(), operator+=(), operator+=(), operator+=(), operator+=(), operator+=(), operator+=(), operator-(), mpfr::operator-(), operator-=(), operator-=(), operator-=(), operator-=(), operator-=(), operator-=(), operator-=(), operator-=(), mpfr::operator/(), operator/=(), operator/=(), operator/=(), operator/=(), operator/=(), operator/=(), operator/=(), operator/=(), operator<<=(), operator<<=(), operator<<=(), operator<<=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator>>=(), operator>>=(), operator>>=(), operator>>=(), mpfr::powr(), set_exp(), set_prec(), setInf(), setNan(), setPrecision(), setSign(), setZero(), subnormalize(), and ~mpreal().