Macaulay2 Engine: mpfr::mpreal::setSign
setSign()
mpreal & mpfr::mpreal::setSign (int Sign, mp_rnd_t RoundingMode = get_default_rnd()) inline
Definition at line 1953 of file mpreal.h.
 {
     mpfr_setsign(mpfr_ptr(), mpfr_srcptr(), sign < 0, RoundingMode);
     MPREAL_MSVC_DEBUGVIEW_CODE;
     return *this;
 }
References mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.
Referenced by setZero().