Macaulay2 Engine: mpfr::mpreal::fits_in_bits
fits_in_bits()
bool mpfr::mpreal::fits_in_bits (double x, int n) inline
Definition at line 2897 of file mpreal.h.
 {
     int i;
     double t;
     return IsInf(x) || (std::modf ( std::ldexp ( std::frexp ( x, &i ), n ), &t ) == 0.0);
 }
References mpfr::frexp(), IsInf, mpfr::ldexp(), mpfr::modf(), and x.
Referenced by mpreal(), and operator=().