Macaulay2 Engine: mpfr::mpreal::operator=
operator=() [12/15]
mpreal & mpfr::mpreal::operator= (const std::string & s) inline
Definition at line 1064 of file mpreal.h.
 {
     // Use other converters for more precise control on base & precision & rounding:
     //
     //        mpreal(const char* s,        mp_prec_t prec, int base, mp_rnd_t mode)
     //        mpreal(const std::string& s,mp_prec_t prec, int base, mp_rnd_t mode)
     //
     // Here we assume base = 10 and we use precision of target variable.
     mpfr_t t;
     mpfr_init2(t, mpfr_get_prec(mpfr_srcptr()));
     if(0 == mpfr_set_str(t, s.c_str(), 10, mpreal::get_default_rnd()))
     {
         mpfr_set(mpfr_ptr(), t, mpreal::get_default_rnd());
         MPREAL_MSVC_DEBUGVIEW_CODE;
     }
     clear(t);
     return *this;
 }
References clear(), get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.