Macaulay2 Engine: mpfr::mpreal::operator=
operator=() [9/15]
mpreal & mpfr::mpreal::operator= (const mpreal & v) inline
Definition at line 926 of file mpreal.h.
 {
     if (this != &v)
     {
         mp_prec_t tp = mpfr_get_prec(  mpfr_srcptr());
         mp_prec_t vp = mpfr_get_prec(v.mpfr_srcptr());
         if(tp != vp){
             clear(mpfr_ptr());
             mpfr_init2(mpfr_ptr(), vp);
         }
         mpfr_set(mpfr_ptr(), v.mpfr_srcptr(), mpreal::get_default_rnd());
         MPREAL_MSVC_DEBUGVIEW_CODE;
     }
     return *this;
 }
References clear(), get_default_rnd(), mpfr_ptr(), mpfr_srcptr(), and MPREAL_MSVC_DEBUGVIEW_CODE.