Macaulay2 Engine: MutableComplex::find_unit
find_unit()
bool MutableComplex::find_unit (iterator & i, const size_t flags) const
Definition at line 78 of file mutablecomplex.cpp.
 {
   if (!(flags & FLAG_BEST_UNIT)) return next_unit(i, flags);
   iterator j(*this, i.index());
   if (!next_unit(j, flags)) return false;
   size_t t = -1, s = complexity(j, flags);
   while (next_unit(j, flags))
     {
       s = complexity(j, flags);
       if (s < t)
         {
           t = s;
           *i = *j;
         }
       ++j;
     }
   return true;
 }
References complexity(), FLAG_BEST_UNIT, MutableComplex::iterator::index(), and next_unit().
Referenced by prune_matrix().