Macaulay2 Engine: MutableComplex::prune_matrix
prune_matrix()
void MutableComplex::prune_matrix (size_t n, const size_t flags)
Definition at line 164 of file mutablecomplex.cpp.
 {
   iterator i(*this, n);
   while (find_unit(i, flags))
     {
       prune_unit(i, flags);
       *i = *iterator(*this, n);
     }
 }
References find_unit(), and prune_unit().
Referenced by prune_complex().