Macaulay2 Engine: MutableComplex::prune_unit
prune_unit()
void MutableComplex::prune_unit (const iterator & i, const size_t flags)
Definition at line 116 of file mutablecomplex.cpp.
 {
   const size_t n = i.index();
   const std::pair<size_t, size_t> u = *i;
   const bool trace = flags & FLAG_TRACE_MORPHISMS;
   /* There is some redundancy here, can set some stuff to zero.
      TODO: Maybe check to see which is more efficient?
            Compare with using rawReduceByPivot
   */
   // Move to last row
   mDifferential[n]->interchange_rows(u.first, mBetti[n] - 1);
   if (0 < n) mDifferential[n - 1]->interchange_columns(u.first, mBetti[n] - 1);
   if (trace) mMorphisms[n]->interchange_columns(u.first, mBetti[n] - 1);
   // Move to last column
   mDifferential[n]->interchange_columns(u.second, mBetti[n + 1] - 1);
   if (n < mDifferential.size() - 1)
     mDifferential[n + 1]->interchange_rows(u.second, mBetti[n + 1] - 1);
   if (trace)
     mMorphisms[n + 1]->interchange_columns(u.second, mBetti[n + 1] - 1);
   // Get the pivot
   ring_elem p, q, f;
   mDifferential[n]->get_entry(mBetti[n] - 1, mBetti[n + 1] - 1, p);
   p = mRing->invert(p);
   q = mRing->negate(p);
   // Clear the column
   for (size_t r = 0; r < mBetti[n] - 1; ++r)
     {
       mDifferential[n]->get_entry(r, mBetti[n + 1] - 1, f);
       mDifferential[n]->row_op(r, mRing->mult(f, q), mBetti[n] - 1);
       if (0 < n)
         mDifferential[n - 1]->column_op(mBetti[n] - 1, mRing->mult(f, p), r);
       if (trace) mMorphisms[n]->column_op(mBetti[n] - 1, mRing->mult(f, p), r);
     }
   // Clear the row
   for (size_t c = 0; c < mBetti[n + 1] - 1; ++c)
     {
       mDifferential[n]->get_entry(mBetti[n] - 1, c, f);
       mDifferential[n]->column_op(c, mRing->mult(f, q), mBetti[n + 1] - 1);
       if (n < mDifferential.size() - 1)
         mDifferential[n + 1]->row_op(mBetti[n + 1] - 1, mRing->mult(f, p), c);
       if (trace)
         mMorphisms[n + 1]->column_op(c, mRing->mult(f, q), mBetti[n + 1] - 1);
     }
   --mBetti[n];
   --mBetti[n + 1];
 }
References FLAG_TRACE_MORPHISMS, MutableComplex::iterator::index(), Ring::invert(), mBetti, mDifferential, mMorphisms, mRing, Ring::mult(), Ring::negate(), and p.
Referenced by prune_matrix().