Macaulay2 Engine: MutableComplex::prune_complex
prune_complex()
void MutableComplex::prune_complex (const size_t nsteps, const size_t flags)
Definition at line 174 of file mutablecomplex.cpp.
 {
   // Initialize pruning maps
   const bool dense = mDifferential[0]->is_dense();
   if (flags & FLAG_TRACE_MORPHISMS)
     for (size_t n = 0; n < mDifferential.size() + 1; ++n)
       mMorphisms.push_back(MutableMatrix::identity(mRing, mBetti[n], dense));
   for (size_t n = 0; n < mDifferential.size() && n < nsteps; n++)
     {
       if (flags & FLAG_REV_ORDER)
         prune_matrix(mDifferential.size() - n - 1, flags);
       else
         prune_matrix(n, flags);
     }
 }
References FLAG_REV_ORDER, FLAG_TRACE_MORPHISMS, MutableMatrix::identity(), mBetti, mDifferential, mMorphisms, mRing, and prune_matrix().
Referenced by rawPruneComplex().