Macaulay2 Engine: BIBasis::FastAllocator::ExpandMemory
ExpandMemory()
void BIBasis::FastAllocator::ExpandMemory () private
Definition at line 34 of file allocator.cpp.
     {
         void **begin = static_cast<void**>(malloc(MemoryPageSize)),
              **end = begin + TSize * (PageSize - 1),
              **tmp;
         if (!begin)
         {
             throw std::string("BIB::FastAllocator::ExpandMemory(): failed to allocate memory.");
         }
         *(reinterpret_cast<void***>(end)) = FreeBlock;
         FreeBlock = static_cast<void**>(begin);
         do
         {
             tmp = begin + TSize;
             *(reinterpret_cast<void***>(begin)) = tmp;
             begin = tmp;
         } while(begin < end);
     }
References begin(), end(), FreeBlock, MemoryPageSize, PageSize, and TSize.
Referenced by Allocate().