Macaulay2 Engine: remove_monideal
remove_monideal()
void remove_monideal (void * p, void * cd)
Definition at line 49 of file finalize.cpp.
 {
 #ifdef MEMDEBUG
   p = M2_debug_to_inner(p);
 #endif
   MonomialIdeal *G = static_cast<MonomialIdeal *>(p);
   AO_t nremoved = AO_fetch_and_add1(&monideals_nremoved);
   if (M2_gbTrace >= 3)
     fprintf(stderr, "\n -- removing monomial ideal %zd at %p\n", nremoved, G);
   G->remove_MonomialIdeal();
 }
References AO_fetch_and_add1(), M2_gbTrace, monideals_nremoved, p, and MonomialIdeal::remove_MonomialIdeal().
Referenced by intern_monideal().