Macaulay2 Engine: intern_monideal
intern_monideal()
void intern_monideal (MonomialIdeal * G)
Definition at line 54 of file finalize.cpp.
 {
 #ifdef MEMDEBUG
   GC_REGISTER_FINALIZER(M2_debug_to_outer(G), remove_monideal, 0, 0, 0);
 #else
   GC_REGISTER_FINALIZER(G,                    remove_monideal, nullptr, nullptr, nullptr);
 #endif
   std::atomic<int> nfinalized = monideals_nfinalized++;
   if (M2_gbTrace >= 3)
     fprintf(stderr,
             "\n   -- registering monomial ideal %d at %p\n",
             nfinalized.load(),
             (void *)G);
 }
References G, M2_gbTrace, monideals_nfinalized, and remove_monideal().
Referenced by IM2_MonomialIdeal_borel(), IM2_MonomialIdeal_intersect(), IM2_MonomialIdeal_make(), rawAlexanderDual(), rawColonMonomialIdeal1(), rawColonMonomialIdeal2(), rawMaximalIndependentSets(), rawMonomialMinimalPrimes(), rawRadicalMonomialIdeal(), rawSaturateMonomialIdeal1(), and rawSaturateMonomialIdeal2().