Macaulay2 Engine: internMutableMatrix
internMutableMatrix()
MutableMatrix* internMutableMatrix (MutableMatrix * G)
Definition at line 196 of file finalize.cpp.
 {
   if (G == 0) return 0;
 #ifdef MEMDEBUG
   GC_REGISTER_FINALIZER(M2_debug_to_outer(G), remove_MutableMatrix, 0, 0, 0);
 #else
   GC_REGISTER_FINALIZER(                  G,  remove_MutableMatrix, 0, 0, 0);
 #endif
   AO_t nfinalized = AO_fetch_and_add1(&mutablematrices_nfinalized);
   if (M2_gbTrace >= 3)
     fprintf(stderr,
             "\n   -- registering mutable matrix %zd at %p\n",
             nfinalized,
             (void *)G);
   return G;
 }
References AO_fetch_and_add1(), M2_gbTrace, mutablematrices_nfinalized, and remove_MutableMatrix().
Referenced by IM2_MutableMatrix_copy(), IM2_MutableMatrix_from_matrix(), IM2_MutableMatrix_identity(), IM2_MutableMatrix_make(), IM2_MutableMatrix_submatrix(), IM2_MutableMatrix_submatrix1(), rawLinAlgInverse(), rawLinAlgMult(), rawLinAlgNullSpace(), rawLinAlgRREF(), rawLinAlgSolve(), rawLinAlgSolveInvertible(), and rawMutableMatrixTranspose().