Macaulay2 Engine: MonomialHashTable::find_or_insert
find_or_insert()
template<typename ValueType > bool MonomialHashTable< ValueType >::find_or_insert (value m, value & result)
Definition at line 83 of file monhashtable.cpp.
 {
   auto mhash = HASHVALUE(m);
   auto hashval = mhash & hashmask;
   if (!hashtab[hashval])
     {
       // No entry is there.  So, we insert it directly.
       hashtab[hashval] = m;
       result = m;
       count++;
       if (count > threshold) grow();
       return false;
     }
   else
     {
       // Something is there, so we need to find either this value,
       // or a free spot, whichever comes first.
       value *hashtop = hashtab.get() + size;
       for (value *i = hashtab.get() + hashval;; i++)
         {
           if (i == hashtop) i = hashtab.get();
           if (!(*i))
             {
               // Spot is empty, so m is a new value
               *i = m;
               result = m;
               count++;
               if (count > threshold) grow();
               return false;
             }
           //          if (HASHVALUE(*i) == mhash)
           //            {
           if (MONOMIAL_EQUAL(m, *i))
             {
               result = *i;
               return true;
             }
           //            }
         }
     }
 }
References HASHVALUE.
Referenced by F4GB::find_or_append_column(), F4GB::mult_monomials(), and F4Res::processCurrentMonomial().