Macaulay2 Engine: M2_tostring
M2_tostring()
M2_string M2_tostring (M2_constcharstarOrNull s)
Definition at line 33 of file M2-replacement.c.
 {
   int n = s ? strlen(s) : 0;
   M2_string p = getmematomicarraytype(M2_string,n);
   p->len = n;
   memcpy(p->array,s,n);
   //GC_CHECK_CLOBBER(p);
   return p;
 }
References getmematomicarraytype, and p.
Referenced by IM2_last_error_message(), IM2_MonomialOrdering_to_string(), intarray_to_string(), ones_to_string(), and stdvector_to_M2_ArrayString().