Macaulay2 Engine: M2_tostringn
M2_tostringn()
M2_string M2_tostringn (char * s, int n)
Definition at line 42 of file M2-replacement.c.
{
    M2_string p = (M2_string)getmem_atomic(sizeofarray(p,n));
    p->len = n;
    memcpy(p->array,s,n);
    //GC_CHECK_CLOBBER(p);
    return p;
}
References getmem_atomic(), p, and sizeofarray.
Referenced by string_std_to_M2(), and buffer::to_string().