Macaulay2 Engine: M2_makearrayint
M2_makearrayint()
M2_arrayint M2_makearrayint (int n)
Definition at line 8 of file M2-replacement.c.
 {
   M2_arrayint z = (M2_arrayint)getmem_atomic(sizeofarray(z,n));
   z->len = n;
   //GC_CHECK_CLOBBER(z);
   return z; /* Note that getmem_atomic returns zeroed memory */
 }
References getmem_atomic(), and sizeofarray.
Referenced by BettiDisplay::betti_make(), ResolutionComputation::betti_make(), SLP< Field >::concatenate(), SLP< Field >::copy(), GBWeight::GBWeight(), FF_LUComputation::get_column_permutation(), IM2_FreeModule_get_degrees(), SLP< Field >::jacobian(), MonomialIdeal::lcm(), Lapack::LU(), SLP< Field >::make(), GBWalker::make_gb(), PolyRingQuotient::make_gb(), MatrixSorter::MatrixSorter(), moGetWeightValues(), ffpackInterface::rankProfile(), rawFactorBase(), rawMonomialOrderingToMatrix(), rawNonTermOrderVariables(), rawPruneBetti(), M2::ARingGFGivaro::representationToM2Array(), Monoid::set_degrees(), res_comp::skeleton_stats(), stdvector_to_M2_arrayint(), Matrix::support(), FreeAlgebra::support(), FractionField::support(), LocalRing::support(), PolyRing::support(), Ring::support(), Tower::support(), PolyRingQuotient::syzygy(), Monoid::to_arrayint(), and ExponentList< E, L >::to_arrayint().