Macaulay2 Engine: toMatrix
toMatrix()
const Matrix * toMatrix (const FreeModule * target, const BasicPolyList & Fs)
Definition at line 5 of file BasicPolyList.cpp.
{
  MatrixStream S(target);
  toStream(Fs, S);
  return S.value();
}
References toStream(), and MatrixStream::value().
Referenced by rawMatrixReadMsolveFile(), rawMatrixReadMsolveString(), TEST(), and TEST().