Macaulay2 Engine: FreeAlgebra::add
add() [1/2]
void FreeAlgebra::add (Poly & result, const Poly & f, const Poly & g) const
Definition at line 388 of file FreeAlgebra.cpp.
 {
   addScalarMultipleOf(result,
                       f.cbegin(),
                       f.cend(),
                       g.cbegin(),
                       g.cend(),
                       coefficientRing()->one());
 }
References addScalarMultipleOf(), coefficientRing(), and Ring::one().