Macaulay2 Engine: FreeAlgebra::makeMonicInPlace
makeMonicInPlace()
void FreeAlgebra::makeMonicInPlace (Poly & f) const
Definition at line 773 of file FreeAlgebra.cpp.
 {
   ring_elem c = f.cbegin().coeff();
   for (auto iter = f.beginCoeff(); iter != f.endCoeff(); ++iter)
     *iter = coefficientRing()->divide(*iter,c);
 }
References coefficientRing(), and Ring::divide().
Referenced by NCGroebner::addToGroebnerBasis().