Macaulay2 Engine: FreeAlgebra::is_homogeneous
is_homogeneous()
bool FreeAlgebra::is_homogeneous (const Poly & f) const
Definition at line 815 of file FreeAlgebra.cpp.
 {
   bool result = true;
   if (f.numTerms() <= 1) return true;
   monomial e = degreeMonoid().make_one();
   monomial degf = degreeMonoid().make_one();
   auto i = f.cbegin();
   auto end = f.cend();
   monoid().multi_degree(i.monom(), degf); // sets degf.
   for (++i; i != end; ++i)
     {
         monoid().multi_degree(i.monom(), e);
         if (not degreeMonoid().is_equal(e, degf))
           {
             result = false;
             break;
           }
     }
   degreeMonoid().remove(e);
   degreeMonoid().remove(degf);
   return result;
 }
References degreeMonoid(), end(), is_equal(), Monoid::make_one(), monoid(), FreeMonoid::multi_degree(), and Monoid::remove().
Referenced by FreeAlgebraQuotient::is_homogeneous(), and M2FreeAlgebra::is_homogeneous().