Macaulay2 Engine: FreeAlgebra::add_to_end
add_to_end() [2/2]
void FreeAlgebra::add_to_end (Poly & f, ring_elem coeff, const Monom & monom) const
Definition at line 687 of file FreeAlgebra.cpp.
 {
   if (coefficientRing()->is_zero(coeff)) return;
   auto& outcoeff = f.getCoeffInserter();
   auto& outmonom = f.getMonomInserter();
   outcoeff.push_back(coeff);
   outmonom.insert(outmonom.end(),monom.begin(), monom.end());
 }
References Monom::begin(), coefficientRing(), Monom::end(), and is_zero().