Macaulay2 Engine: FreeAlgebra::numVars
numVars()
int FreeAlgebra::numVars () const inline
Definition at line 44 of file FreeAlgebra.hpp.
{ return monoid().numVars(); }
References monoid(), and FreeMonoid::numVars().
Referenced by compare_elems(), eval(), and support().