Macaulay2 Engine: FreeAlgebra::swap
swap()
void FreeAlgebra::swap (Poly & f, Poly & g) const
Definition at line 174 of file FreeAlgebra.cpp.
 {
   auto& fCoeff = f.getCoeffInserter();
   auto& fMonom = f.getMonomInserter();
   auto& gCoeff = g.getCoeffInserter();
   auto& gMonom = g.getMonomInserter();
   std::swap(fCoeff,gCoeff);
   std::swap(fMonom,gMonom);
 }
References swap.
Referenced by NCF4::autoreduceByLastElement(), NCGroebner::autoreduceByLastElement(), FreeAlgebraQuotient::normalizeInPlace(), and FreeAlgebraQuotient::swap().