Macaulay2 Engine: FreeAlgebra::coefficientRing
coefficientRing()
const Ring* FreeAlgebra::coefficientRing () const inline
Definition at line 41 of file FreeAlgebra.hpp.
 { return &mCoefficientRing; }
References mCoefficientRing.
Referenced by add(), add_to_end(), addScalarMultipleOf(), MapPolynomialHeap::addTerm(), M2FreeAlgebra::coefficientRing(), FreeAlgebraQuotient::coefficientRing(), compare_elems(), NaiveDedupQueueConfiguration::deduplicate(), NCF4::displayF4Matrix(), NCF4::displayFullF4Matrix(), elem_text_out(), eval(), from_coefficient(), from_int(), from_long(), from_rational(), from_word(), NCGroebner::getCoeffOfMonom(), NCF4::getCoeffOfMonom(), is_equal(), is_unit(), NaivePolynomialHeap< Queue >::isZero(), NaiveDedupPolynomialHeap< Queue >::isZero(), MapPolynomialHeap::isZero(), PriorityQueuePolynomialHeap::isZero(), makeMonic(), makeMonicInPlace(), mult_by_term_left(), mult_by_term_left_and_right(), mult_by_term_right(), negate(), power(), setZero(), subtract(), subtractScalarMultipleOf(), TEST(), and var().