Macaulay2 Engine: FreeAlgebra::monoid
monoid()
const FreeMonoid& FreeAlgebra::monoid () const inline
Definition at line 42 of file FreeAlgebra.hpp.
 { return *mMonoid; }
References mMonoid.
Referenced by addScalarMultipleOf(), NaiveQueueConfiguration::compare(), NaiveDedupQueueConfiguration::compare(), compare_elems(), constructWordTable(), degreeMonoid(), NCF4::displayF4Matrix(), NCF4::displayFullF4Matrix(), elem_text_out(), eval(), from_coefficient(), from_word(), heft_degree(), is_homogeneous(), is_unit(), NaivePolynomialHeap< Queue >::isZero(), PriorityQueuePolynomialHeap::isZero(), lead_word(), lead_word_prefix(), lead_word_suffix(), M2FreeAlgebra::monoid(), FreeAlgebraQuotient::monoid(), mult_by_term_left(), mult_by_term_left_and_right(), mult_by_term_right(), multi_degree(), ncBasis(), numVars(), NCF4::preRowsFromOverlap(), NCF4::processPreRow(), NCF4::reducedRowToPoly(), Matrix::support(), support(), and var().