Macaulay2 Engine: FreeAlgebra::addScalarMultipleOf
addScalarMultipleOf()
void FreeAlgebra::addScalarMultipleOf (Poly & result, Poly::const_iterator fBegin, Poly::const_iterator fEnd, Poly::const_iterator gBegin, Poly::const_iterator gEnd, ring_elem coeff) const
Definition at line 315 of file FreeAlgebra.cpp.
 {
   auto& outcoeff = result.getCoeffInserter();
   auto& outmonom = result.getMonomInserter();
   // loop over the iterators for f and g, adding the bigger of the two to
   // the back of the monomial and coefficient vectors of the result.  If a tie, add the coefficients.
   while ((fBegin != fEnd) && (gBegin != gEnd))
     {
       auto fMon = fBegin.monom();
       auto gMon = gBegin.monom();
       auto fCoeff = fBegin.coeff();
       auto gCoeff = gBegin.coeff();
       ring_elem coeffResult;
       switch(monoid().compare(fMon,gMon))
         {
         case LT:
           coeffResult = coefficientRing()->mult(coeff,gCoeff);
           if (!coefficientRing()->is_zero(coeffResult))
           {
             outcoeff.push_back(coeffResult);
             monoid().copy(gMon, outmonom);
           }
           gBegin++;
           break;
         case GT:
           outcoeff.push_back(fCoeff);
           monoid().copy(fMon, outmonom);
           fBegin++;
           break;
         case EQ:
           ring_elem tempResult = coefficientRing()->mult(coeff,gCoeff);
           coeffResult = coefficientRing()->add(fCoeff,tempResult);
           if (!coefficientRing()->is_zero(coeffResult))
             {
               outcoeff.push_back(coeffResult);
               monoid().copy(gMon, outmonom);
             }
           fBegin++;
           gBegin++;
         }
     }
   if (fBegin == fEnd)
     {
       for ( ; gBegin != gEnd; gBegin++)
         {
           auto gMon = gBegin.monom();
           auto gCoeff = gBegin.coeff();
           ring_elem coeffResult = coefficientRing()->mult(coeff,gCoeff);
           if (!coefficientRing()->is_zero(coeffResult))
           {
             outcoeff.push_back(coeffResult);
             monoid().copy(gMon, outmonom);
           }
         }
     }
   if (gBegin == gEnd)
     {
       for ( ; fBegin != fEnd; fBegin++)
         {
           auto fMon = fBegin.monom();
           auto fCoeff = fBegin.coeff();
           outcoeff.push_back(fCoeff);
           monoid().copy(fMon, outmonom);
         }
     }
 }
References Ring::add(), coefficientRing(), compare(), FreeMonoid::copy(), EQ, GT, is_zero(), LT, monoid(), and Ring::mult().
Referenced by add(), subtract(), and subtractScalarMultipleOf().