Macaulay2 Engine: FreeAlgebra::elem_text_out
elem_text_out()
void FreeAlgebra::elem_text_out (buffer & o, const Poly & f, bool p_one, bool p_plus, bool p_parens) const
Definition at line 780 of file FreeAlgebra.cpp.
 {
   if (f.numTerms() == 0)
     {
       o << "0";
       return;
     }
   bool two_terms = (f.numTerms() > 1);
   bool needs_parens = p_parens && two_terms;
   if (needs_parens)
     {
       if (p_plus) o << '+';
       o << '(';
       p_plus = false;
     }
   for (auto i = f.cbegin(); i != f.cend(); i++)
     {
       bool is_one = monoid().is_one(i.monom());
       p_parens = !is_one;
       bool p_one_this = (is_one && needs_parens) || (is_one && p_one);
       coefficientRing()->elem_text_out(o, i.coeff(), p_one_this, p_plus, p_parens);
       if (!is_one)
         monoid().elem_text_out(o, i.monom());
       p_plus = true;
     }
   if (needs_parens) o << ')';
 }
References coefficientRing(), FreeMonoid::elem_text_out(), Ring::elem_text_out(), FreeMonoid::is_one(), and monoid().
Referenced by FreeAlgebraQuotient::elem_text_out(), M2FreeAlgebra::elem_text_out(), operator<<(), and TEST().