Macaulay2 Engine: FreeAlgebra::power
power() [1/2]
void FreeAlgebra::power (Poly & result, const Poly & f, int n) const
Definition at line 696 of file FreeAlgebra.cpp.
 {
   from_long(result, 1);
   Poly tmp;
   for (int i=0; i<n; i++)
     {
       mult(tmp, result, f);
       result = tmp;
       setZero(tmp);
     }
 }
References from_long(), mult(), and setZero().
Referenced by FreeAlgebraElement::operator^(), M2FreeAlgebra::power(), FreeAlgebraQuotient::power(), and power().