Macaulay2 Engine: FreeAlgebra::copy
copy() [2/2]
void FreeAlgebra::copy (Poly & result, Poly::const_iterator fBegin, Poly::const_iterator fEnd) const
Definition at line 157 of file FreeAlgebra.cpp.
 {
   clear(result);
   auto& resultCoeff = result.getCoeffInserter();
   auto& resultMonom = result.getMonomInserter();
   resultCoeff.insert(resultCoeff.end(),
                      fBegin.cCoeffIterator(),
                      fEnd.cCoeffIterator());
   resultMonom.insert(resultMonom.end(),
                      fBegin.cMonomIterator(),
                      fEnd.cMonomIterator());
 }
References clear().
Referenced by copy(), FreeAlgebraQuotient::copy(), copyMatrixToVector(), M2FreeAlgebraQuotient::lift(), and TrivialPolynomialHeap::value().