Macaulay2 Engine: FreeAlgebra::add_to_end
add_to_end() [1/2]
void FreeAlgebra::add_to_end (Poly & f, const Poly & g) const
Definition at line 678 of file FreeAlgebra.cpp.
 {
   if (is_zero(g)) return;
   auto& outcoeff = f.getCoeffInserter();
   auto& outmonom = f.getMonomInserter();
   outcoeff.insert(outcoeff.end(),g.cbeginCoeff(),g.cendCoeff());
   outmonom.insert(outmonom.end(),g.cbeginMonom(),g.cendMonom());
 }
References is_zero().
Referenced by TEST(), NaivePolynomialHeap< Queue >::value(), NaiveDedupPolynomialHeap< Queue >::value(), MapPolynomialHeap::value(), and PriorityQueuePolynomialHeap::value().