Macaulay2 Engine: FreeAlgebra::mult
mult()
void FreeAlgebra::mult (Poly & result, const Poly & f, const Poly & g) const
Definition at line 503 of file FreeAlgebra.cpp.
 {
   FreeAlgebraHeap H {*this};
   Poly tmp;
   init(tmp);
   if (f.numTerms() <= g.numTerms())
     {
       for (auto fIt = f.cbegin(); fIt != f.cend(); fIt++)
         {
           mult_by_term_left(tmp, g, fIt.coeff(), fIt.monom());
           H.add(tmp);
           setZero(tmp);
         }
     }
   else
     {
       for (auto gIt = g.cbegin(); gIt != g.cend(); gIt++)
         {
           mult_by_term_right(tmp,f, gIt.coeff(), gIt.monom());
           H.add(tmp);
           setZero(tmp);
         }
     }
   H.value(result);
   clear(tmp);
 }
References clear(), init(), mult_by_term_left(), mult_by_term_right(), and setZero().
Referenced by M2FreeAlgebra::mult(), FreeAlgebraQuotient::mult(), mult_by_coeff(), FreeAlgebraElement::operator*(), and power().