Macaulay2 Engine: FreeAlgebra::heft_degree
heft_degree()
std::pair< int, bool > FreeAlgebra::heft_degree (const Poly & f) const
Definition at line 864 of file FreeAlgebra.cpp.
 {
   bool ishomog = true;
   Word tmp;
   auto i = f.cbegin();
   if (i == f.cend()) return std::make_pair(0, true);
   monoid().wordFromMonom(tmp, i.monom());
   int maxheft = monoid().wordHeft(tmp);
   for (++i; i != f.cend(); ++i)
     {
       monoid().wordFromMonom(tmp, i.monom());
       int thisheft = monoid().wordHeft(tmp);
       if (thisheft != maxheft)
         {
           ishomog = false;
           if (thisheft > maxheft)
             maxheft = thisheft;
         }
     }
   return std::make_pair(maxheft, ishomog);
 }
References monoid(), FreeMonoid::wordFromMonom(), and FreeMonoid::wordHeft().
Referenced by NCF4::NCF4(), and NCGroebner::NCGroebner().