Macaulay2 Engine: FreeAlgebra::lead_word_prefix
lead_word_prefix()
Word FreeAlgebra::lead_word_prefix (const Poly & f, int endIndex) const
Definition at line 893 of file FreeAlgebra.cpp.
 {
   Word result;
   monoid().wordPrefixFromMonom(result,f.cbegin().monom(),endIndex);
   return result;
 }
References monoid(), and FreeMonoid::wordPrefixFromMonom().
Referenced by TEST().