Macaulay2 Engine: FreeAlgebra::from_coefficient
from_coefficient()
void FreeAlgebra::from_coefficient (Poly & result, const ring_elem a) const
Definition at line 129 of file FreeAlgebra.cpp.
 {
   if (not coefficientRing()->is_zero(a))
     {
       result.getCoeffInserter().push_back(a);
       monoid().one(result.getMonomInserter());
     }
 }
References coefficientRing(), is_zero(), monoid(), and FreeMonoid::one().
Referenced by M2FreeAlgebra::from_coefficient(), FreeAlgebraQuotient::from_coefficient(), from_int(), from_long(), from_rational(), mult_by_coeff(), and power().