Macaulay2 Engine: FreeAlgebra::from_word
from_word() [1/4]
void FreeAlgebra::from_word (Poly & result, const std::vector< int > & word) const
Definition at line 243 of file FreeAlgebra.cpp.
 {
   from_word(result, coefficientRing()->from_long(1), word);
 }
References coefficientRing(), from_long(), from_word(), and word.