Macaulay2 Engine: FreeAlgebra::degree
degree()
const_monomial FreeAlgebra::degree (const Poly & f) const inline
Definition at line 112 of file FreeAlgebra.hpp.
   {
     auto d = degreeMonoid().make_one();
     multi_degree(f, d);
     return d;
   }
References degreeMonoid(), Monoid::make_one(), and multi_degree().