Macaulay2 Engine: FreeAlgebra::mult_by_term_left_and_right
mult_by_term_left_and_right() [2/4]
void FreeAlgebra::mult_by_term_left_and_right (Poly & result, const Poly & f, const ring_elem c, const Monom leftM, const Monom rightM) const
Definition at line 594 of file FreeAlgebra.cpp.
{
  // return (c*leftM)*f*rightM
  auto& outcoeff = result.getCoeffInserter();
  auto& outmonom = result.getMonomInserter();
  for(auto i=f.cbegin(); i != f.cend(); i++)
    {
      ring_elem d = coefficientRing()->mult(c, i.coeff());
      if (coefficientRing()->is_zero(d))
        continue;
      outcoeff.push_back(d);
      monoid().mult3(leftM, i.monom(), rightM, outmonom);
    }
}
References coefficientRing(), is_zero(), monoid(), Ring::mult(), and FreeMonoid::mult3().
Referenced by TrivialPolynomialHeap::addPolynomial(), NaivePolynomialHeap< Queue >::addPolynomial(), NaiveDedupPolynomialHeap< Queue >::addPolynomial(), MapPolynomialHeap::addPolynomial(), PriorityQueuePolynomialHeap::addPolynomial(), mult_by_term_left_and_right(), mult_by_term_left_and_right(), and TEST().