Macaulay2 Engine: FreeAlgebra::var
var()
void FreeAlgebra::var (Poly & result, int v) const
Definition at line 184 of file FreeAlgebra.cpp.
{
  result.getCoeffInserter().push_back(coefficientRing()->from_long(1));
  monoid().var(v, result.getMonomInserter());
}
References coefficientRing(), from_long(), monoid(), and FreeMonoid::var().
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), M2FreeAlgebra::var(), and FreeAlgebraQuotient::var().