Macaulay2 Engine: FreeAlgebra::add
add() [2/2]
void FreeAlgebra::add (Poly & result, Poly::const_iterator fBegin, Poly::const_iterator fEnd, Poly::const_iterator gBegin, Poly::const_iterator gEnd) const
Definition at line 398 of file FreeAlgebra.cpp.
 {
   addScalarMultipleOf(result,
                       fBegin,
                       fEnd,
                       gBegin,
                       gEnd,
                       coefficientRing()->one());
 }
References addScalarMultipleOf(), coefficientRing(), and Ring::one().
Referenced by FreeAlgebraHeap::add(), M2FreeAlgebra::add(), FreeAlgebraQuotient::add(), TrivialPolynomialHeap::addPolynomial(), FreeAlgebraElement::operator+(), and FreeAlgebraHeap::value().