Macaulay2 Engine: FreeAlgebra::mult_by_coeff
mult_by_coeff()
void FreeAlgebra::mult_by_coeff (Poly & result, const Poly & f, const ring_elem c) const
Definition at line 659 of file FreeAlgebra.cpp.
 {
   // return c*f -- perhaps make this in place later, but for now
   // create a new element
   Poly tmp;
   from_coefficient(tmp,c);
   mult(result, f, tmp);
   clear(tmp);
 }
References clear(), from_coefficient(), and mult().
Referenced by TEST().