Macaulay2 Engine: FreeAlgebra::from_long
from_long()
void FreeAlgebra::from_long (Poly & result, long n) const
Definition at line 138 of file FreeAlgebra.cpp.
{
  from_coefficient(result, coefficientRing()->from_long(n));
}
References coefficientRing(), from_coefficient(), and from_long().
Referenced by from_long(), from_word(), from_word(), power(), power(), TEST(), and var().