Macaulay2 Engine: FreeAlgebra::support
support()
M2_arrayint FreeAlgebra::support (const Poly & f) const
Definition at line 192 of file FreeAlgebra.cpp.
 {
   int numVarsFound = 0;
   std::vector<int> exp, exp2;
   auto fIt = f.cbegin();
   auto fEnd = f.cend();
   for (auto i = 0; i < numVars(); i++)
      exp2.push_back(0);
   for ( ; fIt != fEnd; fIt++)
   {
      monoid().support(fIt.monom(),exp);
      for (auto i : exp)
      {
        if (exp2[i] == 0)
        {
          exp2[i]++;
          numVarsFound++;
        }
      }
      if (numVarsFound == numVars()) break;
   }
   exp.clear();
   for (int i = 0; i < numVars(); i++)
     if (exp2[i] > 0) exp.push_back(i);
   M2_arrayint result = M2_makearrayint(exp.size());
   int next = 0;
   for (auto i : exp)
     result->array[next++] = i;
   return result;
 }
References mpfr::mpreal::clear(), mpfr::exp(), mpfr::exp2(), M2_makearrayint(), monoid(), numVars(), and FreeMonoid::support().
Referenced by M2FreeAlgebra::support().