Macaulay2 Engine: FreeAlgebra::power
power() [2/2]
void FreeAlgebra::power (Poly & result, const Poly & f, mpz_srcptr n) const
Definition at line 710 of file FreeAlgebra.cpp.
 {
   if (mpz_sgn(n) == 0) from_long(result, 1);
   else if (is_zero(f)) from_long(result, 0);
   else if (is_unit(f))  // really want a routine 'is_scalar'...
     {
       ring_elem coeff = f.cbegin().coeff();
       ring_elem a = coefficientRing()->power(coeff, n);
       from_coefficient(result, a);
     }
   else
     {
       std::pair<bool, int> n1 = RingZZ::get_si(n);
       if (mpz_sgn(n) > 0 and n1.first)
           power(result, f, n1.second);
       else
         {
           ERROR("exponent too large");
           from_long(result, 0);
         }
     }
 }
References coefficientRing(), ERROR(), from_coefficient(), from_long(), RingZZ::get_si(), is_unit(), is_zero(), Ring::power(), and power().