Macaulay2 Engine: FreeAlgebra::mult_by_term_left_and_right
mult_by_term_left_and_right() [4/4]
void FreeAlgebra::mult_by_term_left_and_right (Poly & result, const Poly & f, const Word & leftW, const Word & rightW) const
Definition at line 644 of file FreeAlgebra.cpp.
{
  gc_vector<int> leftTmp, rightTmp;
  monoid().monomInsertFromWord(leftTmp,leftW);
  monoid().monomInsertFromWord(rightTmp,rightW);
  Monom leftTmpMonom(leftTmp.data());
  Monom rightTmpMonom(rightTmp.data());
  mult_by_term_left_and_right(result,f,leftTmpMonom,rightTmpMonom);
  leftTmp.clear();
  rightTmp.clear();
}
References monoid(), FreeMonoid::monomInsertFromWord(), and mult_by_term_left_and_right().