Macaulay2 Engine: FreeAlgebra::mult_by_term_left
mult_by_term_left() [1/2]
void FreeAlgebra::mult_by_term_left (Poly & result, const Poly & f, const ring_elem c, const Monom m) const
Definition at line 563 of file FreeAlgebra.cpp.
 {
   // return (c*m)*f
   auto& outcoeff = result.getCoeffInserter();
   auto& outmonom = result.getMonomInserter();
   for(auto i=f.cbegin(); i != f.cend(); i++)
     {
       ring_elem d = coefficientRing()->mult(c, i.coeff());
       if (coefficientRing()->is_zero(d))
         continue;
       outcoeff.push_back(d);
       monoid().mult(m, i.monom(), outmonom);
     }
 }
References coefficientRing(), is_zero(), monoid(), FreeMonoid::mult(), and Ring::mult().
Referenced by mult(), mult_by_term_left(), and TEST().