Macaulay2 Engine: FreeAlgebra::is_equal
is_equal()
bool FreeAlgebra::is_equal (const Poly & f, const Poly & g) const
Definition at line 288 of file FreeAlgebra.cpp.
{
  if (f.numTerms() != g.numTerms()) return false;
  if (f.getMonomVector() != g.getMonomVector()) return false;
  auto fCoeffIt = f.cbeginCoeff();
  auto gCoeffIt = g.cbeginCoeff();
  auto fEnd = f.cendCoeff();
  for ( ; fCoeffIt != fEnd ; fCoeffIt++, gCoeffIt++)
    {
      bool cmp = coefficientRing()->is_equal(*fCoeffIt, *gCoeffIt);
      if (!cmp) return false;
    }
  return true;
}
References coefficientRing(), and Ring::is_equal().
Referenced by FreeAlgebraQuotient::is_equal(), M2FreeAlgebra::is_equal(), is_homogeneous(), multi_degree(), FreeAlgebraElement::operator==(), TEST(), TEST(), and TEST().