Macaulay2 Engine: FreeAlgebra::clear
clear()
void FreeAlgebra::clear (Poly & f) const
Definition at line 114 of file FreeAlgebra.cpp.
 {
   // TODO: need Polynomial type to allow us access, or have a clear function itself.
   setZero(f);
 }
References setZero().
Referenced by copy(), mult(), mult_by_coeff(), NCF4::processPreRow(), FreeAlgebraHeap::value(), FreeAlgebraElement::~FreeAlgebraElement(), and NCF4::~NCF4().