Macaulay2 Engine: FreeAlgebra::setZero
setZero()
void FreeAlgebra::setZero (Poly & f) const
Definition at line 120 of file FreeAlgebra.cpp.
 {
   for (auto a : f.mCoefficients)
     coefficientRing()->remove(a);
   f.mCoefficients.clear();
   f.mMonomials.clear();
 }
References coefficientRing(), and Ring::remove().
Referenced by FreeAlgebraHeap::add(), TrivialPolynomialHeap::addPolynomial(), TrivialPolynomialHeap::clear(), clear(), mult(), power(), FreeAlgebraQuotient::setZero(), TEST(), and FreeAlgebraHeap::value().