Macaulay2 Engine: FreeAlgebra::mult_by_term_right
mult_by_term_right() [2/2]
void FreeAlgebra::mult_by_term_right (Poly & result, const Poly & f, const ring_elem c, const Word & w) const
Definition at line 551 of file FreeAlgebra.cpp.
 {
   gc_vector<int> tmp;
   monoid().monomInsertFromWord(tmp,w);
   Monom tmpMonom(tmp.data());
   mult_by_term_right(result,f,c,tmpMonom);
   tmp.clear();
 }
References monoid(), FreeMonoid::monomInsertFromWord(), and mult_by_term_right().