Macaulay2 Engine: FreeAlgebra::multi_degree
multi_degree()
bool FreeAlgebra::multi_degree (const Poly & f, monomial already_allocated_degree_vector) const
Definition at line 838 of file FreeAlgebra.cpp.
{
  monomial degVec = already_allocated_degree_vector;
  bool ishomog = true;
  auto i = f.cbegin();
  monoid().multi_degree(i.monom(), degVec);
  monomial e = degreeMonoid().make_one();
  for (++i; i != f.cend(); ++i)
    {
      monoid().multi_degree(i.monom(), e);
      if (not degreeMonoid().is_equal(degVec, e))
        {
          ishomog = false;
          degreeMonoid().lcm(degVec, e, degVec);
        }
    }
  degreeMonoid().remove(e);
  return ishomog;
}
References degreeMonoid(), is_equal(), Monoid::lcm(), Monoid::make_one(), monoid(), FreeMonoid::multi_degree(), and Monoid::remove().
Referenced by degree(), FreeAlgebraQuotient::multi_degree(), and M2FreeAlgebra::multi_degree().