Macaulay2 Engine: FreeAlgebra::eval
eval()
ring_elem FreeAlgebra::eval (const RingMap * map, const Poly & f, int first_var) const
Definition at line 731 of file FreeAlgebra.cpp.
 {
   // map: R --> S, this = R.
   // f is an element in R
   // return an element of S - we don't know anything about S
   // plan: do it as in polyring:
   //  cast f to a Poly
   //  loop through the terms of f
   //    for each term: call map->eval_term, need varpower monomial here.
   //    add to a heap object
   // return value of the heap object
   const Ring* target = map->get_ring();
   SumCollector *H = target->make_SumCollector();
   std::vector<int> vp;
   for (auto i = f.cbegin(); i != f.cend(); ++i)
     {
       vp.clear();
       monoid().getMonomial(i.monom(), vp);
       ring_elem g = map->eval_term(coefficientRing(), i.coeff(), vp.data(), first_var, numVars());
       H->add(g);
     }
   ring_elem result = H->getValue();
   return result;
 }
References SumCollector::add(), coefficientRing(), RingMap::eval_term(), RingMap::get_ring(), FreeMonoid::getMonomial(), SumCollector::getValue(), Ring::make_SumCollector(), monoid(), and numVars().
Referenced by FreeAlgebraQuotient::eval(), and M2FreeAlgebra::eval().