Macaulay2 Engine: FreeAlgebra::create
create()
FreeAlgebra * FreeAlgebra::create (const Ring * K, const std::vector< std::string > & names, const PolynomialRing * degreeRing, const std::vector< int > & degrees, const std::vector< int > & wtvecs, const std::vector< int > & heftVector) static
Definition at line 91 of file FreeAlgebra.cpp.
{
  assert(K != nullptr);
  std::shared_ptr<FreeMonoid> M (new FreeMonoid(names, degreeRing, degrees, wtvecs, heftVector));
  FreeAlgebra* result = new FreeAlgebra(K, M);
  return result;
}
References degreeRing().
Referenced by M2FreeAlgebra::create(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().