Macaulay2 Engine: Range::size
size()
template<typename T > int Range< T >::size () const inline
Definition at line 24 of file Range.hpp.
{ return mLast - mFirst; }
References Range< T >::mFirst, and Range< T >::mLast.
Referenced by ConcreteVectorArithmetic< RingType >::denseCancelFromSparse(), ConcreteVectorArithmetic< RingType >::denseCancelFromSparse(), ConcreteVectorArithmetic< RingType >::fillDenseArray(), and PairRange< U, T >::size().