Macaulay2 Engine: GBKernelComputation::geo_reduce
geo_reduce()
void GBKernelComputation::geo_reduce (gbvector *& g, gbvector *& gsyz) private
Definition at line 443 of file Eschreyer.cpp.
 {
   exponents REDUCE_exp = ALLOCATE_EXPONENTS(exp_size);
   monomial REDUCE_mon = ALLOCATE_MONOMIAL(monom_size);
   const Ring *gbringK = GR->get_flattened_coefficients();
   ring_elem one = gbringK->from_long(1);
   gbvector *lastterm = fsyz;  // fsyz has only ONE term.
   const gbvector *r;
   gbvectorHeap fb(GR, F);
   fb.add(f);
   f = NULL;
   const gbvector *lead;
   int q;
   int count = 0;
   if (M2_gbTrace >= 4) emit_wrapped(",");
   while ((lead = fb.get_lead_term()) != NULL)
     {
       if (SF)
         {
           SF->schreyer_down(lead->monom, lead->comp - 1, REDUCE_mon);
           M->to_expvector(REDUCE_mon, REDUCE_exp);
         }
       else
         M->to_expvector(lead->monom, REDUCE_exp);
       if (find_ring_divisor(REDUCE_exp, r))
         {
           ring_elem u, v;
           // Subtract off f, leave fsyz alone
           M->divide(lead->monom, r->monom, REDUCE_mon);
           gbringK->syzygy(f->coeff, r->coeff, u, v);
           gbvector *h = GR->mult_by_term(F, r, v, REDUCE_mon, f->comp);
           fb.add(h);
           if (!gbringK->is_equal(u, one))
             {
               GR->gbvector_mult_by_coeff_to(fsyz, u);
               GR->gbvector_mult_by_coeff_to(f, u);
               gbringK->remove(u);
               gbringK->remove(v);
             }
           fb.add(h);
           total_reduce_count++;
           count++;
         }
       else if (find_divisor(mi[lead->comp - 1], REDUCE_exp, q))
         {
           ring_elem u, v;
           gbringK->syzygy(f->coeff, gb[q]->coeff, u, v);
           M->divide(lead->monom, gb[q]->monom, REDUCE_mon);
           gbvector *h = GR->mult_by_term(F, gb[q], v, REDUCE_mon, 0);
           if (!gbringK->is_equal(u, one))
             {
               GR->gbvector_mult_by_coeff_to(fsyz, u);
               GR->gbvector_mult_by_coeff_to(f, u);
             }
           wipe_unneeded_terms(h);
           lastterm->next = make_syz_term(v, lead->monom, q + 1);  // grabs v.
           lastterm = lastterm->next;
           fb.add(h);
           total_reduce_count++;
           count++;
         }
       else
         {
           // To get here is an ERROR!
           fb.remove_lead_term();
           emit_line(
               "error in Schreyer reduction: element does not reduce to zero!");
         }
     }
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << count;
       emit_wrapped(o.str());
     }
 }
References gbvectorHeap::add(), ALLOCATE_EXPONENTS, ALLOCATE_MONOMIAL, gbvector::coeff, gbvector::comp, Monoid::divide(), emit_line(), emit_wrapped(), exp_size, F, find_divisor(), find_ring_divisor(), Ring::from_long(), gb, GBRing::gbvector_mult_by_coeff_to(), GBRing::get_flattened_coefficients(), gbvectorHeap::get_lead_term(), GR, Ring::is_equal(), M, M2_gbTrace, make_syz_term(), mi, gbvector::monom, monom_size, GBRing::mult_by_term(), gbvector::next, Ring::remove(), gbvectorHeap::remove_lead_term(), SchreyerOrder::schreyer_down(), SF, buffer::str(), Ring::syzygy(), Monoid::to_expvector(), total_reduce_count, and wipe_unneeded_terms().