Macaulay2 Engine: GBKernelComputation::new_pairs
new_pairs()
void GBKernelComputation::new_pairs (int i) private
Definition at line 155 of file Eschreyer.cpp.
 {
   gc_vector<Bag*> elems;
   gc_vector<int> vp;  // This is 'p'.
   gc_vector<int> thisvp;
   if (SF)
     {
       monomial PAIRS_mon = ALLOCATE_MONOMIAL(monom_size);
       SF->schreyer_down(gb[i]->monom, gb[i]->comp - 1, PAIRS_mon);
       M->to_varpower(PAIRS_mon, vp);
     }
   else
     M->to_varpower(gb[i]->monom, vp);
   // First add in syzygies arising from exterior variables
   // At the moment, there are none of this sort.
   if (R->is_skew_commutative())
     {
       exponents_t find_pairs_exp = newarray_atomic(int, M->n_vars());
       varpower::to_expvector(M->n_vars(), vp.data(), find_pairs_exp);
       for (int w = 0; w < R->n_skew_commutative_vars(); w++)
         if (find_pairs_exp[R->skew_variable(w)] > 0)
           {
             thisvp.resize(0);
             varpower::var(w, 1, thisvp);
             Bag *b = new Bag(static_cast<void *>(0), thisvp);
             elems.push_back(b);
           }
       freemem(find_pairs_exp);
     }
   // Second, add in syzygies arising from the base ring, if any
   // The baggage of each of these is NULL
   if (R->is_quotient_ring())
     {
       const MonomialIdeal *Rideal = R->get_quotient_monomials();
       for (Bag& a : *Rideal)
         {
           // Compute (P->quotient_ideal->monom : p->monom)
           // and place this into a varpower and Bag, placing
           // that into 'elems'
           thisvp.resize(0);
           varpower::quotient(a.monom().data(), vp.data(), thisvp);
           if (varpower::is_equal(a.monom().data(), thisvp.data()))
             continue;
           Bag *b = new Bag(static_cast<void *>(0), thisvp);
           elems.push_back(b);
         }
     }
   // Third, add in syzygies arising from previous elements of this same level
   // The baggage of each of these is their corresponding res2_pair
   MonomialIdeal *mi_orig = mi[gb[i]->comp - 1];
   for (Bag& a : *mi_orig)
     {
       Bag *b = new Bag();
       varpower::quotient(a.monom().data(), vp.data(), b->monom());
       elems.push_back(b);
     }
   // Make this monomial ideal, and then run through each minimal generator
   // and insert into the proper degree. (Notice that sorting does not
   // need to be done yet: only once that degree is about to begin.
   mi_orig->insert_minimal(new Bag(i, vp));
   MonomialIdeal *new_mi = new MonomialIdeal(R, elems);
   monomial m = M->make_one();
   for (Bag& a : *new_mi)
     {
       M->from_varpower(a.monom().data(), m);
       M->mult(m, gb[i]->monom, m);
       gbvector *q = make_syz_term(
           GR->get_flattened_coefficients()->from_long(1), m, i + 1);
       syzygies.push_back(q);
     }
 }
References ALLOCATE_MONOMIAL, freemem(), Ring::from_long(), Monoid::from_varpower(), gb, GBRing::get_flattened_coefficients(), PolynomialRing::get_quotient_monomials(), GR, MonomialIdeal::insert_minimal(), ExponentList< E, L >::is_equal(), PolynomialRing::is_quotient_ring(), PolynomialRing::is_skew_commutative(), M, Monoid::make_one(), make_syz_term(), mi, int_bag::monom(), monom_size, Monoid::mult(), PolynomialRing::n_skew_commutative_vars(), Monoid::n_vars(), newarray_atomic, ExponentList< E, L >::quotient(), R, SchreyerOrder::schreyer_down(), SF, PolynomialRing::skew_variable(), syzygies, ExponentList< E, L >::to_expvector(), Monoid::to_varpower(), and ExponentList< E, L >::var().
Referenced by calc().