Macaulay2 Engine: GBKernelComputation::s_pair
s_pair()
gbvector * GBKernelComputation::s_pair (gbvector * syz) private
Definition at line 298 of file Eschreyer.cpp.
 {
   gbvector *result = NULL;
   monomial si = M->make_one();
   for (gbvector *f = gsyz; f != 0; f = f->next)
     {
       SG->schreyer_down(f->monom, f->comp - 1, si);
       gbvector *h = GR->mult_by_term(F, gb[f->comp - 1], f->coeff, si, 0);
       wipe_unneeded_terms(h);
       GR->gbvector_add_to(F, result, h);
     }
   M->remove(si);
   return result;
 }
References F, gb, GBRing::gbvector_add_to(), GR, M, Monoid::make_one(), GBRing::mult_by_term(), gbvector::next, Monoid::remove(), SchreyerOrder::schreyer_down(), SG, and wipe_unneeded_terms().
Referenced by calc().