Macaulay2 Engine: GBKernelComputation::strip_gb
strip_gb() [1/2]
void GBKernelComputation::strip_gb (const GBMatrix * m) private
Definition at line 129 of file Eschreyer.cpp.
 {
   const gc_vector<gbvector*> &g = m->elems;
   int i;
   int *components = newarray_atomic_clear(int, F->rank());
   for (i = 0; i < g.size(); i++)
     if (g[i] != nullptr) components[g[i]->comp - 1]++;
   for (i = 0; i < g.size(); i++)
     {
       gbvector head;
       gbvector *last = &head;
       for (gbvector *v = g[i]; v != nullptr; v = v->next)
         if (components[v->comp - 1] > 0)
           {
             gbvector *t = GR->gbvector_copy_term(v);
             last->next = t;
             last = t;
           }
       last->next = nullptr;
       gb.push_back(head.next);
     }
   for (i = 0; i < F->rank(); i++) mi.push_back(new MonomialIdeal(R));
   freemem(components);
 }
References GBMatrix::elems, F, freemem(), gb, GBRing::gbvector_copy_term(), GR, mi, newarray_atomic_clear, gbvector::next, R, and FreeModule::rank().