Macaulay2 Engine: GBKernelComputation::wipe_unneeded_terms
wipe_unneeded_terms()
void GBKernelComputation::wipe_unneeded_terms (gbvector *& f) private
Definition at line 313 of file Eschreyer.cpp.
 {
   // Remove every term of f (except the lead term)
   // which is NOT divisible by an element of mi.
   exponents_t exp = newarray_atomic(int, GR->n_vars());
   // int nterms = 1;
   // int nsaved = 0;
   gbvector *g = f;
   while (g->next != nullptr)
     {
       // First check to see if the term g->next is in the monideal
       // nterms++;
       Bag *b;
       GR->gbvector_get_lead_exponents(F, g->next, exp);
       if (mi[g->next->comp - 1]->search_expvector(exp, b))
         {
           // Want to keep the monomial
           g = g->next;
         }
       else
         {
           // Want to dump this term
           // nsaved++;
           gbvector *tmp = g->next;
           g->next = tmp->next;
           tmp->next = nullptr;
           GR->gbvector_remove(tmp);
         }
     }
 #if 0
 //   if (M2_gbTrace >= 5)
 //     {
 //       buffer o;
 //       o << "[" << nterms << ",s" << nsaved << "]";
 //       emit_wrapped(o.str());
 //     }
 #endif
 }
References gbvector::comp, mpfr::exp(), F, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_remove(), GR, mi, GBRing::n_vars(), newarray_atomic, and gbvector::next.
Referenced by geo_reduce(), reduce(), and s_pair().