Macaulay2 Engine: GBKernelComputation::make_syz_term
make_syz_term()
gbvector * GBKernelComputation::make_syz_term (ring_elem c, const_monomial monom, int comp) const private
Definition at line 115 of file Eschreyer.cpp.
 {
 #ifdef DEVELOPMENT
 #warning "this might add in the Schreyer up"
 #warning "the previous warning message is confusing, grammatically"
 #endif
   return GR->gbvector_raw_term(c, m, comp);
 }
Referenced by geo_reduce(), new_pairs(), and reduce().