Macaulay2 Engine: GBKernelComputation::GBKernelComputation
GBKernelComputation()
GBKernelComputation::GBKernelComputation (const GBMatrix * m)
Definition at line 40 of file Eschreyer.cpp.
     : F(m->get_free_module()),
       n_ones(0),
       n_unique(0),
       n_others(0),
       total_reduce_count(0)
 {
   const PolynomialRing *R0 = F->get_ring()->cast_to_PolynomialRing();
   GR = R0->get_gb_ring();
   R = R0;
   K = R->getCoefficients();
   M = R->getMonoid();
   G = FreeModule::make_schreyer(m);
   SF = F->get_schreyer_order();
   SG = G->get_schreyer_order();
   exp_size = EXPONENT_BYTE_SIZE(M->n_vars());
   monom_size = MONOMIAL_BYTE_SIZE(M->monomial_size());
   // Set 'gb'.
   strip_gb(m);
 }
References Ring::cast_to_PolynomialRing(), exp_size, EXPONENT_BYTE_SIZE, F, G, PolynomialRing::get_gb_ring(), FreeModule::get_ring(), FreeModule::get_schreyer_order(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), GR, K, M, FreeModule::make_schreyer(), monom_size, MONOMIAL_BYTE_SIZE, Monoid::monomial_size(), Monoid::n_vars(), R, SF, SG, and strip_gb().