Macaulay2 Engine: GBKernelComputation::find_ring_divisor
find_ring_divisor()
bool GBKernelComputation::find_ring_divisor (const_exponents exp, const gbvector *& result) private
Definition at line 246 of file Eschreyer.cpp.
{
  if (!R->is_quotient_ring()) return false;
  Bag *b;
  if (!R->get_quotient_monomials()->search_expvector(exp, b)) return false;
  int index = b->basis_elem();
  result = R->quotient_gbvector(index);
  return true;
}
References int_bag::basis_elem(), PolynomialRing::get_quotient_monomials(), PolynomialRing::is_quotient_ring(), PolynomialRing::quotient_gbvector(), R, and MonomialIdeal::search_expvector().
Referenced by geo_reduce(), and reduce().