Macaulay2 Engine: GBKernelComputation::find_divisor
find_divisor()
int GBKernelComputation::find_divisor (const MonomialIdeal * mi, const_exponents exp, int & result) private
Definition at line 260 of file Eschreyer.cpp.
 {
   // Find all the possible matches, use some criterion for finding the best...
   gc_vector<Bag*> bb;
   this_mi->find_all_divisors(exp, bb);
   int ndivisors = bb.size();
   if (ndivisors == 0) return 0;
   result = bb[0]->basis_elem();
   // Now search through, and find the best one.  If only one, just return it.
   if (M2_gbTrace >= 5)
     if (this_mi->size() > 1)
       {
         buffer o;
         o << ":" << this_mi->size() << "." << ndivisors << ":";
         emit(o.str());
       }
   if (ndivisors == 1)
     {
       if (this_mi->size() == 1)
         n_ones++;
       else
         n_unique++;
       return 1;
     }
   n_others++;
   int lowest = result;
   for (int i = 1; i < ndivisors; i++)
     {
       int p = bb[i]->basis_elem();
       if (p < lowest) lowest = p;
     }
   result = lowest;
   return ndivisors;
 }
References emit(), mpfr::exp(), MonomialIdeal::find_all_divisors(), M2_gbTrace, n_ones, n_others, n_unique, p, MonomialIdeal::size(), and buffer::str().
Referenced by geo_reduce(), and reduce().