Macaulay2 Engine: GBKernelComputation::calc
calc()
int GBKernelComputation::calc ()
Definition at line 71 of file Eschreyer.cpp.
 {
   // First find the skeleton
   for (int i = 0; i < gb.size(); i++) new_pairs(i);
   // Debug code
   GBMatrix *mm = new GBMatrix(G);
   for (int p = 0; p < syzygies.size(); p++)
     mm->append(GR->gbvector_copy(syzygies[p]));
   buffer o;
   Matrix *m = mm->to_matrix();
   if (M2_gbTrace >= 5)
     {
       o << "skeleton = " << newline;
       m->text_out(o);
       emit(o.str());
     }
   // Sort the skeleton now?
   // Now reduce each one of these elements
   for (int j = 0; j < syzygies.size(); j++)
     {
       gbvector *v = s_pair(syzygies[j]);
       reduce(v, syzygies[j]);
     }
   return COMP_DONE;
 }
References GBMatrix::append(), COMP_DONE, emit(), G, gb, GBRing::gbvector_copy(), GR, M2_gbTrace, new_pairs(), newline, p, reduce(), s_pair(), buffer::str(), syzygies, Matrix::text_out(), and GBMatrix::to_matrix().
Referenced by rawKernelOfGB().