Macaulay2 Engine: MutableComplex::iterator::index
index()
size_t MutableComplex::iterator::index () const inline
Definition at line 73 of file mutablecomplex.hpp.
 { return mIndex; }
References mIndex.
Referenced by MutableComplex::find_unit(), MutableComplex::next_unit(), and MutableComplex::prune_unit().