Macaulay2 Engine: DMat< M2::ARingGFFlintBig >::numColumns
numColumns()
size_t DMat< M2::ARingGFFlintBig >::numColumns () const inline
Definition at line 90 of file dmat-gf-flint-big.hpp.
  {
    return fq_nmod_mat_ncols(mArray, ring().flintContext());
  }
References DMat< ACoeffRing >::mArray, and DMat< ACoeffRing >::ring().
Referenced by MatrixOps::addMultipleTo(), and MatrixOps::subtractMultipleTo().