Macaulay2 Engine: gbvectorHeap::add
add()
void gbvectorHeap::add (gbvector * p)
Definition at line 1523 of file gbring.cpp.
 {
   mLead = -1;
   int len = GR->gbvector_n_terms(p);
   int i = 0;
   while (len >= heap_size[i]) i++;
   GR->gbvector_add_to(F, heap[i], p);
   len = GR->gbvector_n_terms(heap[i]);
   p = NULL;
   while (len >= heap_size[i])
     {
       i++;
       GR->gbvector_add_to(F, heap[i], heap[i - 1]);
       len = GR->gbvector_n_terms(heap[i]);
       heap[i - 1] = NULL;
     }
   if (i > top_of_heap) top_of_heap = i;
 }
References F, GBRing::gbvector_add_to(), GBRing::gbvector_n_terms(), GR, heap, heap_size, mLead, p, and top_of_heap.
Referenced by GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GBKernelComputation::geo_reduce(), MarkedGB::geo_remainder(), GBRing::reduce_marked_lead_term_heap(), PolyRing::translate_gbvector_from_vec(), and PolyRing::translate_gbvector_from_vec_QQ().