Macaulay2 Engine: gbvectorHeap::remove_lead_term
remove_lead_term()
gbvector * gbvectorHeap::remove_lead_term ()
Definition at line 1583 of file gbring.cpp.
 {
   if (mLead < 0) get_lead_term();
   if (mLead < 0) return nullptr;
   gbvector *result = heap[mLead];
   heap[mLead] = result->next;
   result->next = nullptr;
   mLead = -1;
   return result;
 }
References get_lead_term(), heap, mLead, and gbvector::next.
Referenced by GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GBKernelComputation::geo_reduce(), and MarkedGB::geo_remainder().