Macaulay2 Engine: gbvectorHeap::value
value()
gbvector * gbvectorHeap::value ()
Definition at line 1594 of file gbring.cpp.
 {
   gbvector *result = NULL;
   for (int i = 0; i <= top_of_heap; i++)
     {
       if (heap[i] == NULL) continue;
       GR->gbvector_add_to(F, result, heap[i]);
       heap[i] = NULL;
     }
   top_of_heap = -1;
   return result;
 }
References F, GBRing::gbvector_add_to(), GR, heap, and top_of_heap.
Referenced by GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), PolyRing::translate_gbvector_from_vec(), and PolyRing::translate_gbvector_from_vec_QQ().