Macaulay2 Engine: gbvectorHeap::get_lead_term
get_lead_term()
const gbvector * gbvectorHeap::get_lead_term ()
Definition at line 1542 of file gbring.cpp.
 {
   int lead_so_far = -1;
   for (int i = 0; i <= top_of_heap; i++)
     {
       if (heap[i] == nullptr) continue;
       if (lead_so_far < 0)
         {
           lead_so_far = i;
           continue;
         }
       int cmp = GR->gbvector_compare(F, heap[lead_so_far], heap[i]);
       if (cmp == GT) continue;
       if (cmp == LT)
         {
           lead_so_far = i;
           continue;
         }
       // At this point we have equality
       K->add_to(heap[lead_so_far]->coeff, heap[i]->coeff);
       gbvector *tmp = heap[i];
       heap[i] = tmp->next;
       tmp->next = nullptr;
       GR->gbvector_remove(tmp);
       if (K->is_zero(heap[lead_so_far]->coeff))
         {
           // Remove, and start over
           tmp = heap[lead_so_far];
           heap[lead_so_far] = tmp->next;
           tmp->next = nullptr;
           GR->gbvector_remove(tmp);
           lead_so_far = -1;
           i = -1;
         }
     }
   mLead = lead_so_far;
   if (lead_so_far < 0) return nullptr;
   gbvector *result = heap[lead_so_far];
   return result;
 }
References Ring::add_to(), gbvector::coeff, F, GBRing::gbvector_compare(), GBRing::gbvector_remove(), GR, GT, heap, Ring::is_zero(), K, LT, mLead, gbvector::next, and top_of_heap.
Referenced by GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GBKernelComputation::geo_reduce(), MarkedGB::geo_remainder(), and remove_lead_term().