Macaulay2 Engine: ChineseRemainder::ratConversion
ratConversion() [2/3]
bool ChineseRemainder::ratConversion (mpz_srcptr a, mpz_srcptr m, mpq_t result) static
Definition at line 300 of file cra.cpp.
 {
   mpz_t a1, a2, u1, u2, q, h, mhalf, u2sqr, a2sqr;
   bool retVal = true;
   mpz_init_set(a1, m);
   mpz_init_set(a2, c);
   mpz_init_set_si(u1, 0);
   mpz_init_set_si(u2, 1);
   mpz_init_set_si(q, 0);
   mpz_init_set_si(h, 0);
   mpz_init(u2sqr);
   mpz_init(a2sqr);
   mpz_init(mhalf);
   mpz_tdiv_q_2exp(mhalf, m, 1);
   for (;;)
     {
       mpz_mul(u2sqr, u2, u2);
       if (mpz_cmp(u2sqr, mhalf) >= 0)  // u2sqr >= mhalf
         {
           retVal = false;
           mpq_set_z(result, c);
           break;
         }
       mpz_mul(a2sqr, a2, a2);
       if (mpz_cmp(a2sqr, mhalf) < 0)  // a2sqr < half
         {
           retVal = true;
           mpq_set_num(result, a2);
           mpq_set_den(result, u2);
           mpq_canonicalize(result);
           break;
         }
       mpz_fdiv_q(q, a1, a2);
       mpz_submul(a1, q, a2);
       mpz_submul(u1, q, u2);
       mpz_swap(a1, a2);
       mpz_swap(u1, u2);
     }
   // clean up
   // mpz_clears(a1,a2,u1,u2,q,h,mhalf,u2sqr,a2sqr,(void *)0);
   mpz_clear(a1);
   mpz_clear(a2);
   mpz_clear(u1);
   mpz_clear(u2);
   mpz_clear(q);
   mpz_clear(h);
   mpz_clear(mhalf);
   mpz_clear(u2sqr);
   mpz_clear(a2sqr);
   return retVal;
 }
Referenced by ratConversion(), rawMatrixRatConversion(), and rawRingElementRatConversion().