Macaulay2 Engine: ChineseRemainder::CRA
CRA() [1/5]
Matrix * ChineseRemainder::CRA (const Matrix * f, const Matrix * g, mpz_srcptr um, mpz_srcptr vn, mpz_srcptr mn) static
Definition at line 252 of file cra.cpp.
 {
   if (f->get_ring() != g->get_ring())
     {
       ERROR("matrices have different base rings");
       return nullptr;
     }
   if (f->rows()->rank() != g->rows()->rank() ||
       f->cols()->rank() != g->cols()->rank())
     {
       ERROR("matrices have different shapes");
       return nullptr;
     }
   const PolyRing *R = f->get_ring()->cast_to_PolyRing();
   if (R == nullptr)
     {
       ERROR("expected polynomial ring over ZZ");
       return nullptr;
     }
   const FreeModule *F = f->rows();
   const FreeModule *G = f->cols();
   const int *deg;
   if (!f->rows()->is_equal(g->rows())) F = R->make_FreeModule(f->n_rows());
   if (!f->cols()->is_equal(g->cols())) G = R->make_FreeModule(f->n_cols());
   if (EQ == f->degree_monoid()->compare(f->degree_shift(), g->degree_shift()))
     deg = f->degree_shift();
   else
     deg = f->degree_monoid()->make_one();
   MatrixConstructor mat(F, G, deg);
   for (int i = 0; i < f->n_cols(); i++)
     {
       vec u = CRA(R, f->elem(i), g->elem(i), um, vn, mn);
       mat.set_column(i, u);
     }
   return mat.to_matrix();
 }
References Ring::cast_to_PolyRing(), Matrix::cols(), Monoid::compare(), CRA(), Matrix::degree_monoid(), Matrix::degree_shift(), Matrix::elem(), EQ, ERROR(), Matrix::get_ring(), FreeModule::is_equal(), Ring::make_FreeModule(), Monoid::make_one(), Matrix::n_cols(), Matrix::n_rows(), FreeModule::rank(), Matrix::rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().