Macaulay2 Engine: ChineseRemainder::CRA
CRA() [2/5]
ring_elem ChineseRemainder::CRA (const PolyRing * R, const ring_elem f, const ring_elem g, mpz_srcptr um, mpz_srcptr vn, mpz_srcptr mn) static
Definition at line 53 of file cra.cpp.
 {
   mpz_t result_coeff;
   mpz_t mn_half;
   mpz_init(result_coeff);
   mpz_init(mn_half);
   Nterm *f = ff;
   Nterm *g = gg;
   Nterm head;
   Nterm *result = &head;
   mpz_tdiv_q_2exp(mn_half, mn, 1);
   const Monoid *M = R->getMonoid();
   const Ring *K = R->getCoefficientRing();
   while (1)
     {
       if (g == nullptr)
         {
           // mult each term of f by n:
           for (; f != nullptr; f = f->next)
             {
               result->next = R->new_term();
               result = result->next;
               result->next = nullptr;
               M->copy(f->monom, result->monom);
               mpz_mul(result_coeff, f->coeff.get_mpz(), vn);
               mpz_mod(result_coeff, result_coeff, mn);
               if (mpz_cmp(result_coeff, mn_half) > 0)
                 {
                   mpz_sub(result_coeff, result_coeff, mn);
                 }
               result->coeff = K->from_int(result_coeff);
             }
           break;
         }
       if (f == nullptr)
         {
           // mult each term of g by n:
           for (; g != nullptr; g = g->next)
             {
               result->next = R->new_term();
               result = result->next;
               result->next = nullptr;
               M->copy(g->monom, result->monom);
               mpz_mul(result_coeff, g->coeff.get_mpz(), um);
               mpz_mod(result_coeff, result_coeff, mn);
               if (mpz_cmp(result_coeff, mn_half) > 0)
                 {
                   mpz_sub(result_coeff, result_coeff, mn);
                 }
               result->coeff = K->from_int(result_coeff);
             }
           break;
         }
       switch (M->compare(f->monom, g->monom))
         {
           case -1:
             result->next = R->new_term();
             result = result->next;
             result->next = nullptr;
             M->copy(g->monom, result->monom);
             mpz_mul(result_coeff, g->coeff.get_mpz(), um);
             result->coeff = K->from_int(result_coeff);
             g = g->next;
             break;
           case 1:
             result->next = R->new_term();
             result = result->next;
             result->next = nullptr;
             M->copy(f->monom, result->monom);
             mpz_mul(result_coeff, f->coeff.get_mpz(), vn);
             result->coeff = K->from_int(result_coeff);
             f = f->next;
             break;
           case 0:
             Nterm *tmf = f;
             Nterm *tmg = g;
             f = f->next;
             g = g->next;
             CRA0(tmf->coeff.get_mpz(),
                  tmg->coeff.get_mpz(),
                  um,
                  vn,
                  mn,
                  result_coeff);
             Nterm *t = R->new_term();
             M->copy(tmf->monom, t->monom);
             t->coeff = K->from_int(result_coeff);
             t->next = nullptr;
             result->next = t;
             result = t;
             break;
         }
     }
   mpz_clear(result_coeff);
   mpz_clear(mn_half);
   result->next = nullptr;
   return head.next;
 }
References Nterm::coeff, Monoid::compare(), Monoid::copy(), CRA0(), Ring::from_int(), ring_elem::get_mpz(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), Nterm::monom, PolyRing::new_term(), and Nterm::next.
Referenced by CRA(), rawMatrixCRA(), and rawRingElementCRA().