Macaulay2 Engine: ChineseRemainder::ratConversion
ratConversion() [1/3]
ring_elem ChineseRemainder::ratConversion (const ring_elem f, mpz_srcptr m, const PolyRing * RQ) static
Definition at line 358 of file cra.cpp.
 {
   mpq_t result_coeff;
   mpq_init(result_coeff);
   Nterm *f = ff;
   Nterm head;
   Nterm *result = &head;
   const Monoid *M = RQ->getMonoid();
   const Ring *K = RQ->getCoefficientRing();
   for (; f != nullptr; f = f->next)
     {
       result->next = RQ->new_term();
       result = result->next;
       result->next = nullptr;
       M->copy(f->monom, result->monom);
       ratConversion(f->coeff.get_mpz(), m, result_coeff);
       bool ok1 = K->from_rational(result_coeff, result->coeff);
       (void)ok1;
       assert(ok1);  // K is supposed to contain (or be) the rationals, so this
                     // should not fail.
     }
   mpq_clear(result_coeff);
   result->next = nullptr;
   return head.next;
 }
References Nterm::coeff, Monoid::copy(), Ring::from_rational(), ring_elem::get_mpz(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), Nterm::monom, PolyRing::new_term(), Nterm::next, and ratConversion().