Macaulay2 Engine: Computation::set_status
set_status()
enum ComputationStatusCode Computation::set_status (enum ComputationStatusCode c) protected
Definition at line 61 of file comp.cpp.
 {
   switch (computation_status)
     {
       case COMP_OVERFLOWED:
         // if (computation_status == COMP_NEED_RESIZE) break;
         throw(exc::internal_error(
             "attempted to reset status of a computation that overflowed"));
       default:
         return computation_status = c;
     }
 }
Referenced by binomialGB_comp::binomialGB_comp(), gbA::do_computation(), GBDeclared::GBDeclared(), res_comp::gens(), gbA::initialize(), res2_comp::initialize(), ReducedGB::ReducedGB(), GBProxy::replace_GB(), GBProxy::start_computation(), GaussElimComputation::start_computation(), GB_comp::start_computation(), GBinhom_comp::start_computation(), binomialGB_comp::start_computation(), GBWalker::start_computation(), HermiteComputation::start_computation(), res2_comp::start_computation(), and gbres_comp::start_computation().