Macaulay2 Engine: Computation::start_computation
start_computation()
virtual void Computation::start_computation () pure virtual
Implemented in ResolutionComputation, GBComputation, F4Computation, F4ResComputation, gbres_comp, res_comp, res2_comp, ReducedGB, NCResComputation, HermiteComputation, GBWalker, binomialGB_comp, GBinhom_comp, GB_comp, gbA, GaussElimComputation, GBKernelComputation, GBProxy, and GBDeclared.
Referenced by PolyRingQuotient::make_gb(), rawStartComputation(), and PolyRingQuotient::syzygy().