Macaulay2 Engine: Computation::status
status()
enum ComputationStatusCode Computation::status () const inline
Definition at line 37 of file comp.hpp.
 { return computation_status; }
Referenced by GaussElimComputation::complete_thru_degree(), HermiteComputation::complete_thru_degree(), res_comp::gens(), rawStartComputation(), GBProxy::replace_GB(), GBProxy::start_computation(), GaussElimComputation::start_computation(), GBWalker::start_computation(), HermiteComputation::start_computation(), and res2_comp::start_computation().