Macaulay2 Engine: Computation::cast_to_GBComputation
cast_to_GBComputation()
virtual GBComputation* Computation::cast_to_GBComputation () inline virtual
Reimplemented in GBComputation, ReducedGB, GBProxy, and GBDeclared.
Definition at line 60 of file comp.hpp.
 { return nullptr; }
Referenced by IM2_GB_contains(), IM2_GB_matrix_lift(), IM2_GB_set_hilbert_function(), IM2_Ring_localization(), rawGBChangeOfBasis(), rawGBGetLeadTerms(), rawGBGetMatrix(), rawGBGetParallelLeadTerms(), rawGBMatrixRemainder(), rawGBMinimalGenerators(), rawGBSyzygies(), rawSubduction(), and rawSubduction1().