Macaulay2 Engine: now
now()
std::chrono::steady_clock::time_point now () inline
Definition at line 9 of file timing.hpp.
 {
   return std::chrono::steady_clock::now();
 }
Referenced by NCF4::process(), timer(), and HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track().