Macaulay2 Engine: seconds
seconds()
template<typename DurationType > double seconds (DurationType time_diff)
Definition at line 29 of file timing.hpp.
 {
   return 1.0e-9 *
          static_cast<double>(
              std::chrono::duration_cast<std::chrono::nanoseconds>(time_diff)
                  .count());
 }
Referenced by F4Res::clearMatrix(), F4Res::construct(), SchreyerFrame::getBetti(), NCF4::process(), SchreyerFrame::rankUsingDenseMatrix(), SchreyerFrame::rankUsingDenseMatrixFlint(), SchreyerFrame::rankUsingSparseMatrix(), F4Res::reorderColumns(), and SchreyerFrame::start_computation().