Macaulay2 Engine: timer
timer()
std::chrono::steady_clock::time_point timer () inline
Definition at line 5 of file timing.hpp.
 {
   return std::chrono::steady_clock::now();
 }
References now().
Referenced by F4Res::clearMatrix(), F4Res::construct(), SchreyerFrame::getBetti(), SchreyerFrame::rankUsingDenseMatrix(), SchreyerFrame::rankUsingDenseMatrixFlint(), SchreyerFrame::rankUsingSparseMatrix(), F4Res::reorderColumns(), and SchreyerFrame::start_computation().