Macaulay2 Engine: parseMsolveFile
parseMsolveFile()
BasicPolyList parseMsolveFile (std::string filename)
Definition at line 286 of file BasicPolyListParser.cpp.
 {
   std::string fileContents { readEntireFile(filename) };
   return parseMsolveFromString(fileContents);
 }
References parseMsolveFromString(), and readEntireFile().
Referenced by rawMatrixReadMsolveFile().