Macaulay2 Engine: parseMsolveFromString
parseMsolveFromString()
BasicPolyList parseMsolveFromString (std::string contents)
Definition at line 249 of file BasicPolyListParser.cpp.
 {
   // Read in file
   // Read in enough of the header to get identifiers
   IdentifierHash idenMap;
   std::string_view fileView { contents };
   BasicPolyList Fs;
   while (fileView.size() > 0)
     {
       std::string_view thisline = next_line(fileView);
       if (lineContainsVars(thisline))
         {
           std::vector<std::string> idenList = readIdentifierList(thisline);
           /*
             std::cout << "-- idenList" << std::endl;
           for (auto& id : idenList)
             std::cout << id << std::endl;
           */
           idenMap = { idenList };
           continue;
         }
       if (thisline.size() == 0 or thisline[0] == '#' or thisline[0] == ']')
         {
           continue;
         }
       BasicPoly F;
       parseBasicPoly(thisline, idenMap, F);
       Fs.push_back(F);
     }
   return Fs;
 }
References lineContainsVars(), next_line(), parseBasicPoly(), and readIdentifierList().
Referenced by parseMsolveFile(), rawMatrixReadMsolveString(), and TEST().