Macaulay2 Engine: M2::RingQQ::create
create()
static RingQQ* M2::RingQQ::create () inline static
Definition at line 424 of file aring-glue.hpp.
   {
     auto R0 = std::make_unique<ARingQQ>();
     auto characteristic = R0->characteristic();
     RingQQ *result = new RingQQ(std::move(R0));
     result->initialize_ring(characteristic);
     result->declare_field();
     result->zeroV = result->from_long(0);
     result->oneV = result->from_long(1);
     result->minus_oneV = result->from_long(-1);
     return result;
   }
References Ring::characteristic(), Ring::declare_field(), M2::ConcreteRing< RingType >::from_long(), Ring::initialize_ring(), Ring::minus_oneV, Ring::oneV, RingQQ(), and Ring::zeroV.
Referenced by initializeRationalRing().