Macaulay2 Engine: M2::RingQQ::fraction
fraction()
ring_elem M2::RingQQ::fraction (ring_elem top, ring_elem bottom) const inline
Definition at line 439 of file aring-glue.hpp.
   {
     mpz_srcptr numer = top.get_mpz();
     mpz_srcptr denom = bottom.get_mpz();
     mpq_ptr b = getmemstructtype(mpq_ptr);
     mpq_init(b);
     mpz_set(mpq_numref(b), numer);
     mpz_set(mpq_denref(b), denom);
     mpq_canonicalize(b);
     mpz_reallocate_limbs(mpq_numref(b));
     mpz_reallocate_limbs(mpq_denref(b));
     return ring_elem(b);
   }
References ring_elem::get_mpz(), getmemstructtype, and mpz_reallocate_limbs().
Referenced by RingElement::fraction(), and PolyRing::translate_gbvector_to_vec_QQ().