Macaulay2 Engine: Interreducer::showElem
showElem()
void Interreducer::showElem (int i, int nterms)
Definition at line 13 of file interreduce.cpp.
 {
   buffer o;
   R->gbvector_text_out(o, F, G[i], nterms);
   emit(o.str());
 }
References emit(), F, G, GBRing::gbvector_text_out(), R, and buffer::str().