Macaulay2 Engine: M2::ARingZZpFFPACK::computeGenerator
computeGenerator()
ARingZZpFFPACK::ElementType M2::ARingZZpFFPACK::computeGenerator () const
Todo:
Remove this function? IE: rewrite it? http://www.johnkerl.org/doc/ffcomp.pdf
Definition at line 35 of file aring-zzp-ffpack.cpp.
 {
   for (UTT currIntElem = 2; currIntElem < mCharac; currIntElem++)
     {
       ElementType currElem;
       set_from_long(currElem, currIntElem);
       bool found = true;
       ElementType tmpElem = currElem;
       for (UTT count = 0; count < mCharac - 2; count++)
         {
           mult(tmpElem, tmpElem, currElem);
           if (is_equal(currElem, tmpElem)) found = false;
         }
       if (found)
         {
           std::cerr << "generator = " << currElem << std::endl;
           return currElem;
         }
     }
   throw exc::internal_error("program logic in ffpack code is wrong if we get to this error");
 }
References is_equal(), mCharac, mult(), and set_from_long().
Referenced by getGenerator().