Macaulay2 Engine: M2::ARingZZpFFPACK::power
power()
void M2::ARingZZpFFPACK::power (ElementType & result, const ElementType a, const STT n) const
Definition at line 185 of file aring-zzp-ffpack.cpp.
 {
   if (is_zero(a))
     {
       if (n < 0)
         throw exc::division_by_zero_error();
       else if (n == 0)
         set_from_long(result, 1);
       else
         set_zero(result);
       return;
     }
   ElementType base;
   set(base, a);
   if (n < 0)
     {
       invert(base, base);
       n = -n;
     }
   n = n % (mCharac - 1);
   set_from_long(result, 1);
   if (n == 0) return;
   // Now use doubling algorithm
   for (;;)
     {
       if ((n % 2) != 0) mFfpackField.mulin(result, base);  // result *= base
       n >>= 1;
       if (n == 0)
         return;
       else
         mFfpackField.mulin(base, base);  // base = base^2
     }
 }
References base, invert(), is_zero(), mCharac, mFfpackField, set(), set_from_long(), and set_zero().
Referenced by power_mpz().