Macaulay2 Engine: M2::ARingZZpFFPACK::power_mpz
power_mpz()
void M2::ARingZZpFFPACK::power_mpz (ElementType & result, const ElementType a, mpz_srcptr n) const
Precondition
ensure that mFfpackField.cardinality() fits in a unsigned long, otherwise instead of mpz_fdiv_ui a different function has to be called)
Definition at line 224 of file aring-zzp-ffpack.cpp.
 {
   if (is_zero(a))
     {
       if (mpz_sgn(n) < 0)
         throw exc::division_by_zero_error();
       else if (mpz_sgn(n) == 0)
         set_from_long(result, 1);
       else
         set_zero(result);
     }
   else
     {
       // a != 0
       STT n1 = static_cast<STT>(mpz_fdiv_ui(n, mFfpackField.cardinality() - 1));
       power(result, a, n1);
     }
 }
References is_zero(), mFfpackField, power(), set_from_long(), and set_zero().