Macaulay2 Engine: intarray::raw
raw() [1/2]
int* intarray::raw () inline
Definition at line 75 of file intarray.hpp.
   {
     assert(entries != NULL);
     return entries;
   }
References entries.
Referenced by MonomialIdeal::alexander_dual(), SchreyerOrder::base_monom(), MonomialIdeal::borel(), MonomialIdeal::computeHashValue(), EngineMonomial::computeHashValue(), convertToFactory(), hilb_comp::do_ideal(), MonomialIdeal::erase(), PolyRing::eval(), MonomialIdeal::first_elem(), MonomialIdeal::insert(), MonomialIdeal::insert1(), MonomialIdeal::intersect(), EngineMonomial::ints(), iquotient_and_sum(), MonomialIdeal::is_borel(), SLP< Field >::jacobian(), MonomialIdeal::lcm(), RingElement::lead_monom(), PolyRing::list_form(), SchurRing2::list_form(), SLP< Field >::make(), binomial_ring::monomial_out(), MonomialIdeal::MonomialIdeal(), MonomialIdeal::n_pure_powers(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), MonomialIdeal::operator*(), MonomialIdeal::operator-(), partition_table::partition(), MonomialIdeal::quotient(), MonomialIdeal::radical(), MonomialIdeal::second_elem(), res_comp::skeleton_pairs(), MonomialIdeal::text_out(), EngineMonomial::text_out(), EngineMonomial::to_arrayint(), and TowerEvaluator::viewTerm().