Macaulay2 Engine: intarray::alloc
alloc()
int* intarray::alloc (int extra) inline
Definition at line 92 of file intarray.hpp.
   {
     if (len <= max + extra) expand(len + extra);
     int *result = entries + max;
     max += extra;
     return result;
   }
References entries, expand(), len, and max.
Referenced by SchreyerOrder::append(), copy(), PolyRing::diff_term(), hilb_comp::do_ideal(), varpower::erase(), varpower::from_arrayint(), varpower::from_expvector(), varpower::gcd(), varpower::lcm(), varpower::monsyz(), varpower::mult(), partition_table::partition_table(), varpower::power(), varpower::quotient(), varpower::radical(), and toVarpower().