Macaulay2 Engine: intarray::shrink
shrink()
void intarray::shrink (int newmax) inline
Definition at line 58 of file intarray.hpp.
   {
     if (newmax < max) max = newmax;
   }
References max.
Referenced by convertToFactory(), hilb_comp::do_ideal(), PolyRing::eval(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), PolyRing::list_form(), SchurRing2::list_form(), varpower::mult(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), QRingInfo_field::QRingInfo_field(), res_comp::skeleton_pairs(), toVarpower(), and TowerEvaluator::viewTerm().