Macaulay2 Engine: intarray::append
append()
void intarray::append (int t) inline
Definition at line 86 of file intarray.hpp.
   {
     if (max == len) expand(max);
     entries[max++] = t;
   }
References entries, expand(), len, and max.
Referenced by binomial_s_pair_set::binomial_s_pair_set(), SLP< Field >::concatenate(), Matrix::elim_keep(), Matrix::elim_vars(), gb2_comp::get_pairs(), binomial_s_pair_set::insert(), SLP< Field >::jacobian(), SLP< Field >::make(), varpower::one(), SLP< Field >::poly_to_horner_slp(), varpower::power(), rawIdealReorder(), toInteger(), and varpower::var().