Macaulay2 Engine: intarray::expand
expand()
void intarray::expand (int newtop)
Definition at line 5 of file intarray.cpp.
 {
   int *tmp =
       reinterpret_cast<int *>(doubles->new_elem(sizeof(int) * (newtop + 1)));
   for (int j = 0; j < max; j++) tmp[j] = entries[j];
   doubles->delete_elem(entries);
   entries = tmp;
   len = static_cast<int>(doubles->allocated_size(entries) / sizeof(int));
 }
References doubling_stash::allocated_size(), doubling_stash::delete_elem(), doubles, entries, len, max, and doubling_stash::new_elem().
Referenced by alloc(), and append().