Macaulay2 Engine: almostEqual
almostEqual()
bool almostEqual (const M2::ARingCCC & C, int nbits, const M2::ARingCCC::ElementType & a, const M2::ARingCCC::ElementType & b)
Definition at line 15 of file ARingCCCTest.cpp.
 {
   mpfr_t epsilon;
   mpfr_init2(epsilon, C.get_precision());
   mpfr_set_ui_2exp(epsilon, 1, -nbits, MPFR_RNDN);  // should there be exp() ???
   M2::ARingCCC::ElementType c;
   C.init(c);
   C.subtract(c, a, b);
   bool ret = mpfr_cmpabs(&c.re, epsilon) < 0 && mpfr_cmpabs(&c.im, epsilon) < 0;
   C.clear(c);
   mpfr_clear(epsilon);
   return ret;
 }
References M2::ARingCCC::clear(), M2::ARingCCC::get_precision(), cc_struct::im, M2::ARingCCC::init(), cc_struct::re, and M2::ARingCCC::subtract().
Referenced by TEST().