Macaulay2 Engine: TEST
TEST() [2/7]
TEST (ARingCCC , axioms)
Definition at line 162 of file ARingCCCTest.cpp.
 {
   M2::ARingCCC C(100);
   ARingElementGenerator<M2::ARingCCC> gen(C);
   M2::ARingCCC::ElementType a, b, c, d, e;
   C.init(a);
   C.init(b);
   C.init(c);
   C.init(d);
   C.init(e);
   for (int i = 0; i < ntrials; i++)
     {
       gen.nextElement(a);
       gen.nextElement(b);
       gen.nextElement(c);
       // Test commutativity
       // test: a*b = b*a
       // test: a+b == b+a
       C.add(d, a, b);
       C.add(e, b, a);
       EXPECT_TRUE(almostEqual(C, 98, d, e));
       C.mult(d, a, b);
       C.mult(e, b, a);
       EXPECT_TRUE(almostEqual(C, 98, d, e));
       // Test associativity
       // test: a+(b+c) == (a+b)+c
       // test: a*(b*c) == (a*b)*c
       C.add(e, b, c);
       C.add(d, a, e);  // a+(b+c)
       C.add(e, a, b);
       C.add(e, e, c);  // (a+b)+c
       EXPECT_TRUE(almostEqual(C, 94, d, e));
       C.mult(e, b, c);
       C.mult(d, a, e);  // a*(b*c)
       C.mult(e, a, b);
       C.mult(e, e, c);  // (a*b)*c
       EXPECT_TRUE(almostEqual(
           C, 93, d, e));  // MES: I'm not sure how equal these should be.
       // Test distributivity
       // test: a*(b+c) == a*b + a*c
       C.add(e, b, c);
       C.mult(d, a, e);  // a*(b+c)
       C.mult(b, a, b);
       C.mult(c, a, c);
       C.add(e, b, c);  // a*b + a*c
       EXPECT_TRUE(almostEqual(C, 93, d, e));
     }
   C.clear(e);
   C.clear(d);
   C.clear(c);
   C.clear(b);
   C.clear(a);
 }
References M2::ARingCCC::add(), almostEqual(), M2::ARingCCC::clear(), M2::ARingCCC::init(), M2::ARingCCC::mult(), ARingElementGenerator< RingType >::nextElement(), and ntrials.