Macaulay2 Engine: TEST
TEST() [6/7]
TEST (ARingCCC , power_and_invert)
Definition at line 218 of file ARingCCCTest.cpp.
 {
   M2::ARingCCC C(100);
   ARingElementGenerator<M2::ARingCCC> gen(C);
   M2::ARingCCC::ElementType a, b, c, d;
   C.init(a);
   C.init(b);
   C.init(c);
   C.init(d);
   mpz_t gmp1;
   mpz_init(gmp1);
   for (int i = 0; i < ntrials; i++)
     {
       gen.nextElement(a);
       // TODO: what should the answer here be?
       // EXPECT_TRUE(R->is_equal(R->power(a, 0), R->one())); // 0^0 == 1 too?
       C.power(b, a, 1);
       EXPECT_TRUE(C.is_equal(b, a));
       int e1 = rawRandomInt(10) + 1;
       int e2 = rawRandomInt(10) + 1;
       C.power(b, a, e1);
       C.power(c, a, e2);
       C.power(d, a, e1 + e2);
       C.mult(c, b, c);
       EXPECT_TRUE(almostEqual(C, 90, c, d)); /* exponentiation gives
                                                 relatively small number
                                                 of correct digits */
       // Make sure that powers via mpz work (at least for small exponents)
       mpz_set_si(gmp1, e1);
       C.power_mpz(d, a, gmp1);
       EXPECT_TRUE(C.is_equal(d, b));
     }
   mpz_clear(gmp1);
   C.clear(d);
   C.clear(c);
   C.clear(b);
   C.clear(a);
 }
References almostEqual(), M2::ARingCCC::clear(), M2::ARingCCC::init(), M2::ARingCCC::is_equal(), M2::ARingCCC::mult(), ARingElementGenerator< RingType >::nextElement(), ntrials, M2::ARingCCC::power(), M2::ARingCCC::power_mpz(), and rawRandomInt().