Macaulay2 Engine: testRingNegateCCC
testRingNegateCCC()
void testRingNegateCCC (const M2::ARingCCC & C, int ntrials)
Definition at line 53 of file ARingCCCTest.cpp.
 {
   ARingElementGenerator<M2::ARingCCC> gen(C);
   M2::ARingCCC::ElementType a, b, c;
   C.init(a);
   C.init(b);
   C.init(c);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (-a) + (a) == 0
       gen.nextElement(a);
       C.negate(b, a);
       C.add(c, a, b);
       EXPECT_TRUE(C.is_zero(c));
     }
   C.clear(c);
   C.clear(b);
   C.clear(a);
 }
References M2::ARingCCC::add(), M2::ARingCCC::clear(), M2::ARingCCC::init(), M2::ARingCCC::is_zero(), M2::ARingCCC::negate(), ARingElementGenerator< RingType >::nextElement(), and ntrials.
Referenced by TEST().