Macaulay2 Engine: M2::ARingZZpFlint::coerceToLongInteger
coerceToLongInteger()
long M2::ARingZZpFlint::coerceToLongInteger (const elem & f) const inline
Definition at line 56 of file aring-zzp-flint.hpp.
   {
     long result = f;
     if (result > characteristic() / 2) result -= characteristic();
     return result;
   }
References characteristic().
Referenced by elem_text_out(), eval(), ResGausserQQHybrid::out(), ResGausserQQ::out(), ResGausserQQHybrid::to_modp_long(), and ResGausserQQ::to_modp_long().