Macaulay2 Engine: M2::ARingZZpFlint::negate
negate()
void M2::ARingZZpFlint::negate (ElementType & result, ElementType a) const inline
Definition at line 116 of file aring-zzp-flint.hpp.
   {
     result = nmod_neg(a, mModulus);
   }
References mModulus.
Referenced by ResGausserQQHybrid::negate_element(), ResGausserQQ::pushBackNegatedElement(), ResGausserQQ::ResGausserQQ(), and syzygy().