Macaulay2 Engine: M2::ARingZZpFlint::eval
eval()
void M2::ARingZZpFlint::eval (const RingMap * map, const ElementType f, int first_var, ring_elem & result) const
Definition at line 47 of file aring-zzp-flint.cpp.
 {
   long a = coerceToLongInteger(f);
   result = map->get_ring()->from_long(a);
 }
References coerceToLongInteger(), Ring::from_long(), and RingMap::get_ring().