Macaulay2 Engine: M2::ARingZZpFlint::characteristic
characteristic()
size_t M2::ARingZZpFlint::characteristic () const inline
Definition at line 49 of file aring-zzp-flint.hpp.
 { return mCharac; }
References mCharac.
Referenced by coerceToLongInteger(), DMat< M2::ARingZZpFlint >::DMat(), and text_out().