Macaulay2 Engine: LLLoperations::REDI
REDI()
void LLLoperations::REDI (int k, int ell, MutableMatrix * A, MutableMatrix * Achange, MutableMatrix * lambda) static private
Definition at line 108 of file LLL.cpp.
 {
   // set q = ...
   // negate q.
   ring_elem Dl, mkl, q;
   if (!lambda->get_entry(ell, k, mkl)) return;
   lambda->get_entry(ell, ell, Dl);
   mpz_srcptr a = mkl.get_mpz();
   mpz_srcptr b = Dl.get_mpz();  // b = D#ell
   mpz_t c, d;
   mpz_init(c);
   mpz_init(d);
   mpz_mul_2exp(c, a, 1);  // c = 2*lambda#(k,ell)
   mpz_abs(d, c);          // d = abs(2*lambda#(k,ell)
   mpz_add(c, c, b);       // c = 2*lambda#(k,ell) + D#ell
   mpz_mul_2exp(d, b, 1);  // d = 2*D#ell
   mpz_fdiv_q(c, c, d);    // c = (almost) final q
   mpz_neg(c, c);
   q = ring_elem(c);
   // A->addColumnMultiple(ell,q,k);
   // lambda->addColumnMultiple(ell,q,k);
   A->column_op(k, q, ell);
   if (Achange) Achange->column_op(k, q, ell);
   lambda->column_op(k, q, ell);
   mpz_clear(c);
   mpz_clear(d);
 }
References MutableMatrix::column_op(), MutableMatrix::get_entry(), and ring_elem::get_mpz().
Referenced by doLLL().