Macaulay2 Engine: LLLoperations::LLL
LLL()
bool LLLoperations::LLL (MutableMatrix * M, MutableMatrix * U, gmp_QQ threshold) static
Definition at line 356 of file LLL.cpp.
 {
   MutableMatrix *LLLstate;
   if (!initializeLLL(A, threshold, LLLstate)) return false;
   int ret = doLLL(A, Achange, LLLstate);
   if (ret != COMP_DONE)
     {
       freemem(LLLstate);
       return false;
     }
   return true;
 }
References COMP_DONE, doLLL(), freemem(), and initializeLLL().
Referenced by rawLLL().