Macaulay2 Engine: LLLoperations::initializeLLL
initializeLLL()
bool LLLoperations::initializeLLL (const MutableMatrix * A, gmp_QQ threshold, MutableMatrix *& LLLstate) static private
Definition at line 28 of file LLL.cpp.
 {
   // First check m: should be a matrix over globalZZ.
   if (A == 0 || A->get_ring() != globalZZ)
     {
       ERROR("LLL only defined for matrices over ZZ");
       return false;
     }
   ring_elem num = globalZZ->from_int(mpq_numref(threshold));
   ring_elem den = globalZZ->from_int(mpq_denref(threshold));
   // Check that 'threshold' is in range, and set the numerator, denom
   if (!checkThreshold(num, den))
     {
       ERROR("LLL threshold should be in the range (1/4, 1]");
       globalZZ->remove(num);
       globalZZ->remove(den);
       return false;
     }
   // LLLstate has n+4 columns, and n rows.
   // First n columns: LLLstate(i,i) = D#i
   //                  LLLstate(i,j) = lambda#(j,i) for
   // Last four columns just have entries in row 0:
   // The entries are: k, kmax, alphaTop, alphaBottom: all are ZZ values.
   size_t n = A->n_cols();
   LLLstate = MutableMatrix::zero_matrix(globalZZ, n, n + 4, A->is_dense());
   if (n > 0)
     {
       LLLstate->set_entry(0, n, globalZZ->from_long(1));  // k := 2
       // LLLstate->set_entry(0,n+1,globalZZ->from_long(0)); // kmax := 1
       LLLstate->set_entry(
           0, n + 2, num);  // Set threshold numerator, denominator
       LLLstate->set_entry(0, n + 3, den);
       ring_elem dot;
       A->dot_product(0, 0, dot);
       LLLstate->set_entry(0, 0, dot);  // D#1 := dot(A,0,0)
     }
   return true;
 }
References checkThreshold(), MutableMatrix::dot_product(), ERROR(), RingZZ::from_int(), RingZZ::from_long(), MutableMatrix::get_ring(), globalZZ, MutableMatrix::is_dense(), MutableMatrix::n_cols(), RingZZ::remove(), MutableMatrix::set_entry(), and MutableMatrix::zero_matrix().
Referenced by LLL().