Macaulay2 Engine: LLLoperations::Lovasz
Lovasz()
bool LLLoperations::Lovasz (MutableMatrix * lambda, int k, ring_elem alphaTop, ring_elem alphaBottom) static private
Definition at line 72 of file LLL.cpp.
 {
   // Test:alphaBottom * (D#(k-2) * D#k + lambda#(k,k-1)^2) <
   //              alphaTop * D#(k-1)^2
   ring_elem D2, D1, D, L;
   mpz_t a, b;
   lambda->get_entry(k - 1, k - 1, D1);
   lambda->get_entry(k, k, D);
   bool Lnotzero = lambda->get_entry(k - 1, k, L);
   if (k == 1)
     mpz_init_set(a, D.get_mpz());
   else
     {
       mpz_init(a);
       lambda->get_entry(k - 2, k - 2, D2);
       mpz_mul(a, D2.get_mpz(), D.get_mpz());
     }
   mpz_init(b);
   if (Lnotzero)
     {
       mpz_mul(b, L.get_mpz(), L.get_mpz());
       mpz_add(a, a, b);
     }
   mpz_mul(a, a, alphaBottom.get_mpz());  // This is the LHS.
   mpz_mul(b, D1.get_mpz(), D1.get_mpz());
   mpz_mul(b, alphaTop.get_mpz(), b);  // RHS
   int cmp = mpz_cmp(a, b);
   mpz_clear(a);
   mpz_clear(b);
   return (cmp < 0);
 }
References MutableMatrix::get_entry(), and ring_elem::get_mpz().
Referenced by doLLL().