Macaulay2 Engine: LLLoperations::SWAPI
SWAPI()
void LLLoperations::SWAPI (int k, int kmax, MutableMatrix * A, MutableMatrix * Achange, MutableMatrix * lambda) static private
Definition at line 143 of file LLL.cpp.
 {
   int i;
   mpz_t a, b, B, C1, C2, D, D1, lam;
   ring_elem rD1, rD, rlam;
   A->interchange_columns(k, k - 1);
   if (Achange) Achange->interchange_columns(k, k - 1);
   mpz_init(a);
   mpz_init(b);
   mpz_init(B);
   mpz_init(C1);
   mpz_init(C2);
   lambda->get_entry(k - 1, k - 1, rD1);
   lambda->get_entry(k, k, rD);
   mpz_init_set(D1, rD1.get_mpz());
   mpz_init_set(D, rD.get_mpz());
   if (lambda->get_entry(k - 1, k, rlam))
     mpz_init_set(lam, rlam.get_mpz());
   else
     mpz_init(lam);
   // Interchange both of these columns, except for these three terms:
   if (k >= 2)
     {
       lambda->interchange_columns(k, k - 1);
       lambda->set_entry(k - 1, k, globalZZ->from_int(lam));
       lambda->set_entry(k, k, globalZZ->from_int(D));
       lambda->set_entry(k, k - 1, globalZZ->from_long(0));
       // (k-1,k-1) is set below.
     }
   // B := (D#(k-2) * D#k + lam^2) // D#(k-1);
   if (k == 1)
     mpz_set(a, D);
   else
     {
       ring_elem rD2;
       lambda->get_entry(k - 2, k - 2, rD2);
       mpz_mul(a, rD2.get_mpz(), D);
     }
   mpz_mul(b, lam, lam);
   mpz_add(a, a, b);
   mpz_fdiv_q(B, a, D1);
   lambda->set_entry(k - 1, k - 1, globalZZ->from_int(B));
   // scan(k+1..C.kmax, i-> (
   //     t := lambda#(i,k);
   //     lambda#(i,k) = (D#k * lambda#(i,k-1) - lam * t) // D#(k-1);
   //     lambda#(i,k-1) = (B*t + lam*lambda#(i,k))//(D#k);));
   for (i = k + 1; i <= kmax; i++)
     {
       ring_elem s, t;
       bool s_notzero = lambda->get_entry(k - 1, i, s);
       bool t_notzero = lambda->get_entry(k, i, t);
       if (s_notzero)
         mpz_mul(a, D, s.get_mpz());
       else
         mpz_set_ui(a, 0);
       // lambda#(i,k) = (D#k * lambda#(i,k-1) - lam * t) // D#(k-1);
       if (t_notzero)
         mpz_mul(b, lam, t.get_mpz());
       else
         mpz_set_ui(b, 0);
       mpz_sub(a, a, b);
       mpz_fdiv_q(C1, a, D1);
       // lambda#(i,k-1) = (B*t + lam*lambda#(i,k))//(D#k);));
       mpz_mul(b, lam, C1);
       if (t_notzero)
         mpz_mul(a, B, t.get_mpz());
       else
         mpz_set_ui(a, 0);
       mpz_add(a, a, b);
       mpz_fdiv_q(C2, a, D);
       lambda->set_entry(
           k, i, globalZZ->from_int(C1));  // These two lines will remove t,s.
       lambda->set_entry(k - 1, i, globalZZ->from_int(C2));
     }
   mpz_clear(a);
   mpz_clear(b);
   mpz_clear(B);
   mpz_clear(C1);
   mpz_clear(C2);
   mpz_clear(D1);
   mpz_clear(D);
   mpz_clear(lam);
 }
References RingZZ::from_int(), RingZZ::from_long(), MutableMatrix::get_entry(), ring_elem::get_mpz(), globalZZ, MutableMatrix::interchange_columns(), and MutableMatrix::set_entry().
Referenced by doLLL().