Macaulay2 Engine: gbres_comp::start_computation
start_computation()
void gbres_comp::start_computation () virtual
Implements ResolutionComputation.
Definition at line 191 of file res-a2.cpp.
 {
   //  int old_compare_type = compare_type;
   //  compare_type = (strategy_flags >> 10);
   //  if (M2_gbTrace >= 4)
   //    {
   //      buffer o;
   //      o << "compare=" << compare_type << newline;
   //      emit(o.str());
   //    }
   for (int i = lo_degree; !is_done(); i++)
     {
       if (stop_.stop_after_degree && stop_.degree_limit->array[0] < i)
         {
           set_status(COMP_DONE_DEGREE_LIMIT);
           //      compare_type = old_compare_type;
           return;
         }
       if (M2_gbTrace >= 1)
         {
           buffer o;
           o << "{" << i << "}";
           emit(o.str());
         }
       enum ComputationStatusCode ret =
           nodes[n_nodes - 1]->calc_gens(i + n_nodes - 3);
       if (ret != COMP_DONE)
         {
           set_status(ret);
           //      compare_type = old_compare_type;
           return;
         }
       last_completed_degree = i;
     }
   //  compare_type = old_compare_type;
   set_status(COMP_DONE);
 }
References gb_node::calc_gens(), COMP_DONE, COMP_DONE_DEGREE_LIMIT, StopConditions::degree_limit, emit(), is_done(), last_completed_degree, lo_degree, M2_gbTrace, n_nodes, nodes, Computation::set_status(), Computation::stop_, StopConditions::stop_after_degree, and buffer::str().