Macaulay2 Engine: gbres_comp::setup
setup()
void gbres_comp::setup (const Matrix * m, int length, int origsyz, int strategy) private
Definition at line 79 of file res-a2.cpp.
 {
   int i;
   originalR = m->get_ring()->cast_to_PolynomialRing();
   if (originalR == nullptr) assert(0);
   GR = originalR->get_gb_ring();
   mi_stash = new stash("res mi nodes", sizeof(Nmi_node));
   FreeModule *Fsyz = originalR->make_Schreyer_FreeModule();
   if (length <= 0)
     {
       ERROR("resolution length must be at least 1");
       length = 1;
     }
   // If origsyz, and length>1, create Fsyz as a Schreyer free
   // if origsyz is smaller, truncate this module...
   if (length > 1 && origsyz > 0)
     {
       if (origsyz > m->n_cols()) origsyz = m->n_cols();
       monomial one = originalR->getMonoid()->make_one();
       const int *mon;
       for (i = 0; i < origsyz; i++)
         {
           if ((*m)[i] == nullptr)
             mon = one;
           else
             {
               Nterm *t = (*m)[i]->coeff;
               mon = t->monom;
             }
           Fsyz->append_schreyer(m->cols()->degree(i), mon, i);
         }
       originalR->getMonoid()->remove(one);
     }
   lo_degree = m->cols()->lowest_primary_degree();
   last_completed_degree = lo_degree - 1;
   n_nodes = length + 1;
   nodes = newarray(gb_node_ptr, n_nodes);
   nodes[0] = new gb_emitter(m);
   nodes[1] =
       new gb2_comp(Fsyz, mi_stash, nodes[0], lo_degree, origsyz, 1, strategy);
   nodes[0]->set_output(nodes[1]);
   if (n_nodes == 2)
     {
       // Don't compute syzygies at all.
       nodes[1]->set_output(nullptr);
     }
   else if (n_nodes >= 3)
     {
       // Compute a resolution to length 'length', with last being
       // a gb node.
       int deg = lo_degree + 1;
       if (origsyz > 0) deg--;
       for (i = 2; i < n_nodes - 1; i++)
         {
           FreeModule *F = originalR->make_Schreyer_FreeModule();
           nodes[i] =
               new gb2_comp(F, mi_stash, nodes[i - 1], deg++, -1, i, strategy);
           nodes[i - 1]->set_output(nodes[i]);
         }
       FreeModule *F = originalR->make_Schreyer_FreeModule();
       nodes[n_nodes - 1] = new gb2_comp(
           F, mi_stash, nodes[n_nodes - 2], deg++, 0, n_nodes - 1, strategy);
       nodes[n_nodes - 1]->set_output(nullptr);
     }
   strategy_flags = strategy;
 }
References FreeModule::append_schreyer(), Ring::cast_to_PolynomialRing(), Nterm::coeff, Matrix::cols(), FreeModule::degree(), ERROR(), PolynomialRing::get_gb_ring(), Matrix::get_ring(), PolynomialRing::getMonoid(), GR, last_completed_degree, lo_degree, FreeModule::lowest_primary_degree(), Monoid::make_one(), Ring::make_Schreyer_FreeModule(), mi_stash, Nterm::monom, Matrix::n_cols(), n_nodes, newarray, nodes, originalR, Monoid::remove(), gb_node::set_output(), and strategy_flags.
Referenced by gbres_comp().