Macaulay2 Engine: gbres_comp::free_module
free_module()
const FreeModule * gbres_comp::free_module (int level) const
Definition at line 274 of file res-a2.cpp.
 {
   if (level >= 0 && level <= n_nodes - 1)
     return const_cast<FreeModule *>(nodes[level]->output_free_module());
   return nodes[0]->output_free_module()->get_ring()->make_FreeModule();
 }
References FreeModule::get_ring(), Ring::make_FreeModule(), n_nodes, nodes, and gb_node::output_free_module().
Referenced by betti_minimal(), change_matrix(), gb_matrix(), get_free(), get_matrix(), initial_matrix(), and min_gens_matrix().