Macaulay2 Engine: gbres_comp::reduce
reduce()
Matrix * gbres_comp::reduce (const Matrix * m, Matrix *& lift)
Definition at line 239 of file res-a2.cpp.
 {
   const FreeModule *F = nodes[0]->output_free_module();
   if (m->n_rows() != F->rank())
     {
       ERROR("expected matrices to have same number of rows");
       return nullptr;
     }
   MatrixConstructor mat_red(m->rows(), m->cols(), m->degree_shift());
   MatrixConstructor mat_lift(nodes[1]->output_free_module(), m->cols(), nullptr);
   for (int i = 0; i < m->n_cols(); i++)
     {
       const FreeModule *Fsyz = nodes[1]->output_free_module();
       ring_elem denom;
       gbvector *f = originalR->translate_gbvector_from_vec(F, (*m)[i], denom);
       gbvector *fsyz = GR->gbvector_zero();
       nodes[1]->reduce(f, fsyz);
       vec fv = originalR->translate_gbvector_to_vec_denom(F, f, denom);
       GR->get_flattened_coefficients()->negate_to(denom);
       vec fsyzv = originalR->translate_gbvector_to_vec_denom(Fsyz, fsyz, denom);
       mat_red.set_column(i, fv);
       mat_lift.set_column(i, fsyzv);
     }
   lift = mat_lift.to_matrix();
   return mat_red.to_matrix();
 }
References Matrix::cols(), Matrix::degree_shift(), ERROR(), GBRing::gbvector_zero(), GBRing::get_flattened_coefficients(), GR, Matrix::n_cols(), Matrix::n_rows(), Ring::negate_to(), nodes, originalR, gb_node::output_free_module(), FreeModule::rank(), gb_node::reduce(), Matrix::rows(), MatrixConstructor::set_column(), MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_from_vec(), and PolynomialRing::translate_gbvector_to_vec_denom().