Macaulay2 Engine: gbres_comp::min_gens_matrix
min_gens_matrix()
const Matrix * gbres_comp::min_gens_matrix (int level)
Definition at line 280 of file res-a2.cpp.
 {
   if (level <= 0 || level >= n_nodes)
     return Matrix::zero(free_module(level - 1), free_module(level));
   return nodes[level]->min_gens_matrix();
 }
References free_module(), gb_node::min_gens_matrix(), n_nodes, nodes, and Matrix::zero().