Macaulay2 Engine: gbres_comp::betti_minimal
betti_minimal()
M2_arrayint gbres_comp::betti_minimal () const
Definition at line 326 of file res-a2.cpp.
 {
   int lev, i, d;
   int lo = nodes[0]->output_free_module()->lowest_primary_degree();
   if (n_nodes >= 2)
     {
       int lo1 = nodes[1]->output_free_module()->lowest_primary_degree() - 1;
       if (lo1 < lo) lo = lo1;
     }
   if (n_nodes >= 3)
     {
       int lo2 = nodes[2]->output_free_module()->lowest_primary_degree() - 2;
       if (lo2 < lo) lo = lo2;
     }
   int hi = lo;
   int len = 1;
   // Set the hi degree, and len
   for (lev = 0; lev < n_nodes; lev++)
     {
       const FreeModule *F = free_module(lev);
       if (F->rank() > 0) len = lev;
       for (i = 0; i < F->rank(); i++)
         {
           d = F->primary_degree(i) - lev;
           if (d > hi) hi = d;
         }
     }
   int *bettis;
   betti_init(lo, hi, len, bettis);
   for (lev = 0; lev <= len; lev++)
     {
       const FreeModule *F = free_module(lev);
       for (i = 0; i < F->rank(); i++)
         {
           d = F->primary_degree(i) - lev - lo;
           bettis[lev + (len + 1) * d]++;
         }
     }
   M2_arrayint result = betti_make(lo, hi, len, bettis);
   freemem(bettis);
   return result;
 }
References ResolutionComputation::betti_init(), ResolutionComputation::betti_make(), free_module(), freemem(), FreeModule::lowest_primary_degree(), n_nodes, nodes, gb_node::output_free_module(), FreeModule::primary_degree(), and FreeModule::rank().