Macaulay2 Engine: s_pair_heap::compare
compare()
int s_pair_heap::compare (s_pair * f, s_pair * g) const private
Definition at line 66 of file spair.cpp.
 {
   int cmp = f->degree - g->degree;
   if (cmp < 0) return -1;
   if (cmp > 0) return 1;
   int compare_type =
       0;  // MES: res-a2.cpp would change this globally, uugh.  Doesn't seem to
           // be used at all, so I am just commenting this out.
   switch (compare_type)
     {
       case 0:
         cmp = M->compare(f->lcm, g->lcm);
         if (cmp != 0)
           return cmp;  // MES: changed cmp to -cmp, to try out different order
                        // 2/21/00.
         if (f->first == NULL || g->first == NULL) return 0;
         cmp = f->first->me - g->first->me;
         if (cmp > 0) return 1;
         if (cmp < 0) return -1;
         break;
       case 1:
         cmp = M->compare(f->lcm, g->lcm);
         if (cmp != 0)
           return -cmp;  // MES: changed cmp to -cmp, to try out different order
                         // 2/21/00.
         if (f->first == NULL || g->first == NULL) return 0;
         cmp = f->first->me - g->first->me;
         if (cmp > 0) return 1;
         if (cmp < 0) return -1;
         break;
       case 2:
         if (f->first != NULL && g->first != NULL)
           {
             cmp = f->first->me - g->first->me;
             if (cmp < 0) return -1;
             if (cmp > 0) return 1;
           }
         if (f->second != NULL && g->second != NULL)
           {
             cmp = f->second->me - g->second->me;
             if (cmp < 0) return -1;
             if (cmp > 0) return 1;
           }
         cmp = M->compare(f->lcm, g->lcm);
         if (cmp != 0) return cmp;
         if (f->first == NULL || g->first == NULL) return 0;
         cmp = f->first->me - g->first->me;
         if (cmp > 0) return 1;
         if (cmp < 0) return -1;
         break;
       default:
         return -1;
         break;
     }
   return 0;
 }
References Monoid::compare(), s_pair::degree, s_pair::first, s_pair::lcm, M, gb_elem::me, and s_pair::second.
Referenced by merge(), and remove().