Macaulay2 Engine: s_pair_heap::sort_list
sort_list()
void s_pair_heap::sort_list (s_pair *& p) const
Definition at line 156 of file spair.cpp.
{
  if (p == nullptr || p->next == nullptr) return;
  s_pair *p1 = nullptr;
  s_pair *p2 = nullptr;
  while (p != nullptr)
    {
      s_pair *tmp = p;
      p = p->next;
      tmp->next = p1;
      p1 = tmp;
      if (p == nullptr) break;
      tmp = p;
      p = p->next;
      tmp->next = p2;
      p2 = tmp;
    }
  sort_list(p1);
  sort_list(p2);
  p = merge(p1, p2);
}
References merge(), s_pair::next, p, p1, and sort_list().
Referenced by GBinhom_comp::find_pairs(), and sort_list().