Macaulay2 Engine: s_pair_heap::put_back
put_back()
void s_pair_heap::put_back (s_pair *& p)
Definition at line 263 of file spair.cpp.
 {
   insert(p);
   p = nullptr;
 }
References insert(), and p.
Referenced by GB_comp::flush_pairs(), GB_comp::gen_step(), gb2_comp::get_pairs(), GB_comp::next_degree(), and GB_comp::s_pair_step().