Macaulay2 Engine: s_pair_heap::merge
merge()
s_pair * s_pair_heap::merge (s_pair * f, s_pair * g) const private
Definition at line 123 of file spair.cpp.
 {
   // Sort in ascending degree order, then ascending monomial order
   if (g == nullptr) return f;
   if (f == nullptr) return g;
   s_pair head;
   s_pair *result = &head;
   while (1) switch (compare(f, g))
       {
         case 1:
           result->next = g;
           result = result->next;
           g = g->next;
           if (g == nullptr)
             {
               result->next = f;
               return head.next;
             }
           break;
         case -1:
         case 0:
           result->next = f;
           result = result->next;
           f = f->next;
           if (f == nullptr)
             {
               result->next = g;
               return head.next;
             }
           break;
       }
 }
References compare(), and s_pair::next.
Referenced by insert(), and sort_list().