Macaulay2 Engine: s_pair_heap::remove
remove()
s_pair * s_pair_heap::remove ()
Definition at line 225 of file spair.cpp.
 {
   // Find a non-zero element
   if (nelems == 0) return NULL;
   int i, first;
   for (first = 0; first <= top_of_heap; first++)
     if (n_in_heap[first] > 0) break;
   s_pair *smallest = heap[first];
   // Now find the smallest one
   for (i = first + 1; i <= top_of_heap; i++)
     {
       if (heap[i] == NULL) continue;
       int cmp = compare(smallest, heap[i]);
       if (cmp > 0)
         {
           first = i;
           smallest = heap[first];
         }
     }
   // Now remove this element and return it:
   heap[first] = smallest->next;
   smallest->next = NULL;
   nelems--;
   n_in_heap[first]--;
   if (n_in_heap[top_of_heap] == 0)
     for (i = top_of_heap - 1; i >= 0; i--)
       if (n_in_heap[i] > 0)
         {
           top_of_heap = i;
           break;
         }
   return smallest;
 }
References compare(), heap, n_in_heap, nelems, s_pair::next, and top_of_heap.
Referenced by GB_comp::flush_pairs(), GB_comp::gen_step(), gb2_comp::get_pairs(), GB_comp::next_degree(), GB_comp::s_pair_step(), and GBinhom_comp::start_computation().