Macaulay2 Engine: s_pair_heap::insert
insert() [1/2]
void s_pair_heap::insert (s_pair *& p)
Definition at line 180 of file spair.cpp.
 {
   heap[0] = merge(p, heap[0]);
   n_in_heap[0]++;
   p = NULL;
   int i = 0;
   while (n_in_heap[i] >= spair_heap_size[i])
     {
       i++;
       if (i >= NHEAP)
         {
           std::cerr << "too many spairs: aborting" << std::endl;
           std::cerr << "n_in_heap[" << i << "]=" << n_in_heap[i - 1]
                     << std::endl;
           abort();
         }
       heap[i] = merge(heap[i - 1], heap[i]);
       n_in_heap[i] += n_in_heap[i - 1];
       heap[i - 1] = NULL;
       n_in_heap[i - 1] = 0;
     }
   if (i > top_of_heap) top_of_heap = i;
   nelems++;
 }
References heap, merge(), n_in_heap, nelems, NHEAP, p, spair_heap_size, and top_of_heap.
Referenced by GBinhom_comp::add_gens(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), GB_comp::initialize(), and put_back().