Macaulay2 Engine: mpfr_reallocate_limbs
mpfr_reallocate_limbs()
void mpfr_reallocate_limbs (mpfr_ptr _z) inline
Definition at line 33 of file gmp-util.h.
 {
   __mpfr_struct tmp;
   tmp = *_z;
   int limb_size = (_z->_mpfr_prec - 1) / GMP_NUMB_BITS + 1;
   mp_limb_t *p = (mp_limb_t*) getmem_atomic(limb_size * sizeof(mp_limb_t));
   memcpy(p, _z->_mpfr_d, limb_size * sizeof(mp_limb_t));
   mpfr_clear(_z);
   _z->_mpfr_prec = tmp._mpfr_prec;
   _z->_mpfr_sign = tmp._mpfr_sign;
   _z->_mpfr_exp = tmp._mpfr_exp;
   _z->_mpfr_d = p;
 }
References getmem_atomic(), and p.
Referenced by moveTo_gmpCC(), moveTo_gmpRR(), moveTo_gmpRRi(), mpfi_reallocate_limbs(), and M2::ARingCCC::to_ring_elem().