Macaulay2 Engine: moveTo_gmpCC
moveTo_gmpCC()
gmp_CC moveTo_gmpCC (gmp_CCmutable _z) inline
Definition at line 79 of file gmp-util.h.
   {
     CCmutable_struct* a = (CCmutable_struct*) _z;
     mpfr_reallocate_limbs(a->re);
     mpfr_reallocate_limbs(a->im);
     return (gmp_CC) a;
   }
References CCmutable_struct::im, mpfr_reallocate_limbs(), and CCmutable_struct::re.
Referenced by M2::ARingCC::toBigComplex(), and M2::ARingCCC::toBigComplex().