Macaulay2 Engine: moveTo_gmpRR
moveTo_gmpRR()
mpfr_srcptr moveTo_gmpRR (mpfr_ptr _z) inline
Definition at line 66 of file gmp-util.h.
   {
     mpfr_reallocate_limbs(_z);
     return _z;
   }
References mpfr_reallocate_limbs().
Referenced by PathTracker::getSolutionLastT(), PathTracker::getSolutionRcond(), IM2_RingElement_to_BigReal(), MutableMat< Mat >::norm(), Matrix::norm(), rawRandomRR(), rawRingElementNorm(), and M2::ARingRRR::to_ring_elem().