Macaulay2 Engine: mpz_reallocate_limbs
mpz_reallocate_limbs()
void mpz_reallocate_limbs (mpz_ptr _z) inline
Multiprecision arithmetic allocation utility routines
Definition at line 14 of file gmp-util.h.
 {
   int _s = _z->_mp_size;
   int _as = (_s>0)?_s:-_s;
   mp_limb_t *_p = (mp_limb_t*) getmem_atomic(_as*sizeof(mp_limb_t));
   memcpy(_p,_z->_mp_d,_as*sizeof(mp_limb_t));
   mpz_clear(_z);
   _z->_mp_d = _p;
   _z->_mp_size = _s;
   _z->_mp_alloc = _as;
 }
References getmem_atomic().
Referenced by RingZZ::add(), RingZZ::copy(), RingZZ::divide(), M2::RingQQ::fraction(), RingZZ::from_int(), RingZZ::from_long(), RingZZ::gcd(), RingZZ::gcd_extended(), IM2_RingElement_to_Integer(), M2::RingQQ::lower_associate_divisor(), RingZZ::lower_associate_divisor(), M2::RingQQ::lower_content(), RingZZ::lower_content(), moveTo_gmpQQ(), RingZZ::mult(), RingZZ::negate(), RingZZ::power(), rawFourierMotzkin(), rawHilbertBasis(), rawRandomInteger(), rawWeightRange(), rawZZfactor(), RingZZ::remainderAndQuotient(), RingZZ::subtract(), to_gmp_ZZ(), M2::ARingQQFlint::to_ring_elem(), M2::ARingQQGMP::to_ring_elem(), M2::ARingZZ::to_ring_elem(), and M2::ARingZZGMP::to_ring_elem().