Macaulay2 Engine: DMatLUinPlace::computeLU
computeLU() [5/5]
void DMatLUinPlace< M2::ARingCC >::computeLU () inline private
Definition at line 339 of file dmat-lu-inplace.hpp.
 {
   if (mIsDone) return;
   int rows = static_cast<int>(mLU.numRows());
   int cols = static_cast<int>(mLU.numColumns());
   int info;
   int min = (rows <= cols) ? rows : cols;
   // printf("entering DMatLUtemplate::computeLUNaive for RR\n");
   int* perm = newarray_atomic(int, min);
   double* copyA = newarray_atomic(double, 2 * mLU.numRows() * mLU.numColumns());
   // place all elements of mLU, but in column major order.
   double* p = copyA;
   for (size_t c = 0; c < mLU.numColumns(); c++)
     {
       auto end = mLU.columnEnd(c);
       for (auto a = mLU.columnBegin(c); a != end; ++a)
         {
           *p++ = (*a).re;
           *p++ = (*a).im;
         }
     }
   zgetrf_(&rows, &cols, copyA, &rows, perm, &info);
   if (info < 0)
     {
       // First, clean up, then throw an exception
       throw exc::engine_error("argument passed to zgetrf had an illegal value");
       // return;
     }
   // Now copy back to row major order
   p = copyA;
   for (size_t c = 0; c < mLU.numColumns(); c++)
     {
       auto end = mLU.columnEnd(c);
       for (auto a = mLU.columnBegin(c); a != end; ++a)
         {
           (*a).re = *p++;
           (*a).im = *p++;
         }
     }
   // Now place the correct permutation into mPerm
   for (int i = 0; i < min; i++)
     {
       int thisloc = perm[i] - 1;
       if (i != thisloc)
         {
           mSign = not mSign;
           size_t tmp = mPerm[thisloc];
           mPerm[thisloc] = mPerm[i];
           mPerm[i] = tmp;
         }
     }
   LUUtil<RingType>::computePivotColumns(mLU, mPivotColumns);
   mIsDone = true;
   freemem(perm);
   freemem(copyA);
 }
References LUUtil< RT >::computePivotColumns(), end(), freemem(), mpfr::min(), newarray_atomic, p, and zgetrf_().