Macaulay2 Engine: DMatLUinPlace::findPivot
findPivot() [3/3]
size_t DMatLUinPlace< M2::ARingCCC >::findPivot (size_t row, size_t col) inline private
Definition at line 165 of file dmat-lu-inplace.hpp.
 {
   // Look at elements A[row,col], A[row+1,col], ..., A[nrows-1, col]
   // Return the index r s.y. abs(A[r,col]) is maximum over all of these
   const M2::ARingRRR& RR = ring().real_ring();
   M2::ARingRRR::Element largest(RR), abs(RR);
   size_t best_row_so_far = static_cast<size_t>(-1);
   RR.set_zero(largest);
   for (size_t i = row; i < mLU.numRows(); i++)
     {
       ring().abs(abs, mLU.entry(i, col));
       if (RR.compare_elems(abs, largest) > 0)
         {
           best_row_so_far = i;
           RR.set(largest, abs);
         }
     }
   return best_row_so_far;
 }
References abs, M2::ARingRRR::compare_elems(), M2::ARingRRR::set(), and M2::ARingRRR::set_zero().