Macaulay2 Engine: safe::add_to
add_to() [2/2]
static int32_t safe::add_to (int32_t & x, int32_t y, const char * msg) inline static
Definition at line 99 of file overflow.hpp.
 {
   int32_t z = (uint32_t)x + (uint32_t)y;
   if
     expect_false((int32_t)((uint32_t)x ^ (uint32_t)z) < 0 &&
                  (int32_t)((uint32_t)x ^ (uint32_t)y) >= 0) ov(msg);
   return x = z;
 }
References expect_false, ov(), and x.
Referenced by add_to(), res2_poly::ring_subtract_multiple_to(), res_poly::ring_subtract_multiple_to(), res2_poly::subtract_multiple_to(), and res_poly::subtract_multiple_to().