Macaulay2 Engine: safe::mult
mult() [2/2]
static int32_t safe::mult (int32_t x, int32_t y, const char * msg) inline static
Definition at line 205 of file overflow.hpp.
 {
   int64_t z = (int64_t)x * y;
   int32_t w = (int32_t)z;
   if
     expect_false(z != (int64_t)w) ov(msg);
   return w;
 }
References expect_false, ov(), and x.
Referenced by main(), monomialOrderEncodeFromActualExponents(), mult(), ExponentVector< E, OC >::multpower(), varpower::power(), ExponentVector< E, OC >::power(), and ExponentVector< E, OC >::weight().