Macaulay2 Engine: safe::ov
ov()
void safe::ov (const char * msg)
Definition at line 5 of file overflow.cpp.
 {
   const std::string s(msg);
   throw(exc::overflow_exception(s));
 }
Referenced by add(), add_to(), div(), div_by(), fits_15(), fits_31(), fits_7(), main(), minus(), mult(), mult_by(), pos_add(), pos_add_2(), pos_add_4(), sub(), sub_from(), and sub_pos().