Macaulay2 Engine: safe::sub_pos
sub_pos() [2/2]
static int32_t safe::sub_pos (int32_t x, int32_t y, const char * msg) inline static
Definition at line 141 of file overflow.hpp.
 {
   if (x <= y) return 0;
   int32_t z = (uint32_t)x - (uint32_t)y;
   if
     expect_false(z < 0) ov(msg);
   return z;
 }
References expect_false, ov(), and x.
Referenced by ExponentVector< E, OC >::quotient(), and sub_pos().