Macaulay2 Engine: safe::pos_add
pos_add() [2/2]
static int32_t safe::pos_add (int32_t x, int32_t y, const char * msg) inline static
Definition at line 166 of file overflow.hpp.
 {
   assert(!over_1(x) && !over_1(y));
   int32_t z = (uint32_t)x + (uint32_t)y;
   if
     expect_false(over_1(z)) ov(msg);
   return z;
 }
References expect_false, ov(), over_1(), and x.
Referenced by Monoid::mult(), and pos_add().