Macaulay2 Engine: safe::fits_15
fits_15() [2/2]
static int32_t safe::fits_15 (int32_t x, const char * msg) inline static
Definition at line 49 of file overflow.hpp.
 {
   if
     expect_false(((uint32_t)x & ~0x7fff) != 0) ov(msg);
   return x;
 }
References expect_false, ov(), and x.
Referenced by fits_15(), and MO_pack2().