Macaulay2 Engine: CoefficientRingZZp::modulus_add
modulus_add()
static int CoefficientRingZZp::modulus_add (int a, int b, int p) inline static private
Definition at line 23 of file coeffrings.hpp.
   {
     int t = a + b;
     return (t < p ? t : t - p);
   }
References p.
Referenced by add(), mult(), negate(), subtract(), and subtract_multiple().