Macaulay2 Engine: CoefficientRingZZp::is_zero
is_zero()
bool CoefficientRingZZp::is_zero (elem result) const inline
Definition at line 83 of file coeffrings.hpp.
 { return result == zero; }
References zero.
Referenced by Gausser::dense_row_next_nonzero(), Gausser::dense_row_to_sparse_row(), and GBRing::gbvector_add_to_zzp().