Macaulay2 Engine: constructWordTable
constructWordTable()
std::unique_ptr<WordTable> constructWordTable (const FreeAlgebra & A, const ConstPolyList & gb)
Definition at line 15 of file matrix-ncbasis.cpp.
 {
   std::unique_ptr<WordTable> W { new WordTable };
   // Build the word table for the reduction
   for (auto& f : gb)
     {
       auto i = f->cbegin();
       Word tmp;
       A.monoid().wordFromMonom(tmp,i.monom());
       W->insert(tmp);
     }
   return W;
 }
References gb(), FreeAlgebra::monoid(), and FreeMonoid::wordFromMonom().