Macaulay2 Engine: PolyRingQuotient::make_gb
make_gb()
GBComputation * PolyRingQuotient::make_gb (const ring_elem g) const protected
Definition at line 204 of file polyquotient.cpp.
 {
   MatrixConstructor mat(make_FreeModule(1), 1);
   mat.set_entry(0, 0, g);
   Matrix *mg = mat.to_matrix();  // {g}
   M2_arrayint weights = M2_makearrayint(n_vars());
   for (int i = 0; i < n_vars(); i++) weights->array[i] = 1;
   GBComputation *G = GBComputation::choose_gb(mg,
                                               false,  // collect syz
                                               -1,
                                               weights,
                                               false,
                                               -1,
                                               0,
                                               0
                                               /* , max_reduction_count */
                                               );
   G->set_stop_conditions(false,
                          nullptr,
                          -1,
                          -1,  // syzygy limit
                          -1,
                          -1,
                          -1,
                          false,
                          nullptr);
   G->start_computation();
   return G;
 }
References GBComputation::choose_gb(), G, M2_makearrayint(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by quotient(), remainder(), and remainderAndQuotient().