Macaulay2 Engine: PolyRingQuotient::divide
divide()
ring_elem PolyRingQuotient::divide (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 192 of file polyquotient.cpp.
 {
   ring_elem rem, d;
   rem = numerR_->remainderAndQuotient(f, g, d);
   if (is_zero(rem)) return d;  // This should be in normal form?
   return ann(f, g);
   //  ring_elem ginv = invert(g);
   //  ring_elem result = mult(f, ginv);
   //  normal_form(result);
   //  return result;
 }
References ann(), is_zero(), PolynomialRing::numerR_, mpfr::rem(), and PolyRing::remainderAndQuotient().