Macaulay2 Engine: PolyRingQuotient::text_out
text_out()
void PolyRingQuotient::text_out (buffer & o) const virtual
Implements PolynomialRing.
Definition at line 103 of file polyquotient.cpp.
 {
   o << "Quotient ring of ";
   numerR_->text_out(o);
   o << newline << "quotient elements" << newline;
   for (int i = 0; i < n_quotients(); i++)
     {
       o << "    ";
       elem_text_out(o, quotient_element(i));
       o << newline;
     }
 }
References elem_text_out(), PolynomialRing::n_quotients(), newline, PolynomialRing::numerR_, PolynomialRing::quotient_element(), and PolyRing::text_out().