Macaulay2 Engine: PolyRingQuotient::normal_form
normal_form()
void PolyRingQuotient::normal_form (ring_elem & f) const inline protected
Definition at line 28 of file polyquotient.hpp.
 { return qinfo_->normal_form(f); }
References QRingInfo::normal_form(), and PolynomialRing::qinfo_.
Referenced by add(), from_BigComplex(), from_BigReal(), from_complex_double(), from_double(), from_int(), from_long(), from_rational(), homogenize(), make_flat_term(), make_logical_term(), mult(), mult_by_term(), mult_coeff_to(), negate(), random(), subtract(), and var().