Macaulay2 Engine: PolyRingQuotient::invert
invert()
ring_elem PolyRingQuotient::invert (const ring_elem f) const virtual
Implements Ring.
Definition at line 161 of file polyquotient.cpp.
 {
   if (nvars_ == 1 && n_quotients() == 1 && K_->is_field() && ! K_->is_fraction_field())
     {
       ring_elem g = quotient_element(0);
       RingElement *f1 = RingElement::make_raw(getAmbientRing(), f);
       RingElement *g1 = RingElement::make_raw(getAmbientRing(), g);
       const RingElement *u1;
       const RingElement *v1;
       const RingElement *ret = rawExtendedGCDRingElement(f1, g1, &u1, &v1);
       if (ret == nullptr)
         {
           // one reason this might return nullptr is if the coefficient ring is not
           // ZZ/n, ZZ, or QQ
           // now what do we do?
           // we can't return nullptr
           INTERNAL_ERROR("ring element gcd computation failed");
         }
       if (!getAmbientRing()->is_unit(ret->get_value())) return from_long(0);
       return u1->get_value();
     }
   else if (M_->getNonTermOrderVariables()->len == 0)
     return ann(from_long(1), f);
   else
     {
       // An error message is generated higher up
       return from_long(0);
     }
 }
References ann(), from_long(), RingElement::get_value(), PolynomialRing::getAmbientRing(), Monoid::getNonTermOrderVariables(), INTERNAL_ERROR(), Ring::is_field(), Ring::is_fraction_field(), is_unit(), PolynomialRing::K_, PolynomialRing::M_, RingElement::make_raw(), PolynomialRing::n_quotients(), PolynomialRing::nvars_, PolynomialRing::quotient_element(), and rawExtendedGCDRingElement().
Referenced by is_unit().