Macaulay2 Engine: PolyRingQuotient::is_unit
is_unit()
bool PolyRingQuotient::is_unit (const ring_elem f) const virtual
Implements Ring.
Definition at line 116 of file polyquotient.cpp.
 {
   ring_elem b = invert(a);
   return !is_zero(b);
 }
References invert(), and is_zero().
Referenced by invert().