Macaulay2 Engine: PolyRingQuotient::remainderAndQuotient
remainderAndQuotient()
ring_elem PolyRingQuotient::remainderAndQuotient (const ring_elem f, const ring_elem g, ring_elem & quot) const virtual
Reimplemented from Ring.
Definition at line 289 of file polyquotient.cpp.
 {
   if (K_->get_precision() > 0)
     {
       ERROR(
           "polynomial division not yet implemented for RR or CC coefficients");
       quot = from_long(0);
       return from_long(0);
     }
   MatrixConstructor matf(make_FreeModule(1), 1);
   matf.set_entry(0, 0, f);
   Matrix *mf = matf.to_matrix();
   GBComputation *G = make_gb(g);
   const Matrix *mrem, *mquot;
   G->matrix_lift(mf, &mrem, &mquot);
   quot = mquot->elem(0, 0);
   ring_elem result = mrem->elem(0, 0);
   delete mrem;
   delete mquot;
   delete mf;
   delete G;
   return result;
 }
References Matrix::elem(), ERROR(), from_long(), Ring::get_precision(), PolynomialRing::K_, Ring::make_FreeModule(), make_gb(), GBComputation::matrix_lift(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().