Macaulay2 Engine: PolyRingQuotient::syzygy
syzygy()
void PolyRingQuotient::syzygy (const ring_elem a, const ring_elem b, ring_elem & x, ring_elem & y) const virtual
Implements Ring.
Definition at line 380 of file polyquotient.cpp.
 {
   MatrixConstructor mat(make_FreeModule(1), 2);
   mat.set_entry(0, 0, a);
   mat.set_entry(0, 1, b);
   Matrix *m = mat.to_matrix();  // {a,b}
   M2_arrayint weights = M2_makearrayint(n_vars());
   for (int i = 0; i < n_vars(); i++) weights->array[i] = 1;
   GBComputation *G = GBComputation::choose_gb(m,
                                               true,  // collect syz
                                               -1,    // keep all rows
                                               weights,
                                               false,
                                               -1,
                                               0,
                                               0
                                               /* , max_reduction_count */
                                               );
   G->set_stop_conditions(false,
                          nullptr,
                          -1,
                          1,  // syzygy limit
                          -1,
                          -1,
                          -1,
                          false,
                          nullptr);
   G->start_computation();
   const Matrix *s = G->get_syzygies();
   // Now extract the two pieces of info
   x = s->elem(0, 0);
   y = s->elem(1, 0);
   ring_elem c = preferred_associate(x);
   ring_elem x1 = mult(c, x);
   ring_elem y1 = mult(c, y);
   x = x1;
   y = y1;
 }
References GBComputation::choose_gb(), Matrix::elem(), M2_makearrayint(), Ring::make_FreeModule(), mult(), PolynomialRing::n_vars(), preferred_associate(), MatrixConstructor::set_entry(), Computation::set_stop_conditions(), Computation::start_computation(), MatrixConstructor::to_matrix(), and x.