Macaulay2 Engine: PolyRingQuotient::from_long
from_long()
virtual ring_elem PolyRingQuotient::from_long (long n) const inline virtual
Implements Ring.
Definition at line 47 of file polyquotient.hpp.
   {
     ring_elem result = numerR_->from_long(n);
     normal_form(result);
     return result;
   }
References PolyRing::from_long(), normal_form(), and PolynomialRing::numerR_.
Referenced by invert(), quotient(), remainder(), and remainderAndQuotient().