Macaulay2 Engine: PolyRingQuotient::ann
ann()
ring_elem PolyRingQuotient::ann (const ring_elem a, const ring_elem b) const protected
Definition at line 318 of file polyquotient.cpp.
 {
   MatrixConstructor mata(make_FreeModule(1), 1);
   mata.set_entry(0, 0, a);
   Matrix *ma = mata.to_matrix();  // {a}
   GBComputation *G = make_gb(b);
   const Matrix *mrem, *mquot;
   G->matrix_lift(ma, &mrem, &mquot);
   // if (M2_gbTrace >= 2)
   //   {
   //     emit("ann a=");
   //     dringelem(this, a);
   //     emit(" b=");
   //     dringelem(this, b);
   //     emit_line("----------");
   //     emit_line(" G->get_gb is ");
   //     dmatrix(G->get_gb());
   //     emit_line(" G ->get_change()");
   //     dmatrix(G->get_change());
   //     emit_line("----------");
   //     emit_line(" mrem is ");
   //     dmatrix(mrem);
   //     emit_line(" mquot is ");
   //     dmatrix(mquot);
   //     emit_line("---------------");
   //     emit_line("-- gb(b): -----");
   //     G->show();
   //     emit_line("---------------");
   //   }
   if (mquot->n_cols() == 0 || !mrem->is_zero())
     {
       // We have just determined that a/b does not exist.
       // So b is not a unit in this ring.
       set_non_unit(b);
       return from_long(0);
     }
   ring_elem answer = mquot->elem(0,0); // possibly off by a scalar?
   ring_elem a1 = mult (answer, b);
   if (not is_equal(a1, a))
     {
       // so answer * b == a1,
       // and a1 * c == a.  Check this?
       // so (answer * c) * b == a
       // emit("a1=");
       // dringelem(this, a1);
       // emit_line("");
       ring_elem c = divide(a, a1);
       if (not is_equal(mult(a1, c), a))
         {
           set_non_unit(b);
           return from_long(0);
         }
       answer = mult(c, answer);
     }
   return answer;
 }
References Matrix::elem(), RingMap::is_equal(), Matrix::is_zero(), GBComputation::matrix_lift(), MatrixOps::mult(), Matrix::n_cols(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by divide(), and invert().