Macaulay2 Engine: PolyRingQuotient::remainder
remainder()
ring_elem PolyRingQuotient::remainder (const ring_elem f, const ring_elem g) const virtual
Reimplemented from Ring.
Definition at line 240 of file polyquotient.cpp.
{
  if (K_->get_precision() > 0)
    {
      ERROR(
          "polynomial division not yet implemented for RR or CC coefficients");
      return from_long(0);
    }
  MatrixConstructor matf(make_FreeModule(1), 1);
  matf.set_entry(0, 0, f);
  const Matrix *mf = matf.to_matrix();
  GBComputation *G = make_gb(g);
  const Matrix *mrem = G->matrix_remainder(mf);
  ring_elem result = mrem->elem(0, 0);
  delete mrem;
  delete mf;
  delete G;
  return result;
}
References Matrix::elem(), ERROR(), from_long(), G, Ring::get_precision(), PolynomialRing::K_, Ring::make_FreeModule(), make_gb(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().