Macaulay2 Engine: end
end() [1/2]
TermIterator<Nterm> end (Nterm *)
Definition at line 5 of file ringelem.cpp.
 { return TermIterator<Nterm>{}; }
Referenced by SchreyerOrder::append(), check_poly(), MatElementaryOps< DMat< RT > >::column2by2(), MatElementaryOps< DMat< RT > >::column_op(), DMatLUinPlace< RT >::computeLU(), SchreyerFrame::computeNextLevel(), F4SPairSet::construct_pairs(), copyPolyVector(), F4Res::debugOutputColumns(), F4Res::debugOutputReducers(), display_poly(), MatElementaryOps< DMat< RT > >::divide_column(), MatElementaryOps< DMat< RT > >::divide_row(), MatElementaryOps< DMat< RT > >::dot_product(), Lapack::eigenvectors(), BIBasis::FastAllocator::ExpandMemory(), fill_from_lapack_array(), findDivisor(), MemoryBlock::freeTopArray(), FlintQQMat::from_fmpq_mat(), FlintZZMat::from_fmpz_mat(), FunctionPair::FunctionPair(), MatElementaryOps< DMat< RT > >::interchange_columns(), MatElementaryOps< DMat< RT > >::interchange_rows(), interreduction(), FreeAlgebra::is_homogeneous(), PolyRing::is_homogeneous(), PolyRing::is_unit(), isGoodPair(), LocalRing::lift_up(), F4Res::loadRow(), DetComputation::make_dynamic_cache(), make_lapack_array(), MonomialTable::make_minimal(), makeList(), makeNewPairs(), MonomialTable::minimalize(), gbA::minimalize_pairs_non_ZZ(), PolyRing::multi_degree(), MatElementaryOps< DMat< RT > >::op2by2(), BRP::operator*(), SuffixTree::operator[](), Pair::Pair(), DPoly::read_poly_0(), reduceLt(), reduceTail(), BRP::reduceTail(), BRP::remainder(), MatElementaryOps< DMat< RT > >::row2by2(), MatElementaryOps< DMat< RT > >::row_op(), MatElementaryOps< DMat< RT > >::scale_column(), MatElementaryOps< DMat< RT > >::scale_row(), ResMonoidSparse::showAlpha(), MemoryBlock::shrinkLastAllocate(), QuickSorter< Sorter >::sort2(), QuickSorter< Sorter >::sort2depth(), Table_toArray(), FlintQQMat::to_fmpq_mat(), FlintZZMat::to_fmpz_mat(), ResF4toM2Interface::to_M2_MutableMatrix(), toMatrix(), HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track(), and MatrixOps::transpose().