Macaulay2 Engine: begin
begin() [1/2]
TermIterator< Nterm > begin (Nterm * ptr)
Definition at line 4 of file ringelem.cpp.
{ return TermIterator<Nterm>(ptr); }
Referenced by SchreyerFrame::computeIdealQuotient(), SchreyerFrame::computeNextLevel(), F4SPairSet::construct_pairs(), NCF4::createOverlapLeadWord(), NCGroebner::createOverlapPoly(), BIBasis::FastAllocator::ExpandMemory(), MemoryBlock::freeTopArray(), PolyRing::is_homogeneous(), PolyRing::is_unit(), minimalize_res_varpower_monomials(), monomToModuleMonom(), PolyRing::multi_degree(), SuffixTree::operator[](), MemoryBlock::shrinkLastAllocate(), QuickSorter< Sorter >::sort2(), and QuickSorter< Sorter >::sort2depth().