Macaulay2 Engine: parseBasicPolyListFromString
parseBasicPolyListFromString() [1/2]
BasicPolyList parseBasicPolyListFromString (std::string contents, const IdentifierHash & idenMap)
Definition at line 209 of file BasicPolyListParser.cpp.
 {
   std::string_view fileView { contents };
   BasicPolyList Fs;
   while (fileView.size() > 0)
     {
       std::string_view thisline = next_line(fileView);
       if (thisline.size() == 0 or thisline[0] == '#')
         {
           continue;
         }
       BasicPoly F;
       parseBasicPoly(thisline, idenMap, F);
       Fs.push_back(F);
     }
   return Fs;
 }
References next_line(), and parseBasicPoly().
Referenced by parseBasicPolyListFromString(), and TEST().