Macaulay2 Engine: F4Computation::show
show()
void F4Computation::show () const override virtual
Reimplemented from Computation.
Definition at line 166 of file f4-computation.cpp.
 {
   buffer o;
   stash::stats(o);
   emit(o.str());
   mMemoryBlock->show();
   // f4->show();
 }
References emit(), mMemoryBlock, F4Mem::show(), stash::stats(), and buffer::str().