Macaulay2 Engine: F4Computation::get_gb
get_gb()
const Matrix * F4Computation::get_gb () override virtual
Implements GBComputation.
Definition at line 99 of file f4-computation.cpp.
 {
   const gb_array &gb = mF4GB->get_gb();
   MatrixConstructor result(mFreeModule, 0);
   for (int i = 0; i < gb.size(); i++)
     {
       vec v = F4toM2Interface::to_M2_vec(
           mVectorArithmetic, mMonoid, gb[i]->f, mFreeModule);
       result.append(v);
     }
   return result.to_matrix();
 }
References MatrixConstructor::append(), gb(), F4GB::get_gb(), mF4GB, mFreeModule, mMonoid, mVectorArithmetic, F4toM2Interface::to_M2_vec(), and MatrixConstructor::to_matrix().