Macaulay2 Engine: F4Computation::F4Computation
F4Computation()
F4Computation::F4Computation (const VectorArithmetic * VA, F4Mem * Mem, const Matrix * m, M2_bool collect_syz, int n_rows_to_keep, M2_arrayint gb_weights, int strategy, M2_bool use_max_degree, int max_degree)
Definition at line 52 of file f4-computation.cpp.
   : mFreeModule(m->rows()),
     mVectorArithmetic(VA),
     mMemoryBlock(Mem0)
 {
   // Note: the F4Mem which K0 uses should be mMemoryBlock. ??TODO: no longer valid, still containing useful info?
   mOriginalRing = m->get_ring()->cast_to_PolynomialRing();
   mMonoid = new MonomialInfo(mOriginalRing->n_vars(),
                         mOriginalRing->getMonoid()->getMonomialOrdering());
   mF4GB = new F4GB(mVectorArithmetic,
                    Mem0,
                    mMonoid,
                    m->rows(),
                    collect_syz,
                    n_rows_to_keep,
                    gb_weights,
                    strategy,
                    use_max_degree,
                    max_degree);
   F4toM2Interface::from_M2_matrix(mVectorArithmetic, mMonoid, m, gb_weights, mF4GB->get_generators());
   mF4GB->new_generators(0, m->n_cols() - 1);
 }
References Ring::cast_to_PolynomialRing(), F4toM2Interface::from_M2_matrix(), F4GB::get_generators(), Matrix::get_ring(), PolynomialRing::getMonoid(), Monoid::getMonomialOrdering(), mF4GB, mMonoid, mOriginalRing, mVectorArithmetic, Matrix::n_cols(), PolynomialRing::n_vars(), F4GB::new_generators(), and Matrix::rows().