Macaulay2 Engine: SchurRing::elem_text_out
elem_text_out()
void SchurRing::elem_text_out (buffer & o, const ring_elem f, bool p_one = true, bool p_plus = false, bool p_parens = false) const virtual
Reimplemented from PolyRing.
Definition at line 348 of file schur.cpp.
 {
   exponents_t EXP = ALLOCATE_EXPONENTS(sizeof(int) * (nvars_ + 1));
   int n = n_terms(f);
   bool needs_parens = p_parens && (n > 1);
   if (needs_parens)
     {
       if (p_plus) o << '+';
       o << '(';
       p_plus = false;
     }
   p_one = false;
   for (Nterm& t : f)
     {
       int isone = M_->is_one(t.monom);
       p_parens = !isone;
       K_->elem_text_out(o, t.coeff, p_one, p_plus, p_parens);
       to_partition(t.monom, EXP);
       o << "{" << EXP[1];
       for (int i = 2; i <= nvars_ && EXP[i] != 0; i++) o << "," << EXP[i];
       o << "}";
       p_plus = true;
     }
   if (needs_parens) o << ')';
 }
References ALLOCATE_EXPONENTS, Ring::elem_text_out(), Monoid::is_one(), PolynomialRing::K_, PolynomialRing::M_, PolynomialRing::n_terms(), PolynomialRing::nvars_, and to_partition().