Macaulay2 Engine: SchurRing::power
power() [1/2]
ring_elem SchurRing::power (const ring_elem f, int n) const virtual
Reimplemented from PolyRing.
Definition at line 295 of file schur.cpp.
{
  ring_elem result = from_long(1);
  if (n < 0)
    {
      throw exc::engine_error("element not invertible");
    }
  for (int i = 0; i < n; i++)
    {
      ring_elem g = mult(result, f);
      remove(result);
      result = g;
    }
  return result;
}
References PolyRing::from_long(), PolyRing::mult(), and PolyRing::remove().