Macaulay2 Engine: SchurRing::skew_schur
skew_schur()
Nterm * SchurRing::skew_schur (int * lambda, int * p) private
Definition at line 212 of file schur.cpp.
 {
   _SMcurrent = 0;
   _SMfinalwt = 0;
   for (int i = 1; p[i] != 0; i++) _SMfinalwt += (p[i] - lambda[i]);
   _SMtab.wt = _SMfinalwt;
   _SMtab.resize(_SMfinalwt);
   _SMfilled.resize(_SMfinalwt);
   _SMfilled.fill(lambda, p);
   _SMresult = NULL;
   SM();
   ring_elem result = _SMresult;
   _SMresult = NULL;
   return result;
 }
References _SMcurrent, _SMfilled, _SMfinalwt, _SMresult, _SMtab, tableau::fill(), p, tableau::resize(), SM(), and tableau::wt.
Referenced by mult_monomials().