Macaulay2 Engine: SchurRing::SM
SM()
void SchurRing::SM () private
Definition at line 173 of file schur.cpp.
 {
   int lo, hi;
   if (_SMcurrent == _SMfinalwt)
     {
       // partition is to be output
       Nterm *f = new_term();
       f->coeff = K_->from_long(1);
       //      fprintf(stderr, "partition: ");
       //      for (int i=1; i <= nvars_; i++)
       //        fprintf(stderr, " %d", _SMtab.p[i]);
       //      fprintf(stderr, "\n");
       from_partition(_SMtab.p, f->monom);
       f->next = _SMresult;
       _SMresult = f;
       return;
     }
   _SMcurrent++;
   bounds(lo, hi);
   int this_one = LARGE_NUMBER;  // larger than any entry of _SMtab
   int last_one;
   for (int i = lo; i <= hi; i++)
     {
       last_one = this_one;
       this_one = _SMtab.p[i];
       if (last_one > this_one)
         {
           _SMtab.p[i]++;
           _SMtab.xloc[_SMcurrent] = i;
           _SMtab.yloc[_SMcurrent] = _SMtab.p[i];
           SM();
           _SMtab.p[i]--;
         }
     }
   _SMcurrent--;
 }
References _SMcurrent, _SMfinalwt, _SMresult, _SMtab, bounds(), Nterm::coeff, Ring::from_long(), from_partition(), PolynomialRing::K_, LARGE_NUMBER, Nterm::monom, PolyRing::new_term(), Nterm::next, tableau::p, tableau::xloc, and tableau::yloc.
Referenced by skew_schur().