Macaulay2 Engine: SchurRing::mult_by_term
mult_by_term()
ring_elem SchurRing::mult_by_term (const ring_elem f, const ring_elem c, const int * m) const virtual
Reimplemented from PolyRing.
Definition at line 263 of file schur.cpp.
{
  // return c*m*f
  ring_elem result = ZERO_RINGELEM;
  for (Nterm& t : f)
    {
      ring_elem a = K_->mult(c, t.coeff);
      ring_elem g = const_cast<SchurRing *>(this)->mult_monomials(t.monom, m);
      for (Nterm& s : g)
        {
          ring_elem b = K_->mult(a, s.coeff);
          s.coeff = b;
        }
      Nterm *gt = g;
      sort(gt);
      g = gt;
      add_to(result, g);
    }
  return result;
}
References Ring::add_to(), PolynomialRing::K_, Ring::mult(), mult_monomials(), PolyRing::sort(), and ZERO_RINGELEM.