Macaulay2 Engine: SchurRing::initialize_schur
initialize_schur()
bool SchurRing::initialize_schur () protected
Definition at line 75 of file schur.cpp.
 {
   _SMtab.initialize(n_vars());
   _SMfilled.initialize(n_vars());
   _SMcurrent = 0;
   _SMfinalwt = 0;
   _SMresult = nullptr;
   _SMtab.p = newarray_atomic_clear(int, nvars_ + 1);
   return true;
 }
References _SMcurrent, _SMfilled, _SMfinalwt, _SMresult, _SMtab, tableau::initialize(), PolynomialRing::n_vars(), newarray_atomic_clear, PolynomialRing::nvars_, and tableau::p.
Referenced by create().