Macaulay2 Engine: SchurRing::from_partition
from_partition()
void SchurRing::from_partition (const int * exp, int * m) const private
Definition at line 126 of file schur.cpp.
 {
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);  // 0..nvars-1
   EXP1[nvars_ - 1] = exp[nvars_];
   for (int i = nvars_ - 1; i > 0; i--) EXP1[i - 1] = exp[i] - exp[i + 1];
   M_->from_expvector(EXP1, m);
 }
References ALLOCATE_EXPONENTS, mpfr::exp(), PolynomialRing::exp_size, Monoid::from_expvector(), PolynomialRing::M_, and PolynomialRing::nvars_.
Referenced by SM().