Macaulay2 Engine: SchurRing::dimension
dimension() [1/2]
void SchurRing::dimension (const int * exp, mpz_t result) const
Definition at line 311 of file schur.cpp.
 {
   int i, j;
   mpz_set_ui(result, 1);
   for (i = 1; i < nvars_; i++)
     for (j = i + 1; j <= nvars_; j++)
       if (exp[i] != exp[j]) mpz_mul_ui(result, result, exp[i] - exp[j] + j - i);
   for (i = 1; i < nvars_; i++)
     for (j = i + 1; j <= nvars_; j++)
       if (exp[i] != exp[j]) mpz_fdiv_q_ui(result, result, j - i);
 }
References mpfr::exp().
Referenced by dimension(), and rawSchurDimension().