Macaulay2 Engine: SchurRing::to_partition
to_partition()
void SchurRing::to_partition (const int * m, int * exp) const private
Definition at line 117 of file schur.cpp.
 {
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);  // 0..nvars-1
   // remark: exp_size is defined in an ancestor class of SchurRing
   M_->to_expvector(m, EXP1);
   exp[nvars_] = EXP1[nvars_ - 1];
   for (int i = nvars_ - 1; i >= 1; i--) exp[i] = exp[i + 1] + EXP1[i - 1];
 }
References ALLOCATE_EXPONENTS, and mpfr::exp().
Referenced by dimension(), elem_text_out(), and mult_monomials().