Macaulay2 Engine: SchurRing::create
create() [1/2]
SchurRing * SchurRing::create (const PolynomialRing * R) static
Definition at line 87 of file schur.cpp.
 {
   SchurRing *result = new SchurRing;
   result->initialize_poly_ring(R->getCoefficients(), R->getMonoid());
   if (!result->initialize_schur()) return nullptr;
   // No GBRing
   return result;
 }
References PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), PolyRing::initialize_poly_ring(), initialize_schur(), and SchurRing().
Referenced by IM2_Ring_schur().