Macaulay2 Engine: SchurRing::dimension
dimension() [2/2]
ring_elem SchurRing::dimension (const ring_elem f) const
Definition at line 329 of file schur.cpp.
 {
   exponents_t EXP = ALLOCATE_EXPONENTS(sizeof(int) * (nvars_ + 1));
   ring_elem result = K_->from_long(0);
   mpz_t dim;
   mpz_init(dim);
   for (Nterm& t : f)
     {
       to_partition(t.monom, EXP);
       dimension(EXP, dim);
       ring_elem h = K_->from_int(dim);
       ring_elem h2 = K_->mult(t.coeff, h);
       K_->add_to(result, h2);
       K_->remove(h);
     }
   mpz_clear(dim);
   return result;
 }
References Ring::add_to(), ALLOCATE_EXPONENTS, mpfr::dim(), dimension(), Ring::from_int(), Ring::from_long(), PolynomialRing::K_, Ring::mult(), PolynomialRing::nvars_, Ring::remove(), and to_partition().