Macaulay2 Engine: SchurRing::mult_monomials
mult_monomials()
ring_elem SchurRing::mult_monomials (const int * m, const int * n) private
Definition at line 230 of file schur.cpp.
 {
   int i;
   exponents_t a_part = ALLOCATE_EXPONENTS(sizeof(int) * (nvars_ + 1));
   exponents_t b_part = ALLOCATE_EXPONENTS(sizeof(int) * (nvars_ + 1));
   exponents_t lambda = ALLOCATE_EXPONENTS(2 * sizeof(int) * (nvars_ + 1));
   exponents_t p = ALLOCATE_EXPONENTS(2 * sizeof(int) * (nvars_ + 1));
   // First: obtain the partitions
   to_partition(m, a_part);
   to_partition(n, b_part);
   // Second: make the skew partition
   int a = b_part[1];
   for (i = 1; i <= nvars_ && a_part[i] != 0; i++)
     {
       p[i] = a + a_part[i];
       lambda[i] = a;
     }
   int top = i - 1;
   for (i = 1; i <= nvars_ && b_part[i] != 0; i++)
     {
       p[top + i] = b_part[i];
       lambda[top + i] = 0;
     }
   p[top + i] = 0;
   lambda[top + i] = 0;
   // Call the SM() algorithm
   return skew_schur(lambda, p);
 }
References ALLOCATE_EXPONENTS, PolynomialRing::nvars_, p, skew_schur(), and to_partition().
Referenced by mult_by_term().