Macaulay2 Engine: M2::ARingQQGMP::elem_text_out
elem_text_out()
void M2::ARingQQGMP::elem_text_out (buffer & o, const ElementType & a, bool p_one = true, bool p_plus = false, bool p_parens = false) const
Definition at line 31 of file aring-qq-gmp.cpp.
 {
   char s[1000];
   char* str;
   bool is_neg = (mpq_sgn(&a) == -1);
   bool one = is_pm_one(a);
   size_t size = mpz_sizeinbase(mpq_numref(&a), 10) +
                 mpz_sizeinbase(mpq_denref(&a), 10) + 3;
   char* allocstr = (size > 1000 ? newarray_atomic(char, size) : s);
   if (!is_neg && p_plus) o << '+';
   if (one)
     {
       if (is_neg) o << '-';
       if (p_one) o << '1';
     }
   else
     {
       str = mpq_get_str(allocstr, 10, &a);
       o << str;
     }
   if (size > 1000) freemem(allocstr);
 }
References freemem(), is_pm_one(), and newarray_atomic.
Referenced by TEST().