Macaulay2 Engine: Ring::negate_to
negate_to()
void Ring::negate_to (ring_elem & f) const
Definition at line 207 of file ring.cpp.
 { f = negate(f); }
References negate().
Referenced by DetComputation::bareiss_det(), PolyRing::diff_term(), FF_LUComputation::do_pivots(), GBRing::find_reduction_coeffs(), GBRing::find_reduction_coeffs_ZZ(), GBDeclared::GBDeclared(), GBRing::gbvector_cancel_lead_terms(), GBRing::gbvector_combine_lead_terms_ZZ(), GBRing::gbvector_negate_to(), PolyRing::imp_attempt_to_cancel_lead_term(), FractionField::internal_negate_to(), PolyRing::internal_negate_to(), Matrix::koszul(), DetComputation::make_dynamic_cache(), GB_comp::matrix_lift(), ReducedGB::matrix_lift(), GBRingSkew::mult_by_term1(), negate_vec_to(), gbres_comp::reduce(), HermiteComputation::reduce(), QRingInfo_field_basic::reduce_lead_term_basic_field(), FractionField::simplify(), and LocalRing::simplify().