Macaulay2 Engine: Ring::from_int
from_int()
virtual ring_elem Ring::from_int (mpz_srcptr n) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by convertToM2(), ChineseRemainder::CRA(), SchurRing::dimension(), M2::ARingZZ::eval(), M2::ARingZZGMP::eval(), RingZZ::eval(), FractionField::from_int(), PolyRing::from_int(), SchurRing2::from_int(), FractionField::from_rational(), IM2_RingElement_from_Integer(), PolyRing::power_direct(), and M2::ConcreteRing< RingType >::promote().