Macaulay2 Engine: Ring::divide_vec_to
divide_vec_to()
void Ring::divide_vec_to (vec & v, const ring_elem a) const
Definition at line 443 of file ring-vecs.cpp.
 {
   if (this->is_zero(a))
     {
       remove_vec(v);
       v = nullptr;
     }
   vecterm head;
   head.next = v;
   vec p = &head;
   while (p->next != nullptr)
     {
       // old version: this->mult_to(p->next->coeff, a);
       ring_elem c =
           this->divide(p->next->coeff, a);  // exact or quotient?? MES MES
       p->next->coeff = c;
       if (this->is_zero(p->next->coeff))
         {
           vec tmp = p->next;
           p->next = tmp->next;
           remove_vec_node(tmp);
         }
       else
         p = p->next;
     }
   v = head.next;
 }
References divide(), is_zero(), vec::next, p, remove_vec(), and remove_vec_node().