Macaulay2 Engine: Ring::promote
promote()
virtual bool Ring::promote (const Ring * R, const ring_elem f, ring_elem & result) const pure virtual
Implemented in M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, and FractionField.
Referenced by PolynomialRing::create_quotient(), IM2_Matrix_promote(), SchurRing2::promote(), RingElement::promote(), and SchurRing2::promote_coeffs().