Macaulay2 Engine: Ring::copy
copy()
virtual ring_elem Ring::copy (const ring_elem f) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by FractionField::add(), M2::ARingGFFlint::ARingGFFlint(), M2::ARingGFFlintBig::ARingGFFlintBig(), res2_poly::copy(), res_poly::copy(), FractionField::copy(), PolyRing::copy_term(), FractionField::denominator(), WeylAlgebra::diff_coefficients(), M2::findMinimalPolynomial(), FractionField::fraction(), M2::GaloisFieldTable::GaloisFieldTable(), get_non_unit(), GF::getMinimalPolynomial(), PolyRing::homogenize(), Matrix::identity(), GF::initialize_GF(), FractionField::invert(), PolyRing::lead_flat_coeff(), FractionField::lift(), M2FreeAlgebra::lift(), M2FreeAlgebraQuotient::lift(), M2FreeAlgebra::list_form(), SLP< Field >::make(), PolyRing::make_flat_term(), res2_poly::mult_by_monomial(), res_poly::mult_by_monomial(), FractionField::negate(), FractionField::numerator(), power(), FractionField::promote(), RingMap::RingMap(), res2_poly::strip(), res_poly::strip(), FractionField::subtract(), and hilb_comp::value().