Macaulay2 Engine: Ring::remove_vec
remove_vec()
void Ring::remove_vec (vec v) const
Definition at line 67 of file ring-vecs.cpp.
 {
   while (v != 0)
     {
       vec tmp = v;
       v = v->next;
       remove_vec_node(tmp);
     }
 }
References remove_vec_node().
Referenced by GaussElimComputation::contains(), HermiteComputation::contains(), divide_vec_to(), vecHeap::get_lead_term(), mult_vec_to(), GaussElimComputation::reduce(), HermiteComputation::reduce(), GaussElimComputation::remove_gm_elem(), HermiteComputation::remove_hm_elem(), HermiteComputation::start_computation(), and SymmMatrix::symm1().