Macaulay2 Engine: Ring::from_BigComplex
from_BigComplex()
bool Ring::from_BigComplex (gmp_CC z, ring_elem & result) const virtual
Reimplemented in PolyRingQuotient, PolyRing, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Definition at line 239 of file ring.cpp.
 {
   result = from_long(0);
   return false;
 }
References from_long().
Referenced by M2::ARingCCC::eval(), PolyRing::from_BigComplex(), and IM2_RingElement_from_BigComplex().