Macaulay2 Engine: Ring::minus_one
minus_one()
ring_elem Ring::minus_one () const inline
Definition at line 316 of file ring.hpp.
 { return minus_oneV; }
References minus_oneV.
Referenced by ReducedGB_ZZ::find_divisor(), Matrix::koszul(), Matrix::koszul_monomials(), gbA::remainder_ZZ(), PolyRing::syzygy(), gbA::tail_remainder_ZZ(), and TEST().