Macaulay2 Engine: Ring::mult_vec
mult_vec() [1/2]
vec Ring::mult_vec (const ring_elem f, const vec w) const
Definition at line 182 of file ring-vecs.cpp.
 {
   if (is_zero(f)) return NULL;
   vecterm head;
   vec result = &head;
   for (vec v = w; v != 0; v = v->next)
     {
       ring_elem a = mult(f, v->coeff);
       if (!is_zero(a))
         {
           vec t = make_vec(v->comp, a);
           result->next = t;
           result = t;
         }
     }
   result->next = NULL;
   return head.next;
 }
References is_zero(), make_vec(), mult(), and vec::next.