Macaulay2 Engine: Ring::get_precision
get_precision()
unsigned long Ring::get_precision () const virtual
Reimplemented in PolynomialRing, LocalRing, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Definition at line 394 of file ring.cpp.
 { return 0; }
Referenced by ResolutionComputation::choose_res(), get_norm_start(), PolynomialRing::get_precision(), IM2_Ring_frac(), ResGausserQQHybrid::isAllowedCoefficientRing(), Matrix::norm(), PolyRingQuotient::quotient(), rawMatrixClean(), rawMutableMatrixClean(), rawRingElementClean(), rawRoots(), PolyRingQuotient::remainder(), PolyRing::remainderAndQuotient(), PolyRingQuotient::remainderAndQuotient(), and test_over_RR_or_CC().