Macaulay2 Engine: Ring::coerceToLongInteger
coerceToLongInteger()
std::pair< bool, long > Ring::coerceToLongInteger (ring_elem a) const virtual
Reimplemented in Z_mod, RingZZ, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Definition at line 233 of file ring.cpp.
 {
   return std::pair<bool, long>(false,
                                0);  // the default is that it cannot be lifted.
 }
Referenced by hilb_comp::coeff_of(), convertToFactory(), GF::from_rational(), RingElement::getSmallIntegerCoefficients(), IM2_RingElement_to_Integer(), matrixToStream(), GF::promote(), M2::ARingGFGivaro::promote(), and Tower::translate().