Macaulay2 Engine: Ring::component_shift
component_shift()
vec Ring::component_shift (int n, vec v) const
Definition at line 248 of file ring-vecs.cpp.
 {
   vecterm head;
   vec result = &head;
   for (const vecterm *p = v; p != 0; p = p->next)
     {
       vec w = new_vec();
       result->next = w;
       result = w;
       w->comp = p->comp + n;
       w->coeff = p->coeff;  // copy is not done
     }
   result->next = 0;
   return head.next;
 }
References new_vec(), vec::next, and p.
Referenced by Matrix::module_tensor(), and tensor().