Macaulay2 Engine: Ring::vec_divide_by_expvector
vec_divide_by_expvector()
vec Ring::vec_divide_by_expvector (const_exponents exp, const vec v) const
Definition at line 739 of file ring-vecs.cpp.
 {
   vecterm head;
   vecterm *result = &head;
   for (vec w = v; w != 0; w = w->next)
     {
       ring_elem a = divide_by_expvector(exp, w->coeff);
       if (!is_zero(a))
         {
           vec t = make_vec(w->comp, a);
           result->next = t;
           result = t;
         }
     }
   result->next = 0;
   return head.next;
 }
References divide_by_expvector(), mpfr::exp(), is_zero(), make_vec(), and vec::next.
Referenced by vec_remove_monomial_factors().