Macaulay2 Engine: Ring::ringID
ringID()
virtual M2::RingID Ring::ringID () const inline virtual
Reimplemented in M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Definition at line 130 of file ring.hpp.
 { return M2::ring_old; }
References M2::ring_old.
Referenced by IM2_RingElement_to_BigReal(), IM2_RingElement_to_Interval(), ResGausserQQHybrid::isAllowedCoefficientRing(), ResGausserQQ::isAllowedCoefficientRing(), M2::ConcreteRing< RingType >::lift(), M2::ConcreteRing< RingType >::promote(), rawRoots(), ResGausserQQHybrid::to_ring_elem(), ResGausserQQ::to_ring_elem(), and VectorArithmetic::VectorArithmetic().