Macaulay2 Engine: Ring::is_unit
is_unit()
virtual bool Ring::is_unit (const ring_elem f) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by Matrix::dimension1(), LocalRing::eval(), FractionField::index_of_var(), RingElement::is_unit(), FreeAlgebra::is_unit(), PolyRing::is_unit(), SchurRing2::is_unit(), CoefficientRingR::is_unit(), and MutableComplex::next_unit().