Macaulay2 Engine: Ring::from_long
from_long()
virtual ring_elem Ring::from_long (long n) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by M2FreeAlgebraOrQuotient::appendFromModuleMonom(), MatrixStream::appendTermDone(), DetComputation::bareiss_det(), WeylAlgebra::binomial(), DetComputation::calc_det(), PfaffianComputation::calc_pfaff(), convertToM2(), convolve(), PolynomialRing::create_quotient(), WeylAlgebra::diff_coefficients(), PolyRing::diff_term(), SchurRing::dimension(), divide_by_var(), PolyRing::division_algorithm_with_laurent_variables(), hilb_comp::do_ideal(), dot_product(), e_sub_i(), M2::ARingZZp::eval(), M2::ARingGFFlintBig::eval(), M2::ARingRRi::eval(), M2::ARingZZpFFPACK::eval(), M2::ARingZZpFlint::eval(), FractionField::eval(), Z_mod::eval(), M2::ARingCC::eval(), M2::ARingCCC::eval(), M2::ARingRR::eval(), M2::ARingRRR::eval(), RingMap::eval_term(), FF_LUComputation::FF_LUComputation(), from_BigComplex(), from_BigReal(), from_complex_double(), from_double(), FractionField::from_int(), from_Interval(), FractionField::from_long(), PolyRing::from_long(), SchurRing2::from_long(), PolyRing::fromSmallIntegerCoefficients(), M2::GaloisFieldTable::GaloisFieldTable(), GBKernelComputation::geo_reduce(), get_entry(), FreeModule::get_induced_order(), hilb_comp::hilb_comp(), Matrix::identity(), MutableMatrix::identity(), PolyRing::index_of_var(), GF::initialize_GF(), PolyRing::lead_flat_coeff(), GF::lift(), Z_mod::lift(), M2::ARingGFGivaro::lift_to_original_ring(), M2::ARingGFM2::lift_to_original_ring(), M2::liftToInt(), Matrix::make(), matrixFromSparseMatrixGenerator(), Matrix::monomials(), mult_vec(), WeylAlgebra::multinomial(), res2_comp::new_base_res2_pair(), GBKernelComputation::new_pairs(), res2_comp::new_res2_pair(), RingElement::operator*(), power(), preferred_associate(), FractionField::promote(), FractionField::random(), hilb_comp::recurse(), GBKernelComputation::reduce(), hilb_comp::reset(), RingMap::RingMap(), CoefficientRingR::set_from_long(), SchurRing::SM(), hilb_comp::step(), TEST(), ResGausserQQHybrid::to_ring_elem(), ResGausserQQ::to_ring_elem(), ResGausserZZp::to_ring_elem(), Matrix::top_coefficients(), FractionField::var(), PolyRing::var(), TowerEvaluator::viewTerm(), and Matrix::wedge_product().