Macaulay2 Engine: Ring::compare_elems
compare_elems()
virtual int Ring::compare_elems (const ring_elem f, const ring_elem g) const pure virtual
Implemented in RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, and Z_mod.
Referenced by FreeAlgebra::compare_elems(), FractionField::compare_elems(), PolyRing::compare_elems(), compare_vecs(), and rawRingElementCompare().