Macaulay2 Engine: Ring::characteristic
characteristic()
long Ring::characteristic () const inline
Definition at line 122 of file ring.hpp.
{ return mCharacteristic; }
References mCharacteristic.
Referenced by M2::ARingGFFlint::ARingGFFlint(), M2::ARingGFFlintBig::ARingGFFlintBig(), checkGaloisFieldInput(), BIBasis::Launcher::CheckMatrix(), coeffMode(), M2::RingQQ::create(), M2FreeAlgebraQuotient::create(), M2FreeAlgebra::create(), Tower::create(), M2::ConcreteRing< RingType >::create(), PolynomialRing::create_quotient(), GF::from_int(), GF::from_long(), FractionField::initialize_frac(), GF::initialize_GF(), LocalRing::initialize_local(), PolyRing::initialize_poly_ring(), SchurRing2::initialize_SchurRing2(), newf4::GBF4Computation::initializeWithBasicPolyList(), newf4::GBF4Computation::initializeWithMatrix(), GF::internal_add(), isUnivariateOverPrimeField(), matrixToStream(), MatrixStream::modulus(), PolyRing::power(), SchreyerFrame::rankUsingDenseMatrix(), SchreyerFrame::rankUsingDenseMatrixFlint(), rawDisplayMatrixStream(), rawGbBoolean(), rawMGB(), rawRingCharacteristic(), rawTowerTranslatePoly(), and Tower::text_out().