Macaulay2 Engine: Ring::remainderAndQuotient
remainderAndQuotient()
ring_elem Ring::remainderAndQuotient (const ring_elem f, const ring_elem g, ring_elem & quot) const virtual
Reimplemented in RingZZ, PolyRingQuotient, and PolyRing.
Definition at line 220 of file ring.cpp.
 {
   if (is_zero(g))
     {
       quot = g;  // zero
       return f;
     }
   quot = divide(f, g);
   return zero();
 }
References divide(), is_zero(), and zero().
Referenced by IM2_RingElement_divmod().