Macaulay2 Engine: Ring::copy_vec
copy_vec()
vec Ring::copy_vec (const vecterm * v) const
Definition at line 51 of file ring-vecs.cpp.
 {
   vecterm head;
   vec result = &head;
   for (const vecterm *p = v; p != 0; p = p->next)
     {
       vec w = new_vec();
       result->next = w;
       result = w;
       w->comp = p->comp;
       w->coeff = p->coeff;  // copy is not done
     }
   result->next = 0;
   return head.next;
 }
References new_vec(), vec::next, and p.
Referenced by add_vec(), GaussElimComputation::contains(), HermiteComputation::contains(), vecHeap::current_value(), GaussElimComputation::get_change(), HermiteComputation::get_change(), GaussElimComputation::get_gb(), HermiteComputation::get_gb(), GaussElimComputation::get_syzygies(), HermiteComputation::get_syzygies(), IM2_Matrix_concat(), GaussElimComputation::matrix_lift(), HermiteComputation::matrix_lift(), GaussElimComputation::matrix_remainder(), HermiteComputation::matrix_remainder(), HermiteComputation::merge(), mult_vec_matrix(), GaussElimComputation::new_gen(), HermiteComputation::new_gen(), Matrix::operator+(), Matrix::remake(), Matrix::scalar_mult(), subtract_vec(), SymmMatrix::symm1(), and vec_remove_monomial_factors().