Macaulay2 Engine: Ring::zeroize_tiny
zeroize_tiny()
ring_elem Ring::zeroize_tiny (gmp_RR epsilon, const ring_elem f) const virtual
Reimplemented in PolyRing, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Definition at line 395 of file ring.cpp.
 {
   return f;
 }
Referenced by rawRingElementClean(), vec_zeroize_tiny(), and PolyRing::zeroize_tiny().