Macaulay2 Engine: Ring::make_vec
make_vec()
vec Ring::make_vec (int r, ring_elem a) const
Definition at line 20 of file ring-vecs.cpp.
 {
   if (is_zero(a)) return NULL;
   vec result = new_vec();
   result->next = 0;
   result->comp = r;
   result->coeff = a;
   return result;
 }
References is_zero(), and new_vec().
Referenced by HilbertController::addMonomial(), BRPStoMatrix(), coeffs_of_vec(), DetComputation::DetComputation(), e_sub_i(), GaussElimComputation::get_initial(), HermiteComputation::get_initial(), PolynomialRing::getPresentation(), KBasis::insert(), make_vec_from_array(), binomial_ring::monomial_to_vector(), Matrix::monomials(), mult_vec(), NCMonomialMatrix(), negate_vec(), GaussElimComputation::new_gen(), PfaffianComputation::PfaffianComputation(), rightmult_vec(), DetComputation::step(), PfaffianComputation::step(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), res2_poly::to_vector(), res_poly::to_vector(), Matrix::top_coefficients(), PolyRing::translate_gbvector_to_vec(), PolyRing::translate_gbvector_to_vec_QQ(), vec_divide_by_expvector(), vec_divide_by_var(), vec_eval(), PolyRing::vec_lead_term(), and vec_lead_term().