Macaulay2 Engine: Ring::negate_vec
negate_vec()
vec Ring::negate_vec (vec v) const
Definition at line 146 of file ring-vecs.cpp.
 {
   vecterm result;
   vecterm *b = &result;
   for (vecterm *a = v; a != NULL; a = a->next)
     {
       b->next = make_vec(a->comp, negate(a->coeff));
       b = b->next;
     }
   b->next = NULL;
   return result.next;
 }
References make_vec(), negate(), and vec::next.
Referenced by Matrix::operator-(), HermiteComputation::start_computation(), and subtract_vec().