Macaulay2 Engine: Ring::multi_degree
multi_degree()
bool Ring::multi_degree (const ring_elem f, monomial d) const virtual
Reimplemented in FractionField, LocalRing, M2FreeAlgebra, M2FreeAlgebraQuotient, PolyRing, PolyRingQuotient, and PolynomialRing.
Definition at line 379 of file ring.cpp.
{
  degree_monoid()->one(d);
  return true;
}
Referenced by degree(), degree_ring_elem(), RingElement::multi_degree(), and vec_is_homogeneous().