Macaulay2 Engine: Ring::coefficient_type
coefficient_type()
virtual CoefficientType Ring::coefficient_type () const inline virtual
Reimplemented in M2::RingQQ, FractionField, LocalRing, PolynomialRing, and RingZZ.
Definition at line 186 of file ring.hpp.
{ return COEFF_BASIC; }
References COEFF_BASIC.
Referenced by FractionField::coefficient_type(), LocalRing::coefficient_type(), TEST(), TEST(), and TEST().