Macaulay2 Engine: Ring::is_equal
is_equal() [1/2]
virtual bool Ring::is_equal (const ring_elem f, const ring_elem g) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by FractionField::add(), check_nterm_multiples(), FractionField::elem_text_out(), M2::GaloisFieldTable::GaloisFieldTable(), GBRing::gbvector_auto_reduce(), GBRing::gbvector_is_equal(), GBRing::gbvector_reduce_lead_term(), GBRing::gbvector_reduce_with_marked_lead_term(), GBKernelComputation::geo_reduce(), IM2_RingElement_is_equal(), M2FreeAlgebra::index_of_var(), PolyRing::index_of_var(), GF::initialize_GF(), FractionField::internal_add_to(), FractionField::internal_subtract_to(), FreeAlgebra::is_equal(), FractionField::is_equal(), PolyRing::is_equal(), SchurRing2::is_equal(), RingElement::is_equal(), RingMap::is_equal(), is_equal(), CoefficientRingR::is_equal(), FractionField::lift(), GBKernelComputation::reduce(), GBRing::reduce_marked_lead_term_heap(), RingMap::RingMap(), FractionField::simplify(), LocalRing::simplify(), FractionField::subtract(), and TEST().