Macaulay2 Engine: Ring::mult_vec_to
mult_vec_to()
void Ring::mult_vec_to (vec & v, const ring_elem r, bool opposite_mult) const
Definition at line 367 of file ring-vecs.cpp.
 {
   if (this->is_zero(r))
     {
       remove_vec(v);
       v = 0;
       return;
     }
   vecterm head;
   head.next = v;
   vec p = &head;
   while (p->next != 0)
     {
       // old version: this->mult_to(p->next->coeff, a);
       ring_elem c;
       if (opposite_mult)
         c = this->mult(p->next->coeff, r);
       else
         c = this->mult(r, p->next->coeff);
       p->next->coeff = c;
       if (this->is_zero(p->next->coeff))
         {
           vec tmp = p->next;
           p->next = tmp->next;
           remove_vec_node(tmp);
         }
       else
         p = p->next;
     }
   v = head.next;
 }
References is_zero(), mult(), vec::next, p, remove_vec(), and remove_vec_node().
Referenced by GaussElimComputation::insert(), mult_vec_matrix(), Matrix::scalar_mult(), SymmMatrix::symm1(), and tensor().