Macaulay2 Engine: Ring::from_rational
from_rational()
virtual bool Ring::from_rational (const mpq_srcptr q, ring_elem & result) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, GF, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, LocalRing, FractionField, M2FreeAlgebraQuotient, and M2FreeAlgebra.
Referenced by convertToM2(), M2::ARingQQFlint::eval(), M2::ARingQQGMP::eval(), M2FreeAlgebra::from_rational(), M2FreeAlgebraQuotient::from_rational(), GF::from_rational(), PolyRing::from_rational(), SchurRing2::from_rational(), FreeAlgebra::from_rational(), FreeAlgebraQuotient::from_rational(), IM2_RingElement_from_rational(), and ChineseRemainder::ratConversion().