Macaulay2 Engine: Ring::vec_divide_by_var
vec_divide_by_var()
vec Ring::vec_divide_by_var (int n, int d, const vec v) const
Definition at line 721 of file ring-vecs.cpp.
 {
   vecterm head;
   vecterm *result = &head;
   for (vec w = v; w != 0; w = w->next)
     {
       ring_elem a = divide_by_var(n, d, w->coeff);
       if (!is_zero(a))
         {
           vec t = make_vec(w->comp, a);
           result->next = t;
           result = t;
         }
     }
   result->next = 0;
   return head.next;
 }
References divide_by_var(), is_zero(), make_vec(), and vec::next.
Referenced by Matrix::divide_by_var().