Macaulay2 Engine: Ring::vec_multi_degree
vec_multi_degree()
bool Ring::vec_multi_degree (const FreeModule * F, const vec f, monomial degf) const
Definition at line 761 of file ring-vecs.cpp.
 {
   monomial degv;
   degree_monoid()->one(degf);
   if (f == NULL) return true;
   bool result = multi_degree(f->coeff, degf);
   degree_monoid()->mult(degf, F->degree(f->comp), degf);
   degv = degree_monoid()->make_one();
   for (vec v = f->next; v != 0; v = v->next)
     {
       bool ishom = multi_degree(v->coeff, degv);
       result = result && ishom;
       degree_monoid()->mult(degv, F->degree(v->comp), degv);
       if (0 != degree_monoid()->compare(degf, degv))
         {
           result = false;
           degree_monoid()->lcm(degf, degv, degf);
         }
     }
   degree_monoid()->remove(degv);
   return result;
 }
References compare().
Referenced by MatrixConstructor::append(), MatrixConstructor::compute_column_degree(), and Matrix::is_homogeneous().