Macaulay2 Engine: Ring::cast_to_SchurRing2
cast_to_SchurRing2() [2/2]
virtual const SchurRing2* Ring::cast_to_SchurRing2 () const inline virtual
Reimplemented in SchurRing2.
Definition at line 243 of file ring.hpp.
 { return 0; }
Referenced by IM2_RingElement_list_form(), SchurRing2::lift(), SchurRing2::promote(), and rawSchurFromPartition().