Macaulay2 Engine: Ring::vec_divide_by_given_content
vec_divide_by_given_content()
vec Ring::vec_divide_by_given_content (vec f, ring_elem c) const
Definition at line 967 of file ring-vecs.cpp.
 {
   if (f == 0) return 0;
   vecterm head;
   vec result = &head;
   for (const vecterm *p = f; p != 0; p = p->next)
     {
       vec w = new_vec();
       result->next = w;
       result = w;
       w->comp = p->comp;
       w->coeff = divide_by_given_content(p->coeff, c);
     }
   result->next = 0;
   return head.next;
 }
References divide_by_given_content(), new_vec(), vec::next, and p.
Referenced by vec_divide_by_content(), and vec_split_off_content().