Macaulay2 Engine: Ring::remove_vec_node
remove_vec_node()
void Ring::remove_vec_node (vec n) const protected
Definition at line 15 of file ring-vecs.cpp.
 {
   freemem(n);
 }
References freemem().
Referenced by add_vec_to(), divide_row(), divide_vec_to(), mult_row(), mult_vec_to(), remove_vec(), and set_entry().