Macaulay2 Engine: Ring::declare_field
declare_field()
bool Ring::declare_field ()
Definition at line 68 of file ring.cpp.
 {
   if (_isfield >= 0)
     {
       _isfield = 1;
       return true;
     }
   else
     {
       ERROR("attempting to declare a ring with known non-units to be a field");
       return false;
     }
 }
References _isfield, and ERROR().
Referenced by M2::RingQQ::create(), M2::ConcreteRing< RingType >::create(), Tower::initialize(), FractionField::initialize_frac(), GF::initialize_GF(), and Z_mod::initialize_Z_mod().