Macaulay2 Engine: Ring::vec_degree_weights
vec_degree_weights()
void Ring::vec_degree_weights (const FreeModule * F, const vec f, const std::vector< int > & wts, int & lo, int & hi) const
Definition at line 815 of file ring-vecs.cpp.
 {
   vecterm *t = f;
   if (t == nullptr)
     {
       lo = hi = 0;
       return;
     }
   degree_weights(t->coeff, wts, lo, hi);
   lo += F->primary_degree(t->comp);
   hi += F->primary_degree(t->comp);
   for (t = t->next; t != nullptr; t = t->next)
     {
       int lo1, hi1;
       degree_weights(t->coeff, wts, lo1, hi1);
       lo1 += F->primary_degree(t->comp);
       hi1 += F->primary_degree(t->comp);
       if (hi1 > hi) hi = hi1;
       if (lo1 < lo) lo = lo1;
     }
 }
References vec::coeff, vec::comp, degree_weights(), vec::next, and FreeModule::primary_degree().
Referenced by vec_homogenize().