Macaulay2 Engine: Ring::vec_is_homogeneous
vec_is_homogeneous()
bool Ring::vec_is_homogeneous (const FreeModule * F, const vec f) const
Definition at line 789 of file ring-vecs.cpp.
 {
   if (!this->is_graded()) return false;
   if (f == nullptr) return true;
   monomial d = degree_monoid()->make_one();
   monomial e = degree_monoid()->make_one();
   bool result = multi_degree(f->coeff, d);
   if (result)
     {
       degree_monoid()->mult(d, F->degree(f->comp), d);
       for (vecterm *t = f->next; (t != nullptr) && result; t = t->next)
         {
           bool ishom = multi_degree(t->coeff, e);
           result = result && ishom;
           if (result)
             {
               degree_monoid()->mult(e, F->degree(t->comp), e);
               if (0 != degree_monoid()->compare(d, e)) result = false;
             }
         }
     }
   degree_monoid()->remove(d);
   degree_monoid()->remove(e);
   return result;
 }
References compare(), FreeModule::degree(), degree_monoid(), is_graded(), Monoid::make_one(), Monoid::mult(), multi_degree(), vec::next, and Monoid::remove().