Macaulay2 Engine: Ring::negate
negate()
virtual ring_elem Ring::negate (const ring_elem f) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by SkewPolynomialRing::antipode(), res2_comp::do_auto_reductions(), PolyRing::imp_subtract_multiple_to(), FractionField::negate(), PolyRing::negate(), SchurRing2::negate(), CoefficientRingR::negate(), negate_to(), negate_vec(), RingElement::operator-(), MutableComplex::prune_unit(), GaussElimComputation::reduce(), res2_comp::reduce(), res_comp::reduce(), res2_comp::reduce2(), res2_comp::reduce3(), res2_comp::reduce4(), res2_comp::reduce_by_level(), res2_comp::reduce_heap_by_level(), QRingInfo_field_basic::reduce_lead_term_basic_field(), and res_comp::reduce_level_one().