Macaulay2 Engine: Ring::power
power() [1/2]
ring_elem Ring::power (const ring_elem f, int n) const virtual
Reimplemented in Z_mod, RingZZ, WeylAlgebra, SolvableAlgebra, SkewPolynomialRing, SchurRing, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Definition at line 163 of file ring.cpp.
 {
   // TODO: reorganize to match the above routine (but using an int).
   ring_elem ff = gg;
   if (n == 0) return one();
   if (n < 0)
     {
       n = -n;
       ff = invert(ff);
       if (is_zero(ff))
         {
           ERROR("negative power of noninvertible element requested");
           return ff;
         }
     }
   // The exponent 'n' should be > 0 here.
   ring_elem prod = from_long(1);
   ring_elem base = copy(ff);
   ring_elem tmp;
   for (;;)
     {
       if ((n % 2) != 0)
         {
           tmp = mult(prod, base);
           prod = tmp;
         }
       n >>= 1;
       if (n == 0) { return prod; }
       else
         {
           tmp = mult(base, base);
           base = tmp;
         }
     }
 }
References base, copy(), ERROR(), from_long(), invert(), is_zero(), mult(), and one().