Macaulay2 Engine: Ring::is_ZZ
is_ZZ()
virtual bool Ring::is_ZZ () const inline virtual
Reimplemented in RingZZ.
Definition at line 134 of file ring.hpp.
 { return false; }
Referenced by binomialGB_comp::add_generators(), GBinhom_comp::create(), Matrix::dimension1(), IM2_RingElement_to_Integer(), M2::ARingQQFlint::promote(), rawRingElementCRA(), rawRingElementRatConversion(), rawRoots(), and TEST().