Macaulay2 Engine: Ring::mult_row
mult_row()
void Ring::mult_row (vec & v, const ring_elem r, int i, bool opposite_mult) const
Definition at line 399 of file ring-vecs.cpp.
 {
   vecterm head;
   head.next = v;
   for (vec p = &head; p->next != 0; p = p->next)
     if (p->next->comp < i)
       break;
     else if (p->next->comp == i)
       {
         ring_elem c;
         if (opposite_mult)
           c = mult(p->next->coeff, r);
         else
           c = mult(r, p->next->coeff);
         p->next->coeff = c;
         if (this->is_zero(p->next->coeff))
           {
             vec tmp = p->next;
             p->next = tmp->next;
             remove_vec_node(tmp);
           }
         break;
       }
   v = head.next;
 }
References is_zero(), mult(), vec::next, p, and remove_vec_node().