Macaulay2 Engine: Ring::mult_vec
mult_vec() [2/2]
vec Ring::mult_vec (int n, vec v) const
Definition at line 175 of file ring-vecs.cpp.
{
  ring_elem f = from_long(n);
  vec result = mult_vec(f, v);
  return result;
}
References from_long(), and mult_vec().
Referenced by HermiteComputation::gb_reduce(), HermiteComputation::gb_reduce(), mult_vec(), GaussElimComputation::reduce(), HermiteComputation::reduce(), GaussElimComputation::reduce(), and GaussElimComputation::reduce().