Macaulay2 Engine: Ring::vec_eval
vec_eval()
vec Ring::vec_eval (const RingMap * map, const FreeModule * F, const vec v) const
Definition at line 314 of file ring-vecs.cpp.
 {
   const Ring *targetRing = map->get_ring();
   vecterm head;
   vec result = &head;
   for (vec t = v; t != nullptr; t = t->next)
     {
       ring_elem a = eval(map, t->coeff, 0);  // a is now in the target ring
       if (!targetRing->is_zero(a))
         {
           result->next = targetRing->make_vec(t->comp, a);
           result = result->next;
         }
     }
   result->next = nullptr;
   return head.next;
 }
References is_zero(), make_vec(), and vec::next.
Referenced by RingMap::eval().