Macaulay2 Engine: Ring::preferred_associate
preferred_associate()
ring_elem Ring::preferred_associate (ring_elem f) const virtual
Reimplemented in RingZZ, PolyRingQuotient, PolyRing, and M2::RingQQ.
Definition at line 274 of file ring.cpp.
 {
   // Here we assume that 'this' is a field:
   if (is_zero(f)) return from_long(1);
   return invert(f);
 }
References from_long(), invert(), and is_zero().
Referenced by PolyRing::preferred_associate().