Macaulay2 Engine: Ring::initialize_ring
initialize_ring()
void Ring::initialize_ring (long charac, const PolynomialRing * DR = nullptr, const std::vector< int > & heft_vec = {}) protected
Definition at line 29 of file ring.cpp.
{
  // Remember: if this is a poly ring, the ring is K[M].
  // If this is a basic routine, K = this, M = trivial monoid.
  // If this is a frac field, K = R, M = trivial monoid.
  mCharacteristic = P0;
  if (DR == nullptr)
    degree_ring = PolyRing::get_trivial_poly_ring();
  else
    degree_ring = DR;
  mHeftVector = heft_vector;
  _non_unit = ZERO_RINGELEM;
  _isfield = 0;
  zeroV = ZERO_RINGELEM;
  oneV = ZERO_RINGELEM;
  minus_oneV = ZERO_RINGELEM;
}
References _isfield, _non_unit, degree_ring, PolyRing::get_trivial_poly_ring(), mCharacteristic, mHeftVector, minus_oneV, oneV, ZERO_RINGELEM, and zeroV.
Referenced by M2::RingQQ::create(), M2FreeAlgebraQuotient::create(), M2FreeAlgebra::create(), M2::ConcreteRing< RingType >::create(), PolynomialRing::create_quotient(), Tower::initialize(), FractionField::initialize_frac(), GF::initialize_GF(), LocalRing::initialize_local(), PolyRing::initialize_poly_ring(), SchurRing2::initialize_SchurRing2(), Z_mod::initialize_Z_mod(), and RingZZ::initialize_ZZ().