Macaulay2 Engine: Ring::eval
eval()
virtual ring_elem Ring::eval (const RingMap * map, const ring_elem f, int first_var) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by RingMap::eval(), FractionField::eval(), and RingMap::eval_term().