Macaulay2 Engine: Ring::from_BigReal
from_BigReal()
bool Ring::from_BigReal (gmp_RR a, ring_elem & result) const virtual
Reimplemented in PolyRing, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, and PolyRingQuotient.
Definition at line 245 of file ring.cpp.
 {
   result = from_long(0);
   return false;
 }
References from_long().
Referenced by M2::ARingRRR::eval(), PolyRing::from_BigReal(), IM2_RingElement_from_BigReal(), and ResGausserQQHybrid::to_ring_elem().