Macaulay2 Engine: Ring::cast_to_M2FreeAlgebra
cast_to_M2FreeAlgebra() [2/2]
virtual const M2FreeAlgebra* Ring::cast_to_M2FreeAlgebra () const inline virtual
Reimplemented in M2FreeAlgebra.
Definition at line 222 of file ring.hpp.
 { return nullptr; }
Referenced by IM2_Ring_quotient(), rawNCBasis(), rawNCGroebnerBasisTwoSided(), rawNCReductionTwoSided(), and rawRingM2FreeAlgebraQuotient().