Macaulay2 Engine: Ring::cast_to_PolyRing
cast_to_PolyRing() [2/2]
virtual const PolyRing* Ring::cast_to_PolyRing () const inline virtual
Reimplemented in PolyRing.
Definition at line 208 of file ring.hpp.
 { return nullptr; }
Referenced by IM2_Ring_localization(), isUnivariateOverPrimeField(), PathTracker::make(), MatrixStream::MatrixStream(), matrixToStream(), rawAssociateDivisor(), rawConvolve(), rawDisplayMatrixStream(), rawMatrixRatConversion(), rawMGB(), rawRingElementCRA(), rawRingElementRatConversion(), sagbi::subduct(), and sagbi::subduct1().