Macaulay2 Engine: Ring::divide
divide()
virtual ring_elem Ring::divide (const ring_elem f, const ring_elem g) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by WeylAlgebra::binomial(), DetComputation::detmult(), CoefficientRingR::divide(), PolyRing::divide_by_given_content(), divide_row(), divide_vec_to(), FractionField::eval(), LocalRing::eval(), PolyRing::imp_attempt_to_cancel_lead_term(), FreeAlgebra::makeMonic(), FreeAlgebra::makeMonicInPlace(), WeylAlgebra::multinomial(), RingElement::operator/(), quotient(), res2_comp::reduce_minimal(), res_comp::reduce_minimal(), remainderAndQuotient(), and FractionField::simplify().