Macaulay2 Engine: Ring::invert
invert()
virtual ring_elem Ring::invert (const ring_elem f) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by convolve(), RingMap::eval_term(), GBRing::gbvector_remove_content(), GaussElimComputation::insert(), RingElement::invert(), M2FreeAlgebra::invert(), PolyRing::invert(), CoefficientRingR::invert(), FractionField::lift(), res2_poly::make_monic(), res_poly::make_monic(), power(), preferred_associate(), MutableComplex::prune_unit(), rawGCDRingElement(), and PolyRing::translate_gbvector_to_vec_denom().