Macaulay2 Engine: Ring::zero
zero()
ring_elem Ring::zero () const inline
Definition at line 317 of file ring.hpp.
 { return zeroV; }
References zeroV.
Referenced by schur_poly_heap::add_to(), PolyRing::content(), SchurRing2::divide(), M2::ARingGFFlint::eval(), SchurRing2::eval(), MutableMat< Mat >::get_entry(), get_non_unit(), NCGroebner::getCoeffOfMonom(), NCF4::getCoeffOfMonom(), SumCollectorDefault::getValue(), PolyRing::imp_attempt_to_cancel_lead_term(), CoefficientRingR::init(), SchurRing2::invert(), RingElement::lead_coeff(), M2FreeAlgebra::lead_coefficient(), PolyRing::lift(), rawExtendedGCDRingElement(), remainder(), remainderAndQuotient(), schur_poly_heap::schur_poly_heap(), FractionField::set_non_unit_frac(), LocalRing::set_non_unit_frac(), CoefficientRingR::set_zero(), FractionField::simplify(), LocalRing::simplify(), SchurRing2::syzygy(), TEST(), schur_poly_heap::value(), and vec_content().