Macaulay2 Engine: Ring::syzygy
syzygy()
virtual void Ring::syzygy (const ring_elem a, const ring_elem b, ring_elem & x, ring_elem & y) const pure virtual
Implemented in M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, and FractionField.
Referenced by GBRing::find_reduction_coeffs(), GBDeclared::GBDeclared(), GBRing::gbvector_auto_reduce(), GBRing::gbvector_cancel_lead_terms(), GBKernelComputation::geo_reduce(), GBKernelComputation::reduce(), and FractionField::simplify().