Macaulay2 Engine: Ring::elem_text_out
elem_text_out()
virtual void Ring::elem_text_out (buffer & o, const ring_elem f, bool p_one = true, bool p_plus = false, bool p_parens = false) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, SchurRing, PolyRingQuotient, PolyRing, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, M2FreeAlgebraQuotient, and M2FreeAlgebra.
Referenced by M2FreeAlgebra::debug_display(), M2FreeAlgebraQuotient::debug_display(), NCF4::displayF4Matrix(), NCF4::displayFullF4Matrix(), dNterm(), res2_comp::do_auto_reductions(), dringelem(), M2::ARingGFFlintBig::elem_text_out(), M2::ARingGFFlint::elem_text_out(), FreeAlgebra::elem_text_out(), res2_poly::elem_text_out(), res_poly::elem_text_out(), FractionField::elem_text_out(), GF::elem_text_out(), PolyRing::elem_text_out(), SchurRing::elem_text_out(), SchurRing2::elem_text_out(), M2::ARingGFM2::elem_text_out(), CoefficientRingR::elem_text_out(), GBRing::gbvector_text_out(), FractionField::simplify(), LocalRing::simplify(), hilb_comp::stats(), MutableMatrix::text_out(), Matrix::text_out(), RingElement::text_out(), RingMap::text_out(), and vec_text_out().