Macaulay2 Engine: Ring::random
random()
ring_elem Ring::random () const virtual
Reimplemented in Z_mod, RingZZ, Tower, PolyRingQuotient, PolyRing, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Definition at line 268 of file ring.cpp.
 {
   ERROR("random scalar elements for this ring are not implemented");
   return 0;
 }
References ERROR().
Referenced by FractionField::random(), PolyRing::random(), RingElement::random(), Matrix::random(), rawMutableMatrixFillRandom(), and rawMutableMatrixFillRandomDensity().