Macaulay2 Engine: Ring::get_heft_vector
get_heft_vector()
const std::vector<int>& Ring::get_heft_vector () const inline
Definition at line 125 of file ring.hpp.
 { return mHeftVector; }
References mHeftVector.
Referenced by PolynomialRing::create_quotient(), FractionField::initialize_frac(), LocalRing::initialize_local(), and FreeModule::primary_degree().