Macaulay2 Engine: Ring::e_sub_i
e_sub_i()
vec Ring::e_sub_i (int r) const
Definition at line 45 of file ring-vecs.cpp.
 {
   ring_elem a = from_long(1);
   return make_vec(i, a);
 }
References from_long(), and make_vec().
Referenced by Matrix::flip(), HermiteComputation::new_gen(), and SymmMatrix::SymmMatrix().