Macaulay2 Engine: Ring::add
add()
virtual ring_elem Ring::add (const ring_elem f, const ring_elem g) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by FractionField::add(), SchurRing2::add(), CoefficientRingR::add(), add_to(), add_vec_to(), FreeAlgebra::addScalarMultipleOf(), MapPolynomialHeap::addTerm(), NaiveDedupQueueConfiguration::deduplicate(), dot_product(), M2::ARingGFFlintBig::eval(), M2::GaloisFieldTable::GaloisFieldTable(), GF::initialize_GF(), NaivePolynomialHeap< Queue >::isZero(), PriorityQueuePolynomialHeap::isZero(), and RingElement::operator+().