Macaulay2 Engine: Ring::get_heft_vector
get_heft_vector()
M2_arrayint Ring::get_heft_vector () const inline
Definition at line 125 of file ring.hpp.
   {
     return heft_vector;
   }  // This CAN BE NULL
References heft_vector.
Referenced by PolynomialRing::create_quotient(), FractionField::initialize_frac(), and LocalRing::initialize_local().