Macaulay2 Engine: Ring::subtract
subtract()
virtual ring_elem Ring::subtract (const ring_elem f, const ring_elem g) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by RingElement::operator-(), FractionField::subtract(), CoefficientRingR::subtract(), CoefficientRingR::subtract_multiple(), and subtract_to().