Macaulay2 Engine: Ring::remove
remove()
virtual void Ring::remove (ring_elem & f) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by DetComputation::bareiss_det(), WeylAlgebra::binomial(), DetComputation::calc_det(), PfaffianComputation::calc_pfaff(), GB_comp::contains(), DetComputation::detmult(), WeylAlgebra::diff_coefficients(), SchurRing::dimension(), res2_comp::do_auto_reductions(), hilb_comp::do_ideal(), FF_LUComputation::do_pivots(), GF::elem_text_out(), M2::ARingGFM2::elem_text_out(), FractionField::eval(), LocalRing::eval(), RingMap::eval_term(), DetComputation::gauss(), GBKernelComputation::geo_reduce(), res2_poly::make_monic(), res_poly::make_monic(), WeylAlgebra::multinomial(), FractionField::random(), GBKernelComputation::reduce(), GaussElimComputation::reduce(), res2_comp::reduce3(), res2_comp::reduce4(), res2_comp::reduce_heap_by_level(), res2_poly::remove(), res_poly::remove(), polyheap::remove_lead_term(), hilb_comp::reset(), RingMap::RingMap(), FreeAlgebra::setZero(), FractionField::simplify(), DetComputation::step(), hilb_comp::step(), PfaffianComputation::step(), FF_LUComputation::~FF_LUComputation(), hilb_comp::~hilb_comp(), and RingMap::~RingMap().