Macaulay2 Engine: Ring::mult_to
mult_to()
void Ring::mult_to (ring_elem & f, const ring_elem g) const
Definition at line 201 of file ring.cpp.
 { f = mult(f, g); }
References mult().
Referenced by PolyRing::diff(), PolyRing::diff_term(), hilb_comp::do_ideal(), LLLoperations::doLLL(), RingMap::eval_term(), GBRing::gbvector_mult_by_coeff(), GBRing::gbvector_mult_by_coeff_to(), GBRing::gbvector_reduce_lead_term(), GBRing::gbvector_reduce_with_marked_lead_term(), GBRing::gbvector_remove_content(), FractionField::internal_add_to(), FractionField::internal_subtract_to(), res2_poly::make_monic(), res_poly::make_monic(), WeylAlgebra::multinomial(), and hilb_comp::step().