Macaulay2 Engine: Ring::subtract_vec
subtract_vec()
vec Ring::subtract_vec (vec v, vec w) const
Definition at line 167 of file ring-vecs.cpp.
 {
   vec f = copy_vec(v);
   vec g = negate_vec(w);
   add_vec_to(f, g);
   return f;
 }
References add_vec_to(), copy_vec(), and negate_vec().
Referenced by Matrix::operator-().