Macaulay2 Engine: Ring::degree
degree()
void Ring::degree (const ring_elem f, monomial d) const virtual
Reimplemented in PolynomialRing, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, and FractionField.
Definition at line 373 of file ring.cpp.
 { degree_monoid()->one(d); }
References degree_monoid(), and Monoid::one().
Referenced by RingElement::multi_degree(), and Matrix::scalar_mult().