Macaulay2 Engine: Ring::vec_text_out
vec_text_out()
void Ring::vec_text_out (buffer & o, const vecterm * v, bool p_one = true, bool p_plus = false, bool p_parens = false) const
Definition at line 293 of file ring-vecs.cpp.
 {
   if (v == nullptr)
     {
       o << "0";
       return;
     }
   p_one = false;
   for (const vecterm *t = v; t != nullptr; t = t->next)
     {
       this->elem_text_out(o, t->coeff, p_one, p_plus, p_parens);
       o << "<" << t->comp << ">";
       p_plus = true;
     }
 }
References elem_text_out(), and vec::next.
Referenced by dvec(), F4GB::show_gb_array(), GaussElimComputation::text_out(), and HermiteComputation::text_out().