Macaulay2 Engine: Ring::from_complex_double
from_complex_double()
bool Ring::from_complex_double (double re, double im, ring_elem & result) const virtual
Reimplemented in PolyRingQuotient, PolyRing, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Definition at line 262 of file ring.cpp.
 {
   result = from_long(0);
   return false;
 }
References from_long().
Referenced by M2::ARingCC::eval(), PolyRing::from_complex_double(), and rawRoots().