Macaulay2 Engine: Ring::cast_to_FractionField
cast_to_FractionField() [2/2]
virtual const FractionField* Ring::cast_to_FractionField () const inline virtual
Reimplemented in FractionField.
Definition at line 214 of file ring.hpp.
 { return nullptr; }
Referenced by RingElement::denominator(), RingElement::fraction(), IM2_Ring_frac(), FractionField::initialize_frac(), and RingElement::numerator().