Macaulay2 Engine: Ring::vec_divide_by_content
vec_divide_by_content()
vec Ring::vec_divide_by_content (vec f) const
Definition at line 984 of file ring-vecs.cpp.
{
  if (f == nullptr) return nullptr;
  ring_elem c = vec_content(f);
  return vec_divide_by_given_content(f, c);
}
References vec_content(), and vec_divide_by_given_content().
Referenced by Matrix::remove_content().