Macaulay2 Engine: Ring::vec_remove_monomial_factors
vec_remove_monomial_factors()
vec Ring::vec_remove_monomial_factors (vec f, bool make_squarefree_only) const
Definition at line 935 of file ring-vecs.cpp.
 {
   const PolynomialRing *PR = cast_to_PolynomialRing();
   if (PR == 0) return copy_vec(f);
   if (f == 0) return 0;
   exponents_t exp = newarray_atomic(int, PR->n_vars());
   Nterm *t = f->coeff;
   PR->getMonoid()->to_expvector(t->monom, exp);  // Get the process started
   for (vec a = f; a != NULL; a = a->next) monomial_divisor(a->coeff, exp);
   if (make_squarefree_only)
     // Now divide each term by exp[i]-1, if exp[i] >= 2
     for (int i = 0; i < PR->n_vars(); i++)
       if (exp[i] >= 1) exp[i]--;
   vec result = vec_divide_by_expvector(exp, f);
   freemem(exp);
   return result;
 }
References cast_to_PolynomialRing(), Nterm::coeff, copy_vec(), mpfr::exp(), freemem(), PolynomialRing::getMonoid(), Nterm::monom, monomial_divisor(), PolynomialRing::n_vars(), newarray_atomic, Monoid::to_expvector(), and vec_divide_by_expvector().