Macaulay2 Engine: Ring::rightmult_vec
rightmult_vec()
vec Ring::rightmult_vec (const vec w, const ring_elem f) const
Definition at line 201 of file ring-vecs.cpp.
 {
   if (is_zero(f)) return NULL;
   vecterm head;
   vec result = &head;
   for (vec v = w; v != 0; v = v->next)
     {
       ring_elem a = mult(v->coeff, f);
       if (!is_zero(a))
         {
           vec t = make_vec(v->comp, a);
           result->next = t;
           result = t;
         }
     }
   result->next = NULL;
   return head.next;
 }
References is_zero(), make_vec(), mult(), and vec::next.