Macaulay2 Engine: Ring::computeHashValue
computeHashValue()
virtual unsigned int Ring::computeHashValue (const ring_elem a) const pure virtual
Implemented in M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, Z_mod, RingZZ, Tower, SchurRing2, PolynomialRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, and FractionField.
Referenced by Matrix::computeHashValue(), RingElement::computeHashValue(), RingMap::computeHashValue(), PolynomialRing::computeHashValue(), and SchurRing2::computeHashValue().