Macaulay2 Engine: Ring::divide_row
divide_row()
void Ring::divide_row (vec & v, int r, const ring_elem a) const
Definition at line 471 of file ring-vecs.cpp.
 {
   vecterm head;
   head.next = v;
   for (vec p = &head; p->next != nullptr; p = p->next)
     if (p->next->comp < r)
       break;
     else if (p->next->comp == r)
       {
         ring_elem c =
             this->divide(p->next->coeff, a);  // exact or quotient?? MES MES
         p->next->coeff = c;
         if (this->is_zero(p->next->coeff))
           {
             vec tmp = p->next;
             p->next = tmp->next;
             remove_vec_node(tmp);
           }
         break;
       }
 }
References divide(), is_zero(), vec::next, p, and remove_vec_node().