Macaulay2 Engine: Ring::cast_to_Tower
cast_to_Tower() [2/2]
virtual const Tower* Ring::cast_to_Tower () const inline virtual
Reimplemented in Tower.
Definition at line 204 of file ring.hpp.
 { return nullptr; }
Referenced by rawDegree(), rawDiff(), rawExtendedGCDRingElement(), rawExtensionDegree(), rawGCDRingElement(), rawLowerP(), rawPowerMod(), rawTowerRing2(), rawTowerRing3(), rawTowerTranslatePoly(), towerExtendedGCD(), and towerGCD().