Macaulay2 Engine: Ring::sub_vector
sub_vector()
vec Ring::sub_vector (const vecterm * v, M2_arrayint r) const
Definition at line 220 of file ring-vecs.cpp.
 {
   if (v == 0) return 0;
   // Largest component which occurs in v occurs first.
   VECTOR(int) trans(v->comp + 1);
   for (int i = 0; i < v->comp; i++) trans.push_back(-1);
   for (unsigned j = 0; j < r->len; j++)
     if (r->array[j] >= 0 && r->array[j] <= v->comp) trans[r->array[j]] = j;
   vecterm head;
   vecterm *result = &head;
   for (; v != NULL; v = v->next)
     if (trans[v->comp] != -1)
       {
         result->next = new_vec();
         result = result->next;
         result->next = 0;
         result->coeff = v->coeff;
         result->comp = trans[v->comp];
       }
   result->next = NULL;
   result = head.next;
   vec_sort(result);
   return result;
 }
References vec::coeff, vec::comp, new_vec(), vec::next, vec_sort(), and VECTOR().