Macaulay2 Engine: Ring::vec_zeroize_tiny
vec_zeroize_tiny()
vec Ring::vec_zeroize_tiny (gmp_RR epsilon, const vec f) const
Definition at line 335 of file ring-vecs.cpp.
 {
   vecterm head;
   vec result = &head;
   for (const vecterm *p = v; p != nullptr; p = p->next)
     {
       ring_elem a = zeroize_tiny(epsilon, p->coeff);
       if (!is_zero(a))
         {
           vec w = new_vec();
           result->next = w;
           result = w;
           w->comp = p->comp;
           w->coeff = a;
         }
     }
   result->next = nullptr;
   return head.next;
 }
References is_zero(), new_vec(), vec::next, p, and zeroize_tiny().
Referenced by Matrix::clean().