Macaulay2 Engine: Ring::degree_monoid
degree_monoid()
const Monoid * Ring::degree_monoid () const
Definition at line 12 of file ring.cpp.
 { return degree_ring->getMonoid(); }
References degree_ring, and PolynomialRing::getMonoid().
Referenced by FreeModule::append(), MatrixConstructor::append(), FreeModule::append_schreyer(), FreeModule::change_degree(), MatrixConstructor::compute_column_degree(), FreeModule::computeHashValue(), degree(), DetComputation::DetComputation(), Matrix::diff(), res2_comp::free_of(), res_comp::free_of(), FreeModule::FreeModule(), IM2_FreeModule_get_degrees(), IM2_FreeModule_make_degs(), IM2_Matrix_get_degree(), IM2_RingElement_multidegree(), WeylAlgebra::initialize_weyl(), FreeModule::is_equal(), PolyRing::is_homogeneous(), Matrix::make(), FreeModule::make_schreyer(), Matrix::make_sparse(), MatrixConstructor::MatrixConstructor(), res2_comp::minimal_free_of(), res_comp::minimal_free_of(), Matrix::mult(), res2_comp::multi_degree(), FractionField::multi_degree(), LocalRing::multi_degree(), PolyRing::multi_degree(), FreeModule::primary_degree(), rawMatrixRatConversion(), Matrix::remake(), gb2_comp::schreyer_append(), FreeModule::select_by_degrees(), SymmMatrix::SymmMatrix(), FreeModule::text_out(), FreeModule::transpose(), and vec_is_homogeneous().