Macaulay2 Engine: Ring::make_FreeModule
make_FreeModule() [1/2]
FreeModule * Ring::make_FreeModule () const virtual
Definition at line 52 of file ring.cpp.
{
  return new FreeModule(this, 0, false);
}
Referenced by BRPStoMatrix(), Matrix::coeffs(), Matrix::content(), ChineseRemainder::CRA(), DetComputation::DetComputation(), SLP< Field >::evaluate(), gbres_comp::free_module(), NCResComputation::get_free(), F4ResComputation::get_free(), FreeModule::get_induced_order(), PathTracker::getAllSolutions(), PolynomialRing::getPresentation(), PathTracker::getSolution(), IM2_FreeModule_make(), IM2_FreeModule_make_degs(), LocalRing::is_in_prime(), LocalRing::lift_up(), Matrix::make(), FreeModule::make_schreyer(), FreeModule::make_schreyer(), MatrixConstructor::MatrixConstructor(), matrixFromSparseMatrixGenerator(), res_comp::minimal_free_of(), NCCoefficientMatrix(), FreeModule::new_free(), PfaffianComputation::PfaffianComputation(), polyListToMatrix(), PolyRingQuotient::quotient(), Matrix::random(), rawFourierMotzkin(), rawHilbertBasis(), rawMatrixRatConversion(), rawMatrixReadMsolveFile(), rawMatrixReadMsolveString(), PathTracker::refine(), PolyRingQuotient::remainder(), PolyRingQuotient::remainderAndQuotient(), Matrix::split_off_content(), sagbi::subduct(), sagbi::subduct1(), PolyRingQuotient::syzygy(), TEST(), TEST(), toMatrix(), toMatrix(), Matrix::top_coefficients(), and FreeModule_symm::value().