Macaulay2 Engine: Ring::subtract_vec_to
subtract_vec_to()
void Ring::subtract_vec_to (vec & v, vec & w) const
Definition at line 503 of file ring-vecs.cpp.
 {
   negate_vec_to(w);
   add_vec_to(v, w);
 }
References add_vec_to(), and negate_vec_to().
Referenced by binomial_ring::binomial_to_vector(), and HermiteComputation::merge().