Macaulay2 Engine: Ring::negate_vec_to
negate_vec_to()
void Ring::negate_vec_to (vec & v) const
Definition at line 493 of file ring-vecs.cpp.
 {
   vec w = v;
   while (w != NULL)
     {
       negate_to(w->coeff);
       w = w->next;
     }
 }
References negate_to().
Referenced by GaussElimComputation::matrix_lift(), HermiteComputation::matrix_lift(), and subtract_vec_to().