Macaulay2 Engine: Ring::subtract_to
subtract_to()
void Ring::subtract_to (ring_elem & f, const ring_elem & g) const
Definition at line 203 of file ring.cpp.
 {
   f = subtract(f, g);
 }
References subtract().
Referenced by DetComputation::calc_det(), PfaffianComputation::calc_pfaff(), DetComputation::detmult(), hilb_comp::do_ideal(), LLLoperations::doLLL(), FractionField::internal_subtract_to(), DetComputation::make_dynamic_cache(), FractionField::subtract(), and LocalRing::subtract().