Macaulay2 Engine: Ring::one
one()
ring_elem Ring::one () const inline
Definition at line 318 of file ring.hpp.
 { return oneV; }
References oneV.
Referenced by FreeAlgebra::add(), HilbertController::addMonomial(), BRPStoMatrix(), convertToM2(), DetComputation::DetComputation(), FractionField::elem_text_out(), LocalRing::elem_text_out(), SchurRing2::from_partition(), M2FreeAlgebra::index_of_var(), GF::initialize_GF(), KBasis::insert(), Matrix::koszul(), Matrix::koszul_monomials(), FractionField::lift(), LocalRing::lift(), gbA::minimalize_pairs_ZZ(), binomial_ring::monomial_to_vector(), GaussElimComputation::new_gen(), PfaffianComputation::PfaffianComputation(), power(), rawExtendedGCDRingElement(), FractionField::set_non_unit_frac(), LocalRing::set_non_unit_frac(), FractionField::simplify(), LocalRing::simplify(), SchurRing2::SMappendTerm(), PolyRing::syzygy(), TEST(), PolyRing::translate_gbvector_from_vec(), PolyRing::translate_gbvector_from_vec_QQ(), PolyRing::translate_gbvector_to_vec(), and Matrix::wedge_product().