Macaulay2 Engine: Ring::mult
mult()
virtual ring_elem Ring::mult (const ring_elem f, const ring_elem g) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurSnRing, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by FractionField::add(), FreeAlgebra::addScalarMultipleOf(), WeylAlgebra::binomial(), DetComputation::calc_det(), PfaffianComputation::calc_pfaff(), check_nterm_multiples(), convertToM2(), DetComputation::detmult(), diff(), WeylAlgebra::diff_coefficients(), SchurRing::dimension(), FractionField::divide(), dot_product(), M2::ARingGFFlintBig::eval(), RingMap::eval_term(), M2::GaloisFieldTable::GaloisFieldTable(), GF::initialize_GF(), FractionField::internal_add_to(), FractionField::internal_subtract_to(), FractionField::lift(), DetComputation::make_dynamic_cache(), FractionField::mult(), SchurRing2::mult(), CoefficientRingR::mult(), res2_poly::mult_by_coefficient(), SchurRing2::mult_by_coefficient(), res2_poly::mult_by_term(), res_poly::mult_by_term(), SchurRing::mult_by_term(), GBRingPoly::mult_by_term1(), GBRingSkew::mult_by_term1(), FreeAlgebra::mult_by_term_left(), FreeAlgebra::mult_by_term_left_and_right(), FreeAlgebra::mult_by_term_right(), PolyRing::mult_coeff_to(), mult_row(), mult_to(), mult_vec(), mult_vec_to(), RingElement::operator*(), power(), PolyRing::power_direct(), MutableComplex::prune_unit(), rightmult_vec(), res2_poly::ring_mult_by_term(), res_poly::ring_mult_by_term(), FractionField::subtract(), and CoefficientRingR::subtract_multiple().