Macaulay2 Engine: Ring::cast_to_PolynomialRing
cast_to_PolynomialRing() [2/2]
virtual const PolynomialRing* Ring::cast_to_PolynomialRing () const inline virtual
Reimplemented in PolynomialRing.
Definition at line 208 of file ring.hpp.
 { return 0; }
Referenced by BRPSfromMatrix(), check_coeff_ring(), checkGaloisFieldInput(), BIBasis::Launcher::CheckMatrix(), GBComputation::choose_gb(), ResolutionComputation::choose_res(), hilb_comp::coeff_of(), Matrix::coeffs(), coeffs_of_vec(), Matrix::content(), RingElement::content(), convertToFactory(), SchreyerOrder::create(), GBDeclared::create(), GBinhom_comp::create(), binomialGB_comp::create(), gbA::create(), createF4GB(), RingElement::degree_weights(), Matrix::diff(), Matrix::dimension1(), Matrix::divide_by_var(), Matrix::elim_keep(), Matrix::elim_vars(), F4Computation::F4Computation(), FreeModule::FreeModule(), ResF4toM2Interface::from_M2_vec(), F4toM2Interface::from_M2_vec(), gb_emitter::gb_emitter(), GBDeclared::GBDeclared(), GBKernelComputation::GBKernelComputation(), GBMatrix::GBMatrix(), GBWeight::GBWeight(), RingElement::get_coeff(), FreeModule::get_induced_order(), RingElement::get_terms(), RingElement::getSmallIntegerCoefficients(), HilbertController::HilbertController(), RingElement::homogenize(), IM2_Monoid_make(), IM2_Ring_quotient(), IM2_Ring_quotient1(), IM2_Ring_schur(), IM2_Ring_skew_polyring(), IM2_Ring_solvable_algebra(), IM2_Ring_weyl_algebra(), IM2_RingElement_list_form(), IM2_RingElement_term(), gbA::initialize(), res2_comp::initialize(), res_comp::initialize(), GB_comp::initialize0(), GF::initialize_GF(), KBasis::k_basis(), KBasis::KBasis(), Matrix::koszul(), Matrix::koszul_monomials(), RingElement::lead_coeff(), RingElement::lead_monom(), PolyRing::lift(), PolyRing::make_logical_term(), Matrix::make_monideal(), FreeModule::make_schreyer(), makemonideal(), PolynomialRing::n_fraction_vars(), RingElement::n_terms(), PolyRing::promote(), rawAmbientRing(), rawCharSeries(), rawDenominatorRing(), rawExtendedGCDRingElement(), rawFactorBase(), rawGbBoolean(), rawGCDRingElement(), rawGetPart(), rawGetParts(), rawIdealOfPoints(), rawIdealReorder(), rawPseudoRemainder(), rawRoots(), rawTowerTranslatePoly(), RingMap::RingMap(), GBinhom_comp::set_up0(), gbres_comp::setup(), gb2_comp::setup(), Matrix::split_off_content(), Matrix::support(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), GBMatrix::to_matrix(), Matrix::top_coefficients(), TowerEvaluator::TowerEvaluator(), vec_in_subring(), and vec_remove_monomial_factors().