Macaulay2 Engine: Ring::vec_degree_of_var
vec_degree_of_var()
void Ring::vec_degree_of_var (int n, const vec v, int & lo, int & hi) const
Definition at line 704 of file ring-vecs.cpp.
 {
   if (v == nullptr)
     {
       ERROR("attempting to find degree of zero vector");
       return;
     }
   degree_of_var(n, v->coeff, lo, hi);
   for (vec w = v->next; w != nullptr; w = w->next)
     {
       int lo1, hi1;
       degree_of_var(n, w->coeff, lo1, hi1);
       if (lo1 < lo) lo = lo1;
       if (hi1 > hi) hi = hi1;
     }
 }
References degree_of_var(), and ERROR().
Referenced by Matrix::divide_by_var().