Macaulay2 Engine: Ring::vec_content
vec_content()
ring_elem Ring::vec_content (vec f) const
Definition at line 959 of file ring-vecs.cpp.
 {
   if (f == nullptr) return zero();
   ring_elem c = content(f->coeff);
   for (vec t = f->next; t != nullptr; t = t->next) lower_content(c, t->coeff);
   return c;
 }
References content(), lower_content(), and zero().
Referenced by Matrix::content(), vec_divide_by_content(), and vec_split_off_content().