Macaulay2 Engine: Ring::get_degree_ring
get_degree_ring()
const PolynomialRing* Ring::get_degree_ring () const inline
Definition at line 124 of file ring.hpp.
 { return degree_ring; }
References degree_ring.
Referenced by PolynomialRing::create_quotient(), hilb_comp::hilbertNumerator(), IM2_GB_set_hilbert_function(), FractionField::initialize_frac(), LocalRing::initialize_local(), KBasis::k_basis(), and KBasis::KBasis().