Macaulay2 Engine: Ring::tensor
tensor()
vec Ring::tensor (const FreeModule * F, vec v, const FreeModule * G, vec w) const
Definition at line 281 of file ring-vecs.cpp.
 {
   vecHeap H(F);
   for (; v != NULL; v = v->next)
     {
       vec w1 = component_shift(v->comp * G->rank(), w);
       mult_vec_to(w1, v->coeff, false);
       H.add(w1);
     }
   return H.value();
 }
References vecHeap::add(), component_shift(), mult_vec_to(), FreeModule::rank(), and vecHeap::value().
Referenced by Matrix::tensor().