Macaulay2 Engine: Ring::is_zero
is_zero()
virtual bool Ring::is_zero (const ring_elem f) const pure virtual
Implemented in Z_mod, RingZZ, Tower, SchurRing2, PolyRingQuotient, PolyRing, M2FreeAlgebraQuotient, M2FreeAlgebra, LocalRing, GF, FractionField, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Referenced by FractionField::add(), SchurRing2::add(), res2_poly::add_to(), res_poly::add_to(), add_vec_to(), DetComputation::calc_det(), PfaffianComputation::calc_pfaff(), DetComputation::detmult(), PolyRing::diff(), WeylAlgebra::diff_coefficients(), PolyRing::diff_term(), FractionField::divide(), divide_row(), divide_vec_to(), PolyRing::division_algorithm(), M2::ARingGFFlintBig::eval(), FractionField::eval(), LocalRing::eval(), RingMap::eval_term(), SchurRing2::from_coeff(), PolyRing::from_int(), PolyRing::from_long(), FractionField::from_rational(), PolyRing::from_rational(), PolyRing::fromCoefficient(), PolyRing::fromSmallIntegerCoefficients(), GBRing::gbvector_add_to(), GBRing::gbvector_reduce_lead_term_ZZ(), gbvectorHeap::get_lead_term(), vecHeap::get_lead_term(), DetComputation::get_pivot(), IM2_RingElement_is_zero(), PolyRing::imp_attempt_to_cancel_lead_term(), FractionField::internal_add_to(), PolyRing::internal_add_to(), FractionField::internal_subtract_to(), FractionField::is_unit(), RingElement::is_zero(), FractionField::is_zero(), CoefficientRingR::is_zero(), NaivePolynomialHeap< Queue >::isZero(), NaiveDedupPolynomialHeap< Queue >::isZero(), MapPolynomialHeap::isZero(), PriorityQueuePolynomialHeap::isZero(), DetComputation::make_dynamic_cache(), PolyRing::make_flat_term(), make_vec(), FractionField::mult(), mult_row(), mult_vec(), mult_vec_to(), FractionField::power(), power(), PolyRing::power_direct(), PolyRing::powerseries_division_algorithm(), preferred_associate(), quotient(), FractionField::random(), rawMutableMatrixFillRandom(), rawMutableMatrixFillRandomDensity(), remainder(), remainderAndQuotient(), polyheap::remove_lead_term(), rightmult_vec(), RingMap::RingMap(), Matrix::scalar_mult(), set_entry(), FractionField::simplify(), DetComputation::step(), PfaffianComputation::step(), FractionField::subtract(), TEST(), MutableMatrix::text_out(), vec_divide_by_expvector(), vec_divide_by_var(), vec_eval(), vec_zeroize_tiny(), and PolyRing::zeroize_tiny().