Macaulay2 Engine: Ring::cast_to_Z_mod
cast_to_Z_mod() [2/2]
virtual const Z_mod* Ring::cast_to_Z_mod () const inline virtual
Reimplemented in Z_mod.
Definition at line 203 of file ring.hpp.
 { return nullptr; }
Referenced by GBRing::GBRing(), Gausser::newGausser(), rawIdealOfPoints(), and VectorArithmetic::VectorArithmetic().