Macaulay2 Engine: Ring::add_vec_to
add_vec_to()
void Ring::add_vec_to (vec & v, vec & w) const
Definition at line 509 of file ring-vecs.cpp.
{
  if (w == nullptr) return;
  if (v == nullptr)
    {
      v = w;
      w = nullptr;
      return;
    }
  vecterm head;
  vec result = &head;
  while (true)
    if (v->comp < w->comp)
      {
        result->next = w;
        result = result->next;
        w = w->next;
        if (w == nullptr)
          {
            result->next = v;
            v = head.next;
            return;
          }
      }
    else if (v->comp > w->comp)
      {
        result->next = v;
        result = result->next;
        v = v->next;
        if (v == nullptr)
          {
            result->next = w;
            v = head.next;
            w = nullptr;
            return;
          }
      }
    else
      {
        vec tmv = v;
        vec tmw = w;
        v = v->next;
        w = w->next;
        tmv->coeff = this->add(tmv->coeff, tmw->coeff);
        if (this->is_zero(tmv->coeff))
          {
            remove_vec_node(tmv);
          }
        else
          {
            result->next = tmv;
            result = result->next;
          }
        remove_vec_node(tmw);
        if (w == nullptr)
          {
            result->next = v;
            v = head.next;
            return;
          }
        if (v == nullptr)
          {
            result->next = w;
            v = head.next;
            w = nullptr;
            return;
          }
      }
}
References add(), is_zero(), vec::next, and remove_vec_node().
Referenced by vecHeap::add(), add_vec(), vecHeap::current_value(), HermiteComputation::gb_reduce(), HermiteComputation::gb_reduce(), HermiteComputation::merge(), mult_vec_matrix(), GaussElimComputation::reduce(), HermiteComputation::reduce(), GaussElimComputation::reduce(), GaussElimComputation::reduce(), subtract_vec(), subtract_vec_to(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), vecHeap::value(), and vec_sort().