Macaulay2 Engine: Ring::isFinitePrimeField
isFinitePrimeField()
virtual bool Ring::isFinitePrimeField () const inline virtual
Reimplemented in M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, and Z_mod.
Definition at line 132 of file ring.hpp.
{ return false; }
Referenced by BIBasis::Launcher::CheckMatrix(), coeffMode(), IM2_RingElement_to_Integer(), rawGbBoolean(), and rawMGB().