Macaulay2 Engine: Ring::vec_sort
vec_sort()
void Ring::vec_sort (vecterm *& f) const
Definition at line 633 of file ring-vecs.cpp.
 {
   // Internal routine to place the elements back in order after
   // an operation such as subvector.
   // Divide f into two lists of equal length, sort each,
   // then add them together.  This allows the same monomial
   // to appear more than once in 'f'.
   if (f == nullptr || f->next == nullptr) return;
   vecterm *f1 = nullptr;
   vecterm *f2 = nullptr;
   while (f != nullptr)
     {
       vecterm *t = f;
       f = f->next;
       t->next = f1;
       f1 = t;
       if (f == nullptr) break;
       t = f;
       f = f->next;
       t->next = f2;
       f2 = t;
     }
   vec_sort(f1);
   vec_sort(f2);
   add_vec_to(f1, f2);
   f = f1;
 }
References add_vec_to(), and vec::next.
Referenced by coeffs_of_vec(), and sub_vector().