Macaulay2 Engine: Ring::power
power() [2/2]
ring_elem Ring::power (const ring_elem f, mpz_srcptr n) const virtual
Reimplemented in M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, M2::ConcreteRing< M2::ARingCC >, FractionField, GF, LocalRing, M2FreeAlgebra, M2FreeAlgebraQuotient, PolyRing, PolyRingQuotient, SchurRing, SkewPolynomialRing, SolvableAlgebra, WeylAlgebra, RingZZ, and Z_mod.
Definition at line 106 of file ring.cpp.
{
  ring_elem ff = gg;
  int cmp = mpz_sgn(m);  // the sign of m, <0, ==0, >0
  if (cmp == 0) return one();
  mpz_t n;
  mpz_init_set(n, m);
  // @TODO MES: rewrite this so it inverts before creating n.
  // That way we don't have to catch any exceptions here.
  // e.g. as
#if 0
  if (cmp < 0)
    ff = invert(ff);
  mpz_init_set(n, m);
  mpz_t n;
  if (cmp < 0)
    mpz_neg(n, n);
#endif
  if (cmp < 0)
    {
      mpz_neg(n, n);
      ff = invert(
          ff);  // this can raise an exception, in which case we need to free n.
      if (is_zero(ff))
        {
          ERROR(
              "either element not invertible, or no method available to "
              "compute its inverse");
          mpz_clear(n);
          return ff;
        }
    }
  ring_elem prod = from_long(1);
  ring_elem base = copy(ff);
  ring_elem tmp;
  for (;;)
    {
      if (RingZZ::mod_ui(n, 2) == 1)
        {
          tmp = mult(prod, base);
          prod = tmp;
        }
      mpz_tdiv_q_2exp(n, n, 1);
      if (mpz_sgn(n) == 0)
        {
          mpz_clear(n);
          return prod;
        }
      else
        {
          tmp = mult(base, base);
          base = tmp;
        }
    }
}
References base, copy(), ERROR(), from_long(), invert(), is_zero(), RingZZ::mod_ui(), mult(), and one().
Referenced by convertToM2(), GF::elem_text_out(), M2::ARingGFM2::elem_text_out(), M2::ARingGFM2::eval(), M2::ARingGFFlint::eval(), GF::eval(), RingMap::eval_term(), GF::getRepresentation(), GF::lift(), M2::ARingGFM2::lift_to_original_ring(), FractionField::power(), PolyRing::power(), PolyRingQuotient::power(), SkewPolynomialRing::power(), SolvableAlgebra::power(), WeylAlgebra::power(), FractionField::power(), PolyRing::power(), PolyRingQuotient::power(), RingElement::power(), RingElement::power(), FreeAlgebra::power(), PolyRing::power_direct(), TEST(), and Matrix::top_coefficients().