Macaulay2 Engine: Ring::from_Interval
from_Interval()
bool Ring::from_Interval (gmp_RRi a, ring_elem & result) const virtual
Reimplemented in PolyRing, M2::ConcreteRing< RingType >, M2::ConcreteRing< ARingQQ >, and M2::ConcreteRing< M2::ARingCC >.
Definition at line 251 of file ring.cpp.
 {
   result = from_long(0);
   return false;
 }
References from_long().
Referenced by M2::ARingRRi::eval(), PolyRing::from_Interval(), and IM2_RingElement_from_Interval().