Macaulay2 Engine: Ring::mult_vec_matrix
mult_vec_matrix()
vec Ring::mult_vec_matrix (const Matrix * m, vec v, bool opposite_mult) const
Definition at line 425 of file ring-vecs.cpp.
 {
   // Multiply m * v, using left or right mult for each scalar mult.
   // Each loop below should read
   // result = 0
   // for each non-zero term f e[component] of the vector v
   //    result += f M[v]
   vec result = NULL;
   for (; v != NULL; v = v->next)
     {
       vec w = this->copy_vec(m->elem(v->comp));
       mult_vec_to(w, v->coeff, !opposite_mult);
       this->add_vec_to(result, w);
     }
   return result;
 }
References add_vec_to(), copy_vec(), Matrix::elem(), and mult_vec_to().
Referenced by Matrix::mult().