Macaulay2 Engine: F4ResComputation::minimal_betti
minimal_betti()
M2_arrayint F4ResComputation::minimal_betti (M2_arrayint slanted_degree_limit, M2_arrayint length_limit)
Definition at line 211 of file res-f4-computation.cpp.
{
  bool stop_after_degree = (slanted_degree_limit->len == 1);
  int top_slanted_degree = slanted_degree_limit->array[0];
  int new_length_limit = (length_limit->len == 1 ? length_limit->array[0]
                                                 : frame().maxLevel() - 1);
  BettiDisplay B = frame().minimalBettiNumbers(
      stop_after_degree, top_slanted_degree, new_length_limit);
  return B.getBetti();
}
References frame(), BettiDisplay::getBetti(), SchreyerFrame::maxLevel(), and SchreyerFrame::minimalBettiNumbers().
Referenced by rawMinimalBetti().