Macaulay2 Engine: F4ResComputation::get_matrix
get_matrix() [1/2]
const Matrix * F4ResComputation::get_matrix (int level) protected virtual
Implements ResolutionComputation.
Definition at line 229 of file res-f4-computation.cpp.
References ERROR(), get_free(), PolynomialRing::getCoefficientRing(), Ring::is_QQ(), mComp, mOriginalRing, and ResF4toM2Interface::to_M2_matrix().