Macaulay2 Engine: F4ResComputation::get_free
get_free()
const FreeModule * F4ResComputation::get_free (int level) protected virtual
Implements ResolutionComputation.
Definition at line 258 of file res-f4-computation.cpp.
References Ring::make_FreeModule(), mComp, mInputGroebnerBasis, mOriginalRing, Matrix::rows(), and ResF4toM2Interface::to_M2_freemodule().
Referenced by get_matrix().