Macaulay2 Engine: TEST
TEST() [6/9]
TEST (RingRRR , ones)
Definition at line 40 of file RingRRRTest.cpp.
 {
   RingRRR *R = RingRRR::create(std::make_unique<M2::ARingRRR>(100));
   EXPECT_TRUE(R->is_equal(R->one(), R->from_long(1)));
   EXPECT_TRUE(R->is_equal(R->minus_one(), R->from_long(-1)));
   EXPECT_TRUE(R->is_equal(R->zero(), R->from_long(0)));
   EXPECT_TRUE(R->is_zero(R->from_long(0)));
 }
References M2::ConcreteRing< RingType >::create(), M2::ConcreteRing< RingType >::from_long(), M2::ConcreteRing< RingType >::is_equal(), M2::ConcreteRing< RingType >::is_zero(), Ring::minus_one(), Ring::one(), and Ring::zero().