Macaulay2 Engine: TEST
TEST() [9/9]
TEST (RingRRR , syzygy)
Definition at line 159 of file RingRRRTest.cpp.
 {
   // NOTE: RingRRR::syzygy, CCC::syzygy are not useful functions.
   // Should we remove these tests, and the corresponding functions?
   RingRRR *R = RingRRR::create(std::make_unique<M2::ARingRRR>(100));
   RingElementGenerator<RingRRR> gen(*R);
   for (int i = 0; i < ntrials; i++)
     {
       ring_elem u, v;
       ring_elem a = gen.nextElement();
       ring_elem b = gen.nextElement();
       if (R->is_zero(b)) continue;
       // special cases (note: b != 0 for rest of routine)
       // syzygy(0,b) returns (1,0)
       R->syzygy(R->zero(), b, u, v);
       EXPECT_TRUE(R->is_equal(u, R->one()));
       EXPECT_TRUE(R->is_equal(v, R->zero()));
       // syzygy(a,1) returns (1,-a)
       R->syzygy(a, R->one(), u, v);
       EXPECT_TRUE(R->is_equal(u, R->one()));
       EXPECT_TRUE(almostEqual(R, 98, v, R->negate(a)));
       // syzygy(a,-1) returns (1,a)
       R->syzygy(a, R->minus_one(), u, v);
       EXPECT_TRUE(R->is_equal(u, R->one()));
       EXPECT_TRUE(almostEqual(R, 98, v, a));
       R->syzygy(a, b, u, v);
       ring_elem result = R->add(R->mult(a, u), R->mult(b, v));
       EXPECT_TRUE(almostEqual(R, 94, result, R->zero()));
     }
 }
References M2::ConcreteRing< RingType >::add(), almostEqual(), M2::ConcreteRing< RingType >::create(), M2::ConcreteRing< RingType >::is_equal(), M2::ConcreteRing< RingType >::is_zero(), Ring::minus_one(), M2::ConcreteRing< RingType >::mult(), M2::ConcreteRing< RingType >::negate(), RingElementGenerator< RingType >::nextElement(), ntrials, Ring::one(), M2::ConcreteRing< RingType >::syzygy(), and Ring::zero().