Macaulay2 Engine: TEST
TEST() [4/9]
TEST (RingRRR , multDivide)
Definition at line 74 of file RingRRRTest.cpp.
 {
   RingRRR *R = RingRRR::create(std::make_unique<M2::ARingRRR>(100));
   RingElementGenerator<RingRRR> gen(*R);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (a*b) // b == a
       ring_elem a = gen.nextElement();
       ring_elem b = gen.nextElement();
       ring_elem c = R->mult(a, b);
       if (R->is_zero(b))
         EXPECT_TRUE(R->is_zero(c));
       else
         {
           ring_elem d = R->divide(c, b);
           EXPECT_TRUE(almostEqual(R, 94, d, a));
         }
     }
 }
References almostEqual(), M2::ConcreteRing< RingType >::create(), M2::ConcreteRing< RingType >::divide(), M2::ConcreteRing< RingType >::is_zero(), M2::ConcreteRing< RingType >::mult(), RingElementGenerator< RingType >::nextElement(), and ntrials.