Macaulay2 Engine: TEST
TEST() [7/9]
TEST (RingRRR , power)
Definition at line 130 of file RingRRRTest.cpp.
 {
   RingRRR *R = RingRRR::create(std::make_unique<M2::ARingRRR>(100));
   mpz_t gmp1;
   mpz_init(gmp1);
   RingElementGenerator<RingRRR> gen(*R);
   for (int i = 0; i < ntrials; i++)
     {
       ring_elem a = gen.nextElement();
       // TODO: what should the answer here be?
       // EXPECT_TRUE(R->is_equal(R->power(a, 0), R->one())); // 0^0 == 1 too?
       EXPECT_TRUE(R->is_equal(R->power(a, 1), a));
       int e1 = rawRandomInt(10) + 1;
       int e2 = rawRandomInt(10) + 1;
       // std::cout << "(" << e1 << "," << e2 << ")" << std::endl;
       ring_elem b = R->power(a, e1);
       ring_elem c = R->power(a, e2);
       ring_elem d = R->power(a, e1 + e2);
       EXPECT_TRUE(almostEqual(R, 96, R->mult(b, c), d));
       // Make sure that powers via mpz work (at least for small exponents)
       mpz_set_si(gmp1, e1);
       ring_elem b1 = R->power(a, gmp1);
       EXPECT_TRUE(R->is_equal(b1, b));
     }
   mpz_clear(gmp1);
 }
References almostEqual(), M2::ConcreteRing< RingType >::create(), M2::ConcreteRing< RingType >::is_equal(), M2::ConcreteRing< RingType >::mult(), RingElementGenerator< RingType >::nextElement(), ntrials, M2::ConcreteRing< RingType >::power(), and rawRandomInt().