Macaulay2 Engine: almostEqual
almostEqual()
bool almostEqual (const RingRRR * R, int nbits, ring_elem a, ring_elem b)
Definition at line 9 of file RingRRRTest.cpp.
{
  mpfr_t epsilon;
  mpfr_init2(epsilon, 100);
  mpfr_set_ui_2exp(epsilon, 1, -nbits, MPFR_RNDN);
  ring_elem c = R->subtract(a, b);
  bool ret = mpfr_cmpabs(c.get_mpfr(), epsilon) < 0;
  mpfr_clear(epsilon);
  return ret;
}
References ring_elem::get_mpfr(), and M2::ConcreteRing< RingType >::subtract().
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().