Macaulay2 Engine: DetComputation::DetComputation
DetComputation()
DetComputation::DetComputation (const Matrix * M, int p, bool do_exterior, int strategy)
Definition at line 8 of file det.cpp.
     : R(M0->get_ring()),
       M(M0),
       done(false),
       p(p0),
       do_exterior(do_exterior0),
       strategy(strategy0),
       row_set(nullptr),
       col_set(nullptr),
       this_row(0),
       this_col(0),
       D(nullptr),
       dynamic_cache(0)
 {
   if (do_exterior)
     {
       F = M->rows()->exterior(p);
       FreeModule *G = M->cols()->exterior(p);
       int *deg = R->degree_monoid()->make_new(M->degree_shift());
       R->degree_monoid()->power(deg, p, deg);
       result = MatrixConstructor(F, G, deg);
       R->degree_monoid()->remove(deg);
     }
   else
     {
       F = R->make_FreeModule(1);
       result = MatrixConstructor(F, 0);
     }
   // Handle trivial cases
   if (p < 0)
     {
       // In either case, want a zero matrix
       done = true;
       return;
     }
   if (p == 0)
     {
       // We want a single element which is '1'
       if (do_exterior)
         result.set_entry(0, 0, R->one());
       else
         result.append(R->make_vec(0, R->one()));
       done = true;
       return;
     }
   if (p > M->n_rows() || p > M->n_cols())
     {
       // Zero matrix in either case
       done = true;
       return;
     }
   done = false;
   row_set = newarray_atomic(size_t, p);
   col_set = newarray_atomic(size_t, p);
   for (size_t i = 0; i < p; i++)
     {
       row_set[i] = i;
       col_set[i] = i;
     }
   D = newarray(ring_elem *, p);
   for (size_t i = 0; i < p; i++)
     {
       D[i] = newarray(ring_elem, p);
       for (size_t j = 0; j < p; j++) D[i][j] = ZERO_RINGELEM;
     }
 }
References MatrixConstructor::append(), col_set, Matrix::cols(), D, Ring::degree_monoid(), Matrix::degree_shift(), do_exterior, done, FreeModule::exterior(), F, G, M, Ring::make_FreeModule(), Monoid::make_new(), Ring::make_vec(), Matrix::n_cols(), Matrix::n_rows(), newarray, newarray_atomic, Ring::one(), p, Monoid::power(), R, Monoid::remove(), result, row_set, Matrix::rows(), MatrixConstructor::set_entry(), and ZERO_RINGELEM.