Macaulay2 Engine: DetComputation::calc
calc()
int DetComputation::calc (int nsteps)
Definition at line 272 of file det.cpp.
 {
   for (;;)
     {
       int r = step();
       if (M2_gbTrace >= 3) emit_wrapped(".");
       if (r == COMP_DONE) return COMP_DONE;
       if (--nsteps == 0) return COMP_DONE_STEPS;
       if (system_interrupted()) return COMP_INTERRUPTED;
     }
 }
References COMP_DONE, COMP_DONE_STEPS, COMP_INTERRUPTED, emit_wrapped(), M2_gbTrace, step(), and system_interrupted().
Referenced by Matrix::exterior(), and Matrix::minors().