Macaulay2 Engine: DetComputation::step
step()
int DetComputation::step ()
Definition at line 190 of file det.cpp.
 {
   if (done) return COMP_DONE;
   ring_elem r;
   if (strategy == DET_BAREISS)
     {
       get_minor(row_set, col_set, p, D);
       r = bareiss_det();
     }
   else if (strategy == DET_DYNAMIC)
     {
       if (dynamic_cache.empty())
         {  // Cache minors if needed
           dynamic_cache.resize(p);
           if (make_dynamic_cache() == COMP_INTERRUPTED) return COMP_INTERRUPTED;
         }
       std::vector<int> row_vec(p), col_vec(p);
       for (int i = 0; i < p; ++i)
         {
           row_vec[i] = static_cast<int>(row_set[i]);
           col_vec[i] = static_cast<int>(col_set[i]);
         }
       // Find row number
       const Subdeterminant &map = dynamic_cache[p - 1][row_lookup[row_vec[0]]];
       auto it = map.find({row_vec, col_vec});
       if (it != map.end()) { r = it->second; }
       else { r = ZERO_RINGELEM; }
     }
   else
     r = calc_det(row_set, col_set, p);
   if (!R->is_zero(r))
     {
       if (do_exterior)
         result.set_entry(this_row, this_col, r);
       else
         result.append(R->make_vec(0, r));
     }
   else
     R->remove(r);
   this_row++;
   if (!Subsets::increment(M->n_rows(), p, row_set))
     {
       // Now we increment column
       if (!Subsets::increment(M->n_cols(), p, col_set))
         {
           done = true;
           return COMP_DONE;
         }
       // Now set the row set back to initial value
       this_col++;
       this_row = 0;
       for (size_t i = 0; i < p; i++) row_set[i] = i;
     }
   return COMP_COMPUTING;
 }
References MatrixConstructor::append(), bareiss_det(), calc_det(), col_set, COMP_COMPUTING, COMP_DONE, COMP_INTERRUPTED, D, DET_BAREISS, DET_DYNAMIC, do_exterior, done, dynamic_cache, get_minor(), Subsets::increment(), Ring::is_zero(), M, make_dynamic_cache(), Ring::make_vec(), Matrix::n_cols(), Matrix::n_rows(), p, R, Ring::remove(), result, row_lookup, row_set, MatrixConstructor::set_entry(), strategy, this_col, this_row, and ZERO_RINGELEM.
Referenced by calc().