Macaulay2 Engine: DetComputation::bareiss_det
bareiss_det()
ring_elem DetComputation::bareiss_det () private
Definition at line 345 of file det.cpp.
 {
   // Computes the determinant of the p by p matrix D. (dense form).
   int sign = 1;
   size_t pivot_col;
   ring_elem pivot = R->from_long(0);
   ring_elem lastpivot = R->from_long(0);
   for (size_t r = p - 1; r >= 1; --r)
     {
       R->remove(lastpivot);
       lastpivot = pivot;
       if (!get_pivot(D, r, pivot, pivot_col))  // sets pivot_col and pivot
         {
           // Remove the rest of D.
           for (size_t i = 0; i <= r; i++)
             for (size_t j = 0; j <= r; j++) R->remove(D[i][j]);
           R->remove(lastpivot);
           return R->from_long(0);
         }
       for (size_t i = 0; i < r; i++) gauss(D, i, r, pivot_col, lastpivot);
       if (((r + pivot_col) % 2) == 1)
         sign = -sign;  // MES: do I need to rethink this logic?
       for (size_t c = 0; c <= r; c++)
         if (c != pivot_col)
           R->remove(D[r][c]);
         else
           D[r][c] = ZERO_RINGELEM;
     }
   R->remove(pivot);
   R->remove(lastpivot);
   ring_elem r = D[0][0];
   D[0][0] = ZERO_RINGELEM;
   if (sign < 0) R->negate_to(r);
   return r;
 }
References D, Ring::from_long(), gauss(), get_pivot(), Ring::negate_to(), p, R, Ring::remove(), and ZERO_RINGELEM.
Referenced by step().