Macaulay2 Engine: DetComputation::set_next_minor
set_next_minor()
void DetComputation::set_next_minor (const int * rows, const int * cols)
Definition at line 258 of file det.cpp.
 {
   if (do_exterior) return;
   if (rows != NULL && Subsets::isValid(M->n_rows(), p, rows))
     for (size_t i = 0; i < p; i++) row_set[i] = rows[i];
   else
     for (size_t i = 0; i < p; i++) row_set[i] = i;
   if (cols != NULL && Subsets::isValid(M->n_cols(), p, cols))
     for (size_t i = 0; i < p; i++) col_set[i] = cols[i];
   else
     for (size_t i = 0; i < p; i++) col_set[i] = i;
 }
References col_set, do_exterior, Subsets::isValid(), M, Matrix::n_cols(), Matrix::n_rows(), p, and row_set.
Referenced by Matrix::minors().