Macaulay2 Engine: DetComputation::gauss
gauss()
void DetComputation::gauss (ring_elem ** D, size_t i, size_t r, size_t pivot_col, ring_elem lastpivot) private
Definition at line 327 of file det.cpp.
 {
   ring_elem f = D0[i][pivot_col];
   ring_elem pivot = D0[r][pivot_col];
   for (size_t c = 0; c < pivot_col; c++)
     D0[i][c] = detmult(pivot, D0[i][c], f, D0[r][c], lastpivot);
   for (size_t c = pivot_col + 1; c <= r; c++)
     D0[i][c - 1] = detmult(pivot, D0[i][c], f, D0[r][c], lastpivot);
   R->remove(f);
 }
References detmult(), R, and Ring::remove().
Referenced by bareiss_det().