Macaulay2 Engine: DetComputation::calc_det
calc_det()
ring_elem DetComputation::calc_det (size_t * r, size_t * c, int p) private
Definition at line 387 of file det.cpp.
 {
   if (p0 == 1) return M->elem(static_cast<int>(r[0]), static_cast<int>(c[0]));
   ring_elem answer = R->from_long(0);
   int negate = 1;
   for (int i = p0 - 1; i >= 0; i--)
     {
       std::swap(c[i], c[p0 - 1]);
       negate = !negate;
       ring_elem g =
           M->elem(static_cast<int>(r[p0 - 1]), static_cast<int>(c[p0 - 1]));
       if (R->is_zero(g))
         {
           R->remove(g);
           continue;
         }
       ring_elem h = calc_det(r, c, p0 - 1);
       ring_elem gh = R->mult(g, h);
       R->remove(g);
       R->remove(h);
       if (negate)
         R->subtract_to(answer, gh);
       else
         R->add_to(answer, gh);
     }
   // pulling out the columns has disordered c. Fix it.
   size_t temp = c[p0 - 1];
   for (size_t i = p0 - 1; i > 0; i--) c[i] = c[i - 1];
   c[0] = temp;
   return answer;
 }
References Ring::add_to(), Matrix::elem(), Ring::from_long(), Ring::is_zero(), M, Ring::mult(), mpfr::negate(), R, Ring::remove(), Ring::subtract_to(), and swap.
Referenced by step().