Macaulay2 Engine: check_coeff_ring
check_coeff_ring()
int check_coeff_ring (const Ring * coeffR, const PolyRing * P)
Definition at line 347 of file poly.cpp.
 {
   int nvars = P->n_vars();
   if (coeffR != P->getCoefficients())
     {
       const PolynomialRing *P0 = coeffR->cast_to_PolynomialRing();
       if (P0 == 0)
         nvars = -1;
       else
         nvars -= P0->n_vars();
     }
   if (nvars < 0) ERROR("expected coefficient ring");
   return nvars;
 }
References Ring::cast_to_PolynomialRing(), ERROR(), PolynomialRing::getCoefficients(), and PolynomialRing::n_vars().
Referenced by PolyRing::get_coeff(), and PolyRing::list_form().