Macaulay2 Engine: isUnivariateOverPrimeField
isUnivariateOverPrimeField()
const PolyRing* isUnivariateOverPrimeField (const Ring * R)
Definition at line 2226 of file poly.cpp.
 {
   const PolyRing *P = R->cast_to_PolyRing();
   if (P == 0) return 0;
   if (P->n_vars() != 1) return 0;
   if (P->characteristic() == 0) return 0;
   return P;
 }
References Ring::cast_to_PolyRing(), Ring::characteristic(), and PolynomialRing::n_vars().