Macaulay2 Engine: M2::ARingGFM2::lift_to_original_ring
lift_to_original_ring()
void M2::ARingGFM2::lift_to_original_ring (ring_elem & result, const ElementType & f) const
Definition at line 152 of file aring-m2-gf.cpp.
 {
   if (f == 0)
     result = mGF.ring().from_long(0);
   else if (f == mGF.one())
     result = mGF.ring().from_long(1);
   else
     result = mGF.ring().power(mGF.primitiveElement(), f);
 }
References Ring::from_long(), mGF, M2::GaloisFieldTable::one(), Ring::power(), M2::GaloisFieldTable::primitiveElement(), and M2::GaloisFieldTable::ring().
Referenced by lift().