Macaulay2 Engine: M2::ARingGFM2::elem_text_out
elem_text_out()
void M2::ARingGFM2::elem_text_out (buffer & o, ElementType a, bool p_one = true, bool p_plus = false, bool p_parens = false) const
Definition at line 188 of file aring-m2-gf.cpp.
 {
   if (a == 0)
     {
       o << "0";
       return;
     }
   ring_elem h = mGF.ring().power(mGF.primitiveElement(), a);
   mGF.ring().elem_text_out(o, h, p_one, p_plus, p_parens);
   mGF.ring().remove(h);
 }
References Ring::elem_text_out(), mGF, Ring::power(), M2::GaloisFieldTable::primitiveElement(), Ring::remove(), and M2::GaloisFieldTable::ring().