Macaulay2 Engine: M2::ARingGFM2::promote
promote()
bool M2::ARingGFM2::promote (const Ring * Rf, const ring_elem f, elem & result) const
Definition at line 141 of file aring-m2-gf.cpp.
 {
   if (&mGF.ring() != Rf) return false;
   std::vector<long> poly;
   RingElement F(Rf, f);
   F.getSmallIntegerCoefficients(poly);
   fromSmallIntegerCoefficients(result, poly);
   return true;
 }
References fromSmallIntegerCoefficients(), RingElement::getSmallIntegerCoefficients(), mGF, and M2::GaloisFieldTable::ring().