Macaulay2 Engine: M2::ARingGFM2::divide
divide()
void M2::ARingGFM2::divide (elem & result, elem a, elem b) const inline
Definition at line 260 of file aring-m2-gf.hpp.
   {
     if (b == 0)
       throw exc::division_by_zero_error();
     if (a != 0)
       {
         int c = a - b;
         if (c <= 0) c += mGF.orderMinusOne();
         result = c;
       }
     else
       result = 0;
   }
References mGF, and M2::GaloisFieldTable::orderMinusOne().
Referenced by set_from_mpq(), and syzygy().