Macaulay2 Engine: M2::ARingGFM2::fromSmallIntegerCoefficients
fromSmallIntegerCoefficients()
void M2::ARingGFM2::fromSmallIntegerCoefficients (ElementType & result, const std::vector< long > & poly) const
Definition at line 125 of file aring-m2-gf.cpp.
 {
   result = 0;
   ElementType a, b;
   for (long i = 0; i < poly.size(); i++)
     if (poly[i] != 0)
       {
         set_from_long(a, poly[i]);
         power(b, mGF.generatorExponent(), i);
         mult(a, a, b);
         add(result, result, a);
       }
 }
References add(), M2::GaloisFieldTable::generatorExponent(), mGF, mult(), power(), and set_from_long().
Referenced by promote().