Macaulay2 Engine: M2::ARingGFM2::set_from_mpz
set_from_mpz()
void M2::ARingGFM2::set_from_mpz (elem & result, mpz_srcptr a) const inline
Definition at line 167 of file aring-m2-gf.hpp.
   {
     int b = static_cast<int>(mpz_fdiv_ui(a, characteristic()));
     result = mGF.fromZZTable(b);
   }
References characteristic(), M2::GaloisFieldTable::fromZZTable(), and mGF.
Referenced by set_from_mpq().