Macaulay2 Engine: M2::ARingGFM2::add
add()
void M2::ARingGFM2::add (elem & result, elem a, elem b) const inline
Definition at line 199 of file aring-m2-gf.hpp.
   {
     if (a == 0)
       result = b;
     else if (b == 0)
       result = a;
     else
       {
         int n = a - b;
         if (n > 0)
           {
             if (n == mGF.minusOne())
               result = 0;
             else
               result = modulus_add(b, mGF.oneTable(n), mGF.orderMinusOne());
           }
         else if (n < 0)
           {
             if (-n == mGF.minusOne())
               result = 0;
             else
               result = modulus_add(a, mGF.oneTable(-n), mGF.orderMinusOne());
           }
         else
           {
             if (mGF.characteristic() == 2)
               result = 0;
             else
               result =
                   modulus_add(a, mGF.oneTable(mGF.one()), mGF.orderMinusOne());
           }
       }
   }
References M2::GaloisFieldTable::characteristic(), mGF, M2::GaloisFieldTable::minusOne(), modulus_add(), M2::GaloisFieldTable::one(), M2::GaloisFieldTable::oneTable(), and M2::GaloisFieldTable::orderMinusOne().
Referenced by fromSmallIntegerCoefficients(), and subtract().