Macaulay2 Engine: M2::ARingGFM2::syzygy
syzygy()
void M2::ARingGFM2::syzygy (ElementType a, ElementType b, ElementType & x, ElementType & y) const inline
Definition at line 326 of file aring-m2-gf.hpp.
   {
     assert(a != 0);
     assert(b != 0);
     x = mGF.one();
     divide(y, a, b);
     negate(y, y);
   }
References divide(), mGF, negate(), M2::GaloisFieldTable::one(), and x.