Macaulay2 Engine: SMat::numColumns
numColumns()
template<typename ACoeffRing > size_t SMat< ACoeffRing >::numColumns () const inline
Definition at line 73 of file smat.hpp.
{ return ncols_; }
References SMat< ACoeffRing >::ncols_.
Referenced by MatrixOps::addInPlace(), SMat< ACoeffRing >::column(), SMat< ACoeffRing >::column(), MatrixOps::subtractInPlace(), toMatrix(), and MatrixOps::transpose().