Macaulay2 Engine: ResMonoidDense::monomial_size
monomial_size()
int ResMonoidDense::monomial_size (res_const_packed_monomial m) const inline
Definition at line 66 of file res-moninfo-dense.hpp.
 { return nslots; }
References nslots.
Referenced by dump(), ResF4toM2Interface::from_M2_vec(), ResPolynomialIterator::operator++(), ResPolynomialConstructor::setPoly(), show(), ResF4toM2Interface::to_M2_MutableMatrix(), and ResF4toM2Interface::to_M2_vec().