Macaulay2 Engine: ResMonoidDense::showAlpha
showAlpha()
void ResMonoidDense::showAlpha (res_const_packed_monomial m) const
Definition at line 106 of file res-moninfo-dense.cpp.
 {
   component_index comp = get_component(m);
   m += 2 + nweights;  // get by: hashcode, component, weightvals
   for (int i = 0; i < nvars; i++)
     {
       long e = *m++;
       if (e == 0) continue;
       fprintf(stdout, "%c", 'a' + i);
       if (e > 1) fprintf(stdout, "%ld", e);
     }
   fprintf(stdout, "<%d>", comp);
 }
References get_component(), nvars, and nweights.
Referenced by compare_schreyer(), F4Res::debugOutputColumns(), F4Res::debugOutputReducers(), display_poly(), and SchreyerFrame::show().