Macaulay2 Engine: ResMonoidDense::show
show() [1/2]
void ResMonoidDense::show () const
Definition at line 71 of file res-moninfo-dense.cpp.
 {
   fprintf(stderr, "monomial info\n");
   fprintf(stderr, "  nvars  = %d", nvars);
   fprintf(stderr, "  nslots = %d", nslots);
   fprintf(stderr, "  mask   = %d", mask);
   fprintf(stderr, "  hash values for each variable\n");
   for (int i = 0; i < nvars; i++) fprintf(stderr, "    %d\n", hashfcn[i]);
   fprintf(stderr, "  #calls hashval = %lu\n", ncalls_hash_value);
   fprintf(stderr, "  #calls compare = %lu\n", ncalls_compare);
   fprintf(stderr, "  #calls mult    = %lu\n", ncalls_mult);
   fprintf(stderr, "  #calls get comp= %lu\n", ncalls_get_component);
   fprintf(stderr, "  #calls fromexp = %lu\n", ncalls_from_expvector);
   fprintf(stderr, "  #calls toexp   = %lu\n", ncalls_to_expvector);
   fprintf(stderr, "  #calls fromvp  = %lu\n", ncalls_from_varpower);
   fprintf(stderr, "  #calls tovp    = %lu\n", ncalls_to_varpower);
   fprintf(stderr, "  #calls is equal= %lu\n", ncalls_is_equal);
   fprintf(stderr, "  #calls eq true = %lu\n", ncalls_is_equal_true);
   fprintf(stderr, "  #calls divide  = %lu\n", ncalls_divide);
   fprintf(stderr, "  #calls weight  = %lu\n", ncalls_weight);
   fprintf(stderr, "  #calls unneeded= %lu\n", ncalls_unneccesary);
   fprintf(stderr, "  #calls vp quot = %lu\n", ncalls_quotient_as_vp);
 }
References hashfcn, mask, ncalls_compare, ncalls_divide, ncalls_from_expvector, ncalls_from_varpower, ncalls_get_component, ncalls_hash_value, ncalls_is_equal, ncalls_is_equal_true, ncalls_mult, ncalls_quotient_as_vp, ncalls_to_expvector, ncalls_to_varpower, ncalls_unneccesary, ncalls_weight, nslots, and nvars.
Referenced by SchreyerFrame::minimalBettiNumbers(), ResMonomialsWithComponent::show(), and ResMonomialsIgnoringComponent::show().