Macaulay2 Engine: ResMonoidDense::to_expvector
to_expvector()
bool ResMonoidDense::to_expvector (res_const_packed_monomial m, res_ntuple_monomial result, component_index & result_comp) const inline
Definition at line 147 of file res-moninfo-dense.hpp.
   {
     // Unpack the monomial m.
     ncalls_to_expvector++;
     result_comp = m[1];
     m += 2 + nweights;
     for (int i = 0; i < nvars; i++) *result++ = *m++;
     return true;
   }
References ncalls_to_expvector, nvars, and nweights.
Referenced by ResF4MonomialLookupTableT< Key >::find_all_divisors_packed(), ResF4toM2Interface::to_M2_freemodule(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), and ResMonomialSorter::toMonomial().