Macaulay2 Engine: ResMonoidDense::get_component
get_component()
component_index ResMonoidDense::get_component (res_const_packed_monomial m) const inline
Definition at line 86 of file res-moninfo-dense.hpp.
   {
     ncalls_get_component++;
     return m[1];
   }
References ncalls_get_component.
Referenced by ResF4MonomialLookupTableT< Key >::find_all_divisors_packed(), F4Res::findDivisor(), ResMonomialsWithComponent::hash_value(), DegreeZeroMapGenerator::iterator::increment(), SchreyerFrame::insertBasic(), SchreyerFrame::insertLevelOne(), F4Res::loadRow(), DegreeZeroMapGenerator::numNonzero(), F4Res::processMonomialProduct(), SchreyerFrame::setSchreyerOrder(), showAlpha(), and ResF4toM2Interface::to_M2_MutableMatrix().