Macaulay2 Engine: getElement< M2::ARingZZ >
getElement< M2::ARingZZ >()
template<> void getElement< M2::ARingZZ > (const M2::ARingZZ & R, int index, M2::ARingZZ::ElementType & result)
Definition at line 17 of file ARingZZTest.cpp.
 {
   if (index < 50)
     R.set_from_long(result, index - 25);
   else
     {
       gmp_ZZ a = getRandomInteger();
       R.set_from_mpz(result, a);
     }
 }
References getRandomInteger(), M2::ARingZZ::set_from_long(), and M2::ARingZZ::set_from_mpz().