Macaulay2 Engine: TEST
TEST() [2/2]
TEST (ARingZZ , create)
Definition at line 30 of file ARingZZTest.cpp.
 {
   M2::ARingZZ R;
   M2::ARingZZ::ElementType a;
   buffer o;
   ARingElementGenerator<M2::ARingZZ> gen(R);
   R.init(a);
   gen.nextElement(a);
   EXPECT_EQ(ringName(R), "ZZFlint");
   EXPECT_EQ(R.cardinality(), static_cast<size_t>(-1));
   EXPECT_EQ(R.characteristic(), 0);
   R.clear(a);
 }
References M2::ARingZZ::cardinality(), M2::ARingZZ::characteristic(), M2::ARingZZ::clear(), M2::ARingZZ::init(), ARingElementGenerator< RingType >::nextElement(), and ringName().