Macaulay2 Engine: TEST
TEST() [1/2]
TEST (ARingZZ , arithmetic)
Definition at line 47 of file ARingZZTest.cpp.
 {
   M2::ARingZZ R;
   testCoercions(R);
   testNegate(R, ntrials);
   testAdd(R, ntrials);
   testSubtract(R, ntrials);
   testMultiply(R, ntrials);
   testDivide(R, ntrials);
   //  testReciprocal(R, ntrials); // this test is not applicable, as this is not
   //  a field
   //  testPower(R, ntrials);  // this test can't work, as it expects a finite
   //  field
   testAxioms(R, ntrials);
 }
References ntrials, testAdd(), testAxioms(), testCoercions(), testDivide(), testMultiply(), testNegate(), and testSubtract().