Macaulay2 Engine: getRandomInteger
getRandomInteger()
gmp_ZZ getRandomInteger ()
Definition at line 20 of file ARingZZpTest.cpp.
 {
   if (!maxH_initialized)
     {
       maxH_initialized = true;
       mpz_init(maxH);
       mpz_set_str(maxH, "100000000000", 10);
     }
   return rawRandomInteger(maxH);
 }
Referenced by getElement< M2::ARingZZ >(), getElement< M2::ARingZZp >(), getElement< M2::ARingZZpFFPACK >(), and getElement< M2::ARingZZpFlint >().