Macaulay2 Engine: SLP::make
make() [1/2]
template<class Field > SLP< Field > * SLP< Field >::make (const Matrix * consts, M2_arrayint program) static
Definition at line 88 of file NAG.cpp.
     {
References SLP< Field >::C, cast_to_CCC(), SLP< Field >::cols_out, SLP< Field >::compiled_fn, dlopen, dlsym, Matrix::elem(), ERROR(), Matrix::get_ring(), SLP< Field >::handle, SLP< Field >::is_relative_position, libPREFIX, MAX_NUM_SLPs, Matrix::n_cols(), SLP< Field >::nodes, SLP< Field >::num_consts, SLP< Field >::num_inputs, SLP< Field >::program, SLP< Field >::rows_out, slpCOMPILED, slpCORRECTOR, slpPREDICTOR, and toBigComplex().