Macaulay2 Engine: SLP::concatenate
concatenate()
template<class Field > SLP< Field > * SLP< Field >::concatenate (const SLP< Field > * slp)
!! assume: appending constants
!! assume: appending constants
!! assume: appending constants
!! assume: appending constants
Definition at line 353 of file NAG.cpp.
References SLP< Field >::C, SLP< Field >::cols_out, CONST_OFFSET, ERROR(), SLP< Field >::is_relative_position, M2_makearrayint(), SLP< Field >::node_index, SLP< Field >::nodes, nodes, SLP< Field >::num_consts, SLP< Field >::num_inputs, SLP< Field >::num_operations, SLP< Field >::program, SLP< Field >::rows_out, and SLP_HEADER_LEN.
Referenced by StraightLineProgram::concatenate().