Macaulay2 Engine: SLP::make
make() [2/2]
template<class Field > SLP< Field > * SLP< Field >::make (const PolyRing * R, ring_elem e) static
Definition at line 289 of file NAG.cpp.
         {
           out = res->num_operations++;
           res->node_index.append(prog.length());
           prog.append(slpMULTIsum);
           prog.append(0);  // sum with zero summands
         }
       // make program
       res->program = M2_makearrayint(
           prog.length() + 2 /* accounts for lines +2,+3 */ + SLP_HEADER_LEN);
       res->program->array[0] = res->num_consts =
           static_cast<int>(consts.size());
       prog.append(slpEND);
       prog.append(out + res->num_consts +
                   res->num_inputs);  // position of the output
       res->program->array[1] = res->num_inputs;
       res->program->array[2] = res->rows_out;
       res->program->array[3] = res->cols_out;
       memcpy(res->program->array + SLP_HEADER_LEN,
              prog.raw(),
              sizeof(int) * prog.length());
       // make nodes: [constants, inputs, operations]
       make_nodes(res->nodes,
                  res->num_consts + res->num_inputs + res->num_operations);
       for (int i = 0; i < res->num_consts; i++)
         {
           res->nodes[i] = consts[i];
         }
     }
   return res;
 }
References intarray::append(), SLP< Field >::C, cast_to_CCC(), SLP< Field >::cols_out, Ring::copy(), ERROR(), ring_elem::get_poly(), SLP< Field >::is_relative_position, intarray::length(), M2_makearrayint(), MAX_NUM_SLPs, monomials_to_conventional_expvectors(), SLP< Field >::node_index, SLP< Field >::nodes, SLP< Field >::num_consts, SLP< Field >::num_inputs, SLP< Field >::num_operations, SLP< Field >::poly_to_horner_slp(), SLP< Field >::program, FreeModule::R, intarray::raw(), SLP< Field >::rows_out, SLP_HEADER_LEN, slpEND, slpMULTIsum, VECTOR(), and ZERO_CONST.
Referenced by StraightLineProgram::make().