Macaulay2 Engine: SLP::poly_to_horner_slp
poly_to_horner_slp()
template<class Field > int SLP< Field >::poly_to_horner_slp (int n, gc_vector< int > & prog, gc_vector< element_type > & consts, Nterm *& f) private
Definition at line 237 of file NAG.cpp.
 {
   int part_pos[n];  // absolute positions of the parts
   int last_nonzero_part_pos = ZERO_CONST;
   for (int i = 0; i < n; i++)
     {
       Nterm* fx = extract_divisible_by_x(f, i);
       if (fx == NULL)
         part_pos[i] = ZERO_CONST;
       else
         {
           int p = poly_to_horner_slp(n, prog, consts, fx);
           last_nonzero_part_pos = part_pos[i] = num_operations++;
           node_index.push_back(prog.size());
           prog.push_back(slpPRODUCT);
           prog.push_back(n - 1 - i);  // reference to (n-1-i)-th input (recall: the
                                    // order of vars is reversed in monomials)
           prog.push_back(p - part_pos[i]);  // relative position of p
         }
     }
   int c = 0;  // count nonzeros
   if (f != NULL) c++;
   for (int i = 0; i < n; i++)
     if (part_pos[i] != ZERO_CONST) c++;
   if (c == 0) return ZERO_CONST;
   if (c == 1 && last_nonzero_part_pos != ZERO_CONST)
     return last_nonzero_part_pos;
   int cur_p = num_operations++;
   node_index.push_back(prog.size());
   prog.push_back(slpMULTIsum);
   prog.push_back(c);
   if (f != NULL)
     prog.push_back(CONST_OFFSET +
                 add_constant_get_position<Field>(
                     consts, element_type(toBigComplex(C, f->coeff))));
   for (int i = 0; i < n; i++)
     if (part_pos[i] != ZERO_CONST)
       prog.push_back(part_pos[i] - cur_p);  // relative position of the i-th part
   return cur_p;
 }
References Nterm::coeff, CONST_OFFSET, extract_divisible_by_x(), p, slpMULTIsum, slpPRODUCT, toBigComplex(), and ZERO_CONST.
Referenced by SLP< Field >::make().