Macaulay2 Engine: QRingInfo_field_basic::reduce_lead_term_basic_field
reduce_lead_term_basic_field()
void QRingInfo_field_basic::reduce_lead_term_basic_field (Nterm *& f, const Nterm * g) const private
Definition at line 95 of file qring.cpp.
 {
   monomial MONOM1 = ALLOCATE_MONOMIAL(monom_size);
   const Monoid *M = R->getMonoid();
   M->divide(f->monom, g->monom, MONOM1);
   ring_elem c = R->getCoefficients()->negate(f->coeff);
   if (R->is_skew_commutative())
     {
       exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
       exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
       // We need to determine the sign
       M->to_expvector(g->monom, EXP2);
       M->to_expvector(MONOM1, EXP1);
       if (R->getSkewInfo().mult_sign(EXP1, EXP2) < 0)
         R->getCoefficients()->negate_to(c);
     }
   ring_elem g1 = const_cast<Nterm *>(g);
   g1 = R->mult_by_term(g1, c, MONOM1);
   ring_elem f1 = f;
   R->internal_add_to(f1, g1);
   f = f1;
 }
References ALLOCATE_EXPONENTS, ALLOCATE_MONOMIAL, Nterm::coeff, Monoid::divide(), QRingInfo::exp_size, PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), PolynomialRing::getSkewInfo(), PolyRing::internal_add_to(), PolynomialRing::is_skew_commutative(), Nterm::monom, QRingInfo::monom_size, PolyRing::mult_by_term(), SkewMultiplication::mult_sign(), Ring::negate(), Ring::negate_to(), QRingInfo::R, and Monoid::to_expvector().