Macaulay2 Engine: M2::ARingRRR::abs
abs()
void M2::ARingRRR::abs (ElementType & result, const ElementType & a) const inline
Definition at line 272 of file aring-RRR.hpp.
   {
     if (mpfr_cmp_si(&a, 0) < 0)
       negate(result, a);
     else
       set(result, a);
   }
References negate(), and set().
Referenced by increase_norm().