Macaulay2 Engine: M2::ARingRRR::syzygy
syzygy()
void M2::ARingRRR::syzygy (const ElementType & a, const ElementType & b, ElementType & x, ElementType & y) const inline
Definition at line 220 of file aring-RRR.hpp.
   {
     set_var(x, 0);  // set x=1
     if (!is_zero(b))
       {
         set(y, a);
         negate(y, y);
         divide(y, y, b);
       }
   }
References divide(), is_zero(), negate(), set(), set_var(), and x.