Macaulay2 Engine: M2::ARingRRR::eval
eval()
void M2::ARingRRR::eval (const RingMap * map, ElementType & f, int first_var, ring_elem & result) const inline
Definition at line 242 of file aring-RRR.hpp.
   {
     if (!map->get_ring()->from_BigReal(&f, result))
       {
         result = map->get_ring()->from_long(0);
         ERROR("cannot coerce RRR value to ring type");
       }
   }
References ERROR(), Ring::from_BigReal(), Ring::from_long(), and RingMap::get_ring().