Macaulay2 Engine: M2::ARingRRR::clear
clear()
void M2::ARingRRR::clear (ElementType & result) const inline
Definition at line 99 of file aring-RRR.hpp.
 { mpfr_clear(&result); }
Referenced by M2::ARingCCC::abs_squared(), almostEqual(), ResGausserQQHybrid::clear_element(), DMatLUinPlace< RT >::findPivot(), M2::ConcreteRing< RingType >::increase_maxnorm(), M2::ARingCCC::increase_norm(), subtract_multiple(), TEST(), testRingNegateRRi(), and testRingNegateRRR().