Macaulay2 Engine: M2::ARingRRR::set
set()
void M2::ARingRRR::set (ElementType & result, const ElementType & a) const inline
Definition at line 96 of file aring-RRR.hpp.
   {
     mpfr_set(&result, &a, MPFR_RNDN);
   }
Referenced by abs(), ResGausserQQHybrid::copy_element(), DMatLUinPlace< RT >::findPivot(), M2::ARingCCC::increase_norm(), increase_norm(), M2::mylift(), M2::mypromote(), and syzygy().