Macaulay2 Engine: M2::ARingRRR::init
init()
void M2::ARingRRR::init (ElementType & result) const inline
Definition at line 89 of file aring-RRR.hpp.
{ mpfr_init2(&result, mPrecision); }
References mPrecision.
Referenced by almostEqual(), init_set(), subtract_multiple(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), testRingNegateRRi(), and testRingNegateRRR().