Macaulay2 Engine: M2::ARingRRR::is_zero
is_zero()
bool M2::ARingRRR::is_zero (const ElementType & f) const inline
Definition at line 48 of file aring-RRR.hpp.
 { return mpfr_cmp_si(&f, 0) == 0; }
Referenced by is_unit(), M2::mylift(), syzygy(), TEST(), testRingNegateRRi(), and testRingNegateRRR().