Macaulay2 Engine: M2::ARingRRR::clear
clear()
static void M2::ARingRRR::clear (ElementType & result) inline static
Definition at line 106 of file aring-RRR.hpp.
 { mpfr_clear(&result); }
Referenced by almostEqual(), ResGausserQQHybrid::clear_element(), subtract_multiple(), TEST(), testRingNegateRRi(), and testRingNegateRRR().