Macaulay2 Engine: SchreyerOrder_symm::symm1
symm1()
void SchreyerOrder_symm::symm1 (int lastn, int pow) inline
Definition at line 260 of file schorder.cpp.
   {
     if (pow == 0)
       symm1_result->append(symm1_next++, symm1_base);
     else
       {
         for (int i = lastn; i < S->rank(); i++)
           {
             // increase symm1_base with e_i
             M->mult(symm1_base, S->base_monom(i), symm1_base);
             symm1(i, pow - 1);
             // decrease symm1_base back
             M->divide(symm1_base, S->base_monom(i), symm1_base);
           }
       }
   }
References SchreyerOrder::append(), SchreyerOrder::base_monom(), Monoid::divide(), M, Monoid::mult(), mpfr::pow(), SchreyerOrder::rank(), S, symm1_base, symm1_next, and symm1_result.
Referenced by value().