Macaulay2 Engine: SchreyerOrder_symm::value
value()
SchreyerOrder* SchreyerOrder_symm::value () inline
Definition at line 290 of file schorder.cpp.
   {
     if (symm1_result == 0)
       {
         symm1_result = SchreyerOrder::create(M);
         if (n >= 0)
           {
             symm1_base = M->make_one();
             symm1(0, n);
             M->remove(symm1_base);
           }
       }
     return symm1_result;
   }
References SchreyerOrder::create(), M, Monoid::make_one(), n, Monoid::remove(), symm1(), symm1_base, and symm1_result.
Referenced by SchreyerOrder::symm().