Macaulay2 Engine: compare
compare()
static int compare (const vecterm * t, const vecterm * s) static
Definition at line 82 of file geovec.hpp.
 {
   int cmp = t->comp - s->comp;
   if (cmp < 0) return LT;
   if (cmp > 0) return GT;
   return EQ;
 }
References vec::comp, EQ, GT, and LT.
Referenced by FreeAlgebra::addScalarMultipleOf(), vecHeap::get_lead_term(), Matrix::is_homogeneous(), PolyRing::is_homogeneous(), PolyRing::multi_degree(), binomial_ring::normalize(), Matrix::operator+(), Matrix::operator-(), ResMonoidDense::ResMonoidDense(), Ring::vec_is_homogeneous(), and Ring::vec_multi_degree().