Macaulay2 Engine: NCBasis::basis0
basis0()
void NCBasis::basis0 () private
Definition at line 113 of file matrix-ncbasis.cpp.
 {
   if (system_interrupted()) return;
   // order of events:
   // 1. check if the degree is greater than hi_degree.  If so, exit.
   // 2. check if a suffix of the current word is a pattern in the WordTable.  If so, exit.
   // 3. if the degree is >= lo_degree, then call insert.
   // 4. if the degree is equal to hi_degree, then exit (no recursion necessary)
   // 5. for each variable, append the variable to the state monomial, and make recursive call.
   Word tmpWord(mMonomial.data(),mMonomial.data() + mCurrentIndex + 1);
   int notUsed;
   if (mHiHeft != -1 and mCurrentHeftValue > mHiHeft) return;
   if (mWordTable->isSuffix(tmpWord,notUsed)) return;
   if (mCurrentHeftValue >= mLoHeft) insert();
   if (mHiHeft != -1 and mCurrentHeftValue == mHiHeft) return;
   // this ensures that we do not move past allocated memory in the loop below
   if (mMonomial.size() <= mCurrentIndex + 1) mMonomial.push_back(0);
   mCurrentIndex++;
   for (int i = 0; i < mVariables.size(); ++i)
     {
       mMonomial[mCurrentIndex] = mVariables[i];
       mCurrentHeftValue += mVariableHefts[i];
       basis0();
       mCurrentHeftValue -= mVariableHefts[i];
       if (mLimit == 0) return;
     }
   mCurrentIndex--;
 }
References insert(), mCurrentHeftValue, mCurrentIndex, mHiHeft, mLimit, mLoHeft, mMonomial, mVariableHefts, mVariables, mWordTable, and system_interrupted().
Referenced by compute().