Macaulay2 Engine: MonomialInfo::get_component
get_component()
long MonomialInfo::get_component (const_packed_monomial m) const inline
Definition at line 104 of file moninfo.hpp.
   {
     ncalls_get_component++;
     return m[1];
   }
References ncalls_get_component.
Referenced by F4SPairSet::construct_pairs(), F4MonomialLookupTableT< Key >::find_all_divisors_packed(), F4GB::insert_gb_element(), F4SPairSet::pair_not_needed(), and showAlpha().