Macaulay2 Engine: MonomialInfo::MonomialInfo
MonomialInfo()
MonomialInfo::MonomialInfo (int nvars, const MonomialOrdering * mo)
Definition at line 10 of file moninfo.cpp.
 {
   nvars = nvars0;
   hashfcn = newarray_atomic(monomial_word, nvars);
   for (int i = 0; i < nvars; i++) hashfcn[i] = rand();
   mask = 0x10000000;
   ncalls_compare = 0;
   ncalls_mult = 0;
   ncalls_get_component = 0;
   ncalls_from_expvector = 0;
   ncalls_to_expvector = 0;
   ncalls_to_varpower = 0;
   ncalls_from_varpower = 0;
   ncalls_is_equal = 0;
   ncalls_is_equal_true = 0;
   ncalls_divide = 0;
   ncalls_weight = 0;
   ncalls_unneccesary = 0;
   ncalls_quotient_as_vp = 0;
   nweights = 0;
   weight_vectors = nullptr;
   if (moIsLex(mo))
     {
       compare = &MonomialInfo::compare_lex;
       if (M2_gbTrace >= 1) fprintf(stderr, "lex order\n");
     }
   else if (moIsGRevLex(mo))
     {
       compare = &MonomialInfo::compare_grevlex;
       if (M2_gbTrace >= 1) fprintf(stderr, "grevlex order\n");
     }
   else
     {
       weight_vectors = moGetWeightValues(mo);
       nweights = weight_vectors->len / nvars;
       compare = &MonomialInfo::compare_weightvector;
       if (M2_gbTrace >= 1) fprintf(stderr, "weight order\n");
     }
   nslots = 2 + nvars + nweights;
   firstvar = 2 + nweights;
 }
References compare, compare_grevlex(), compare_lex(), compare_weightvector(), firstvar, hashfcn, M2_gbTrace, mask, moGetWeightValues(), moIsGRevLex(), moIsLex(), ncalls_compare, ncalls_divide, ncalls_from_expvector, ncalls_from_varpower, ncalls_get_component, ncalls_is_equal, ncalls_is_equal_true, ncalls_mult, ncalls_quotient_as_vp, ncalls_to_expvector, ncalls_to_varpower, ncalls_unneccesary, ncalls_weight, newarray_atomic, nslots, nvars, nweights, and weight_vectors.