Macaulay2 Engine: MonomialInfo::compare_grevlex
compare_grevlex()
int MonomialInfo::compare_grevlex (const_packed_monomial m, const_packed_monomial n) const inline
Definition at line 338 of file moninfo.hpp.
   {
     ncalls_compare++;
     const_packed_monomial m1 = m + nslots;
     const_packed_monomial n1 = n + nslots;
     for (int i = nslots - 2; i > 0; i--)
       {
         varpower_word cmp = *--m1 - *--n1;
         if (cmp < 0) return -1;
         if (cmp > 0) return 1;
       }
     monomial_word cmp = m[1] - n[1];
     if (cmp < 0) return 1;
     if (cmp > 0) return -1;
     return 0;
   }
References ncalls_compare, and nslots.
Referenced by ColumnsSorter::compare(), MonomialInfo(), and ColumnsSorter::operator()().