Macaulay2 Engine: MonomialInfo::monomial_size
monomial_size()
int MonomialInfo::monomial_size (const_packed_monomial m) const inline
Definition at line 87 of file moninfo.hpp.
 { return nslots; }
References nslots.
Referenced by F4GB::find_or_append_column(), F4toM2Interface::from_M2_vec(), F4GB::load_gen(), F4GB::load_row(), F4GB::mult_monomials(), F4toM2Interface::poly_set_degrees(), F4GB::process_column(), F4GB::process_s_pair(), show(), and F4toM2Interface::to_M2_vec().