Macaulay2 Engine: ringName
ringName()
template<typename T > std::string ringName (const T & R)
Definition at line 87 of file ARingTest.hpp.
{
  buffer o;
  R.text_out(o);
  std::string result = o.str();
  return result;
}
References buffer::str().
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().