Macaulay2 Engine: testFiniteField
testFiniteField()
template<typename T > void testFiniteField (const T & R, int ntrials)
Definition at line 413 of file ARingTest.hpp.
{
  testCoercions(R);
  testNegate(R, ntrials);
  testAdd(R, ntrials);       // fails in char 2, ffpack (negating 1 gives -1)...
  testSubtract(R, ntrials);  // fails in char 2, ffpack
  testMultiply(R, ntrials);
  testDivide(R, ntrials);  // fails in char 2, ffpack
  testReciprocal(R, ntrials);
  testPower(R, ntrials);  // fails?
  testAxioms(R, ntrials);
  // TODO: test promote, lift, syzygy(?), (ringmaps)
  // test random number generation?
  // get generator
}
References ntrials, testAdd(), testAxioms(), testCoercions(), testDivide(), testMultiply(), testNegate(), testPower(), testReciprocal(), and testSubtract().
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().