Macaulay2 Engine: testSomeMore
testSomeMore()
template<typename T > void testSomeMore (const T & R)
Definition at line 36 of file ARingTest.hpp.
{
  typename T::ElementType a, b, c, d;
  R.init(a);
  R.init(b);
  R.init(c);
  R.init(d);
  R.set_from_long(a, 27);
  R.set_from_long(b, static_cast<int>(R.characteristic()) - 11);
  R.set_from_long(c, 16);
  R.add(d, a, b);
  buffer o;
  o << "a=";
  R.elem_text_out(o, a, true);
  o << " b=";
  R.elem_text_out(o, b, true);
  o << " c=";
  R.elem_text_out(o, c, true);
  o << " d=a+b=";
  R.elem_text_out(o, d, true);
  std::cout << o.str() << std::endl;
  EXPECT_TRUE(R.is_equal(c, d));
  R.clear(a);
  R.clear(b);
  R.clear(c);
  R.clear(d);
}
References buffer::str().
Referenced by TEST(), TEST(), and TEST().