Macaulay2 Engine: testAxioms
testAxioms()
template<typename T > void testAxioms (const T & R, int ntrials)
Definition at line 150 of file ARingTest.hpp.
 {
   ARingElementGenerator<T> gen(R);
   typename T::ElementType a, b, c, d, e, f;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(d);
   R.init(e);
   R.init(f);
   for (int i = 0; i < ntrials; i++)
     {
       gen.nextElement(a);
       gen.nextElement(b);
       gen.nextElement(c);
       // Test commutativity
       // test: a*b = b*a
       // test: a+b == b+a
       R.add(d, a, b);
       R.add(e, b, a);
       EXPECT_TRUE(R.is_equal(d, e));
       R.mult(d, a, b);
       R.mult(e, b, a);
       EXPECT_TRUE(R.is_equal(d, e));
       // Test associativity
       // test: a+(b+c) == (a+b)+c
       // test: a*(b*c) == (a*b)*c
       R.add(d, b, c);
       R.add(d, a, d);
       R.add(e, a, b);
       R.add(e, e, c);
       EXPECT_TRUE(R.is_equal(d, e));
       R.mult(d, b, c);
       R.mult(d, a, d);
       R.mult(e, a, b);
       R.mult(e, e, c);
       EXPECT_TRUE(R.is_equal(d, e));
       // Test distributivity
       // test: a*(b+c) == a*b + a*c
       R.add(d, b, c);
       R.mult(d, a, d);
       R.mult(e, a, b);
       R.mult(f, a, c);
       R.add(e, e, f);
       EXPECT_TRUE(R.is_equal(d, e));
     }
   R.clear(a);
   R.clear(b);
   R.clear(c);
   R.clear(d);
   R.clear(e);
   R.clear(f);
 }
References ARingElementGenerator< RingType >::nextElement(), and ntrials.
Referenced by TEST(), and testFiniteField().