Macaulay2 Engine: testPower
testPower()
template<typename T > void testPower (const T & R, int ntrials)
Definition at line 361 of file ARingTest.hpp.
 {
   // test the following: (x=generator of the finite field, q = card of field)
   // check: x^i != x, for 2 <= i <= characteristic-??
   // x^q == x
   // x^(q-1) == 1
   // x^(-1) * x == 1
   // x^(-2) * x^2 == 1
   // a^2 == a*a, for various a
   // a^3 == a*a*a
   // a^0 == 1, what if a == 0?
   // 1^n == 1, various n
   ARingElementGenerator<T> gen(R);
   typename T::ElementType a, b, c, d, one;
   int q = static_cast<int>(R.cardinality());
   R.init(one);
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(d);
   R.set_from_long(one, 1);
   for (int i = 0; i < ntrials; i++)
     {
       gen.nextElement(a);
       gen.nextElement(b);
       R.power(c, a, q);
       EXPECT_TRUE(R.is_equal(c, a));  // test a^q == a
       if (R.is_zero(a)) continue;
       R.power(c, a, q - 1);
       EXPECT_TRUE(R.is_equal(c, one));  // test a^(q-1) == 1
       R.power(c, a, -1);  // test a^-1 * a == 1
       R.mult(c, a, c);
       EXPECT_TRUE(R.is_equal(c, one));
       R.power(c, a, -2);  // test a^-2 * a^3 == a
       R.power(d, a, 3);
       R.mult(d, c, d);
       EXPECT_TRUE(R.is_equal(d, a));
     }
   R.clear(a);
   R.clear(b);
   R.clear(c);
   R.clear(d);
   R.clear(one);
 }
References ARingElementGenerator< RingType >::nextElement(), and ntrials.
Referenced by TEST(), and testFiniteField().