Macaulay2 Engine: testMultiply
testMultiply()
template<typename T > void testMultiply (const T & R, int ntrials)
Definition at line 276 of file ARingTest.hpp.
 {
   ARingElementGenerator<T> gen(R);
   typename T::ElementType a, b, c, d, zero;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(d);
   R.init(zero);
   R.set_from_long(zero, 0);
   for (int i = 0; i < ntrials; i++)
     {
       gen.nextElement(a);
       gen.nextElement(b);
       gen.nextElement(c);
       gen.nextElement(d);
       R.mult(c, a, zero);
       EXPECT_TRUE(R.is_equal(c, zero));
       // TODO: finish this with more tests
     }
   R.clear(a);
   R.clear(b);
   R.clear(c);
   R.clear(d);
   R.clear(zero);
 }
References ARingElementGenerator< RingType >::nextElement(), ntrials, and zero.
Referenced by TEST(), and testFiniteField().