Macaulay2 Engine: res2_poly::subtract_multiple_to
subtract_multiple_to()
void res2_poly::subtract_multiple_to (res2term *& f, ring_elem c, const int * m, const res2term * g) const
Definition at line 217 of file res-a0-poly.cpp.
 {
   ring_elem minus_c = K->negate(c);
   res2term *h = mult_by_term(g, minus_c, m);
   add_to(f, h);
   K->remove(minus_c);
 }
References safe::add_to().
Referenced by res2_comp::reduce(), res2_comp::reduce2(), res2_comp::reduce_by_level(), and res2_comp::reduce_minimal().