Macaulay2 Engine: res2_poly::elem_text_out
elem_text_out() [1/2]
void res2_poly::elem_text_out (buffer & o, const res2term * f) const
Definition at line 254 of file res-a0-poly.cpp.
 {
   if (f == NULL)
     {
       o << "0";
       return;
     }
   bool p_one = false;
   bool p_parens = true;
   bool p_plus = false;
   for (const res2term *t = f; t != NULL; t = t->next)
     {
       int isone = M->is_one(t->monom);
       K->elem_text_out(o, t->coeff, p_one, p_plus, p_parens);
       if (!isone) M->elem_text_out(o, t->monom, p_one);
       o << "<" << t->comp->me << ">";
       p_plus = true;
     }
 }
References Ring::elem_text_out(), Monoid::elem_text_out(), Monoid::is_one(), K, M, and res2term::next.
Referenced by res2_comp::do_auto_reductions(), drespoly2(), elem_text_out(), res2_comp::handle_pair_by_level(), and res2_comp::text_out().