Macaulay2 Engine: res2_poly::from_vector
from_vector()
res2term * res2_poly::from_vector (const gc_vector< res2_pair * > & base, const vec v) const
Definition at line 295 of file res-a0-poly.cpp.
 {
   res2term head;
   res2term *result = &head;
   for (vecterm *w = v; w != nullptr; w = w->next)
     for (Nterm& t : w->coeff)
       {
         result->next = new_term();
         result = result->next;
         result->comp = base[w->comp];
         result->coeff = t.coeff;
         M->copy(t.monom, result->monom);
         M->mult(result->monom, result->comp->syz->monom, result->monom);
       }
   result->next = nullptr;
   // Now we must sort these
   sort(head.next);
   return head.next;
 }
References base, res2term::coeff, Nterm::coeff, res2term::comp, Monoid::copy(), M, res2term::monom, Nterm::monom, Monoid::mult(), new_term(), res2term::next, vec::next, sort(), and res2_pair::syz.
Referenced by res2_comp::new_res2_pair().