Macaulay2 Engine: res2_poly::strip
strip()
res2term * res2_poly::strip (const res2term * f) const
Definition at line 317 of file res-a0-poly.cpp.
 {
   res2term head;
   res2term *result = &head;
   for (const res2term *tm = f; tm != NULL; tm = tm->next)
     if (tm->comp->syz_type != SYZ2_NOT_MINIMAL)
       {
         result->next = new_term();
         result = result->next;
         result->comp = tm->comp;
         result->coeff = K->copy(tm->coeff);
         M->copy(tm->monom, result->monom);
       }
   result->next = NULL;
   return head.next;
 }
References res2term::coeff, res2term::comp, Ring::copy(), Monoid::copy(), K, M, res2term::monom, new_term(), res2term::next, and SYZ2_NOT_MINIMAL.
Referenced by res2_comp::make_minimal(), and res2_comp::reduce_minimal().