Macaulay2 Engine: res2_poly::new_term
new_term() [1/2]
res2term * res2_poly::new_term () const private
Definition at line 28 of file res-a0-poly.cpp.
 {
   res2term *result = reinterpret_cast<res2term *>(resterm_stash->new_elem());
   result->next = nullptr;
   return result;
 }
References stash::new_elem(), res2term::next, and resterm_stash.
Referenced by copy(), from_vector(), mult_by_coefficient(), mult_by_monomial(), mult_by_term(), res2_comp::new_base_res2_pair(), res2_comp::new_res2_pair(), res2_comp::reduce(), res2_comp::reduce2(), res2_comp::reduce3(), res2_comp::reduce4(), res2_comp::reduce_by_level(), res2_comp::reduce_heap_by_level(), ring_mult_by_term(), and strip().