Macaulay2 Engine: res2_poly::remove
remove()
void res2_poly::remove (res2term *& f) const
Definition at line 92 of file res-a0-poly.cpp.
 {
   while (f != NULL)
     {
       res2term *tmp = f;
       f = f->next;
       K->remove(tmp->coeff);
       resterm_stash->delete_elem(tmp);
     }
 }
References res2term::coeff, stash::delete_elem(), K, res2term::next, Ring::remove(), and resterm_stash.
Referenced by res2_comp::handle_pair(), res2_comp::reduce(), res2_comp::reduce3(), res2_comp::reduce4(), res2_comp::reduce_by_level(), res2_comp::reduce_heap_by_level(), and res2_comp::remove_res2_pair().