Macaulay2 Engine: res2_poly::add_to
add_to()
void res2_poly::add_to (res2term *& f, res2term *& g) const
Definition at line 150 of file res-a0-poly.cpp.
 {
   if (g == nullptr) return;
   if (f == nullptr)
     {
       f = g;
       g = nullptr;
       return;
     }
   res2term head;
   res2term *result = &head;
   while (1) switch (compare(f, g))
       {
         case -1:
           result->next = g;
           result = result->next;
           g = g->next;
           if (g == nullptr)
             {
               result->next = f;
               f = head.next;
               return;
             }
           break;
         case 1:
           result->next = f;
           result = result->next;
           f = f->next;
           if (f == nullptr)
             {
               result->next = g;
               f = head.next;
               g = nullptr;
               return;
             }
           break;
         case 0:
           res2term *tmf = f;
           res2term *tmg = g;
           f = f->next;
           g = g->next;
           K->add_to(tmf->coeff, tmg->coeff);
           if (K->is_zero(tmf->coeff))
             resterm_stash->delete_elem(tmf);
           else
             {
               result->next = tmf;
               result = result->next;
             }
           resterm_stash->delete_elem(tmg);
           if (g == nullptr)
             {
               result->next = f;
               f = head.next;
               return;
             }
           if (f == nullptr)
             {
               result->next = g;
               f = head.next;
               g = nullptr;
               return;
             }
           break;
       }
 }
References Ring::add_to(), res2term::coeff, compare(), stash::delete_elem(), Ring::is_zero(), K, res2term::next, and resterm_stash.
Referenced by res2_comp::do_auto_reductions(), res2_comp::reduce4(), res2_comp::s_pair(), and sort().