Macaulay2 Engine: res2_poly::mult_by_coefficient
mult_by_coefficient()
res2term * res2_poly::mult_by_coefficient (const res2term * f, const ring_elem c) const
Definition at line 60 of file res-a0-poly.cpp.
 {
   res2term head;
   res2term *result = &head;
   for (const res2term *tm = f; tm != NULL; tm = tm->next)
     {
       result->next = new_term();
       result = result->next;
       result->comp = tm->comp;
       result->coeff = K->mult(c, tm->coeff);
       M->copy(tm->monom, result->monom);
     }
   result->next = NULL;
   return head.next;
 }
References res2term::coeff, res2term::comp, Monoid::copy(), K, M, res2term::monom, Ring::mult(), new_term(), and res2term::next.
Referenced by res2_comp::do_auto_reductions().