Macaulay2 Engine: res2_poly::sort
sort()
void res2_poly::sort (res2term *& f) const private
Definition at line 342 of file res-a0-poly.cpp.
{
  // Divide f into two lists of equal length, sort each,
  // then add them together.  This allows the same monomial
  // to appear more than once in 'f'.
  if (f == nullptr || f->next == nullptr) return;
  res2term *f1 = nullptr;
  res2term *f2 = nullptr;
  while (f != nullptr)
    {
      res2term *t = f;
      f = f->next;
      t->next = f1;
      f1 = t;
      if (f == nullptr) break;
      t = f;
      f = f->next;
      t->next = f2;
      f2 = t;
    }
  sort(f1);
  sort(f2);
  add_to(f1, f2);
  f = f1;
}
References add_to(), res2term::next, and sort().
Referenced by from_vector(), and sort().