Macaulay2 Engine: res2_poly::make_monic
make_monic()
void res2_poly::make_monic (res2term *& f) const
Definition at line 139 of file res-a0-poly.cpp.
 {
   if (f == nullptr) return;
   ring_elem c_inv = K->invert(f->coeff);
   for (res2term *tm = f; tm != nullptr; tm = tm->next)
     K->mult_to(tm->coeff, c_inv);
   K->remove(c_inv);
 }
References res2term::coeff, Ring::invert(), K, Ring::mult_to(), res2term::next, and Ring::remove().
Referenced by res2_comp::handle_pair().