Macaulay2 Engine: res2_poly::to_vector
to_vector()
vec res2_poly::to_vector (const res2term * f, const FreeModule * F, int to_minimal = 0) const
Definition at line 275 of file res-a0-poly.cpp.
 {
   vecHeap H(F);
   monomial mon = M->make_one();
   for (const res2term *tm = f; tm != nullptr; tm = tm->next)
     {
       //    int x = (to_minimal ? tm->comp->minimal_me : tm->comp->me);
       int x = tm->comp->me;  // MES: Currently used for non-minimal as well...
       M->divide(tm->monom, tm->comp->syz->monom, mon);
       ring_elem a = R->make_flat_term(tm->coeff, mon);
       vec tmp = R->make_vec(x, a);
       H.add(tmp);
     }
   M->remove(mon);
   return H.value();
 }
References vecHeap::add(), Monoid::divide(), M, PolynomialRing::make_flat_term(), Monoid::make_one(), Ring::make_vec(), res2term::next, R, Monoid::remove(), vecHeap::value(), and x.
Referenced by res2_comp::make(), and res2_comp::make_minimal().