Macaulay2 Engine: TEST
TEST() [5/14]
TEST (RingZZ , gcd)
Definition at line 111 of file RingZZTest.cpp.
 {
   testRingGCD(globalZZ, ntrials);
   const RingZZ* R = globalZZ;
   RingElementGenerator<RingZZ> gen(*globalZZ);
   for (int i = 0; i < ntrials; i++)
     {
       ring_elem a = gen.nextElement();
       ring_elem b = gen.nextElement();
       // (a // gcd(a,b) == 0, b // gcd(a,b) == 0,
       ring_elem c = R->gcd(a, b);
       ring_elem u, v;
       ring_elem d = R->gcd_extended(a, b, u, v);
       EXPECT_TRUE(globalZZ->is_positive(c));
       EXPECT_TRUE(R->is_equal(c, d));
       EXPECT_TRUE(R->is_equal(c, R->add(R->mult(a, u), R->mult(b, v))));
       EXPECT_TRUE(R->is_equal(a, R->mult(R->divide(a, c), c)));
     }
   EXPECT_TRUE(R->is_equal(R->zero(), R->gcd(R->zero(), R->zero())));
   EXPECT_TRUE(R->is_equal(R->one(), R->gcd(R->one(), R->minus_one())));
   EXPECT_TRUE(R->is_equal(R->one(), R->gcd(R->minus_one(), R->minus_one())));
 }
References RingZZ::add(), RingZZ::divide(), RingZZ::gcd(), RingZZ::gcd_extended(), globalZZ, RingZZ::is_equal(), RingZZ::is_positive(), Ring::minus_one(), RingZZ::mult(), RingElementGenerator< RingType >::nextElement(), ntrials, Ring::one(), testRingGCD(), and Ring::zero().