Macaulay2 Engine: TEST
TEST() [4/14]
TEST (RingZZ , create)
Definition at line 23 of file RingZZTest.cpp.
 {
   EXPECT_TRUE(globalZZ != nullptr);
   EXPECT_TRUE(dynamic_cast<const RingZZ*>(globalZZ) != nullptr);
   EXPECT_EQ(globalZZ->coefficient_type(), Ring::COEFF_ZZ);
   EXPECT_TRUE(globalZZ->is_ZZ());
   EXPECT_EQ(ringName(*globalZZ), "ZZ");
 }
References Ring::COEFF_ZZ, RingZZ::coefficient_type(), globalZZ, RingZZ::is_ZZ(), and ringName().