Macaulay2 Engine: TEST
TEST() [7/14]
TEST (RingZZ , multDivide)
Definition at line 97 of file RingZZTest.cpp.
 {
   testRingDivide(globalZZ, ntrials);
   // I would prefer for 'divide' to be exact division, with a return value of
   // false, if not exactly divisible
   ring_elem a = globalZZ->from_long(5);
   ring_elem b = globalZZ->from_long(2);
   EXPECT_THROW(globalZZ->divide(a, b), exc::engine_error);
   // ring_elem c = globalZZ->divide(a, b);
   // EXPECT_ANY_THROW(globalZZ->is_equal(c, globalZZ->from_long(2)));
 }
References RingZZ::divide(), RingZZ::from_long(), globalZZ, ntrials, and testRingDivide().