Macaulay2 Engine: TEST
TEST() [9/14]
TEST (RingZZ , ones)
Definition at line 32 of file RingZZTest.cpp.
 {
   EXPECT_TRUE(globalZZ->is_equal(globalZZ->one(), globalZZ->from_long(1)));
   EXPECT_TRUE(
       globalZZ->is_equal(globalZZ->minus_one(), globalZZ->from_long(-1)));
   EXPECT_TRUE(globalZZ->is_equal(globalZZ->zero(), globalZZ->from_long(0)));
   EXPECT_TRUE(globalZZ->is_zero(globalZZ->from_long(0)));
 }
References RingZZ::from_long(), globalZZ, RingZZ::is_equal(), RingZZ::is_zero(), Ring::minus_one(), Ring::one(), and Ring::zero().