Macaulay2 Engine: TEST
TEST() [3/14]
TEST (RingZZ , content)
Definition at line 140 of file RingZZTest.cpp.
 {
   buffer o;
   ring_elem a = globalZZ->from_long(-10);
   ring_elem b = globalZZ->from_long(-15);
   ring_elem c = globalZZ->from_long(-5);
   ring_elem d = globalZZ->from_long(5);
   globalZZ->is_equal(d, globalZZ->preferred_associate(c));
   ring_elem e = globalZZ->from_long(0);
   bool ret1 = globalZZ->lower_associate_divisor(e, a);
   o << "ret1=" << (ret1 ? "true" : "false") << " e=";
   globalZZ->elem_text_out(o, e);
   o << newline;
   bool ret2 = globalZZ->lower_associate_divisor(e, b);
   o << "ret2=" << (ret2 ? "true" : "false") << " e=";
   globalZZ->elem_text_out(o, e);
   o << newline;
   std::cout << o.str();
 }
References RingZZ::elem_text_out(), RingZZ::from_long(), globalZZ, RingZZ::is_equal(), RingZZ::lower_associate_divisor(), newline, RingZZ::preferred_associate(), and buffer::str().