Macaulay2 Engine: TEST
TEST() [11/14]
TEST (RingZZ , random)
Definition at line 40 of file RingZZTest.cpp.
 {
   mpz_t b;
   mpz_init(b);
   mpz_t maxH;
   mpz_init(maxH);
   mpz_set_str(maxH, "100000000000", 10);
   for (int i = 0; i <= 10; i++)
     {
       buffer o;
       ring_elem a =
           globalZZ->random();  // POOR DESIGN!  Need to be able to choose size
       gmp_ZZ a1 = rawRandomInteger(maxH);  // This one is fine
       a = globalZZ->from_int(a1);
       globalZZ->elem_text_out(o, a);
       // std::cout << o.str() << std::endl;
       mpz_set_str(b, o.str(), 10);
       ring_elem c = globalZZ->from_int(b);
       EXPECT_TRUE(globalZZ->is_equal(a, c));
     }
   mpz_clear(maxH);
   mpz_clear(b);
 }
References RingZZ::elem_text_out(), RingZZ::from_int(), globalZZ, RingZZ::is_equal(), maxH, RingZZ::random(), rawRandomInteger(), and buffer::str().