Macaulay2 Engine: getElement< RingZZ >
getElement< RingZZ >()
template<> ring_elem getElement< RingZZ > (const RingZZ & R, int index)
Definition at line 9 of file RingZZTest.cpp.
 {
   if (index < 50) return R.from_long(index - 25);
   if (!maxH_initialized)
     {
       maxH_initialized = true;
       mpz_init(maxH);
       mpz_set_str(maxH, "100000000000", 10);
     }
   gmp_ZZ a1 = rawRandomInteger(maxH);
   return R.from_int(a1);
 }
References RingZZ::from_int(), RingZZ::from_long(), maxH, maxH_initialized, and rawRandomInteger().
Referenced by getElement< Z_mod >().