Macaulay2 Engine: exponent_table_put
exponent_table_put()
long exponent_table_put (exponent_table * E, const exponent expon, long value)
Definition at line 56 of file exptable.c.
 {
   table_nvars = E->nvars;
   return (long)Table_put(E->table, expon, (void *)value);
 }
References exponent_table::nvars, exponent_table::table, table_nvars, and Table_put().
Referenced by Matrix::coeffs(), and Matrix::monomials().