Macaulay2 Engine: TowerEvaluator::viewTerm
viewTerm()
virtual bool TowerEvaluator::viewTerm (long coeff, const_exponents exp) inline private virtual
Implements DPolyTraverser.
Definition at line 271 of file tower.cpp.
  {
    // translate exp to varpower
    // map->eval_term
    // either:
    //  H->add, or target->add_to
    vp.resize(0);
    varpower::from_expvector(nvars, exp, vp);
    ring_elem c = K->from_long(coeff);
    ring_elem a = map->eval_term(K, c, vp.data(), first_var, nvars);
    H->add(a);
    return true;
  }
References SumCollector::add(), RingMap::eval_term(), first_var, ExponentList< E, L >::from_expvector(), Ring::from_long(), H, K, map, nvars, and vp.