Macaulay2 Engine: TowerEvaluator::getValue
getValue()
ring_elem TowerEvaluator::getValue () inline
Definition at line 303 of file tower.cpp.
   {
     traverse(f);
     return H->getValue();
   }
References f, SumCollector::getValue(), H, and DPolyTraverser::traverse().
Referenced by Tower::eval().