Macaulay2 Engine: TowerEvaluator::TowerEvaluator
TowerEvaluator()
TowerEvaluator::TowerEvaluator (const Tower * T, const RingMap * map0, const ring_elem f0, int first_var0) inline
Definition at line 286 of file tower.cpp.
       : DPolyTraverser(T->D),
         map(map0),
         f(TOWER_POLYNOMIAL_VAL(f0)),
         first_var(first_var0),
         nvars(T->n_vars())
   {
     target = map->get_ring();
     H = target->make_SumCollector();
     const PolynomialRing *P = target->cast_to_PolynomialRing();
     K = (P == nullptr ? target : P->getCoefficients());
   }
References Ring::cast_to_PolynomialRing(), RingMap::get_ring(), PolynomialRing::getCoefficients(), H, K, Ring::make_SumCollector(), map, and target.