Macaulay2 Engine: TowerEvaluator::viewTerm
viewTerm()
virtual bool TowerEvaluator::viewTerm (long coeff, const exponents exp) inline private virtual
Implements DPolyTraverser.
Definition at line 271 of file tower.cpp.
   {
     // translate exp to varpower
     // map->eval_term
     // either:
     //  H->add, or target->add_to
     vp.shrink(0);
     varpower::from_ntuple(nvars, exp, vp);
     ring_elem c = K->from_long(coeff);
     ring_elem a = map->eval_term(K, c, vp.raw(), first_var, nvars);
     H->add(a);
     return true;
   }
References SumCollector::add(), RingMap::eval_term(), mpfr::exp(), first_var, Ring::from_long(), varpower::from_ntuple(), H, K, map, nvars, intarray::raw(), intarray::shrink(), and vp.