Macaulay2 Engine: RingElement::operator-
operator-() [2/2]
RingElement * RingElement::operator- (const RingElement & b) const
Definition at line 69 of file relem.cpp.
{
  if (R != b.get_ring())
    {
      ERROR(
          "ring subtraction requires both elements to have the same base ring");
      return nullptr;
    }
  ring_elem result = R->subtract(get_value(), b.get_value());
  if (error()) return nullptr;
  return new RingElement(R, result);
}
References error(), ERROR(), get_ring(), get_value(), operator-(), R, and Ring::subtract().