Macaulay2 Engine: RingElement::numerator
numerator()
RingElement * RingElement::numerator () const
Definition at line 360 of file relem.cpp.
 {
   if (R == globalQQ) return new RingElement(globalZZ, globalQQ->numerator(val));
   const FractionField *K = R->cast_to_FractionField();
   if (K != nullptr)
     return new RingElement(K->get_ring(), K->numerator(val));
   const LocalRing *L = R->cast_to_LocalRing();
   if (L != nullptr)
     return new RingElement(L->get_ring(), L->numerator(val));
   ERROR("fraction field or local ring required");
   return nullptr;
 }
References Ring::cast_to_FractionField(), Ring::cast_to_LocalRing(), ERROR(), FractionField::get_ring(), LocalRing::get_ring(), globalQQ, globalZZ, FractionField::numerator(), LocalRing::numerator(), M2::RingQQ::numerator(), R, RingElement(), and val.
Referenced by IM2_RingElement_numerator().