Macaulay2 Engine: RingElement::homogenize
homogenize() [1/2]
RingElement * RingElement::homogenize (int v, int deg, M2_arrayint wts) const
Definition at line 309 of file relem.cpp.
 {
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P == 0)
     {
       ERROR("expected polynomial ring");
       return 0;
     }
   if (v < 0 || v >= P->n_vars())
     {
       ERROR("homogenization: improper ring variable");
       return 0;
     }
   if (wts == NULL || wts->len != static_cast<unsigned int>(P->n_vars()))
     {
       ERROR("homogenization: improper weight function");
       return 0;
     }
   if (wts->array[v] == 0)
     {
       ERROR("homogenization: variable weight is zero");
       return 0;
     }
   RingElement *result = new RingElement(R, P->homogenize(val, v, deg, wts));
   if (error()) return 0;
   return result;
 }
References Ring::cast_to_PolynomialRing(), error(), ERROR(), PolynomialRing::homogenize(), PolynomialRing::n_vars(), R, RingElement(), and val.