Macaulay2 Engine: RingElement::fraction
fraction()
RingElement * RingElement::fraction (const Ring * R, const RingElement * bottom) const
Definition at line 388 of file relem.cpp.
{
  if (bottom->is_zero())
    throw exc::division_by_zero_error();
  if (K == globalQQ)
    return new RingElement(globalQQ,
                           globalQQ->fraction(val, bottom->get_value()));
  const FractionField *K1 = K->cast_to_FractionField();
  if (K1 != nullptr)
    {
      if (K1->get_ring() != R)
        {
          ERROR("fraction field required");
          return nullptr;
        }
      return new RingElement(K1, K1->fraction(val, bottom->get_value()));
    }
  const LocalRing *L1 = K->cast_to_LocalRing();
  if (L1 != nullptr)
    {
      if (L1->get_ring() != R)
        {
          ERROR("local ring required");
          return nullptr;
        }
      return new RingElement(L1, L1->fraction(val, bottom->get_value()));
    }
  ERROR("fraction field or local ring required");
  return nullptr;
}
References Ring::cast_to_FractionField(), Ring::cast_to_LocalRing(), ERROR(), fraction(), FractionField::fraction(), LocalRing::fraction(), M2::RingQQ::fraction(), FractionField::get_ring(), LocalRing::get_ring(), get_value(), globalQQ, is_zero(), R, and val.
Referenced by fraction(), and IM2_RingElement_fraction().