Macaulay2 Engine: RingElement::multi_degree
multi_degree()
M2_arrayint RingElement::multi_degree () const
Definition at line 264 of file relem.cpp.
 {
   if (is_zero())
     {
       ERROR("the zero element has no degree");
       return 0;
     }
   int *mon = newarray_atomic(int, R->degree_monoid()->monomial_size());
   R->degree(get_value(), mon);
   M2_arrayint result = R->degree_monoid()->to_arrayint(mon);
   freemem(mon);
   return result;
 }
References Ring::degree(), Ring::degree_monoid(), ERROR(), freemem(), get_value(), is_zero(), Monoid::monomial_size(), newarray_atomic, R, and Monoid::to_arrayint().
Referenced by degree_ring_elem(), and IM2_RingElement_multidegree().