Macaulay2 Engine: RingElement::operator/
operator/()
RingElement * RingElement::operator/ (const RingElement & b) const
Definition at line 105 of file relem.cpp.
 {
   if (R != b.get_ring())
     {
       ERROR("ring division requires both elements to have the same base ring");
       return nullptr;
     }
   if (b.is_zero())
     {
       ERROR("ring division: attempt to divide by zero");
       return nullptr;
     }
   ring_elem result = R->divide(get_value(), b.get_value());
   if (error()) return nullptr;
   return new RingElement(R, result);
 }
References Ring::divide(), error(), ERROR(), get_ring(), get_value(), is_zero(), R, and RingElement().