Macaulay2 Engine: RingElement::is_equal
is_equal()
bool RingElement::is_equal (const RingElement & b) const inline
Definition at line 113 of file relem.hpp.
 {
   if (this == &b) return true;
   if (get_ring() != b.get_ring())
     {
       ERROR("cannot compare ring elements from different rings");
       return false;
     }
   return get_ring()->is_equal(val, b.val);
 }
References ERROR(), get_ring(), Ring::is_equal(), and val.