Macaulay2 Engine: RingElement::homogenize
homogenize() [2/2]
RingElement * RingElement::homogenize (int v, M2_arrayint wts) const
Definition at line 280 of file relem.cpp.
 {
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("expected polynomial ring");
       return nullptr;
     }
   if (v < 0 || v >= P->n_vars())
     {
       ERROR("homogenization: improper ring variable");
       return nullptr;
     }
   if (wts == nullptr || wts->len != static_cast<unsigned int>(P->n_vars()))
     {
       ERROR("homogenization: improper weight function");
       return nullptr;
     }
   if (wts->array[v] == 0)
     {
       ERROR("homogenization: variable weight is zero");
       return nullptr;
     }
   RingElement *result = new RingElement(P, P->homogenize(val, v, wts));
   if (error()) return nullptr;
   return result;
 }
References Ring::cast_to_PolynomialRing(), error(), ERROR(), PolynomialRing::homogenize(), PolynomialRing::n_vars(), R, RingElement(), and val.
Referenced by IM2_RingElement_homogenize(), and IM2_RingElement_homogenize_to_degree().