Macaulay2 Engine: RingElement::get_ring
get_ring()
const Ring * RingElement::get_ring () const inline
Definition at line 25 of file relem.hpp.
{ return R; }
References R.
Referenced by checkGaloisFieldInput(), hilb_comp::coeff_of(), computeHashValue(), convertToFactory(), RingMap::eval(), getSmallIntegerCoefficients(), IM2_GB_set_hilbert_function(), IM2_MutableMatrix_column_2by2(), IM2_MutableMatrix_column_operation(), IM2_MutableMatrix_column_scale(), IM2_MutableMatrix_row_2by2(), IM2_MutableMatrix_row_operation(), IM2_MutableMatrix_row_scale(), IM2_MutableMatrix_set_entry(), IM2_RingElement_divmod(), IM2_RingElement_index_if_var(), IM2_RingElement_is_equal(), IM2_RingElement_is_zero(), IM2_RingElement_list_form(), IM2_RingElement_multidegree(), IM2_RingElement_ring(), IM2_RingElement_term(), IM2_RingElement_to_BigComplex(), IM2_RingElement_to_BigReal(), IM2_RingElement_to_Integer(), IM2_RingElement_to_Interval(), IM2_RingElement_to_rational(), GF::initialize_GF(), is_equal(), is_unit(), is_zero(), operator*(), operator+(), operator-(), operator/(), rawARingTower3(), rawAssociateDivisor(), rawDegree(), rawDiff(), rawDiscreteLog(), rawExtendedGCDRingElement(), rawFactorBase(), rawGCDRingElement(), rawGetPart(), rawGetParts(), rawIsLocalUnit(), rawLowerP(), rawPowerMod(), rawPseudoRemainder(), rawRingElementAntipode(), rawRingElementClean(), rawRingElementCompare(), rawRingElementCRA(), rawRingElementIndices(), rawRingElementNorm(), rawRingElementRatConversion(), rawSchurDimension(), rawSchurSnTensorMult(), rawTowerRing3(), rawTowerTranslatePoly(), gbA::set_hilbert_function(), GB_comp::set_hilbert_function(), towerExtendedGCD(), and towerGCD().