Macaulay2 Engine: RingElement::operator*
operator*() [2/2]
RingElement * RingElement::operator* (int n) const
Definition at line 96 of file relem.cpp.
{
  ring_elem nR = R->from_long(n);
  if (is_zero() || (n == 0))
    return new RingElement(R, ZERO_RINGELEM);
  else
    return new RingElement(R, R->mult(nR, get_value()));
}
References Ring::from_long(), get_value(), is_zero(), Ring::mult(), operator*(), R, and ZERO_RINGELEM.