Macaulay2 Engine: RingElement::getSmallIntegerCoefficients
getSmallIntegerCoefficients() [2/2]
bool RingElement::getSmallIntegerCoefficients (std::vector< long > & result_coeffs) const
Definition at line 454 of file relem.cpp.
 {
   const PolynomialRing *R = get_ring()->cast_to_PolynomialRing();
   if (R == 0 || R->n_vars() != 1)
     {
       throw exc::engine_error(
           "Expected a polynomial in a univariate polynomial ring");
       return false;  // Should not be needed
     }
   if (is_zero())
     {
       result_coeffs.resize(0);
       return true;
     }
   int lo, deg;  // ignore lo, and deg == degree of the univariate polynomial f.
   R->degree_of_var(0, get_value(), lo, deg);
   result_coeffs.resize(deg + 1);
   for (int i = 0; i <= deg; i++) result_coeffs[i] = 0;
   int exp[1];
   for (Nterm *t = get_value(); t != NULL; t = t->next)
     {
       std::pair<bool, long> res =
           R->getCoefficientRing()->coerceToLongInteger(t->coeff);
       if (not res.first)
         {
           // At this point, the answer is meaningless
           result_coeffs.resize(0);
           return false;
         }
       long coeff = res.second;
       R->getMonoid()->to_expvector(t->monom, exp);
       assert(exp[0] >= 0);
       assert(exp[0] <= deg);
       result_coeffs[exp[0]] = coeff;
     }
   return true;
 }
References Ring::cast_to_PolynomialRing(), Ring::coerceToLongInteger(), Ring::degree_of_var(), mpfr::exp(), get_ring(), get_value(), is_zero(), and R.
Referenced by M2::ARingGFFlint::ARingGFFlint(), M2::ARingGFFlintBig::ARingGFFlintBig(), getGFRepresentation(), M2::ARingGFM2::promote(), M2::ARingGFFlintBig::promote(), and M2::ARingGFFlint::promote().