Macaulay2 Engine: RingElement::lift
lift()
bool RingElement::lift (const Ring * S, const RingElement *& result) const
Definition at line 321 of file relem.cpp.
 {
   if (S == R)
     {
       result = this;
       return true;
     }
   ring_elem g;
   if (R->lift(S, val, g))
     {
       result = new RingElement(S, g);
       return true;
     }
   return false;
 }
References Ring::lift(), R, RingElement(), and val.
Referenced by IM2_RingElement_lift().