Macaulay2 Engine: RingElement::power
power() [2/2]
RingElement * RingElement::power (mpz_srcptr n) const
Definition at line 130 of file relem.cpp.
 {
   ring_elem f = R->power(val, n);
   if (error()) return 0;
   return new RingElement(R, f);
 }
References error(), Ring::power(), R, RingElement(), and val.