Macaulay2 Engine: RingElement::lead_monom
lead_monom()
Monomial * RingElement::lead_monom (int nvars) const
Definition at line 197 of file relem.cpp.
 {
   if (is_zero())
     {
       ERROR("the zero element has no lead monomial");
       return nullptr;
     }
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P != nullptr)
     {
       intarray resultvp;
       Nterm *t = get_value();
       int *exp = newarray_atomic(int, nvars);
       P->lead_logical_exponents(nvars, t, exp);
       varpower::from_ntuple(nvars, exp, resultvp);
       return Monomial::make(resultvp.raw());
     }
   const M2FreeAlgebraOrQuotient* Q = dynamic_cast<const M2FreeAlgebraOrQuotient*>(R);
   if (Q != nullptr)
     {
       ERROR("not implemented yet");
       return nullptr;
     }
   ERROR("expected polynomial ring");
   return nullptr;
 }
References Ring::cast_to_PolynomialRing(), ERROR(), mpfr::exp(), varpower::from_ntuple(), get_value(), is_zero(), PolynomialRing::lead_logical_exponents(), Monomial::make(), newarray_atomic, R, and intarray::raw().
Referenced by IM2_RingElement_lead_monomial().