Macaulay2 Engine: RingElement::remove_content
remove_content()
const RingElement * RingElement::remove_content () const
Definition at line 345 of file relem.cpp.
 {
   ring_elem g = R->divide_by_content(val);
   return new RingElement(R, g);
 }
References Ring::divide_by_content(), R, RingElement(), and val.
Referenced by rawRingElementRemoveContent().