Macaulay2 Engine: RingElement::get_coeff
get_coeff()
RingElement * RingElement::get_coeff (const Ring * coeffR, const EngineMonomial * m) const
Definition at line 185 of file relem.cpp.
 {
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("expected polynomial ring");
       return nullptr;
     }
   return new RingElement(coeffR, P->get_coeff(coeffR, get_value(), m->ints()));
 }
References Ring::cast_to_PolynomialRing(), ERROR(), PolynomialRing::get_coeff(), get_value(), EngineMonomial::ints(), R, and RingElement().
Referenced by IM2_RingElement_get_coeff().