Macaulay2 Engine: RingElement::denominator
denominator()
RingElement * RingElement::denominator () const
Definition at line 374 of file relem.cpp.
{
  if (R == globalQQ)
    return new RingElement(globalZZ, globalQQ->denominator(val));
  const FractionField *K = R->cast_to_FractionField();
  if (K != nullptr)
    return new RingElement(K->get_ring(), K->denominator(val));
  const LocalRing *L = R->cast_to_LocalRing();
  if (L != nullptr)
    return new RingElement(L->get_ring(), L->denominator(val));
  ERROR("fraction field or local rings required");
  return nullptr;
}
References Ring::cast_to_FractionField(), Ring::cast_to_LocalRing(), denominator(), FractionField::denominator(), LocalRing::denominator(), M2::RingQQ::denominator(), ERROR(), FractionField::get_ring(), LocalRing::get_ring(), globalQQ, globalZZ, R, and val.
Referenced by denominator(), and IM2_RingElement_denominator().