Macaulay2 Engine: RingElement::RingElement
RingElement()
RingElement::RingElement (const Ring * R, ring_elem f) inline
Definition at line 110 of file relem.hpp.
 : R(R0), val(f) {}
Referenced by content(), denominator(), fraction(), get_coeff(), get_terms(), homogenize(), invert(), lead_coeff(), lift(), make_raw(), numerator(), operator*(), operator+(), operator-(), operator/(), power(), promote(), random(), remove_content(), and split_off_content().