Macaulay2 Engine: RingElement::random
random()
RingElement * RingElement::random (const Ring * R) static
Definition at line 137 of file relem.cpp.
{
  return new RingElement(R, R->random());
}
References R, Ring::random(), and random().
Referenced by random().