Macaulay2 Engine: RingElement::text_out
text_out()
void RingElement::text_out (buffer & o) const
Definition at line 142 of file relem.cpp.
{
  R->elem_text_out(o, val);
}
References Ring::elem_text_out(), R, text_out(), and val.
Referenced by drelem(), IM2_RingElement_to_string(), FractionField::simplify(), LocalRing::simplify(), and text_out().