Macaulay2 Engine: RingElement::homogenize
homogenize() [1/2]
RingElement * RingElement::homogenize (int v, const std::vector< int > & wts) const
Definition at line 245 of file relem.cpp.
{
  const PolynomialRing *P = R->cast_to_PolynomialRing();
  if (P == nullptr)
    {
      ERROR("expected polynomial ring");
      return nullptr;
    }
  if (v < 0 || v >= P->n_vars())
    {
      ERROR("homogenization: improper ring variable");
      return nullptr;
    }
  if (wts.size() == 0 || wts.size() != static_cast<unsigned int>(P->n_vars()))
    {
      ERROR("homogenization: improper weight function");
      return nullptr;
    }
  if (wts[v] == 0)
    {
      ERROR("homogenization: variable weight is zero");
      return nullptr;
    }
  RingElement *result = new RingElement(P, P->homogenize(val, v, wts));
  if (error()) return nullptr;
  return result;
}
References Ring::cast_to_PolynomialRing(), error(), ERROR(), PolynomialRing::homogenize(), homogenize(), PolynomialRing::n_vars(), R, and val.
Referenced by homogenize(), homogenize(), IM2_RingElement_homogenize(), and IM2_RingElement_homogenize_to_degree().