Macaulay2 Engine: RingElement::lead_coeff
lead_coeff()
RingElement * RingElement::lead_coeff (const Ring * coeffR) const
Definition at line 165 of file relem.cpp.
 {
   if (is_zero())
     {
       return new RingElement(coeffR, coeffR->zero());
     }
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P != nullptr)
     {
       return new RingElement(coeffR, P->lead_logical_coeff(coeffR, val));
     }
   const M2FreeAlgebra* A = dynamic_cast<const M2FreeAlgebra*>(R);
   if (A != nullptr)
     {
       return new RingElement(coeffR, A->lead_coefficient(coeffR, val));
     }
   ERROR("expected polynomial ring");
   return nullptr;
 }
References Ring::cast_to_PolynomialRing(), ERROR(), is_zero(), M2FreeAlgebra::lead_coefficient(), PolynomialRing::lead_logical_coeff(), R, RingElement(), val, and Ring::zero().
Referenced by IM2_RingElement_lead_coeff().