Macaulay2 Engine: RingElement::get_terms
get_terms()
RingElement * RingElement::get_terms (int nvars, int lo, int hi) const
Definition at line 147 of file relem.cpp.
 {
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P != nullptr)
     {
       return new RingElement(P, P->get_terms(nvars, val, lo, hi));
     }
   const M2FreeAlgebra* A = dynamic_cast<const M2FreeAlgebra*>(R);
   if (A != nullptr)
     {
       return new RingElement(A, A->get_terms(val, lo, hi));
     }
   ERROR("expected polynomial ring");
   return nullptr;
 }
References Ring::cast_to_PolynomialRing(), ERROR(), M2FreeAlgebra::get_terms(), PolynomialRing::get_terms(), R, RingElement(), and val.
Referenced by IM2_RingElement_get_terms().