Macaulay2 Engine: RingElement::n_terms
n_terms()
int RingElement::n_terms (int nvars) const
Definition at line 25 of file relem.cpp.
 {
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (is_zero()) return 0;
   if (P != nullptr)
     {
       return P->n_logical_terms(nvars, val);
     }
   auto Q = dynamic_cast<const M2FreeAlgebra *>(R);
   if (Q != nullptr)
     {
       return Q->n_terms(val);
     }
   return 1;
 }
References Ring::cast_to_PolynomialRing(), is_zero(), PolynomialRing::n_logical_terms(), M2FreeAlgebra::n_terms(), R, and val.
Referenced by IM2_RingElement_n_terms().