Macaulay2 Engine: RingElement::lead_monom
lead_monom()
EngineMonomial * RingElement::lead_monom (int nvars) const
Definition at line 197 of file relem.cpp.
 {
   if (is_zero())
     {
       ERROR("the zero element has no lead monomial");
       return nullptr;
     }
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P != nullptr)
     {
       gc_vector<int> resultvp;
       Nterm *t = get_value();
       exponents_t exp = newarray_atomic(int, nvars);
       P->lead_logical_exponents(nvars, t, exp);
       varpower::from_expvector(nvars, exp, resultvp);
       return EngineMonomial::make(resultvp.data());
     }
   const M2FreeAlgebraOrQuotient* Q = dynamic_cast<const M2FreeAlgebraOrQuotient*>(R);
   if (Q != nullptr)
     {
       ERROR("not implemented yet");
       return nullptr;
     }
   ERROR("expected polynomial ring");
   return nullptr;
 }
References Ring::cast_to_PolynomialRing(), ERROR(), mpfr::exp(), ExponentList< E, L >::from_expvector(), get_value(), is_zero(), PolynomialRing::lead_logical_exponents(), EngineMonomial::make(), newarray_atomic, and R.
Referenced by IM2_RingElement_lead_monomial().