Macaulay2 Engine: RingElement::make_raw
make_raw()
RingElement * RingElement::make_raw (const Ring * R, ring_elem f) static
Definition at line 20 of file relem.cpp.
 {
   return new RingElement(R, f);
 }
References R, and RingElement().
Referenced by M2::ARingGFFlint::ARingGFFlint(), M2::ARingGFFlintBig::ARingGFFlintBig(), convertRingelemsToArray(), convertToM2(), degree_ring_elem(), MutableMat< Mat >::determinant(), RingMap::eval(), M2::findMinimalPolynomial(), M2::GaloisFieldTable::GaloisFieldTable(), M2::getGen(), GF::getGenerator(), M2::getLiftedRepresentation(), GF::getMinimalPolynomial(), GF::getRepresentation(), IM2_Matrix_dot_product(), IM2_Matrix_get_entry(), IM2_MutableMatrix_get_entry(), IM2_RingElement_divmod(), IM2_RingElement_from_BigComplex(), IM2_RingElement_from_BigReal(), IM2_RingElement_from_Integer(), IM2_RingElement_from_Interval(), IM2_RingElement_from_rational(), IM2_RingElement_make_var(), IM2_RingElement_term(), PolyRingQuotient::invert(), LocalRing::lift_up(), M2FreeAlgebra::list_form(), PolyRing::list_form(), SchurRing2::list_form(), FractionField::lower_content(), LocalRing::lower_content(), rawAssociateDivisor(), rawCharSeries(), rawConvolve(), rawDiff(), rawExtendedGCDRingElement(), rawFactorBase(), rawGCDRingElement(), rawGetNonUnit(), rawGetPart(), rawGetParts(), rawIdealReorder(), rawLowerP(), rawPowerMod(), rawRingElementAntipode(), rawRingElementClean(), rawRingElementCRA(), rawRingElementRatConversion(), rawRoots(), rawSchurFromPartition(), rawSchurSnTensorMult(), rawTowerTranslatePoly(), gbA::set_hilbert_function(), GB_comp::set_hilbert_function(), FractionField::simplify(), LocalRing::simplify(), towerExtendedGCD(), towerGCD(), and hilb_comp::value().