Macaulay2 Engine: RingElement::is_zero
is_zero()
bool RingElement::is_zero () const inline
Definition at line 111 of file relem.hpp.
 { return get_ring()->is_zero(val); }
References get_ring(), Ring::is_zero(), and val.
Referenced by degree_weights(), fraction(), getSmallIntegerCoefficients(), invert(), lead_coeff(), lead_monom(), multi_degree(), n_terms(), operator*(), operator/(), rawExtendedGCDRingElement(), and rawGCDRingElement().