Macaulay2 Engine: RingElement::operator+
operator+()
RingElement * RingElement::operator+ (const RingElement & b) const
Definition at line 57 of file relem.cpp.
 {
   if (R != b.get_ring())
     {
       ERROR("ring addition requires both elements to have the same base ring");
       return nullptr;
     }
   ring_elem result = R->add(get_value(), b.get_value());
   if (error()) return nullptr;
   return new RingElement(R, result);
 }
References Ring::add(), error(), ERROR(), get_ring(), get_value(), R, and RingElement().