Macaulay2 Engine: RingElement::get_value
get_value()
ring_elem RingElement::get_value () const inline
Definition at line 23 of file relem.hpp.
{ return val; }
References val.
Referenced by hilb_comp::coeff_of(), computeHashValue(), convertToFactory(), convertToM2(), GF::elem_text_out(), RingMap::eval(), fraction(), get_coeff(), GF::getRepresentation(), getSmallIntegerCoefficients(), IM2_MutableMatrix_column_2by2(), IM2_MutableMatrix_column_operation(), IM2_MutableMatrix_column_scale(), IM2_MutableMatrix_row_2by2(), IM2_MutableMatrix_row_operation(), IM2_MutableMatrix_row_scale(), IM2_MutableMatrix_set_entry(), IM2_RingElement_divmod(), IM2_RingElement_index_if_var(), IM2_RingElement_is_equal(), IM2_RingElement_is_zero(), IM2_RingElement_list_form(), IM2_RingElement_term(), IM2_RingElement_to_BigComplex(), IM2_RingElement_to_BigReal(), IM2_RingElement_to_Integer(), IM2_RingElement_to_Interval(), IM2_RingElement_to_rational(), GF::initialize_GF(), PolyRingQuotient::invert(), lead_monom(), GF::lift(), LocalRing::lift_up(), FractionField::lower_content(), LocalRing::lower_content(), operator*(), operator*(), operator+(), operator-(), operator/(), rawARingGaloisField1(), rawARingGaloisFieldFlintBig(), rawARingGaloisFieldFlintZech(), rawARingTower3(), rawAssociateDivisor(), rawDegree(), rawDiff(), rawDiscreteLog(), rawGCDRingElement(), rawGetPart(), rawGetParts(), rawIsLocalUnit(), rawLowerP(), rawPowerMod(), rawRingElementAntipode(), rawRingElementClean(), rawRingElementCompare(), rawRingElementCRA(), rawRingElementIndices(), rawRingElementNorm(), rawRingElementRatConversion(), rawSchurDimension(), rawSchurSnTensorMult(), rawTowerRing3(), rawTowerTranslatePoly(), FractionField::simplify(), LocalRing::simplify(), towerExtendedGCD(), and towerGCD().