Macaulay2 Engine: all_have_pure_powers
all_have_pure_powers()
static bool all_have_pure_powers (const MonomialIdeal * M, std::vector< int > varlist) static
Definition at line 351 of file matrix-kbasis.cpp.
 {
   // returns true iff all the variables in varlist have some pure power in M
   std::vector<int> lcms = M2_arrayint_to_stdvector<int>(M->lcm());
   exponents_t exp = ALLOCATE_EXPONENTS(EXPONENT_BYTE_SIZE(lcms.size()));
   for (int i = 0; i < lcms.size(); i++) exp[i] = 0;
   for (int i = 0; i < varlist.size(); i++)
     {
       Bag *b;
       int v = varlist[i];
       exp[v] = lcms[v];
       if (!M->search_expvector(exp, b)) return false;
       exp[v] = 0;
     }
   return true;
 }
References ALLOCATE_EXPONENTS, mpfr::exp(), EXPONENT_BYTE_SIZE, MonomialIdeal::lcm(), and MonomialIdeal::search_expvector().
Referenced by KBasis::compute().