Macaulay2 Engine: std::swap
swap()
template<> void std::swap (mpfr::mpreal & x, mpfr::mpreal & y) inline
Definition at line 3219 of file mpreal.h.
    {
        return mpfr::swap(x, y);
    }
References x.
Referenced by FreeAlgebraHeap::add(), TrivialPolynomialHeap::addPolynomial(), TrivialPolynomialHeap::addPolynomial(), DetComputation::calc_det(), PfaffianComputation::calc_pfaff(), newf4::MonomialHashTable::grow(), SchreyerFrame::insertLevelOne(), MatrixOps::LUincremental(), F4Res::makeMatrix(), ncBasis(), ffpackInterface::nullSpace(), F4GB::reorder_columns(), F4GB::reorder_rows(), F4Res::reorderColumns(), ResPolynomialConstructor::setPoly(), ResPolynomialConstructor::setPolyFromArrays(), BettiDisplay::swap(), DMat< M2::ARingGFFlintBig >::swap(), DMat< M2::ARingGFFlint >::swap(), DMat< M2::ARingQQFlint >::swap(), DMat< M2::ARingZZ >::swap(), DMat< M2::ARingZZpFlint >::swap(), DMat< ACoeffRing >::swap(), ElementArray::swap(), M2::ARingCC::swap(), M2::ARingRR::swap(), FreeAlgebra::swap(), and FreeAlgebraHeap::value().