Macaulay2 Engine: GBRingPoly::mult_by_term1
mult_by_term1()
gbvector * GBRingPoly::mult_by_term1 (const FreeModule * F, const gbvector * f, ring_elem u, const int * monom, int comp) virtual
Implements GBRing.
Definition at line 98 of file gbring.cpp.
 {
   // Remember: this multiplies w/o regard to any quotient elements
   gbvector head;
   gbvector *inresult = &head;
   int monlen = M->monomial_size();
   for (const gbvector *s = f; s != NULL; s = s->next)
     {
       gbvector *t = new_raw_term();
       t->next = 0;
       t->comp = s->comp + comp;
       t->coeff = K->mult(u, s->coeff);
       exponents::mult(monlen, monom, s->monom, t->monom);
       inresult->next = t;
       inresult = inresult->next;
     }
   inresult->next = 0;
   return head.next;
 }
References gbvector::coeff, gbvector::comp, GBRing::K, GBRing::M, gbvector::monom, Monoid::monomial_size(), Ring::mult(), ExponentVector< E, OC >::mult(), GBRing::new_raw_term(), and gbvector::next.