Macaulay2 Engine: towerExtendedGCD
towerExtendedGCD()
const RingElement * towerExtendedGCD (const RingElement * F, const RingElement * G, const RingElement ** A, const RingElement ** B) extern
Definition at line 419 of file tower.cpp.
{
  const Tower *R = F->get_ring()->cast_to_Tower();
  const Tower *S = G->get_ring()->cast_to_Tower();
  if (R == nullptr || R != S)
    {
      ERROR("encountered different rings");
    }
  ring_elem u, v;
  ring_elem result = R->gcd_extended(F->get_value(), G->get_value(), u, v);
  *A = RingElement::make_raw(R, u);
  *B = RingElement::make_raw(R, v);
  return RingElement::make_raw(R, result);
}
References Tower::cast_to_Tower(), Ring::cast_to_Tower(), ERROR(), G, Tower::gcd_extended(), RingElement::get_ring(), and RingElement::get_value().
Referenced by rawExtendedGCDRingElement().