Macaulay2 Engine: towerExtendedGCD
towerExtendedGCD()
const RingElement* towerExtendedGCD (const RingElement * F, const RingElement * G, const RingElement ** A, const RingElement ** B)
Definition at line 419 of file tower.cpp.
 {
   const Tower *R = F->get_ring()->cast_to_Tower();
   const Tower *S = G->get_ring()->cast_to_Tower();
   if (R == 0 || R != S)
     {
       ERROR("encountered different rings");
     }
   ring_elem u, v;
   ring_elem result = R->gcd_extended(F->get_value(), G->get_value(), u, v);
   *A = RingElement::make_raw(R, u);
   *B = RingElement::make_raw(R, v);
   return RingElement::make_raw(R, result);
 }
References Ring::cast_to_Tower(), ERROR(), Tower::gcd_extended(), RingElement::get_ring(), RingElement::get_value(), and RingElement::make_raw().
Referenced by rawExtendedGCDRingElement().