Macaulay2 Engine: QRingInfo_field_QQ::gbvector_normal_form
gbvector_normal_form() [1/2]
void QRingInfo_field_QQ::gbvector_normal_form (const FreeModule * F, gbvector *& f) const virtual
Reimplemented from QRingInfo.
Definition at line 244 of file qring.cpp.
 {
   exponents EXP1 = ALLOCATE_EXPONENTS(exp_size);
   GBRing *GR = R->get_gb_ring();
   gbvector head;
   gbvector *result = &head;
   result->next = NULL;
   gbvector *t = f;
   while (t != NULL)
     {
       GR->gbvector_get_lead_exponents(F, t, EXP1);
       int x = ringtable->find_divisor(EXP1, 1);
       if (x >= 0)
         {
           const gbvector *r = quotient_gbvector(x);
           gbvector *zero = 0;
           GR->gbvector_reduce_lead_term(F, F, head.next, t, zero, r, zero);
         }
       else
         {
           result->next = t;
           t = t->next;
           result = result->next;
           result->next = NULL;
         }
     }
   f = head.next;
 }
References ALLOCATE_EXPONENTS, QRingInfo::exp_size, MonomialTable::find_divisor(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_reduce_lead_term(), PolynomialRing::get_gb_ring(), gbvector::next, QRingInfo::quotient_gbvector(), QRingInfo::R, QRingInfo_field::ringtable, x, and zero.