Macaulay2 Engine: BRP::reduceTail
reduceTail()
bool BRP::reduceTail (const BRP & g)
Definition at line 159 of file franzi-brp.cpp.
 {
   // cout << "reduceTail: this = " << (*this) << ", by g = " << g << endl;
   //  if ( (*this) == 0 ) {
   //    cerr << "Called reduceTail on 0 brp" << endl;
   //    return false;
   //  }
   brMonomial lt = g.LT();
   bool ret = false;
   monomials::iterator it = m.begin();
   ++it;  // really only reduce tail
   monomials::iterator end = m.end();
   for (; it != end;)
     {
       brMonomial mono = *it;
       if (isDivisibleBy(mono, lt))
         {
           // cout << mono << " is divisible by " << lt << endl;
           addition(g * (mono ^ lt), it--);
           // cout << *this << endl;
           ++it;
           ret = true;
         }
       if (lt > mono)
         {  // stop iterating because smaller are never divisible by larger
           return ret;
         }
       ++it;
     }
   // cout << "at the end of reduceTail, this = " << (*this) << endl;
   return ret;
 }
References addition(), end(), isDivisibleBy(), LT(), and m.
Referenced by reduceTail().