Macaulay2 Engine: BRP::isLeadingReducibleBy
isLeadingReducibleBy() [2/2]
bool BRP::isLeadingReducibleBy (const BRP & other) const
Definition at line 125 of file franzi-brp.cpp.
 {
   //  if ( (*this) == 0 ) cout << "This is 0 " << endl;
   //  if ( other == 0 ) cout << "Other is 0 " << endl;
   return isDivisibleBy(LT(), other.LT());
 }
References isDivisibleBy(), and LT().
Referenced by findDivisor(), and testIsLeadingReducibleBy().