Macaulay2 Engine: BRP::remainder
remainder()
BRP BRP::remainder (const BRP & x) const
Definition at line 138 of file franzi-brp.cpp.
 {
   monomials tmp;
   monomials::const_iterator end = m.end();
   brMonomial xx = x.LT();
   for (monomials::const_iterator it = m.begin(); it != end; it++)
     {
       brMonomial mono = *it;
       if (!isDivisibleBy(mono, xx))
         {
           tmp.push_back(mono);  // don't remove doubles, there shouldn't be any
         }
     }
   return BRP(tmp);
 }
References BRP(), end(), isDivisibleBy(), m, and x.
Referenced by testRemainder().