Macaulay2 Engine: BRP::LT
LT()
brMonomial BRP::LT () const inline
Definition at line 77 of file franzi-brp.hpp.
   {
     //    if ( (*this) == 0 ) {
     //      cerr << "ERROR, calling LT on 0" << endl;
     //      throw "calling LT on 0 polynomial";
     //    }
     return *(m.begin());
   }  // Leading Term
References m.
Referenced by cancelLeadTerm(), isGoodPair(), isLeadingReducibleBy(), reduceTail(), sPolynomial(), testIsRelativelyPrime(), and testLT().