Macaulay2 Engine: BRP::isDivisibleBy
isDivisibleBy()
static bool BRP::isDivisibleBy (const brMonomial & a, const brMonomial & b) inline static
Definition at line 42 of file franzi-brp.hpp.
   {
     // check if a is divisible by b
     brMonomial lcm = a | b;
     return lcm == a;
   }
Referenced by isGoodPair(), isLeadingReducibleBy(), reduceTail(), remainder(), and testDivide().