Macaulay2 Engine: M2::GaloisFieldTable::GaloisFieldTable
GaloisFieldTable()
M2::GaloisFieldTable::GaloisFieldTable (const PolynomialRing & R, const ring_elem prim)
R should be the ring of the element prim. preferably, prim is the generator of R, but it is allowed to be something else as well.
Definition at line 18 of file aring-m2-gf.cpp.
     : mCharac(static_cast<int>(R.characteristic())),
       mOriginalRing(R),
       mPrimitiveElement(prim)
 {
   assert(mOriginalRing.n_quotients() == 1);
   mGenerator = RingElement::make_raw(&R, R.copy(prim));
   ring_elem f = mOriginalRing.quotient_element(0);
   Nterm *t = f;
   mDimension = mOriginalRing.getMonoid()->primary_degree(t->monom);
   mOrder = mCharac;
   for (int i = 1; i < mDimension; i++) mOrder *= mCharac;
   mOne = mOrder - 1;      // representation for the number 1: p^n - 1.
   mOrderMinusOne = mOne;  // p^n - 1
   mMinusOne = (mCharac == 2 ? mOne : mOne / 2);
   // Get ready to create mOneTable.
   VECTOR(ring_elem) polys;
   polys.push_back(mOriginalRing.from_long(0));
   polys.push_back(mOriginalRing.copy(mPrimitiveElement));
   ring_elem oneR = mOriginalRing.from_long(1);
   mGeneratorExponent = static_cast<GFElement>(-1);
   ring_elem x = mOriginalRing.var(0);
   if (mOriginalRing.is_equal(mPrimitiveElement, x)) mGeneratorExponent = 1;
   for (GFElement i = 2; i <= mOne; i++)
     {
       ring_elem g = mOriginalRing.mult(polys[i - 1], mPrimitiveElement);
       polys.push_back(g);
       if (mOriginalRing.is_equal(g, oneR)) break;
       if (mOriginalRing.is_equal(g, x)) mGeneratorExponent = i;
     }
 #if 0
     for (size_t i = 0; i < polys.size(); i++)
       {
         std::cerr << i << "  ";
         dringelem(&R, polys[i]);
         std::cerr << "\n";
       }
 #endif
   assert(polys.size() == mOrder);
   assert(mGeneratorExponent != static_cast<GFElement>(-1));
   // Set 'one_table'.
   mOneTable = newarray_atomic(GFElement, mOrder);
   mOneTable[0] = mOrderMinusOne;
   for (GFElement i = 1; i <= mOrderMinusOne; i++)
     {
       if (system_interrupted())
         {
           // first clean up?
           return;
         }
       ring_elem f1 = mOriginalRing.add(polys[i], oneR);
       GFElement j;
       for (j = 0; j <= mOrderMinusOne; j++)
         if (mOriginalRing.is_equal(f1, polys[j])) break;
       if (j > mOrderMinusOne)
         {
           std::cout << "oops: didn't find element " << i << " !!" << std::endl;
         }
       mOneTable[i] = j;
     }
   // Create the ZZ/P ---> GF(Q) inclusion map
   mFromIntTable = newarray_atomic(GFElement, mCharac);
   GFElement a = mOne;
   ;
   mFromIntTable[0] = 0;
   for (GFElement i = 1; i < mCharac; i++)
     {
       mFromIntTable[i] = a;
       a = mOneTable[a];
     }
 }
References Ring::add(), Ring::copy(), dringelem(), Ring::from_long(), PolynomialRing::getMonoid(), Ring::is_equal(), RingElement::make_raw(), mCharac, mDimension, mFromIntTable, mGenerator, mGeneratorExponent, mMinusOne, mOne, mOneTable, Nterm::monom, mOrder, mOrderMinusOne, mOriginalRing, mPrimitiveElement, Ring::mult(), PolynomialRing::n_quotients(), newarray_atomic, Monoid::primary_degree(), PolynomialRing::quotient_element(), system_interrupted(), PolynomialRing::var(), VECTOR(), and x.