Macaulay2 Engine: M2::GaloisFieldTable::one
one()
GFElement M2::GaloisFieldTable::one () const inline
Definition at line 44 of file aring-m2-gf.hpp.
 { return mOne; }
References mOne.
Referenced by M2::ARingGFM2::add(), M2::ARingGFM2::invert(), M2::ARingGFM2::lift_to_original_ring(), M2::ARingGFM2::power(), M2::ARingGFM2::power_mpz(), and M2::ARingGFM2::syzygy().