Macaulay2 Engine: getmem
getmem()
char* getmem (size_t n)
Definition at line 44 of file M2mem-replacement.c.
 {
   char *p;
   p = GC_MALLOC(n);     /* GC_MALLOC clears its memory, but getmem doesn't guarantee to */
   if (p == NULL) outofmem2(n);
 #ifndef NDEBUG
   memset(p,0xbe,n);     /* fill with 0xbebebebe ... */
   trapchk(p);
 #endif
   return p;
 }
References outofmem2(), p, and trapchk().
Referenced by monomialOrderMake(), our_new_delete::operator new(), our_new_delete::operator new[](), Table_new(), and Table_toArray().