Macaulay2 Engine: freemem
freemem()
void freemem (void * s)
Definition at line 63 of file M2mem-replacement.c.
                       {
 #    ifndef NDEBUG
      trapchk(s);
 #    endif
      GC_FREE(s);
 }
References trapchk().
Referenced by MinimalPrimes::alg1_min_primes(), res2_comp::betti_minimal(), gbres_comp::betti_minimal(), res2_comp::betti_nmonoms(), res2_comp::betti_remaining(), bignum_text_out(), MonomialIdeal::borel(), BRPSfromMatrix(), BRPStoMatrix(), hilb_comp::coeff_of(), coeffs_of_vec(), DMatLinAlg< M2::ARingZZpFlint >::columnRankProfile(), DMatLUinPlace< RT >::computeLU(), cond_number_via_svd(), SchreyerOrder::create(), DPoly::dealloc_poly(), F4Vec::deallocate(), F4Mem::deallocate_monomial_array(), PolyRing::degree_of_var(), stash::delete_elem(), Matrix::diff(), Matrix::dimension1(), PolyRing::divide_by_expvector(), PolyRing::divide_by_var(), res2_comp::do_auto_reductions(), Lapack::eigenvalues(), Lapack::eigenvalues_hermitian(), Lapack::eigenvalues_symmetric(), Lapack::eigenvectors(), Lapack::eigenvectors_hermitian(), Lapack::eigenvectors_symmetric(), M2::ARingQQFlint::elem_text_out(), M2::ARingQQGMP::elem_text_out(), RingZZ::elem_text_out(), binomialGB_comp::enlarge(), PathTracker::evaluate_slpHxt(), buffer::expand(), GBRing::exponents_delete(), Matrix::exterior(), BIBasis::BooleanInvolutiveBasis< MonomType >::FillInitialSet(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), FrobbyAlexanderDual(), GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), WeylAlgebra::gbvector_mult_by_term(), WeylAlgebra::gbvector_weyl_diff(), res_comp::get_betti(), PolyRing::get_coeff(), PolyRing::get_part(), PolyRing::homogenize(), binomialGB::ideal_quotient(), DPoly::increase_size_0(), DPoly::increase_size_n(), GaussElimComputation::insert(), F4GB::insert_gb_element(), MonomialIdeal::is_borel(), KBasis::KBasis(), Matrix::koszul(), Matrix::koszul_monomials(), Lapack::least_squares(), Lapack::least_squares_deficient(), PolyRing::list_form(), LLLoperations::LLL(), Lapack::LU(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), DMatLinAlg< M2::ARingZZpFlint >::matrixPLU(), MonomialTable::minimalize(), minimalize_res_varpower_monomials(), Matrix::minors(), Matrix::module_tensor(), Matrix::monomials(), mpfc_clear(), WeylAlgebra::mult_by_term(), PolyRing::n_logical_terms(), binomialGB::n_masks(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), binomial_s_pair_set::next(), norm_of_inverse_via_svd(), our_new_delete::operator delete(), our_new_delete::operator delete[](), popular_var(), Lapack::QR(), QRingInfo_field::QRingInfo_field(), QRingInfo_ZZ::QRingInfo_ZZ(), rawGetParts(), DPoly::read_poly_0(), DPoly::read_poly_n(), PathTracker::refine(), Solution::release(), binomialGB_comp::remove_gb(), GaussElimComputation::remove_gm_elem(), binomial_s_pair_set::remove_lcm_list(), binomialGB::remove_monomial_list(), GB_comp::remove_pair(), GBinhom_comp::remove_pair(), gb2_comp::remove_pair(), binomial_s_pair_set::remove_pair_list(), res2_comp::remove_res2_level(), res2_comp::remove_res2_pair(), res_comp::remove_res_degree(), res_comp::remove_res_level(), Ring::remove_vec_node(), tableau::resize(), tableau2::resize(), FreeModule::select_by_degrees(), res_comp::skeleton_pairs(), res_comp::skeleton_stats(), solve_via_lapack(), solve_via_lapack_without_transposition(), QuickSorter< Sorter >::sortC(), GBKernelComputation::strip_gb(), Matrix::sub_matrix(), FreeModule::sub_space(), SchreyerOrder::sub_space(), Matrix::support(), Lapack::SVD(), Lapack::SVD_divide_conquer(), ResF4toM2Interface::to_M2_MutableMatrix(), BIBasis::BooleanInvolutiveBasis< MonomType >::ToMatrix(), PathTracker::track(), PolyRing::translate_gbvector_to_vec(), PolyRing::translate_gbvector_to_vec_QQ(), F4MonomialLookupTableT< Key >::update_expvector(), ResF4MonomialLookupTableT< Key >::update_expvector(), PolyRing::vec_coefficient_of_var(), Ring::vec_remove_monomial_factors(), PolyRing::vec_top_coefficient(), WeylAlgebra::weyl_diff(), wrapperFrobbyAlexanderDual(), M2::ARingGFFlint::~ARingGFFlint(), M2::ARingGFFlintBig::~ARingGFFlintBig(), M2::ARingZZp::~ARingZZp(), AssociatedPrimes::~AssociatedPrimes(), binomial_ring::~binomial_ring(), buffer::~buffer(), DetComputation::~DetComputation(), DMat< ACoeffRing >::~DMat(), doubling_stash::~doubling_stash(), CoefficientRingR::ElementArray::~ElementArray(), FF_LUComputation::~FF_LUComputation(), gb_emitter::~gb_emitter(), MarkedGB::~MarkedGB(), MatrixStream::~MatrixStream(), MinimalPrimes::~MinimalPrimes(), MonomialInfo::~MonomialInfo(), MyIdealConsumer::~MyIdealConsumer(), PathTracker::~PathTracker(), PfaffianComputation::~PfaffianComputation(), RingMap::~RingMap(), SLP< Field >::~SLP(), SMat< ACoeffRing >::~SMat(), and Subsets::~Subsets().