Macaulay2 Engine: outofmem2
outofmem2()
void outofmem2 (size_t new)
Definition at line 35 of file M2mem-replacement.c.
{
      const char *msg = "\n\n *** out of memory trying to allocate %ld bytes, exiting ***\n";
      static char buf[sizeof(msg) + 100];
      sprintf(buf,msg,(long)new);
      int r = write(STDERR,buf,strlen(buf));
      if (r == ERROR) exit(1);
      exit(1);
 }
References ERROR().
Referenced by getmem(), getmem_atomic(), getmem_atomic_clear(), getmem_clear(), getmem_malloc(), getmoremem(), getmoremem1(), getmoremem_atomic(), our_new_delete::operator new(), and our_new_delete::operator new[]().