Macaulay2 Engine: TEST
TEST() [3/6]
TEST (NewF4 , matrixstream)
Definition at line 58 of file NewF4Test.cpp.
 {
   const PolynomialRing* R = simplePolynomialRing(1235952427, {"x", "y", "z"});
   const std::string polys = R"(1*x^1+2*y^1+2*z^1+1235952426
 y^1*z^1+494380972*z^2+370785728*y^1+247190485*z^1
 y^2+988761941*z^2+741571456*y^1+494380971*z^1
 1*z^3+924021576*z^2+700373042*y^1+653289140*z^1
 )";
   const Ring *K = R->getCoefficients();
   auto VA = new VectorArithmetic(K);
   BasicPolyList B = parseBasicPolyListFromString(polys, {"x", "y", "z"});
   newf4::MonomialHashTable monHashTable;
   newf4::PolynomialList L(*VA, monHashTable);
   newf4::PolynomialListStreamCollector S(1235952427, 3, 1, L);
   toStream(B, S);
   std::cout << "Number of monomials: " << monHashTable.size() << std::endl;
   monHashTable.dump();
 }
References PolynomialRing::getCoefficients(), parseBasicPolyListFromString(), simplePolynomialRing(), and toStream().