Macaulay2 Engine: TEST
TEST() [2/6]
TEST (NewF4 , hashtable)
Definition at line 32 of file NewF4Test.cpp.
 {
   newf4::MonomialHashTable hashtab(5);
   // std::vector<int32_t> mdata{5, 1, 2, 2, 5};
   // newf4::Monomial m(mdata);
   // newf4::MonomialIndex m1 = hashtab.find(m, 7342643);
   // newf4::MonomialIndex m2 = hashtab.find(m, 7342643);
   // std::cout << "m1 = " << m1 << std::endl;
   // EXPECT_EQ(m1, m2);
   MemoryBlock B;
   for (int i=0; i<100000; ++i)
     {
       newf4::MonomialView m({5, 1, 2, i, 3}, B);
       /*newf4::MonomialIndex m1 = */ hashtab.find(m, hashFunction(m));
     }
   for (int i=0; i<10000; ++i)
     {
       newf4::MonomialView m({5, 1, 2, i, 3}, B);
       /*newf4::MonomialIndex m1 = */ hashtab.find(m, hashFunction(m));
     }
   std::cout << std::endl;
   hashtab.dump();
 }
References newf4::MonomialHashTable::dump(), newf4::MonomialHashTable::find(), and hashFunction().