Macaulay2 Engine: TEST
TEST() [6/6]
TEST (NewF4MonomialLookupTable , monomialOperations)
Definition at line 120 of file NewF4Test.cpp.
 {
   MemoryBlock B;
   newf4::MonomialView ab({5,0,1,1,1}, B);
   newf4::MonomialView ac({5,0,1,2,1}, B);
   newf4::MonomialView abc({7,0,1,1,1,2,1}, B);
   newf4::MonomialView a2bc({7,0,2,1,1,2,1}, B);
   newf4::MonomialView b({3,1,1}, B);
   newf4::MonomialView lcm = newf4::MonomialView::lcm(ab,ac,B);
   newf4::MonomialView product = newf4::MonomialView::product(ab,ac,B);
   newf4::MonomialView quotient = newf4::MonomialView::quotient(ab,ac,B);
   std::cout << lcm.size() << std::endl;
   for (auto i = lcm.begin(); i != lcm.end(); ++i)
   {
     std::cout << i.var() << " ";
     std::cout << i.power() << " ";
   }
   std::cout << std::endl;
   std::cout << product.size() << std::endl;
   for (auto i = product.begin(); i != product.end(); ++i)
   {
     std::cout << i.var() << " ";
     std::cout << i.power() << " ";
   }
   std::cout << std::endl;
   std::cout << quotient.size() << std::endl;
   for (auto i = quotient.begin(); i != quotient.end(); ++i)
   {
     std::cout << i.var() << " ";
     std::cout << i.power() << " ";
   }
   std::cout << std::endl;
   EXPECT_TRUE(newf4::MonomialView::monomialDivides(lcm,abc));
   EXPECT_TRUE(newf4::MonomialView::monomialDivides(abc,lcm));
   EXPECT_TRUE(newf4::MonomialView::monomialDivides(product,a2bc));
   EXPECT_TRUE(newf4::MonomialView::monomialDivides(a2bc,product));
   EXPECT_TRUE(newf4::MonomialView::monomialDivides(quotient,b));
   EXPECT_TRUE(newf4::MonomialView::monomialDivides(b,quotient));
 }
References newf4::MonomialView::begin(), newf4::MonomialView::end(), newf4::MonomialView::lcm(), newf4::MonomialView::monomialDivides(), newf4::MonomialView::product(), newf4::MonomialView::quotient(), and newf4::MonomialView::size().