Macaulay2 Engine: PriorityQueuePolynomialHeap::addPolynomial
addPolynomial() [1/2]
PriorityQueuePolynomialHeap & PriorityQueuePolynomialHeap::addPolynomial (const Poly & poly) inline override virtual
Implements PolynomialHeap.
Definition at line 910 of file NCReduction.cpp.
  {
    if (mLeadTermSet)
      {
        mQueue.push(mLeadTerm);
        mLeadTermSet = false;
      }
    for (auto i = poly.cbegin(); i != poly.cend(); ++i)
      addEntry(Entry(i.monom(),i.coeff()));
    return *this;
  }
References addEntry(), mLeadTerm, mLeadTermSet, and mQueue.
Referenced by addPolynomial(), and value().