Macaulay2 Engine: PriorityQueuePolynomialHeap::isZero
isZero()
bool PriorityQueuePolynomialHeap::isZero () inline override virtual
Implements PolynomialHeap.
Definition at line 934 of file NCReduction.cpp.
   {
     if (mLeadTermSet) return false;
     if (mQueue.empty()) return true;
     Entry lt = mQueue.top();
     mQueue.pop();
     while (not mQueue.empty())
       {
         Entry e = mQueue.top();
         if (mRing.monoid().compare(e.first, lt.first) == EQ)
           {
             lt.second = mRing.coefficientRing()->add(lt.second, e.second);
             mQueue.pop();
           }
         else
           {
             if (not mRing.coefficientRing()->is_zero(lt.second))
               {
                 mLeadTermSet = true;
                 mLeadTerm = lt;
                 return false;
               }
             else
               {
                 lt = mQueue.top();
                 mQueue.pop();
               }
           }
       }
     if (not mRing.coefficientRing()->is_zero(lt.second))
       {
         mLeadTermSet = true;
         mLeadTerm = lt;
         return false;
       }
     return true;
   }
References Ring::add(), FreeAlgebra::coefficientRing(), FreeMonoid::compare(), EQ, Ring::is_zero(), mLeadTerm, mLeadTermSet, FreeAlgebra::monoid(), mQueue, and mRing.
Referenced by removeLeadTerm(), value(), and viewLeadTerm().