Macaulay2 Engine: PriorityQueuePolynomialHeap::value
value()
Poly * PriorityQueuePolynomialHeap::value () inline override virtual
Implements PolynomialHeap.
Definition at line 991 of file NCReduction.cpp.
  {
    Poly* f = new Poly;
    if (mLeadTermSet)
      mQueue.push(mLeadTerm);
    mLeadTermSet = false;
    while (not isZero())
      {
        auto tm = viewLeadTerm();
        mRing.add_to_end(*f, tm.second, tm.first);
        removeLeadTerm();
      }
    addPolynomial(*f);
    return f;
  }
References FreeAlgebra::add_to_end(), addPolynomial(), isZero(), mLeadTerm, mLeadTermSet, mQueue, mRing, removeLeadTerm(), and viewLeadTerm().