Macaulay2 Engine: F4toM2Interface::from_M2_matrix
from_M2_matrix()
void F4toM2Interface::from_M2_matrix (const VectorArithmetic * VA, const MonomialInfo * MI, const Matrix * m, M2_arrayint wts, gb_array & result_polys) static
Definition at line 79 of file f4-m2-interface.cpp.
 {
   const FreeModule *F = m->rows();
   for (int i = 0; i < m->n_cols(); i++)
     {
       gbelem *g = new gbelem;
       from_M2_vec(VA, MI, F, m->elem(i), g->f);
       if (wts != nullptr) poly_set_degrees(VA, MI, wts, g->f, g->deg, g->alpha);
       result_polys.push_back(g);
     }
 }
References gbelem::alpha, gbelem::deg, Matrix::elem(), gbelem::f, from_M2_vec(), Matrix::n_cols(), poly_set_degrees(), and Matrix::rows().
Referenced by F4Computation::F4Computation().