Macaulay2 Engine: F4toM2Interface::to_M2_vec
to_M2_vec()
vec F4toM2Interface::to_M2_vec (const VectorArithmetic * VA, const MonomialInfo * MI, const GBF4Polynomial & f, const FreeModule * F) static
Definition at line 95 of file f4-m2-interface.cpp.
 {
   const PolynomialRing *R = F->get_ring()->cast_to_PolynomialRing();
   const Monoid *M = R->getMonoid();
   monomial m1 = M->make_one();
   Nterm **comps = newarray(Nterm *, F->rank());
   Nterm **last = newarray(Nterm *, F->rank());
   for (int i = 0; i < F->rank(); i++)
     {
       comps[i] = nullptr;
       last[i] = nullptr;
     }
   int *exp = newarray_atomic(int, M->n_vars() + 1);
   ntuple_word *lexp = newarray_atomic(ntuple_word, M->n_vars() + 1);
   const monomial_word *w = f.monoms;
   for (int i = 0; i < f.len; i++)
     {
       long comp;
       MI->to_expvector(w, lexp, comp);
       w = w + MI->monomial_size(w);
       for (int a = 0; a < M->n_vars(); a++) exp[a] = static_cast<int>(lexp[a]);
       M->from_expvector(exp, m1);
       ring_elem a = VA->ringElemFromElementArray(f.coeffs, i);
       Nterm *g = R->make_flat_term(a, m1);
       g->next = nullptr;
       if (last[comp] == nullptr)
         {
           comps[comp] = g;
           last[comp] = g;
         }
       else
         {
           last[comp]->next = g;
           last[comp] = g;
         }
     }
   vec result = nullptr;
   for (int i = 0; i < F->rank(); i++)
     {
       if (comps[i] != nullptr)
         {
           vec v = R->make_vec(i, comps[i]);
           R->add_vec_to(result, v);
           comps[i] = nullptr;
           last[i] = nullptr;
         }
     }
   return result;
 }
References Ring::add_vec_to(), Ring::cast_to_PolynomialRing(), GBF4Polynomial::coeffs, mpfr::exp(), Monoid::from_expvector(), FreeModule::get_ring(), PolynomialRing::getMonoid(), GBF4Polynomial::len, PolynomialRing::make_flat_term(), Monoid::make_one(), Ring::make_vec(), MonomialInfo::monomial_size(), GBF4Polynomial::monoms, Monoid::n_vars(), newarray, newarray_atomic, Nterm::next, FreeModule::rank(), VectorArithmetic::ringElemFromElementArray(), and MonomialInfo::to_expvector().
Referenced by F4Computation::get_gb(), F4GB::show_gb_array(), and to_M2_matrix().