Macaulay2 Engine: F4toM2Interface::to_M2_matrix
to_M2_matrix()
Matrix * F4toM2Interface::to_M2_matrix (const VectorArithmetic * VA, const MonomialInfo * MI, gb_array & polys, const FreeModule * F) static
Definition at line 154 of file f4-m2-interface.cpp.
 {
   MatrixConstructor result(F, INTSIZE(polys));
   for (int i = 0; i < polys.size(); i++)
     result.set_column(i, to_M2_vec(VA, MI, polys[i]->f, F));
   return result.to_matrix();
 }
References INTSIZE, MatrixConstructor::set_column(), to_M2_vec(), and MatrixConstructor::to_matrix().