Macaulay2 Engine: ResMonoidSparse::showAlpha
showAlpha()
void ResMonoidSparse::showAlpha (res_const_packed_monomial m) const
Definition at line 101 of file res-moninfo-sparse.cpp.
{
  component_index comp = get_component(m);
  const int* end = m + *m;
  for (const int* v = m + mFirstVar; v != end; ++v)
    {
      fprintf(stdout, "%c", 'a' + *v);
    }
  fprintf(stdout, "<%d>", comp);
}
References end(), get_component(), and mFirstVar.
Referenced by compare_schreyer().