Macaulay2 Engine: F4toM2Interface::poly_set_degrees
poly_set_degrees()
void F4toM2Interface::poly_set_degrees (const VectorArithmetic * VA, const MonomialInfo * MI, const M2_arrayint wts, const GBF4Polynomial & f, int & deg, int & alpha) static
Definition at line 59 of file f4-m2-interface.cpp.
 {
   const monomial_word *w = f.monoms;
   monomial_word leaddeg = MI->monomial_weight(w, wts);
   monomial_word deg = leaddeg;
   for (int i = 1; i < f.len; i++)
     {
       w = w + MI->monomial_size(w);
       monomial_word degi = MI->monomial_weight(w, wts);
       if (degi > deg) deg = degi;
     }
   alpha = static_cast<int>(deg - leaddeg);
   deg_result = static_cast<int>(deg);
 }
References GBF4Polynomial::len, MonomialInfo::monomial_size(), MonomialInfo::monomial_weight(), and GBF4Polynomial::monoms.
Referenced by from_M2_matrix().