Macaulay2 Engine: F4toM2Interface::from_M2_vec
from_M2_vec()
void F4toM2Interface::from_M2_vec (const VectorArithmetic * VA, const MonomialInfo * MI, const FreeModule * F, vec v, GBF4Polynomial & result) static
Definition at line 20 of file f4-m2-interface.cpp.
 {
   const PolynomialRing *R = F->get_ring()->cast_to_PolynomialRing();
   const Monoid *M = R->getMonoid();
   ring_elem denom;
   gbvector *f = R->translate_gbvector_from_vec(F, v, denom);
   GBRing *GR = R->get_gb_ring();
   int n = GR->gbvector_n_terms(f);
   int *exp = new int[M->n_vars() + 1]; // newarray_atomic(int, M->n_vars() + 1);
   ntuple_word *lexp = new ntuple_word[M->n_vars() + 1]; // newarray_atomic(ntuple_word, M->n_vars() + 1);
   result.len = n;
   std::vector<ring_elem> relem_array;
   result.monoms = newarray_atomic(monomial_word, n * MI->max_monomial_size());
   n = 0;
   monomial_word *nextmonom = result.monoms;
   for (gbvector *t = f; t != nullptr; t = t->next)
     {
       relem_array.push_back(t->coeff);
       M->to_expvector(t->monom, exp);
       for (int a = 0; a < M->n_vars(); a++) lexp[a] = exp[a];
       MI->from_expvector(
           lexp,
           t->comp - 1,
           nextmonom);  // gbvector components are shifted up by one
       nextmonom += MI->monomial_size(nextmonom);
       n++;
     }
   result.coeffs = VA->elementArrayFromContainer(relem_array);
   delete [] exp;
   delete [] lexp;
 }
References Ring::cast_to_PolynomialRing(), GBF4Polynomial::coeffs, VectorArithmetic::elementArrayFromContainer(), mpfr::exp(), MonomialInfo::from_expvector(), GBRing::gbvector_n_terms(), PolynomialRing::get_gb_ring(), FreeModule::get_ring(), PolynomialRing::getMonoid(), GBF4Polynomial::len, MonomialInfo::max_monomial_size(), MonomialInfo::monomial_size(), GBF4Polynomial::monoms, Monoid::n_vars(), newarray_atomic, gbvector::next, Monoid::to_expvector(), and PolynomialRing::translate_gbvector_from_vec().
Referenced by from_M2_matrix().