Macaulay2 Engine: F4toM2Interface::to_M2_MutableMatrix
to_M2_MutableMatrix()
MutableMatrix * F4toM2Interface::to_M2_MutableMatrix (const VectorArithmetic * VA, coefficient_matrix * mat, gb_array & gens, gb_array & gb) static
Definition at line 165 of file f4-m2-interface.cpp.
 {
   int nrows = INTSIZE(mat->rows);
   int ncols = INTSIZE(mat->columns);
   MutableMatrix *M =
       IM2_MutableMatrix_make(VA->ring(), nrows, ncols, false);
   for (int r = 0; r < nrows; r++)
     {
       row_elem &row = mat->rows[r];
       const ElementArray* coeffs;
       if (row.coeffs.isNull())
         {
           if (row.monom == nullptr)
             coeffs = & gens[row.elem]->f.coeffs;
           else
             coeffs = & gb[row.elem]->f.coeffs;
         }
       else
         {
           coeffs = & row.coeffs;
         }
       for (int i = 0; i < row.len; i++)
         {
           int c = row.comps[i];
           ring_elem a = VA->ringElemFromElementArray(* coeffs, i);
           M->set_entry(r, c, a);
         }
     }
   return M;
 }
References row_elem::coeffs, coefficient_matrix::columns, row_elem::comps, row_elem::elem, gb(), IM2_MutableMatrix_make(), INTSIZE, ElementArray::isNull(), row_elem::len, row_elem::monom, VectorArithmetic::ring(), VectorArithmetic::ringElemFromElementArray(), coefficient_matrix::rows, and MutableMatrix::set_entry().
Referenced by F4GB::show_matrix().