Macaulay2 Engine: ResMonoidSparse::compare_schreyer
compare_schreyer()
int ResMonoidSparse::compare_schreyer (res_const_packed_monomial m, res_const_packed_monomial n, res_const_packed_monomial m0, res_const_packed_monomial n0, component_index tie1, component_index tie2) const inline
Definition at line 403 of file res-moninfo-sparse.hpp.
   {
     // REWRITE
     ncalls_compare++;
 #if 0
     printf("compare_schreyer: ");
     printf("  m=");
     showAlpha(m);
     printf("  n=");
     showAlpha(n);
     printf("  m0=");
     showAlpha(m0);
     printf("  n0=");
     showAlpha(n0);
     printf("  tiebreakers: %ld %ld\n", tie1, tie2);
 #endif
     int* m1 = new int[*m + *m0];  // need less than this
     int* n1 = new int[*n + *n0];  // need less than this
     mult(m, m0, m1);
     mult(n, n0, n1);
     int cmp = compare_grevlex(m1, n1);
     if (cmp == 0)
       {
         if (tie1 > tie2)
           cmp = -1;
         else if (tie1 < tie2)
           cmp = 1;
         else
           cmp = 0;
       }
     delete[] m1;
     delete[] n1;
     return cmp;
   }
References compare_grevlex(), mult(), ncalls_compare, and showAlpha().