Macaulay2 Engine: IntsSet::find
find()
template<typename Configuration > std::pair<int,bool> IntsSet< Configuration >::find (Monom m, int comp) inline
Definition at line 246 of file monomial-collection.hpp.
   {
     size_t sz = ModuleMonom::sizeOfCorrespondingModuleMonom(m);
     std::pair<int*, int*> mon { mArena.allocArrayNoCon<int>(sz) };
     ModuleMonom a = monomToModuleMonom(m, comp, mon);
     auto result = mHash.find(a); // returns iterator pointing to value, or mHash.end()
     bool found = (result != mHash.end());
     int idx = (found ? result->index() : -1);
     mArena.freeTop(mon.first);
     return {idx, found};
   }
References IntsSet< Configuration >::mArena, IntsSet< Configuration >::mHash, monomToModuleMonom(), and ModuleMonom::sizeOfCorrespondingModuleMonom().
Referenced by NCCoefficientMatrix().