Macaulay2 Engine: IntsSet::insert
insert()
template<typename Configuration > bool IntsSet< Configuration >::insert (Monom m, int comp) inline
Definition at line 225 of file monomial-collection.hpp.
   {
     size_t sz = ModuleMonom::sizeOfCorrespondingModuleMonom(m);
     std::pair<int*, int*> mon { mArena.allocArrayNoCon<int>(sz) };
     ModuleMonom a = monomToModuleMonom(m, comp, mon);
     auto result = mHash.insert(a);
     bool new_elem = result.second;
     if (new_elem)
       {
         a.setIndex(mElements.size());
         mElements.push_back(a);
       }
     else
       {
         mArena.freeTop(a + 0);
       }
     return new_elem;
   }
References IntsSet< Configuration >::mArena, IntsSet< Configuration >::mElements, IntsSet< Configuration >::mHash, monomToModuleMonom(), ModuleMonom::setIndex(), and ModuleMonom::sizeOfCorrespondingModuleMonom().
Referenced by NCMonomials().