Macaulay2 Engine: RingZZ::divide
divide()
ring_elem RingZZ::divide (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 295 of file ZZ.cpp.
 {
   if (is_zero(g)) throw exc::division_by_zero_error();
   mpz_ptr result = new_elem();
   mpz_t rem;
   mpz_init(rem);
   mpz_fdiv_qr(result, rem, f.get_mpz(), g.get_mpz());
   if (mpz_sgn(rem)) throw exc::engine_error("division not exact");
   mpz_clear(rem);
   mpz_reallocate_limbs(result);
   return ring_elem(result);
 }
References ring_elem::get_mpz(), is_zero(), mpz_reallocate_limbs(), new_elem(), and mpfr::rem().
Referenced by LLLoperations::doLLL(), HermiteComputation::reduce(), syzygy(), and TEST().