Macaulay2 Engine: RingZZ::is_positive
is_positive()
int RingZZ::is_positive (const ring_elem a) const
Definition at line 168 of file ZZ.cpp.
 {
   mpz_srcptr a = f.get_mpz();
   return mpz_sgn(a) > 0;
 }
References ring_elem::get_mpz().
Referenced by HermiteComputation::start_computation(), and TEST().