Macaulay2 Engine: RingZZ::coerceToLongInteger
coerceToLongInteger()
std::pair< bool, long > RingZZ::coerceToLongInteger (ring_elem a) const virtual
Reimplemented from Ring.
Definition at line 64 of file ZZ.cpp.
 {
   return std::pair<bool, long>(mpz_fits_slong_p(a.get_mpz()),
                                mpz_get_si(a.get_mpz()));
 }
References ring_elem::get_mpz().
Referenced by LLLoperations::doLLL(), and binomial_ring::intvector_to_binomial().