Macaulay2 Engine: RingZZ::eval
eval()
ring_elem RingZZ::eval (const RingMap * map, const ring_elem f, int first_var) const virtual
Implements Ring.
Definition at line 413 of file ZZ.cpp.
 {
   return map->get_ring()->from_int(f.get_mpz());
 }
References Ring::from_int(), ring_elem::get_mpz(), and RingMap::get_ring().