Macaulay2 Engine: RingZZ::gcd_extended
gcd_extended()
ring_elem RingZZ::gcd_extended (const ring_elem f, const ring_elem g, ring_elem & u, ring_elem & v) const
Definition at line 360 of file ZZ.cpp.
 {
   mpz_ptr result = new_elem();
   mpz_ptr u1 = new_elem();
   mpz_ptr v1 = new_elem();
   mpz_gcdext(result, u1, v1, f.get_mpz(), g.get_mpz());
   mpz_reallocate_limbs(u1);
   mpz_reallocate_limbs(v1);
   mpz_reallocate_limbs(result);
   u = ring_elem(u1);
   v = ring_elem(v1);
   return ring_elem(result);
 }
References ring_elem::get_mpz(), mpz_reallocate_limbs(), and new_elem().
Referenced by HermiteComputation::reduce(), and TEST().