Macaulay2 Engine: RingZZ::get_si
get_si()
std::pair< bool, int > RingZZ::get_si (mpz_srcptr n) static
Definition at line 46 of file ZZ.cpp.
 {
   if (not mpz_fits_slong_p(n)) return std::make_pair<bool, int>(false, 0);
   long a = mpz_get_si(n);
   int b = static_cast<int>(a);
   if (a == b) return std::make_pair<bool, int>(true, std::move(b));
   return std::make_pair<bool, int>(false, 0);
 }
Referenced by PolyRing::power(), SchurRing::power(), SkewPolynomialRing::power(), SolvableAlgebra::power(), WeylAlgebra::power(), power(), FreeAlgebra::power(), M2::ARingCC::power_mpz(), M2::ARingCCC::power_mpz(), M2::ARingQQFlint::power_mpz(), M2::ARingQQGMP::power_mpz(), M2::ARingRR::power_mpz(), M2::ARingZZ::power_mpz(), M2::ARingZZGMP::power_mpz(), and TEST().