Macaulay2 Engine: RingZZ::from_int
from_int()
ring_elem RingZZ::from_int (mpz_srcptr n) const virtual
Implements Ring.
Definition at line 113 of file ZZ.cpp.
 {
   mpz_ptr result = new_elem();
   mpz_set(result, n);
   mpz_reallocate_limbs(result);
   return ring_elem(result);
 }
References mpz_reallocate_limbs(), and new_elem().
Referenced by M2::RingQQ::denominator(), fp_LLL(), from_rational(), getElement< RingZZ >(), LLLoperations::initializeLLL(), M2::ConcreteRing< RingType >::lift(), ntl_LLL(), M2::RingQQ::numerator(), LLLoperations::SWAPI(), and TEST().