Macaulay2 Engine: RingZZ::preferred_associate
preferred_associate()
ring_elem RingZZ::preferred_associate (ring_elem f) const virtual
Reimplemented from Ring.
Definition at line 190 of file ZZ.cpp.
 {
   mpz_srcptr a = f.get_mpz();
   if (mpz_sgn(a) >= 0) return from_long(1);
   return from_long(-1);
 }
References from_long(), and ring_elem::get_mpz().
Referenced by TEST().