Macaulay2 Engine: RingZZ::remainder
remainder()
ring_elem RingZZ::remainder (const ring_elem f, const ring_elem g) const virtual
Reimplemented from Ring.
Definition at line 336 of file ZZ.cpp.
 {
   ring_elem quot;
   ring_elem rem = RingZZ::remainderAndQuotient(f, g, quot);
   remove(quot);
   return rem;
 }
References mpfr::rem(), remainderAndQuotient(), and remove().
Referenced by PolyRing::internal_add_to().