Macaulay2 Engine: RingZZ::elem_text_out
elem_text_out()
void RingZZ::elem_text_out (buffer & o, const ring_elem f, bool p_one = true, bool p_plus = false, bool p_parens = false) const virtual
Implements Ring.
Definition at line 72 of file ZZ.cpp.
 {
   mpz_srcptr a = ap.get_mpz();
   char s[1000];
   char *str;
   bool is_neg = (mask_mpz_cmp_si(a, 0) == -1);
   bool is_one = (mask_mpz_cmp_si(a, 1) == 0 || mask_mpz_cmp_si(a, -1) == 0);
   int size = static_cast<int>(mpz_sizeinbase(a, 10)) + 2;
   char *allocstr = (size > 1000 ? newarray_atomic(char, size) : s);
   if (!is_neg && p_plus) o << '+';
   if (is_one)
     {
       if (is_neg) o << '-';
       if (p_one) o << '1';
     }
   else
     {
       str = mpz_get_str(allocstr, 10, a);
       o << str;
     }
   if (size > 1000) freemem(allocstr);
 }
References freemem(), ring_elem::get_mpz(), mask_mpz_cmp_si(), and newarray_atomic.
Referenced by TEST().