Macaulay2 Engine: RingZZ::new_elem
new_elem()
mpz_ptr RingZZ::new_elem () const private
Definition at line 34 of file ZZ.cpp.
 {
   mpz_ptr result = getmemstructtype(mpz_ptr);
   mpz_init(result);
   return result;
 }
References getmemstructtype.
Referenced by add(), copy(), divide(), from_int(), from_long(), gcd(), gcd_extended(), lower_associate_divisor(), lower_content(), mult(), negate(), power(), remainderAndQuotient(), and subtract().