Macaulay2 Engine: RingZZ::syzygy
syzygy()
void RingZZ::syzygy (const ring_elem a, const ring_elem b, ring_elem & x, ring_elem & y) const virtual
Implements Ring.
Definition at line 377 of file ZZ.cpp.
 {
   assert(!is_zero(b));
   // First check the special cases a = 0, b = 1, -1.  Other cases: use gcd.
   if (RingZZ::is_zero(a))
     {
       x = RingZZ::from_long(1);
       y = RingZZ::from_long(0);
       return;
     }
   mpz_srcptr bb = b.get_mpz();
   if (mpz_cmp_ui(bb, 1) == 0)
     {
       x = RingZZ::from_long(1);
       y = RingZZ::negate(a);
       return;
     }
   if (mask_mpz_cmp_si(bb, -1) == 0)
     {
       x = RingZZ::from_long(1);
       y = RingZZ::copy(a);
       return;
     }
   ring_elem g = RingZZ::gcd(a, b);
   y = RingZZ::divide(a, g);
   x = RingZZ::divide(b, g);
   RingZZ::remove(g);
   if (mpz_sgn(x.get_mpz()) > 0)
     y = RingZZ::negate(y);
   else
     x = RingZZ::negate(x);
 }
References copy(), divide(), from_long(), gcd(), ring_elem::get_mpz(), is_zero(), mask_mpz_cmp_si(), negate(), remove(), and x.
Referenced by gbA::minimalize_pairs_ZZ().