Macaulay2 Engine: RingZZ::negate
negate()
ring_elem RingZZ::negate (const ring_elem f) const virtual
Implements Ring.
Definition at line 234 of file ZZ.cpp.
 {
   mpz_ptr result = new_elem();
   mpz_neg(result, f.get_mpz());
   mpz_reallocate_limbs(result);
   return ring_elem(result);
 }
References ring_elem::get_mpz(), mpz_reallocate_limbs(), and new_elem().
Referenced by GBRing::find_reduction_coeffs_ZZ(), HermiteComputation::gb_reduce(), GBRing::gbvector_auto_reduce_ZZ(), QRingInfo_ZZ::reduce_lead_term_ZZ(), and syzygy().