Macaulay2 Engine: RingZZ::lower_associate_divisor
lower_associate_divisor()
bool RingZZ::lower_associate_divisor (ring_elem & f, ring_elem g) const virtual
Reimplemented from Ring.
Definition at line 197 of file ZZ.cpp.
 {
   // This sets f to either 0, 1 or -1.
   // if f is 0, do f=sign(g), else f=sign(f)
   // return whether f is zero
   mpz_ptr result = RingZZ::new_elem();
   mpz_srcptr a = f.get_mpz();
   mpz_srcptr b = g.get_mpz();
   int sa = mpz_sgn(a);
   int sb = mpz_sgn(b);
   int s = (sa == 0 ? sb : sa);
   mpz_set_si(result, s);
   mpz_reallocate_limbs(result);
   f = ring_elem(result);
   return !RingZZ::is_zero(f);
 }
References ring_elem::get_mpz(), is_zero(), mpz_reallocate_limbs(), and new_elem().
Referenced by TEST().