Macaulay2 Engine: RingZZ::quotient
quotient()
ring_elem RingZZ::quotient (const ring_elem f, const ring_elem g) const virtual
Reimplemented from Ring.
Definition at line 344 of file ZZ.cpp.
 {
   ring_elem quot;
   ring_elem rem = RingZZ::remainderAndQuotient(f, g, quot);
   remove(rem);
   return quot;
 }
References mpfr::rem(), remainderAndQuotient(), and remove().
Referenced by GBRing::gbvector_auto_reduce_ZZ().