Macaulay2 Engine: RingZZ::mod_ui
mod_ui()
unsigned int RingZZ::mod_ui (mpz_srcptr n, unsigned int p) static
Definition at line 55 of file ZZ.cpp.
 {
   mpz_t ans;
   mpz_init(ans);
   unsigned int exp = static_cast<unsigned int>(mpz_mod_ui(ans, n, p));
   mpz_clear(ans);
   return exp;
 }
References mpfr::exp(), and p.
Referenced by GF::power(), Ring::power(), Z_mod::power(), and DPoly::power_mod().