Macaulay2 Engine: RingZZ::get_ARing
get_ARing()
M2::ARingZZGMP* RingZZ::get_ARing () const inline
Definition at line 50 of file ZZ.hpp.
   {
     return coeffR;
   }
References coeffR.
Referenced by ResGausserQQHybrid::from_ring_elem(), ResGausserQQ::from_ring_elem(), and makeMutableMatrix().