Macaulay2 Engine: RingZZ::remove
remove()
void RingZZ::remove (ring_elem & f) const virtual
Implements Ring.
Definition at line 185 of file ZZ.cpp.
 {
   // NOTHING
 }
Referenced by LLLoperations::doLLL(), LLLoperations::initializeLLL(), quotient(), HermiteComputation::reduce(), remainder(), and syzygy().