Macaulay2 Engine: RingZZ::initialize_ZZ
initialize_ZZ()
bool RingZZ::initialize_ZZ (const PolynomialRing * deg_ring)
Definition at line 19 of file ZZ.cpp.
 {
   initialize_ring(0);
   zeroV = from_long(0);
   oneV = from_long(1);
   minus_oneV = from_long(-1);
   degree_ring = deg_ring;
   coeffR = new M2::ARingZZGMP;
   return true;
 }
References coeffR, Ring::degree_ring, from_long(), Ring::initialize_ring(), Ring::minus_oneV, Ring::oneV, and Ring::zeroV.
Referenced by PolyRing::make_trivial_ZZ_poly_ring().