Macaulay2 Engine: RingZZ::remainderAndQuotient
remainderAndQuotient()
ring_elem RingZZ::remainderAndQuotient (const ring_elem f, const ring_elem g, ring_elem & quot) const virtual
Reimplemented from Ring.
Definition at line 308 of file ZZ.cpp.
 {
   mpz_ptr q = new_elem();
   mpz_ptr r = new_elem();
   int gsign = mpz_sgn(g.get_mpz());
   mpz_t gg, ghalf;
   mpz_init(gg);
   mpz_init(ghalf);
   mpz_abs(gg, g.get_mpz());
   mpz_fdiv_qr(q, r, f.get_mpz(), gg);
   mpz_tdiv_q_2exp(ghalf, gg, 1);
   if (mpz_cmp(r, ghalf) > 0)  // r > ghalf
     {
       mpz_sub(r, r, gg);
       mpz_add_ui(q, q, 1);
     }
   if (gsign < 0) mpz_neg(q, q);
   mpz_clear(gg);
   mpz_clear(ghalf);
   mpz_reallocate_limbs(q);
   mpz_reallocate_limbs(r);
   quot = ring_elem(q);
   return ring_elem(r);
 }
References ring_elem::get_mpz(), mpz_reallocate_limbs(), and new_elem().
Referenced by GBRing::find_reduction_coeffs_ZZ(), HermiteComputation::gb_reduce(), PolyRing::imp_attempt_to_cancel_lead_term(), quotient(), QRingInfo_ZZ::reduce_lead_term_ZZ(), and remainder().