Macaulay2 Engine: BIBasis::TSet::CollectNonMultiProlongations
CollectNonMultiProlongations()
template<typename MonomType > void BIBasis::TSet< MonomType >::CollectNonMultiProlongations (Iterator & iterator, std::list< Triple< MonomType > * > & set)
Definition at line 133 of file tset.hpp.
    {
        if (iterator == TripleList.end() || !(*iterator))
        {
            return;
        }
        typename MonomType::Integer firstMultiVar = (**iterator).GetPolynomLm().FirstMultiVar();
        for (typename MonomType::Integer var = 0; var < firstMultiVar; ++var)
        {
            if (!(**iterator).TestNmp(var))
            {
                Polynom<MonomType>* tmpPolynom = new Polynom<MonomType>(*(**iterator).GetPolynom());
                (*tmpPolynom) *= var;
                (**iterator).SetNmp(var);
                if (!tmpPolynom->IsZero())
                {
                    set.push_back(new Triple<MonomType>(tmpPolynom
                                                      , (**iterator).GetAncestor()
                                                      , (**iterator).GetNmp()
                                                      , (*iterator)
                                                      , var)
                                 );
                }
                delete tmpPolynom;
            }
        }
    }
References BIBasis::Triple< MonomType >::GetPolynomLm(), BIBasis::Polynom< MonomType >::IsZero(), and set().