Macaulay2 Engine: MinimalPrimes::alg1_min_primes
alg1_min_primes()
MonomialIdeal * MinimalPrimes::alg1_min_primes (int maxcodim, int count)
Definition at line 163 of file monideal-minprimes.cpp.
 {
   // First, let's write out the (radical) monomial ideal in an array.
   // We need to know how large to make it.  So, we first add up all of the
   // degrees of the gens
   depth_limit = -maxcodim - 1;
   long len = 1;
   for (Bag& a : *mi)
     {
       long d = varpower::simple_degree(a.monom().data());
       len += d;
     }
   len += mi->size();
   len += mi->size();
   monoms = newarray_atomic(int, len);
   int next_monom = 0;
   for (Bag& a : *mi)
     {
       int *m = a.monom().data();
       int d = varpower::simple_degree(m);
       monoms[next_monom++] = d + 2;
       for (index_varpower j = m; j.valid(); ++j)
         monoms[next_monom++] = j.var() + 1;
       monoms[next_monom++] = 0;
     }
   monoms[next_monom] = 0;
   exp = newarray_atomic_clear(int, nvars + 1);
   exp2 = newarray_atomic_clear(int, nvars);
   alg1_min_prime_generator(monoms, -1);
   freemem(monoms);
   freemem(exp);
   buffer o;
   o << "number of tentative minprimes is " << Q.size();
   MonomialIdeal *result = new MonomialIdeal(mi->get_ring(), Q);
   o << " actual number is " << result->size() << newline;
   emit(o.str());
   return result;
 }
References alg1_min_prime_generator(), depth_limit, emit(), exp, exp2, freemem(), MonomialIdeal::get_ring(), mi, monoms, newarray_atomic, newarray_atomic_clear, newline, nvars, Q, ExponentList< E, L >::simple_degree(), MonomialIdeal::size(), buffer::str(), and ExponentListIterator< E, L >::valid().
Referenced by rawMonomialMinimalPrimes().