Macaulay2 Engine: MinimalPrimes::alg1_min_prime_generator
alg1_min_prime_generator()
void MinimalPrimes::alg1_min_prime_generator (int * which, int depth) private
Definition at line 110 of file monideal-minprimes.cpp.
{
  for (;;)
    {
      if (*which == 0)
        {
          alg1_grab_prime(depth);
          return;
        }
      switch (alg1_reduce_exp(which + 1, exp))
        {
          case 0:
            which = which + *which;
            break;
          case -1:
            return;
          case 1:
            if (depth > depth_limit)
              {
                int *m = which + 1;
                while (*m != 0)
                  {
                    int v = *m;
                    if (exp[v] == 0)
                      {
                        exp[v] = 1;
                        alg1_min_prime_generator(which + *which, depth - 1);
                        exp[v] = depth;
                      }
                    m++;
                  }
                // This code sets the 'exp' array back to the way it was
                m = which + 1;
                while (*m != 0)
                  {
                    int v = *m;
                    if (exp[v] == depth) exp[v] = 0;
                    m++;
                  }
              }
            return;
        }
    }
}
References alg1_grab_prime(), alg1_min_prime_generator(), alg1_reduce_exp(), depth_limit, and exp.
Referenced by alg1_min_prime_generator(), and alg1_min_primes().