Macaulay2 Engine: MinimalPrimes::ass_prime_generator
ass_prime_generator()
void MinimalPrimes::ass_prime_generator (Nmi_node * p, int codim) private
Definition at line 263 of file monideal-minprimes.cpp.
 {
   int i = codim + 1;
   if (exps[i] == 0) exps[i] = newarray_atomic(int, nvars);
   exponents_t exp0 = exps[i];
   for (int j = 0; j < nvars; j++) exp0[j] = exps[codim][j];
   for (;;)
     {
       if (p == NULL)
         {
           if (state == do_codim)
             {
               if (codim < codim_limit) codim_limit = codim;
             }
           else
             {
               to_prime_ideal(nvars, exp0);
               Bag *b = new Bag(0);
               varpower::from_expvector(nvars, exp0, b->monom());
               primes->insert(b);
               n_minprimes++;
             }
           return;
         }
       const int *m = p->monom().data();
       switch (reduce_exp(m, exp0))
         {
           case 0:
             p = mi->next(p);
             break;
           case -1:
             return;
           case 1:
             if (codim < codim_limit)
               for (index_varpower i2 = m; i2.valid(); ++i2)
                 if (exp0[i2.var()] == 0)
                   {
                     exp0[i2.var()] = 1;
                     ass_prime_generator(mi->next(p), codim + 1);
                     exp0[i2.var()] = -1;
                     if (minprime_limit > 0 && n_minprimes >= minprime_limit)
                       return;
                   }
             return;
         }
     }
 }
References codim_limit, do_codim, exps, ExponentList< E, L >::from_expvector(), MonomialIdeal::insert(), mi, minprime_limit, int_bag::monom(), n_minprimes, newarray_atomic, MonomialIdeal::next(), nvars, p, primes, reduce_exp(), state, to_prime_ideal(), and ExponentListIterator< E, L >::valid().
Referenced by codimension(), and min_primes().