Macaulay2 Engine: MinimalPrimes::alg1_grab_prime
alg1_grab_prime()
void MinimalPrimes::alg1_grab_prime (int depth) private
Definition at line 98 of file monideal-minprimes.cpp.
 {
   Bag *b = new Bag(0);
   for (int i = 0; i < nvars; i++)
     if (exp[i + 1] > 0)
       exp2[i] = 1;
     else
       exp2[i] = 0;
   varpower::from_expvector(nvars, exp2, b->monom());
   Q.push_back(b);
 }
References exp, exp2, ExponentList< E, L >::from_expvector(), int_bag::monom(), nvars, and Q.
Referenced by alg1_min_prime_generator().