Macaulay2 Engine: TEST
TEST() [2/3]
TEST (ARingQQFlint , create)
Definition at line 30 of file ARingQQFlintTest.cpp.
 {
   M2::ARingQQFlint R;
   M2::ARingQQFlint::ElementType a;
   buffer o;
   ARingElementGenerator<M2::ARingQQFlint> gen(R);
   R.init(a);
   gen.nextElement(a);
   EXPECT_EQ(ringName(R), "QQFlint");
   EXPECT_EQ(R.cardinality(), static_cast<size_t>(-1));
   EXPECT_EQ(R.characteristic(), 0);
   R.clear(a);
 }
References M2::ARingQQFlint::cardinality(), M2::ARingQQFlint::characteristic(), M2::ARingQQFlint::clear(), M2::ARingQQFlint::init(), ARingElementGenerator< RingType >::nextElement(), and ringName().