Macaulay2 Engine: TEST
TEST() [3/3]
TEST (ARingQQFlint , display)
Definition at line 47 of file ARingQQFlintTest.cpp.
 {
   M2::ARingQQFlint R;
   M2::ARingQQFlint::ElementType a, b;
   buffer o;
   ARingElementGenerator<M2::ARingQQFlint> gen(R);
   R.init(a);
   R.init(b);
   gen.nextElement(a);
   gen.nextElement(b);
   R.divide(a, a, b);
   R.elem_text_out(o, a, true, false, false);
   EXPECT_TRUE(strcmp(o.str(), "24/23") == 0);
   std::cout << "a = ." << o.str() << "." << std::endl;
   EXPECT_EQ(ringName(R), "QQFlint");
   EXPECT_EQ(R.cardinality(), static_cast<size_t>(-1));
   EXPECT_EQ(R.characteristic(), 0);
   R.clear(a);
 }
References M2::ARingQQFlint::cardinality(), M2::ARingQQFlint::characteristic(), M2::ARingQQFlint::clear(), M2::ARingQQFlint::divide(), M2::ARingQQFlint::elem_text_out(), M2::ARingQQFlint::init(), ARingElementGenerator< RingType >::nextElement(), ringName(), and buffer::str().