Macaulay2 Engine: M2::ARingGFFlint::set_from_long
set_from_long()
void M2::ARingGFFlint::set_from_long (ElementType & result, long a) const inline
Definition at line 174 of file aring-gf-flint.hpp.
   {
     long a1 = a % characteristic();
     if (a1 < 0) a1 += characteristic();
     fq_zech_set_ui(&result, a1, mContext);
   }
References characteristic(), and mContext.
Referenced by getGenerator(), set_from_mpz(), set_var(), syzygy(), and TEST().