Macaulay2 Engine: M2::ARingGFFlint::ARingGFFlint
ARingGFFlint()
M2::ARingGFFlint::ARingGFFlint (const PolynomialRing & R, const ring_elem a)
Definition at line 10 of file aring-gf-flint.cpp.
     : mOriginalRing(R),
       mCharacteristic(R.characteristic()),
       mGeneratorComputed(false)
 {
   ring_elem b = R.copy(a);
   mPrimitiveElement = RingElement::make_raw(&R, b);
   ring_elem minpoly = mOriginalRing.quotient_element(0);
   std::vector<long> poly;
   RingElement F(&R, minpoly);
   F.getSmallIntegerCoefficients(poly);
   // warning: flint expects unsigned longs, so we must make
   // all of these coeffs non-negative.
   for (long i = poly.size() - 1; i >= 0; i--)
     {
       long a = poly[i];
       if (a == 0) continue;
       if (a < 0) poly[i] += characteristic();
     }
   mDimension = poly.size() - 1;
 #if 0
     printf("minpoly: ");
     for (long i=0; i<poly.size(); i++)
       printf(" %ld", poly[i]);
     printf("\n");
 #endif
   nmod_poly_t mMinPoly;
   nmod_poly_init(mMinPoly, R.characteristic());
   for (long i = poly.size() - 1; i >= 0; i--)
     if (poly[i] != 0) nmod_poly_set_coeff_ui(mMinPoly, i, poly[i]);
   fq_zech_ctx_init_modulus(mContext, mMinPoly, "a");
   fq_nmod_ctx_init_modulus(mBigContext, mMinPoly, "a");
 #if 0
     fq_zech_ctx_print(mContext);
 #endif
   nmod_poly_clear(mMinPoly);
   // powers of p, as ulongs's
   mPPowers = newarray_atomic(mp_limb_t, mDimension + 1);
   mPPowers[0] = 1;
   for (long i = 1; i <= mDimension; i++)
     mPPowers[i] = mPPowers[i - 1] * static_cast<ulong>(mCharacteristic);
   flint_randinit(mRandomState);
 }
References characteristic(), Ring::characteristic(), Ring::copy(), RingElement::getSmallIntegerCoefficients(), RingElement::make_raw(), mBigContext, mCharacteristic, mContext, mDimension, mOriginalRing, mPPowers, mPrimitiveElement, mRandomState, newarray_atomic, and PolynomialRing::quotient_element().