Macaulay2 Engine: M2::ARingGFFlint::lift_to_original_ring
lift_to_original_ring()
void M2::ARingGFFlint::lift_to_original_ring (ring_elem & result, const ElementType & f) const
Definition at line 154 of file aring-gf-flint.cpp.
 {
   std::vector<long> poly;
   getSmallIntegerCoefficients(f, poly);
   result =
       originalRing().getNumeratorRing()->fromSmallIntegerCoefficients(poly, 0);
 }
References PolyRing::fromSmallIntegerCoefficients(), PolynomialRing::getNumeratorRing(), getSmallIntegerCoefficients(), and originalRing().
Referenced by lift().