Macaulay2 Engine: M2::ARingGFFlint::fromSmallIntegerCoefficients
fromSmallIntegerCoefficients()
void M2::ARingGFFlint::fromSmallIntegerCoefficients (ElementType & result, const std::vector< long > & poly) const
Definition at line 86 of file aring-gf-flint.cpp.
 {
   fq_nmod_t f;
   fq_nmod_init(f, mBigContext);
 #if 0
     printf("input = ");
     for (long i=0; i<poly.size(); i++)
       printf("%ld ", poly[i]);
     printf("\n");
 #endif
   for (long i = poly.size() - 1; i >= 0; i--)
     {
       long a = poly[i];
       if (a == 0) continue;
       if (a < 0) a += characteristic();
       nmod_poly_set_coeff_ui(f, i, a);
     }
 #if 0
     printf("  result before reduction = ");
     fq_nmod_print_pretty(f, mBigContext);
     printf("\n");
 #endif
   fq_nmod_reduce(f, mBigContext);
 #if 0
     printf("  result = ");
     fq_nmod_print_pretty(f, mBigContext);
     printf("\n");
 #endif
   fq_zech_set_fq_nmod(&result, f, mContext);
 #if 0
     printf("  zech result = %lu", result.value);
     printf("\n");
 #endif
   fq_nmod_clear(f, mBigContext);
 }
References characteristic(), mBigContext, and mContext.
Referenced by promote(), random(), and set_var().