Macaulay2 Engine: M2::ARingGFFlint::getGenerator
getGenerator()
void M2::ARingGFFlint::getGenerator (ElementType & result_gen) const
Definition at line 126 of file aring-gf-flint.cpp.
 {
   if (not mGeneratorComputed)
     {
       fq_zech_init(&mCachedGenerator, mContext);
       if (mCharacteristic == 2 and mDimension == 1)
         // This is currently a bug in flint...
         set_from_long(mCachedGenerator, 1);
       else
         fq_zech_gen(&mCachedGenerator, mContext);
       mGeneratorComputed = true;
     }
   copy(result_gen, mCachedGenerator);
 }
References copy(), mCachedGenerator, mCharacteristic, mContext, mDimension, mGeneratorComputed, and set_from_long().
Referenced by getElement< M2::ARingGFFlint >().