Macaulay2 Engine: M2::ARingGFFlint::lift
lift()
bool M2::ARingGFFlint::lift (const Ring * Rg, const ElementType & f, ring_elem & result) const
Definition at line 163 of file aring-gf-flint.cpp.
 {
   // Rg = ZZ/p[x]/F(x) ---> GF(p,n)
   if (&originalRing() != Rg) return false;
   lift_to_original_ring(result, f);
   return true;
 }
References lift_to_original_ring(), and originalRing().
Referenced by elem_text_out().