Macaulay2 Engine: M2::ARingGFFlint::eval
eval()
void M2::ARingGFFlint::eval (const RingMap * map, const ElementType & f, int first_var, ring_elem & result) const
Definition at line 173 of file aring-gf-flint.cpp.
 {
   // f is represented by: f.value, the power of the generator
   if (is_zero(f))
     result = map->get_ring()->zero();
   else
     result =
         map->get_ring()->power(map->elem(first_var), static_cast<int>(f.value));
 }
References RingMap::elem(), RingMap::get_ring(), is_zero(), Ring::power(), and Ring::zero().