Macaulay2 Engine: M2::ARingGFFlint::promote
promote()
bool M2::ARingGFFlint::promote (const Ring * Rf, const ring_elem f, ElementType & result) const
Definition at line 142 of file aring-gf-flint.cpp.
{
  if (&originalRing() != Rf) return false;
  std::vector<long> poly;
  RingElement F(Rf, f);
  F.getSmallIntegerCoefficients(poly);
  fromSmallIntegerCoefficients(result, poly);
  return true;
}
References fromSmallIntegerCoefficients(), RingElement::getSmallIntegerCoefficients(), and originalRing().