Macaulay2 Engine: MonomialSorterObject::operator()
operator()()
bool MonomialSorterObject::operator() (int a, int b) inline
Definition at line 28 of file res-monomial-sorter.hpp.
   {
     // implements < function.  In fact, a and b should not refer to objects that are == under this order.
     // should we flag that?
     mNumComparisons++;
     bool result = false;
     const int* m = mMonoms[a];
     const int* n = mMonoms[b];
     // TODO: make sure this is the order we want!!
     int cmp = mMonoid.compare(m+2, m[1], n+2, n[1]);
     if (cmp == LT) result = false;
     else if (cmp == GT) result = true;
     else
       {
         // compare using tie breaker
         auto cmptie = m[0] - n[0];
         result = (cmptie > 0);
       }
 #if 0
     buffer o;
     o << "comparing: ";
     mMonoid.elem_text_out(o, m+2);
     o << " and ";
     mMonoid.elem_text_out(o, n+2);
     o << " result: " << (result ? "true" : "false");
     emit_line(o.str());
 #endif
     return result;
   }
References Monoid::compare(), Monoid::elem_text_out(), emit_line(), GT, LT, mMonoid, mMonoms, mNumComparisons, and buffer::str().