Macaulay2 Engine: SumCollector::add
add()
virtual void SumCollector::add (ring_elem f) pure virtual
Implemented in SumCollectorFreeAlgebraHeap, SumCollectorDefault, and SumCollectorPolyHeap.
Referenced by FreeAlgebra::eval(), PolyRing::eval(), PolyRing::fromSmallIntegerCoefficients(), and TowerEvaluator::viewTerm().