Macaulay2 Engine: SumCollector::getValue
getValue()
virtual ring_elem SumCollector::getValue () pure virtual
Implemented in SumCollectorDefault, SumCollectorPolyHeap, and SumCollectorFreeAlgebraHeap.
Referenced by FreeAlgebra::eval(), PolyRing::eval(), PolyRing::fromSmallIntegerCoefficients(), and TowerEvaluator::getValue().