Macaulay2 Engine: wrapperFrobbyAlexanderDual
wrapperFrobbyAlexanderDual()
static MonomialIdeal* wrapperFrobbyAlexanderDual (const MonomialIdeal * I, const M2_arrayint top) static
Definition at line 349 of file monomial-ideal.cpp.
 {
   // Create a Frobby Ideal containing I.
   int nv = I->topvar() + 1;
   if (nv == 0)
     {
       INTERNAL_ERROR("attempting to use frobby with zero variables");
       return 0;
     }
   mpz_t *topvec = 0;
   if (top->len > 0)
     {
       topvec = newarray(mpz_t, top->len);
       for (int i = 0; i < top->len; i++)
         mpz_init_set_si(topvec[i], top->array[i]);
     }
   MonomialIdeal *result = FrobbyAlexanderDual(I, topvec);
   // Clean up
   if (topvec != 0)
     {
       for (int i = 0; i < top->len; i++) mpz_clear(topvec[i]);
       freemem(topvec);
     }
   return result;
 }
References freemem(), FrobbyAlexanderDual(), INTERNAL_ERROR(), newarray, and MonomialIdeal::topvar().
Referenced by alexDual().