Macaulay2 Engine: FrobbyAlexanderDual
FrobbyAlexanderDual()
static MonomialIdeal* FrobbyAlexanderDual (const MonomialIdeal * I, const mpz_t * topvec) static
Definition at line 323 of file monomial-ideal.cpp.
 {
   int nv = I->topvar() + 1;
   exponents_t exp = newarray_atomic(int, nv);
   Frobby::Ideal F(nv);
   for (Bag& b : *I)
     {
       varpower::to_expvector(nv, b.monom().raw(), exp);
       if (M2_gbTrace >= 4) fprintf(stderr, "adding ");
       for (int j = 0; j < nv; j++)
         {
           if (M2_gbTrace >= 4) fprintf(stderr, "%d ", exp[j]);
           F.addExponent(exp[j]);
         }
       if (M2_gbTrace >= 4) fprintf(stderr, "\n");
     }
   // Now create the consumer object, and call Frobby
   MyIdealConsumer M(I->get_ring(), nv);
   Frobby::alexanderDual(F, topvec, M);
   freemem(exp);
   // Extract the answer as a MonomialIdeal
   return M.result();
 }
References mpfr::exp(), freemem(), MonomialIdeal::get_ring(), M2_gbTrace, newarray_atomic, MyIdealConsumer::result(), varpower::to_expvector(), and MonomialIdeal::topvar().
Referenced by wrapperFrobbyAlexanderDual().