Macaulay2 Engine: alexDual
alexDual()
static MonomialIdeal* alexDual (const MonomialIdeal * I, const M2_arrayint top, int strategy) static
Definition at line 382 of file monomial-ideal.cpp.
 {
   if (I->topvar() < 0)
     strategy =
         1;  // i.e. don't use frobby if there are no generators and/or variables
   switch (strategy)
     {
       case 0:
         if (M2_gbTrace >= 1) emit_line(" -- [Alexander dual: frobby]");
         return wrapperFrobbyAlexanderDual(I, top);
       default:
         if (M2_gbTrace >= 1) emit_line(" -- [Alexander dual: M2 monideal]");
         return I->alexander_dual(top);
     }
 }
References MonomialIdeal::alexander_dual(), emit_line(), M2_gbTrace, MonomialIdeal::topvar(), and wrapperFrobbyAlexanderDual().
Referenced by rawAlexanderDual().