Macaulay2 Engine: rawSaturateMonomialIdeal1
rawSaturateMonomialIdeal1()
const MonomialIdeal* rawSaturateMonomialIdeal1 (const MonomialIdeal * I, const EngineMonomial * a)
Definition at line 159 of file monomial-ideal.cpp.
 {
   try
     {
       MonomialIdeal *result = I->erase(a->ints());
       intern_monideal(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References MonomialIdeal::erase(), ERROR(), intern_monideal(), and EngineMonomial::ints().