Macaulay2 Engine: IM2_MonomialIdeal_is_equal
IM2_MonomialIdeal_is_equal()
int IM2_MonomialIdeal_is_equal (const MonomialIdeal * I, const MonomialIdeal * J)
Definition at line 67 of file monomial-ideal.cpp.
 {
   try
     {
       if (I->get_ring() != J->get_ring()) return false;
       return I->is_equal(*J);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return -1;
   }
 }
References ERROR(), MonomialIdeal::get_ring(), and MonomialIdeal::is_equal().