Macaulay2 Engine: rawSaturateMonomialIdeal2
rawSaturateMonomialIdeal2()
const MonomialIdeal* rawSaturateMonomialIdeal2 (const MonomialIdeal * I, const MonomialIdeal * J)
Definition at line 175 of file monomial-ideal.cpp.
 {
   try
     {
       if (I->get_ring() != J->get_ring())
         {
           ERROR("expected ideals in the same ring");
           return 0;
         }
       MonomialIdeal *result = I->sat(*J);
       intern_monideal(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References ERROR(), MonomialIdeal::get_ring(), intern_monideal(), and MonomialIdeal::sat().