Macaulay2 Engine: Matrix::iterator::row
row()
int Matrix::iterator::row () inline
Definition at line 256 of file matrix.hpp.
 { return v->comp; }
References v.
Referenced by MutableMatrix::from_matrix(), IM2_Matrix_lift(), IM2_Matrix_promote(), matrixToStream(), and Matrix::transpose().