Macaulay2 Engine: Matrix::iterator::set
set()
void Matrix::iterator::set (int newcol) inline
Definition at line 249 of file matrix.hpp.
     {
       col = newcol;
       v = M->elem(col);
     }
References col, Matrix::elem(), M, and v.
Referenced by Matrix::computeHashValue(), MutableMatrix::from_matrix(), IM2_Matrix_lift(), IM2_Matrix_promote(), matrixToStream(), and Matrix::transpose().