Macaulay2 Engine: SchreyerFrame::debugCheckOrder
debugCheckOrder()
bool SchreyerFrame::debugCheckOrder (int lev) const
Definition at line 617 of file res-schreyer-frame.cpp.
 {
   if (lev == 0) return true;
   bool result = true;
   auto& mylevel = level(lev);
   auto& myorder = schreyerOrder(lev - 1);
   int which = 0;
   for (auto i = mylevel.cbegin(); i != mylevel.cend(); ++i, ++which)
     {
       if (!check_poly(ring(), i->mSyzygy, myorder))
         {
           std::cout << "Error: terms of polynomial at level " << lev
                     << " location " << which << " not in order" << std::endl;
           std::cout << "  poly = ";
           display_poly(std::cout, ring(), i->mSyzygy);
           std::cout << std::endl;
           result = false;
         }
     }
   return result;
 }
References check_poly(), display_poly(), level(), ring(), and schreyerOrder().
Referenced by debugCheckOrderAll().