Macaulay2 Engine: SchreyerFrame::ring
ring()
const ResPolyRing& SchreyerFrame::ring () const inline
Definition at line 89 of file res-schreyer-frame.hpp.
 { return mRing; }
References mRing.
Referenced by computeIdealQuotient(), debugCheckOrder(), DegreeZeroMapGenerator::iterator::increment(), insertLevelOne(), DegreeZeroMapGenerator::numNonzero(), show(), showMemoryUsage(), ResF4toM2Interface::to_M2_matrix(), and ResF4toM2Interface::to_M2_MutableMatrix().