Macaulay2 Engine: SchreyerFrame::computeFrame
computeFrame()
bool SchreyerFrame::computeFrame ()
Definition at line 92 of file res-schreyer-frame.cpp.
 {
   if (mState == Initializing)
     {
       std::cout << "error: calling computeFrame too soon" << std::endl;
     }
   if (mState != Frame) return true;  // already computed
   // Uses mCurrentLevel
   while (mCurrentLevel < mFrame.mLevels.size())
     {
       if (M2_gbTrace >= 1)
         std::cout << "maxsize = " << mFrame.mLevels.size()
                   << " and mCurrentLevel = " << mCurrentLevel << std::endl;
       if (computeNextLevel() == 0) break;  // increments mCurrentLevel
       //      if (interrupted) return false;
     }
   //  show(-1);
   // Now change the state of the computation
   mState = Matrices;
   mCurrentLevel = 2;
   getBounds(mLoSlantedDegree, mHiSlantedDegree, mMaxLength);
   mSlantedDegree = mLoSlantedDegree;
   setBettiDisplays();  // Also sets mMinimalizeTODO
   if (M2_gbTrace >= 1)
     {
       std::cout << "non-minimal betti: " << std::endl;
       mBettiNonminimal.output();
     }
   // for (int i=0; i<mMinimalizeTODO.size(); i++)
   //  {
   //     auto a = mMinimalizeTODO[i];
   //     std::cout << "(" << a.first << "," << a.second << ") ";
   //  }
   // std::cout << std::endl;
   return true;
 }
References computeNextLevel(), getBounds(), Initializing, M2_gbTrace, Matrices, mBettiNonminimal, mCurrentLevel, mFrame, mHiSlantedDegree, SchreyerFrame::Frame::mLevels, mLoSlantedDegree, mMaxLength, mSlantedDegree, mState, BettiDisplay::output(), and setBettiDisplays().
Referenced by getBetti(), minimalBettiNumbers(), and start_computation().