Macaulay2 Engine: SchreyerFrame::monomialBlock
monomialBlock()
ResMemoryBlock<res_monomial_word>& SchreyerFrame::monomialBlock () inline
Definition at line 94 of file res-schreyer-frame.hpp.
 { return mMonomialSpace; }
References mMonomialSpace.
Referenced by computeIdealQuotient(), insertBasic(), and insertLevelZero().