Macaulay2 Engine: SchreyerFrame::insertLevelOne
insertLevelOne()
bool SchreyerFrame::insertLevelOne (res_packed_monomial monom, int degree, ResPolynomial & syzygy)
Definition at line 633 of file res-schreyer-frame.cpp.
 {
   insertBasic(1, monom, deg);  // deg is the actual degree of this element.
   component_index comp = monoid().get_component(monom);
   auto last = static_cast<component_index>(level(1).size());
   auto& p = level(0)[comp];
   if (p.mBegin == -1) p.mBegin = last - 1;
   p.mEnd = last;
   if (!check_poly(ring(), syzygy, schreyerOrder(0)))
     {
       if (M2_gbTrace >= 1)
         {
           std::cout
               << "Error: expected terms of polynomial to be in order, in poly#"
               << last << ": ";
           display_poly(std::cout, ring(), syzygy);
           std::cout << std::endl;
         }
       return false;
     }
   std::swap(level(1)[level(1).size() - 1].mSyzygy, syzygy);
   return true;
 }
References check_poly(), display_poly(), ResMonoidDense::get_component(), insertBasic(), level(), M2_gbTrace, monoid(), p, ring(), schreyerOrder(), and swap.