Macaulay2 Engine: SchreyerFrame::insertLevelZero
insertLevelZero()
void SchreyerFrame::insertLevelZero (res_packed_monomial monom, int degree, int maxdeglevel0)
Definition at line 617 of file res-schreyer-frame.cpp.
 {
   auto& myframe = level(0);
   long idx = myframe.size();
   myframe.emplace_back(FrameElement(monom, degree));
   auto& myelem = myframe[idx];
   auto& myorder = schreyerOrder(0);
   auto myTotalMonom =
       monomialBlock().allocate(monoid().monomial_size(myelem.mMonom));
   // Create the total monomial.  It is monom * (firstvar)^(maxdeglevel0-degree)
   monoid().copy(myelem.mMonom, myTotalMonom);
   myorder.mTotalMonom.push_back(myTotalMonom);
 }
References ResMemoryBlock< T, NSLAB >::allocate(), ResMonoidDense::copy(), degree(), level(), monoid(), monomialBlock(), and schreyerOrder().