Macaulay2 Engine: SchreyerFrame::setSchreyerOrder
setSchreyerOrder()
void SchreyerFrame::setSchreyerOrder (int lev)
Definition at line 562 of file res-schreyer-frame.cpp.
 {
   auto& myframe = level(lev);
   auto& myorder = schreyerOrder(lev);
   myorder.mTieBreaker.resize(myframe.size());
   //  std::cout << "setSchreyerOrder: entering, lev=" << lev << ", nelems=" <<
   //  myframe.size() << std::endl;
   if (lev == 0)
     {
       for (component_index i = 0; i < myorder.mTieBreaker.size(); i++)
         myorder.mTieBreaker[i] = i;
       return;
     }
   auto& prevorder = schreyerOrder(lev - 1);
   long* tiebreakers = new long[myframe.size()];
   auto n_frame_elems = myframe.size();
   for (component_index i = 0; i < n_frame_elems; i++)
     {
       component_index comp = monoid().get_component(myframe[i].mMonom);
       tiebreakers[i] = i + n_frame_elems * prevorder.mTieBreaker[comp];
     }
   std::stable_sort(tiebreakers, tiebreakers + n_frame_elems);
   for (component_index i = 0; i < n_frame_elems; i++)
     {
       myorder.mTieBreaker[tiebreakers[i] % n_frame_elems] = i;
     }
   delete[] tiebreakers;
   //  std::cout << "  setSchreyerOrder: exiting, lev=" << lev << std::endl;
 }
References ResMonoidDense::get_component(), level(), monoid(), and schreyerOrder().
Referenced by computeNextLevel(), and endLevel().