Macaulay2 Engine: SchreyerFrame::showMemoryUsage
showMemoryUsage()
void SchreyerFrame::showMemoryUsage () const
Definition at line 701 of file res-schreyer-frame.cpp.
 {
   std::cout << "Frame memory usage" << std::endl;
   // widths: level: 6, #elems: 8, used: 6, allocated: 11
   std::cout << " level"
             << "   #elems"
             << "   used"
             << "   allocated"
             << "     nterms"
             << "       poly"
             << "   polalloc" << std::endl;
   long alloc = 0;
   long used = 0;
   long nelems = 0;
   long poly_used = 0;
   long poly_alloc = 0;
   long poly_nterms = 0;
   long poly_used_level = 0;
   long poly_alloc_level = 0;
   long poly_nterms_level = 0;
   for (int i = 0; i < mFrame.mLevels.size(); i++)
     {
       long nelems_level = level(i).size();
       if (nelems_level == 0) continue;
       long used_level = nelems_level * sizeof(FrameElement);
       long alloc_level = level(i).capacity() * sizeof(FrameElement);
       poly_nterms_level = 0;
       poly_used_level = 0;
       poly_alloc_level = 0;
       for (int j = 0; j < nelems_level; j++)
         {
           ring().memUsage(level(i)[j].mSyzygy,
                           poly_nterms_level,
                           poly_used_level,
                           poly_alloc_level);
         }
       poly_nterms += poly_nterms_level;
       poly_used += poly_used_level;
       poly_alloc += poly_alloc_level;
       std::cout << std::setw(6) << i << " " << std::setw(8) << nelems_level
                 << " " << std::setw(6) << used_level << " " << std::setw(11)
                 << alloc_level << " " << std::setw(10) << poly_nterms_level
                 << " " << std::setw(10) << poly_used_level << " "
                 << std::setw(10) << poly_alloc_level << std::endl;
       nelems += nelems_level;
       used += used_level;
       alloc += alloc_level;
     }
   std::cout << "   all"
             << " " << std::setw(8) << nelems << " " << std::setw(6) << used
             << " " << std::setw(11) << alloc << " " << std::setw(10)
             << poly_nterms << " " << std::setw(10) << poly_used << " "
             << std::setw(10) << poly_alloc << std::endl;
   long monomSpace = mMonomialSpace.memoryUsage();
   long monomUsed =
       nelems * monoid().max_monomial_size() * sizeof(monomial_word);
   std::cout << "monomials     " << std::setw(6) << monomUsed << " "
             << std::setw(11) << monomSpace << std::endl;
   std::cout << "total mem     " << std::setw(6)
             << (used + monomUsed + poly_used) << " " << std::setw(11)
             << (alloc + monomSpace + poly_alloc) << std::endl;
 }
References level(), ResMonoidDense::max_monomial_size(), ResMemoryBlock< T, NSLAB >::memoryUsage(), ResPolyRing::memUsage(), mFrame, SchreyerFrame::Frame::mLevels, mMonomialSpace, monoid(), and ring().
Referenced by minimalBettiNumbers(), show(), and start_computation().