Macaulay2 Engine: SchreyerFrame::computeRank
computeRank()
void SchreyerFrame::computeRank (int slanted_degree, int lev) private
Definition at line 951 of file res-schreyer-frame.cpp.
 {
   //  std::cout << "computeRank(" << slanted_degree << "," << lev << ")" <<
   //  std::endl;
   int& status = mComputationStatus.entry(slanted_degree, lev);
   if (status == 0) return;  // Nothing here
   if (status == 1)
     {
       fillinSyzygies(slanted_degree, lev);
     }
   if (status == 3) return;  // already done
   int rk = rank(slanted_degree, lev);
   if (rk > 0)
     {
       mBettiMinimal.entry(slanted_degree, lev) -= rk;
       if (slanted_degree <= mHiSlantedDegree and lev > 0)
         mBettiMinimal.entry(slanted_degree + 1, lev - 1) -= rk;
     }
   status = 3;
 }
References BettiDisplay::entry(), fillinSyzygies(), mBettiMinimal, mComputationStatus, and rank().
Referenced by computeRanks(), and minimalBettiNumbers().