Macaulay2 Engine: SchreyerFrame::monoid
monoid()
const ResMonoid& SchreyerFrame::monoid () const inline
Definition at line 87 of file res-schreyer-frame.hpp.
 { return mRing.monoid(); }
References ResPolyRing::monoid(), and mRing.
Referenced by computeIdealQuotient(), createQuotientElement(), DegreeZeroMapGenerator::iterator::increment(), insertBasic(), insertLevelOne(), insertLevelZero(), minimalBettiNumbers(), DegreeZeroMapGenerator::numNonzero(), SchreyerFrame(), setSchreyerOrder(), show(), showMemoryUsage(), ResF4toM2Interface::to_M2_freemodule(), and ResF4toM2Interface::to_M2_MutableMatrix().