Macaulay2 Engine: SchreyerFrame::computeIdealQuotient
computeIdealQuotient()
component_index SchreyerFrame::computeIdealQuotient (int lev, component_index begin, component_index elem) private
std::cout << "computeIdealQuotient(" << lev << "," << begin << "," << elem << ")" << std::endl;
Definition at line 470 of file res-schreyer-frame.cpp.
 {
   // Returns the number of elements added
   res_packed_monomial m = monomial(lev, elem);
   std::vector<PreElement*> elements;
   if (ring().isSkewCommutative())
     {
       auto skewvars = new int[ring().monoid().n_vars()];
       int a = ring().monoid().skew_vars(ring().skewInfo(), m, skewvars);
       // std::cout << "adding " << a << " syz from skew" << std::endl;
       for (int i = 0; i < a; ++i)
         {
           PreElement* vp = mPreElements.allocate();
           vp->vp = mVarpowers.reserve(mMaxVPSize);
           monoid().variable_as_vp(skewvars[i], vp->vp);
           vp->degree = monoid().degree_of_vp(vp->vp);
           int len = static_cast<int>(res_varpower_monomials::length(vp->vp));
           mVarpowers.intern(len);
           elements.push_back(vp);
         }
       delete[] skewvars;
     }
   for (component_index i = begin; i < elem; i++)
     elements.push_back(createQuotientElement(monomial(lev, i), m));
   typedef ResF4MonomialLookupTableT<int32_t> MonomialLookupTable;
   MonomialLookupTable montab(monoid().n_vars());
 #if 0
   std::cout << "  #pre elements = " << elements.size() << std::endl;
   for (auto i=elements.begin(); i != elements.end(); ++i)
     {
       varpower_monomials::elem_text_out(stdout, (*i)->vp);
       fprintf(stdout, "\n");
     }
 #endif
   PreElementSorter C;
   std::stable_sort(elements.begin(), elements.end(), C);
   component_index n_elems = 0;
   for (auto i = elements.begin(); i != elements.end(); ++i)
     {
       int32_t not_used;
       bool inideal = montab.find_one_divisor_vp(0, (*i)->vp, not_used);
       if (inideal) continue;
       // Now we create a res_packed_monomial, and insert it into 'lev+1'
       montab.insert_minimal_vp(0, (*i)->vp, 0);
       res_packed_monomial monom =
           monomialBlock().allocate(monoid().max_monomial_size());
       monoid().from_varpower_monomial((*i)->vp, elem, monom);
       // Now insert it into the frame
       insertBasic(currentLevel(),
                   monom,
                   (*i)->degree + degree(currentLevel() - 1,
                                         monoid().get_component(monom)));
       n_elems++;
     }
   // std::cout << "  returns " << n_elems << std::endl;
   return n_elems;
 }
References ResMemoryBlock< T, NSLAB >::allocate(), begin(), createQuotientElement(), currentLevel(), SchreyerFrameTypes::PreElement::degree, degree(), ResMonoidDense::degree_of_vp(), ExponentList< E, L >::elem_text_out(), F4MonomialLookupTableT< Key >::find_one_divisor_vp(), ResMonoidDense::from_varpower_monomial(), F4MonomialLookupTableT< Key >::insert_minimal_vp(), insertBasic(), ResMemoryBlock< T, NSLAB >::intern(), ExponentList< E, L >::length(), mMaxVPSize, ResPolyRing::monoid(), monoid(), monomial(), monomialBlock(), mPreElements, mVarpowers, ResMonoidDense::n_vars(), ResMemoryBlock< T, NSLAB >::reserve(), ring(), ResMonoidDense::skew_vars(), ResMonoidDense::variable_as_vp(), and SchreyerFrameTypes::PreElement::vp.
Referenced by computeNextLevel().