Macaulay2 Engine: SchreyerFrame::fillinSyzygies
fillinSyzygies()
void SchreyerFrame::fillinSyzygies (int slanted_deg, int lev) private
Definition at line 917 of file res-schreyer-frame.cpp.
 {
   // Fill in syzygies of slanted degree mSlantedDegree, at level mCurrentLevel =
   // 2.
   // Assumption/prereq:
   // Compute the matrix at this level, where lev >= 2. (lev=0,1 have already
   // been filled in).
   // Prereqs: fillin(i,lev-1) has been called, for all i <= slanted_degree.
   // WARNING: this is not currently checked or remembered.
   int& status = mComputationStatus.entry(slanted_deg, lev);
   if (status != 1) return;
   if (M2_gbTrace >= 2)
     {
 //      std::cout << "construct(" << slanted_deg << ", " << lev << ")"
 //                << std::endl;
     }
   // experimenting whether building/destroying local computers
   // are expensive
   F4Res thisComputer {*this};
   thisComputer.construct(lev, slanted_deg + lev);
   //mComputer->construct(lev, slanted_deg + lev);
   status = 2;
   if (M2_gbTrace >= 2)
     {
       //std::cout << "done" << std::endl;
       //std::cout << "#additions so far: " << vectorArithmetic().getNumAdditions()
       //          << std::endl;
     }
 }
References F4Res::construct(), BettiDisplay::entry(), M2_gbTrace, and mComputationStatus.
Referenced by computeRank(), and computeSyzygies().