Macaulay2 Engine: SchreyerFrame::minimalBettiNumbers
minimalBettiNumbers()
BettiDisplay SchreyerFrame::minimalBettiNumbers (bool stop_after_degree, int top_slanted_degree, int length_limit)
hi: . . . . . .
Definition at line 141 of file res-schreyer-frame.cpp.
{
  // The lo degree will be: mLoSlantedDegree.
  // The highest slanted degree will either be mHiSlantedDegree, or
  // top_slanted_degree (minimum of these two).
  // The length we need to compute to is either maxLevel(), or length_limit+1.
  // We set maxlevel to length_limit.  We insist that length_limit <= maxLevel()
  // - 2.
  // Here is what needs to be computed:
  //  lo: . . . . . . .
  //      . . . . . . .
  // Each dot in all rows other than 'hi' needs to have syzygies computed for
  // it.
  // if hi == mHiSlantedDegree, then we do NOT need to compute syzygies in this
  // last row.
  //   else we need to compute syzygies in these rows, EXCEPT not at level
  //   maxlevel+1
  computeFrame();
  int top_degree;  // slanted degree
  if (stop_after_degree)
    {
      top_degree = std::min(top_slanted_degree, mHiSlantedDegree);
      top_degree = std::max(mLoSlantedDegree, top_degree);
    }
  else
    {
      top_degree = mHiSlantedDegree;
    }
  // First: if length_limit is too low, extend the Frame
  if (length_limit >= maxLevel())
    {
      std::cout << "WARNING: cannot extend resolution length" << std::endl;
      length_limit = maxLevel() - 1;
      // Extend the length of the Frame, change mMaxLength, possibly
      // mHiSlantedDegree
      // increase mComputationStatus if needed, mMinimalBetti, ...
      // computeFrame()
    }
#if defined(WITH_TBB)
  // build the dependency graph
  if (mParallelizeByDegree)
  {
    //std::cout << "In dep graph" << std::endl;
     mScheduler.execute([&] {
        makeDependencyGraph(mDepGraph,length_limit+1,top_degree - mLoSlantedDegree+1,true);
        mDepGraph.startComputation();
        mDepGraph.waitForCompletion();
     });
     //std::cout << "Out dep graph" << std::endl;
  }
  // If this is not run, the 'computeRanks' calls below compute all of these elements
#endif
  // What needs to be computed?
  // lodeg..hideg, level: 0..maxlevel.  Note: need to compute at level
  // maxlevel+1 in order to get min betti numbers at
  //   level maxlevel.
  // Also note: if hideg is the highest degree that occurs in the frame, we do
  // not need to compute any matrices for these.
  for (int deg = mLoSlantedDegree; deg <= top_degree - 1; deg++)
    for (int lev = 1; lev <= length_limit + 1; lev++)
      {
        computeRank(deg, lev);
      }
  for (int lev = 1; lev <= length_limit; lev++)
    {
      computeRank(top_degree, lev);
    }
  if (M2_gbTrace >= 1)
    {
      std::cout << "displaying stats" << std::endl;
      showMemoryUsage();
      monoid().show();
      std::cout << "total setPoly: " << ResPolynomialConstructor::ncalls << std::endl;
      std::cout << "total setPolyFromArray: "
                << ResPolynomialConstructor::ncalls_fromarray << std::endl;
      std::cout << "total ~ResPolynomial: " << ResPolynomial::npoly_destructor << std::endl;
      std::cout << "total time for make matrix: " << timeMakeMatrix
                << std::endl;
      std::cout << "total time for sort matrix: " << timeSortMatrix
                << std::endl;
      std::cout << "total time for reorder matrix: " << timeReorderMatrix
                << std::endl;
      std::cout << "total time for gauss matrix: " << timeGaussMatrix
                << std::endl;
      std::cout << "total time for clear matrix: " << timeClearMatrix
                << std::endl;
      std::cout << "total time for reset hash table: " << timeResetHashTable
                << std::endl;
      std::cout << "total time for computing ranks: " << timeComputeRanks
                << std::endl;
      std::cout << "total time for computing sparse ranks: " << timeComputeSparseRanks
                << std::endl;
    }
  BettiDisplay B(mBettiMinimal);  // copy
  B.resize(mLoSlantedDegree, top_degree, length_limit);
  return B;
}
References computeFrame(), computeRank(), M2_gbTrace, makeDependencyGraph(), maxLevel(), mBettiMinimal, mHiSlantedDegree, mLoSlantedDegree, monoid(), mParallelizeByDegree, ResPolynomialConstructor::ncalls, ResPolynomialConstructor::ncalls_fromarray, ResPolynomial::npoly_destructor, BettiDisplay::resize(), ResMonoidDense::show(), showMemoryUsage(), timeClearMatrix, timeComputeRanks, timeComputeSparseRanks, timeGaussMatrix, timeMakeMatrix, timeReorderMatrix, timeResetHashTable, and timeSortMatrix.
Referenced by F4ResComputation::minimal_betti().