Macaulay2 Engine: SchreyerFrame::getBettiFrame
getBettiFrame()
M2_arrayint SchreyerFrame::getBettiFrame () const
Definition at line 972 of file res-schreyer-frame.cpp.
 {
   int lo, hi, len;
   getBounds(lo, hi, len);
   //  std::cout << "bounds: lo=" << lo << " hi=" << hi << " len=" << len <<
   //  std::endl;
   BettiDisplay B(lo, hi, len);
   // now set B
   for (int lev = 0; lev <= len; lev++)
     {
       auto& myframe = level(lev);
       for (auto p = myframe.begin(); p != myframe.end(); ++p)
         {
           int deg = p->mDegree;  // this is actual degree, not slanted degree
           B.entry(deg - lev, lev)++;
         }
     }
   return B.getBetti();
 }
References BettiDisplay::entry(), BettiDisplay::getBetti(), getBounds(), level(), and p.
Referenced by getBetti().