Macaulay2 Engine: SchreyerFrame::rankUsingDenseMatrixFlint
rankUsingDenseMatrixFlint()
template<typename Gen > int SchreyerFrame::rankUsingDenseMatrixFlint (Gen & D, bool transposed = true)
Definition at line 792 of file res-f4-m2-interface.cpp.
 {
   unsigned int charac =
       static_cast<unsigned int>(gausser().get_ring()->characteristic());
   M2::ARingZZpFlint R(charac);
   DMat<M2::ARingZZpFlint> M(R, 0, 0);
   if (!transposed)
     setDMatFromSparseMatrixGenerator(D, M);
   else
     setDMatFromSparseMatrixGeneratorTransposed(D, M);
   auto a = DMatLinAlg<M2::ARingZZpFlint>(M);
   //  std::cout << "---- dense matrix ----" << std::endl;
   //  displayMat(M);
   //  std::cout << "----------------------" << std::endl;
   auto timeA = timer();
   int rk = static_cast<int>(a.rank());
   auto timeB = timer();
   double nsecs = seconds(timeB - timeA);
   timeComputeRanks += nsecs;
   if (M2_gbTrace >= 2)
     {
       if (M.numRows() > 0 and M.numColumns() > 0)
         std::cout << "   dense rank = " << rk
                   << " time = " << nsecs << " sec"
                   << std::endl;
     }
   return rk;
 }
References Ring::characteristic(), gausser(), ResGausser::get_ring(), M2_gbTrace, DMat< M2::ARingZZpFlint >::numColumns(), DMat< M2::ARingZZpFlint >::numRows(), seconds(), setDMatFromSparseMatrixGenerator(), setDMatFromSparseMatrixGeneratorTransposed(), timeComputeRanks, and timer().