Macaulay2 Engine: SchreyerFrame::rankUsingDenseMatrix
rankUsingDenseMatrix()
template<typename Gen > int SchreyerFrame::rankUsingDenseMatrix (Gen & D, bool transposed = true)
Definition at line 615 of file res-f4-m2-interface.cpp.
 {
   unsigned int charac =
       static_cast<unsigned int>(vectorArithmetic().ring()->characteristic());
   M2::ARingZZpFFPACK R(charac);
   DMat<M2::ARingZZpFFPACK> M(R, 0, 0);
   if (!transposed)
     setDMatFromSparseMatrixGenerator(D, M);
   else
     setDMatFromSparseMatrixGeneratorTransposed(D, M);
   auto a = DMatLinAlg<M2::ARingZZpFFPACK>(M);
   //  std::cout << "---- dense matrix ----" << std::endl;
   //  displayMat(M);
   //  std::cout << "----------------------" << std::endl;
   auto timeA = timer();
   int rk = static_cast<int>(a.rank());
   auto timeB = timer();
   double nsecs = seconds(timeB - timeA);
   timeComputeRanks += nsecs;
   if (M2_gbTrace >= 2)
     {
       if (M.numRows() > 0 and M.numColumns() > 0)
         std::cout << "   dense rank = " << rk
                   << " time = " << nsecs << " sec"
                   << std::endl;
     }
   return rk;
 }
References Ring::characteristic(), M2_gbTrace, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), VectorArithmetic::ring(), seconds(), setDMatFromSparseMatrixGenerator(), setDMatFromSparseMatrixGeneratorTransposed(), timeComputeRanks, timer(), and vectorArithmetic().
Referenced by rank().