Macaulay2 Engine: SchreyerFrame::computeRanks
computeRanks()
void SchreyerFrame::computeRanks (int slanted_degree, int maxlevel)
Definition at line 864 of file res-schreyer-frame.cpp.
 {
   // Compute all needed ranks to get the minimal Betti numbers in the range
   // deg <= slanted_degree, lev <=maxlevel.
   // This means: we need to compute ranks to level maxlevel+1 (or largest that
   // exists)
   // in degrees <= slanted_degree, EXCEPT we don't need to compute at
   // (slanted_degree,maxlevel+1).
   int toplevel = (maxlevel < maxLevel() ? maxlevel - 1 : mMaxLength);
   for (int deg = mLoSlantedDegree; deg <= slanted_degree; deg++)
     for (int lev = 1; lev <= toplevel; lev++) computeRank(deg, lev);
 }
References computeRank(), maxLevel(), mLoSlantedDegree, and mMaxLength.
Referenced by getBetti(), and start_computation().