Macaulay2 Engine: SchreyerFrame::computeSyzygies
computeSyzygies()
void SchreyerFrame::computeSyzygies (int slanted_degree, int maxlevel)
Definition at line 852 of file res-schreyer-frame.cpp.
 {
   // Compute everything up to this point
   int toplevel = (maxlevel < maxLevel() ? maxlevel : maxLevel());
   for (int deg = mLoSlantedDegree; deg <= slanted_degree; deg++)
     for (int lev = 2; lev <= toplevel; lev++)
       {
         fillinSyzygies(deg, lev);
       }
   //  show(-1);
 }
References fillinSyzygies(), maxLevel(), and mLoSlantedDegree.
Referenced by start_computation().