Macaulay2 Engine: SchreyerFrame::degree
degree()
int SchreyerFrame::degree (int lev, component_index component) const inline private
Definition at line 168 of file res-schreyer-frame.hpp.
   {
     return level(lev)[component].mDegree;
   }
References level().
Referenced by computeIdealQuotient(), insertBasic(), and insertLevelZero().