Macaulay2 Engine: SchreyerFrame::getBounds
getBounds()
void SchreyerFrame::getBounds (int & loDegree, int & hiDegree, int & length) const
Definition at line 756 of file res-schreyer-frame.cpp.
 {
   if (mFrame.mLevels.size() == 0 or mFrame.mLevels[0].mElements.size() == 0)
     {
       loDegree = 0;
       hiDegree = -1;
       length = 0;
       return;
     }
   length = 0;
   auto& lev0 = level(0);
   loDegree = hiDegree = static_cast<int>(lev0[0].mDegree);
   for (int lev = 0; lev < mFrame.mLevels.size(); lev++)
     {
       auto& myframe = level(lev);
       if (myframe.size() == 0) return;
       length = lev;
       for (auto p = myframe.begin(); p != myframe.end(); ++p)
         {
           int deg = p->mDegree;
           deg -= lev;  // slanted degree
           if (deg < loDegree) loDegree = deg;
           if (deg > hiDegree) hiDegree = deg;
         }
     }
   //  show();
 }
References level(), mFrame, SchreyerFrame::Frame::mLevels, and p.
Referenced by computeFrame(), getBettiFrame(), setBettiDisplays(), and start_computation().