Macaulay2 Engine: SchreyerFrame::level
level() [1/2]
std::vector<FrameElement>& SchreyerFrame::level (int lev) inline
Definition at line 182 of file res-schreyer-frame.hpp.
   {
     return mFrame.mLevels[lev].mElements;
   }
References mFrame, and SchreyerFrame::Frame::mLevels.
Referenced by computeNextLevel(), debugCheckOrder(), degree(), DegreeZeroMapGenerator::DegreeZeroMapGenerator(), F4Res::findDivisor(), F4Res::gaussReduce(), getBettiFrame(), getBounds(), insertBasic(), insertLevelOne(), insertLevelZero(), F4Res::loadRow(), F4Res::makeMatrix(), memoryUsage(), monomial(), DegreeZeroMapGenerator::numNonzero(), F4Res::processMonomialProduct(), setBettiDisplays(), setSchreyerOrder(), show(), showMemoryUsage(), ResF4toM2Interface::to_M2_freemodule(), ResF4toM2Interface::to_M2_matrix(), and ResF4toM2Interface::to_M2_MutableMatrix().