Macaulay2 Engine: SchreyerFrame::maxLevel
maxLevel()
int SchreyerFrame::maxLevel () const inline
Definition at line 182 of file res-schreyer-frame.hpp.
 { return static_cast<int>(mFrame.mLevels.size() - 1); }
References mFrame, and SchreyerFrame::Frame::mLevels.
Referenced by computeRanks(), computeSyzygies(), debugCheckOrderAll(), DegreeZeroMapGenerator::DegreeZeroMapGenerator(), getBetti(), F4ResComputation::minimal_betti(), minimalBettiNumbers(), setBettiDisplays(), ResF4toM2Interface::to_M2_freemodule(), ResF4toM2Interface::to_M2_matrix(), and ResF4toM2Interface::to_M2_MutableMatrix().