Macaulay2 Engine: SchreyerFrame::getBetti
getBetti()
M2_arrayint SchreyerFrame::getBetti (int type)
Definition at line 428 of file res-schreyer-frame.cpp.
 {
   if (type == 4)
     {
       computeFrame();
       decltype(timer()) timeA, timeB;
       timeA = timer();
       computeRanks(mHiSlantedDegree, maxLevel());
       timeB = timer();
       timeComputeRanks += seconds(timeB - timeA);
       return mBettiMinimal.getBetti();
     }
   if (type == 0 or type == 1) return getBettiFrame();
   if (type == 5) return mComputationStatus.getBetti();
   ERROR("betti display not implemented yet");
   return nullptr;
 }
References computeFrame(), computeRanks(), ERROR(), BettiDisplay::getBetti(), getBettiFrame(), maxLevel(), mBettiMinimal, mComputationStatus, mHiSlantedDegree, seconds(), timeComputeRanks, and timer().