Macaulay2 Engine: SchreyerFrame::insertBasic
insertBasic()
void SchreyerFrame::insertBasic (int lev, res_packed_monomial monom, int degree)
Definition at line 595 of file res-schreyer-frame.cpp.
 {
   assert(lev >= 1);  // Should not be called with lev==0.
   // if lev >= 2, then level(lev-1)[comp].(mBegin,mEnd) is set separately.
   auto& myframe = level(lev);
   long idx = myframe.size();
   myframe.emplace_back(FrameElement(monom, degree));
   auto& myelem = myframe[idx];
   myelem.mSyzygy.coeffs = vectorArithmetic().allocateElementArray();
   // The rest of this code simply sets the total monomial for the Schreyer order
   // and should be moved out of here. (MES 3 Feb 2016)
   auto& myorder = schreyerOrder(lev);
   auto myTotalMonom = monomialBlock().allocate(monoid().max_monomial_size());
   auto& prevorder = schreyerOrder(lev - 1);
   component_index comp = monoid().get_component(myelem.mMonom);
   monoid().unchecked_mult(
       myelem.mMonom, prevorder.mTotalMonom[comp], myTotalMonom);
   monoid().set_component(monoid().get_component(prevorder.mTotalMonom[comp]),
                          myTotalMonom);
   myorder.mTotalMonom.push_back(myTotalMonom);
 }
References ResMemoryBlock< T, NSLAB >::allocate(), VectorArithmetic::allocateElementArray(), degree(), ResMonoidDense::get_component(), level(), monoid(), monomialBlock(), schreyerOrder(), ResMonoidDense::set_component(), ResMonoidDense::unchecked_mult(), and vectorArithmetic().
Referenced by computeIdealQuotient(), and insertLevelOne().