Macaulay2 Engine: SchreyerFrame::vectorArithmetic
vectorArithmetic()
const VectorArithmetic & SchreyerFrame::vectorArithmetic () const inline
Definition at line 90 of file res-schreyer-frame.hpp.
{ return mRing.vectorArithmetic(); }
References mRing, and ResPolyRing::vectorArithmetic().
Referenced by DegreeZeroMapGenerator::iterator::increment(), insertBasic(), rankUsingDenseMatrix(), rankUsingDenseMatrixFlint(), DegreeZeroMapGenerator::ring(), and ResF4toM2Interface::to_M2_MutableMatrix().