Macaulay2 Engine: SchreyerFrame::show
show()
void SchreyerFrame::show (int len) const
Definition at line 724 of file res-schreyer-frame.cpp.
 {
   std::cout << "#levels=" << mFrame.mLevels.size()
             << " currentLevel=" << currentLevel() << std::endl;
   for (int i = 0; i < mFrame.mLevels.size(); i++)
     {
       auto& myframe = level(i);
       auto& myorder = schreyerOrder(i);
       if (myframe.size() == 0) continue;
       std::cout << "--- level " << i << " ------" << std::endl;
       for (int j = 0; j < myframe.size(); j++)
         {
           std::cout << "    " << j << " " << myframe[j].mDegree << " ("
                     << myframe[j].mBegin << "," << myframe[j].mEnd << ") "
                     << std::flush;
           if (myframe[j].mSyzygy.coeffs.isNull())
             std::cout << "coeffs=null " << std::flush;
           std::cout << "(size:" << myframe[j].mSyzygy.len << ") [";
           monoid().showAlpha(myorder.mTotalMonom[j]);
           std::cout << "  " << myorder.mTieBreaker[j] << "] ";
           if (len == 0 or myframe[j].mSyzygy.len == 0)
             monoid().showAlpha(myframe[j].mMonom);
           else
             {
               display_poly(std::cout, ring(), myframe[j].mSyzygy);
             }
           std::cout << std::endl;
         }
     }
   showMemoryUsage();
 }
References currentLevel(), display_poly(), level(), mFrame, SchreyerFrame::Frame::mLevels, monoid(), ring(), schreyerOrder(), ResMonoidDense::showAlpha(), and showMemoryUsage().