Macaulay2 Engine: SchreyerFrame::rankUsingSparseMatrix
rankUsingSparseMatrix()
template<typename Gen > int SchreyerFrame::rankUsingSparseMatrix (Gen & D)
Definition at line 726 of file res-f4-m2-interface.cpp.
 {
   const Matrix* M = matrixFromSparseMatrixGenerator(D);
   //  std::cout << "--- sparse matrix ----" << std::endl;
   //  dmatrix(M);
   //  std::cout << "----------------------" << std::endl;
   auto timeA = timer();
   GaussElimComputation comp { M, 0, 0 };
   comp.set_stop_conditions(false, nullptr, -1, -1, -1, -1, -1, false, nullptr);
   comp.start_computation();
   //  const Matrix* gbM = comp.get_gb();
   //  std::cout << "--- gb of matrix ----" << std::endl;
   //  dmatrix(gbM);
   //  std::cout << "----------------------" << std::endl;
   int rk = comp.get_initial(-1)->n_cols();
   auto timeB = timer();
   double nsecs = seconds(timeB - timeA);
   timeComputeSparseRanks += nsecs;
   if (M2_gbTrace >= 2)
     {
       if (M->n_rows() > 0 and M->n_cols() > 0)
         std::cout << "  sparse rank = " << rk
                   << " time = " << nsecs << " sec"
                   << std::endl;
     }
   return rk;
 }
References M2_gbTrace, matrixFromSparseMatrixGenerator(), Matrix::n_cols(), Matrix::n_rows(), seconds(), timeComputeSparseRanks, and timer().
Referenced by rank().