Macaulay2 Engine: SchreyerFrame::computeNextLevel
computeNextLevel()
component_index SchreyerFrame::computeNextLevel ()
Definition at line 535 of file res-schreyer-frame.cpp.
 {
   if (currentLevel() == 1) return 0;
   if (currentLevel() >= mFrame.mLevels.size()) return 0;
   //  std::cout << "computeNextLevel: level = " << currentLevel() << std::endl;
   // loop through all the elements at level currentLevel()-2
   int level0 = currentLevel() - 2;
   int level1 = level0 + 1;
   component_index n_elems_added = 0;
   for (auto i = level(level0).begin(); i != level(level0).end(); ++i)
     {
       component_index begin = (*i).mBegin;
       component_index end = (*i).mEnd;
       for (component_index i = begin; i < end; ++i)
         {
           auto& elem = level(level1)[i];
           elem.mBegin = n_elems_added;
           n_elems_added += computeIdealQuotient(level1, begin, i);
           elem.mEnd = n_elems_added;
         }
     }
   setSchreyerOrder(mCurrentLevel);
   mCurrentLevel++;
   return n_elems_added;
 }
References begin(), computeIdealQuotient(), currentLevel(), end(), level(), mCurrentLevel, mFrame, SchreyerFrame::Frame::mLevels, and setSchreyerOrder().
Referenced by computeFrame(), and start_computation().