Macaulay2 Engine: SchreyerFrame::rank
rank()
int SchreyerFrame::rank (int slanted_degree, int lev)
Definition at line 824 of file res-f4-m2-interface.cpp.
 {
   DegreeZeroMapGenerator D(*this, slanted_degree, lev);
   long nnonzero = D.numNonzero();
   long nelements = static_cast<long>(D.numRows()) * static_cast<long>(D.numColumns());
   double nnonzeroD = static_cast<double>(nnonzero);
   double nelementsD = static_cast<double>(nelements);
   double frac_nonzero = (nelements > 0 ? nnonzeroD/nelementsD : 1.0);
   if (M2_gbTrace >= 2 and nelements > 0)
     {
       std::cout << "rank(" << slanted_degree << "," << lev << ") size = "
                 << D.numRows() << " x " << D.numColumns()
                 << " frac non-zero= " << frac_nonzero << std::endl << std::flush;
     }
   int rkSparse = -1;
   int rkDense = -1;
   if (frac_nonzero <= .007)
     {
       rkSparse = rankUsingSparseMatrix(D);
       return rkSparse;
     }
   else
     {
       rkDense = rankUsingDenseMatrix(D);
       return rkDense;
     }
 }
References M2_gbTrace, nelements, DegreeZeroMapGenerator::numColumns(), DegreeZeroMapGenerator::numNonzero(), DegreeZeroMapGenerator::numRows(), rankUsingDenseMatrix(), and rankUsingSparseMatrix().
Referenced by computeRank(), and start_computation().