Macaulay2 Engine: SchreyerFrame::createQuotientElement
createQuotientElement()
SchreyerFrame::PreElement * SchreyerFrame::createQuotientElement (res_packed_monomial m1, res_packed_monomial m) private
Definition at line 458 of file res-schreyer-frame.cpp.
 {
   PreElement* vp = mPreElements.allocate();
   vp->vp = mVarpowers.reserve(mMaxVPSize);
   monoid().quotient_as_vp(m1, m, vp->vp);
   vp->degree = monoid().degree_of_vp(vp->vp);
   int len = static_cast<int>(res_varpower_monomials::length(vp->vp));
   mVarpowers.intern(len);
   return vp;
 }
References SchreyerFrameTypes::PreElement::degree, ResMonoidDense::degree_of_vp(), ResMemoryBlock< T, NSLAB >::intern(), ExponentList< E, L >::length(), mMaxVPSize, monoid(), mPreElements, mVarpowers, ResMonoidDense::quotient_as_vp(), ResMemoryBlock< T, NSLAB >::reserve(), and SchreyerFrameTypes::PreElement::vp.
Referenced by computeIdealQuotient().