Macaulay2 Engine: DPolyTraverser::traverse
traverse()
void DPolyTraverser::traverse (const TowerPolynomial f)
Definition at line 1556 of file dpoly.cpp.
 {
   exponents_t exp = new int[D->nvars];
   for (size_t i = 0; i < D->nvars; i++) exp[i] = 0;
   traverse1(D->nlevels - 1,
             f,
             exp);  // the return value is only for the recursive algorithm
   delete[] exp;
 }
References D, mpfr::exp(), DPoly::nlevels, DPoly::nvars, and traverse1().
Referenced by TowerEvaluator::getValue().