Macaulay2 Engine: DPolyTraverser::traverse1
traverse1()
bool DPolyTraverser::traverse1 (int level, const TowerPolynomial g, exponents_t exp) private
Definition at line 1566 of file dpoly.cpp.
 {
   if (level == 0)
     {
       long *cfs = f->arr.ints;
       for (int i = f->deg; i >= 0; --i)
         if (cfs[i] != 0)
           {
             exp[level] = i;
             if (!viewTerm(cfs[i], exp)) return false;
           }
       exp[level] = 0;
     }
   else
     {
       TowerPolynomial *cfs = f->arr.polys;
       for (int i = f->deg; i >= 0; --i)
         if (cfs[i] != nullptr)
           {
             exp[level] = i;
             if (!traverse1(level - 1, cfs[i], exp)) return false;
           }
       exp[level] = 0;
     }
   return true;
 }
References mpfr::exp(), and viewTerm().
Referenced by traverse().