Macaulay2 Engine: MutableEngineObject::hash
hash()
unsigned int MutableEngineObject::hash () const inline
Definition at line 42 of file hash.hpp.
 { return mHashValue; }
References mHashValue.
Referenced by RingMap::computeHashValue(), PolynomialRing::computeHashValue(), Monoid::computeHashValue(), rawComputationHash(), rawMonoidHash(), rawMutableComplexHash(), rawMutableMatrixHash(), rawPointArrayHash(), rawRingHash(), and rawStraightLineProgramHash().