Macaulay2 Engine: rawRandomInt
rawRandomInt()
int32_t rawRandomInt (int32_t max)
Definition at line 41 of file random.cpp.
{
  if (max <= 0) return 0;
  int32_t k = RandomSeed / IQ;
  RandomSeed =
      IA * (RandomSeed - k * IQ) - IR * k; /* Schrage algorithm to compute
                                  idum = (IA*idum) mod IM */
  if (RandomSeed < 0) RandomSeed += IM;
  return RandomSeed % max;
}
References IA, IM, IQ, IR, max, and RandomSeed.
Referenced by getElement< M2::ARingGFFlint >(), GF::random(), Z_mod::random(), Matrix::random(), M2::ARingGFM2::random(), M2::ARingZZp::random(), rawMutableMatrixFillRandom(), rawMutableMatrixFillRandomDensity(), system_randomint(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), testRingPower(), and ZZp_RANDOM().