Macaulay2 Engine: newf4::MonomialView::combine
combine()
MonomialView newf4::MonomialView::combine (const MonomialView & left, const MonomialView & right, bool copyLeft, bool copyRight, std::function< int(int, int)> , MemoryBlock & block) static
Definition at line 6 of file MonomialView.cpp.
 {
     auto rng = block.allocateArray<MonomialInt>(left.size() + right.size() - 1);
     MonomialView result(rng.first);
     auto leftIt = left.begin();
     auto rightIt = right.begin();
     auto leftEnd = left.end();
     auto rightEnd = right.end();
     auto resultIt = result.begin();
     while (true)
     {
        if (leftIt == leftEnd)
        {
      // take from right and increment right and result
      if (useRight)
      {
        std::copy(rightIt.loc(),rightEnd.loc(),resultIt.loc());
        resultIt += ((rightEnd.loc() - rightIt.loc()) >> 1);
      }
      break;
        }
        if (rightIt == rightEnd)
        {
          // take from left and increment left and result
      if (useLeft)
      {
         std::copy(leftIt.loc(),leftEnd.loc(),resultIt.loc());
         resultIt += ((leftEnd.loc() - leftIt.loc()) >> 1);
      }
      break;
        }
        if (leftIt.var() < rightIt.var())
        {
       // take from left and increment left and result
       std::copy(leftIt.loc(), leftIt.loc() + 2, resultIt.loc());
       ++resultIt;
       ++leftIt;
        }
        else if (leftIt.var() > rightIt.var())
        {
       // take from right and increment right and result
       std::copy(rightIt.loc(), rightIt.loc() + 2, resultIt.loc());
       ++resultIt;
       ++rightIt;
        }
        else
        {
       // take maximum and increment both
       resultIt.loc()[0] = leftIt.var();
       auto temp = bothFunc(leftIt.power(), rightIt.power());
       if (temp > 0) // if we actually need this variable, store power and increment result
       {
         resultIt.loc()[1] = bothFunc(leftIt.power(), rightIt.power());
         ++resultIt;
       }
       ++leftIt;
       ++rightIt;
        }
     }
     block.shrinkLastAllocate(rng.first, rng.second, resultIt.loc());
     *rng.first = resultIt.loc() - rng.first;
     return result;
 }
References MemoryBlock::allocateArray(), begin(), end(), rng(), MemoryBlock::shrinkLastAllocate(), and size().
Referenced by lcm(), product(), and quotient().