Macaulay2 Engine: newf4::MonomialView::MonomialView
MonomialView() [4/4]
newf4::MonomialView::MonomialView (const MonomialView & m, MemoryBlock & block) inline
Definition at line 26 of file MonomialView.hpp.
  {
    auto rng = block.allocateArray<MonomialInt>(m.size());
    mData = rng.first;
    std::copy(m.dataBegin(), m.dataEnd(), mData);
  }
References MemoryBlock::allocateArray(), dataBegin(), dataEnd(), mData, rng(), and size().