Macaulay2 Engine: newf4::MonomialView::display
display()
void newf4::MonomialView::display (std::ostream & o, const std::vector< std::string > & varnames, const newf4::MonomialView & m) static
Definition at line 115 of file MonomialView.cpp.
 {
   // Note: if the monomial is '1', nothing is printed.
   // TODO: possibly allow print_one boolean argument, instead of handling it at calling point?
   bool first = true;
   for (auto t = m.begin(); t != m.end(); ++t)
     {
       auto v = t.var();
       auto e = t.power();
       if (v >= varnames.size() or v < 0)
         {
           throw exc::engine_error("variable out of range");
         }
       if (not first)
         {
           o << '*';
         }
       first = false;
       o << varnames[v];
       if (e != 1)
         o << '^' << e;
     }
 }
References begin(), and end().
Referenced by BasicPoly::display().