Macaulay2 Engine: newf4::MonomialView::begin
begin() [2/2]
auto newf4::MonomialView::begin () const -> MonomialIterator<true> inline
Definition at line 179 of file MonomialView.hpp.
 { return MonomialIterator<true>(mData + 1); }
References mData.
Referenced by combine(), display(), monomialDivides(), simpleDegree(), TEST(), and newf4::toStream().