Macaulay2 Engine: newf4::MonomialView::monomialDivides
monomialDivides()
static bool newf4::MonomialView::monomialDivides (const MonomialView & divisor, const MonomialView & divisee) inline static
Definition at line 50 of file MonomialView.hpp.
   {
     if (divisor.size() > divisee.size()) return false;
     auto divisorIt = divisor.begin();
     auto diviseeIt = divisee.begin();
     auto divisorEnd = divisor.end();
     auto diviseeEnd = divisee.end();
     while (divisorIt != divisorEnd)
     {
       auto divisorVar = divisorIt.var();
       while (true)
       {
         if (diviseeIt == diviseeEnd) return false;
         if (diviseeIt.var() > divisorVar) return false;
         if (diviseeIt.var() == divisorVar) break;
         ++diviseeIt;
       }
       // at this point, both diviseeIt.var() and divisorIt.var() are equal
       if (divisorIt.power() > diviseeIt.power()) return false;
       ++divisorIt;
       ++diviseeIt;
     }
     return true;
   }
References begin(), end(), and size().
Referenced by newf4::MonomialLookupTable::findAllDivisees(), newf4::MonomialLookupTable::findAllDivisors(), and TEST().