Macaulay2 Engine: TEST
TEST() [2/3]
TEST (ARingQQGMP , create)
Definition at line 30 of file ARingQQGmpTest.cpp.
 {
   M2::ARingQQGMP R;
   M2::ARingQQGMP::ElementType a;
   buffer o;
   ARingElementGenerator<M2::ARingQQGMP> gen(R);
   R.init(a);
   gen.nextElement(a);
   EXPECT_EQ(ringName(R), "QQGMP");
   EXPECT_EQ(R.cardinality(), static_cast<size_t>(-1));
   EXPECT_EQ(R.characteristic(), 0);
   R.clear(a);
 }
References M2::ARingQQGMP::cardinality(), M2::ARingQQGMP::characteristic(), M2::ARingQQGMP::clear(), M2::ARingQQGMP::init(), ARingElementGenerator< RingType >::nextElement(), and ringName().