Macaulay2 Engine: TEST
TEST() [3/3]
TEST (ARingQQGMP , display)
Definition at line 47 of file ARingQQGmpTest.cpp.
 {
   M2::ARingQQGMP R;
   M2::ARingQQGMP::ElementType a, b;
   buffer o;
   ARingElementGenerator<M2::ARingQQGMP> gen(R);
   R.init(a);
   R.init(b);
   gen.nextElement(a);
   gen.nextElement(b);
   R.divide(a, a, b);
   R.elem_text_out(o, a, true, false, false);
   EXPECT_TRUE(strcmp(o.str(), "24/23") == 0);
   std::cout << "a = ." << o.str() << "." << std::endl;
   EXPECT_EQ(ringName(R), "QQGMP");
   EXPECT_EQ(R.cardinality(), static_cast<size_t>(-1));
   EXPECT_EQ(R.characteristic(), 0);
   R.clear(a);
   R.clear(b);
 }
References M2::ARingQQGMP::cardinality(), M2::ARingQQGMP::characteristic(), M2::ARingQQGMP::clear(), M2::ARingQQGMP::divide(), M2::ARingQQGMP::elem_text_out(), M2::ARingQQGMP::init(), ARingElementGenerator< RingType >::nextElement(), ringName(), and buffer::str().