Macaulay2 Engine: check_poly
check_poly()
bool check_poly (const ResPolyRing & R, const ResPolynomial & f, const ResSchreyerOrder & O)
Definition at line 61 of file res-poly-ring.cpp.
 {
   std::vector<int*> monoms;
   auto end = ResPolynomialIterator(R,f,1);
   for (auto i = ResPolynomialIterator(R,f); i != end; ++i)
     {
       monoms.push_back(const_cast<res_packed_monomial>(i.monomial()));
     }
   ResMonomialSorter S(R.originalMonoid(), R.monoid(), ord, monoms);
   return S.ordered();
 }
References end(), ResPolyRing::monoid(), ResMonomialSorter::ordered(), and ResPolyRing::originalMonoid().
Referenced by SchreyerFrame::debugCheckOrder(), and SchreyerFrame::insertLevelOne().