Macaulay2 Engine: display_poly
display_poly()
void display_poly (std::ostream & o, const ResPolyRing & R, const ResPolynomial & f) inline
Definition at line 192 of file res-poly-ring.hpp.
{
  auto end = ResPolynomialIterator(R, f, 1);  // end
  int i = 0;
  for (auto it = ResPolynomialIterator(R, f); it != end; ++it, ++i)
    {
      R.vectorArithmetic().displayElement(o, f.coeffs, i);
      res_const_packed_monomial mon = it.monomial();
      R.monoid().showAlpha(mon);
    }
}
References ResPolynomial::coeffs, VectorArithmetic::displayElement(), end(), ResPolyRing::monoid(), ResMonoidDense::showAlpha(), and ResPolyRing::vectorArithmetic().
Referenced by SchreyerFrame::debugCheckOrder(), SchreyerFrame::insertLevelOne(), and SchreyerFrame::show().