Macaulay2 Engine: rawResolutionBetti
rawResolutionBetti()
M2_arrayint rawResolutionBetti (Computation * G, int type)
Definition at line 608 of file groebner.cpp.
{
  try
    {
      ResolutionComputation *G = C->cast_to_ResolutionComputation();
      if (G != nullptr) return G->get_betti(type);
      ERROR("expected resolution computation type");
      return nullptr;
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References Computation::cast_to_ResolutionComputation(), ERROR(), G, and ResolutionComputation::get_betti().