Macaulay2 Engine: IM2_initialize
IM2_initialize()
void IM2_initialize (void)
Initialize the engine. This routine must be called before any other engine routine is called. May be called multiple times. The subsequent calls do nothing.
Definition at line 40 of file engine.cpp.
 {
   if (initialized) return;
   initialized = true;
   doubles = new doubling_stash;
   // This next routine initializes: globalZZ, trivial_monoid, trivial_poly_ring,
   // and makes sure their degree rings are interconnected.
   PolyRing::get_trivial_poly_ring();
   initializeRationalRing();
   rawRandomInitialize();
 }
References doubles, PolyRing::get_trivial_poly_ring(), initialized, initializeRationalRing(), and rawRandomInitialize().
Referenced by main().