Macaulay2 Engine: rawSubduction
rawSubduction()
Matrix* rawSubduction (int numparts, const Matrix * M, const RingMap * F, Computation * C)
Definition at line 630 of file groebner.cpp.
 {
   try
     {
       GBComputation *G = C->cast_to_GBComputation();
       if (G == 0)
         {
           ERROR("expected a Groebner basis computation");
           return 0;
         }
       return sagbi::subduct(numparts, M, F, G);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Computation::cast_to_GBComputation(), ERROR(), RingMap::M, and sagbi::subduct().