Macaulay2 Engine: rawIdealOfPoints
rawIdealOfPoints()
M2_bool rawIdealOfPoints (const Ring * R, const MutableMatrix * Pts, Matrix ** result_GB, Matrix ** result_std_monoms)
Definition at line 13 of file points.cpp.
 {
   // Branch depending on the type of K, the ring of Pts.
   // If Pts is not a DMatrix, make it one.
   // First: check that coeff ring of R is the same as ring of Pts
   // Now branch depending on this type
   const Ring *K = Pts->get_ring();
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P == 0 || K != P->getCoefficients())
     {
       ERROR("expected polynomial ring with same coefficient ring");
       return false;
     }
   const Z_mod *KZZp = K->cast_to_Z_mod();
   if (KZZp != 0)
     {
       DMat<M2::ARingZZp> *Pts1 = 0;
       *result_GB = PointsComputation<M2::ARingZZp>::points(
           P, KZZp, Pts1, *result_std_monoms);
       return true;
     }
   ERROR("not implemented yet");
   return false;
 }
References Ring::cast_to_PolynomialRing(), Ring::cast_to_Z_mod(), ERROR(), MutableMatrix::get_ring(), PolynomialRing::getCoefficients(), and PointsComputation< CoeffRing >::points().