Macaulay2 Engine: rawResolutionGetMutableMatrix2B
rawResolutionGetMutableMatrix2B()
MutableMatrix * rawResolutionGetMutableMatrix2B (Computation * C, const Ring * KK, int level, int degree)
Definition at line 541 of file groebner.cpp.
{
  try
    {
      clear_emit_size();
      F4ResComputation *G = dynamic_cast<F4ResComputation *>(C);
      if (G != nullptr) return G->get_mutable_matrix(KK, level, degree);
      ERROR("expected fast nonminimal resolution computation type");
      return nullptr;
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References clear_emit_size(), ERROR(), G, and F4ResComputation::get_mutable_matrix().