Macaulay2 Engine: rawGbBoolean
rawGbBoolean()
const Matrix* rawGbBoolean (const Matrix * m)
Definition at line 100 of file franzi-interface.cpp.
 {
   IntermediateBasis F = BRPSfromMatrix(m);
   // cout << "first BRP in F " << F.begin()->second << endl;
   const Ring *R = m->get_ring();
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P == 0)
     {
       ERROR("expected a polynomial ring");
       return 0;
     }
   if (P->characteristic() != 2)
     {
       ERROR("expected coefficient ring ZZ/2");
       return 0;
     }
   if (not P->getCoefficientRing()->isFinitePrimeField())
     {
       ERROR("expected coefficient ring ZZ/2");
       return 0;
     }
   int n = P->n_vars();
   if (n > 64)
     {
       ERROR("Cannot handle more than 64 variables yet");
       return 0;
     }
   gb(F, n);
   // cout << "first BRP in F after gb() " << F.begin()->second << endl;
   return BRPStoMatrix(P, F);
 }
References BRPSfromMatrix(), BRPStoMatrix(), Ring::cast_to_PolynomialRing(), Ring::characteristic(), ERROR(), gb(), Matrix::get_ring(), PolynomialRing::getCoefficientRing(), Ring::isFinitePrimeField(), and PolynomialRing::n_vars().