Macaulay2 Engine: IM2_GB_set_hilbert_function
IM2_GB_set_hilbert_function()
Computation* IM2_GB_set_hilbert_function (Computation * G, const RingElement * h)
Definition at line 136 of file groebner.cpp.
 {
   try
     {
       clear_emit_size();
       GBComputation *G = C->cast_to_GBComputation();
       if (G->get_ring()->get_degree_ring() != h->get_ring())
         {
           ERROR("expected Hilbert function hint to be in correct degree ring");
           return 0;
         }
       if (G != 0) return G->set_hilbert_function(h);
       ERROR("computation type unknown or not implemented");
       return 0;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Computation::cast_to_GBComputation(), clear_emit_size(), ERROR(), Ring::get_degree_ring(), RingElement::get_ring(), GBComputation::get_ring(), and GBComputation::set_hilbert_function().