Macaulay2 Engine: IM2_Ring_skew_polyring
IM2_Ring_skew_polyring()
const Ring * IM2_Ring_skew_polyring (const Ring * R, M2_arrayint skewvars)
Definition at line 145 of file ring.cpp.
{
  try
    {
      const PolynomialRing *P = R->cast_to_PolynomialRing();
      if (P == nullptr)
        {
          ERROR("expected a polynomial ring");
          return nullptr;
        }
      SkewPolynomialRing *result = SkewPolynomialRing::create(
          P->getCoefficients(), P->getMonoid(), skewvars);
      intern_polyring(result);
      return result;
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References Ring::cast_to_PolynomialRing(), SkewPolynomialRing::create(), ERROR(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), and intern_polyring().