Macaulay2 Engine: IM2_Ring_polyring
IM2_Ring_polyring()
const Ring* IM2_Ring_polyring (const Ring * K, const Monoid * M)
Definition at line 113 of file ring.cpp.
 {
   try
     {
       const PolyRing *result = PolyRing::create(K, M);
       intern_polyring(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References PolyRing::create(), ERROR(), and intern_polyring().