Macaulay2 Engine: rawRingM2FreeAlgebra
rawRingM2FreeAlgebra()
const Ring* rawRingM2FreeAlgebra (const Ring * coefficientRing, M2_ArrayString names, const Ring * degreeRing, M2_arrayint degrees, M2_arrayint wtvecs, M2_arrayint heftVector)
Definition at line 214 of file ring.cpp.
 {
   try {
     if (coefficientRing == nullptr)
       {
         ERROR("internal error: expected non-null Ring!");
         return nullptr;
       }
     const PolynomialRing *P = degreeRing->cast_to_PolynomialRing();
     if (P == nullptr)
       {
         ERROR("expected polynomial ring");
         return nullptr;
       }
     const M2FreeAlgebra* result = M2FreeAlgebra::create(coefficientRing,
                                                         M2_ArrayString_to_stdvector(names),
                                                         P,
                                                         M2_arrayint_to_stdvector<int>(degrees),
                                                         M2_arrayint_to_stdvector<int>(wtvecs),
                                                         M2_arrayint_to_stdvector<int>(heftVector));
     //intern_polyring(result); // we might want to intern our rings (to register a finalizer with the gc)
     return result;
   }
   catch (exc::engine_error& e) {
     ERROR(e.what());
     return NULL;
   }
 }
References PolynomialRing::cast_to_PolynomialRing(), M2FreeAlgebra::create(), degreeRing(), ERROR(), and M2_ArrayString_to_stdvector().