Macaulay2 Engine: IM2_Ring_weyl_algebra
IM2_Ring_weyl_algebra()
const Ring * IM2_Ring_weyl_algebra (const Ring * R, M2_arrayint comm_vars, M2_arrayint diff_vars, int homog_var)
Definition at line 167 of file ring.cpp.
{
  try
    {
      const PolynomialRing *P = R->cast_to_PolynomialRing();
      if (P == nullptr)
        {
          ERROR("expected a polynomial ring");
          return nullptr;
        }
      WeylAlgebra *result = WeylAlgebra::create(P->getCoefficients(),
                                                P->getMonoid(),
                                                diff_vars,
                                                comm_vars,
                                                homog_var);
      intern_polyring(result);
      return result;
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References Ring::cast_to_PolynomialRing(), WeylAlgebra::create(), ERROR(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), and intern_polyring().