Macaulay2 Engine: IM2_Ring_frac
IM2_Ring_frac()
const Ring* IM2_Ring_frac (const Ring * R)
Definition at line 302 of file ring.cpp.
 {
   try
     {
       if (R == globalZZ) return globalQQ;
       const PolyRingFlat *P = R->cast_to_PolyRingFlat();
       if (P == 0)
         {
           ERROR("expected polynomial ring");
           return 0;
         }
       if (P->getMonoid()->numNonTermOrderVariables() > 0)
         {
           ERROR(
               "cannot currently make fraction field over a polynomial ring "
               "with a non-global monomial order");
           return 0;
         }
       if (P->getMonoid()->numInvertibleVariables() > 0)
         {
           ERROR(
               "cannot currently make fraction field over a polynomial ring "
               "with Laurent variables, i.e. Inverses=>true set");
           return 0;
         }
       if (R->get_precision() > 0)
         {
           ERROR("cannot make fraction field over approximate field base");
           return 0;
         }
       if (P->getCoefficients()->cast_to_FractionField() != 0)
         {
           ERROR(
               "fraction fields over other fraction fields not yet implemented");
           return 0;
         }
       if (P->getCoefficients()->cast_to_LocalRing() != 0)
         {
           ERROR("fraction fields over other local rings not yet implemented");
           return 0;
         }
       return FractionField::create(P);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References Ring::cast_to_FractionField(), Ring::cast_to_LocalRing(), Ring::cast_to_PolyRingFlat(), FractionField::create(), ERROR(), Ring::get_precision(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), globalQQ, globalZZ, Monoid::numInvertibleVariables(), and Monoid::numNonTermOrderVariables().