Macaulay2 Engine: IM2_Ring_quotient1
IM2_Ring_quotient1()
const Ring* IM2_Ring_quotient1 (const Ring * R, const Ring * B)
Definition at line 414 of file ring.cpp.
 {
   try
     {
       const PolynomialRing *R1 = R->cast_to_PolynomialRing();
       const PolynomialRing *B1 = B->cast_to_PolynomialRing();
       if (R1 == 0 || B1 == 0)
         {
           ERROR("expected a polynomial ring");
           return 0;
         }
       if (R1->n_quotients() > 0)
         {
           ERROR("encountered quotient polynomial ring");
           return 0;
         }
       PolynomialRing *result = PolyRingQuotient::create_quotient(R1, B1);
       intern_polyring(result);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References Ring::cast_to_PolynomialRing(), PolynomialRing::create_quotient(), ERROR(), intern_polyring(), and PolynomialRing::n_quotients().