Macaulay2 Engine: M2_ArrayString_to_stdvector
M2_ArrayString_to_stdvector() [2/2]
void M2_ArrayString_to_stdvector (M2_ArrayString strs, std::vector< std::string > & result)
Definition at line 16 of file util.cpp.
 {
   for (size_t i = 0; i < strs->len; i++)
     {
       M2_string a = strs->array[i];
       std::string b((char *)a->array, a->len);
       result.push_back(b);
     }
 }
Referenced by rawARingTower1(), rawARingTower2(), and rawRingM2FreeAlgebra().