Macaulay2 Engine: F4Res::construct
construct()
void F4Res::construct (int lev, int degree)
Definition at line 642 of file res-f4.cpp.
 {
   decltype(timer()) timeA, timeB;
   resetMatrix(lev, degree);
   if (M2_gbTrace >= 2)
      std::cout << "construct (" << lev << "," << degree-lev << ")" << std::endl;
   timeA = timer();
   makeMatrix();
   timeB = timer();
   mFrame.timeMakeMatrix += seconds(timeB - timeA);
   //if (M2_gbTrace >= 2) mHashTable.dump();
   if (M2_gbTrace >= 2)
     std::cout << "  make (" << lev << "," << degree-lev << "): " << seconds(timeB - timeA) << " sec"
               << std::endl;
 #if 0
   std::cout << "-- rows --" << std::endl;
   debugOutputReducers();
   std::cout << "-- columns --" << std::endl;
   debugOutputColumns();
   std :: cout << "-- reducer matrix --" << std::endl;
   if (true or lev <= 2)
     debugOutputMatrix(mReducers);
   else
     debugOutputMatrixSparse(mReducers);
   std :: cout << "-- reducer matrix --" << std::endl;
   debugOutputMatrix(mReducers);
   debugOutputMatrixSparse(mReducers);
   std :: cout << "-- spair matrix --" << std::endl;
   debugOutputMatrix(mSPairs);
   debugOutputMatrixSparse(mSPairs);
 #endif
 //  if (M2_gbTrace >= 2)
 //    std::cout << "  (degree,level)=(" << (mThisDegree - mThisLevel) << ","
 //              << mThisLevel << ") #spairs=" << mSPairs.size()
 //              << " reducer= " << mReducers.size() << " x " << mReducers.size()
 //              << std::endl;
 //  if (M2_gbTrace >= 2) std::cout << "  gauss reduce matrix" << std::endl;
   timeA = timer();
   gaussReduce();
   timeB = timer();
   mFrame.timeGaussMatrix += seconds(timeB - timeA);
   if (M2_gbTrace >= 2)
     std::cout << "  gauss (" << lev << "," << degree-lev << "): " << seconds(timeB - timeA) << " sec"
               << std::endl;
 //    std::cout << "    time: " << seconds(timeB - timeA) << " sec" << std::endl;
   //  mFrame.show(-1);
   timeA = timer();
   clearMatrix();
   timeB = timer();
   mFrame.timeClearMatrix += seconds(timeB - timeA);
 }
References clearMatrix(), debugOutputColumns(), debugOutputMatrix(), debugOutputMatrixSparse(), debugOutputReducers(), gaussReduce(), M2_gbTrace, makeMatrix(), mFrame, mReducers, mSPairs, resetMatrix(), seconds(), SchreyerFrame::timeClearMatrix, SchreyerFrame::timeGaussMatrix, SchreyerFrame::timeMakeMatrix, and timer().
Referenced by SchreyerFrame::fillinSyzygies().