Macaulay2 Engine: F4Res::debugOutputReducers
debugOutputReducers()
void F4Res::debugOutputReducers () private
Definition at line 665 of file res-f4.cpp.
 {
   std::cout << "-- reducers(rows) -- " << std::endl;
   auto end = mReducers.cend();
   for (auto i = mReducers.cbegin(); i != end; ++i)
     {
       monoid().showAlpha((*i).mLeadTerm);
       std::cout << std::endl;
     }
 }
References end(), monoid(), mReducers, and ResMonoidDense::showAlpha().
Referenced by construct(), makeMatrix(), and reorderColumns().