Macaulay2 Engine: F4Res::debugOutputColumns
debugOutputColumns()
void F4Res::debugOutputColumns () private
Definition at line 717 of file res-f4.cpp.
 {
   std::cout << "-- columns --" << std::endl;
   auto end = mColumns.cend();
   for (auto i = mColumns.cbegin(); i != end; ++i)
     {
       monoid().showAlpha((*i));
       std::cout << std::endl;
     }
 }
References end(), mColumns, monoid(), and ResMonoidDense::showAlpha().
Referenced by construct(), makeMatrix(), and reorderColumns().