Macaulay2 Engine: F4Res::monoid
monoid()
const ResMonoid& F4Res::monoid () const inline
Definition at line 37 of file res-f4.hpp.
 { return mRing.monoid(); }
References ResPolyRing::monoid(), and mRing.
Referenced by debugOutputColumns(), debugOutputReducers(), findDivisor(), gaussReduce(), loadRow(), processCurrentMonomial(), processMonomialProduct(), and reorderColumns().