Macaulay2 Engine: F4Res::debugOutputMatrixSparse
debugOutputMatrixSparse()
void F4Res::debugOutputMatrixSparse (std::vector< Row > & rows) private
Definition at line 728 of file res-f4.cpp.
{
  for (ComponentIndex i = 0; i < rows.size(); i++)
    {
      std::cout << "coeffs[" << i << "] = ";
      mRing.vectorArithmetic().displayElementArray(std::cout, rows[i].mCoeffs);
      std::cout << " comps = ";
      for (long j = 0; j < rows[i].mComponents.size(); ++j)
        std::cout << rows[i].mComponents[j] << " ";
      std::cout << std::endl;
    }
}
References VectorArithmetic::displayElementArray(), mRing, and ResPolyRing::vectorArithmetic().
Referenced by construct(), and makeMatrix().