Macaulay2 Engine: F4Res::processMonomialProduct
processMonomialProduct()
ComponentIndex F4Res::processMonomialProduct (res_const_packed_monomial m, res_const_packed_monomial n, int & result_sign_if_skew) private
Definition at line 156 of file res-f4.cpp.
 {
   result_sign_if_skew = 1;
   auto x = monoid().get_component(n);
   auto& p = mFrame.level(mThisLevel - 2)[x];
   if (p.mBegin == p.mEnd) return -1;
   int* thisMonom = mMonomSpace2.allocate(1 + monoid().max_monomial_size());
   thisMonom++; // so thisMonom[-1] exists, but is not part of the monomial, as far as
   monoid().unchecked_mult(m, n, thisMonom);
   monoid().set_component(x, thisMonom);
   if (ring().isSkewCommutative())
     {
       result_sign_if_skew = monoid().skew_mult_sign(ring().skewInfo(), m, n);
       if (result_sign_if_skew == 0)
         {
           mMonomSpace2.popLastAlloc(thisMonom-1); // we did not need this monomial!
           return -1;
         }
     }
   return processCurrentMonomial(thisMonom);
 }
References MonomialMemorySpace::allocate(), ResMonoidDense::get_component(), SchreyerFrame::level(), mFrame, mMonomSpace2, monoid(), mThisLevel, p, MonomialMemorySpace::popLastAlloc(), processCurrentMonomial(), ring(), ResMonoidDense::set_component(), ResMonoidDense::skew_mult_sign(), ResMonoidDense::unchecked_mult(), and x.
Referenced by loadRow().