Macaulay2 Engine: F4Res::processCurrentMonomial
processCurrentMonomial()
ComponentIndex F4Res::processCurrentMonomial (res_packed_monomial thisMonom) private
Definition at line 194 of file res-f4.cpp.
 {
   res_packed_monomial new_m;  // a pointer to a monomial we are visiting
   if (mHashTable.find_or_insert(thisMonom, new_m))
     {
       // we did not need the monomial. So pop it.
       mMonomSpace2.popLastAlloc(thisMonom-1);
       return static_cast<ComponentIndex>(
                                          new_m[-1]);  // monom exists, don't save monomial space
     }
   // At this point thisMonom has been inserted.  We keep it.
   thisMonom = mMonomSpace2.allocate(1 + monoid().max_monomial_size());
   thisMonom++; // so thisMonom[-1] exists, but is not part of the monomial, as far as
   bool has_divisor = findDivisor(new_m, thisMonom);
   if (!has_divisor)
     {
       mMonomSpace2.popLastAlloc(thisMonom-1);
       new_m[-1] = -1;  // no divisor exists
       return -1;
     }
   ComponentIndex thiscol = static_cast<ComponentIndex>(mColumns.size());
   new_m[-1] = thiscol;  // this is a HACK: where we keep the divisor
   mColumns.push_back(new_m);
   Row row;
   row.mLeadTerm = thisMonom;
   mReducers.push_back(row);
   return thiscol;
 }
References MonomialMemorySpace::allocate(), MonomialHashTable< ValueType >::find_or_insert(), findDivisor(), ResMonoidDense::max_monomial_size(), mColumns, mHashTable, F4Res::Row::mLeadTerm, mMonomSpace2, monoid(), mReducers, and MonomialMemorySpace::popLastAlloc().
Referenced by processMonomialProduct().