Macaulay2 Engine: F4Res::makeMatrix
makeMatrix()
void F4Res::makeMatrix () private
Definition at line 410 of file res-f4.cpp.
 {
   // std::cout << "entering makeMatrix()" << std::endl;
   auto& myframe = mFrame.level(mThisLevel);
   long r = 0;
   long comp = 0;
   for (auto it = myframe.begin(); it != myframe.end(); ++it)
     {
       if (it->mDegree == mThisDegree)
         {
           mSPairs.push_back(Row());
           mSPairComponents.push_back(comp);
           Row& row = mSPairs[r];
           r++;
           row.mLeadTerm = it->mMonom;
           loadRow(row);
           if (M2_gbTrace >= 4)
             if (r % 5000 == 0)
               std::cout << "makeMatrix  sp: " << r
                         << " #rows = " << mColumns.size() << std::endl;
         }
       comp++;
     }
   // Now we process all monomials in the columns array
   while (mNextReducerToProcess < mColumns.size())
     {
       // Warning: mReducers is being appended to during 'loadRow', and
       // since we act on the Row directly, it might get moved on us!
       // (actually, it did get moved, which prompted this fix)
       Row thisrow;
       std::swap(mReducers[mNextReducerToProcess], thisrow);
       loadRow(thisrow);
       std::swap(mReducers[mNextReducerToProcess], thisrow);
       mNextReducerToProcess++;
       if (M2_gbTrace >= 4)
         if (mNextReducerToProcess % 5000 == 0)
           std::cout << "makeMatrix red: " << mNextReducerToProcess
                     << " #rows = " << mReducers.size() << std::endl;
     }
   reorderColumns();
 #if 0
   debugOutputReducers();
   debugOutputColumns();
   std :: cout << "-- reducer matrix --" << std::endl;
   debugOutputMatrix(mReducers);
   debugOutputMatrixSparse(mReducers);
   std :: cout << "-- spair matrix --" << std::endl;
   debugOutputMatrix(mSPairs);
   debugOutputMatrixSparse(mSPairs);
 #endif
 }
References debugOutputColumns(), debugOutputMatrix(), debugOutputMatrixSparse(), debugOutputReducers(), SchreyerFrame::level(), loadRow(), M2_gbTrace, mColumns, mFrame, F4Res::Row::mLeadTerm, mNextReducerToProcess, mReducers, mSPairComponents, mSPairs, mThisDegree, mThisLevel, reorderColumns(), and swap.
Referenced by construct().