Macaulay2 Engine: F4Res::debugOutputMatrix
debugOutputMatrix()
void F4Res::debugOutputMatrix (std::vector< Row > & rows) private
Definition at line 741 of file res-f4.cpp.
 {
   for (ComponentIndex i = 0; i < rows.size(); i++)
     {
       mRing.vectorArithmetic().displayAsDenseArray(std::cout,
                                              static_cast<int>(mColumns.size()),
                                              rows[i].mCoeffs,
                                              Range(rows[i].mComponents.data(), rows[i].mComponents.data() + rows[i].mComponents.size()));
     }
 }
References VectorArithmetic::displayAsDenseArray(), mColumns, mRing, and ResPolyRing::vectorArithmetic().
Referenced by construct(), debugOutputReducerMatrix(), debugOutputSPairMatrix(), and makeMatrix().