Macaulay2 Engine: F4Res::findDivisor
findDivisor()
bool F4Res::findDivisor (res_const_packed_monomial m, res_packed_monomial result) private
Definition at line 109 of file res-f4.cpp.
{
  // get component of m
  // find the range of monomials to check
  // for each of these, check divisibility in turn
  //   if one works, then return true, and set result.
  long comp =
      monoid().get_component(m);  // component is an index into level mLevel-2
  auto& elem = mFrame.level(mThisLevel - 2)[comp];
  auto& lev = mFrame.level(mThisLevel - 1);
  for (auto j = elem.mBegin; j < elem.mEnd; ++j)
    {
      // Check divisibility of m by this element
      res_packed_monomial pj = lev[j].mMonom;
      if (monoid().divide(m, pj, result))  // this sets the component to be 0
        {
          monoid().set_component(j, result);  // this sets component correctly
          return true;
        }
    }
  return false;
}
References ResMonoidDense::divide(), ResMonoidDense::get_component(), SchreyerFrame::level(), mFrame, monoid(), mThisLevel, and ResMonoidDense::set_component().
Referenced by processCurrentMonomial().