Macaulay2 Engine: F4Res::clearMatrix
clearMatrix()
void F4Res::clearMatrix () private
Definition at line 78 of file res-f4.cpp.
 {
   mThisLevel = -1;
   mThisDegree = -1;
   mNextReducerToProcess = 0;
   auto timeA = timer();
   mHashTable.reset();
   auto timeB = timer();
   mFrame.timeResetHashTable += seconds(timeB - timeA);
   for (auto& f : mReducers)
     {
       mRing.resGausser().deallocate(f.mCoeffs);
     }
   for (auto& f : mSPairs)
     {
       mRing.resGausser().deallocate(f.mCoeffs);
     }
   mReducers.clear();
   mSPairs.clear();
   mSPairComponents.clear();
   mColumns.clear();
   mMonomSpace2.freeAllAllocs();
 }
References ResGausser::deallocate(), MonomialMemorySpace::freeAllAllocs(), mColumns, mFrame, mHashTable, mMonomSpace2, mNextReducerToProcess, mReducers, mRing, mSPairComponents, mSPairs, mThisDegree, mThisLevel, MonomialHashTable< ValueType >::reset(), ResPolyRing::resGausser(), seconds(), timer(), and SchreyerFrame::timeResetHashTable.
Referenced by construct().