Macaulay2 Engine: F4Res::gaussReduce
gaussReduce()
void F4Res::gaussReduce () private
Definition at line 467 of file res-f4.cpp.
 {
   bool onlyConstantMaps = false;
   std::vector<bool> track(mReducers.size());
   if (onlyConstantMaps)  // and not exterior algebra?
     {
       for (auto i = 0; i < mReducers.size(); i++)
         {
           track[i] = monoid().is_divisible_by_var_in_range(
               mReducers[i].mLeadTerm,
               monoid().n_vars() - mThisLevel + 1,
               monoid().n_vars() - 1);
         }
     }
   // Reduce to zero every spair. Recording creates the
   // corresponding syzygy, which is auto-reduced and correctly ordered.
   // allocate a dense row, of correct size
   CoefficientVector gauss_row = mRing.resGausser().allocateCoefficientVector(
       static_cast<ComponentIndex>(mColumns.size()));
   //  std::cout << "gauss_row: " << (gauss_row.isNull() ? "null" : "not-null")
   //  << std::endl;
   //  std::cout << "gauss_row size: " << mRing.resGausser().size(gauss_row) <<
   //  std::endl;
   for (long i = 0; i < mSPairs.size(); i++)
     {
 #ifdef DEBUG_GAUSS
       std::cout << "reducing row " << i << std::endl;
 #endif
       // Reduce spair #i
       // fill in dense row with this element.
       ResPolynomialConstructor result(mRing);
       Row& r = mSPairs[i];  // row to be reduced.
       long comp = mSPairComponents[i];
       result.appendMonicTerm(mFrame.level(mThisLevel)[comp].mMonom);
       auto& syz = mFrame.level(mThisLevel)[comp]
                       .mSyzygy;  // this is the element we will fill out
       // Note: in the polynomial ring case, the row r is non-zero.
       // BUT: for skew commuting variables, it can happen that r is zero
       // (e.g. a.(acd<0>) = 0).  In this case we have nothing to reduce.
       if (!r.mComponents.empty())
         {
           ComponentIndex firstcol = r.mComponents[0];
           ComponentIndex lastcol = static_cast<ComponentIndex>(
               mColumns.size() -
               1);  // maybe: r.mComponents[r.mComponents.size()-1];
 #ifdef DEBUG_GAUSS
           std::cout << "about to fill from sparse " << i << std::endl;
 #endif
           mRing.resGausser().fillFromSparse(
               gauss_row,
               static_cast<ComponentIndex>(r.mComponents.size()),
               r.mCoeffs,
               &r.mComponents[0]);  // FIX: not correct call
           while (firstcol <= lastcol)
             {
 #ifdef DEBUG_GAUSS
               std::cout << "about to reduce with col " << firstcol << std::endl;
               std::cout << "gauss_row: "
                         << (gauss_row.isNull() ? "null" : "not-null")
                         << std::endl;
               std::cout << "mReducers[" << firstcol << "]: "
                         << (mReducers[firstcol].mCoeffs.isNull() ? "null"
                                                                  : "not-null")
                         << std::endl;
               std::cout << "result: " << (result.coefficientInserter().isNull()
                                               ? "null"
                                               : "not-null")
                         << std::endl;
               std::cout << "  dense: ";
               mRing.resGausser().debugDisplay(std::cout, gauss_row)
                   << std::endl;
               mRing.resGausser().debugDisplay(std::cout,
                                               mReducers[firstcol].mCoeffs);
               std::cout << std::endl;
               mRing.resGausser().debugDisplay(std::cout,
                                               result.coefficientInserter());
               std::cout << std::endl;
 #endif
               if (onlyConstantMaps and not track[firstcol])
                 {
                   mRing.resGausser().sparseCancel(
                       gauss_row,
                       mReducers[firstcol].mCoeffs,
                       mReducers[firstcol].mComponents.data());
                 }
               else
                 {
                   mRing.resGausser().sparseCancel(
                       gauss_row,
                       mReducers[firstcol].mCoeffs,
                       mReducers[firstcol].mComponents.data(),
                       result.coefficientInserter());
 #ifdef DEBUG_GAUSS
                   std::cout << "  done with sparseCancel" << std::endl;
                   mRing.resGausser().debugDisplay(std::cout, gauss_row)
                       << std::endl;
                   mRing.resGausser().debugDisplay(std::cout,
                                                   mReducers[firstcol].mCoeffs)
                       << std::endl;
                   mRing.resGausser().debugDisplay(std::cout,
                                                   result.coefficientInserter())
                       << std::endl;
                   std::cout << "  about to push back term" << std::endl;
 #endif
                   result.pushBackTerm(mReducers[firstcol].mLeadTerm);
 #ifdef DEBUG_GAUSS
                   std::cout << "done with col " << firstcol << std::endl;
 #endif
                 }
               firstcol = mRing.resGausser().nextNonzero(
                   gauss_row, firstcol + 1, lastcol);
             }
         }
 #ifdef DEBUG_GAUSS
       std::cout << "about to set syz" << std::endl;
 #endif
       result.setPoly(syz);
 #ifdef DEBUG_GAUSS
       std::cout << "just set syz" << std::endl;
 #endif
     }
   mRing.resGausser().deallocate(gauss_row);
 }
References ResGausser::allocateCoefficientVector(), ResPolynomialConstructor::appendMonicTerm(), ResPolynomialConstructor::coefficientInserter(), ResGausser::deallocate(), ResGausser::debugDisplay(), ResGausser::fillFromSparse(), ResMonoidDense::is_divisible_by_var_in_range(), CoefficientVector::isNull(), SchreyerFrame::level(), F4Res::Row::mCoeffs, mColumns, F4Res::Row::mComponents, mFrame, monoid(), mReducers, mRing, mSPairComponents, mSPairs, mThisLevel, ResGausser::nextNonzero(), ResPolynomialConstructor::pushBackTerm(), ResPolyRing::resGausser(), ResPolynomialConstructor::setPoly(), and ResGausser::sparseCancel().
Referenced by construct().