Macaulay2 Engine: F4Res::loadRow
loadRow()
void F4Res::loadRow (Row & r) private
Definition at line 226 of file res-f4.cpp.
 {
   //  std::cout << "loadRow: " << std::endl;
   r.mCoeffs = vectorArithmetic().allocateElementArray();
   //  monoid().showAlpha(r.mLeadTerm);
   //  std::cout << std::endl;
   int skew_sign;  // will be set to 1, unless ring().isSkewCommutative() is
                   // true, then it can be -1,0,1.
   // however, if it is 0, then "val" below will also be -1.
   long comp = monoid().get_component(r.mLeadTerm);
   auto& thiselement = mFrame.level(mThisLevel - 1)[comp];
   // std::cout << "  comp=" << comp << " mDegree=" << thiselement.mDegree << "
   // mThisDegree=" << mThisDegree << std::endl;
   if (thiselement.mDegree == mThisDegree)
     {
       // We only need to add in the current monomial
       // fprintf(stdout, "USING degree 0 monomial\n");
       ComponentIndex val =
           processMonomialProduct(r.mLeadTerm, thiselement.mMonom, skew_sign);
       if (val < 0) fprintf(stderr, "ERROR: expected monomial to live\n");
       r.mComponents.push_back(val);
       if (skew_sign > 0)
         mRing.vectorArithmetic().pushBackOne(r.mCoeffs);
       else
         {
           // Only happens if we are in a skew commuting ring.
           ring().vectorArithmetic().pushBackMinusOne(r.mCoeffs);
         }
       return;
     }
   auto& p = thiselement.mSyzygy;
   auto end = ResPolynomialIterator(mRing, p, 1);
   auto i = ResPolynomialIterator(mRing, p);
   for (; i != end; ++i)
     {
       ComponentIndex val =
           processMonomialProduct(r.mLeadTerm, i.monomial(), skew_sign);
       // std::cout << "  monom: " << val << " skewsign=" << skew_sign << "
       // mColumns.size=" << mColumns.size() << std::endl;
       if (val < 0) continue;
       r.mComponents.push_back(val);
       if (skew_sign > 0)
         mRing.vectorArithmetic().pushBackElement(
             r.mCoeffs, p.coeffs, i.coefficient_index());
       else
         {
           // Only happens if we are in a skew commuting ring.
           mRing.vectorArithmetic().pushBackNegatedElement(
               r.mCoeffs, p.coeffs, i.coefficient_index());
         }
     }
 }
References VectorArithmetic::allocateElementArray(), end(), ResMonoidDense::get_component(), SchreyerFrame::level(), F4Res::Row::mCoeffs, F4Res::Row::mComponents, mFrame, F4Res::Row::mLeadTerm, monoid(), mRing, mThisDegree, mThisLevel, p, processMonomialProduct(), VectorArithmetic::pushBackElement(), VectorArithmetic::pushBackMinusOne(), VectorArithmetic::pushBackNegatedElement(), VectorArithmetic::pushBackOne(), ring(), vectorArithmetic(), and ResPolyRing::vectorArithmetic().
Referenced by makeMatrix().