Macaulay2 Engine: ResolutionComputation::betti_display
betti_display()
void ResolutionComputation::betti_display (buffer & o, M2_arrayint a) static
Definition at line 205 of file comp-res.cpp.
 {
   int *a = ar->array;
   int total_sum = 0;
   int lo = a[0];
   int hi = a[1];
   int len = a[2] + 1;
   o << "total  ";
   for (int lev = 0; lev < len; lev++)
     {
       int sum = 0;
       for (int d = lo; d <= hi; d++) sum += a[len * (d - lo) + lev + 3];
       total_sum += sum;
       o.put(sum, 6);
       o << ' ';
     }
   o << " [" << total_sum << "]" << newline;
   for (int d = lo; d <= hi; d++)
     {
       o.put(d, 5);
       o << ": ";
       for (int lev = 0; lev < len; lev++)
         {
           int c = a[len * (d - lo) + lev + 3];
           if (c != 0)
             o.put(c, 6);
           else
             o << "     -";
           o << " ";
         }
       o << newline;
     }
 }
References newline, buffer::put(), and mpfr::sum().
Referenced by res_comp::skeleton_stats(), res2_comp::start_computation(), res2_comp::text_out(), and res_comp::text_out().