Macaulay2 Engine: ResolutionComputation::betti_init
betti_init()
void ResolutionComputation::betti_init (int lo, int hi, int len, int *& bettis) static
Definition at line 149 of file comp-res.cpp.
 {
   int z = (hi - lo + 1) * (len + 1);
   bettis = newarray_atomic_clear(int, z);
 }
References newarray_atomic_clear.
Referenced by res2_comp::betti_minimal(), gbres_comp::betti_minimal(), res2_comp::betti_nmonoms(), res2_comp::betti_remaining(), and res_comp::get_betti().