Macaulay2 Engine: BIBasis::MonomDL::SetOne
SetOne()
void BIBasis::MonomDL::SetOne () inline virtual
Implements BIBasis::Monom.
Definition at line 124 of file monomDL.hpp.
     {
         TotalDegree = 0;
         if (ListHead)
         {
             VarsListNode* tmpNode;
             while (ListHead)
             {
                 tmpNode = ListHead;
                 ListHead = ListHead->Next;
                 delete tmpNode;
             }
         }
     }
References BIBasis::Monom::ListHead, BIBasis::Monom::VarsListNode::Next, and BIBasis::Monom::TotalDegree.
Referenced by operator=(), SetQuotientOf(), and ~MonomDL().