Macaulay2 Engine: ResolutionComputation::betti_make
betti_make()
M2_arrayint ResolutionComputation::betti_make (int lo, int hi, int len, int * bettis) static
Definition at line 157 of file comp-res.cpp.
 {
   int d, lev;
   int hi1 = hi + 1;
   int len1 = len + 1;
   // Reset 'hi1' to reflect the top degree that occurs
   for (d = hi; d >= lo; d--)
     {
       for (lev = 0; lev <= len; lev++)
         if (bettis[lev + (len + 1) * (d - lo)] > 0)
           {
             hi1 = d;
             break;
           }
       if (hi1 <= hi) break;
     }
   if (hi1 > hi) hi1 = hi;
   // Reset 'len1' to reflect the top level that occurs
   for (lev = len; lev >= 0; lev--)
     {
       for (d = lo; d <= hi1; d++)
         if (bettis[lev + (len + 1) * (d - lo)] > 0)
           {
             len1 = lev;
             break;
           }
       if (len1 <= len) break;
     }
   if (len1 > len) len1 = len;
   int totallen = (hi1 - lo + 1) * (len1 + 1);
   M2_arrayint result = M2_makearrayint(3 + totallen);
   result->array[0] = lo;
   result->array[1] = hi1;
   result->array[2] = len1;
   int next = 3;
   for (d = lo; d <= hi1; d++)
     for (lev = 0; lev <= len1; lev++)
       result->array[next++] = bettis[lev + (len + 1) * (d - lo)];
   return result;
 }
References M2_makearrayint().
Referenced by res2_comp::betti_minimal(), gbres_comp::betti_minimal(), res2_comp::betti_nmonoms(), res2_comp::betti_remaining(), and res_comp::get_betti().