Macaulay2 Engine: MutableMatrix::column_op
column_op()
virtual bool MutableMatrix::column_op (size_t i, ring_elem r, size_t j) pure virtual
Implemented in MutableMat< Mat >.
Referenced by FF_LUComputation::do_pivots(), IM2_MutableMatrix_column_operation(), and LLLoperations::REDI().