Macaulay2 Engine: MutableMatrix::get_ring
get_ring()
virtual const Ring* MutableMatrix::get_ring () const pure virtual
Implemented in MutableMat< Mat >.
Referenced by IM2_Matrix_dot_product(), IM2_MutableMatrix_column_2by2(), IM2_MutableMatrix_column_operation(), IM2_MutableMatrix_column_scale(), IM2_MutableMatrix_get_entry(), IM2_MutableMatrix_row_2by2(), IM2_MutableMatrix_row_operation(), IM2_MutableMatrix_row_scale(), IM2_MutableMatrix_set_entry(), LLLoperations::initializeLLL(), rawIdealOfPoints(), rawLeastSquares(), rawLinAlgCharPoly(), rawLinAlgMinPoly(), rawMutableMatrixClean(), rawMutableMatrixFillRandom(), rawMutableMatrixFillRandomDensity(), MutableMat< Mat >::solveInvertible(), MutableMat< Mat >::solveLinear(), text_out(), and HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track().