Macaulay2 Engine: MutableMatrix::n_rows
n_rows()
virtual size_t MutableMatrix::n_rows () const pure virtual
Implemented in MutableMat< Mat >.
Referenced by fp_LLL(), IM2_MutableMatrix_get_entry(), IM2_MutableMatrix_n_rows(), IM2_MutableMatrix_row_operation(), IM2_MutableMatrix_row_permute(), IM2_MutableMatrix_row_scale(), IM2_MutableMatrix_row_swap(), IM2_MutableMatrix_set_entry(), MutableComplex::MutableComplex(), mutableMatrix_to_NTL_mat_ZZ(), ntl_LLL(), rawLeastSquares(), rawLinAlgCharPoly(), rawMutableMatrixFillRandom(), rawMutableMatrixFillRandomDensity(), rawMutableMatrixLift(), rawMutableMatrixPromote(), rawRingMapEvalMutableMatrix(), MutableMat< Mat >::solveInvertible(), MutableMat< Mat >::solveLinear(), and text_out().