Macaulay2 Engine: MutableMatrix::zero_matrix
zero_matrix()
MutableMatrix * MutableMatrix::zero_matrix (const Ring * R, size_t nrows, size_t ncols, bool dense) static
Definition at line 54 of file mat.cpp.
{
  MutableMatrix *result = R->makeMutableMatrix(nrows, ncols, dense);
  if (result != nullptr) return result;
  // In this case, we just use ring elem arithmetic
  const CoefficientRingR *cR = R->getCoefficientRingR();
  if (dense)
    return new MutableMat<DMat<CoefficientRingR> >(R, cR, nrows, ncols);
  else
    return new MutableMat<SMat<CoefficientRingR> >(R, cR, nrows, ncols);
}
References Ring::getCoefficientRingR(), and Ring::makeMutableMatrix().
Referenced by from_matrix(), identity(), IM2_MutableMatrix_make(), LLLoperations::initializeLLL(), mutableMatrix_from_NTL_mat_ZZ(), rawMutableMatrixLift(), rawMutableMatrixPromote(), rawRingMapEvalMutableMatrix(), ResF4toM2Interface::to_M2_MutableMatrix(), and ResF4toM2Interface::to_M2_MutableMatrix().