Macaulay2 Engine: MutableMatrix::n_cols
n_cols()
virtual size_t MutableMatrix::n_cols () const pure virtual
Implemented in MutableMat< Mat >.
Referenced by LLLoperations::doLLL(), FF_LUComputation::FF_LUComputation(), fp_LLL(), FF_LUComputation::get_column_permutation(), IM2_MutableMatrix_column_operation(), IM2_MutableMatrix_column_permute(), IM2_MutableMatrix_column_scale(), IM2_MutableMatrix_column_swap(), IM2_MutableMatrix_get_entry(), IM2_MutableMatrix_n_cols(), IM2_MutableMatrix_set_entry(), LLLoperations::initializeLLL(), MutableComplex::MutableComplex(), mutableMatrix_to_NTL_mat_ZZ(), ntl_LLL(), rawMutableMatrixFillRandom(), rawMutableMatrixFillRandomDensity(), rawMutableMatrixLift(), rawMutableMatrixPromote(), rawRingMapEvalMutableMatrix(), and text_out().