Macaulay2 Engine: MutableMatrix::coerce
coerce()
template<typename MatT > MatT* MutableMatrix::coerce () inline
Definition at line 96 of file mat.hpp.
   {
     MutableMat<MatT> *P = cast_to_MutableMat<MatT>();
     if (P == 0) return 0;
     return P->get_Mat();
   }
References MutableMat< Mat >::get_Mat().
Referenced by MutableMat< Mat >::eigenvalues(), MutableMat< Mat >::eigenvectors(), MutableMat< Mat >::least_squares(), MutableMat< Mat >::LU(), MutableMat< Mat >::QR(), and MutableMat< Mat >::SVD().