Macaulay2 Engine: MutableMatrix::identity
identity()
MutableMatrix * MutableMatrix::identity (const Ring * R, size_t nrows, bool dense) static
Definition at line 69 of file mat.cpp.
 {
   MutableMatrix *result = MutableMatrix::zero_matrix(R, nrows, nrows, dense);
   for (size_t i = 0; i < nrows; i++) result->set_entry(i, i, R->from_long(1));
   return result;
 }
References Ring::from_long(), set_entry(), and zero_matrix().
Referenced by IM2_MutableMatrix_identity(), and MutableComplex::prune_complex().