Macaulay2 Engine: MutableMatrix::text_out
text_out()
void MutableMatrix::text_out (buffer & o) const
Definition at line 89 of file mat.cpp.
 {
   const Ring *R = get_ring();
   size_t nrows = n_rows();
   size_t ncols = n_cols();
   buffer *p = new buffer[nrows];
   size_t r;
   for (size_t c = 0; c < ncols; c++)
     {
       size_t maxcount = 0;
       for (r = 0; r < nrows; r++)
         {
           ring_elem f;
           get_entry(r, c, f);
           if (!R->is_zero(f))
             R->elem_text_out(p[r], f);
           else
             p[r] << ".";
           if (p[r].size() > maxcount) maxcount = p[r].size();
         }
       for (r = 0; r < nrows; r++)
         for (size_t k = maxcount + 1 - p[r].size(); k > 0; k--) p[r] << ' ';
     }
   for (r = 0; r < nrows; r++)
     {
       p[r] << '\0';
       char *s = p[r].str();
       o << s << newline;
     }
   delete[] p;
 }
References Ring::elem_text_out(), get_entry(), get_ring(), Ring::is_zero(), n_cols(), n_rows(), newline, and p.
Referenced by dmutablemat(), IM2_MutableMatrix_to_string(), F4GB::show_matrix(), and F4GB::show_new_rows_matrix().