Macaulay2 Engine: MutableMatrix::coerce_const
coerce_const()
template<typename MatT > const MatT* MutableMatrix::coerce_const () const inline
Definition at line 104 of file mat.hpp.
   {
     const MutableMat<MatT> *P = cast_to_MutableMat<MatT>();
     if (P == 0) return 0;
     return P->get_Mat();
   }
References MutableMat< Mat >::get_Mat().
Referenced by MutableMat< Mat >::add(), MutableMat< Mat >::addMultipleTo(), MutableMat< Mat >::least_squares(), MutableMat< Mat >::mult(), MutableMat< Mat >::solveInvertible(), MutableMat< Mat >::solveLinear(), MutableMat< Mat >::subtract(), and MutableMat< Mat >::subtractMultipleTo().