Macaulay2 Engine: MutableMatrix::set_entry
set_entry()
virtual bool MutableMatrix::set_entry (size_t r, size_t c, const ring_elem a) pure virtual
Implemented in MutableMat< Mat >.
Referenced by LLLoperations::doLLL(), fp_LLL(), from_matrix(), identity(), IM2_MutableMatrix_set_entry(), LLLoperations::initializeLLL(), mutableMatrix_from_NTL_mat_ZZ(), ntl_LLL(), rawMutableMatrixFillRandom(), rawMutableMatrixFillRandomDensity(), set_values(), F4GB::show_new_rows_matrix(), LLLoperations::SWAPI(), F4toM2Interface::to_M2_MutableMatrix(), and ResF4toM2Interface::to_M2_MutableMatrix().