Macaulay2 Engine: MutableMatrix::is_dense
is_dense()
virtual bool MutableMatrix::is_dense () const pure virtual
Implemented in MutableMat< Mat >.
Referenced by LLLoperations::initializeLLL(), rawMutableMatrixIsDense(), rawMutableMatrixLift(), rawMutableMatrixPromote(), and rawRingMapEvalMutableMatrix().