Macaulay2 Engine: toMatrix
toMatrix() [1/2]
template<typename CoeffRing > Matrix* toMatrix (const Ring * R, const DMat< CoeffRing > & A)
Definition at line 89 of file mutablemat-defs.hpp.
 {
   int nrows = static_cast<int>(A.numRows());
   int ncols = static_cast<int>(A.numColumns());
   FreeModule* F = R->make_FreeModule(nrows);
   MatrixConstructor result(F, ncols);
   if (nrows == 0 || ncols == 0) return result.to_matrix();
   for (int c = 0; c < ncols; c++)
     {
       int r = 0;
       auto end = A.columnEnd(c);
       for (auto j = A.columnBegin(c); not(j == end); ++j, ++r)
         {
           if (not A.ring().is_zero(*j))
             {
               ring_elem a;
               A.ring().to_ring_elem(a, *j);
               result.set_entry(r, c, a);
             }
         }
     }
   result.compute_column_degrees();
   return result.to_matrix();
 }
References DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::columnEnd(), MatrixConstructor::compute_column_degrees(), end(), Ring::make_FreeModule(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::ring(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by MutableMat< Mat >::to_matrix().