Macaulay2 Engine: toMatrix
toMatrix() [2/2]
template<typename CoeffRing > Matrix* toMatrix (const Ring * R, const SMat< CoeffRing > & A)
Definition at line 115 of file mutablemat-defs.hpp.
 {
   int nrows = static_cast<int>(A.numRows());
   int ncols = static_cast<int>(A.numColumns());
   FreeModule* F = R->make_FreeModule(nrows);
   MatrixConstructor result(F, ncols);
   if (nrows == 0 || ncols == 0) return result.to_matrix();
   ring_elem f;
   auto i = A.begin();
   for (int c = 0; c < ncols; c++)
     {
       ring_elem a;
       for (i.set(c); i.valid(); i.next())
         {
           i.copy_elem(a);
           int r = static_cast<int>(i.row());
           result.set_entry(r, c, a);
         }
     }
   result.compute_column_degrees();
   return result.to_matrix();
 }
References SMat< ACoeffRing >::begin(), MatrixConstructor::compute_column_degrees(), Ring::make_FreeModule(), SMat< ACoeffRing >::numColumns(), SMat< ACoeffRing >::numRows(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().