Macaulay2 Engine: error_row_bound
error_row_bound()
bool error_row_bound (size_t r, size_t nrows) inline
Definition at line 148 of file mutablemat-defs.hpp.
{
  if (r >= nrows)
    {
      ERROR("row out of range");
      return true;
    }
  return false;
}
References ERROR().
Referenced by MutableMat< Mat >::delete_rows(), MutableMat< Mat >::divide_row(), MutableMat< Mat >::interchange_rows(), MutableMat< Mat >::row2by2(), MutableMat< Mat >::row_op(), MutableMat< Mat >::scale_row(), and MutableMat< Mat >::set_entry().