Macaulay2 Engine: IM2_MutableMatrix_identity
IM2_MutableMatrix_identity()
MutableMatrix* IM2_MutableMatrix_identity (const Ring * R, int nrows, M2_bool prefer_dense)
MutableMatrix interface routines
Also: Fraction free LU decomposition LLL bases Lapack routines for dense mutable matrices Fast linear algebra routines Special routines for objects over RRR,CCC
Definition at line 25 of file mutable-matrix.cpp.
 {
   if (n < 0)
     {
       ERROR("expected non-negative integer");
       return 0;
     }
   size_t nrows = static_cast<size_t>(n);
   return internMutableMatrix(MutableMatrix::identity(R, nrows, is_dense));
 }
References ERROR(), MutableMatrix::identity(), and internMutableMatrix().