Macaulay2 Engine: rawMutableMatrixFillRandomDensity
rawMutableMatrixFillRandomDensity()
void rawMutableMatrixFillRandomDensity (MutableMatrix * M, double density, int special_type)
Definition at line 127 of file mutable-matrix.cpp.
 {
   bool doing_fraction = false;
   int threshold = 0;
   int nrows = static_cast<int>(M->n_rows());
   int ncols = static_cast<int>(M->n_cols());
   const Ring *R = M->get_ring();
   if (density != 1.0)
     {
       doing_fraction = true;
       threshold = static_cast<int>(density * 10000);
     }
   if (special_type == 0)
     {
       for (int i = 0; i < ncols; i++)
         for (int j = 0; j < nrows; j++)
           {
             if (doing_fraction)
               {
                 int32_t u = rawRandomInt((int32_t)10000);
                 if (u > threshold) continue;
               }
             ring_elem a = R->random();
             if (!R->is_zero(a)) M->set_entry(j, i, a);
           }
     }
   else if (special_type == 1)
     {
       for (int i = 0; i < ncols; i++)
         {
           int top = (i >= nrows ? nrows : i);
           for (int j = 0; j < top; j++)
             {
               if (doing_fraction)
                 {
                   int32_t u = rawRandomInt((int32_t)10000);
                   if (u > threshold) continue;
                 }
               ring_elem a = R->random();
               if (!R->is_zero(a)) M->set_entry(j, i, a);
             }
         }
     }
 }
References MutableMatrix::get_ring(), Ring::is_zero(), MutableMatrix::n_cols(), MutableMatrix::n_rows(), Ring::random(), rawRandomInt(), and MutableMatrix::set_entry().