Macaulay2 Engine: IM2_MutableMatrix_row_permute
IM2_MutableMatrix_row_permute()
M2_bool IM2_MutableMatrix_row_permute (MutableMatrix * M, int start, M2_arrayint perm)
Definition at line 413 of file mutable-matrix.cpp.
 {
   size_t nrows = M->n_rows();
   if (start < 0 || start + perm->len > nrows)
     {
       ERROR("row indices out of range");
       return false;
     }
   for (int i = 0; i < perm->len; i++)
     {
       int r = start + perm->array[i];
       if (r < 0 || r >= nrows)
         {
           ERROR("row indices out of range");
           return false;
         }
     }
   return M->row_permute(start, perm);
 }
References ERROR(), MutableMatrix::n_rows(), and MutableMatrix::row_permute().