Macaulay2 Engine: rawRingElementClean
rawRingElementClean()
const RingElement* rawRingElementClean (gmp_RR epsilon, const RingElement * f)
Definition at line 1042 of file mutable-matrix.cpp.
 {
   const Ring *R = f->get_ring();
   if (R->get_precision() == 0)
     {
       ERROR("expected ring over an RR or CC");
       return 0;
     }
   return RingElement::make_raw(R, R->zeroize_tiny(epsilon, f->get_value()));
 }
References ERROR(), Ring::get_precision(), RingElement::get_ring(), RingElement::get_value(), RingElement::make_raw(), and Ring::zeroize_tiny().