Macaulay2 Engine: rawRingElementNorm
rawRingElementNorm()
gmp_RRorNull rawRingElementNorm (gmp_RR p, const RingElement * f)
Definition at line 1093 of file mutable-matrix.cpp.
 {
   gmp_RRmutable norm = get_norm_start(p, f->get_ring());
   if (!norm) return nullptr;  // error already given.
   f->get_ring()->increase_maxnorm(norm, f->get_value());
   return moveTo_gmpRR(norm);
 }
References get_norm_start(), RingElement::get_ring(), RingElement::get_value(), Ring::increase_maxnorm(), moveTo_gmpRR(), and p.