Macaulay2 Engine: rawLinAlgCharPoly
rawLinAlgCharPoly()
engine_RawRingElementArrayOrNull rawLinAlgCharPoly (MutableMatrix * A)
Definition at line 944 of file mutable-matrix.cpp.
 {
 #if 1
 #if 0
   const Ring *R = A->get_ring();
   typedef DMat<M2::ARingZZpFFPACK> DMatZZp;
   MutableMat<DMatZZp> *B = A->cast_to_MutableMat<DMatZZp>();
   if (B == 0)
     {
       ERROR("expected a dense mutable matrix over the ffpack finite field");
       return 0;
     }
   M2::ARingZZpFFPACK::ElementType *elemsA = B->get_Mat()->array();
   std::vector<M2::ARingZZpFFPACK::ElementType> charpoly;
   // CharPoly isn't there any more (?)
   FFPACK::CharPoly(B->get_Mat()->ring().field(), charpoly, A->n_rows(),
   elemsA, A->n_rows());
   for (size_t i = 0; i < charpoly.size(); i++) std::cout << charpoly[i] << " ";
   std::cout << std::endl;
   return convertRingelemsToArray(R, charpoly);
 #else
   return nullptr;
 #endif
 #else
   ERROR("not implemented: configure M2 with --enable-ffpack-fflas");
   return 0;
 #endif
 }
References MutableMatrix::cast_to_MutableMat(), convertRingelemsToArray(), ERROR(), MutableMat< Mat >::get_Mat(), MutableMatrix::get_ring(), and MutableMatrix::n_rows().