Macaulay2 Engine: get_norm_start
get_norm_start()
static gmp_RRmutable get_norm_start (gmp_RR p, const Ring * R) static
Definition at line 1073 of file mutable-matrix.cpp.
 {
   if (R->get_precision() == 0)
     {
       ERROR("expected ring over an RR or CC");
       return 0;
     }
   gmp_RRmutable norm = getmemstructtype(gmp_RRmutable);
   mpfr_init2(norm, mpfr_get_prec(p));
   mpfr_ui_div(norm, 1, p, MPFR_RNDN);
   if (!mpfr_zero_p(norm))
     {
       ERROR("Lp norm only implemented for p = infinity");
       mpfr_clear(norm);
       return 0;
     }
   return norm;
 }
References ERROR(), Ring::get_precision(), getmemstructtype, and p.
Referenced by rawRingElementNorm().