Macaulay2 Engine: rawMutableMatrixPromote
rawMutableMatrixPromote()
MutableMatrix* rawMutableMatrixPromote (const Ring * S, const MutableMatrix * f)
Definition at line 69 of file mutable-matrix.cpp.
 {
   // Given a natural map i : R --> S
   // f is a matrix over R.
   // returns a matrix over S.
   ERROR("MutableMatrix promote not implemented yet");
   return nullptr;
 #if 0
   auto result = MutableMatrix::zero_matrix(S, f->n_rows(), f->n_cols(), f->is_dense());
   return result;
 #endif
 }
References ERROR(), MutableMatrix::is_dense(), MutableMatrix::n_cols(), MutableMatrix::n_rows(), and MutableMatrix::zero_matrix().