Macaulay2 Engine: IM2_MutableMatrix_set_entry
IM2_MutableMatrix_set_entry()
M2_bool IM2_MutableMatrix_set_entry (MutableMatrix * M, int r, int c, const RingElement * a)
Definition at line 196 of file mutable-matrix.cpp.
 {
   const Ring *R = M->get_ring();
   if (R != a->get_ring())
     {
       ERROR("expected same ring");
       return 0;
     }
   if (r < 0 || r >= M->n_rows())
     {
       ERROR("row index %d out of range 0..%d", r, M->n_rows() - 1);
       return 0;
     }
   if (c < 0 || c >= M->n_cols())
     {
       ERROR("column index %d out of range 0..%d", c, M->n_cols() - 1);
       return 0;
     }
   M->set_entry(r, c, a->get_value());
   return 1;
 }
References ERROR(), RingElement::get_ring(), MutableMatrix::get_ring(), RingElement::get_value(), MutableMatrix::n_cols(), MutableMatrix::n_rows(), and MutableMatrix::set_entry().