Macaulay2 Engine: rawEigenvalues
rawEigenvalues()
M2_bool rawEigenvalues (MutableMatrix * A, MutableMatrix * eigenvalues, M2_bool is_symm_or_hermitian)
Definition at line 670 of file mutable-matrix.cpp.
 {
   try
     {
       return A->eigenvalues(eigenvalues, is_symm_or_hermitian);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return false;
   }
 }
References EigenM2::eigenvalues(), MutableMatrix::eigenvalues(), and ERROR().