Macaulay2 Engine: IM2_Matrix_dot_product
IM2_Matrix_dot_product()
const RingElement* IM2_Matrix_dot_product (const MutableMatrix * M, int c1, int c2)
Definition at line 461 of file mutable-matrix.cpp.
 {
   ring_elem a;
   M->dot_product(c1, c2, a);
   return RingElement::make_raw(M->get_ring(), a);
 }
References MutableMatrix::dot_product(), MutableMatrix::get_ring(), and RingElement::make_raw().