Macaulay2 Engine: convertRingelemsToArray
convertRingelemsToArray()
engine_RawRingElementArray convertRingelemsToArray (const Ring * R, std::vector< M2::ARingZZpFFPACK::ElementType > & elems)
Definition at line 930 of file mutable-matrix.cpp.
 {
   size_t len = elems.size();
   engine_RawRingElementArray result =
       getmemarraytype(engine_RawRingElementArray, len);
   result->len = static_cast<int>(len);
   for (size_t i = 0; i < len; i++)
     result->array[i] = RingElement::make_raw(R, static_cast<int>(elems[i]));
   return result;
 }
References getmemarraytype, and RingElement::make_raw().
Referenced by rawLinAlgCharPoly(), and rawLinAlgMinPoly().