Macaulay2 Engine: rawEigenvectors
rawEigenvectors()
M2_bool rawEigenvectors (MutableMatrix * A, MutableMatrix * eigenvalues, MutableMatrix * eigenvectors, M2_bool is_symm_or_hermitian)
Definition at line 684 of file mutable-matrix.cpp.
 {
   try
     {
       return A->eigenvectors(eigenvalues, eigenvectors, is_symm_or_hermitian);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return false;
   }
 }
References EigenM2::eigenvalues(), EigenM2::eigenvectors(), MutableMatrix::eigenvectors(), and ERROR().