Macaulay2 Engine: newf4::PolynomialListStreamCollector::appendPolynomialDone
appendPolynomialDone()
void newf4::PolynomialListStreamCollector::appendPolynomialDone ()
Definition at line 45 of file PolynomialList.cpp.
 {
   mValue[mCurrentPoly].mCoefficients = mValue.vectorArithmetic().elementArrayFromContainerOfLongs(mCoefficients);
   if (mCurrentTerm != mValue[mCurrentPoly].mComponents.size() - 1)
     throw exc::engine_error("internal error: building PolyList from stream has incorrect number of terms in a polynomial");
 }
References VectorArithmetic::elementArrayFromContainerOfLongs(), mCoefficients, mCurrentPoly, mCurrentTerm, mValue, newf4::PolynomialList::size(), and newf4::PolynomialList::vectorArithmetic().