Macaulay2 Engine: newf4::MonomialLookupTable::insertMonomial
insertMonomial()
void newf4::MonomialLookupTable::insertMonomial (const MonomialView monView, int index)
Definition at line 10 of file MonomialLookupTable.cpp.
 {
   MonomialInfo newMonomialInfo;
   newMonomialInfo.mIsUsed = true;
   newMonomialInfo.mSimpleDegree = monView.simpleDegree();
   newMonomialInfo.mMask = createMask(monView);
   newMonomialInfo.mOffset = mMonomialSpace.size();
   mMonomialSpace.insert(mMonomialSpace.end(), monView.dataBegin(), monView.dataEnd());
   newMonomialInfo.mValue = index;
   mMonomialInfo.push_back(newMonomialInfo);
 }
References createMask(), newf4::MonomialView::dataBegin(), newf4::MonomialView::dataEnd(), newf4::MonomialInfo::mIsUsed, newf4::MonomialInfo::mMask, mMonomialInfo, mMonomialSpace, newf4::MonomialInfo::mOffset, newf4::MonomialInfo::mSimpleDegree, newf4::MonomialInfo::mValue, and newf4::MonomialView::simpleDegree().