Macaulay2 Engine: newf4::MonomialLookupTable::findAllDivisees
findAllDivisees() [2/2]
void newf4::MonomialLookupTable::findAllDivisees (const MonomialView monView, std::vector< int > & result) const
Definition at line 75 of file MonomialLookupTable.cpp.
 {
   int curIndex = 0;
   MonomialMask mask = createMask(monView);
   for (; curIndex < mMonomialInfo.size(); ++curIndex)
   {
     auto m = mMonomialInfo[curIndex];
     if (m.mIsUsed && maskDivides(mask,m.mMask))
     {
        // ugh with the const_cast, but MonomialInt doesn't store const pointers
        MonomialView mvDivisee(const_cast<MonomialInt*>(mMonomialSpace.data() + m.mOffset));
        if ((monView.simpleDegree() <= m.mSimpleDegree) &&
        (MonomialView::monomialDivides(monView, mvDivisee)))
        {
       result.push_back(curIndex);
        }
     }
   }
 }
References createMask(), maskDivides(), mMonomialInfo, mMonomialSpace, newf4::MonomialView::monomialDivides(), and newf4::MonomialView::simpleDegree().