Macaulay2 Engine: matrixFromSparseMatrixGenerator
matrixFromSparseMatrixGenerator()
template<typename Gen > Matrix* matrixFromSparseMatrixGenerator (Gen & G)
Definition at line 537 of file res-f4-m2-interface.cpp.
 {
   const Ring* R = G.ring();
   MatrixConstructor M(R->make_FreeModule(G.numRows()), R->make_FreeModule(G.numColumns()), nullptr);
   for (auto i = G.begin(); i != G.end(); ++i)
     {
       for (int j=i.components().size()-1; j>=0; --j)
       {
         M.set_entry(i.components()[j], i.column(), R->from_long(i.coefficients()[j]));
       }
     }
   return M.to_matrix();
 }
References Ring::from_long(), G, Ring::make_FreeModule(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by SchreyerFrame::rankUsingSparseMatrix().