Macaulay2 Engine: setDMatFromSparseMatrixGenerator
setDMatFromSparseMatrixGenerator()
template<typename RingType , typename Gen > void setDMatFromSparseMatrixGenerator (Gen & G, DMat< RingType > & M)
Definition at line 697 of file res-f4-m2-interface.cpp.
 {
   M.resize(G.numRows(), G.numColumns());
   for (auto i = G.begin(); i != G.end(); ++i)
     {
       for (int j=0; j<i.components().size(); ++j)
       {
         M.ring().set_from_long(M.entry(i.components()[j], i.column()), i.coefficients()[j]);
       }
     }
 }
References DMat< ACoeffRing >::entry(), DMat< ACoeffRing >::resize(), and DMat< ACoeffRing >::ring().
Referenced by SchreyerFrame::rankUsingDenseMatrix(), and SchreyerFrame::rankUsingDenseMatrixFlint().