Macaulay2 Engine: TEST
TEST() [1/9]
TEST (RingCCC , add)
Definition at line 59 of file RingCCCTest.cpp.
 {
   RingCCC *R = RingCCC::create(100);
   RingElementGenerator<RingCCC> gen(*R);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (a+b) + (-b) == a
       ring_elem a = gen.nextElement();
       ring_elem b = gen.nextElement();
       ring_elem c = R->add(a, b);
       ring_elem d = R->negate(b);
       ring_elem e = R->add(c, d);  // should be a
       EXPECT_TRUE(almostEqual(R, 98, a, e));
     }
 }
References M2::ConcreteRing< RingType >::add(), almostEqual(), M2::ConcreteRing< RingType >::create(), M2::ConcreteRing< RingType >::negate(), RingElementGenerator< RingType >::nextElement(), and ntrials.