Macaulay2 Engine: TEST
TEST() [2/9]
TEST (RingCCC , axioms)
Definition at line 99 of file RingCCCTest.cpp.
 {
   RingCCC *R = RingCCC::create(100);
   RingElementGenerator<RingCCC> gen(*R);
   for (int i = 0; i < ntrials; i++)
     {
       ring_elem a = gen.nextElement();
       ring_elem b = gen.nextElement();
       ring_elem c = gen.nextElement();
       // Test commutativity
       // test: a*b = b*a
       // test: a+b == b+a
       ring_elem d = R->add(a, b);
       ring_elem e = R->add(b, a);
       EXPECT_TRUE(R->is_equal(d, e));
       d = R->mult(a, b);
       e = R->mult(b, a);
       EXPECT_TRUE(almostEqual(R, 98, d, e));
       // Test associativity
       // test: a+(b+c) == (a+b)+c
       // test: a*(b*c) == (a*b)*c
       d = R->add(a, R->add(b, c));
       e = R->add(R->add(a, b), c);
       EXPECT_TRUE(almostEqual(R, 94, d, e));
       d = R->mult(a, R->mult(b, c));
       e = R->mult(R->mult(a, b), c);
       EXPECT_TRUE(almostEqual(R, 94, d, e));
       // Test distributivity
       // test: a*(b+c) == a*b + a*c
       d = R->mult(a, R->add(b, c));
       e = R->add(R->mult(a, b), R->mult(a, c));
 #if 0
       mpfr_printf("a=(%.20Rf,%.20Rf)\n",BIGCC_RE(a), BIGCC_IM(a));
       mpfr_printf("b=(%.20Rf,%.20Rf)\n",BIGCC_RE(b), BIGCC_IM(b));
       mpfr_printf("a*(b+c)=(%.20Rf,%.20Rf)\n",BIGCC_RE(d), BIGCC_IM(d));
       mpfr_printf("a*b+a*c=(%.20Rf,%.20Rf)\n",BIGCC_RE(e), BIGCC_IM(e));
 #endif
       EXPECT_TRUE(almostEqual(R, 92, d, e));
     }
 }
References M2::ConcreteRing< RingType >::add(), almostEqual(), BIGCC_IM, BIGCC_RE, M2::ConcreteRing< RingType >::create(), M2::ConcreteRing< RingType >::is_equal(), M2::ConcreteRing< RingType >::mult(), RingElementGenerator< RingType >::nextElement(), and ntrials.