Macaulay2 Engine: TEST
TEST() [7/9]
TEST (RingCCC , power)
Definition at line 142 of file RingCCCTest.cpp.
 {
   RingCCC *R = RingCCC::create(100);
   mpz_t gmp1;
   mpz_init(gmp1);
   RingElementGenerator<RingCCC> gen(*R);
   for (int i = 0; i < ntrials; i++)
     {
       ring_elem a = gen.nextElement();
       // TODO: what should the answer here be?
       // EXPECT_TRUE(R->is_equal(R->power(a, 0), R->one())); // 0^0 == 1 too?
       EXPECT_TRUE(R->is_equal(R->power(a, 1), a));
       int e1 = rawRandomInt(10) + 1;
       int e2 = rawRandomInt(10) + 1;
       // std::cout << "(" << e1 << "," << e2 << ")" << std::endl;
       ring_elem b = R->power(a, e1);
       ring_elem c = R->power(a, e2);
       ring_elem d = R->power(a, e1 + e2);
 #if 0
       ring_elem e = R->mult(b,c);
       mpfr_printf("b=(%.30Rf,%.30Rf)\n",BIGCC_RE(b), BIGCC_IM(b));
       mpfr_printf("c=(%.30Rf,%.30Rf)\n",BIGCC_RE(c), BIGCC_IM(c));
       mpfr_printf("d=(%.30Rf,%.30Rf)\n",BIGCC_RE(d), BIGCC_IM(d));
       mpfr_printf("e=(%.30Rf,%.30Rf)\n",BIGCC_RE(e), BIGCC_IM(e));
 #endif
       EXPECT_TRUE(almostEqual(R, 80, R->mult(b, c), d));
       // Make sure that powers via mpz work (at least for small exponents)
       mpz_set_si(gmp1, e1);
       ring_elem b1 = R->power(a, gmp1);
       EXPECT_TRUE(R->is_equal(b1, b));
     }
   mpz_clear(gmp1);
 }
References almostEqual(), BIGCC_IM, BIGCC_RE, M2::ConcreteRing< RingType >::create(), M2::ConcreteRing< RingType >::is_equal(), M2::ConcreteRing< RingType >::mult(), RingElementGenerator< RingType >::nextElement(), ntrials, M2::ConcreteRing< RingType >::power(), and rawRandomInt().