Macaulay2 Engine: displayMat
displayMat() [1/2]
template<typename Mat > void displayMat (buffer & o, const Mat & A)
Definition at line 14 of file mat-util.hpp.
 {
   // Assumption: Mat is either DMat<RingType> or SMat<RingType>, in that it
   // defines the following:
   // Mat::ElementType
   // A.ring()
   // A.numRows(), A.numColumns()
   // A.entry(r,c)
   // and A.ring().elem_text_out
   size_t nrows = A.numRows();
   size_t ncols = A.numColumns();
   buffer* p = new buffer[nrows];
   size_t r;
   for (size_t c = 0; c < ncols; c++)
     {
       size_t maxcount = 0;
       for (r = 0; r < nrows; r++)
         {
           const typename Mat::ElementType& a = A.entry(r, c);
           if (!A.ring().is_zero(a))
             A.ring().elem_text_out(p[r], a, true, false, false);
           else
             p[r] << ".";
           if (p[r].size() > maxcount) maxcount = p[r].size();
         }
       for (r = 0; r < nrows; r++)
         for (size_t k = maxcount + 1 - p[r].size(); k > 0; k--) p[r] << ' ';
     }
   for (r = 0; r < nrows; r++)
     {
       p[r] << '\0';
       char* s = p[r].str();
       o << s << newline;
     }
   delete[] p;
 }
References newline, and p.
Referenced by DMatLinAlg< RingType >::debug_out(), LUUtil< RT >::debug_out(), displayMat(), and TEST().