Macaulay2 Engine: copyMatrixToVector
copyMatrixToVector()
ConstPolyList copyMatrixToVector (const M2FreeAlgebra & F, const Matrix * input)
Definition at line 12 of file M2FreeAlgebraQuotient.cpp.
 {
   ConstPolyList result;
   result.reserve(input->n_cols());
   for (int i=0; i<input->n_cols(); i++)
     {
       ring_elem a = input->elem(0,i);
       auto f = reinterpret_cast<const Poly*>(a.get_Poly());
       auto g = new Poly;
       F.freeAlgebra().copy(*g, *f);
       result.push_back(g);
     }
   return result;
 }
References FreeAlgebra::copy(), Matrix::elem(), M2FreeAlgebra::freeAlgebra(), ring_elem::get_Poly(), and Matrix::n_cols().
Referenced by M2FreeAlgebraQuotient::create().