Macaulay2 Engine: BIBasis::BooleanInvolutiveBasis::ToMatrix
ToMatrix()
template<typename MonomType > const Matrix * BIBasis::BooleanInvolutiveBasis< MonomType >::ToMatrix
Definition at line 109 of file involutive.hpp.
     {
         MatrixConstructor matrixConstructor(PRing->make_FreeModule(1), 0);
         const Monoid* monoid = PRing->getMonoid();
         const ring_elem coefficientUnit = PRing->getCoefficients()->one();
         monomial tmpRingMonomial = monoid->make_one();
         for (typename std::list<Polynom<MonomType>*>::const_iterator currentPolynom = GBasis.begin();
              currentPolynom != GBasis.end();
              ++currentPolynom)
         {
             if (!*currentPolynom)
             {
                 continue;
             }
             ring_elem currentRingPolynomial;
             for (const MonomType* currentMonom = &(**currentPolynom).Lm();
                  currentMonom;
                  currentMonom = currentMonom->Next)
             {
                 exponents_t currentExponent = newarray_atomic_clear(int, MonomType::GetDimIndepend());
                 typename std::set<typename MonomType::Integer> variablesSet = currentMonom->GetVariablesSet();
                 for (typename std::set<typename MonomType::Integer>::const_iterator currentVariable = variablesSet.begin();
                      currentVariable != variablesSet.end();
                      ++currentVariable)
                 {
                     currentExponent[*currentVariable] = 1;
                 }
                 monoid->from_expvector(currentExponent, tmpRingMonomial);
                 freemem(currentExponent);
                 ring_elem tmpRingPolynomial = PRing->make_flat_term(coefficientUnit, tmpRingMonomial);
                 PRing->add_to(currentRingPolynomial, tmpRingPolynomial);
             }
             matrixConstructor.append(PRing->make_vec(0, currentRingPolynomial));
         }
         return matrixConstructor.to_matrix();
     }
References MatrixConstructor::append(), freemem(), Monoid::from_expvector(), Monoid::make_one(), newarray_atomic_clear, and MatrixConstructor::to_matrix().
Referenced by BIBasis::Launcher::GetBIBasisMatrix().