Macaulay2 Engine: BIBasis::BooleanInvolutiveBasis::Construct
Construct()
template<typename MonomType > void BIBasis::BooleanInvolutiveBasis< MonomType >::Construct (const std::list< Polynom< MonomType > * > & set, bool toGroebner) private
Definition at line 370 of file involutive.hpp.
     {
         Reset();
         GBasis = set;
         ReduceSet(true);
         ProlongationsSet.Insert(GBasis);
         GBasis.clear();
         ConstructInvolutiveBasis();
         ProlongationsSet.Clear();
         typename TSet<MonomType>::ConstIterator i2(IntermediateBasis.Begin());
         while (i2 != IntermediateBasis.End())
         {
             GBasis.push_back(const_cast<Polynom<MonomType>*>((**i2).GetPolynom()));
             ++i2;
         }
         ReduceSet(toGroebner);
     }
References BIBasis::TSet< MonomType >::End(), and set().
Referenced by BIBasis::BooleanInvolutiveBasis< MonomType >::BooleanInvolutiveBasis().