Macaulay2 Engine: BIBasis::BooleanInvolutiveBasis::FindDivisor
FindDivisor()
template<typename MonomType > const Polynom< MonomType > * BIBasis::BooleanInvolutiveBasis< MonomType >::FindDivisor (const Polynom< MonomType > * polynom, const std::list< Polynom< MonomType > * > & set, bool toGroebner) const private
Definition at line 250 of file involutive.hpp.
     {
         if (!polynom || polynom->IsZero())
         {
             return 0;
         }
         typename std::list<Polynom<MonomType>*>::const_iterator it(set.begin()), setEnd(set.end());
         const MonomType& plm = polynom->Lm();
         while (it != setEnd)
         {
             if (toGroebner && plm.IsDivisibleBy((**it).Lm()))
             {
                 return *it;
             }
             else if (!toGroebner && plm.IsPommaretDivisibleBy((**it).Lm()))
             {
                 return *it;
             }
             ++it;
         }
         return 0;
     }
References BIBasis::Polynom< MonomType >::IsZero(), BIBasis::Polynom< MonomType >::Lm(), and set().