Macaulay2 Engine: BIBasis::BooleanInvolutiveBasis::FillInitialSet
FillInitialSet()
template<typename MonomType > void BIBasis::BooleanInvolutiveBasis< MonomType >::FillInitialSet (const Matrix * matrix, std::list< Polynom< MonomType > * > & initialSet) const private
Definition at line 155 of file involutive.hpp.
     {
         const Monoid* monoid = PRing->getMonoid();
         typename MonomType::Integer independ = MonomType::GetDimIndepend();
         //construct Polynom for every column in matrix
         for (int column = 0; column < matrix->n_cols(); ++column)
         {
             vec polynomVector = matrix->elem(column);
             if (!polynomVector)
             {
                 continue;
             }
             Polynom<MonomType>* currentPolynom = new Polynom<MonomType>();
             for (Nterm& currentTerm : polynomVector->coeff)
             {
                 exponents_t monomVector = newarray_atomic(int, independ);
                 monoid->to_expvector(currentTerm.monom, monomVector);
                 //construct Monom for every term
                 MonomType* currentMonom = new MonomType();
                 if (!currentMonom)
                 {
                     freemem(monomVector);
                     throw std::string("BIBasis::BooleanInvolutiveBasis::FillInitialSet(): got NULL instead of new monom.");
                 }
                 for (typename MonomType::Integer currentVariable = 0; currentVariable < independ; ++currentVariable)
                 {
                     if (monomVector[currentVariable])
                     {
                         *currentMonom *= currentVariable;
                     }
                 }
                 *currentPolynom += *currentMonom;
                 freemem(monomVector);
                 delete currentMonom;
             }
             initialSet.push_back(currentPolynom);
         }
     }
References Nterm::coeff, Matrix::elem(), freemem(), Nterm::monom, Matrix::n_cols(), newarray_atomic, and Monoid::to_expvector().
Referenced by BIBasis::BooleanInvolutiveBasis< MonomType >::BooleanInvolutiveBasis().