Macaulay2 Engine: BIBasis::BooleanInvolutiveBasis::NormalForm
NormalForm()
template<typename MonomType > Polynom< MonomType > * BIBasis::BooleanInvolutiveBasis< MonomType >::NormalForm (const Triple< MonomType > * triple) const private
Definition at line 202 of file involutive.hpp.
     {
         /* As far as currentTriple can't be 0 (checked in QSET and TSET),
          * no need to check for NULL pointer.
          */
         const Triple<MonomType>* involutiveDivisor = 0;
         Polynom<MonomType>* originalForm = 0;
         Polynom<MonomType>* normalForm = new Polynom<MonomType>();
         if (triple->GetVariable() == -1)
         {
             originalForm = new Polynom<MonomType>(*triple->GetPolynom());
         }
         else
         {
             originalForm = new Polynom<MonomType>(*triple->GetWeakAncestor()->GetPolynom());
             (*originalForm) *= triple->GetVariable();
         }
         while (!originalForm->IsZero())
         {
             involutiveDivisor = IntermediateBasis.Find(originalForm->Lm());
             while (involutiveDivisor)
             {
                 originalForm->HeadReduction(*involutiveDivisor->GetPolynom());
                 if (!originalForm->IsZero())
                 {
                     involutiveDivisor = IntermediateBasis.Find(originalForm->Lm());
                 }
                 else
                 {
                     involutiveDivisor = 0;
                 }
             }
             if (!originalForm->IsZero())
             {
                 (*normalForm) += originalForm->Lm();
                 originalForm->RidOfLm();
             }
         }
         delete originalForm;
         return normalForm;
     }
References BIBasis::Triple< MonomType >::GetPolynom(), BIBasis::Triple< MonomType >::GetVariable(), BIBasis::Triple< MonomType >::GetWeakAncestor(), BIBasis::Polynom< MonomType >::HeadReduction(), BIBasis::Polynom< MonomType >::IsZero(), BIBasis::Polynom< MonomType >::Lm(), and BIBasis::Polynom< MonomType >::RidOfLm().