Macaulay2 Engine: BIBasis::BooleanInvolutiveBasis::BooleanInvolutiveBasis
BooleanInvolutiveBasis()
template<typename MonomType > BIBasis::BooleanInvolutiveBasis< MonomType >::BooleanInvolutiveBasis (const Matrix * matrix, bool toGroebner)
Definition at line 58 of file involutive.hpp.
         : GBasis()
         , IntermediateBasis()
         , ProlongationsSet()
         , PRing(matrix->get_ring()->cast_to_PolynomialRing())
     {
         try
         {
             std::list<Polynom<MonomType>*> initialSet;
             FillInitialSet(matrix, initialSet);
             Construct(initialSet, toGroebner);
             initialSet.clear();
         }
         catch(std::string& errorString)
         {
             ERROR(errorString.c_str());
             Reset();
         }
         catch(...)
         {
             ERROR("BIBasis::BooleanInvolutiveBasis::BooleanInvolutiveBasis(): unknown error.");
             Reset();
         }
     }
References BIBasis::BooleanInvolutiveBasis< MonomType >::Construct(), ERROR(), BIBasis::BooleanInvolutiveBasis< MonomType >::FillInitialSet(), and BIBasis::BooleanInvolutiveBasis< MonomType >::Reset().