Macaulay2 Engine: BIBasis::BooleanInvolutiveBasis::Reduce
Reduce()
template<typename MonomType > Polynom< MonomType > * BIBasis::BooleanInvolutiveBasis< MonomType >::Reduce (Polynom< MonomType > * polynom, const std::list< Polynom< MonomType > * > & set, bool toGroebner) const private
Definition at line 279 of file involutive.hpp.
     {
         if (!polynom)
         {
             return 0;
         }
         Polynom<MonomType>* result = new Polynom<MonomType>();
         const Polynom<MonomType>* currentReducer = 0;
         while (!polynom->IsZero())
         {
             currentReducer = FindDivisor(polynom, set, toGroebner);
             while (currentReducer)
             {
                 polynom->Reduction(*currentReducer);
                 currentReducer = FindDivisor(polynom, set, toGroebner);
             }
             if (!polynom->IsZero())
             {
                 (*result) += polynom->Lm();
                 polynom->RidOfLm();
             }
         }
         polynom = result;
         return result;
     }
References BIBasis::Polynom< MonomType >::IsZero(), BIBasis::Polynom< MonomType >::Lm(), BIBasis::Polynom< MonomType >::Reduction(), BIBasis::Polynom< MonomType >::RidOfLm(), and set().