Macaulay2 Engine: ReducedGB_Field_Local::minimalize
minimalize()
void ReducedGB_Field_Local::minimalize (const gc_vector< POLY > & polys0, bool auto_reduced) virtual
Reimplemented from ReducedGB_Field.
Definition at line 70 of file reducedgb-field-local.cpp.
 {
   // First sort these elements via increasing lex order (or monomial order?)
   // Next insert minimal elements into T, and polys
   VECTOR(int) positions;
   positions.reserve(polys0.size());
   for (int i = 0; i < polys0.size(); i++) positions.push_back(i);
   //  displayElements("-- before sort --", R, polys0, [](auto& g) { return g.f;
   //  } );
   std::stable_sort(positions.begin(),
                    positions.end(),
                    ReducedGB_Field_Local_sorter(R, F, polys0));
   //  VECTOR(gbvector*) sorted_elements_debug_only;
   //  for (int i=0; i<positions.size(); i++)
   //    sorted_elements_debug_only.push_back(polys0[positions[i]].f);
   //  displayElements("-- after sort --", R, sorted_elements_debug_only,
   //  [](auto& g) { return g; } );
   // Now loop through each element, and see if the lead monomial is in T.
   // If not, add it in , and place element into 'polys'.
   for (VECTOR(int)::iterator i = positions.begin(); i != positions.end(); i++)
     {
       Bag *not_used;
       gbvector *f = polys0[*i].f;
       exponents_t e = R->exponents_make();
       R->gbvector_get_lead_exponents(F, f, e);
       if ((!Rideal || !Rideal->search_expvector(e, not_used)) &&
           T->find_divisors(1, e, f->comp) == 0)
         {
           // Keep this element
           POLY h;
           ring_elem junk;
           h.f = R->gbvector_copy(f);
           h.fsyz = R->gbvector_copy(polys0[*i].fsyz);
           if (false and auto_reduced)
             remainder(h, false, junk);  // This auto-reduces h.
           R->gbvector_remove_content(h.f, h.fsyz);
           T->insert(e, f->comp, INTSIZE(polys));
           polys.push_back(h);
         }
       else
         R->exponents_delete(e);
     }
   for (int i = 0; i < polys.size(); i++)
     {
       int f_lead_wt;
       gbvector *f = polys[i].f;
       int d = wt->gbvector_weight(f, f_lead_wt);
       int a = d - f_lead_wt;
       divisor_info t;
       t.g = polys[i];
       t.size = R->gbvector_n_terms(f);
       t.alpha = a;
       gb_elems.push_back(t);
     }
 }
References ReducedGB_Field_Local::divisor_info::alpha, gbvector::comp, GBRing::exponents_delete(), GBRing::exponents_make(), POLY::f, ReducedGB::F, MonomialTable::find_divisors(), POLY::fsyz, ReducedGB_Field_Local::divisor_info::g, gb_elems, GBRing::gbvector_copy(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_n_terms(), GBRing::gbvector_remove_content(), GBWeight::gbvector_weight(), MonomialTable::insert(), INTSIZE, ReducedGB::polys, ReducedGB::R, remainder(), ReducedGB_Field::Rideal, MonomialIdeal::search_expvector(), ReducedGB_Field_Local::divisor_info::size, ReducedGB_Field::T, VECTOR(), and wt.