Macaulay2 Engine: ReducedGB_Field_Local::remainder
remainder() [2/2]
void ReducedGB_Field_Local::remainder (POLY & f, bool use_denom, ring_elem & denom) virtual
Reimplemented from ReducedGB_Field.
Definition at line 480 of file reducedgb-field-local.cpp.
 {
   if (M2_gbTrace >= 4) {
       buffer o;
       text_out(o);
       emit(o.str());
     }
   if (f.f == nullptr) return;
   T1 = MonomialTable::make(R->n_vars());
   gbvector head;
   gbvector *frem = &head;
   frem->next = nullptr;
   POLY h = f;
   exponents_t h_exp = R->exponents_make();
   int h_alpha, g_alpha;
   int h_deg = wt->gbvector_weight(f.f);
   while (!R->gbvector_is_zero(h.f))
     {
       if (M2_gbTrace == 3) emit_wrapped(".");
       POLY g;
       R->gbvector_get_lead_exponents(F, h.f, h_exp);
       int h_comp = h.f->comp;
       if (M2_gbTrace >= 4)
         {
           buffer o;
           o << "\nreducing ";
           R->gbvector_text_out(o, F, h.f);
           emit(o.str());
         }
       if (find_good_divisor(h_exp,
                             h_comp,
                             h_deg,
                             h_alpha,
                             g,
                             g_alpha))  // sets these three values
         {
           if (M2_gbTrace >= 4)
             {
               buffer o;
               o << "  h_alpha " << h_alpha << " g_alpha "
                 << g_alpha;  // << " reducing using ";
               // R->gbvector_text_out(o,F,g.f);
               // o << newline;
               emit(o.str());
             }
           if (g_alpha > h_alpha)
             {
               if (head.next != nullptr)
                 {
                   // In this case, we can't reduce the tail without
                   // risking an infinite loop.  So we declare ourselves done
                   // Attach the rest of h.f to frem
                   frem->next = h.f;
                   break;
                 }
               // place h into T1, and store its (value,deg,alpha) values.
               // store_in_table copies h
               store_in_table(h, h_exp, h_comp, h_alpha);
               if (M2_gbTrace == 3) emit_wrapped("x");
               if (M2_gbTrace == 4) emit("\nstored result\n");
               h_deg += g_alpha - h_alpha;
               h_exp = R->exponents_make();
             }
           R->gbvector_reduce_lead_term(
               F, Fsyz, head.next, h.f, h.fsyz, g.f, g.fsyz, use_denom, denom);
         }
       else
         {
           frem->next = h.f;
           frem = frem->next;
           h.f = h.f->next;
           frem->next = nullptr;
         }
     }
   f.f = head.next;
   f.fsyz = h.fsyz;
   R->exponents_delete(h_exp);
   reset_table();
 }
References gbvector::comp, emit(), emit_wrapped(), GBRing::exponents_delete(), GBRing::exponents_make(), POLY::f, ReducedGB::F, find_good_divisor(), POLY::fsyz, ReducedGB::Fsyz, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), GBRing::gbvector_reduce_lead_term(), GBRing::gbvector_text_out(), GBWeight::gbvector_weight(), M2_gbTrace, MonomialTable::make(), GBRing::n_vars(), gbvector::next, ReducedGB::R, reset_table(), store_in_table(), buffer::str(), T1, ReducedGB::text_out(), and wt.
Referenced by minimalize().