Macaulay2 Engine: ReducedGB_Field_Local::store_in_table
store_in_table()
void ReducedGB_Field_Local::store_in_table (const POLY & h, exponents_t h_exp, int h_comp, int h_alpha) protected
Definition at line 465 of file reducedgb-field-local.cpp.
 {
   int id = INTSIZE(new_poly_elems);
   divisor_info t;
   t.g.f = R->gbvector_copy(h.f);
   t.g.fsyz = R->gbvector_copy(h.fsyz);
   t.alpha = h_alpha;
   t.size = R->gbvector_n_terms(t.g.f);
   new_poly_elems.push_back(t);
   T1->insert(h_exp, h_comp, id);  // grabs h_exp
 }
References ReducedGB_Field_Local::divisor_info::alpha, POLY::f, POLY::fsyz, ReducedGB_Field_Local::divisor_info::g, GBRing::gbvector_copy(), GBRing::gbvector_n_terms(), MonomialTable::insert(), INTSIZE, new_poly_elems, ReducedGB::R, ReducedGB_Field_Local::divisor_info::size, and T1.
Referenced by remainder().