Macaulay2 Engine: ReducedGB_Field_Local::ReducedGB_Field_Local
ReducedGB_Field_Local()
ReducedGB_Field_Local::ReducedGB_Field_Local (GBRing * R0, const PolynomialRing * originalR0, const FreeModule * F0, const FreeModule * Fsyz0, const GBWeight * wt0) protected
Definition at line 13 of file reducedgb-field-local.cpp.
     : ReducedGB_Field(R0, originalR0, F0, Fsyz0),
       T1(nullptr),
       wt(wt0)
 {
   // fprintf(stderr, "creating GB with local order\n");
   if (wt == nullptr) wt = new GBWeight(F0, nullptr);
   for (int i = 0; i < originalR0->n_quotients(); i++)
     {
       int f_lead_wt;
       const gbvector *f = originalR0->quotient_gbvector(i);
       int d = wt->gbvector_weight(f, f_lead_wt);
       int a = d - f_lead_wt;
       divisor_info t;
       t.g.f = const_cast<gbvector *>(f);
       t.g.fsyz = nullptr;
       t.size = R->gbvector_n_terms(f);
       t.alpha = a;
       ring_elems.push_back(t);
     }
 }
References ReducedGB_Field_Local::divisor_info::alpha, POLY::f, POLY::fsyz, ReducedGB_Field_Local::divisor_info::g, GBRing::gbvector_n_terms(), GBWeight::gbvector_weight(), PolynomialRing::n_quotients(), PolynomialRing::quotient_gbvector(), ReducedGB::R, ring_elems, ReducedGB_Field_Local::divisor_info::size, and wt.