Macaulay2 Engine: KBasis::try_insert_sg
try_insert_sg()
bool KBasis::try_insert_sg () inline private
Definition at line 250 of file matrix-kbasis.cpp.
 {
   Bag *b;
   if (kb_monideal->search_expvector(kb_exp, b)) return false;
   if (hi_degree && kb_exp_weight > kb_target_hi_weight)
     {
       if (do_truncation) insert();
       return false;
     }
   if (!lo_degree || kb_exp_weight >= kb_target_lo_weight) insert();
   return true;
 }
References do_truncation, hi_degree, insert(), kb_exp, kb_exp_weight, kb_monideal, kb_target_hi_weight, kb_target_lo_weight, lo_degree, and MonomialIdeal::search_expvector().
Referenced by basis0_singly_graded().