Macaulay2 Engine: KBasis::try_insert_full
try_insert_full()
bool KBasis::try_insert_full () inline private
Definition at line 224 of file matrix-kbasis.cpp.
 {
   Bag *b;
   if (kb_monideal->search_expvector(kb_exp, b)) return false;
   insert();
   return true;
 }
References insert(), kb_exp, kb_monideal, and MonomialIdeal::search_expvector().
Referenced by basis0_full().