Macaulay2 Engine: KBasis::basis0_full
basis0_full()
void KBasis::basis0_full () private
Definition at line 232 of file matrix-kbasis.cpp.
 {
   // insert the all zeros vector
   if (!try_insert_full()) return;
   if (mVariables.size() == 0) return;
   int curr = 0;
   do {
       int vcurr = mVariables[curr];
       // increase the curr index until we reach a limit
       do {
           if (limit == 0 || system_interrupted()) return;
           kb_exp[vcurr]++;
           kb_exp_weight += var_wts[curr];
       } while (try_insert_full());
   } while (backtrack(curr));
 }
References backtrack(), kb_exp, kb_exp_weight, limit, mVariables, system_interrupted(), try_insert_full(), and var_wts.
Referenced by compute().