Macaulay2 Engine: KBasis::insert
insert()
void KBasis::insert () private
Definition at line 195 of file matrix-kbasis.cpp.
 {
   // We have a new basis element
   M->from_expvector(kb_exp, kb_mon);
   ring_elem r = P->make_flat_term(P->getCoefficients()->one(), kb_mon);
   vec v = P->make_vec(kb_comp, r);
   mat.append(v);
   if (limit > 0) limit--;
 }
References MatrixConstructor::append(), Monoid::from_expvector(), PolynomialRing::getCoefficients(), kb_comp, kb_exp, kb_mon, limit, M, PolynomialRing::make_flat_term(), Ring::make_vec(), mat, Ring::one(), and P.
Referenced by try_insert_full(), try_insert_mg(), and try_insert_sg().