Macaulay2 Engine: KBasis::basis0_multi_graded
basis0_multi_graded()
void KBasis::basis0_multi_graded () private
Definition at line 329 of file matrix-kbasis.cpp.
 {
   // insert the all zeros vector
   if (!try_insert_mg()) return;
   if (mVariables.size() == 0) return;
   int curr = 0;
   do {
       int vcurr = mVariables[curr];
       // increase the curr index until we reach a limit
       do {
           if (limit == 0 || system_interrupted()) return;
           kb_exp[vcurr]++;
           kb_exp_weight += var_wts[curr];
           exponents::mult(mHeftVector.size(),
                        kb_exp_multidegree,
                        var_degs + (mHeftVector.size() * curr),
                        kb_exp_multidegree);
       } while (try_insert_mg());
   } while (backtrack_mg(curr));
 }
References backtrack_mg(), kb_exp, kb_exp_multidegree, kb_exp_weight, limit, mHeftVector, ExponentVector< E, OC >::mult(), mVariables, system_interrupted(), try_insert_mg(), var_degs, and var_wts.
Referenced by compute().