Macaulay2 Engine: KBasis::backtrack_mg
backtrack_mg()
bool KBasis::backtrack_mg (int & curr) inline private
Definition at line 280 of file matrix-kbasis.cpp.
 {
   int vcurr = -1;
   // if we are the end, decrease the last entry to 0
   if (curr == mVariables.size() - 1)
     {
       vcurr = mVariables[curr];
       kb_exp_weight -= var_wts[curr] * kb_exp[vcurr];
       exponents::multpower(mHeftVector.size(),
                         kb_exp_multidegree,
                         var_degs + (mHeftVector.size() * curr),
                         -kb_exp[vcurr],
                         kb_exp_multidegree);
       kb_exp[vcurr] = 0;
       do {
           curr--;
       } while (curr >= 0 && kb_exp[mVariables[curr]] == 0);
     }
   if (curr < 0) return false;
   vcurr = mVariables[curr];
   kb_exp[vcurr]--;
   kb_exp_weight -= var_wts[curr];
   exponents::divide(mHeftVector.size(),
                  kb_exp_multidegree,
                  var_degs + (mHeftVector.size() * curr),
                  kb_exp_multidegree);
   curr++;
   return true;
 }
References ExponentVector< E, OC >::divide(), kb_exp, kb_exp_multidegree, kb_exp_weight, mHeftVector, ExponentVector< E, OC >::multpower(), mVariables, var_degs, and var_wts.
Referenced by basis0_multi_graded().