Macaulay2 Engine: KBasis::compute
compute()
void KBasis::compute () private
Definition at line 364 of file matrix-kbasis.cpp.
 {
   if (limit == 0) return;
   M2_arrayint zero_vars = NULL;
   if (weight_has_zeros)
     {
       zero_vars = getmematomicarraytype(M2_arrayint, vars->len);
       int j = 0;
       for (int i = 0; i < vars->len; i++)
         {
           if (var_wts[i] == 0)
             {
               zero_vars->array[j] = i;
               j++;
             }
         }
       zero_vars->len = j;
     }
   for (int i = 0; i < bottom_matrix->n_rows(); i++)
     {
       if (system_interrupted()) return;
       kb_comp = i;
       // Make the monomial ideal: this should contain only
       // monomials involving 'vars'.
       kb_monideal = bottom_matrix->make_monideal(i, true);
       // the true means: over ZZ, don't consider monomials with non-unit lead
       // coeffs
       if (kb_monideal->is_one()) continue;
       if (hi_degree == NULL)
         {
           // check here that kb_monideal is 0-dimensional
           // (at least for the variables being used):
           if (!all_have_pure_powers(kb_monideal, vars))
             {
               kb_error = true;
               ERROR("module given is not finite over the base");
               freemem(zero_vars);
               return;
             }
         }
       else if (zero_vars)
         {
           // if we have any variables with zero degrees, then kb_monideal needs
           // to be 0-dimensional in those variables.
           if (!all_have_pure_powers(kb_monideal, zero_vars))
             {
               kb_error = true;
               ERROR(
                   "module given is not finite over the zero-degree variables");
               freemem(zero_vars);
               return;
             }
         }
       const int *component_degree = bottom_matrix->rows()->degree(i);
       D->to_expvector(component_degree, kb_exp_multidegree);
       kb_exp_weight =
           ntuple::weight(heft_vector->len, kb_exp_multidegree, heft_vector);
       // Do the recursion
       switch (computation_type)
         {
           case KB_FULL:
             basis0_full();
             break;
           case KB_SINGLE:
             basis0_singly_graded();
             break;
           case KB_MULTI:
             basis0_multi_graded();
             break;
         }
     }
   freemem(zero_vars);
 }
References all_have_pure_powers(), basis0_full(), basis0_multi_graded(), basis0_singly_graded(), bottom_matrix, computation_type, D, FreeModule::degree(), ERROR(), freemem(), getmematomicarraytype, heft_vector, hi_degree, MonomialIdeal::is_one(), kb_comp, kb_error, kb_exp_multidegree, kb_exp_weight, KB_FULL, kb_monideal, KB_MULTI, KB_SINGLE, limit, Matrix::make_monideal(), Matrix::n_rows(), Matrix::rows(), system_interrupted(), Monoid::to_expvector(), var_wts, vars, ntuple::weight(), and weight_has_zeros.
Referenced by k_basis().