Macaulay2 Engine: KBasis::try_insert_mg
try_insert_mg()
bool KBasis::try_insert_mg () inline private
Definition at line 310 of file matrix-kbasis.cpp.
 {
   Bag *b;
   if (kb_monideal->search_expvector(kb_exp, b)) return false;
   if (kb_exp_weight > kb_target_lo_weight)
     {
       if (do_truncation) insert();
       return false;
     }
   if (kb_exp_weight == kb_target_lo_weight)
     {
       if (EQ == exponents::lex_compare(mHeftVector.size(),
                                     kb_target_multidegree,
                                     kb_exp_multidegree))
         insert();
     }
   return true;
 }
References do_truncation, EQ, insert(), kb_exp, kb_exp_multidegree, kb_exp_weight, kb_monideal, kb_target_lo_weight, kb_target_multidegree, ExponentVector< E, OC >::lex_compare(), mHeftVector, and MonomialIdeal::search_expvector().
Referenced by basis0_multi_graded().