Macaulay2 Engine: KBasis::KBasis
KBasis()
KBasis::KBasis (const Matrix * bottom, const int * lo_degree, const int * hi_degree, std::vector< int > heftvec, std::vector< int > varlist, bool do_truncation, int limit) private
Definition at line 121 of file matrix-kbasis.cpp.
     : bottom_matrix(bottom),
       mHeftVector(heftvec),
       mVariables(varlist),
       do_truncation(do_truncation0),
       weight_has_zeros(false),
       limit(limit0),
       lo_degree(lo_degree0),
       hi_degree(hi_degree0),
       kb_error(false)
 {
   P = bottom->get_ring()->cast_to_PolynomialRing();
   M = P->getMonoid();
   D = P->get_degree_ring()->getMonoid();
   if (lo_degree == nullptr && hi_degree == nullptr) { computation_type = KB_FULL; }
   else if (mHeftVector.size() == 1) { computation_type = KB_SINGLE; }
   else { computation_type = KB_MULTI; }
   // Compute the (non-negative) weights of each of the variables in
   // 'mVariables'.
   var_wts = newarray_atomic(int, mVariables.size());
   var_degs = newarray_atomic(int, mVariables.size() * mHeftVector.size());
   int *exp =
       newarray_atomic(int, D->n_vars());  // used to hold exponent vectors
   int next = 0;
   for (int i = 0; i < mVariables.size(); i++, next += mHeftVector.size())
     {
       int v = mVariables[i];
       D->to_expvector(M->degree_of_var(v), exp);
       var_wts[i] = exponents::weight(mHeftVector.size(), exp, mHeftVector);
       if (var_wts[i] == 0) weight_has_zeros = true;
       exponents::copy(mHeftVector.size(), exp, var_degs + next);
     }
   freemem(exp);
   // Set the recursion variables
   kb_exp = newarray_atomic_clear(int, P->n_vars());
   kb_exp_weight = 0;
   if (lo_degree != nullptr)
     kb_target_lo_weight =
         exponents::weight(mHeftVector.size(), lo_degree, mHeftVector);
   if (hi_degree != nullptr)
     kb_target_hi_weight =
         exponents::weight(mHeftVector.size(), hi_degree, mHeftVector);
   if (lo_degree && hi_degree && mHeftVector.size() == 1 && mHeftVector[0] < 0)
     {
       int t = kb_target_lo_weight;
       kb_target_lo_weight = kb_target_hi_weight;
       kb_target_hi_weight = t;
     }
   kb_mon = M->make_one();
   mat = MatrixConstructor(bottom->rows(), 0);
   kb_exp_multidegree = D->make_one();
   if (mHeftVector.size() > 1 && lo_degree != nullptr)
     {
       kb_target_multidegree = D->make_one();
       exponents::copy(mHeftVector.size(), lo_degree, kb_target_multidegree);
     }
   else { kb_target_multidegree = nullptr; }
 }
References Ring::cast_to_PolynomialRing(), computation_type, ExponentVector< E, OC >::copy(), D, Monoid::degree_of_var(), mpfr::exp(), freemem(), Ring::get_degree_ring(), Matrix::get_ring(), PolynomialRing::getMonoid(), hi_degree, kb_exp, kb_exp_multidegree, kb_exp_weight, KB_FULL, kb_mon, KB_MULTI, KB_SINGLE, kb_target_hi_weight, kb_target_lo_weight, kb_target_multidegree, lo_degree, M, Monoid::make_one(), mat, mHeftVector, mVariables, Monoid::n_vars(), PolynomialRing::n_vars(), newarray_atomic, newarray_atomic_clear, P, Matrix::rows(), Monoid::to_expvector(), var_degs, var_wts, ExponentVector< E, OC >::weight(), and weight_has_zeros.