Macaulay2 Engine: suffix
suffix()
Word suffix (const Word vec, int indexOfSuffix)
Definition at line 86 of file SuffixTree.cpp.
 {
   // this command sets the pointers to the terminal segment of vec
   return Word(vec.begin()+indexOfSuffix,vec.end());
 }
References Word::begin(), and Word::end().
Referenced by SuffixTree::contractedLocus(), NCGroebner::createOverlapPoly(), SuffixTree::extendedLocus(), NCF4::findDivisor(), NCF4::findPreviousReducerSuffix(), SuffixTree::insertStepC(), SuffixTree::insertStepD(), SuffixTree::leftOverlaps(), WordTable::overlaps(), WordWithDataTable::overlaps(), SuffixTree::subwords(), and SuffixTree::subwordsStepC().