Macaulay2 Engine: isPatternPrefix
isPatternPrefix() [2/2]
bool isPatternPrefix (const Word a, const Word b, int startIndex)
Definition at line 100 of file SuffixTree.cpp.
 {
   // here, a is a pattern label so we only compare the first a.size()-1 many entries
   // sometimes we know that the first startIndex many symbols will match, so we start
   // at the first possible non-match.
   std::cout << a << " " << b << " " << startIndex << std::endl;
   if (b.size() + 1 < a.size()) return false;
   Word tmpA = Word(a.begin()+startIndex,a.end()-1);
   Word tmpB = Word(b.begin()+startIndex, b.begin()+a.size()-1);
   return (tmpA == tmpB);
 }
References Word::begin(), Word::end(), and Word::size().
Referenced by isPatternPrefix(), and SuffixTree::subwords().