Macaulay2 Engine: Lapack::least_squares
least_squares() [4/4]
bool Lapack::least_squares (const LMatrixRRR * A, const LMatrixRRR * b, LMatrixRRR * x) static
Definition at line 792 of file lapack.cpp.
 {
   bool ret = true;
   char job = 'N';
   int info;
   int rows = static_cast<int>(A->numRows());
   int cols = static_cast<int>(A->numColumns());
   int brows = static_cast<int>(b->numRows());
   int bcols = static_cast<int>(b->numColumns());
   int min = (rows <= cols) ? rows : cols;
   int max = (rows >= cols) ? rows : cols;
   int wsize = min + ((bcols >= max) ? bcols : max);
   if (brows != rows)
     {
       ERROR("expected compatible right hand side");
       return false;
     }
   if (min == 0 || bcols == 0)
     {
       x->resize(cols, bcols);
       return true;
     }
   double *copyA = make_lapack_array(*A);
   double *copyb = make_lapack_array(*b);
   double *workspace = newarray_atomic(double, wsize);
   if (rows < cols)
     {
       // Make 'b' (copyb) into a cols x bcols matrix, by adding a zero block at
       // the bottom
       double *copyb2 = newarray_atomic_clear(double, cols *bcols);
       int bloc = 0;
       int copyloc = 0;
       for (int j = 0; j < bcols; j++)
         {
           copyloc = j * cols;
           for (int i = 0; i < brows; i++)
             {
               copyb2[copyloc++] = copyb[bloc++];
             }
         }
       freemem(copyb);
       copyb = copyb2;
     }
   dgels_(&job,
          &rows,
          &cols,
          &bcols,
          copyA,
          &rows,
          copyb,
          &max,
          workspace,
          &wsize,
          &info);
   if (info != 0)
     {
       ERROR("argument passed to dgels had an illegal value");
       ret = false;
     }
   else
     {
       x->resize(cols, bcols);
       if (rows > cols)
         {
           // We only need the first 'cols' rows of copyb
           int copyloc = 0;
           for (int j = 0; j < bcols; j++)
             {
               auto xj = x->columnBegin(j);
               copyloc = j * rows;
               for (int i = 0; i < cols; i++, ++xj)
                 {
                   x->ring().set_from_double(*xj, copyb[copyloc++]);
                 }
             }
         }
       else
         {
           fill_from_lapack_array(copyb, *x);
         }
     }
   freemem(copyA);
   freemem(copyb);
   freemem(workspace);
   return ret;
 }
References dgels_(), ERROR(), fill_from_lapack_array(), freemem(), make_lapack_array(), max, mpfr::min(), newarray_atomic, newarray_atomic_clear, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and x.
Referenced by MatrixOps::leastSquares().