Macaulay2 Engine: Lapack::least_squares_deficient
least_squares_deficient() [4/4]
bool Lapack::least_squares_deficient (const LMatrixRRR * A, const LMatrixRRR * b, LMatrixRRR * x) static
Definition at line 889 of file lapack.cpp.
 {
   bool ret = true;
   int rows = static_cast<int>(A->numRows());
   int cols = static_cast<int>(A->numColumns());
   int brows = static_cast<int>(b->numRows());
   int bcols = static_cast<int>(b->numColumns());
   double rcond = -1.0;  // use machine precision
   int rank, info;
   int min = (rows < cols) ? rows : cols;
   int max = (rows > cols) ? rows : cols;
   int tempmax = ((2 * min > max) ? 2 * min : max);
   int wsize = 3 * min + ((tempmax > bcols) ? tempmax : bcols);
   if (brows != rows)
     {
       ERROR("expected compatible right hand side");
       return false;
     }
   if (min == 0 || bcols == 0)
     {
       x->resize(cols, bcols);
       return true;
     }
   double *copyA = make_lapack_array(*A);
   double *copyb = make_lapack_array(*b);
   double *workspace = newarray_atomic(double, wsize);
   double *sing = newarray_atomic(double, min);
   if (rows < cols)
     {
       // Make 'b' (copyb) into a cols x bcols matrix, by adding a zero block at
       // the bottom
       double *copyb2 = newarray_atomic_clear(double, cols *bcols);
       int bloc = 0;
       int copyloc = 0;
       for (int j = 0; j < bcols; j++)
         {
           copyloc = j * cols;
           for (int i = 0; i < brows; i++)
             {
               copyb2[copyloc++] = copyb[bloc++];
             }
         }
       freemem(copyb);
       copyb = copyb2;
     }
   dgelss_(&rows,
           &cols,
           &bcols,
           copyA,
           &rows,
           copyb,
           &max,
           sing,
           &rcond,
           &rank,
           workspace,
           &wsize,
           &info);
   if (info != 0)
     {
       ERROR("argument passed to dgelss had an illegal value");
       ret = false;
     }
   else
     {
       x->resize(cols, bcols);
       if (rows > cols)
         {
           int copyloc = 0;
           for (int j = 0; j < bcols; j++)
             {
               auto xj = x->columnBegin(j);
               copyloc = j * rows;
               for (int i = 0; i < cols; i++, ++xj)
                 {
                   x->ring().set_from_double(*xj, copyb[copyloc++]);
                 }
             }
         }
       else
         {
           fill_from_lapack_array(copyb, *x);
         }
     }
   freemem(copyA);
   freemem(copyb);
   freemem(workspace);
   freemem(sing);
   return ret;
 }
References dgelss_(), ERROR(), fill_from_lapack_array(), freemem(), make_lapack_array(), max, mpfr::min(), newarray_atomic, newarray_atomic_clear, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), ffpackInterface::rank(), and x.
Referenced by MatrixOps::leastSquares().