Macaulay2 Engine: Lapack::eigenvalues
eigenvalues() [4/4]
bool Lapack::eigenvalues (const LMatrixRRR * A, LMatrixCCC * eigenvals) static
Definition at line 374 of file lapack.cpp.
 {
   int size = static_cast<int>(A->numRows());
   if (size != static_cast<int>(A->numColumns()))
     {
       ERROR("expected a square matrix");
       return false;
     }
   if (size == 0)
     {
       eigvals->resize(0, 1);
       return true;
     }
   bool ret = true;
   char dont = 'N';
   int wsize = 3 * size;
   double *workspace = newarray_atomic(double, wsize);
   int info;
   double *copyA = make_lapack_array(*A);
   double *real = newarray_atomic(double, size);  // real components of eigvals
   double *imag = newarray_atomic(double, size);  // imaginary components
   dgeev_(&dont,
          &dont,
          &size,
          copyA,
          &size,
          real,
          imag,
          static_cast<double *>(0),
          &size, /* left eigenvectors */
          static_cast<double *>(0),
          &size, /* right eigenvectors */
          workspace,
          &wsize,
          &info);
   if (info < 0)
     {
       ERROR("argument passed to dgeev had an illegal value");
       ret = false;
     }
   else if (info > 0)
     {
       ERROR("the QR algorithm in dgeev failed to compute all eigvals");
       ret = false;
     }
   else
     {
       eigvals->resize(size, 1);
       LMatrixCCC::ElementType *elems = eigvals->rowMajorArray();
       for (int i = 0; i < size; i++)
         eigvals->ring().set_from_doubles(elems[i], real[i], imag[i]);
     }
   freemem(copyA);
   freemem(real);
   freemem(imag);
   return ret;
 }
References dgeev_(), ERROR(), freemem(), make_lapack_array(), newarray_atomic, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::resize(), DMat< ACoeffRing >::ring(), and DMat< ACoeffRing >::rowMajorArray().
Referenced by MatrixOps::eigenvalues().