Macaulay2 Engine: Lapack::eigenvectors_symmetric
eigenvectors_symmetric() [2/2]
bool Lapack::eigenvectors_symmetric (const LMatrixRRR * A, LMatrixRRR * eigenvals, LMatrixRRR * eigenvecs) static
Definition at line 590 of file lapack.cpp.
 {
   int size = static_cast<int>(A->numRows());
   if (size != static_cast<int>(A->numColumns()))
     {
       ERROR("expected a square matrix");
       return false;
     }
   if (size == 0)
     {
       eigvals->resize(0, 1);
       eigvecs->resize(0, 0);
       return true;
     }
   bool ret = true;
   char doit = 'V';
   char triangle = 'U'; /* Upper triangular part makes symmetric matrix */
   int wsize = 3 * size - 1;
   double *workspace = newarray_atomic(double, wsize);
   int info;
   double *evecs = make_lapack_array(*A);
   double *evals = newarray_atomic(double, size);
   dsyev_(
       &doit, &triangle, &size, evecs, &size, evals, workspace, &wsize, &info);
   if (info < 0)
     {
       ERROR("argument passed to dsyev had an illegal value");
       ret = false;
     }
   else if (info > 0)
     {
       ERROR("dsyev did not converge");
       ret = false;
     }
   else
     {
       // Copy results to eigvals, eigvecs
       eigvecs->resize(size, size);
       fill_from_lapack_array(evecs, *eigvecs);
       eigvals->resize(size, 1);
       fill_from_lapack_array(evals, *eigvals);
     }
   freemem(workspace);
   freemem(evecs);
   freemem(evals);
   return ret;
 }
References dsyev_(), ERROR(), fill_from_lapack_array(), freemem(), make_lapack_array(), newarray_atomic, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::resize().
Referenced by MatrixOps::eigenvectorsHermitian().