Macaulay2 Engine: Lapack::solve
solve() [4/4]
bool Lapack::solve (const LMatrixRRR * A, const LMatrixRRR * b, LMatrixRRR * x) static
Definition at line 314 of file lapack.cpp.
 {
   int size = static_cast<int>(A->numRows());
   int bsize = static_cast<int>(b->numColumns());
   int info;
   /* make sure matrix is square */
   if (A->numRows() != A->numColumns())
     {
       ERROR("expected a square matrix");
       return false;
     }
   /* make sure dimensions of b make sense for Ax=b */
   if (b->numRows() != size)
     {
       ERROR("expected matrices to have same number of rows");
       return false;
       ;
     }
   if (size == 0)
     {
       x->resize(size, bsize);
       return true;
     }
   int *permutation = newarray_atomic(int, size);
   LapackDoubles copyA = make_lapack_array(*A);
   LapackDoubles copyb = make_lapack_array(*b);
   dgesv_(&size,
          &bsize,
          copyA,
          &size,
          permutation,
          copyb,  // also the result
          &size,
          &info);
   // Now set x
   x->resize(size, bsize);
   fill_from_lapack_array(copyb, *x);
   if (info > 0)
     {
       ERROR("according to dgesv, matrix is singular");
       return false;
     }
   else if (info < 0)
     {
       ERROR("argument passed to dgesv had an illegal value");
       return false;
     }
   return true;
 }
References dgesv_(), ERROR(), fill_from_lapack_array(), make_lapack_array(), newarray_atomic, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and x.