Macaulay2 Engine: Lapack::SVD_divide_conquer
SVD_divide_conquer() [4/4]
bool Lapack::SVD_divide_conquer (const LMatrixRRR * A, LMatrixRRR * Sigma, LMatrixRRR * U, LMatrixRRR * VT) static
Definition at line 719 of file lapack.cpp.
 {
   bool ret = true;
   char doit = 'A';  // other options are 'S' and 'O' for singular vectors only
   int rows = static_cast<int>(A->numRows());
   int cols = static_cast<int>(A->numColumns());
   int info;
   int min = (rows <= cols) ? rows : cols;
   if (min == 0)
     {
       ERROR("expected a matrix with positive dimensions");
       return false;
     }
   int max = (rows >= cols) ? rows : cols;
   int wsize = 4 * min * min + max + 9 * min;
   double *workspace = newarray_atomic(double, wsize);
   int *iworkspace = newarray_atomic(int, 8 * min);
   double *copyA = make_lapack_array(*A);
   double *u = newarray_atomic(double, rows *rows);
   double *vt = newarray_atomic(double, cols *cols);
   double *sigma = newarray_atomic(double, min);
   dgesdd_(&doit,
           &rows,
           &cols,
           copyA,
           &rows,
           sigma,
           u,
           &rows,
           vt,
           &cols,
           workspace,
           &wsize,
           iworkspace,
           &info);
   if (info < 0)
     {
       ERROR("argument passed to dgesdd had an illegal value");
       ret = false;
     }
   else if (info > 0)
     {
       ERROR("dgesdd did not converge");
       ret = false;
     }
   else
     {
       U->resize(rows, rows);
       VT->resize(cols, cols);
       Sigma->resize(min, 1);
       fill_from_lapack_array(u, *U);
       fill_from_lapack_array(vt, *VT);
       fill_from_lapack_array(sigma, *Sigma);
     }
   freemem(workspace);
   freemem(iworkspace);
   freemem(copyA);
   freemem(u);
   freemem(vt);
   freemem(sigma);
   return ret;
 }
References dgesdd_(), ERROR(), fill_from_lapack_array(), freemem(), make_lapack_array(), max, mpfr::min(), newarray_atomic, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::resize().
Referenced by MatrixOps::SVD().