Macaulay2 Engine: Lapack::eigenvectors_hermitian
eigenvectors_hermitian() [2/2]
bool Lapack::eigenvectors_hermitian (const LMatrixCCC * A, LMatrixRRR * eigenvals, LMatrixCCC * eigenvecs) static
Definition at line 1327 of file lapack.cpp.
 {
   int size = static_cast<int>(A->numRows());
   if (size != static_cast<int>(A->numColumns()))
     {
       ERROR("expected a square matrix");
       return false;
     }
   if (size == 0)
     {
       eigvals->resize(0, 1);
       eigvecs->resize(0, 0);
       return true;
     }
   bool ret = true;
   char doit = 'V';
   char triangle = 'U'; /* Upper triangular part makes symmetric matrix */
   int wsize = 4 * size - 2;
   double *workspace = newarray_atomic(double, wsize);
   double *rwork = newarray_atomic(double, 3 * size - 2);
   int info;
   double *evecs = make_lapack_array(*A);
   double *evals = newarray_atomic(double, size);
   zheev_(&doit,
          &triangle,
          &size,
          evecs,
          &size,
          evals,
          workspace,
          &wsize,
          rwork,
          &info);
   if (info < 0)
     {
       ERROR("argument passed to zheev had an illegal value");
       ret = false;
     }
   else if (info > 0)
     {
       ERROR("zheev did not converge");
       ret = false;
     }
   else
     {
       eigvals->resize(size, 1);
       fill_from_lapack_array(evals, *eigvals);
       eigvecs->resize(size, size);
       fill_from_lapack_array(evecs, *eigvecs);
     }
   freemem(evals);
   freemem(evecs);
   freemem(workspace);
   freemem(rwork);
   return ret;
 }
References ERROR(), fill_from_lapack_array(), freemem(), make_lapack_array(), newarray_atomic, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::resize(), and zheev_().