Macaulay2 Engine: Lapack::LU
LU() [4/4]
M2_arrayintOrNull Lapack::LU (const LMatrixRRR * A, LMatrixRRR * L, LMatrixRRR * U) static
Definition at line 267 of file lapack.cpp.
 {
   int rows = static_cast<int>(A->numRows());
   int cols = static_cast<int>(A->numColumns());
   int info;
   int min = (rows <= cols) ? rows : cols;
   M2_arrayint result = M2_makearrayint(rows);
   L->resize(rows, min);
   U->resize(min, cols);
   if (min == 0)
     {
       if (rows > 0)
         for (int i = 0; i < rows; i++) result->array[i] = i;
       return result;
     }
   int *perm = newarray_atomic(int, min);
   LapackDoubles copyA = make_lapack_array(*A);
   dgetrf_(&rows, &cols, copyA, &rows, perm, &info);
   fill_lower_and_upper(copyA, *L, *U);
   for (int i = 0; i < rows; i++) result->array[i] = i;
   for (int i = 0; i < min; i++)
     {
       int thisloc = perm[i] - 1;
       int tmp = result->array[thisloc];
       result->array[thisloc] = result->array[i];
       result->array[i] = tmp;
     }
   freemem(copyA);
   freemem(perm);
   if (info < 0)
     {
       ERROR("argument passed to dgetrf had an illegal value");
       return 0;
     }
   return result;
 }
References dgetrf_(), ERROR(), fill_lower_and_upper(), freemem(), M2_makearrayint(), make_lapack_array(), mpfr::min(), newarray_atomic, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::resize().