Macaulay2 Engine: Lapack::eigenvectors
eigenvectors() [4/4]
bool Lapack::eigenvectors (const LMatrixRRR * A, LMatrixCCC * eigenvals, LMatrixCCC * eigenvecs) static
Definition at line 438 of file lapack.cpp.
 {
   int size = static_cast<int>(A->numRows());
   if (size != static_cast<int>(A->numColumns()))
     {
       ERROR("expected a square matrix");
       return false;
     }
   if (size == 0)
     {
       eigvals->resize(0, 1);
       eigvecs->resize(0, 0);
       return true;
     }
   bool ret = true;
   char dont = 'N';
   char doit = 'V';
   int wsize = 4 * size;
   double *workspace = newarray_atomic(double, wsize);
   int info;
   double *copyA = make_lapack_array(*A);
   double *real = newarray_atomic(double, size);  // real components of eigvals
   double *imag = newarray_atomic(double, size);  // imaginary components
   double *eigen = newarray_atomic(double, size *size);  // eigvecs
   dgeev_(&dont, /* left e-vectors */
          &doit, /* right e-vectors */
          &size,
          copyA,
          &size,
          real,
          imag,
          static_cast<double *>(nullptr),
          &size, /* left eigvecs */
          eigen,
          &size, /* right eigvecs */
          workspace,
          &wsize,
          &info);
   if (info < 0)
     {
       ERROR("argument passed to dgeev had an illegal value");
       ret = false;
     }
   else if (info > 0)
     {
       ERROR("the QR algorithm in dgeev failed to compute all eigvals");
       ret = false;
     }
   else
     {
       // Make the complex arrays of eigvals and eigvecs
       eigvals->resize(size, 1);
       eigvecs->resize(size, size);
       //      LMatrixCCC::ElementType* elems = eigvecs->array();
       LMatrixCCC::ElementType *elems = eigvals->rowMajorArray();
       for (int j = 0; j < size; j++)
         {
           eigvals->ring().set_from_doubles(elems[j], real[j], imag[j]);
           auto end = eigvecs->columnEnd(j);
           // mpfr_get_d(&(*a), MPFR_RNDN);
           int loc = j * size;
           if (imag[j] == 0)
             {
               auto a = eigvecs->columnBegin(j);
               for (int i = 0; a != end; ++a, ++i)
                 eigvecs->ring().set_from_doubles((*a), eigen[loc + i], 0);
             }
           else if (imag[j] > 0)
             {
               auto a = eigvecs->columnBegin(j);
               auto b = eigvecs->columnBegin(j + 1);
               for (int i = 0; a != end; ++a, ++b, ++i)
                 {
                   eigvecs->ring().set_from_doubles(
                       *a, eigen[loc + i], eigen[loc + size + i]);
                   eigvecs->ring().set_from_doubles(
                       *b, eigen[loc + i], -eigen[loc + size + i]);
                 }
             }
         }
     }
   freemem(copyA);
   freemem(workspace);
   freemem(real);
   freemem(imag);
   freemem(eigen);
   return ret;
 }
References DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::columnEnd(), dgeev_(), end(), ERROR(), freemem(), make_lapack_array(), newarray_atomic, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::resize(), DMat< ACoeffRing >::ring(), and DMat< ACoeffRing >::rowMajorArray().
Referenced by MatrixOps::eigenvectors().