Macaulay2 Engine: Lapack::eigenvalues_symmetric
eigenvalues_symmetric() [2/2]
bool Lapack::eigenvalues_symmetric (const LMatrixRRR * A, LMatrixRRR * eigenvals) static
Definition at line 537 of file lapack.cpp.
 {
   int size = static_cast<int>(A->numRows());
   if (size != static_cast<int>(A->numColumns()))
     {
       ERROR("expected a square matrix");
       return false;
     }
   if (size == 0)
     {
       eigvals->resize(0, 1);
       return true;
     }
   bool ret = true;
   char dont = 'N';
   char triangle = 'U'; /* Upper triangular part makes symmetric matrix. */
   int info;
   int wsize = 3 * size - 1;
   double *workspace = newarray_atomic(double, wsize);
   double *copyA = make_lapack_array(*A);
   double *evals = newarray_atomic(double, size);
   dsyev_(
       &dont, &triangle, &size, copyA, &size, evals, workspace, &wsize, &info);
   if (info < 0)
     {
       ERROR("argument passed to dsyev had an illegal value");
       ret = false;
     }
   else if (info > 0)
     {
       ERROR("dsyev did not converge");
       ret = false;
     }
   else
     {
       // Copy eigenvalues back to eigvals
       eigvals->resize(size, 1);
       fill_from_lapack_array(evals, *eigvals);
     }
   freemem(workspace);
   freemem(copyA);
   freemem(evals);
   return ret;
 }
References dsyev_(), ERROR(), fill_from_lapack_array(), freemem(), make_lapack_array(), newarray_atomic, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::resize().
Referenced by MatrixOps::eigenvaluesHermitian().