Macaulay2 Engine: ResGausserZZp::debugDisplayRow
debugDisplayRow()
std::ostream & ResGausserZZp::debugDisplayRow (std::ostream & o, int ncolumns, const std::vector< int > & comps, CoefficientVector coeffs) const virtual
Implements ResGausser.
Definition at line 234 of file res-gausser-ZZp.cpp.
 {
   auto& elems = coefficientVector(coeffs);
   auto monom = comps.begin();
   auto coeff = elems.begin();
   auto end = elems.end();
   for (ComponentIndex c = 0; c < ncolumns; c++)
     {
       if (coeff == end or *monom != c)
         o << " .";
       else
         {
           out(o, *coeff);
           o << " ";
           ++coeff;
           ++monom;
         }
     }
   o << std::endl;
   return o;
 }
References coefficientVector(), end(), and out().