Macaulay2 Engine: ResGausserZZp::from_ring_elem
from_ring_elem()
void ResGausserZZp::from_ring_elem (CoefficientVector & result, ring_elem a, ring_elem unused) const virtual
Implements ResGausser.
Definition at line 59 of file res-f4-m2-interface.cpp.
 {
   auto& elems = coefficientVector(result);
   int a1;
   Kp->set_from_long(
       a1, static_cast<int>(get_ring()->coerceToLongInteger(a).second));
   elems.push_back(a1);
 }
References coefficientVector(), ResGausser::get_ring(), Kp, and CoefficientRingZZp::set_from_long().