Macaulay2 Engine: ResGausserZZp::ResGausserZZp
ResGausserZZp()
ResGausserZZp::ResGausserZZp (const Ring * K)
Definition at line 9 of file res-gausser-ZZp.cpp.
                                            : ResGausser(K1)
 {
   int p = static_cast<int>(get_ring()->characteristic());
   auto K2 = Z_mod::create(p);
   Kp = K2->get_CoeffRing();
 }
References Ring::characteristic(), Z_mod::create(), ResGausser::get_ring(), Kp, and p.