Macaulay2 Engine: PfaffianComputation::PfaffianComputation
PfaffianComputation()
PfaffianComputation::PfaffianComputation (const Matrix * M, int p)
Definition at line 7 of file pfaff.cpp.
     : R(M0->get_ring()), M(M0), p(p0), done(false), row_set(0)
 {
   pfaffs = MatrixConstructor(R->make_FreeModule(1), 0);
   if (p == 0)
     {
       pfaffs.append(R->make_vec(0, R->one()));
       done = true;
       return;
     }
   if (p % 2 != 0 || p < 0 || (p > M->n_cols()) || (p > M->n_rows()))
     {
       done = true;
       return;
     }
   row_set = newarray_atomic(size_t, p);
   for (int i = 0; i < p; i++) row_set[i] = i;
 }
References MatrixConstructor::append(), done, M, Ring::make_FreeModule(), Ring::make_vec(), Matrix::n_cols(), Matrix::n_rows(), newarray_atomic, Ring::one(), p, pfaffs, R, and row_set.