Macaulay2 Engine: PfaffianComputation::calc_pfaff
calc_pfaff()
ring_elem PfaffianComputation::calc_pfaff (size_t * r, int p) private
Definition at line 57 of file pfaff.cpp.
 {
   if (p2 == 2) return M->elem(static_cast<int>(r[0]), static_cast<int>(r[1]));
   ring_elem result = R->from_long(0);
   bool negate = true;
   for (int i = p2 - 2; i >= 0; i--)
     {
       std::swap(r[i], r[p2 - 2]);
       negate = !negate;
       ring_elem g =
           M->elem(static_cast<int>(r[p2 - 2]), static_cast<int>(r[p2 - 1]));
       if (R->is_zero(g))
         {
           R->remove(g);
           continue;
         }
       ring_elem h = calc_pfaff(r, p2 - 2);
       ring_elem gh = R->mult(g, h);
       R->remove(g);
       R->remove(h);
       if (negate)
         R->subtract_to(result, gh);
       else
         R->add_to(result, gh);
     }
   // pulling out the columns has disordered r. Fix it.
   size_t temp = r[p2 - 2];
   for (size_t i = p2 - 2; i > 0; i--) r[i] = r[i - 1];
   r[0] = temp;
   return result;
 }
References Ring::add_to(), Matrix::elem(), Ring::from_long(), Ring::is_zero(), M, Ring::mult(), mpfr::negate(), R, Ring::remove(), Ring::subtract_to(), and swap.
Referenced by step().