Macaulay2 Engine: PfaffianComputation::step
step()
int PfaffianComputation::step () private
Definition at line 27 of file pfaff.cpp.
 {
   if (done) return COMP_DONE;
   ring_elem r = calc_pfaff(row_set, p);
   if (!R->is_zero(r))
     pfaffs.append(R->make_vec(0, r));
   else
     R->remove(r);
   if (Subsets::increment(M->n_cols(), p, row_set)) return COMP_COMPUTING;
   // Otherwise, we are at the end.
   done = true;
   return COMP_DONE;
 }
References MatrixConstructor::append(), calc_pfaff(), COMP_COMPUTING, COMP_DONE, done, Subsets::increment(), Ring::is_zero(), M, Ring::make_vec(), Matrix::n_cols(), p, pfaffs, R, Ring::remove(), and row_set.
Referenced by calc().