Macaulay2 Engine: polyheap::add
add()
void polyheap::add (Nterm * p) inline
Definition at line 53 of file geopoly.hpp.
 {
   int len = F->n_terms(p);
   int i = 0;
   while (len >= heap_size[i]) i++;
   ring_elem tmp1 = heap[i];
   ring_elem tmp2 = p;
   F->add_to(tmp1, tmp2);
   heap[i] = tmp1;
   len = F->n_terms(heap[i]);
   p = NULL;
   while (len >= heap_size[i])
     {
       i++;
       tmp1 = heap[i];
       tmp2 = heap[i - 1];
       F->add_to(tmp1, tmp2);
       heap[i] = tmp1;
       len = F->n_terms(heap[i]);
       heap[i - 1] = NULL;
     }
   if (i > top_of_heap) top_of_heap = i;
 }
References Ring::add_to(), F, heap, heap_size, PolynomialRing::n_terms(), p, and top_of_heap.
Referenced by SumCollectorPolyHeap::add(), PolyRing::diff(), PolyRing::mult(), and WeylAlgebra::mult_by_term().