Macaulay2 Engine: polyheap::remove_lead_term
remove_lead_term()
Nterm * polyheap::remove_lead_term () inline
Definition at line 81 of file geopoly.hpp.
 {
   int lead_so_far = -1;
   for (int i = 0; i <= top_of_heap; i++)
     {
       if (heap[i] == NULL) continue;
       if (lead_so_far < 0)
         {
           lead_so_far = i;
           continue;
         }
       int cmp = EQ;  // F->compare(heap[lead_so_far], heap[i]);
       if (cmp == GT) continue;
       if (cmp == LT)
         {
           lead_so_far = i;
           continue;
         }
       // At this point we have equality
       K->add_to(heap[lead_so_far]->coeff, heap[i]->coeff);
       Nterm *tmp = heap[i];
       heap[i] = tmp->next;
       tmp->next = NULL;
       F->remove(reinterpret_cast<ring_elem &>(tmp));
       if (K->is_zero(heap[lead_so_far]->coeff))
         {
           // Remove, and start over
           tmp = heap[lead_so_far];
           heap[lead_so_far] = tmp->next;
           tmp->next = NULL;
           F->remove(reinterpret_cast<ring_elem &>(tmp));
           lead_so_far = -1;
           i = -1;
         }
     }
   if (lead_so_far < 0) return NULL;
   Nterm *result = heap[lead_so_far];
   heap[lead_so_far] = result->next;
   result->next = NULL;
   return result;
 }
References Ring::add_to(), Nterm::coeff, EQ, F, GT, heap, Ring::is_zero(), K, LT, Nterm::next, Ring::remove(), and top_of_heap.