Macaulay2 Engine: F4GB::insert_gb_element
insert_gb_element()
void F4GB::insert_gb_element (row_elem & r) private
Definition at line 642 of file f4.cpp.
 {
   // Insert row as gb element.
   // Actions to do:
   //  translate row to a gbelem + poly
   //    set degrees as needed
   //  insert the monomial into the lookup table
   //  find new pairs associated to this new element
   int nslots = M->max_monomial_size();
   int nlongs = r.len * nslots;
   gbelem *result = new gbelem;
   result->f.len = r.len;
   // If the coeff array is null, then that means the coeffs come from the
   // original array
   // Here we copy it over.
   //  const ElementArray& v = (not r.coeffs.isNull() ? r.coeffs : mVectorArithmetic->copyElementArray(get_coeffs_array(r)));
   //  result->f.coeffs.swap(v);
   if (r.coeffs.isNull())
     {
       // this means the actual coeff vector is coming from a GB element.  Copy it into result->f.coeffs
       ElementArray v { mVectorArithmetic->copyElementArray(get_coeffs_array(r)) };
       result->f.coeffs.swap(v);
     }
   else
     {
       result->f.coeffs.swap(r.coeffs);
     }
   result->f.monoms = Mem->allocate_monomial_array(nlongs);
   monomial_word *nextmonom = result->f.monoms;
   for (int i = 0; i < r.len; i++)
     {
       M->copy(mat->columns[r.comps[i]].monom, nextmonom);
       nextmonom += nslots;
     }
   Mem->components.deallocate(r.comps);
   r.len = 0;
   result->deg = this_degree;
   result->alpha = static_cast<int>(M->last_exponent(result->f.monoms));
   result->minlevel = ELEM_MIN_GB;  // MES: How do
   // we distinguish between ELEM_MIN_GB, ELEM_POSSIBLE_MINGEN?
   int which = INTSIZE(gb);
   gb.push_back(result);
   if (hilbert)
     {
       int x;
       int *exp = newarray_atomic(int, M->n_vars());
       M->to_intstar_vector(result->f.monoms, exp, x);
       hilbert->addMonomial(exp, x + 1);
       freemem(exp);
     }
   // now insert the lead monomial into the lookup table
   varpower_monomial vp = newarray_atomic(varpower_word, 2 * M->n_vars() + 1);
   M->to_varpower_monomial(result->f.monoms, vp);
   lookup->insert_minimal_vp(M->get_component(result->f.monoms), vp, which);
   freemem(vp);
   // now go forth and find those new pairs
   S->find_new_pairs(is_ideal);
 }
References HilbertController::addMonomial(), F4Mem::allocate_monomial_array(), gbelem::alpha, GBF4Polynomial::coeffs, row_elem::coeffs, coefficient_matrix::columns, F4Mem::components, row_elem::comps, MonomialInfo::copy(), VectorArithmetic::copyElementArray(), F4Vec::deallocate(), gbelem::deg, ELEM_MIN_GB, mpfr::exp(), gbelem::f, F4SPairSet::find_new_pairs(), freemem(), gb, get_coeffs_array(), MonomialInfo::get_component(), hilbert, F4MonomialLookupTableT< Key >::insert_minimal_vp(), INTSIZE, is_ideal, ElementArray::isNull(), MonomialInfo::last_exponent(), GBF4Polynomial::len, row_elem::len, lookup, M, mat, MonomialInfo::max_monomial_size(), Mem, gbelem::minlevel, GBF4Polynomial::monoms, mVectorArithmetic, MonomialInfo::n_vars(), newarray_atomic, S, ElementArray::swap(), this_degree, MonomialInfo::to_intstar_vector(), MonomialInfo::to_varpower_monomial(), and x.
Referenced by new_GB_elements().