Macaulay2 Engine: F4GB::mult_monomials
mult_monomials()
int F4GB::mult_monomials (packed_monomial m, packed_monomial n) private
Definition at line 141 of file f4.cpp.
 {
   // We already have allocated space for a monomial
   // Do the multiply
   // Look it up in the hashtable
   // If it is there, return its column
   // If not, increment our memory block, and insert a new column.
   packed_monomial new_m;
   M->unchecked_mult(m, n, next_monom);
   if (H.find_or_insert(next_monom, new_m))
     return static_cast<int>(
         new_m[-1]);  // monom exists, don't save monomial space
   m = next_monom;
   B.intern(1 + M->monomial_size(m));
   next_monom = B.reserve(1 + M->max_monomial_size());
   next_monom++;
   return new_column(m);
 }
References B, MonomialHashTable< ValueType >::find_or_insert(), H, F4MemoryBlock< T, NSLAB >::intern(), M, MonomialInfo::max_monomial_size(), MonomialInfo::monomial_size(), new_column(), next_monom, F4MemoryBlock< T, NSLAB >::reserve(), and MonomialInfo::unchecked_mult().
Referenced by load_row().