Macaulay2 Engine: F4GB::reorder_columns
reorder_columns()
void F4GB::reorder_columns () private
Definition at line 274 of file f4.cpp.
 {
   // Set up to sort the columns.
   // Result is an array 0..ncols-1, giving the new order.
   // Find the inverse of this permutation: place values into "ord" column
   // fields.
   // Loop through every element of the matrix, changing its comp array.
   int nrows = INTSIZE(mat->rows);
   int ncols = INTSIZE(mat->columns);
   // sort the columns
   int *column_order = Mem->components.allocate(ncols);
   int *ord = Mem->components.allocate(ncols);
   ColumnsSorter C(M, mat);
 // Actual sort of columns /////////////////
   C.reset_ncomparisons();
   clock_t begin_time0 = clock();
   for (int i = 0; i < ncols; i++)
     {
       column_order[i] = i;
     }
   if (M2_gbTrace >= 2) fprintf(stderr, "ncomparisons = ");
   std::stable_sort(column_order, column_order + ncols, C);
   clock_t end_time0 = clock();
   if (M2_gbTrace >= 2) fprintf(stderr, "%ld, ", C.ncomparisons0());
   double nsecs0 = (double)(end_time0 - begin_time0) / CLOCKS_PER_SEC;
   clock_sort_columns += nsecs0;
   if (M2_gbTrace >= 2) fprintf(stderr, " time = %f\n", nsecs0);
   for (int i = 0; i < ncols; i++)
     {
       ord[column_order[i]] = i;
     }
   // Now move the columns into position
   coefficient_matrix::column_array newcols;
   newcols.reserve(ncols);
   for (int i = 0; i < ncols; i++)
     {
       long newc = column_order[i];
       newcols.push_back(mat->columns[newc]);
     }
   // Now reset the components in each row
   for (int r = 0; r < nrows; r++)
     {
       row_elem &row = mat->rows[r];
       for (int i = 0; i < row.len; i++)
         {
           int oldcol = row.comps[i];
           int newcol = ord[oldcol];
           row.comps[i] = newcol;
         }
       for (int i = 1; i < row.len; i++)
         {
           if (row.comps[i] <= row.comps[i - 1])
             {
               fprintf(stderr, "Internal error: array out of order\n");
               break;
             }
         }
     }
   std::swap(mat->columns, newcols);
   Mem->components.deallocate(column_order);
   Mem->components.deallocate(ord);
 }
References F4Vec::allocate(), clock_sort_columns, coefficient_matrix::columns, F4Mem::components, row_elem::comps, F4Vec::deallocate(), INTSIZE, row_elem::len, M, M2_gbTrace, mat, Mem, ColumnsSorter::ncomparisons0(), ColumnsSorter::reset_ncomparisons(), coefficient_matrix::rows, and swap.
Referenced by make_matrix().