Macaulay2 Engine: F4GB::load_row
load_row()
void F4GB::load_row (packed_monomial monom, int which) private
Definition at line 182 of file f4.cpp.
 {
   GBF4Polynomial &g = gb[which]->f;
   row_elem r{};
   r.monom = monom;
   r.elem = which;
   r.len = g.len;
   r.comps = Mem->components.allocate(g.len);
   // r.coeffs is already initialized to [nullptr].
   monomial_word *w = g.monoms;
   for (int i = 0; i < g.len; i++)
     {
       r.comps[i] = mult_monomials(monom, w);
       w += M->monomial_size(w);
     }
   mat->rows.push_back(r);
 }
References F4Vec::allocate(), F4Mem::components, gb, GBF4Polynomial::len, M, mat, Mem, row_elem::monom, MonomialInfo::monomial_size(), GBF4Polynomial::monoms, mult_monomials(), and coefficient_matrix::rows.
Referenced by process_column(), and process_s_pair().