Macaulay2 Engine: F4GB::reset_matrix
reset_matrix()
void F4GB::reset_matrix () private
Definition at line 382 of file f4.cpp.
 {
   // mat
   next_col_to_process = 0;
   next_monom = B.reserve(1 + M->max_monomial_size());
   next_monom++;
 }
References B, M, MonomialInfo::max_monomial_size(), next_col_to_process, next_monom, and F4MemoryBlock< T, NSLAB >::reserve().
Referenced by computation_is_complete().