Macaulay2 Engine: F4GB::show_gb_array
show_gb_array()
void F4GB::show_gb_array (const gb_array & g) const
Definition at line 937 of file f4.cpp.
 {
   // Debugging routine
   // Display the array, and all of the internal information in it too.
   buffer o;
   for (int i = 0; i < g.size(); i++)
     {
       vec v = F4toM2Interface::to_M2_vec(
           mVectorArithmetic, M, g[i]->f, F);
       o << "element " << i << " degree " << g[i]->deg << " alpha "
         << g[i]->alpha << newline << "    ";
       F->get_ring()->vec_text_out(o, v);
       o << newline;
     }
   emit(o.str());
 }
References emit(), F, FreeModule::get_ring(), M, mVectorArithmetic, newline, buffer::str(), F4toM2Interface::to_M2_vec(), and Ring::vec_text_out().
Referenced by computation_is_complete().