Macaulay2 Engine: F4GB::is_new_GB_row
is_new_GB_row()
bool F4GB::is_new_GB_row (int row) const private
Definition at line 464 of file f4.cpp.
 {
   row_elem &r = mat->rows[row];
   return (r.len > 0 && not r.coeffs.isNull());
 }
References row_elem::coeffs, ElementArray::isNull(), and row_elem::len.
Referenced by new_GB_elements(), and show_new_rows_matrix().