Macaulay2 Engine: F4GB::clear_matrix
clear_matrix()
void F4GB::clear_matrix () private
Definition at line 390 of file f4.cpp.
 {
   // Clear the rows first
   for (auto & r : mat->rows)
     {
       if (not r.coeffs.isNull())
         mVectorArithmetic->deallocateElementArray(r.coeffs);
       Mem->components.deallocate(r.comps);
       r.len = 0;
       r.elem = -1;
       r.monom = nullptr;
     }
   mat->rows.clear();
   mat->columns.clear();
   H.reset();
   B.reset();
   if (M2_gbTrace >= 4)
     {
       Mem->components.show();
       Mem->coefficients.show();
       Mem->show();
     }
 }
References B, F4Mem::coefficients, coefficient_matrix::columns, F4Mem::components, F4Vec::deallocate(), VectorArithmetic::deallocateElementArray(), H, M2_gbTrace, mat, Mem, mVectorArithmetic, F4MemoryBlock< T, NSLAB >::reset(), MonomialHashTable< ValueType >::reset(), coefficient_matrix::rows, F4Vec::show(), and F4Mem::show().
Referenced by computation_is_complete().