Macaulay2 Engine: F4GB::find_or_append_column
find_or_append_column()
int F4GB::find_or_append_column (packed_monomial m) private
Definition at line 129 of file f4.cpp.
 {
   packed_monomial new_m;
   if (H.find_or_insert(m, new_m)) return static_cast<int>(new_m[-1]);
   // At this point, m is a new monomial to be placed as a column
   m = next_monom;
   B.intern(1 + M->monomial_size(m));
   next_monom = B.reserve(1 + M->max_monomial_size());
   next_monom++;
   return new_column(m);
 }
References B, MonomialHashTable< ValueType >::find_or_insert(), H, F4MemoryBlock< T, NSLAB >::intern(), M, MonomialInfo::max_monomial_size(), MonomialInfo::monomial_size(), new_column(), next_monom, and F4MemoryBlock< T, NSLAB >::reserve().
Referenced by load_gen().