Macaulay2 Engine: F4GB::load_gen
load_gen()
void F4GB::load_gen (int which) private
Definition at line 160 of file f4.cpp.
 {
   GBF4Polynomial &g = gens[which]->f;
   row_elem r{};
   r.monom = nullptr;  // This says that this element corresponds to a generator
   r.elem = which;
   r.len = g.len;
   r.comps = Mem->components.allocate(g.len);
   // r.coeffs is already initialized to [nullptr].
   monomial_word *w = g.monoms;
   for (int i = 0; i < g.len; i++)
     {
       M->copy(w, next_monom);
       r.comps[i] = find_or_append_column(next_monom);
       w += M->monomial_size(w);
     }
   mat->rows.push_back(r);
 }
References F4Vec::allocate(), F4Mem::components, MonomialInfo::copy(), find_or_append_column(), gens, GBF4Polynomial::len, M, mat, Mem, row_elem::monom, MonomialInfo::monomial_size(), GBF4Polynomial::monoms, next_monom, and coefficient_matrix::rows.
Referenced by process_s_pair().