Macaulay2 Engine: F4GB::tail_reduce
tail_reduce()
void F4GB::tail_reduce () private
Definition at line 565 of file f4.cpp.
 {
   int nrows = INTSIZE(mat->rows);
   int ncols = INTSIZE(mat->columns);
   ElementArray gauss_row { mVectorArithmetic->allocateElementArray(ncols) };
   for (int i = nrows - 1; i >= 0; i--)
     {
       row_elem &r = mat->rows[i];
       if (r.len <= 1 || r.coeffs.isNull())
         continue;  // row reduced to zero, ignore it.
       // At this point, we should have an element to reduce
       bool anychange = false;
       mVectorArithmetic->fillDenseArray(gauss_row, r.coeffs, Range(r.comps,
                                                                    r.comps + r.len));
       int firstnonzero = r.comps[0];
       int first = (r.len == 1 ? ncols : r.comps[1]);
       int last = r.comps[r.len - 1];
       while (first <= last)
         {
           int pivotrow = mat->columns[first].head;
           if (pivotrow >= 0)
             {
               anychange = true;
               row_elem &pivot_rowelem =
                   mat->rows[pivotrow];  // pivot_rowelems.coeffs is set at this
               mVectorArithmetic->denseCancelFromSparse(gauss_row,
                                                        pivot_rowelem.coeffs,
                                                        Range(pivot_rowelem.comps,
                                                              pivot_rowelem.comps + pivot_rowelem.len));
               int last1 = pivot_rowelem.comps[pivot_rowelem.len - 1];
               if (last1 > last) last = last1;
             }
           else if (firstnonzero == ncols)
             firstnonzero = first;
           first = mVectorArithmetic->denseNextNonzero(gauss_row, first+1, last);
         };
       if (anychange)
         {
           Mem->components.deallocate(r.comps);
           mVectorArithmetic->deallocateElementArray(r.coeffs);
           r.len = 0;
           //Range<int> monomRange;
           //mVectorArithmetic->denseToSparse(gauss_row,
           //                                       r.coeffs,
           //                                       monomRange,
           //                                       firstnonzero, last,
           //                                       mComponentSpace);
           mVectorArithmetic->denseToSparse(gauss_row,
                                                  r.coeffs,
                                                  r.comps,
                                                  firstnonzero, last,
                                                  Mem->components);
           r.len = mVectorArithmetic->size(r.coeffs);
           //r.len = monomRange.size();
           //r.comps = Mem->components.allocate(r.len);
           //std::copy(monomRange.begin(), monomRange.end(), r.comps);
           //mComponentSpace.freeTopArray(monomRange.begin(), monomRange.end());
           assert(r.len == mVectorArithmetic->size(r.coeffs));
         }
       else
         {
           mVectorArithmetic->setZeroInRange(gauss_row, firstnonzero, last);
         }
       if (r.len > 0)
         {
           mVectorArithmetic->makeMonic(r.coeffs);
         }
     }
   mVectorArithmetic->deallocateElementArray(gauss_row);
 }
References VectorArithmetic::allocateElementArray(), row_elem::coeffs, coefficient_matrix::columns, F4Mem::components, row_elem::comps, F4Vec::deallocate(), VectorArithmetic::deallocateElementArray(), VectorArithmetic::denseCancelFromSparse(), VectorArithmetic::denseNextNonzero(), VectorArithmetic::denseToSparse(), VectorArithmetic::fillDenseArray(), INTSIZE, ElementArray::isNull(), row_elem::len, VectorArithmetic::makeMonic(), mat, Mem, mVectorArithmetic, coefficient_matrix::rows, VectorArithmetic::setZeroInRange(), and VectorArithmetic::size().
Referenced by gauss_reduce().