Macaulay2 Engine: F4GB::get_coeffs_array
get_coeffs_array()
const ElementArray & F4GB::get_coeffs_array (row_elem & r) private
Definition at line 452 of file f4.cpp.
 {
   // If r.coeffs is set, returns that, otherwise returns the coeffs array from
   // the generator or GB element.  The resulting value should not be modified.
   if (not r.coeffs.isNull() || r.len == 0) return r.coeffs;
   // At this point, we must go find the coeff array
   if (r.monom == nullptr)  // i.e. a generator
     return gens[r.elem]->f.coeffs;
   return gb[r.elem]->f.coeffs;
 }
References row_elem::coeffs, row_elem::elem, gb, gens, ElementArray::isNull(), row_elem::len, and row_elem::monom.
Referenced by gauss_reduce(), insert_gb_element(), and show_new_rows_matrix().