Macaulay2 Engine: F4GB::show_new_rows_matrix
show_new_rows_matrix()
void F4GB::show_new_rows_matrix ()
Definition at line 989 of file f4.cpp.
 {
   int ncols = INTSIZE(mat->columns);
   int nrows = 0;
   for (int nr = 0; nr < mat->rows.size(); nr++)
     if (is_new_GB_row(nr)) nrows++;
   MutableMatrix *gbM =
       IM2_MutableMatrix_make(mVectorArithmetic->ring(), nrows, ncols, false);
   int r = -1;
   for (int nr = 0; nr < mat->rows.size(); nr++)
     if (is_new_GB_row(nr))
       {
         r++;
         row_elem &row = mat->rows[nr];
         auto& coeffs = get_coeffs_array(row);
         for (int i = 0; i < row.len; i++)
           {
             int c = row.comps[i];
             ring_elem a = mVectorArithmetic->ringElemFromElementArray(coeffs, i);
             gbM->set_entry(r, c, a);
           }
       }
   buffer o;
   gbM->text_out(o);
   emit(o.str());
 }
References coefficient_matrix::columns, row_elem::comps, emit(), get_coeffs_array(), IM2_MutableMatrix_make(), INTSIZE, is_new_GB_row(), row_elem::len, mat, mVectorArithmetic, VectorArithmetic::ring(), VectorArithmetic::ringElemFromElementArray(), coefficient_matrix::rows, MutableMatrix::set_entry(), buffer::str(), and MutableMatrix::text_out().