Macaulay2 Engine: F4GB::process_column
process_column()
void F4GB::process_column (int c) private
Definition at line 203 of file f4.cpp.
 {
   /* If this column has been handled before, return.
      Otherwise, find a GB element whose lead term
      divides this monomial, and either mark this column
      as not an initial element, OR append a row
   */
   column_elem &ce = mat->columns[c];
   if (ce.head >= -1) return;
   int32_t which;
   bool found = lookup->find_one_divisor_packed(M, ce.monom, which);
   if (found)
     {
       packed_monomial n = next_monom;
       M->unchecked_divide(ce.monom, gb[which]->f.monoms, n);
       B.intern(1 + M->monomial_size(n));
       next_monom = B.reserve(1 + M->max_monomial_size());
       next_monom++;
       // M->set_component(which, n);
       ce.head = INTSIZE(mat->rows);
       load_row(n, which);
     }
   else
     ce.head = -1;
 }
References B, coefficient_matrix::columns, F4MonomialLookupTableT< Key >::find_one_divisor_packed(), gb, column_elem::head, F4MemoryBlock< T, NSLAB >::intern(), INTSIZE, load_row(), lookup, M, mat, MonomialInfo::max_monomial_size(), column_elem::monom, MonomialInfo::monomial_size(), next_monom, F4MemoryBlock< T, NSLAB >::reserve(), coefficient_matrix::rows, and MonomialInfo::unchecked_divide().
Referenced by make_matrix().