Macaulay2 Engine: F4GB::do_spairs
do_spairs()
void F4GB::do_spairs () private
Definition at line 737 of file f4.cpp.
{
  if (hilbert && hilbert->nRemainingExpected() == 0)
    {
      if (M2_gbTrace >= 1)
        fprintf(stderr,
                "-- skipping degree...no elements expected in this degree\n");
      return;
    }
  reset_matrix();
  clock_t begin_time = clock();
  n_lcmdups = 0;
  make_matrix();
  if (M2_gbTrace >= 5)
    {
      fprintf(stderr, "---------\n");
      show_matrix();
      fprintf(stderr, "---------\n");
    }
  clock_t end_time = clock();
  clock_make_matrix += end_time - begin_time;
  double nsecs = static_cast<double>(end_time - begin_time);
  nsecs /= CLOCKS_PER_SEC;
  if (M2_gbTrace >= 2) fprintf(stderr, " make matrix time = %f\n", nsecs);
  if (M2_gbTrace >= 2) H.dump();
  begin_time = clock();
  gauss_reduce(true);
  end_time = clock();
  clock_gauss += end_time - begin_time;
  //  fprintf(stderr, "---------\n");
  //  show_matrix();
  //  fprintf(stderr, "---------\n");
  nsecs = static_cast<double>(end_time - begin_time);
  nsecs /= CLOCKS_PER_SEC;
  if (M2_gbTrace >= 2)
    {
      fprintf(stderr, " gauss time          = %f\n", nsecs);
      fprintf(stderr, " lcm dups            = %ld\n", n_lcmdups);
      if (M2_gbTrace >= 5)
        {
          fprintf(stderr, "---------\n");
          show_matrix();
          fprintf(stderr, "---------\n");
        }
    }
  new_GB_elements();
  int ngb = INTSIZE(gb);
  if (M2_gbTrace >= 1)
    {
      fprintf(stderr, " # GB elements   = %d\n", ngb);
      if (M2_gbTrace >= 5) show_gb_array(gb);
    }
  clear_matrix();
}
References clear_matrix(), clock_gauss, clock_make_matrix, MonomialHashTable< ValueType >::dump(), gauss_reduce(), gb, H, hilbert, INTSIZE, M2_gbTrace, make_matrix(), n_lcmdups, new_GB_elements(), HilbertController::nRemainingExpected(), reset_matrix(), show_gb_array(), and show_matrix().
Referenced by start_computation().