Macaulay2 Engine: F4GB::computation_is_complete
computation_is_complete()
enum ComputationStatusCode F4GB::computation_is_complete (StopConditions & stop_) private
Definition at line 737 of file f4.cpp.
 {
   // This handles everything but stop_.always, stop_.degree_limit
   if (stop_.basis_element_limit > 0 && gb.size() >= stop_.basis_element_limit)
     return COMP_DONE_GB_LIMIT;
   if (stop_.pair_limit > 0 && n_pairs_computed >= stop_.pair_limit)
     return COMP_DONE_PAIR_LIMIT;
   if (stop_.just_min_gens && n_gens_left == 0) return COMP_DONE_MIN_GENS;
   if (stop_.subring_limit > 0 && n_subring >= stop_.subring_limit)
     return COMP_DONE_SUBRING_LIMIT;
   if (stop_.use_codim_limit)
     {
 #ifdef DEVELOPMENT
 #warning "compute the codimension"
 #endif
       int c = 0;  // replace this line
       // int c = codim_of_lead_terms();
       if (c >= stop_.codim_limit) return COMP_DONE_CODIM;
     }
   return COMP_COMPUTING;
 }
References clear_matrix(), clock_gauss, clock_make_matrix, MonomialHashTable< ValueType >::dump(), gauss_reduce(), gb, H, hilbert, INTSIZE, M2_gbTrace, make_matrix(), n_lcmdups, new_GB_elements(), HilbertController::nRemainingExpected(), reset_matrix(), show_gb_array(), and show_matrix().