Macaulay2 Engine: F4GB::start_computation
start_computation()
enum ComputationStatusCode F4GB::start_computation (StopConditions & stop_)
Definition at line 839 of file f4.cpp.
{
  clock_sort_columns = 0;
  clock_gauss = 0;
  clock_make_matrix = 0;
  int npairs;
  //  test_spair_code();
  enum ComputationStatusCode is_done = COMP_COMPUTING;
  for (;;)
    {
      if (system_interrupted())
        {
          is_done = COMP_INTERRUPTED;
          break;
        }
      is_done = computation_is_complete(stop_);
      if (is_done != COMP_COMPUTING) break;
      this_degree = S->prepare_next_degree(-1, npairs);
      if (npairs == 0)
        {
          is_done = COMP_DONE;
          break;
        }
      if (stop_.stop_after_degree && this_degree > stop_.degree_limit->array[0])
        {
          is_done = COMP_DONE_DEGREE_LIMIT;
          break;
        }
      if (hilbert)
        {
          if (!hilbert->setDegree(this_degree))
            {
              if (error())
                is_done = COMP_ERROR;
              else
                is_done = COMP_INTERRUPTED;
              break;
            }
        }
      if (M2_gbTrace >= 1)
        {
          if (hilbert)
            fprintf(stderr,
                    "DEGREE %d (nexpected %d npairs %d)\n",
                    this_degree,
                    hilbert->nRemainingExpected(),
                    npairs);
          else
            fprintf(stderr, "DEGREE %d (npairs %d)\n", this_degree, npairs);
        }
      do_spairs();
      complete_thru_this_degree = this_degree;
    }
  if (M2_gbTrace >= 2)
    {
      // fprintf(stderr,
      //         "number of calls to cancel row       : %ld\n",
      //         mGausser->n_dense_row_cancel);
      // fprintf(stderr,
      //         "number of calls to subtract_multiple: %ld\n",
      //         mGausser->n_subtract_multiple);
      fprintf(
          stderr, "total time for sorting columns: %f\n", clock_sort_columns);
      fprintf(stderr,
              "total time for making matrix (includes sort): %f\n",
              ((double)clock_make_matrix) / CLOCKS_PER_SEC);
      fprintf(stderr,
              "total time for gauss: %f\n",
              ((double)clock_gauss) / CLOCKS_PER_SEC);
      fprintf(stderr,
              "number of spairs computed           : %ld\n",
              n_pairs_computed);
      fprintf(stderr,
              "number of reduction steps           : %ld\n",
              n_reduction_steps);
    }
  fprintf(stderr,
          "number of spairs removed by criterion = %ld\n",
          S->n_unneeded_pairs());
  M->show();
  return is_done;
}
References clock_gauss, clock_make_matrix, clock_sort_columns, COMP_COMPUTING, COMP_DONE, COMP_DONE_DEGREE_LIMIT, COMP_ERROR, COMP_INTERRUPTED, complete_thru_this_degree, computation_is_complete(), StopConditions::degree_limit, do_spairs(), error(), hilbert, M, M2_gbTrace, n_pairs_computed, n_reduction_steps, F4SPairSet::n_unneeded_pairs(), HilbertController::nRemainingExpected(), F4SPairSet::prepare_next_degree(), S, HilbertController::setDegree(), MonomialInfo::show(), StopConditions::stop_after_degree, system_interrupted(), and this_degree.
Referenced by F4Computation::start_computation().