Macaulay2 Engine: F4GB::new_GB_elements
new_GB_elements()
void F4GB::new_GB_elements () private
Definition at line 706 of file f4.cpp.
 {
   /* After LU decomposition, loop through each
      row of the matrix.  If the corresponding
      lead term is not in the initial ideal (or, at least,
      wasn't) then insert GB element (and so update spairs, etc,
      but don't do auto_reduce...)
      If instead the lead term is not new, then keep track of this
      information somehow: place ... into a monheap...
   */
   /* If we can place the possible new elements first, or in a separate place,
      then
      we don't need to loop through all of these */
   for (int r = 0; r < mat->rows.size(); r++)
     {
       if (is_new_GB_row(r))
         {
           insert_gb_element(mat->rows[r]);
         }
     }
 }
References insert_gb_element(), is_new_GB_row(), mat, and coefficient_matrix::rows.
Referenced by computation_is_complete().