Macaulay2 Engine: F4GB::gauss_reduce
gauss_reduce()
void F4GB::gauss_reduce (bool diagonalize) private
Definition at line 473 of file f4.cpp.
 {
   // For each row which is a non-pivot row:
   //  note that the row must be reducible, since the lead term corresponds to an
   //  spair cancellation
   //   actually: not true: generators will often not be reducible...
   //  also each such row must be non-zero, for the same reason
   int nrows = INTSIZE(mat->rows);
   int ncols = INTSIZE(mat->columns);
   int n_newpivots = -1;  // the number of new GB elements in this degree
   int n_zero_reductions = 0;
   if (hilbert)
     {
       n_newpivots = hilbert->nRemainingExpected();
       if (n_newpivots == 0) return;
     }
   ElementArray gauss_row { mVectorArithmetic->allocateElementArray(ncols) };
   for (int i = 0; i < nrows; i++)
     {
       row_elem &r = mat->rows[i];
       if (r.len == 0) continue;  // could happen once we include syzygies...
       int pivotcol = r.comps[0];
       int pivotrow = mat->columns[pivotcol].head;
       if (pivotrow == i) continue;  // this is a pivot row, so leave it alone
       const ElementArray& rcoeffs = get_coeffs_array(r);
       n_pairs_computed++;
       mVectorArithmetic->fillDenseArray(gauss_row, rcoeffs, Range(r.comps, r.comps + r.len));
       int firstnonzero = ncols;
       int first = r.comps[0];
       int last = r.comps[r.len - 1];
       do
         {
           pivotrow = mat->columns[first].head;
           if (pivotrow >= 0)
             {
               row_elem &pivot_rowelem = mat->rows[pivotrow];
               auto& pivot_coeffs = get_coeffs_array(pivot_rowelem);
               n_reduction_steps++;
               mVectorArithmetic->denseCancelFromSparse(gauss_row,
                                                           pivot_coeffs,
                                                           Range(pivot_rowelem.comps,
                                                                 pivot_rowelem.comps + pivot_rowelem.len)
                                                           );
               int last1 = pivot_rowelem.comps[pivot_rowelem.len - 1];
               if (last1 > last) last = last1;
             }
           else if (firstnonzero == ncols)
             firstnonzero = first;
           first = mVectorArithmetic->denseNextNonzero(gauss_row, first+1, last);
         }
       while (first <= last);
       if (not r.coeffs.isNull())
         mVectorArithmetic->deallocateElementArray(r.coeffs);
       Mem->components.deallocate(r.comps);
       r.len = 0;
       //Range<int> monomRange;
       //mVectorArithmetic->denseToSparse(gauss_row, r.coeffs, monomRange, firstnonzero, last, mComponentSpace);
       mVectorArithmetic->denseToSparse(gauss_row, r.coeffs, r.comps, firstnonzero, last, Mem->components);
       // TODO set r.comps from monomRange.  Question: who has allocated this space??
       // Maybe for now it is just the following line:
       r.len = mVectorArithmetic->size(r.coeffs);
       //r.len = monomRange.size();
       //r.comps = Mem->components.allocate(r.len);
       //std::copy(monomRange.begin(), monomRange.end(), r.comps);
       //mComponentSpace.freeTopArray(monomRange.begin(), monomRange.end());
       //assert(r.len == mVectorArithmetic->size(r.coeffs));
       // the above line leaves gauss_row zero, and also handles the case when
       // r.len is 0 (TODO: check this!!)
       // it also potentially frees the old r.coeffs and r.comps (TODO: ?? r.comps??)
       if (r.len > 0)
         {
           mVectorArithmetic->makeMonic(r.coeffs);
           mat->columns[r.comps[0]].head = i;
           if (--n_newpivots == 0) break;
         }
       else
         n_zero_reductions++;
     }
   mVectorArithmetic->deallocateElementArray(gauss_row);
   if (M2_gbTrace >= 3)
     fprintf(stderr, "-- #zeroreductions %d\n", n_zero_reductions);
   if (diagonalize) tail_reduce();
 }
References VectorArithmetic::allocateElementArray(), row_elem::coeffs, coefficient_matrix::columns, F4Mem::components, row_elem::comps, F4Vec::deallocate(), VectorArithmetic::deallocateElementArray(), VectorArithmetic::denseCancelFromSparse(), VectorArithmetic::denseNextNonzero(), VectorArithmetic::denseToSparse(), VectorArithmetic::fillDenseArray(), get_coeffs_array(), hilbert, INTSIZE, ElementArray::isNull(), row_elem::len, M2_gbTrace, VectorArithmetic::makeMonic(), mat, Mem, mVectorArithmetic, n_pairs_computed, n_reduction_steps, HilbertController::nRemainingExpected(), coefficient_matrix::rows, VectorArithmetic::size(), and tail_reduce().
Referenced by computation_is_complete().