Macaulay2 Engine: F4GB::show_matrix
show_matrix()
void F4GB::show_matrix ()
Definition at line 977 of file f4.cpp.
 {
   // Debugging routine
   MutableMatrix *q = F4toM2Interface::to_M2_MutableMatrix(
       mVectorArithmetic, mat, gens, gb);
   buffer o;
   q->text_out(o);
   emit(o.str());
 }
References emit(), gb, gens, mat, mVectorArithmetic, buffer::str(), MutableMatrix::text_out(), and F4toM2Interface::to_M2_MutableMatrix().
Referenced by computation_is_complete().