Macaulay2 Engine: F4GB::make_matrix
make_matrix()
void F4GB::make_matrix () private
Definition at line 414 of file f4.cpp.
 {
   /* loop through all spairs, process,
      then while there are any columns to process, do so,
      then process rows.
      Is this the best order to do it in?  Maybe not...
   */
   spair *p;
   while ((p = S->get_next_pair()))
     {
       process_s_pair(p);
     }
   while (next_col_to_process < mat->columns.size())
     process_column(next_col_to_process++);
   // DEBUGGING:
   if (M2_gbTrace >= 2)
     {
       fprintf(stderr,
               "--matrix--%ld by %ld\n",
               (long)mat->rows.size(),
               (long)mat->columns.size());
     }
   //  show_row_info();
   //  show_column_info();
   //  show_matrix();
   // Now we reorder the columns, possibly rows?
   reorder_columns();
   // reorder_rows();  // This is only here so we can see what we are doing...?
 }
References coefficient_matrix::columns, F4SPairSet::get_next_pair(), M2_gbTrace, mat, next_col_to_process, p, process_column(), process_s_pair(), reorder_columns(), coefficient_matrix::rows, and S.
Referenced by computation_is_complete().