Macaulay2 Engine: F4GB::process_s_pair
process_s_pair()
void F4GB::process_s_pair (spair * p) private
Definition at line 230 of file f4.cpp.
 {
   int c;
   switch (p->type)
     {
       case F4_SPAIR_SPAIR:
         {
           packed_monomial n = next_monom;
           M->unchecked_divide(p->lcm, gb[p->i]->f.monoms, n);
           B.intern(1 + M->monomial_size(n));
           next_monom = B.reserve(1 + M->max_monomial_size());
           next_monom++;
           load_row(n, p->i);
           c = mat->rows[mat->rows.size() - 1].comps[0];
           if (mat->columns[c].head >= -1)
             n_lcmdups++;
           else
             {
               // In this situation, we load the other half as a reducer
               n = next_monom;
               M->unchecked_divide(p->lcm, gb[p->j]->f.monoms, n);
               B.intern(1 + M->monomial_size(n));
               next_monom = B.reserve(1 + M->max_monomial_size());
               next_monom++;
               load_row(n, p->j);
               mat->columns[c].head = INTSIZE(mat->rows) - 1;
             }
           break;
         }
       case F4_SPAIR_GEN:
         load_gen(p->i);
         break;
       default:
         break;
     }
 }
References B, coefficient_matrix::columns, F4_SPAIR_GEN, F4_SPAIR_SPAIR, gb, F4MemoryBlock< T, NSLAB >::intern(), INTSIZE, load_gen(), load_row(), M, mat, MonomialInfo::max_monomial_size(), MonomialInfo::monomial_size(), n_lcmdups, next_monom, p, F4MemoryBlock< T, NSLAB >::reserve(), coefficient_matrix::rows, and MonomialInfo::unchecked_divide().
Referenced by make_matrix().