Macaulay2 Engine: gb2_comp::hilbertNumerator
hilbertNumerator()
RingElement * gb2_comp::hilbertNumerator () virtual
Implements gb_node.
Definition at line 846 of file res-a2-gb.cpp.
{
  if (hf_numgens_gb == n_gb && hf_numgens_F == F->rank())
    {
      return hf;
    }
  Matrix *hf_matrix = make_lead_term_matrix();
  hf = hilb_comp::hilbertNumerator(hf_matrix);
  // hf is NULL if the computation was interrupted
  if (hf == nullptr) return nullptr;
  hf_numgens_F = F->rank();
  hf_numgens_gb = n_gb;
  return hf;
}
References F, hf, hf_numgens_F, hf_numgens_gb, hilb_comp::hilbertNumerator(), make_lead_term_matrix(), n_gb, and FreeModule::rank().
Referenced by calc_gb().