Macaulay2 Engine: gb2_comp::gb_reduce
gb_reduce()
void gb2_comp::gb_reduce (gbvector *& f, gbvector *& fsyz) private
Definition at line 328 of file res-a2-gb.cpp.
 {
   if ((strategy_flags & STRATEGY_LONGPOLYNOMIALS) != 0)
     {
       gb_geo_reduce(f, fsyz);
       return;
     }
   gbvector head;
   gbvector *result = &head;
   result->next = 0;
   exponents_t div_totalexp = newarray_atomic(int, M->n_vars());
   int count = 0;
   if (M2_gbTrace == 10)
     {
       buffer o;
       o << "reducing ";
       GR->gbvector_text_out(o, F, f);
       emit_line(o.str());
     }
   while (f != NULL)
     {
       Bag *b;
       GR->gbvector_get_lead_exponents(F, f, div_totalexp);
       if (originalR->is_quotient_ring() &&
           originalR->get_quotient_monomials()->search_expvector(div_totalexp,
                                                                 b))
         {
           const gbvector *g = originalR->quotient_gbvector(b->basis_elem());
           GR->gbvector_reduce_lead_term(F, Fsyz, head.next, f, fsyz, g, 0);
           count++;
         }
       else if (monideals[f->comp]->mi_search->search_expvector(div_totalexp, b))
         {
           gb_elem *q = reinterpret_cast<gb_elem *>(b->basis_ptr());
           GR->gbvector_reduce_lead_term(
               F, Fsyz, head.next, f, fsyz, q->f, q->fsyz);
           count++;
           if (M2_gbTrace == 10)
             {
               buffer o;
               o << "  reduced by ";
               GR->gbvector_text_out(o, F, q->f);
               o << newline;
               o << "    giving ";
               GR->gbvector_text_out(o, F, f);
               o << newline;
               emit(o.str());
             }
         }
       else
         {
           result->next = f;
           f = f->next;
           result = result->next;
           result->next = 0;
         }
     }
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << "." << count;
       emit_wrapped(o.str());
     }
   f = head.next;
   freemem(div_totalexp);
 }
References int_bag::basis_elem(), int_bag::basis_ptr(), gbvector::comp, emit(), emit_line(), emit_wrapped(), F, gb_elem::f, freemem(), Fsyz, gb_elem::fsyz, gb_geo_reduce(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_reduce_lead_term(), GBRing::gbvector_text_out(), PolynomialRing::get_quotient_monomials(), GR, PolynomialRing::is_quotient_ring(), M, M2_gbTrace, monideals, Monoid::n_vars(), newarray_atomic, newline, gbvector::next, originalR, PolynomialRing::quotient_gbvector(), MonomialIdeal::search_expvector(), buffer::str(), strategy_flags, and STRATEGY_LONGPOLYNOMIALS.
Referenced by receive_generator(), reduce(), and s_pair_step().