Macaulay2 Engine: gb2_comp::receive_generator
receive_generator()
bool gb2_comp::receive_generator (gbvector * f, int n, const ring_elem denom) virtual
Implements gb_node.
Definition at line 614 of file res-a2-gb.cpp.
 {
   bool isgen = false;
   // It is our duty to free 'f'...
   for (int i = monideals.size(); i <= F->rank(); i++)
     {
       monideal_pair *p = new monideal_pair(originalR, mi_stash);
       monideals.push_back(p);
     }
   gbvector *fsyz = NULL;
   if (orig_syz >= 0)
     {
       if (orig_syz > n)
         fsyz = GR->gbvector_term(
             Fsyz, denom, n + 1);  // Note the change in component number
       gb_reduce(f, fsyz);
       if (f == NULL)
         {
           if (fsyz != NULL && syz != NULL)
             syz->receive_generator(fsyz, n_syz++, GR->one());
         }
       else
         {
           isgen = true;
           gb_insert(f, fsyz, 1);
         }
     }
   else
     {
       gb_reduce(f, fsyz);
       GR->gbvector_remove(fsyz);
       GR->gbvector_remove_content(f, NULL);
       if (f != NULL)
         {
           // schreyer_append(f);
           isgen = true;
           // gb_insert(f,Fsyz->e_sub_i(n_mingens),1);
           // The fsyz part will be set at the end of the degree,
           // after sorting takes place, and after auto-reduction in
           // this degree.
           gb_insert(f, NULL, 1);
         }
     }
   return isgen;
 }
References Fsyz, gb_insert(), gb_reduce(), GBRing::gbvector_remove(), GBRing::gbvector_remove_content(), GBRing::gbvector_term(), GR, mi_stash, monideals, n_syz, GBRing::one(), orig_syz, originalR, p, ffpackInterface::rank(), gb_node::receive_generator(), and syz.