Macaulay2 Engine: gb2_comp::stats
stats()
void gb2_comp::stats () const virtual
Implements gb_node.
Definition at line 982 of file res-a2-gb.cpp.
 {
   buffer o;
   if (M2_gbTrace >= 4 && n_gb > 0)
     {
       int nmonoms = 0;
       int nchange = 0;
       for (int i = 0; i < gb.size(); i++)
         {
           nmonoms += GR->gbvector_n_terms(gb[i]->f);
           nchange += GR->gbvector_n_terms(gb[i]->fsyz);
         }
       o.put(n_gb, 5);
       o.put(" ");
       o.put(n_pairs, 5);
       o.put(" ");
       o.put(n_pairs_computed, 5);
       o.put(" ");
       o.put(n_pairs_gb, 5);
       o.put(" ");
       o.put(n_pairs_syz, 5);
       o.put(" ");
       o.put(n_pairs_zero, 5);
       o.put(" ");
       o.put(n_pairs_usyz, 5);
       o.put(" ");
       o.put(n_pairs_hilb, 5);
       o.put(" ");
       o.put(n_pairs_gcd, 5);
       o.put(" ");
       o.put(nmonoms, 5);
       o.put(" ");
       o.put(nchange, 5);
       o.put(newline);
       emit(o.str());
       o.reset();
     }
   spairs->stats();
   if (M2_gbTrace >= 5 && M2_gbTrace % 2 == 1)
     {
       o << "free module is ";
       F->text_out(o);
       o << newline;
       for (int i = 0; i < gb.size(); i++)
         {
           o.reset();
           o << i << '\t';
           GR->gbvector_text_out(o, F, gb[i]->f);
           o << newline;
           emit(o.str());
         }
     }
   //  dfree(F);
 }
References emit(), F, gb, GBRing::gbvector_n_terms(), GBRing::gbvector_text_out(), GR, M2_gbTrace, n_gb, n_pairs, n_pairs_computed, n_pairs_gb, n_pairs_gcd, n_pairs_hilb, n_pairs_syz, n_pairs_usyz, n_pairs_zero, newline, buffer::put(), buffer::reset(), spairs, s_pair_heap::stats(), buffer::str(), and FreeModule::text_out().