Macaulay2 Engine: gb2_comp::compute_s_pair
compute_s_pair()
void gb2_comp::compute_s_pair (s_pair * p) private
Definition at line 311 of file res-a2-gb.cpp.
 {
   if (p->f == NULL)
     {
       monomial s = M->make_one();
       GR->gbvector_get_lead_monomial(F, p->first->f, s);
       M->divide(p->lcm, s, s);
       GR->gbvector_mult_by_term(
           F, Fsyz, GR->one(), s, p->first->f, p->first->fsyz, p->f, p->fsyz);
       if (p->syz_type == SPAIR_PAIR)
         GR->gbvector_reduce_lead_term(
             F, Fsyz, 0, p->f, p->fsyz, p->second->f, p->second->fsyz);
       M->remove(s);
     }
 }
References Monoid::divide(), F, Fsyz, GBRing::gbvector_get_lead_monomial(), GBRing::gbvector_mult_by_term(), GBRing::gbvector_reduce_lead_term(), GR, M, Monoid::make_one(), GBRing::one(), p, Monoid::remove(), and SPAIR_PAIR.
Referenced by s_pair_step().