Macaulay2 Engine: gb2_comp::s_pair_step
s_pair_step()
bool gb2_comp::s_pair_step () private
Definition at line 557 of file res-a2-gb.cpp.
 {
   if (use_hilb && n_gb_syz == 0) flush_pairs();
   if (these_pairs == nullptr) return false;  // Done
   s_pair *p = these_pairs;
   these_pairs = these_pairs->next;
   n_pairs_computed++;
   compute_s_pair(p);
   gbvector *f = p->f;
   gbvector *fsyz = p->fsyz;
   p->f = nullptr;
   p->fsyz = nullptr;
   remove_pair(p);
   gb_reduce(f, fsyz);
   if (f != nullptr)
     {
       gb_insert(f, fsyz, 0);
       n_gb_syz--;
       n_pairs_gb++;
       if (M2_gbTrace >= 3) emit_wrapped("m");
     }
   else if (fsyz != nullptr && syz != nullptr)
     {
       if (syz->receive_generator(fsyz, n_syz++, GR->one()))
         {
           n_gb_syz--;
           n_pairs_syz++;
           if (M2_gbTrace >= 3) emit_wrapped("z");
         }
       else
         {
           n_pairs_usyz++;
           if (M2_gbTrace >= 3) emit_wrapped("u");
         }
     }
   else
     {
       if (fsyz != nullptr) GR->gbvector_remove(fsyz);
       n_pairs_zero++;
       if (M2_gbTrace >= 3) emit_wrapped("o");
     }
   return true;
 }
References compute_s_pair(), emit_wrapped(), flush_pairs(), gb_insert(), gb_reduce(), GBRing::gbvector_remove(), GR, M2_gbTrace, n_gb_syz, n_pairs_computed, n_pairs_gb, n_pairs_syz, n_pairs_usyz, n_pairs_zero, n_syz, s_pair::next, GBRing::one(), p, gb_node::receive_generator(), remove_pair(), syz, these_pairs, and use_hilb.