Macaulay2 Engine: gb2_comp::gb_insert
gb_insert()
void gb2_comp::gb_insert (gbvector * f, gbvector * fsyz, int ismin) private
Definition at line 485 of file res-a2-gb.cpp.
 {
   monomial f_m = M->make_one();
   gbvector *bull = nullptr;
   gb_elem *p = new gb_elem(f, fsyz, ismin);
   if (orig_syz < 0 && ismin)
     GR->gbvector_remove_content(p->f, bull);
   else
     GR->gbvector_remove_content(p->f, p->fsyz);
   if (M2_gbTrace >= 10)
     {
       buffer o;
       o << "inserting level " << level << " ";
       GR->gbvector_text_out(o, F, p->f);
       o << newline;
       emit(o.str());
     }
   if (ismin) n_mingens++;
   GR->gbvector_get_lead_monomial(F, p->f, f_m);
   if (M->in_subring(1, f_m)) n_subring++;
   // insert into p->f->comp->mi_search
   gc_vector<int> vp;
   M->to_varpower(f_m, vp);
   monideals[p->f->comp]->mi_search->insert(new Bag(p, vp));
   gb.push_back(p);
   M->remove(f_m);
   // Now do auto-reduction of previous elements using this one.
   if (orig_syz >= 0 || !ismin)
     for (int i = n_gb_first; i < n_gb; i++)
       {
         // Now compute gb(i) := gb(i) - c gb(j), where
         // c in(gb(j)) is a term in gb(i).
         // Also compute change(i) -= c change(j).
         GR->gbvector_auto_reduce(F, Fsyz, gb[i]->f, gb[i]->fsyz, p->f, p->fsyz);
       }
   n_gb++;
 }
References emit(), F, Fsyz, gb, GBRing::gbvector_auto_reduce(), GBRing::gbvector_get_lead_monomial(), GBRing::gbvector_remove_content(), GBRing::gbvector_text_out(), GR, Monoid::in_subring(), level, M, M2_gbTrace, Monoid::make_one(), monideals, n_gb, n_gb_first, n_mingens, n_subring, newline, orig_syz, p, Monoid::remove(), buffer::str(), and Monoid::to_varpower().
Referenced by receive_generator(), and s_pair_step().