Macaulay2 Engine: gb2_comp::initial_matrix
initial_matrix()
Matrix * gb2_comp::initial_matrix (int n) virtual
Implements gb_node.
Definition at line 883 of file res-a2-gb.cpp.
 {
   MatrixConstructor mat(F, 0);
   for (int i = 0; i < gb.size(); i++)
     {
       gbvector *tmp = GR->gbvector_lead_term(n, F, gb[i]->f);
       mat.append(originalR->translate_gbvector_to_vec(F, tmp));
       GR->gbvector_remove(tmp);
     }
   return mat.to_matrix();
 }
References MatrixConstructor::append(), F, gb, GBRing::gbvector_lead_term(), GBRing::gbvector_remove(), GR, originalR, MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().