Macaulay2 Engine: gb2_comp::gb_geo_reduce
gb_geo_reduce()
void gb2_comp::gb_geo_reduce (gbvector *& f, gbvector *& fsyz) private
Definition at line 397 of file res-a2-gb.cpp.
 {
   gbvector head;
   gbvector *result = &head;
   result->next = 0;
   int *div_totalexp = newarray_atomic(int, M->n_vars());
   int count = 0;
   gbvectorHeap fb(GR, F);
   gbvectorHeap fsyzb(GR, Fsyz);
   fb.add(f);
   fsyzb.add(fsyz);
   const gbvector *lead;
   while ((lead = fb.get_lead_term()) != NULL)
     {
       Bag *b;
       GR->gbvector_get_lead_exponents(F, lead, div_totalexp);
       if (originalR->is_quotient_ring() &&
           originalR->get_quotient_monomials()->search_expvector(div_totalexp,
                                                                 b))
         {
           const gbvector *g = originalR->quotient_gbvector(b->basis_elem());
           GR->reduce_lead_term_heap(F,
                                     Fsyz,
                                     lead,
                                     div_totalexp,  // are these two needed
                                     head.next,
                                     fb,
                                     fsyzb,
                                     g,
                                     0);
           count++;
         }
       else if (monideals[lead->comp]->mi_search->search_expvector(div_totalexp,
                                                                   b))
         {
           gb_elem *q = reinterpret_cast<gb_elem *>(b->basis_ptr());
           GR->reduce_lead_term_heap(
               F, Fsyz, lead, div_totalexp, head.next, fb, fsyzb, q->f, q->fsyz);
           count++;
         }
       else
         {
           result->next = fb.remove_lead_term();
           result = result->next;
           result->next = 0;
         }
     }
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << "." << count;
       emit_wrapped(o.str());
     }
   f = head.next;
   fsyz = fsyzb.value();
   freemem(div_totalexp);
 }
References gbvectorHeap::add(), int_bag::basis_elem(), int_bag::basis_ptr(), gbvector::comp, emit_wrapped(), F, gb_elem::f, freemem(), Fsyz, gb_elem::fsyz, GBRing::gbvector_get_lead_exponents(), gbvectorHeap::get_lead_term(), PolynomialRing::get_quotient_monomials(), GR, PolynomialRing::is_quotient_ring(), M, M2_gbTrace, monideals, Monoid::n_vars(), newarray_atomic, gbvector::next, originalR, PolynomialRing::quotient_gbvector(), GBRing::reduce_lead_term_heap(), gbvectorHeap::remove_lead_term(), MonomialIdeal::search_expvector(), buffer::str(), and gbvectorHeap::value().
Referenced by gb_reduce().