Macaulay2 Engine: gb2_comp::change_matrix
change_matrix()
Matrix * gb2_comp::change_matrix () virtual
Implements gb_node.
Definition at line 903 of file res-a2-gb.cpp.
 {
   MatrixConstructor mat(Fsyz, 0);
   for (int i = 0; i < gb.size(); i++)
     mat.append(originalR->translate_gbvector_to_vec(Fsyz, gb[i]->fsyz));
   return mat.to_matrix();
 }
References MatrixConstructor::append(), Fsyz, gb, originalR, MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().