Macaulay2 Engine: gb2_comp::remove_pair
remove_pair()
void gb2_comp::remove_pair (s_pair *& p) private
Definition at line 90 of file res-a2-gb.cpp.
 {
   p->f = nullptr;  // these are not used in res-a2-gb algorithm except for temp space
   p->fsyz = nullptr;  // ditto
   p->first = nullptr;
   p->second = nullptr;
   p->next = nullptr;
   M->remove(p->lcm);
   freemem(p);
   p = nullptr;
 }
References freemem(), M, p, and Monoid::remove().
Referenced by find_pairs(), flush_pairs(), and s_pair_step().