Macaulay2 Engine: gb2_comp::find_pairs
find_pairs()
void gb2_comp::find_pairs (gb_elem * p) private
Definition at line 195 of file res-a2-gb.cpp.
 {
   gc_vector<Bag*> elems;
   gc_vector<int> vplcm;
   monomial find_pairs_m = M->make_one();
   monomial f_m = M->make_one();
   int *find_pairs_lcm = newarray_atomic(int, M->n_vars());
   GR->gbvector_get_lead_monomial(F, p->f, f_m);
   if (GR->is_skew_commutative())
     {
       exponents_t find_pairs_exp = newarray_atomic(int, M->n_vars());
       M->to_expvector(f_m, find_pairs_exp);
       for (int v = 0; v < GR->n_skew_commutative_vars(); v++)
         {
           int w = GR->skew_variable(v);
           if (find_pairs_exp[w] == 0) continue;
           find_pairs_exp[w]++;
           M->from_expvector(find_pairs_exp, find_pairs_lcm);
           find_pairs_exp[w]--;
           vplcm.resize(0);
           M->to_varpower(find_pairs_lcm, vplcm);
           s_pair *q = new_ring_pair(p, find_pairs_lcm);
           elems.push_back(new Bag(q, vplcm));
         }
       freemem(find_pairs_exp);
     }
   // Add in syzygies arising from a base ring
   if (originalR->is_quotient_ring())
     {
       for (int i = 0; i < originalR->n_quotients(); i++)
         {
           const Nterm *f = originalR->quotient_element(i);
           M->lcm(f->monom, f_m, find_pairs_lcm);
           vplcm.resize(0);
           M->to_varpower(find_pairs_lcm, vplcm);
           s_pair *q = new_ring_pair(p, find_pairs_lcm);
           elems.push_back(new Bag(q, vplcm));
         }
     }
   // Add in syzygies arising as s-pairs
   MonomialIdeal *mi1 = monideals[p->f->comp]->mi;
   for (Bag& a : *mi1)
     {
       M->from_varpower(a.monom().data(), find_pairs_m);
       M->lcm(find_pairs_m, f_m, find_pairs_lcm);
       vplcm.resize(0);
       M->to_varpower(find_pairs_lcm, vplcm);
       s_pair *q =
           new_s_pair(p,
                      reinterpret_cast<gb_elem *>(a.basis_ptr()),
                      find_pairs_lcm);
       elems.push_back(new Bag(q, vplcm));
     }
   // Add 'p' to the correct monideal
   gc_vector<int> vp;
   M->to_varpower(f_m, vp);
   mi1->insert(new Bag(p, vp));
   // Now minimalize these elements, and insert them into
   // the proper degree.
   VECTOR(Bag *) rejects;
   MonomialIdeal *mi = new MonomialIdeal(originalR, elems, rejects, mi_stash);
   for (auto& b : rejects)
     {
       s_pair *q = reinterpret_cast<s_pair *>(b->basis_ptr());
       remove_pair(q);
       delete b;
     }
   int is_ideal2 = (F->rank() == 1 && orig_syz == 0);
   for (Bag& a : *mi)
     {
       n_pairs++;
       s_pair *q = reinterpret_cast<s_pair *>(a.basis_ptr());
       if (is_ideal2 && q->syz_type == SPAIR_PAIR)
         {
           // MES: the following line is suspect, for Schreyer orders
           M->gcd(q->first->f->monom, q->second->f->monom, find_pairs_m);
           if (M->is_one(find_pairs_m))
             {
               n_pairs_gcd++;
               if (M2_gbTrace >= 8)
                 {
                   buffer o;
                   o << "removed pair[" << q->first->me << " " << q->second->me
                     << "]" << newline;
                   emit(o.str());
                 }
               remove_pair(q);
             }
           else
             spairs->insert(q);
         }
       else
         spairs->insert(q);
     }
   delete mi;
   // Remove the local variables
   M->remove(find_pairs_m);
   M->remove(f_m);
   freemem(find_pairs_lcm);
 }
References emit(), F, gb_elem::f, s_pair::first, freemem(), Monoid::from_expvector(), Monoid::from_varpower(), GBRing::gbvector_get_lead_monomial(), Monoid::gcd(), GR, MonomialIdeal::insert(), s_pair_heap::insert(), Monoid::is_one(), PolynomialRing::is_quotient_ring(), GBRing::is_skew_commutative(), Monoid::lcm(), M, M2_gbTrace, Monoid::make_one(), gb_elem::me, mi_stash, monideals, gbvector::monom, Nterm::monom, n_pairs, n_pairs_gcd, PolynomialRing::n_quotients(), GBRing::n_skew_commutative_vars(), Monoid::n_vars(), new_ring_pair(), new_s_pair(), newarray_atomic, newline, orig_syz, originalR, p, PolynomialRing::quotient_element(), FreeModule::rank(), Monoid::remove(), remove_pair(), s_pair::second, GBRing::skew_variable(), SPAIR_PAIR, spairs, buffer::str(), s_pair::syz_type, Monoid::to_expvector(), Monoid::to_varpower(), and VECTOR().