Macaulay2 Engine: gb2_comp::setup
setup()
void gb2_comp::setup (FreeModule * Fsyz, stash * mi_stash, gb_node * gens, int lodegree, int origsyz, int level, int strategy) private
Definition at line 11 of file res-a2-gb.cpp.
 {
   level = lev;
   int i;
   originalR = FFsyz->get_ring()->cast_to_PolynomialRing();
   if (originalR == NULL)
     {
       ERROR("internal error - ring is not a polynomial ring");
       assert(0);
     }
   GR = originalR->get_gb_ring();
   M = GR->get_flattened_monoid();
   K = GR->get_flattened_coefficients();
   mi_stash = mi_stash0;
   F = const_cast<FreeModule *>(ggens->output_free_module());
   gens = ggens;
   syz = NULL;
   Fsyz = const_cast<FreeModule *>(FFsyz);
   spairs = new s_pair_heap(M);
   n_gb = n_mingens = n_subring = 0;
   n_gb_first = 0;
   n_pairs = n_pairs_computed = 0;
   n_pairs_syz = n_pairs_usyz = 0;
   n_pairs_gb = n_pairs_zero = 0;
   n_pairs_gcd = n_pairs_hilb = 0;
   orig_syz = origsyz;  // Note: if orig_syz > 0, then Fsyz is
                        // completely set already.
   this_degree = lodeg;
   // We index into this using gbvector components (which are one greater than
   // the
   // FreeModule components
   monideals.push_back(0);
   for (i = 0; i < F->rank(); i++)
     {
       monideal_pair *p = new monideal_pair(originalR, mi_stash);
       monideals.push_back(p);
     }
   use_hilb = 0;
   hf_numgens_F = F->rank();
   hf_numgens_gb = 0;  // This will enable the initial computation of HF,
                       // if use_hilb is set.
   hf = hilb_comp::hilbertNumerator(F);
   n_gb_syz = 0;
   strategy_flags = strategy;
   state = STATE_GENS;
 }
References Ring::cast_to_PolynomialRing(), ERROR(), F, Fsyz, gens, GBRing::get_flattened_coefficients(), GBRing::get_flattened_monoid(), PolynomialRing::get_gb_ring(), FreeModule::get_ring(), GR, hf, hf_numgens_F, hf_numgens_gb, hilb_comp::hilbertNumerator(), K, level, M, mi_stash, monideals, n_gb, n_gb_first, n_gb_syz, n_mingens, n_pairs, n_pairs_computed, n_pairs_gb, n_pairs_gcd, n_pairs_hilb, n_pairs_syz, n_pairs_usyz, n_pairs_zero, n_subring, orig_syz, originalR, gb_node::output_free_module(), p, FreeModule::rank(), spairs, state, STATE_GENS, strategy_flags, syz, this_degree, and use_hilb.
Referenced by gb2_comp().