Macaulay2 Engine: gb2_comp::make_lead_term_matrix
make_lead_term_matrix()
Matrix * gb2_comp::make_lead_term_matrix () private
Definition at line 828 of file res-a2-gb.cpp.
 {
   MatrixConstructor result(F, gb.size());
   for (int i = 0; i < gb.size(); i++)
     {
       gb_elem *g = gb[i];
       gbvector *f = g->f;
       if (f == nullptr) continue;
       // Only grab the lead term, which should be non-null
       gbvector *fnext = f->next;
       f->next = nullptr;
       vec v = originalR->translate_gbvector_to_vec(F, f);
       f->next = fnext;
       result.set_column(i, v);
     }
   return result.to_matrix();
 }
References F, gb_elem::f, gb, gbvector::next, originalR, MatrixConstructor::set_column(), MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().
Referenced by hilbertNumerator().