Macaulay2 Engine: gb2_comp::new_ring_pair
new_ring_pair()
s_pair * gb2_comp::new_ring_pair (gb_elem * p, const int * lcm) private
Definition at line 118 of file res-a2-gb.cpp.
 {
   s_pair *result = new s_pair;
   result->next = nullptr;
   result->syz_type = SPAIR_RING;
   result->degree = M->primary_degree(lcm) + F->primary_degree(p->f->comp - 1);
   result->compare_num = 0;
   result->first = p;
   result->second = nullptr;
   result->f = nullptr;
   result->fsyz = nullptr;
   result->lcm = M->make_new(lcm);
   return result;
 }
References s_pair::compare_num, s_pair::degree, F, s_pair::f, s_pair::first, s_pair::fsyz, s_pair::lcm, M, Monoid::make_new(), s_pair::next, p, Monoid::primary_degree(), FreeModule::primary_degree(), s_pair::second, SPAIR_RING, and s_pair::syz_type.
Referenced by find_pairs().