Macaulay2 Engine: gb2_comp::schreyer_append
schreyer_append()
void gb2_comp::schreyer_append (gbvector * f) private
Definition at line 474 of file res-a2-gb.cpp.
 {
   if (orig_syz < 0)
     {
       monomial d = originalR->degree_monoid()->make_one();
       GR->gbvector_multidegree(F, f, d);
       Fsyz->append_schreyer(d, f->monom, Fsyz->rank());
       originalR->degree_monoid()->remove(d);
     }
 }
References FreeModule::append_schreyer(), Ring::degree_monoid(), F, Fsyz, GBRing::gbvector_multidegree(), GR, Monoid::make_one(), gbvector::monom, orig_syz, originalR, FreeModule::rank(), and Monoid::remove().
Referenced by calc_gb().