Macaulay2 Engine: ExponentListIterator::exponent
exponent()
template<class E , bool L> Exponent ExponentListIterator< E, L >::exponent () inline
Definition at line 223 of file ExponentList.hpp.
 { return loc[1]; }
References ExponentListIterator< E, L >::loc.
Referenced by ExponentList< E, L >::divides(), ExponentList< E, L >::elem_text_out(), ExponentList< E, L >::erase(), ExponentList< E, L >::gcd(), ExponentList< E, L >::lcm(), ExponentList< E, L >::monsyz(), ExponentList< E, L >::mult(), popular_var(), and ExponentList< E, L >::quotient().