Macaulay2 Engine: ExponentListIterator::valid
valid()
template<class E , bool L> bool ExponentListIterator< E, L >::valid () inline
Definition at line 218 of file ExponentList.hpp.
 { return loc < hi; }
References ExponentListIterator< E, L >::hi, and ExponentListIterator< E, L >::loc.
Referenced by MinimalPrimes::alg1_min_primes(), AssociatedPrimes::ass_prime_generator(), MinimalPrimes::ass_prime_generator(), ExponentList< E, L >::computeHashValue(), convertToFactory(), Monoid::degree_of_varpower(), ExponentList< E, L >::divides(), hilb_comp::do_ideal(), ExponentList< E, L >::elem_text_out(), ExponentList< E, L >::erase(), RingMap::eval_term(), MonomialInfo::from_varpower_monomial(), ResMonoidDense::from_varpower_monomial(), ResMonoidSparse::from_varpower_monomial(), ExponentList< E, L >::gcd(), F4MonomialLookupTableT< Key >::insert1(), ResF4MonomialLookupTableT< Key >::insert1(), ExponentList< E, L >::lcm(), partition_table::merge_in(), ExponentList< E, L >::monsyz(), ExponentList< E, L >::mult(), popular_var(), ExponentList< E, L >::quotient(), ExponentList< E, L >::radical(), reduce_exp(), ExponentList< E, L >::simple_degree(), ExponentList< E, L >::to_expvector(), varpower_monideal(), and ExponentList< E, L >::weight().