Macaulay2 Engine: PolyRing::multi_degree
multi_degree()
bool PolyRing::multi_degree (const ring_elem f, monomial d) const virtual
Implements PolynomialRing.
Definition at line 541 of file poly.cpp.
 {
   auto D = degree_monoid();
   if (begin(f) == end(f) || M_->n_vars() == 0)
     {
       D->one(degf);
       return true;
     }
   bool result = true;
   Nterm& t = *begin(f);
   M_->multi_degree(t.monom, degf);
   for (Nterm& t : f)
     {
       auto e = D->make_one();
       M_->multi_degree(t.monom, e);
       if (EQ != D->compare(degf, e))
         {
           result = false;
           D->lcm(degf, e, degf);
         }
     }
   // for (int i = 0; i < D->monomial_size(); i++)
   //   std::cout << degf[i] << " , ";
   // std::cout << std::endl;
   return result;
 }
References begin(), Ring::degree_monoid(), end(), EQ, PolynomialRing::M_, Nterm::monom, Monoid::multi_degree(), and Monoid::n_vars().
Referenced by LocalRing::multi_degree().