Macaulay2 Engine: PolyRing::sort
sort()
void PolyRing::sort (Nterm *& f) const
Definition at line 2062 of file poly.cpp.
{
  // Divide f into two lists of equal length, sort each,
  // then add them together.  This allows the same monomial
  // to appear more than once in 'f'.
  if (f == nullptr || f->next == nullptr) return;
  Nterm *f1 = nullptr;
  Nterm *f2 = nullptr;
  while (f != nullptr)
    {
      Nterm *t = f;
      f = f->next;
      t->next = f1;
      f1 = t;
      if (f == nullptr) break;
      t = f;
      f = f->next;
      t->next = f2;
      f2 = t;
    }
  sort(f1);
  sort(f2);
  ring_elem g = f1;
  ring_elem h = f2;
  add_to(g, h);
  f = g;
}
References Ring::add_to(), Nterm::next, and sort().
Referenced by divide_by_expvector(), homogenize(), SchurRing::mult_by_term(), and sort().