Macaulay2 Engine: PolyRing::compare_elems
compare_elems()
int PolyRing::compare_elems (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 498 of file poly.cpp.
 {
   int cmp;
   Nterm *a = f;
   Nterm *b = g;
   for (;; a = a->next, b = b->next)
     {
       if (a == nullptr)
         {
           if (b == nullptr) return 0;
           return -1;
         }
       if (b == nullptr) return 1;
       if (nvars_ > 0)
         {
           cmp = M_->compare(a->monom, b->monom);
           if (cmp != 0) return cmp;
         }
       cmp = K_->compare_elems(a->coeff, b->coeff);
       if (cmp != 0) return cmp;
     }
 }
References Nterm::coeff, Monoid::compare(), Ring::compare_elems(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, Nterm::next, and PolynomialRing::nvars_.
Referenced by LocalRing::compare_elems().