Macaulay2 Engine: PolyRing::create
create()
const PolyRing * PolyRing::create (const Ring * K, const Monoid * M) static
Definition at line 101 of file poly.cpp.
 {
   PolyRing *R = new PolyRing;
   R->initialize_poly_ring(K, M);
   R->gb_ring_ = GBRing::create_PolynomialRing(K, M);
   return R;
 }
References GBRing::create_PolynomialRing(), PolynomialRing::gb_ring_, initialize_poly_ring(), and PolyRing().
Referenced by degreeRing(), IM2_Ring_polyring(), simplePolynomialRing(), and TEST().