Macaulay2 Engine: PolyRing::power_direct
power_direct()
ring_elem PolyRing::power_direct (const ring_elem f, int n) const protected
Definition at line 856 of file poly.cpp.
 {
     ring_elem result, g, rest, h, tmp;
     ring_elem coef1, coef2, coef3;
     Nterm *lead = ff;
     if (lead == nullptr) return ZERO_RINGELEM;
     rest = lead->next;
     g = from_long(1);
     // Start the result with the n th power of the lead term
     Nterm *t = new_term();
     t->coeff = K_->power(lead->coeff, n);
     M_->power(lead->monom, n, t->monom);
     t->next = nullptr;
     //  if (_base_ring != NULL) normal_form(t);  NOT NEEDED
     result = t;
     if (POLY(rest) == nullptr) return result;
     monomial m = M_->make_one();
     mpz_t bin_c;
     mpz_init_set_ui(bin_c, 1);
     for (int i = 1; i <= n; i++)
     {
         tmp = mult(g, rest);
         g = tmp;
         mpz_mul_ui(bin_c, bin_c, n - i + 1);
         mpz_fdiv_q_ui(bin_c, bin_c, i);
         coef1 = K_->from_int(bin_c);
         if (!K_->is_zero(coef1))
         {
             coef2 = K_->power(lead->coeff, n - i);
             coef3 = K_->mult(coef1, coef2);
             M_->power(lead->monom, n - i, m);
             h = mult_by_term(g, coef3, m);
             add_to(result, h);
         }
     }
     mpz_clear(bin_c);
     return result;
 }
References Ring::add_to(), Nterm::coeff, Ring::from_int(), from_long(), Ring::is_zero(), PolynomialRing::K_, PolynomialRing::M_, Monoid::make_one(), Nterm::monom, mult(), Ring::mult(), mult_by_term(), new_term(), Nterm::next, POLY, Ring::power(), Monoid::power(), and ZERO_RINGELEM.
Referenced by power().