Macaulay2 Engine: PolyRing::add
add()
ring_elem PolyRing::add (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 753 of file poly.cpp.
 {
   ring_elem a = copy(f);
   ring_elem b = copy(g);
   internal_add_to(a, b);
   return a;
 }
References copy(), and internal_add_to().
Referenced by LocalRing::add().