Macaulay2 Engine: PolyRing::diff_term
diff_term()
ring_elem PolyRing::diff_term (const_monomial m, const_monomial n, monomial resultmon, int use_coeff) const protected
Definition at line 2022 of file poly.cpp.
 {
   int sign = 0;
   if (!M_->divides(m, n)) return K_->from_long(0);
   if (is_skew_ && use_coeff)
     {
       exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
       exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
       exponents_t EXP3 = ALLOCATE_EXPONENTS(exp_size);
       M_->to_expvector(m, EXP1);
       M_->to_expvector(n, EXP2);
       sign = skew_.diff(EXP1, EXP2, EXP3);
       M_->from_expvector(EXP3, resultmon);
     }
   else
     M_->divide(n, m, resultmon);
   ring_elem result = K_->from_long(1);
   if (!use_coeff) return result;
   gc_vector<int> e1(n_vars()), e2(n_vars());
   exponents_t exp1 = e1.data();
   exponents_t exp2 = e2.data();
   M_->to_expvector(m, exp1);
   M_->to_expvector(n, exp2);
   if (is_skew_ && sign < 0) K_->negate_to(result);
   for (int i = 0; i < n_vars(); i++)
     {
       for (int j = exp1[i] - 1; j >= 0; j--)
         {
           ring_elem g = K_->from_long(exp2[i] - j);
           K_->mult_to(result, g);
           if (K_->is_zero(result)) return result;
         }
     }
   return result;
 }
References ALLOCATE_EXPONENTS, SkewMultiplication::diff(), Monoid::divide(), Monoid::divides(), mpfr::exp2(), PolynomialRing::exp_size, Monoid::from_expvector(), Ring::from_long(), PolynomialRing::is_skew_, Ring::is_zero(), PolynomialRing::K_, PolynomialRing::M_, Ring::mult_to(), PolynomialRing::n_vars(), Ring::negate_to(), PolynomialRing::skew_, and Monoid::to_expvector().
Referenced by diff().