Macaulay2 Engine: PolyRing::initialize_poly_ring
initialize_poly_ring() [2/2]
void PolyRing::initialize_poly_ring (const Ring * K, const Monoid * M, const PolynomialRing * deg_ring) private
Definition at line 72 of file poly.cpp.
 {
   initialize_ring(K->characteristic(), deg_ring, M->get_heft_vector());
   initialize_PolynomialRing(K, M, this, this, NULL);
   poly_size_ = sizeof(Nterm) + sizeof(int) * (M_->monomial_size() - 1);
   gb_ring_ = 0;
   // A polynomial ring is ALWAYS graded (if the coeff vars, if any,
   //   all have degree 0, which is the case with our flattened poly rings
   this->setIsGraded(true);
   exp_size = EXPONENT_BYTE_SIZE(nvars_);
   zeroV = from_long(0);
   oneV = from_long(1);
   minus_oneV = from_long(-1);
 }
References Ring::characteristic(), PolynomialRing::exp_size, EXPONENT_BYTE_SIZE, from_long(), PolynomialRing::gb_ring_, Monoid::get_heft_vector(), PolynomialRing::initialize_PolynomialRing(), Ring::initialize_ring(), PolynomialRing::M_, Ring::minus_oneV, Monoid::monomial_size(), PolynomialRing::nvars_, Ring::oneV, PolynomialRing::poly_size_, PolynomialRing::setIsGraded(), and Ring::zeroV.
Referenced by SchurRing::create(), create(), SolvableAlgebra::create(), WeylAlgebra::create(), SkewPolynomialRing::create(), initialize_poly_ring(), and make_trivial_ZZ_poly_ring().