Macaulay2 Engine: PolyRing::zeroize_tiny
zeroize_tiny()
ring_elem PolyRing::zeroize_tiny (gmp_RR epsilon, const ring_elem f) const virtual
Reimplemented from Ring.
Definition at line 1355 of file poly.cpp.
 {
   Nterm head;
   Nterm *result = &head;
   for (Nterm& a : f)
     {
       ring_elem c = K_->zeroize_tiny(epsilon, a.coeff);
       if (!K_->is_zero(c))
         {
           result->next = new_term();
           result = result->next;
           result->coeff = c;
           M_->copy(a.monom, result->monom);
         }
     }
   result->next = nullptr;
   return head.next;
 }
References Nterm::coeff, Monoid::copy(), Ring::is_zero(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, new_term(), Nterm::next, and Ring::zeroize_tiny().