Macaulay2 Engine: PolyRing::invert
invert()
ring_elem PolyRing::invert (const ring_elem f) const virtual
Implements Ring.
Definition at line 950 of file poly.cpp.
 {
   Nterm *ft = f;
   if (is_zero(f))
     {
       ERROR("cannot divide by zero");
       return ZERO_RINGELEM;
     }
   if (ft->next == NULL)
     {
       if (M_->is_one(ft->monom))
         {
           Nterm *t = new_term();
           t->coeff = K_->invert(ft->coeff);
           M_->one(t->monom);
           return t;
         }
       else if (M_->is_invertible(ft->monom))
         {
           Nterm *t = new_term();
           t->coeff = K_->invert(ft->coeff);
           M_->power(ft->monom, -1, t->monom);
           return t;
         }
     }
   ERROR("element is not invertible in this ring");
   return ZERO_RINGELEM;
 }
References Nterm::coeff, ERROR(), Ring::invert(), Monoid::is_invertible(), Monoid::is_one(), is_zero(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, new_term(), Nterm::next, Monoid::one(), Monoid::power(), and ZERO_RINGELEM.
Referenced by LocalRing::lift(), and power().