Macaulay2 Engine: PolyRing::make_flat_term
make_flat_term()
ring_elem PolyRing::make_flat_term (const ring_elem a, const_monomial m) const virtual
Implements PolynomialRing.
Definition at line 1951 of file poly.cpp.
 {
   if (K_->is_zero(a)) return ZERO_RINGELEM;
   Nterm *t = new_term();
   t->coeff = K_->copy(a);
   M_->copy(m, t->monom);
   t->next = NULL;
   return t;
 }
References Nterm::coeff, Ring::copy(), Monoid::copy(), Ring::is_zero(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, new_term(), Nterm::next, and ZERO_RINGELEM.
Referenced by make_logical_term(), power(), and random().