Macaulay2 Engine: PolyRing::from_complex_double
from_complex_double()
bool PolyRing::from_complex_double (double re, double im, ring_elem & result) const virtual
Reimplemented from Ring.
Definition at line 273 of file poly.cpp.
 {
   ring_elem a;
   if (!K_->from_complex_double(re, im, a))
     {
       result = ZERO_RINGELEM;
       return false;
     }
   result = fromCoefficient(a);
   return true;
 }
References Ring::from_complex_double(), fromCoefficient(), PolynomialRing::K_, and ZERO_RINGELEM.
Referenced by PolyRingQuotient::from_complex_double().