Macaulay2 Engine: PolyRing::gcd
gcd()
ring_elem PolyRing::gcd (const ring_elem f, const ring_elem g) const
Definition at line 1048 of file poly.cpp.
 {
   if (nvars_ != 1)
     {
       ERROR("multivariate gcd not yet implemented");
       return ZERO_RINGELEM;
     }
   ring_elem f = copy(ff);
   ring_elem g = copy(gg);
   ring_elem s, rem;
   while (!is_zero(g))
     {
       rem = remainderAndQuotient(f, g, s);
       f = g;
       g = rem;
     }
 #if 0
 // #warning commented out make monic in gcd
 //   make_monic(f);
 #endif
   return f;
 }
References copy(), ERROR(), is_zero(), PolynomialRing::nvars_, mpfr::rem(), remainderAndQuotient(), and ZERO_RINGELEM.