Macaulay2 Engine: PolyRing::diff
diff()
ring_elem PolyRing::diff (ring_elem a, ring_elem b, int use_coeff) const virtual
Implements PolynomialRing.
Definition at line 1999 of file poly.cpp.
 {
   polyheap H(this);
   Nterm *d = new_term();
   for (Nterm& s : a)
     {
       for (Nterm& t : b)
         {
           d->coeff = diff_term(s.monom, t.monom, d->monom, use_coeff);
           if (!K_->is_zero(d->coeff))
             {
               K_->mult_to(d->coeff, s.coeff);
               K_->mult_to(d->coeff, t.coeff);
               d->next = nullptr;
               H.add(d);
               d = new_term();
             }
         }
     }
   return H.value();
 }
References polyheap::add(), Nterm::coeff, diff_term(), Ring::is_zero(), PolynomialRing::K_, Nterm::monom, Ring::mult_to(), new_term(), Nterm::next, and polyheap::value().