Macaulay2 Engine: PolyRing::translate_gbvector_from_vec_QQ
translate_gbvector_from_vec_QQ()
gbvector * PolyRing::translate_gbvector_from_vec_QQ (const FreeModule * F, const vec v, ring_elem & result_denominator) const
Definition at line 2489 of file poly.cpp.
 {
   if (v == nullptr)
     {
       result_denominator = globalZZ->one();
       return nullptr;
     }
   GBRing *GR = get_gb_ring();
   result_denominator = vec_get_denominator_QQ(v);
   gbvectorHeap H(GR, F);
   gbvector head;
   gbvector *inresult;
   mpz_t a;
   mpz_init(a);
   for (vec w = v; w != nullptr; w = w->next)
     {
       inresult = &head;
       int comp = w->comp + 1;
       for (Nterm& t : w->coeff)
         {
           // make a gbvector node.
           mpq_srcptr b = MPQ_VAL(t.coeff);
           mpz_mul(a, result_denominator.get_mpz(), mpq_numref(b));
           mpz_divexact(a, a, mpq_denref(b));
           gbvector *g = GR->gbvector_term(
               F, globalZZ->RingZZ::from_int(a), t.monom, comp);
           inresult->next = g;
           inresult = inresult->next;
         }
       H.add(head.next);
     }
   mpz_clear(a);
   return H.value();
 }
References gbvectorHeap::add(), Nterm::coeff, gbvector::comp, GBRing::gbvector_term(), PolynomialRing::get_gb_ring(), ring_elem::get_mpz(), globalZZ, Nterm::monom, MPQ_VAL, gbvector::next, Ring::one(), gbvectorHeap::value(), and vec_get_denominator_QQ().
Referenced by translate_gbvector_from_vec().