Macaulay2 Engine: PolyRing::is_homogeneous
is_homogeneous()
bool PolyRing::is_homogeneous (const ring_elem f) const virtual
Implements PolynomialRing.
Definition at line 521 of file poly.cpp.
 {
   if (!is_graded()) return false;
   if (begin(f) == end(f)) return true;
   auto D = degree_monoid();
   auto degf = D->make_one();
   Nterm& t = *begin(f);
   M_->multi_degree(t.monom, degf);
   for (Nterm& t : f)
     {
       auto e = D->make_one();
       M_->multi_degree(t.monom, e);
       if (EQ != D->compare(degf, e))
         return false;
     }
   return true;
 }
References begin(), Ring::degree_monoid(), end(), EQ, PolynomialRing::is_graded(), PolynomialRing::M_, Nterm::monom, and Monoid::multi_degree().
Referenced by LocalRing::is_homogeneous(), and PolynomialRing::setQuotientInfo().