Macaulay2 Engine: PolyRing::mult
mult()
ring_elem PolyRing::mult (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 809 of file poly.cpp.
 {
   polyheap H(this);
   for (Nterm& a : f)
     H.add(mult_by_term(g, a.coeff, a.monom));
   return H.value();
 }
References polyheap::add(), mult_by_term(), and polyheap::value().
Referenced by LocalRing::add(), LocalRing::divide(), LocalRing::lift(), LocalRing::lift_up(), LocalRing::mult(), power(), SchurRing::power(), power_direct(), and LocalRing::subtract().