Macaulay2 Engine: PolyRing::new_term
new_term()
Nterm * PolyRing::new_term () const protected
Definition at line 146 of file poly.cpp.
 {
   Nterm *result = GETMEM(Nterm *, poly_size_);
   result->next = nullptr;
   result->coeff = 0;  // This value is never used, one hopes...
   // In fact, it gets used in the line below:       K->remove(tmp->coeff);
   // which is called from the line below:           remove(idiotic);
   // and it crashes there, because this assignment only sets the integer
   // part of the union, so on a machine with 4 byte ints and 8 byte pointers,
   // the
   // pointer part is not NULL!
   result->coeff.poly_val = nullptr;  // so I added this line
   return result;
 }
References Nterm::coeff, GETMEM, Nterm::next, PolynomialRing::poly_size_, and ring_elem::poly_val.
Referenced by SkewPolynomialRing::antipode(), MatrixStream::appendTermDone(), copy_term(), ChineseRemainder::CRA(), diff(), divide_by_expvector(), divide_by_given_content(), division_algorithm(), from_int(), from_long(), from_rational(), fromCoefficient(), fromSmallIntegerCoefficients(), get_logical_coeff(), homogenize(), invert(), lead_term(), make_flat_term(), make_logical_term(), negate(), power_direct(), powerseries_division_algorithm(), preferred_associate(), ChineseRemainder::ratConversion(), SchurRing::SM(), translate_gbvector_to_vec(), translate_gbvector_to_vec_QQ(), var(), and zeroize_tiny().