Macaulay2 Engine: PolyRing::lead_logical_exponents
lead_logical_exponents()
void PolyRing::lead_logical_exponents (int nvars0, const ring_elem f, exponents_t result_exp) const virtual
Implements PolynomialRing.
Definition at line 1735 of file poly.cpp.
 {
   Nterm *g = f;
   assert(g != NULL);
   exponents_t exp = newarray_atomic(int, n_vars());
   M_->to_expvector(g->monom, exp);
   exponents::copy(nvars0, exp, result_exp);
 }
References ExponentVector< E, OC >::copy(), mpfr::exp(), PolynomialRing::M_, Nterm::monom, PolynomialRing::n_vars(), newarray_atomic, and Monoid::to_expvector().
Referenced by lift().