Macaulay2 Engine: PolyRing::internal_subtract_to
internal_subtract_to()
void PolyRing::internal_subtract_to (ring_elem & f, ring_elem & g) const
Definition at line 733 of file poly.cpp.
 {
   internal_negate_to(g);
   internal_add_to(f, g);
 }
References internal_add_to(), and internal_negate_to().
Referenced by sagbi::subduct(), and sagbi::subduct1().