Macaulay2 Engine: PolyRing::homogenize
homogenize() [2/2]
ring_elem PolyRing::homogenize (const ring_elem f, int v, int deg, const std::vector< int > & wts) const virtual
Implements PolynomialRing.
Definition at line 591 of file poly.cpp.
{
  // assert(wts[v] != 0);
  // If an error occurs, then return 0, and set gError.
  exponents_t exp = newarray_atomic(int, nvars_);
  Nterm head;
  Nterm *result = &head;
  for (Nterm& a : f)
    {
      M_->to_expvector(a.monom, exp);
      auto e = exponents::weight(n_vars(), exp, wts);
      if (((d - e) % wts[v]) != 0)
        {
          // We cannot homogenize, so clean up and exit.
          result->next = nullptr;
          ERROR("homogenization impossible");
          result = nullptr;
          return result;
        }
      exp[v] += (d - e) / wts[v];
      if (is_skew_ && skew_.is_skew_var(v) && exp[v] > 1) continue;
      result->next = new_term();
      result = result->next;
      result->coeff = K_->copy(a.coeff);
      M_->from_expvector(exp, result->monom);
    }
  result->next = nullptr;
  sort(head.next);  // The monomial order, etc. might all have changed.
                    // Some terms might even drop out
  freemem(exp);
  return head.next;
}
References Nterm::coeff, Ring::copy(), ERROR(), freemem(), Monoid::from_expvector(), PolynomialRing::is_skew_, SkewMultiplication::is_skew_var(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, PolynomialRing::n_vars(), new_term(), newarray_atomic, Nterm::next, PolynomialRing::nvars_, PolynomialRing::skew_, sort(), Monoid::to_expvector(), and ExponentVector< E, OC >::weight().
Referenced by LocalRing::homogenize(), homogenize(), and LocalRing::homogenize().