Macaulay2 Engine: PolyRing::text_out
text_out()
void PolyRing::text_out (buffer & o) const virtual
Implements PolynomialRing.
Reimplemented in WeylAlgebra, SkewPolynomialRing, and SchurRing.
Definition at line 140 of file poly.cpp.
 {
   K_->text_out(o);
   M_->text_out(o);
 }
References PolynomialRing::K_, PolynomialRing::M_, Monoid::text_out(), and Ring::text_out().
Referenced by LocalRing::text_out(), and PolyRingQuotient::text_out().