Macaulay2 Engine: PolyRing::power
power() [1/2]
ring_elem PolyRing::power (const ring_elem f, int n) const virtual
Reimplemented from Ring.
Reimplemented in WeylAlgebra, SolvableAlgebra, SkewPolynomialRing, and SchurRing.
Definition at line 906 of file poly.cpp.
 {
   ring_elem ff;
   if (n > 0)
     ff = f0;
   else if (n < 0)
   {
     ff = invert(f0);
     n = -n;
   }
   else
     return from_long(1);
   if(!characteristic())
   {
     return power_direct(ff, n);
   }
   else
   {
     long p=characteristic(), pk=1;
     ring_elem result = from_long(1);
     ring_elem gg = copy(ff), temp; // no need to copy, just the correct number of terms
     while(n)
     {
       for(Nterm *it=ff, *jt=gg; it!=nullptr; it=it->next, jt=jt->next)
       {
         jt->coeff = K_->power(it->coeff, pk);
         M_->power(it->monom, pk, jt->monom);
       }
       temp = power_direct(gg, n%p);
       result = mult(result, temp);
       pk *= p;
       n /= p;
     }
     return result;
   }
 }
References Ring::characteristic(), copy(), from_long(), invert(), PolynomialRing::K_, PolynomialRing::M_, mult(), p, Ring::power(), Monoid::power(), and power_direct().