Macaulay2 Engine: PolyRing::fromCoefficient
fromCoefficient()
ring_elem PolyRing::fromCoefficient (ring_elem & coeff) const
Definition at line 213 of file poly.cpp.
 {
   Nterm *result;
   if (K_->is_zero(coeff))
     {
       result = ZERO_RINGELEM;
       return result;
     }
   result = new_term();
   result->coeff = coeff;
   M_->one(result->monom);
   return result;
 }
References Nterm::coeff, Ring::is_zero(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, new_term(), Monoid::one(), and ZERO_RINGELEM.
Referenced by from_BigComplex(), from_BigReal(), from_complex_double(), from_double(), and from_Interval().