Macaulay2 Engine: PolyRing::is_equal
is_equal()
bool PolyRing::is_equal (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 481 of file poly.cpp.
 {
   Nterm *a = f;
   Nterm *b = g;
   for (;; a = a->next, b = b->next)
     {
       if (a == nullptr)
         {
           if (b == nullptr) return true;
           return false;
         }
       if (b == nullptr) return false;
       if (!K_->is_equal(a->coeff, b->coeff)) return false;
       if (nvars_ > 0 && (M_->compare(a->monom, b->monom) != 0)) return false;
     }
 }
References Nterm::coeff, Monoid::compare(), Ring::is_equal(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, Nterm::next, and PolynomialRing::nvars_.
Referenced by LocalRing::add(), LocalRing::elem_text_out(), LocalRing::is_equal(), LocalRing::lift(), LocalRing::simplify(), LocalRing::subtract(), and syzygy().