Macaulay2 Engine: PolyRing::eval
eval()
ring_elem PolyRing::eval (const RingMap * map, const ring_elem f, int first_var) const virtual
Implements Ring.
Definition at line 1334 of file poly.cpp.
 {
   // The way we collect the result depends on whether the target ring
   // is a polynomial ring: if so, use a heap structure.  If not, just add to the
   // result.
   gc_vector<int> vp;
   const Ring *target = map->get_ring();
   SumCollector *H = target->make_SumCollector();
   for (Nterm& t : f)
     {
       M_->to_varpower(t.monom, vp);
       H->add(map->eval_term(K_, t.coeff, vp.data(), first_var, n_vars()));
     }
   ring_elem result = H->getValue();
   delete H;
   return result;
 }
References SumCollector::add(), RingMap::eval_term(), RingMap::get_ring(), SumCollector::getValue(), PolynomialRing::K_, PolynomialRing::M_, Ring::make_SumCollector(), PolynomialRing::n_vars(), and Monoid::to_varpower().
Referenced by LocalRing::eval(), sagbi::subduct(), and sagbi::subduct1().