Macaulay2 Engine: PolyRing::fromSmallIntegerCoefficients
fromSmallIntegerCoefficients()
ring_elem PolyRing::fromSmallIntegerCoefficients (const std::vector< long > & coeffs, int var) const
Definition at line 2234 of file poly.cpp.
 {
   // create a poly
   SumCollector *H = make_SumCollector();
   exponents_t exp = ALLOCATE_EXPONENTS(EXPONENT_BYTE_SIZE(
       n_vars()));  // deallocates automatically at end of block
   exponents::one(n_vars(), exp);
   for (long i = 0; i < coeffs.size(); i++)
     {
       exp[var] = static_cast<int>(i);
       ring_elem c = K_->from_long(coeffs[i]);
       if (K_->is_zero(c)) continue;
       Nterm *t = new_term();
       t->coeff = c;
       t->next = nullptr;
       M_->from_expvector(exp, t->monom);
       H->add(t);
     }
   ring_elem result = H->getValue();
   delete H;
   return result;
 }
References SumCollector::add(), ALLOCATE_EXPONENTS, Nterm::coeff, mpfr::exp(), EXPONENT_BYTE_SIZE, Monoid::from_expvector(), Ring::from_long(), SumCollector::getValue(), Ring::is_zero(), PolynomialRing::K_, PolynomialRing::M_, PolynomialRing::make_SumCollector(), Nterm::monom, PolynomialRing::n_vars(), new_term(), Nterm::next, ExponentVector< E, OC >::one(), and var().
Referenced by M2::ARingGFFlintBig::lift_to_original_ring(), and M2::ARingGFFlint::lift_to_original_ring().