Macaulay2 Engine: PolyRing::vec_lead_term
vec_lead_term()
vec PolyRing::vec_lead_term (int nparts, const FreeModule * F, vec v) const virtual
Implements PolynomialRing.
Definition at line 2316 of file poly.cpp.
 {
   // The first step is to find the lead monomial.
   if (v == nullptr) return nullptr;
   const vecterm *lead = vec_locate_lead_term(F, v);
   // Now that we have the lead term, use the first n parts of the monomial
   // ordering
   ring_elem r = PolyRing::lead_term(nparts, lead->coeff);
   return make_vec(lead->comp, r);
 }
References vec::coeff, vec::comp, lead_term(), Ring::make_vec(), and vec_locate_lead_term().