Macaulay2 Engine: PolyRing::get_logical_coeff
get_logical_coeff()
ring_elem PolyRing::get_logical_coeff (const Ring * coeffR, const Nterm *& f) const protected
Definition at line 1689 of file poly.cpp.
 {
   if (f == nullptr) return coeffR->zero();
   if (coeffR == K_)
     {
       ring_elem result = f->coeff;
       f = f->next;
       return result;
     }
   const PolynomialRing *KR = coeffR->cast_to_PolynomialRing();
   assert(KR);
   const PolyRing *K = KR->getNumeratorRing();
   Nterm head;
   Nterm *inresult = &head;
   inresult->next = nullptr;
   exponents_t exp = newarray_atomic(int, n_vars());
   exponents_t exp2 = newarray_atomic(int, n_vars());
   int nvars = n_vars() - K->n_vars();
   M_->to_expvector(f->monom, exp);
   exponents::copy(n_vars(), exp, exp2);
   do
     {
       Nterm *t = K->new_term();
       inresult->next = t;
       inresult = t;
       t->coeff = f->coeff;
       K->getMonoid()->from_expvector(exp2 + nvars, t->monom);
       f = f->next;
       if (f == nullptr) break;
       M_->to_expvector(f->monom, exp2);
     }
   while (EQ == exponents::lex_compare(nvars, exp, exp2));
   inresult->next = nullptr;
   return head.next;
 }
References PolynomialRing::cast_to_PolynomialRing(), Nterm::coeff, ExponentVector< E, OC >::copy(), EQ, mpfr::exp(), mpfr::exp2(), Monoid::from_expvector(), PolynomialRing::getMonoid(), PolynomialRing::getNumeratorRing(), ExponentVector< E, OC >::lex_compare(), Nterm::monom, PolynomialRing::n_vars(), new_term(), newarray_atomic, and Nterm::next.
Referenced by get_coeff(), lead_logical_coeff(), and list_form().