Macaulay2 Engine: PolyRing::mult_by_term
mult_by_term()
ring_elem PolyRing::mult_by_term (const ring_elem f, const ring_elem c, const_monomial m) const virtual
Implements PolynomialRing.
Reimplemented in WeylAlgebra, SolvableAlgebra, SkewPolynomialRing, and SchurRing.
Definition at line 769 of file poly.cpp.
 {
   Nterm head;
   Nterm *result = &head;
   for (Nterm& a : f)
     {
       result->next = new_term();
       result = result->next;
       result->coeff = K_->mult(a.coeff, c);
       M_->mult(m, a.monom, result->monom);
     }
   result->next = NULL;
   return head.next;
 }
References Nterm::coeff, Nterm::monom, and Nterm::next.
Referenced by convolve(), division_algorithm_with_laurent_variables(), imp_subtract_multiple_to(), mult(), PolyRingQuotient::mult_by_term(), power_direct(), QRingInfo_field_basic::reduce_lead_term_basic_field(), and QRingInfo_field_QQ::reduce_lead_term_QQ().