Macaulay2 Engine: PolyRing::list_form
list_form()
engine_RawArrayPairOrNull PolyRing::list_form (const Ring * coeffR, const ring_elem f) const virtual
Implements PolynomialRing.
Definition at line 1777 of file poly.cpp.
 {
   // Either coeffR should be the actual coefficient ring (possible a "toField"ed
   // ring)
   // or a polynomial ring.  If not, NULL is returned and an error given
   // In the latter case, the last set of variables are part of
   // the coefficients.
   int nvars0 = check_coeff_ring(coeffR, this);
   if (nvars0 < 0) return nullptr;
   int n = n_logical_terms(nvars0, f);
   engine_RawMonomialArray monoms =
       GETMEM(engine_RawMonomialArray, sizeofarray(monoms, n));
   engine_RawRingElementArray coeffs =
       GETMEM(engine_RawRingElementArray, sizeofarray(coeffs, n));
   monoms->len = n;
   coeffs->len = n;
   engine_RawArrayPair result = newitem(struct engine_RawArrayPair_struct);
   result->monoms = monoms;
   result->coeffs = coeffs;
   exponents_t exp = newarray_atomic(int, n_vars());
   gc_vector<int> resultvp;
   const Nterm *t = f;
   for (int next = 0; next < n; next++)
     {
       getMonoid()->to_expvector(t->monom, exp);
       ring_elem c =
           get_logical_coeff(coeffR, t);  // increments t to the next term of f.
       varpower::from_expvector(nvars0, exp, resultvp);
       monoms->array[next] = EngineMonomial::make(resultvp.data());
       coeffs->array[next] = RingElement::make_raw(coeffR, c);
       resultvp.resize(0);
       assert(monoms->array[next] != NULL);
       assert(coeffs->array[next] != NULL);
     }
   freemem(exp);
   return result;
 }
References check_coeff_ring(), mpfr::exp(), freemem(), ExponentList< E, L >::from_expvector(), get_logical_coeff(), GETMEM, PolynomialRing::getMonoid(), EngineMonomial::make(), RingElement::make_raw(), Nterm::monom, n_logical_terms(), PolynomialRing::n_vars(), newarray_atomic, newitem, sizeofarray, and Monoid::to_expvector().