Macaulay2 Engine: PolyRing::division_algorithm_with_laurent_variables
division_algorithm_with_laurent_variables()
Nterm * PolyRing::division_algorithm_with_laurent_variables (Nterm * f, Nterm * g, Nterm *& quot) const protected
Definition at line 1410 of file poly.cpp.
 {
   // Step 1: replace f with f1, m1 (f = m1 * f1, f1 has only exponents >= 0, and no monomial factors)
   // Same: g = n1 * g1.
   // then if f1 = q * g1 + r, (q, r polynomials with only non-negative exponents)
   // then f = (q*m1*n1^(-1)) * g + m1*r
   //std::pair<Nterm*, int*> factor_out_inverse_variables(f);
   auto expf = setNegativeExponentMonomial(f);
   auto expg = setNegativeExponentMonomial(g);
   monomial m = getMonoid()->make_one();
   monomial n = getMonoid()->make_one();
   getMonoid()->from_expvector(expf.data(), m);
   getMonoid()->from_expvector(expg.data(), n);
   for (auto& a : expf) a = -a;
   for (auto& a : expg) a = -a;
   monomial minv = getMonoid()->make_one();
   monomial ninv = getMonoid()->make_one();
   getMonoid()->from_expvector(expf.data(), minv);
   getMonoid()->from_expvector(expg.data(), ninv);
   for (int i=0; i<n_vars(); ++i)
     expf[i] = -expf[i] + expg[i];
   monomial mninv = getMonoid()->make_one();
   getMonoid()->from_expvector(expf.data(), mninv);
   ring_elem c = getCoefficientRing()->from_long(1);
   Nterm* f1 = mult_by_term(f, c, minv); // f1 = m^-1 * f, m only involves the variables which allow negative exponents
   Nterm* g1 = mult_by_term(g, c, ninv); // g1 = n^-1 * g.
   Nterm* quot1 = nullptr;
   Nterm* rem1 = division_algorithm(f1, g1, quot1);
   Nterm* rem = mult_by_term(rem1, c, m);
   quot = mult_by_term(quot1, c, mninv);
   return rem;
 }
References division_algorithm(), Monoid::from_expvector(), Ring::from_long(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), Monoid::make_one(), mult_by_term(), PolynomialRing::n_vars(), mpfr::rem(), and setNegativeExponentMonomial().
Referenced by remainderAndQuotient().