Macaulay2 Engine: PolyRing::get_coeff
get_coeff()
ring_elem PolyRing::get_coeff (const Ring * coeffR, const ring_elem f, const_varpower vp) const virtual
Implements PolynomialRing.
Definition at line 1986 of file poly.cpp.
 {
   int nvars0 = check_coeff_ring(coeffR, this);
   if (nvars0 < 0) return from_long(0);
   exponents_t exp = newarray_atomic(int, nvars0);
   exponents_t exp2 = newarray_atomic(int, n_vars());  // FLAT number of variables
   varpower::to_expvector(nvars0, vp, exp);
   // Now loop thru f until exponents match up.
   const Nterm *t = f;
   for (; t != 0; t = t->next)
     {
       M_->to_expvector(t->monom, exp2);
       if (EQ == exponents::lex_compare(nvars0, exp, exp2)) break;
     }
   ring_elem result = get_logical_coeff(coeffR, t);
   freemem(exp2);
   freemem(exp);
   return result;
 }
References check_coeff_ring(), EQ, mpfr::exp(), mpfr::exp2(), freemem(), from_long(), get_logical_coeff(), ExponentVector< E, OC >::lex_compare(), PolynomialRing::M_, Nterm::monom, PolynomialRing::n_vars(), newarray_atomic, Nterm::next, Monoid::to_expvector(), and varpower::to_expvector().