Macaulay2 Engine: PolyRing::lift
lift()
bool PolyRing::lift (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 403 of file poly.cpp.
 {
   // case 1:  Rf = A[x]/J ---> A[x]/I  is one of the 'base_ring's of 'this'.
   // case 2:  Rf = A      ---> A[x]/I  is the ring of scalars
   // We assume that Rg is one of the coefficient rings of 'this'
   Nterm *t = f;
   if (t == 0)
     {
       result = Rg->zero();
       return true;
     }
   int nvars0 = n_vars();
   if (Rg != K_)
     {
       const PolynomialRing *Rg1 = Rg->cast_to_PolynomialRing();
       if (Rg1 != 0)
         nvars0 -= Rg1->n_vars();
       else
         return false;
     }
   exponents_t exp = newarray_atomic(int, nvars0);
   lead_logical_exponents(nvars0, f, exp);
   if (!exponents::is_one(nvars0, exp)) return false;
   if (n_logical_terms(nvars0, f) > 1) return false;
   result = lead_logical_coeff(Rg, f);
   return true;
 }
References Ring::cast_to_PolynomialRing(), mpfr::exp(), ExponentVector< E, OC >::is_one(), PolynomialRing::K_, lead_logical_coeff(), lead_logical_exponents(), n_logical_terms(), PolynomialRing::n_vars(), newarray_atomic, and Ring::zero().
Referenced by LocalRing::lift().