Macaulay2 Engine: PolyRing::support
support()
M2_arrayint PolyRing::support (const ring_elem a) const virtual
Implements PolynomialRing.
Definition at line 327 of file poly.cpp.
 {
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
   for (int i = 0; i < n_vars(); i++) EXP1[i] = 0;
   for (Nterm& t : f)
     {
       M_->to_expvector(t.monom, EXP2);
       exponents::lcm(n_vars(), EXP1, EXP2, EXP1);
     }
   int nelems = 0;
   for (int i = 0; i < n_vars(); i++)
     if (EXP1[i] > 0) nelems++;
   M2_arrayint result = M2_makearrayint(nelems);
   int next = 0;
   for (int i = 0; i < n_vars(); i++)
     if (EXP1[i] > 0) result->array[next++] = i;
   return result;
 }
References ALLOCATE_EXPONENTS, PolynomialRing::exp_size, ExponentVector< E, OC >::lcm(), M2_makearrayint(), PolynomialRing::M_, PolynomialRing::n_vars(), and Monoid::to_expvector().
Referenced by LocalRing::support().