Macaulay2 Engine: PolyRing::var
var()
ring_elem PolyRing::var (int v) const virtual
Implements PolynomialRing.
Definition at line 286 of file poly.cpp.
 {
   exponents EXP1 = ALLOCATE_EXPONENTS(exp_size);
   for (int i = 0; i < nvars_; i++) EXP1[i] = 0;
   if (v >= 0 && v < nvars_)
     EXP1[v] = 1;
   else
     {
       std::cerr << "internal error: PolyRing::var(int v) with v = " << v
                 << "  nvars = " << nvars_ << std::endl;
       std::cerr << "aborting" << std::endl;
       abort();
       return ZERO_RINGELEM;
     }
   Nterm *result = new_term();
   result->coeff = K_->from_long(1);
   M_->from_expvector(EXP1, result->monom);
   return result;
 }
References ALLOCATE_EXPONENTS, Nterm::coeff, PolynomialRing::exp_size, Monoid::from_expvector(), Ring::from_long(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, new_term(), PolynomialRing::nvars_, and ZERO_RINGELEM.
Referenced by fromSmallIntegerCoefficients(), LocalRing::var(), and PolyRingQuotient::var().