Macaulay2 Engine: PolyRing::vec_top_coefficient
vec_top_coefficient()
vec PolyRing::vec_top_coefficient (const vec v, int & var, int & exp) const virtual
Implements PolynomialRing.
Definition at line 2359 of file poly.cpp.
 {
   x = n_vars();
   e = 0;
   if (v == nullptr)
     {
       return nullptr;
     }
   exponents_t exp = newarray_atomic(int, n_vars());
   for (vec t = v; t != nullptr; t = t->next)
     for (Nterm& f : t->coeff)
       {
         M_->to_expvector(f.monom, exp);
         for (int i = 0; i < x; i++)
           {
             if (exp[i] > 0)
               {
                 x = i;
                 e = exp[i];
                 break;
               }
           }
         if (x < n_vars() && exp[x] > e) e = exp[x];
       }
   // Now we have the variable, and its exponent.
   freemem(exp);
   if (x == n_vars()) return v;
   return vec_coefficient_of_var(v, x, e);
 }
References Nterm::coeff, mpfr::exp(), freemem(), Nterm::monom, newarray_atomic, and x.
Referenced by PolyRingQuotient::vec_top_coefficient().