Macaulay2 Engine: PolyRing::n_logical_terms
n_logical_terms()
int PolyRing::n_logical_terms (int nvars0, const ring_elem f) const virtual
Implements PolynomialRing.
Definition at line 1752 of file poly.cpp.
 {
   // nvars0 is the number of variables in the outer monoid
   if (nvars0 == n_vars()) return n_terms(f);
   Nterm *t = f;
   if (t == 0) return 0;
   exponents_t exp1 = newarray_atomic(int, n_vars());
   exponents_t exp2 = newarray_atomic(int, n_vars());
   M_->to_expvector(t->monom, exp1);
   int result = 1;
   for (; t != 0; t = t->next)
     {
       M_->to_expvector(t->monom, exp2);
       if (EQ == exponents::lex_compare(nvars0, exp1, exp2)) continue;
       // TODO: use std::swap?
       exponents_t temp = exp1;
       exp1 = exp2;
       exp2 = temp;
       result++;
     }
   freemem(exp1);
   freemem(exp2);
   return result;
 }
References EQ, mpfr::exp2(), freemem(), ExponentVector< E, OC >::lex_compare(), PolynomialRing::M_, Nterm::monom, PolynomialRing::n_terms(), PolynomialRing::n_vars(), newarray_atomic, Nterm::next, and Monoid::to_expvector().
Referenced by get_terms(), lift(), and list_form().