Macaulay2 Engine: PolyRing::quotient
quotient()
ring_elem PolyRing::quotient (const ring_elem f, const ring_elem g) const virtual
Reimplemented from Ring.
Definition at line 1142 of file poly.cpp.
 {
   ring_elem quot;
   ring_elem rem;
   if (is_zero(g)) throw exc::internal_error("cannot use division algorithm dividing by zero");
   rem = remainderAndQuotient(f, g, quot);
   return quot;
 }
References is_zero(), mpfr::rem(), and remainderAndQuotient().