Macaulay2 Engine: PolyRing::get_part
get_part()
ring_elem PolyRing::get_part (const M2_arrayint wts, const ring_elem f, bool lobound_given, bool hibound_given, long lobound, long hibound) const virtual
Implements PolynomialRing.
Definition at line 1841 of file poly.cpp.
 {
   Nterm head;
   Nterm *inresult = &head;
   exponents_t exp = newarray_atomic(int, M_->n_vars());
   for (Nterm& t : f)
     {
       M_->to_expvector(t.monom, exp);
       long wt = exponents::weight(M_->n_vars(), exp, wts);
       if (lobound_given && wt < lobound) continue;
       if (hibound_given && wt > hibound) continue;
       inresult->next = copy_term(&t);
       inresult = inresult->next;
     }
   inresult->next = 0;
   freemem(exp);
   return head.next;
 }
References copy_term(), mpfr::exp(), freemem(), PolynomialRing::M_, Monoid::n_vars(), newarray_atomic, Nterm::next, Monoid::to_expvector(), and ExponentVector< E, OC >::weight().