Macaulay2 Engine: PolyRing::translate_gbvector_from_ringelem_QQ
translate_gbvector_from_ringelem_QQ()
gbvector * PolyRing::translate_gbvector_from_ringelem_QQ (ring_elem coeff) const
Definition at line 2467 of file poly.cpp.
 {
   // We assume that the ring elements here have no denominators
   GBRing *GR = get_gb_ring();
   gbvector head;
   gbvector *inresult = &head;
   for (Nterm *t = coeff; t != 0; t = t->next)
     {
       // make a gbvector node.
       ring_elem a = globalZZ->RingZZ::from_int(mpq_numref(MPQ_VAL(t->coeff)));
       gbvector *g = GR->gbvector_term(0, a, t->monom, 0);
       inresult->next = g;
       inresult = inresult->next;
     }
   return head.next;
 }
References GBRing::gbvector_term(), PolynomialRing::get_gb_ring(), globalZZ, MPQ_VAL, and gbvector::next.
Referenced by translate_gbvector_from_ringelem().