Macaulay2 Engine: PolyRing::copy_term
copy_term()
Nterm * PolyRing::copy_term (const Nterm * t) const protected
Definition at line 161 of file poly.cpp.
 {
   Nterm *result = new_term();
   result->coeff = K_->copy(t->coeff);
   M_->copy(t->monom, result->monom);
   return result;
 }
References Nterm::coeff, Ring::copy(), Monoid::copy(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, and new_term().
Referenced by copy(), get_part(), and get_terms().