Macaulay2 Engine: PolyRing::copy
copy()
ring_elem PolyRing::copy (const ring_elem f) const virtual
Implements Ring.
Definition at line 641 of file poly.cpp.
 {
   Nterm *a = f;
   Nterm head;
   Nterm *result = &head;
   for (; a != nullptr; a = a->next, result = result->next)
     result->next = copy_term(a);
   result->next = nullptr;
   return head.next;
 }
References copy_term(), and Nterm::next.
Referenced by LocalRing::add(), add(), convolve(), LocalRing::copy(), LocalRing::denominator(), division_algorithm(), LocalRing::fraction(), gcd(), LocalRing::invert(), LocalRing::lift(), LocalRing::negate(), LocalRing::numerator(), power(), powerseries_division_algorithm(), LocalRing::promote(), promote(), remainderAndQuotient(), sagbi::subduct(), sagbi::subduct1(), LocalRing::subtract(), subtract(), and syzygy().