Macaulay2 Engine: PolyRing::translate_gbvector_from_ringelem
translate_gbvector_from_ringelem()
gbvector * PolyRing::translate_gbvector_from_ringelem (ring_elem coeff) const virtual
Implements PolynomialRing.
Definition at line 2472 of file poly.cpp.
 {
   if (getCoefficients() == globalQQ)
     return translate_gbvector_from_ringelem_QQ(coeff);
   GBRing *GR = get_gb_ring();
   gbvector head;
   gbvector *inresult = &head;
   for (Nterm& t : coeff)
     {
       // make a gbvector node.
       gbvector *g = GR->gbvector_term(nullptr, t.coeff, t.monom, 0);
       inresult->next = g;
       inresult = inresult->next;
     }
   return head.next;
 }
References GBRing::gbvector_term(), PolynomialRing::get_gb_ring(), PolynomialRing::getCoefficients(), globalQQ, gbvector::next, and translate_gbvector_from_ringelem_QQ().
Referenced by QRingInfo_field::QRingInfo_field(), and QRingInfo_ZZ::QRingInfo_ZZ().