Macaulay2 Engine: PolyRing::imp_attempt_to_cancel_lead_term
imp_attempt_to_cancel_lead_term()
bool PolyRing::imp_attempt_to_cancel_lead_term (ring_elem & f, ring_elem g, ring_elem & coeff, monomial monom) const protected
Definition at line 998 of file poly.cpp.
 {
   bool result;
   Nterm *t = f;
   Nterm *s = g;
   if (t == nullptr || s == nullptr) return true;
   if (K_->is_field())
     {
       coeff = K_->divide(t->coeff, s->coeff);
       result = true;
     }
   else if (K_ == globalZZ)
     {
       ring_elem r = globalZZ->remainderAndQuotient(t->coeff, s->coeff, coeff);
       result =
           (globalZZ->is_zero(r));  // true means lead term will be cancelled.
     }
   else
     {
       throw exc::internal_error("should not get to this code in imp_attempt_to_cancel_lead_term");
       coeff = K_->zero();
       result = false;
       // What do we do here??  Call divide, and hope for the best?
     }
   if (!K_->is_zero(coeff))
     {
       if (is_skew_)
         {
           exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
           exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
           exponents_t EXP3 = ALLOCATE_EXPONENTS(exp_size);
           M_->to_expvector(t->monom, EXP1);
           M_->to_expvector(s->monom, EXP2);
           int sign = skew_.divide(EXP1, EXP2, EXP3);
           M_->from_expvector(EXP3, monom);
           if (sign < 0) K_->negate_to(coeff);
           imp_subtract_multiple_to(f, coeff, monom, g);
         }
       else
         {
           M_->divide(t->monom, s->monom, monom);
           imp_subtract_multiple_to(f, coeff, monom, g);
         }
     }
   return result;
 }
References ALLOCATE_EXPONENTS, Nterm::coeff, SkewMultiplication::divide(), Ring::divide(), Monoid::divide(), PolynomialRing::exp_size, Monoid::from_expvector(), globalZZ, imp_subtract_multiple_to(), Ring::is_field(), PolynomialRing::is_skew_, RingZZ::is_zero(), Ring::is_zero(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, Ring::negate_to(), RingZZ::remainderAndQuotient(), PolynomialRing::skew_, Monoid::to_expvector(), and Ring::zero().
Referenced by division_algorithm(), and powerseries_division_algorithm().