Macaulay2 Engine: PolyRing::division_algorithm
division_algorithm() [1/2]
Nterm * PolyRing::division_algorithm (Nterm * f, Nterm * g) const protected
Definition at line 1506 of file poly.cpp.
 {
   // This does standard division by one polynomial, returning the remainder.
   // However, it does work for Weyl algebra, skew commutative algebra,
   // as long as the coefficient ring is a field.
   ring_elem a = copy(f);
   Nterm *t = a;
   Nterm *b = g;
   Nterm remhead;
   Nterm *remt = &remhead;
   ring_elem c;
   monomial m = M_->make_one();
   while (t != NULL)
     if (M_->divides_partial_order(b->monom, t->monom))
       {
         a = t;
         bool cancelled = imp_attempt_to_cancel_lead_term(a, g, c, m);
         t = a;
         if (!cancelled)
           {
             remt->next = t;
             remt = remt->next;
             t = t->next;
           }
       }
     else
       {
         remt->next = t;
         remt = remt->next;
         t = t->next;
       }
   remt->next = NULL;
   return remhead.next;
 }
References copy(), Monoid::divides_partial_order(), imp_attempt_to_cancel_lead_term(), PolynomialRing::M_, Monoid::make_one(), Nterm::monom, and Nterm::next.