Macaulay2 Engine: PolyRing::elem_text_out
elem_text_out()
void PolyRing::elem_text_out (buffer & o, const ring_elem f, bool p_one = true, bool p_plus = false, bool p_parens = false) const virtual
Implements Ring.
Reimplemented in SchurRing.
Definition at line 1296 of file poly.cpp.
 {
   Nterm *t = f;
   if (t == nullptr)
     {
       o << '0';
       return;
     }
   int two_terms = (t->next != nullptr);
   int needs_parens = p_parens && two_terms;
   if (needs_parens)
     {
       if (p_plus) o << '+';
       o << '(';
       p_plus = false;
     }
   for (t = f; t != nullptr; t = t->next)
     {
       int isone = M_->is_one(t->monom);
       p_parens = !isone;
       bool p_one_this = (isone && needs_parens) || (isone && p_one);
       K_->elem_text_out(o, t->coeff, p_one_this, p_plus, p_parens);
       if (!isone)
         {
           M_->elem_text_out(o, t->monom, p_one_this);
         }
       p_plus = true;
     }
   if (needs_parens) o << ')';
 }
References Nterm::coeff, Ring::elem_text_out(), Monoid::elem_text_out(), Monoid::is_one(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, and Nterm::next.
Referenced by LocalRing::elem_text_out(), and LocalRing::simplify().