Macaulay2 Engine: PolyRing::index_of_var
index_of_var()
int PolyRing::index_of_var (const ring_elem a) const virtual
Implements PolynomialRing.
Definition at line 307 of file poly.cpp.
 {
   Nterm *f = a;
   if (f == nullptr || f->next != nullptr) return -1;
   if (!K_->is_equal(f->coeff, K_->from_long(1))) return -1;
   int result = -1;
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   M_->to_expvector(f->monom, EXP1);
   for (int i = 0; i < n_vars(); i++)
     if (EXP1[i] > 1)
       return -1;
     else if (EXP1[i] == 1)
       {
         if (result >= 0) return -1;
         result = i;
       }
   return result;
 }
References ALLOCATE_EXPONENTS, Nterm::coeff, PolynomialRing::exp_size, Ring::from_long(), Ring::is_equal(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, PolynomialRing::n_vars(), Nterm::next, and Monoid::to_expvector().
Referenced by LocalRing::index_of_var().