Macaulay2 Engine: PolyRing::divide_by_expvector
divide_by_expvector()
ring_elem PolyRing::divide_by_expvector (const_exponents exp, const ring_elem a) const virtual
Implements PolynomialRing.
Definition at line 2161 of file poly.cpp.
 {
   Nterm *result = 0;
   exponents_t exp0 = newarray_atomic(int, n_vars());
   for (Nterm& t : a)
     {
       M_->to_expvector(t.monom, exp0);
       exponents::quotient(n_vars(), exp0, exp, exp0);
       Nterm *u = new_term();
       u->coeff = t.coeff;
       M_->from_expvector(exp0, u->monom);
       u->next = result;
       result = u;
     }
   freemem(exp0);
   sort(result);
   return result;
 }
References Nterm::coeff, mpfr::exp(), freemem(), Monoid::from_expvector(), PolynomialRing::M_, Nterm::monom, PolynomialRing::n_vars(), new_term(), newarray_atomic, Nterm::next, ExponentVector< E, OC >::quotient(), sort(), and Monoid::to_expvector().