Macaulay2 Engine: PolyRing::remainderAndQuotient
remainderAndQuotient()
ring_elem PolyRing::remainderAndQuotient (const ring_elem f, const ring_elem g, ring_elem & quot) const virtual
Reimplemented from Ring.
Definition at line 1152 of file poly.cpp.
 {
   if (K_->get_precision() > 0)
     {
       throw exc::engine_error(
           "polynomial division not yet implemented for RR or CC coefficients");
     }
   Nterm *q, *r;
   ring_elem rem;
   if (is_zero(f))
     {
       // In this case both the remainder and quotient are 0.
       quot = from_long(0);
       return from_long(0);
     }
   if (is_zero(g))
     {
       quot = from_long(0);
       return copy(f);
     }
   else
     {
       bool has_negative_exponent_variables = getMonoid()->numInvertibleVariables() > 0;
       bool has_vars_lt_one = getMonoid()->numNonTermOrderVariables() > 0;
       if (has_negative_exponent_variables and not has_vars_lt_one)
         {
           Nterm* f1 = f;
           Nterm* g1 = g;
           r = division_algorithm_with_laurent_variables(f1, g1, q);
           quot = q;
           return r;
         }
       else if (has_vars_lt_one)
         {
           Nterm *f1 = f;
           Nterm *g1 = g;
           r = powerseries_division_algorithm(f1, g1, q);
           quot = q;
           return r;
         }
       else
         {
           rem = division_algorithm(f, g, q);
           quot = q;
           return rem;
         }
     }
   quot = from_long(0);
   return from_long(0);
 }
References copy(), division_algorithm(), division_algorithm_with_laurent_variables(), from_long(), Ring::get_precision(), PolynomialRing::getMonoid(), is_zero(), PolynomialRing::K_, Monoid::numInvertibleVariables(), Monoid::numNonTermOrderVariables(), powerseries_division_algorithm(), and mpfr::rem().
Referenced by divide(), PolyRingQuotient::divide(), gcd(), quotient(), and remainder().