Macaulay2 Engine: PolyRing::from_long
from_long()
ring_elem PolyRing::from_long (long n) const virtual
Implements Ring.
Definition at line 169 of file poly.cpp.
 {
   ring_elem a = K_->from_long(n);
   if (K_->is_zero(a))
     {
       return ZERO_RINGELEM;
     }
   Nterm *result = new_term();
   result->coeff = a;
   M_->one(result->monom);
   return result;
 }
References Nterm::coeff, Ring::from_long(), Ring::is_zero(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, new_term(), Monoid::one(), and ZERO_RINGELEM.
Referenced by LocalRing::from_int(), LocalRing::from_long(), PolyRingQuotient::from_long(), get_coeff(), initialize_poly_ring(), LocalRing::lift_up(), make_logical_term(), SchurRing::power(), power(), power_direct(), preferred_associate(), LocalRing::promote(), LocalRing::random(), remainderAndQuotient(), and LocalRing::var().