Macaulay2 Engine: PolyRing::subtract
subtract()
ring_elem PolyRing::subtract (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 761 of file poly.cpp.
 {
   ring_elem a = copy(f);
   ring_elem b = negate(g);
   internal_add_to(a, b);
   return a;
 }
References copy(), internal_add_to(), and negate().
Referenced by LocalRing::subtract().