Macaulay2 Engine: PolyRing::preferred_associate
preferred_associate()
ring_elem PolyRing::preferred_associate (ring_elem f) const virtual
Reimplemented from Ring.
Definition at line 435 of file poly.cpp.
 {
   Nterm *f = ff;
   if (f == NULL) return from_long(1);
   ring_elem c = K_->preferred_associate(f->coeff);
   Nterm *t = new_term();
   t->coeff = c;
   M_->one(t->monom);
   t->next = 0;
   return t;
 }
References Nterm::coeff, from_long(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, new_term(), Nterm::next, Monoid::one(), and Ring::preferred_associate().
Referenced by PolyRingQuotient::preferred_associate().