Macaulay2 Engine: PolyRing::promote
promote()
bool PolyRing::promote (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 367 of file poly.cpp.
 {
   // case 1:  Rf = A[x]/J ---> A[x]/I  is one of the 'base_ring's of 'this'.
   // case 2:  Rf = A      ---> A[x]/I  is the ring of scalars
   // Cases:
   //  Rf is a poly ring (or quotient of one), with the same coeff ring as this.
   //  Rf is a poly ring (or quotient) with the same monoid as this (but coeffs
   //  are maybe different).
   //  Rf is the coeff ring of this
   //  Rf is not the coeff ring K of this, but is a base ring of K (e.g. ZZ -->
   //  QQ, A --> frac(A), any others?)
   //  Rf is a poly ring in a smaller number of variables
   int nvars0 = n_vars();
   if (Rf != K_)
     {
       const PolynomialRing *Rf1 = Rf->cast_to_PolynomialRing();
       if (Rf1 != 0)
         nvars0 -= Rf1->n_vars();
       else
         return false;
       if (Rf1 && nvars0 == 0)
         {
           result = copy(f);
           return true;
         }
     }
   exponents_t exp = newarray_atomic_clear(int, nvars0);
   result = make_logical_term(Rf, f, exp);
   return true;
 }
References Ring::cast_to_PolynomialRing(), copy(), mpfr::exp(), PolynomialRing::K_, make_logical_term(), PolynomialRing::n_vars(), and newarray_atomic_clear.