Macaulay2 Engine: PolyRing::content
content() [1/2]
ring_elem PolyRing::content (ring_elem f) const virtual
Reimplemented from Ring.
Definition at line 2185 of file poly.cpp.
{
  Nterm *t = f;
  if (t == nullptr) return K_->zero();
  ring_elem c = t->coeff;
  for (t = t->next; t != nullptr; t = t->next) K_->lower_content(c, t->coeff);
  return c;
}
References Nterm::coeff, PolynomialRing::K_, Ring::lower_content(), Nterm::next, and Ring::zero().
Referenced by PolyRingQuotient::content(), and LocalRing::simplify().