Macaulay2 Engine: PolyRing::degree_weights
degree_weights()
void PolyRing::degree_weights (const ring_elem f, const std::vector< int > & wts, int & lo, int & hi) const virtual
Implements PolynomialRing.
Definition at line 568 of file poly.cpp.
 {
   Nterm *t = f;
   if (t == nullptr)
     {
       lo = hi = 0;
       return;
     }
   int e = M_->degree_weights(t->monom, wts);
   lo = hi = e;
   for (t = t->next; t != nullptr; t = t->next)
     {
       e = M_->degree_weights(t->monom, wts);
       if (e > hi)
         hi = e;
       else if (e < lo)
         lo = e;
     }
 }
References Monoid::degree_weights(), PolynomialRing::M_, Nterm::monom, and Nterm::next.
Referenced by homogenize(), and LocalRing::homogenize().