Macaulay2 Engine: PolyRing::from_rational
from_rational()
bool PolyRing::from_rational (mpq_srcptr q, ring_elem & result) const virtual
Implements Ring.
Definition at line 194 of file poly.cpp.
 {
   ring_elem a;
   bool ok = K_->from_rational(q, a);
   if (not ok) return false;
   if (K_->is_zero(a))
     {
       result = ZERO_RINGELEM;
     }
   else
     {
       Nterm *resultpoly = new_term();
       resultpoly->coeff = a;
       M_->one(resultpoly->monom);
       result = resultpoly;
     }
   return true;
 }
References Nterm::coeff, Ring::from_rational(), Ring::is_zero(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, new_term(), Monoid::one(), and ZERO_RINGELEM.
Referenced by PolyRingQuotient::from_rational().