Macaulay2 Engine: PolyRing::get_trivial_poly_ring
get_trivial_poly_ring()
const PolyRing * PolyRing::get_trivial_poly_ring () static
Definition at line 35 of file poly.cpp.
 {
   if (trivial_poly_ring == nullptr)
     {
       make_trivial_ZZ_poly_ring();
     }
   return trivial_poly_ring;
 }
References make_trivial_ZZ_poly_ring(), and trivial_poly_ring.
Referenced by IM2_initialize(), IM2_Ring_trivial_polyring(), GF::initialize_GF(), and Ring::initialize_ring().