Macaulay2 Engine: PolyRing::make_trivial_ZZ_poly_ring
make_trivial_ZZ_poly_ring()
void PolyRing::make_trivial_ZZ_poly_ring () static protected
Definition at line 54 of file poly.cpp.
 {
   if (trivial_poly_ring != nullptr) return;
   //  globalZZ = new RingZZ;
   globalZZ = makeIntegerRing();
   Monoid *M = Monoid::get_trivial_monoid();
   trivial_poly_ring = new PolyRing();
   Monoid::set_trivial_monoid_degree_ring(trivial_poly_ring);
   globalZZ->initialize_ZZ(trivial_poly_ring);
   trivial_poly_ring->initialize_poly_ring(globalZZ, M, trivial_poly_ring);
   const PolyRing *flatR = trivial_poly_ring;
   trivial_poly_ring->gb_ring_ = GBRing::create_PolynomialRing(
       flatR->getCoefficientRing(), flatR->getMonoid());
 }
References GBRing::create_PolynomialRing(), PolynomialRing::gb_ring_, Monoid::get_trivial_monoid(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), globalZZ, initialize_poly_ring(), RingZZ::initialize_ZZ(), makeIntegerRing(), PolyRing(), Monoid::set_trivial_monoid_degree_ring(), and trivial_poly_ring.
Referenced by get_trivial_poly_ring().