Macaulay2 Engine: PolyRing::is_zero
is_zero()
bool PolyRing::is_zero (const ring_elem f) const virtual
Implements Ring.
Definition at line 475 of file poly.cpp.
 {
   Nterm *a = f;
   return a == NULL;
 }
Referenced by LocalRing::add(), LocalRing::from_rational(), gcd(), LocalRing::invert(), invert(), LocalRing::is_zero(), LocalRing::mult(), LocalRing::power(), power(), quotient(), LocalRing::random(), remainder(), remainderAndQuotient(), LocalRing::simplify(), and LocalRing::subtract().