Macaulay2 Engine: PolyRing::get_terms
get_terms()
ring_elem PolyRing::get_terms (int nvars0, const ring_elem f, int lo, int hi) const virtual
Implements PolynomialRing.
Definition at line 1904 of file poly.cpp.
 {
   int nterms = n_logical_terms(nvars0, f);
   if (lo < 0) lo = nterms + lo;
   if (hi < 0) hi = nterms + hi;
   Nterm *t = f;
   if (t == nullptr) return t;
   Nterm head;
   Nterm *result = &head;
   exponents_t exp1 = newarray_atomic(int, n_vars());
   exponents_t exp2 = newarray_atomic(int, n_vars());
   M_->to_expvector(t->monom, exp1);
   int n = 0;
   while (t != nullptr)
     {
       if (n > hi) break;
       if (n >= lo)
         {
           result->next = copy_term(t);
           result = result->next;
         }
       t = t->next;
       if (t == nullptr) break;
       M_->to_expvector(t->monom, exp2);
       if (EQ == exponents::lex_compare(nvars0, exp1, exp2)) continue;
       exponents_t temp = exp1;
       exp1 = exp2;
       exp2 = temp;
       n++;
     }
   result->next = nullptr;
   return head.next;
 }
References copy_term(), EQ, mpfr::exp2(), ExponentVector< E, OC >::lex_compare(), PolynomialRing::M_, Nterm::monom, n_logical_terms(), PolynomialRing::n_vars(), newarray_atomic, Nterm::next, and Monoid::to_expvector().