Macaulay2 Engine: PolyRing::random
random()
ring_elem PolyRing::random () const virtual
Reimplemented from Ring.
Definition at line 1299 of file poly.cpp.
 {
   return make_flat_term(K_->random(), M_->make_one());
 }
References PolynomialRing::K_, PolynomialRing::M_, make_flat_term(), Monoid::make_one(), and Ring::random().
Referenced by LocalRing::random().