Macaulay2 Engine: PolyRing::setNegativeExponentMonomial
setNegativeExponentMonomial()
std::vector< int > PolyRing::setNegativeExponentMonomial (Nterm * f) const protected
Definition at line 1389 of file poly.cpp.
 {
   exponents_t exp = new int[n_vars()];
   std::vector<int> result(n_vars(), 0);
   Nterm* t = f;
   getMonoid()->to_expvector(t->monom, exp);
   for (int i=0; i<n_vars(); i++)
     if (getMonoid()->isLaurentVariable(i))
       result[i] = exp[i];
   for (t = t->next; t != nullptr; t = t->next)
     {
       getMonoid()->to_expvector(t->monom, exp);
       for (int i=0; i<n_vars(); i++)
         if (getMonoid()->isLaurentVariable(i) and exp[i] < result[i])
           result[i] = exp[i];
     }
   delete [] exp;
   return result;
 }
References mpfr::exp(), PolynomialRing::getMonoid(), Monoid::isLaurentVariable(), Nterm::monom, PolynomialRing::n_vars(), Nterm::next, and Monoid::to_expvector().
Referenced by division_algorithm_with_laurent_variables().