Macaulay2 Engine: PolyRing::translate_gbvector_to_vec_denom
translate_gbvector_to_vec_denom()
vec PolyRing::translate_gbvector_to_vec_denom (const FreeModule * F, const gbvector * v, const ring_elem denom) const virtual
Implements PolynomialRing.
Definition at line 2688 of file poly.cpp.
 {
   if (getCoefficients() == globalQQ)
     return translate_gbvector_to_vec_QQ(F, v, denom);
   GBRing *GR = get_gb_ring();
   const ring_elem c = K_->invert(denom);
   gbvector *w = GR->gbvector_mult_by_coeff(v, c);
   vec result = translate_gbvector_to_vec(F, w);
   GR->gbvector_remove(w);
   return result;
 }
References GBRing::gbvector_mult_by_coeff(), GBRing::gbvector_remove(), PolynomialRing::get_gb_ring(), PolynomialRing::getCoefficients(), globalQQ, Ring::invert(), PolynomialRing::K_, translate_gbvector_to_vec(), and translate_gbvector_to_vec_QQ().