Macaulay2 Engine: PolyRing::make_logical_term
make_logical_term()
ring_elem PolyRing::make_logical_term (const Ring * coeffR, const ring_elem a, const_exponents exp) const virtual
Implements PolynomialRing.
Definition at line 1867 of file poly.cpp.
 {
   const PolynomialRing *logicalK = coeffR->cast_to_PolynomialRing();
   int nvars0 = n_vars();
   if (K_ == coeffR)
     {
       monomial m = M_->make_one();
       M_->from_expvector(exp0, m);
       return make_flat_term(a, m);
     }
   if (logicalK == nullptr)
     {
       ERROR("expected actual coefficient ring");
       return from_long(0);
     }
   nvars0 -= logicalK->n_vars();
   Nterm head;
   Nterm *inresult = &head;
   exponents_t exp = newarray_atomic(int, M_->n_vars());
   exponents::copy(nvars0, exp0, exp);  // Sets the first part of exp
   for (Nterm& f : a)
     {
       Nterm *t = new_term();
       inresult->next = t;
       inresult = t;
       t->coeff = f.coeff;
       logicalK->getMonoid()->to_expvector(f.monom, exp + nvars0);
       M_->from_expvector(exp, t->monom);
     }
   inresult->next = nullptr;
   return head.next;
 }
References Ring::cast_to_PolynomialRing(), Nterm::coeff, ExponentVector< E, OC >::copy(), ERROR(), mpfr::exp(), Monoid::from_expvector(), from_long(), PolynomialRing::getMonoid(), PolynomialRing::K_, PolynomialRing::M_, make_flat_term(), Monoid::make_one(), Nterm::monom, Monoid::n_vars(), PolynomialRing::n_vars(), new_term(), newarray_atomic, Nterm::next, and Monoid::to_expvector().
Referenced by promote().