Macaulay2 Engine: PolyRing::power
power() [2/2]
ring_elem PolyRing::power (const ring_elem f, mpz_srcptr n) const virtual
Reimplemented from Ring.
Reimplemented in SchurRing, SkewPolynomialRing, SolvableAlgebra, and WeylAlgebra.
Definition at line 817 of file poly.cpp.
{
  ring_elem ff, result;
  if (mpz_sgn(n) == 0) return from_long(1);
  if (is_zero(f0)) return ZERO_RINGELEM;
  mpz_t abs_n;
  mpz_init(abs_n);
  mpz_abs(abs_n, n);
  if (mpz_sgn(n) > 0)
    ff = f0;
  else
    ff = invert(f0);
  Nterm *f = ff;
  // In this case, the computation may only be formed in two
  // cases: (1) f is a constant, or (2) n is small enough
  std::pair<bool, int> n1 = RingZZ::get_si(abs_n);
  if (n1.first)
    {
      result = power(f, n1.second);
    }
  else if (is_unit(f))  // really want a routine 'is_scalar'...
    {
      ring_elem a = K_->power(f->coeff, abs_n);
      result = make_flat_term(a, f->monom);
    }
  else
    {
      ERROR("exponent too large");
      result = ZERO_RINGELEM;
    }
  mpz_clear(abs_n);
  return result;
}
References Nterm::coeff, ERROR(), from_long(), RingZZ::get_si(), invert(), is_unit(), is_zero(), PolynomialRing::K_, make_flat_term(), Nterm::monom, power(), Ring::power(), and ZERO_RINGELEM.
Referenced by LocalRing::power(), LocalRing::power(), and power().