Macaulay2 Engine: PolyRing::syzygy
syzygy()
void PolyRing::syzygy (const ring_elem a, const ring_elem b, ring_elem & x, ring_elem & y) const virtual
Implements Ring.
Definition at line 1206 of file poly.cpp.
 {
   // Do some special cases first.  After that: compute a GB
   // For the GB, we need to make a 1 by 2 matrix, and compute until one syzygy
   // is found.
   // create the matrix
   // create the gb comp
   // compute until one syz is found
   // grab the answer from the syz matrix.
   // Special situations:
   if (PolyRing::is_equal(b, one()))
     {
       x = PolyRing::copy(b);
       y = PolyRing::negate(a);
     }
   else if (PolyRing::is_equal(b, minus_one()))
     {
       x = one();
       y = PolyRing::copy(a);
     }
   else
     {
 #if 0
 // // MES Aug 2002 ifdef'ed because gb_comp is not back yet
 //       intarray syzygy_stop_conditions;
 //       syzygy_stop_conditions.append(0); // ngb
 //       syzygy_stop_conditions.append(1); // nsyz
 //       syzygy_stop_conditions.append(0); // npairs
 //       syzygy_stop_conditions.append(0);
 //       syzygy_stop_conditions.append(0);
 //       syzygy_stop_conditions.append(0); // subring limit
 //       syzygy_stop_conditions.append(0);
 //
 //       const FreeModule *F = make_FreeModule(1);
 //       Matrix *m = new Matrix(F);
 //       m->append(F->raw_term(a,0));
 //       m->append(F->raw_term(b,0));
 // #if 0
 // //   buffer o;
 // //   o << "constructing syzygy on ";
 // //   elem_text_out(o,a);
 // //   o << " and ";
 // //   elem_text_out(o,b);
 // //   emit_line(o.str());
 // //   o.reset();
 // //   o << "matrix is" << newline;
 // //   m->text_out(o);
 // //   emit_line(o.str());
 // //   o.reset();
 // #endif
 //
 //       gb_comp *g = gb_comp::make(m,true,-1,0);
 //       g->calc(0, syzygy_stop_conditions);
 //       Matrix *s = g->syz_matrix();
 //
 // #if 0
 // //   if (s.n_cols() != 1)
 // //     {
 // //       o << "found " << s.n_cols() << " syzygies";
 // //       emit_line(o.str());
 // //     }
 // #endif
 //       x = s->elem(0,0);
 //       y = s->elem(1,0);
 //       ring_elem c = preferred_associate(x);
 //       ring_elem x1 = mult(c,x);
 //       ring_elem y1 = mult(c,y);
 //       x = x1;
 //       y = y1;
 // #if 0
 // //   o << "result: x = ";
 // //   elem_text_out(o,x);
 // //   o << " and y = ";
 // //   elem_text_out(o,y);
 // //   emit_line(o.str());
 // #endif
 //       freemem(g);
 #endif
     }
 }
References copy(), is_equal(), Ring::minus_one(), negate(), Ring::one(), and x.
Referenced by LocalRing::simplify().