Macaulay2 Engine: PolyRing::translate_gbvector_to_vec_QQ
translate_gbvector_to_vec_QQ()
vec PolyRing::translate_gbvector_to_vec_QQ (const FreeModule * F, const gbvector * v, const ring_elem denom) const
Definition at line 2561 of file poly.cpp.
 {
   if (v == nullptr) return nullptr;
   GBRing *GR = get_gb_ring();
   int firstcomp = v->comp;
   int lastcomp = firstcomp;
   for (const gbvector *t = v->next; t != nullptr; t = t->next)
     {
       if (firstcomp > t->comp)
         firstcomp = t->comp;
       else if (lastcomp < t->comp)
         lastcomp = t->comp;
     }
   Nterm **vec_comps = newarray(Nterm *, lastcomp - firstcomp + 1);
   Nterm **vec_last = newarray(Nterm *, lastcomp - firstcomp + 1);
   for (int i = 0; i < lastcomp - firstcomp + 1; i++)
     {
       vec_comps[i] = nullptr;
       vec_last[i] = nullptr;
     }
   // Now make a list of Nterm's, copy gbvectors in (except comps)
   for (const gbvector *t = v; t != nullptr; t = t->next)
     {
       Nterm *s = new_term();
       GR->gbvector_get_lead_monomial(F, t, s->monom);
       s->coeff = globalQQ->fraction(t->coeff, denom);
       s->next = nullptr;
       int x = t->comp - firstcomp;
       if (!vec_comps[x])
         {
           vec_comps[x] = s;
           vec_last[x] = s;
         }
       else
         {
           vec_last[x]->next = s;
           vec_last[x] = s;
         }
     }
   // Now create the vecs
   vec result = nullptr;
   for (int x = 0; x < lastcomp - firstcomp + 1; x++)
     if (vec_comps[x])
       {
         vec w = make_vec(x + firstcomp - 1, vec_comps[x]);
         w->next = result;
         result = w;
       }
   // Finally, free vec_last, vec_comps;
   freemem(vec_comps);
   freemem(vec_last);
   return result;
 }
References Nterm::coeff, gbvector::comp, M2::RingQQ::fraction(), freemem(), GBRing::gbvector_get_lead_monomial(), PolynomialRing::get_gb_ring(), globalQQ, Ring::make_vec(), Nterm::monom, new_term(), newarray, gbvector::next, Nterm::next, and x.
Referenced by translate_gbvector_to_vec(), and translate_gbvector_to_vec_denom().