Macaulay2 Engine: PolyRing::is_unit
is_unit()
bool PolyRing::is_unit (const ring_elem f) const virtual
Implements Ring.
Definition at line 466 of file poly.cpp.
 {
   Nterm *t = f;
   if (begin(f) == end(f)) return false;
   if (t->next == NULL && M_->is_one(t->monom) && K_->is_unit(t->coeff))
     return true;
   return false;
 }
References begin(), Nterm::coeff, end(), Monoid::is_one(), Ring::is_unit(), PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, and Nterm::next.
Referenced by LocalRing::index_of_var(), and power().