Macaulay2 Engine: PolyRing::degree_of_var
degree_of_var()
void PolyRing::degree_of_var (int n, const ring_elem a, int & lo, int & hi) const virtual
Implements PolynomialRing.
Definition at line 2100 of file poly.cpp.
 {
   Nterm *t = a;
   if (t == nullptr)
     {
       ERROR("attempting to find degree of a zero element");
       return;
     }
   exponents_t exp = newarray_atomic(int, n_vars());
   M_->to_expvector(t->monom, exp);
   lo = hi = exp[n];
   for (t = t->next; t != nullptr; t = t->next)
     {
       M_->to_expvector(t->monom, exp);
       if (exp[n] < lo)
         lo = exp[n];
       else if (exp[n] > hi)
         hi = exp[n];
     }
   freemem(exp);
 }
References ERROR(), mpfr::exp(), freemem(), PolynomialRing::M_, Nterm::monom, PolynomialRing::n_vars(), newarray_atomic, Nterm::next, and Monoid::to_expvector().