Macaulay2 Engine: PolyRing::internal_add_to
internal_add_to()
void PolyRing::internal_add_to (ring_elem & f, ring_elem & g) const
Definition at line 664 of file poly.cpp.
 {
   Nterm *f = ff;
   Nterm *g = gg;
   gg = ZERO_RINGELEM;
   if (g == NULL) return;
   if (f == NULL)
     {
       ff = g;
       return;
     }
   Nterm head;
   Nterm *result = &head;
   while (1) switch (M_->compare(f->monom, g->monom))
       {
         case -1:
           result->next = g;
           result = result->next;
           g = g->next;
           if (g == NULL)
             {
               result->next = f;
               ff = head.next;
               return;
             }
           break;
         case 1:
           result->next = f;
           result = result->next;
           f = f->next;
           if (f == NULL)
             {
               result->next = g;
               ff = head.next;
               return;
             }
           break;
         case 0:
           Nterm *tmf = f;
           Nterm *tmg = g;
           f = f->next;
           g = g->next;
           K_->add_to(tmf->coeff, tmg->coeff);
           if (is_ZZ_quotient_)
             {
               ring_elem t = globalZZ->remainder(tmf->coeff, ZZ_quotient_value_);
               tmf->coeff = t;
             }
           if (!K_->is_zero(tmf->coeff))
             {
               result->next = tmf;
               result = result->next;
             }
           if (g == NULL)
             {
               result->next = f;
               ff = head.next;
               return;
             }
           if (f == NULL)
             {
               result->next = g;
               ff = head.next;
               return;
             }
           break;
       }
 }
References Ring::add_to(), Nterm::coeff, Monoid::compare(), globalZZ, Ring::is_zero(), PolynomialRing::is_ZZ_quotient_, PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, Nterm::next, RingZZ::remainder(), ZERO_RINGELEM, and PolynomialRing::ZZ_quotient_value_.
Referenced by add(), convolve(), internal_subtract_to(), QRingInfo_field_basic::reduce_lead_term_basic_field(), QRingInfo_field_QQ::reduce_lead_term_QQ(), and subtract().