Macaulay2 Engine: PolyRing::translate_gbvector_from_vec
translate_gbvector_from_vec()
gbvector * PolyRing::translate_gbvector_from_vec (const FreeModule * F, const vec v, ring_elem & result_denominator) const virtual
Implements PolynomialRing.
Definition at line 2527 of file poly.cpp.
 {
   if (getCoefficients() == globalQQ)
     return translate_gbvector_from_vec_QQ(F, v, result_denominator);
   result_denominator = getCoefficients()->one();
   if (v == 0) return 0;
   GBRing *GR = get_gb_ring();
   gbvectorHeap H(GR, F);
   gbvector head;
   gbvector *inresult;
   for (vec w = v; w != 0; w = w->next)
     {
       inresult = &head;
       int comp = w->comp + 1;
       for (Nterm& t : w->coeff)
         {
           // make a gbvector node.
           gbvector *g = GR->gbvector_term(F, t.coeff, t.monom, comp);
           inresult->next = g;
           inresult = inresult->next;
         }
       H.add(head.next);
     }
   return H.value();
 }
References gbvectorHeap::add(), Nterm::coeff, gbvector::comp, GBRing::gbvector_term(), PolynomialRing::get_gb_ring(), PolynomialRing::getCoefficients(), globalQQ, Nterm::monom, gbvector::next, Ring::one(), translate_gbvector_from_vec_QQ(), and gbvectorHeap::value().