Macaulay2 Engine: DMat::numColumns
numColumns()
template<typename ACoeffRing > size_t DMat< ACoeffRing >::numColumns () const inline
Definition at line 134 of file dmat.hpp.
 { return mNumColumns; }
References DMat< ACoeffRing >::mNumColumns.
Referenced by MatrixOps::addInPlace(), MatrixOps::addMultipleTo(), MatrixOps::clean(), MatElementaryOps< DMat< RT > >::column2by2(), MatElementaryOps< DMat< RT > >::column_op(), DMat< M2::ARingGFFlintBig >::columnBegin(), DMat< M2::ARingGFFlint >::columnBegin(), DMat< M2::ARingQQFlint >::columnBegin(), DMat< M2::ARingZZ >::columnBegin(), DMat< M2::ARingZZpFlint >::columnBegin(), DMat< ACoeffRing >::columnBegin(), DMat< M2::ARingGFFlintBig >::columnEnd(), DMat< M2::ARingGFFlint >::columnEnd(), DMat< M2::ARingQQFlint >::columnEnd(), DMat< M2::ARingZZ >::columnEnd(), DMat< M2::ARingZZpFlint >::columnEnd(), DMat< ACoeffRing >::columnEnd(), MatElementaryOps< DMat< RT > >::delete_columns(), MatElementaryOps< DMat< RT > >::delete_rows(), MatElementaryOps< DMat< RT > >::divide_column(), DMat< M2::ARingQQFlint >::DMat(), MatElementaryOps< DMat< RT > >::dot_product(), EigenM2::eigenvalues(), Lapack::eigenvalues(), Lapack::eigenvalues_hermitian(), EigenM2::eigenvalues_hermitian(), Lapack::eigenvalues_symmetric(), EigenM2::eigenvectors(), Lapack::eigenvectors(), Lapack::eigenvectors_hermitian(), EigenM2::eigenvectors_hermitian(), Lapack::eigenvectors_symmetric(), DMat< M2::ARingQQFlint >::entry(), DMat< M2::ARingZZ >::entry(), SLEvaluatorConcrete< RT >::evaluate(), fill_from_lapack_array(), fill_from_lapack_upper(), fill_lower_and_upper(), EigenM2::fill_to_MatrixXmp(), FlintQQMat::FlintQQMat(), FlintZZMat::FlintZZMat(), MatrixOps::increase_norm(), MatElementaryOps< DMat< RT > >::insert_columns(), MatElementaryOps< DMat< RT > >::insert_rows(), MatElementaryOps< DMat< RT > >::interchange_columns(), MatrixOps::isEqual(), MatrixOps::isZero(), DMatLinAlg< RingType >::kernel(), EigenM2::least_squares(), Lapack::least_squares(), Lapack::least_squares_deficient(), Lapack::LU(), make_lapack_array(), MatrixOps::mult(), MatrixOps::negateInPlace(), DMatLUinPlace< RT >::numColumns(), Lapack::QR(), MatrixOps::rankProfile(), SchreyerFrame::rankUsingDenseMatrix(), MatElementaryOps< DMat< RT > >::reduce_by_pivots(), MatElementaryOps< DMat< RT > >::row_permute(), DMat< M2::ARingGFFlintBig >::rowBegin(), DMat< M2::ARingGFFlint >::rowBegin(), DMat< M2::ARingQQFlint >::rowBegin(), DMat< M2::ARingZZ >::rowBegin(), DMat< M2::ARingZZpFlint >::rowBegin(), DMat< ACoeffRing >::rowBegin(), DMat< M2::ARingGFFlintBig >::rowEnd(), DMat< M2::ARingGFFlint >::rowEnd(), DMat< M2::ARingQQFlint >::rowEnd(), DMat< M2::ARingZZ >::rowEnd(), DMat< M2::ARingZZpFlint >::rowEnd(), DMat< ACoeffRing >::rowEnd(), MatrixOps::scalarMultInPlace(), MatElementaryOps< DMat< RT > >::scale_column(), Lapack::solve(), DMatLinAlg< M2::ARingZZpFlint >::solve(), DMatLinAlg< RingType >::solve(), DMatLinAlg< M2::ARingQQ >::solve(), DMatLinAlg< M2::ARingZZpFlint >::solveInvertible(), DMatLinAlg< RingType >::solveInvertible(), DMatLinAlg< M2::ARingQQ >::solveInvertible(), MatrixOps::subtractInPlace(), MatrixOps::subtractMultipleTo(), EigenM2::SVD(), Lapack::SVD(), EigenM2::SVD_divide_conquer(), Lapack::SVD_divide_conquer(), toMatrix(), and MatrixOps::transpose().