Macaulay2 Engine: DMat::rowMajorArray
rowMajorArray() [2/2]
template<typename ACoeffRing > const ElementType * DMat< ACoeffRing >::rowMajorArray () const inline
Definition at line 202 of file dmat.hpp.
{ return mArray; }
References DMat< ACoeffRing >::mArray.
Referenced by Lapack::eigenvalues(), Lapack::eigenvectors(), fill_from_lapack_upper(), fill_from_lapack_upper(), fill_lower_and_upper(), fill_lower_and_upper(), fill_lower_and_upper(), and fill_lower_and_upper().