Macaulay2 Engine: DMat::numRows
numRows()
template<typename ACoeffRing > size_t DMat< ACoeffRing >::numRows () const inline
Definition at line 132 of file dmat.hpp.
 { return mNumRows; }
References DMat< ACoeffRing >::mNumRows.
Referenced by MatrixOps::addInPlace(), MatrixOps::addMultipleTo(), MatrixOps::clean(), MatElementaryOps< DMat< RT > >::column_permute(), DMat< M2::ARingGFFlintBig >::columnEnd(), DMat< M2::ARingGFFlint >::columnEnd(), DMat< M2::ARingQQFlint >::columnEnd(), DMat< M2::ARingZZ >::columnEnd(), DMat< M2::ARingZZpFlint >::columnEnd(), DMat< ACoeffRing >::columnEnd(), MatElementaryOps< DMat< RT > >::delete_columns(), MatElementaryOps< DMat< RT > >::delete_rows(), MatElementaryOps< DMat< RT > >::divide_row(), DMat< M2::ARingQQFlint >::DMat(), EigenM2::eigenvalues(), Lapack::eigenvalues(), Lapack::eigenvalues_hermitian(), EigenM2::eigenvalues_hermitian(), Lapack::eigenvalues_symmetric(), EigenM2::eigenvectors(), Lapack::eigenvectors(), Lapack::eigenvectors_hermitian(), EigenM2::eigenvectors_hermitian(), Lapack::eigenvectors_symmetric(), DMat< M2::ARingQQFlint >::entry(), DMat< M2::ARingZZ >::entry(), SLEvaluatorConcrete< RT >::evaluate(), fill_from_lapack_upper(), fill_lower_and_upper(), EigenM2::fill_to_MatrixXmp(), FlintQQMat::FlintQQMat(), FlintZZMat::FlintZZMat(), FlintQQMat::from_fmpq_mat(), FlintZZMat::from_fmpz_mat(), MatrixOps::increase_norm(), MatElementaryOps< DMat< RT > >::insert_columns(), MatElementaryOps< DMat< RT > >::insert_rows(), MatElementaryOps< DMat< RT > >::interchange_rows(), MatrixOps::isEqual(), MatrixOps::isZero(), MatElementaryOps< DMat< RT > >::lead_row(), EigenM2::least_squares(), Lapack::least_squares(), Lapack::least_squares_deficient(), Lapack::LU(), make_lapack_array(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), MatrixOps::mult(), MatrixOps::negateInPlace(), DMatLUinPlace< RT >::numRows(), Lapack::QR(), MatrixOps::rankProfile(), SchreyerFrame::rankUsingDenseMatrix(), MatElementaryOps< DMat< RT > >::reduce_by_pivots(), MatElementaryOps< DMat< RT > >::row2by2(), MatElementaryOps< DMat< RT > >::row_op(), MatrixOps::scalarMultInPlace(), MatElementaryOps< DMat< RT > >::scale_row(), MatElementaryOps< DMat< RT > >::setFromSubmatrix(), LUUtil< RT >::setUpperLower(), DMatLinAlg< RingType >::setUpperLower(), Lapack::solve(), DMatLinAlg< RingType >::solve(), DMatLinAlg< M2::ARingZZpFlint >::solveInvertible(), DMatLinAlg< RingType >::solveInvertible(), MatrixOps::subtractInPlace(), MatrixOps::subtractMultipleTo(), EigenM2::SVD(), Lapack::SVD(), EigenM2::SVD_divide_conquer(), Lapack::SVD_divide_conquer(), FlintQQMat::to_fmpq_mat(), FlintZZMat::to_fmpz_mat(), toMatrix(), and MatrixOps::transpose().