Macaulay2 Engine: DMat::resize
resize()
template<typename ACoeffRing > void DMat< ACoeffRing >::resize (size_t new_nrows, size_t new_ncols) inline
Definition at line 194 of file dmat.hpp.
   {
     DMat newMatrix(ring(), new_nrows, new_ncols);
     swap(newMatrix);
   }
References DMat< ACoeffRing >::ring(), and DMat< ACoeffRing >::swap().
Referenced by Lapack::eigenvalues(), Lapack::eigenvalues_hermitian(), Lapack::eigenvalues_symmetric(), Lapack::eigenvectors(), Lapack::eigenvectors_hermitian(), Lapack::eigenvectors_symmetric(), EigenM2::fill_from_MatrixXmp(), DMatLinAlg< M2::ARingZZpFlint >::inverse(), DMatLinAlg< M2::ARingZZpFlint >::kernel(), DMatLinAlg< RingType >::kernel(), Lapack::LU(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), Lapack::QR(), setDMatFromSparseMatrixGenerator(), setDMatFromSparseMatrixGeneratorTransposed(), MatElementaryOps< DMat< RT > >::setFromSubmatrix(), LUUtil< RT >::setUpperLower(), DMatLinAlg< RingType >::setUpperLower(), DMatLinAlg< M2::ARingZZpFlint >::solve(), DMatLinAlg< RingType >::solve(), DMatLinAlg< M2::ARingZZpFlint >::solveInvertible(), DMatLinAlg< RingType >::solveInvertible(), Lapack::SVD(), Lapack::SVD_divide_conquer(), FlintQQMat::toDMat(), and FlintZZMat::toDMat().