Macaulay2 Engine: DMat::ring
ring()
template<typename ACoeffRing > const ACoeffRing & DMat< ACoeffRing >::ring () const inline
Definition at line 132 of file dmat.hpp.
{ return *mRing; }
References DMat< ACoeffRing >::mRing.
Referenced by MatrixOps::addInPlace(), MatrixOps::addMultipleTo(), MatrixOps::addTo(), MatrixOps::clean(), DMat< M2::ARingGFFlintBig >::DMat(), DMat< M2::ARingGFFlint >::DMat(), DMat< ACoeffRing >::DMat(), DMat< M2::ARingGFFlintBig >::DMat(), DMat< M2::ARingGFFlint >::DMat(), DMat< ACoeffRing >::DMat(), EigenM2::eigenvalues(), Lapack::eigenvalues(), EigenM2::eigenvalues_hermitian(), EigenM2::eigenvectors(), Lapack::eigenvectors(), EigenM2::eigenvectors_hermitian(), fill_from_lapack_array(), fill_from_lapack_array(), fill_from_lapack_array(), fill_from_lapack_upper(), EigenM2::fill_from_MatrixXmp(), EigenM2::fill_from_MatrixXmp(), fill_lower_and_upper(), fill_lower_and_upper(), fill_lower_and_upper(), fill_lower_and_upper(), MatrixOps::increase_norm(), MatrixOps::isEqual(), MatrixOps::isZero(), EigenM2::least_squares(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), MatrixOps::mult(), MatrixOps::negateInPlace(), norm2(), DMat< M2::ARingGFFlintBig >::numColumns(), DMat< M2::ARingGFFlint >::numColumns(), DMat< M2::ARingGFFlintBig >::numRows(), DMat< M2::ARingGFFlint >::numRows(), MatrixOps::rankProfile(), DMat< M2::ARingGFFlintBig >::resize(), DMat< M2::ARingGFFlint >::resize(), DMat< M2::ARingQQFlint >::resize(), DMat< M2::ARingZZ >::resize(), DMat< M2::ARingZZpFlint >::resize(), DMat< ACoeffRing >::resize(), DMatLUinPlace< RT >::ring(), MatrixOps::scalarMult(), MatrixOps::scalarMultInPlace(), MatrixOps::scalarMultInPlace(), MatrixOps::set(), setDMatFromSparseMatrixGenerator(), setDMatFromSparseMatrixGeneratorTransposed(), MatrixOps::setZero(), MatrixOps::subtractInPlace(), MatrixOps::subtractMultipleTo(), EigenM2::SVD(), EigenM2::SVD_divide_conquer(), toMatrix(), MatrixOps::transpose(), DMat< M2::ARingGFFlintBig >::~DMat(), DMat< M2::ARingGFFlint >::~DMat(), and DMat< ACoeffRing >::~DMat().