Macaulay2 Engine: DMat::array
array() [2/2]
template<typename ACoeffRing > const ElementType * DMat< ACoeffRing >::array () const inline
Definition at line 200 of file dmat.hpp.
{ return mArray; }
References DMat< ACoeffRing >::mArray.
Referenced by MatrixOps::addInPlace(), MatrixOps::clean(), DMat< M2::ARingGFFlintBig >::columnBegin(), DMat< M2::ARingGFFlint >::columnBegin(), DMat< M2::ARingQQFlint >::columnBegin(), DMat< M2::ARingZZ >::columnBegin(), DMat< M2::ARingZZpFlint >::columnBegin(), DMat< ACoeffRing >::columnBegin(), DMat< M2::ARingGFFlintBig >::columnBegin(), DMat< M2::ARingGFFlint >::columnBegin(), DMat< M2::ARingQQFlint >::columnBegin(), DMat< M2::ARingZZ >::columnBegin(), DMat< M2::ARingZZpFlint >::columnBegin(), DMat< ACoeffRing >::columnBegin(), DMat< M2::ARingGFFlintBig >::columnEnd(), DMat< M2::ARingGFFlint >::columnEnd(), DMat< M2::ARingQQFlint >::columnEnd(), DMat< M2::ARingZZ >::columnEnd(), DMat< M2::ARingZZpFlint >::columnEnd(), DMat< ACoeffRing >::columnEnd(), DMat< ACoeffRing >::DMat(), SLEvaluatorConcrete< RT >::evaluate(), MatrixOps::increase_norm(), MatrixOps::isEqual(), MatrixOps::isZero(), MatrixOps::mult(), MatrixOps::negateInPlace(), DMat< M2::ARingGFFlintBig >::rowBegin(), DMat< M2::ARingGFFlint >::rowBegin(), DMat< M2::ARingQQFlint >::rowBegin(), DMat< M2::ARingZZ >::rowBegin(), DMat< M2::ARingZZpFlint >::rowBegin(), DMat< ACoeffRing >::rowBegin(), DMat< M2::ARingGFFlintBig >::rowBegin(), DMat< M2::ARingGFFlint >::rowBegin(), DMat< M2::ARingQQFlint >::rowBegin(), DMat< M2::ARingZZ >::rowBegin(), DMat< M2::ARingZZpFlint >::rowBegin(), DMat< ACoeffRing >::rowBegin(), DMat< M2::ARingGFFlintBig >::rowEnd(), DMat< M2::ARingGFFlint >::rowEnd(), DMat< M2::ARingQQFlint >::rowEnd(), DMat< M2::ARingZZ >::rowEnd(), DMat< M2::ARingZZpFlint >::rowEnd(), DMat< ACoeffRing >::rowEnd(), MatrixOps::scalarMultInPlace(), MatrixOps::subtractInPlace(), and MatrixOps::subtractMultipleTo().