Macaulay2 Engine: DMat::swap
swap()
template<typename ACoeffRing > void DMat< ACoeffRing >::swap (DMat< ACoeffRing > & M) inline
Definition at line 124 of file dmat.hpp.
   {
     std::swap(mRing, M.mRing);
     std::swap(mNumRows, M.mNumRows);
     std::swap(mNumColumns, M.mNumColumns);
     std::swap(mArray, M.mArray);
   }
References DMat< ACoeffRing >::mArray, DMat< ACoeffRing >::mNumColumns, DMat< ACoeffRing >::mNumRows, DMat< ACoeffRing >::mRing, and swap.
Referenced by MatElementaryOps< DMat< RT > >::delete_columns(), MatElementaryOps< DMat< RT > >::delete_rows(), MatElementaryOps< DMat< RT > >::insert_columns(), MatElementaryOps< DMat< RT > >::insert_rows(), DMat< M2::ARingGFFlintBig >::resize(), DMat< M2::ARingGFFlint >::resize(), DMat< M2::ARingQQFlint >::resize(), DMat< M2::ARingZZ >::resize(), DMat< M2::ARingZZpFlint >::resize(), and DMat< ACoeffRing >::resize().