Macaulay2 Engine: DMat::rowEnd
rowEnd()
template<typename ACoeffRing > ConstIterator DMat< ACoeffRing >::rowEnd (size_t row) const inline
Definition at line 159 of file dmat.hpp.
   {
     return ConstIterator(array() + (row + 1) * numColumns(), 1);
   }
References DMat< ACoeffRing >::array(), and DMat< ACoeffRing >::numColumns().
Referenced by MatElementaryOps< DMat< RT > >::divide_row(), FlintQQMat::from_fmpq_mat(), FlintZZMat::from_fmpz_mat(), MatElementaryOps< DMat< RT > >::interchange_rows(), MatrixOps::mult(), MatElementaryOps< DMat< RT > >::row2by2(), MatElementaryOps< DMat< RT > >::row_op(), MatElementaryOps< DMat< RT > >::row_permute(), MatElementaryOps< DMat< RT > >::scale_row(), MatrixOps::subtractMultipleTo(), FlintQQMat::to_fmpq_mat(), and FlintZZMat::to_fmpz_mat().