Macaulay2 Engine: DMat::entry
entry() [1/2]
template<typename ACoeffRing > ElementType& DMat< ACoeffRing >::entry (size_t row, size_t column) inline
Definition at line 185 of file dmat.hpp.
   {
     return mArray[mNumColumns * row + column];
   }
References DMat< ACoeffRing >::mArray, and DMat< ACoeffRing >::mNumColumns.
Referenced by MatrixOps::addMultipleTo(), MatrixOps::addTo(), SLEvaluatorConcrete< RT >::computeNextNode(), MatElementaryOps< DMat< RT > >::delete_columns(), MatElementaryOps< DMat< RT > >::delete_rows(), SLEvaluatorConcrete< RT >::evaluate(), EigenM2::fill_from_MatrixXmp(), EigenM2::fill_to_MatrixXmp(), MatElementaryOps< DMat< RT > >::getEntry(), MatElementaryOps< DMat< RT > >::insert_columns(), MatElementaryOps< DMat< RT > >::insert_rows(), DMatLinAlg< RingType >::kernel(), MatElementaryOps< DMat< RT > >::lead_row(), MatrixOps::LUincremental(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), norm2(), MatrixOps::scalarMult(), MatrixOps::scalarMultInPlace(), MatrixOps::set(), setDMatFromSparseMatrixGenerator(), setDMatFromSparseMatrixGeneratorTransposed(), MatElementaryOps< DMat< RT > >::setEntry(), MatElementaryOps< DMat< RT > >::setFromSubmatrix(), LUUtil< RT >::setUpperLower(), DMatLinAlg< RingType >::setUpperLower(), MatrixOps::setZero(), DMatLinAlg< M2::ARingZZpFlint >::solve(), DMatLinAlg< RingType >::solve(), HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track(), and MatrixOps::triangularSolve().