Macaulay2 Engine: DMat::ring
ring()
template<typename ACoeffRing > const ACoeffRing& DMat< ACoeffRing >::ring () const inline
Definition at line 132 of file dmat.hpp.
 { return *mRing; }
References DMat< ACoeffRing >::mRing.
Referenced by MatrixOps::addInPlace(), MatrixOps::addMultipleTo(), MatrixOps::addTo(), MatrixOps::clean(), MatElementaryOps< DMat< RT > >::column2by2(), MatElementaryOps< DMat< RT > >::column_op(), MatElementaryOps< DMat< RT > >::column_permute(), MatElementaryOps< DMat< RT > >::delete_columns(), MatElementaryOps< DMat< RT > >::delete_rows(), MatElementaryOps< DMat< RT > >::divide_column(), MatElementaryOps< DMat< RT > >::divide_row(), DMat< M2::ARingGFFlintBig >::DMat(), DMat< M2::ARingGFFlint >::DMat(), DMat< ACoeffRing >::DMat(), MatElementaryOps< DMat< RT > >::dot_product(), EigenM2::eigenvalues(), Lapack::eigenvalues(), EigenM2::eigenvalues_hermitian(), EigenM2::eigenvectors(), Lapack::eigenvectors(), EigenM2::eigenvectors_hermitian(), fill_from_lapack_array(), fill_from_lapack_upper(), EigenM2::fill_from_MatrixXmp(), fill_lower_and_upper(), MatElementaryOps< DMat< RT > >::getEntry(), MatrixOps::increase_norm(), MatElementaryOps< DMat< RT > >::insert_columns(), MatElementaryOps< DMat< RT > >::insert_rows(), MatElementaryOps< DMat< RT > >::interchange_columns(), MatElementaryOps< DMat< RT > >::interchange_rows(), MatrixOps::isEqual(), MatrixOps::isZero(), MatElementaryOps< DMat< RT > >::lead_row(), EigenM2::least_squares(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), MatrixOps::mult(), MatrixOps::negateInPlace(), norm2(), DMat< M2::ARingGFFlintBig >::numColumns(), DMat< M2::ARingGFFlint >::numColumns(), DMat< M2::ARingGFFlintBig >::numRows(), DMat< M2::ARingGFFlint >::numRows(), MatElementaryOps< DMat< RT > >::perform_reduction(), MatrixOps::rankProfile(), MatElementaryOps< DMat< RT > >::reduce_by_pivots(), DMat< M2::ARingGFFlintBig >::resize(), DMat< M2::ARingGFFlint >::resize(), DMat< M2::ARingQQFlint >::resize(), DMat< M2::ARingZZ >::resize(), DMat< M2::ARingZZpFlint >::resize(), DMat< ACoeffRing >::resize(), DMatLUinPlace< RT >::ring(), MatElementaryOps< DMat< RT > >::row2by2(), MatElementaryOps< DMat< RT > >::row_op(), MatElementaryOps< DMat< RT > >::row_permute(), MatrixOps::scalarMult(), MatrixOps::scalarMultInPlace(), MatElementaryOps< DMat< RT > >::scale_column(), MatElementaryOps< DMat< RT > >::scale_row(), MatrixOps::set(), setDMatFromSparseMatrixGenerator(), setDMatFromSparseMatrixGeneratorTransposed(), MatElementaryOps< DMat< RT > >::setEntry(), MatElementaryOps< DMat< RT > >::setFromSubmatrix(), MatrixOps::setZero(), MatrixOps::subtractInPlace(), MatrixOps::subtractMultipleTo(), EigenM2::SVD(), EigenM2::SVD_divide_conquer(), toMatrix(), MatrixOps::transpose(), DMat< M2::ARingGFFlintBig >::~DMat(), DMat< M2::ARingGFFlint >::~DMat(), and DMat< ACoeffRing >::~DMat().