Macaulay2 Engine: DMat::columnEnd
columnEnd()
template<typename ACoeffRing > ConstIterator DMat< ACoeffRing >::columnEnd (size_t col) const inline
Definition at line 172 of file dmat.hpp.
   {
     return ConstIterator(array() + col + numRows() * numColumns(),
                          numColumns());
   }
References DMat< ACoeffRing >::array(), DMat< ACoeffRing >::numColumns(), and DMat< ACoeffRing >::numRows().
Referenced by MatElementaryOps< DMat< RT > >::column2by2(), MatElementaryOps< DMat< RT > >::column_op(), MatElementaryOps< DMat< RT > >::column_permute(), MatElementaryOps< DMat< RT > >::divide_column(), MatElementaryOps< DMat< RT > >::dot_product(), Lapack::eigenvectors(), fill_from_lapack_array(), MatElementaryOps< DMat< RT > >::interchange_columns(), make_lapack_array(), MatElementaryOps< DMat< RT > >::reduce_by_pivots(), MatElementaryOps< DMat< RT > >::scale_column(), toMatrix(), and MatrixOps::transpose().