Macaulay2 Engine: DMat::columnBegin
columnBegin() [1/2]
template<typename ACoeffRing > Iterator DMat< ACoeffRing >::columnBegin (size_t col) inline
Definition at line 164 of file dmat.hpp.
   {
     return Iterator(array() + col, numColumns());
   }
References DMat< ACoeffRing >::array(), and DMat< ACoeffRing >::numColumns().
Referenced by MatElementaryOps< DMat< RT > >::column2by2(), MatElementaryOps< DMat< RT > >::column_op(), MatElementaryOps< DMat< RT > >::column_permute(), MatElementaryOps< DMat< RT > >::divide_column(), MatElementaryOps< DMat< RT > >::dot_product(), Lapack::eigenvectors(), fill_from_lapack_array(), MatElementaryOps< DMat< RT > >::interchange_columns(), make_lapack_array(), MatrixOps::mult(), MatElementaryOps< DMat< RT > >::reduce_by_pivots(), MatElementaryOps< DMat< RT > >::scale_column(), MatrixOps::subtractMultipleTo(), toMatrix(), and MatrixOps::transpose().