Macaulay2 Engine: Monomial::ints
ints() [1/2]
int* Monomial::ints () inline private
Definition at line 26 of file monomial.hpp.
 { return val.raw(); }
References intarray::raw(), and val.
Referenced by compare(), divides(), erase(), gcd(), RingElement::get_coeff(), IM2_RingElement_term(), is_equal(), is_one(), lcm(), monsyz(), operator*(), operator/(), power(), radical(), rawColonMonomialIdeal1(), rawSaturateMonomialIdeal1(), and simple_degree().