Macaulay2 Engine: Monomial::lcm
lcm()
Monomial * Monomial::lcm (const Monomial & b) const
Definition at line 107 of file monomial.cpp.
 {
   Monomial *result = new Monomial;
   varpower::lcm(ints(), b.ints(), result->val);
   return result;
 }
References ints(), varpower::lcm(), Monomial(), and val.