Macaulay2 Engine: Monomial::Monomial
Monomial() [1/5]
Monomial::Monomial () private
Definition at line 7 of file monomial.cpp.
 {
   // This routine is private because it leaves the object in
   // an incorrect state... to be filled in by varpower routines.
 }
Referenced by erase(), gcd(), lcm(), make(), monsyz(), operator*(), operator/(), power(), and radical().