Macaulay2 Engine: Monomial::gcd
gcd()
Monomial * Monomial::gcd (const Monomial & b) const
Definition at line 114 of file monomial.cpp.
 {
   Monomial *result = new Monomial;
   varpower::gcd(ints(), b.ints(), result->val);
   return result;
 }
References varpower::gcd(), ints(), Monomial(), and val.