Macaulay2 Engine: Monomial::divides
divides()
bool Monomial::divides (const Monoid * M, const Monomial & b) const
Definition at line 94 of file monomial.cpp.
 {
   int *monom1 = M->make_one();
   int *monom2 = M->make_one();
   M->from_varpower(ints(), monom1);
   M->from_varpower(b.ints(), monom2);
   bool result = M->divides(monom1, monom2);
   M->remove(monom1);
   M->remove(monom2);
   return result;
 }
References Monoid::divides(), Monoid::from_varpower(), ints(), Monoid::make_one(), monom1, monom2, and Monoid::remove().