Macaulay2 Engine: GBDeclared::create
create() [1/2]
GBComputation * GBDeclared::create (const Matrix * leadterms, const Matrix * m, const Matrix * gb, const Matrix * change, const Matrix * syz) static
Definition at line 117 of file comp-gb-declared.cpp.
 {
   // Check:
   //   the rings are all the same, and all are not NULL.
   //   m->rows(), gb->rows() are the same
   //   change->rows(), syz->rows() are the same.
   assert(leadterms != 0 && m != 0 && gb != 0 && change != 0 && syz != 0);
   const Ring *R = gb->get_ring();
   if (R != m->get_ring() || R != leadterms->get_ring() ||
       R != change->get_ring() || R != syz->get_ring())
     {
       ERROR("expected the same ring");
       return nullptr;
     }
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("declaring a GB requires a polynomial ring");
       return nullptr;
     }
   if (leadterms->n_rows() != gb->n_rows() ||
       leadterms->n_cols() != gb->n_cols())
     {
       ERROR(
           "expected same number of lead terms as marked Groebner basis "
           "elements");
       return nullptr;
     }
   // Then: create and return the object
   return new GBDeclared(leadterms, m, gb, change, syz);
 }
References Ring::cast_to_PolynomialRing(), ERROR(), gb(), GBDeclared(), Matrix::get_ring(), Matrix::n_cols(), Matrix::n_rows(), and syz.