Macaulay2 Engine: GBDeclared::GBDeclared
GBDeclared() [1/2]
GBDeclared::GBDeclared (const Matrix * m0, const Matrix * gb, const Matrix * change, const Matrix * syz0)
Definition at line 7 of file comp-gb-declared.cpp.
     : trimmed_gens(m0), syz(syz0)
 {
   set_status(COMP_DONE);
   const Ring *R = gb->get_ring();
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   GBRing *GR = P->get_gb_ring();
   const Ring *K = GR->get_flattened_coefficients();
   const FreeModule *F = m0->rows();
   const FreeModule *Fsyz = change->rows();
   G = ReducedGB::create(P, F, Fsyz);
   // Now add in the elements
   VECTOR(POLY) elems;
   for (int i = 0; i < gb->n_cols(); i++)
     {
       POLY g;
       ring_elem denom1, denom2, u, v;
       if (gb->elem(i) == 0)
         continue;  // Do not even consider including 0 elements.
       g.f = P->translate_gbvector_from_vec(F, gb->elem(i), denom1);
       g.fsyz = P->translate_gbvector_from_vec(Fsyz, change->elem(i), denom2);
       K->syzygy(denom1, denom2, u, v);
       GR->gbvector_mult_by_coeff_to(g.f, u);
       K->negate_to(v);
       GR->gbvector_mult_by_coeff_to(g.fsyz, v);
       elems.push_back(g);
     }
   G->minimalize(elems);
 }
References Ring::cast_to_PolynomialRing(), COMP_DONE, ReducedGB::create(), Matrix::elem(), POLY::f, POLY::fsyz, G, gb(), GBRing::gbvector_mult_by_coeff_to(), GBRing::get_flattened_coefficients(), PolynomialRing::get_gb_ring(), ReducedGB::minimalize(), Ring::negate_to(), Matrix::rows(), Computation::set_status(), Ring::syzygy(), PolynomialRing::translate_gbvector_from_vec(), and VECTOR().
Referenced by create().