Macaulay2 Engine: makeDependencyGraph
makeDependencyGraph()
void makeDependencyGraph (int nlevels, int nslanted_degrees)
Definition at line 54 of file res-tasking-example.cpp.
 {
   for (int lev = 0; lev < nlevels; ++lev) nodes.emplace_back(std::vector<NodePtr>(nslanted_degrees));
   // Create the nodes
   for (int lev=0; lev<nlevels; ++lev)
     for (int sldeg=0; sldeg < nslanted_degrees; ++sldeg)
       nodes[lev][sldeg] = createNode(G, lev, sldeg);
   // Add the edges
   for (int lev=0; lev<nlevels; ++lev)
     for (int sldeg=0; sldeg < nslanted_degrees; ++sldeg)
       {
         if (lev > 0)
       tbb::flow::make_edge(* nodes[lev-1][sldeg], * nodes[lev][sldeg]);
         if (sldeg > 0)
           tbb::flow::make_edge(* nodes[lev][sldeg-1], * nodes[lev][sldeg]);
       }
 }
References createNode(), G, and nodes.
Referenced by main(), SchreyerFrame::minimalBettiNumbers(), and SchreyerFrame::start_computation().