Macaulay2 Engine: MatElementaryOps< DMat< RT > >::scale_row
scale_row()
template<typename RT > static void MatElementaryOps< DMat< RT > >::scale_row (Mat & mat, size_t i, const ElementType & r) inline static
Definition at line 97 of file mat-elem-ops.hpp.
   {
     assert(i < mat.numRows());
     auto loc = mat.rowBegin(i);
     auto end = mat.rowEnd(i);
     for (; loc != end; ++loc)
       mat.ring().mult(*loc, r, *loc);  // *loc = r * *loc
   }
References end(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::ring(), DMat< ACoeffRing >::rowBegin(), and DMat< ACoeffRing >::rowEnd().