Macaulay2 Engine: MatElementaryOps< DMat< RT > >::interchange_rows
interchange_rows()
template<typename RT > static void MatElementaryOps< DMat< RT > >::interchange_rows (Mat & mat, size_t i, size_t j) inline static
Definition at line 71 of file mat-elem-ops.hpp.
   {
     assert(i < mat.numRows());
     assert(j < mat.numRows());
     if (i == j) return;
     auto ii = mat.rowBegin(i);
     auto jj = mat.rowBegin(j);
     auto end = mat.rowEnd(i);
     for (; ii != end; ++ii, ++jj) mat.ring().swap(*ii, *jj);
   }
References end(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::ring(), DMat< ACoeffRing >::rowBegin(), and DMat< ACoeffRing >::rowEnd().