Macaulay2 Engine: MatElementaryOps< DMat< RT > >::column2by2
column2by2()
template<typename RT > static void MatElementaryOps< DMat< RT > >::column2by2 (Mat & mat, size_t c1, size_t c2, const ElementType & a1, const ElementType & a2, const ElementType & b1, const ElementType & b2) inline static
Definition at line 235 of file mat-elem-ops.hpp.
   {
     assert(c1 < mat.numColumns());
     assert(c2 < mat.numColumns());
     assert(c1 != c2);
     auto loc1 = mat.columnBegin(c1);
     auto loc2 = mat.columnBegin(c2);
     auto end = mat.columnEnd(c1);
     op2by2(mat.ring(), loc1, end, loc2, a1, a2, b1, b2);
   }
References DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::columnEnd(), end(), DMat< ACoeffRing >::numColumns(), and DMat< ACoeffRing >::ring().