Macaulay2 Engine: MatElementaryOps< DMat< RT > >::row_permute
row_permute()
template<typename RT > static bool MatElementaryOps< DMat< RT > >::row_permute (Mat & mat, size_t start_row, M2_arrayint perm) inline static
Definition at line 290 of file mat-elem-ops.hpp.
   {
     // We copy one row to another location for each cycle in 'perm' of length >
     // 1.
     size_t nrows_to_permute = perm->len;
     bool* done = newarray_atomic(bool, nrows_to_permute);
     for (size_t i = 0; i < nrows_to_permute; i++) done[i] = true;
     for (size_t i = 0; i < nrows_to_permute; i++)
       {
         size_t j = perm->array[i];
         if (!done[j])
           {
             ERROR("expected permutation");
             freemem(done);
             return false;
           }
         done[j] = false;
       }
     ElementType* tmp = newarray_clear(ElementType, mat.numColumns());
     for (size_t c = 0; c < mat.numColumns(); c++) mat.ring().init(tmp[c]);
     size_t next = 0;
     while (next < nrows_to_permute)
       {
         if (done[next] || perm->array[next] == next)
           {
             next++;
           }
         else
           {
             // store row 'next' into tmp
             auto loc1 = mat.rowBegin(start_row + next);
             auto end1 = mat.rowEnd(start_row + next);
             copy_from_iter(mat.ring(), tmp, tmp + mat.numColumns(), loc1);
             size_t r = next;
             for (;;)
               {
                 // copy row perm[r] to row r
                 auto loc2 = mat.rowBegin(start_row + perm->array[r]);
                 loc1 = mat.rowBegin(start_row + r);
                 end1 = mat.rowEnd(start_row + r);
                 copy_from_iter(mat.ring(), loc1, end1, loc2);
                 done[r] = true;
                 size_t next_r = perm->array[r];
                 if (next_r == next) break;  // and so r is the previous one
                 r = perm->array[r];
               }
             // Now copy tmp back
             copy_from_iter(mat.ring(), loc1, end1, tmp);
             done[r] = true;
           }
       }
     for (size_t c = 0; c < mat.numColumns(); c++) mat.ring().clear(tmp[c]);
     freemem(tmp);
     freemem(done);
     return true;
   }
References ERROR(), freemem(), newarray_atomic, newarray_clear, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::ring(), DMat< ACoeffRing >::rowBegin(), and DMat< ACoeffRing >::rowEnd().