Macaulay2 Engine: MatElementaryOps< DMat< RT > >::lead_row
lead_row() [2/2]
template<typename RT > static size_t MatElementaryOps< DMat< RT > >::lead_row (const Mat & mat, size_t col, ElementType & result) inline static
Definition at line 46 of file mat-elem-ops.hpp.
   {
     size_t row = mat.numRows();
     while (row != 0)
       {
         --row;
         if (!mat.ring().is_zero(mat.entry(row, col)))
           {
             mat.ring().set(result, mat.entry(row, col));
             return row;
           }
       }
     return static_cast<size_t>(-1);
   }
References DMat< ACoeffRing >::entry(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::ring().