Macaulay2 Engine: MatElementaryOps< DMat< RT > >::reduce_by_pivots
reduce_by_pivots()
template<typename RT > static void MatElementaryOps< DMat< RT > >::reduce_by_pivots (Mat & M) inline static
Definition at line 542 of file mat-elem-ops.hpp.
   {
     if (M.numRows() == 0 or M.numColumns() == 0) return;
     size_t nr = M.numRows() - 1;
     size_t nc = M.numColumns() - 1;
     typename Mat::ElementType one, minus_one;
     M.ring().init(one);
     M.ring().init(minus_one);
     M.ring().set_from_long(one, 1);
     M.ring().set_from_long(minus_one, -1);
     // After using the pivot element, it is moved to [nrows-1,ncols-1]
     // and nrows and ncols are decremented.
     for (size_t i = 0; i <= nc; i++)
       {
         auto p = M.columnBegin(i);
         auto p_end = M.columnEnd(i);
         for (size_t j = 0; p != p_end; ++p, ++j)
           {
             if (M.ring().is_zero(*p)) continue;
             int pivot_type = 0;
             if (M.ring().is_equal(one, *p))
               pivot_type = 1;
             else if (M.ring().is_equal(minus_one, *p))
               pivot_type = -1;
             if (pivot_type != 0)
               {
                 // printf("before reduction: j=%lu i=%lu:\n",j,i);
                 // displayMat(M);
                 perform_reduction(M, j, i, nr--, nc--, pivot_type);
                 // printf("after reduction: j=%lu i=%lu:\n",j,i);
                 // displayMat(M);
                 if (nr == static_cast<size_t>(-1) or
                     nc == static_cast<size_t>(-1))
                   return;
                 // restart loop with the (new) column i
                 i = -1;
                 break;
               }
           }
       }
     // Now search for other possible pivots
     for (size_t i = 0; i <= nc; i++)
       {
         auto p = M.columnBegin(i);
         auto p_end = M.columnEnd(i);
         for (size_t j = 0; p != p_end; ++p, ++j)
           {
             if (M.ring().is_zero(*p)) continue;
             if (!M.ring().is_unit(*p)) continue;
             int pivot_type = 0;
             if (M.ring().is_equal(one, *p))
               pivot_type = 1;
             else if (M.ring().is_equal(minus_one, *p))
               pivot_type = -1;
             // printf("before general reduction: j=%lu i=%lu:\n",j,i);
             // displayMat(M);
             perform_reduction(M, j, i, nr--, nc--, pivot_type);
             // printf("after general reduction: j=%lu i=%lu:\n",j,i);
             // displayMat(M);
             if (nr == static_cast<size_t>(-1) or nc == static_cast<size_t>(-1))
               return;
             // restart loop with the (new) column i
             i = -1;
             break;
           }
       }
     M.ring().clear(minus_one);
     M.ring().clear(one);
   }
References DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::columnEnd(), minus_one, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), p, and DMat< ACoeffRing >::ring().