Macaulay2 Engine: MatElementaryOps< DMat< RT > >::scale_column
scale_column()
template<typename RT > static void MatElementaryOps< DMat< RT > >::scale_column (Mat & mat, size_t i, const ElementType & r) inline static
Definition at line 108 of file mat-elem-ops.hpp.
   {
     assert(i < mat.numColumns());
     auto loc = mat.columnBegin(i);
     auto end = mat.columnEnd(i);
     for (; loc != end; ++loc)
       mat.ring().mult(*loc, r, *loc);  // *loc = r * *loc
   }
References DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::columnEnd(), end(), DMat< ACoeffRing >::numColumns(), and DMat< ACoeffRing >::ring().