Macaulay2 Engine: MatElementaryOps< DMat< RT > >::column_permute
column_permute()
template<typename RT > static bool MatElementaryOps< DMat< RT > >::column_permute (Mat & mat, size_t start_col, M2_arrayint perm) inline static
Definition at line 350 of file mat-elem-ops.hpp.
   {
     // We copy one column to another location for each cycle in 'perm' of length
     // > 1.
     size_t ncols_to_permute = perm->len;
     bool* done = newarray_atomic(bool, ncols_to_permute);
     for (size_t i = 0; i < ncols_to_permute; i++) done[i] = true;
     for (size_t i = 0; i < ncols_to_permute; i++)
       {
         size_t j = perm->array[i];
         if (!done[j])
           {
             ERROR("expected permutation");
             freemem(done);
             return false;
           }
         done[j] = false;
       }
     ElementType* tmp = newarray_clear(ElementType, mat.numRows());
     for (size_t r = 0; r < mat.numRows(); r++) mat.ring().init(tmp[r]);
     size_t next = 0;
     while (next < ncols_to_permute)
       {
         if (done[next] || perm->array[next] == next)
           {
             next++;
           }
         else
           {
             auto loc1 = mat.columnBegin(start_col + next);
             auto end1 = mat.columnEnd(start_col + next);
             // store col 'next' into tmp
             copy_from_iter(mat.ring(), tmp, tmp + mat.numRows(), loc1);
             size_t r = next;
             for (;;)
               {
                 auto loc2 = mat.columnBegin(start_col + perm->array[r]);
                 loc1 = mat.columnBegin(start_col + r);
                 end1 = mat.columnEnd(start_col + r);
                 // copy col perm[r] to col r
                 copy_from_iter(mat.ring(), loc1, end1, loc2);
                 done[r] = true;
                 size_t next_r = perm->array[r];
                 if (next_r == next) break;  // and so r is the previous one
                 r = perm->array[r];
               }
             // Now copy tmp back
             copy_from_iter(mat.ring(), loc1, end1, tmp);
             done[r] = true;
           }
       }
     for (size_t r = 0; r < mat.numRows(); r++) mat.ring().clear(tmp[r]);
     freemem(tmp);
     freemem(done);
     return true;
   }
References DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::columnEnd(), ERROR(), freemem(), newarray_atomic, newarray_clear, DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::ring().