Macaulay2 Engine: M2PointArray::value
value()
PointArray& M2PointArray::value () inline
Definition at line 47 of file NAG.hpp.
 { return *mPointArray; }
References mPointArray.
Referenced by rawPointArrayLookup(), rawPointArrayLookupOrAppend(), and rawPointArrayToString().