Macaulay2 Engine: binomialGB::end
end()
iterator binomialGB::end () const inline
Definition at line 265 of file gb-toric.hpp.
 { return iterator(NULL); }
Referenced by debug_display(), binomialGB_comp::get_gb(), binomialGB_comp::get_initial(), ideal_quotient(), and binomialGB_comp::subringGB().