Macaulay2 Engine: binomialGB::make_new_pairs
make_new_pairs()
void binomialGB::make_new_pairs (binomial_s_pair_set * Pairs, binomial_gb_elem * f) const
Definition at line 795 of file gb-toric.cpp.
 {
   // Compute (a minimal generating set of)
   // the ideal quotient in(Gmin) : in(f).
   // Remove any that satisfy certain criteria:
   // 1. gcd(lead terms) is 1: remove.
   // 2. if homog_prime, gcd(tail terms) is not 1: remove.
   // Any that pass these tests, insert into Pairs.
   monomial m = f->f.lead;
   monomial_list *I = ideal_quotient(m);
   for (monomial_list *q = I; q != NULL; q = q->next)
     {
       gbmin_elem *ge = q->tag;  // a list of possibles
       binomial_gb_elem *g = ge->elem;
       // Criterion 1: gcd of lead terms must be not 1.
       if (R->gcd_is_one(R->lead_monomial(f->f), R->lead_monomial(g->f)))
         {
           // remove each of the elements in 'g'.
           continue;
         }
       // Criterion 2: if a homogeneous prime,
       // gcd of tails must be 1.
       if (is_homogeneous_prime)
         {
           if (!R->gcd_is_one(f->f.tail, g->f.tail)) continue;
         }
       // Finally do the insert
       monomial lcm = R->mult(m, q->m);
       Pairs->insert(binomial_s_pair(f, g, lcm));
     }
   remove_monomial_list(I);
 }
References binomialGB::gbmin_elem::elem, binomial_gb_elem::f, binomial_ring::gcd_is_one(), ideal_quotient(), is_homogeneous_prime, binomial::lead, binomial_ring::lead_monomial(), binomial_ring::mult(), binomialGB::monomial_list::next, R, remove_monomial_list(), and binomial::tail.
Referenced by binomialGB_comp::process_pair().