Macaulay2 Engine: binomialGB::reduce
reduce()
bool binomialGB::reduce (binomial & f) const
Definition at line 883 of file gb-toric.cpp.
 {
   while (true)
     {
       binomial_gb_elem *p = find_divisor(f.lead);
       if (p == nullptr)
         {
           reduce_monomial(f.tail);
           return R->normalize(f);
         }
       else
         {
           // Do the division:
           if (!R->one_reduction_step(f, p->f))  // Modifies 'f'.
             return false;
         }
     }
 }
References find_divisor(), binomial::lead, binomial_ring::normalize(), binomial_ring::one_reduction_step(), p, R, reduce_monomial(), and binomial::tail.
Referenced by binomialGB_comp::process_pair().