Macaulay2 Engine: binomialGB::debug_display
debug_display()
void binomialGB::debug_display () const
Definition at line 955 of file gb-toric.cpp.
 {
   buffer o;
   for (iterator p = begin(); p != end(); p++)
     {
       binomial_gb_elem *g = *p;
       R->elem_text_out(o, g->f);
       o << newline;
     }
   emit(o.str());
 }
References begin(), binomial_ring::elem_text_out(), emit(), end(), binomial_gb_elem::f, newline, p, R, and buffer::str().
Referenced by binomialGB_comp::stats().