Macaulay2 Engine: binomialGB::remove_monomial_list
remove_monomial_list()
void binomialGB::remove_monomial_list (monomial_list * mm) const
Definition at line 835 of file gb-toric.cpp.
 {
   while (mm != NULL)
     {
       R->remove_monomial(mm->m);
       monomial_list *tmp = mm;
       mm = mm->next;
       freemem(tmp);
     }
 }
References freemem(), binomialGB::monomial_list::m, binomialGB::monomial_list::next, R, and binomial_ring::remove_monomial().
Referenced by make_new_pairs().