Macaulay2 Engine: binomialGB::ideal_quotient
ideal_quotient()
binomialGB::monomial_list * binomialGB::ideal_quotient (monomial0 m) const
Definition at line 734 of file gb-toric.cpp.
 {
   monomial_list *r;
   monomial_list **deglist = newarray(monomial_list *, _max_degree + 1);
   for (int i = 0; i <= _max_degree; i++) deglist[i] = NULL;
   for (iterator p = begin(); p != end(); p++)
     {
       binomial_gb_elem *g = *p;
       gbmin_elem *gm = new gbmin_elem(g, R->mask(g->f.lead));
       monomial n = R->quotient(g->f.lead, m);
       monomial_list *nl = new monomial_list(n, R->mask(n), gm);
       int d = R->degree(n);
       nl->next = deglist[d];
       deglist[d] = nl;
     }
   monomial_list *result = NULL;
   for (int d = 0; d <= _max_degree; d++)
     if (deglist[d] != NULL)
       {
         monomial_list *currentresult = NULL;
         while (deglist[d] != NULL)
           {
             monomial_list *p = deglist[d];
             deglist[d] = p->next;
             if (find_divisor(result, p->m))
               {
                 R->remove_monomial(p->m);
                 freemem(p->tag);  // There is only one element at this point
                 freemem(p);
               }
             else if ((r = find_divisor(currentresult, p->m)))
               {
                 gbmin_elem *p1 = new gbmin_elem(p->tag->elem, p->mask);
                 R->remove_monomial(p->m);
                 freemem(p);
                 p1->next = r->tag;
                 r->tag = p1;
               }
             else
               {
                 p->next = currentresult;
                 currentresult = p;
               }
           }
         if (result == NULL)
           result = currentresult;
         else if (currentresult != NULL)
           {
             monomial_list *q;
             for (q = result; q->next != NULL; q = q->next)
               ;
             q->next = currentresult;
           }
         currentresult = NULL;
       }
   freemem(deglist);
   return result;
 }
References _max_degree, begin(), binomial_ring::degree(), end(), binomial_gb_elem::f, find_divisor(), freemem(), binomial::lead, binomial_ring::mask(), newarray, binomialGB::monomial_list::next, p, p1, binomial_ring::quotient(), R, binomial_ring::remove_monomial(), and binomialGB::monomial_list::tag.
Referenced by make_new_pairs().