Macaulay2 Engine: binomialGB::n_masks
n_masks()
int binomialGB::n_masks () const
Definition at line 933 of file gb-toric.cpp.
 {
   int *masks = newarray_atomic(int, 100000);
   buffer o;
   unsigned int nmasks = 1;
   masks[0] = first->mask;
   for (gbmin_elem *p = first; p != NULL; p = p->next)
     {
       o << " " << p->mask;
       bool found = false;
       for (unsigned int i = 0; i < nmasks && !found; i++)
         if (masks[i] == p->mask)
           {
             found = true;
             break;
           }
       if (!found) masks[nmasks++] = p->mask;
     }
   emit(o.str());
   freemem(masks);
   return nmasks;
 }
References emit(), first, freemem(), binomialGB::gbmin_elem::mask, newarray_atomic, p, and buffer::str().
Referenced by binomialGB_comp::stats().