Macaulay2 Engine: binomialGB::find_divisor
find_divisor() [2/2]
binomialGB::monomial_list * binomialGB::find_divisor (binomialGB::monomial_list * I, monomial0 m) const
Definition at line 719 of file gb-toric.cpp.
 {
   unsigned int mask = ~(R->mask(m));
   int d = R->degree(m);
   for (monomial_list *p = I; p != NULL; p = p->next)
     {
       if (R->degree(p->m) > d) return NULL;
       if (mask & p->mask) continue;
       if (R->divides(p->m, m)) return p;
     }
   return NULL;
 }
References binomial_ring::degree(), binomial_ring::divides(), binomial_ring::mask(), p, and R.
Referenced by ideal_quotient(), and reduce().