Macaulay2 Engine: binomialGB::minimalize_and_insert
minimalize_and_insert()
void binomialGB::minimalize_and_insert (binomial_gb_elem * f)
Definition at line 680 of file gb-toric.cpp.
 {
   monomial m = f->f.lead;
   gbmin_elem *fm = new gbmin_elem(f, R->mask(m));
   gbmin_elem head, *p;
   head.next = first;
   int deg = R->degree(m);
   if (deg > _max_degree) _max_degree = deg;
   for (p = &head; p->next != NULL; p = p->next)
     {
       if (R->graded_compare(m, p->next->elem->f.lead) == LT) break;
     }
   fm->next = p->next;
   p->next = fm;
   first = head.next;
   p = fm;
   while (p->next != NULL)
     {
       if (R->degree(p->next->elem->f.lead) > deg &&
           R->divides(m, p->next->elem->f.lead))
         {
           // remove this element
           gbmin_elem *q = p->next;
           binomial_gb_elem *qe = q->elem;
           p->next = q->next;
           q->next = NULL;
           qe->smaller = f;
         }
       else
         {
           reduce_monomial(p->next->elem->f.tail);
           p = p->next;
         }
     }
 }
References _max_degree, binomial_ring::degree(), binomial_ring::divides(), binomialGB::gbmin_elem::elem, binomial_gb_elem::f, first, binomial_ring::graded_compare(), binomial::lead, LT, binomial_ring::mask(), binomialGB::gbmin_elem::next, p, R, reduce_monomial(), and binomial_gb_elem::smaller.
Referenced by binomialGB_comp::process_pair().