Macaulay2 Engine: ResGausser::get_ring
get_ring()
const Ring* ResGausser::get_ring () const inline
Definition at line 43 of file res-gausser.hpp.
 { return mOriginalRing; }
References mOriginalRing.
Referenced by ResGausserZZp::from_ring_elem(), SchreyerFrame::rankUsingDenseMatrix(), SchreyerFrame::rankUsingDenseMatrixFlint(), ResGausserZZp::ResGausserZZp(), and DegreeZeroMapGenerator::ring().