Macaulay2 Engine: M2FreeAlgebraOrQuotient::fromModuleMonom
fromModuleMonom()
ring_elem M2FreeAlgebraOrQuotient::fromModuleMonom (const ModuleMonom & m) const
Definition at line 35 of file M2FreeAlgebra.cpp.
 {
   auto result = new Poly;
   appendFromModuleMonom(*result, m);
   return fromPoly(result);
 }
References appendFromModuleMonom(), and fromPoly().
Referenced by NCMonomialMatrix().