Macaulay2 Engine: RingMap::elem
elem()
const ring_elem RingMap::elem (int i) const inline
Definition at line 54 of file ringmap.hpp.
   {
     assert(i >= 0);
     assert(i < nvars);
     return _elem[i].bigelem;
   }
References _elem, RingMap::var::bigelem, and nvars.
Referenced by M2::ARingGFGivaro::eval(), M2::ARingGFM2::eval(), M2::ARingGFFlintBig::eval(), M2::ARingGFFlint::eval(), GF::eval(), and is_equal().