Macaulay2 Engine: RingMap::eval
eval() [1/2]
Matrix * RingMap::eval (const FreeModule * newrows, const Matrix * m) const
Definition at line 246 of file ringmap.cpp.
 {
   MatrixConstructor mat(F, 0);
   for (int i = 0; i < m->n_cols(); i++)
     mat.append(m->get_ring()->vec_eval(this, F, m->elem(i)));
   if (error()) return nullptr;
   return mat.to_matrix();
 }
References MatrixConstructor::append(), Matrix::elem(), error(), Matrix::get_ring(), Matrix::n_cols(), MatrixConstructor::to_matrix(), and Ring::vec_eval().