Macaulay2 Engine: RingMap::~RingMap
~RingMap()
RingMap::~RingMap ()
Definition at line 88 of file ringmap.cpp.
 {
   for (int i = 0; i < nvars; i++)
     {
       if (!_elem[i].coeff_is_one) K->remove(_elem[i].coeff);
       if (!_elem[i].monom_is_one) M->remove(_elem[i].monom);
       R->remove(_elem[i].bigelem);
     }
   freemem(_elem);
   K = NULL;
   M = NULL;
 }
References _elem, freemem(), K, M, nvars, R, Monoid::remove(), and Ring::remove().