Macaulay2 Engine: RingMap::computeHashValue
computeHashValue()
unsigned int RingMap::computeHashValue () const protected virtual
Implements EngineObject.
Definition at line 101 of file ringmap.cpp.
 {
   unsigned int hashval = 4565 * get_ring()->hash();
   for (int i = 0; i < nvars; i++)
     {
       hashval =
           46343 * hashval + get_ring()->computeHashValue(_elem[i].bigelem);
     }
   return hashval;
 }
References _elem, Ring::computeHashValue(), get_ring(), MutableEngineObject::hash(), and nvars.