Macaulay2 Engine: RingMap::get_ring
get_ring()
const Ring* RingMap::get_ring () const inline
Definition at line 51 of file ringmap.hpp.
 { return R; }
References R.
Referenced by computeHashValue(), eval(), M2::ARingGFM2::eval(), M2::ARingZZp::eval(), M2::ARingGFFlintBig::eval(), M2::ARingGFFlint::eval(), M2::ARingQQFlint::eval(), M2::ARingQQGMP::eval(), M2::ARingRRi::eval(), M2::ARingZZ::eval(), M2::ARingZZGMP::eval(), M2::ARingZZpFFPACK::eval(), M2::ARingZZpFlint::eval(), FreeAlgebra::eval(), FractionField::eval(), GF::eval(), LocalRing::eval(), PolyRing::eval(), SchurRing2::eval(), RingZZ::eval(), Z_mod::eval(), M2::ARingCC::eval(), M2::ARingCCC::eval(), M2::ARingRR::eval(), M2::ARingRRR::eval(), IM2_RingMap_target(), is_equal(), rawRingMapEvalMutableMatrix(), and TowerEvaluator::TowerEvaluator().