Macaulay2 Engine: RingMap::RingMap
RingMap()
RingMap::RingMap (const Matrix * m) private
Definition at line 10 of file ringmap.cpp.
                                 : R(m->get_ring())
 {
   M = nullptr;
   P = R->cast_to_PolynomialRing();
   if (P != nullptr)
     {
       M = P->getMonoid();
       K = P->getCoefficientRing();
     }
   else
     K = R;
   nvars = m->n_cols();
   is_monomial = true;
   ring_elem one = K->from_long(1);
   // Allocate space for the ring map elements
   _elem = new var[nvars];
   for (int i = 0; i < nvars; i++)
     {
       // First initialize these fields:
       _elem[i].is_zero = false;
       _elem[i].coeff_is_one = true;
       _elem[i].monom_is_one = true;
       _elem[i].bigelem_is_one = true;
       _elem[i].coeff = ZERO_RINGELEM;
       _elem[i].monom = nullptr;
       ring_elem f = m->elem(0, i);  // This does a copy.
       _elem[i].bigelem = f;
       if (R->is_zero(f))
         _elem[i].is_zero = true;
       else if (P == nullptr)
         {
           // Not a polynomial ring, so put everything into coeff
           if (!K->is_equal(f, one))
             {
               _elem[i].coeff_is_one = false;
               _elem[i].coeff = K->copy(f);
             }
         }
       else
         {
 // A polynomial ring.
 #ifdef DEVELOPMENT
 #warning "also handle fraction rings"
 #endif
           Nterm *t = f;
           if (t->next == nullptr)
             {
               // This is a single term
               if (!K->is_equal(t->coeff, one))
                 {
                   _elem[i].coeff_is_one = false;
                   _elem[i].coeff = K->copy(t->coeff);
                 }
               if (!M->is_one(t->monom))  // should handle M->n_vars() == 0 case
                                          // correctly.
                 {
                   _elem[i].monom_is_one = false;
                   _elem[i].monom = M->make_new(t->monom);
                 }
             }
           else
             {
               // This is a bigterm
               is_monomial = false;
               _elem[i].bigelem_is_one = false;
             }
         }
       K->remove(one);
     }
 }
References _elem, RingMap::var::bigelem, RingMap::var::bigelem_is_one, Ring::cast_to_PolynomialRing(), Nterm::coeff, RingMap::var::coeff, RingMap::var::coeff_is_one, Ring::copy(), Matrix::elem(), Ring::from_long(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), Ring::is_equal(), is_monomial, Monoid::is_one(), Ring::is_zero(), RingMap::var::is_zero, K, M, Monoid::make_new(), Nterm::monom, RingMap::var::monom, RingMap::var::monom_is_one, Matrix::n_cols(), Nterm::next, nvars, P, R, Ring::remove(), and ZERO_RINGELEM.
Referenced by make().