Macaulay2 Engine: RingMap::eval
eval() [2/2]
RingElement * RingMap::eval (const RingElement * r) const
Definition at line 238 of file ringmap.cpp.
 {
   RingElement *result = RingElement::make_raw(
       get_ring(), r->get_ring()->eval(this, r->get_value(), 0));
   if (error()) return nullptr;
   return result;
 }
References error(), Ring::eval(), RingElement::get_ring(), get_ring(), RingElement::get_value(), and RingElement::make_raw().
Referenced by IM2_RingMap_eval_matrix(), and IM2_RingMap_eval_ringelem().