Macaulay2 Engine: F4MemoryBlock::intern
intern()
template<typename T , long int NSLAB> void F4MemoryBlock< T, NSLAB >::intern (int len)
Definition at line 106 of file memblock.hpp.
 {
   next_free += len;
 }
Referenced by F4SPairSet::create_pre_spair(), F4GB::find_or_append_column(), F4GB::mult_monomials(), F4GB::process_column(), and F4GB::process_s_pair().