Macaulay2 Engine: F4MemoryBlock::reserve
reserve()
template<typename T , long int NSLAB> T * F4MemoryBlock< T, NSLAB >::reserve (int len)
Definition at line 86 of file memblock.hpp.
 {
   if (next_free + len > current_slab->block + NSLAB)
     {
       if (current_slab->next == 0)
         {
           last_slab->next = new slab;
           last_slab = last_slab->next;
           current_slab = last_slab;
         }
       else
         {
           current_slab = current_slab->next;
         }
       next_free = current_slab->block;
     }
   return next_free;
 }
References F4MemoryBlock< T, NSLAB >::slab::block, and F4MemoryBlock< T, NSLAB >::slab::next.
Referenced by F4SPairSet::create_pre_spair(), F4GB::find_or_append_column(), F4GB::mult_monomials(), F4GB::process_column(), F4GB::process_s_pair(), and F4GB::reset_matrix().