Macaulay2 Engine: rawCharSeries
rawCharSeries()
engine_RawMatrixArrayOrNull rawCharSeries (const Matrix * M)
Definition at line 805 of file factory.cpp.
 {
   const bool inExtension = false;
   try
     {
       const PolynomialRing *P = M->get_ring()->cast_to_PolynomialRing();
       if (P == nullptr)
         {
           ERROR("expected polynomial ring");
           return nullptr;
         }
       init_seeds();
       struct enter_factory foo(P);
       if (foo.mode == modeError) return nullptr;
       if (foo.mode == modeGF)
         {
           ERROR("not implemented yet");
           return nullptr;
         }
       CFList I;
       for (int i = 0; i < M->n_rows(); i++)
         {
           for (int j = 0; j < M->n_cols(); j++)
             {
               const RingElement *g;
               {
                 g = RingElement::make_raw(P, M->elem(i, j));
               }
               I.append(convertToFactory(*g, inExtension));
             }
         }
       List<CFList> t = irrCharSeries(I);
       engine_RawMatrixArray result =
           getmemarraytype(engine_RawMatrixArray, t.length());
       result->len = t.length();
       int next = 0;
       for (ListIterator<List<CanonicalForm> > ii = t; ii.hasItem(); ii++)
         {
           CFList u = ii.getItem();
           engine_RawRingElementArray result1 =
               getmemarraytype(engine_RawRingElementArray, u.length());
           result1->len = u.length();
           int next1 = 0;
           for (ListIterator<CanonicalForm> j = u; j.hasItem(); j++)
             {
               result1->array[next1++] = convertToM2(P, j.getItem());
               if (error()) return nullptr;
             }
           result->array[next++] =
               IM2_Matrix_make1(M->rows(), u.length(), result1, false);
         }
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Ring::cast_to_PolynomialRing(), convertToFactory(), convertToM2(), Matrix::elem(), error(), ERROR(), Matrix::get_ring(), getmemarraytype, IM2_Matrix_make1(), init_seeds(), RingElement::make_raw(), enter_factory::mode, modeError, modeGF, Matrix::n_cols(), Matrix::n_rows(), and Matrix::rows().