Macaulay2 Engine: rawPseudoRemainder
rawPseudoRemainder()
const RingElement * rawPseudoRemainder (const RingElement * f, const RingElement * g)
Definition at line 625 of file factory.cpp.
{
  const bool inExtension = false;
  const PolynomialRing *P = f->get_ring()->cast_to_PolynomialRing();
  const PolynomialRing *P2 = g->get_ring()->cast_to_PolynomialRing();
  if (P == nullptr)
    {
      ERROR("expected polynomial ring");
      return nullptr;
    }
  if (P != P2)
    {
      ERROR("encountered different rings");
      return nullptr;
    }
  struct enter_factory foo(P);
  if (foo.mode == modeError) return nullptr;
  if (foo.mode == modeGF)
    {
      set_GF_minimal_poly(P);
    }
  CanonicalForm p = convertToFactory(*f, inExtension);
  CanonicalForm q = convertToFactory(*g, inExtension);
  CanonicalForm h = Prem(p, q);
  const RingElement *r = convertToM2(P, h);
  if (error())
    {
      algebraicElement_M2 = nullptr;
      return nullptr;
    }
  algebraicElement_M2 = nullptr;
  return r;
}
References algebraicElement_M2, Ring::cast_to_PolynomialRing(), convertToFactory(), convertToM2(), error(), ERROR(), RingElement::get_ring(), enter_factory::mode, modeError, modeGF, p, and set_GF_minimal_poly().