Macaulay2 Engine: FF_LUComputation::DO
DO()
M2_arrayintOrNull FF_LUComputation::DO (MutableMatrix * M) static
Definition at line 116 of file fractionfreeLU.cpp.
 {
   FF_LUComputation F(M);
   if (!F.calc()) return nullptr;
   M2_arrayint col_permutation = F.get_column_permutation();
   return col_permutation;
 }
References calc(), get_column_permutation(), and M.
Referenced by IM2_FF_LU().