Macaulay2 Engine: FF_LUComputation::do_pivots
do_pivots()
void FF_LUComputation::do_pivots (int lo, int hi, int pivot_col) private
Definition at line 54 of file fractionfreeLU.cpp.
 {
   // Here we clear out row r in columns lo..hi, using the pivot.
   R->remove(lastpivot);
   lastpivot = pivot;
   size_t pivot_row = M->lead_row(
       pivotCol, pivot);  // pivot is the element at (pivot_row, pivotCol)
   for (int i = lo; i <= hi; i++)
     {
       ring_elem a;
       size_t r = M->lead_row(i, a);
       if (r == pivot_row)
         {
           // Need to modify column i:
           // col(i) := pivot*M[i] - M[pivot_row,i] * M[pivotCol]
           R->negate_to(a);
           M->scale_column(i, pivot);
           M->column_op(i, a, pivotCol);
         }
       if (need_div[i]) M->divide_column(i, lastpivot);
       need_div[i] = (r == pivot_row);
     }
 }
References MutableMatrix::column_op(), MutableMatrix::divide_column(), lastpivot, MutableMatrix::lead_row(), M, need_div, Ring::negate_to(), pivot, R, Ring::remove(), and MutableMatrix::scale_column().
Referenced by calc().