Macaulay2 Engine: FF_LUComputation::get_column_permutation
get_column_permutation()
M2_arrayint FF_LUComputation::get_column_permutation () private
Definition at line 108 of file fractionfreeLU.cpp.
 {
   int ncols = static_cast<int>(M->n_cols());
   M2_arrayint result = M2_makearrayint(ncols);
   for (int i = 0; i < ncols; i++) result->array[i] = col_perm[i];
   return result;
 }
References col_perm, M, M2_makearrayint(), and MutableMatrix::n_cols().
Referenced by DO().