Macaulay2 Engine: FF_LUComputation::calc
calc()
bool FF_LUComputation::calc () private
Definition at line 81 of file fractionfreeLU.cpp.
 {
   int c1;
   while (choose_pivot_column(0, --pivot_col, c1))
     {
       if (system_interrupted()) return false;
       if (pivot_col != c1)
         {
           M->interchange_columns(pivot_col, c1);
           // swap need_div[pivot_col], need_div[c1]
           bool tmp = need_div[pivot_col];
           need_div[pivot_col] = need_div[c1];
           need_div[c1] = tmp;
           // swap col_perm
           int ctmp = col_perm[pivot_col];
           col_perm[pivot_col] = col_perm[c1];
           col_perm[c1] = ctmp;
         }
       do_pivots(0, pivot_col - 1, pivot_col);
     }
   return true;
 }
References choose_pivot_column(), col_perm, do_pivots(), MutableMatrix::interchange_columns(), M, need_div, pivot_col, and system_interrupted().
Referenced by DO().