Macaulay2 Engine: TEST
TEST() [1/2]
TEST (RingTower , create)
Definition at line 30 of file RingTowerTest.cpp.
 {
   std::vector<std::string> vars = {"a", "b"};
   M2_ArrayString varnames = stdvector_to_M2_ArrayString(vars);
   const Tower* R = Tower::create(101, varnames);
   EXPECT_TRUE(R != 0);
   EXPECT_EQ(ringName(*R), "Tower[ZZ/101[a,b]]");
   EXPECT_EQ(R->n_vars(), 2);
   for (int i = 1; i < 1; i++)
     {
       ring_elem f = R->random();
       buffer o;
       o << "f = ";
       R->elem_text_out(o, f);
       std::cout << o.str() << std::endl;
     }
 }
References Tower::create(), Tower::elem_text_out(), Tower::n_vars(), Tower::random(), ringName(), stdvector_to_M2_ArrayString(), and buffer::str().