Macaulay2 Engine: TEST
TEST() [2/2]
TEST (RingTower , elems)
Definition at line 48 of file RingTowerTest.cpp.
 {
   std::vector<std::string> vars = {"a", "b"};
   M2_ArrayString varnames = stdvector_to_M2_ArrayString(vars);
   const Tower* R = Tower::create(101, varnames);
   ring_elem a = R->var(0);
   ring_elem b = R->var(1);
   buffer o;
   o << "a=";
   R->elem_text_out(o, a);
   o << " b=";
   R->elem_text_out(o, b);
   ring_elem c = R->add(a, R->from_long(2));
   c = R->add(c, b);
   o << " c=";
   R->elem_text_out(o, c);
   ring_elem d = R->power(c, 2);
   o << " d=";
   R->elem_text_out(o, d);
   o << newline;
   std::cout << o.str();
 }
References Tower::add(), Tower::create(), Tower::elem_text_out(), Tower::from_long(), newline, Ring::power(), stdvector_to_M2_ArrayString(), buffer::str(), and Tower::var().