Macaulay2 Engine: ResGausserQQHybrid::pushBackNegatedElement
pushBackNegatedElement()
void ResGausserQQHybrid::pushBackNegatedElement (CoefficientVector & coeffs, const CoefficientVector & take_from_here, size_t loc) const virtual
Implements ResGausser.
Definition at line 167 of file res-gausser-QQ-hybrid.cpp.
 {
   auto& elems = coefficientVector(coeffs);
   auto& elems_to_take = coefficientVector(take_from_here);
   FieldElement uninitializedElement;
   elems.emplace_back(uninitializedElement);
   init_element(elems.back());
   copy_element(elems.back(), elems_to_take[loc]);
   negate_element(elems.back());
 }
References coefficientVector(), copy_element(), init_element(), and negate_element().