Macaulay2 Engine: ResGausserQQHybrid::to_ring_elem
to_ring_elem()
ring_elem ResGausserQQHybrid::to_ring_elem (const Ring * K, const CoefficientVector & coeffs, size_t loc) const virtual
Implements ResGausser.
Definition at line 134 of file res-f4-m2-interface.cpp.
 {
   auto& elems = coefficientVector(coeffs);
   ring_elem result;
   if (K->ringID() == M2::ring_RR)
     K->from_double(elems[loc].mDouble, result);
   else if (K->ringID() == M2::ring_RRR)
     K->from_BigReal(&(elems[loc].mLongDouble), result);
   else if (K == globalZZ)
     {
       result = K->from_long(elems[loc].mDenominatorSize);
     }
   else if (K->characteristic() == Kp1.characteristic())
     Kp1.to_ring_elem(result, elems[loc].mMod1);
   else if (K->characteristic() == Kp2.characteristic())
     Kp2.to_ring_elem(result, elems[loc].mMod2);
   else
     {
       std::cout << "Internal logic error: should not get to this statement"
                 << std::endl;
       exit(1);
     }
   return result;
 }
References M2::ARingZZpFlint::characteristic(), Ring::characteristic(), coefficientVector(), Ring::from_BigReal(), Ring::from_double(), Ring::from_long(), globalZZ, Kp1, Kp2, M2::ring_RR, M2::ring_RRR, Ring::ringID(), and M2::ARingZZpFlint::to_ring_elem().