Macaulay2 Engine: ResGausserQQHybrid::copy_element
copy_element()
void ResGausserQQHybrid::copy_element (FieldElement & result, const FieldElement & a) const private
Definition at line 78 of file res-gausser-QQ-hybrid.cpp.
 {
   result.mDouble = a.mDouble;
   result.mMod1 = a.mMod1;
   result.mMod2 = a.mMod2;
   mRRing.set(result.mLongDouble, a.mLongDouble);
   result.mDenominatorSize = a.mDenominatorSize;
   result.mAccuracy = a.mAccuracy;
   result.mIsPresent = a.mIsPresent;
 }
References ResGausserQQHybrid::FieldElement::mAccuracy, ResGausserQQHybrid::FieldElement::mDenominatorSize, ResGausserQQHybrid::FieldElement::mDouble, ResGausserQQHybrid::FieldElement::mIsPresent, ResGausserQQHybrid::FieldElement::mLongDouble, ResGausserQQHybrid::FieldElement::mMod1, ResGausserQQHybrid::FieldElement::mMod2, mRRing, and M2::ARingRRR::set().
Referenced by pushBackElement(), pushBackMinusOne(), pushBackNegatedElement(), and pushBackOne().