Macaulay2 Engine: ResGausserQQHybrid::from_ring_elem
from_ring_elem()
void ResGausserQQHybrid::from_ring_elem (CoefficientVector & result, ring_elem numer, ring_elem denom) const virtual
Implements ResGausser.
Definition at line 161 of file res-f4-m2-interface.cpp.
 {
   //  std::cout << "creating element..." << std::flush;
   const M2::ARingZZGMP* Z = globalZZ->get_ARing();
   auto& elems = coefficientVector(result);
   const M2::ARingZZGMP::ElementType& numer1 = Z->from_ring_elem_const(numer);
   const M2::ARingZZGMP::ElementType& denom1 = Z->from_ring_elem_const(denom);
   bool isunit = Z->is_equal(numer1, denom1);
   mpq_t c;
   mpq_init(c);
   mpq_set_num(c, &numer1);
   mpq_set_den(c, &denom1);
   mpq_canonicalize(c);
   FieldElement b;
   init_element(b);
   from_mpq_element(b, c, (isunit ? 0 : 1));
   elems.emplace_back(std::move(b));
   mpq_clear(c);
   //  out(std::cout, result, elems.size()-1);
   //  std::cout << " done" << std::endl;
 }
References coefficientVector(), from_mpq_element(), M2::ARingZZGMP::from_ring_elem_const(), RingZZ::get_ARing(), globalZZ, init_element(), and M2::ARingZZGMP::is_equal().