Macaulay2 Engine: ResGausserQQHybrid::coefficientVector
coefficientVector() [2/2]
CoefficientVector ResGausserQQHybrid::coefficientVector (std::vector< FieldElement > * vals) const inline private
Definition at line 50 of file res-gausser-QQ-hybrid.hpp.
   {
     CoefficientVector result;
     result.mValue = vals;
     vals = nullptr;
     return result;
   }
References CoefficientVector::mValue.
Referenced by allocateCoefficientVector(), deallocate(), debugDisplay(), debugDisplayRow(), from_ring_elem(), out(), pushBackElement(), pushBackMinusOne(), pushBackNegatedElement(), pushBackOne(), size(), to_modp_long(), and to_ring_elem().