Macaulay2 Engine: ResGausserQQHybrid::out
out() [1/2]
std::ostream & ResGausserQQHybrid::out (std::ostream & o, CoefficientVector f, int loc) const virtual
Implements ResGausser.
Definition at line 365 of file res-gausser-QQ-hybrid.cpp.
 {
   if (r.isNull())
     {
       o << "[vector is null!]";
       return o;
     }
   auto& elems = coefficientVector(r);
   out(o, elems[loc]);
   return o;
 }
References coefficientVector(), CoefficientVector::isNull(), and out().