Macaulay2 Engine: ResGausserQQHybrid::from_long_element
from_long_element()
void ResGausserQQHybrid::from_long_element (FieldElement & a, long val) const private
Definition at line 51 of file res-gausser-QQ-hybrid.cpp.
 {
   a.mDouble = val;
   Kp1.set_from_long(a.mMod1, val);
   Kp2.set_from_long(a.mMod2, val);
   mRRing.set_from_long(a.mLongDouble, val);
   a.mDenominatorSize = 0;
   a.mAccuracy = 1;  // what should this be??
   if (val != 0)
     a.mIsPresent = true;
   else
     a.mIsPresent = false;
 }
References Kp1, Kp2, ResGausserQQHybrid::FieldElement::mAccuracy, ResGausserQQHybrid::FieldElement::mDenominatorSize, ResGausserQQHybrid::FieldElement::mDouble, ResGausserQQHybrid::FieldElement::mIsPresent, ResGausserQQHybrid::FieldElement::mLongDouble, ResGausserQQHybrid::FieldElement::mMod1, ResGausserQQHybrid::FieldElement::mMod2, mRRing, M2::ARingRRR::set_from_long(), and M2::ARingZZpFlint::set_from_long().
Referenced by ResGausserQQHybrid().