Macaulay2 Engine: ResGausserQQHybrid::isAllowedCoefficientRing
isAllowedCoefficientRing()
bool ResGausserQQHybrid::isAllowedCoefficientRing (const Ring * K) const virtual
Implements ResGausser.
Definition at line 125 of file res-f4-m2-interface.cpp.
 {
   return K->ringID() == M2::ring_RR or
          (K->isFinitePrimeField() and
           (K->characteristic() == Kp1.characteristic() or
            K->characteristic() == Kp2.characteristic())) or
          (K->get_precision() == mRRing.get_precision()) or (K == globalZZ);
 }
References M2::ARingZZpFlint::characteristic(), Ring::characteristic(), M2::ARingRRR::get_precision(), Ring::get_precision(), globalZZ, Ring::isFinitePrimeField(), Kp1, Kp2, mRRing, M2::ring_RR, and Ring::ringID().