Macaulay2 Engine: ResGausserQQHybrid::from_mpq_element
from_mpq_element()
void ResGausserQQHybrid::from_mpq_element (FieldElement & a, mpq_t val, int denomPower) const private
Definition at line 65 of file res-gausser-QQ-hybrid.cpp.
 {
   a.mDouble = mpq_get_d(val);
   Kp1.set_from_mpq(a.mMod1, val);
   Kp2.set_from_mpq(a.mMod2, val);
   mRRing.set_from_mpq(a.mLongDouble, val);
   a.mDenominatorSize = denomPower;
   a.mAccuracy = 53;
   a.mIsPresent = true;
 }
References Kp1, Kp2, ResGausserQQHybrid::FieldElement::mAccuracy, ResGausserQQHybrid::FieldElement::mDenominatorSize, ResGausserQQHybrid::FieldElement::mDouble, ResGausserQQHybrid::FieldElement::mIsPresent, ResGausserQQHybrid::FieldElement::mLongDouble, ResGausserQQHybrid::FieldElement::mMod1, ResGausserQQHybrid::FieldElement::mMod2, mRRing, M2::ARingRRR::set_from_mpq(), and M2::ARingZZpFlint::set_from_mpq().
Referenced by from_ring_elem().