Macaulay2 Engine: Z_mod::syzygy
syzygy()
void Z_mod::syzygy (const ring_elem a, const ring_elem b, ring_elem & x, ring_elem & y) const virtual
Implements Ring.
Definition at line 293 of file ZZp.cpp.
 {
   assert(!Z_mod::is_zero(b));
   x = Z_mod::from_long(1);
   y = Z_mod::divide(a, b);
   y = ring_elem(internal_negate(y.get_int()));
 }
References divide(), from_long(), ring_elem::get_int(), internal_negate(), is_zero(), and x.