Macaulay2 Engine: Z_mod::create
create()
Z_mod * Z_mod::create (int p) static
Definition at line 64 of file ZZp.cpp.
{
  Z_mod *result = new Z_mod;
  if (!result->initialize_Z_mod(p)) return nullptr;
  return result;
}
References initialize_Z_mod(), p, and Z_mod().
Referenced by IM2_Ring_ZZp(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().