Macaulay2 Engine: Z_mod::to_int
to_int()
int Z_mod::to_int (int a) const private
Definition at line 73 of file ZZp.cpp.
 {
   int n = _exp_table[f];
   if (n > P / 2) n -= P;
   return n;
 }
References _exp_table, and P.
Referenced by coerceToLongInteger(), elem_text_out(), eval(), and lift().