Macaulay2 Engine: Z_mod::initialize_Z_mod
initialize_Z_mod()
bool Z_mod::initialize_Z_mod (int p) protected
Definition at line 15 of file ZZp.cpp.
 {
   initialize_ring(p);
   P = p;
   declare_field();
   int i, j, q, n;
   if (P == 2)
     _minus_one = 0;
   else
     _minus_one = (P - 1) / 2;
   if (P == 2)
     _prim_root = 1;
   else
     {
       j = 1;
       for (i = 2; (i < P && j < P - 1); i++)
         for (q = i, j = 1; (q != 1 && j < P); q = (q * i) % P, j++)
           ;
       _prim_root = i - 1;
     }
   // cerr << "z_mod_p: creating table for P = " << P << endl;
   _log_table = newarray_atomic(int, P);
   _exp_table = newarray_atomic(int, P);
   for (i = 0, n = 1; i < P - 1; i++, n = (n * _prim_root) % P)
     {
       _log_table[n] = i;  // i = log_(base _prim_root)(n)
       _exp_table[i] = n;  // n = (_prim_root)^i
     }
   _ZERO = P - 1;
   _exp_table[_ZERO] = 0;
   _log_table[0] = _ZERO;
   _P1 = P - 1;
   zeroV = from_long(0);
   oneV = from_long(1);
   minus_oneV = from_long(-1);
   coeffR = new CoefficientRingZZp(P, _log_table, _exp_table);
   aringZZp = new M2::ARingZZp(P);  // WARNING: this uses that the primitive
                                    // element is the SAME as computed above!!
   // Remove this warning once Z_mod is not in existence any longer.
   return true;
 }
References _exp_table, _log_table, _minus_one, _P1, _prim_root, _ZERO, aringZZp, coeffR, Ring::declare_field(), from_long(), Ring::initialize_ring(), Ring::minus_oneV, newarray_atomic, Ring::oneV, p, P, and Ring::zeroV.
Referenced by create().