Macaulay2 Engine: Z_mod::internal_subtract
internal_subtract()
int Z_mod::internal_subtract (int f, int g) const
Definition at line 221 of file ZZp.cpp.
 {
   if (g == _ZERO) return f;
   if (f == _ZERO) return internal_negate(g);
   int n = modulus_sub(_exp_table[f], _exp_table[g], P);
   return _log_table[n];
 }
References _exp_table, _log_table, _ZERO, internal_negate(), modulus_sub(), and P.
Referenced by subtract().