Macaulay2 Engine: Z_mod::from_rational
from_rational()
bool Z_mod::from_rational (mpq_srcptr q, ring_elem & result) const virtual
Implements Ring.
Definition at line 155 of file ZZp.cpp.
 {
   ring_elem a = Z_mod::from_int(mpq_numref(q));
   ring_elem b = Z_mod::from_int(mpq_denref(q));
   if (b.get_int() == _ZERO) return false;
   result = Z_mod::divide(a, b);
   return true;
 }
References _ZERO, divide(), from_int(), and ring_elem::get_int().