Macaulay2 Engine: Z_mod::eval
eval()
ring_elem Z_mod::eval (const RingMap * map, const ring_elem f, int first_var) const virtual
Implements Ring.
Definition at line 304 of file ZZp.cpp.
 {
   int a = to_int(f.get_int());
   return map->get_ring()->from_long(a);
 }
References Ring::from_long(), ring_elem::get_int(), RingMap::get_ring(), and to_int().