Macaulay2 Engine: F4Vec::reallocate
reallocate()
void F4Vec::reallocate (f4vec & a, int newsize) inline
Definition at line 85 of file f4-mem.hpp.
   {
     nreallocs++;
     f4vec newa = allocate(newsize);
     int oldsize = size(a);
     int *oldp = a;
     int *p = newa;
     for (int i = oldsize; i > 0; i--) *p++ = *oldp++;
     newa[-1] += (newsize - oldsize);
     deallocate(a);
     a = p;
   }
References allocate(), deallocate(), nreallocs, p, and size().
Referenced by resize().