Macaulay2 Engine: F4Vec::deallocate
deallocate()
void F4Vec::deallocate (f4vec & a) inline
Definition at line 66 of file f4-mem.hpp.
   {
     if (a == nullptr) return;
     int s = alloc_stash(a);
     ndeallocs[s]++;
     current[s]--;
     freemem(a - 1);
     a = nullptr;
   }
References alloc_stash(), current, freemem(), and ndeallocs.
Referenced by F4GB::clear_matrix(), F4GB::gauss_reduce(), F4GB::insert_gb_element(), reallocate(), F4GB::reorder_columns(), and F4GB::tail_reduce().