Macaulay2 Engine: F4Vec::allocate
allocate()
f4vec F4Vec::allocate (int alloc_sz) inline
Definition at line 53 of file f4-mem.hpp.
   {
     if (alloc_sz == 0) return nullptr;
     int s = find_alloc_size(alloc_sz);
     int nextlen = doublesize[s];
     nallocs[s]++;
     current[s]++;
     if (highwater[s] < current[s]) highwater[s] = current[s];
     int *result = newarray_atomic(int, nextlen);
     result[0] = (s << STASH_SHIFT) | alloc_sz;
     return (result + 1);
   }
References current, doublesize, find_alloc_size(), highwater, nallocs, newarray_atomic, and STASH_SHIFT.
Referenced by ConcreteVectorArithmetic< RingType >::denseToSparse(), F4GB::load_gen(), F4GB::load_row(), reallocate(), and F4GB::reorder_columns().