Macaulay2 Engine: F4Vec::resize
resize()
void F4Vec::resize (f4vec & a, int newsize) inline
Definition at line 98 of file f4-mem.hpp.
   {
     // grow 'a' to have size 'newsize'.
     // If the size becomes too large for a to handle
     // then reallocation is done.
     int s = alloc_stash(a);
     if (doublesize[s] < newsize)
       reallocate(a, newsize);
     else
       a[-1] += (newsize - size(a));
   }
References alloc_stash(), doublesize, reallocate(), and size().
Referenced by grow().