Macaulay2 Engine: newf4::MonomialHashTable::find
find() [2/2]
auto MonomialHashTable< ValueType >::find (const MonomialView & m, HashInt mhash) -> MonomialIndex
Definition at line 83 of file MonomialHashTable.cpp.
   {
     mStats.n_calls_find++;
     if (mMonomialPointers.size() >= mThreshold) grow();
     auto hash = mhash & mHashMask;
     long run = 0;
     while (mBuckets[hash] != 0)
       {
         MonomialIndex current = mBuckets[hash];
         if (mhash == mHashValues[current])
           {
             // likely a match.  But need to check equality first
             mStats.monequal_count++;
             if (m == mMonomialPointers[current])  // this == is a required MonomialView method!
               {
                 // Already in the table
                 if (run > mStats.max_run_length) mStats.max_run_length = run;
                 return current;
               }
             mStats.monequal_fails++;
           }
         ++hash;
         ++run;
         mStats.n_clashes++;
         if (hash == mBuckets.size()) hash = 0;
       }
     if (run > mStats.max_run_length) mStats.max_run_length = run;
     mBuckets[hash] = mMonomialPointers.size(); // index of the new element.
     mMonomialPointers.emplace_back(m, mMonomialSpace);
     mHashValues.push_back(mhash);
     return mBuckets[hash];
   }
References run.
Referenced by newf4::PolynomialListStreamCollector::appendTermDone(), find(), and TEST().