Macaulay2 Engine: newf4::MonomialHashTable::dump
dump()
auto MonomialHashTable< ValueType >::dump () const
Definition at line 116 of file MonomialHashTable.cpp.
   {
     std::cout << "--hash table info--" << std::endl;
     std::cout << "  size of hashtable = " << mBuckets.size() << std::endl;
     std::cout << "  threshold         = " << mThreshold << std::endl;
     std::cout << "  number of monoms  = " << size() << std::endl;
     mStats.dump();
   }
References newf4::HashTableStats::dump(), mBuckets, mStats, mThreshold, and size().
Referenced by newf4::GBF4Computation::dumpBasisMonomials(), grow(), and TEST().