Macaulay2 Engine: GBComputation::get_parallel_lead_terms
get_parallel_lead_terms()
const Matrix * GBComputation::get_parallel_lead_terms (M2_arrayint w) virtual
Reimplemented in GBDeclared, GBProxy, gbA, GB_comp, GBinhom_comp, GBWalker, MarkedGB, and ReducedGB.
Definition at line 211 of file comp-gb.cpp.
{
  ERROR(
      "Cannot compute parallel lead terms for this kind of Groebner "
      "computation");
  return nullptr;
}
References ERROR().
Referenced by GBProxy::get_parallel_lead_terms(), and rawGBGetParallelLeadTerms().