Macaulay2 Engine: GBComputation::get_mingens
get_mingens()
virtual const Matrix* GBComputation::get_mingens () pure virtual
Implemented in F4Computation, ReducedGB, HermiteComputation, GBWalker, binomialGB_comp, GBinhom_comp, GB_comp, gbA, GaussElimComputation, GBProxy, and GBDeclared.
Referenced by GBProxy::get_mingens(), rawGBMinimalGenerators(), and LocalRing::text_out().