Macaulay2 Engine: GBComputation::contains
contains()
virtual int GBComputation::contains (const Matrix * m) pure virtual
Implemented in F4Computation, ReducedGB, HermiteComputation, GBWalker, binomialGB_comp, GBinhom_comp, GB_comp, gbA, GaussElimComputation, GBProxy, and GBDeclared.
Referenced by GBProxy::contains(), IM2_GB_contains(), and LocalRing::is_in_prime().