Macaulay2 Engine: GBComputation::get_gb
get_gb()
virtual const Matrix * GBComputation::get_gb () pure virtual
Implemented in GBDeclared, GBProxy, GaussElimComputation, gbA, GB_comp, GBinhom_comp, binomialGB_comp, GBWalker, HermiteComputation, ReducedGB, F4Computation, and newf4::GBF4Interface.
Referenced by GBProxy::get_gb(), rawGBGetMatrix(), and GBWalker::start_computation().