Macaulay2 Engine: GBComputation::get_initial
get_initial()
virtual const Matrix * GBComputation::get_initial (int nparts) pure virtual
Implemented in GBDeclared, GBProxy, GaussElimComputation, gbA, GB_comp, GBinhom_comp, binomialGB_comp, GBWalker, HermiteComputation, MarkedGB, ReducedGB, F4Computation, and newf4::GBF4Interface.
Referenced by GBProxy::get_initial(), rawGBGetLeadTerms(), and GBWalker::start_computation().