Macaulay2 Engine: GBComputation::get_mingens
get_mingens()
virtual const Matrix * GBComputation::get_mingens () pure virtual
Implemented in GBDeclared, GBProxy, GaussElimComputation, gbA, GB_comp, GBinhom_comp, binomialGB_comp, GBWalker, HermiteComputation, ReducedGB, F4Computation, and newf4::GBF4Interface.
Referenced by GBProxy::get_mingens(), rawGBMinimalGenerators(), and LocalRing::text_out().