Macaulay2 Engine: GBComputation::get_initial
get_initial()
virtual const Matrix* GBComputation::get_initial (int nparts) pure virtual
Implemented in F4Computation, ReducedGB, MarkedGB, HermiteComputation, GBWalker, binomialGB_comp, GBinhom_comp, GB_comp, gbA, GaussElimComputation, GBProxy, and GBDeclared.
Referenced by GBProxy::get_initial(), rawGBGetLeadTerms(), and GBWalker::start_computation().