Macaulay2 Engine: GBComputation::matrix_remainder
matrix_remainder()
virtual const Matrix * GBComputation::matrix_remainder (const Matrix * m) pure virtual
Implemented in GBDeclared, GBProxy, GaussElimComputation, gbA, GB_comp, GBinhom_comp, binomialGB_comp, GBWalker, HermiteComputation, ReducedGB, F4Computation, and newf4::GBF4Interface.
Referenced by GBProxy::matrix_remainder(), rawGBMatrixRemainder(), sagbi::subduct(), and sagbi::subduct1().