Macaulay2 Engine: GBComputation::get_gb
get_gb()
virtual const Matrix* GBComputation::get_gb () pure virtual
Implemented in F4Computation, ReducedGB, HermiteComputation, GBWalker, binomialGB_comp, GBinhom_comp, GB_comp, gbA, GaussElimComputation, GBProxy, and GBDeclared.
Referenced by GBProxy::get_gb(), rawGBGetMatrix(), and GBWalker::start_computation().