Macaulay2 Engine: GBComputation::get_ring
get_ring()
virtual const Ring* GBComputation::get_ring () const pure virtual
Implemented in F4Computation, ReducedGB, HermiteComputation, GBWalker, binomialGB_comp, GBinhom_comp, GB_comp, gbA, GaussElimComputation, GBProxy, and GBDeclared.
Referenced by GBProxy::get_ring(), IM2_GB_set_hilbert_function(), and IM2_Ring_localization().