Macaulay2 Engine: GBComputation::matrix_remainder
matrix_remainder()
virtual const Matrix* GBComputation::matrix_remainder (const Matrix * m) pure virtual
Implemented in F4Computation, ReducedGB, HermiteComputation, GBWalker, binomialGB_comp, GBinhom_comp, GB_comp, gbA, GaussElimComputation, GBProxy, and GBDeclared.
Referenced by GBProxy::matrix_remainder(), rawGBMatrixRemainder(), PolyRingQuotient::remainder(), sagbi::subduct(), and sagbi::subduct1().