Macaulay2 Engine: TEST
TEST() [12/19]
TEST (RingZZmod2 , create)
Definition at line 82 of file RingZZpTest.cpp.
 {
   Ring* R = Z_mod::create(2);
   EXPECT_TRUE(R != 0);
   EXPECT_TRUE(dynamic_cast<const Z_mod*>(R) != 0);
   EXPECT_EQ(R->coefficient_type(), Ring::COEFF_BASIC);
   EXPECT_FALSE(R->is_ZZ());
   EXPECT_EQ(ringName(*R), "ZZ/2");
 }
References Ring::COEFF_BASIC, Ring::coefficient_type(), Z_mod::create(), Ring::is_ZZ(), and ringName().