Macaulay2 Engine: TEST
TEST() [19/19]
TEST (RingZZmod32003 , fromStream)
Definition at line 13 of file RingZZpTest.cpp.
 {
   std::istringstream i("+1234 +345 -235*a");
   Z_mod* R = Z_mod::create(32003);
   ring_elem a;
   while (fromStream(i, *R, a))
     {
       buffer o;
       R->elem_text_out(o, a);
       std::cout << o.str() << " peek: "
                 << "." << static_cast<char>(i.peek()) << "." << std::endl;
     }
 }
References Z_mod::create(), Z_mod::elem_text_out(), fromStream(), and buffer::str().