Macaulay2 Engine: getElement< Z_mod >
getElement< Z_mod >()
template<> ring_elem getElement< Z_mod > (const Z_mod & R, int index)
Definition at line 7 of file RingZZpTest.cpp.
 {
   ring_elem a = getElement<RingZZ>(*globalZZ, index);
   return R.from_int(a.get_mpz());
 }
References Z_mod::from_int(), ring_elem::get_mpz(), getElement< RingZZ >(), and globalZZ.