Macaulay2 Engine: DMat< M2::ARingZZpFlint >::columnEnd
columnEnd()
ConstIterator DMat< M2::ARingZZpFlint >::columnEnd (size_t col) const inline
Definition at line 72 of file dmat-zzp-flint.hpp.
   {
     return ConstIterator(array() + col + numRows() * numColumns(),
                          numColumns());
   }
References DMat< ACoeffRing >::array(), DMat< ACoeffRing >::numColumns(), and DMat< ACoeffRing >::numRows().