Macaulay2 Engine: DMat< M2::ARingZZpFlint >::numColumns
numColumns()
size_t DMat< M2::ARingZZpFlint >::numColumns () const inline
Definition at line 88 of file dmat-zzp-flint.hpp.
 { return nmod_mat_ncols(mArray); }
References DMat< ACoeffRing >::mArray.
Referenced by MatrixOps::addMultipleTo(), SchreyerFrame::rankUsingDenseMatrixFlint(), and MatrixOps::subtractMultipleTo().