Macaulay2 Engine: tryOutMathicCode
tryOutMathicCode()
void tryOutMathicCode ()
Monoid tests
Definition at line 1088 of file NCReduction.cpp.
{
  std::cout << "trying out mathic code!" << std::endl;
  auto Q = makeQueue();
  Q->push(3);
  Q->push(7);
  Q->push(2);
  Q->push(42);
  Q->push(7);
  while (not Q->empty())
    {
      int a = Q->pop();
      std::cout << "popped: " << a << std::endl;
    }
  std::cout << "trying out mathic code, part 2!" << std::endl;
  auto Q1 = makeQueue1();
  Q1->push(3);
  Q1->push(7);
  Q1->push(2);
  Q1->push(42);
  Q1->push(7);
  while (not Q1->empty())
    {
      int a = Q1->pop();
      std::cout << "popped: " << a << std::endl;
    }
}
References makeQueue(), and makeQueue1().
Referenced by TEST().