Macaulay2 Engine: mask_mpz_cmp_si
mask_mpz_cmp_si()
int mask_mpz_cmp_si (mpz_srcptr x, long int i) inline
Definition at line 16 of file ZZ.hpp.
 {
   return mpz_cmp_si(x, i);
 }
References x.
Referenced by RingZZ::elem_text_out(), GBRing::gbvector_remove_content_ZZ(), RingZZ::is_unit(), GBRing::lower_content_ZZ(), and RingZZ::syzygy().