Macaulay2 Engine: rawLexMonomialOrdering
rawLexMonomialOrdering()
MonomialOrdering* rawLexMonomialOrdering (int nvars, int packing)
Definition at line 532 of file monomial-ordering.cpp.
 {
   MonomialOrdering *result;
   mon_part p;
   enum MonomialOrdering_type typ;
   if (packing == 2)
     typ = MO_LEX2;
   else if (packing == 4)
     typ = MO_LEX4;
   else
     typ = MO_LEX;
   p = mo_make(typ, nvars, NULL);
   result = make_mon_order(1);
   result->array[0] = p;
   return result;
 }
References MonomialOrdering::array, make_mon_order(), MO_LEX, MO_LEX2, MO_LEX4, mo_make(), mon_part::nvars, and p.
Referenced by MonomialOrderings::Lex(), MonomialOrderings::Lex2(), and MonomialOrderings::Lex4().