Macaulay2 Engine: IM2_MonomialOrdering_to_string
IM2_MonomialOrdering_to_string()
M2_string IM2_MonomialOrdering_to_string (const MonomialOrdering * mo)
Definition at line 745 of file monomial-ordering.cpp.
 {
   int i;
   const int N = 200;
   char s[N];
   int p_ones = 0;
   M2_string result = M2_tostring("MonomialOrder => {");
   for (i = 0; i < mo->len; i++)
     {
       mon_part p = mo->array[i];
       p_ones = 0;
       if (i == 0)
         result = M2_join(result, M2_tostring("\n    "));
       else
         result = M2_join(result, M2_tostring(",\n    "));
       switch (p->type)
         {
           case MO_LEX:
             snprintf(s, N, "Lex => %d", p->nvars);
             break;
           case MO_LEX2:
             snprintf(s, N, "LexSmall => %d", p->nvars);
             break;
           case MO_LEX4:
             snprintf(s, N, "LexTiny => %d", p->nvars);
             break;
           case MO_GREVLEX:
             snprintf(s, N, "GRevLex => ");
             p_ones = 1;
             break;
           case MO_GREVLEX2:
             snprintf(s, N, "GRevLexSmall => ");
             p_ones = 1;
             break;
           case MO_GREVLEX4:
             snprintf(s, N, "GRevLexTiny => ");
             p_ones = 1;
             break;
           case MO_GREVLEX_WTS:
             snprintf(s, N, "GRevLex => ");
             break;
           case MO_GREVLEX2_WTS:
             snprintf(s, N, "GRevLexSmall => ");
             break;
           case MO_GREVLEX4_WTS:
             snprintf(s, N, "GRevLexTiny => ");
             break;
           case MO_REVLEX:
             snprintf(s, N, "RevLex => %d", p->nvars);
             break;
           case MO_WEIGHTS:
             snprintf(s, N, "Weights => ");
             break;
           case MO_LAURENT:
             snprintf(s, N, "GroupLex => %d", p->nvars);
             break;
           case MO_LAURENT_REVLEX:
             snprintf(s, N, "GroupRevLex => %d", p->nvars);
             break;
           case MO_NC_LEX:
             snprintf(s, N, "NCLex => %d", p->nvars);
             break;
           case MO_POSITION_UP:
             snprintf(s, N, "Position => Up");
             break;
           case MO_POSITION_DOWN:
             snprintf(s, N, "Position => Down");
             break;
           default:
             snprintf(s, N, "UNKNOWN");
             break;
         }
       result = M2_join(result, M2_tostring(s));
       if (p->wts != NULL)
         result = M2_join(result, intarray_to_string(p->nvars, p->wts));
       else if (p_ones)
         result = M2_join(result, ones_to_string(p->nvars));
     }
   result = M2_join(result, M2_tostring("\n    }"));
   return result;
 }
References MonomialOrdering::array, intarray_to_string(), MonomialOrdering::len, M2_join(), M2_tostring(), MO_GREVLEX, MO_GREVLEX2, MO_GREVLEX2_WTS, MO_GREVLEX4, MO_GREVLEX4_WTS, MO_GREVLEX_WTS, MO_LAURENT, MO_LAURENT_REVLEX, MO_LEX, MO_LEX2, MO_LEX4, MO_NC_LEX, MO_POSITION_DOWN, MO_POSITION_UP, MO_REVLEX, MO_WEIGHTS, ones_to_string(), and p.
Referenced by Monoid::text_out().