Macaulay2 Engine: rawPositionMonomialOrdering
rawPositionMonomialOrdering()
MonomialOrdering* rawPositionMonomialOrdering (M2_bool up_or_down)
Definition at line 633 of file monomial-ordering.cpp.
 {
   mon_part p =
       mo_make((up_or_down ? MO_POSITION_UP : MO_POSITION_DOWN), 0, nullptr);
   MonomialOrdering *result = make_mon_order(1);
   result->array[0] = p;
   return result;
 }
References MonomialOrdering::array, make_mon_order(), mo_make(), MO_POSITION_DOWN, MO_POSITION_UP, and p.
Referenced by MonomialOrderings::PositionDown(), and MonomialOrderings::PositionUp().