Macaulay2 Engine: RingElementGenerator::nextElement
nextElement()
template<typename RingType > ring_elem RingElementGenerator< RingType >::nextElement () inline
Definition at line 45 of file RingTest.hpp.
{ return getElement<RingType>(mRing, ++mNext); }
References RingElementGenerator< RingType >::mNext, and RingElementGenerator< RingType >::mRing.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), testRingAdd(), testRingAxioms(), testRingDivide(), testRingGCD(), testRingNegate(), testRingPower(), testRingRemainder(), testRingSubtract(), and testRingSyzygy().