Macaulay2 Engine: checkGaloisFieldInput
checkGaloisFieldInput()
static const PolynomialRing* checkGaloisFieldInput (const RingElement * f) static
Definition at line 56 of file aring.cpp.
 {
   // Check that the ring R of f is a polynomial ring in one var over a ZZ/p
   // Check that f is monic
   // If any of these fail, then return 0.
   const PolynomialRing *R = f->get_ring()->cast_to_PolynomialRing();
   if (R == nullptr)
     {
       ERROR("expected poly ring of the form ZZ/p[x]/(f)");
       return nullptr;
     }
   if (R->n_vars() != 1)
     {
       ERROR("expected poly ring of the form ZZ/p[x]/(f)");
       return nullptr;
     }
   if (R->n_quotients() != 1)
     {
       ERROR("expected poly ring of the form ZZ/p[x]/(f)");
       return nullptr;
     }
   if (R->characteristic() == 0)
     {
       ERROR("expected poly ring of the form ZZ/p[x]/(f)");
       return nullptr;
     }
   return R;
 }
References Ring::cast_to_PolynomialRing(), Ring::characteristic(), ERROR(), RingElement::get_ring(), PolynomialRing::n_quotients(), and PolynomialRing::n_vars().
Referenced by rawARingGaloisField1(), rawARingGaloisFieldFlintBig(), and rawARingGaloisFieldFlintZech().