Macaulay2 Engine: rawARingTower3
rawARingTower3()
const Ring* rawARingTower3 (const Ring * R1, engine_RawRingElementArray eqns)
Definition at line 346 of file aring.cpp.
 {
   try
     {
       const M2::ConcreteRing<M2::ARingTower> *K =
           dynamic_cast<const M2::ConcreteRing<M2::ARingTower> *>(R1);
       if (K == nullptr)
         {
           ERROR("expected a tower ring");
           return nullptr;
         }
       const M2::ARingTower &A = K->ring();
       std::vector<M2::ARingTower::ElementType> extensions;
       for (int i = 0; i < eqns->len; i++)
         {
           const RingElement *f = eqns->array[i];
           M2::ARingTower::ElementType f1;
           if (f->get_ring() != R1)
             {
               ERROR("extension element has incorrect base ring");
               return nullptr;
             }
           A.from_ring_elem(f1, f->get_value());
           extensions.push_back(f1);
         }
       M2::ARingTower *T = M2::ARingTower::create(A, extensions);
       return M2::ConcreteRing<M2::ARingTower>::create(
           std::unique_ptr<M2::ARingTower>(T));
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References M2::ARingTower::create(), M2::ConcreteRing< RingType >::create(), ERROR(), M2::ARingTower::from_ring_elem(), RingElement::get_ring(), RingElement::get_value(), M2::ConcreteRing< RingType >::ring(), and T.