Macaulay2 Engine: res_comp::make
make()
Matrix * res_comp::make (int i) const
Definition at line 1388 of file res-a1.cpp.
 {
   const FreeModule *F = free_of(level - 1);
   const FreeModule *G = free_of(level);
   MatrixConstructor result(F, G, nullptr);
   int n = 0;
   if (G == nullptr) return result.to_matrix();
   res_level *lev = resn[level];
   for (int j = 0; j < lev->bin.size(); j++)
     {
       res_degree *mypairs = lev->bin[j];
       for (res_pair *p = mypairs->first; p != nullptr; p = p->next)
         result.set_column(n++, R->to_vector(p->syz, F));
     }
   return result.to_matrix();
 }
References res_level::bin, res_degree::first, free_of(), G, p, R, resn, MatrixConstructor::set_column(), MatrixConstructor::to_matrix(), and res_poly::to_vector().