Macaulay2 Engine: res_comp::merge_compares
merge_compares()
res_pair * res_comp::merge_compares (res_pair * f, res_pair * g) const private
Definition at line 511 of file res-a1.cpp.
 {
   if (g == nullptr) return f;
   if (f == nullptr) return g;
   res_pair head;
   res_pair *result = &head;
   while (1) switch (compare_compares(f, g))
       {
         case -1:
           result->next_compare = g;
           result = result->next_compare;
           g = g->next_compare;
           if (g == nullptr)
             {
               result->next_compare = f;
               return head.next_compare;
             }
           break;
         case 1:
           result->next_compare = f;
           result = result->next_compare;
           f = f->next_compare;
           if (f == nullptr)
             {
               result->next_compare = g;
               return head.next_compare;
             }
           break;
         case 0:
           assert(0);
       }
 }
References compare_compares(), and res_pair::next_compare.
Referenced by set_compare_nums(), and sort_compares().