Macaulay2 Engine: res_comp::minimal_free_of
minimal_free_of()
const FreeModule * res_comp::minimal_free_of (int i) const
Definition at line 1363 of file res-a1.cpp.
 {
   FreeModule *result;
   if (i == 0) return generator_matrix->rows();
   result = P->make_FreeModule();
   if (i < 0 || i > length_limit) return result;
   monomial deg = P->degree_monoid()->make_one();
   int nminimals = 0;
   res_level *lev = resn[i];
   for (int j = 0; j < lev->bin.size(); j++)
     {
       res_degree *mypairs = lev->bin[j];
       for (res_pair *p = mypairs->first; p != nullptr; p = p->next)
         if (p->syz_type == SYZ_MINIMAL)
           {
             multi_degree(p, deg);
             result->append(deg);
             p->minimal_me = nminimals++;
           }
     }
   P->degree_monoid()->remove(deg);
   return result;
 }
References FreeModule::append(), res_level::bin, Ring::degree_monoid(), res_degree::first, generator_matrix, length_limit, Ring::make_FreeModule(), Monoid::make_one(), multi_degree(), p, P, Monoid::remove(), resn, Matrix::rows(), and SYZ_MINIMAL.
Referenced by get_free(), and make_minimal().