Macaulay2 Engine: res_comp::get_betti
get_betti()
M2_arrayint res_comp::get_betti (int type) const virtual
Implements ResolutionComputation.
Definition at line 1179 of file res-a1.cpp.
 {
   int lo = low_degree();
   int hi = high_degree();
   int len = (type == 0 ? length_limit : max_level());
   int *bettis;
   betti_init(lo, hi, len, bettis);
   for (int d = lo; d <= hi; d++)
     for (int lev = 0; lev <= len; lev++)
       {
         int val = 0;
         switch (type)
           {
             case 0:
               val = n_minimal(lev, d);
               break;
             case 1:
               val = n_pairs(lev, d);
               break;
             case 2:
               val = n_left(lev, d);
               break;
             case 3:
               val = n_monoms(lev, d);
               break;
             case 4:
               ERROR(
                   "cannot use Minimize=>true unless "
                   "res(...,FastNonminimal=>true) was used");
               return nullptr;
             default:
               val = -1;
               break;
           }
         bettis[lev + (len + 1) * (d - lo)] = val;
       }
   M2_arrayint result = betti_make(lo, hi, len, bettis);
   freemem(bettis);
   return result;
 }
References ResolutionComputation::betti_init(), ResolutionComputation::betti_make(), ERROR(), freemem(), high_degree(), length_limit, low_degree(), max_level(), n_left(), n_minimal(), n_monoms(), and n_pairs().
Referenced by betti_minimal(), betti_nmonoms(), betti_remaining(), and betti_skeleton().