Macaulay2 Engine: res_comp::reduce_minimal
reduce_minimal()
void res_comp::reduce_minimal (int x, resterm *& f, gc_vector< res_pair * > & elems) const private
Definition at line 1410 of file res-a1.cpp.
 {
   monomial MINIMAL_mon = ALLOCATE_MONOMIAL(monom_size);
   // Reduce any components of 'f' that correspond to non minimal syzygies.
   const resterm *tm;
   for (int i = x - 1; i >= 0; i--)
     {
       res_pair *p = elems[i];
       if (p->syz_type == SYZ_NOT_MINIMAL)
         while ((tm = R->component_occurs_in(p->pivot_term->comp, f)) != nullptr)
           {
             // Subtract the proper multiple to f.  f = ... + c m e_y + ...
             // and                                 p = ... + d n e_y
             // where n|m.  So we want to compute f -= c/d m/n p.
             ring_elem c =
                 K->divide(tm->coeff, p->pivot_term->coeff);  // exact division
             // MES: is the following line actually needed?
             M->divide(tm->monom, p->pivot_term->monom, MINIMAL_mon);
             if (p->stripped_syz == nullptr) p->stripped_syz = R->strip(p->syz);
             R->subtract_multiple_to(f, c, MINIMAL_mon, p->stripped_syz);
           }
     }
 }
References ALLOCATE_MONOMIAL, resterm::coeff, res_poly::component_occurs_in(), Ring::divide(), Monoid::divide(), K, M, resterm::monom, monom_size, p, R, res_poly::strip(), res_poly::subtract_multiple_to(), SYZ_NOT_MINIMAL, and x.
Referenced by make_minimal().