Macaulay2 Engine: res_comp::insert_res_pair
insert_res_pair()
void res_comp::insert_res_pair (int level, res_pair * p) private
Definition at line 288 of file res-a1.cpp.
 {
   // First determine the degree of 'p':
   int deg = degree(p) - level;
   res_degree *mypairs = make_degree_set(level, deg);
   p->next = mypairs->first;
   mypairs->first = p;
   if (level > 1)
     {
       resn[level]->npairs++;
       resn[level]->nleft++;
       mypairs->nleft++;
       mypairs->npairs++;
       npairs++;
       nleft++;
     }
   else
     {
       gc_vector<int> vp;
       M->to_varpower(p->syz->monom, vp);
       search_mi[p->syz->comp->me]->insert_minimal(new Bag(p, vp));
     }
 }
References degree(), res_degree::first, M, make_degree_set(), res_degree::nleft, nleft, res_degree::npairs, npairs, p, resn, search_mi, and Monoid::to_varpower().
Referenced by handle_gen(), new_pairs(), reduce(), and reduce_level_one().