Macaulay2 Engine: res_comp::new_res_pair
new_res_pair() [2/4]
res_pair * res_comp::new_res_pair (int i) private
Definition at line 243 of file res-a1.cpp.
 {
   res_pair *p = new_res_pair();  // Fills in almost all fields
   p->syz_type = SYZ_GEN;
   p->me = component_number++;
   p->compare_num = i;
   p->syz = R->from_vector(base_components, (*generator_matrix)[i]);
   p->base_monom = M->make_new(p->syz->monom);
   p->base_comp = p->syz->comp;
   p->first = p->base_comp;
   p->mi = new MonomialIdeal(P, mi_stash);
   return p;
 }
References base_components, component_number, res_poly::from_vector(), generator_matrix, M, Monoid::make_new(), mi_stash, new_res_pair(), p, P, R, and SYZ_GEN.