Macaulay2 Engine: res_comp::find_ring_divisor
find_ring_divisor()
int res_comp::find_ring_divisor (const_exponents exp, ring_elem & result) const private
Definition at line 710 of file res-a1.cpp.
 {
   if (!P->is_quotient_ring()) return 0;
   Bag *b;
   if (!P->get_quotient_monomials()->search_expvector(exp, b)) return 0;
   result.poly_val = P->quotient_element(b->basis_elem());
   return 1;
 }
References int_bag::basis_elem(), and mpfr::exp().
Referenced by reduce(), reduce_gen(), and reduce_level_one().