Macaulay2 Engine: res_comp::get_degree_set
get_degree_set()
res_degree * res_comp::get_degree_set (int level, int d) const private
Definition at line 200 of file res-a1.cpp.
{
  if (level < 0 || level >= resn.size()) return nullptr;
  res_level *lev = resn[level];
  d -= lodegree;
  if (d < 0 || d >= lev->bin.size()) return nullptr;
  return lev->bin[d];
}
References res_level::bin.
Referenced by gens(), n_left(), n_minimal(), n_monoms(), n_pairs(), pairs(), reductions(), set_compare_nums(), and sort_pairs().