Macaulay2 Engine: res_comp::reduce_gen
reduce_gen()
void res_comp::reduce_gen (resterm *& f) const private
Definition at line 844 of file res-a1.cpp.
 {
   exponents_t REDUCE_exp = ALLOCATE_EXPONENTS(exp_size);
   monomial REDUCE_mon = ALLOCATE_MONOMIAL(monom_size);
   res_pair *q;
   ring_elem rg;
   Bag *b;
   while (f != nullptr)
     {
       M->divide(f->monom, f->comp->base_monom, REDUCE_mon);
       M->to_expvector(REDUCE_mon, REDUCE_exp);
       if (find_ring_divisor(REDUCE_exp, rg))
         {
           // Subtract off f, leave fsyz alone
           Nterm *r = rg;
           M->divide(f->monom, r->monom, REDUCE_mon);
           R->ring_subtract_multiple_to(f, f->coeff, REDUCE_mon, f->comp, rg);
         }
       else if (search_mi[f->comp->me]->search_expvector(REDUCE_exp, b))
         {
           q = reinterpret_cast<res_pair *>(b->basis_ptr());
           M->divide(f->monom, q->syz->monom, REDUCE_mon);
           R->subtract_multiple_to(f, f->coeff, REDUCE_mon, q->syz);
         }
       else
         break;  // MES: possibly auto reduce further...
     }
 }
References ALLOCATE_EXPONENTS, ALLOCATE_MONOMIAL, res_pair::base_monom, int_bag::basis_ptr(), resterm::coeff, resterm::comp, Monoid::divide(), exp_size, find_ring_divisor(), M, res_pair::me, resterm::monom, Nterm::monom, monom_size, R, res_poly::ring_subtract_multiple_to(), search_mi, res_poly::subtract_multiple_to(), res_pair::syz, and Monoid::to_expvector().
Referenced by handle_gen().