Macaulay2 Engine: res_comp::skeleton_init
skeleton_init()
void res_comp::skeleton_init (gc_vector< res_pair * > & reslevel)
Definition at line 1473 of file res-a1.cpp.
 {
   // Do level 0
   res_pair *pp = nullptr;
   for (auto p = base_components.rbegin(); p != base_components.rend(); ++p)
     {
       (*p)->next = pp;
       pp = *p;
     }
   reslevel.push_back(pp);
   // Do level 1
   pp = nullptr;
   for (auto i = 0; i < generator_matrix->n_cols(); i++)
     if ((*generator_matrix)[i] != nullptr)
       {
         res_pair *p = new_res_pair(i);  // Makes a generator 'pair'
         p->next = pp;
         pp = p;
       }
   reslevel.push_back(pp);
 }
References base_components, generator_matrix, Matrix::n_cols(), new_res_pair(), res_pair::next, and p.
Referenced by skeleton().