Macaulay2 Engine: res_comp::handle_pair
handle_pair()
void res_comp::handle_pair (res_pair * p) private
Definition at line 1075 of file res-a1.cpp.
 {
   if (p->syz_type == SYZ_NOT_NEEDED) return;
   resterm *f = s_pair(p);
   res_pair *q;
   if (n_level == 2)
     q = reduce_level_one(f, p->syz, p->pivot_term);
   else
     q = reduce(f, p->syz, p->pivot_term);
   if (f == NULL)
     {
       // minimal syzygy
       p->syz_type = SYZ_MINIMAL;
       p->minimal_me = resn[n_level]->nminimal++;
       nminimal++;
       if (M2_gbTrace >= 2) emit_wrapped("z");
     }
   else
     {
       R->make_monic(f);
       p->syz_type = SYZ_NOT_MINIMAL;
       // non-minimal syzygy
       q->syz = f;
       q->syz_type = SYZ_NOT_NEEDED;
       if (M2_gbTrace >= 2) emit_wrapped("m");
       // MES: need to decrement nleft for 'q'.
     }
 }
References emit_wrapped(), M2_gbTrace, res_poly::make_monic(), n_level, nminimal, p, R, reduce(), reduce_level_one(), resn, s_pair(), res_pair::syz, SYZ_MINIMAL, SYZ_NOT_MINIMAL, SYZ_NOT_NEEDED, and res_pair::syz_type.