Macaulay2 Engine: res_comp::text_out
text_out() [1/3]
void res_comp::text_out (buffer & o) const virtual
Implements ResolutionComputation.
Definition at line 1300 of file res-a1.cpp.
 {
   o << "level/degree = " << n_level << '/' << n_degree << newline;
   o << "--- The total number of pairs in each level/slanted degree -----"
     << newline;
   M2_arrayint a = betti_skeleton();
   betti_display(o, a);
   o << "--- The number of pairs left to compute ------------------------"
     << newline;
   a = betti_remaining();
   betti_display(o, a);
   o << "--- (Lower bounds of) the minimal betti numbers ----------" << newline;
   a = betti_minimal();
   betti_display(o, a);
   if (M2_gbTrace >= 1)
     {
       o << "--- Number of monomials  ---------------------------------"
         << newline;
       a = betti_nmonoms();
       betti_display(o, a);
     }
   // If the printlevel is high enough, display each element
   if (M2_gbTrace >= 2)
     for (int lev = 0; lev < resn.size(); lev++)
       {
         o << "---- level " << lev << " ----" << newline;
         for (int i = 0; i < resn[lev]->bin.size(); i++)
           {
             res_degree *mypairs = resn[lev]->bin[i];
             if (mypairs == NULL) continue;
             for (res_pair *p = mypairs->first; p != NULL; p = p->next)
               {
                 o.put(i, 4);
                 o << ' ';
                 text_out(o, p);
               }
           }
       }
 }
References ResolutionComputation::betti_display(), betti_minimal(), betti_nmonoms(), betti_remaining(), betti_skeleton(), res_degree::first, M2_gbTrace, n_degree, n_level, newline, p, buffer::put(), resn, and text_out().