Macaulay2 Engine: res_comp::remove_res_degree
remove_res_degree()
void res_comp::remove_res_degree (res_degree * p) private
Definition at line 147 of file res-a1.cpp.
{
  if (p == nullptr) return;
  while (p->first != nullptr)
    {
      res_pair *tmp = p->first;
      p->first = tmp->next;
      remove_res_pair(tmp);
    }
  freemem(p);
}
References freemem(), res_pair::next, p, and remove_res_pair().
Referenced by remove_res_level().