Macaulay2 Engine: res_comp::degree
degree()
int res_comp::degree (const res_pair * q) const private
Definition at line 273 of file res-a1.cpp.
 {
   int result = M->primary_degree(p->base_monom);
   result += generator_matrix->rows()->primary_degree(p->base_comp->me);
   return result;
 }
References generator_matrix, M, p, Monoid::primary_degree(), FreeModule::primary_degree(), and Matrix::rows().
Referenced by compare_res_pairs(), insert_res_pair(), skeleton_maxdegree(), and skeleton_stats().