Macaulay2 Engine: res_comp::remove_res_level
remove_res_level()
void res_comp::remove_res_level (res_level * lev) private
Definition at line 159 of file res-a1.cpp.
 {
   if (lev == NULL) return;
   int i;
   for (i = 0; i < lev->bin.size(); i++)
     {
       res_degree *mypairs = lev->bin[i];
       remove_res_degree(mypairs);
     }
   freemem(lev);
 }
References res_level::bin, freemem(), and remove_res_degree().
Referenced by ~res_comp().