Macaulay2 Engine: res_comp::set_compare_nums
set_compare_nums()
void res_comp::set_compare_nums (int level, int deg) private
Definition at line 569 of file res-a1.cpp.
 {
   if (level == 0) return;
   // This assumes that the pairs at level 'level' are ordered already
   // and that all previous pairs at this level (i.e. of lower degree)
   // are sorted on the 'next_compare' field, in ascending order
   // First, place the new pairs onto a 'next_compare' list, sort, and then merge
   // them into the previous list, using (first->compare_num, me) in ascending
   // order.
   res_degree *mypairs = get_degree_set(level, deg);
   if (mypairs == NULL) return;
   res_pair *p;
   res_pair *compare_num_list = mypairs->first;
   for (p = mypairs->first; p != NULL; p = p->next)
     {
       p->next_compare = p->next;
       p->me = next_me_number++;
     }
   sort_compares(compare_num_list);
   resn[level]->compare_num_list =
       merge_compares(resn[level]->compare_num_list, compare_num_list);
   int next = 0;
   for (p = resn[level]->compare_num_list; p != NULL; p = p->next_compare)
     p->compare_num = next++;
 }
References res_degree::first, get_degree_set(), merge_compares(), next_me_number, p, resn, and sort_compares().
Referenced by sort_pairs().