Macaulay2 Engine: res_comp::skeleton_stats
skeleton_stats()
void res_comp::skeleton_stats (const gc_vector< res_pair * > & reslevel)
Definition at line 1607 of file res-a1.cpp.
 {
   buffer o;
   int level;
   int maxlevel = reslevel.size() - 1;
   int maxdegree = skeleton_maxdegree(reslevel);  // max slanted degree
   int *bettis = newarray_atomic_clear(int, (maxlevel + 1) * (maxdegree + 1));
   for (level = 0; level < reslevel.size(); level++)
     {
       for (res_pair *p = reslevel[level]; p != nullptr; p = p->next)
         {
           int d = degree(p);
           d -= level;
           d -= lodegree;
           bettis[level + (maxlevel + 1) * d] += 1;
         }
     }
   // Now make an arrayint so that we may just use betti_display
   int lo = lodegree;
   int hi = maxdegree;
   int len = maxlevel;
   int totallen = 3 + (hi - lo + 1) * (len + 1);
   M2_arrayint betti = M2_makearrayint(totallen);
   betti->array[0] = lo;
   betti->array[1] = hi;
   betti->array[2] = len;
   int next = 3;
   for (int d = 0; d <= maxdegree - lodegree; d++)
     for (level = 0; level <= maxlevel; level++)
       betti->array[next++] = bettis[level + (maxlevel + 1) * d];
   betti_display(o, betti);
   freemem(bettis);
   for (level = 0; level <= maxlevel; level++)
     {
       o << "---- level " << level << " ----" << newline;
       for (res_pair *p = reslevel[level]; p != nullptr; p = p->next)
         {
           int d = degree(p);
           o.put(d, 4);
           o << ' ';
           text_out(o, p);
         }
     }
   emit(o.str());
 }
References ResolutionComputation::betti_display(), degree(), emit(), freemem(), lodegree, M2_makearrayint(), newarray_atomic_clear, newline, p, buffer::put(), skeleton_maxdegree(), buffer::str(), and text_out().
Referenced by skeleton().