Macaulay2 Engine: res_comp::make_minimal
make_minimal()
Matrix * res_comp::make_minimal (int i) const
Definition at line 1438 of file res-a1.cpp.
 {
   const FreeModule *F = minimal_free_of(i - 1);
   const FreeModule *G = minimal_free_of(i);
   MatrixConstructor result(F, G, nullptr);
   if (i < 0 || i > length_limit) return result.to_matrix();
   VECTOR(res_pair *) elems;
   res_level *lev = resn[i];
   for (int j = 0; j < lev->bin.size(); j++)
     for (res_pair *p = lev->bin[j]->first; p != nullptr; p = p->next)
       elems.push_back(p);
   int thisx = 0;
   for (int x = 0; x < elems.size(); x++)
     {
       res_pair *p = elems[x];
       if (p->syz_type == SYZ_MINIMAL)
         {
           if (p->stripped_syz == nullptr)
             {
               p->stripped_syz = R->strip(p->syz);
               reduce_minimal(x, p->stripped_syz, elems);
             }
           result.set_column(thisx++, R->to_vector(p->stripped_syz, F, 1));
         }
     }
   return result.to_matrix();
 }
References res_level::bin, G, length_limit, minimal_free_of(), p, R, reduce_minimal(), resn, MatrixConstructor::set_column(), res_poly::strip(), SYZ_MINIMAL, MatrixConstructor::to_matrix(), res_poly::to_vector(), VECTOR(), and x.
Referenced by get_matrix().