Macaulay2 Engine: res_comp::skeleton
skeleton()
void res_comp::skeleton (int strategy)
Definition at line 1658 of file res-a1.cpp.
 {
   int level;
   VECTOR(res_pair *) reslevel;
   // First, set reslevel[0], reslevel[1].
   skeleton_init(reslevel);
   // Now loop through each level, until the length limit is hit,
   // or there are no new pairs
   for (level = 1; level < reslevel.size(); level++)
     {
       // Sort the pairs in the current level:
       res_pair *pp = reslevel[level];
       if (pp == nullptr) break;
       compare_type = strategy;
       sort_res_pairs(pp);
       reslevel[level] = pp;
       compare_type = 0;
       // Now compute the pairs at the next level
       res_pair head, *ptrhead;
       head.next = nullptr;
       ptrhead = &head;
       for (res_pair *p = pp; p != nullptr; p = p->next) skeleton_pairs(ptrhead, p);
       reslevel.push_back(head.next);
     }
   // Now display the skeleton and stats on it
   skeleton_stats(reslevel);
 }
References compare_type, res_pair::next, p, skeleton_init(), skeleton_pairs(), skeleton_stats(), sort_res_pairs(), and VECTOR().