Macaulay2 Engine: res_comp::gens
gens()
enum ComputationStatusCode res_comp::gens (int deg) private
Definition at line 964 of file res-a1.cpp.
{
  if (M2_gbTrace >= 5)
    {
      buffer o;
      o << "gens(" << deg << ")" << newline;
      emit(o.str());
    }
  // preconditions: reductions(2,deg), gens(deg-1)
  res_pair *p;
  res_degree *mypairs = get_degree_set(1, deg);
  if (mypairs != nullptr)
    {
      while ((p = mypairs->next_gen) != nullptr)
        {
          mypairs->next_gen = p->next;
          handle_gen(p);  // Consumes 'p'
          mypairs->nleft--;
          resn[1]->nleft--;
          nleft--;
          if (stop_.pair_limit > 0 && npairs - nleft >= stop_.pair_limit)
            return COMP_DONE_PAIR_LIMIT;
          if (stop_.syzygy_limit > 0 && nminimal >= stop_.syzygy_limit)
            return COMP_DONE_SYZYGY_LIMIT;
          if (system_interrupted()) return COMP_INTERRUPTED;
        }
      sort_pairs(1, deg);  // Sort the level 1 GB elements
    }
  return COMP_COMPUTING;
}
References COMP_COMPUTING, COMP_DONE_PAIR_LIMIT, COMP_DONE_SYZYGY_LIMIT, COMP_INTERRUPTED, emit(), get_degree_set(), handle_gen(), M2_gbTrace, newline, res_degree::next_gen, res_degree::nleft, nleft, nminimal, npairs, p, StopConditions::pair_limit, resn, sort_pairs(), Computation::stop_, buffer::str(), system_interrupted(), and StopConditions::syzygy_limit.
Referenced by start_computation().