Macaulay2 Engine: res_comp::multi_degree
multi_degree()
void res_comp::multi_degree (const res_pair * q, monomial result) const private
Definition at line 280 of file res-a1.cpp.
 {
   // MES: Is this correct?
   M->multi_degree(p->base_monom, deg);
   M->degree_monoid()->mult(
       deg, generator_matrix->rows()->degree(p->base_comp->me), deg);
 }
References FreeModule::degree(), Monoid::degree_monoid(), generator_matrix, M, Monoid::mult(), Monoid::multi_degree(), p, and Matrix::rows().
Referenced by free_of(), and minimal_free_of().