Macaulay2 Engine: res_comp::compare_res_pairs
compare_res_pairs()
int res_comp::compare_res_pairs (res_pair * f, res_pair * g) const private
Definition at line 318 of file res-a1.cpp.
 {
   exponents_t EXP1, EXP2;
   int cmp, df, dg, i;
   //  if (f->compare_num < g->compare_num) return 1;
   //  if (f->compare_num > g->compare_num) return -1;
   // MES: what to do if we obtain equality? Here is one way:
   switch (compare_type)
     {
       case 1:
         // Compare using descending lexicographic order
         // on the usual set of variables
         EXP1 = ALLOCATE_EXPONENTS(exp_size);
         EXP2 = ALLOCATE_EXPONENTS(exp_size);
         M->to_expvector(f->base_monom, EXP1);
         M->to_expvector(g->base_monom, EXP2);
         for (i = 0; i < M->n_vars(); i++)
           {
             if (EXP1[i] < EXP2[i]) return -1;
             if (EXP1[i] > EXP2[i]) return 1;
           }
         return 0;
       case 2:
         // Compare using ascending lexicographic order
         // on the usual set of variables
         EXP1 = ALLOCATE_EXPONENTS(exp_size);
         EXP2 = ALLOCATE_EXPONENTS(exp_size);
         M->to_expvector(f->base_monom, EXP1);
         M->to_expvector(g->base_monom, EXP2);
         for (i = 0; i < M->n_vars(); i++)
           {
             if (EXP1[i] < EXP2[i]) return 1;
             if (EXP1[i] > EXP2[i]) return -1;
           }
         return 0;
       case 3:
         // Compare using descending lexicographic order
         // on the reversed set of variables
         EXP1 = ALLOCATE_EXPONENTS(exp_size);
         EXP2 = ALLOCATE_EXPONENTS(exp_size);
         M->to_expvector(f->base_monom, EXP1);
         M->to_expvector(g->base_monom, EXP2);
         for (i = M->n_vars() - 1; i >= 0; i--)
           {
             if (EXP1[i] < EXP2[i]) return -1;
             if (EXP1[i] > EXP2[i]) return 1;
           }
         return 0;
       case 4:
         // Compare using ascending lexicographic order
         // on the reversed set of variables
         EXP1 = ALLOCATE_EXPONENTS(exp_size);
         EXP2 = ALLOCATE_EXPONENTS(exp_size);
         M->to_expvector(f->base_monom, EXP1);
         M->to_expvector(g->base_monom, EXP2);
         for (i = M->n_vars() - 1; i >= 0; i--)
           {
             if (EXP1[i] < EXP2[i]) return 1;
             if (EXP1[i] > EXP2[i]) return -1;
           }
         return 0;
       case 5:
         // The original method, but with degree added, since
         // the new skeleton code doesn't just sort elements of
         // the same degree.
         df = degree(f);
         dg = degree(g);
         if (df > dg) return -1;
         if (df < dg) return 1;
         cmp = M->compare(f->base_monom, g->base_monom);
         if (cmp != 0) return cmp;
         cmp = f->first->compare_num - g->first->compare_num;
         if (cmp < 0) return 1;
         if (cmp > 0) return -1;
         return 0;
       default:
         cmp = M->compare(f->base_monom, g->base_monom);
         if (cmp != 0) return cmp;
         cmp = f->first->compare_num - g->first->compare_num;
         if (cmp < 0) return 1;
         if (cmp > 0) return -1;
         return 0;
     }
   return 0;
 }
References ALLOCATE_EXPONENTS, res_pair::base_monom, Monoid::compare(), res_pair::compare_num, compare_type, degree(), exp_size, res_pair::first, M, Monoid::n_vars(), and Monoid::to_expvector().
Referenced by merge_res_pairs().