Macaulay2 Engine: res_comp::remove_res_pair
remove_res_pair()
void res_comp::remove_res_pair (res_pair * p) private
Definition at line 137 of file res-a1.cpp.
 {
   if (p == NULL) return;
   delete p->mi;
   R->remove(p->syz);
   R->remove(p->stripped_syz);
   M->remove(p->base_monom);
   res_pair_stash->delete_elem(p);
 }
References stash::delete_elem(), M, p, R, Monoid::remove(), res_poly::remove(), and res_pair_stash.
Referenced by handle_gen(), and remove_res_degree().