Macaulay2 Engine: res_comp::new_pairs
new_pairs()
void res_comp::new_pairs (res_pair * p) private
Definition at line 606 of file res-a1.cpp.
 {
   gc_vector<Bag*> elems;
   gc_vector<int> vp;  // This is 'p'.
   gc_vector<int> thisvp;
   monomial PAIRS_mon = ALLOCATE_MONOMIAL(monom_size);
   if (M2_gbTrace >= 10)
     {
       buffer o;
       o << "Computing pairs with first = " << p->me << newline;
       emit(o.str());
     }
   M->divide(p->base_monom, p->first->base_monom, PAIRS_mon);
   M->to_varpower(PAIRS_mon, vp);
   // First add in syzygies arising from exterior variables
   // At the moment, there are none of this sort.
   if (P->is_skew_commutative())
     {
       exponents_t exp = newarray_atomic(int, M->n_vars());
       varpower::to_expvector(M->n_vars(), vp.data(), exp);
       int nskew = P->n_skew_commutative_vars();
       for (int v = 0; v < nskew; v++)
         {
           int w = P->skew_variable(v);
           if (exp[w] > 0)
             {
               thisvp.resize(0);
               varpower::var(w, 1, thisvp);
               Bag *b = new Bag(static_cast<void *>(0), thisvp);
               elems.push_back(b);
             }
         }
       freemem(exp);
     }
   // Second, add in syzygies arising from the base ring, if any
   // The baggage of each of these is NULL
   if (P->is_quotient_ring())
     {
       const MonomialIdeal *Rideal = P->get_quotient_monomials();
       for (Bag& a : *Rideal)
         {
           // Compute (P->quotient_ideal->monom : p->monom)
           // and place this into a varpower and Bag, placing
           // that into 'elems'
           thisvp.resize(0);
           varpower::quotient(a.monom().data(), vp.data(), thisvp);
           if (varpower::is_equal(a.monom().data(), thisvp.data()))
             continue;
           Bag *b = new Bag(static_cast<void *>(0), thisvp);
           elems.push_back(b);
         }
     }
   // Third, add in syzygies arising from previous elements of this same level
   // The baggage of each of these is their corresponding res_pair
   MonomialIdeal *mi_orig = p->first->mi;
   for (Bag& a : *mi_orig)
     {
       Bag *b = new Bag(a.basis_ptr());
       varpower::quotient(a.monom().data(), vp.data(), b->monom());
       elems.push_back(b);
     }
   // Make this monomial ideal, and then run through each minimal generator
   // and insert into the proper degree. (Notice that sorting does not
   // need to be done yet: only once that degree is about to begin.
   mi_orig->insert_minimal(new Bag(p, vp));
   VECTOR(Bag *) rejects;
   MonomialIdeal *mi = new MonomialIdeal(P, elems, rejects, mi_stash);
   for (auto& b : rejects)
     delete b;
   if (M2_gbTrace >= 11) mi->debug_out(1);
   for (Bag& a : *mi)
     {
       res_pair *second = reinterpret_cast<res_pair *>(a.basis_ptr());
       res_pair *q = new_res_pair(SYZ_S_PAIR, p, second);
       // That set most fields except base_monom:
       M->from_varpower(a.monom().data(), q->base_monom);
       M->mult(q->base_monom, p->base_monom, q->base_monom);
       insert_res_pair(n_level, q);
     }
   delete mi;
 }
References ALLOCATE_MONOMIAL, res_pair::base_monom, MonomialIdeal::debug_out(), Monoid::divide(), emit(), mpfr::exp(), freemem(), Monoid::from_varpower(), PolynomialRing::get_quotient_monomials(), MonomialIdeal::insert_minimal(), insert_res_pair(), ExponentList< E, L >::is_equal(), PolynomialRing::is_quotient_ring(), PolynomialRing::is_skew_commutative(), M, M2_gbTrace, mi_stash, int_bag::monom(), monom_size, Monoid::mult(), n_level, PolynomialRing::n_skew_commutative_vars(), Monoid::n_vars(), new_res_pair(), newarray_atomic, newline, p, P, ExponentList< E, L >::quotient(), PolynomialRing::skew_variable(), buffer::str(), SYZ_S_PAIR, ExponentList< E, L >::to_expvector(), Monoid::to_varpower(), ExponentList< E, L >::var(), and VECTOR().