Macaulay2 Engine: res_comp::new_res_pair
new_res_pair() [1/4]
res_pair * res_comp::new_res_pair () private
Definition at line 210 of file res-a1.cpp.
 {
   res_pair *result = reinterpret_cast<res_pair *>(res_pair_stash->new_elem());
   result->me = 0;
   result->compare_num = 0;
   result->base_monom = NULL;
   result->next = NULL;
   result->first = NULL;
   result->second = NULL;
   result->base_comp = NULL;
   result->syz_type = 0;
   result->mi2 = NULL;
   result->next_mi = NULL;
   result->syz = NULL;
   result->minimal_me = 0;
   result->pivot_term = NULL;
   result->stripped_syz = NULL;
   return result;
 }
References res_pair::base_comp, res_pair::base_monom, res_pair::compare_num, res_pair::first, res_pair::me, res_pair::mi2, res_pair::minimal_me, stash::new_elem(), res_pair::next, res_pair::next_mi, res_pair::pivot_term, res_pair_stash, res_pair::second, res_pair::stripped_syz, res_pair::syz, and res_pair::syz_type.
Referenced by initialize(), new_pairs(), new_res_pair(), reduce(), reduce_level_one(), skeleton_init(), and skeleton_pairs().