Macaulay2 Engine: res_comp::handle_gen
handle_gen()
void res_comp::handle_gen (res_pair * p) private
Definition at line 1053 of file res-a1.cpp.
 {
   reduce_gen(p->syz);
   if (p->syz != nullptr)
     {
       R->make_monic(p->syz);
       M->copy(p->syz->monom, p->base_monom);
       p->first = p->syz->comp;
       p->second = nullptr;
       p->syz_type = SYZ_MINIMAL;
       p->base_comp = p->syz->comp->base_comp;  // MES: added 7/11/97
       insert_res_pair(1, p);
       p->minimal_me = resn[1]->nminimal++;
       nminimal++;
       if (M2_gbTrace >= 2) emit_wrapped("z");
     }
   else
     {
       remove_res_pair(p);
       if (M2_gbTrace >= 2) emit_wrapped("o");
     }
 }
References Monoid::copy(), emit_wrapped(), insert_res_pair(), M, M2_gbTrace, res_poly::make_monic(), nminimal, p, R, reduce_gen(), remove_res_pair(), resn, and SYZ_MINIMAL.