Macaulay2 Engine: res_comp::initialize
initialize()
void res_comp::initialize (const Matrix * mat, int LengthLimit, int strategy) private
Definition at line 14 of file res-a1.cpp.
 {
   int i;
   P = mat->get_ring()->cast_to_PolynomialRing();
   assert(P != NULL);
   R = new res_poly(const_cast<PolynomialRing *>(P));
   M = P->getMonoid();
   K = P->getCoefficientRing();
   generator_matrix = mat;
   // These next two lines may be added next (5/2/06)
   //  res_degree_stash      = new stash("resDegree", sizeof(res_degree));
   //  res_level_stash       = new stash("resLevel", sizeof(res_level));
   res_pair_stash = new stash("respair", sizeof(res_pair));
   mi_stash = new stash("res minodes", sizeof(Nmi_node));
   for (i = 0; i <= LengthLimit; i++) resn.push_back(new res_level);
   max_degree = M->max_degree();
   length_limit = LengthLimit;
   if (mat->n_rows() > 0)
     {
       lodegree = mat->rows()->primary_degree(0);
       for (i = 1; i < mat->n_rows(); i++)
         if (lodegree > mat->rows()->primary_degree(i))
           lodegree = mat->rows()->primary_degree(i);
     }
   else
     lodegree = 0;
   for (i = 0; i < mat->n_cols(); i++)
     if (lodegree > mat->cols()->primary_degree(i) - 1)
       lodegree = mat->cols()->primary_degree(i) - 1;
   hidegree = lodegree;
   n_level = 2;
   n_degree = lodegree;
   component_number = 0;
   next_me_number = 0;
   const SchreyerOrder *S = mat->rows()->get_schreyer_order();
   for (i = 0; i < mat->n_rows(); i++)
     {
       res_pair *p = new_res_pair();
       p->me = component_number++;
       p->minimal_me = p->me;
       next_me_number++;  // this and 'component_number' should still be equal
                          // here.
       p->compare_num = i;
       if (S == nullptr)
         p->base_monom = M->make_one();
       else
         p->base_monom = M->make_new(S->base_monom(i));
       p->mi = new MonomialIdeal(P, mi_stash);
       p->syz_type = SYZ_MINIMAL;
       p->base_comp = p;
       base_components.push_back(p);
       search_mi.push_back(new MonomialIdeal(P, mi_stash));
       int d = mat->rows()->primary_degree(i);
       res_degree *mypairs = make_degree_set(0, d);
       p->next = mypairs->first;
       mypairs->first = p;
       mypairs->npairs++;
       resn[0]->npairs++;
       npairs++;
     }
   nleft = 0;
   npairs = 0;
   nminimal = 0;
   for (i = 0; i < mat->n_cols(); i++)
     if ((*mat)[i] != nullptr)
       {
         res_pair *p = new_res_pair(i);  // Makes a generator 'pair'
         int d = mat->cols()->primary_degree(i);
         res_degree *mypairs = make_degree_set(1, d - 1);
         p->next = mypairs->next_gen;
         mypairs->next_gen = p;
         mypairs->nleft++;
         mypairs->npairs++;
         resn[1]->nleft++;
         resn[1]->npairs++;
         nleft++;
         npairs++;
       }
   for (i = 0; i < base_components.size(); i++)
     {
       res_pair *p = base_components[i];
       p->compare_num = i;
     }
   exp_size = EXPONENT_BYTE_SIZE(P->n_vars());
   monom_size = MONOMIAL_BYTE_SIZE(M->monomial_size());
   compare_type = 0;
 }
References base_components, SchreyerOrder::base_monom(), Ring::cast_to_PolynomialRing(), Matrix::cols(), compare_type, component_number, exp_size, EXPONENT_BYTE_SIZE, res_degree::first, generator_matrix, Matrix::get_ring(), FreeModule::get_schreyer_order(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), hidegree, K, length_limit, lodegree, M, make_degree_set(), Monoid::make_new(), Monoid::make_one(), Monoid::max_degree(), max_degree, mi_stash, monom_size, MONOMIAL_BYTE_SIZE, Monoid::monomial_size(), Matrix::n_cols(), n_degree, n_level, Matrix::n_rows(), PolynomialRing::n_vars(), new_res_pair(), res_degree::next_gen, next_me_number, res_degree::nleft, nleft, nminimal, res_degree::npairs, npairs, p, P, FreeModule::primary_degree(), R, res_pair_stash, resn, Matrix::rows(), search_mi, and SYZ_MINIMAL.
Referenced by res_comp().