Macaulay2 Engine: res_comp::sort_pairs
sort_pairs()
void res_comp::sort_pairs (int level, int deg) private
Definition at line 481 of file res-a1.cpp.
{
  res_degree *mypairs = get_degree_set(level, deg);
  if (mypairs == nullptr) return;
  if (mypairs->is_sorted) return;
  res_pair *p = mypairs->first;
  if (p != nullptr && p->next != nullptr) sort_res_pairs(mypairs->first);
  mypairs->next_pair = mypairs->first;
  mypairs->next_new_pair = mypairs->first;
  mypairs->is_sorted = 1;
  set_compare_nums(level, deg);
}
References res_degree::first, get_degree_set(), res_degree::is_sorted, res_degree::next_new_pair, res_degree::next_pair, p, set_compare_nums(), and sort_res_pairs().
Referenced by gens(), pairs(), and reductions().