Macaulay2 Engine: res_comp::reduce_level_one
reduce_level_one()
res_pair * res_comp::reduce_level_one (resterm *& f, resterm *& fsyz, resterm *& pivot) private
Definition at line 795 of file res-a1.cpp.
 {
   // 'lastterm' is used to append the next monomial to fsyz->syz
   exponents_t REDUCE_exp = ALLOCATE_EXPONENTS(exp_size);
   monomial REDUCE_mon = ALLOCATE_MONOMIAL(monom_size);
   resterm *lastterm = (fsyz->next == NULL ? fsyz : fsyz->next);
   res_pair *q;
   ring_elem rg;
   Bag *b;
   while (f != NULL)
     {
       M->divide(f->monom, f->comp->base_monom, REDUCE_mon);
       M->to_expvector(REDUCE_mon, REDUCE_exp);
       if (find_ring_divisor(REDUCE_exp, rg))
         {
           // Subtract off f, leave fsyz alone
           Nterm *r = rg;
           M->divide(f->monom, r->monom, REDUCE_mon);
           R->ring_subtract_multiple_to(f, f->coeff, REDUCE_mon, f->comp, rg);
         }
       else if (search_mi[f->comp->me]->search_expvector(REDUCE_exp, b))
         {
           q = reinterpret_cast<res_pair *>(b->basis_ptr());
           lastterm->next = R->new_term(K->negate(f->coeff), f->monom, q);
           lastterm = lastterm->next;
           pivot = lastterm;
           if (q->syz_type == SYZ_S_PAIR) return q;  // i.e. not computed yet
           M->divide(f->monom, q->syz->monom, REDUCE_mon);
           R->subtract_multiple_to(f, f->coeff, REDUCE_mon, q->syz);
         }
       else
         {
           // level 1: monomial not seen yet
           q = new_res_pair(SYZ_S_PAIR, f);
           insert_res_pair(1, q);
           lastterm->next = R->new_term(K->negate(f->coeff), f->monom, q);
           lastterm = lastterm->next;
           pivot = lastterm;
           return q;
         }
     }
   return NULL;
 }
References ALLOCATE_EXPONENTS, ALLOCATE_MONOMIAL, res_pair::base_monom, int_bag::basis_ptr(), resterm::coeff, resterm::comp, Monoid::divide(), exp_size, find_ring_divisor(), insert_res_pair(), K, M, res_pair::me, resterm::monom, Nterm::monom, monom_size, Ring::negate(), new_res_pair(), res_poly::new_term(), resterm::next, R, res_poly::ring_subtract_multiple_to(), search_mi, res_poly::subtract_multiple_to(), res_pair::syz, SYZ_S_PAIR, res_pair::syz_type, and Monoid::to_expvector().
Referenced by handle_pair().