Macaulay2 Engine: res_comp::sort_res_pairs
sort_res_pairs()
void res_comp::sort_res_pairs (res_pair *& p) const private
Definition at line 438 of file res-a1.cpp.
 {
   // These elements are sorted in ascending 'me' values
   if (p == nullptr || p->next == nullptr) return;
   res_pair *p1 = nullptr;
   res_pair *p2 = nullptr;
   while (p != nullptr)
     {
       res_pair *tmp = p;
       p = p->next;
       tmp->next = p1;
       p1 = tmp;
       if (p == nullptr) break;
       tmp = p;
       p = p->next;
       tmp->next = p2;
       p2 = tmp;
     }
   sort_res_pairs(p1);
   sort_res_pairs(p2);
   p = merge_res_pairs(p1, p2);
 }
References merge_res_pairs(), res_pair::next, p, and p1.
Referenced by skeleton(), sort_gens(), and sort_pairs().