Macaulay2 Engine: res_comp::free_of
free_of()
const FreeModule * res_comp::free_of (int i) const
Definition at line 1341 of file res-a1.cpp.
 {
   FreeModule *result;
   result = P->make_Schreyer_FreeModule();
   if (i < 0 || i >= resn.size()) return result;
   monomial deg = P->degree_monoid()->make_one();
   int n = 0;
   res_level *lev = resn[i];
   for (int j = 0; j < lev->bin.size(); j++)
     {
       res_degree *mypairs = lev->bin[j];
       for (res_pair *p = mypairs->first; p != NULL; p = p->next)
         {
           multi_degree(p, deg);
           result->append_schreyer(deg, p->base_monom, p->compare_num);
           p->minimal_me = n++;
         }
     }
   P->degree_monoid()->remove(deg);
   return result;
 }
References FreeModule::append_schreyer(), res_level::bin, Ring::degree_monoid(), res_degree::first, Monoid::make_one(), Ring::make_Schreyer_FreeModule(), multi_degree(), p, P, Monoid::remove(), and resn.
Referenced by make().