Macaulay2 Engine: operator<<
operator<<()
std::ostream& operator<< (std::ostream & o, const FreeAlgebraElement & f)
Definition at line 19 of file FreeAlgebra.cpp.
 {
   buffer b;
   f.ring().elem_text_out(b, *f, true, false, false);
   o << b.str();
   return o;
 }
References FreeAlgebra::elem_text_out(), FreeAlgebraElement::ring(), and buffer::str().