Macaulay2 Engine: error
error()
int error ()
Definition at line 48 of file error.c.
 { return iserror; }
References iserror.
Referenced by convertToM2(), gbA::do_computation(), RingMap::eval(), M2::ARingCC::eval(), RingElement::homogenize(), IM2_RingElement_divmod(), IM2_RingElement_fraction(), IM2_RingElement_make_var(), Monomial::make(), Monomial::operator*(), RingElement::operator*(), RingElement::operator+(), RingElement::operator-(), RingElement::operator/(), Monomial::power(), RingElement::power(), rawCharSeries(), rawExtendedGCDRingElement(), rawFactorBase(), rawGCDRingElement(), rawPseudoRemainder(), rawStartComputation(), rawWeightRange(), HilbertController::setDegree(), GB_comp::start_computation(), GBinhom_comp::start_computation(), and TEST().