Macaulay2 Engine: INTERNAL_ERROR
INTERNAL_ERROR()
void INTERNAL_ERROR (const char * s, ...)
Definition at line 36 of file error.c.
 {
   char buf[MAXERROR];
   buf[0] = 0;
   va_list ap;
   va_start(ap, s);
   vsprintf(buf, s, ap);
   va_end(ap);
   fprintf(stderr, "--internal error: %s\n", buf);
   abort(); /* we should exit after an internal error, to avoid crashing */
 }
References MAXERROR.
Referenced by MatrixConstructor::append(), MatrixConstructor::compute_column_degree(), MatrixConstructor::compute_column_degrees(), PolyRingQuotient::invert(), Monoid::Monoid(), rawNonTermOrderVariables(), MatrixConstructor::set_column_degree(), and wrapperFrobbyAlexanderDual().