Macaulay2 Engine: popular_var
popular_var()
static int popular_var (const MonomialIdeal & I, int & npure, exponents_t pure, int & nhits, const_varpower & non_pure_power, int & exp_of_popular) static
Definition at line 172 of file hilb.cpp.
 {
   int k;
   npure = 0;
   int nvars = I.topvar() + 1;
   for (k = 0; k < nvars; k++) pure[k] = -1;
   exponents_t hits = newarray_atomic_clear(int, nvars);
   exponents_t minnonzero = newarray_atomic(int, nvars);
   for (k = 0; k < nvars; k++) hits[k] = 0;
   for (k = 0; k < nvars; k++) minnonzero[k] = MAX_EXP;
   non_pure_power = nullptr;
   for (Bag& a : I)
     {
       const_varpower m = a.monom().data();
       index_varpower j = m;
       assert(j.valid());  // The monomial cannot be '1'.
       int v = j.var();
       int e = j.exponent();
       ++j;
       if (j.valid())
         {
           non_pure_power = m;
           for (; j.valid(); ++j)
             {
               v = j.var();
               e = j.exponent();
               if (minnonzero[v] > e) minnonzero[v] = e;
               hits[v]++;
             }
         }
       else
         {
           if (pure[v] == -1)
             {
               npure++;
               pure[v] = e;
             }
           else if (pure[v] > e)
             pure[v] = e;
         }
     }
   int popular = 0;
   for (k = 1; k < nvars; k++)
     if (hits[k] > hits[popular]) popular = k;
   nhits = hits[popular];
   exp_of_popular = minnonzero[popular];
   freemem(hits);
   freemem(minnonzero);
   return popular;
 }
References ExponentListIterator< E, L >::exponent(), freemem(), MAX_EXP, newarray_atomic, newarray_atomic_clear, MonomialIdeal::topvar(), ExponentListIterator< E, L >::valid(), and ExponentListIterator< E, L >::var().
Referenced by find_pivot().