Macaulay2 Engine: find_pivot
find_pivot()
static int find_pivot (const MonomialIdeal & I, int & npure, exponents_t pure, gc_vector< int > & m) static
Definition at line 236 of file hilb.cpp.
 {
   int nhits;
   int exp_of_v;
   const_varpower vp;
   int v = popular_var(I, npure, pure, nhits, vp, exp_of_v);
   // The following will take some tweaking...
   // Some possibilities: take just this variable, take gcd of 2 or 3
   // elements containing this variable (choose first 3, last 3, or randomly).
   // For now, let's just take this variable, if there is more than one
   // non pure power.
   if (npure >= I.size() - 1)
     {
       assert(vp != NULL);
       varpower::copy(vp, m);
       return 0;
     }
   varpower::var(v, exp_of_v, m);
   return 1;
 }
References ExponentList< E, L >::copy(), popular_var(), MonomialIdeal::size(), and ExponentList< E, L >::var().
Referenced by hilb_comp::do_ideal().