Macaulay2 Engine: iquotient_and_sum
iquotient_and_sum()
static void iquotient_and_sum (MonomialIdeal & I, const_varpower m, MonomialIdeal *& quot, MonomialIdeal *& sum, stash * mi_stash) static
Definition at line 267 of file hilb.cpp.
 {
   gc_vector<Bag*> elems;
   sum = new MonomialIdeal(I.get_ring(), mi_stash);
   quot = new MonomialIdeal(I.get_ring(), mi_stash);
   Bag *bmin = new Bag();
   varpower::copy(m, bmin->monom());
   sum->insert_minimal(bmin);
   for (Bag& a : I)
     {
       Bag *b = new Bag();
       varpower::quotient(a.monom().data(), m, b->monom());
       if (varpower::divides(m, a.monom().data()))
         quot->insert_minimal(b);
       else
         {
           sum->insert_minimal(new Bag(0, a.monom()));
           elems.push_back(b);
         }
     }
   // Now we sort items in 'elems' so that we can insert as min gens into 'quot'
   std::vector<std::pair<int, int>> degs_and_indices;
   int count = 0;
   for (auto& b : elems)
     {
       int deg = varpower::simple_degree(b->monom().data());
       degs_and_indices.push_back(std::make_pair(deg, count));
       ++count;
     }
   std::stable_sort(degs_and_indices.begin(), degs_and_indices.end());
   for (auto p : degs_and_indices)
     {
       Bag* b = elems[p.second];
       Bag* b1; // not used here...
       if (quot->search(b->monom().data(), b1))
         delete b;
       else
         quot->insert_minimal(b);
     }
 }
References ExponentList< E, L >::copy(), ExponentList< E, L >::divides(), MonomialIdeal::get_ring(), MonomialIdeal::insert_minimal(), int_bag::monom(), p, ExponentList< E, L >::quotient(), MonomialIdeal::search(), ExponentList< E, L >::simple_degree(), and mpfr::sum().
Referenced by hilb_comp::recurse().