Macaulay2 Engine: AssociatedPrimes::codimension
codimension()
int AssociatedPrimes::codimension ()
Definition at line 33 of file assprime.cpp.
 {
   minprime_limit = -1;
   exps[0] = newarray_atomic_clear(int, nvars);
   ass_prime_generator(mi->first_node(), 0);
   state = do_primes;
   return min_codim;
 }
References ass_prime_generator(), do_primes, exps, MonomialIdeal::first_node(), mi, min_codim, minprime_limit, newarray_atomic_clear, nvars, and state.
Referenced by associated_primes(), and Matrix::dimension1().