Macaulay2 Engine: AssociatedPrimes::ass_prime_generator
ass_prime_generator()
void AssociatedPrimes::ass_prime_generator (Nmi_node * p, int codim) private
Definition at line 89 of file assprime.cpp.
 {
   int i = codim + 1;
   if (exps[i] == 0) exps[i] = newarray_atomic(int, nvars);
   exponents_t exp = exps[i];
   for (int j = 0; j < nvars; j++) exp[j] = exps[codim][j];
   for (;;)
     {
       if (p == NULL)
         {
           if (state == do_codim)
             {
               if (codim < min_codim) min_codim = codim;
             }
           else
             {
               to_prime_ideal(nvars, exp);
               Bag *b = new Bag(0);
               varpower::from_expvector(nvars, exp, b->monom());
               ass_primes->insert(b);
               n_minprimes++;
               if (minprime_limit > 0 && n_minprimes >= minprime_limit) return;
             }
           return;
         }
       const int *m = p->monom().data();
       switch (reduce_exp(m, exp))
         {
           case 0:
             p = mi->next(p);
             break;
           case -1:
             return;
           case 1:
             if (codim < min_codim)
               for (index_varpower i2 = m; i2.valid(); ++i2)
                 if (exp[i2.var()] == 0)
                   {
                     exp[i2.var()] = 1;
                     ass_prime_generator(mi->next(p), codim + 1);
                     exp[i2.var()] = -1;
                     if (minprime_limit > 0 && n_minprimes >= minprime_limit)
                       return;
                   }
             return;
         }
     }
 }
References ass_primes, do_codim, mpfr::exp(), exps, ExponentList< E, L >::from_expvector(), MonomialIdeal::insert(), mi, min_codim, minprime_limit, int_bag::monom(), n_minprimes, newarray_atomic, MonomialIdeal::next(), nvars, p, reduce_exp(), state, to_prime_ideal(), and ExponentListIterator< E, L >::valid().
Referenced by associated_primes(), and codimension().