Macaulay2 Engine: AssociatedPrimes::associated_primes
associated_primes()
MonomialIdeal * AssociatedPrimes::associated_primes (int count)
Definition at line 42 of file assprime.cpp.
 {
   if (state == do_codim)
     {
       codimension();
       state = do_primes;
     }
   minprime_limit = count;
   n_minprimes = 0;
   if (exps[0] == nullptr) exps[0] = newarray_atomic_clear(int, nvars);
   ass_prime_generator(mi->first_node(), 0);
   return ass_primes;
 }
References ass_prime_generator(), ass_primes, codimension(), do_codim, do_primes, exps, MonomialIdeal::first_node(), mi, minprime_limit, n_minprimes, newarray_atomic_clear, nvars, and state.
Referenced by rawMaximalIndependentSets().