Macaulay2 Engine: makemonideal
makemonideal()
static MonomialIdeal* makemonideal (const Matrix * A) static
Definition at line 1113 of file matrix.cpp.
 {
   const PolynomialRing *P = A->get_ring()->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("expected polynomial ring");
       return nullptr;
     }
   const Monoid *M = P->getMonoid();
   VECTOR(Bag *) new_elems;
   for (int i = 0; i < A->n_cols(); i++)
     {
       vec v = A->elem(i);
       if (v == nullptr) continue;
       Bag *b = new Bag(i);
       M->to_varpower(P->lead_flat_monomial(v->coeff), b->monom());
       new_elems.push_back(b);
     }
   MonomialIdeal *result = new MonomialIdeal(P, new_elems);
   return result;
 }
References Ring::cast_to_PolynomialRing(), Matrix::elem(), ERROR(), Matrix::get_ring(), PolynomialRing::getMonoid(), PolynomialRing::lead_flat_monomial(), int_bag::monom(), Matrix::n_cols(), Monoid::to_varpower(), and VECTOR().
Referenced by Matrix::koszul_monomials().