Macaulay2 Engine: NCCoefficientMatrix
NCCoefficientMatrix() [1/2]
std::pair<Matrix*, Matrix*> NCCoefficientMatrix (const Matrix * M)
Definition at line 1663 of file matrix.cpp.
 {
   const M2FreeAlgebraOrQuotient* Q = dynamic_cast<const M2FreeAlgebraOrQuotient*>(M->get_ring());
   if (Q == nullptr)
     {
       ERROR("expected NC polynomial algebra");
       return {nullptr, nullptr};
     }
   ModuleMonomialSet H(ModuleMonomDefaultConfig(Q->n_vars()));
   NCMonomials(H, M);
   // now loop through all columns in M, monomials in column:
   //   find index.
   //   create coeff
   // return matrix constructed.
   return {nullptr, nullptr};
 }
References ERROR(), Matrix::get_ring(), M2FreeAlgebraOrQuotient::n_vars(), and NCMonomials().