Macaulay2 Engine: coeffs_of_vec
coeffs_of_vec()
static vec coeffs_of_vec (exponent_table * E, M2_arrayint vars, const FreeModule * F, vec f) static
Definition at line 1797 of file matrix.cpp.
 {
   if (f == nullptr) return nullptr;
   const PolynomialRing *P = F->get_ring()->cast_to_PolynomialRing();
   if (P == nullptr) return nullptr;
   const Monoid *M = P->getMonoid();
   monomial mon = M->make_one();
   // At this point, we know that we have a polynomial ring
   int nvars = M->n_vars();
   exponents_t exp = newarray_atomic(int, nvars);
   exponents_t scratch_exp = newarray_atomic(int, 1 + vars->len);
   vec result = nullptr;
   for (vec g = f; g != nullptr; g = g->next)
     {
       for (Nterm& h : g->coeff)
         {
           M->to_expvector(h.monom, exp);
           get_part_of_expvector(vars, exp, g->comp, scratch_exp);
           int val = static_cast<int>(exponent_table_get(E, scratch_exp));
           if (val > 0)
             {
               M->from_expvector(exp, mon);
               ring_elem t = P->make_flat_term(h.coeff, mon);
               vec v = P->make_vec(val - 1, t);
               v->next = result;
               result = v;
             }
         }
     }
   freemem(exp);
   freemem(scratch_exp);
   M->remove(mon);
   P->vec_sort(result);
   return result;
 }
References Ring::cast_to_PolynomialRing(), Nterm::coeff, mpfr::exp(), exponent_table_get(), freemem(), Monoid::from_expvector(), get_part_of_expvector(), FreeModule::get_ring(), PolynomialRing::getMonoid(), PolynomialRing::make_flat_term(), Monoid::make_one(), Ring::make_vec(), Nterm::monom, Monoid::n_vars(), newarray_atomic, Monoid::remove(), Monoid::to_expvector(), and Ring::vec_sort().
Referenced by Matrix::coeffs().