Macaulay2 Engine: NCMonomialMatrix
NCMonomialMatrix()
Matrix* NCMonomialMatrix (ModuleMonomialSet & H, const FreeModule * target)
Definition at line 1586 of file matrix.cpp.
 {
   const M2FreeAlgebraOrQuotient* Q = dynamic_cast<const M2FreeAlgebraOrQuotient*>(target->get_ring());
   if (Q == nullptr)
     {
       ERROR("expected NC polynomial algebra");
       return nullptr;
     }
   MatrixConstructor mat(target, 0);
   for (auto i = H.begin(); i != H.end(); ++i)
     {
       ring_elem rf = Q->fromModuleMonom(*i);
       vec v = Q->make_vec(i->component(), rf);
       mat.append(v);
     }
   // Finally, we sort them
   Matrix *result = mat.to_matrix();
   M2_arrayint perm = result->sort(0, -1);
   return result->sub_matrix(perm);
 }
References MatrixConstructor::append(), IntsSet< Configuration >::begin(), IntsSet< Configuration >::end(), ERROR(), M2FreeAlgebraOrQuotient::fromModuleMonom(), FreeModule::get_ring(), Ring::make_vec(), Matrix::sort(), Matrix::sub_matrix(), and MatrixConstructor::to_matrix().
Referenced by Matrix::monomials().