Macaulay2 Engine: NCMonomials
NCMonomials()
void NCMonomials (ModuleMonomialSet & H, const Matrix * M)
Definition at line 1583 of file matrix.cpp.
 {
   const M2FreeAlgebraOrQuotient* Q = dynamic_cast<const M2FreeAlgebraOrQuotient*>(M->get_ring());
   if (Q == nullptr) return;
   // should not get here unless 'M' is a matrix over a M2FreeAlgebraOrQuotient
   for (int c = 0; c < M->n_cols(); c++)
     {
       vec v = M->elem(c);
       for (; v != nullptr; v = v->next)
         {
           int comp = v->comp;
           auto f = Q->toPoly(v->coeff);
           for (auto i = f->cbegin(); i != f->cend(); ++i)
             H.insert(i.monom(), comp);
         }
     }
 }
References Matrix::elem(), Matrix::get_ring(), IntsSet< Configuration >::insert(), Matrix::n_cols(), and M2FreeAlgebraOrQuotient::toPoly().
Referenced by Matrix::coeffs(), Matrix::monomials(), and NCCoefficientMatrix().