Macaulay2 Engine: NCCoefficientMatrix
NCCoefficientMatrix() [2/2]
Matrix* NCCoefficientMatrix (ModuleMonomialSet & H, const Matrix * M)
Definition at line 1629 of file matrix.cpp.
 {
   const M2FreeAlgebraOrQuotient* Q = dynamic_cast<const M2FreeAlgebraOrQuotient*>(M->get_ring());
   if (Q == nullptr)
     {
       ERROR("expected NC polynomial algebra");
       return nullptr;
     }
   // should not get here unless 'M' is a matrix over a M2FreeAlgebraOrQuotient
   MatrixConstructor mat(Q->make_FreeModule(H.size()), M->cols());
   for (int c = 0; c < M->n_cols(); c++)
     {
       vec v = M->elem(c);
       for (; v != nullptr; v = v->next)
         {
           int comp = v->comp;
           auto f = Q->toPoly(v->coeff);
           for (auto i = f->cbegin(); i != f->cend(); ++i)
             {
               auto result = H.find(i.monom(), comp);
               if (result.second)
                 {
                   ring_elem cf = Q->from_coefficient(i.coeff());
                   mat.set_entry(result.first, c, cf);
                 }
             }
         }
     }
   return mat.to_matrix();
 }
References Matrix::cols(), Matrix::elem(), ERROR(), IntsSet< Configuration >::find(), M2FreeAlgebraOrQuotient::from_coefficient(), Matrix::get_ring(), Ring::make_FreeModule(), Matrix::n_cols(), MatrixConstructor::set_entry(), IntsSet< Configuration >::size(), MatrixConstructor::to_matrix(), and M2FreeAlgebraOrQuotient::toPoly().
Referenced by Matrix::coeffs().