Macaulay2 Engine: signdivide
signdivide()
static int signdivide (int n, const_exponents a, const_exponents b, exponents_t exp) static
Definition at line 1136 of file matrix.cpp.
 {
   int sign = 0;
   int sum = 0;
   for (int i = 0; i < n; i++)
     {
       int e = a[i] - b[i];
       if (e < 0) return 0;
       exp[i] = e;
       sign += sum * e;
       sum += b[i];
     }
   sign %= 2;
   if (sign == 0) return 1;
   return -1;
 }
References mpfr::exp(), and mpfr::sum().
Referenced by Matrix::koszul().