Macaulay2 Engine: DegreeZeroMapGenerator::iterator::increment
increment()
void DegreeZeroMapGenerator::iterator::increment () inline private
Definition at line 483 of file res-f4-m2-interface.cpp.
     {
       ++mColumn;
       mComponents.clear();
       mCoefficients.clear();
       if (mColumn == mNumColumns) return;
       for (; mIter != mEnd; ++mIter)
         {
           if (mIter->mDegree == mGenerator.mDegree) break;
         }
       auto& f = mIter->mSyzygy;
       auto end = ResPolynomialIterator(mGenerator.mSchreyerFrame.ring(), f, 1);
       auto i = ResPolynomialIterator(mGenerator.mSchreyerFrame.ring(), f);
       for (; i != end; ++i)
         {
           auto comp = mGenerator.mSchreyerFrame.monoid().get_component(i.monomial());
           auto new_comp = mGenerator.mComponentTranslation[comp];
           if (new_comp >= 0)
             {
               mComponents.push_back(new_comp);
               long val =
                 mGenerator.mSchreyerFrame.vectorArithmetic().to_modp_long(f.coeffs, i.coefficient_index());
               mCoefficients.push_back(val);
             }
         }
       ++mIter;
     }
References DegreeZeroMapGenerator::end(), ResMonoidDense::get_component(), mCoefficients, mColumn, mComponents, DegreeZeroMapGenerator::mComponentTranslation, DegreeZeroMapGenerator::mDegree, mEnd, mGenerator, mIter, mNumColumns, SchreyerFrame::monoid(), DegreeZeroMapGenerator::mSchreyerFrame, SchreyerFrame::ring(), VectorArithmetic::to_modp_long(), and SchreyerFrame::vectorArithmetic().
Referenced by iterator(), and operator++().