Macaulay2 Engine: QRingInfo_field::QRingInfo_field
QRingInfo_field()
QRingInfo_field::QRingInfo_field (const PolyRing * ambientR, const gc_vector< Nterm * > & quotients)
Definition at line 43 of file qring.cpp.
     : QRingInfo(ambientR)
 // This constructs the quotient ideal, and sets the MonomialIdeal.
 // A subset of 'quotients' must be a minimal GB, and any non-minimal elements
 // should be writable in terms of previous ones.
 // IE, in constructing (R/I)/J, the GB elements of J (mod I), together with the
 // GB elements of I, form a GB, but the GB elements of I might not be minimal.
 // In this case, 'quotients' should be the list of GB elements of J followed by
 // those
 // of I.
 //
 // The ideal may be in a tower of polynomial rings, in which case it needs to be
 // a GB over the flattened ring.
 {
   Rideal = new MonomialIdeal(R);
   ringtable = MonomialTable::make(R->n_vars());
   gc_vector<int> vp;
   exponents_t exp = newarray_atomic(int, R->n_vars());
   for (int i = 0; i < quotients.size(); i++)
     {
       // Make a varpower element.  See if it is in Rideal.
       // If not, place it into quotient_elements_.
       Nterm *f = quotients[i];
       R->getMonoid()->to_expvector(f->monom, exp);
       Bag *not_used;
       if (!Rideal->search_expvector(exp, not_used))
         {
           // The element is part of a minimal GB
           int index = n_quotients();
           gbvector *g = R->translate_gbvector_from_ringelem(f);
           appendQuotientElement(f, g);
           R->getMonoid()->to_varpower(f->monom, vp);
           Bag *b = new Bag(index, vp);
           Rideal->insert(b);
           ringtable->insert(exp, 1, index);  // consumes exp
           exp = newarray_atomic(int, R->n_vars());
         }
     }
   freemem(exp);
 }
References QRingInfo::appendQuotientElement(), mpfr::exp(), freemem(), PolynomialRing::getMonoid(), MonomialIdeal::insert(), MonomialTable::insert(), MonomialTable::make(), Nterm::monom, QRingInfo::n_quotients(), PolynomialRing::n_vars(), newarray_atomic, QRingInfo::R, Rideal, ringtable, MonomialIdeal::search_expvector(), Monoid::to_expvector(), Monoid::to_varpower(), and PolyRing::translate_gbvector_from_ringelem().