Macaulay2 Engine: FreeAlgebraQuotient::var
var()
void FreeAlgebraQuotient::var (Poly & result, int v) const
Definition at line 75 of file FreeAlgebraQuotient.cpp.
 {
   mFreeAlgebra.var(result, v);
   normalizeInPlace(result);
 }
References mFreeAlgebra, normalizeInPlace(), and FreeAlgebra::var().
Referenced by TEST(), and M2FreeAlgebraQuotient::var().