Macaulay2 Engine: FreeAlgebraQuotient::normalizeInPlace
normalizeInPlace()
void FreeAlgebraQuotient::normalizeInPlace (Poly & f) const
Definition at line 24 of file FreeAlgebraQuotient.cpp.
 {
   // for now, we will simply reduce the poly f and copy the result into f.
   // TODO: Make this work 'in place'.
   auto fRed = mGroebner.twoSidedReduction(&f);
   freeAlgebra().swap(f,*fRed);
 }
References freeAlgebra(), mGroebner, FreeAlgebra::swap(), and NCGroebner::twoSidedReduction().
Referenced by from_coefficient(), from_word(), mult(), power(), M2FreeAlgebraQuotient::promote(), and var().