Macaulay2 Engine: FreeAlgebraQuotient::negate
negate()
void FreeAlgebraQuotient::negate (Poly & result, const Poly & f) const
Definition at line 110 of file FreeAlgebraQuotient.cpp.
 {
   return mFreeAlgebra.negate(result, f);
 }
References mFreeAlgebra, and FreeAlgebra::negate().
Referenced by M2FreeAlgebraQuotient::negate(), and TEST().