Macaulay2 Engine: FreeAlgebraQuotient::mult
mult()
void FreeAlgebraQuotient::mult (Poly & result, const Poly & f, const Poly & g) const
Definition at line 122 of file FreeAlgebraQuotient.cpp.
 {
   mFreeAlgebra.mult(result, f, g);
   normalizeInPlace(result);
 }
References mFreeAlgebra, FreeAlgebra::mult(), and normalizeInPlace().
Referenced by M2FreeAlgebraQuotient::mult(), and FreeAlgebraQuotientElement::operator*().