Macaulay2 Engine: FreeAlgebraQuotient::from_rational
from_rational()
bool FreeAlgebraQuotient::from_rational (Poly & result, const mpq_srcptr q) const
Definition at line 56 of file FreeAlgebraQuotient.cpp.
 {
   ring_elem cq; // in coeff ring.
   bool worked = coefficientRing()->from_rational(q, cq);
   if (!worked) return false;
   from_coefficient(result, cq);
   return true;
 }
References coefficientRing(), from_coefficient(), and Ring::from_rational().