Macaulay2 Engine: FreeAlgebraQuotient::is_equal
is_equal()
bool FreeAlgebraQuotient::is_equal (const Poly & f, const Poly & g) const
Definition at line 102 of file FreeAlgebraQuotient.cpp.
 {
   return mFreeAlgebra.is_equal(f, g);
 }
References FreeAlgebra::is_equal(), and mFreeAlgebra.
Referenced by M2FreeAlgebraQuotient::is_equal(), and FreeAlgebraQuotientElement::operator==().