Macaulay2 Engine: FreeAlgebraQuotient::coefficientRing
coefficientRing()
const Ring* FreeAlgebraQuotient::coefficientRing () const inline
Definition at line 37 of file FreeAlgebraQuotient.hpp.
 { return mFreeAlgebra.coefficientRing(); }
References FreeAlgebra::coefficientRing(), and mFreeAlgebra.
Referenced by from_int(), from_long(), from_rational(), and from_word().