Macaulay2 Engine: cast_to_CCC
cast_to_CCC()
const M2::ConcreteRing< M2::ARingCC > * cast_to_CCC (const Ring * R) inline
Definition at line 135 of file NAG.hpp.
{
  return dynamic_cast<const CCC*>(R);
}
References CCC.
Referenced by SLP< Field >::evaluate(), PathTracker::make(), SLP< Field >::make(), PathTracker::make(), SLP< Field >::make(), PathTracker::refine(), and PathTracker::track().