Macaulay2 Engine: toBigComplex
toBigComplex()
gmp_CC toBigComplex (const M2::ConcreteRing< M2::ARingCC > * C, ring_elem a) inline
Definition at line 150 of file NAG.hpp.
 {
   M2::ARingCC::Element b(C->ring());
   C->ring().from_ring_elem(b, a);
   gmp_CC result = C->ring().toBigComplex(b);
   return result;
 }
Referenced by SLP< Field >::evaluate(), SLP< Field >::make(), SLP< Field >::poly_to_horner_slp(), PathTracker::refine(), and PathTracker::track().