Macaulay2 Engine: binomial_ring::normalize
normalize()
bool binomial_ring::normalize (binomial & f) const
Definition at line 382 of file gb-toric.cpp.
 {
   int cmp = compare(f.lead, f.tail);
   if (cmp == EQ) return false;
   if (cmp == LT)
     {
       monomial a = f.lead;
       f.lead = f.tail;
       f.tail = a;
     }
   return true;
 }
References compare(), EQ, and LT.
Referenced by calc_s_pair(), and binomialGB::reduce().