Macaulay2 Engine: binomial_ring::binomial_to_vector
binomial_to_vector() [1/2]
vec binomial_ring::binomial_to_vector (binomial f) const
Definition at line 311 of file gb-toric.cpp.
 {
   vec v1 = monomial_to_vector(f.lead);
   vec v2 = monomial_to_vector(f.tail);
   R->subtract_vec_to(v1, v2);
   return v1;
 }
References binomial::lead, monomial_to_vector(), R, Ring::subtract_vec_to(), and binomial::tail.
Referenced by binomialGB_comp::get_gb(), binomialGB_comp::get_initial(), binomialGB_comp::get_mingens(), binomialGB_comp::subring(), and binomialGB_comp::subringGB().