Macaulay2 Engine: binomial_ring::calc_s_pair
calc_s_pair()
bool binomial_ring::calc_s_pair (binomial_s_pair & s, binomial & result) const
Definition at line 406 of file gb-toric.cpp.
 {
   binomial f = s.f1->f;
   binomial g = s.f2->f;
   result = make_binomial();
   for (int i = 0; i < nslots; i++)
     {
       result.lead[i] = s.lcm[i] - f.lead[i] + f.tail[i];
       result.tail[i] = s.lcm[i] - g.lead[i] + g.tail[i];
     }
   return normalize(result);
 }
References binomial_gb_elem::f, binomial_s_pair::f1, binomial_s_pair::f2, binomial_s_pair::lcm, binomial::lead, make_binomial(), normalize(), nslots, and binomial::tail.
Referenced by binomialGB_comp::process_pair().