Macaulay2 Engine: binomial_ring::mask
mask()
unsigned int binomial_ring::mask (const_exponents m) const
Definition at line 117 of file gb-toric.cpp.
{
  return exponents::mask(nvars, m);
}
References ExponentVector< E, OC >::mask(), and nvars.
Referenced by binomialGB::find_divisor(), binomialGB::find_divisor(), binomialGB::ideal_quotient(), and binomialGB::minimalize_and_insert().