Macaulay2 Engine: binomial_ring::remove_monomial
remove_monomial()
void binomial_ring::remove_monomial (monomial0 & m) const
Definition at line 54 of file gb-toric.cpp.
 {
   if (m == nullptr) return;
   monstash->delete_elem(m);
   m = nullptr;
 }
References stash::delete_elem(), and monstash.
Referenced by binomial_s_pair_set::enlarge(), binomialGB::ideal_quotient(), binomial_s_pair_set::insert_pair(), binomial_s_pair_set::next(), remove_binomial(), binomial_s_pair_set::remove_lcm_list(), binomialGB::remove_monomial_list(), translate_monomial(), and binomial_s_pair_set::~binomial_s_pair_set().