Macaulay2 Engine: binomial_ring::new_monomial
new_monomial()
monomial0 binomial_ring::new_monomial () const private
Definition at line 61 of file gb-toric.cpp.
 {
   return (monomial)((const binomial_ring *)this)->monstash->new_elem();
 }
Referenced by copy_monomial(), divide(), make_binomial(), mult(), and translate_monomial().