Macaulay2 Engine: binomial_ring::make_binomial
make_binomial()
binomial binomial_ring::make_binomial () const
Definition at line 100 of file gb-toric.cpp.
 {
   return binomial(new_monomial(), new_monomial());
 }
References new_monomial().
Referenced by binomialGB_comp::add_generators(), and calc_s_pair().