Macaulay2 Engine: binomial_ring::degree
degree()
int binomial_ring::degree (monomial0 m) const
Definition at line 116 of file gb-toric.cpp.
 { return -m[nvars]; }
References nvars.
Referenced by binomial_to_vector(), binomialGB::find_divisor(), binomialGB::ideal_quotient(), binomial_s_pair_set::insert(), and binomialGB::minimalize_and_insert().