Macaulay2 Engine: binomial_ring::binomial_to_vector
binomial_to_vector() [2/2]
vec binomial_ring::binomial_to_vector (binomial f, int n) const
Definition at line 318 of file gb-toric.cpp.
 {
   vec v1 = monomial_to_vector(f.lead);
   bool include_tail = false;
   if (n == 0)
     include_tail = true;
   else if (n == 1 && degree(f.tail) == degree(f.lead))
     include_tail = true;
   else if (n == 2 && degree(f.tail) == degree(f.lead) &&
            weight(f.tail) == weight(f.lead))
     include_tail = true;
   if (include_tail)
     {
       vec v2 = monomial_to_vector(f.tail);
       R->subtract_vec_to(v1, v2);
     }
   return v1;
 }
References degree(), binomial::lead, monomial_to_vector(), R, Ring::subtract_vec_to(), binomial::tail, and weight().