Macaulay2 Engine: binomial_ring::weight
weight()
int binomial_ring::weight (monomial0 m) const
Definition at line 110 of file gb-toric.cpp.
 {
   if (have_weights) return -m[nvars + 1];
   return 0;
 }
References have_weights, and nvars.
Referenced by binomial_to_vector(), binomialGB_comp::process_pair(), and binomialGB_comp::subringGB().