Macaulay2 Engine: binomial_ring::translate_monomial
translate_monomial()
void binomial_ring::translate_monomial (const binomial_ring * old_ring, monomial0 & m) const
Definition at line 283 of file gb-toric.cpp.
 {
   int i;
   if (m == NULL) return;
   monomial result = new_monomial();
   for (i = 0; i < old_ring->nvars; i++) result[i] = m[i];
   for (i = old_ring->nvars; i < nvars; i++) result[i] = 0;
   old_ring->remove_monomial(m);
   set_weights(result);
   m = result;
 }
References new_monomial(), nvars, remove_monomial(), and set_weights().
Referenced by binomial_s_pair_set::enlarge(), and translate_binomial().