Macaulay2 Engine: binomial_ring::monomial_to_vector
monomial_to_vector()
vec binomial_ring::monomial_to_vector (monomial0 m) const
Definition at line 303 of file gb-toric.cpp.
 {
   if (m == NULL) return NULL;
   ring_elem f = R->make_logical_term(
       R->getCoefficients(), R->getCoefficients()->one(), m);
   return R->make_vec(0, f);
 }
References PolynomialRing::getCoefficients(), PolynomialRing::make_logical_term(), Ring::make_vec(), Ring::one(), and R.
Referenced by binomial_to_vector().