Macaulay2 Engine: binomial_ring::monomial_out
monomial_out()
void binomial_ring::monomial_out (buffer & o, const_exponents m) const
Definition at line 419 of file gb-toric.cpp.
 {
   if (m == NULL) return;
   gc_vector<int> vp;
   varpower::from_expvector(nvars, m, vp);
   monomial n = R->getMonoid()->make_one();
   R->getMonoid()->from_varpower(vp.data(), n);
   R->getMonoid()->elem_text_out(o, n);
   R->getMonoid()->remove(n);
 }
References Monoid::elem_text_out(), ExponentList< E, L >::from_expvector(), Monoid::from_varpower(), PolynomialRing::getMonoid(), Monoid::make_one(), nvars, R, and Monoid::remove().
Referenced by elem_text_out().