Macaulay2 Engine: binomial_ring::monomial_out
monomial_out()
void binomial_ring::monomial_out (buffer & o, const monomial0 m) const
Definition at line 418 of file gb-toric.cpp.
 {
   if (m == NULL) return;
   intarray vp;
   varpower::from_ntuple(nvars, m, vp);
   int *n = R->getMonoid()->make_one();
   R->getMonoid()->from_varpower(vp.raw(), n);
   R->getMonoid()->elem_text_out(o, n);
   R->getMonoid()->remove(n);
 }
References Monoid::elem_text_out(), varpower::from_ntuple(), Monoid::from_varpower(), PolynomialRing::getMonoid(), Monoid::make_one(), nvars, R, intarray::raw(), and Monoid::remove().
Referenced by elem_text_out().