Macaulay2 Engine: ResF4MonomialLookupTableT::find_one_divisor_vp
find_one_divisor_vp()
template<typename Key > bool ResF4MonomialLookupTableT< Key >::find_one_divisor_vp (long comp, const_varpower_monomial m, Key & result_k) const
Definition at line 277 of file res-f4-monlookup.cpp.
 {
   if (comp >= mis.size()) return false;
   mi_node *mi = mis[comp];
   if (mi == NULL) return false;
   ResF4MonomialLookupTableT *me = const_cast<ResF4MonomialLookupTableT *>(this);
   me->update_expvector(static_cast<int>(mi->var), m);
   bool result = find_one_divisor1(mi, exp0, result_k);
   me->reset_expvector(m);
   return result;
 }
References ResF4MonomialLookupTableT< Key >::reset_expvector(), ResF4MonomialLookupTableT< Key >::update_expvector(), and ResF4MonomialLookupTableT< Key >::mi_node::var.
Referenced by minimalize_res_varpower_monomials().