Macaulay2 Engine: ResF4MonomialLookupTableT::update_expvector
update_expvector()
template<typename Key > void ResF4MonomialLookupTableT< Key >::update_expvector (int topvar, const_varpower_monomial m) private
Definition at line 240 of file res-f4-monlookup.cpp.
 {
   int nvars = topvar + 1;
   if (*m > 0 && m[1] >= nvars) nvars = static_cast<int>(m[1] + 1);
   if (size_of_exp <= nvars)
     {
       // Increase size of exponent vector
       freemem(exp0);
       if (nvars > 2 * size_of_exp)
         size_of_exp = nvars;
       else
         size_of_exp *= 2;
       exp0 = newarray_atomic_clear(ntuple_word, size_of_exp);
     }
   int nparts = static_cast<int>(*m++);
   for (int i = nparts; i > 0; i--, m += 2)
     {
       exp0[*m] = m[1];
     }
 }
References freemem(), and newarray_atomic_clear.
Referenced by ResF4MonomialLookupTableT< Key >::find_all_divisors_vp(), and ResF4MonomialLookupTableT< Key >::find_one_divisor_vp().