Macaulay2 Engine: F4MonomialLookupTableT::find_one_divisor_vp
find_one_divisor_vp()
template<typename Key > bool F4MonomialLookupTableT< Key >::find_one_divisor_vp (long comp, const_varpower_monomial m, Key & result_k) const
Definition at line 275 of file f4-monlookup.cpp.
 {
   if (comp >= mis.size()) return false;
   mi_node *mi = mis[comp];
   if (mi == nullptr) return false;
   F4MonomialLookupTableT *me = const_cast<F4MonomialLookupTableT *>(this);
   me->update_expvector(static_cast<int>(mi->var), m);
   bool result = find_one_divisor1(mi, exp0, result_k);
   me->reset_expvector(m);
   return result;
 }
References F4MonomialLookupTableT< Key >::reset_expvector(), F4MonomialLookupTableT< Key >::update_expvector(), and F4MonomialLookupTableT< Key >::mi_node::var.
Referenced by SchreyerFrame::computeIdealQuotient(), F4SPairSet::construct_pairs(), and minimalize_varpower_monomials().