Macaulay2 Engine: F4MonomialLookupTableT::debug_out
debug_out()
template<typename Key > void F4MonomialLookupTableT< Key >::debug_out (int disp = 1) const private
Definition at line 442 of file f4-monlookup.cpp.
 {
   nlists = 0;
   nnodes = 0;
   nleaves = 0;
   ndepth = 0;
   for (typename VECTOR(mi_node *)::const_iterator i = mis.begin();
        i != mis.end();
        i++)
     if (*i != nullptr) do_tree(*i, 0, 0, disp);
   buffer o;
   o << "list nodes     = " << nlists << newline;
   o << "internal nodes = " << nnodes << newline;
   o << "monomials      = " << nleaves << newline;
   o << "max depth      = " << ndepth << newline;
   emit(o.str());
 }
References emit(), ndepth, newline, nleaves, nlists, nnodes, buffer::str(), and VECTOR().