Macaulay2 Engine: F4MonomialLookupTableT::insert_minimal_vp
insert_minimal_vp()
template<typename Key > void F4MonomialLookupTableT< Key >::insert_minimal_vp (long comp, const_varpower_monomial m, Key k)
Definition at line 336 of file f4-monlookup.cpp.
 {
   if (comp >= mis.size())
     {
       for (long j = comp - mis.size(); j >= 0; j--) mis.push_back(nullptr);
     }
   insert1(mis[comp], m, k);
 }
Referenced by SchreyerFrame::computeIdealQuotient(), F4SPairSet::construct_pairs(), F4GB::insert_gb_element(), and minimalize_varpower_monomials().