Macaulay2 Engine: VectorArithmetic::ring
ring()
const Ring * VectorArithmetic::ring () const inline
Definition at line 648 of file VectorArithmetic.hpp.
{
    return std::visit([&](auto& arg) -> const Ring* { return arg->ring(); }, mConcreteVector);
  }
References mConcreteVector.
Referenced by newf4::GBF4Computation::initializeWithBasicPolyList(), newf4::GBF4Computation::initializeWithMatrix(), SchreyerFrame::rankUsingDenseMatrix(), SchreyerFrame::rankUsingDenseMatrixFlint(), DegreeZeroMapGenerator::ring(), F4GB::show_new_rows_matrix(), F4toM2Interface::to_M2_MutableMatrix(), and VectorArithmetic().