Macaulay2 Engine: VectorArithmetic::fillDenseArray
fillDenseArray()
void VectorArithmetic::fillDenseArray (ElementArray & dense, const ElementArray & coeffs, const Range< const int > & comps) const inline
Definition at line 681 of file VectorArithmetic.hpp.
{
     std::visit([&](auto& arg) { arg->fillDenseArray(dense,coeffs,comps); }, mConcreteVector);
   }
References mConcreteVector.
Referenced by F4GB::gauss_reduce(), F4Res::gaussReduceRow(), NCF4::generalReduceF4Row(), and F4GB::tail_reduce().