Macaulay2 Engine: VectorArithmetic::makeMonic
makeMonic()
void VectorArithmetic::makeMonic (ElementArrayType & coeffs) const inline
Definition at line 542 of file VectorArithmetic.hpp.
{
     std::visit([&](auto& arg) { arg->makeMonic(coeffs); }, mConcreteVector);
   }
References mConcreteVector.
Referenced by F4GB::gauss_reduce(), NCF4::generalReduceF4Row(), and F4GB::tail_reduce().