Macaulay2 Engine: VectorArithmetic::ringElemFromElementArray
ringElemFromElementArray()
ring_elem VectorArithmetic::ringElemFromElementArray (const ElementArray & coeffs, int index) const inline
Definition at line 765 of file VectorArithmetic.hpp.
{
     return std::visit([&](auto& arg) -> ring_elem { return arg->ringElemFromElementArray(coeffs,index); }, mConcreteVector);
   }
References mConcreteVector.
Referenced by NCF4::displayF4Matrix(), NCF4::displayFullF4Matrix(), F4GB::show_new_rows_matrix(), F4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), and F4toM2Interface::to_M2_vec().