Macaulay2 Engine: VectorArithmetic::VectorArithmetic
VectorArithmetic()
VectorArithmetic::VectorArithmetic (const Ring * R) inline
Definition at line 592 of file VectorArithmetic.hpp.
   {
     // if the rings coming in are defined in a similar way, we could avoid the switch
     // statement here as well and make it compile time.  It would make the class templated
     // on the variant class describing all the rings.
     switch (R->ringID())
       {
       case M2::ring_ZZpFlint:
         mConcreteVector = new ConcreteVectorArithmetic
           {R, &dynamic_cast< const M2::ConcreteRing<M2::ARingZZpFlint>* >(R)->ring()};
         break;
       case M2::ring_GFFlintBig:
         mConcreteVector = new ConcreteVectorArithmetic
           {R, &dynamic_cast< const M2::ConcreteRing<M2::ARingGFFlintBig>* >(R)->ring()};
         break;
       case M2::ring_GFFlintZech:
         mConcreteVector = new ConcreteVectorArithmetic
           {R, &dynamic_cast< const M2::ConcreteRing<M2::ARingGFFlint>* >(R)->ring()};
         break;
       case M2::ring_QQ:
         mConcreteVector = new ConcreteVectorArithmetic
           {R, &dynamic_cast< const M2::ConcreteRing<M2::ARingQQGMP>* >(R)->ring()};
     break;
       case M2::ring_ZZpFfpack:
         mConcreteVector = new ConcreteVectorArithmetic
           {R, &dynamic_cast< const M2::ConcreteRing<M2::ARingZZpFFPACK>* >(R)->ring()};
     break;
       case M2::ring_ZZp:
         mConcreteVector = new ConcreteVectorArithmetic
           {R, &dynamic_cast< const M2::ConcreteRing<M2::ARingZZp>* >(R)->ring()};
         break;
       case M2::ring_GFM2:
         mConcreteVector = new ConcreteVectorArithmetic
           {R, &dynamic_cast< const M2::ConcreteRing<M2::ARingGFM2>* >(R)->ring()};
         break;
       case M2::ring_old:
         if (R->cast_to_Z_mod() != nullptr)
           mConcreteVector = new ConcreteVectorArithmetic{R, R->cast_to_Z_mod()->get_CoeffRing()};
         else
           {
             std::cout << "Using GC ring in VectorArithmetic." << std::endl;
             mConcreteVector = new ConcreteVectorArithmetic{R, R->getCoefficientRingR()};
           }
         break;
       default:
         // dummy ring type for default
         // throw an error here...
         std::cerr << "*** error! *** ring ID not found....!" << std::endl;
         mConcreteVector = new ConcreteVectorArithmetic<M2::DummyRing>();
       }
   }
References Ring::cast_to_Z_mod(), Z_mod::get_CoeffRing(), Ring::getCoefficientRingR(), mConcreteVector, ring(), M2::ring_GFFlintBig, M2::ring_GFFlintZech, M2::ring_GFM2, M2::ring_old, M2::ring_QQ, M2::ring_ZZp, M2::ring_ZZpFfpack, M2::ring_ZZpFlint, and Ring::ringID().