Macaulay2 Engine: VectorArithmetic::deallocateElementArray
deallocateElementArray()
void VectorArithmetic::deallocateElementArray (ElementArray & coeffs) const inline
Definition at line 674 of file VectorArithmetic.hpp.
{
     std::visit([&](auto& arg) { arg->deallocateElementArray(coeffs); }, mConcreteVector);
   }
References mConcreteVector.
Referenced by F4GB::clear_matrix(), F4Res::clearMatrix(), NCF4::clearRows(), F4GB::delete_gb_array(), F4GB::gauss_reduce(), F4Res::gaussReduce(), NCF4::parallelReduceF4Matrix(), NCF4::reduceF4Matrix(), F4GB::tail_reduce(), and ResPolynomialConstructor::~ResPolynomialConstructor().