Macaulay2 Engine: VectorArithmetic::denseNextNonzero
denseNextNonzero()
int VectorArithmetic::denseNextNonzero (ElementArrayType & dense, int first, int last) const inline
Definition at line 501 of file VectorArithmetic.hpp.
{
     return std::visit([&](auto& arg) -> int { return arg->denseNextNonzero(dense,first,last); }, mConcreteVector);
   }
References mConcreteVector.
Referenced by F4GB::gauss_reduce(), NCF4::generalReduceF4Row(), and F4GB::tail_reduce().