Macaulay2 Engine: VectorArithmetic::size
size()
size_t VectorArithmetic::size (const ElementArray & coeffs) const inline
Definition at line 653 of file VectorArithmetic.hpp.
{
     return std::visit([&](auto& arg) -> size_t { return arg->size(coeffs); }, mConcreteVector);
   }
References mConcreteVector.
Referenced by NCF4::displayF4Matrix(), NCF4::displayF4MatrixSize(), NCF4::displayFullF4Matrix(), newf4::Polynomial::end(), F4GB::gauss_reduce(), F4Res::gaussReduceRow(), NCF4::generalReduceF4Row(), ResPolynomialConstructor::setPoly(), and F4GB::tail_reduce().