Macaulay2 Engine: VectorArithmetic::allocateElementArray
allocateElementArray() [2/2]
ElementArray VectorArithmetic::allocateElementArray (ComponentIndex nelems) const inline
Definition at line 661 of file VectorArithmetic.hpp.
{
     return std::visit([&](auto& arg) -> ElementArray { return arg->allocateElementArray(nelems);}, mConcreteVector);
   }
References mConcreteVector.
Referenced by ResF4toM2Interface::from_M2_vec(), F4GB::gauss_reduce(), F4Res::gaussReduce(), SchreyerFrame::insertBasic(), F4Res::loadRow(), NCF4::parallelReduceF4Matrix(), NCF4::reduceF4Matrix(), ResPolynomialConstructor::ResPolynomialConstructor(), and F4GB::tail_reduce().