Macaulay2 Engine: M2_mo_offset
M2_mo_offset()
static MonomialOrdering* M2_mo_offset (const MonomialOrdering * mo, int offset) static
Definition at line 45 of file monomial-ordering.cpp.
 {
   int i, j;
   MonomialOrdering *result = make_mon_order(mo->len);
   for (i = 0; i < mo->len; i++)
     {
       mon_part p = mo->array[i];
       if (p->type != MO_WEIGHTS)
         result->array[i] = mo_make(p->type, p->nvars, p->wts);
       else
         {
           mon_part q = mo_make(MO_WEIGHTS, offset + p->nvars, NULL);
           q->wts = getmemvectortype(int, q->nvars);
           for (j = 0; j < offset; j++) q->wts[j] = 0;
           for (; j < q->nvars; j++) q->wts[j] = p->wts[j - offset];
         }
     }
   return result;
 }
References MonomialOrdering::array, getmemvectortype, MonomialOrdering::len, make_mon_order(), mo_make(), MO_WEIGHTS, and p.
Referenced by MonomialOrderings::product(), and rawProductMonomialOrdering().