Macaulay2 Engine: ones_to_string
ones_to_string()
M2_string ones_to_string (int len)
Definition at line 722 of file monomial-ordering.cpp.
 {
   int i;
   const int N = 200;
   char s[N];
   M2_string one;
   M2_string result = M2_tostring("{");
   snprintf(s, N, "1");
   one = M2_tostring(s);
   for (i = 0; i < len; i++)
     {
       if (i > 0) result = M2_join(result, M2_tostring(","));
       result = M2_join(result, one);
     }
   result = M2_join(result, M2_tostring("}"));
   return result;
 }
References M2_join(), and M2_tostring().
Referenced by IM2_MonomialOrdering_to_string().