Macaulay2 Engine: rawProductMonomialOrdering
rawProductMonomialOrdering()
MonomialOrdering* rawProductMonomialOrdering (engine_RawMonomialOrderingArray M)
Definition at line 687 of file monomial-ordering.cpp.
 {
   MonomialOrdering *result;
   int i, j, sum, next, offset;
   sum = 0;
   for (i = 0; i < M->len; i++) sum += M->array[i]->len;
   result = make_mon_order(sum);
   next = 0;
   offset = 0;
   for (i = 0; i < M->len; i++)
     {
       int nvars = rawNumberOfVariables(M->array[i]);
       MonomialOrdering *mo = M2_mo_offset(M->array[i], offset);
       for (j = 0; j < mo->len; j++) result->array[next++] = mo->array[j];
       offset += nvars;
     }
   return result;
 }
References MonomialOrdering::array, MonomialOrdering::len, M2_mo_offset(), make_mon_order(), mon_part::nvars, rawNumberOfVariables(), and mpfr::sum().