Macaulay2 Engine: moGetWeightValues
moGetWeightValues()
M2_arrayint moGetWeightValues (const MonomialOrdering * mo)
Definition at line 438 of file monomial-ordering.cpp.
 {
   int nvars = rawNumberOfVariables(mo);
   // grab the first weight vector
   if (mo->len == 0) return 0;
   if (mo->array[0]->type == MO_WEIGHTS)
     {
       int i;
       M2_arrayint result = M2_makearrayint(nvars);
       int *wts = mo->array[0]->wts;
       for (i = 0; i < mo->array[0]->nvars; i++) result->array[i] = wts[i];
       for (; i < nvars; i++) result->array[i] = 0;
       return result;
     }
   return 0;
 }
References MonomialOrdering::array, MonomialOrdering::len, M2_makearrayint(), MO_WEIGHTS, mon_part::nvars, rawNumberOfVariables(), and mon_part::wts.
Referenced by MonomialInfo::MonomialInfo().