Macaulay2 Engine: make_mon_order
make_mon_order()
static MonomialOrdering* make_mon_order (int n) static
Definition at line 34 of file monomial-ordering.cpp.
 {
   static unsigned int next_hash = 23023421;
   MonomialOrdering *z = getmemarraytype(MonomialOrdering *, n);
   z->len = n;
   z->_hash = next_hash++;
   int i;
   for (i = 0; i < n; i++) z->array[i] = NULL;
   return z;
 }
References MonomialOrdering::_hash, MonomialOrdering::array, getmemarraytype, and MonomialOrdering::len.
Referenced by MonomialOrderings::GRevLex(), MonomialOrderings::join(), M2_mo_offset(), MonomialOrderings::product(), rawGRevLexMonomialOrdering(), rawGroupLexMonomialOrdering(), rawGroupRevLexMonomialOrdering(), rawJoinMonomialOrdering(), rawLexMonomialOrdering(), rawNClexMonomialOrdering(), rawPositionMonomialOrdering(), rawProductMonomialOrdering(), rawRevLexMonomialOrdering(), rawWeightsMonomialOrdering(), and MonomialOrderings::Weights().