Macaulay2 Engine: mo_make
mo_make()
static struct mon_part_rec_* mo_make (enum MonomialOrdering_type type, int nvars, const int * wts) static
Definition at line 16 of file monomial-ordering.cpp.
 {
   mon_part result;
   result = getmemstructtype(mon_part);
   result->type = type;
   result->nvars = nvars;
   if (wts != 0)
     {
       int i;
       result->wts = getmematomicvectortype(int, nvars);
       for (i = 0; i < nvars; i++) result->wts[i] = wts[i];
     }
   else
     result->wts = 0;
   return result;
 }
References getmematomicvectortype, getmemstructtype, mon_part::nvars, mon_part::type, and mon_part::wts.
Referenced by MonomialOrderings::GRevLex(), MonomialOrderings::join(), M2_mo_offset(), rawGRevLexMonomialOrdering(), rawGroupLexMonomialOrdering(), rawGroupRevLexMonomialOrdering(), rawJoinMonomialOrdering(), rawLexMonomialOrdering(), rawNClexMonomialOrdering(), rawPositionMonomialOrdering(), rawRevLexMonomialOrdering(), rawWeightsMonomialOrdering(), and MonomialOrderings::Weights().