Macaulay2 Engine: rawGRevLexMonomialOrdering
rawGRevLexMonomialOrdering()
MonomialOrdering* rawGRevLexMonomialOrdering (M2_arrayint degs, int packing)
Definition at line 552 of file monomial-ordering.cpp.
 {
   MonomialOrdering *result;
   mon_part p;
   enum MonomialOrdering_type typ;
   int *wts;
   int all_one = 1;
   unsigned int i;
   for (i = 0; i < degs->len; i++)
     if (degs->array[i] <= 0)
       {
         ERROR("grevlex: expected all degrees to be positive");
         return nullptr;
       }
     else if (degs->array[i] > 1)
       all_one = 0;
   if (all_one)
     {
       if (packing == 2)
         typ = MO_GREVLEX2;
       else if (packing == 4)
         typ = MO_GREVLEX4;
       else
         typ = MO_GREVLEX;
       wts = nullptr;
     }
   else
     {
       if (packing == 2)
         typ = MO_GREVLEX2_WTS;
       else if (packing == 4)
         typ = MO_GREVLEX4_WTS;
       else
         typ = MO_GREVLEX_WTS;
       wts = degs->array;
     }
   p = mo_make(typ, degs->len, wts);
   result = make_mon_order(1);
   result->array[0] = p;
   return result;
 }
References MonomialOrdering::array, ERROR(), make_mon_order(), MO_GREVLEX, MO_GREVLEX2, MO_GREVLEX2_WTS, MO_GREVLEX4, MO_GREVLEX4_WTS, MO_GREVLEX_WTS, mo_make(), p, and mon_part::wts.
Referenced by TEST().