Macaulay2 Engine: intarray_to_string
intarray_to_string()
M2_string intarray_to_string (int len, int * p)
Definition at line 706 of file monomial-ordering.cpp.
 {
   int i;
   const int N = 200;
   char s[N];
   M2_string result = M2_tostring("{");
   for (i = 0; i < len; i++)
     {
       if (i > 0) result = M2_join(result, M2_tostring(","));
       snprintf(s, N, "%d", p[i]);
       result = M2_join(result, M2_tostring(s));
     }
   result = M2_join(result, M2_tostring("}"));
   return result;
 }
References M2_join(), M2_tostring(), and p.
Referenced by IM2_MonomialOrdering_to_string().