Macaulay2 Engine: rawNonTermOrderVariables
rawNonTermOrderVariables()
M2_arrayint rawNonTermOrderVariables (const MonomialOrdering * mo)
Definition at line 466 of file monomial-ordering.cpp.
 {
   int i, j, sum, nextvar;
   int nvars = rawNumberOfVariables(mo);
   int *gt = getmematomicvectortype(int, nvars);
   for (i = 0; i < nvars; i++)
     gt[i] =
         0;  // 0 means undecided, -1 means non term order, 1 means term order
   // Now we loop through the parts of the monomial order
   nextvar = 0;
   for (i = 0; i < mo->len; i++)
     {
       mon_part p = mo->array[i];
       switch (p->type)
         {
           case MO_LEX:
           case MO_LEX2:
           case MO_LEX4:
           case MO_GREVLEX:
           case MO_GREVLEX2:
           case MO_GREVLEX4:
           case MO_GREVLEX_WTS:
           case MO_GREVLEX2_WTS:
           case MO_GREVLEX4_WTS:
           case MO_LAURENT:
           case MO_NC_LEX:
             for (j = 0; j < p->nvars; j++, nextvar++)
               if (gt[nextvar] == 0) gt[nextvar] = 1;
             break;
           case MO_LAURENT_REVLEX:
           case MO_REVLEX:
             for (j = 0; j < p->nvars; j++, nextvar++)
               if (gt[nextvar] == 0) gt[nextvar] = -1;
             break;
           case MO_WEIGHTS:
             for (j = nextvar; j < p->nvars; j++)
               if (gt[j] == 0)
                 {
                   if (p->wts[j] > 0)
                     gt[j] = 1;
                   else if (p->wts[j] < 0)
                     gt[j] = -1;
                 }
             break;
           case MO_POSITION_UP:
           case MO_POSITION_DOWN:
             break;
         }
     }
   // At this point every variables' gt should be 1 or -1.
   sum = 0;
   for (i = 0; i < nvars; i++)
     {
       if (gt[i] == 0) INTERNAL_ERROR("gt[i] should not be 0");
       if (gt[i] < 0) sum++;
     }
   // Make an array of this length.
   M2_arrayint result = M2_makearrayint(sum);
   nextvar = 0;
   for (i = 0; i < nvars; i++)
     if (gt[i] < 0) result->array[nextvar++] = i;
   return result;
 }
References MonomialOrdering::array, getmematomicvectortype, INTERNAL_ERROR(), MonomialOrdering::len, M2_makearrayint(), MO_GREVLEX, MO_GREVLEX2, MO_GREVLEX2_WTS, MO_GREVLEX4, MO_GREVLEX4_WTS, MO_GREVLEX_WTS, MO_LAURENT, MO_LAURENT_REVLEX, MO_LEX, MO_LEX2, MO_LEX4, MO_NC_LEX, MO_POSITION_DOWN, MO_POSITION_UP, MO_REVLEX, MO_WEIGHTS, mon_part::nvars, p, rawNumberOfVariables(), and mpfr::sum().