Macaulay2 Engine: IM2_RingMap_eval_matrix
IM2_RingMap_eval_matrix()
const Matrix* IM2_RingMap_eval_matrix (const RingMap * F, const FreeModule * newTarget, const Matrix * M)
Definition at line 51 of file ringmap.cpp.
 {
   if (newTarget->rank() < M->n_rows())
     {
       ERROR("expected FreeModule of rank at least %d", M->n_rows());
       return nullptr;
     }
   try
     {
       return F->eval(newTarget, M);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References ERROR(), RingMap::eval(), Matrix::n_rows(), and FreeModule::rank().