Macaulay2 Engine: rawRingMapEvalMutableMatrix
rawRingMapEvalMutableMatrix()
MutableMatrix* rawRingMapEvalMutableMatrix (const RingMap * F, const MutableMatrix * M)
Definition at line 70 of file ringmap.cpp.
 {
   try
     {
       return MutableMatrix::zero_matrix(
           F->get_ring(), M->n_rows(), M->n_cols(), M->is_dense());
       // TODO: now map it!
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References ERROR(), RingMap::get_ring(), MutableMatrix::is_dense(), MutableMatrix::n_cols(), MutableMatrix::n_rows(), and MutableMatrix::zero_matrix().