Macaulay2 Engine: SchurRing2::list_form
list_form()
engine_RawArrayPairOrNull SchurRing2::list_form (const Ring * coeffR, const ring_elem f) const
Definition at line 675 of file schur2.cpp.
 {
   if (coeffR != coefficientRing)
     {
       ERROR("expected coefficient ring of Schur ring");
       return 0;
     }
   const schur_poly *f1 = f.get_schur_poly();
   int n = static_cast<int>(f1->size());  // this is here because the lengths of
                                          // arrays for M3 front end use int as
                                          // length field.
   engine_RawMonomialArray monoms =
       GETMEM(engine_RawMonomialArray, sizeofarray(monoms, n));
   engine_RawRingElementArray coeffs =
       GETMEM(engine_RawRingElementArray, sizeofarray(coeffs, n));
   monoms->len = n;
   coeffs->len = n;
   engine_RawArrayPair result = newitem(struct engine_RawArrayPair_struct);
   result->monoms = monoms;
   result->coeffs = coeffs;
   // Loop through the terms
   gc_vector<int> vp;
   schur_poly::iterator i = f1->begin();
   for (int next = 0; next < n; ++i, ++next)
     {
       coeffs->array[next] =
           RingElement::make_raw(coefficientRing, i.getCoefficient());
       to_varpower(i.getMonomial(), vp);
       monoms->array[next] = EngineMonomial::make(vp.data());
       vp.resize(0);
     }
   return result;
 }
References schur_poly::begin(), coefficientRing, ERROR(), ring_elem::get_schur_poly(), schur_poly_iterator::getCoefficient(), GETMEM, schur_poly_iterator::getMonomial(), EngineMonomial::make(), RingElement::make_raw(), newitem, schur_poly::size(), sizeofarray, and to_varpower().
Referenced by IM2_RingElement_list_form().