Macaulay2 Engine: SchurRing2::add
add()
ring_elem SchurRing2::add (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 523 of file schur2.cpp.
 {
   if (is_zero(f)) return g;
   if (is_zero(g)) return f;
   const schur_poly *f1 = f.get_schur_poly();
   const schur_poly *g1 = g.get_schur_poly();
   schur_poly *result = new schur_poly;
   schur_poly::iterator i = f1->begin();
   schur_poly::iterator j = g1->begin();
   schur_poly::iterator iend = f1->end();
   schur_poly::iterator jend = g1->end();
   bool done = false;
   while (!done)
     {
       int cmp = compare_partitions(i.getMonomial(), j.getMonomial());
       switch (cmp)
         {
           case LT:
             result->appendTerm(j.getCoefficient(), j.getMonomial());
             ++j;
             if (j == jend)
               {
                 result->append(i, iend);
                 done = true;
               }
             break;
           case GT:
             result->appendTerm(i.getCoefficient(), i.getMonomial());
             ++i;
             if (i == iend)
               {
                 result->append(j, jend);
                 done = true;
               }
             break;
           case EQ:
             ring_elem c =
                 coefficientRing->add(i.getCoefficient(), j.getCoefficient());
             if (!coefficientRing->is_zero(c))
               result->appendTerm(c, i.getMonomial());
             ++j;
             ++i;
             if (j == jend)
               {
                 result->append(i, iend);
                 done = true;
               }
             else
               {
                 if (i == iend)
                   {
                     result->append(j, jend);
                     done = true;
                   }
               }
             break;
         }
     }
   return ring_elem(result);
 }
References Ring::add(), schur_poly::append(), schur_poly::appendTerm(), schur_poly::begin(), coefficientRing, compare_partitions(), schur_poly::end(), EQ, ring_elem::get_schur_poly(), schur_poly_iterator::getCoefficient(), schur_poly_iterator::getMonomial(), GT, is_zero(), Ring::is_zero(), and LT.
Referenced by schur_poly_heap::add_to(), and subtract().