Macaulay2 Engine: SchurRing2::computeHashValue
computeHashValue()
unsigned int SchurRing2::computeHashValue (const ring_elem a) const virtual
Implements Ring.
Definition at line 91 of file schur2.cpp.
 {
 //  assuming a normal form: distinct monomials in the linear order introduced by compare_partitions()
   const auto& coeffs = a.get_schur_poly()->coeffs;
   const auto& monoms = a.get_schur_poly()->monoms;
   size_t seed = 95864398;  // using previous M2's constant hash value
   for(auto it=coeffs.begin(); it!=coeffs.end(); ++it)
     hash_combine(seed, coefficientRing->computeHashValue(*it));
   for(auto it=monoms.begin(); it!=monoms.end(); ++it)
     hash_combine(seed, *it);
   return static_cast<unsigned>(seed);
 }
References coefficientRing, schur_poly::coeffs, Ring::computeHashValue(), ring_elem::get_schur_poly(), hash_combine(), and schur_poly::monoms.