Macaulay2 Engine: SchurRing2::negate
negate()
ring_elem SchurRing2::negate (const ring_elem f) const virtual
Implements Ring.
Definition at line 489 of file schur2.cpp.
 {
   if (is_zero(f)) return f;
   const schur_poly *f1 = f.get_schur_poly();
   schur_poly *result = new schur_poly;
   for (VECTOR(ring_elem)::const_iterator i = f1->coeffs.begin();
        i != f1->coeffs.end();
        ++i)
     result->coeffs.push_back(coefficientRing->negate(*i));
   result->monoms.insert(
       result->monoms.end(), f1->monoms.begin(), f1->monoms.end());
   return ring_elem(result);
 }
References coefficientRing, schur_poly::coeffs, ring_elem::get_schur_poly(), is_zero(), schur_poly::monoms, Ring::negate(), and VECTOR().
Referenced by subtract().