Macaulay2 Engine: SchurRing2::compare_elems
compare_elems()
int SchurRing2::compare_elems (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 358 of file schur2.cpp.
 {
 //  assuming the monomials are sorted in the linear order on the partitions
 //  see SchurRing2::compare_partitions
   auto f_it = f.get_schur_poly()->begin(),
     f_end = f.get_schur_poly()->end();
   auto g_it = g.get_schur_poly()->begin(),
     g_end = g.get_schur_poly()->end();
   for(; f_it!=f_end && g_it!=g_end; ++f_it, ++g_it) {
     auto cmp = compare_partitions(f_it.getMonomial(), g_it.getMonomial());
     if(cmp) return cmp;
   }
   return (f_it!=f_end)-(g_it!=g_end);  // LT, EQ or GT
 }
References schur_poly::begin(), compare_partitions(), schur_poly::end(), and ring_elem::get_schur_poly().