Macaulay2 Engine: SchurRing2::SM
SM()
void SchurRing2::SM () private
Definition at line 786 of file schur2.cpp.
 {
   int lo, hi;
   if (SMcurrent == SMfinalwt)
     {
       // partition is to be output
       SMsetPartitionLength(SMtab.p, SMmaxrows);
       SMappendTerm(SMtab.p);
       return;
     }
   SMcurrent++;
   SMbounds(lo, hi);
   int this_one = LARGE_NUMBER;  // larger than any entry of SMtab: SMfinalwt+1
                                 // should work...
   int last_one;
   for (int i = lo; i <= hi; i++)
     {
       last_one = this_one;
       this_one = SMtab.p[i];
       if (last_one > this_one)
         {
           SMtab.p[i]++;
           SMtab.xloc[SMcurrent] = i;
           SMtab.yloc[SMcurrent] = SMtab.p[i];
           SM();
           SMtab.p[i]--;
         }
     }
   SMcurrent--;
 }
References LARGE_NUMBER, tableau2::p, SMappendTerm(), SMbounds(), SMcurrent, SMfinalwt, SMmaxrows, SMsetPartitionLength(), SMtab, tableau2::xloc, and tableau2::yloc.
Referenced by skew_schur().