Macaulay2 Engine: SchurRing2::size
size()
size_t SchurRing2::size (ring_elem f) const inline
Definition at line 142 of file schur2.hpp.
 { return f.get_schur_poly()->coeffs.size(); }
References schur_poly::coeffs, and ring_elem::get_schur_poly().
Referenced by schur_poly_heap::add(), and schur_poly_heap::value().