Macaulay2 Engine: SchurRing2::create
create()
SchurRing2 * SchurRing2::create (const Ring * A, int n = -1) static
Definition at line 128 of file schur2.cpp.
 {
   SchurRing2 *R = new SchurRing2(A, n);
   R->initialize_SchurRing2();
   return R;
 }
References initialize_SchurRing2(), and SchurRing2().
Referenced by rawSchurRing2().