Macaulay2 Engine: SchurRing2::elem_text_out
elem_text_out()
void SchurRing2::elem_text_out (buffer & o, const ring_elem f, bool p_one = true, bool p_plus = false, bool p_parens = false) const virtual
Implements Ring.
Definition at line 200 of file schur2.cpp.
 {
   const schur_poly *g = f.get_schur_poly();
   size_t n = g->size();
   bool needs_parens = p_parens && (n > 1);
   if (needs_parens)
     {
       if (p_plus) o << '+';
       o << '(';
       p_plus = false;
     }
   p_one = false;
   for (schur_poly::iterator i = g->begin(); i != g->end(); ++i)
     {
       const_schur_partition part = i.getMonomial();
       int len = *part++;
       int isone = (len == 1);  // the empty partition
       p_parens = !isone;
       coefficientRing->elem_text_out(
           o, i.getCoefficient(), p_one, p_plus, p_parens);
       o << "{";
       for (int j = 0; j < len - 1; j++)
         {
           if (j > 0) o << ",";
           o << part[j];
         }
       o << "}";
       p_plus = true;
     }
   if (needs_parens) o << ')';
 }
References schur_poly::begin(), coefficientRing, Ring::elem_text_out(), schur_poly::end(), ring_elem::get_schur_poly(), and schur_poly::size().