Macaulay2 Engine: SchurRing2::from_partition
from_partition()
ring_elem SchurRing2::from_partition (M2_arrayint part) const
Definition at line 182 of file schur2.cpp.
 {
   schur_poly *f = new schur_poly;
   f->coeffs.push_back(coefficientRing->one());
   int len = last_nonzero(part) + 1;
   f->monoms.push_back(len + 1);
   for (int i = 0; i < len; i++) f->monoms.push_back(part->array[i]);
   return ring_elem(f);
 }
References coefficientRing, schur_poly::coeffs, last_nonzero(), schur_poly::monoms, and Ring::one().
Referenced by rawSchurFromPartition().