Macaulay2 Engine: SchurRing2::get_scalar
get_scalar()
bool SchurRing2::get_scalar (const schur_poly * f, ring_elem & result) const
Definition at line 271 of file schur2.cpp.
 {
   if (g->size() != 1) return false;
   if (g->monoms.size() != 1) return false;
   result = g->coeffs[0];
   return true;
 }
References schur_poly::coeffs, schur_poly::monoms, and schur_poly::size().
Referenced by lift(), and mult().