Macaulay2 Engine: SchurRing2::mult
mult()
ring_elem SchurRing2::mult (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Reimplemented in SchurSnRing.
Definition at line 609 of file schur2.cpp.
 {
   ring_elem resultRE;
   const schur_poly *f1 = f.get_schur_poly();
   const schur_poly *g1 = g.get_schur_poly();
   ring_elem a;
   if (get_scalar(f1, a))
     {
       return ring_elem(mult_by_coefficient(a, g1));
       // In this case, do a simple multiplication
     }
   else if (get_scalar(g1, a))
     {
       return ring_elem(mult_by_coefficient(a, f1));
     }
   else
     {
       // use the poly heap
       schur_poly_heap H(this);
       for (schur_poly::iterator i = f1->begin(); i != f1->end(); ++i)
         for (schur_poly::iterator j = g1->begin(); j != g1->end(); ++j)
           {
             ring_elem c =
                 coefficientRing->mult(i.getCoefficient(), j.getCoefficient());
             ring_elem r = const_cast<SchurRing2 *>(this)->mult_terms(
                 i.getMonomial(), j.getMonomial());
             H.add(ring_elem(mult_by_coefficient(c, r.get_schur_poly())));
           }
       return H.value();
     }
 }
References schur_poly_heap::add(), schur_poly::begin(), coefficientRing, schur_poly::end(), get_scalar(), ring_elem::get_schur_poly(), Ring::mult(), mult_by_coefficient(), mult_terms(), and schur_poly_heap::value().
Referenced by SchurSnRing::mult(), and SchurSnRing::tensor_mult().