Macaulay2 Engine: SchurRing2::initialize_SchurRing2
initialize_SchurRing2()
bool SchurRing2::initialize_SchurRing2 () protected
Definition at line 143 of file schur2.cpp.
 {
   initialize_ring(coefficientRing->characteristic());
   zeroV = from_long(0);
   oneV = from_long(1);
   minus_oneV = from_long(-1);
   SMinitialize(nvars, 0);
   return true;
 }
References Ring::characteristic(), coefficientRing, from_long(), Ring::initialize_ring(), Ring::minus_oneV, nvars, Ring::oneV, SMinitialize(), and Ring::zeroV.
Referenced by create(), SchurSnRing::create(), and createInfinite().