Macaulay2 Engine: SchurRing2::is_equal
is_equal()
bool SchurRing2::is_equal (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 251 of file schur2.cpp.
 {
   const schur_poly *f1 = f.get_schur_poly();
   const schur_poly *g1 = g.get_schur_poly();
   if (f1->size() != g1->size()) return false;
   if (f1->monoms.size() != g1->monoms.size()) return false;
   VECTOR(schur_word)::const_iterator m_f = f1->monoms.begin();
   VECTOR(schur_word)::const_iterator m_g = g1->monoms.begin();
   for (; m_f != f1->monoms.end(); ++m_f, ++m_g)
     if (*m_f != *m_g) return false;
   VECTOR(ring_elem)::const_iterator c_f = f1->coeffs.begin();
   VECTOR(ring_elem)::const_iterator c_g = g1->coeffs.begin();
   for (; c_f != f1->coeffs.end(); ++c_f, ++c_g)
     if (!coefficientRing->is_equal(*c_f, *c_g)) return false;
   return true;
 }
References coefficientRing, schur_poly::coeffs, ring_elem::get_schur_poly(), Ring::is_equal(), schur_poly::monoms, schur_poly::size(), and VECTOR().