Macaulay2 Engine: SchurRing2::promote_coeffs
promote_coeffs()
bool SchurRing2::promote_coeffs (const SchurRing2 * Sf, const ring_elem f, ring_elem & resultRE) const protected
Definition at line 376 of file schur2.cpp.
 {
   // Assumption in use: Rf (ring of f) is a Schur ring, with coeff ring coeffRf
   const schur_poly *f1 = f.get_schur_poly();
   schur_poly *result = new schur_poly;
   for (schur_poly::iterator i = f1->begin(); i != f1->end(); ++i)
     {
       if (i.getMonomial()[0] - 1 > nvars) continue;
       ring_elem a;
       if (!coefficientRing->promote(
               Rf->getCoefficientRing(), i.getCoefficient(), a))
         {
           delete result;
           resultRE = from_long(0);
           return false;
         }
       result->appendTerm(a, i.getMonomial());
     }
   resultRE = ring_elem(result);
   return true;
 }
References schur_poly::appendTerm(), schur_poly::begin(), coefficientRing, schur_poly::end(), from_long(), ring_elem::get_schur_poly(), getCoefficientRing(), nvars, and Ring::promote().
Referenced by promote().