Macaulay2 Engine: SchurRing2::truncate
truncate()
ring_elem SchurRing2::truncate (const ring_elem f) const protected
Definition at line 505 of file schur2.cpp.
 {
   if (is_zero(f)) return f;
   const schur_poly *f1 = f.get_schur_poly();
   schur_poly *result = new schur_poly;
   for (schur_poly::iterator i = f1->begin(); i != f1->end(); ++i)
     {
       if (i.getMonomial()[0] - 1 > nvars) continue;
       result->appendTerm(i.getCoefficient(), i.getMonomial());
     }
   return ring_elem(result);
 }
References schur_poly::appendTerm(), schur_poly::begin(), and schur_poly::end().
Referenced by lift(), and promote().