Macaulay2 Engine: SchurRing2::promote
promote()
bool SchurRing2::promote (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 424 of file schur2.cpp.
 {
   // Cases:
   // 1.  Rf is ZZ
   // 2. Rf is coefficientRing
   // 3. Rf is another SchurRing2
   if (Rf == globalZZ)
     {
       from_coeff(Rf->promote(globalZZ, f, result));
       return true;
     }
   else if (Rf == coefficientRing)
     {
       result = from_coeff(f);
       return true;
     }
   else
     {
       const SchurRing2 *Sf = Rf->cast_to_SchurRing2();
       if (Sf != 0)
         {
           if (coefficientRing == Sf->getCoefficientRing())
             {
               result = truncate(f);
               return true;
             }
           return promote_coeffs(Sf, f, result);
         }
     }
   return false;
 }
References Ring::cast_to_SchurRing2(), coefficientRing, from_coeff(), getCoefficientRing(), globalZZ, Ring::promote(), promote_coeffs(), and truncate().