Macaulay2 Engine: SchurRing2::skew_schur
skew_schur()
ring_elem SchurRing2::skew_schur (const_schur_partition lambda, const_schur_partition p) private
Definition at line 827 of file schur2.cpp.
 {
   SMcurrent = 0;
   SMfinalwt = 0;
   for (int i = 1; i < p[0]; i++) SMfinalwt += p[i];
   for (int i = 1; i < lambda[0]; i++) SMfinalwt -= lambda[i];
   SMmaxrows = p[0] - 1;  // this is the number of elements in the partition p
   if (nvars != -1 && SMmaxrows > nvars) SMmaxrows = nvars;
   delete[] SMtab
       .p;  // FLAG: should use gc for this?  or not use it, but not both!
   SMtab.p = new int[SMmaxrows + 1];  // FLAG: should use gc for this?  or not
                                      // use it, but not both!
   for (int i = 0; i <= SMmaxrows; i++) SMtab.p[i] = 0;
   SMtab.wt = SMfinalwt;
   SMtab.resize(SMfinalwt);
   SMfilled.resize(SMfinalwt);
   // lambda and p should not be modified in the following call
   SMfilled.fill(const_cast<schur_partition>(lambda),
                 const_cast<schur_partition>(
                     p));  // FLAG:fill should take const arguments...
   lambda++;               // FLAG: why is this here?
   p++;                    // FLAG: why is this here?
   SM();
   return SMheap->value();  // resets itself back to new
 }
References tableau2::fill(), nvars, p, tableau2::p, tableau2::resize(), SM(), SMcurrent, SMfilled, SMfinalwt, SMheap, SMmaxrows, SMtab, schur_poly_heap::value(), and tableau2::wt.
Referenced by mult_terms().