Macaulay2 Engine: SchurRing2::SMappendTerm
SMappendTerm()
void SchurRing2::SMappendTerm (const_schur_partition f) private
Definition at line 819 of file schur2.cpp.
 {
   // make a poly, and insert it into the heap
   schur_poly * val = new schur_poly;
   val->appendTerm(coefficientRing->one(), f);
   SMheap->add(ring_elem(val));
 }
References schur_poly_heap::add(), schur_poly::appendTerm(), coefficientRing, Ring::one(), and SMheap.
Referenced by SM().