Macaulay2 Engine: SchurRing2::from_long
from_long()
ring_elem SchurRing2::from_long (long n) const virtual
Implements Ring.
Definition at line 289 of file schur2.cpp.
 {
   ring_elem a = coefficientRing->from_long(n);
   return from_coeff(a);
 }
References coefficientRing, from_coeff(), and Ring::from_long().
Referenced by initialize_SchurRing2(), lift_coeffs(), and promote_coeffs().