Macaulay2 Engine: SchurRing2::lift
lift()
bool SchurRing2::lift (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 459 of file schur2.cpp.
 {
   const schur_poly *f1 = f.get_schur_poly();
   if (Rg == coefficientRing || Rg == globalZZ)
     {
       if (get_scalar(f1, result))
         {
           if (Rg == globalZZ)
             return coefficientRing->lift(globalZZ, result, result);
           return true;
         }
     }
   else
     {
       const SchurRing2 *Sg = Rg->cast_to_SchurRing2();
       if (Sg != nullptr)
         {
           if (coefficientRing == Sg->getCoefficientRing())
             {
               result = Sg->truncate(f);
               return true;
             }
           return lift_coeffs(Sg, f, result);
         }
     }
   return false;
 }
References Ring::cast_to_SchurRing2(), coefficientRing, get_scalar(), ring_elem::get_schur_poly(), getCoefficientRing(), globalZZ, Ring::lift(), lift_coeffs(), and truncate().