Macaulay2 Engine: SchurRing2::from_coeff
from_coeff()
ring_elem SchurRing2::from_coeff (ring_elem a) const
Definition at line 279 of file schur2.cpp.
 {
   schur_poly *f = new schur_poly;
   if (!coefficientRing->is_zero(a))
     {
       f->coeffs.push_back(a);
       f->monoms.push_back(1);
     }
   return ring_elem(f);
 }
References coefficientRing, schur_poly::coeffs, Ring::is_zero(), and schur_poly::monoms.
Referenced by from_int(), from_long(), from_rational(), and promote().