Macaulay2 Engine: SchurRing2::createInfinite
createInfinite()
SchurRing2 * SchurRing2::createInfinite (const Ring * A) static
Definition at line 135 of file schur2.cpp.
 {
   SchurRing2 *R = new SchurRing2(A);
   R->initialize_SchurRing2();
   return R;
 }
References initialize_SchurRing2(), and SchurRing2().
Referenced by rawSchurRing1().