Macaulay2 Engine: newf4::PolynomialList::vectorArithmetic
vectorArithmetic()
const VectorArithmetic& newf4::PolynomialList::vectorArithmetic () const inline
Definition at line 31 of file PolynomialList.hpp.
 { return mVectorArithmetic; }
References mVectorArithmetic.
Referenced by newf4::PolynomialListStreamCollector::appendPolynomialDone(), newf4::Polynomial::end(), newf4::toStream(), and newf4::Basis::vectorArithmetic().