Macaulay2 Engine: newf4::PolynomialList::size
size()
size_t newf4::PolynomialList::size () const inline
Definition at line 36 of file PolynomialList.hpp.
{ return mPolynomials.size(); }
References mPolynomials.
Referenced by newf4::PolynomialListStreamCollector::appendPolynomialDone(), newf4::PolynomialListStreamCollector::idealDone(), and newf4::toStream().