Macaulay2 Engine: TEST
TEST() [1/19]
TEST (FreeAlgebra , comparisons)
Definition at line 381 of file NCGroebnerTest.cpp.
 {
   FreeAlgebra* A = FreeAlgebra::create(globalQQ,
                                        { "x", "y", "z" },
                                        degreeRing(1),
                                        {1,2,3},
                                        {},
                                        {1}
                                        );
   FreeAlgebraElement x(A), y(A), z(A), f(A), g(A), h(A);
   A->var(*x, 0);
   A->var(*y, 1);
   A->var(*z, 2);
   EXPECT_TRUE(A->compare_elems(*x,*y) == GT);
   EXPECT_TRUE(A->compare_elems(*y,*x) == LT);
   EXPECT_TRUE(A->compare_elems(*x,*x) == EQ);
 }
References FreeAlgebra::compare_elems(), FreeAlgebra::create(), degreeRing(), EQ, globalQQ, GT, LT, FreeAlgebra::var(), and x.