Macaulay2 Engine: TEST
TEST() [3/19]
TEST (FreeAlgebra , polyarithmetic)
Definition at line 284 of file NCGroebnerTest.cpp.
 {
   FreeAlgebra* A = FreeAlgebra::create(globalQQ,
                                        { "x", "y", "z" },
                                        degreeRing(1),
                                        {1,2,3},
                                        {},
                                        {1}
                                        );
   FreeAlgebraElement x(A), y(A), z(A), f(A), g(A), h(A);
   A->var(*x, 0);
   A->var(*y, 1);
   A->var(*z, 2);
   f = x + y;
   g = y + z;
   EXPECT_TRUE(x + y == y + x);
   EXPECT_FALSE(f == g);
   EXPECT_TRUE(x * (y + z) == x * y + x * z);
   EXPECT_TRUE((f * g) * f == f * (g * f));
   EXPECT_TRUE((f^2) == (f * f));
   A->from_word(*h, {1,2,1,0,1});
   EXPECT_TRUE(h == y * z * y * x * y);
   A->setZero(*f);
   A->subtract(*f,*x,*y);
   EXPECT_TRUE(f == (x - y));
   A->setZero(*f);
   A->setZero(*g);
   A->from_long(*f,1);
   std::vector<int> gdata {};
   A->from_word(*g, gdata);
   // from_rational test? How to create an mpq_ptr?
   EXPECT_TRUE(f == g);
   EXPECT_TRUE(A->is_unit(*f));
   EXPECT_TRUE((h^0) == f);
   A->setZero(*f);
   A->setZero(*g);
   A->setZero(*h);
   f = x + y;
   A->from_long(*g,-1);
   A->negate(*h,*f);
   EXPECT_TRUE(h == f*g);
   A->setZero(*h);
   A->mult_by_coeff(*h,*f,A->coefficientRing()->from_long(-1));
   EXPECT_TRUE(h == f*g);
   A->setZero(*f);
   A->setZero(*g);
   A->setZero(*h);
   EXPECT_TRUE(A->is_zero(*h));
   f = x + y;
   A->lead_term_as_poly(*g,*f);
   EXPECT_TRUE(g == x);
   A->add_to_end(*f,*z);
   EXPECT_TRUE(f == (x + y + z));
   A->subtract(*h,*f,*(x+y+z));
   EXPECT_TRUE(A->is_zero(*h));
   A->setZero(*f);
   A->setZero(*g);
   f = x + y;
   A->mult_by_term_left(*g,*f,A->coefficientRing()->from_long(1),Word(monom2));
   EXPECT_TRUE(g == z*z*f);
   A->setZero(*g);
   A->mult_by_term_right(*g,*f,A->coefficientRing()->from_long(1),Word(monom3));
   EXPECT_TRUE(g == f*y*x*y*x);
   A->setZero(*g);
   A->mult_by_term_left_and_right(*g,*f,A->coefficientRing()->from_long(1),Word(monom2),Word(monom3));
   EXPECT_TRUE(g == z*z*f*y*x*y*x);
   // making polynomial monic test
   A->setZero(*f);
   A->setZero(*g);
   A->setZero(*h);
   A->from_long(*f,-1);
   g = f*(x + y);
   A->makeMonic(*h,*g);
   EXPECT_TRUE(h == x + y);
 }
References FreeAlgebra::add_to_end(), FreeAlgebra::coefficientRing(), FreeAlgebra::create(), degreeRing(), Ring::from_long(), FreeAlgebra::from_long(), FreeAlgebra::from_word(), globalQQ, FreeAlgebra::is_unit(), FreeAlgebra::is_zero(), FreeAlgebra::lead_term_as_poly(), FreeAlgebra::makeMonic(), monom2, monom3, FreeAlgebra::mult_by_coeff(), FreeAlgebra::mult_by_term_left(), FreeAlgebra::mult_by_term_left_and_right(), FreeAlgebra::mult_by_term_right(), FreeAlgebra::negate(), FreeAlgebra::setZero(), FreeAlgebra::subtract(), FreeAlgebra::var(), and x.