Macaulay2 Engine: TEST
TEST() [13/19]
TEST (OverlapTable , insertion)
Definition at line 455 of file NCGroebnerTest.cpp.
 {
   OverlapTable overlapTable;
   overlapTable.insert(3,false,std::make_tuple(1,2,3,true));
   overlapTable.insert(3,false,std::make_tuple(1,2,1,true));
   overlapTable.insert(2,false,std::make_tuple(1,1,1,true));
   EXPECT_FALSE(overlapTable.isFinished());
   EXPECT_TRUE(overlapTable.isFinished(1));
   EXPECT_FALSE(overlapTable.isFinished(3));
   EXPECT_TRUE(overlapTable.size() == 3);
 }
References OverlapTable::insert(), OverlapTable::isFinished(), and OverlapTable::size().