Macaulay2 Engine: TEST
TEST() [5/19]
TEST (FreeAlgebra , spairs)
Definition at line 399 of file NCGroebnerTest.cpp.
 {
   FreeAlgebra* A = FreeAlgebra::create(globalQQ,
                                        { "x", "y", "z" },
                                        degreeRing(1),
                                        {3,2,1},
                                        {3,2,1},
                                        {1}
                                        );
   FreeAlgebraElement x(A), y(A), z(A), f(A), g(A), h(A);
   A->var(*x, 0);
   A->var(*y, 1);
   A->var(*z, 2);
   f = x*y*x + z*y*z;
   Word leadWord = A->lead_word(*f);
   Word leadWordPrefix = A->lead_word_prefix(*f,2);
   Word leadWordSuffix = A->lead_word_suffix(*f,1);
   // TODO: did the offset change on our recent heft changes?
   EXPECT_TRUE((*f).cbegin().monom().begin() + 2 == leadWord.begin() && (*f).cbegin().monom().begin() + 5 == leadWord.end());
   EXPECT_TRUE((*f).cbegin().monom().begin() + 2 == leadWordPrefix.begin() && (*f).cbegin().monom().begin() + 4 == leadWordPrefix.end());
   EXPECT_TRUE((*f).cbegin().monom().begin() + 3 == leadWordSuffix.begin() && (*f).cbegin().monom().begin() + 5 == leadWordSuffix.end());
   PolyList polyList {&*f};
   *g = *(NCGroebner::createOverlapPoly(*A, polyList, 0, 2, 0));
   h = f*y*x - x*y*f;
   EXPECT_TRUE(g == h);
 }
References Word::begin(), FreeAlgebra::create(), NCGroebner::createOverlapPoly(), degreeRing(), Word::end(), globalQQ, FreeAlgebra::lead_word(), FreeAlgebra::lead_word_prefix(), FreeAlgebra::lead_word_suffix(), FreeAlgebra::var(), and x.