Macaulay2 Engine: TEST
TEST() [18/19]
TEST (WordTable , skylanin)
Definition at line 651 of file NCGroebnerTest.cpp.
 {
   // X,Y Z are the 3 variables
 #if 0
   mons = {{Z, X}, {Z, Y}, {Z, Z}, {Y, Y, X}, {Y, Y, Z},
             {Y, X, Y, Y}, {Y, Y, Y, Y}, {Y, X, Y, X, X},
             {Y, X, Y, X, Y}, {Y, X, Y, X, Z},
             {Y, X, X, Y, X, X}, {Y, X, X, Y, X, Z},
           {Y, X, X, Y, Y, Y}}
 #endif
   std::vector<int> m0 {2,0};  // ZX
   std::vector<int> m1 {2,1};  // ZY
   std::vector<int> m2 {2,2};  // ZZ
   std::vector<int> m3 {1,1,0};  // YYX
   std::vector<int> m4 {1,1,2};  // YYZ
   std::vector<int> m5 {1,0,1,1};  // YXYY
   std::vector<int> m6 {1,1,1,1};  // YYYY
   std::vector<int> m7 {1,0,1,0,0};  // YXYXX
   std::vector<int> m8 {1,0,1,0,1};  // YXYXY
   std::vector<int> m9 {1,0,1,0,2};  // YXYXZ
   std::vector<int> m10 {1,0,0,1,0,0};  // YXXYXX
   std::vector<int> m11 {1,0,0,1,0,2};  // YXXYXZ
   std::vector<int> m12 {1,0,0,1,1,1};  // YXXYYY
   std::vector<Overlap> overlaps;
   std::vector<std::pair<int,int>> matches;
   WordTable W;
   W.insert(Word(m0), overlaps);
   EXPECT_EQ(0, overlaps.size());
   W.insert(Word(m1), overlaps);
   EXPECT_EQ(0, overlaps.size());
   W.insert(Word(m2), overlaps);
   std::vector<Overlap> ans {
       std::make_tuple(2,1,0,true),
       std::make_tuple(2,1,1,true),
       std::make_tuple(2,1,2,true)
       };
   std::sort(ans.begin(),ans.end());
   std::sort(overlaps.begin(),overlaps.end());
   EXPECT_EQ(overlaps, ans);
   overlaps.clear();
   W.leftOverlaps(overlaps);
   EXPECT_EQ(0, overlaps.size());
   W.insert(Word(m3));
   W.insert(Word(m4));
   W.insert(Word(m5));
   W.insert(Word(m6));
   W.insert(Word(m7));
   W.insert(Word(m8));
   W.insert(Word(m9));
   W.insert(Word(m10));
   W.insert(Word(m11));
   W.insert(Word(m12));
   matches.clear();
   W.superwords(Word(std::vector<int> {1, 1}), matches);
   std::vector<std::pair<int,int>> ans2
     {
      std::make_pair(3,0),
      std::make_pair(4,0),
      std::make_pair(5,2),
      std::make_pair(6,0),
      std::make_pair(6,1),
      std::make_pair(6,2),
      std::make_pair(12,3),
      std::make_pair(12,4)
     };
   std::sort(ans2.begin(),ans2.end());
   std::sort(matches.begin(),matches.end());
   EXPECT_EQ(ans2, matches);
   matches.clear();
   EXPECT_TRUE(W.isNontrivialSuperword(Word(std::vector<int> {1,2,1,1,2,1,1}), 6, 6));
   EXPECT_TRUE(W.isNontrivialSuperword(Word(std::vector<int> {1,1,2,1,1,2,1,1,2}), 4, 4));
   matches.clear();
   W.subwords(Word(std::vector<int> {2,2,0,1,1,0,1,0,1,1}), matches); // ZZXYYXYXYY
   std::vector<std::pair<int,int>> ans3
     {
      {0,1},
      {2,0},
      {3,3},
      {5,6},
      {8,4}
     };
   std::sort(ans3.begin(),ans3.end());
   std::sort(matches.begin(),matches.end());
   EXPECT_EQ(ans3, matches);
 }
References WordTable::insert(), WordTable::isNontrivialSuperword(), WordTable::leftOverlaps(), WordTable::subwords(), and WordTable::superwords().