Macaulay2 Engine: TEST
TEST() [4/19]
TEST (FreeAlgebra , quotientArithmetic)
Definition at line 340 of file NCGroebnerTest.cpp.
 {
   FreeAlgebra* Q = FreeAlgebra::create(globalQQ,
                                        { "x", "y", "z" },
                                        degreeRing(1),
                                        {1,2,3},
                                        {},
                                        {1}
                                        );
   FreeAlgebraElement X(Q), Y(Q), Z(Q), F(Q), G(Q), H(Q);
   Q->var(*X,0);
   Q->var(*Y,1);
   Q->var(*Z,2);
   F = X*Y + Y*X;
   G = X*Z + Z*X;
   H = Y*Z + Z*Y;
   auto GB = std::unique_ptr<ConstPolyList> (new ConstPolyList);
   //auto GB = new ConstPolyList;
   GB->push_back(&*F);
   GB->push_back(&*G);
   GB->push_back(&*H);
   EXPECT_TRUE(GB->size() == 3);
   FreeAlgebraQuotient* A = new FreeAlgebraQuotient(*Q, *GB, -1); // are we transferring ownership of GB?
   FreeAlgebraQuotientElement x(A), y(A), z(A), f(A), g(A), h(A);
   // check if things reduce properly
   A->var(*x,0);
   A->var(*y,1);
   A->var(*z,2);
   A->setZero(*f);
   A->setZero(*g);
   A->setZero(*h);
   f = x*y*x*z*x*y*x*z;
   g = x*x*x*x*y*y*z*z;
   A->negate(*h,*g);
   EXPECT_TRUE(f == h);
 }
References FreeAlgebra::create(), degreeRing(), G, globalQQ, FreeAlgebraQuotient::negate(), FreeAlgebraQuotient::setZero(), FreeAlgebra::var(), FreeAlgebraQuotient::var(), and x.