Macaulay2 Engine: TEST
TEST() [2/19]
TEST (FreeAlgebra , create)
Definition at line 266 of file NCGroebnerTest.cpp.
 {
   if (degreeRing(1) == nullptr or error())
     {
       std::cout << "Error: " << error_message() << std::endl;
       EXPECT_TRUE(false);
     }
   FreeAlgebra* A = FreeAlgebra::create(globalQQ,
                                        { "x", "y", "z" },
                                        degreeRing(1),
                                        {1,2,3},
                                        {},
                                        {1}
                                        );
   EXPECT_TRUE(A != nullptr);
 }
References FreeAlgebra::create(), degreeRing(), error(), error_message(), and globalQQ.