Macaulay2 Engine: degreeMonoid
degreeMonoid()
const Monoid* degreeMonoid (const std::vector< std::string > & names)
Monoid tests
Definition at line 55 of file NCGroebnerTest.cpp.
 {
   std::vector<int> wts;
   for (int i=0; i<names.size(); i++)
     wts.push_back(-1);
   MonomialOrdering* mo = MonomialOrderings::join
     ({
       MonomialOrderings::Weights(wts),
       MonomialOrderings::GroupLex(1),
       MonomialOrderings::PositionUp()
     });
   return Monoid::create(mo,
                         names,
                         IM2_Ring_trivial_polyring()->cast_to_PolynomialRing(),
                         {},
                         {});
 }
References Monoid::create(), MonomialOrderings::GroupLex(), IM2_Ring_trivial_polyring(), MonomialOrderings::join(), MonomialOrderings::PositionUp(), and MonomialOrderings::Weights().
Referenced by degreeRing().