Macaulay2 Engine: TEST
TEST() [16/19]
TEST (WordTable , prefix_suffix)
Definition at line 577 of file NCGroebnerTest.cpp.
 {
   std::vector<int> monom1 {1, 0, 1, 2};  // babc
   std::vector<int> monom2 {1, 0, 2, 2};  // bacc
   std::vector<int> monom3 {1, 0, 1, 0};  // baba
   std::vector<int> word {1, 0, 1, 0, 2, 2, 1, 0, 1, 2};
   std::vector<int> word2 {1, 0, 1, 1, 2, 2, 1, 1, 1, 2};
   WordTable W;
   EXPECT_EQ(monom1.size(), 4);
   EXPECT_EQ(monom2.size(), 4);
   EXPECT_EQ(monom3.size(), 4);
   EXPECT_EQ(word.size(), 10);
   W.insert(Word(monom1));
   W.insert(Word(monom2));
   W.insert(Word(monom3));
   int ind = -1; // index of prefix solution, if any.
   int ind2 = -1; // index of suffix solution, if any.
   bool isprefix = W.isPrefix(Word(word), ind);
   bool issuffix = W.isSuffix(Word(word), ind2);
   EXPECT_TRUE(isprefix);
   EXPECT_TRUE(issuffix);
   EXPECT_EQ(2, ind);
   EXPECT_EQ(0, ind2);
   ind = -1;
   ind2 = -1;
   isprefix = W.isPrefix(Word(monom1), ind);
   issuffix = W.isSuffix(Word(monom2), ind2);
   EXPECT_TRUE(isprefix);
   EXPECT_EQ(0,ind);
   EXPECT_TRUE(issuffix);
   EXPECT_EQ(1,ind2);
   ind = -1;
   ind2 = -1;
   isprefix = W.isPrefix(Word(word2), ind);
   issuffix = W.isSuffix(Word(word2), ind2);
   EXPECT_FALSE(isprefix);
   EXPECT_FALSE(issuffix);
 }
References WordTable::insert(), WordTable::isPrefix(), WordTable::isSuffix(), monom1, monom2, monom3, and word.