Macaulay2 Engine: degreeRing
degreeRing() [1/2]
const PolynomialRing* degreeRing (const std::vector< std::string > & names)
Definition at line 74 of file NCGroebnerTest.cpp.
 {
   auto degM = degreeMonoid(names);
   if (degM == nullptr) return nullptr;
   return PolyRing::create(globalZZ, degM);
 }
References PolyRing::create(), degreeMonoid(), and globalZZ.
Referenced by FreeAlgebra::create(), degreeRing(), rawRingM2FreeAlgebra(), and TEST().