Macaulay2 Engine: check_nterm_multiples
check_nterm_multiples()
static bool check_nterm_multiples (const PolyRing * R, ring_elem f1, ring_elem g1, ring_elem c, ring_elem d) static
Definition at line 886 of file ring-vecs.cpp.
{
  Nterm *f;
  Nterm *g;
  const Monoid *M = R->getMonoid();
  const Ring *K = R->getCoefficients();
  for (f = f1, g = g1; f != nullptr && g != nullptr; f = f->next, g = g->next)
    {
      if (M->compare(f->monom, g->monom) != 0) return false;
      ring_elem c1 = K->mult(c, g->coeff);
      ring_elem d1 = K->mult(d, f->coeff);
      int isequal = K->is_equal(c1, d1);
      if (!isequal) return false;
    }
  if (f == nullptr && g == nullptr) return true;
  return false;
}
References Nterm::coeff, Monoid::compare(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), Ring::is_equal(), Nterm::monom, Ring::mult(), and Nterm::next.
Referenced by Ring::vec_is_scalar_multiple().