Macaulay2 Engine: SchreyerOrder::text_out
text_out()
void SchreyerOrder::text_out (buffer & o) const
Definition at line 313 of file schorder.cpp.
 {
   for (int i = 0; i < _rank; i++)
     {
       if (i != 0) o << ' ';
       M->elem_text_out(o, base_monom(i));
       o << '.';
       o << compare_num(i);
     }
 }
References _rank, base_monom(), compare_num(), Monoid::elem_text_out(), and M.
Referenced by FreeModule::text_out().