Macaulay2 Engine: SchreyerOrder::rank
rank()
int SchreyerOrder::rank () const inline
Definition at line 34 of file schorder.hpp.
 { return _rank; }
References _rank.
Referenced by append_order(), copy(), sub_space(), and SchreyerOrder_symm::symm1().