Macaulay2 Engine: SchreyerOrder::create
create() [3/3]
SchreyerOrder * SchreyerOrder::create (const Monoid * m) static
Definition at line 11 of file schorder.cpp.
 {
   SchreyerOrder *S = new SchreyerOrder(M);
   intern_SchreyerOrder(S);
   return S;
 }
References intern_SchreyerOrder(), M, and SchreyerOrder().
Referenced by FreeModule::FreeModule(), FreeModule::make_schreyer(), and SchreyerOrder_symm::value().