Macaulay2 Engine: SchreyerOrder::schreyer_compare_encoded
schreyer_compare_encoded()
int SchreyerOrder::schreyer_compare_encoded (const_monomial m, int m_comp, const_monomial n, int n_comp) const
Definition at line 343 of file schorder.cpp.
 {
   int cmp = M->compare(m, n);
   if (cmp != EQ) return cmp;
   cmp = compare_num(m_comp) - compare_num(n_comp);
   if (cmp < 0) return LT;
   if (cmp > 0) return GT;
   return EQ;
 }
References Monoid::compare(), compare_num(), EQ, GT, LT, and M.
Referenced by GBRing::gbvector_compare().