Macaulay2 Engine: SchreyerOrder::append_order
append_order()
void SchreyerOrder::append_order (const SchreyerOrder * G)
Definition at line 182 of file schorder.cpp.
 {
   for (int i = 0; i < G->rank(); i++)
     append(G->compare_num(i), G->base_monom(i));
 }
References append(), base_monom(), compare_num(), and rank().
Referenced by direct_sum().