Macaulay2 Engine: SchreyerOrder::sub_space
sub_space() [2/2]
SchreyerOrder * SchreyerOrder::sub_space (M2_arrayint a) const
Definition at line 164 of file schorder.cpp.
 {
   // Since this is called only from FreeModule::sub_space,
   // the elements of 'a' are all in bounds, and do not need to be checked...
   // BUT, we check anyway...
   SchreyerOrder *result = new SchreyerOrder(M);
   for (unsigned int i = 0; i < a->len; i++)
     if (a->array[i] >= 0 && a->array[i] < rank())
       result->append(compare_num(a->array[i]), base_monom(a->array[i]));
     else
       {
         ERROR("schreyer order subspace: index out of bounds");
         freemem(result);
         return NULL;
       }
   return result;
 }
References append(), base_monom(), compare_num(), ERROR(), freemem(), M, rank(), and SchreyerOrder().