Macaulay2 Engine: SchreyerOrder::create
create() [1/3]
SchreyerOrder * SchreyerOrder::create (const GBMatrix * m) static
Definition at line 80 of file schorder.cpp.
 {
 #ifdef DEVELOPMENT
 #warning "the logic in SchreyerOrder creation is WRONG!"
 #endif
   int i;
   const FreeModule *F = m->get_free_module();
   const Ring *R = F->get_ring();
   const SchreyerOrder *S = F->get_schreyer_order();
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   const Monoid *M = P->getMonoid();
   SchreyerOrder *result = new SchreyerOrder(M);
   int rk = INTSIZE(m->elems);
   if (rk == 0) return result;
   monomial base = M->make_one();
   int *tiebreaks = newarray_atomic(int, rk);
   int *ties = newarray_atomic(int, rk);
   for (i = 0; i < rk; i++)
     {
       gbvector *v = m->elems[i];
       if (v == NULL || S == NULL)
         tiebreaks[i] = i;
       else
         tiebreaks[i] = i + rk * S->compare_num(v->comp - 1);
     }
   // Now sort tiebreaks in increasing order.
   std::sort<int *>(tiebreaks, tiebreaks + rk);
   for (i = 0; i < rk; i++) ties[tiebreaks[i] % rk] = i;
   for (i = 0; i < rk; i++)
     {
       gbvector *v = m->elems[i];
       if (v == NULL)
         M->one(base);
       else  // if (S == NULL)
         M->copy(v->monom, base);
 #ifdef DEVELOPMENT
 #warning "Schreyer unencoded case not handled here"
 #endif
 #if 0
 //       else
 //      M->mult(v->monom, S->base_monom(i), base);
 #endif
       result->append(ties[i], base);
     }
   intern_SchreyerOrder(result);
   M->remove(base);
   freemem(tiebreaks);
   freemem(ties);
   return result;
 }
References append(), base, Ring::cast_to_PolynomialRing(), gbvector::comp, compare_num(), Monoid::copy(), GBMatrix::elems, freemem(), GBMatrix::get_free_module(), FreeModule::get_ring(), FreeModule::get_schreyer_order(), PolynomialRing::getMonoid(), intern_SchreyerOrder(), INTSIZE, M, Monoid::make_one(), gbvector::monom, newarray_atomic, Monoid::one(), Monoid::remove(), and SchreyerOrder().