Macaulay2 Engine: SchreyerOrder::sub_space
sub_space() [1/2]
SchreyerOrder * SchreyerOrder::sub_space (int n) const
Definition at line 154 of file schorder.cpp.
{
  if (n < 0 || n > rank())
    {
      ERROR("sub schreyer order: index out of bounds");
      return nullptr;
    }
  SchreyerOrder *result = new SchreyerOrder(M);
  for (int i = 0; i < n; i++) result->append(compare_num(i), base_monom(i));
  return result;
}
References append(), base_monom(), compare_num(), ERROR(), M, and rank().
Referenced by FreeModule::sub_space(), and FreeModule::sub_space().