Macaulay2 Engine: SchreyerOrder::create
create() [2/3]
SchreyerOrder * SchreyerOrder::create (const Matrix * m) static
Definition at line 27 of file schorder.cpp.
 {
   int i;
   const Ring *R = m->get_ring();
   const SchreyerOrder *S = m->rows()->get_schreyer_order();
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   if (P == 0)
     {
       throw exc::engine_error("expected polynomial ring");
     }
   const Monoid *M = P->getMonoid();
   SchreyerOrder *result = new SchreyerOrder(M);
   int rk = m->n_cols();
   if (rk == 0) return result;
   int *base = M->make_one();
   int *tiebreaks = newarray_atomic(int, rk);
   int *ties = newarray_atomic(int, rk);
   for (i = 0; i < rk; i++)
     {
       vec v = (*m)[i];
       if (v == NULL || S == NULL)
         tiebreaks[i] = i;
       else
         tiebreaks[i] = i + rk * S->compare_num(v->comp);
     }
   // Now sort tiebreaks in increasing order.
   std::sort<int *>(tiebreaks, tiebreaks + rk);
   for (i = 0; i < rk; i++) ties[tiebreaks[i] % rk] = i;
   for (i = 0; i < rk; i++)
     {
       vec v = (*m)[i];
       if (v == NULL)
         M->one(base);
       else if (S == NULL)
         M->copy(P->lead_flat_monomial(v->coeff), base);
       else
         {
           int x = v->comp;
           M->mult(P->lead_flat_monomial(v->coeff), S->base_monom(x), base);
         }
       result->append(ties[i], base);
     }
   intern_SchreyerOrder(result);
   M->remove(base);
   freemem(tiebreaks);
   freemem(ties);
   return result;
 }
References append(), base, base_monom(), Ring::cast_to_PolynomialRing(), compare_num(), Monoid::copy(), freemem(), Matrix::get_ring(), FreeModule::get_schreyer_order(), PolynomialRing::getMonoid(), intern_SchreyerOrder(), PolynomialRing::lead_flat_monomial(), M, Monoid::make_one(), Monoid::mult(), Matrix::n_cols(), newarray_atomic, Monoid::one(), Monoid::remove(), Matrix::rows(), SchreyerOrder(), and x.