Macaulay2 Engine: SchreyerOrder::base_monom
base_monom()
const_monomial SchreyerOrder::base_monom (int i) const inline
Definition at line 36 of file schorder.hpp.
{ return _order.data() + i * _nslots + 1; }
References _nslots, and _order.
Referenced by copy(), create(), FreeModule::get_induced_order(), res_comp::initialize(), schreyer_compare(), schreyer_down(), schreyer_up(), sub_space(), sub_space(), SchreyerOrder_symm::symm1(), and text_out().