Macaulay2 Engine: SchreyerOrder::schreyer_compare
schreyer_compare()
int SchreyerOrder::schreyer_compare (const_monomial m, int m_comp, const_monomial n, int n_comp) const
Definition at line 324 of file schorder.cpp.
 {
   const_monomial ms = base_monom(m_comp);
   const_monomial ns = base_monom(n_comp);
   for (int i = M->monomial_size(); i > 0; --i)
     {
       int cmp = *ms++ + *m++ - *ns++ - *n++;
       if (cmp < 0) return LT;
       if (cmp > 0) return GT;
     }
   int cmp = compare_num(m_comp) - compare_num(n_comp);
   if (cmp < 0) return LT;
   if (cmp > 0) return GT;
   return EQ;
 }
References base_monom(), compare_num(), EQ, GT, LT, M, and Monoid::monomial_size().
Referenced by GBRing::gbvector_compare(), and PolyRing::vec_locate_lead_term().