Macaulay2 Engine: SchreyerOrder::schreyer_down
schreyer_down()
void SchreyerOrder::schreyer_down (const_monomial m, int comp, monomial result) const inline
Definition at line 58 of file schorder.hpp.
   {
     M->divide(m, base_monom(comp), result);
   }
References base_monom(), Monoid::divide(), and M.
Referenced by GBRing::find_reduction_monomial(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_get_lead_monomial(), GBKernelComputation::geo_reduce(), GBKernelComputation::new_pairs(), GBKernelComputation::reduce(), and GBKernelComputation::s_pair().