Macaulay2 Engine: SchreyerOrder::append
append()
void SchreyerOrder::append (int compare_num, const_monomial base_monom)
Definition at line 19 of file schorder.cpp.
{
  auto end = _order.size();
  _order.resize(end + _nslots);
  int *me = _order.data() + end;
  *me++ = compare_num0;
  for (int i = 1; i < _nslots; i++) *me++ = *baseMonom++;
  _rank++;
}
References _nslots, _order, _rank, and end().
Referenced by append_order(), FreeModule::append_schreyer(), copy(), create(), create(), exterior(), sub_space(), sub_space(), SchreyerOrder_symm::symm1(), and tensor().