Macaulay2 Engine: SchreyerOrder::tensor
tensor()
SchreyerOrder * SchreyerOrder::tensor (const SchreyerOrder * G) const
Definition at line 198 of file schorder.cpp.
 {
   // Since this is called only from FreeModule::tensor,
   // we assume that 'this', 'G' have the same monoid 'M'.
   SchreyerOrder *result = new SchreyerOrder(M);
   monomial base = M->make_one();
   int next = 0;
   for (int i = 0; i < rank(); i++)
     for (int j = 0; j < G->rank(); j++)
       {
         M->mult(base_monom(i), G->base_monom(j), base);
         result->append(next++, base);
       }
   M->remove(base);
   return result;
 }
References append(), base, G, and ffpackInterface::rank().
Referenced by FreeModule::tensor().