Macaulay2 Engine: SchreyerOrder::exterior
exterior()
SchreyerOrder * SchreyerOrder::exterior (int p) const
Definition at line 219 of file schorder.cpp.
 {
   // This routine is only called from FreeModule::exterior.
   // Therefore: p is in the range 0 < p <= rk.
   SchreyerOrder *result = new SchreyerOrder(M);
   int rk = rank();
   assert(pp > 0);
   assert(pp <= rk);
   size_t p = static_cast<size_t>(pp);
   Subset a(p, 0);
   for (size_t i = 0; i < p; i++) a[i] = i;
   monomial base = M->make_one();
   int next = 0;
   do
     {
       M->one(base);
       for (size_t r = 0; r < p; r++)
         M->mult(base, base_monom(static_cast<int>(a[r])), base);
       result->append(next++, base);
     }
   while (Subsets::increment(rk, a));
   M->remove(base);
   return result;
 }
References append(), base, Subsets::increment(), p, and ffpackInterface::rank().
Referenced by FreeModule::exterior().