Macaulay2 Engine: SchreyerOrder::copy
copy()
SchreyerOrder * SchreyerOrder::copy () const
Definition at line 146 of file schorder.cpp.
 {
   SchreyerOrder *result = new SchreyerOrder(M);
   for (int i = 0; i < rank(); i++)
     result->append(compare_num(i), base_monom(i));
   return result;
 }
References append(), base_monom(), compare_num(), M, rank(), and SchreyerOrder().
Referenced by FreeModule::shift().