Macaulay2 Engine: SchreyerOrder::compare_num
compare_num()
int SchreyerOrder::compare_num (int i) const inline
Definition at line 35 of file schorder.hpp.
 { return _order[i * _nslots]; }
References _nslots, and _order.
Referenced by append_order(), copy(), create(), FreeModule::get_induced_order(), schreyer_compare(), schreyer_compare_encoded(), sub_space(), and text_out().