Macaulay2 Engine: PolynomialRing::create_quotient
create_quotient() [2/3]
PolynomialRing * PolynomialRing::create_quotient (const PolynomialRing * R, const PolynomialRing * B) static
Definition at line 156 of file polyring.cpp.
 {
   VECTOR(Nterm *) elems;
   for (int i = 0; i < B->n_quotients(); i++)
     {
       ring_elem f;
       R->promote(B->getNumeratorRing(), B->quotient_element(i), f);
       elems.push_back(f);
     }
   return create_quotient(R, elems);
 }
References create_quotient(), getNumeratorRing(), n_quotients(), Ring::promote(), quotient_element(), and VECTOR().