Macaulay2 Engine: PolynomialRing::coefficient_type
coefficient_type()
CoefficientType PolynomialRing::coefficient_type () const inline virtual
Reimplemented from Ring.
Definition at line 134 of file polyring.hpp.
 { return coeff_type_; }
References coeff_type_.
Referenced by gbA::create(), ReducedGB::create(), create_quotient(), gbA::initialize(), and Matrix::make_monideal().