Macaulay2 Engine: PolynomialRing::clear
clear()
virtual void PolynomialRing::clear () inline virtual
Reimplemented in PolyRing.
Definition at line 111 of file polyring.hpp.
 { qinfo_->destroy(gb_ring_); }
References QRingInfo::destroy(), gb_ring_, and qinfo_.
Referenced by PolyRing::clear(), and remove_polyring().