Macaulay2 Engine: PolynomialRing::get_quotient_monomials
get_quotient_monomials()
const MonomialIdeal * PolynomialRing::get_quotient_monomials () const inline
Definition at line 152 of file polyring.hpp.
  {
    return qinfo_->get_quotient_monomials();
  }
References QRingInfo::get_quotient_monomials(), and qinfo_.
Referenced by GBKernelComputation::find_ring_divisor(), GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), make_basis_MonomialIdeal(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), ReducedGB_Field::ReducedGB_Field(), and res_comp::skeleton_pairs().