Macaulay2 Engine: PolynomialRing::setQuotientInfo
setQuotientInfo()
void PolynomialRing::setQuotientInfo (QRingInfo * qinfo0) protected
Definition at line 12 of file polyring.cpp.
 {
   qinfo_ = qinfo0;
   const PolyRing *numerR = getNumeratorRing();  // might be 'this'
   for (int i = 0; i < n_quotients(); i++)
     {
       if (!numerR->is_homogeneous(quotient_element(i)))
         {
           setIsGraded(false);
           break;
         }
     }
   overZZ_ = (coeff_type_ == Ring::COEFF_ZZ);
 }
References coeff_type_, Ring::COEFF_ZZ, getNumeratorRing(), PolyRing::is_homogeneous(), n_quotients(), overZZ_, qinfo_, quotient_element(), and setIsGraded().
Referenced by create_quotient().