Macaulay2 Engine: PolynomialRing::initialize_PolynomialRing
initialize_PolynomialRing()
void PolynomialRing::initialize_PolynomialRing (const Ring * K, const Monoid * M, const PolyRing * numeratorR, const PolynomialRing * ambientR, const Ring * denomR) protected
Definition at line 29 of file polyring.cpp.
 {
   nvars_ = M->n_vars();
   K_ = K;
   M_ = M;
   numerR_ = numeratorR;
   ambientR_ = ambientR;
   denomR_ = denomR;
   exp_size = EXPONENT_BYTE_SIZE(nvars_);
   if (K->is_QQ() || (K == globalZZ && denomR != nullptr))
     coeff_type_ = Ring::COEFF_QQ;
   else if (K == globalZZ && denomR == nullptr)
     coeff_type_ = Ring::COEFF_ZZ;
   else
     coeff_type_ = Ring::COEFF_BASIC;
   is_weyl_ = false;
   is_solvable_ = false;
   is_skew_ = false;
   overZZ_ = false;
   qinfo_ = new QRingInfo;
   is_ZZ_quotient_ = false;
   ZZ_quotient_value_ = ZERO_RINGELEM;
   if (numeratorR != this)
     {
       // We must set the non-commutative settings ourselves at this time
       if (numeratorR->cast_to_WeylAlgebra() != nullptr)
         is_weyl_ = true;
       else if (numeratorR->cast_to_SolvableAlgebra() != nullptr)
         is_solvable_ = true;
       else if (numeratorR->is_skew_commutative())
         {
           is_skew_ = true;
           skew_ = numeratorR->getSkewInfo();
         }
     }
   poly_size_ = 0;  // The callee needs to set this later
   gb_ring_ = nullptr;    // The callee needs to set this later
   // Also: callee should call setIsGraded, and set oneV, minus_oneV, zeroV
 }
References ambientR_, Ring::cast_to_SolvableAlgebra(), Ring::cast_to_WeylAlgebra(), Ring::COEFF_BASIC, Ring::COEFF_QQ, coeff_type_, Ring::COEFF_ZZ, denomR_, exp_size, EXPONENT_BYTE_SIZE, gb_ring_, getSkewInfo(), globalZZ, Ring::is_QQ(), is_skew_, is_skew_commutative(), is_solvable_, is_weyl_, is_ZZ_quotient_, K_, M_, Monoid::n_vars(), numerR_, nvars_, overZZ_, poly_size_, qinfo_, skew_, ZERO_RINGELEM, and ZZ_quotient_value_.
Referenced by create_quotient(), and PolyRing::initialize_poly_ring().