Macaulay2 Engine: PolynomialRing::create_quotient
create_quotient() [3/3]
PolynomialRing * PolynomialRing::create_quotient (const PolynomialRing * R, gc_vector< Nterm * > & elems) static protected
Definition at line 79 of file polyring.cpp.
 {
   // Here are the cases:
   // (1) R is a polynomial ring over a basic field
   // (2) R is a polynomial ring over ZZ
   // (3) R is a polynomial ring over QQ
   // case (1), (2): PolyRingQuotient
   // case (3): PolyQQ
   PolynomialRing *result = nullptr;
   Ring::CoefficientType coeff_type = R->coefficient_type();
   QRingInfo *qrinfo = nullptr;
   switch (coeff_type)
     {
       case COEFF_BASIC:
         qrinfo = new QRingInfo_field_basic(R->getNumeratorRing(), elems);
         result = new PolyRingQuotient;
         break;
       case COEFF_QQ:
         qrinfo = new QRingInfo_field_QQ(R->getNumeratorRing(), elems);
         result = new PolyRingQuotient;
         break;
       case COEFF_ZZ:
         QRingInfo_ZZ *qrinfoZZ = new QRingInfo_ZZ(R->getNumeratorRing(), elems);
         qrinfo = qrinfoZZ;
         result = new PolyRingQuotient;
         result->is_ZZ_quotient_ = qrinfoZZ->is_ZZ_quotient();
         result->ZZ_quotient_value_ = qrinfoZZ->ZZ_quotient_value();
         break;
     }
   result->initialize_ring(
       R->characteristic(), R->get_degree_ring(), R->get_heft_vector());
   result->initialize_PolynomialRing(R->getCoefficients(),
                                     R->getMonoid(),
                                     R->getNumeratorRing(),
                                     R->getAmbientRing(),
                                     R->getDenominatorRing());
   result->gb_ring_ = R->get_gb_ring();
   result->setQuotientInfo(qrinfo);  // Also sets graded-ness
   result->zeroV = result->from_long(0);
   result->oneV = result->from_long(1);
   result->minus_oneV = result->from_long(-1);
   return result;
 }
References Ring::characteristic(), Ring::COEFF_BASIC, Ring::COEFF_QQ, Ring::COEFF_ZZ, coefficient_type(), Ring::from_long(), gb_ring_, Ring::get_degree_ring(), get_gb_ring(), Ring::get_heft_vector(), getAmbientRing(), getCoefficients(), getDenominatorRing(), getMonoid(), getNumeratorRing(), initialize_PolynomialRing(), Ring::initialize_ring(), QRingInfo_ZZ::is_ZZ_quotient(), is_ZZ_quotient_, Ring::minus_oneV, Ring::oneV, setQuotientInfo(), Ring::zeroV, QRingInfo_ZZ::ZZ_quotient_value(), and ZZ_quotient_value_.
Referenced by create_quotient(), IM2_Ring_quotient(), and IM2_Ring_quotient1().