Macaulay2 Engine: PolynomialRing::n_fraction_vars
n_fraction_vars()
virtual int PolynomialRing::n_fraction_vars () const inline virtual
Definition at line 238 of file polyring.hpp.
   {
     const Ring *D = getDenominatorRing();
     if (D == 0) return 0;
     const PolynomialRing *DR = D->cast_to_PolynomialRing();
     if (DR == 0) return 0;
     return DR->n_vars();
   }
References Ring::cast_to_PolynomialRing(), getDenominatorRing(), and n_vars().
Referenced by gbA::initialize().