Macaulay2 Engine: PolynomialRing::cast_to_PolynomialRing
cast_to_PolynomialRing() [2/2]
virtual const PolynomialRing* PolynomialRing::cast_to_PolynomialRing () const inline virtual
Reimplemented from Ring.
Definition at line 247 of file polyring.hpp.
 { return this; }
Referenced by FractionField::coefficient_type(), LocalRing::coefficient_type(), PolyRing::get_logical_coeff(), PolyRingQuotient::lift(), Matrix::make(), Matrix::monomials(), PolyRingQuotient::promote(), rawRingM2FreeAlgebra(), and MonomialIdeal::text_out().