Macaulay2 Engine: PolynomialRing::create_quotient
create_quotient() [1/3]
PolynomialRing * PolynomialRing::create_quotient (const PolynomialRing * R, const Matrix * M) static
Definition at line 134 of file polyring.cpp.
 {
   if (M->get_ring() != R)
     {
       ERROR("quotient elements not in the expected polynomial ring");
       return nullptr;
     }
   VECTOR(Nterm *) elems;
   for (int i = 0; i < M->n_cols(); i++)
     {
       Nterm *f = R->numerator(M->elem(0, i));
       elems.push_back(f);
     }
   for (int i = 0; i < R->n_quotients(); i++)
     elems.push_back(R->quotient_element(i));
   return create_quotient(R->getAmbientRing(), elems);
 }
References create_quotient(), Matrix::elem(), ERROR(), Matrix::get_ring(), getAmbientRing(), Matrix::n_cols(), n_quotients(), numerator(), quotient_element(), and VECTOR().