Macaulay2 Engine: PolynomialRing::skew_variable
skew_variable()
int PolynomialRing::skew_variable (int i) const inline
Definition at line 182 of file polyring.hpp.
 { return skew_.skew_variable(i); }
References skew_, and SkewMultiplication::skew_variable().
Referenced by GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), and res_comp::skeleton_pairs().