Macaulay2 Engine: PolynomialRing::make_flat_term
make_flat_term()
virtual ring_elem PolynomialRing::make_flat_term (const ring_elem a, const_monomial m) const pure virtual
Implemented in PolyRingQuotient, and PolyRing.
Referenced by HilbertController::addMonomial(), BRPStoMatrix(), coeffs_of_vec(), hilb_comp::do_ideal(), RingMap::eval_term(), FreeModule::get_induced_order(), KBasis::insert(), Matrix::koszul(), Matrix::koszul_monomials(), Matrix::make(), Matrix::monomials(), hilb_comp::recurse(), hilb_comp::step(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), res2_poly::to_vector(), and res_poly::to_vector().