Macaulay2 Engine: PolynomialRing::n_vars
n_vars()
int PolynomialRing::n_vars () const inline
Definition at line 139 of file polyring.hpp.
 { return nvars_; }
References nvars_.
Referenced by MatrixStream::appendTermDone(), BRPSfromMatrix(), BRPStoMatrix(), check_coeff_ring(), checkGaloisFieldInput(), BIBasis::Launcher::CheckMatrix(), hilb_comp::coeff_of(), Matrix::coeffs(), convertToFactory(), convertToM2(), Monoid::create(), PolyRing::degree_of_var(), PolyRing::diff_term(), Matrix::dimension1(), PolyRing::divide_by_expvector(), PolyRing::division_algorithm_with_laurent_variables(), PolyRing::eval(), F4Computation::F4Computation(), PolyRing::fromSmallIntegerCoefficients(), PolyRing::get_coeff(), PolyRing::get_logical_coeff(), PolyRing::get_terms(), PolyRing::homogenize(), RingElement::homogenize(), IM2_RingElement_term(), PolyRing::index_of_var(), res2_comp::initialize(), res_comp::initialize(), SchurRing::initialize_schur(), isUnivariateOverPrimeField(), KBasis::KBasis(), PolyRing::lead_logical_exponents(), PolyRing::lift(), PolyRing::list_form(), PolyRing::make_logical_term(), MatrixStream::MatrixStream(), matrixToStream(), FractionField::n_fraction_vars(), LocalRing::n_fraction_vars(), n_fraction_vars(), PolyRing::n_logical_terms(), PolyRing::promote(), QRingInfo::QRingInfo(), QRingInfo_field::QRingInfo_field(), QRingInfo_ZZ::QRingInfo_ZZ(), rawDisplayMatrixStream(), rawFactorBase(), rawGbBoolean(), rawIdealReorder(), rawMGB(), rawRoots(), rawTowerTranslatePoly(), PolyRing::setNegativeExponentMonomial(), res2_comp::sort_value(), res_comp::sort_value(), Matrix::support(), PolyRing::support(), PolyRingQuotient::syzygy(), Tower::translate(), MatrixStream::varCount(), and Ring::vec_remove_monomial_factors().