Macaulay2 Engine: PolynomialRing::is_quotient_ring
is_quotient_ring()
bool PolynomialRing::is_quotient_ring () const inline virtual
Reimplemented from Ring.
Definition at line 178 of file polyring.hpp.
 { return n_quotients() > 0; }
References n_quotients().
Referenced by GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), GBKernelComputation::find_ring_divisor(), GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), gbA::initialize(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), ReducedGB_Field::ReducedGB_Field(), ReducedGB_ZZ::ReducedGB_ZZ(), and res_comp::skeleton_pairs().