Macaulay2 Engine: PolynomialRing::getMonoid
getMonoid()
virtual const Monoid* PolynomialRing::getMonoid () const inline virtual
Definition at line 225 of file polyring.hpp.
 { return M_; }
References M_.
Referenced by MarkedGB::add_marked_elems(), HilbertController::addMonomial(), MatrixStream::appendTermDone(), binomial_ring::binomial_ring(), BRPSfromMatrix(), BRPStoMatrix(), check_nterm_multiples(), BIBasis::Launcher::CheckMatrix(), ResolutionComputation::choose_res(), hilb_comp::coeff_of(), Matrix::coeffs(), coeffs_of_vec(), computeHashValue(), convertToFactory(), ChineseRemainder::CRA(), SchreyerOrder::create(), gbA::create(), ReducedGB::create(), SchurRing::create(), SolvableAlgebra::create(), create_quotient(), Ring::degree_monoid(), FreeMonoid::degreeMonoid(), PolyRing::division_algorithm_with_laurent_variables(), Matrix::elim_keep(), Matrix::elim_vars(), F4Computation::F4Computation(), FreeModule::FreeModule(), ResF4toM2Interface::from_M2_vec(), F4toM2Interface::from_M2_vec(), M2::GaloisFieldTable::GaloisFieldTable(), GBKernelComputation::GBKernelComputation(), PolyRing::get_logical_coeff(), hilb_comp::hilb_comp(), IM2_Ring_frac(), IM2_Ring_skew_polyring(), IM2_Ring_weyl_algebra(), gbA::initialize(), res2_comp::initialize(), res_comp::initialize(), FractionField::initialize_frac(), GF::initialize_GF(), KBasis::KBasis(), Matrix::koszul(), Matrix::koszul_monomials(), PolyRing::list_form(), Matrix::make(), PolyRing::make_logical_term(), Matrix::make_monideal(), PolyRing::make_trivial_ZZ_poly_ring(), makemonideal(), matrixToStream(), binomial_ring::monomial_out(), Matrix::monomials(), GF::promote(), M2::ARingGFGivaro::promote(), QRingInfo::QRingInfo(), QRingInfo_field::QRingInfo_field(), QRingInfo_ZZ::QRingInfo_ZZ(), ChineseRemainder::ratConversion(), rawMGB(), rawRoots(), QRingInfo_field_basic::reduce_lead_term_basic_field(), QRingInfo_field_QQ::reduce_lead_term_QQ(), PolyRing::remainderAndQuotient(), RingMap::RingMap(), PolyRing::setNegativeExponentMonomial(), gbres_comp::setup(), sagbi::subduct(), Matrix::support(), MonomialIdeal::text_out(), ResF4toM2Interface::to_M2_freemodule(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), Tower::translate(), Ring::vec_in_subring(), and Ring::vec_remove_monomial_factors().