Macaulay2 Engine: PolynomialRing::getCoefficientRing
getCoefficientRing()
const Ring* PolynomialRing::getCoefficientRing () const inline
Definition at line 143 of file polyring.hpp.
 { return getCoefficients(); }
References getCoefficients().
Referenced by HilbertController::addMonomial(), BIBasis::Launcher::CheckMatrix(), ResolutionComputation::choose_res(), hilb_comp::coeff_of(), FractionField::coefficient_type(), LocalRing::coefficient_type(), computeHashValue(), convertGFToFactory(), convolve(), ChineseRemainder::CRA(), Matrix::dimension1(), PolyRing::division_algorithm_with_laurent_variables(), F4ResComputation::get_matrix(), hilb_comp::hilb_comp(), res2_comp::initialize(), res_comp::initialize(), Matrix::make(), PolyRing::make_trivial_ZZ_poly_ring(), matrixToStream(), M2::ARingGFGivaro::promote(), ChineseRemainder::ratConversion(), rawGbBoolean(), rawMGB(), rawRingElementCRA(), rawRingElementRatConversion(), RingMap::RingMap(), set_GF_minimal_poly(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), and hilb_comp::~hilb_comp().