Macaulay2 Engine: PolynomialRing::n_quotients
n_quotients()
int PolynomialRing::n_quotients () const inline
Definition at line 162 of file polyring.hpp.
 { return qinfo_->n_quotients(); }
References QRingInfo::n_quotients(), and qinfo_.
Referenced by checkGaloisFieldInput(), create_quotient(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), M2::GaloisFieldTable::GaloisFieldTable(), getPresentation(), IM2_Ring_quotient1(), gbA::initialize(), FractionField::initialize_frac(), GF::initialize_GF(), PolyRingQuotient::invert(), is_quotient_ring(), Matrix::make_monideal(), ReducedGB_Field_Local::ReducedGB_Field_Local(), setQuotientInfo(), and PolyRingQuotient::text_out().