Macaulay2 Engine: PolynomialRing::translate_gbvector_from_vec
translate_gbvector_from_vec()
virtual gbvector* PolynomialRing::translate_gbvector_from_vec (const FreeModule * F, const vec v, ring_elem & result_denominator) const pure virtual
Implemented in PolyRingQuotient, and PolyRing.
Referenced by GBinhom_comp::add_gens(), GB_comp::contains(), ReducedGB::contains(), ResF4toM2Interface::from_M2_vec(), F4toM2Interface::from_M2_vec(), GBDeclared::GBDeclared(), GBMatrix::GBMatrix(), gbA::initialize(), GB_comp::initialize(), GB_comp::matrix_lift(), ReducedGB::matrix_lift(), GB_comp::matrix_remainder(), ReducedGB::matrix_remainder(), and gbres_comp::reduce().