Macaulay2 Engine: PolynomialRing::translate_gbvector_to_vec
translate_gbvector_to_vec()
virtual vec PolynomialRing::translate_gbvector_to_vec (const FreeModule * F, const gbvector * v) const pure virtual
Implemented in PolyRingQuotient, and PolyRing.
Referenced by gb2_comp::change_matrix(), gb2_comp::gb_matrix(), GB_comp::get_change(), ReducedGB::get_change(), GB_comp::get_gb(), ReducedGB::get_gb(), GB_comp::get_initial(), MarkedGB::get_initial(), ReducedGB::get_initial(), gbA::get_mingens(), GB_comp::get_mingens(), GBinhom_comp::get_mingens(), GB_comp::get_parallel_lead_terms(), MarkedGB::get_parallel_lead_terms(), ReducedGB::get_parallel_lead_terms(), gbA::get_syzygies(), GB_comp::get_syzygies(), gb2_comp::initial_matrix(), gbA::make_lead_term_matrix(), gb2_comp::make_lead_term_matrix(), gb2_comp::min_gens_matrix(), GBinhom_comp::new_gen(), GBinhom_comp::s_pair_step(), and GBMatrix::to_matrix().