Macaulay2 Engine: PolynomialRing::get_quotient_MonomialTable
get_quotient_MonomialTable()
MonomialTable* PolynomialRing::get_quotient_MonomialTable () const inline
Definition at line 147 of file polyring.hpp.
   {
     return qinfo_->get_quotient_MonomialTable();
   }
References QRingInfo::get_quotient_MonomialTable(), and qinfo_.
Referenced by ReducedGB_Field_Local::find_good_divisor(), and gbA::initialize().