Macaulay2 Engine: PolynomialRing::var
var()
virtual ring_elem PolynomialRing::var (int v) const pure virtual
Reimplemented from Ring.
Implemented in PolyRingQuotient, and PolyRing.
Referenced by convertToM2(), M2::GaloisFieldTable::GaloisFieldTable(), GF::initialize_GF(), rawFactorBase(), Matrix::top_coefficients(), and FractionField::var().