Macaulay2 Engine: PolynomialRing::get_gb_ring
get_gb_ring()
virtual GBRing* PolynomialRing::get_gb_ring () const inline virtual
Definition at line 219 of file polyring.hpp.
 { return gb_ring_; }
References gb_ring_.
Referenced by ReducedGB::create(), create_quotient(), ResF4toM2Interface::from_M2_vec(), F4toM2Interface::from_M2_vec(), gb_emitter::gb_emitter(), GBDeclared::GBDeclared(), GBKernelComputation::GBKernelComputation(), QRingInfo_field_basic::gbvector_normal_form(), QRingInfo_field_QQ::gbvector_normal_form(), GBWeight::GBWeight(), gbA::initialize(), GB_comp::initialize0(), GBinhom_comp::set_up0(), gbres_comp::setup(), gb2_comp::setup(), PolyRing::translate_gbvector_from_ringelem(), PolyRing::translate_gbvector_from_ringelem_QQ(), PolyRing::translate_gbvector_from_vec(), PolyRing::translate_gbvector_from_vec_QQ(), PolyRing::translate_gbvector_to_vec(), PolyRing::translate_gbvector_to_vec_denom(), and PolyRing::translate_gbvector_to_vec_QQ().