Macaulay2 Engine: PolynomialRing::getPresentation
getPresentation()
Matrix * PolynomialRing::getPresentation () const
Definition at line 174 of file polyring.cpp.
 {
   const PolynomialRing *R = getAmbientRing();
   MatrixConstructor mat(R->make_FreeModule(1), 0);
   for (int i = 0; i < n_quotients(); i++)
     // NEED: to make this into a fraction, if R has fractions.
     mat.append(R->make_vec(0, quotient_element(i)));
   return mat.to_matrix();
 }
References MatrixConstructor::append(), getAmbientRing(), Ring::make_FreeModule(), Ring::make_vec(), n_quotients(), quotient_element(), and MatrixConstructor::to_matrix().