Macaulay2 Engine: PolynomialRing::getCoefficients
getCoefficients()
virtual const Ring* PolynomialRing::getCoefficients () const inline virtual
Definition at line 220 of file polyring.hpp.
 { return K_; }
References K_.
Referenced by MatrixStream::appendTermDone(), BRPStoMatrix(), check_coeff_ring(), check_nterm_multiples(), Matrix::content(), RingElement::content(), GBinhom_comp::create(), SchurRing::create(), SolvableAlgebra::create(), create_quotient(), PolyRing::determine_common_denominator_QQ(), GF::from_rational(), GBKernelComputation::GBKernelComputation(), FreeModule::get_induced_order(), getCoefficientRing(), IM2_Ring_frac(), IM2_Ring_skew_polyring(), IM2_Ring_weyl_algebra(), IM2_RingElement_term(), FractionField::initialize_frac(), KBasis::insert(), Matrix::koszul(), Matrix::koszul_monomials(), binomial_ring::monomial_to_vector(), Matrix::monomials(), GF::promote(), rawAssociateDivisor(), rawGCDRingElement(), rawIdealOfPoints(), rawRoots(), QRingInfo_field_basic::reduce_lead_term_basic_field(), FractionField::simplify(), LocalRing::simplify(), Matrix::split_off_content(), TEST(), TowerEvaluator::TowerEvaluator(), Tower::translate(), PolyRing::translate_gbvector_from_ringelem(), PolyRing::translate_gbvector_from_vec(), PolyRing::translate_gbvector_to_vec(), and PolyRing::translate_gbvector_to_vec_denom().