Macaulay2 Engine: PolynomialRing::getSkewInfo
getSkewInfo()
const SkewMultiplication& PolynomialRing::getSkewInfo () const inline
Definition at line 184 of file polyring.hpp.
 { return skew_; }
References skew_.
Referenced by initialize_PolynomialRing(), QRingInfo_field_basic::reduce_lead_term_basic_field(), and QRingInfo_field_QQ::reduce_lead_term_QQ().