Macaulay2 Engine: PolynomialRing::getAmbientRing
getAmbientRing()
virtual const PolynomialRing * PolynomialRing::getAmbientRing () const inline virtual
Definition at line 203 of file polyring.hpp.
{ return ambientR_; }
References ambientR_.
Referenced by create_quotient(), create_quotient(), M2::findMinimalPolynomial(), GF::getMinimalPolynomial(), getPresentation(), PolyRingQuotient::invert(), PolyRingQuotient::lift(), PolyRingQuotient::promote(), and rawAmbientRing().