Macaulay2 Engine: PolynomialRing::quotient_element
quotient_element()
Nterm* PolynomialRing::quotient_element (int i) const inline
Definition at line 163 of file polyring.hpp.
 { return qinfo_->quotient_element(i); }
References qinfo_, and QRingInfo::quotient_element().
Referenced by M2::ARingGFFlint::ARingGFFlint(), M2::ARingGFFlintBig::ARingGFFlintBig(), create_quotient(), gb2_comp::find_pairs(), M2::findMinimalPolynomial(), M2::GaloisFieldTable::GaloisFieldTable(), GF::getMinimalPolynomial(), getPresentation(), GF::initialize_GF(), PolyRingQuotient::invert(), Matrix::make_monideal(), setQuotientInfo(), and PolyRingQuotient::text_out().