Macaulay2 Engine: PolynomialRing::is_skew_commutative
is_skew_commutative()
bool PolynomialRing::is_skew_commutative () const inline
Definition at line 180 of file polyring.hpp.
 { return is_skew_; }
References is_skew_.
Referenced by ResolutionComputation::choose_res(), initialize_PolynomialRing(), Matrix::make_monideal(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), QRingInfo_field_basic::reduce_lead_term_basic_field(), QRingInfo_field_QQ::reduce_lead_term_QQ(), and res_comp::skeleton_pairs().