Macaulay2 Engine: PolynomialRing::setIsGraded
setIsGraded()
void PolynomialRing::setIsGraded (bool new_val) inline protected
Definition at line 85 of file polyring.hpp.
 { is_graded_ = new_val; }
References is_graded_.
Referenced by PolyRing::initialize_poly_ring(), WeylAlgebra::initialize_weyl(), and setQuotientInfo().