Macaulay2 Engine: PolynomialRing::computeHashValue
computeHashValue()
unsigned int PolynomialRing::computeHashValue (const ring_elem a) const virtual
Implements Ring.
Definition at line 201 of file polyring.cpp.
 {
   unsigned int hash = 0;
   unsigned int seed1 = 103;
   unsigned int seed2 = 347654;
   for (Nterm& t : a.poly_val)
     {
       unsigned int hash1 = getCoefficientRing()->computeHashValue(t.coeff);
       unsigned int hash2 = getMonoid()->computeHashValue(t.monom);
       hash += seed1 * hash1 + seed2 * hash2;
       seed1 += 463633;
       seed2 += 7858565;
     }
   return hash;
 }
References Nterm::coeff, Ring::computeHashValue(), Monoid::computeHashValue(), getCoefficientRing(), getMonoid(), MutableEngineObject::hash(), Nterm::monom, and ring_elem::poly_val.
Referenced by FractionField::computeHashValue(), and LocalRing::computeHashValue().