Macaulay2 Engine: rawIsLocalUnit
rawIsLocalUnit()
M2_bool rawIsLocalUnit (const RingElement * f)
Definition at line 750 of file localring.cpp.
 {
   const LocalRing *L = f->get_ring()->cast_to_LocalRing();
   if (L == nullptr)
     {
       ERROR("expected an object over a local ring");
       return false;
     }
   return L->is_unit(f->get_value());
 }
References Ring::cast_to_LocalRing(), ERROR(), RingElement::get_ring(), RingElement::get_value(), and LocalRing::is_unit().