Macaulay2 Engine: rawLiftLocalMatrix
rawLiftLocalMatrix()
Matrix* rawLiftLocalMatrix (const Ring * R, const Matrix * f)
Definition at line 731 of file localring.cpp.
 {
   const LocalRing *L = f->get_ring()->cast_to_LocalRing();
   if (L == nullptr)
     {
       ERROR("expected an object over a local ring");
       return nullptr;
     }
   // TODO: Check that f is over a localization of R
   if (R != L->get_ring())
     {
       ERROR("expected an object over a localization of the first argument");
       return nullptr;
     }
   Matrix *result;
   L->lift_up(R, f, result);
   return result;
 }
References Ring::cast_to_LocalRing(), ERROR(), LocalRing::get_ring(), Matrix::get_ring(), and LocalRing::lift_up().