Macaulay2 Engine: Gausser::dense_row_to_sparse_row
dense_row_to_sparse_row()
void Gausser::dense_row_to_sparse_row (dense_row & r, int & result_len, F4CoefficientArray & result_sparse, int *& result_comps, int first, int last) const
Definition at line 141 of file gausser.cpp.
 {
   int *elems = static_cast<int *>(r.coeffs);
   int len = 0;
   for (int i = first; i <= last; i++)
     if (!Kp->is_zero(elems[i])) len++;
   int *in_sparse = Mem->coefficients.allocate(len);
   int *in_comps = Mem->components.allocate(len);
   result_len = len;
   result_sparse = in_sparse;
   result_comps = in_comps;
   for (int i = first; i <= last; i++)
     if (!Kp->is_zero(elems[i]))
       {
         *in_sparse++ = elems[i];
         *in_comps++ = i;
         Kp->set_zero(elems[i]);
       }
 }
References F4Vec::allocate(), F4Mem::coefficients, dense_row::coeffs, F4Mem::components, CoefficientRingZZp::is_zero(), Kp, Mem, and CoefficientRingZZp::set_zero().