Macaulay2 Engine: M2::ARingZZp::eval
eval()
void M2::ARingZZp::eval (const RingMap * map, const elem f, int first_var, ring_elem & result) const
Definition at line 91 of file aring-zzp.cpp.
 {
   long a = coerceToLongInteger(f);
   result = map->get_ring()->from_long(a);
 }
References coerceToLongInteger(), Ring::from_long(), and RingMap::get_ring().