Macaulay2 Engine: M2::ARingZZp::set_from_long
set_from_long()
void M2::ARingZZp::set_from_long (elem & result, long a) const inline
Definition at line 115 of file aring-zzp.hpp.
   {
     a = a % p;
     if (a < 0) a += p;
     result = log_table[a];
   }
References log_table, and p.
Referenced by fromStream< M2::ARingZZp >(), getElement< M2::ARingZZp >(), and TEST().