Macaulay2 Engine: SLEvaluatorConcrete::evaluate
evaluate() [2/2]
template<typename RT > bool SLEvaluatorConcrete< RT >::evaluate (const MutableMatrix * inputs, MutableMatrix * outputs) virtual
Implements SLEvaluator.
Definition at line 188 of file SLP-imp.hpp.
 {
   auto inp = dynamic_cast<const MutableMat<DMat<RT> >*>(inputs);
   auto out = dynamic_cast<MutableMat<DMat<RT> >*>(outputs);
   if (inp == nullptr)
     {
       ERROR("inputs: expected a dense mutable matrix");
       return false;
     }
   if (out == nullptr)
     {
       ERROR("outputs: expected a dense mutable matrix");
       return false;
     }
   if (&ring() != &inp->getMat().ring())
     {
       ERROR("inputs are in a different ring");
       return false;
     }
   if (&ring() != &out->getMat().ring())
     {
       ERROR("outputs are in a different ring");
       return false;
     }
   return evaluate(inp->getMat(), out->getMat());
 }
References ERROR(), and MutableMat< Mat >::getMat().
Referenced by HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track().