Macaulay2 Engine: SLEvaluatorConcrete::evaluate
evaluate() [1/2]
template<typename RT > bool SLEvaluatorConcrete< RT >::evaluate (const DMat< RT > & inputs, DMat< RT > & outputs)
Definition at line 217 of file SLP-imp.hpp.
 {
   if (nInputs != inputs.numRows() * inputs.numColumns()) {
     ERROR(
           "inputs: the number of inputs does not match the number of entries "
           "in the inputs matrix");
     std::cout << nInputs
               << " != " << inputs.numRows() * inputs.numColumns()
               << std::endl;
     return false;
   }
   if (nOutputs != outputs.numRows() * outputs.numColumns()) {
     ERROR(
           "outputs: the number of outputs does not match the number of entries "
           "in the outputs matrix");
     std::cout << nOutputs << " != " << outputs.numRows()
               << " * " << outputs.numColumns() << std::endl;
     return false;
   }
   if (isCompiled) {
     if(parametersAndInputs==nullptr) {
       (*compiled_fn)(inputs.array(), outputs.array());
     } else {
       std::copy(inputs.array(),inputs.array()+nInputs,parametersAndInputs+nParams);
       (*compiled_fn)(parametersAndInputs, outputs.array());
     }
     return true;
   } else {
     size_t i = 0;
     for (size_t r = 0; r < inputs.numRows(); r++)
       for (size_t c = 0; c < inputs.numColumns(); c++)
         ring().set(values[varsPos[i++]], inputs.entry(r, c));
     nIt = slp->mNodes.begin();
     numInputsIt = slp->mNumInputs.begin();
     inputPositionsIt = slp->mInputPositions.begin();
     for (vIt = values.begin() + slp->inputCounter; vIt != values.end(); ++vIt)
       computeNextNode();
     i = 0;
     for (size_t r = 0; r < outputs.numRows(); r++)
       for (size_t c = 0; c < outputs.numColumns(); c++)
         ring().set(outputs.entry(r, c), values[ap(slp->mOutputPositions[i++])]);
     return true;
   }
 }
References DMat< ACoeffRing >::array(), DMat< ACoeffRing >::entry(), ERROR(), DMat< ACoeffRing >::numColumns(), and DMat< ACoeffRing >::numRows().