Macaulay2 Engine: SLEvaluatorConcrete::computeNextNode
computeNextNode()
template<typename RT > void SLEvaluatorConcrete< RT >::computeNextNode private
Definition at line 150 of file SLP-imp.hpp.
 {
   ElementType& v = *vIt;
   switch (*nIt++)
     {
       case SLProgram::MProduct:
         ring().set_from_long(v, 1);
         for (int i = 0; i < *numInputsIt; i++)
           ring().mult(v, v, *(vIt + (*inputPositionsIt++)));
         numInputsIt++;
         break;
       case SLProgram::MSum:
         ring().set_zero(v);
         for (int i = 0; i < *numInputsIt; i++)
           ring().add(v, v, *(vIt + (*inputPositionsIt++)));
         numInputsIt++;
         break;
       case SLProgram::Det:
         {
           int n = static_cast<int>(sqrt(*numInputsIt++));
           DMat<RT> mat(ring(), n, n);
           for (int i = 0; i < n; i++)
             for (int j = 0; j < n; j++)
               ring().set(mat.entry(i, j), *(vIt + (*inputPositionsIt++)));
           DMatLinAlg<RT>(mat).determinant(v);
         }
         break;
       case SLProgram::Divide:
         ring().set(v, *(vIt + (*inputPositionsIt++)));
         ring().divide(v, v, *(vIt + (*inputPositionsIt++)));
         break;
       default:
         std::cerr << "unknown node type\n";
         abort();
     }
 }
References SLProgram::Det, DMatLinAlg< RingType >::determinant(), SLProgram::Divide, DMat< ACoeffRing >::entry(), SLProgram::MProduct, SLProgram::MSum, and mpfr::sqrt().