Macaulay2 Engine: binomialGB_comp::process_pair
process_pair()
void binomialGB_comp::process_pair (binomial_s_pair p) private
Definition at line 1092 of file gb-toric.cpp.
 {
   bool ismin, subringmin;
   binomial f;
   if (s.f2 == nullptr)
     {
       // A generator
       ismin = true;
       subringmin = true;
       f = R->copy_binomial(
           s.f1->f);  // This is probably being left for garbage...
     }
   else
     {
       if (s.f1->smaller != nullptr || s.f2->smaller != nullptr)
         {
           if (s.f1->smaller != s.f2 && s.f2->smaller != s.f1)
             {
               return;
             }
         }
       if (M2_gbTrace >= 5)
         {
           buffer o;
           o << "pair [";
           R->elem_text_out(o, s.f1->f);
           o << " ";
           R->elem_text_out(o, s.f2->f);
           o << "]" << newline;
           emit(o.str());
         }
       if (!R->calc_s_pair(s, f))
         {
           // The pair already reduces to zero.
           return;
         }
       ismin = false;
       subringmin = (R->weight(s.lcm) > 0);
     }
   if (Gmin->reduce(f))
     {
       if (M2_gbTrace >= 5)
         {
           buffer o;
           o << "  reduced to ";
           R->elem_text_out(o, f);
           emit_line(o.str());
         }
       subringmin = (subringmin && R->weight(f.lead) == 0);
       binomial_gb_elem *p = new binomial_gb_elem(f);
       Gmin->make_new_pairs(Pairs, p);
       Gmin->minimalize_and_insert(p);
       if (ismin) mingens.push_back(p);
       if (subringmin) mingens_subring.push_back(p);
       G.push_back(p);
     }
   else
     R->remove_binomial(f);
 }
References binomial_ring::calc_s_pair(), binomial_ring::copy_binomial(), binomial_ring::elem_text_out(), emit(), emit_line(), binomial_gb_elem::f, binomial_s_pair::f1, binomial_s_pair::f2, G, Gmin, binomial_s_pair::lcm, binomial::lead, M2_gbTrace, binomialGB::make_new_pairs(), mingens, mingens_subring, binomialGB::minimalize_and_insert(), newline, p, R, binomialGB::reduce(), binomial_ring::remove_binomial(), binomial_gb_elem::smaller, buffer::str(), and binomial_ring::weight().
Referenced by start_computation().