Macaulay2 Engine: binomialGB_comp::get_initial
get_initial()
const Matrix * binomialGB_comp::get_initial (int nparts) virtual
Implements GBComputation.
Definition at line 1231 of file gb-toric.cpp.
 {
   MatrixConstructor result(R->F, 0);
   for (binomialGB::iterator p = Gmin->begin(); p != Gmin->end(); p++)
     result.append(R->binomial_to_vector((*p)->f, n));
   return result.to_matrix();
 }
References MatrixConstructor::append(), binomialGB::begin(), binomial_ring::binomial_to_vector(), binomialGB::end(), binomial_ring::F, Gmin, p, R, and MatrixConstructor::to_matrix().