Macaulay2 Engine: binomialGB_comp::create
create()
binomialGB_comp * binomialGB_comp::create (const Matrix * m, M2_bool collect_syz, int n_rows_to_keep, M2_arrayint gb_weights, int strategy, M2_bool use_max_degree, int max_degree) static
Definition at line 992 of file gb-toric.cpp.
 {
   if (collect_syz || n_rows_to_keep > 0)
     {
       ERROR("Groebner basis Algorithm=>Toric cannot keep syzygies");
       return nullptr;
     }
   const PolynomialRing *R = m->get_ring()->cast_to_PolynomialRing();
   if (R == nullptr)
     {
       ERROR("expected polynomial ring");
       return nullptr;
     }
   binomialGB_comp *result = new binomialGB_comp(R, nullptr, true, strategy);
   result->add_generators(m);
   return result;
 }
References add_generators(), binomialGB_comp(), Ring::cast_to_PolynomialRing(), ERROR(), Matrix::get_ring(), and R.
Referenced by GBComputation::choose_gb().