Macaulay2 Engine: binomialGB_comp::get_mingens
get_mingens()
const Matrix * binomialGB_comp::get_mingens () virtual
Implements GBComputation.
Definition at line 1223 of file gb-toric.cpp.
 {
   MatrixConstructor result(R->F, 0);
   for (int i = 0; i < mingens.size(); i++)
     result.append(R->binomial_to_vector(mingens[i]->f));
   return result.to_matrix();
 }
References MatrixConstructor::append(), binomial_ring::binomial_to_vector(), binomial_ring::F, mingens, R, and MatrixConstructor::to_matrix().