Macaulay2 Engine: binomialGB_comp::start_computation
start_computation()
void binomialGB_comp::start_computation () virtual
Implements GBComputation.
Definition at line 1161 of file gb-toric.cpp.
 {
   binomial_s_pair s;
   int *deg = nullptr;
   if (stop_.always_stop) return;  // don't change status
   if (stop_.stop_after_degree) deg = &stop_.degree_limit->array[0];
   while (Pairs->next(deg, s, top_degree))
     {
       ComputationStatusCode ret = gb_done();
       if (ret != COMP_COMPUTING) return;
       process_pair(s);  // consumes 's'.
       if (system_interrupted())
         {
           set_status(COMP_INTERRUPTED);
           return;
         }
     }
   if (Pairs->n_elems() == 0)
     set_status(COMP_DONE);
   else
     set_status(COMP_DONE_DEGREE_LIMIT);
 }
References StopConditions::always_stop, COMP_COMPUTING, COMP_DONE, COMP_DONE_DEGREE_LIMIT, COMP_INTERRUPTED, StopConditions::degree_limit, gb_done(), process_pair(), Computation::set_status(), Computation::stop_, StopConditions::stop_after_degree, system_interrupted(), and top_degree.