Macaulay2 Engine: MatrixSorter::MatrixSorter
MatrixSorter()
MatrixSorter::MatrixSorter (const Matrix * m, int degorder, int ringorder)
Definition at line 78 of file matrix-sort.cpp.
     : deg_ascending(degorder), ringorder_ascending(ringorder)
 {
   R = m->get_ring();
   int nelems = m->n_cols();
   if (degorder != 0)
     {
       sort_degs = newarray_atomic(int, nelems);
       for (int i = 0; i < nelems; i++)
         sort_degs[i] = m->cols()->primary_degree(i);
     }
   result = M2_makearrayint(nelems);
   sort_vals = result->array;
   for (int i = 0; i < nelems; i++) sort_vals[i] = i;
   sort_vecs = newarray(vec, nelems);
   for (int i = 0; i < nelems; i++) sort_vecs[i] = m->elem(i);
 }
References Matrix::cols(), Matrix::elem(), Matrix::get_ring(), M2_makearrayint(), Matrix::n_cols(), newarray, newarray_atomic, FreeModule::primary_degree(), R, result, sort_degs, sort_vals, and sort_vecs.