Macaulay2 Engine: binomialGB_comp::subring
subring()
Matrix * binomialGB_comp::subring ()
Definition at line 1188 of file gb-toric.cpp.
 {
   // Subsequent calls will not receive duplicate elements
   MatrixConstructor result(R->F, 0);
   for (int i = 0; i < mingens_subring.size(); i++)
     {
       result.append(R->binomial_to_vector(mingens_subring[i]->f));
       mingens_subring[i] = NULL;
     }
   mingens_subring.clear();
   return result.to_matrix();
 }
References MatrixConstructor::append(), binomial_ring::binomial_to_vector(), binomial_ring::F, mingens_subring, R, and MatrixConstructor::to_matrix().