Macaulay2 Engine: binomialGB_comp::stats
stats()
void binomialGB_comp::stats () const
Definition at line 1265 of file gb-toric.cpp.
 {
   buffer o;
   o << "binomial GB ";
   if (is_homogeneous)
     o << "homogeneous ";
   else
     o << "inhomogeneous ";
   if (is_nondegenerate) o << "nondegenerate ";
   if (use_bigcell) o << "bigcell ";
   o << newline;
   o << "--- pairs ----" << newline;
   emit(o.str());
   Pairs->stats();
   o.reset();
   o << Gmin->n_masks() << newline;
   emit(o.str());
   if (M2_gbTrace >= 3) Gmin->debug_display();
 }
References binomialGB::debug_display(), emit(), Gmin, is_homogeneous, is_nondegenerate, M2_gbTrace, binomialGB::n_masks(), newline, buffer::reset(), buffer::str(), and use_bigcell.