Macaulay2 Engine: binomialGB_comp::enlarge
enlarge()
void binomialGB_comp::enlarge (const PolynomialRing * R, int * wts)
Definition at line 1036 of file gb-toric.cpp.
 {
   binomial_ring *old_ring = R;
   R = new binomial_ring(newR, wts, old_ring->revlex);
   // We need to change all of the monomials in sight.
   Gmin->enlarge(R);
   Pairs->enlarge(R);
   int i;
   for (i = 0; i < Gens.size(); i++)
     R->translate_binomial(old_ring, Gens[i]->f);
   for (i = 0; i < G.size(); i++) R->translate_binomial(old_ring, G[i]->f);
   freemem(old_ring);
 }
References binomialGB::enlarge(), freemem(), G, Gens, Gmin, R, binomial_ring::revlex, and binomial_ring::translate_binomial().