Macaulay2 Engine: MemoryBlock::deallocateAll
deallocateAll()
template<typename T , long int NSLAB = 4092> void MemoryBlock< T, NSLAB >::deallocateAll () inline
Definition at line 48 of file MemoryBlock.hpp.
   {
     mArena->freeAllAllocs();
   }
References MemoryBlock< T, NSLAB >::mArena.
Referenced by NaivePolynomialHeap< Queue >::clear(), NaiveDedupPolynomialHeap< Queue >::clear(), MapPolynomialHeap::clear(), PriorityQueuePolynomialHeap::clear(), NCF4::matrixReset(), and NCF4::processPreviousF4Matrix().