Macaulay2 Engine: MemoryBlock::allocateArray
allocateArray()
template<typename T > std::pair<T*, T*> MemoryBlock::allocateArray (size_t nelems) inline
Definition at line 21 of file MemoryBlock.hpp.
   {
     return mArena->allocArrayNoCon<T>(nelems);
   }
References mArena, and T.
Referenced by PriorityQueuePolynomialHeap::addEntry(), NaivePolynomialHeap< Queue >::addPolynomial(), NaiveDedupPolynomialHeap< Queue >::addPolynomial(), MapPolynomialHeap::addTerm(), newf4::MonomialView::combine(), NCF4::createOverlapLeadWord(), WordTable::insert(), newf4::MonomialView::MonomialView(), NCF4::processPreRow(), testMemoryBlock(), FreeMonoid::wordProductAsMonom(), and FreeMonoid::wordProductAsWord().