Macaulay2 Engine: ElementArray::swap
swap()
void ElementArray::swap (ElementArray & b) inline
Definition at line 57 of file VectorArithmetic.hpp.
{ std::swap(mValue, b.mValue); }
References mValue, and std::swap().
Referenced by F4GB::insert_gb_element(), and ResPolynomialConstructor::setPolyFromArrays().