Macaulay2 Engine: ElementArray::isNull
isNull()
bool ElementArray::isNull () const inline
Definition at line 56 of file VectorArithmetic.hpp.
 { return mValue == nullptr; }
References mValue.
Referenced by F4GB::gauss_reduce(), F4Res::gaussReduceRow(), F4GB::get_coeffs_array(), F4GB::insert_gb_element(), F4GB::is_new_GB_row(), F4GB::tail_reduce(), F4toM2Interface::to_M2_MutableMatrix(), and ResPolynomial::~ResPolynomial().