Macaulay2 Engine: FlintZZMat::toDMat
toDMat()
void FlintZZMat::toDMat (DMatZZGMP & result) inline
Definition at line 28 of file dmat-qq-interface-flint.hpp.
  {
    result.resize(fmpz_mat_nrows(mMatrix), fmpz_mat_ncols(mMatrix));
    from_fmpz_mat(mMatrix, result);
  }
References from_fmpz_mat(), mMatrix, and DMat< ACoeffRing >::resize().
Referenced by MatrixOps::addMultipleTo(), MatrixOps::mult(), and MatrixOps::subtractMultipleTo().