Macaulay2 Engine: FlintZZMat::FlintZZMat
FlintZZMat() [1/2]
FlintZZMat::FlintZZMat (const DMatZZGMP & mat) inline
Definition at line 16 of file dmat-qq-interface-flint.hpp.
   {
     fmpz_mat_init(mMatrix, mat.numRows(), mat.numColumns());
     to_fmpz_mat(mat, mMatrix);
   }
References mMatrix, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and to_fmpz_mat().