Macaulay2 Engine: FlintZZMat::from_fmpz_mat
from_fmpz_mat()
static void FlintZZMat::from_fmpz_mat (fmpz_mat_t mat, DMatZZGMP & result_mat) inline static private
Definition at line 49 of file dmat-qq-interface-flint.hpp.
  {
    for (long r = 0; r < result_mat.numRows(); r++)
      {
        auto end = result_mat.rowEnd(r);
        long c = 0;
        for (auto it = result_mat.rowBegin(r); it != end; ++it, ++c)
          fmpz_get_mpz(&(*it), fmpz_mat_entry(mat, r, c));
      }
  }
References end(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::rowBegin(), and DMat< ACoeffRing >::rowEnd().
Referenced by toDMat().