Macaulay2 Engine: FlintZZMat::to_fmpz_mat
to_fmpz_mat()
static void FlintZZMat::to_fmpz_mat (const DMatZZGMP & mat1, fmpz_mat_t result_mat) inline static private
Definition at line 38 of file dmat-qq-interface-flint.hpp.
   {
     DMatZZGMP& mat = const_cast<DMatZZGMP&>(mat1);
     for (long r = 0; r < mat.numRows(); r++)
       {
         auto end = mat.rowEnd(r);
         long c = 0;
         for (auto it = mat.rowBegin(r); it != end; ++it, ++c)
           fmpz_set_mpz(fmpz_mat_entry(result_mat, r, c), &(*it));
       }
   }
References end(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::rowBegin(), and DMat< ACoeffRing >::rowEnd().
Referenced by FlintZZMat().