Macaulay2 Engine: BRPStoMatrix
BRPStoMatrix()
const Matrix* BRPStoMatrix (const PolynomialRing * P, const IntermediateBasis & F)
Definition at line 66 of file franzi-interface.cpp.
 {
   MatrixConstructor C(P->make_FreeModule(1), 0);
   const Monoid *M = P->getMonoid();
   const Ring *K = P->getCoefficients();
   int n = P->n_vars();
   exponents_t exp = newarray_atomic(int, n);
   monomial mon = M->make_one();
   for (IntermediateBasis::const_iterator it = F.begin(); it != F.end(); ++it)
     {
       ring_elem f;
       for (monomials::const_iterator it2 = it->second.m.begin();
            it2 != it->second.m.end();
            ++it2)
         {
           brMonomial mono = *it2;
           // cout << "a single mono in brpstoMatrix " << mono << endl;
           longToExponents(n, mono, exp);
           //          for( int i=0; i < n; i++ )
           //          {
           //            cout << exp[i] << " ";
           //          }
           //          cout << endl;
           M->from_expvector(exp, mon);
           ring_elem g = P->make_flat_term(K->one(), mon);
           P->add_to(f, g);
         }
       C.append(P->make_vec(0, f));
     }
   freemem(exp);
   return C.to_matrix();
 }
References Ring::add_to(), MatrixConstructor::append(), mpfr::exp(), freemem(), Monoid::from_expvector(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), longToExponents(), PolynomialRing::make_flat_term(), Ring::make_FreeModule(), Monoid::make_one(), Ring::make_vec(), PolynomialRing::n_vars(), newarray_atomic, Ring::one(), and MatrixConstructor::to_matrix().
Referenced by rawGbBoolean().