Macaulay2 Engine: BRPSfromMatrix
BRPSfromMatrix()
IntermediateBasis BRPSfromMatrix (const Matrix * m)
Definition at line 40 of file franzi-interface.cpp.
 {
   const Ring *R = m->get_ring();
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   assert(P != 0);  // TODO: change this.
   const Monoid *M = P->getMonoid();
   int n = P->n_vars();
   exponents_t exp = newarray_atomic(int, n);
   IntermediateBasis F;
   for (int i = 0; i < m->n_cols(); i++)
     {
       vec v = m->elem(i);
       if (v == 0) continue;
       BRP temp;
       for (Nterm& f : v->coeff)
         {
           M->to_expvector(f.monom, exp);
           brMonomial mono = exponentsToLong(n, exp);
           temp = temp + BRP(mono);
         }
       F[i] = temp;
     }
   freemem(exp);
   return F;
 }
References Ring::cast_to_PolynomialRing(), Nterm::coeff, Matrix::elem(), mpfr::exp(), exponentsToLong(), freemem(), Matrix::get_ring(), PolynomialRing::getMonoid(), Nterm::monom, Matrix::n_cols(), PolynomialRing::n_vars(), newarray_atomic, and Monoid::to_expvector().
Referenced by rawGbBoolean().