Macaulay2 Engine: HilbertController::recomputeHilbertFunction
recomputeHilbertFunction()
bool HilbertController::recomputeHilbertFunction () private
Definition at line 69 of file hilb-fcn.cpp.
 {
   if (hilb_new_elems)
     {
       // Recompute h, hf_diff
       Matrix *M = make_lead_term_matrix();
       RingElement *h = hilb_comp::hilbertNumerator(M);
       if (h == 0) return false;  // computation was interrupted
       hf_diff = (*h) - (*hf_orig);
       hilb_new_elems = false;
     }
   return true;
 }
References hf_diff, hilb_new_elems, hilb_comp::hilbertNumerator(), and make_lead_term_matrix().
Referenced by setDegree().