Macaulay2 Engine: HilbertController::setDegree
setDegree()
bool HilbertController::setDegree (int this_degree)
Definition at line 43 of file hilb-fcn.cpp.
{
  // Recomputes Hilbert function, returns #elems expected in degree this_degree
  // There should be NO elements expected in lower degrees than that.
  // false is returned if either the computation was interrupted, or
  // it was determined that the Hilbert function could not be correct
  // (by expecting a negative number of elements).
  if (!recomputeHilbertFunction()) return false;
  hilb_n_in_degree = hilb_comp::coeff_of(hf_diff, this_degree);
  if (error()) return false;
  return true;
}
References hilb_comp::coeff_of(), error(), hf_diff, hilb_n_in_degree, and recomputeHilbertFunction().
Referenced by F4GB::start_computation().