Macaulay2 Engine: HilbertController::addMonomial
addMonomial()
bool HilbertController::addMonomial (int * a, int comp)
Definition at line 56 of file hilb-fcn.cpp.
 {
   monomial m = R->getMonoid()->make_one();
   R->getMonoid()->from_expvector(a, m);
   ring_elem r = R->make_flat_term(R->getCoefficientRing()->one(), m);
   vec v = R->make_vec(comp - 1, r);
   elems.push_back(v);
   hilb_new_elems = true;
   hilb_n_in_degree--;
   return hilb_n_in_degree == 0;
 }
References Monoid::from_expvector(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), hilb_n_in_degree, hilb_new_elems, PolynomialRing::make_flat_term(), Monoid::make_one(), Ring::make_vec(), Ring::one(), and R.
Referenced by F4GB::insert_gb_element().