Macaulay2 Engine: rawSubduction1
rawSubduction1()
Matrix* rawSubduction1 (int numparts, const Ring * rawT, const Ring * rawS, const Matrix * m, const RingMap * inclusionAmbient, const RingMap * fullSubstitution, const RingMap * substitutionInclusion, Computation * rawGBI, Computation * rawGBReductionIdeal)
Definition at line 660 of file groebner.cpp.
 {
     try
     {
         GBComputation *gbReductionIdeal = rawGBReductionIdeal->cast_to_GBComputation();
         GBComputation *gbI = rawGBI->cast_to_GBComputation();
         if ((gbReductionIdeal == nullptr) || (gbI == nullptr))
         {
             ERROR("expected a Groebner basis computation");
             return nullptr;
         }
         return sagbi::subduct1(numparts, rawT, rawS, m, inclusionAmbient, fullSubstitution, substitutionInclusion, gbI, gbReductionIdeal);
     } catch (const exc::engine_error& e)
     {
         ERROR(e.what());
         return nullptr;
     }
 }
References Computation::cast_to_GBComputation(), ERROR(), and sagbi::subduct1().