Macaulay2 Engine: rawNCReductionTwoSided
rawNCReductionTwoSided()
const Matrix* rawNCReductionTwoSided (const Matrix * toBeReduced, const Matrix * reducers)
Definition at line 951 of file groebner.cpp.
 {
   const Ring* R = toBeReduced->get_ring();
   if (R != reducerMatrix->get_ring())
     {
       ERROR("expected matrices to be over the same ring");
       return nullptr;
     }
   const M2FreeAlgebra* A = R->cast_to_M2FreeAlgebra();
   if (A != nullptr and reducerMatrix->n_rows() == 1)
     {
       auto outRows = toBeReduced->n_rows();
       auto outCols = toBeReduced->n_cols();
       auto reducees = matrixToPolyList(A, toBeReduced);
       auto reducers = matrixToPolyList(A, reducerMatrix);
       NCGroebner G(A->freeAlgebra(),reducers, 0, 0);
       G.initReductionOnly();
       auto result = G.twoSidedReduction(reducees);
       return polyListToMatrix(A, result, outRows, outCols); // consumes the Poly's in result.
     }
   ERROR("expected a matrix over a noncommutative algebra");
   return nullptr;
 }
References Ring::cast_to_M2FreeAlgebra(), ERROR(), M2FreeAlgebra::freeAlgebra(), G, Matrix::get_ring(), matrixToPolyList(), Matrix::n_cols(), Matrix::n_rows(), and polyListToMatrix().