Macaulay2 Engine: rawNCBasis
rawNCBasis()
const Matrix* rawNCBasis (const Matrix * gb2SidedIdeal, M2_arrayint lo_degree, M2_arrayint hi_degree, int limit)
Definition at line 965 of file groebner.cpp.
 {
   const Ring* R = gb2SidedIdeal->get_ring();
   if (R == nullptr)
     {
       ERROR("internal error: expected non-null Ring!");
       return nullptr;
     }
   try {
     const M2FreeAlgebra* A = R->cast_to_M2FreeAlgebra();
     if (A != nullptr)
       {
         ConstPolyList G = matrixToPolyList(A, gb2SidedIdeal);
         // WARNING: The following line creates new polynomials
         // which are used directly in vectorToMatrix (without copying)
         // but when result goes out of scope, the list is deleted,
         // but not the polynomials themselves, as they are pointers.
         PolyList result;
         bool worked = ncBasis(A->freeAlgebra(),
                               G,
                               M2_arrayint_to_stdvector<int>(lo_degree),
                               M2_arrayint_to_stdvector<int>(hi_degree),
                               limit,
                               result);
         if (not worked) return nullptr;
         return polyListToMatrix(A, result, 1, result.size()); // consumes entries of result
       }
     ERROR("expected a free algebra");
     return nullptr;
   }
   catch (exc::engine_error& e) {
     ERROR(e.what());
     return nullptr;
   }
 }
References Ring::cast_to_M2FreeAlgebra(), ERROR(), M2FreeAlgebra::freeAlgebra(), Matrix::get_ring(), matrixToPolyList(), ncBasis(), and polyListToMatrix().