Macaulay2 Engine: binomial_s_pair_set::insert_pair
insert_pair()
void binomial_s_pair_set::insert_pair (s_pair_degree_list * q, binomial_s_pair & s) private
Definition at line 495 of file gb-toric.cpp.
 {
   int cmp;
   s_pair_lcm_list head;
   head.next = q->pairs;
   s_pair_lcm_list *r = &head;
   while (true)
     {
       if (r->next == NULL || ((cmp = R->compare(s.lcm, r->next->lcm)) == GT))
         {
           // Insert new lcm node
           s_pair_lcm_list *r1 = new s_pair_lcm_list;
           r1->next = r->next;
           r1->lcm = s.lcm;
           r1->pairs = NULL;
           r->next = r1;
           break;
         }
       if (cmp == EQ)
         {
           R->remove_monomial(s.lcm);
           break;
         }
       r = r->next;
     }
   r = r->next;
   s_pair_elem *s1 = new s_pair_elem(s.f1, s.f2);
   q->pairs = head.next;
   s1->next = r->pairs;
   r->pairs = s1;
 }
References binomial_ring::compare(), EQ, binomial_s_pair::f1, binomial_s_pair::f2, GT, binomial_s_pair::lcm, binomial_s_pair_set::s_pair_lcm_list::lcm, binomial_s_pair_set::s_pair_lcm_list::next, binomial_s_pair_set::s_pair_elem::next, binomial_s_pair_set::s_pair_degree_list::pairs, binomial_s_pair_set::s_pair_lcm_list::pairs, R, and binomial_ring::remove_monomial().
Referenced by insert().