Macaulay2 Engine: binomial_s_pair_set::stats
stats()
void binomial_s_pair_set::stats () const
Definition at line 627 of file gb-toric.cpp.
 {
   buffer o;
   int np, nl;
   np = nl = 0;
   o << " degree"
     << "   pairs"
     << "   left"
     << "   done" << newline;
   for (int i = 0; i <= _max_degree; i++)
     {
       np += _npairs[2 * i];
       nl += _npairs[2 * i + 1];
       o.put(i, 7);
       o << " ";
       o.put(_npairs[2 * i], 6);
       o << " ";
       o.put(_npairs[2 * i + 1], 6);
       o << " ";
       o.put(_npairs[2 * i] - _npairs[2 * i + 1], 6);
       o << newline;
     }
   o << "  total ";
   o.put(np, 6);
   o << " ";
   o.put(nl, 6);
   o << " ";
   o.put(np - nl, 6);
   o << newline;
   emit(o.str());
 }
References _max_degree, _npairs, emit(), newline, buffer::put(), and buffer::str().