Macaulay2 Engine: binomial_s_pair_set::remove_pair_list
remove_pair_list()
void binomial_s_pair_set::remove_pair_list (s_pair_degree_list * p) private
Definition at line 474 of file gb-toric.cpp.
 {
   while (p->pairs != nullptr)
     {
       s_pair_lcm_list *thislcm = p->pairs;
       p->pairs = thislcm->next;
       remove_lcm_list(thislcm);
     }
   freemem(p);
 }
References freemem(), binomial_s_pair_set::s_pair_lcm_list::next, p, and remove_lcm_list().
Referenced by ~binomial_s_pair_set().