Macaulay2 Engine: MonomialIdeal::radical
radical()
MonomialIdeal * MonomialIdeal::radical () const
Definition at line 899 of file monideal.cpp.
 {
   // std::cout << "monideal: calling radical on ";
   // dmonideal(const_cast<MonomialIdeal*>(this));
   // std::cout << std::endl << "  -- radical(I) = ";
   VECTOR(Bag*) new_elems;
   for (Bag& a : *this)
     {
       Bag *b = new Bag(a.basis_elem());
       varpower::radical(a.monom().data(), b->monom());
       new_elems.push_back(b);
     }
   MonomialIdeal *result = new MonomialIdeal(get_ring(), new_elems);
   // dmonideal(result);
   // std::cout << "----" << std::endl;
   return result;
 }
References int_bag::basis_elem(), get_ring(), int_bag::monom(), MonomialIdeal(), ExponentList< E, L >::radical(), and VECTOR().
Referenced by rawRadicalMonomialIdeal().