Macaulay2 Engine: MonomialIdeal::find_all_divisors
find_all_divisors()
void MonomialIdeal::find_all_divisors (const_exponents exp, gc_vector< Bag * > & b) const
Definition at line 246 of file monideal.cpp.
 {
   b.clear();
   if (mi == nullptr) return;
   Nmi_node *p = mi;
   for (;;)
     {
       p = p->right;
       if (p == p->header)
         {
           if ((p = p->down()) == nullptr) return;
           continue;
         }
       if (p->exp > exp[p->var])
         {
           if ((p = p->header->down()) == nullptr) return;
           continue;
         }
       if (p->tag == Nmi_node::leaf)
         {
           b.push_back(p->baggage());
         }
       else
         p = p->down();
     }
 }
References mpfr::exp(), Nmi_node::leaf, mi, and p.
Referenced by res2_comp::find_divisor(), GBKernelComputation::find_divisor(), and Matrix::koszul_monomials().