Macaulay2 Engine: MonomialIdeal::search
search()
int MonomialIdeal::search (const int * m, Bag *& b) const
Definition at line 275 of file monideal.cpp.
 {
   int* exp = ARRAY_ON_STACK(int, get_ring()->n_vars());
   varpower::to_ntuple(get_ring()->n_vars(), m, exp);
   int result = search_expvector(exp, b);
   return result;
 }
References ARRAY_ON_STACK, mpfr::exp(), get_ring(), search_expvector(), and varpower::to_ntuple().
Referenced by insert(), intersect(), iquotient_and_sum(), and MonomialIdeal().