Macaulay2 Engine: MonomialIdeal::intersect
intersect() [1/2]
MonomialIdeal * MonomialIdeal::intersect (const MonomialIdeal & J) const
Definition at line 668 of file monideal.cpp.
 {
   // The idea: take the elements of 'this'
   //   for each: if the element is in J, then keep it directly.
   //      otherwie compute the lcm's.
   VECTOR(Bag*) new_elems;
   for (Bag& a : *this)
     {
       Bag *c;
       if (J.search(a.monom().data(), c))
         {
           new_elems.push_back(new Bag(a));
         }
       else
         for (Bag& b : J)
           {
             Bag *new_elem = new Bag(a.basis_elem());
             varpower::lcm(a.monom().data(),
                           b.monom().data(),
                           new_elem->monom());
             new_elems.push_back(new_elem);
           }
     }
   MonomialIdeal *result = new MonomialIdeal(get_ring(), new_elems);
   GC_reachable_here(&J);
   return result;
 }
References int_bag::basis_elem(), get_ring(), ExponentList< E, L >::lcm(), int_bag::monom(), MonomialIdeal(), search(), and VECTOR().