Macaulay2 Engine: MonomialIdeal::get_ring
get_ring()
const PolynomialRing* MonomialIdeal::get_ring () const inline
Definition at line 126 of file monideal.hpp.
 { return R; }
References R.
Referenced by MinimalPrimes::alg1_min_primes(), borel(), copy(), erase(), FrobbyAlexanderDual(), hilb_comp::hilbertNumerator(), IM2_MonomialIdeal_intersect(), IM2_MonomialIdeal_is_equal(), intersect(), iquotient_and_sum(), is_borel(), lcm(), Matrix::make(), MinimalPrimes::MinimalPrimes(), operator*(), operator+(), partition_table::partition(), quotient(), radical(), rawColonMonomialIdeal2(), rawSaturateMonomialIdeal2(), sat(), search(), and text_out().