Macaulay2 Engine: MonomialIdeal::search_expvector
search_expvector()
int MonomialIdeal::search_expvector (const_exponents m, Bag *& b) const
Definition at line 214 of file monideal.cpp.
 {
   if (mi == nullptr) return 0;
   Nmi_node *p = mi;
   for (;;)
     {
       p = p->right;
       if (p == p->header)
         {
           if ((p = p->down()) == nullptr) return 0;
           continue;
         }
       if (p->exp > exp[p->var])
         {
           if ((p = p->header->down()) == nullptr) return 0;
           continue;
         }
       if (p->tag == Nmi_node::leaf)
         {
           b = p->baggage();
           return 1;
         }
       p = p->down();
     }
 }
References mpfr::exp(), Nmi_node::leaf, mi, and p.
Referenced by all_have_pure_powers(), GBKernelComputation::find_ring_divisor(), GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), is_borel(), ReducedGB_Field_Local::minimalize(), ReducedGB_Field::minimalize(), QRingInfo_field::QRingInfo_field(), res_comp::reduce(), ReducedGB_Field::remainder(), search(), KBasis::try_insert_full(), KBasis::try_insert_mg(), and KBasis::try_insert_sg().