Macaulay2 Engine: MonomialIdeal::MonomialIdeal
MonomialIdeal() [1/3]
MonomialIdeal::MonomialIdeal (const PolynomialRing * RR, stash * mi_stash = nullptr)
Definition at line 91 of file monideal.cpp.
     : R(RR), mi(nullptr), count(0), mi_stash(mi_stash0)
 {
   if (mi_stash == nullptr)
     {
       count = 1;
       mi_stash = new stash("mi_node", sizeof(Nmi_node));
     }
 }
References count, and mi_stash.
Referenced by borel(), copy(), erase(), intersect(), operator*(), operator+(), quotient(), radical(), and sat().