Macaulay2 Engine: MonomialIdeal::sat
sat()
MonomialIdeal * MonomialIdeal::sat (const MonomialIdeal & J) const
Definition at line 869 of file monideal.cpp.
 {
   // std::cout << "--calling sat -- I = ";
   // dmonideal(const_cast<MonomialIdeal*>(this));
   // std::cout << std::endl << "  -- J = ";
   // dmonideal(const_cast<MonomialIdeal*>(&J));
   // std::cout << std::endl << "  -- sat(I,J) = ";
   // debug_check();
   // J.debug_check();
   MonomialIdeal *result = new MonomialIdeal(get_ring());
   Bag *b = new Bag();
   varpower::one(b->monom());
   result->insert(b);
   for (Bag& a : J)
     {
       MonomialIdeal *result1 = erase(a.monom().data());
       // result1->debug_check();
       MonomialIdeal *next_result = result->intersect(*result1);
       // next_result->debug_check();
       delete result1;
       delete result;
       result = next_result;
     }
   // dmonideal(result);
   // std::cout << "----" << std::endl;
   GC_reachable_here(&J);
   return result;
 }
References erase(), get_ring(), insert(), intersect(), int_bag::monom(), MonomialIdeal(), and ExponentList< E, L >::one().
Referenced by rawSaturateMonomialIdeal2().