Macaulay2 Engine: MonomialIdeal::insert_minimal
insert_minimal()
void MonomialIdeal::insert_minimal (Bag * b) inline
Definition at line 256 of file monideal.hpp.
 {
   insert1(mi, b);
   count += 2;
 }
References count, insert1(), and mi.
Referenced by MyIdealConsumer::consume(), copy(), insert(), iquotient_and_sum(), MonomialIdeal(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), operator-(), and res_comp::skeleton_pairs().