Macaulay2 Engine: MonomialIdeal::prev
prev() [1/2]
Nmi_node * MonomialIdeal::prev (Nmi_node * p) const private
Definition at line 303 of file monideal.cpp.
 {
   while (p != nullptr)
     {
       p = p->right;
       if (p->tag == Nmi_node::leaf)
         return p;
       else
         p = p->down();
     }
   return nullptr;
 }
References Nmi_node::leaf, and p.
Referenced by last_node(), MonomialIdeal::Iterator::operator--(), and prev().