Macaulay2 Engine: MonomialIdeal::next
next() [1/2]
Nmi_node * MonomialIdeal::next (Nmi_node * p) const private
Definition at line 285 of file monideal.cpp.
{
  while (p != nullptr)
    {
      p = p->left;
      if (p->tag == Nmi_node::leaf)
        return p;
      else
        p = p->down();
    }
  return nullptr;
}
References Nmi_node::leaf, and p.
Referenced by AssociatedPrimes::ass_prime_generator(), MinimalPrimes::ass_prime_generator(), first_node(), next(), MonomialIdeal::Iterator::operator++(), remove(), and second_elem().