Macaulay2 Engine: MonomialIdeal::do_tree
do_tree()
void MonomialIdeal::do_tree (Nmi_node * p, int depth, int indent, int disp) const private
Definition at line 494 of file monideal.cpp.
{
  if (depth > ndepth) ndepth = depth;
  do_node(p, indent, disp);
  Nmi_node *q = p->right;
  while (q != p)
    {
      do_node(q, indent, disp);
      if (q->tag != Nmi_node::leaf)
        do_tree(q->down(), depth + 1, indent + 2, disp);
      q = q->right;
    }
}
References do_node(), do_tree(), Nmi_node::down, Nmi_node::leaf, ndepth, p, Nmi_node::right, and Nmi_node::tag.
Referenced by do_tree().