Macaulay2 Engine: MonomialIdeal::second_elem
second_elem()
const int * MonomialIdeal::second_elem () const
Definition at line 179 of file monideal.cpp.
 {
   return next(first_node())->monom().raw();
 }
References first_node(), Nmi_node::monom(), next(), and intarray::raw().
Referenced by hilb_comp::do_ideal().