Macaulay2 Engine: MonomialIdeal::insert1
insert1()
void MonomialIdeal::insert1 (Nmi_node *& p, Bag * b) private
Definition at line 321 of file monideal.cpp.
 {
   Nmi_node **p = &top, *up = nullptr;
   int one_element = 1;
   for (index_varpower i = b->monom().data(); i.valid();)
     {
       one_element = 0;
       int insert_var = i.var();
       int insert_exp;
       if (*p == nullptr)
         {
           // make a new header node
           *p = new_internal_mi_node(insert_var, 0, up);
           (*p)->header = (*p)->left = (*p)->right = *p;
         }
       else if ((*p)->var < insert_var)
         {
           // make a new layer
           Nmi_node *header_node, *zero_node;
           header_node = new_internal_mi_node(insert_var, 0, up);
           zero_node = new_internal_mi_node(insert_var, 0, *p);
           header_node->left = header_node->right = zero_node;
           (*p)->down() = zero_node;
           *p = header_node->header = zero_node->header = zero_node->left =
               zero_node->right = header_node;
         }
       if ((*p)->var > insert_var)
         {
           insert_var = (*p)->var;
           insert_exp = 0;
         }
       else
         {
           insert_exp = i.exponent();
           ++i;
         }
       Nmi_node *q = (*p)->right;
       while ((q != q->header) && (q->exp < insert_exp)) q = q->right;
       if (q->exp != insert_exp)
         {
           Nmi_node *insert_node;
           if (i.valid())
             {
               insert_node = new_internal_mi_node(
                 insert_var, insert_exp, static_cast<Nmi_node*>(nullptr));
               q->insert_to_left(insert_node);
               q = insert_node;
             }
           else
             {
               insert_node = new_leaf_mi_node(insert_var, insert_exp, b);
               q->insert_to_left(insert_node);
               return;
             }
         }
       up = q;
       p = &(q->down());
     }
   if (one_element)
     {
       // insert a header node and a var/exp = 0/0 leaf
       top = new_internal_mi_node(0, 0, static_cast<Nmi_node *>(nullptr));
       Nmi_node *leaf_node = new_leaf_mi_node(0, 0, b);
       top->left = top->right = leaf_node;
       top->header = leaf_node->header = leaf_node->left = leaf_node->right =
           top;
     }
 }
References Nmi_node::down, Nmi_node::exp, Nmi_node::header, Nmi_node::insert_to_left(), Nmi_node::left, int_bag::monom(), new_internal_mi_node(), new_leaf_mi_node(), p, Nmi_node::right, and Nmi_node::var.
Referenced by insert_minimal().