Macaulay2 Engine: MonomialIdeal::is_one
is_one()
bool MonomialIdeal::is_one () const
Definition at line 977 of file monideal.cpp.
 {
   if (size() != 1) return false;
   Nmi_node *p = mi->left;
   if (p->var != 0 || p->exp != 0 || p->tag != Nmi_node::leaf) return false;
   return true;
 }
References Nmi_node::leaf, Nmi_node::left, mi, p, and size().
Referenced by KBasis::compute(), and text_out().