Macaulay2 Engine: MonomialIdeal::MonomialIdeal
MonomialIdeal() [3/3]
MonomialIdeal::MonomialIdeal (const PolynomialRing * R0, gc_vector< Bag * > & elems, stash * mi_stash0 = nullptr)
Definition at line 140 of file monideal.cpp.
     : R(R0), mi(nullptr), count(0), mi_stash(mi_stash0)
 {
   if (mi_stash == nullptr)
     {
       count = 1;
       mi_stash = new stash("mi_node", sizeof(Nmi_node));
     }
   // create a vector of <simple degree, index> for each element of 'elems'.
   // sort them in increasing simple degree.
   // then loop through, adding them in.  This will insure that we only add in
   // minimal generators.
   std::vector<std::pair<int, int>> degs_and_indices;
   int count = 0;
   for (auto& b : elems)
     {
       int deg = varpower::simple_degree(b->monom().data());
       degs_and_indices.push_back(std::make_pair(deg, count));
       ++count;
     }
   std::stable_sort(degs_and_indices.begin(), degs_and_indices.end());
   for (auto p : degs_and_indices)
     {
       Bag* b = elems[p.second];
       Bag* b1; // not used here...
       if (search(b->monom().data(), b1))
         delete b;
       else
         insert_minimal(b);
     }
 }
References count, insert_minimal(), mi_stash, int_bag::monom(), p, search(), and ExponentList< E, L >::simple_degree().