Macaulay2 Engine: MonomialIdeal::text_out
text_out()
void MonomialIdeal::text_out (buffer & o) const
Definition at line 639 of file monideal.cpp.
 {
   const PolynomialRing *P = get_ring()->cast_to_PolynomialRing();
   assert(P != nullptr);
   const Monoid *M = P->getMonoid();
   if (size() == 0)
     {
       o << "0";
       return;
     }
   if (is_one())
     {
       if (size() != 1)
         std::cout << "bad news: count is not 1, but ideal is 1..." << std::endl;
       o << "1";
       return;
     }
   monomial m = M->make_one();
   for (Bag& j : *this)
     {
       const_varpower n = j.monom().data();
       M->from_varpower(n, m);
       M->elem_text_out(o, m);
       if (M2_gbTrace > 0) o << '(' << j.basis_elem() << ")";
       o << ' ';
     }
   M->remove(m);
 }
References int_bag::basis_elem(), PolynomialRing::cast_to_PolynomialRing(), Monoid::elem_text_out(), Monoid::from_varpower(), get_ring(), PolynomialRing::getMonoid(), is_one(), M2_gbTrace, Monoid::make_one(), int_bag::monom(), Monoid::remove(), and size().
Referenced by dmonideal(), and MonomialIdeal_to_string().