Macaulay2 Engine: MonomialIdeal::intersect
intersect() [2/2]
MonomialIdeal * MonomialIdeal::intersect (const_varpower m) const
Definition at line 696 of file monideal.cpp.
 {
   VECTOR(Bag*) new_elems;
   for (Bag& a : *this)
     {
       Bag *b = new Bag(a.basis_elem());
       varpower::lcm(a.monom().data(), m, b->monom());
       new_elems.push_back(b);
     }
   MonomialIdeal *result = new MonomialIdeal(get_ring(), new_elems);
   return result;
 }
References int_bag::basis_elem(), ExponentList< E, L >::lcm(), int_bag::monom(), and VECTOR().
Referenced by alexander_dual(), IM2_MonomialIdeal_intersect(), quotient(), and sat().