Macaulay2 Engine: MonomialIdeal::size
size()
int MonomialIdeal::size () const inline
Definition at line 121 of file monideal.hpp.
 { return count / 2; }
References count.
Referenced by MinimalPrimes::alg1_min_primes(), computeHashValue(), hilb_comp::do_ideal(), res2_comp::find_divisor(), GBKernelComputation::find_divisor(), find_pivot(), IM2_MonomialIdeal_n_gens(), is_equal(), is_one(), Matrix::make(), and text_out().