Macaulay2 Engine: MonomialIdeal::first_node
first_node()
Nmi_node * MonomialIdeal::first_node () const inline private
Definition at line 262 of file monideal.hpp.
 { return next(mi); }
References mi, and next().
Referenced by AssociatedPrimes::associated_primes(), AssociatedPrimes::codimension(), MinimalPrimes::codimension(), first_elem(), MinimalPrimes::min_primes(), and second_elem().