Macaulay2 Engine: MonomialIdeal::insert
insert()
int MonomialIdeal::insert (Bag * b)
Definition at line 622 of file monideal.cpp.
 {
   Bag *old_b;
   const_varpower m = b->monom().raw();
   if (search(m, old_b))
     {
       delete b;
       return 0;
     }
   insert_minimal(b);
   return 1;
 }
References insert_minimal(), int_bag::monom(), intarray::raw(), and search().
Referenced by alexander_dual(), AssociatedPrimes::ass_prime_generator(), MinimalPrimes::ass_prime_generator(), GB_comp::find_pairs(), gb2_comp::find_pairs(), QRingInfo_field::QRingInfo_field(), quotient(), sat(), and varpower_monideal().