Macaulay2 Engine: MonomialIdeal::remove
remove()
int MonomialIdeal::remove (Bag *& b)
Definition at line 451 of file monideal.cpp.
 {
   Nmi_node *p = reinterpret_cast<Nmi_node *>(next(mi));
   if (p == nullptr) return 0;
   b = p->baggage();
   remove1(p);
   return 1;
 }
References mi, next(), p, and remove1().
Referenced by partition_table::partition().