Macaulay2 Engine: MonomialIdeal::second_elem
second_elem()
const_varpower MonomialIdeal::second_elem () const
Definition at line 182 of file monideal.cpp.
 {
   return next(first_node())->monom().data();
 }
References first_node(), Nmi_node::monom(), and next().
Referenced by hilb_comp::do_ideal().