Macaulay2 Engine: MonomialIdeal::lcm
lcm()
M2_arrayint MonomialIdeal::lcm () const
Definition at line 819 of file monideal.cpp.
 {
   M2_arrayint result = M2_makearrayint(get_ring()->n_vars());
   for (int i = 0; i < result->len; i++) result->array[i] = 0;
   for (Bag& a : *this)
     {
       for (index_varpower j = a.monom().data(); j.valid(); ++j)
         if (result->array[j.var()] < j.exponent())
           result->array[j.var()] = j.exponent();
     }
   return result;
 }
References get_ring(), M2_makearrayint(), and int_bag::monom().
Referenced by all_have_pure_powers(), and rawMonomialIdealLCM().