Macaulay2 Engine: MonomialIdeal::operator+
operator+()
MonomialIdeal * MonomialIdeal::operator+ (const MonomialIdeal & F) const
Definition at line 726 of file monideal.cpp.
 {
   VECTOR(Bag*) new_elems;
   for (Bag& a : *this)
     {
       new_elems.push_back(new Bag(a));
     }
   for (Bag& a : J)
     {
       new_elems.push_back(new Bag(a));
     }
   MonomialIdeal *result = new MonomialIdeal(get_ring(), new_elems);
   GC_reachable_here(&J);
   return result;
 }
References get_ring(), MonomialIdeal(), and VECTOR().