Macaulay2 Engine: MonomialIdeal::topvar
topvar()
int MonomialIdeal::topvar () const inline
Definition at line 122 of file monideal.hpp.
{ return (mi == nullptr ? -1 : mi->var); }
References mi, and Nmi_node::var.
Referenced by alexDual(), hilb_comp::do_ideal(), FrobbyAlexanderDual(), partition_table::partition(), popular_var(), and wrapperFrobbyAlexanderDual().