Macaulay2 Engine: MonomialIdeal::quotient
quotient() [1/2]
MonomialIdeal * MonomialIdeal::quotient (const MonomialIdeal & J) const
Definition at line 773 of file monideal.cpp.
 {
   // std::cout << "--calling quotient -- I = ";
   // dmonideal(const_cast<MonomialIdeal*>(this));
   // std::cout << std::endl << "  -- J = ";
   // dmonideal(const_cast<MonomialIdeal*>(&J));
   // std::cout << std::endl << "  -- I:J = ";
   // debug_check();
   // J.debug_check();
   MonomialIdeal *result = new MonomialIdeal(get_ring());
   Bag *b = new Bag();
   varpower::one(b->monom());
   result->insert(b);
   for (Bag& a : J)
     {
       MonomialIdeal *result1 = quotient(a.monom().data());
       // result1->debug_check();
       MonomialIdeal *next_result = result->intersect(*result1);
       // next_result->debug_check();
       delete result1;
       delete result;
       result = next_result;
     }
   // dmonideal(result);
   // std::cout << "----" << std::endl;
   GC_reachable_here(&J);
   return result;
 }
References get_ring(), insert(), intersect(), int_bag::monom(), MonomialIdeal(), ExponentList< E, L >::one(), and quotient().