Macaulay2 Engine: MonomialIdeal::alexander_dual
alexander_dual()
MonomialIdeal * MonomialIdeal::alexander_dual (const M2_arrayint a) const
Definition at line 836 of file monideal.cpp.
 {
   MonomialIdeal *result = new MonomialIdeal(get_ring());
   Bag *b = new Bag();
   varpower::one(b->monom());
   result->insert(b);
   for (Bag& b : *this)
     {
       MonomialIdeal *I1 =
           varpower_monideal(get_ring(), a, b.monom().raw());
       MonomialIdeal *next_result = result->intersect(*I1);
       delete I1;
       delete result;
       result = next_result;
     }
   return result;
 }
References insert(), intersect(), int_bag::monom(), varpower::one(), intarray::raw(), and varpower_monideal().
Referenced by alexDual().