Macaulay2 Engine: MonomialIdeal::erase
erase()
MonomialIdeal * MonomialIdeal::erase (const_varpower m) const
Definition at line 853 of file monideal.cpp.
 {
   debug_check();
   VECTOR(Bag*) new_elems;
   for (Bag& a : *this)
     {
       Bag *b = new Bag(a.basis_elem());
       varpower::erase(a.monom().data(), m, b->monom());
       new_elems.push_back(b);
     }
   MonomialIdeal *result = new MonomialIdeal(get_ring(), new_elems);
   result->debug_check();
   return result;
 }
References int_bag::basis_elem(), debug_check(), ExponentList< E, L >::erase(), get_ring(), int_bag::monom(), MonomialIdeal(), and VECTOR().
Referenced by rawSaturateMonomialIdeal1(), and sat().