Macaulay2 Engine: MonomialIdeal::first_elem
first_elem()
const_varpower MonomialIdeal::first_elem () const
Definition at line 177 of file monideal.cpp.
 {
   return first_node()->monom().raw();
 }
References first_node(), Nmi_node::monom(), and intarray::raw().
Referenced by hilb_comp::do_ideal().