Macaulay2 Engine: MonomialIdeal::debug_out
debug_out()
void MonomialIdeal::debug_out (int disp = 1) const
Definition at line 508 of file monideal.cpp.
 {
   nlists = 0;
   nnodes = 0;
   nleaves = 0;
   ndepth = 0;
   if (mi != nullptr) do_tree(mi, 0, 0, disp);
   buffer o;
   o << "list nodes     = " << nlists << newline;
   o << "internal nodes = " << nnodes << newline;
   o << "monomials      = " << nleaves << newline;
   o << "max depth      = " << ndepth << newline;
   emit(o.str());
 }
References emit(), ndepth, newline, nleaves, nlists, nnodes, and buffer::str().
Referenced by res2_comp::new_pairs(), res_comp::new_pairs(), and res_comp::skeleton_pairs().