Macaulay2 Engine: MonomialIdeal::quotient
quotient() [2/2]
MonomialIdeal * MonomialIdeal::quotient (const_varpower m) const
Definition at line 759 of file monideal.cpp.
 {
   VECTOR(Bag*) new_elems;
   for (Bag& a : *this)
     {
       Bag *b = new Bag(a.basis_elem());
       varpower::quotient(a.monom().data(), m, b->monom());
       new_elems.push_back(b);
     }
   MonomialIdeal *result = new MonomialIdeal(get_ring(), new_elems);
   return result;
 }
References int_bag::basis_elem(), int_bag::monom(), ExponentList< E, L >::quotient(), and VECTOR().
Referenced by quotient(), rawColonMonomialIdeal1(), and rawColonMonomialIdeal2().