Macaulay2 Engine: MonomialIdeal::is_borel
is_borel()
bool MonomialIdeal::is_borel () const
Definition at line 955 of file monideal.cpp.
 {
   exponents_t bexp = newarray_atomic(int, get_ring()->n_vars());
   for (Bag& b : *this)
     {
       Bag *c;
       varpower::to_expvector(get_ring()->n_vars(), b.monom().data(), bexp);
       for (int j = get_ring()->n_vars() - 1; j >= 1; j--)
         if (bexp[j] > 0)
           {
             bexp[j]--;
             bexp[j - 1]++;
             int isthere = search_expvector(bexp, c);
             bexp[j]++;
             bexp[j - 1]--;
             if (!isthere) return 0;
           }
     }
   freemem(bexp);
   return 1;
 }
References freemem(), get_ring(), int_bag::monom(), newarray_atomic, search_expvector(), and ExponentList< E, L >::to_expvector().
Referenced by IM2_MonomialIdeal_is_borel().