Macaulay2 Engine: MonomialIdeal::delete_mi_node
delete_mi_node()
void MonomialIdeal::delete_mi_node (Nmi_node * p) private
Definition at line 78 of file monideal.cpp.
 {
   if (p == nullptr) return;
   if (p->right != p->header) delete_mi_node(p->right);
   if (p->tag == Nmi_node::node)
     {
       if (p->header != p) delete_mi_node(p->down());
     }
   else
     delete p->baggage();
   mi_stash->delete_elem(p);
 }
References stash::delete_elem(), delete_mi_node(), mi_stash, Nmi_node::node, and p.
Referenced by delete_mi_node(), remove1(), and remove_MonomialIdeal().