Macaulay2 Engine: MonomialIdeal::remove1
remove1()
void MonomialIdeal::remove1 (Nmi_node * p) private
Definition at line 397 of file monideal.cpp.
 {
   assert(p != nullptr);
   assert(p->tag == Nmi_node::leaf);
   p->baggage() = nullptr;
   count -= 2;
   for (; p != nullptr;)
     {
       p->left->right = p->right;
       p->right->left = p->left;
       Nmi_node *q = p->header;
       p->left = p->right = nullptr;
       delete_mi_node(p);
       if (q->right == q->header)  // only the header is left, so delete it
         {
           p = q->down();
           q->down() = nullptr;
           if (p != nullptr) p->down() = nullptr;
           delete_mi_node(q);
           continue;
         }
       if (q->left != q->right) return;
       if (q->left->exp > 0) return;
       Nmi_node *dad = q->down();
       if (q->left->tag == Nmi_node::leaf)
         {
           // set parent of q to be a leaf with baggage of q->left
           // since this is a leaf, dad should be non null
           assert(dad != nullptr);
           dad->tag = Nmi_node::leaf;
           dad->baggage() = q->left->baggage();
         }
       else
         {
           // set parent of q to be node pointing to q->left->down
           q->left->down()->down() = dad;
           if (dad != nullptr)
             dad->down() = q->left->down();
           else
             mi = q->left->down();
           q->left->down() = nullptr;
         }
       q->down() = nullptr;
       delete_mi_node(q);  // Deletes both nodes q, q->left.
       return;
     }
   if (p == nullptr) mi = nullptr;
 }
References Nmi_node::baggage(), count, delete_mi_node(), Nmi_node::down, Nmi_node::exp, Nmi_node::header, Nmi_node::leaf, Nmi_node::left, mi, p, Nmi_node::right, and Nmi_node::tag.
Referenced by remove().