Macaulay2 Engine: MonomialIdeal::search
search()
int MonomialIdeal::search (const_varpower m, Bag *& b) const
Definition at line 278 of file monideal.cpp.
 {
   exponents_t exp = ARRAY_ON_STACK(int, get_ring()->n_vars());
   varpower::to_expvector(get_ring()->n_vars(), m, exp);
   return search_expvector(exp, b);
 }
References ARRAY_ON_STACK, mpfr::exp(), get_ring(), search_expvector(), and ExponentList< E, L >::to_expvector().
Referenced by insert(), intersect(), iquotient_and_sum(), and MonomialIdeal().