Macaulay2 Engine: mpfr::hypot
hypot() [2/3]
const mpreal mpfr::hypot (const mpreal & a, const mpreal & b, const mpreal & c, const mpreal & d) inline
Definition at line 2460 of file mpreal.h.
 {
     if(isnan(a) || isnan(b) || isnan(c) || isnan(d)) return mpreal().setNan();
     else
     {
         mpreal absa = abs(a), absb = abs(b), absc = abs(c), absd = abs(d);
         mpreal w = (std::max)(absa, (std::max)(absb, (std::max)(absc, absd)));
         mpreal r;
         if (!iszero(w))
         {
             mpreal iw = 1/w;
             r = w * sqrt(sqr(absa*iw) + sqr(absb*iw) + sqr(absc*iw) + sqr(absd*iw));
         }
         return r;
     }
 }
References abs(), isnan(), iszero(), max, mpfr::mpreal::setNan(), sqr(), and sqrt().