Macaulay2 Engine: mpfr::negate
negate()
mpreal& mpfr::negate (mpreal & x) inline
Definition at line 2022 of file mpreal.h.
 {
     mpfr_neg(x.mpfr_ptr(),x.mpfr_srcptr(),mpreal::get_default_rnd());
     return x;
 }
References mpfr::mpreal::get_default_rnd(), and x.
Referenced by DetComputation::calc_det(), PfaffianComputation::calc_pfaff(), Matrix::koszul(), and DetComputation::make_dynamic_cache().