Macaulay2 Engine: mpfr::fabs
fabs()
const mpreal mpfr::fabs (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2268 of file mpreal.h.
 {   MPREAL_UNARY_MATH_FUNCTION_BODY(abs  );    }
Referenced by M2::ARingRR::abs(), PointArray::are_same(), M2::ARingCC::divide(), M2::ARingRR::increase_norm(), M2::ARingCC::invert(), mpfc_abs(), mpfc_div(), mpfc_sqrt(), TEST(), HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track(), M2::ARingCC::zeroize_tiny(), and M2::ARingRR::zeroize_tiny().