Macaulay2 Engine: mpfr::ldexp
ldexp()
const mpreal mpfr::ldexp (const mpreal & v, mp_exp_t exp) inline
Definition at line 2048 of file mpreal.h.
 {
     mpreal x(v);
     // rounding is not important since we are just increasing the exponent (= exact operation)
     mpfr_mul_2si(x.mpfr_ptr(), x.mpfr_srcptr(), exp, mpreal::get_default_rnd());
     return x;
 }
References exp(), mpfr::mpreal::get_default_rnd(), and x.
Referenced by mpfr::mpreal::fits_in_bits(), and scalbn().