Macaulay2 Engine: mpfr::exp2
exp2()
const mpreal mpfr::exp2 (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2274 of file mpreal.h.
 {   MPREAL_UNARY_MATH_FUNCTION_BODY(exp2 );    }
Referenced by SkewMultiplication::diff(), PolyRing::diff_term(), SkewMultiplication::divide(), GBRing::divide_exponents(), GBRing::exponent_syzygy(), PolyRing::get_coeff(), PolyRing::get_logical_coeff(), PolyRing::get_terms(), SkewMultiplication::mult_sign(), PolyRing::n_logical_terms(), GBinhom_comp::search(), gbA::spair_make(), gbA::spair_make_skew(), Matrix::support(), FreeAlgebra::support(), TEST(), and ResMonomialSorter::toMonomial().