Macaulay2 Engine: mpfr::isnan
isnan()
bool mpfr::isnan (const mpreal & op) inline
Definition at line 1719 of file mpreal.h.
{    return (mpfr_nan_p    (op.mpfr_srcptr()) != 0);    }
Referenced by hypot(), hypot(), operator<(), operator<(), operator<(), operator<(), operator<(), operator<(), operator<=(), operator<=(), operator<=(), operator<=(), operator<=(), operator<=(), operator==(), operator==(), operator==(), operator==(), operator==(), operator==(), operator>(), operator>(), operator>(), operator>(), operator>(), operator>(), operator>=(), operator>=(), operator>=(), operator>=(), operator>=(), and operator>=().