Macaulay2 Engine: mpfr::pow
pow() [34/50]
const mpreal mpfr::pow (const mpreal & a, const unsigned int b, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2937 of file mpreal.h.
{
    return pow(a,static_cast<unsigned long int>(b),rnd_mode);
}
References pow().
Referenced by pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), pow(), and pow().