Macaulay2 Engine: mpfr::sqrt
sqrt() [6/7]
const mpreal mpfr::sqrt (const unsigned int v, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2219 of file mpreal.h.
 {
     return sqrt(static_cast<unsigned long int>(v),rnd_mode);
 }
Referenced by M2::ARingCC::abs(), SLEvaluatorConcrete< RT >::computeNextNode(), PathTracker::evaluate_slpHxH(), PathTracker::evaluate_slpHxt(), complex::getmodulus(), hypot(), PathTracker::make(), mpfc_abs(), mpfc_sqrt(), sqrt(), and PathTracker::track().