Macaulay2 Engine: mpfr::rem
rem()
const mpreal mpfr::rem (const mpreal & x, const mpreal & y, mp_rnd_t rnd_mode = mpreal::get_default_rnd()) inline
Definition at line 2603 of file mpreal.h.
 {
     /*  R = rem(X,Y) if Y != 0, returns X - n * Y where n = trunc(X/Y). */
     return fmod(x, y, rnd_mode);
 }
Referenced by PolyRing::divide(), PolyRingQuotient::divide(), RingZZ::divide(), PolyRing::division_algorithm_with_laurent_variables(), GBRing::find_reduction_coeffs_ZZ(), HermiteComputation::gb_reduce(), PolyRing::gcd(), PolyRing::quotient(), RingZZ::quotient(), QRingInfo_ZZ::reduce_lead_term_ZZ(), PolyRing::remainder(), RingZZ::remainder(), and PolyRing::remainderAndQuotient().