Macaulay2 Engine: mpfr::sum
sum()
const mpreal mpfr::sum (const mpreal tab[], const unsigned long int n, int & status, mp_rnd_t mode = mpreal::get_default_rnd()) inline
Definition at line 2575 of file mpreal.h.
 {
     mpfr_srcptr *p = new mpfr_srcptr[n];
     for (unsigned long int  i = 0; i < n; i++)
         p[i] = tab[i].mpfr_srcptr();
     mpreal x;
     status = mpfr_sum(x.mpfr_ptr(), (mpfr_ptr*)p, n, mode);
     delete [] p;
     return x;
 }
Referenced by ResolutionComputation::betti_display(), BettiDisplay::betti_display(), ntuple::degree(), GBWeight::exponents_weight(), WeylAlgebra::gbvector_weyl_diff(), iquotient_and_sum(), MonomialOrderings::join(), MonomialInfo::monomial_weight(), MonomialOrderings::product(), rawJoinMonomialOrdering(), rawNonTermOrderVariables(), rawNumberOfInvertibleVariables(), rawNumberOfVariables(), rawProductMonomialOrdering(), hilb_comp::recurse(), signdivide(), varpower_monomials::simple_degree(), ntuple_monomials::simple_degree(), res_varpower_monomials::simple_degree(), OverlapTable::size(), TEST(), varpower_monomials::weight(), ntuple::weight(), ntuple_monomials::weight(), res_varpower_monomials::weight(), and WeylAlgebra::weyl_diff().