Macaulay2 Engine: mpfr::isEqualFuzzy
isEqualFuzzy() [1/2]
bool mpfr::isEqualFuzzy (const mpreal & a, const mpreal & b) inline
Definition at line 2103 of file mpreal.h.
 {
     return isEqualFuzzy(a, b, machine_epsilon((max)(1, (min)(abs(a), abs(b)))));
 }
References abs(), isEqualFuzzy(), machine_epsilon(), max(), and min().