Macaulay2 Engine: mpfr::exp
exp()
const mpreal mpfr::exp (const mpreal & x, mp_rnd_t r = mpreal::get_default_rnd()) inline
Definition at line 2273 of file mpreal.h.
 {   MPREAL_UNARY_MATH_FUNCTION_BODY(exp  );    }
Referenced by DRing::add_term(), DPoly::add_term(), alg1_reduce_exp(), all_have_pure_powers(), AssociatedPrimes::ass_prime_generator(), BRPSfromMatrix(), BRPStoMatrix(), hilb_comp::coeff_of(), coeffs_of_vec(), PolyRing::degree_of_var(), WeylAlgebra::diff_coefficients(), SchurRing::dimension(), PolyRing::divide_by_expvector(), PolyRingQuotient::divide_by_expvector(), PolyRing::divide_by_var(), M2::ARingGFGivaro::elem_text_out(), SkewMultiplication::exp_is_zero(), exponents_show(), exponentsToLong(), WeylAlgebra::extractCommutativePart(), WeylAlgebra::extractDerivativePart(), MonomialIdeal::find_all_divisors(), F4MonomialLookupTableT< Key >::find_all_divisors1(), ResF4MonomialLookupTableT< Key >::find_all_divisors1(), res2_comp::find_divisor(), GBKernelComputation::find_divisor(), MonomialTable::find_divisor(), MonomialTable::find_divisors(), MonomialTable::find_exact(), MonomialTableZZ::find_exact(), MonomialTableZZ::find_exact_monomial(), MonomialTableZZ::find_monomial_divisors(), F4MonomialLookupTableT< Key >::find_one_divisor1(), ResF4MonomialLookupTableT< Key >::find_one_divisor1(), res2_comp::find_ring_divisor(), GBKernelComputation::find_ring_divisor(), res_comp::find_ring_divisor(), MonomialTableZZ::find_smallest_coeff_divisor(), MonomialTableZZ::find_term_divisors(), frexp(), FrobbyAlexanderDual(), Monoid::from_expvector(), ResF4toM2Interface::from_M2_vec(), F4toM2Interface::from_M2_vec(), SchurRing::from_partition(), PolyRing::fromSmallIntegerCoefficients(), GBRingSkew::GBRingSkew(), GBRing::gbvector_term_exponents(), WeylAlgebra::gbvector_weyl_diff(), PolyRing::get_coeff(), PolyRing::get_logical_coeff(), PolyRing::get_part(), RingElement::getSmallIntegerCoefficients(), PolyRing::homogenize(), IM2_FreeModule_get_degrees(), IM2_RingElement_term(), MonomialTable::insert(), MonomialTableZZ::insert(), F4GB::insert_gb_element(), MonomialTableZZ::is_strong_member(), MonomialTableZZ::is_weak_member(), KBasis::KBasis(), ldexp(), PolyRing::lead_logical_exponents(), RingElement::lead_monom(), PolyRing::lift(), PolyRing::list_form(), longToExponents(), PolyRing::make_logical_term(), PolyRingQuotient::make_logical_term(), binomial_ring::make_monomial(), ExponentVector< E, OC >::mask(), matrixToStream(), RingZZ::mod_ui(), PolyRing::monomial_divisor(), PolyRingQuotient::monomial_divisor(), monomial_mask(), Matrix::monomials(), WeylAlgebra::multinomial(), res2_comp::new_pairs(), res_comp::new_pairs(), GF::power(), GF::promote(), PolyRing::promote(), M2::ARingGFGivaro::promote(), QRingInfo_field::QRingInfo_field(), QRingInfo_ZZ::QRingInfo_ZZ(), GF::random(), Z_mod::random(), reduce_exp(), GBRing::reduce_lead_term_heap(), M2::ARingGFGivaro::representationToM2Array(), scalbn(), GBinhom_comp::search(), MonomialIdeal::search(), MonomialIdeal::search_expvector(), FreeModule::select_by_degrees(), PolyRing::setNegativeExponentMonomial(), MonomialTableZZ::show_weak(), signdivide(), res_comp::skeleton_pairs(), SkewMultiplication::skew_degree(), SkewMultiplication::skew_vars(), Matrix::support(), FreeAlgebra::support(), TEST(), ResF4toM2Interface::to_M2_freemodule(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), SchurRing::to_partition(), to_prime_ideal(), ResMonomialSorter::toMonomial(), Matrix::top_coefficients(), Tower::translate(), DPolyTraverser::traverse(), DPolyTraverser::traverse1(), PolyRing::vec_coefficient_of_var(), Ring::vec_divide_by_expvector(), Ring::vec_remove_monomial_factors(), PolyRing::vec_top_coefficient(), TowerEvaluator::viewTerm(), WeylAlgebra::weyl_diff(), and GBKernelComputation::wipe_unneeded_terms().