Macaulay2 Engine: mpfr::bits2digits
bits2digits()
int mpfr::bits2digits (mp_prec_t b) inline
Definition at line 1944 of file mpreal.h.
 {
     const double LOG10_2 = 0.30102999566398119;
     return int(std::floor( b * LOG10_2 ));
 }
References floor().
Referenced by std::numeric_limits< mpfr::mpreal >::digits10(), and mpfr::mpreal::toString().