Macaulay2 Engine: mpfr::min
min()
const mpreal() mpfr::min (const mpreal & x, const mpreal & y)
Definition at line 2767 of file mpreal.h.
 {    return (y<x?y:x);       }
References x.
Referenced by ExponentList< E, L >::compare(), DMatLUinPlace< RT >::computeLU(), cond_number_via_svd(), std::numeric_limits< mpfr::mpreal >::denorm_min(), ExponentList< E, L >::gcd(), getmoremem_atomic(), isEqualFuzzy(), Lapack::least_squares(), Lapack::least_squares_deficient(), Lapack::LU(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), SchreyerFrame::minimalBettiNumbers(), norm_of_inverse_via_svd(), Lapack::QR(), BettiDisplay::resize(), LUUtil< RT >::setUpperLower(), DMatLinAlg< RingType >::setUpperLower(), Matrix::sub_matrix(), Lapack::SVD(), Lapack::SVD_divide_conquer(), and TEST().