Macaulay2 Engine: hilb_comp::step
step()
int hilb_comp::step () private
Definition at line 446 of file hilb.cpp.
 {
   nsteps++;
   if (current->i == current->first_sum)
     {
       current->h0 = current->h1;
       current->h1 = R->from_long(1);
     }
   if (current->i >= 0)
     {
       // If the i th monomial ideal is a 'special case', simply compute its
       // value
       // Otherwise, find pivot, and quotient/sum creating next level down
       // (possibly make new hilb_step, and increment max_depth if needed)
       // and set current = current->down
       do_ideal(current->monids[current->i]);  // consumes this monomial ideal
     }
   else
     {
       // At this point, all Hilbert functions at this level have been
       // computed, so add the values, and place one step up
       R->add_to(current->h0, current->h1);
       ring_elem f = current->h0;
       current->h0 = R->from_long(0);
       current->h1 = R->from_long(0);
       current->monids.clear();
       if (current->up == NULL)
         {
           if (input_mat)
             {
               ring_elem tmp =
                   R->make_flat_term(one, input_mat->rows()->degree(this_comp));
               R->mult_to(f, tmp);
               R->remove(tmp);
             }
           R->add_to(result_poincare, f);
           this_comp++;
           // Now check if we have any more components
           if (this_comp >= n_components) return COMP_DONE;
           // otherwise go on to the next component:
           next_monideal();
           return COMP_COMPUTING;
         }
       current = current->up;
       R->mult_to(current->h1, f);
       current->i--;
       R->remove(f);
     }
   return COMP_COMPUTING;
 }
References Ring::add_to(), COMP_COMPUTING, COMP_DONE, current, FreeModule::degree(), do_ideal(), hilb_step::first_sum, Ring::from_long(), hilb_step::h0, hilb_step::h1, hilb_step::i, input_mat, PolynomialRing::make_flat_term(), hilb_step::monids, Ring::mult_to(), n_components, next_monideal(), nsteps, one, R, Ring::remove(), result_poincare, Matrix::rows(), this_comp, and hilb_step::up.
Referenced by calc().