Macaulay2 Engine: hilb_comp::recurse
recurse()
void hilb_comp::recurse (MonomialIdeal *& I, const_varpower pivot_vp) private
Definition at line 500 of file hilb.cpp.
 {
   depth++;
   if (depth > maxdepth) maxdepth = depth;
   nrecurse++;
   if (current->down == nullptr)
     {
       current->down = new hilb_step;  // MES: is this ok?
       current->down->up = current;
       current->down->down = nullptr;
     }
   current = current->down;
   current->h0 = R->from_long(0);
   M->degree_of_varpower(pivot_vp, LOCAL_deg1);
   current->h1 = R->make_flat_term(one, LOCAL_deg1);  // t^(deg vp)
   MonomialIdeal *quot, *sum;
   iquotient_and_sum(*I, pivot_vp, quot, sum, mi_stash);
   delete I;
   part_table.partition(sum, current->monids);
   current->first_sum = current->monids.size() - 1;
   part_table.partition(quot, current->monids);
   current->i = current->monids.size() - 1;
 }
References current, Monoid::degree_of_varpower(), depth, hilb_step::down, hilb_step::first_sum, Ring::from_long(), hilb_step::h0, hilb_step::h1, hilb_step::i, iquotient_and_sum(), LOCAL_deg1, M, PolynomialRing::make_flat_term(), maxdepth, mi_stash, hilb_step::monids, nrecurse, one, part_table, partition_table::partition(), R, mpfr::sum(), and hilb_step::up.
Referenced by do_ideal().