Macaulay2 Engine: hilb_comp::hilb_comp
hilb_comp() [2/2]
hilb_comp::hilb_comp (const PolynomialRing * R, const MonomialIdeal * I)
Definition at line 371 of file hilb.cpp.
     : S(I->get_ring()->cast_to_PolynomialRing()),
       R(RR),
       M(S->getMonoid()),
       D(S->degree_monoid()),
       mi_stash(new stash("hilb mi", sizeof(Nmi_node))),
       input_mat(nullptr),
       this_comp(0),
       n_components(1),
       current(nullptr),
       part_table(S->n_vars(), mi_stash)
 {
   assert(D == R->getMonoid());
   one = R->getCoefficientRing()->from_long(1);
   minus_one = R->getCoefficientRing()->from_long(-1);
   LOCAL_deg1 = D->make_one();
   result_poincare = R->from_long(0);
   nsteps = 0;
   maxdepth = 0;
   nideal = 0;
   nrecurse = 0;
   reset();
   MonomialIdeal *copyI = I->copy();
   part_table.partition(copyI, current->monids);
   current->i = current->monids.size() - 1;
   current->first_sum = current->i + 1;  // This part is not used at top level
 }
References MonomialIdeal::copy(), current, D, hilb_step::first_sum, Ring::from_long(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), hilb_step::i, LOCAL_deg1, Monoid::make_one(), maxdepth, minus_one, hilb_step::monids, nideal, nrecurse, nsteps, one, part_table, partition_table::partition(), R, reset(), and result_poincare.