Macaulay2 Engine: hilb_comp::do_ideal
do_ideal()
void hilb_comp::do_ideal (MonomialIdeal * I) private
Definition at line 524 of file hilb.cpp.
 {
   // This either will multiply to current->h1, or it will recurse down
   // Notice that one, and minus_one are global in this class.
   // LOCAL_deg1, LOCAL_vp are scratch variables defined in this class
   nideal++;
   ring_elem F = R->from_long(1);
   ring_elem G;
   int len = I->size();
   if (len <= 2)
     {
       // len==1: set F to be 1 - t^(deg m), where m = this one element
       // len==2: set F to be 1 - t^(deg m1) - t^(deg m2) + t^(deg lcm(m1,m2))
       M->degree_of_varpower(I->first_elem(), LOCAL_deg1);
       G = R->make_flat_term(minus_one, LOCAL_deg1);
       R->add_to(F, G);
       if (len == 2)
         {
           M->degree_of_varpower(I->second_elem(), LOCAL_deg1);
           G = R->make_flat_term(minus_one, LOCAL_deg1);
           R->add_to(F, G);
           varpower::lcm(I->first_elem(), I->second_elem(), LOCAL_vp);
           M->degree_of_varpower(LOCAL_vp.data(), LOCAL_deg1);
           G = R->make_flat_term(one, LOCAL_deg1);
           R->add_to(F, G);
         }
       delete I;
     }
   else
     {
       int npure;
       gc_vector<int> pivot;
       gc_vector<int> pure_a(I->topvar() + 1);
       exponents_t pure = pure_a.data();
       if (!find_pivot(*I, npure, pure, pivot))
         {
           // set F to be product(1-t^(deg x_i^e_i))
           //              - t^(deg pivot) product((1-t^(deg x_i^(e_i - m_i)))
           // where e_i >= 1 is the smallest number s.t. x_i^(e_i) is in I,
           // and m_i = exponent of x_i in pivot element (always < e_i).
           M->degree_of_varpower(pivot.data(), LOCAL_deg1);
           G = R->make_flat_term(one, LOCAL_deg1);
           for (index_varpower i = pivot.data(); i.valid(); ++i)
             if (pure[i.var()] != -1)
               {
                 ring_elem H = R->from_long(1);
                 D->power(M->degree_of_var(i.var()), pure[i.var()], LOCAL_deg1);
                 ring_elem tmp = R->make_flat_term(minus_one, LOCAL_deg1);
                 R->add_to(H, tmp);
                 R->mult_to(F, H);
                 R->remove(H);
                 H = R->from_long(1);
                 D->power(M->degree_of_var(i.var()),
                          pure[i.var()] - i.exponent(),
                          LOCAL_deg1);
                 tmp = R->make_flat_term(minus_one, LOCAL_deg1);
                 R->add_to(H, tmp);
                 R->mult_to(G, H);
                 R->remove(H);
               }
           R->subtract_to(F, G);
           delete I;
         }
       else
         {
           // This is the one case in which we recurse down
           R->remove(F);
           recurse(I, pivot.data());
           return;
         }
     }
   R->mult_to(current->h1, F);
   R->remove(F);
   current->i--;
 }
References Ring::add_to(), current, D, Monoid::degree_of_var(), Monoid::degree_of_varpower(), find_pivot(), MonomialIdeal::first_elem(), Ring::from_long(), hilb_step::h1, hilb_step::i, ExponentList< E, L >::lcm(), LOCAL_deg1, LOCAL_vp, M, PolynomialRing::make_flat_term(), minus_one, Ring::mult_to(), nideal, one, Monoid::power(), R, recurse(), Ring::remove(), MonomialIdeal::second_elem(), MonomialIdeal::size(), Ring::subtract_to(), MonomialIdeal::topvar(), and ExponentListIterator< E, L >::valid().
Referenced by step().