Macaulay2 Engine: hilb_comp::coeff_of
coeff_of()
int hilb_comp::coeff_of (const RingElement * h, int deg) static
Definition at line 704 of file hilb.cpp.
 {
   // This is a bit of a kludge of a routine.  The idea is to loop through
   // all the terms of the polynomial h, expand out the exponent, and to add
   // up the small integer values of the coefficients of those that have
   // exp[0]=deg.
   const PolynomialRing *P = h->get_ring()->cast_to_PolynomialRing();
   exponents_t exp = newarray_atomic(int, P->n_vars());
   int result = 0;
   for (Nterm& f : h->get_value())
     {
       P->getMonoid()->to_expvector(f.monom, exp);
       if (exp[0] < deg)
         {
           ERROR("incorrect Hilbert function given");
           fprintf(
               stderr,
               "internal error: incorrect Hilbert function given, aborting\n");
           abort();
         }
       else if (exp[0] == deg)
         {
           std::pair<bool, long> res =
               P->getCoefficientRing()->coerceToLongInteger(f.coeff);
           assert(res.first &&
                  std::abs(res.second) < std::numeric_limits<int>::max());
           int n = static_cast<int>(res.second);
           result += n;
         }
     }
   freemem(exp);
   return result;
 }
References abs, Ring::cast_to_PolynomialRing(), Ring::coerceToLongInteger(), ERROR(), mpfr::exp(), freemem(), RingElement::get_ring(), RingElement::get_value(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), max, PolynomialRing::n_vars(), newarray_atomic, and Monoid::to_expvector().
Referenced by gbA::do_computation(), HilbertController::setDegree(), and GB_comp::start_computation().