Macaulay2 Engine: hilb_comp::hilbertNumerator
hilbertNumerator() [3/3]
RingElement * hilb_comp::hilbertNumerator (const MonomialIdeal * I) static
Definition at line 689 of file hilb.cpp.
 {
   const PolynomialRing *P = I->get_ring()->get_degree_ring();
   if (P == 0) return 0;
   hilb_comp *hf = new hilb_comp(P, I);
   int retval = hf->calc(-1);
   if (retval != COMP_DONE) return 0;
   RingElement *result = hf->value();
   delete hf;
   return result;
 }
References calc(), COMP_DONE, Ring::get_degree_ring(), MonomialIdeal::get_ring(), hilb_comp(), and value().