Macaulay2 Engine: hilb_comp::~hilb_comp
~hilb_comp()
hilb_comp::~hilb_comp ()
Definition at line 401 of file hilb.cpp.
 {
   // free 'current' (which is most of the stuff here...)
   while (current != nullptr)
     {
       hilb_step *p = current;
       current = current->down;
       R->remove(p->h0);
       R->remove(p->h1);
       for (int i = 0; i < p->monids.size(); i++) delete p->monids[i];
       delete p;
     }
   R->remove(result_poincare);
   R->getCoefficientRing()->remove(one);
   R->getCoefficientRing()->remove(minus_one);
   D->remove(LOCAL_deg1);
   delete mi_stash;
 }
References current, D, hilb_step::down, PolynomialRing::getCoefficientRing(), LOCAL_deg1, mi_stash, minus_one, one, p, R, Monoid::remove(), Ring::remove(), and result_poincare.