Macaulay2 Engine: hilb_comp::reset
reset()
void hilb_comp::reset ()
Definition at line 325 of file hilb.cpp.
 {
   depth = 0;
   if (current == nullptr)
     {
       current = new hilb_step;
       current->up = current->down = nullptr;
       current->h0 = R->from_long(0);
       current->h1 = R->from_long(0);
     }
   else
     while (current->up != nullptr) current = current->up;
   R->remove(current->h0);  // This line should not be needed...
   R->remove(current->h1);
   current->h0 = R->from_long(0);  // This top level h0 is not used
   current->h1 = R->from_long(1);
 }
References current, depth, hilb_step::down, Ring::from_long(), hilb_step::h0, hilb_step::h1, R, Ring::remove(), and hilb_step::up.
Referenced by hilb_comp(), and next_monideal().