Macaulay2 Engine: hilb_comp::value
value()
RingElement * hilb_comp::value ()
Definition at line 607 of file hilb.cpp.
 {
   if (!is_done())
     {
       ERROR("Hilbert function computation not complete");
       return nullptr;
     }
   RingElement *result = RingElement::make_raw(R, R->copy(result_poincare));
   return result;
 }
References Ring::copy(), ERROR(), is_done(), RingElement::make_raw(), R, and result_poincare.
Referenced by hilbertNumerator().