Macaulay2 Engine: hilb_comp::calc
calc()
int hilb_comp::calc (int nsteps)
Definition at line 422 of file hilb.cpp.
 {
   if (n_components == 0) return COMP_DONE;
   if (n_steps >= 0)
     {
       int calc_nsteps = nsteps + n_steps;
       while (calc_nsteps-- > 0)
         {
           int result = step();
           if (result == COMP_DONE) return COMP_DONE;
           if (system_interrupted()) return COMP_INTERRUPTED;
         }
       return COMP_DONE_STEPS;
     }
   else
     for (;;)
       {
         int result = step();
         if (result == COMP_DONE) return COMP_DONE;
         if (system_interrupted()) return COMP_INTERRUPTED;
       }
 }
References COMP_DONE, COMP_DONE_STEPS, COMP_INTERRUPTED, n_components, nsteps, step(), and system_interrupted().
Referenced by hilbertNumerator().