Macaulay2 Engine: hilb_comp::hilb_comp
hilb_comp() [1/2]
hilb_comp::hilb_comp (const PolynomialRing * R, const Matrix * M)
Definition at line 343 of file hilb.cpp.
     : S(m->get_ring()->cast_to_PolynomialRing()),
       R(RR),
       M(S->getMonoid()),
       D(S->degree_monoid()),
       mi_stash(new stash("hilb mi", sizeof(Nmi_node))),
       input_mat(m),
       this_comp(0),
       n_components(m->n_rows()),
       current(NULL),
       part_table(S->n_vars(), mi_stash)
 {
   assert(D == R->getMonoid());
   one = R->getCoefficientRing()->from_long(1);
   minus_one = R->getCoefficientRing()->from_long(-1);
   LOCAL_deg1 = D->make_one();
   result_poincare = R->from_long(0);
   nsteps = 0;
   maxdepth = 0;
   nideal = 0;
   nrecurse = 0;
   // Collect the 'this_comp' monideal of the input matrix
   // Set up the computation for that
   next_monideal();
 }
References D, Ring::from_long(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), LOCAL_deg1, Monoid::make_one(), maxdepth, minus_one, next_monideal(), nideal, nrecurse, nsteps, one, R, and result_poincare.
Referenced by hilbertNumerator().