Macaulay2 Engine: hilb_comp::next_monideal
next_monideal()
void hilb_comp::next_monideal ()
Definition at line 314 of file hilb.cpp.
 {
   reset();
   MonomialIdeal *I = input_mat->make_monideal(this_comp);
   // The above line adds the squares of the variables which are skew variables
   // into the monomial ideal.  This allows Hilbert functions of such rings
   // to be computed as usual.
   part_table.partition(I, current->monids);
   current->i = current->monids.size() - 1;
   current->first_sum = current->i + 1;  // This part is not used at top level
 }
References current, hilb_step::first_sum, hilb_step::i, input_mat, Matrix::make_monideal(), hilb_step::monids, part_table, partition_table::partition(), reset(), and this_comp.
Referenced by hilb_comp(), and step().