Macaulay2 Engine: hilb_comp::hilbertNumerator
hilbertNumerator() [2/3]
RingElement * hilb_comp::hilbertNumerator (const Matrix * M) static
Definition at line 650 of file hilb.cpp.
 {
   const PolynomialRing *P = M->get_ring()->get_degree_ring();
   if (P == 0) return 0;
   hilb_comp *hf = new hilb_comp(P, M);
   int retval = hf->calc(-1);
   if (retval != COMP_DONE) return 0;
   RingElement *result = hf->value();
   delete hf;
   return result;
 }
References calc(), COMP_DONE, Monoid::get_degree_ring(), hilb_comp(), M, and value().
Referenced by gbA::do_computation(), gb2_comp::hilbertNumerator(), hilbertNumerator(), IM2_Matrix_Hilbert(), IM2_MonomialIdeal_Hilbert(), HilbertController::recomputeHilbertFunction(), and gb2_comp::setup().