Macaulay2 Engine: IM2_Matrix_concat
IM2_Matrix_concat()
const Matrix* IM2_Matrix_concat (const engine_RawMatrixArray Ms)
Definition at line 262 of file matrix.cpp.
 {
   try
     {
       unsigned int n = Ms->len;
       if (n == 0)
         {
           ERROR("matrix concat: expects at least one matrix");
           return nullptr;
         }
       const FreeModule *F = Ms->array[0]->rows();
       const Ring *R = F->get_ring();
       MatrixConstructor mat(Ms->array[0]->rows(), 0);
       int next = 0;
       for (unsigned int i = 0; i < n; i++)
         {
           const Matrix *M = Ms->array[i];
           if (R != M->get_ring())
             {
               ERROR("matrix concat: different base rings");
               return nullptr;
             }
           if (F->rank() != M->n_rows())
             {
               ERROR("matrix concat: row sizes are not equal");
               return nullptr;
             }
           for (int j = 0; j < M->n_cols(); j++)
             {
               mat.append(R->copy_vec(M->elem(j)));
               mat.set_column_degree(next++, M->cols()->degree(j));
             }
         }
       return mat.to_matrix();
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References MatrixConstructor::append(), Matrix::cols(), Ring::copy_vec(), FreeModule::degree(), Matrix::elem(), ERROR(), FreeModule::get_ring(), Matrix::get_ring(), Matrix::n_cols(), Matrix::n_rows(), FreeModule::rank(), MatrixConstructor::set_column_degree(), and MatrixConstructor::to_matrix().