Macaulay2 Engine: rawMatrixReadMsolveFile
rawMatrixReadMsolveFile()
const Matrix* rawMatrixReadMsolveFile (const Ring * R, M2_string filename)
Definition at line 228 of file matrix.cpp.
 {
   try
     {
       std::string str = string_M2_to_std(filename);
       auto Fs = parseMsolveFile(str);
       return toMatrix(R->make_FreeModule(1), Fs);
     } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
     }
 }
References ERROR(), Ring::make_FreeModule(), parseMsolveFile(), string_M2_to_std(), and toMatrix().