Macaulay2 Engine: rawKoszulMonomials
rawKoszulMonomials()
const Matrix* rawKoszulMonomials (int nskew, const Matrix * M, const Matrix * N)
Definition at line 420 of file matrix.cpp.
 {
   try
     {
 #ifdef DEVELOPMENT
 #warning "check with 0.9.2 about what this should even do"
 #endif
       if (M->get_ring() != N->get_ring())
         {
           ERROR("expected same ring");
           return 0;
         }
       return Matrix::koszul_monomials(nskew, M, N);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References ERROR(), Matrix::get_ring(), and Matrix::koszul_monomials().