Macaulay2 Engine: IM2_Matrix_direct_sum
IM2_Matrix_direct_sum()
const Matrix* IM2_Matrix_direct_sum (const engine_RawMatrixArray Ms)
Definition at line 303 of file matrix.cpp.
 {
   try
     {
       // Check that the matrices all have the same ring, and that there is
       // at least one matrix.
       unsigned int n = Ms->len;
       if (n == 0)
         {
           ERROR("matrix direct sum: expects at least one matrix");
           return nullptr;
         }
       const Matrix *result = Ms->array[0];
       const Ring *R = result->get_ring();
       for (unsigned int i = 1; i < n; i++)
         if (R != Ms->array[i]->get_ring())
           {
             ERROR("matrix direct sum: different base rings");
             return nullptr;
           }
       for (unsigned int i = 1; i < n; i++)
         result = result->direct_sum(Ms->array[i]);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Matrix::direct_sum(), ERROR(), and Matrix::get_ring().