Macaulay2 Engine: SymmMatrix::SymmMatrix
SymmMatrix()
SymmMatrix::SymmMatrix (const Matrix * m0, int p) inline private
Definition at line 45 of file matrix-symm.cpp.
       : symm1_next(0), R(m0->get_ring()), ncols(m0->n_cols()), m(m0), result()
   {
     const FreeModule *Fp = m0->rows()->symm(p);
     const FreeModule *Gp = m0->cols()->symm(p);
     monomial dp = R->degree_monoid()->make_new(m->degree_shift());
     R->degree_monoid()->power(dp, p, dp);
     result = MatrixConstructor(Fp, Gp, dp);
     if (p >= 0)
       {
         vec f = R->e_sub_i(0);
         symm1(f, 0, p);  // consumes f
       }
   }
References Matrix::cols(), Ring::degree_monoid(), Matrix::degree_shift(), Ring::e_sub_i(), m, Monoid::make_new(), p, Monoid::power(), R, result, Matrix::rows(), FreeModule::symm(), and symm1().