Macaulay2 Engine: SymmMatrix::symm1
symm1()
void SymmMatrix::symm1 (vec f, int lastn, int pow) inline private
Definition at line 26 of file matrix-symm.cpp.
   {
     if (pow == 0)
       result.set_column(symm1_next++, f);
     else
       {
         for (int i = lastn; i < ncols; i++)
           {
             ring_elem r = m->elem(0, i);
             vec h = R->copy_vec(f);
             R->mult_vec_to(h, r, false);
             symm1(h, i, pow - 1);
           }
         R->remove_vec(f);
       }
   }
References Ring::copy_vec(), Matrix::elem(), m, Ring::mult_vec_to(), ncols, mpfr::pow(), R, Ring::remove_vec(), result, MatrixConstructor::set_column(), and symm1_next.
Referenced by SymmMatrix().