Macaulay2 Engine: TEST
TEST() [4/4]
TEST (MatrixIO , readPolys)
Definition at line 196 of file MatrixIOTest.cpp.
 {
   std::string contents = R"(1*x^1+2*y^1+2*z^1+1235952426
 1*y^1*z^1+494380972*z^2+370785728*y^1+247190485*z^1
 1*y^2+988761941*z^2+741571456*y^1+494380971*z^1
 1*z^3+924021576*z^2+700373042*y^1+653289140*z^1
 )";
   std::vector<std::string> varnames = {"x", "y", "z"};
   auto result = parseBasicPolyListFromString(contents, varnames);
   EXPECT_TRUE(result.size() == 4);
   const PolynomialRing* R = simplePolynomialRing(1235952427, varnames);
   const Matrix* M = toMatrix(R->make_FreeModule(1), result);
   EXPECT_TRUE(M->n_rows() == 1);
   EXPECT_TRUE(M->n_cols() == 4);
   buffer o;
   M->text_out(o);
   std::cout << o.str() << std::endl;
 }
References Ring::make_FreeModule(), Matrix::n_cols(), Matrix::n_rows(), parseBasicPolyListFromString(), simplePolynomialRing(), buffer::str(), Matrix::text_out(), and toMatrix().