Macaulay2 Engine: TEST
TEST() [1/4]
TEST (MatrixIO , readMsolve)
Definition at line 71 of file MatrixIOTest.cpp.
 {
   std::string filename { EXAMPLE_DIR"eg2-gb.ms" };
   std::string contents = R"(#Reduced Groebner basis data
 #---
 #field characteristic: 1235952427
 #variable order:       x, y, z
 #monomial order:       graded reverse lexicographical
 #length of basis:      4 elements sorted by increasing leading monomials
 #---
 [1*x^1+2*y^1+2*z^1+1235952426,
 1*y^1*z^1+494380972*z^2+370785728*y^1+247190485*z^1,
 1*y^2+988761941*z^2+741571456*y^1+494380971*z^1,
 1*z^3+924021576*z^2+700373042*y^1+653289140*z^1]:
 )";
   auto result = parseMsolveFromString(contents);
   std::cout << "bytes used for poly list: " << bytesUsed(result) << '\n';
   EXPECT_TRUE(result.size() == 4);
   const PolynomialRing* R = simplePolynomialRing(1235952427, {"x", "y", "z"});
   const Matrix* M = toMatrix(R->make_FreeModule(1), result);
   EXPECT_TRUE(M->n_rows() == 1);
   EXPECT_TRUE(M->n_cols() == 4);
 }
References bytesUsed(), EXAMPLE_DIR, Ring::make_FreeModule(), parseMsolveFromString(), simplePolynomialRing(), and toMatrix().