Macaulay2 Engine: ResPolynomialConstructor::setPoly
setPoly()
void ResPolynomialConstructor::setPoly (ResPolynomial & result) inline
Definition at line 118 of file res-poly-ring.hpp.
   {
     ncalls++;
     result.len = static_cast<int>(mRing.vectorArithmetic().size(coeffs));
     std::swap(result.coeffs, coeffs);
     result.monoms.resize(result.len * mRing.monoid().max_monomial_size());
     // copy monoms: not pointers, actual monoms
     res_monomial_word* monomptr = result.monoms.data();
     for (int i = 0; i < result.len; i++)
       {
         mRing.monoid().copy(monoms[i], monomptr);
         monomptr += mRing.monoid().monomial_size(monoms[i]);
       }
   }
References ResPolynomial::coeffs, coeffs, ResMonoidDense::copy(), ResPolynomial::len, ResMonoidDense::max_monomial_size(), ResPolyRing::monoid(), ResMonoidDense::monomial_size(), ResPolynomial::monoms, monoms, mRing, ncalls, VectorArithmetic::size(), swap, and ResPolyRing::vectorArithmetic().
Referenced by F4Res::gaussReduceRow().