Macaulay2 Engine: ResPolynomialConstructor::appendMonicTerm
appendMonicTerm()
void ResPolynomialConstructor::appendMonicTerm (res_packed_monomial monom) inline
Definition at line 106 of file res-poly-ring.hpp.
   {
     monoms.push_back(monom);  // a pointer
     mRing.vectorArithmetic().pushBackOne(coeffs);
   }
References coeffs, monoms, mRing, VectorArithmetic::pushBackOne(), and ResPolyRing::vectorArithmetic().
Referenced by F4Res::gaussReduceRow().