Macaulay2 Engine: res2_comp::s_pair
s_pair()
res2term * res2_comp::s_pair (res2term * fsyz) const private
Definition at line 1110 of file res-a0.cpp.
 {
   res2term *result = NULL;
   monomial si = M->make_one();
   while (f != NULL)
     {
       M->divide(f->monom, f->comp->syz->monom, si);
       res2term *h = R->mult_by_term(f->comp->syz, f->coeff, si);
       R->add_to(result, h);
       //      R->subtract_multiple_to(result, f->coeff, si, f->comp->syz);
       f = f->next;
     }
   M->remove(si);
   return result;
 }
References res2_poly::add_to(), res2term::coeff, res2term::comp, Monoid::divide(), M, Monoid::make_one(), res2term::monom, res2_poly::mult_by_term(), res2term::next, R, Monoid::remove(), and res2_pair::syz.
Referenced by handle_pair(), handle_pair_by_degree(), and handle_pair_by_level().