Macaulay2 Engine: res2_comp::multi_degree
multi_degree()
void res2_comp::multi_degree (const res2_pair * q, int * result) const private
Definition at line 701 of file res-a0.cpp.
 {
   const res2_pair *q;
   M->multi_degree(p->syz->monom, deg);
   for (q = p; q->level != 0; q = q->syz->comp)
     ;
   get_ring()->degree_monoid()->mult(deg, generator_matrix->rows()->degree(q->me), deg);
 }
References res2term::comp, FreeModule::degree(), Ring::degree_monoid(), generator_matrix, get_ring(), res2_pair::level, M, res2_pair::me, Monoid::mult(), Monoid::multi_degree(), p, Matrix::rows(), and res2_pair::syz.
Referenced by free_of(), and minimal_free_of().