Macaulay2 Engine: res2_comp::betti_minimal
betti_minimal()
M2_arrayint res2_comp::betti_minimal () const
Definition at line 1855 of file res-a0.cpp.
 {
   int lo = lodegree;
   int hi = lo + hidegree;
   int len = resn.size() - 1;
   int *bettis;
   betti_init(lo, hi, len, bettis);
   for (int lev = 0; lev <= len; lev++)
     {
       for (res2_pair *p = resn[lev]->pairs; p != NULL; p = p->next)
         {
           if (p->syz_type != SYZ2_MINIMAL) continue;
           int d = p->degree;
           bettis[lev + (len + 1) * d]++;
         }
     }
   M2_arrayint result = betti_make(lo, hi, len, bettis);
   freemem(bettis);
   return result;
 }
References ResolutionComputation::betti_init(), ResolutionComputation::betti_make(), freemem(), hidegree, lodegree, p, resn, and SYZ2_MINIMAL.
Referenced by get_betti(), and text_out().