Macaulay2 Engine: res2_comp::remove_res2_level
remove_res2_level()
void res2_comp::remove_res2_level (res2_level * lev) private
Definition at line 578 of file res-a0.cpp.
 {
   if (lev == NULL) return;
   while (lev->pairs != NULL)
     {
       res2_pair *p = lev->pairs;
       lev->pairs = p->next;
       remove_res2_pair(p);
     }
   freemem(lev);
 }
References freemem(), p, res2_level::pairs, and remove_res2_pair().
Referenced by ~res2_comp().