Macaulay2 Engine: res2_comp::reduce_minimal
reduce_minimal()
void res2_comp::reduce_minimal (int x, res2term *& f, gc_vector< res2_pair * > & elems, gc_vector< res2term * > & stripped) const private
Definition at line 2091 of file res-a0.cpp.
 {
   // Reduce any components of 'f' that correspond to non minimal syzygies.
   monomial MINIMAL_mon = ALLOCATE_MONOMIAL(monom_size);
   const res2term *tm;
   for (int i = x - 1; i >= 0; i--)
     {
       res2_pair *p = elems[i];
       if (p->syz_type == SYZ2_NOT_MINIMAL)
         while ((tm = R->component_occurs_in(p->pivot_term->comp, f)) != nullptr)
           {
             // Subtract the proper multiple to f.  f = ... + c m e_y + ...
             // and                                 p = ... + d n e_y
             // where n|m.  So we want to compute f -= c/d m/n p.
             ring_elem c =
                 K->divide(tm->coeff, p->pivot_term->coeff);  // exact division
             // MES: is the following line actually needed?
             M->divide(tm->monom, p->pivot_term->monom, MINIMAL_mon);
             if (stripped[p->me] == nullptr) stripped[p->me] = R->strip(p->syz);
             R->subtract_multiple_to(f, c, MINIMAL_mon, stripped[p->me]);
           }
     }
 }
References ALLOCATE_MONOMIAL, res2term::coeff, res2_poly::component_occurs_in(), Ring::divide(), Monoid::divide(), K, M, res2term::monom, monom_size, p, R, res2_poly::strip(), res2_poly::subtract_multiple_to(), SYZ2_NOT_MINIMAL, and x.
Referenced by make_minimal().