Macaulay2 Engine: res2_comp::betti_skeleton
betti_skeleton()
M2_arrayint res2_comp::betti_skeleton () const
Definition at line 1816 of file res-a0.cpp.
 {
   int lo = lodegree;
   int hi = lo + hidegree;
   int len = resn.size() - 1;
   BettiDisplay B(lo, hi, len);
   for (int lev = 0; lev <= len; lev++)
     {
       for (res2_pair *p = resn[lev]->pairs; p != nullptr; p = p->next)
         {
           int d = p->degree;
           B.entry(d, lev)++;
         }
     }
   return B.getBetti();
 }
References BettiDisplay::entry(), BettiDisplay::getBetti(), hidegree, lodegree, p, and resn.
Referenced by get_betti(), start_computation(), and text_out().