Macaulay2 Engine: res2_comp::new_pairs
new_pairs()
void res2_comp::new_pairs (res2_pair * p)
Definition at line 951 of file res-a0.cpp.
 {
   gc_vector<Bag*> elems;
   gc_vector<int> vp;  // This is 'p'.
   gc_vector<int> thisvp;
   monomial PAIRS_mon = ALLOCATE_MONOMIAL(monom_size);
   if (M2_gbTrace >= 10)
     {
       buffer o;
       o << "Computing pairs with first = " << p->pair_num << newline;
       emit(o.str());
     }
   M->divide(p->syz->monom, p->syz->comp->syz->monom, PAIRS_mon);
   M->to_varpower(PAIRS_mon, vp);
   // First add in syzygies arising from exterior variables
   // At the moment, there are none of this sort.
   if (P->is_skew_commutative())
     {
       exponents_t exp = newarray_atomic(int, M->n_vars());
       varpower::to_expvector(M->n_vars(), vp.data(), exp);
       int nskew = P->n_skew_commutative_vars();
       for (int v = 0; v < nskew; v++)
         {
           int w = P->skew_variable(v);
           if (exp[w] > 0)
             {
               thisvp.resize(0);
               varpower::var(w, 1, thisvp);
               Bag *b = new Bag(static_cast<void *>(0), thisvp);
               elems.push_back(b);
             }
         }
       freemem(exp);
     }
   // Second, add in syzygies arising from the base ring, if any
   // The baggage of each of these is NULL
   if (P->is_quotient_ring())
     {
       const MonomialIdeal *Rideal = P->get_quotient_monomials();
       for (Bag& a : *Rideal)
         {
           // Compute (P->quotient_ideal->monom : p->monom)
           // and place this into a varpower and Bag, placing
           // that into 'elems'
           thisvp.resize(0);
           varpower::quotient(a.monom().data(), vp.data(), thisvp);
           if (varpower::is_equal(a.monom().data(), thisvp.data()))
             continue;
           Bag *b = new Bag(static_cast<void *>(0), thisvp);
           elems.push_back(b);
         }
     }
   // Third, add in syzygies arising from previous elements of this same level
   // The baggage of each of these is their corresponding res2_pair
   MonomialIdeal *mi_orig = p->syz->comp->mi;
   for (Bag& a : *mi_orig)
     {
       Bag *b = new Bag(a.basis_ptr());
       varpower::quotient(a.monom().data(), vp.data(), b->monom());
       elems.push_back(b);
     }
   // Make this monomial ideal, and then run through each minimal generator
   // and insert into the proper degree. (Notice that sorting does not
   // need to be done yet: only once that degree is about to begin.
   mi_orig->insert_minimal(new Bag(p, vp));
   MonomialIdeal mi(P, elems);
   if (M2_gbTrace >= 11) mi.debug_out(1);
   monomial m = M->make_one();
   for (Bag& a : mi)
     {
       res2_pair *second = reinterpret_cast<res2_pair *>(a.basis_ptr());
       M->from_varpower(a.monom().data(), m);
       M->mult(m, p->syz->monom, m);
       res2_pair *q = new_res2_pair(p, second, m);
       insert_pair(q);
     }
 }
References ALLOCATE_MONOMIAL, MonomialIdeal::debug_out(), Monoid::divide(), emit(), mpfr::exp(), freemem(), Monoid::from_varpower(), PolynomialRing::get_quotient_monomials(), MonomialIdeal::insert_minimal(), insert_pair(), ExponentList< E, L >::is_equal(), PolynomialRing::is_quotient_ring(), PolynomialRing::is_skew_commutative(), M, M2_gbTrace, Monoid::make_one(), int_bag::monom(), monom_size, Monoid::mult(), PolynomialRing::n_skew_commutative_vars(), Monoid::n_vars(), new_res2_pair(), newarray_atomic, newline, p, P, ExponentList< E, L >::quotient(), PolynomialRing::skew_variable(), buffer::str(), ExponentList< E, L >::to_expvector(), Monoid::to_varpower(), and ExponentList< E, L >::var().