Macaulay2 Engine: res2_comp::betti_remaining
betti_remaining()
M2_arrayint res2_comp::betti_remaining () const
Definition at line 1834 of file res-a0.cpp.
{
  int lo = lodegree;
  int hi = lo + hidegree;
  int len = resn.size() - 1;
  int *bettis;
  betti_init(lo, hi, len, bettis);
  for (int lev = 0; lev <= len; lev++)
    {
      for (res2_pair *p = resn[lev]->pairs; p != nullptr; p = p->next)
        {
          if (p->syz_type != SYZ2_S_PAIR) continue;
          int d = p->degree;
          bettis[lev + (len + 1) * d]++;
        }
    }
  M2_arrayint result = betti_make(lo, hi, len, bettis);
  freemem(bettis);
  return result;
}
References ResolutionComputation::betti_init(), ResolutionComputation::betti_make(), freemem(), hidegree, lodegree, p, resn, and SYZ2_S_PAIR.
Referenced by get_betti().