Macaulay2 Engine: res2_comp::do_pairs_by_level
do_pairs_by_level()
enum ComputationStatusCode res2_comp::do_pairs_by_level (int level)
Definition at line 151 of file res-a0.cpp.
{
  // The pairs should be sorted in ascending monomial order
  res2_pair *p;
  if (M2_gbTrace >= 2)
    {
      int nelems = resn[level]->nleft;
      if (nelems > 0)
        {
          buffer o;
          o << "[lev " << nelems << ']';
          emit(o.str());
        }
    }
  for (p = resn[level]->next_pair; p != nullptr; p = p->next)
    {
      resn[level]->next_pair = p->next;
      handle_pair_by_level(p);
      if (stop_.pair_limit > 0 && npairs - nleft >= stop_.pair_limit)
        return COMP_DONE_PAIR_LIMIT;
      //      if (--PairLimit == 0) return COMP_DONE_PAIR_LIMIT;
      if (system_interrupted()) return COMP_INTERRUPTED;
    }
  if (do_by_level == 2)
    {
      // The following is experimental
      // Remove any term that cannot appear as a lead term.
      // This destroys the resolution as we go, so in general, we would have
      // to place this information elsewhere.
      int nmonoms = 0;
      int nkilled = 0;
      for (p = resn[level]->pairs; p != nullptr; p = p->next)
        {
          res2term *f = p->syz;
          res2term head;
          res2term *g = &head;
          for (f = p->syz; f != nullptr; f = f->next)
            {
              if (f->comp->mi->size() > 0)
                {
                  g->next = R->new_term(K->copy(f->coeff), f->monom, f->comp);
                  g = g->next;
                  nmonoms++;
                }
              else
                nkilled++;
            }
          g->next = nullptr;
          p->pivot_term = head.next;
        }
      if (M2_gbTrace >= 3)
        {
          buffer o;
          o << "[kept " << nmonoms << " killed " << nkilled << "]";
          emit(o.str());
        }
    }
  return COMP_COMPUTING;
}
References res2term::coeff, res2term::comp, COMP_COMPUTING, COMP_DONE_PAIR_LIMIT, COMP_INTERRUPTED, Ring::copy(), do_by_level, emit(), handle_pair_by_level(), K, M2_gbTrace, res2_pair::mi, res2term::monom, res2_poly::new_term(), res2term::next, nleft, npairs, p, StopConditions::pair_limit, R, resn, MonomialIdeal::size(), Computation::stop_, buffer::str(), and system_interrupted().
Referenced by start_computation().