Macaulay2 Engine: res2_comp::do_auto_reductions
do_auto_reductions()
void res2_comp::do_auto_reductions (res2_pair * p, auto_reduce_node * au) private
Definition at line 1621 of file res-a0.cpp.
 {
   buffer o;
   while (au != nullptr)
     {
       auto_reduce_node *a = au;
       au = au->next;
       o << "auto reduction: " << newline << "    ";
       R->elem_text_out(p->syz);
       o << newline << "    ";
       R->elem_text_out(a->p->syz);
       o << newline << "    by coeff = ";
       K->elem_text_out(o, a->pivot->coeff);
       ring_elem c = K->negate(a->pivot->coeff);
       res2term *h = R->mult_by_coefficient(p->syz, c);
       K->remove(c);
       R->add_to(a->p->syz, h);
       o << newline << "    result = ";
       R->elem_text_out(a->p->syz);
       o << newline;
       freemem(a);
     }
   emit(o.str());
 }
References res2_poly::add_to(), res2term::coeff, res2_poly::elem_text_out(), Ring::elem_text_out(), emit(), freemem(), K, res2_poly::mult_by_coefficient(), Ring::negate(), newline, auto_reduce_node::next, p, auto_reduce_node::p, auto_reduce_node::pivot, R, Ring::remove(), buffer::str(), and res2_pair::syz.
Referenced by handle_pair().