Macaulay2 Engine: res2_comp::text_out
text_out() [1/3]
void res2_comp::text_out (buffer & o) const virtual
Implements ResolutionComputation.
Definition at line 1998 of file res-a0.cpp.
 {
   o << "--- The total number of pairs in each level/slanted degree -----"
     << newline;
   M2_arrayint a = betti_skeleton();
   betti_display(o, a);
   //  o << "--- The number of pairs left to compute ------------------------" <<
   //  newline;
   //  a.shrink(0);
   //  betti_remaining(a);
   //  betti_display(o, a);
   o << "--- (Lower bounds of) the minimal betti numbers ----------" << newline;
   a = betti_minimal();
   betti_display(o, a);
   if (M2_gbTrace >= 1)
     {
       o << "-- #Reduction steps = " << total_reduce_count << "--"
         << " ones " << n_ones << " unique " << n_unique << " others "
         << n_others << " ----" << newline;
       o << "--- Number of monomials  ---------------------------------"
         << newline;
       a = betti_nmonoms();
       betti_display(o, a);
     }
   // If the printlevel is high enough, display each element
   if (M2_gbTrace >= 2)
     for (int lev = 0; lev < resn.size(); lev++)
       {
         if (resn[lev]->pairs == nullptr) continue;
         o << "---- level " << lev << " ----" << newline;
         for (res2_pair *p = resn[lev]->pairs; p != nullptr; p = p->next)
           text_out(o, p);
       }
 }
References ResolutionComputation::betti_display(), betti_minimal(), betti_nmonoms(), betti_skeleton(), M2_gbTrace, n_ones, n_others, n_unique, newline, p, resn, text_out(), and total_reduce_count.