Macaulay2 Engine: res2_comp::reduce4
reduce4()
res2_pair * res2_comp::reduce4 (res2term *& f, res2term *& fsyz, res2term *& pivot, res2_pair * p) private
Definition at line 1404 of file res-a0.cpp.
 {
   // 'lastterm' is used to append the next monomial to fsyz->syz
   exponents_t REDUCE_exp = ALLOCATE_EXPONENTS(exp_size);
   monomial REDUCE_mon = ALLOCATE_MONOMIAL(monom_size);
   res2term *lastterm = fsyz;
   while (lastterm->next != NULL) lastterm = lastterm->next;
   res2term head;
   res2term *red = &head;
   res2_pair *result = NULL;
   res2_pair *q;
   ring_elem rg;
   int count = total_reduce_count;
   if (M2_gbTrace >= 4) emit_wrapped(",");
   while (f != NULL)
     {
       res2term *lead = f;
       f = f->next;
       lead->next = NULL;
       M->divide(lead->monom, lead->comp->syz->monom, REDUCE_mon);
       M->to_expvector(REDUCE_mon, REDUCE_exp);
       if (find_ring_divisor(REDUCE_exp, rg))
         {
           // Subtract off f, leave fsyz alone
           Nterm *r = rg;
           M->divide(lead->monom, r->monom, REDUCE_mon);
           ring_elem c = K->negate(lead->coeff);
           res2term *h =
               R->ring_mult_by_term(r->next, c, REDUCE_mon, lead->comp);
           R->remove(lead);
           K->remove(c);
           R->add_to(f, h);
           total_reduce_count++;
         }
       else if (find_divisor(lead->comp->mi, REDUCE_exp, q))
         {
           if (q->degree == p->degree + 1)
             // if (q->syz_type == SYZ2_S_PAIR)
             {
               lastterm->next =
                   R->new_term(K->negate(lead->coeff), lead->monom, q);
               lastterm = lastterm->next;
               if (result == NULL && q->syz_type == SYZ2_S_PAIR)
                 {
                   // Only do this for the first non-computed pair
                   // Question: do we really need to keep this information
                   // around?
                   pivot = lastterm;
                   result = q;
                 }
               red->next = lead;
               red = red->next;
               continue;
             }
           else
             {
               ring_elem c = K->negate(lead->coeff);
               M->divide(lead->monom, q->syz->monom, REDUCE_mon);
               res2term *h = R->mult_by_term(q->syz->next, c, REDUCE_mon);
               lastterm->next = R->new_term(c, lead->monom, q);  // grabs 'c'.
               lastterm = lastterm->next;
               R->remove(lead);
               R->add_to(f, h);
               total_reduce_count++;
             }
         }
       else
         {
           red->next = lead;
           red = red->next;
         }
     }
   red->next = NULL;
   f = head.next;
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << (total_reduce_count - count);
       emit_wrapped(o.str());
     }
   return result;
 }
References res2_poly::add_to(), ALLOCATE_EXPONENTS, ALLOCATE_MONOMIAL, res2term::coeff, res2term::comp, res2_pair::degree, Monoid::divide(), emit_wrapped(), exp_size, find_divisor(), find_ring_divisor(), K, M, M2_gbTrace, res2_pair::mi, res2term::monom, Nterm::monom, monom_size, res2_poly::mult_by_term(), Ring::negate(), res2_poly::new_term(), res2term::next, Nterm::next, p, R, res2_poly::remove(), Ring::remove(), res2_poly::ring_mult_by_term(), buffer::str(), res2_pair::syz, SYZ2_S_PAIR, res2_pair::syz_type, Monoid::to_expvector(), and total_reduce_count.
Referenced by handle_pair_by_degree().