Macaulay2 Engine: res2_comp::new_base_res2_pair
new_base_res2_pair()
res2_pair * res2_comp::new_base_res2_pair (int i) private
Definition at line 627 of file res-a0.cpp.
 {
   res2_pair *p = new res2_pair;
   p->next = nullptr;
   p->me = next_component++;
   p->pair_num = p->me;
   p->syz_type = SYZ2_MINIMAL;
   p->level = 0;
   p->degree = (short unsigned int)(generator_matrix->rows()->primary_degree(i) -
                                    lodegree);
   p->compare_num = i;
   monomial m = M->make_one();
   p->syz = R->new_term(K->from_long(1), m, p);  // circular link...
   M->remove(m);
   p->mi = new MonomialIdeal(P, mi_stash);
   p->pivot_term = nullptr;
   return p;
 }
References Ring::from_long(), generator_matrix, K, lodegree, M, Monoid::make_one(), mi_stash, res2_poly::new_term(), next_component, p, P, FreeModule::primary_degree(), R, Monoid::remove(), Matrix::rows(), and SYZ2_MINIMAL.
Referenced by initialize().