Macaulay2 Engine: res2_comp::insert_pair
insert_pair()
void res2_comp::insert_pair (res2_pair * p) private
Definition at line 663 of file res-a0.cpp.
 {
   // This is where we insert the pair:
   // If the degree is not in the range lodegree..hard_degree_limit+1
   // then don't insert it.
   if (q->level >= 1)
     {
       if (have_degree_limit)
         {
           if (q->degree + lodegree > hard_degree_limit + 1)
             {
               resn[q->level]->nthrown++;
               remove_res2_pair(q);
               return;
             }
           if (q->degree <= hard_degree_limit && q->degree > hidegree)
             hidegree = q->degree;
         }
       else if (q->degree > hidegree)
         hidegree = q->degree;
     }
   q->next = resn[q->level]->pairs;
   resn[q->level]->pairs = q;
   npairs++;
   resn[q->level]->npairs++;
   if (q->syz_type == SYZ2_S_PAIR)
     {
       nleft++;
       resn[q->level]->nleft++;
     }
   else
     {
       nminimal++;
       resn[q->level]->nminimal++;
     }
 }
References res2_pair::degree, hard_degree_limit, have_degree_limit, hidegree, res2_pair::level, lodegree, res2_pair::next, nleft, nminimal, npairs, remove_res2_pair(), resn, SYZ2_S_PAIR, and res2_pair::syz_type.
Referenced by initialize(), and new_pairs().