Macaulay2 Engine: res2_comp::find_ring_divisor
find_ring_divisor()
int res2_comp::find_ring_divisor (const int * exp, ring_elem & result) const private
Definition at line 1048 of file res-a0.cpp.
 {
   if (!P->is_quotient_ring()) return 0;
   Bag *b;
   if (!P->get_quotient_monomials()->search_expvector(exp, b)) return 0;
   result.poly_val = P->quotient_element(b->basis_elem());
   return 1;
 }
References int_bag::basis_elem(), and mpfr::exp().
Referenced by reduce(), reduce2(), reduce3(), reduce4(), reduce_by_level(), and reduce_heap_by_level().