Macaulay2 Engine: res2_comp::handle_pair
handle_pair()
void res2_comp::handle_pair (res2_pair * p) private
Definition at line 1647 of file res-a0.cpp.
 {
   nleft--;
   resn[p->level]->nleft--;
   // For level 1: any non-marked GB elements in this degree are
   // minimal generators, so we need to mark them as such
   if (p->level == 1)
     {
       p->syz_type = SYZ2_MINIMAL;
       if (M2_gbTrace >= 2) emit_wrapped("z");
       if (projdim == 0) projdim = 1;
       nminimal++;
       return;
     }
   res2term *f = s_pair(p->syz);
   res2_pair *q;
   // This is used only for full auto reduction type 2.
   auto_reduce_node *au = reinterpret_cast<auto_reduce_node *>(p->pivot_term);
   if (use_respolyHeaps)
     q = reduce3(f, p->syz, p->pivot_term, p);
   else if (auto_reduce >= 1)
     q = reduce2(f, p->syz, p->pivot_term, p);
   else
     q = reduce(f, p->syz, p->pivot_term, p);
   // Auto reduction: here is where we 'modify' the
   // other elements by 'p'.
   if (auto_reduce == 2)
     {
       do_auto_reductions(p, au);
     }
   else if (auto_reduce == 3)
     {
     }
   if (f == nullptr)
     {
       // minimal syzygy
       if (p->level == length_limit + 1)
         {
           p->syz_type = SYZ2_MAYBE_MINIMAL;
         }
       else
         {
           p->syz_type = SYZ2_MINIMAL;
           nminimal++;
           if (p->level > projdim) projdim = p->level;
         }
       if (M2_gbTrace >= 2) emit_wrapped("z");
     }
   else
     {
       R->make_monic(f);
       p->syz_type = SYZ2_NOT_MINIMAL;
       // non-minimal syzygy
       R->remove(q->syz);
       q->syz = f;
       q->syz_type = SYZ2_NOT_NEEDED;
       // Auto reduction: here is where we modify the
       // other elements by 'q'.
       if (auto_reduce == 2)
         {
           do_auto_reductions(
               q, reinterpret_cast<auto_reduce_node *>(q->pivot_term));
           q->pivot_term = nullptr;
         }
       else if (auto_reduce == 3)
         {
         }
       if (M2_gbTrace >= 2) emit_wrapped("m");
     }
 }
References auto_reduce, do_auto_reductions(), emit_wrapped(), length_limit, M2_gbTrace, res2_poly::make_monic(), nleft, nminimal, p, res2_pair::pivot_term, projdim, R, reduce(), reduce2(), reduce3(), res2_poly::remove(), resn, s_pair(), res2_pair::syz, SYZ2_MAYBE_MINIMAL, SYZ2_MINIMAL, SYZ2_NOT_MINIMAL, SYZ2_NOT_NEEDED, res2_pair::syz_type, and use_respolyHeaps.