Macaulay2 Engine: res2_comp::minimal_free_of
minimal_free_of()
FreeModule * res2_comp::minimal_free_of (int i) const
Definition at line 2052 of file res-a0.cpp.
 {
   FreeModule *result;
   result = P->make_Schreyer_FreeModule();
   if (i < 0 || i >= resn.size() - 1) return result;
   if (do_by_level > 0) return free_of(i);
   auto D = get_ring()->degree_monoid();
   monomial deg = D->make_one();
   int n = 0;
   for (res2_pair *p = resn[i]->pairs; p != nullptr; p = p->next)
     if (p->syz_type == SYZ2_MINIMAL)
       {
         multi_degree(p, deg);
         result->append_schreyer(deg, p->syz->monom, p->compare_num);
         p->me = n++;
       }
   D->remove(deg);
   return result;
 }
References FreeModule::append_schreyer(), Ring::degree_monoid(), do_by_level, free_of(), get_ring(), Monoid::make_one(), Ring::make_Schreyer_FreeModule(), multi_degree(), p, P, resn, and SYZ2_MINIMAL.
Referenced by get_free(), and make_minimal().