Macaulay2 Engine: res2_comp::handle_pair_by_degree
handle_pair_by_degree()
void res2_comp::handle_pair_by_degree (res2_pair * p) private
Definition at line 1767 of file res-a0.cpp.
 {
   nleft--;
   resn[p->level]->nleft--;
   // For level 1: any non-marked GB elements in this degree are
   // minimal generators, so we need to mark them as such
   if (p->level == 1)
     {
       if (p->syz_type != SYZ2_NOT_NEEDED)
         {
           p->syz_type = SYZ2_MINIMAL;
           if (M2_gbTrace >= 2) emit_wrapped("z");
           nminimal++;
         }
       return;
     }
   res2term *f = s_pair(p->syz);
   res2_pair *q = reduce4(f, p->syz, p->pivot_term, p);
   // In this version of 'reduce', the resulting value of 'f' is irrelevant.
   // And in fact the routine should probably read:
   //  res2_pair *q = reduce4(p->syz, p->pivot_term);
   if (q == NULL)
     {
       if (p->syz_type != SYZ2_NOT_NEEDED)
         {
           // minimal syzygy
           p->syz_type = SYZ2_MINIMAL;
           nminimal++;
           resn[p->level]->nminimal++;
           if (M2_gbTrace >= 2) emit_wrapped("z");
         }
       else
         {
           if (M2_gbTrace >= 2) emit_wrapped("o");
         }
     }
   else
     {
       p->syz_type = SYZ2_NOT_MINIMAL;
       q->syz_type = SYZ2_NOT_NEEDED;
       if (M2_gbTrace >= 2) emit_wrapped("m");
     }
 }
References emit_wrapped(), M2_gbTrace, nleft, nminimal, p, reduce4(), resn, s_pair(), SYZ2_MINIMAL, SYZ2_NOT_MINIMAL, SYZ2_NOT_NEEDED, and res2_pair::syz_type.