Macaulay2 Engine: res2_comp::new_res2_pair
new_res2_pair() [2/2]
res2_pair * res2_comp::new_res2_pair (res2_pair * first, res2_pair * second, const int * basemon) private
Definition at line 603 of file res-a0.cpp.
 {
   res2_pair *p = new res2_pair;
   p->next = nullptr;
   p->me = next_component++;
   p->pair_num = p->me;
   p->syz_type = SYZ2_S_PAIR;
   p->level = (unsigned char)(first->level + 1);
   p->degree = (short unsigned int)(M->primary_degree(basemon) + first->degree -
                                    M->primary_degree(first->syz->monom) - 1);
   p->compare_num = 0;  // Will be set after pairs are done
   p->syz = R->new_term(K->from_long(1), basemon, first);
 #if 0
 //   if (second != NULL)
 //     p->syz->next = R->new_term(K->from_long(-1), basemon, second);
 #endif
   p->mi = new MonomialIdeal(P, mi_stash);
   p->pivot_term = nullptr;
   return p;
 }
References res2_pair::degree, Ring::from_long(), K, res2_pair::level, M, mi_stash, res2term::monom, res2_poly::new_term(), next_component, p, P, Monoid::primary_degree(), R, res2_pair::syz, and SYZ2_S_PAIR.