Macaulay2 Engine: res2_comp::handle_pair_by_level
handle_pair_by_level()
void res2_comp::handle_pair_by_level (res2_pair * p) private
Definition at line 1727 of file res-a0.cpp.
 {
   nleft--;
   resn[p->level]->nleft--;
   // level 1 is easy: just mark as minimal
   if (p->level == 1)
     {
       p->syz_type = SYZ2_MINIMAL;
       if (M2_gbTrace >= 2) emit_wrapped("z");
       return;
     }
   res2term *f = s_pair(p->syz);
   if (do_by_level == 2)
     {
       if (use_respolyHeaps)
         reduce_heap_by_level(f, p->syz);
       else
         reduce_by_level(f, p->syz);
     }
   else
     reduce(f, p->syz, p->pivot_term, p);
   if (f == nullptr)
     {
       p->syz_type = SYZ2_MINIMAL;
       if (M2_gbTrace >= 2) emit_wrapped("z");
     }
   else
     {
       // This should not happen at all!!
       buffer o;
       o << "handle pair: should not be here!";
       o << "p->syz == ";
       R->elem_text_out(o, p->syz);
       emit(o.str());
     }
 }
References do_by_level, res2_poly::elem_text_out(), emit(), emit_wrapped(), M2_gbTrace, nleft, p, R, reduce(), reduce_by_level(), reduce_heap_by_level(), resn, s_pair(), buffer::str(), SYZ2_MINIMAL, and use_respolyHeaps.