Macaulay2 Engine: res2_comp::get_betti
get_betti()
M2_arrayint res2_comp::get_betti (int type) const virtual
Implements ResolutionComputation.
Definition at line 1897 of file res-a0.cpp.
 {
   switch (type)
     {
       case 0:
         return betti_minimal();
       case 1:
         return betti_skeleton();
       case 2:
         return betti_remaining();
       case 3:
         return betti_nmonoms();
       case 4:
         ERROR(
             "cannot use Minimize=>true unless res(...,FastNonminimal=>true) "
             "was used");
         return nullptr;
     }
   ERROR("received unknown betti type");
   return nullptr;
 }
References betti_minimal(), betti_nmonoms(), betti_remaining(), betti_skeleton(), and ERROR().