Macaulay2 Engine: res2_comp::new_res2_pair
new_res2_pair() [1/2]
res2_pair * res2_comp::new_res2_pair (int i) private
Definition at line 646 of file res-a0.cpp.
 {
   res2_pair *p = new res2_pair;
   p->next = NULL;
   p->me = next_component++;
   p->pair_num = p->me;
   p->syz_type = SYZ2_S_PAIR;
   p->level = 1;
   p->degree = (short unsigned int)(generator_matrix->cols()->primary_degree(i) -
                                    1 - lodegree);
   p->compare_num = 0;
   p->syz = R->from_vector(base_components, (*generator_matrix)[i]);
   p->mi = new MonomialIdeal(P, mi_stash);
   p->pivot_term = NULL;
   return p;
 }
References base_components, Matrix::cols(), res2_poly::from_vector(), generator_matrix, lodegree, mi_stash, next_component, p, P, FreeModule::primary_degree(), R, and SYZ2_S_PAIR.
Referenced by initialize(), and new_pairs().