Macaulay2 Engine: res2_comp::reduce3
reduce3()
res2_pair * res2_comp::reduce3 (res2term *& f, res2term *& fsyz, res2term *& pivot, res2_pair * p) private
Definition at line 1308 of file res-a0.cpp.
 {
   // 'lastterm' is used to append the next monomial to fsyz->syz
   exponents REDUCE_exp = ALLOCATE_EXPONENTS(exp_size);
   monomial REDUCE_mon = ALLOCATE_MONOMIAL(monom_size);
   res2term *lastterm = (fsyz->next == NULL ? fsyz : fsyz->next);
   res2term head;
   res2term *red = &head;
   res2_pair *result = NULL;
   res2_pair *q;
   ring_elem rg;
   respolyHeap fb(R);  // No bucket is needed for fsyz, since we
                       // only append elements to the end of fsyz.
   fb.add(f);
   f = NULL;
   res2term *lead;
   //  Bag *b;
   int count = 0;
   if (M2_gbTrace >= 4) emit_wrapped(",");
   while ((lead = fb.remove_lead_term()) != NULL)
     {
       M->divide(lead->monom, lead->comp->syz->monom, REDUCE_mon);
       M->to_expvector(REDUCE_mon, REDUCE_exp);
       if (find_ring_divisor(REDUCE_exp, rg))
         {
           // Subtract off f, leave fsyz alone
           Nterm *r = rg;
           M->divide(lead->monom, r->monom, REDUCE_mon);
           ring_elem c = K->negate(lead->coeff);
           res2term *h =
               R->ring_mult_by_term(r->next, c, REDUCE_mon, lead->comp);
           R->remove(lead);
           K->remove(c);
           fb.add(h);
           total_reduce_count++;
           count++;
         }
       else if (find_divisor(lead->comp->mi, REDUCE_exp, q))
         {
           // q = (res2_pair *) (b->basis_ptr());
           if (q->syz_type == SYZ2_S_PAIR || q->syz_type == SYZ2_MAYBE_MINIMAL)
             {
               if (result == NULL)
                 {
                   lastterm->next =
                       R->new_term(K->negate(lead->coeff), lead->monom, q);
                   lastterm = lastterm->next;
                   pivot = lastterm;
                   result = q;
                 }
               red->next = lead;
               red = red->next;
               continue;
             }
           else
             {
               ring_elem c = K->negate(lead->coeff);
               M->divide(lead->monom, q->syz->monom, REDUCE_mon);
               res2term *h = R->mult_by_term(q->syz->next, c, REDUCE_mon);
               lastterm->next = R->new_term(c, lead->monom, q);
               lastterm = lastterm->next;
               R->remove(lead);
               fb.add(h);
               total_reduce_count++;
               count++;
             }
         }
       else
         {
           red->next = lead;
           red = red->next;
         }
     }
   red->next = NULL;
   f = head.next;
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << count;
       emit_wrapped(o.str());
     }
   return result;
 }
References geobucket< FREEMODULETYPE, VECTYPE >::add(), ALLOCATE_EXPONENTS, ALLOCATE_MONOMIAL, res2term::coeff, res2term::comp, Monoid::divide(), emit_wrapped(), exp_size, find_divisor(), find_ring_divisor(), K, M, M2_gbTrace, res2_pair::mi, res2term::monom, Nterm::monom, monom_size, res2_poly::mult_by_term(), Ring::negate(), res2_poly::new_term(), res2term::next, Nterm::next, R, res2_poly::remove(), Ring::remove(), geobucket< FREEMODULETYPE, VECTYPE >::remove_lead_term(), res2_poly::ring_mult_by_term(), buffer::str(), res2_pair::syz, SYZ2_MAYBE_MINIMAL, SYZ2_S_PAIR, res2_pair::syz_type, Monoid::to_expvector(), and total_reduce_count.
Referenced by handle_pair().