Macaulay2 Engine: res2_comp::sort_res2_pairs
sort_res2_pairs()
void res2_comp::sort_res2_pairs (res2_pair *& p) const private
Definition at line 891 of file res-a0.cpp.
{
  // These elements are sorted in ascending 'me' values
  if (p == nullptr || p->next == nullptr) return;
  res2_pair *p1 = nullptr;
  res2_pair *p2 = nullptr;
  while (p != nullptr)
    {
      res2_pair *tmp = p;
      p = p->next;
      tmp->next = p1;
      p1 = tmp;
      if (p == nullptr) break;
      tmp = p;
      p = p->next;
      tmp->next = p2;
      p2 = tmp;
    }
  sort_res2_pairs(p1);
  sort_res2_pairs(p2);
  p = merge_res2_pairs(p1, p2);
}
References merge_res2_pairs(), res2_pair::next, p, p1, and sort_res2_pairs().
Referenced by sort_monorder(), sort_reduction(), sort_res2_pairs(), and sort_skeleton().