Macaulay2 Engine: res2_comp::text_out
text_out() [2/3]
void res2_comp::text_out (buffer & o, const res2_pair * p) const
Definition at line 1925 of file res-a0.cpp.
 {
   res2_pair *a, *b;
   a = p->syz->comp;
   if (p->syz->next == nullptr)
     b = nullptr;
   else
     b = p->syz->next->comp;
   o << p->me << ' ';
   o << p->level << ' ' << p->degree << ' ';
   if (a != nullptr)
     o << a->me << ' ';
   else
     o << ". ";
   if (b != nullptr)
     o << b->me << ' ';
   else
     o << ". ";
   o << p->compare_num << ' ';
   switch (p->syz_type)
     {
       case SYZ2_S_PAIR:
         o << "PR";
         break;
       case SYZ2_MINIMAL:
         o << "SZ";
         break;
       case SYZ2_NOT_MINIMAL:
         o << "GB";
         o << "(pivot " << p->pivot_term->comp->me << ")";
         break;
       case SYZ2_NOT_NEEDED:
         o << "NO";
         break;
       default:
         break;
     }
 #if 0
 //   if (p->mi_exists)
 #endif
   o << "[mi: " << p->mi->size() << "]";
 #if 0
 //   else
 //     {
 //       res2_pair *q = p->next_div;
 //       int n = 0;
 //       while (q != NULL) { n++; q = q->next_div; }
 //       o << "[midiv: " << n << "]";
 //     }
 #endif
   M->elem_text_out(o, p->syz->monom);
   o << " [" << R->n_terms(p->syz) << "] ";
   if (M2_gbTrace >= 4)
     {
       // Display the vector
       o << " syz: ";
       R->elem_text_out(o, p->syz);
     }
   o << newline;
 }
References res2_poly::elem_text_out(), Monoid::elem_text_out(), M, M2_gbTrace, res2_pair::me, res2_poly::n_terms(), newline, p, R, SYZ2_MINIMAL, SYZ2_NOT_MINIMAL, SYZ2_NOT_NEEDED, and SYZ2_S_PAIR.