Macaulay2 Engine: res2_comp::make_minimal
make_minimal()
Matrix * res2_comp::make_minimal (int i) const
Definition at line 2119 of file res-a0.cpp.
 {
   const FreeModule *F = minimal_free_of(i - 1);
   const FreeModule *G = minimal_free_of(i);
   MatrixConstructor result(F, G, nullptr);
   if (i <= 0 || i >= resn.size() - 1) return result.to_matrix();
   if (do_by_level > 0) return make(i);
   VECTOR(res2_pair *) elems;
   VECTOR(res2term *) stripped;
   int n = 0;
   for (res2_pair *p = resn[i]->pairs; p != nullptr; p = p->next)
     {
       p->me = n++;
       elems.push_back(p);
       stripped.push_back(static_cast<res2term *>(nullptr));
     }
   int thisx = 0;
   for (int x = 0; x < elems.size(); x++)
     {
       res2_pair *p = elems[x];
       if (p->syz_type == SYZ2_MINIMAL)
         {
           if (stripped[p->me] == nullptr)
             {
               stripped[p->me] = R->strip(p->syz);
               reduce_minimal(x, stripped[p->me], elems, stripped);
             }
           result.set_column(thisx++, R->to_vector(stripped[p->me], F, 1));
         }
     }
   return result.to_matrix();
 }
References do_by_level, G, make(), minimal_free_of(), p, R, reduce_minimal(), resn, MatrixConstructor::set_column(), res2_poly::strip(), SYZ2_MINIMAL, MatrixConstructor::to_matrix(), res2_poly::to_vector(), VECTOR(), and x.
Referenced by get_matrix().