Macaulay2 Engine: res2_comp::reduce
reduce()
res2_pair * res2_comp::reduce (res2term *& f, res2term *& fsyz, res2term *& pivot, res2_pair * p) private
Definition at line 1126 of file res-a0.cpp.
 {
   // 'lastterm' is used to append the next monomial to fsyz->syz
   exponents_t REDUCE_exp = ALLOCATE_EXPONENTS(exp_size);
   monomial REDUCE_mon = ALLOCATE_MONOMIAL(monom_size);
   res2term *lastterm = (fsyz->next == nullptr ? fsyz : fsyz->next);
   res2_pair *q;
   ring_elem rg;
   //  Bag *b;
   int count = 0;
   if (M2_gbTrace >= 4) emit_wrapped(",");
   while (f != nullptr)
     {
       M->divide(f->monom, f->comp->syz->monom, REDUCE_mon);
       M->to_expvector(REDUCE_mon, REDUCE_exp);
       if (find_ring_divisor(REDUCE_exp, rg))
         {
           // Subtract off f, leave fsyz alone
           Nterm *r = rg;
           M->divide(f->monom, r->monom, REDUCE_mon);
           R->ring_subtract_multiple_to(f, f->coeff, REDUCE_mon, f->comp, rg);
           total_reduce_count++;
           count++;
         }
       //      else if (f->comp->mi.search_expvector(REDUCE_exp, b))
       else if (find_divisor(f->comp->mi, REDUCE_exp, q))
         {
           // q = (res2_pair *) (b->basis_ptr());
           lastterm->next = R->new_term(K->negate(f->coeff), f->monom, q);
           lastterm = lastterm->next;
           pivot = lastterm;
           if (q->syz_type == SYZ2_S_PAIR || q->syz_type == SYZ2_MAYBE_MINIMAL)
             {
               if (M2_gbTrace >= 4)
                 {
                   buffer o;
                   o << count;
                   emit_wrapped(o.str());
                 }
               return q;  // i.e. not computed yet
             }
           M->divide(f->monom, q->syz->monom, REDUCE_mon);
           R->subtract_multiple_to(f, f->coeff, REDUCE_mon, q->syz);
           total_reduce_count++;
           count++;
         }
       else
         {
           res2term *tmp = f;
           f = f->next;
           tmp->next = nullptr;
           R->remove(tmp);
         }
     }
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << count;
       emit_wrapped(o.str());
     }
   return nullptr;
 }
References ALLOCATE_EXPONENTS, ALLOCATE_MONOMIAL, res2term::coeff, res2term::comp, Monoid::divide(), emit_wrapped(), exp_size, find_divisor(), find_ring_divisor(), K, M, M2_gbTrace, res2_pair::mi, res2term::monom, Nterm::monom, monom_size, Ring::negate(), res2_poly::new_term(), res2term::next, R, res2_poly::remove(), res2_poly::ring_subtract_multiple_to(), buffer::str(), res2_poly::subtract_multiple_to(), res2_pair::syz, SYZ2_MAYBE_MINIMAL, SYZ2_S_PAIR, res2_pair::syz_type, Monoid::to_expvector(), and total_reduce_count.
Referenced by handle_pair(), and handle_pair_by_level().