Macaulay2 Engine: res2_comp::find_divisor
find_divisor()
int res2_comp::find_divisor (const MonomialIdeal * mi, const int * exp, res2_pair *& result) private
Definition at line 1062 of file res-a0.cpp.
 {
   // Find all the possible matches, use some criterion for finding the best...
   res2_pair *p;
   VECTOR(Bag *) bb;
   mi->find_all_divisors(exp, bb);
   if (bb.size() == 0) return 0;
   result = reinterpret_cast<res2_pair *>((bb[0]->basis_ptr()));
   // Now search through, and find the best one.  If only one, just return it.
   if (M2_gbTrace >= 5)
     if (mi->size() > 1)
       {
         buffer o;
         o << ":" << mi->size() << "." << bb.size() << ":";
         emit(o.str());
       }
   if (bb.size() == 1)
     {
       if (mi->size() == 1)
         n_ones++;
       else
         n_unique++;
       return 1;
     }
   n_others++;
   //  int n = R->n_terms(result->syz);
   unsigned int lowest = result->pair_num;
   for (int i = 1; i < bb.size(); i++)
     {
       p = reinterpret_cast<res2_pair *>(bb[i]->basis_ptr());
       if (p->pair_num < lowest)
         {
           lowest = p->pair_num;
           result = p;
         }
 #if 0
 //       int nt = R->n_terms(p->syz);
 //       if (nt < n)
 //      {
 //        n = nt;
 //        result = p;
 //      }
 #endif
     }
   return 1;
 }
References emit(), mpfr::exp(), MonomialIdeal::find_all_divisors(), M2_gbTrace, n_ones, n_others, n_unique, p, res2_pair::pair_num, MonomialIdeal::size(), buffer::str(), and VECTOR().
Referenced by reduce(), reduce2(), reduce3(), reduce4(), reduce_by_level(), and reduce_heap_by_level().