Macaulay2 Engine: res2_comp::make
make()
Matrix * res2_comp::make (int i) const
Definition at line 2071 of file res-a0.cpp.
 {
   const FreeModule *F = free_of(level - 1);
   const FreeModule *G = free_of(level);
   MatrixConstructor result(F, G, NULL);
   //  Matrix *result = new Matrix(free_of(level-1), free_of(level));
   int n = 0;
   if (G->rank() == 0) return result.to_matrix();
   for (res2_pair *p = resn[level]->pairs; p != NULL; p = p->next)
     result.set_column(n++, R->to_vector(p->syz, F));
   return result.to_matrix();
 }
References free_of(), p, R, FreeModule::rank(), resn, MatrixConstructor::set_column(), MatrixConstructor::to_matrix(), and res2_poly::to_vector().
Referenced by make_minimal().