Macaulay2 Engine: res2_comp::sort_value
sort_value()
int res2_comp::sort_value (res2_pair * p, const std::vector< int > sort_order) const private
Definition at line 940 of file res-a0.cpp.
 {
   exponents_t REDUCE_exp = ALLOCATE_EXPONENTS(exp_size);
   M->to_expvector(p->syz->monom, REDUCE_exp);
   return exponents::weight(P->n_vars(), REDUCE_exp, sort_order);
 }
References ALLOCATE_EXPONENTS, exp_size, M, PolynomialRing::n_vars(), p, P, Monoid::to_expvector(), and ExponentVector< E, OC >::weight().