Macaulay2 Engine: DMat< M2::ARingQQFlint >::fmpq_mat
fmpq_mat() [2/2]
const fmpq_mat_t& DMat< M2::ARingQQFlint >::fmpq_mat () const inline
Definition at line 113 of file dmat-qq-flint.hpp.
 { return mArray; }
References DMat< ACoeffRing >::mArray.
Referenced by MatrixOps::addMultipleTo(), MatrixOps::determinant(), MatrixOps::inverse(), MatrixOps::mult(), MatrixOps::nullSpace(), MatrixOps::rank(), MatrixOps::rowReducedEchelonForm(), and MatrixOps::subtractMultipleTo().