Macaulay2 Engine: rawTowerTranslatePoly
rawTowerTranslatePoly()
const RingElement* rawTowerTranslatePoly (const Ring * newRing, const RingElement * F)
Definition at line 507 of file tower.cpp.
 {
   // either: F is an element in a Tower, or is an element in a PolynomialRing.
   // In both cases: the number of variables and the characteristic should
   // be the same.
   const PolynomialRing *P = F->get_ring()->cast_to_PolynomialRing();
   const Tower *T = newRing->cast_to_Tower();
   if (P != nullptr && T != nullptr)
     {
       if (P->n_vars() != T->n_vars())
         {
           ERROR("expected rings with the same number of variables");
           return nullptr;
         }
       if (P->characteristic() != T->characteristic())
         {
           ERROR("expected rings with the same characteristic");
           return nullptr;
         }
       ring_elem a = T->translate(P, F->get_value());
       return RingElement::make_raw(T, a);
     }
 #if 0
   P = newRing->cast_to_PolynomialRing();
   T = F->get_ring()->cast_to_Tower();
   if (P != 0 && T != 0)
     {
       ring_elem a = T->translateFromTower(P, F->get_value());
       return RingElement::make_raw(P, a);
     }
 #endif
   ERROR("expected an element of a TowerRing or a PolynomialRing");
   return nullptr;
 }
References Ring::cast_to_PolynomialRing(), Ring::cast_to_Tower(), Ring::characteristic(), ERROR(), RingElement::get_ring(), RingElement::get_value(), RingElement::make_raw(), PolynomialRing::n_vars(), and T.