Macaulay2 Engine: copyPolyVector
copyPolyVector()
PolyList copyPolyVector (const M2FreeAlgebraOrQuotient * A, const PolyList & polys)
Definition at line 14 of file M2FreeAlgebra.cpp.
{
  auto& A0 = A->freeAlgebra();
  PolyList result;
  auto end = polys.cend();
  for (auto i = polys.cbegin(); i != end; ++i)
    {
      Poly* f = new Poly;
      A0.copy(*f, *(*i));
      result.push_back(f);
    }
  return result;
}
References FreeAlgebra::copy(), end(), and M2FreeAlgebraOrQuotient::freeAlgebra().
Referenced by rawNCGroebnerBasisTwoSided().