Macaulay2 Engine: NCF4::buildF4Matrix
buildF4Matrix()
void NCF4::buildF4Matrix (const std::deque< Overlap > & overlapsToProcess) private
Definition at line 466 of file NCF4.cpp.
 {
   matrixReset();
   mColumnMonomials.rehash(pow(2, ceil(log2(mPreviousColumnMonomials.size()))));
   for (auto o : overlapsToProcess)
     {
       auto stillValid = std::get<3>(o);
       if (stillValid) preRowsFromOverlap(o);
     }
   // can't do this loop as a range-based for loop since we are adding to it
   // during the for loop
   // process each element in mReducersTodo (false indicates a reducer row)
   for (int i=0 ; i < mReducersTodo.size(); ++i)
     processPreRow(mReducersTodo[i],mRows); // this often adds new elements to mReducersTodo
   int numReducersAtFirst = mReducersTodo.size();
   // process the overlap rows (true indicates an overlap row)
   for (auto over : mOverlapsTodo)
     processPreRow(over,mOverlaps);  // this often adds new elements to mReducersTodo
   // can't do this loop as a range-based for loop since we are adding
   // to mReducersTodo during the for loop
   for (int i=numReducersAtFirst ; i < mReducersTodo.size(); ++i)
     processPreRow(mReducersTodo[i],mRows); // this often adds new elements to mReducersTodo
   // Now we move the overlaps into mRows, and set mFirstOverlap.
   // double range, so use a for loop
   mFirstOverlap = mRows.size();
   for (int i=0; i < mOverlapsTodo.size(); ++i)
     {
       mRows.emplace_back(mOverlaps[i]);
       mReducersTodo.emplace_back(mOverlapsTodo[i]);
     }
 }
References mpfr::ceil(), mpfr::log2(), matrixReset(), mColumnMonomials, mFirstOverlap, mOverlaps, mOverlapsTodo, mPreviousColumnMonomials, mReducersTodo, mRows, mpfr::pow(), preRowsFromOverlap(), and processPreRow().
Referenced by process().