Macaulay2 Engine: NCF4::displayF4MatrixSize
displayF4MatrixSize()
void NCF4::displayF4MatrixSize (std::ostream & o) const
Definition at line 1064 of file NCF4.cpp.
 {
   // Display sizes:
   o << "(#cols, #reducer rows, #spair rows) = ("
     << mColumnMonomials.size() << ", "
     << mFirstOverlap << ", "
     << mRows.size() - mFirstOverlap << ")"
     << "  ";
   long numReducerEntries = 0;
   long numSPairEntries = 0;
   // if (mRows.size() != mReducersTodo.size())
   //   {
   //     o << std::endl;
   //     o << "***ERROR*** expected mRows and mReducersTodo to have the same length!" << std::endl;
   //     o << "        mRows size: " << mRows.size() << std::endl;
   //     o << "mReducersTodo size: " << mReducersTodo.size() << std::endl;
   //     exit(1);
   //   }
   for (auto i = 0; i < mRows.size(); ++i)
   {
     if (i < mFirstOverlap)
        numReducerEntries += mVectorArithmetic->size(mRows[i].coeffVector);
     else
        numSPairEntries += mVectorArithmetic->size(mRows[i].coeffVector);
     if (mVectorArithmetic->size(mRows[i].coeffVector) != mRows[i].columnIndices.size())
       o << "***ERROR*** ring_elem and component ranges do not match!" << std::endl;
   }
   o << "#entries: (" << numReducerEntries << "," << numSPairEntries << ")"
     << std::endl;
 }
References mColumnMonomials, mFirstOverlap, mRows, mVectorArithmetic, and VectorArithmetic::size().
Referenced by displayF4Matrix(), displayFullF4Matrix(), and process().