Macaulay2 Engine: NCF4::generalReduceF4Row
generalReduceF4Row()
template<typename LockType > void NCF4::generalReduceF4Row (int index, int first, int firstcol, NCF4Stats & ncF4Stats, ElementArray & dense, bool updateColumnIndex, LockType & lock) private
Definition at line 904 of file NCF4.cpp.
 {
   int sz = mRows[index].columnIndices.size();
   //assert(sz > 0);  this may be zero when autoreducing the new gb elements
   if (sz == 0) return;
   if (sz == 1 && firstcol != -1) return;
   int last = mRows[index].columnIndices[sz-1];
   mVectorArithmetic->fillDenseArray(dense,
                                   mRows[index].coeffVector,
                                   mRows[index].columnIndices);
   do {
     int pivotrow = mColumns[first].pivotRow;
     if (pivotrow >= 0)
       {
         ncF4Stats.numCancellations++;
         mVectorArithmetic->denseCancelFromSparse(dense,
                                                     mRows[pivotrow].coeffVector,
                                                     mRows[pivotrow].columnIndices);
         // last component in the row corresponding to pivotrow
         int last1 = mRows[pivotrow].columnIndices.cend()[-1];
         last = (last1 > last ? last1 : last);
       }
     else if (firstcol == -1)
       {
         firstcol = first;
       }
     first = mVectorArithmetic->denseNextNonzero(dense, first+1, last);
   } while (first <= last);
   // we have to free mRows[index] information because we are about to overwrite it
   // how can I free mRows[index].columnIndices?  it wasn't the last block allocated on mMonomialSpace...
   mVectorArithmetic->safeDenseToSparse(dense,
                                              mRows[index].coeffVector,
                                              mRows[index].columnIndices,
                                              firstcol,
                                              last,
                                              mMonomialSpace,
                                              lock);
   if (mVectorArithmetic->size(mRows[index].coeffVector) > 0)
     {
       mVectorArithmetic->makeMonic(mRows[index].coeffVector);
       // don't do this in the parallel version
       if (updateColumnIndex) mColumns[firstcol].pivotRow = index;
     }
 }
References VectorArithmetic::denseCancelFromSparse(), VectorArithmetic::denseNextNonzero(), VectorArithmetic::fillDenseArray(), VectorArithmetic::makeMonic(), mColumns, mMonomialSpace, mRows, mVectorArithmetic, NCF4::NCF4Stats::numCancellations, VectorArithmetic::safeDenseToSparse(), and VectorArithmetic::size().