Macaulay2 Engine: NCF4::findDivisor
findDivisor()
std::pair< bool, NCF4::PreRow > NCF4::findDivisor (Word w) private
Definition at line 708 of file NCF4.cpp.
 {
   Word newword;
   // look in previous F4 matrix for Monom before checking mWordTable
   auto usePreviousSuffix = findPreviousReducerSuffix(word);
   if (usePreviousSuffix.first)
     {
       // here, we use a multiple of a previously reduced row
       Word tmpWord;
       if (word.size() != 0)
         tmpWord.init(word.begin(), word.begin() + 1);
       return std::make_pair(true, PreRow {tmpWord,
                                           usePreviousSuffix.second,
                                           Word(),
                                           PreviousReducerPreRow});
     }
   auto usePreviousPrefix = findPreviousReducerPrefix(word);
   if (usePreviousPrefix.first)
     {
       // here, we use a multiple of a previously reduced row
       Word tmpWord;
       if (word.size() != 0)
         tmpWord.init(word.end()-1, word.end());
       return std::make_pair(true, PreRow {Word(),
                                           usePreviousPrefix.second,
                                           tmpWord,
                                           PreviousReducerPreRow});
     }
   // if we are here, then the Monom does not have a prefix/suffix
   // that was processed previously.
   // look in mWordTable for Monom
   std::pair<int,int> divisorInfo;
   // TODO: for certain inputs (e.g. Monoms that we *know* are of
   //       the form xm or mx for m a standard monomial and x a
   //       variable, one needs only to check prefixes or
   //       suffixes, not all subwords.  Not sure how to utilize that
   //       just yet.
   bool found = mWordTable.subword(word, divisorInfo);
   // if newword = x^a x^b x^c, with x^b in the word table, then:
   //  divisorInfo.first = index of the GB element with x^b as lead monomial.
   //  divisorInfo.second = position of the start of x^b in newword
   //   (that is, the length of x^a).
   if (not found)
     return std::make_pair(false, PreRow {Word(), 0, Word(), ReducerPreRow});
   // if found, then return this information to caller
   Word prefix = Word(word.begin(), word.begin() + divisorInfo.second);
   Word divisorWord = mWordTable[divisorInfo.first];
   Word suffix = Word(word.begin() + divisorInfo.second + divisorWord.size(),
                      word.end());
   return std::make_pair(true, PreRow {prefix, divisorInfo.first, suffix, ReducerPreRow});
 }
References findPreviousReducerPrefix(), findPreviousReducerSuffix(), Word::init(), mWordTable, prefix(), PreviousReducerPreRow, ReducerPreRow, Word::size(), WordTable::subword(), suffix(), and word.
Referenced by processWordInPreRow().