Macaulay2 Engine: NCF4::process
process()
void NCF4::process (const std::deque< Overlap > & overlapsToProcess) private
Definition at line 87 of file NCF4.cpp.
 {
 #if 0
   if (M2_gbTrace >= 2)
     {
       buffer o;
       o << newline << "F4 processing: # overlaps (spairs): " << overlapsToProcess.size() << newline;
       emit(o.str());
     }
 #endif
   // build the F4 matrix
   mtbb::tick_count t0 = mtbb::tick_count::now();
   // if (mIsParallel)
   //   parallelBuildF4Matrix(overlapsToProcess);
   // else
     buildF4Matrix(overlapsToProcess);
   mtbb::tick_count t1 = mtbb::tick_count::now();
   if (M2_gbTrace >= 2)
     std::cout << "Time spent on build step: " << (t1-t0).seconds() << std::endl;
   if (M2_gbTrace >= 2)
     {
       std::cout << "NC F4 GB: matrix size: ";
       displayF4MatrixSize(std::cout);
     }
   // sort the columns so that the matrix is `upper triangular'
   labelAndSortF4Matrix();
   if (M2_gbTrace >= 100) displayFullF4Matrix(std::cout);
   else if (M2_gbTrace >= 50) displayF4Matrix(std::cout);
   // reduce the matrix
   t0 = mtbb::tick_count::now();
   if (mIsParallel)
     parallelReduceF4Matrix();
   else
     reduceF4Matrix();
   t1 = mtbb::tick_count::now();
   if (M2_gbTrace >= 2)
     std::cout << "Time spent on reduction step: " << (t1-t0).seconds() << std::endl;
   if (M2_gbTrace >= 100) displayFullF4Matrix(std::cout);
   else if (M2_gbTrace >= 50) displayF4Matrix(std::cout);
   // convert back to GB elements...
   PolyList newElems = newGBelements();
   for (auto& f : newElems)
     {
       addToGroebnerBasis(f);
       updateOverlaps(f);
     }
   // prepare reduced matrix for use in the next degree
   processPreviousF4Matrix();
 #if 0
   if (M2_gbTrace >= 2)
     {
       buffer o;
       o << "F4 processing: # GB added: " << newElems.size() << newline;
       o << "F4 processing: # GB total: " << mGroebner.size() << newline;
       emit(o.str());
     }
 #endif
 }
References addToGroebnerBasis(), buildF4Matrix(), displayF4Matrix(), displayF4MatrixSize(), displayFullF4Matrix(), emit(), labelAndSortF4Matrix(), M2_gbTrace, mGroebner, mIsParallel, newGBelements(), newline, now(), parallelReduceF4Matrix(), processPreviousF4Matrix(), reduceF4Matrix(), seconds(), buffer::size(), buffer::str(), and updateOverlaps().
Referenced by compute().