Macaulay2 Engine: NCF4::matrixReset
matrixReset()
void NCF4::matrixReset () private
Definition at line 373 of file NCF4.cpp.
 {
   mReducersTodo.clear();
   mOverlapsTodo.clear();
   mColumns.clear();
   mColumnMonomials.clear();
   clearRows(mRows);
   // we don't have to call clearRows on mOverlaps because the coeff vectors
   // were moved to mRows first
   mOverlaps.clear();
   mFirstOverlap = 0;
   mMonomialSpace.deallocateAll();
   // the MemoryBlock objects that were in this vector
   // have been passed to mPreviousMemoryBlocks at this point.
   mMemoryBlocks.clear();
 }
References clearRows(), MemoryBlock< T, NSLAB >::deallocateAll(), mColumnMonomials, mColumns, mFirstOverlap, mMemoryBlocks, mMonomialSpace, mOverlaps, mOverlapsTodo, mReducersTodo, and mRows.
Referenced by buildF4Matrix(), and parallelBuildF4Matrix().