Macaulay2 Engine: NCF4::getCoeffOfMonom
getCoeffOfMonom()
ring_elem NCF4::getCoeffOfMonom (const Poly & f, const Monom & m) const private
Definition at line 345 of file NCF4.cpp.
 {
   for (auto t = f.cbegin(); t != f.cend(); ++t)
   {
     if (freeAlgebra().monoid().isEqual(t.monom(),m))
       return t.coeff();
   }
   return freeAlgebra().coefficientRing()->zero();
 }
References FreeAlgebra::coefficientRing(), freeAlgebra(), MatrixOps::isEqual(), and Ring::zero().
Referenced by autoreduceByLastElement().