Macaulay2 Engine: NCF4::reducedRowToPoly
reducedRowToPoly()
void NCF4::reducedRowToPoly (Poly * result, const RowsVector & rows, const ColumnsVector & cols, int i) const private
Definition at line 326 of file NCF4.cpp.
 {
   // this function places the elements of the ith row of the
   // (reduced!) F4 matrix in result.  This assumes that the first
   // term of the ith row is after the last entry of result (or that result is empty).
   auto& resultCoeffInserter = result->getCoeffInserter();
   auto& resultMonomInserter = result->getMonomInserter();
   //mVectorArithmetic->appendSparseVectorToContainer(rows[i].first,resultCoeffInserter);
   using ContainerType = decltype(resultCoeffInserter);
   mVectorArithmetic->appendToContainer<ContainerType>(rows[i].coeffVector,resultCoeffInserter);
   for (const auto& col : rows[i].columnIndices)
     freeAlgebra().monoid().monomInsertFromWord(resultMonomInserter,cols[col].word);
 }
References VectorArithmetic::appendToContainer(), freeAlgebra(), FreeAlgebra::monoid(), FreeMonoid::monomInsertFromWord(), mVectorArithmetic, and word.
Referenced by newGBelements(), and processPreRow().