Macaulay2 Engine: NCF4::updateOverlaps
updateOverlaps()
void NCF4::updateOverlaps (const Poly * toAdd) private
Definition at line 196 of file NCF4.cpp.
 {
    std::vector<Overlap> newLeftOverlaps;
    std::vector<Overlap> newRightOverlaps;
    Word newLeadWord = freeAlgebra().lead_word(*toAdd);
    // the word table insert places the right overlaps into newOverlaps
    mWordTable.insert(newLeadWord,newRightOverlaps);
    // this function finds the left overlaps with the most recently
    // inserted word.
    mWordTable.leftOverlaps(newLeftOverlaps);
    // can *also* remove previously added overlaps based on poly using
    // the same criterion from before
    checkOldOverlaps(newLeadWord);
    // finally, insert the new overlaps
    insertNewOverlaps(newRightOverlaps);
    insertNewOverlaps(newLeftOverlaps);
 }
References checkOldOverlaps(), freeAlgebra(), WordTable::insert(), insertNewOverlaps(), FreeAlgebra::lead_word(), WordTable::leftOverlaps(), and mWordTable.
Referenced by process().