Macaulay2 Engine: NCF4::freeAlgebra
freeAlgebra()
const FreeAlgebra& NCF4::freeAlgebra () const inline
Definition at line 168 of file NCF4.hpp.
 { return mFreeAlgebra; }
References mFreeAlgebra.
Referenced by autoreduceByLastElement(), displayF4Matrix(), displayFullF4Matrix(), getCoeffOfMonom(), labelAndSortF4Matrix(), NCF4(), preRowsFromOverlap(), processPreRow(), reducedRowToPoly(), and updateOverlaps().