Macaulay2 Engine: NCF4::clearRows
clearRows()
void NCF4::clearRows (RowsVector & rowsVector) private
Definition at line 1208 of file NCF4.cpp.
 {
   for (auto r : rowsVector)
   {
     // the VectorArithmetic object calls clear() on the ring elements in r.coeffVector as well.
     mVectorArithmetic->deallocateElementArray(r.coeffVector);
   }
   rowsVector.clear();
 }
References VectorArithmetic::deallocateElementArray(), and mVectorArithmetic.
Referenced by matrixReset(), processPreviousF4Matrix(), and ~NCF4().