Macaulay2 Engine: NCF4::displayFullF4Matrix
displayFullF4Matrix()
void NCF4::displayFullF4Matrix (std::ostream & o) const
Definition at line 1160 of file NCF4.cpp.
 {
   displayF4MatrixSize(o);
   // Now column monomials
   for (auto i : mColumnMonomials)
     {
       buffer b;
       FreeMonoid::MonomialInserter monomInserter;
       freeAlgebra().monoid().monomInsertFromWord(monomInserter,i.first);
       Monom m(monomInserter.data());
       freeAlgebra().monoid().elem_text_out(b, m);
       o << b.str() << "(" << i.second.first << ", " << i.second.second << ") ";
       // each i is a pair (const Monom, pair(int,int)).
     }
   o << std::endl;
   // For each row, and each overlap row, display the non-zero comps, non-zero coeffs.
   if (mRows.size() != mReducersTodo.size())
     {
       o << "***ERROR*** expected mRows and mReducersTodo to have the same length!" << std::endl;
       exit(1);
     }
   const Ring* kk = freeAlgebra().coefficientRing();
   for (auto count = 0; count < mRows.size(); ++count)
     {
       PreRow pr = mReducersTodo[count];
       o << count << " ("<< pr.left << ", "
         << pr.preRowIndex << ", "
         << pr.right << ")";
       size_t count2 = 0;
       for (auto i=0; i < mColumnMonomials.size(); i++)
         {
           if (count2 == mVectorArithmetic->size(mRows[count].coeffVector) or
               mRows[count].columnIndices[count2] != i)
             {
               o << " 0 ";
             }
           else
             {
               buffer b;
               kk->elem_text_out(b,mVectorArithmetic->ringElemFromElementArray(mRows[count].coeffVector,count2));
               o << " " << b.str() << " ";
               count2++;
             }
         }
       o << std::endl;
     }
 }
References FreeAlgebra::coefficientRing(), displayF4MatrixSize(), FreeMonoid::elem_text_out(), Ring::elem_text_out(), freeAlgebra(), NCF4::PreRow::left, mColumnMonomials, FreeAlgebra::monoid(), FreeMonoid::monomInsertFromWord(), mReducersTodo, mRows, mVectorArithmetic, NCF4::PreRow::preRowIndex, NCF4::PreRow::right, VectorArithmetic::ringElemFromElementArray(), VectorArithmetic::size(), and buffer::str().
Referenced by process().