Macaulay2 Engine: NCF4::processPreviousF4Matrix
processPreviousF4Matrix()
void NCF4::processPreviousF4Matrix () private
Definition at line 157 of file NCF4.cpp.
 {
   // flag the columns correspond to lead terms of new GB elements as reducers
   for (int i = mFirstOverlap; i < mRows.size(); ++i)
   {
     if (mRows[i].columnIndices.size() == 0) continue;
     int newReducerCol = mRows[i].columnIndices[0];
     mColumns[newReducerCol].pivotRow = i;
     mColumnMonomials[mColumns[newReducerCol].word].second = i;
   }
   // copy the finished rows and columns into the holding areas
   clearRows(mPreviousRows);
   mPreviousColumns.clear();
   mPreviousColumnMonomials.clear();
   mPreviousMonomialSpace.deallocateAll();
   for (auto& p : mPreviousMemoryBlocks)
   {
     if (p != nullptr)
       p->deallocateAll();
     p = nullptr;
   }
   mPreviousMemoryBlocks.clear();
   mPreviousRows = std::move(mRows);
   mPreviousColumns = std::move(mColumns);
   mPreviousColumnMonomials = std::move(mColumnMonomials);
   mPreviousMemoryBlocks = std::move(mMemoryBlocks);
   // need to move mMonomialSpace to a holding area since all the monomials
   // and int arrays in mPrevious data types are allocated there.
   mPreviousMonomialSpace.swap(mMonomialSpace);
 }
References clearRows(), MemoryBlock< T, NSLAB >::deallocateAll(), mColumnMonomials, mColumns, mFirstOverlap, mMemoryBlocks, mMonomialSpace, mPreviousColumnMonomials, mPreviousColumns, mPreviousMemoryBlocks, mPreviousMonomialSpace, mPreviousRows, mRows, p, and MemoryBlock< T, NSLAB >::swap().
Referenced by process().