Macaulay2 Engine: NCF4::compute
compute()
void NCF4::compute (int softDegreeLimit)
Definition at line 65 of file NCF4.cpp.
{
  while (!mOverlapTable.isFinished(softDegreeLimit))
    {
      auto degSet = mOverlapTable.nextDegreeOverlaps();
      auto toBeProcessed = degSet.second;
      if (M2_gbTrace >= 1)
        {
          buffer o;
          o << "{" << degSet.first << "}(" << toBeProcessed->size() << ")";
          emit_wrapped(o.str());
        }
      mScheduler.execute([this,&toBeProcessed]()
      {
        process(*toBeProcessed);
      });
      mOverlapTable.removeLowestDegree(); // TODO: suspect line.
      // we really want to just delete toBeProcessed...
      }
}
References emit_wrapped(), OverlapTable::isFinished(), M2_gbTrace, mOverlapTable, mScheduler, OverlapTable::nextDegreeOverlaps(), process(), OverlapTable::removeLowestDegree(), buffer::size(), and buffer::str().