Macaulay2 Engine: NCF4::NCF4
NCF4()
NCF4::NCF4 (const FreeAlgebra & A, const ConstPolyList & input, int hardDegreeLimit, int strategy, int numThreads)
Definition at line 19 of file NCF4.cpp.
     : mFreeAlgebra(A),
       mInput(input),
       //mTopComputedDegree(-1),            // not used yet.
       //mHardDegreeLimit(hardDegreeLimit), // not used yet.
       mMonomEq(A.monoid()),
       mMonomHashEqual(A.monoid()),
       mColumnMonomials(10,mMonomHash,mMonomHashEqual),
       mPreviousColumnMonomials(10,mMonomHash,mMonomHashEqual),
       mVectorArithmetic(new VectorArithmetic(A.coefficientRing())),
       mNumThreads(mtbb::numThreads(numThreads)),
       mIsParallel(mNumThreads != 1),
       mScheduler(mNumThreads)
 {
   //  std::cout << "number of processors being used: " << mNumThreads << std::endl;
   if (M2_gbTrace >= 1)
     {
       buffer o;
       o << "[NCGB F4]";
       emit_wrapped(o.str());
     }
   // process input polynomials
   mIsGraded = true;
   for (int i = 0; i < mInput.size(); ++i)
     {
       auto d = freeAlgebra().heft_degree(*mInput[i]);
       if (not d.second)
         mIsGraded = false;
       mOverlapTable.insert(d.first,
                            true,
                            std::make_tuple(i,-1,-1,true));
     }
   if (M2_gbTrace >= 1)
     {
       buffer o;
       o << (mIsGraded ? " homogeneous " : " inhomogeneous ");
       emit_wrapped(o.str());
     }
 }
References emit_wrapped(), freeAlgebra(), FreeAlgebra::heft_degree(), OverlapTable::insert(), M2_gbTrace, mInput, mIsGraded, mOverlapTable, and buffer::str().