Macaulay2 Engine: NCF4::createOverlapLeadWord
createOverlapLeadWord()
Word NCF4::createOverlapLeadWord (const Overlap & o) private
Definition at line 299 of file NCF4.cpp.
 {
   // this function adds the return value to mMemoryBlock, so should only be used
   // when running a GB since it will be subsequently cleared.
   Word left(mWordTable[std::get<0>(o)].begin(),
             mWordTable[std::get<0>(o)].begin()+std::get<1>(o));
   Word right = mWordTable[std::get<2>(o)];
   int sz = left.size() + right.size();
   auto rg = mMonomialSpace.allocateArray<int>(sz);
   std::copy(left.begin(),left.end(),rg.first);
   std::copy(right.begin(),right.end(),rg.first+left.size());
   return Word(rg.first, rg.second);
 }
References MemoryBlock< T, NSLAB >::allocateArray(), Word::begin(), begin(), Word::end(), mMonomialSpace, mWordTable, and Word::size().