Macaulay2 Engine: NCF4::findPreviousReducerPrefix
findPreviousReducerPrefix()
std::pair< bool, int > NCF4::findPreviousReducerPrefix (const Word & w) private
Definition at line 767 of file NCF4.cpp.
 {
   // build the largest proper prefix of m and look it up in previous
   // mColumnMonomials table.  we will return (true, row index) if
   // found and (false, -1) if not.
   // note that just because the second coordinate of an
   // mColumnMonomials entry is -1 does not mean there isn't a reducer
   // in the row -- in this case it is a new GB element and already
   // added to the mGroebner list.  In this case, we will be using that
   // entry anyway so no need to make the additional effort to find it
   // in the mRows table.
   // get prefix of m as a monom
   // search for prefix in mPreviousColumnMonomials
   // if it.second.second != -1, then return (true,it.second.first)
   // else return (false, -1)
   // if the monom is the empty monomial, return false
   if (w.size() == 0) return std::make_pair(false,-1);
   std::pair<bool,int> retval;
   Word prefix(w.begin(),w.end()-1);
   const auto it = mPreviousColumnMonomials.find(prefix);
   if (it == mPreviousColumnMonomials.end()) // not in table
     retval = std::make_pair(false,-1);
   else
   {
     int colNum = (*it).second.first;
     if (mPreviousColumns[colNum].pivotRow == -1)  // in column table and not a reducer monomial
       retval = std::make_pair(false,-1);
     else  // in table and a reducer monomial
       retval = std::make_pair(true,mPreviousColumns[colNum].pivotRow);
   }
   return retval;
 }
References Word::begin(), Word::end(), mPreviousColumnMonomials, mPreviousColumns, prefix(), and Word::size().
Referenced by findDivisor().