Macaulay2 Engine: NCF4::findPreviousReducerSuffix
findPreviousReducerSuffix()
std::pair< bool, int > NCF4::findPreviousReducerSuffix (const Word & w) private
Definition at line 806 of file NCF4.cpp.
 {
   // basically the same as above, except with suffixes
   // get suffix of m
   // search for suffix in mPreviousColumnMonomials
   // if it.second.second != -1, then return (true,it.second.first)
   // else return (false, -1)
   if (w.size() == 0) return std::make_pair(false,-1);
   std::pair<bool,int> retval;
   Word suffix(w.begin()+1,w.end());
   const auto it = mPreviousColumnMonomials.find(suffix);
   if (it == mPreviousColumnMonomials.end()) //not in table
     retval = std::make_pair(false,-1);
   else
   {
     int colNum = (*it).second.first;
     if (mPreviousColumns[colNum].pivotRow == -1)  // in column table and not a reducer monomial
       retval = std::make_pair(false,-1);
     else  // in table and a reducer monomial
       retval = std::make_pair(true,mPreviousColumns[colNum].pivotRow);
   }
   return retval;
 }
References Word::begin(), Word::end(), mPreviousColumnMonomials, mPreviousColumns, Word::size(), and suffix().
Referenced by findDivisor().