Macaulay2 Engine: NCF4::displayF4Matrix
displayF4Matrix()
void NCF4::displayF4Matrix (std::ostream & o) const
Definition at line 1096 of file NCF4.cpp.
 {
   displayF4MatrixSize(o);
   // Now column monomials
   for (auto i : mColumnMonomials)
     {
       // each i is a pair (const Monom, pair(int,int)).
       buffer b;
       FreeMonoid::MonomialInserter monomInserter;
       freeAlgebra().monoid().monomInsertFromWord(monomInserter,i.first);
       Monom m(monomInserter.data());
       freeAlgebra().monoid().elem_text_out(b, m);
       o << b.str() << "(" << i.second.first << ", " << i.second.second << ") ";
       if (i.second.second != -1 and
           (mRows[i.second.second].columnIndices.begin() == nullptr or
            mRows[i.second.second].columnIndices[0] != i.second.first))
       {
         std::cout << "Oops (" << mRows[i.second.second].columnIndices.begin()
                   << "," << mRows[i.second.second].columnIndices[0] << ","
                   << i.second.first << ")";
       }
     }
   o << std::endl;
   // For each row, and each overlap row, display the non-zero comps, non-zero coeffs.
   // if (mRows.size() != mReducersTodo.size())
   //   {
   //     o << std::endl;
   //     o << "***ERROR*** expected mRows and mReducersTodo to have the same length!" << std::endl;
   //     o << "        mRows size: " << mRows.size() << std::endl;
   //     o << "mReducersTodo size: " << mReducersTodo.size() << std::endl;
   //     exit(1);
   //   }
   const Ring* kk = freeAlgebra().coefficientRing();
   for (auto count = 0; count < mRows.size(); ++count)
     {
       // PreRow pr = mReducersTodo[count];
       // o << count << " ("<< std::get<0>(pr) << ", "
       //   << std::get<1>(pr) << ", "
       //   << std::get<2>(pr) << ", "
       //   << std::get<3>(pr) << ") "
       if (mRows[count].columnIndices.begin() == nullptr)
       {
         o << "Row " << count
           << " is empty.  This may indicate an error depending on the current state."
           << std::endl;
         continue;
       }
       o << "Row " << count << ";" << mRows[count].columnIndices.size() << ": ";
       if (mVectorArithmetic->size(mRows[count].coeffVector) != mRows[count].columnIndices.size())
         {
           o << "***ERROR*** expected coefficient array and components array to have the same length" << std::endl;
           exit(1);
         }
       for (auto i=0; i < mVectorArithmetic->size(mRows[count].coeffVector); ++i)
         {
           buffer b;
           kk->elem_text_out(b, mVectorArithmetic->ringElemFromElementArray(mRows[count].coeffVector,i));
           o << "[" << mRows[count].columnIndices[i] << "," << b.str() << "] ";
         }
       o << std::endl;
     }
 }
References FreeAlgebra::coefficientRing(), displayF4MatrixSize(), FreeMonoid::elem_text_out(), Ring::elem_text_out(), freeAlgebra(), mColumnMonomials, FreeAlgebra::monoid(), FreeMonoid::monomInsertFromWord(), mRows, mVectorArithmetic, VectorArithmetic::ringElemFromElementArray(), VectorArithmetic::size(), and buffer::str().
Referenced by process().