Macaulay2 Engine: Matrix::make_sparse
make_sparse() [2/2]
const Matrix * Matrix::make_sparse (const FreeModule * target, int ncols, M2_arrayint rows, M2_arrayint cols, const engine_RawRingElementArray entries) static
Definition at line 191 of file matrix.cpp.
 {
   MatrixConstructor mat(target, ncols);
   if (!Matrix::make_sparse_vecs(mat, target, ncols, rows, cols, entries))
     return nullptr;  // error message has already been sent
   mat.compute_column_degrees();
   return mat.to_matrix();
 }
References cols(), MatrixConstructor::compute_column_degrees(), make_sparse_vecs(), rows(), and MatrixConstructor::to_matrix().
Referenced by IM2_Matrix_make_sparse1(), and IM2_Matrix_make_sparse2().