Macaulay2 Engine: Matrix::make_sparse
make_sparse() [1/2]
const Matrix * Matrix::make_sparse (const FreeModule * target, const FreeModule * source, M2_arrayint deg, M2_arrayint rows, M2_arrayint cols, const engine_RawRingElementArray entries) static
Definition at line 205 of file matrix.cpp.
 {
 #ifdef DEVELOPMENT
 #warning "check that all rings are correct, give error otherwise"
 #endif
   const Ring *R = target->get_ring();
   auto D = R->degree_monoid();
   monomial degshift = D->make_one();
   D->from_expvector(deg->array, degshift);
   MatrixConstructor mat(target, source, degshift);
   if (!Matrix::make_sparse_vecs(
           mat, target, source->rank(), rows, cols, entries))
     return nullptr;  // error message has already been sent
   return mat.to_matrix();
 }
References cols(), Ring::degree_monoid(), FreeModule::get_ring(), Monoid::make_one(), make_sparse_vecs(), FreeModule::rank(), rows(), and MatrixConstructor::to_matrix().