Macaulay2 Engine: Matrix::text_out
text_out()
void Matrix::text_out (buffer & o) const
Definition at line 1306 of file matrix.cpp.
{
  auto R = get_ring();
  int nrows = n_rows();
  int ncols = n_cols();
  buffer *p = new buffer[nrows];
  //  buffer *p = new buffer[nrows];
  int r;
  for (int c = 0; c < ncols; c++)
    {
      int maxcount = 0;
      for (r = 0; r < nrows; r++)
        {
          ring_elem f = elem(r, c);
          R->elem_text_out(p[r], f);
          R->remove(f);
          if (p[r].size() > maxcount) maxcount = p[r].size();
        }
      for (r = 0; r < nrows; r++)
        for (int k = maxcount + 1 - p[r].size(); k > 0; k--) p[r] << ' ';
    }
  for (r = 0; r < nrows; r++)
    {
      p[r] << '\0';
      char *s = p[r].str();
      o << s << newline;
    }
  delete[] p;
}
References elem(), get_ring(), n_cols(), n_rows(), newline, p, and text_out().
Referenced by GBKernelComputation::calc(), dmatrix(), IM2_Matrix_to_string(), random(), newf4::GBF4Computation::showInput(), TEST(), LocalRing::text_out(), and text_out().