Macaulay2 Engine: Matrix::mult
mult()
Matrix * Matrix::mult (const Matrix * m, bool opposite_mult) const
Definition at line 630 of file matrix.cpp.
 {
   const Ring *R = get_ring();
   if (R != m->get_ring())
     {
       ERROR("matrix mult: different base rings");
       return nullptr;
     }
   if (n_cols() != m->n_rows())
     {
       ERROR("matrix mult: matrix sizes don't match");
       return nullptr;
     }
   int *deg = degree_monoid()->make_new(degree_shift());
   degree_monoid()->mult(deg, m->degree_shift(), deg);
   MatrixConstructor mat(rows(), m->cols(), deg);
   degree_monoid()->remove(deg);
   for (int i = 0; i < m->n_cols(); i++)
     mat.set_column(i, R->mult_vec_matrix(this, m->elem(i), opposite_mult));
   return mat.to_matrix();
 }
References cols(), degree_monoid(), degree_shift(), elem(), ERROR(), get_ring(), Monoid::make_new(), Monoid::mult(), Ring::mult_vec_matrix(), n_cols(), n_rows(), Monoid::remove(), rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().