Macaulay2 Engine: Matrix::zero
zero()
Matrix * Matrix::zero (const FreeModule * F, const FreeModule * G) static
Definition at line 369 of file matrix.cpp.
{
  if (F->get_ring() != G->get_ring())
    {
      ERROR("free modules have different base rings");
      return nullptr;
    }
  MatrixConstructor mat(F, G);
  return mat.to_matrix();
}
References ERROR(), G, FreeModule::get_ring(), MatrixConstructor::to_matrix(), and zero().
Referenced by zero().