Macaulay2 Engine: Matrix::norm
norm()
gmp_RRorNull Matrix::norm (gmp_RR p) const
Definition at line 2044 of file matrix.cpp.
 {
   const Ring *R = get_ring();
   if (R->get_precision() == 0)
     {
       ERROR("expected ring over an RR or CC");
       return nullptr;
     }
   gmp_RRmutable nm = getmemstructtype(gmp_RRmutable);
   mpfr_init2(nm, mpfr_get_prec(p));
   mpfr_ui_div(nm, 1, p, MPFR_RNDN);
   if (!mpfr_zero_p(nm))
     {
       ERROR("Lp norm only implemented for p = infinity");
       mpfr_clear(nm);
       return nullptr;
     }
   for (int i = 0; i < n_cols(); i++) R->vec_increase_maxnorm(nm, elem(i));
   return moveTo_gmpRR(nm);
 }
References elem(), ERROR(), Ring::get_precision(), get_ring(), getmemstructtype, moveTo_gmpRR(), n_cols(), p, and Ring::vec_increase_maxnorm().
Referenced by rawMatrixNorm().