Macaulay2 Engine: Matrix::identity
identity()
Matrix * Matrix::identity (const FreeModule * F) static
Definition at line 380 of file matrix.cpp.
 {
   const Ring *R = F->get_ring();
   const ring_elem one = R->from_long(1);
   MatrixConstructor mat(F, F, nullptr);
   for (int i = 0; i < F->rank(); i++) mat.set_entry(i, i, R->copy(one));
   return mat.to_matrix();
 }
References Ring::copy(), Ring::from_long(), FreeModule::get_ring(), FreeModule::rank(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by IM2_Matrix_identity(), and KBasis::k_basis().