Macaulay2 Engine: Matrix::tensor
tensor()
Matrix * Matrix::tensor (const Matrix * m) const
Definition at line 758 of file matrix.cpp.
 {
   if (get_ring() != m->get_ring())
     {
       ERROR("matrix tensor: different base rings");
       return 0;
     }
   const FreeModule *F = rows()->tensor(m->rows());
   const FreeModule *G = cols()->tensor(m->cols());
   monomial deg = degree_monoid()->make_new(degree_shift());
   degree_monoid()->mult(deg, m->degree_shift(), deg);
   MatrixConstructor mat(F, G, deg);
   degree_monoid()->remove(deg);
   int i, j, next = 0;
   for (i = 0; i < n_cols(); i++)
     for (j = 0; j < m->n_cols(); j++)
       mat.set_column(next++,
                      get_ring()->tensor(rows(), elem(i), m->rows(), (*m)[j]));
   return mat.to_matrix();
 }
References cols(), degree_monoid(), degree_shift(), elem(), ERROR(), get_ring(), Monoid::make_new(), Monoid::mult(), n_cols(), Monoid::remove(), rows(), MatrixConstructor::set_column(), Ring::tensor(), FreeModule::tensor(), and MatrixConstructor::to_matrix().
Referenced by IM2_Matrix_tensor().