Macaulay2 Engine: Matrix::get_ring
get_ring()
const Ring * Matrix::get_ring () const inline
Definition at line 85 of file matrix.hpp.
{ return rows()->get_ring(); }
References FreeModule::get_ring().
Referenced by binomialGB_comp::add_generators(), BRPSfromMatrix(), BIBasis::Launcher::CheckMatrix(), GBComputation::choose_gb(), ResolutionComputation::choose_res(), clean(), coeffs(), computeHashValue(), concat(), GaussElimComputation::contains(), GB_comp::contains(), HermiteComputation::contains(), ReducedGB::contains(), content(), convertToCFList(), ChineseRemainder::CRA(), GBDeclared::create(), SchreyerOrder::create(), GBDeclared::create(), GBinhom_comp::create(), binomialGB_comp::create(), gbA::create(), PolynomialRing::create_quotient(), createF4GB(), diff(), dimension1(), direct_sum(), divide_by_var(), elem(), elim_keep(), elim_vars(), RingMap::eval(), SLP< Field >::evaluate(), exterior(), F4Computation::F4Computation(), MutableMatrix::from_matrix(), gb_emitter::gb_emitter(), NCResComputation::get_free(), homogenize(), IM2_GB_force(), IM2_GB_make(), IM2_Matrix_concat(), IM2_Matrix_direct_sum(), IM2_Matrix_get_degree(), IM2_Matrix_get_entry(), IM2_Matrix_lift(), IM2_Matrix_promote(), IM2_res_make(), IM2_Ring_quotient(), gbA::initialize(), res2_comp::initialize(), res_comp::initialize(), GB_comp::initialize0(), is_equal(), is_homogeneous(), KBasis::k_basis(), KBasis::KBasis(), koszul(), PathTracker::make(), SLP< Field >::make(), PathTracker::make(), make_monideal(), FreeModule::make_schreyer(), makemonideal(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), MatrixSorter::MatrixSorter(), matrixToStream(), minors(), minors(), module_tensor(), mult(), NCCoefficientMatrix(), NCCoefficientMatrix(), NCMonomials(), norm(), operator+(), operator-(), operator-(), pfaffians(), rawCharSeries(), rawDisplayMatrixStream(), rawFourierMotzkin(), rawGbBoolean(), rawHilbertBasis(), rawIdealReorder(), rawKoszulMonomials(), rawLiftLocalMatrix(), rawMarkedGB(), rawMatrixClean(), rawMatrixCRA(), rawMatrixRatConversion(), rawMGB(), rawNCBasis(), rawNCGroebnerBasisTwoSided(), rawNCReductionTwoSided(), rawRingM2FreeAlgebraQuotient(), PathTracker::refine(), remake(), remake(), remove_content(), remove_scalar_multiples(), scalar_mult(), GBinhom_comp::set_up0(), gbres_comp::setup(), split_off_content(), sub_matrix(), sagbi::subduct(), support(), tensor(), text_out(), top_coefficients(), and PathTracker::track().