Macaulay2 Engine: Matrix::is_homogeneous
is_homogeneous()
bool Matrix::is_homogeneous () const
Definition at line 329 of file matrix.cpp.
 {
   if (!get_ring()->is_graded()) return 0;
   monomial d = degree_monoid()->make_one();
   for (int i = 0; i < n_cols(); i++)
     {
       if (elem(i) == nullptr) continue;
       if (!get_ring()->vec_is_homogeneous(rows(), elem(i)))
         {
           degree_monoid()->remove(d);
           return 0;
         }
       get_ring()->vec_multi_degree(rows(), elem(i), d);
       degree_monoid()->divide(d, degree_shift(), d);
       if (0 != degree_monoid()->compare(d, cols()->degree(i)))
         {
           degree_monoid()->remove(d);
           return 0;
         }
     }
   degree_monoid()->remove(d);
   return 1;
 }
References cols(), compare(), degree_monoid(), degree_shift(), Monoid::divide(), elem(), get_ring(), Monoid::make_one(), n_cols(), Monoid::remove(), rows(), Ring::vec_is_homogeneous(), and Ring::vec_multi_degree().
Referenced by IM2_Matrix_is_graded().