Macaulay2 Engine: Matrix::scalar_mult
scalar_mult()
Matrix * Matrix::scalar_mult (const ring_elem r, bool opposite_mult) const
Definition at line 580 of file matrix.cpp.
 {
   const Ring *R = get_ring();
   monomial deg = degree_monoid()->make_one();
   if (!R->is_zero(r)) R->degree(r, deg);
   degree_monoid()->mult(deg, degree_shift(), deg);
   MatrixConstructor mat(rows(), cols(), deg);
   for (int i = 0; i < n_cols(); i++)
     {
       vec w = R->copy_vec(elem(i));
       R->mult_vec_to(w, r, opposite_mult);
       mat.set_column(i, w);
     }
   return mat.to_matrix();
 }
References cols(), Ring::copy_vec(), Ring::degree(), degree_monoid(), degree_shift(), elem(), get_ring(), Ring::is_zero(), Monoid::make_one(), Monoid::mult(), Ring::mult_vec_to(), n_cols(), rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().