Macaulay2 Engine: Matrix::symm
symm()
Matrix * Matrix::symm (int n) const
Definition at line 66 of file matrix-symm.cpp.
{
  return SymmMatrix::symmetricPower(this, n);
}
References symm(), and SymmMatrix::symmetricPower().
Referenced by IM2_Matrix_symm(), and symm().