Macaulay2 Engine: Matrix::top_coefficients
top_coefficients()
Matrix * Matrix::top_coefficients (Matrix *& monoms) const
Definition at line 984 of file matrix.cpp.
 {
   const PolynomialRing *R = get_ring()->cast_to_PolynomialRing();
   if (R == nullptr)
     {
       ERROR("expected polynomial ring");
       return nullptr;
     }
   MatrixConstructor result(rows(), 0);
   MatrixConstructor cons_monoms(R->make_FreeModule(1), 0);
   for (int i = 0; i < n_cols(); i++)
     {
       int var, exp;
       vec u = elem(i);
       vec v = R->vec_top_coefficient(u, var, exp);
       result.append(v);
       if (v == nullptr)
         cons_monoms.append(v);
       else
         {
           ring_elem b;
           if (var < R->n_vars())
             {
               ring_elem a = R->var(var);
               b = R->power(a, exp);
             }
           else
             {
               b = R->from_long(1);
             }
           vec w = R->make_vec(0, b);
           cons_monoms.append(w);
         }
     }
   monoms = cons_monoms.to_matrix();
   return result.to_matrix();
 }
References MatrixConstructor::append(), Ring::cast_to_PolynomialRing(), elem(), ERROR(), mpfr::exp(), Ring::from_long(), get_ring(), Ring::make_FreeModule(), Ring::make_vec(), n_cols(), Ring::power(), rows(), MatrixConstructor::to_matrix(), PolynomialRing::var(), and PolynomialRing::vec_top_coefficient().
Referenced by rawTopCoefficients().