Macaulay2 Engine: Matrix::koszul
koszul() [1/2]
Matrix * Matrix::koszul (const Matrix * rows, const Matrix * cols) static
Definition at line 1215 of file matrix.cpp.
 {
   // First check rings: r,c,'this' should be row vectors.
   // and the ring should be a polynomial ring
   const FreeModule *F = r->cols();
   const PolynomialRing *P = F->get_ring()->cast_to_PolynomialRing();
   if (P == nullptr) return nullptr;
   const Ring *K = P->getCoefficients();
   const Monoid *M = P->getMonoid();
   MatrixConstructor mat(F, c->cols(), nullptr);
   int nvars = M->n_vars();
   int nrows = r->n_cols();
   int ncols = c->n_cols();
   const_monomial a, b;
   exponents_t aexp = newarray_atomic(int, nvars);
   exponents_t bexp = newarray_atomic(int, nvars);
   exponents_t result_exp = newarray_atomic(int, nvars);
   for (int i = 0; i < ncols; i++)
     {
       if (c->elem(i) == nullptr) continue;
       a = P->lead_flat_monomial(c->elem(i)->coeff);
       M->to_expvector(a, aexp);
       for (int j = 0; j < nrows; j++)
         {
           if (r->elem(j) == nullptr) continue;
           b = P->lead_flat_monomial(r->elem(j)->coeff);
           M->to_expvector(b, bexp);
           int sign = signdivide(nvars, aexp, bexp, result_exp);
           if (sign != 0)
             {
               monomial m = M->make_one();
               M->from_expvector(result_exp, m);
               ring_elem s = (sign > 0 ? K->one() : K->minus_one());
               ring_elem f = P->make_flat_term(s, m);
               mat.set_entry(j, i, f);
             }
         }
     }
   freemem(aexp);
   freemem(bexp);
   freemem(result_exp);
   return mat.to_matrix();
 }
References Ring::cast_to_PolynomialRing(), cols(), elem(), freemem(), Monoid::from_expvector(), FreeModule::get_ring(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), PolynomialRing::lead_flat_monomial(), PolynomialRing::make_flat_term(), Monoid::make_one(), Ring::minus_one(), n_cols(), Monoid::n_vars(), newarray_atomic, Ring::one(), MatrixConstructor::set_entry(), signdivide(), Monoid::to_expvector(), and MatrixConstructor::to_matrix().