Macaulay2 Engine: Matrix::make
make() [1/3]
const Matrix * Matrix::make (const FreeModule * target, const FreeModule * source, M2_arrayint deg, const engine_RawRingElementArray M) static
Definition at line 93 of file matrix.cpp.
 {
   const Ring *R = target->get_ring();
   auto D = R->degree_monoid();
   if (source->get_ring() != R)
     {
       ERROR("expected free modules over the same ring");
       return nullptr;
     }
   if (D->n_vars() != static_cast<int>(deg->len))
     {
       ERROR("expected degree of matrix to have %d entries", D->n_vars());
       return nullptr;
     }
   if (M != nullptr)
     {
       for (unsigned int i = 0; i < M->len; i++)
         {
           if (R != M->array[i]->get_ring())
             {
               ERROR("expected vectors in the same ring");
               return nullptr;
             }
         }
     }
   monomial degshift = D->make_one();
   D->from_expvector(deg->array, degshift);
   MatrixConstructor mat(target, source, degshift);
   if (M != nullptr)
     {
       unsigned int next = 0;
       for (int r = 0; r < target->rank(); r++)
         {
           for (int c = 0; c < source->rank(); c++)
             {
               mat.set_entry(r, c, M->array[next]->get_value());
               next++;
               if (next >= M->len) break;
             }
         }
     }
   return mat.to_matrix();
 }
References Ring::degree_monoid(), ERROR(), FreeModule::get_ring(), FreeModule::rank(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().