Macaulay2 Engine: Matrix::is_equal
is_equal()
bool Matrix::is_equal (const Matrix & m) const
Definition at line 312 of file matrix.cpp.
{
  auto R = get_ring();
  if (this == &m) return true;
  if (hash() != m.hash()) return false;
  if (R != m.get_ring()) return false;
  if (n_rows() != m.n_rows()) return false;
  if (n_cols() != m.n_cols()) return false;
  for (int i = 0; i < n_cols(); i++)
    if (!R->is_equal(elem(i), m.elem(i))) return false;
  return true;
}
References elem(), get_ring(), EngineObject::hash(), is_equal(), n_cols(), and n_rows().
Referenced by IM2_Matrix_is_equal(), is_equal(), operator+(), and operator-().