Macaulay2 Engine: Matrix::rows
rows()
const FreeModule* Matrix::rows () const inline
Definition at line 96 of file matrix.hpp.
 { return mTarget; }
References mTarget.
Referenced by clean(), coeffs(), compress(), KBasis::compute(), concat(), ChineseRemainder::CRA(), SchreyerOrder::create(), res_comp::degree(), DetComputation::DetComputation(), diff(), direct_sum(), divide_by_var(), F4Computation::F4Computation(), F4toM2Interface::from_M2_matrix(), GBDeclared::GBDeclared(), NCResComputation::get_free(), F4ResComputation::get_free(), GaussElimComputation::get_gb(), HermiteComputation::get_gb(), GaussElimComputation::get_initial(), HermiteComputation::get_initial(), get_ring(), homogenize(), IM2_Matrix_get_target(), gbA::initialize(), res2_comp::initialize(), res_comp::initialize(), GB_comp::initialize0(), is_homogeneous(), KBasis::k_basis(), KBasis::KBasis(), make_monideal(), make_sparse(), make_sparse_vecs(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), res_comp::minimal_free_of(), module_tensor(), mult(), res2_comp::multi_degree(), res_comp::multi_degree(), n_rows(), res2_comp::new_base_res2_pair(), operator+(), operator-(), gb_emitter::output_free_module(), rawCharSeries(), rawMatrixCRA(), rawMatrixRatConversion(), rawMGB(), gbres_comp::reduce(), remove_content(), remove_scalar_multiples(), scalar_mult(), GBinhom_comp::set_up0(), split_off_content(), hilb_comp::step(), sub_matrix(), sagbi::subduct(), sagbi::subduct1(), SymmMatrix::SymmMatrix(), tensor(), top_coefficients(), and transpose().