Macaulay2 Engine: Matrix::degree_shift
degree_shift()
const_monomial Matrix::degree_shift () const inline
Definition at line 100 of file matrix.hpp.
 { return mDegreeShift; }
References mDegreeShift.
Referenced by clean(), ChineseRemainder::CRA(), DetComputation::DetComputation(), diff(), IM2_Matrix_get_degree(), is_homogeneous(), koszul(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), mult(), operator+(), operator-(), gbres_comp::reduce(), remove_content(), scalar_mult(), split_off_content(), sub_matrix(), SymmMatrix::SymmMatrix(), tensor(), and transpose().