Macaulay2 Engine: Matrix::auto_reduce
auto_reduce()
Matrix * Matrix::auto_reduce () const
References content(), dimension1(), lead_term(), remove_content(), sort(), and split_off_content().