Macaulay2 Engine: Matrix::diff
diff()
Matrix * Matrix::diff (const Matrix * m, int use_coef) const
Definition at line 781 of file matrix.cpp.
 {
   const PolynomialRing *P = get_ring()->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("expected a polynomial ring");
       return nullptr;
     }
   if (P != m->get_ring())
     {
       ERROR("matrix diff: different base rings");
       return nullptr;
     }
   FreeModule *F1 = rows()->transpose();
   const FreeModule *F = F1->tensor(m->rows());
   FreeModule *G1 = cols()->transpose();
   const FreeModule *G = G1->tensor(m->cols());
   monomial deg = degree_monoid()->make_one();
   degree_monoid()->divide(m->degree_shift(), degree_shift(), deg);
   freemem(F1);
   freemem(G1);
   MatrixConstructor mat(F, G, deg);
   degree_monoid()->remove(deg);
   int i, j, next = 0;
   for (i = 0; i < n_cols(); i++)
     for (j = 0; j < m->n_cols(); j++)
       mat.set_column(
           next++,
           P->vec_diff(elem(i), m->rows()->rank(), m->elem(j), use_coef));
   return mat.to_matrix();
 }
References Ring::cast_to_PolynomialRing(), cols(), degree_monoid(), degree_shift(), Monoid::divide(), elem(), ERROR(), freemem(), get_ring(), Monoid::make_one(), n_cols(), FreeModule::rank(), Monoid::remove(), rows(), MatrixConstructor::set_column(), FreeModule::tensor(), MatrixConstructor::to_matrix(), FreeModule::transpose(), and Ring::vec_diff().
Referenced by IM2_Matrix_contract(), and IM2_Matrix_diff().