Macaulay2 Engine: Matrix::remove_scalar_multiples
remove_scalar_multiples()
Matrix * Matrix::remove_scalar_multiples () const
Definition at line 1427 of file matrix.cpp.
{
  bool keep;
  auto R = get_ring();
  MatrixConstructor result(rows(), 0);
  for (int i = 0; i < n_cols(); i++)
    {
      vec f = elem(i);
      if (f == nullptr) continue;
      keep = true;
      for (int j = i + 1; j < n_cols(); j++)
        {
          vec g = elem(j);
          if (g == nullptr) continue;
          if (R->vec_is_scalar_multiple(f, g))
            {
              keep = false;
              break;
            }
        }
      if (keep) result.append(R->copy_vec(f));
    }
  return result.to_matrix();
}
References MatrixConstructor::append(), elem(), get_ring(), n_cols(), remove_scalar_multiples(), rows(), and MatrixConstructor::to_matrix().
Referenced by minimal_lead_terms(), rawRemoveScalarMultiples(), and remove_scalar_multiples().