Macaulay2 Engine: Matrix::cols
cols()
const FreeModule* Matrix::cols () const inline
Definition at line 97 of file matrix.hpp.
 { return mSource; }
References mSource.
Referenced by clean(), compress(), concat(), ChineseRemainder::CRA(), DetComputation::DetComputation(), diff(), direct_sum(), GaussElimComputation::GaussElimComputation(), gb_emitter::gb_emitter(), NCResComputation::get_free(), HermiteComputation::HermiteComputation(), IM2_Matrix_concat(), IM2_Matrix_get_source(), gbA::initialize(), GB_comp::initialize(), res2_comp::initialize(), res_comp::initialize(), is_homogeneous(), koszul(), koszul_monomials(), FreeModule::make_schreyer(), make_sparse(), make_sparse_vecs(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), MatrixSorter::MatrixSorter(), module_tensor(), mult(), n_cols(), NCCoefficientMatrix(), res2_comp::new_res2_pair(), operator+(), operator-(), rawMatrixCRA(), rawMatrixRatConversion(), gbres_comp::reduce(), remove_content(), scalar_mult(), GBinhom_comp::set_up(), gbres_comp::setup(), split_off_content(), gb_emitter::start_degree(), sub_matrix(), sagbi::subduct(), sagbi::subduct1(), SymmMatrix::SymmMatrix(), tensor(), and transpose().