Macaulay2 Engine: Matrix::elem
elem() [3/3]
ring_elem Matrix::elem (int i, int j) const
Definition at line 305 of file matrix.cpp.
 {
   return get_ring()->get_entry(elem(j), i);
 }
References Ring::get_entry(), and get_ring().
Referenced by PolyRingQuotient::ann(), BRPSfromMatrix(), DetComputation::calc_det(), PfaffianComputation::calc_pfaff(), clean(), coeffs(), compress(), concat(), GaussElimComputation::contains(), HermiteComputation::contains(), content(), copyMatrixToVector(), ChineseRemainder::CRA(), PolynomialRing::create_quotient(), diff(), dimension1(), direct_sum(), divide_by_var(), elim_keep(), elim_vars(), RingMap::eval(), SLP< Field >::evaluate(), BIBasis::BooleanInvolutiveBasis< MonomType >::FillInitialSet(), F4toM2Interface::from_M2_matrix(), GBDeclared::GBDeclared(), GBMatrix::GBMatrix(), DetComputation::get_minor(), homogenize(), IM2_Matrix_concat(), IM2_Matrix_get_entry(), is_equal(), is_homogeneous(), is_zero(), koszul(), koszul_monomials(), SLP< Field >::make(), PathTracker::make(), DetComputation::make_dynamic_cache(), make_monideal(), makemonideal(), GaussElimComputation::matrix_lift(), HermiteComputation::matrix_lift(), GaussElimComputation::matrix_remainder(), HermiteComputation::matrix_remainder(), MatrixSorter::MatrixSorter(), matrixToPolyList(), module_tensor(), mult(), Ring::mult_vec_matrix(), NCCoefficientMatrix(), NCMonomials(), GaussElimComputation::new_gen(), HermiteComputation::new_gen(), norm(), operator+(), operator-(), PolyRingQuotient::quotient(), rawCharSeries(), rawIdealReorder(), rawMatrixRatConversion(), PathTracker::refine(), PolyRingQuotient::remainder(), PolyRingQuotient::remainderAndQuotient(), remove_content(), remove_scalar_multiples(), RingMap::RingMap(), scalar_mult(), Matrix::iterator::set(), split_off_content(), sub_matrix(), sagbi::subduct(), sagbi::subduct1(), support(), SymmMatrix::symm1(), PolyRingQuotient::syzygy(), tensor(), text_out(), top_coefficients(), and PathTracker::track().