Macaulay2 Engine: Matrix::remake
remake() [1/2]
const Matrix * Matrix::remake (const FreeModule * target) const
Definition at line 260 of file matrix.cpp.
 {
   if (n_rows() != target->rank())
     {
       ERROR("wrong number of rows");
       return nullptr;
     }
   const Ring *R = get_ring();
   if (R != target->get_ring())
     {
       ERROR("expected same ring");
       return nullptr;
     }
   MatrixConstructor mat(target, n_cols());
   for (int i = 0; i < n_cols(); i++)
     mat.set_column(i, R->copy_vec(mEntries[i]));
   mat.compute_column_degrees();
   return mat.to_matrix();
 }
References MatrixConstructor::compute_column_degrees(), Ring::copy_vec(), ERROR(), FreeModule::get_ring(), get_ring(), mEntries, n_cols(), n_rows(), FreeModule::rank(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().