Macaulay2 Engine: Matrix::random
random() [2/2]
Matrix * Matrix::random (const Ring * R, int r, int c, double fraction_non_zero, int special_type) static
Definition at line 688 of file matrix.cpp.
 {
   bool doing_fraction = false;
   int threshold = 0;
   FreeModule *F = R->make_FreeModule(r);
   FreeModule *G = R->make_FreeModule(c);
   MatrixConstructor mat(F, G, nullptr);
   // Loop through all selected elements, flip a 'fraction_non_zero' coin, and if
   // non-zero
   // set that element.
   if (density != 1.0)
     {
       doing_fraction = true;
       threshold = static_cast<int>(density * 10000);
     }
   if (special_type == 0)
     {
       for (int i = 0; i < c; i++)
         for (int j = 0; j < r; j++)
           {
             if (doing_fraction)
               {
                 int32_t u = rawRandomInt((int32_t)10000);
                 if (u > threshold) continue;
               }
             mat.set_entry(j, i, R->random());
           }
     }
   else if (special_type == 1)
     {
       for (int i = 0; i < c; i++)
         {
           int top = (i >= r ? r : i);
           for (int j = 0; j < top; j++)
             {
               if (doing_fraction)
                 {
                   int32_t u = rawRandomInt((int32_t)10000);
                   if (u > threshold) continue;
                 }
               mat.set_entry(j, i, R->random());
             }
         }
     }
   return mat.to_matrix();
 }
References Ring::make_FreeModule(), Ring::random(), rawRandomInt(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().