Macaulay2 Engine: Matrix::transpose
transpose()
Matrix * Matrix::transpose () const
Definition at line 566 of file matrix.cpp.
{
  const FreeModule *F = cols()->transpose();
  const FreeModule *G = rows()->transpose();
  const Ring *R = F->get_ring();
  MatrixConstructor mat(F, G, degree_shift());
  // The efficiency of this code relies on the way of ordering
  // the sparse vectors (lead term has largest component)
  iterator i(this);
  for (int c = 0; c < n_cols(); c++)
    {
      for (i.set(c); i.valid(); i.next())
        {
          ring_elem f = i.entry();
          mat.set_entry(c, i.row(), R->antipode(f));
        }
    }
  return mat.to_matrix();
}
References Ring::antipode(), cols(), degree_shift(), Matrix::iterator::entry(), G, FreeModule::get_ring(), n_cols(), Matrix::iterator::next(), Matrix::iterator::row(), rows(), Matrix::iterator::set(), MatrixConstructor::set_entry(), MatrixConstructor::to_matrix(), FreeModule::transpose(), transpose(), and Matrix::iterator::valid().
Referenced by IM2_Matrix_transpose(), and transpose().