Macaulay2 Engine: Matrix::dimension1
dimension1()
int Matrix::dimension1 () const
Definition at line 1968 of file matrix.cpp.
{
  const PolynomialRing *P = get_ring()->cast_to_PolynomialRing();
  const Ring *K = (P != nullptr ? P->getCoefficientRing() : get_ring());
  bool is_ZZ = K->is_ZZ();
  int base = (is_ZZ ? 1 : 0);
  int result = -1;
  if (P != nullptr)
    {
      int n = P->n_vars();
      for (int i = 0; i < n_rows(); i++)
        {
          MonomialIdeal *mi = make_monideal(i);
          AssociatedPrimes ap(mi);
          int d = n - ap.codimension();
          if (d > result) result = d;
        }
      if (result != -1) result += base;
      return result;
    }
  else
    {
      // This handles the case when the coefficients are a field, or ZZ
      int i, j;
      int *dims = newarray_atomic(int, n_rows());
      for (i = 0; i < n_rows(); i++) dims[i] = base;
      for (j = 0; j < n_cols(); j++)
        {
          vec f = elem(j);
          if (f == nullptr) continue;
          if (dims[f->comp] == -1) continue;
          if (K->is_unit(f->coeff))
            dims[f->comp] = -1;
          else
            dims[f->comp] = 0;
        }
      for (i = 0; i < n_rows(); i++)
        if (dims[i] > result) result = dims[i];
      freemem(dims);
      return result;
    }
}
References base, Ring::cast_to_PolynomialRing(), AssociatedPrimes::codimension(), dimension1(), elem(), freemem(), get_ring(), PolynomialRing::getCoefficientRing(), Ring::is_unit(), Ring::is_ZZ(), make_monideal(), n_cols(), n_rows(), PolynomialRing::n_vars(), and newarray_atomic.
Referenced by auto_reduce(), and dimension1().