Macaulay2 Engine: Matrix::wedge_product
wedge_product()
Matrix * Matrix::wedge_product (int p, int q, const FreeModule * F) static
Definition at line 1262 of file matrix.cpp.
 {
   const FreeModule *Fp = F->exterior(p);
   const FreeModule *Fq = F->exterior(q);
   const FreeModule *Fn = F->exterior(p + q);
   const FreeModule *G = Fp->tensor(Fq);
   const Ring *R = F->get_ring();
   MatrixConstructor mat(Fn, G, nullptr);
   if (p < 0 || q < 0 || p + q > F->rank()) return mat.to_matrix();
   if (p == 0 || q == 0)
     {
       for (int i = 0; i < G->rank(); i++) mat.set_entry(i, i, R->one());
       return mat.to_matrix();
     }
   Subsets C(F->rank(), p + q);
   Subset a(p, 0);
   Subset b(q, 0);
   Subset c(p + q, 0);
   int col = 0;
   for (int i = 0; i < Fp->rank(); i++)
     {
       C.decode(i, a);
       for (int j = 0; j < Fq->rank(); j++)
         {
           C.decode(j, b);
           int sgn = Subsets::concatenateSubsets(a, b, c);
           if (sgn == 0)
             {
               col++;
               continue;
             }
           ring_elem r = R->from_long(sgn);
           int row = static_cast<int>(C.encode(c));
           mat.set_entry(row, col++, r);
         }
     }
   return mat.to_matrix();
 }
References Subsets::concatenateSubsets(), Subsets::decode(), Subsets::encode(), FreeModule::exterior(), Ring::from_long(), G, FreeModule::get_ring(), Ring::one(), p, FreeModule::rank(), MatrixConstructor::set_entry(), mpfr::sgn(), FreeModule::tensor(), and MatrixConstructor::to_matrix().
Referenced by rawWedgeProduct().