Macaulay2 Engine: Matrix::make_monideal
make_monideal()
MonomialIdeal * Matrix::make_monideal (int n, bool use_only_monomials_with_unit_coeffs = false) const
Definition at line 1915 of file matrix.cpp.
 {
   const PolynomialRing *P = get_ring()->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("expected polynomial ring");
       return nullptr;
     }
   bool coeffsZZ = (P->coefficient_type() == Ring::COEFF_ZZ &&
                    use_only_monomials_with_unit_coeffs);
   const Monoid *M = P->getMonoid();
   VECTOR(Bag *) new_elems;
   for (int i = 0; i < n_cols(); i++)
     {
       vec v = elem(i);
       if (v == nullptr) continue;
       const vecterm *w = P->vec_locate_lead_term(rows(), v);
       if (w->comp != n) continue;
       if (coeffsZZ && !globalZZ->is_unit(P->lead_flat_coeff(w->coeff)))
         continue;
       Bag *b = new Bag(i);
       M->to_varpower(P->lead_flat_monomial(w->coeff), b->monom());
       new_elems.push_back(b);
     }
   // If the base ring is a quotient ring, include these lead monomials.
   for (int i = 0; i < P->n_quotients(); i++)
     {
       Nterm *f = P->quotient_element(i);
       if (coeffsZZ && !globalZZ->is_unit(f->coeff)) continue;
       Bag *b = new Bag(-1);
       M->to_varpower(f->monom, b->monom());
       new_elems.push_back(b);
     }
   // If the base ring has skew commuting variables, include their squares
   if (P->is_skew_commutative())
     {
       for (int i = 0; i < M->n_vars(); i++)
         if (P->is_skew_var(i))
           {
             Bag *b = new Bag(-1);
             varpower::var(i, 2, b->monom());
             new_elems.push_back(b);
           }
     }
   MonomialIdeal *result = new MonomialIdeal(P, new_elems);
   return result;
 }
References Ring::cast_to_PolynomialRing(), Nterm::coeff, vec::coeff, Ring::COEFF_ZZ, PolynomialRing::coefficient_type(), vec::comp, elem(), ERROR(), get_ring(), PolynomialRing::getMonoid(), globalZZ, PolynomialRing::is_skew_commutative(), PolynomialRing::is_skew_var(), RingZZ::is_unit(), PolynomialRing::lead_flat_coeff(), PolynomialRing::lead_flat_monomial(), int_bag::monom(), Nterm::monom, n_cols(), PolynomialRing::n_quotients(), Monoid::n_vars(), PolynomialRing::quotient_element(), rows(), Monoid::to_varpower(), ExponentList< E, L >::var(), PolynomialRing::vec_locate_lead_term(), and VECTOR().
Referenced by KBasis::compute(), dimension1(), IM2_MonomialIdeal_make(), and hilb_comp::next_monideal().