Macaulay2 Engine: Matrix::koszul
koszul() [2/2]
Matrix * Matrix::koszul (int p) const
Definition at line 1077 of file matrix.cpp.
 {
   if (n_rows() != 1)
     {
       ERROR("expected a matrix with one row");
       return nullptr;
     }
   FreeModule *F = cols()->exterior(p - 1);
   FreeModule *G = cols()->exterior(p);
   const Ring *R = get_ring();
   MatrixConstructor mat(F, G, degree_shift());
   if (p <= 0 || p > n_cols()) return mat.to_matrix();
   Subsets C(n_cols(), p);
   Subset a(p, 0);
   for (int c = 0; c < G->rank(); c++)
     {
       C.decode(c, a);
       int negate = ((p % 2) != 0);
       for (int r = p - 1; r >= 0; r--)
         {
           negate = !negate;
           size_t x = C.encodeBoundary(r, a);
           ring_elem f = elem(0, static_cast<int>(a[r]));
           if (negate) R->negate_to(f);
           mat.set_entry(static_cast<int>(x), c, f);
         }
     }
   return mat.to_matrix();
 }
References cols(), Subsets::decode(), degree_shift(), elem(), Subsets::encodeBoundary(), ERROR(), FreeModule::exterior(), get_ring(), n_cols(), n_rows(), mpfr::negate(), Ring::negate_to(), p, FreeModule::rank(), MatrixConstructor::set_entry(), MatrixConstructor::to_matrix(), and x.
Referenced by IM2_Matrix_koszul().