Macaulay2 Engine: Matrix::clean
clean()
Matrix * Matrix::clean (gmp_RR epsilon) const
Definition at line 2055 of file matrix.cpp.
{
  auto R = get_ring();
  MatrixConstructor mat(rows(), cols(), degree_shift());
  for (int i = 0; i < n_cols(); i++)
    mat.set_column(i, R->vec_zeroize_tiny(epsilon, elem(i)));
  return mat.to_matrix();
}
References clean(), cols(), degree_shift(), elem(), get_ring(), n_cols(), rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().
Referenced by clean(), and rawMatrixClean().