Macaulay2 Engine: Matrix::homogenize
homogenize()
Matrix * Matrix::homogenize (int v, M2_arrayint wts) const
Definition at line 354 of file matrix.cpp.
 {
   MatrixConstructor mat(rows(), n_cols());
   for (int i = 0; i < n_cols(); i++)
     mat.set_column(i, get_ring()->vec_homogenize(rows(), elem(i), v, wts));
   mat.compute_column_degrees();
   return mat.to_matrix();
 }
References MatrixConstructor::compute_column_degrees(), elem(), get_ring(), n_cols(), rows(), MatrixConstructor::set_column(), MatrixConstructor::to_matrix(), and Ring::vec_homogenize().
Referenced by IM2_Matrix_homogenize().