Macaulay2 Engine: Matrix::make
make() [3/3]
const Matrix * Matrix::make (const MonomialIdeal * mi) static
Definition at line 281 of file matrix.cpp.
 {
   const PolynomialRing *P = mi->get_ring()->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("expected a matrix over a polynomial ring");
       return nullptr;
     }
   const Monoid *M = P->getMonoid();
   monomial mon = M->make_one();
   MatrixConstructor mat(P->make_FreeModule(1), mi->size());
   int next = 0;
   for (auto i = mi->beginAtLast(); i != mi->end(); --i)  // TODO MES: should go from last() via --i to end()...
     {
       M->from_varpower(i->monom().data(), mon);
       ring_elem f =
           P->make_flat_term(P->getCoefficientRing()->from_long(1), mon);
       mat.set_entry(0, next++, f);
     }
   M->remove(mon);
   mat.compute_column_degrees();
   return mat.to_matrix();
 }
References MonomialIdeal::beginAtLast(), PolynomialRing::cast_to_PolynomialRing(), MatrixConstructor::compute_column_degrees(), MonomialIdeal::end(), ERROR(), Ring::from_long(), Monoid::from_varpower(), MonomialIdeal::get_ring(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), PolynomialRing::make_flat_term(), Ring::make_FreeModule(), Monoid::make_one(), Monoid::remove(), MatrixConstructor::set_entry(), MonomialIdeal::size(), and MatrixConstructor::to_matrix().