Macaulay2 Engine: Matrix::n_cols
n_cols()
int Matrix::n_cols () const inline
Definition at line 98 of file matrix.hpp.
 { return cols()->rank(); }
References cols(), and FreeModule::rank().
Referenced by binomialGB_comp::add_generators(), PolyRingQuotient::ann(), BRPSfromMatrix(), ResolutionComputation::choose_res(), clean(), coeffs(), compress(), computeHashValue(), concat(), GaussElimComputation::contains(), GB_comp::contains(), HermiteComputation::contains(), ReducedGB::contains(), content(), copyMatrixToVector(), ChineseRemainder::CRA(), GBDeclared::create(), SchreyerOrder::create(), PolynomialRing::create_quotient(), DetComputation::DetComputation(), diff(), dimension1(), direct_sum(), divide_by_var(), elim_keep(), elim_vars(), RingMap::eval(), SLP< Field >::evaluate(), F4Computation::F4Computation(), BIBasis::BooleanInvolutiveBasis< MonomType >::FillInitialSet(), F4toM2Interface::from_M2_matrix(), MutableMatrix::from_matrix(), GaussElimComputation::GaussElimComputation(), gb_emitter::gb_emitter(), GBMatrix::GBMatrix(), HermiteComputation::HermiteComputation(), homogenize(), IM2_Matrix_concat(), IM2_Matrix_get_entry(), IM2_Matrix_lift(), IM2_Matrix_n_cols(), IM2_Matrix_promote(), gbA::initialize(), GB_comp::initialize(), res2_comp::initialize(), res_comp::initialize(), GB_comp::initialize0(), is_equal(), is_homogeneous(), is_zero(), koszul(), koszul_monomials(), LocalRing::lift_up(), SLP< Field >::make(), PathTracker::make(), DetComputation::make_dynamic_cache(), make_monideal(), FreeModule::make_schreyer(), makemonideal(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), MatrixSorter::MatrixSorter(), matrixToPolyList(), matrixToStream(), module_tensor(), mult(), NCCoefficientMatrix(), NCMonomials(), norm(), operator+(), operator-(), PfaffianComputation::PfaffianComputation(), SchreyerFrame::rankUsingSparseMatrix(), rawCharSeries(), rawFourierMotzkin(), rawHilbertBasis(), rawIdealReorder(), rawMatrixRatConversion(), rawNCReductionTwoSided(), gbres_comp::reduce(), PathTracker::refine(), remake(), remove_content(), remove_scalar_multiples(), RingMap::RingMap(), scalar_mult(), DetComputation::set_next_minor(), GBinhom_comp::set_up(), GBinhom_comp::set_up0(), gbres_comp::setup(), res_comp::skeleton_init(), split_off_content(), gb_emitter::start_degree(), DetComputation::step(), PfaffianComputation::step(), sagbi::subduct(), sagbi::subduct1(), support(), tensor(), TEST(), text_out(), top_coefficients(), PathTracker::track(), and transpose().