Macaulay2 Engine: Matrix::flip
flip()
Matrix * Matrix::flip (const FreeModule * G, const FreeModule * H) static
Definition at line 547 of file matrix.cpp.
 {
   const Ring *R = F->get_ring();
   if (R != G->get_ring())
     {
       ERROR("flip: expected same ring");
       return nullptr;
     }
   const FreeModule *H = F->tensor(G);
   const FreeModule *K = G->tensor(F);
   MatrixConstructor mat(K, H, nullptr);
   int next = 0;
   for (int f = 0; f < F->rank(); f++)
     for (int g = 0; g < G->rank(); g++)
       mat.set_column(next++, R->e_sub_i(f + g * F->rank()));
   return mat.to_matrix();
 }
References Ring::e_sub_i(), ERROR(), G, FreeModule::get_ring(), FreeModule::rank(), MatrixConstructor::set_column(), FreeModule::tensor(), and MatrixConstructor::to_matrix().
Referenced by IM2_Matrix_flip().