Macaulay2 Engine: Matrix::sub_matrix
sub_matrix() [1/2]
Matrix * Matrix::sub_matrix (M2_arrayint c) const
Definition at line 505 of file matrix.cpp.
 {
   const FreeModule *G = cols()->sub_space(c);
   if (G == nullptr) return nullptr;
   MatrixConstructor mat(rows(), G, degree_shift());
   for (unsigned int i = 0; i < c->len; i++)
     mat.set_column(i, get_ring()->copy_vec(elem(c->array[i])));
   return mat.to_matrix();
 }
References cols(), degree_shift(), elem(), G, get_ring(), rows(), MatrixConstructor::set_column(), FreeModule::sub_space(), and MatrixConstructor::to_matrix().