Macaulay2 Engine: Matrix::split_off_content
split_off_content()
const Matrix * Matrix::split_off_content (const Matrix *& result) const
Definition at line 2014 of file matrix.cpp.
 {
   const Ring *R = get_ring();
   const PolynomialRing *P = R->cast_to_PolynomialRing();
   const Ring *targetR = (P == nullptr ? R : P->getCoefficients());
   const FreeModule *F = targetR->make_FreeModule(1);
   MatrixConstructor mat_content(F, n_cols());
   MatrixConstructor mat(rows(), cols(), degree_shift());
   for (int i = 0; i < n_cols(); i++)
     {
       vec g;
       ring_elem c = R->vec_split_off_content(elem(i), g);
       mat_content.set_entry(0, i, c);
       mat.set_column(i, g);
     }
   result = mat.to_matrix();
   return mat_content.to_matrix();
 }
References Ring::cast_to_PolynomialRing(), cols(), degree_shift(), elem(), get_ring(), PolynomialRing::getCoefficients(), Ring::make_FreeModule(), n_cols(), rows(), MatrixConstructor::set_column(), MatrixConstructor::set_entry(), MatrixConstructor::to_matrix(), and Ring::vec_split_off_content().
Referenced by rawMatrixSplitContent().