Macaulay2 Engine: Matrix::n_rows
n_rows()
int Matrix::n_rows () const inline
Definition at line 97 of file matrix.hpp.
 { return rows()->rank(); }
References FreeModule::rank(), and rows().
Referenced by coeffs(), KBasis::compute(), computeHashValue(), concat(), ChineseRemainder::CRA(), GBDeclared::create(), DetComputation::DetComputation(), dimension1(), direct_sum(), MutableMatrix::from_matrix(), GaussElimComputation::GaussElimComputation(), GaussElimComputation::get_change(), GaussElimComputation::get_gb(), GaussElimComputation::get_initial(), HermiteComputation::HermiteComputation(), IM2_Matrix_concat(), IM2_Matrix_get_entry(), IM2_Matrix_n_rows(), IM2_Ring_quotient(), IM2_RingMap_eval_matrix(), res2_comp::initialize(), res_comp::initialize(), is_equal(), koszul(), LocalRing::lift_up(), PathTracker::make(), DetComputation::make_dynamic_cache(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), matrixToPolyList(), module_tensor(), mult(), operator+(), operator-(), PfaffianComputation::PfaffianComputation(), SchreyerFrame::rankUsingSparseMatrix(), rawCharSeries(), rawDisplayMatrixStream(), rawFourierMotzkin(), rawHilbertBasis(), rawIdealReorder(), rawMGB(), rawNCGroebnerBasisTwoSided(), rawNCReductionTwoSided(), gbres_comp::reduce(), PathTracker::refine(), remake(), DetComputation::set_next_minor(), GaussElimComputation::start_computation(), DetComputation::step(), sub_matrix(), SymmMatrix::symmetricPower(), TEST(), GaussElimComputation::text_out(), text_out(), PathTracker::track(), and GaussElimComputation::~GaussElimComputation().