Macaulay2 Engine: Matrix::pfaffians
pfaffians()
Matrix * Matrix::pfaffians (int p) const
Definition at line 96 of file pfaff.cpp.
{
  if (get_ring()->get_precision() > 0)
    {
      ERROR("pfaffian computations over RR or CC not yet implemented");
      return nullptr;
    }
  PfaffianComputation d {this, p};
  d.calc();
  return d.pfaffians();
}
References ERROR(), get_ring(), p, and pfaffians().
Referenced by IM2_Matrix_pfaffians(), and pfaffians().