Macaulay2 Engine: Matrix::operator+
operator+()
Matrix * Matrix::operator+ (const Matrix & m) const
Definition at line 381 of file matrix.cpp.
 {
   if (get_ring() != m.get_ring())
     {
       ERROR("matrices have different base rings");
       return nullptr;
     }
   if (rows()->rank() != m.rows()->rank() || cols()->rank() != m.cols()->rank())
     {
       ERROR("matrices have different shapes");
       return nullptr;
     }
   const Ring *R = get_ring();
   const FreeModule *F = rows();
   const FreeModule *G = cols();
   const_monomial deg;
   if (!rows()->is_equal(m.rows())) F = R->make_FreeModule(n_rows());
   if (!cols()->is_equal(m.cols())) G = R->make_FreeModule(n_cols());
   if (EQ == degree_monoid()->compare(degree_shift(), m.degree_shift()))
     deg = degree_shift();
   else
     deg = degree_monoid()->make_one();
   MatrixConstructor mat(F, G, deg);
   for (int i = 0; i < n_cols(); i++)
     {
       vec v = R->copy_vec(elem(i));
       vec w = R->copy_vec(m[i]);
       R->add_vec_to(v, w);
       mat.set_column(i, v);
     }
   return mat.to_matrix();
 }
References Ring::add_vec_to(), cols(), compare(), Ring::copy_vec(), degree_monoid(), degree_shift(), elem(), EQ, ERROR(), get_ring(), is_equal(), Ring::make_FreeModule(), Monoid::make_one(), n_cols(), n_rows(), FreeModule::rank(), ffpackInterface::rank(), rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().