Macaulay2 Engine: Matrix::make_sparse_vecs
make_sparse_vecs()
bool Matrix::make_sparse_vecs (MatrixConstructor & mat, const FreeModule * target, int ncols, M2_arrayint rows, M2_arrayint cols, const engine_RawRingElementArray entries) static private
Definition at line 143 of file matrix.cpp.
{
  const Ring *R = target->get_ring();
  for (unsigned int i = 0; i < entries->len; i++)
    {
      if (R != entries->array[i]->get_ring())
        {
          ERROR("expected vectors in the same ring");
          return false;
        }
    }
  if (rows->len != cols->len || rows->len != entries->len)
    {
      ERROR("sparse matrix creation: encountered different length arrays");
      return false;
    }
  for (int x = 0; x < entries->len; x++)
    {
      int r = rows->array[x];
      int c = cols->array[x];
      if (r < 0 || r >= target->rank())
        {
          ERROR("sparse matrix creation: row index out of range");
          return false;
        }
      if (c < 0 || c >= ncols)
        {
          ERROR("sparse matrix creation: column index out of range");
          return false;
        }
    }
  for (int x = 0; x < entries->len; x++)
    {
      int r = rows->array[x];
      int c = cols->array[x];
      mat.set_entry(r, c, entries->array[x]->get_value());
    }
  return true;
}
References ERROR(), FreeModule::get_ring(), make_sparse_vecs(), FreeModule::rank(), MatrixConstructor::set_entry(), and x.
Referenced by make_sparse(), make_sparse(), and make_sparse_vecs().