Macaulay2 Engine: Matrix::homogenize
homogenize()
Matrix * Matrix::homogenize (int v, const std::vector< int > & wts) const
Definition at line 359 of file matrix.cpp.
{
  auto R = get_ring();
  MatrixConstructor mat(rows(), n_cols());
  for (int i = 0; i < n_cols(); i++)
    mat.set_column(i, R->vec_homogenize(rows(), elem(i), v, wts));
  mat.compute_column_degrees();
  return mat.to_matrix();
}
References MatrixConstructor::compute_column_degrees(), elem(), get_ring(), homogenize(), n_cols(), rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().
Referenced by homogenize(), and IM2_Matrix_homogenize().