Macaulay2 Engine: Matrix::elim_keep
elim_keep()
M2_arrayintOrNull Matrix::elim_keep (int nparts) const
Definition at line 1008 of file matrix.cpp.
 {
   intarray keep;
   const PolynomialRing *P = get_ring()->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("expected polynomial ring");
       return nullptr;
     }
   int nslots = P->getMonoid()->n_slots(nparts);
   for (int i = 0; i < n_cols(); i++)
     if (!P->vec_in_subring(nslots, elem(i))) keep.append(i);
   M2_arrayint result = M2_makearrayint(keep.length());
   for (unsigned int i = 0; i < result->len; i++) result->array[i] = keep[i];
   return result;
 }
References intarray::append(), Ring::cast_to_PolynomialRing(), elem(), ERROR(), get_ring(), PolynomialRing::getMonoid(), intarray::length(), M2_makearrayint(), n_cols(), Monoid::n_slots(), and Ring::vec_in_subring().
Referenced by IM2_Matrix_keep_vars().