Macaulay2 Engine: Matrix::reshape
reshape()
Matrix * Matrix::reshape (const FreeModule * G, const FreeModule * H) const
Definition at line 516 of file matrix.cpp.
{
  if (F->get_ring() != get_ring() || G->get_ring() != get_ring())
    {
      ERROR("reshape: expected same ring");
      return nullptr;
    }
  if (n_rows() * n_cols() != F->rank() * G->rank())
    {
      ERROR("reshape: ranks of the free modules are incorrect");
      return nullptr;
    }
  // EFFICIENCY: might be better to sort columns at end?
  MatrixConstructor mat(F, G, degree_shift());
  for (int c = 0; c < n_cols(); c++)
    for (vecterm *p = elem(c); p != nullptr; p = p->next)
      {
        // Determine new component
        int loc = c * n_rows() + p->comp;
        int result_col = loc / F->rank();
        int result_row = loc % F->rank();
        mat.set_entry(result_row, result_col, p->coeff);
      }
  return mat.to_matrix();
}
References ERROR(), G, p, reshape(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by IM2_Matrix_reshape(), and reshape().