Macaulay2 Engine: Matrix::minors
minors() [1/2]
Matrix * Matrix::minors (int p, int strategy) const
Definition at line 440 of file det.cpp.
 {
   if (strategy == DET_BAREISS && get_ring()->get_precision() > 0)
     {
       ERROR(
           "determinant computations over RR or CC requires Strategy=>Cofactor");
       return 0;
     }
   DetComputation *d = new DetComputation(this, p, 0, strategy);
   d->calc(-1);
   Matrix *result = d->determinants();
   freemem(d);
   return result;
 }
References DetComputation::calc(), DET_BAREISS, DetComputation::determinants(), ERROR(), freemem(), get_ring(), and p.
Referenced by IM2_Matrix_minors(), and rawMinors().