Macaulay2 Engine: Matrix::concat
concat()
Matrix * Matrix::concat (const Matrix & m) const
Definition at line 605 of file matrix.cpp.
{
  auto R = get_ring();
  if (R != m.get_ring())
    {
      ERROR("concat: different base rings");
      return nullptr;
    }
  if (n_rows() != m.n_rows())
    {
      ERROR("concat: matrices have different numbers of rows");
      return nullptr;
    }
  const FreeModule *G = cols()->direct_sum(m.cols());
  MatrixConstructor mat(rows(), G, nullptr);
  int i;
  int nc = n_cols();
  for (i = 0; i < nc; i++) mat.set_column(i, R->copy_vec(elem(i)));
  for (i = 0; i < m.n_cols(); i++)
    mat.set_column(nc + i, R->copy_vec(m.elem(i)));
  return mat.to_matrix();
}
References cols(), concat(), FreeModule::direct_sum(), elem(), ERROR(), G, get_ring(), n_cols(), n_rows(), rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().
Referenced by concat().