Macaulay2 Engine: Matrix::remove_monomial_factors
remove_monomial_factors()
Matrix * Matrix::remove_monomial_factors (bool make_squarefree_only) const
Definition at line 1452 of file matrix.cpp.
{
  auto R = get_ring();
  MatrixConstructor result(rows(), 0);
  for (int i = 0; i < n_cols(); i++)
    {
      vec f = R->vec_remove_monomial_factors(elem(i), make_squarefree_only);
      result.append(f);
    }
  return result.to_matrix();
}
References MatrixConstructor::append(), remove_monomial_factors(), and MatrixConstructor::to_matrix().
Referenced by minimal_lead_terms(), rawRemoveMonomialFactors(), and remove_monomial_factors().