Macaulay2 Engine: Matrix::module_tensor
module_tensor()
Matrix * Matrix::module_tensor (const Matrix * m) const
Definition at line 686 of file matrix.cpp.
 {
   auto R = get_ring();
   if (R != m->get_ring())
     {
       ERROR("module tensor: different base rings");
       return nullptr;
     }
   FreeModule *F = rows()->tensor(m->rows());
   FreeModule *G = rows()->tensor(m->cols());
   FreeModule *G1 = m->rows()->tensor(cols());
   G->direct_sum_to(G1);
   freemem(G1);
   MatrixConstructor mat(F, G, nullptr);
   int i, j, next = 0;
   for (i = 0; i < n_rows(); i++)
     for (j = 0; j < m->n_cols(); j++)
       mat.set_column(next++, R->component_shift(i * m->n_rows(), m->elem(j)));
   for (i = 0; i < m->n_rows(); i++)
     for (j = 0; j < n_cols(); j++)
       mat.set_column(next++, R->tensor_shift(m->n_rows(), i, elem(j)));
   return mat.to_matrix();
 }
References cols(), elem(), ERROR(), freemem(), G, get_ring(), n_cols(), n_rows(), rows(), MatrixConstructor::set_column(), FreeModule::tensor(), and MatrixConstructor::to_matrix().
Referenced by rawModuleTensor().