Macaulay2 Engine: Matrix::koszul_monomials
koszul_monomials()
Matrix * Matrix::koszul_monomials (int nskew, const Matrix * rows, const Matrix * cols) static
Definition at line 1125 of file matrix.cpp.
 {
   // First check rings: r,c,'this' should be row vectors.
   // and the ring should be a polynomial ring
   const FreeModule *F = r->cols();
   const PolynomialRing *P = F->get_ring()->cast_to_PolynomialRing();
   if (P == nullptr)
     {
       ERROR("expected polynomial ring");
       return nullptr;
     }
   const MonomialIdeal *A = makemonideal(r);
   const Ring *K = P->getCoefficients();
   const Monoid *M = P->getMonoid();
   MatrixConstructor mat(F, c->cols(), nullptr);
   int nvars = M->n_vars();
   int *skew_list = newarray_atomic(int, nskew);
   for (int j = 0; j < nskew; j++) skew_list[j] = j;
   SkewMultiplication skew(nvars, nskew, skew_list);
   int ncols = c->n_cols();
   exponents_t aexp = newarray_atomic(int, nvars);
   exponents_t bexp = newarray_atomic(int, nvars);
   exponents_t result_exp = newarray_atomic(int, nvars);
   monomial m = M->make_one();
   VECTOR(Bag *) divisors;
   for (int i = 0; i < ncols; i++)
     {
       if (c->elem(i) == nullptr) continue;
       const_monomial a = P->lead_flat_monomial(c->elem(i)->coeff);
       M->to_expvector(a, aexp);
       divisors.clear();
       A->find_all_divisors(aexp, divisors);
       for (int j = 0; j < divisors.size(); j++)
         {
           int rownum = divisors[j]->basis_elem();
           const_monomial b = P->lead_flat_monomial(r->elem(rownum)->coeff);
           M->to_expvector(b, bexp);
           exponents::divide(nvars, aexp, bexp, result_exp);
           int sign = skew.mult_sign(result_exp, bexp);
           if (sign != 0)
             {
               M->from_expvector(result_exp, m);
               ring_elem s = (sign > 0 ? K->one() : K->minus_one());
               ring_elem f = P->make_flat_term(s, m);
               mat.set_entry(rownum, i, f);
             }
         }
     }
   freemem(aexp);
   freemem(bexp);
   freemem(result_exp);
   return mat.to_matrix();
 }
References Ring::cast_to_PolynomialRing(), cols(), ExponentVector< E, OC >::divide(), elem(), ERROR(), MonomialIdeal::find_all_divisors(), freemem(), Monoid::from_expvector(), FreeModule::get_ring(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), PolynomialRing::lead_flat_monomial(), PolynomialRing::make_flat_term(), Monoid::make_one(), makemonideal(), Ring::minus_one(), SkewMultiplication::mult_sign(), n_cols(), Monoid::n_vars(), newarray_atomic, Ring::one(), MatrixConstructor::set_entry(), Monoid::to_expvector(), MatrixConstructor::to_matrix(), and VECTOR().
Referenced by rawKoszulMonomials().