Macaulay2 Engine: Matrix::sub_matrix
sub_matrix() [2/2]
Matrix * Matrix::sub_matrix (M2_arrayint r, M2_arrayint c) const
Definition at line 470 of file matrix.cpp.
 {
   const FreeModule *F = rows()->sub_space(r);
   const FreeModule *G = cols()->sub_space(c);
   if (F == nullptr || G == nullptr) return nullptr;
   int *minrow = newarray_atomic(int, n_rows());
   int *maxrow = newarray_atomic(int, n_rows());
   for (int i = 0; i < n_rows(); i++)
     {
       minrow[i] = n_rows();
       maxrow[i] = -1;
     }
   for (int i = 0; i < r->len; i++)
     if (r->array[i] >= 0 && r->array[i] < n_rows())
       {
         minrow[r->array[i]] = std::min(minrow[r->array[i]], i);
         maxrow[r->array[i]] = std::max(maxrow[r->array[i]], i);
       }
   MatrixConstructor mat(F, G, degree_shift());
   for (size_t j = 0; j < c->len; j++)
     {
       vec v = elem(c->array[j]);
       for (; v != nullptr; v = v->next)
         for (int i = minrow[v->comp]; i <= maxrow[v->comp]; i++)
           if (v->comp == r->array[i])
             mat.set_entry(i, j, v->coeff);
     }
   freemem(minrow);
   freemem(maxrow);
   return mat.to_matrix();
 }
References cols(), degree_shift(), elem(), freemem(), G, max, mpfr::min(), n_rows(), newarray_atomic, rows(), MatrixConstructor::set_entry(), FreeModule::sub_space(), and MatrixConstructor::to_matrix().
Referenced by IM2_Matrix_submatrix(), IM2_Matrix_submatrix1(), monomials(), and NCMonomialMatrix().