Macaulay2 Engine: Matrix::remake
remake() [2/2]
const Matrix * Matrix::remake (const FreeModule * target, const FreeModule * source, M2_arrayint deg) const
Definition at line 228 of file matrix.cpp.
{
  if (n_rows() != target->rank() || n_cols() != source->rank())
    {
      ERROR("wrong number of rows or columns");
      return nullptr;
    }
  const Ring *R = get_ring();
  auto D = R->degree_monoid();
  if (deg->len != D->n_vars())
    {
      ERROR("degree for matrix has the wrong length");
      return nullptr;
    }
  const Ring *Rtarget = target->get_ring();
  const Ring *Rsource = source->get_ring();
  if (R != Rtarget || Rtarget != Rsource)
    {
      ERROR("expected same ring");
      return nullptr;
    }
  monomial degshift = D->make_one();
  D->from_expvector(deg->array, degshift);
  MatrixConstructor mat(target, source, degshift);
  for (int i = 0; i < source->rank(); i++)
    mat.set_column(i, R->copy_vec(mEntries[i]));
  return mat.to_matrix();
}
References Ring::copy_vec(), Ring::degree_monoid(), ERROR(), FreeModule::get_ring(), get_ring(), mEntries, n_cols(), n_rows(), FreeModule::rank(), remake(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().
Referenced by IM2_Matrix_remake1(), IM2_Matrix_remake2(), remake(), and remake().