Macaulay2 Engine: Matrix::direct_sum
direct_sum()
Matrix * Matrix::direct_sum (const Matrix * m) const
const_monomial deg; if (EQ == R->degree_monoid()->compare(degree_shift(), m->degree_shift())) deg = degree_shift(); else deg = nullptr;
Definition at line 629 of file matrix.cpp.
{
  auto R = get_ring();
  if (R != m->get_ring())
    {
      ERROR("concat: different base rings");
      return nullptr;
    }
  // direct_sum ignores the degree shift of each summand.
  const FreeModule *F = rows()->direct_sum(m->rows());
  const FreeModule *G = cols()->direct_sum(m->cols());
  MatrixConstructor mat(F, G, nullptr);
  int i;
  int nr = n_rows();
  int nc = n_cols();
  for (i = 0; i < nc; i++) mat.set_column(i, R->copy_vec(elem(i)));
  for (i = 0; i < m->n_cols(); i++)
    mat.set_column(nc + i, R->component_shift(nr, m->elem(i)));
  return mat.to_matrix();
}
References cols(), FreeModule::direct_sum(), direct_sum(), elem(), ERROR(), G, get_ring(), n_cols(), n_rows(), rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().
Referenced by direct_sum(), and IM2_Matrix_direct_sum().