Macaulay2 Engine: Matrix::coeffs
coeffs()
Matrix * Matrix::coeffs (M2_arrayint vars, const Matrix * monoms) const
Definition at line 1823 of file matrix.cpp.
 {
   // Given an array_ of variable indices, 'vars', and given
   // that 'monoms' and 'this' both have one row, makes a matrix
   // having number of rows = ncols(monoms),
   //        number of cols = ncols(this),
   // whose (r,c) entry is the coefficient (in the other variables)
   // of this[0,c] in the monomial monoms[0,r].
   // Step 0: Do some error checking
   const PolynomialRing *P = get_ring()->cast_to_PolynomialRing();
   if (P != nullptr)
     {
       int nvars = P->n_vars();
       int nelements = monoms->n_cols();
       if (monoms->n_rows() != n_rows())
         {
           ERROR("expected matrices with the same number of rows");
           return nullptr;
         }
       for (unsigned int i = 0; i < vars->len; i++)
         if (vars->array[i] < 0 || vars->array[i] >= nvars)
           {
             ERROR("coeffs: expected a set of variable indices");
             return nullptr;
           }
       // Step 1: Make an exponent_table of all of the monoms.
       // We set the value of the i th monomial to be 'i+1', since 0
       // indicates a non-existent entry.
       // The extra size in monomial refers to the component:
       exponent_table *E = exponent_table_new(nelements, 1 + vars->len);
       exponent EXP = newarray_atomic(int, nvars);
       for (int i = 0; i < nelements; i++)
         {
           vec v = monoms->elem(i);
           if (v == nullptr)
             {
               ERROR("expected non-zero column");
               return nullptr;
             }
           ring_elem f = v->coeff;
           const_monomial m = P->lead_flat_monomial(f);
           P->getMonoid()->to_expvector(m, EXP);
           // grab only that part of the monomial we need
           exponent e = newarray_atomic(int, 1 + vars->len);
           get_part_of_expvector(vars, EXP, v->comp, e);
           exponent_table_put(E, e, i + 1);
         }
       // Step 2: for each vector column of 'this'
       //     create a column, and put this vector into result.
       MatrixConstructor mat(P->make_FreeModule(nelements), 0);
       for (int i = 0; i < n_cols(); i++)
         mat.append(coeffs_of_vec(E, vars, rows(), elem(i)));
       return mat.to_matrix();
     }
   const M2FreeAlgebraOrQuotient* Q = dynamic_cast<const M2FreeAlgebraOrQuotient*>(get_ring());
   if (Q != nullptr)
     {
       ModuleMonomialSet H(Q->n_vars());
       NCMonomials(H, monoms);
       return NCCoefficientMatrix(H, this);
     }
   ERROR("expected polynomial ring");
   return nullptr;
 }
References MatrixConstructor::append(), Ring::cast_to_PolynomialRing(), coeffs_of_vec(), elem(), ERROR(), exponent_table_new(), exponent_table_put(), get_part_of_expvector(), get_ring(), PolynomialRing::getMonoid(), PolynomialRing::lead_flat_monomial(), Ring::make_FreeModule(), n_cols(), n_rows(), PolynomialRing::n_vars(), M2FreeAlgebraOrQuotient::n_vars(), NCCoefficientMatrix(), NCMonomials(), nelements, newarray_atomic, rows(), Monoid::to_expvector(), and MatrixConstructor::to_matrix().
Referenced by rawCoefficients().