Macaulay2 Engine: Matrix::minors
minors() [2/2]
Matrix * Matrix::minors (int p, int strategy, int n_to_compute, M2_arrayintOrNull first_row, M2_arrayintOrNull first_col) const
Definition at line 455 of file det.cpp.
 {
   if (strategy == DET_BAREISS && get_ring()->get_precision() > 0)
     {
       ERROR(
           "determinant computations over RR or CC requires Strategy=>Cofactor");
       return nullptr;
     }
   if (first_row != nullptr || first_col != nullptr)
     {
       // Make sure these are the correct size, and both are given
       if (first_row == nullptr || first_row->len != p)
         {
           ERROR("row index set inappropriate");
           return nullptr;
         }
       if (first_col == nullptr || first_col->len != p)
         {
           ERROR("column index set inappropriate");
           return nullptr;
         }
     }
   DetComputation *d = new DetComputation(this, p, 0, strategy);
   if (first_row != nullptr && first_col != nullptr)
     d->set_next_minor(first_row->array, first_col->array);
   d->calc(n_to_compute);
   Matrix *result = d->determinants();
   freemem(d);
   return result;
 }
References DetComputation::calc(), DET_BAREISS, DetComputation::determinants(), ERROR(), freemem(), get_ring(), p, and DetComputation::set_next_minor().