Macaulay2 Engine: Matrix::is_zero
is_zero()
bool Matrix::is_zero () const
Definition at line 322 of file matrix.cpp.
 {
   for (int i = 0; i < n_cols(); i++)
     if (elem(i) != nullptr) return false;
   return true;
 }
References elem(), and n_cols().
Referenced by PolyRingQuotient::ann(), and IM2_Matrix_is_zero().