Macaulay2 Engine: Matrix::make
make() [2/3]
const Matrix * Matrix::make (const FreeModule * target, int ncols, const engine_RawRingElementArray M) static
Definition at line 60 of file matrix.cpp.
 {
   // Checks to make:
   // each vector in V is over same ring.
   const Ring *R = target->get_ring();
   if (M != nullptr)
     for (unsigned int i = 0; i < M->len; i++)
       {
         if (R != M->array[i]->get_ring())
           {
             ERROR("expected vectors in the same ring");
             return nullptr;
           }
       }
   MatrixConstructor mat(target, ncols);
   if (M != nullptr)
     {
       unsigned int next = 0;
       for (int r = 0; r < target->rank(); r++)
         for (int c = 0; c < ncols && next < M->len; c++)
           {
             mat.set_entry(r, c, M->array[next]->get_value());
             next++;
           }
       mat.compute_column_degrees();
     }
   return mat.to_matrix();
 }
References MatrixConstructor::compute_column_degrees(), ERROR(), FreeModule::get_ring(), FreeModule::rank(), MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by hilb_comp::hilbertNumerator(), IM2_Matrix_make1(), IM2_Matrix_make2(), and IM2_MonomialIdeal_to_matrix().