Macaulay2 Engine: rawMatrixCRA
rawMatrixCRA()
const Matrix* rawMatrixCRA (const Matrix * f, const Matrix * g, mpz_srcptr m, mpz_srcptr n)
Definition at line 61 of file cra.cpp.
 {
   // Error handling:
   if (f->get_ring() != g->get_ring())
     {
       ERROR("matrices have different base rings");
       return nullptr;
     }
   if (f->rows()->rank() != g->rows()->rank() ||
       f->cols()->rank() != g->cols()->rank())
     {
       ERROR("matrices have different shapes");
       return nullptr;
     }
   // Assumption: f and g are either matrices over ZZ, or over a polynomial ring
   // whose coeff
   // ring is ZZ.  The output is a matrix in the same ring.
   mpz_t um, vn, mn;
   mpz_init(um);
   mpz_init(vn);
   mpz_init(mn);
   ChineseRemainder::computeMultipliers(m, n, um, vn, mn);
   mpz_t result_coeff;
   mpz_init(result_coeff);
   Matrix *result = ChineseRemainder::CRA(f, g, um, vn, mn);
   mpz_clear(um);
   mpz_clear(vn);
   mpz_clear(mn);
   return result;
 }
References Matrix::cols(), ChineseRemainder::computeMultipliers(), ChineseRemainder::CRA(), ERROR(), Matrix::get_ring(), FreeModule::rank(), and Matrix::rows().