Macaulay2 Engine: rawRingElementRatConversion
rawRingElementRatConversion()
const RingElement* rawRingElementRatConversion (const RingElement * f, mpz_srcptr m, const Ring * RQ)
Definition at line 94 of file cra.cpp.
 {
   const Ring *Rf = f->get_ring();
   const PolyRing *P = Rf->cast_to_PolyRing();
   const PolyRing *PQ = RQ->cast_to_PolyRing();
   if (P == nullptr)
     {
       // check whether Rf is ZZ.  If not, error.
       if (!Rf->is_ZZ())
         {
           ERROR("expected ZZ, or polynomial ring over ZZ");
           return nullptr;
         }
       ERROR("not implemented yet");
       return nullptr;
     }
   else
     {
       const Ring *K = P->getCoefficientRing();
       if (K->is_ZZ())
         {
           ring_elem rf = f->get_value();
           ring_elem result = ChineseRemainder::ratConversion(rf, m, PQ);
           return RingElement::make_raw(PQ, result);  // debug this line!
         }
       else
         {
           ERROR("expected coefficient ring to be ZZ");
           return nullptr;
         }
     }
   ERROR("not written yet");
   return nullptr;
 }
References Ring::cast_to_PolyRing(), ERROR(), RingElement::get_ring(), RingElement::get_value(), PolynomialRing::getCoefficientRing(), Ring::is_ZZ(), RingElement::make_raw(), and ChineseRemainder::ratConversion().