Macaulay2 Engine: rawMatrixRatConversion
rawMatrixRatConversion()
const Matrix * rawMatrixRatConversion (const Matrix * f, mpz_srcptr m, const Ring * RQ)
Definition at line 135 of file cra.cpp.
{
  const Ring *Rf = f->get_ring();
  const PolyRing *P = Rf->cast_to_PolyRing();
  const PolyRing *PQ = RQ->cast_to_PolyRing();
  if (P == nullptr)
    {
      ERROR("expected polynomial ring over ZZ");
      return nullptr;
    }
  const FreeModule *F = f->rows();
  const FreeModule *G = f->cols();
  const FreeModule *FQ = PQ->make_FreeModule(F->rank());
  const FreeModule *GQ = PQ->make_FreeModule(G->rank());
  const int *deg;
  deg = Rf->degree_monoid()->make_one();
  MatrixConstructor mat(FQ, GQ, deg);
  for (int i = 0; i < f->n_cols(); i++)
    {
      vec u = ChineseRemainder::ratConversion(f->elem(i), m, PQ);
      mat.set_column(i, u);
    }
  return mat.to_matrix();
}
References Ring::cast_to_PolyRing(), Matrix::cols(), Ring::degree_monoid(), Matrix::elem(), ERROR(), G, Matrix::get_ring(), Ring::make_FreeModule(), Monoid::make_one(), Matrix::n_cols(), FreeModule::rank(), ChineseRemainder::ratConversion(), Matrix::rows(), MatrixConstructor::set_column(), and MatrixConstructor::to_matrix().