Macaulay2 Engine: rawRingElementCRA
rawRingElementCRA()
const RingElement* rawRingElementCRA (const RingElement * f, const RingElement * g, mpz_srcptr m, mpz_srcptr n)
Chinese remainder and rational reconstruction interface routines
Definition at line 14 of file cra.cpp.
 {
   // Assumption: f and g are either in ZZ, or in a polynomial ring whose coeff
   // ring is ZZ.  The output is a ring element in the same ring.
   const Ring *Rf = f->get_ring();
   const Ring *Rg = g->get_ring();
   if (Rf != Rg)
     {
       ERROR("expected same ring");
       return nullptr;
     }
   const PolyRing *P = Rf->cast_to_PolyRing();
   if (P == nullptr)
     {
       // check whether Rf is ZZ.  If not, error.
       if (!Rf->is_ZZ())
         {
           ERROR("expected ZZ, or polynomial ring over ZZ");
           return nullptr;
         }
       ERROR("not implemented yet");
       return nullptr;
     }
   else
     {
       const Ring *K = P->getCoefficientRing();
       if (K->is_ZZ())
         {
           ring_elem rf = f->get_value();
           ring_elem rg = g->get_value();
           ring_elem result = ChineseRemainder::CRA(P, rf, rg, m, n);
           return RingElement::make_raw(Rf, result);
         }
       else
         {
           ERROR("expected coefficient ring to be ZZ");
           return nullptr;
         }
     }
   ERROR("not written yet");
   return nullptr;
 }
References Ring::cast_to_PolyRing(), ChineseRemainder::CRA(), ERROR(), RingElement::get_ring(), RingElement::get_value(), PolynomialRing::getCoefficientRing(), Ring::is_ZZ(), and RingElement::make_raw().