Macaulay2 Engine: GBWalker::make_gb
make_gb()
GBComputation * GBWalker::make_gb (const Matrix * M) const private
Definition at line 84 of file gb-walk.cpp.
 {
   M2_arrayint weights = M2_makearrayint(R->n_vars());
   for (int i = 0; i < R->n_vars(); i++) weights->array[i] = 1;
   GBComputation *G0 = GBComputation::choose_gb(M,
                                                false,  // collect syz
                                                -1,
                                                weights,
                                                false,
                                                -1,
                                                0,
                                                0
                                                /* , max_reduction_count */
                                                );
   G0->set_stop_conditions(false,
                           nullptr,
                           -1,
                           -1,  // syzygy limit
                           -1,
                           -1,
                           -1,
                           false,
                           nullptr);
   return G0;
 }
References GBComputation::choose_gb(), M2_makearrayint(), and Computation::set_stop_conditions().
Referenced by start_computation().