Macaulay2 Engine: GBWalker::start_computation
start_computation()
void GBWalker::start_computation () virtual
Implements GBComputation.
Definition at line 142 of file gb-walk.cpp.
 {
   if (stop_.always_stop) return;  // don't change status
   for (;;) switch (state)
       {
         case STATE_compute_w:
           if (!compute_next_w())
             {
               // We are done!
               state = STATE_done;
               set_status(COMP_DONE);
               return;
             }
           inwwG = G->get_parallel_lead_terms(ww);
           gb_inwwG = make_gb(inwwG);
           state = STATE_do_gb;
         case STATE_do_gb:
           // Now compute the GB object.  If not interrupted, go on:
           gb_inwwG->start_computation();
           if (gb_inwwG->status() == COMP_INTERRUPTED)
             {
               set_status(COMP_INTERRUPTED);
               return;
             }
           next_to_reduce = 0;
           state = STATE_reduce;
         case STATE_reduce:
           while (next_to_reduce < 0)  // TODO: consider the top of the loop
             {
               H = G->matrix_remainder(
                   gb_inwwG->get_gb());  // Not quite: need to subtract...
               next_to_reduce++;
             }
           state = STATE_autoreduce;
         case STATE_autoreduce:
           G->remove_gb();
           delete G;
           G1 = static_cast<MarkedGB *>(
               GBDeclared::create(gb_inwwG->get_initial(-1), H, H, nullptr, nullptr));
           state = STATE_compute_w;
         case STATE_done:
           set_status(COMP_DONE);
           return;
       }
 }
References StopConditions::always_stop, COMP_DONE, COMP_INTERRUPTED, compute_next_w(), GBDeclared::create(), G, G1, gb_inwwG, GBComputation::get_gb(), GBComputation::get_initial(), MarkedGB::get_parallel_lead_terms(), H, inwwG, make_gb(), ReducedGB::matrix_remainder(), next_to_reduce, MarkedGB::remove_gb(), Computation::set_status(), GBComputation::start_computation(), state, STATE_autoreduce, STATE_compute_w, STATE_do_gb, STATE_done, STATE_reduce, Computation::status(), Computation::stop_, and ww.