Macaulay2 Engine: ResMemoryBlock::allocate
allocate()
template<typename T , long int NSLAB> T * ResMemoryBlock< T, NSLAB >::allocate (int len = 1)
Definition at line 110 of file res-memblock.hpp.
 {
   T *result = reserve(len);
   next_free += len;
   return result;
 }
References T.
Referenced by SchreyerFrame::computeIdealQuotient(), SchreyerFrame::insertBasic(), and SchreyerFrame::insertLevelZero().