Macaulay2 Engine: sort_sign
sort_sign()
static int sort_sign (int a, int * v1, int b, int * v2) static
Definition at line 19 of file skew.cpp.
{
  if (a == 0 || b == 0) return 1;
  int result = 0;  // number of sign switches
  a--;
  b--;
  for (;;)
    {
      if (v1[a] < v2[b])
        {
          b--;
          if (b < 0)
            {
              return (result % 2 == 0 ? 1 : -1);
            }
        }
      else if (v1[a] > v2[b])
        {
          result += b + 1;
          a--;
          if (a < 0)
            {
              return (result % 2 == 0 ? 1 : -1);
            }
        }
      else
        return 0;
    }
}
Referenced by SkewMultiplication::diff(), SkewMultiplication::mult_sign(), and SkewMultiplication::mult_sign().