Macaulay2 Engine: main
main()
int main (int argc, char ** argv)
Definition at line 39 of file overflow-test.cpp.
{
  int i, j;
  int s = s0;
  s0 = s;  // use s at least once
  //   use one of these to see if overflows are really detected.  Each one
  //   should generate an overflow and a program termination.
  if (argc > 1)
    {
      if (0 == strcmp(argv[1], "sub"))
        {
          printf("test failed, result %x\n",
                 (unsigned int)safe::sub(0x80000000, 1 - x + x));
          exit(1);
        }
      else if (0 == strcmp(argv[1], "add"))
        {
          printf("test failed, result %x\n",
                 (unsigned int)safe::add(0x7fffffff, 1 - x + x));
          exit(1);
        }
      else if (0 == strcmp(argv[1], "mult"))
        {
          printf("test failed, result %x\n",
                 (unsigned int)safe::mult(0x8000, 0x10000 - x + x));
          exit(1);
        }
      else if (0 == strcmp(argv[1], "div"))
        {
          printf("test failed, result %x\n",
                 (unsigned int)safe::div(0x80000000, -1 - x + x));
          exit(1);
        }
      else if (0 == strcmp(argv[1], "minus"))
        {
          printf("test failed, result %x\n",
                 (unsigned int)safe::minus(0x80000000 - x + x));
          exit(1);
        }
      else if (0 == strcmp(argv[1], "throw"))
        {
          safe::ov("throw overflow exception");
          printf("test failed\n");
          exit(1);
        }
      else
        {
          printf("unknown test: %s\n", argv[1]);
          exit(1);
        }
    }
#define roll 100
  printf("%lld repetitions\n", (long long)inner * outer * roll);
  for (i = outer; i > 0; i--)
    for (j = 0; j < inner; j++)
      {  // 100 times ( == roll, defined above )
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
        {
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt;
          stmt; /* 10 times */
        }
      }
}
References safe::add(), safe::div(), inner, safe::minus(), safe::mult(), outer, safe::ov(), roll, s0, stmt, safe::sub(), and x.