Macaulay2 Engine: Monoid::divides
divides()
bool Monoid::divides (const_monomial m, const_monomial n) const
Definition at line 494 of file monoid.cpp.
 {
   if (mVariableCount == 0) return true;
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
   // can we speed this up by not unpacking ??
   to_expvector(m, EXP1);
   to_expvector(n, EXP2);
   if (numInvertibleVariables() == 0)
     return exponents::divides(mVariableCount, EXP1, EXP2);
   for (int i = 0; i < mVariableCount; ++i)
     if (not mLaurentVariablesPredicate[i] and EXP1[i] > EXP2[i])
       return false;
   return true;
 }
References ALLOCATE_EXPONENTS, and ExponentVector< E, OC >::divides().
Referenced by PolyRing::diff_term(), EngineMonomial::divides(), GBinhom_comp::gb_insert(), and PolyRing::powerseries_division_algorithm().