Macaulay2 Engine: Monoid::to_arrayint
to_arrayint()
M2_arrayint Monoid::to_arrayint (const_monomial monom) const
Definition at line 394 of file monoid.cpp.
 {
   M2_arrayint result = M2_makearrayint(n_vars());
   to_expvector(monom, result->array);
   return result;
 }
References M2_makearrayint(), n_vars(), and to_expvector().
Referenced by IM2_Matrix_get_degree(), and RingElement::multi_degree().