Macaulay2 Engine: Monoid::is_one
is_one()
bool Monoid::is_one (const_monomial m) const
Definition at line 748 of file monoid.cpp.
 {
   for (int i = 0; i < monomial_size(); i++)
     if (*m++ != 0) return false;
   return true;
 }
References monomial_size().
Referenced by res2_poly::elem_text_out(), res_poly::elem_text_out(), PolyRing::elem_text_out(), SchurRing::elem_text_out(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), GBRing::gbvector_text_out(), WeylAlgebra::initialize_weyl(), PolyRing::invert(), PolyRing::is_unit(), QRingInfo_ZZ::QRingInfo_ZZ(), and RingMap::RingMap().