Macaulay2 Engine: Monoid::computeHashValue
computeHashValue()
unsigned int Monoid::computeHashValue (const_monomial m) const
Definition at line 349 of file monoid.cpp.
 {
   unsigned int seed = 0x3124252;
   unsigned int hash = 0x43435728;
   int len = monomial_size();
   for (int i = 0; i < len; i++)
     {
       unsigned int val = *m++;
       hash += seed * val;
       seed = seed + 1342234;
     }
   return hash;
 }
References MutableEngineObject::hash(), and monomial_size().
Referenced by PolynomialRing::computeHashValue().