Macaulay2 Engine: Monoid::from_expvector
from_expvector()
void Monoid::from_expvector (const_exponents exp, monomial result) const
Definition at line 390 of file monoid.cpp.
 {
   monomialOrderEncodeFromActualExponents(monorder_, exp, result);
 }
References mpfr::exp(), monomialOrderEncodeFromActualExponents(), and monorder_.
Referenced by HilbertController::addMonomial(), MatrixStream::appendTermDone(), BRPStoMatrix(), coeffs_of_vec(), PolyRing::diff_term(), PolyRing::divide_by_expvector(), PolyRing::division_algorithm_with_laurent_variables(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), FreeMonoid::FreeMonoid(), SchurRing::from_partition(), from_varpower(), PolyRing::fromSmallIntegerCoefficients(), GBRingSkew::GBRingSkew(), GBRing::gbvector_cancel_lead_terms(), GBRing::gbvector_combine_lead_terms_ZZ(), GBRing::gbvector_term_exponents(), gcd(), PolyRing::get_logical_coeff(), PolyRing::homogenize(), IM2_FreeModule_make_degs(), PolyRing::imp_attempt_to_cancel_lead_term(), KBasis::insert(), Matrix::koszul(), Matrix::koszul_monomials(), lcm(), Matrix::make(), PolyRing::make_logical_term(), Matrix::make_sparse(), Matrix::monomials(), monsyz(), power(), Matrix::remake(), set_degrees(), ResF4toM2Interface::to_M2_freemodule(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), BIBasis::BooleanInvolutiveBasis< MonomType >::ToMatrix(), ResMonomialSorter::toMonomial(), and PolyRing::var().