Macaulay2 Engine: Monoid::to_varpower
to_varpower()
void Monoid::to_varpower (const_monomial m, intarray & result_vp) const
Definition at line 734 of file monoid.cpp.
 {
   exponents EXP1 = ALLOCATE_EXPONENTS(exp_size);
   to_expvector(m, EXP1);
   varpower::from_ntuple(nvars_, EXP1, result_vp);
 }
References ALLOCATE_EXPONENTS, exp_size, varpower::from_ntuple(), nvars_, and to_expvector().
Referenced by convertToFactory(), PolyRing::eval(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), GB_comp::gb_insert(), gb2_comp::gb_insert(), res_comp::insert_res_pair(), Matrix::make_monideal(), makemonideal(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), QRingInfo_field::QRingInfo_field(), and res_comp::skeleton_pairs().