Macaulay2 Engine: Monoid::degree_of_varpower
degree_of_varpower()
void Monoid::degree_of_varpower (const_varpower vp, monomial result) const
Definition at line 690 of file monoid.cpp.
 {
   if (nvars_ == 0) return;
   if (degree_monoid()->n_vars() == 0) return;
   degree_monoid()->one(result);
   monomial mon1 = degree_monoid()->make_one();
   for (index_varpower j = vp; j.valid(); ++j)
     {
       int v = j.var();
       int e = j.exponent();
       degree_monoid()->power(degree_of_var(v), e, mon1);
       degree_monoid()->mult(result, mon1, result);
     }
   degree_monoid()->remove(mon1);
 }
References degree_monoid(), degree_of_var(), make_one(), mult(), n_vars(), nvars_, one(), power(), remove(), and ExponentListIterator< E, L >::valid().
Referenced by hilb_comp::do_ideal(), and hilb_comp::recurse().