Macaulay2 Engine: Monoid::set_degrees
set_degrees()
void Monoid::set_degrees () private
Definition at line 198 of file monoid.cpp.
 {
   if (degree_monoid_ == NULL)
     {
       degree_of_var_.push_back(static_cast<const_monomial>(NULL));
       return;
     }
   // Set 'degree_of_var
   int degvars = degree_monoid_->n_vars();
   int *t = degvals_->array;
   heft_degree_of_var_ = M2_makearrayint(nvars_);
   if (heftvals_->len != degvars)
     {
       ERROR("internal error: heftvals_->len == %d != degvars == %d",
             heftvals_->len,
             degvars);
       return;
     }
   if (degvars > 0)
     for (int i = 0; i < nvars_; i++)
       {
         monomial m = degree_monoid_->make_one();
         degree_monoid_->from_expvector(t, m);
         degree_of_var_.push_back(m);
         heft_degree_of_var_->array[i] = exponents::weight(degvars, t, heftvals_);
         t += degvars;
       }
   else
     {
       for (int i = 0; i < nvars_; i++)
         {
           monomial m = degree_monoid_->make_one();
           degree_monoid_->from_expvector(t, m);
           degree_of_var_.push_back(m);
           heft_degree_of_var_->array[i] = 1;
         }
     }
   degree_of_var_.push_back(degree_monoid_->make_one());
 }
References degree_monoid_, degree_of_var_, degvals_, ERROR(), from_expvector(), heft_degree_of_var_, heftvals_, M2_makearrayint(), make_one(), n_vars(), nvars_, and ExponentVector< E, OC >::weight().
Referenced by Monoid().