Macaulay2 Engine: Monoid::compare
compare() [3/3]
int Monoid::compare (int nslots, const_monomial m, const_monomial n) const inline
Definition at line 164 of file monoid.hpp.
   {
     for (int i = nslots; i != 0; --i)
       {
         if (*m > *n) return GT;
         if (*m < *n) return LT;
         m++;
         n++;
       }
     return EQ;
   }
References EQ, GT, and LT.
Referenced by MarkedGB::add_marked_elems(), check_nterm_multiples(), GBinhom_comp::compare(), EngineMonomial::compare(), res2_poly::compare(), res_poly::compare(), s_pair_heap::compare(), PolyRing::compare_elems(), res2_comp::compare_res2_pairs(), res_comp::compare_res_pairs(), ChineseRemainder::CRA(), gb2_comp::gb_sort_partition(), GBRing::gbvector_is_equal(), GBRing::gbvector_lead_term(), WeylAlgebra::initialize_weyl(), PolyRing::internal_add_to(), FreeModule::is_equal(), PolyRing::is_equal(), is_equal(), PolyRing::lead_term(), MonomialSorterObject::operator()(), and SchreyerOrder::schreyer_compare_encoded().