Macaulay2 Engine: Monoid::from_varpower
from_varpower()
void Monoid::from_varpower (const_varpower vp, monomial result) const
Definition at line 745 of file monoid.cpp.
 {
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   varpower::to_expvector(nvars_, vp, EXP1);
   from_expvector(EXP1, result);
 }
References ALLOCATE_EXPONENTS, exp_size, from_expvector(), nvars_, and varpower::to_expvector().
Referenced by EngineMonomial::compare(), EngineMonomial::divides(), GB_comp::find_pairs(), gb2_comp::find_pairs(), Matrix::make(), binomial_ring::monomial_out(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), res_comp::skeleton_pairs(), and MonomialIdeal::text_out().