Macaulay2 Engine: Monoid::multi_degree
multi_degree()
void Monoid::multi_degree (const_monomial m, monomial result) const
Definition at line 669 of file monoid.cpp.
 {
   if (degree_monoid()->n_vars() == 0) return;
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   degree_monoid()->one(result);
   if (nvars_ == 0) return;
   monomial mon1 = degree_monoid()->make_one();
   to_expvector(m, EXP1);
   for (int i = 0; i < nvars_; i++)
     if (EXP1[i] != 0)
       {
         degree_monoid()->power(degree_of_var(i), EXP1[i], mon1);
         degree_monoid()->mult(result, mon1, result);
       }
   degree_monoid()->remove(mon1);
 }
References ALLOCATE_EXPONENTS, degree_monoid(), degree_of_var(), exp_size, make_one(), mult(), n_vars(), nvars_, one(), power(), remove(), and to_expvector().
Referenced by GBRing::gbvector_multidegree(), PolyRing::is_homogeneous(), res2_comp::multi_degree(), res_comp::multi_degree(), and PolyRing::multi_degree().