Macaulay2 Engine: Monoid::n_slots
n_slots()
int Monoid::n_slots (int nparts) const
Definition at line 430 of file monoid.cpp.
 {
   if (nparts == 0 or num_parts() == 0) return 0;
   nparts--;
   if (nparts < 0) return monomial_size();
   if (nparts >= num_parts()) nparts = num_parts() - 1;
   return nslots_[nparts];
 }
References monomial_size(), nslots_, and num_parts().
Referenced by Matrix::elim_keep(), Matrix::elim_vars(), GBRing::gbvector_lead_term(), PolyRing::lead_term(), and sagbi::subduct().