Macaulay2 Engine: Monoid::mult
mult()
void Monoid::mult (const_monomial m, const_monomial n, monomial result) const
Definition at line 365 of file monoid.cpp.
 {
   overflow_type *t = overflow;
   for (int i = monomial_size_; i != 0; i--) switch (*t++)
       {
         case OVER:
           *result++ = safe::add(*m++, *n++);
           break;
         case OVER1:
           *result++ = safe::pos_add(*m++, *n++);
           break;
         case OVER2:
           *result++ = safe::pos_add_2(*m++, *n++);
           break;
         case OVER4:
           *result++ = safe::pos_add_4(*m++, *n++);
           break;
         default:
           throw(exc::internal_error("missing case"));
       }
 }
References safe::add(), monomial_size_, OVER, OVER1, OVER2, OVER4, overflow, safe::pos_add(), safe::pos_add_2(), and safe::pos_add_4().
Referenced by SchreyerOrder::create(), degree_of_expvector(), degree_of_varpower(), RingMap::eval_term(), res2_poly::from_vector(), res_poly::from_vector(), GBRing::gbvector_multidegree(), res2_poly::mult_by_monomial(), res_poly::mult_by_monomial(), res2_poly::mult_by_term(), res_poly::mult_by_term(), GBRingSkew::mult_by_term1(), FreeMonoid::multi_degree(), res2_comp::multi_degree(), res_comp::multi_degree(), multi_degree(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), res2_poly::ring_mult_by_term(), res_poly::ring_mult_by_term(), SchreyerOrder::schreyer_up(), res_comp::skeleton_pairs(), SchreyerOrder_symm::symm1(), FreeModule_symm::symm1(), ResF4toM2Interface::to_M2_freemodule(), and Ring::vec_is_homogeneous().