Macaulay2 Engine: Monoid::make_new
make_new()
monomial Monoid::make_new (const_monomial d) const
Definition at line 450 of file monoid.cpp.
 {
   if (mVariableCount == 0) return nullptr;
   monomial result = newarray_atomic(int, monomial_size());
   copy(d, result);
   return result;
 }
References copy(), monomial_size(), mVariableCount, and newarray_atomic.
Referenced by FreeModule::append(), FreeModule::append_schreyer(), DetComputation::DetComputation(), res_comp::initialize(), MatrixConstructor::MatrixConstructor(), Matrix::mult(), GB_comp::new_gen(), GBinhom_comp::new_gen(), res_comp::new_res_pair(), GB_comp::new_ring_pair(), GBinhom_comp::new_ring_pair(), gb2_comp::new_ring_pair(), GB_comp::new_s_pair(), GBinhom_comp::new_s_pair(), gb2_comp::new_s_pair(), RingMap::RingMap(), SymmMatrix::SymmMatrix(), and ResF4toM2Interface::to_M2_freemodule().