Macaulay2 Engine: Monoid::degree_weights
degree_weights() [2/2]
template<typename T > T Monoid::degree_weights (const_monomial m, const std::vector< T > & wts) const
Definition at line 684 of file monoid.cpp.
 {
   if (mVariableCount == 0) return 0;
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   to_expvector(m, EXP1);
   int sz = (wts.size() < mVariableCount ? wts.size() : mVariableCount);
   T wt = 0;
   for (int i=0; i<sz; i++)
     wt += EXP1[i] * wts[i];
   return wt;
 }
References ALLOCATE_EXPONENTS, exp_size, mVariableCount, T, and to_expvector().
Referenced by PolyRing::degree_weights(), primary_degree(), and FreeModule::primary_degree().