Macaulay2 Engine: Monoid::get_trivial_monoid
get_trivial_monoid()
Monoid * Monoid::get_trivial_monoid () static
Definition at line 55 of file monoid.cpp.
 {
   if (trivial_monoid == 0) trivial_monoid = new Monoid;
   return trivial_monoid;
 }
References Monoid(), and trivial_monoid.
Referenced by IM2_Monoid_trivial(), PolyRing::make_trivial_ZZ_poly_ring(), and set_trivial_monoid_degree_ring().