Macaulay2 Engine: Monoid::numInvertibleVariables
numInvertibleVariables()
int Monoid::numInvertibleVariables () const inline
Definition at line 138 of file monoid.hpp.
 { return n_invertible_vars_; }
References n_invertible_vars_.
Referenced by gbA::create(), IM2_Ring_frac(), and PolyRing::remainderAndQuotient().