Macaulay2 Engine: Monoid::one
one()
void Monoid::one (monomial result) const
Definition at line 513 of file monoid.cpp.
 {
   for (int i = 0; i < monomial_size(); i++) *result++ = 0;
 }
References monomial_size().
Referenced by SchreyerOrder::create(), Ring::degree(), degree_of_expvector(), degree_of_varpower(), PolyRing::from_int(), PolyRing::from_long(), PolyRing::from_rational(), PolyRing::fromCoefficient(), GBRing::gbvector_term(), PolyRing::invert(), make_one(), FreeMonoid::multi_degree(), multi_degree(), and PolyRing::preferred_associate().