Macaulay2 Engine: Monoid::monomial_size
monomial_size()
int Monoid::monomial_size () const inline
Definition at line 156 of file monoid.hpp.
 { return monomial_size_; }
References monomial_size_.
Referenced by computeHashValue(), copy(), GBKernelComputation::GBKernelComputation(), GBRing::GBRing(), res2_comp::initialize(), res_comp::initialize(), PolyRing::initialize_poly_ring(), is_one(), make_new(), make_one(), GBRingPoly::mult_by_term1(), n_slots(), one(), QRingInfo::QRingInfo(), res2_poly::res2_poly(), res_poly::res_poly(), SchreyerOrder::schreyer_compare(), and ResMonomialSorter::setMonoms().