Macaulay2 Engine: Monoid::to_expvector
to_expvector()
void Monoid::to_expvector (const_monomial m, exponents_t result_exp) const
Definition at line 748 of file monoid.cpp.
 {
   monomialOrderDecodeToActualExponents(monorder_, m, result_exp);
 }
References monomialOrderDecodeToActualExponents(), and monorder_.
Referenced by SkewPolynomialRing::antipode(), BRPSfromMatrix(), hilb_comp::coeff_of(), Matrix::coeffs(), coeffs_of_vec(), res2_comp::compare_res2_pairs(), res_comp::compare_res_pairs(), KBasis::compute(), PolyRing::degree_of_var(), degree_weights(), PolyRing::diff_term(), PolyRing::divide_by_expvector(), elem_text_out(), BIBasis::BooleanInvolutiveBasis< MonomType >::FillInitialSet(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), ResF4toM2Interface::from_M2_vec(), F4toM2Interface::from_M2_vec(), GBinhom_comp::gb_insert(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_parallel_lead_terms(), gcd(), GBKernelComputation::geo_reduce(), PolyRing::get_coeff(), PolyRing::get_part(), PolyRing::get_terms(), PolyRing::homogenize(), PolyRing::imp_attempt_to_cancel_lead_term(), PolyRing::index_of_var(), KBasis::KBasis(), Matrix::koszul(), Matrix::koszul_monomials(), lcm(), PolyRing::lead_logical_exponents(), PolyRing::list_form(), PolyRing::make_logical_term(), matrixToStream(), GBWeight::monomial_weight(), Matrix::monomials(), monsyz(), GBRingSkew::mult_by_term1(), multi_degree(), PolyRing::n_logical_terms(), QRingInfo_field_basic::normal_form(), QRingInfo_field_QQ::normal_form(), QRingInfo_ZZ::normal_form(), partial_compare(), power(), GF::promote(), M2::ARingGFGivaro::promote(), QRingInfo_field::QRingInfo_field(), QRingInfo_ZZ::QRingInfo_ZZ(), rawRoots(), GBKernelComputation::reduce(), res2_comp::reduce(), res_comp::reduce(), res2_comp::reduce2(), res2_comp::reduce3(), res2_comp::reduce4(), res2_comp::reduce_by_level(), res_comp::reduce_gen(), res2_comp::reduce_heap_by_level(), QRingInfo_field_basic::reduce_lead_term_basic_field(), QRingInfo_field_QQ::reduce_lead_term_QQ(), QRingInfo_ZZ::reduce_lead_term_ZZ(), res_comp::reduce_level_one(), PolyRing::setNegativeExponentMonomial(), simple_degree(), res2_comp::sort_value(), res_comp::sort_value(), Matrix::support(), PolyRing::support(), to_degree_vector(), to_varpower(), Tower::translate(), and Ring::vec_remove_monomial_factors().