Macaulay2 Engine: Monoid::degree_of_expvector
degree_of_expvector()
template<typename T > void Monoid::degree_of_expvector (const T * expvector, monomial result) const inline
Definition at line 233 of file monoid.hpp.
   {
     degree_monoid()->one(result);
     monomial mon1 = degree_monoid()->make_one();
     for (int i=0; i<n_vars(); i++)
       {
         if (expvector[i] != 0)
           {
             degree_monoid()->power(degree_of_var(i), expvector[i], mon1);
             degree_monoid()->mult(result, mon1, result);
           }
       }
     degree_monoid()->remove(mon1);
   }
References degree_monoid(), degree_of_var(), make_one(), mult(), n_vars(), one(), power(), and remove().
Referenced by ResF4toM2Interface::to_M2_freemodule().