Macaulay2 Engine: Monoid::elem_text_out
elem_text_out()
void Monoid::elem_text_out (buffer & o, const_monomial m, bool p_one = true) const
Definition at line 574 of file monoid.cpp.
 {
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   to_expvector(m, EXP1);
 //   elem_text_out(o, EXP1, p_one);
 // }
 // void Monoid::elem_text_out(buffer &o, const_exponents EXP1, bool p_one) const
 // {
   int len_ = 0;
   for (unsigned int v = 0; v < mVariableCount; v++)
     if (EXP1[v] != 0)
       {
         len_++;
         if (mVariableNames.size() < v)
           o << ".";
         else
           o << mVariableNames[v];
         int e = EXP1[v];
         int single = (mVariableNames[v].size() == 1);
         if (e > 1 && single)
           o << e;
         else if (e > 1)
           o << "^" << e;
         else if (e < 0)
           o << "^(" << e << ")";
       }
   if (len_ == 0 && p_one) o << "1";
 }
References ALLOCATE_EXPONENTS, exp_size, mVariableCount, mVariableNames, and to_expvector().
Referenced by GBinhom_comp::debug_out(), gb2_comp::debug_out(), GB_comp::debug_out(), res2_poly::elem_text_out(), res_poly::elem_text_out(), PolyRing::elem_text_out(), GBRing::gbvector_text_out(), binomial_ring::monomial_out(), MonomialSorterObject::operator()(), MonomialIdeal::text_out(), SchreyerOrder::text_out(), res2_comp::text_out(), and res_comp::text_out().