Macaulay2 Engine: Monoid::lcm
lcm()
void Monoid::lcm (const_monomial m, const_monomial n, monomial result) const
Definition at line 604 of file monoid.cpp.
 {
   if (nvars_ == 0) return;
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
   to_expvector(m, EXP1);
   to_expvector(n, EXP2);
   exponents::lcm(nvars_, EXP1, EXP2, EXP1);
   from_expvector(EXP1, p);
 }
References ALLOCATE_EXPONENTS, exp_size, from_expvector(), ExponentVector< E, OC >::lcm(), nvars_, p, and to_expvector().
Referenced by GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), and FreeAlgebra::multi_degree().