Macaulay2 Engine: Monoid::n_vars
n_vars()
int Monoid::n_vars () const inline
Definition at line 143 of file monoid.hpp.
 { return nvars_; }
References nvars_.
Referenced by coeffs_of_vec(), res2_comp::compare_res2_pairs(), res_comp::compare_res_pairs(), degree_of_expvector(), degree_of_varpower(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), FreeMonoid::FreeMonoid(), ResF4toM2Interface::from_M2_vec(), F4toM2Interface::from_M2_vec(), GB_comp::gb_geo_reduce(), GBinhom_comp::gb_geo_reduce(), gb2_comp::gb_geo_reduce(), GBinhom_comp::gb_insert(), GB_comp::gb_reduce(), GBinhom_comp::gb_reduce(), gb2_comp::gb_reduce(), GBKernelComputation::GBKernelComputation(), GBRingSkew::GBRingSkew(), PolyRing::get_part(), getFirstWeightVector(), IM2_FreeModule_get_degrees(), IM2_FreeModule_make_degs(), gbA::initialize(), PolynomialRing::initialize_PolynomialRing(), FreeModule::is_equal(), KBasis::k_basis(), KBasis::KBasis(), Matrix::koszul(), Matrix::koszul_monomials(), Matrix::make(), PolyRing::make_logical_term(), Matrix::make_monideal(), Monoid(), Matrix::monomials(), PolyRing::multi_degree(), multi_degree(), ncBasis(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), GBinhom_comp::search(), FreeModule::select_by_degrees(), set_degrees(), res_comp::skeleton_pairs(), text_out(), to_arrayint(), ResF4toM2Interface::to_M2_freemodule(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), and ResMonomialSorter::toMonomial().