Macaulay2 Engine: Monoid::degree_monoid
degree_monoid()
const Monoid * Monoid::degree_monoid () const inline
Definition at line 124 of file monoid.hpp.
{ return mDegreeMonoid; }
References mDegreeMonoid.
Referenced by GBRing::gbvector_multidegree(), res_comp::multi_degree(), ResF4toM2Interface::to_M2_freemodule(), and ResF4toM2Interface::to_M2_freemodule().