Macaulay2 Engine: Monoid::numNonTermOrderVariables
numNonTermOrderVariables()
int Monoid::numNonTermOrderVariables () const inline
Definition at line 139 of file monoid.hpp.
 { return local_vars.size(); }
References local_vars.
Referenced by gbA::create(), ReducedGB::create(), IM2_Ring_frac(), gbA::initialize(), FractionField::initialize_frac(), PolyRingQuotient::invert(), and PolyRing::remainderAndQuotient().