Macaulay2 Engine: Monoid::create
create() [2/2]
Monoid * Monoid::create (const MonomialOrdering * mo, M2_ArrayString names, const PolynomialRing * DR, M2_arrayint degs, M2_arrayint hefts) static
Definition at line 62 of file monoid.cpp.
 {
   unsigned int nvars = rawNumberOfVariables(mo);
   ;
   unsigned int eachdeg = deg_ring->n_vars();
   if (degs->len != nvars * eachdeg)
     {
       ERROR("degree list should be of length %d", nvars * eachdeg);
       return 0;
     }
   if (nvars != names->len)
     {
       ERROR("expected %d variable names", nvars);
       return 0;
     }
   return new Monoid(mo, names, deg_ring, degs, hefts);
 }
References ERROR(), Monoid(), PolynomialRing::n_vars(), and rawNumberOfVariables().
Referenced by create(), degreeMonoid(), and IM2_Monoid_make().