Macaulay2 Engine: Monoid::degree_of_var
degree_of_var()
const_monomial Monoid::degree_of_var (int v) const inline
Definition at line 110 of file monoid.hpp.
 { return degree_of_var_[v]; }
References degree_of_var_.
Referenced by degree_of_expvector(), degree_of_varpower(), hilb_comp::do_ideal(), WeylAlgebra::initialize_weyl(), KBasis::KBasis(), and multi_degree().