Macaulay2 Engine: Monoid::power
power()
void Monoid::power (const_monomial m, int n, monomial result) const
Definition at line 512 of file monoid.cpp.
 {
   if (mVariableCount == 0) return;
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   to_expvector(m, EXP1);
   exponents::power(mVariableCount, EXP1, n, EXP1);
   from_expvector(EXP1, result);
 }
References ALLOCATE_EXPONENTS, exp_size, from_expvector(), mVariableCount, ExponentVector< E, OC >::power(), and to_expvector().
Referenced by degree_of_expvector(), degree_of_varpower(), DetComputation::DetComputation(), hilb_comp::do_ideal(), RingMap::eval_term(), PolyRing::invert(), multi_degree(), PolyRing::power(), PolyRing::power_direct(), and SymmMatrix::SymmMatrix().