Macaulay2 Engine: Monoid::Monoid
Monoid() [2/2]
Monoid::Monoid (const MonomialOrdering * mo, M2_ArrayString names, const PolynomialRing * DR, M2_arrayint degs, M2_arrayint hefts) private
Definition at line 98 of file monoid.cpp.
     : nvars_(rawNumberOfVariables(mo)),
       varnames_(names),
       degvals_(degs),
       heftvals_(hefts),
       heft_degree_of_var_(nullptr), // set below, except in the trivial case.
       degree_ring_(deg_ring),
       degree_monoid_(deg_ring->getMonoid()),
       mo_(mo),
       monorder_(nullptr), // set below
       overflow(0),
       exp_size(0), // set below
       monomial_size_(0), // set below
       monomial_bound_(0),
       n_invertible_vars_(0), // set below
       n_before_component_(0), // set below
       n_after_component_(0), // set below
       component_up_(true), // set below
       local_vars(nullptr), // set below
       first_weights_slot_(-1) // set below
       // nslots: set below
 {
   monorder_ = monomialOrderMake(mo);
   monomial_size_ = monorder_->nslots;
   n_before_component_ = monorder_->nslots_before_component;
   n_after_component_ = monomial_size_ - n_before_component_;
   component_up_ = monorder_->component_up;
   // Set nslots_
   int total = 0;
   for (int i = 0; i < monorder_->nblocks; i++)
     {
       total += monorder_->blocks[i].nslots;
       nslots_.push_back(total);
     }
   // Set first_weight_value_
   bool get_out = false;
   first_weights_slot_ = -1;
   for (int i = 0; i < monorder_->nblocks && !get_out; i++)
     {
       switch (monorder_->blocks[i].typ)
         {
           case MO_LEX:
           case MO_LEX2:
           case MO_LEX4:
           case MO_NC_LEX:
             get_out = true;
             break;
           case MO_REVLEX:
           case MO_LAURENT:
           case MO_LAURENT_REVLEX:
           case MO_GREVLEX:
           case MO_GREVLEX2:
           case MO_GREVLEX4:
           case MO_GREVLEX_WTS:
           case MO_GREVLEX2_WTS:
           case MO_GREVLEX4_WTS:
           case MO_WEIGHTS:
             first_weights_slot_ = 0;
           case MO_POSITION_UP:
             continue;
           case MO_POSITION_DOWN:
             continue;
           default:
             INTERNAL_ERROR("monomial order block type not handled");
         }
     }
   exp_size = EXPONENT_BYTE_SIZE(nvars_);
   n_invertible_vars_ = rawNumberOfInvertibleVariables(mo_);
   set_degrees();
   set_overflow_flags();
   local_vars = rawNonTermOrderVariables(mo);
   for (int i=0; i<n_vars(); ++i)
     {
       bool isLaurent = isLaurentVariable(i);
       mLaurentVariablesPredicate.push_back(isLaurent);
     }
   // Debugging only:
   //  fprintf(stderr, "%d variables < 1\n", local_vars->len);
   //  if (local_vars->len > 0)
   //    {
   //      fprintf(stderr, "they are: ");
   //      for (int i=0; i<local_vars->len; i++)
   //      fprintf(stderr, "%d ", local_vars->array[i]);
   //      fprintf(stderr, "\n");
   //    }
 }
References component_up_, exp_size, EXPONENT_BYTE_SIZE, first_weights_slot_, INTERNAL_ERROR(), isLaurentVariable(), local_vars, mLaurentVariablesPredicate, mo_, MO_GREVLEX, MO_GREVLEX2, MO_GREVLEX2_WTS, MO_GREVLEX4, MO_GREVLEX4_WTS, MO_GREVLEX_WTS, MO_LAURENT, MO_LAURENT_REVLEX, MO_LEX, MO_LEX2, MO_LEX4, MO_NC_LEX, MO_POSITION_DOWN, MO_POSITION_UP, MO_REVLEX, MO_WEIGHTS, monomial_size_, monomialOrderMake(), monorder_, n_after_component_, n_before_component_, n_invertible_vars_, n_vars(), nslots_, nvars_, rawNonTermOrderVariables(), rawNumberOfInvertibleVariables(), set_degrees(), and set_overflow_flags().