Macaulay2 Engine: Monoid::divide
divide()
void Monoid::divide (const_monomial m, const_monomial n, monomial result) const inline
Definition at line 269 of file monoid.hpp.
 {
   for (int i = monomial_size_; i > 0; i--) *result++ = *m++ - *n++;
 }
References monomial_size_.
Referenced by GB_comp::compute_s_pair(), GBinhom_comp::compute_s_pair(), gb2_comp::compute_s_pair(), GBinhom_comp::debug_out(), FractionField::degree(), LocalRing::degree(), Matrix::diff(), PolyRing::diff_term(), GBinhom_comp::find_pairs(), GBRing::find_reduction_monomial(), GBKernelComputation::geo_reduce(), PolyRing::imp_attempt_to_cancel_lead_term(), Matrix::is_homogeneous(), FractionField::multi_degree(), LocalRing::multi_degree(), res2_comp::new_pairs(), res_comp::new_pairs(), GBKernelComputation::reduce(), res2_comp::reduce(), res_comp::reduce(), res2_comp::reduce2(), res2_comp::reduce3(), res2_comp::reduce4(), res2_comp::reduce_by_level(), res_comp::reduce_gen(), res2_comp::reduce_heap_by_level(), QRingInfo_field_basic::reduce_lead_term_basic_field(), QRingInfo_field_QQ::reduce_lead_term_QQ(), QRingInfo_ZZ::reduce_lead_term_ZZ(), res_comp::reduce_level_one(), res2_comp::reduce_minimal(), res_comp::reduce_minimal(), res2_comp::s_pair(), SchreyerOrder::schreyer_down(), res_comp::skeleton_pairs(), SchreyerOrder_symm::symm1(), FreeModule_symm::symm1(), res2_poly::to_vector(), and res_poly::to_vector().