Macaulay2 Engine: Monoid::text_out
text_out()
void Monoid::text_out (buffer & o) const
Definition at line 305 of file monoid.cpp.
 {
   int i;
   o << "[";
   for (i = 0; i < mVariableCount - 1; i++) o << mVariableNames[i] << ",";
   if (mVariableCount > 0) o << mVariableNames[mVariableCount - 1];
   int degrk = mDegreeMonoid->n_vars();
   o << "," << newline << "  DegreeLength => " << degrk;
   o << "," << newline << "  Degrees => {";
   for (i = 0; i < mVariableCount; i++)
     {
       if (i != 0) o << ", ";
       if (degrk != 1) o << '{';
       for (int j = 0; j < degrk; j++)
         {
           if (j != 0) o << ", ";
           o << mDegrees[i * degrk + j];
         }
       if (degrk != 1) o << '}';
     }
   o << "}";
   if (mHeftVector.size() != 0)
     {
       o << "," << newline << "  Heft => {";
       for (i = 0; i < mHeftVector.size(); i++)
         {
           if (i != 0) o << ", ";
           o << mHeftVector[i];
         }
       o << "}";
     }
   if (mo_ != nullptr)
     {
       o << "," << newline << "  ";
       o << IM2_MonomialOrdering_to_string(mo_);
     }
   o << newline << "  ]";
 }
References IM2_MonomialOrdering_to_string(), mDegreeMonoid, mDegrees, mHeftVector, mo_, mVariableCount, mVariableNames, n_vars(), and newline.
Referenced by rawMonoidToString(), PolyRing::text_out(), SchurRing::text_out(), SkewPolynomialRing::text_out(), and WeylAlgebra::text_out().