Macaulay2 Engine: Monoid::primary_degree
primary_degree()
int Monoid::primary_degree (const_monomial m) const
Definition at line 666 of file monoid.cpp.
 {
   return degree_weights(m, primary_degree_of_vars());
 }
References degree_weights(), and primary_degree_of_vars().
Referenced by res_comp::degree(), M2::GaloisFieldTable::GaloisFieldTable(), GF::initialize_GF(), res2_comp::new_res2_pair(), gb2_comp::new_ring_pair(), and gb2_comp::new_s_pair().