Macaulay2 Engine: Monoid::remove
remove()
void Monoid::remove (monomial d) const
Definition at line 506 of file monoid.cpp.
 {
 #if 0
 //   freemem(d);
 #endif
 }
Referenced by MatrixConstructor::append(), coeffs_of_vec(), EngineMonomial::compare(), MatrixConstructor::compute_column_degree(), GB_comp::compute_s_pair(), GBinhom_comp::compute_s_pair(), gb2_comp::compute_s_pair(), SchreyerOrder::create(), GBinhom_comp::debug_out(), FractionField::degree(), LocalRing::degree(), degree_of_expvector(), degree_of_varpower(), DetComputation::DetComputation(), Matrix::diff(), EngineMonomial::divides(), RingMap::eval_term(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), res2_comp::free_of(), res_comp::free_of(), FreeModule::FreeModule(), GB_comp::gb_insert(), gb2_comp::gb_insert(), GBinhom_comp::gb_insert(), Matrix::is_homogeneous(), FreeAlgebra::is_homogeneous(), Matrix::make(), res2_comp::minimal_free_of(), res_comp::minimal_free_of(), binomial_ring::monomial_out(), Matrix::monomials(), Matrix::mult(), FreeAlgebra::multi_degree(), FractionField::multi_degree(), LocalRing::multi_degree(), multi_degree(), res2_comp::new_base_res2_pair(), GB_comp::remove_pair(), GBinhom_comp::remove_pair(), gb2_comp::remove_pair(), res_comp::remove_res_pair(), GBKernelComputation::s_pair(), res2_comp::s_pair(), gb2_comp::schreyer_append(), gbres_comp::setup(), Matrix::tensor(), MonomialIdeal::text_out(), ResF4toM2Interface::to_M2_freemodule(), res2_poly::to_vector(), res_poly::to_vector(), FreeModule::transpose(), FreeModule_symm::value(), SchreyerOrder_symm::value(), Ring::vec_is_homogeneous(), hilb_comp::~hilb_comp(), and RingMap::~RingMap().