Macaulay2 Engine: Monoid::copy
copy()
void Monoid::copy (const_monomial m, monomial result) const
Definition at line 476 of file monoid.cpp.
 {
   memcpy(result, m, monomial_size() * sizeof(int));
 }
References monomial_size().
Referenced by SkewPolynomialRing::antipode(), FreeModule::change_degree(), res2_poly::copy(), res_poly::copy(), PolyRing::copy_term(), ChineseRemainder::CRA(), SchreyerOrder::create(), PolyRing::divide_by_given_content(), res2_poly::from_vector(), res_poly::from_vector(), GBRing::gbvector_copy_term(), GBRing::gbvector_get_lead_monomial(), GBRing::gbvector_raw_term(), res_comp::handle_gen(), PolyRing::lead_term(), PolyRing::make_flat_term(), make_new(), PolyRing::minimal_monomial(), res2_poly::mult_by_coefficient(), PolyRing::negate(), ChineseRemainder::ratConversion(), res2_poly::strip(), res_poly::strip(), and PolyRing::zeroize_tiny().