Macaulay2 Engine: Monoid::create
create() [1/2]
Monoid * Monoid::create (const MonomialOrdering * mo, const std::vector< std::string > & names, const PolynomialRing * DR, const std::vector< int > & degs, const std::vector< int > & hefts) static
Definition at line 85 of file monoid.cpp.
 {
   return create(mo,
                 stdvector_to_M2_ArrayString(names),
                 DR,
                 stdvector_to_M2_arrayint(degs),
                 stdvector_to_M2_arrayint(hefts));
 }
References create(), stdvector_to_M2_arrayint(), and stdvector_to_M2_ArrayString().