Macaulay2 Engine: Monoid::create
create()
Monoid * Monoid::create (const MonomialOrdering * mo, const PolynomialRing * DR, const std::vector< std::string > & names, const std::vector< int > & degs, const std::vector< int > & hefts) static
Definition at line 61 of file monoid.cpp.
{
  unsigned int nvars = rawNumberOfVariables(mo);
  unsigned int degrk = deg_ring->n_vars();
  if (degs.size() != nvars * degrk)
    {
      ERROR("degree list should be of length %d", nvars * degrk);
      return nullptr;
    }
  if (names.size() != nvars)
    {
      ERROR("expected %d variable names", nvars);
      return nullptr;
    }
  return new Monoid(mo, deg_ring, names, degs, hefts);
}
References ERROR(), Monoid(), PolynomialRing::n_vars(), and rawNumberOfVariables().
Referenced by degreeMonoid(), rawMonoid(), simplePolynomialRing(), and TEST().