Macaulay2 Engine: Monoid::make_one
make_one()
monomial Monoid::make_one () const
Definition at line 499 of file monoid.cpp.
 {
   if (nvars_ == 0) return NULL;
   monomial result = newarray_atomic(int, monomial_size());
   one(result);
   return result;
 }
References monomial_size(), newarray_atomic, nvars_, and one().
Referenced by HilbertController::addMonomial(), MatrixConstructor::append(), BRPStoMatrix(), coeffs_of_vec(), EngineMonomial::compare(), MatrixConstructor::compute_column_degree(), GB_comp::compute_s_pair(), GBinhom_comp::compute_s_pair(), gb2_comp::compute_s_pair(), ChineseRemainder::CRA(), SchreyerOrder::create(), GBinhom_comp::debug_out(), FractionField::degree(), LocalRing::degree(), degree_of_expvector(), degree_of_varpower(), Matrix::diff(), EngineMonomial::divides(), PolyRing::division_algorithm(), PolyRing::division_algorithm_with_laurent_variables(), RingMap::eval_term(), GB_comp::find_pairs(), GBinhom_comp::find_pairs(), gb2_comp::find_pairs(), res2_comp::free_of(), res_comp::free_of(), FreeModule::FreeModule(), FreeMonoid::FreeMonoid(), GB_comp::gb_insert(), gb2_comp::gb_insert(), GBinhom_comp::gb_insert(), GBRingSkew::GBRingSkew(), GBRing::gbvector_multidegree(), hilb_comp::hilb_comp(), IM2_FreeModule_make_degs(), res_comp::initialize(), WeylAlgebra::initialize_weyl(), Matrix::is_homogeneous(), FreeAlgebra::is_homogeneous(), KBasis::KBasis(), Matrix::koszul(), Matrix::koszul_monomials(), Matrix::make(), PolyRing::make_logical_term(), FreeModule::make_schreyer(), Matrix::make_sparse(), MatrixConstructor::MatrixConstructor(), res2_comp::minimal_free_of(), res_comp::minimal_free_of(), binomial_ring::monomial_out(), Matrix::monomials(), FreeAlgebra::multi_degree(), FractionField::multi_degree(), LocalRing::multi_degree(), multi_degree(), res2_comp::new_base_res2_pair(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_res_pair(), Matrix::operator+(), Matrix::operator-(), PolyRing::power_direct(), PolyRing::random(), rawMatrixRatConversion(), Matrix::remake(), GBKernelComputation::s_pair(), res2_comp::s_pair(), Matrix::scalar_mult(), gb2_comp::schreyer_append(), set_degrees(), gbres_comp::setup(), MonomialIdeal::text_out(), ResF4toM2Interface::to_M2_freemodule(), ResF4toM2Interface::to_M2_MutableMatrix(), ResF4toM2Interface::to_M2_vec(), F4toM2Interface::to_M2_vec(), res2_poly::to_vector(), res_poly::to_vector(), BIBasis::BooleanInvolutiveBasis< MonomType >::ToMatrix(), FreeModule::transpose(), FreeModule_symm::value(), SchreyerOrder_symm::value(), and Ring::vec_is_homogeneous().