Macaulay2 Engine: parseBasicPoly
parseBasicPoly() [2/2]
BasicPoly parseBasicPoly (std::string poly, std::vector< std::string > varnames)
Definition at line 200 of file BasicPolyListParser.cpp.
{
  std::string_view str { poly};
  IdentifierHash idenMap {varnames};
  BasicPoly result;
  parseBasicPoly(str, idenMap, result);
  return result;
}
References parseBasicPoly().
Referenced by TEST(), and TEST().