Macaulay2 Engine: rawPowerMod
rawPowerMod()
const RingElement* rawPowerMod (const RingElement * f, mpz_srcptr n, const RingElement * g)
Definition at line 959 of file ringelement.cpp.
 {
   const Tower *R = f->get_ring()->cast_to_Tower();
   if (R == 0)
     {
       ERROR("not implemented for this ring");
       return 0;
     }
   if (g->get_ring() != R)
     {
       ERROR("expected elements in the same ring");
       return 0;
     }
   return RingElement::make_raw(R,
                                R->power_mod(f->get_value(), n, g->get_value()));
 }
References Ring::cast_to_Tower(), ERROR(), RingElement::get_ring(), RingElement::get_value(), RingElement::make_raw(), and Tower::power_mod().