Macaulay2 Engine: IM2_RingElement_to_Integer
IM2_RingElement_to_Integer()
gmp_ZZorNull IM2_RingElement_to_Integer (const RingElement * a)
Definition at line 88 of file ringelement.cpp.
 {
   const Ring *R = a->get_ring();
   if (R->is_ZZ())
     {
       // Note: RingElement ZZ elements are on the "gc" side of the memory barrier, and
       // are read only.  Therefore we can just return the same value.
       return a->get_value().get_mpz();
     }
   if (R->isFinitePrimeField())
     {
       mpz_ptr result = newitem(__mpz_struct);
       std::pair<bool, long> res = R->coerceToLongInteger(a->get_value());
       assert(res.first);
       mpz_init_set_si(result, static_cast<int>(res.second));
       mpz_reallocate_limbs(result);
       return result;
     }
   ERROR("Expected ZZ or ZZ/p as base ring");
   return nullptr;
 }
References Ring::coerceToLongInteger(), ERROR(), ring_elem::get_mpz(), RingElement::get_ring(), RingElement::get_value(), Ring::is_ZZ(), Ring::isFinitePrimeField(), mpz_reallocate_limbs(), and newitem.