Macaulay2 Engine: rawRingElementCompare
rawRingElementCompare()
int rawRingElementCompare (const RingElement * a, const RingElement * b)
Definition at line 288 of file ringelement.cpp.
 {
   try
     {
       const Ring *R = a->get_ring();
       if (R != b->get_ring()) return 0;
       //  if (a->is_zero())
       //    {
       //      if (b->is_zero()) return 0;
       //      return 1;
       //    }
       //  if (b->is_zero()) return -1;
       return R->compare_elems(a->get_value(), b->get_value());
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return -2;
   }
 }
References Ring::compare_elems(), ERROR(), RingElement::get_ring(), and RingElement::get_value().