Macaulay2 Engine: IM2_RingElement_term
IM2_RingElement_term()
const RingElement* IM2_RingElement_term (const Ring * R, const RingElement * a, const EngineMonomial * m)
Definition at line 433 of file ringelement.cpp.
 {
   try {
     const PolynomialRing *P = R->cast_to_PolynomialRing();
     if (P != nullptr)
       {
         int nvars0 = P->n_vars();
         const PolynomialRing *K = a->get_ring()->cast_to_PolynomialRing();
         if (K != nullptr && K != P->getCoefficients()) nvars0 -= K->n_vars();
         exponents_t exp = newarray_atomic(int, nvars0);
         varpower::to_expvector(nvars0, m->ints(), exp);
         ring_elem val = P->make_logical_term(a->get_ring(), a->get_value(), exp);
         return RingElement::make_raw(R,val);
       }
     auto Q = dynamic_cast<const M2FreeAlgebraOrQuotient *>(R);
     if (Q != nullptr)
       {
         if (Q->coefficientRing() != a->get_ring())
           {
             ERROR("wrong coefficient ring");
             return nullptr;
           }
         return RingElement::make_raw(Q,
                                      Q->makeTerm(a->get_value(),
                                                  m->ints()));
       }
     ERROR("requires a polynomial ring");
     return nullptr;
   }
   catch (exc::engine_error& e) {
     ERROR(e.what());
     return nullptr;
   }
 }
References Ring::cast_to_PolynomialRing(), ERROR(), mpfr::exp(), RingElement::get_ring(), RingElement::get_value(), PolynomialRing::getCoefficients(), EngineMonomial::ints(), PolynomialRing::make_logical_term(), RingElement::make_raw(), PolynomialRing::n_vars(), newarray_atomic, and ExponentList< E, L >::to_expvector().