Macaulay2 Engine: IM2_RingElement_from_BigReal
IM2_RingElement_from_BigReal()
const RingElement* IM2_RingElement_from_BigReal (const Ring * R, gmp_RR z)
Definition at line 70 of file ringelement.cpp.
 {
   ring_elem f;
   if (R->from_BigReal(z, f)) return RingElement::make_raw(R, f);
   ERROR("cannot create element of this ring from an element of RR");
   return 0;
 }
References ERROR(), Ring::from_BigReal(), and RingElement::make_raw().