Macaulay2 Engine: IM2_RingElement_list_form
IM2_RingElement_list_form()
engine_RawArrayPairOrNull IM2_RingElement_list_form (const Ring * coeffRing, const RingElement * f)
Definition at line 543 of file ringelement.cpp.
 {
   try {
     const PolynomialRing* P = f->get_ring()->cast_to_PolynomialRing();
     if (P != nullptr)
       {
         return P->list_form(coeffRing, f->get_value());
       }
     const SchurRing2* S = f->get_ring()->cast_to_SchurRing2();
     if (S != nullptr)
       {
         return S->list_form(coeffRing, f->get_value());
       }
     /* added by Frank */
     const M2FreeAlgebra* ncP = dynamic_cast<const M2FreeAlgebra*>(f->get_ring());
     if (ncP != nullptr)
       {
         return ncP->list_form(coeffRing, f->get_value());
       }
     /* added by Frank */
     const M2FreeAlgebraQuotient* ncQ = dynamic_cast<const M2FreeAlgebraQuotient*>(f->get_ring());
     if (ncQ != nullptr)
       {
         return ncQ->m2FreeAlgebra().list_form(coeffRing, f->get_value());
       }
     ERROR("expected a polynomial");
     return nullptr;
   }
   catch (exc::engine_error& e) {
     ERROR(e.what());
     return nullptr;
   }
 }
References Ring::cast_to_PolynomialRing(), Ring::cast_to_SchurRing2(), ERROR(), RingElement::get_ring(), RingElement::get_value(), M2FreeAlgebra::list_form(), SchurRing2::list_form(), PolynomialRing::list_form(), and M2FreeAlgebraQuotient::m2FreeAlgebra().