Macaulay2 Engine: rawConvolve
rawConvolve()
engine_RawRingElementArrayOrNull rawConvolve (engine_RawRingElementArray H, int convolve_type)
Definition at line 676 of file ringelement.cpp.
 {
   // convolve_type == 1: E_n = E_(n-1) * H_1 - E(n-2) * H_2 + ... + (-1)^n * H_n
   // convolve_type == 2: n * E_n = E_(n-1) * H_1 - E(n-2) * H_2 + ... + (-1)^n *
   // H_n
   // others of interest?  These are good for translating between symmetric
   // functions of type E,H,P
   // H_0 is ignored... (OR: should we instead shift everything: first entry of H
   // is denoted H_1...?)
   try
     {
       int len = H->len;
       if (len <= 1)
         {
           ERROR("expected ring element array of length at least 2");
           return nullptr;
         }
       const PolyRing *P = H->array[1]->get_ring()->cast_to_PolyRing();
       if (P == nullptr)
         {
           ERROR("expected a polynomial ring");
           return nullptr;
         }
       VECTOR(ring_elem) input_relems(len);
       VECTOR(ring_elem) output_relems(len);
       for (int i = 0; i < len; i++) input_relems[i] = H->array[i]->get_value();
       convolve(P, input_relems, output_relems, convolve_type);
       engine_RawRingElementArray result =
           getmemarraytype(engine_RawRingElementArray, len);
       result->len = len;
       for (int i = 0; i < result->len; i++)
         result->array[i] = RingElement::make_raw(P, output_relems[i]);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Ring::cast_to_PolyRing(), convolve(), ERROR(), getmemarraytype, RingElement::make_raw(), and VECTOR().