Macaulay2 Engine: IM2_RingElement_to_BigComplex
IM2_RingElement_to_BigComplex()
gmp_CCorNull IM2_RingElement_to_BigComplex (const RingElement * a)
Definition at line 176 of file ringelement.cpp.
 {
   const Ring *R = a->get_ring();
   auto RCCC = dynamic_cast<const M2::ConcreteRing<M2::ARingCCC> *>(R);
   if (RCCC != nullptr)
     {
       const M2::ARingCCC::ElementType &b =
           RCCC->ring().from_ring_elem_const(a->get_value());
       gmp_CC result = RCCC->ring().toBigComplex(b);
       return result;
     }
   auto RCC = dynamic_cast<const M2::ConcreteRing<M2::ARingCC> *>(R);
   if (RCC != nullptr)
     {
       const M2::ARingCC::ElementType &b =
           RCC->ring().from_ring_elem_const(a->get_value());
       gmp_CC result = RCC->ring().toBigComplex(b);
       return result;
     }
   ERROR("expected an element of CCC");
   return nullptr;
 }
References ERROR(), RingElement::get_ring(), and RingElement::get_value().