Macaulay2 Engine: rawGetParts
rawGetParts()
engine_RawRingElementArray rawGetParts (const M2_arrayint wts, const RingElement * f)
Definition at line 586 of file ringelement.cpp.
 {
   try
     {
       const PolynomialRing *P = f->get_ring()->cast_to_PolynomialRing();
       if (P == nullptr)
         {
           ERROR("expected a polynomial");
           return nullptr;
         }
       long relems_len;
       ring_elem *relems = P->get_parts(
           M2_arrayint_to_stdvector<int>(wts), f->get_value(), relems_len);
       engine_RawRingElementArray result =
           getmemarraytype(engine_RawRingElementArray, relems_len);
       result->len = static_cast<int>(relems_len);
       for (int i = 0; i < result->len; i++)
         result->array[i] = RingElement::make_raw(P, relems[i]);
       freemem(relems);
       return result;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Ring::cast_to_PolynomialRing(), ERROR(), freemem(), PolynomialRing::get_parts(), RingElement::get_ring(), RingElement::get_value(), getmemarraytype, and RingElement::make_raw().