Macaulay2 Engine: rawSchurDimension
rawSchurDimension()
gmp_ZZorNull rawSchurDimension (const RingElement * f)
Definition at line 842 of file ringelement.cpp.
 {
   try
     {
       const SchurRing *S = f->get_ring()->cast_to_SchurRing();
       if (S == 0)
         {
           ERROR("expected a polynomial over a Schur ring");
           return 0;
         }
       ring_elem result = S->dimension(f->get_value());
       return result.get_mpz();
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References Ring::cast_to_SchurRing(), SchurRing::dimension(), ERROR(), ring_elem::get_mpz(), RingElement::get_ring(), and RingElement::get_value().