Macaulay2 Engine: rawSchurFromPartition
rawSchurFromPartition()
const RingElement* rawSchurFromPartition (const Ring * R, M2_arrayint part)
Definition at line 902 of file ringelement.cpp.
 {
   // R should be a SchurRing2
   // part should be a partition: a weakly descending list of integers (for now,
   // non-negative)
   // if R has a limit on the size of partitions, then
   try
     {
       const SchurRing2 *S = R->cast_to_SchurRing2();
       if (S == nullptr)
         {
           ERROR("expected a Schur ring");
           return nullptr;
         }
       // Check that part is a partition, and that the number of parts is <=
       // number allowed
       if (!S->is_valid_partition(part)) return nullptr;
       ring_elem result = S->from_partition(part);
       return RingElement::make_raw(S, result);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Ring::cast_to_SchurRing2(), ERROR(), SchurRing2::from_partition(), SchurRing2::is_valid_partition(), and RingElement::make_raw().