Macaulay2 Engine: IM2_RingElement_to_Interval
IM2_RingElement_to_Interval()
gmp_RRiorNull IM2_RingElement_to_Interval (const RingElement * a)
Definition at line 148 of file ringelement.cpp.
 {
     const Ring *R = a->get_ring();
     gmp_RRimutable result;
     const M2::ConcreteRing<M2::ARingRRi> *R1;
     switch (R->ringID())
     {
        case M2::ring_RR:
           result = getmemstructtype(gmp_RRimutable);
           mpfi_init2(result, 53);
           mpfi_set_d(result, a->get_value().get_double());
           return moveTo_gmpRRi(result);
        case M2::ring_RRi:
           R1 =
           dynamic_cast<const M2::ConcreteRing<M2::ARingRRi> *>(a->get_ring());
           result = getmemstructtype(gmp_RRimutable);
           mpfi_init2(result, R1->get_precision());
           mpfi_set(result, a->get_value().get_mpfi());
           return moveTo_gmpRRi(result);
        default:
           ERROR("expected an element of RRi");
           return nullptr;
     }
 }
References ERROR(), ring_elem::get_double(), ring_elem::get_mpfi(), M2::ConcreteRing< RingType >::get_precision(), RingElement::get_ring(), RingElement::get_value(), getmemstructtype, moveTo_gmpRRi(), M2::ring_RR, M2::ring_RRi, and Ring::ringID().