Macaulay2 Engine: IM2_RingElement_from_BigComplex
IM2_RingElement_from_BigComplex()
const RingElement* IM2_RingElement_from_BigComplex (const Ring * R, gmp_CC z)
Definition at line 64 of file ringelement.cpp.
 {
   ring_elem f;
   if (R->from_BigComplex(z, f)) return RingElement::make_raw(R, f);
   ERROR("cannot create element of this ring from an element of CC");
   return nullptr;
 }
References ERROR(), Ring::from_BigComplex(), and RingElement::make_raw().