Macaulay2 Engine: IM2_RingElement_make_var
IM2_RingElement_make_var()
const RingElement* IM2_RingElement_make_var (const Ring * R, int v)
Definition at line 233 of file ringelement.cpp.
 {
   try
     {
       ring_elem a = R->var(v);
       if (error()) return 0;
       return RingElement::make_raw(R, a);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References error(), ERROR(), RingElement::make_raw(), and Ring::var().