Macaulay2 Engine: rawAssociateDivisor
rawAssociateDivisor()
const RingElement* rawAssociateDivisor (const RingElement * f)
Definition at line 770 of file ringelement.cpp.
 {
   try
     {
       const PolyRing *P = f->get_ring()->cast_to_PolyRing();
       if (P == nullptr)
         {
           ERROR("expected an element of a polynomial ring");
           return nullptr;
         }
       if (!P->getCoefficients()->has_associate_divisors())
         {
           ERROR("cannot find preferred associates for this ring");
           return nullptr;
         }
       return RingElement::make_raw(
           P->getCoefficients(), P->preferred_associate_divisor(f->get_value()));
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Ring::cast_to_PolyRing(), ERROR(), RingElement::get_ring(), RingElement::get_value(), PolynomialRing::getCoefficients(), Ring::has_associate_divisors(), RingElement::make_raw(), and PolyRing::preferred_associate_divisor().