Macaulay2 Engine: rawWeightRange
rawWeightRange()
gmp_ZZpairOrNull rawWeightRange (M2_arrayint wts, const RingElement * a)
Definition at line 376 of file ringelement.cpp.
 {
   try
     {
       int lo, hi;
       a->degree_weights(wts, lo, hi);
       if (error()) return 0;
       gmp_ZZpair p = new gmp_ZZpair_struct;
       p->a = newitem(__mpz_struct);
       p->b = newitem(__mpz_struct);
       mpz_init_set_si(const_cast<mpz_ptr>(p->a), static_cast<long>(lo));
       mpz_init_set_si(const_cast<mpz_ptr>(p->b), static_cast<long>(hi));
       mpz_reallocate_limbs(const_cast<mpz_ptr>(p->a));
       mpz_reallocate_limbs(const_cast<mpz_ptr>(p->b));
       return p;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return NULL;
   }
 }
References RingElement::degree_weights(), error(), ERROR(), mpz_reallocate_limbs(), newitem, and p.