Macaulay2 Engine: MapPolynomialHeap::addTerm
addTerm()
void MapPolynomialHeap::addTerm (Entry tm) inline
Definition at line 582 of file NCReduction.cpp.
   {
     auto result = mMap.find(tm.first);
     bool found = (result != mMap.end());
     if (found)
       {
         result->second = mRing.coefficientRing()->add(tm.second, result->second);
       }
     else
       {
         // need to allocate new term, and insert into hash table and the queue.
         auto rg = mMonomialSpace.allocateArray<int>(tm.first.size());
         std::copy(tm.first.begin(), tm.first.end(), rg.first);
         mMap.insert({Monom(rg.first), tm.second});
       }
   }
References Ring::add(), MemoryBlock< T, NSLAB >::allocateArray(), FreeAlgebra::coefficientRing(), mMap, mMonomialSpace, and mRing.
Referenced by addPolynomial().