Macaulay2 Engine: MapPolynomialHeap::value
value()
Poly* MapPolynomialHeap::value () inline override virtual
Implements PolynomialHeap.
Definition at line 643 of file NCReduction.cpp.
   {
     Poly* f = new Poly;
     while (not isZero())
       {
         auto tm = viewLeadTerm();
         mRing.add_to_end(*f, tm.second, tm.first);
         removeLeadTerm();
       }
     addPolynomial(*f);
     return f;
   }
References FreeAlgebra::add_to_end(), addPolynomial(), isZero(), mRing, removeLeadTerm(), and viewLeadTerm().