Macaulay2 Engine: MapPolynomialHeap::isZero
isZero()
bool MapPolynomialHeap::isZero () inline override virtual
Implements PolynomialHeap.
Definition at line 619 of file NCReduction.cpp.
   {
     // idempotent function.
     while (not mMap.empty())
       {
         const Entry& e = *(mMap.begin());
         if (mRing.coefficientRing()->is_zero(e.second))
           mMap.erase(mMap.begin());
         else
           return false;
       }
     return true;
   }
References FreeAlgebra::coefficientRing(), Ring::is_zero(), mMap, and mRing.
Referenced by value().