Macaulay2 Engine: MapPolynomialHeap::addPolynomial
addPolynomial() [1/2]
MapPolynomialHeap& MapPolynomialHeap::addPolynomial (const Poly & poly) inline override virtual
Implements PolynomialHeap.
Definition at line 599 of file NCReduction.cpp.
   {
     for (auto i = poly.cbegin(); i != poly.cend(); ++i)
       {
         addTerm(Entry(i.monom(), i.coeff()));
       }
     return *this;
   }
References addTerm().
Referenced by addPolynomial(), and value().