Macaulay2 Engine: simplePolynomialRing
simplePolynomialRing() [2/2]
const PolynomialRing* simplePolynomialRing (int p, const std::vector< std::string > & names)
Definition at line 57 of file util-polyring-creation.cpp.
 {
   // if p is 0, use QQ.
   // degrees are all set to 1. (degree ring has one variable)
   // heft is 1.
   // monomial order is grevlex.
   const Ring *kk = (p > 0 ? rawARingZZpFlint(p) : rawARingQQFlint());
   if (kk == nullptr) return nullptr; // one of these routines would have made an error.
   MonomialOrdering* monorder = MonomialOrderings::join
     ({
       MonomialOrderings::GRevLex(names.size()),
       MonomialOrderings::PositionUp()
     });
   return simplePolynomialRing(kk, names, monorder);
 }
References MonomialOrderings::GRevLex(), MonomialOrderings::join(), p, MonomialOrderings::PositionUp(), rawARingQQFlint(), rawARingZZpFlint(), and simplePolynomialRing().