Macaulay2 Engine: simplePolynomialRing
simplePolynomialRing() [1/2]
const PolynomialRing * simplePolynomialRing (const Ring * kk, const std::vector< std::string > & names, MonomialOrdering * monorder)
Definition at line 34 of file util-polyring-creation.cpp.
{
  // degrees are all set to 1. (degree ring has one variable)
  // heft is 1.
  // Now create the monomial order.  This one is a pain in the butt!
  std::vector<int> degs;
  for (int i=0; i<names.size(); i++) degs.push_back(1);
  std::vector<int> heft {1};
  const Monoid* M = Monoid::create(
                             monorder,
                             degreeRing(1),
                             names,
                             degs,
                             heft
                             );
  if (M == nullptr) return nullptr; // an error should have been constructed
  return PolyRing::create(kk, M);
}
References Monoid::create(), PolyRing::create(), and degreeRing().
Referenced by simplePolynomialRing(), TEST(), TEST(), TEST(), and TEST().