Macaulay2 Engine: reduce_exp
reduce_exp()
static int reduce_exp (const int * m, const int * exp) static
Definition at line 59 of file assprime.cpp.
 {
   int is_one = 1;
   for (index_varpower i = m; i.valid(); ++i)
     {
       if (exp[i.var()] == 1) return 0;
       if (exp[i.var()] == 0) is_one = 0;
     }
   if (is_one) return -1;
   return 1;
 }
References mpfr::exp(), and index_varpower::valid().
Referenced by AssociatedPrimes::ass_prime_generator().