Macaulay2 Engine: MonomialTable::make_minimal
make_minimal()
MonomialTable * MonomialTable::make_minimal (int nvars, const gc_vector< exponents_t > & exps, const gc_vector< int > & comps, const gc_vector< int > & vals, gc_vector< int > & rejects) static private
Definition at line 367 of file montable.cpp.
 {
   MonomialTable *T;
   VECTOR(int) positions;
   positions.reserve(exps.size());
   for (unsigned int i = 0; i < exps.size(); i++) positions.push_back(i);
   /* The following sorts in ascending lex order, considering the component and
      the
      inhomogeneous part of the exponent vector */
   std::stable_sort(
       positions.begin(), positions.end(), sorter(nvars, exps, comps));
   T = MonomialTable::make(nvars);
   VECTOR(int)::iterator first, end, last_minimal;
   first = positions.begin();
   end = positions.end();
   last_minimal = first;
   while (first != end)
     {
       VECTOR(int)::iterator next = first + 1;
       exponents_t this_exp = exps[*first];
       int comp = comps[*first];
       while (next != end)
         {
           if (!exponents_equal(nvars, this_exp, exps[*next])) break;
           if (comp != comps[*next]) break;
           rejects.push_back(*next);
           next++;
         }
       if (T->find_divisor(this_exp, comp) == -1)
         {
           /* We have a minimal element */
           T->insert(this_exp, comp, vals[*first]);
           *last_minimal++ = *first;
         }
       else
         rejects.push_back(*first);
       first = next;
       /* At this point: [first,next) is the range of equal monomials */
     }
   return T;
 }
References end(), exponents_equal(), make(), T, and VECTOR().