Macaulay2 Engine: MonomialTable::find_divisor
find_divisor()
int MonomialTable::find_divisor (exponents_t exp, int comp)
Definition at line 131 of file montable.cpp.
{
  assert(comp >= 1);
  if (comp >= static_cast<int>(_head.size())) return -1;
  if (comp == _last_match_comp && _last_match != nullptr &&
      exponents::divides(_nvars, _last_match->_lead, exp))
    return _last_match->_val;
  unsigned long expmask = ~exponents::mask(_nvars, exp);
  mon_term *head = _head[comp];
  for (mon_term *t = head->_next; t != head; t = t->_next)
    if ((expmask & t->_mask) == 0)
      if (exponents::divides(_nvars, t->_lead, exp))
        {
          _last_match = t;
          _last_match_comp = comp;
          // move_up(t,head);
          return t->_val;
        }
  return -1;
}
References _head, _last_match, _last_match_comp, MonomialTable::mon_term::_lead, MonomialTable::mon_term::_next, _nvars, MonomialTable::mon_term::_val, and ExponentVector< E, OC >::divides().
Referenced by QRingInfo_field_basic::gbvector_normal_form(), QRingInfo_field_QQ::gbvector_normal_form(), QRingInfo_field_QQ::gbvector_normal_form(), MarkedGB::geo_remainder(), MarkedGB::marked_remainder(), ReducedGB_Field::remainder(), MarkedGB::remainder(), and ReducedGB_Field::remainder().