Macaulay2 Engine: MonomialTable::make
make()
MonomialTable * MonomialTable::make (int nvars) static
Definition at line 61 of file montable.cpp.
{
  MonomialTable *result;
  result = new MonomialTable;
  result->mon_term_stash = new stash("montable terms", sizeof(mon_term));
  result->_nvars = nvars;
  result->_count = 0;
  /* The first entry is a dummy entry.  Components
     will always start at 1. */
  result->_head.push_back(nullptr);
  return result;
}
References _count, _head, _nvars, mon_term_stash, and MonomialTable().
Referenced by gbA::initialize(), make_minimal(), MarkedGB::MarkedGB(), minimalize(), gbA::minimalize_pairs_non_ZZ(), QRingInfo_field::QRingInfo_field(), ReducedGB_Field::ReducedGB_Field(), ReducedGB_Field_Local::remainder(), and ReducedGB_Field_Local::remainder().