Macaulay2 Engine: MonomialTable::insert
insert()
void MonomialTable::insert (exponents_t exp, int comp, int id)
Definition at line 218 of file montable.cpp.
 {
   /* Insert 'exp' into the monomial table.  These are kept sorted in ascending
      order
      in some order (lex order?).  No element is ever removed.
   */
   if (comp >= INTSIZE(_head))
     {
       for (int i = INTSIZE(_head); i <= comp; i++)
         _head.push_back(make_list_head());
     }
   mon_term *head = _head[comp];
   mon_term *t;
   /* Make a new mon_term including exp */
   mon_term *newterm = reinterpret_cast<mon_term *>(mon_term_stash->new_elem());
   newterm->_lead = exp;
   newterm->_mask = exponents::mask(_nvars, exp);
   newterm->_val = id;
   _count++;
 /* Find where to put it */
 #ifdef INSERT_AT_END
   // put it at the end
   t = head->_prev;
 #else
   // insert it in sequence (stupid ordering, though)
   for (t = head; t->_next != head; t = t->_next)
     {
       if (exponents_greater(_nvars, newterm->_lead, t->_next->_lead))
         {
           /* Time to insert newterm, right between t, t->next */
           break;
         }
     }
 #endif
   /* The actual insertion */
   newterm->_next = t->_next;
   newterm->_prev = t;
   t->_next->_prev = newterm;
   t->_next = newterm;
 }
References _count, _head, MonomialTable::mon_term::_lead, MonomialTable::mon_term::_mask, MonomialTable::mon_term::_next, _nvars, MonomialTable::mon_term::_prev, MonomialTable::mon_term::_val, mpfr::exp(), exponents_greater(), INTSIZE, make_list_head(), ExponentVector< E, OC >::mask(), mon_term_stash, and stash::new_elem().
Referenced by MarkedGB::add_marked_elems(), gbA::insert_gb(), ReducedGB_Field_Local::minimalize(), ReducedGB_Field::minimalize(), gbA::minimalize_pairs_non_ZZ(), QRingInfo_field::QRingInfo_field(), and ReducedGB_Field_Local::store_in_table().