Macaulay2 Engine: MonomialTable::find_divisors
find_divisors()
int MonomialTable::find_divisors (int max, exponents_t exp, int comp, gc_vector< mon_term * > * result = nullptr)
Definition at line 152 of file montable.cpp.
 {
   assert(comp >= 1);
   assert(max != 0);
   if (comp >= static_cast<int>(_head.size())) return 0;
   if (max == 1 && comp == _last_match_comp && _last_match != nullptr &&
       exponents::divides(_nvars, _last_match->_lead, exp))
     {
       if (result != nullptr) result->push_back(_last_match);
       return 1;
     }
   mon_term *head = _head[comp];
   int nmatches = 0;
   unsigned long expmask = ~exponents::mask(_nvars, exp);
   //*DEBUG*/ long nviewed = 0;
   //*DEBUG*/ long nmasked = 0;
   for (mon_term *t = head->_next, *tnext = t->_next; t != head;
        t = tnext, tnext = t->_next)
     if ((expmask & t->_mask) == 0)
       {
         //*DEBUG*/   nviewed++;
         if (exponents::divides(_nvars, t->_lead, exp))
           {
             nmatches++;  // this doesn't happen very often
             _last_match = t;
             _last_match_comp = comp;
             // move_up(t,head);
             if (result != nullptr) result->push_back(t);
             if (max >= 0 && nmatches >= max) break;
           }
       }
   //*DEBUG*/    else
   //*DEBUG*/      nmasked++;
   //*DEBUG*/  fprintf(stderr, "nviewed %d nmasked %ld max %d nfound %ld\n",
   // nviewed, nmasked, max, nmatches);
   return nmatches;
 }
References _head, _last_match, _last_match_comp, MonomialTable::mon_term::_lead, MonomialTable::mon_term::_next, _nvars, ExponentVector< E, OC >::divides(), mpfr::exp(), and max.
Referenced by gbA::find_good_divisor(), ReducedGB_Field_Local::find_good_divisor(), ReducedGB_Field_Local::minimalize(), ReducedGB_Field::minimalize(), and gbA::minimalize_pairs_non_ZZ().