Macaulay2 Engine: ReducedGB::get_initial
get_initial()
const Matrix * ReducedGB::get_initial (int nparts) virtual
Implements GBComputation.
Reimplemented in MarkedGB.
Definition at line 91 of file reducedgb.cpp.
 {
   MatrixConstructor mat(F, 0);
   for (VECTOR(POLY)::const_iterator i = polys.begin(); i != polys.end(); i++)
     {
       gbvector *f = R->gbvector_lead_term(nparts, F, (*i).f);
       mat.append(originalR->translate_gbvector_to_vec(F, f));
       R->gbvector_remove(f);
     }
   return mat.to_matrix();
 }
References MatrixConstructor::append(), F, GBRing::gbvector_lead_term(), GBRing::gbvector_remove(), originalR, polys, R, MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_to_vec(), and VECTOR().
Referenced by GBDeclared::get_initial(), gbA::get_initial(), and GBinhom_comp::get_initial().