Macaulay2 Engine: ReducedGB::get_gb
get_gb()
const Matrix * ReducedGB::get_gb () virtual
Implements GBComputation.
Definition at line 54 of file reducedgb.cpp.
 {
   MatrixConstructor mat(F, 0);
   for (VECTOR(POLY)::const_iterator i = polys.begin(); i != polys.end(); i++)
     {
       vec v = originalR->translate_gbvector_to_vec(F, (*i).f);
       mat.append(v);
     }
   return mat.to_matrix();
 }
References MatrixConstructor::append(), F, originalR, polys, MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_to_vec(), and VECTOR().
Referenced by GBDeclared::get_gb(), gbA::get_gb(), and GBinhom_comp::get_gb().