Macaulay2 Engine: ReducedGB::matrix_lift
matrix_lift()
M2_bool ReducedGB::matrix_lift (const Matrix * m, const Matrix ** result_remainder, const Matrix ** result_quotient) virtual
Implements GBComputation.
Definition at line 155 of file reducedgb.cpp.
 {
   if (m->get_ring() != originalR)
     {
       ERROR("expected matrix over the same ring");
       *result_remainder = nullptr;
       *result_quotient = nullptr;
       return false;
     }
   if (m->n_rows() != F->rank())
     {
       ERROR("expected matrices to have same number of rows");
       *result_remainder = nullptr;
       *result_quotient = nullptr;
       return false;
     }
   MatrixConstructor mat_remainder(m->rows(), m->cols(), m->degree_shift());
   MatrixConstructor mat_quotient(Fsyz, m->cols(), nullptr);
 #ifdef DEVELOPMENT
 #warning "K should be the denominator ring?"
 #endif
   const Ring *K = R->get_flattened_coefficients();
   bool all_zeroes = true;
   for (int i = 0; i < m->n_cols(); i++)
     {
       ring_elem denom;
       POLY g;
       g.f = originalR->translate_gbvector_from_vec(F, (*m)[i], denom);
       g.fsyz = R->gbvector_zero();
       remainder(g, true, denom);
       if (g.f != nullptr) all_zeroes = false;
       vec fv = originalR->translate_gbvector_to_vec_denom(F, g.f, denom);
       K->negate_to(denom);
       vec fsyzv =
           originalR->translate_gbvector_to_vec_denom(Fsyz, g.fsyz, denom);
       mat_remainder.set_column(i, fv);
       mat_quotient.set_column(i, fsyzv);
       R->gbvector_remove(g.f);
       R->gbvector_remove(g.fsyz);
     }
   *result_remainder = mat_remainder.to_matrix();
   *result_quotient = mat_quotient.to_matrix();
   return all_zeroes;
 }
References Matrix::cols(), Matrix::degree_shift(), ERROR(), POLY::f, F, POLY::fsyz, Fsyz, GBRing::gbvector_remove(), GBRing::gbvector_zero(), GBRing::get_flattened_coefficients(), Matrix::get_ring(), Matrix::n_cols(), Matrix::n_rows(), Ring::negate_to(), originalR, R, FreeModule::rank(), remainder(), Matrix::rows(), MatrixConstructor::set_column(), MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_from_vec(), and PolynomialRing::translate_gbvector_to_vec_denom().
Referenced by GBDeclared::matrix_lift(), gbA::matrix_lift(), and GBinhom_comp::matrix_lift().