Macaulay2 Engine: ReducedGB::get_parallel_lead_terms
get_parallel_lead_terms()
const Matrix * ReducedGB::get_parallel_lead_terms (M2_arrayint w) virtual
Reimplemented from GBComputation.
Reimplemented in MarkedGB.
Definition at line 103 of file reducedgb.cpp.
 {
   MatrixConstructor mat(F, 0);
   for (int i = 0; i < polys.size(); i++)
     {
       gbvector *f =
           R->gbvector_parallel_lead_terms(w, F, polys[i].f, polys[i].f);
       mat.append(originalR->translate_gbvector_to_vec(F, f));
       R->gbvector_remove(f);
     }
   return mat.to_matrix();
 }
References MatrixConstructor::append(), F, GBRing::gbvector_parallel_lead_terms(), GBRing::gbvector_remove(), originalR, polys, R, MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().
Referenced by GBDeclared::get_parallel_lead_terms(), gbA::get_parallel_lead_terms(), and GBinhom_comp::get_parallel_lead_terms().