Macaulay2 Engine: ReducedGB::create
create()
ReducedGB * ReducedGB::create (const PolynomialRing * originalR0, const FreeModule * F0, const FreeModule * Fsyz0, const GBWeight * wt0 = nullptr) static
Definition at line 11 of file reducedgb.cpp.
{
  // Depending on whether the ring is over a field, or over ZZ, or
  // has local variables, we create a different class.
  bool over_ZZ = originalR0->coefficient_type() == Ring::COEFF_ZZ;
  bool is_local = originalR0->getMonoid()->numNonTermOrderVariables() > 0;
  GBRing *R = originalR0->get_gb_ring();
  if (over_ZZ)
    return new ReducedGB_ZZ(R, originalR0, F0, Fsyz0);
  else
    {
      if (is_local)
        return new ReducedGB_Field_Local(R, originalR0, F0, Fsyz0, wt0);
      else
        return new ReducedGB_Field(R, originalR0, F0, Fsyz0);
    }
}
References Ring::COEFF_ZZ, PolynomialRing::coefficient_type(), PolynomialRing::get_gb_ring(), PolynomialRing::getMonoid(), Monoid::numNonTermOrderVariables(), and R.
Referenced by GBDeclared::GBDeclared(), gbA::initialize(), gbA::minimalize_gb(), and GBinhom_comp::set_up().