Macaulay2 Engine: ReducedGB::get_change
get_change()
const Matrix * ReducedGB::get_change () virtual
Implements GBComputation.
Definition at line 80 of file reducedgb.cpp.
{
  MatrixConstructor mat(Fsyz, 0);
  for (VECTOR(POLY)::const_iterator i = polys.begin(); i != polys.end(); i++)
    {
      vec v = originalR->translate_gbvector_to_vec(Fsyz, (*i).fsyz);
      mat.append(v);
    }
  return mat.to_matrix();
}
References MatrixConstructor::append(), Fsyz, originalR, polys, MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_to_vec(), and VECTOR.
Referenced by GBDeclared::get_change(), gbA::get_change(), and GBinhom_comp::get_change().