Macaulay2 Engine: ReducedGB::contains
contains()
int ReducedGB::contains (const Matrix * m) virtual
Implements GBComputation.
Definition at line 208 of file reducedgb.cpp.
 {
   // Reduce each column of m one by one.
   if (m->get_ring() != originalR)
     {
       ERROR("expected matrix over the same ring");
       return -2;
     }
   for (int i = 0; i < m->n_cols(); i++)
     {
       ring_elem denom;
       gbvector *g = originalR->translate_gbvector_from_vec(F, (*m)[i], denom);
       remainder(g, false, denom);
       if (g != NULL)
         {
           R->gbvector_remove(g);
           return i;
         }
     }
   return -1;
 }
References ERROR(), F, GBRing::gbvector_remove(), Matrix::get_ring(), Matrix::n_cols(), originalR, R, remainder(), and PolynomialRing::translate_gbvector_from_vec().
Referenced by GBDeclared::contains(), gbA::contains(), and GBinhom_comp::contains().