Macaulay2 Engine: ReducedGB::matrix_remainder
matrix_remainder()
const Matrix * ReducedGB::matrix_remainder (const Matrix * m) virtual
Implements GBComputation.
Definition at line 126 of file reducedgb.cpp.
 {
   if (m->get_ring() != originalR)
     {
       ERROR("expected matrix over the same ring");
       return nullptr;
     }
   if (m->n_rows() != F->rank())
     {
       ERROR("expected matrices to have same number of rows");
       return nullptr;
     }
   MatrixConstructor red(m->rows(), m->cols(), m->degree_shift());
   for (int i = 0; i < m->n_cols(); i++)
     {
       ring_elem denom;
       gbvector *g = originalR->translate_gbvector_from_vec(F, (*m)[i], denom);
       remainder(g, true, denom);
       vec fv = originalR->translate_gbvector_to_vec_denom(F, g, denom);
       red.set_column(i, fv);
       R->gbvector_remove(g);
     }
   return red.to_matrix();
 }
References Matrix::cols(), Matrix::degree_shift(), ERROR(), F, GBRing::gbvector_remove(), Matrix::get_ring(), Matrix::n_cols(), Matrix::n_rows(), originalR, R, FreeModule::rank(), remainder(), Matrix::rows(), MatrixConstructor::set_column(), MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_from_vec(), and PolynomialRing::translate_gbvector_to_vec_denom().
Referenced by GBDeclared::matrix_remainder(), gbA::matrix_remainder(), GBinhom_comp::matrix_remainder(), and GBWalker::start_computation().