Macaulay2 Engine: rawHomotopy
rawHomotopy()
M2Homotopy* rawHomotopy (M2SLEvaluator * Hx, M2SLEvaluator * Hxt, M2SLEvaluator * HxH)
Numerical Algebraic Geometry interface routines
Definition at line 759 of file matrix.cpp.
 {
   try {
     return new M2Homotopy(Hx->value().createHomotopy(&(Hxt->value()), &(HxH->value())));
   } catch (const exc::engine_error& e) {
     ERROR(e.what());
     return nullptr;
   }
 }
References SLEvaluator::createHomotopy(), ERROR(), and M2SLEvaluator::value().