Macaulay2 Engine: IM2_Matrix_get_entry
IM2_Matrix_get_entry()
const RingElement* IM2_Matrix_get_entry (const Matrix * M, int r, int c)
Definition at line 55 of file matrix.cpp.
 {
   try
     {
       if (r < 0 || r >= M->n_rows())
         {
           ERROR("matrix row index %d out of range 0 .. %d", r, M->n_rows() - 1);
           return nullptr;
         }
       if (c < 0 || c >= M->n_cols())
         {
           ERROR("matrix column index %d out of range 0 .. %d",
                 c,
                 M->n_cols() - 1);
           return nullptr;
         }
       ring_elem result;
       result = M->elem(r, c);
       return RingElement::make_raw(M->get_ring(), result);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Matrix::elem(), ERROR(), Matrix::get_ring(), RingElement::make_raw(), Matrix::n_cols(), and Matrix::n_rows().