Macaulay2 Engine: rawHomotopyTrack
rawHomotopyTrack()
M2_bool rawHomotopyTrack (M2Homotopy * H, const MutableMatrix * inputs, MutableMatrix * outputs, MutableMatrix * output_extras, gmp_RR init_dt, gmp_RR min_dt, gmp_RR epsilon, int max_corr_steps, gmp_RR infinity_threshold, M2_bool checkPrecision)
Definition at line 771 of file matrix.cpp.
{
  try {
    return H->value().track(inputs,
                            outputs,
                            output_extras,
                            init_dt,
                            min_dt,
                            epsilon,  // o.CorrectorTolerance,
                            max_corr_steps,
                            infinity_threshold,
                            checkPrecision);
  } catch (const exc::engine_error& e) {
    ERROR(e.what());
    return false;
  }
}
References ERROR(), Homotopy::track(), and M2Homotopy::value().