Macaulay2 Engine: to_gmp_ZZ
to_gmp_ZZ()
gmp_ZZ to_gmp_ZZ (int a)
Definition at line 718 of file matrix.cpp.
 {
   mpz_ptr result = getmemstructtype(mpz_ptr);
   mpz_init(result);
   mpz_set_si(result, a);
   mpz_reallocate_limbs(result);
   return result;
 }
References getmemstructtype, and mpz_reallocate_limbs().
Referenced by rawSLPDetGate(), rawSLPDivideGate(), rawSLPInputGate(), rawSLPProductGate(), rawSLPsetOutputPositions(), and rawSLPSumGate().