Macaulay2 Engine: rawPointArrayLookup
rawPointArrayLookup()
int rawPointArrayLookup (M2PointArray * pa, const MutableMatrix * M, int col)
Definition at line 973 of file matrix.cpp.
 {
   return pa->value().lookup(getRealVector(M, col));
 }
References getRealVector(), PointArray::lookup(), and M2PointArray::value().