Macaulay2 Engine: IM2_Matrix_get_degree
IM2_Matrix_get_degree()
M2_arrayint IM2_Matrix_get_degree (const Matrix * M)
Definition at line 31 of file matrix.cpp.
 {
   return M->degree_monoid()->to_arrayint(M->degree_shift());
 }
References Matrix::degree_monoid(), Matrix::degree_shift(), and Monoid::to_arrayint().