Macaulay2 Engine: IM2_Matrix_promote
IM2_Matrix_promote()
const Matrix * IM2_Matrix_promote (const FreeModule * newTarget, const Matrix * f)
Matrix interface routines
Definition at line 692 of file matrix.cpp.
{
  try
    {
      ring_elem a;
      const Ring *R = f->get_ring();
      const Ring *S = newTarget->get_ring();
      MatrixConstructor mat(newTarget, f->n_cols());
      Matrix::iterator i(f);
      for (int c = 0; c < f->n_cols(); c++)
        for (i.set(c); i.valid(); i.next())
          if (S->promote(R, i.entry(), a))
            mat.set_entry(i.row(), c, a);
          else
            {
              ERROR("cannot promote given matrix");
              return nullptr;
            }
      mat.compute_column_degrees();
      return mat.to_matrix();
  } catch (const exc::engine_error& e)
    {
      ERROR(e.what());
      return nullptr;
  }
}
References MatrixConstructor::compute_column_degrees(), Matrix::iterator::entry(), ERROR(), FreeModule::get_ring(), Matrix::get_ring(), Matrix::n_cols(), Matrix::iterator::next(), Ring::promote(), Matrix::iterator::row(), Matrix::iterator::set(), MatrixConstructor::set_entry(), MatrixConstructor::to_matrix(), and Matrix::iterator::valid().