Macaulay2 Engine: rawPointArrayToString
rawPointArrayToString()
M2_string rawPointArrayToString (M2PointArray * pa)
Definition at line 967 of file matrix.cpp.
 {
   buffer o;
   pa->value().text_out(o);
   return o.to_string();
 }
References PointArray::text_out(), buffer::to_string(), and M2PointArray::value().