Macaulay2 Engine: EngineObject::hash
hash()
unsigned int EngineObject::hash () const inline
Definition at line 19 of file hash.hpp.
  {
    if (mHashValue == 0)
      {
        mHashValue = computeHashValue();
        if (mHashValue == 0) mHashValue = 1;
      }
    return mHashValue;
  }
References computeHashValue(), and mHashValue.
Referenced by Matrix::is_equal(), rawFreeModuleHash(), rawMatrixHash(), rawMonomialIdealHash(), rawRingElementHash(), and rawRingMapHash().