Macaulay2 Engine: gb_emitter::gb_emitter
gb_emitter()
gb_emitter::gb_emitter (const Matrix * m)
Definition at line 10 of file res-a2.cpp.
     : gens(m), g(nullptr), n_left(m->n_cols()), n_i(0)
 {
   originalR = m->get_ring()->cast_to_PolynomialRing();
   assert(originalR != 0);
   GR = originalR->get_gb_ring();
   this_degree = m->cols()->lowest_primary_degree() - 1;
   n_gens = 0;  // Also needs to be set at that time.
   these = newarray_atomic_clear(int, m->n_cols());
 }
References Ring::cast_to_PolynomialRing(), Matrix::cols(), PolynomialRing::get_gb_ring(), Matrix::get_ring(), GR, FreeModule::lowest_primary_degree(), Matrix::n_cols(), n_gens, newarray_atomic_clear, originalR, these, and this_degree.