Macaulay2 Engine: gb_emitter::calc_gb
calc_gb()
enum ComputationStatusCode gb_emitter::calc_gb (int degree) virtual
Implements gb_node.
Definition at line 27 of file res-a2.cpp.
{
  // This is when we ship off the elements in this degree.  This should NEVER
  // be called if elements of lower degree have not been sent.
  if (this_degree != degree)
    {
      start_degree(degree);
    }
  for (;;)
    {
      if (system_interrupted()) return COMP_INTERRUPTED;
      if (n_i >= n_gens) return COMP_DONE;
      if (g != nullptr)
        {
          ring_elem denom;
          gbvector *v = originalR->translate_gbvector_from_vec(
              gens->rows(), (*gens)[these[n_i]], denom);
          g->receive_generator(v, these[n_i], denom);
        }
      n_i++;
      n_left--;
    }
}
References COMP_DONE, COMP_INTERRUPTED, g, gens, n_gens, n_i, n_left, originalR, gb_node::receive_generator(), Matrix::rows(), start_degree(), system_interrupted(), these, this_degree, and PolynomialRing::translate_gbvector_from_vec().
Referenced by calc_gens().