Macaulay2 Engine: gb_emitter::start_degree
start_degree()
int gb_emitter::start_degree (int deg) private
Definition at line 55 of file res-a2.cpp.
{
  this_degree = deg;
  n_gens = 0;
  n_i = 0;
  for (int i = 0; i < gens->n_cols(); i++)
    {
      if (gens->cols()->primary_degree(i) == this_degree) these[n_gens++] = i;
    }
  return n_gens;
}
References Matrix::cols(), gens, Matrix::n_cols(), n_gens, n_i, FreeModule::primary_degree(), these, and this_degree.
Referenced by calc_gb().