Macaulay2 Engine: ncBasis
ncBasis()
bool ncBasis (const FreeAlgebra & A, const ConstPolyList & gb, const std::vector< int > & lo_degree, const std::vector< int > & hi_degree, int limit, PolyList & result)
Definition at line 153 of file matrix-ncbasis.cpp.
 {
   if (A.monoid().degreeMonoid().n_vars() != 1)
     {
       ERROR("expected singly graded algebra");
       return false;
     }
   if (lo_degree.size() > 1 or hi_degree.size() > 1)
     {
       ERROR("expected singly graded algebra");
       return false;
     }
   NCBasis computation(A, gb, lo_degree, hi_degree, limit);
   std::swap(result, computation.compute());
   return true;
 }
References NCBasis::compute(), FreeMonoid::degreeMonoid(), ERROR(), gb(), FreeAlgebra::monoid(), Monoid::n_vars(), and swap.
Referenced by rawNCBasis().