Macaulay2 Engine: TEST
TEST() [9/9]
TEST (Subsets , outOfRange)
Definition at line 158 of file SubsetTest.cpp.
 {
   const int n = 7;
   const int p = 3;
   const int q = 2;
   Subsets C(n, std::max(p, q));
   Subset b(q, 0);
   for (size_t i = 0; i < 21; i++)
     {
       C.decode(i, b);
       std::cout << "i=" << i << " set=";
       Subsets::show(std::cout, b);
       std::cout << std::endl;
       EXPECT_TRUE(C.isValid(b));
     }
 }
References Subsets::decode(), Subsets::isValid(), max, p, and Subsets::show().