Macaulay2 Engine: TEST
TEST() [8/9]
TEST (Subsets , encodeBoundary)
Definition at line 177 of file SubsetTest.cpp.
 {
   const int n = 7;
   const int p = 3;
   const int n_choose_p = 35;
   Subsets C(n, p);
   Subset a(p, 0);
   Subset b(p - 1, 0);
   for (size_t i = 0; i < n_choose_p; i++)
     {
       C.decode(i, a);
       std::cout << "i=" << i << "set=";
       Subsets::show(std::cout, a);
       std::cout << " bds= ";
       for (size_t j = 0; j < p; j++)
         {
           size_t x = C.encodeBoundary(j, a);
           C.decode(x, b);
           Subsets::show(std::cout, b);
           std::cout << " ";
         }
       std::cout << std::endl;
     }
 }
References Subsets::decode(), Subsets::encodeBoundary(), p, Subsets::show(), and x.