Macaulay2 Engine: TEST
TEST() [1/9]
TEST (Subsets , concatenateSubsets)
Definition at line 119 of file SubsetTest.cpp.
 {
   const int n = 7;
   const int p = 3;
   const int q = 2;
   const int n_choose_p = 35;
   Subsets C(n, std::max(p, q));
   Subset a(p, 0);
   Subset b(q, 0);
   Subset c(p + q, 0);
   Subset d(p + q, 0);
   int sign;
   if ((p % 2 == 1) && (q % 2 == 1))
     sign = -1;
   else
     sign = 1;
   for (size_t i = 0; i < n_choose_p; i++)
     {
       C.decode(i, a);
       EXPECT_TRUE(C.isValid(a));
       for (size_t j = 0; j < n_choose_p; j++)
         {
           C.decode(j, b);
           EXPECT_TRUE(C.isValid(b));
           int ret1 = Subsets::concatenateSubsets(a, b, c);
           int ret2 = Subsets::concatenateSubsets(b, a, d);
           if (ret1 == 0 || ret2 == 0)
             {
               EXPECT_EQ(ret1, ret2);
               break;
             }
           EXPECT_EQ(ret1, sign * ret2);
           EXPECT_TRUE(sameSubset(c, d));
         }
     }
 }
References Subsets::concatenateSubsets(), Subsets::decode(), Subsets::isValid(), max, p, and sameSubset().