Macaulay2 Engine: TEST
TEST() [4/9]
TEST (Subsets , encode3)
Definition at line 41 of file SubsetTest.cpp.
 {
   Subsets C(12, 0);
   Subset a(0, 0);
   for (int i = 0; i < 1; i++)
     {
       C.decode(i, a);
       EXPECT_TRUE(C.isValid(a));
       size_t j = C.encode(a);
       EXPECT_EQ(i, j);
     }
 }
References Subsets::decode(), Subsets::encode(), and Subsets::isValid().