Macaulay2 Engine: TEST
TEST() [7/9]
TEST (Subsets , encode6)
Definition at line 94 of file SubsetTest.cpp.
 {
   // test the increment and decrement functions too
   const int n = 21;
   const int p = 7;
   const int n_choose_p = 116280;
   Subsets C(n, p);
   Subset a(p, 0);
   Subset b(p, 0);
   for (size_t i = 0; i < p; i++) b[i] = i;
   for (size_t i = 0; i < n_choose_p; i++)
     {
       C.decode(i, a);
       EXPECT_TRUE(sameSubset(a, b));
       EXPECT_TRUE(C.isValid(a));
       size_t j = C.encode(a);
       EXPECT_EQ(i, j);
       bool ret = Subsets::increment(n, b);
       EXPECT_EQ(ret, i + 1 != n_choose_p);
     }
 }
References Subsets::decode(), Subsets::encode(), Subsets::increment(), Subsets::isValid(), p, and sameSubset().