Macaulay2 Engine: DMatLinAlg< M2::ARingZZpFlint >::solveInvertible
solveInvertible()
bool DMatLinAlg< M2::ARingZZpFlint >::solveInvertible (const Mat & B, Mat & X) inline
Definition at line 51 of file dmat-lu-zzp-flint.hpp.
  {
    // printf("called mat-linalg zzp flint solveInvertible\n");
    assert(mMatrix.numRows() == mMatrix.numColumns());
    assert(mMatrix.numRows() == B.numRows());
    X.resize(mMatrix.numColumns(), B.numColumns());
    int isinvertible =
        nmod_mat_solve(X.nmod_mat(), mMatrix.nmod_mat(), B.nmod_mat());
    return (isinvertible != 0);
  }
References DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::resize().