Macaulay2 Engine: DMatLinAlg< M2::ARingZZpFlint >::columnRankProfile
columnRankProfile()
void DMatLinAlg< M2::ARingZZpFlint >::columnRankProfile (std::vector< size_t > & profile) inline
Definition at line 31 of file dmat-lu-zzp-flint.hpp.
   {
     Mat LU(mMatrix);  // copy
     mp_limb_signed_t* perm = newarray_atomic(mp_limb_signed_t, LU.numRows());
     nmod_mat_lu(perm, LU.nmod_mat(), false);
     freemem(perm);
     LUUtil<RingType>::computePivotColumns(LU, profile);
   }
References LUUtil< RT >::computePivotColumns(), freemem(), MatrixOps::LU(), and newarray_atomic.