Macaulay2 Engine: DMatLinAlg< M2::ARingZZpFlint >::matrixPLU
matrixPLU()
void DMatLinAlg< M2::ARingZZpFlint >::matrixPLU (std::vector< size_t > & P, Mat & L, Mat & U) inline
Definition at line 40 of file dmat-lu-zzp-flint.hpp.
   {
     Mat LU(mMatrix);  // copy
     mp_limb_signed_t* perm = newarray_atomic(mp_limb_signed_t, LU.numRows());
     nmod_mat_lu(perm, LU.nmod_mat(), false);
     P.resize(0);
     for (long i = 0; i < LU.numRows(); i++) P.push_back(perm[i]);
     freemem(perm);
     LUUtil<RingType>::setUpperLower(LU, L, U);
   }
References freemem(), MatrixOps::LU(), newarray_atomic, and LUUtil< RT >::setUpperLower().