Macaulay2 Engine: GB_comp::new_s_pair
new_s_pair()
s_pair * GB_comp::new_s_pair (gb_elem * p, gb_elem * q, const int * lcm) private
Definition at line 165 of file gb-homog2.cpp.
 {
   // p and q should have 'f' field defined.
   s_pair *result = new s_pair;
   result->next = nullptr;
   result->syz_type = SPAIR_PAIR;
   result->degree = weightInfo_->monomial_weight(
       lcm, p->f->comp);  //_M->primary_degree(lcm) +
                          //_F->primary_degree(p->f->comp-1);
   result->compare_num = 0;
   result->first = p;
   result->second = q;
   result->f = nullptr;
   result->fsyz = nullptr;
   result->lcm = _M->make_new(lcm);
   return result;
 }
References _M, s_pair::compare_num, s_pair::degree, s_pair::f, s_pair::first, s_pair::fsyz, s_pair::lcm, Monoid::make_new(), GBWeight::monomial_weight(), s_pair::next, p, s_pair::second, SPAIR_PAIR, s_pair::syz_type, and weightInfo_.
Referenced by find_pairs().