Macaulay2 Engine: GB_comp::flush_pairs
flush_pairs()
void GB_comp::flush_pairs (int deg) private
Definition at line 530 of file gb-homog2.cpp.
 {
   s_pair *p;
   while ((p = _spairs->remove()) != nullptr)
     if (p->degree != deg)
       {
         _spairs->put_back(p);
         break;
       }
     else
       {
         _n_saved_hilb++;
         remove_pair(p);
       }
   while ((p = _gens->remove()) != nullptr)
     if (p->degree != deg)
       {
         _gens->put_back(p);
         break;
       }
     else
       {
         _n_saved_hilb++;
         remove_pair(p);
       }
 }
References _gens, _n_saved_hilb, _spairs, p, s_pair_heap::put_back(), s_pair_heap::remove(), and remove_pair().
Referenced by gb_insert(), and start_computation().