Macaulay2 Engine: GB_comp::get_change
get_change()
const Matrix * GB_comp::get_change () virtual
Implements GBComputation.
Definition at line 1023 of file gb-homog2.cpp.
 {
   start_computation();
   MatrixConstructor mat(_Fsyz, 0);
   for (int i = 0; i < _gb.size(); i++)
     mat.append(originalR->translate_gbvector_to_vec(_Fsyz, _gb[i]->fsyz));
   return mat.to_matrix();
 }
References _Fsyz, _gb, MatrixConstructor::append(), originalR, start_computation(), MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().