Macaulay2 Engine: GB_comp::find_pairs
find_pairs()
void GB_comp::find_pairs (gb_elem * p) private
Definition at line 263 of file gb-homog2.cpp.
{
  gc_vector<Bag*> elems;
  gc_vector<int> vplcm;
  monomial find_pairs_m = _M->make_one();
  monomial f_m = _M->make_one();
  exponents_t find_pairs_exp = newarray_atomic(int, _M->n_vars());
  int *find_pairs_lcm = newarray_atomic(int, _M->n_vars());
  _GR->gbvector_get_lead_monomial(_F, p->f, f_m);
  if (_GR->is_skew_commutative())
    {
      _M->to_expvector(f_m, find_pairs_exp);
      for (int v = 0; v < _GR->n_skew_commutative_vars(); v++)
        {
          int w = _GR->skew_variable(v);
          if (find_pairs_exp[w] == 0) continue;
          find_pairs_exp[w]++;
          _M->from_expvector(find_pairs_exp, find_pairs_lcm);
          find_pairs_exp[w]--;
          vplcm.resize(0);
          _M->to_varpower(find_pairs_lcm, vplcm);
          s_pair *q = new_var_pair(p, find_pairs_lcm);
          elems.push_back(new Bag(q, vplcm));
        }
    }
  // Add in syzygies arising from a base ring
  if (originalR->is_quotient_ring())
    {
      for (int i = 0; i < originalR->n_quotients(); i++)
        {
          const gbvector *f = originalR->quotient_gbvector(i);
          _M->lcm(f->monom, f_m, find_pairs_lcm);
          vplcm.resize(0);
          _M->to_varpower(find_pairs_lcm, vplcm);
          s_pair *q = new_ring_pair(p, find_pairs_lcm);
          elems.push_back(new Bag(q, vplcm));
        }
    }
  // Add in syzygies arising as s-pairs
  MonomialIdeal *mi1 = _monideals[p->f->comp]->mi;
  for (Bag& a : *mi1)
    {
      _M->from_varpower(a.monom().data(), find_pairs_m);
      _M->lcm(find_pairs_m, f_m, find_pairs_lcm);
      vplcm.resize(0);
      _M->to_varpower(find_pairs_lcm, vplcm);
      s_pair *q =
          new_s_pair(p,
                     reinterpret_cast<gb_elem *>(a.basis_ptr()),
                     find_pairs_lcm);
      elems.push_back(new Bag(q, vplcm));
    }
  // Add 'p' to the correct monideal
  gc_vector<int> vp;
  _M->to_varpower(f_m, vp);
  mi1->insert(new Bag(p, vp));
  // Now minimalize these elements, and insert them into
  // the proper degree.
  VECTOR(Bag *) rejects;
  MonomialIdeal mi(originalR, elems, rejects);
  for (auto& b : rejects)
    {
      s_pair *q = reinterpret_cast<s_pair *>(b->basis_ptr());
      remove_pair(q);
      delete b;
    }
  for (Bag& a : mi)
    {
      s_pair *q = reinterpret_cast<s_pair *>(a.basis_ptr());
      if (_is_ideal && q->syz_type == SPAIR_PAIR)
        {
          _M->gcd(q->first->f->monom, q->second->f->monom, find_pairs_m);
          if (_M->is_one(find_pairs_m))
            {
              _n_saved_gcd++;
              if (M2_gbTrace >= 8)
                {
                  buffer o;
                  o << "removed pair[" << q->first->me << " " << q->second->me
                    << "]" << newline;
                  emit(o.str());
                }
              remove_pair(q);
            }
          else
            _spairs->insert(q);
        }
      else
        _spairs->insert(q);
    }
  // Remove the local variables
  _M->remove(find_pairs_m);
  _M->remove(f_m);
  freemem(find_pairs_exp);
  freemem(find_pairs_lcm);
}
References _F, _GR, _is_ideal, _M, _monideals, _n_saved_gcd, _spairs, emit(), gb_elem::f, s_pair::first, freemem(), Monoid::from_expvector(), Monoid::from_varpower(), GBRing::gbvector_get_lead_monomial(), Monoid::gcd(), MonomialIdeal::insert(), s_pair_heap::insert(), Monoid::is_one(), PolynomialRing::is_quotient_ring(), GBRing::is_skew_commutative(), Monoid::lcm(), M2_gbTrace, Monoid::make_one(), gb_elem::me, MonomialIdeal::mi, gbvector::monom, PolynomialRing::n_quotients(), GBRing::n_skew_commutative_vars(), Monoid::n_vars(), new_ring_pair(), new_s_pair(), new_var_pair(), newarray_atomic, newline, originalR, p, PolynomialRing::quotient_gbvector(), Monoid::remove(), remove_pair(), s_pair::second, GBRing::skew_variable(), SPAIR_PAIR, buffer::str(), s_pair::syz_type, Monoid::to_expvector(), Monoid::to_varpower(), and VECTOR.
Referenced by new_pairs_step().