Macaulay2 Engine: GB_comp::initialize
initialize()
void GB_comp::initialize (const Matrix * m, int csyz, int nsyz, M2_arrayint gb_weights, int strategy) private
Definition at line 84 of file gb-homog2.cpp.
 {
   int i;
   _strategy = strat;
   initialize0(m, csyz, nsyz, gb_weights);
   _Fsyz = m->cols()->sub_space(_n_rows_per_syz);
   _state = GB_COMP_NEWDEGREE;
   for (i = 0; i < m->n_cols(); i++)
     {
       ring_elem denom;
       gbvector *f = originalR->translate_gbvector_from_vec(_F, (*m)[i], denom);
       s_pair *p = new_gen(i, f, denom);
       if (p != nullptr)
         {
           _gens->insert(p);
           _n_gens_left++;
         }
     }
 }
References _F, _Fsyz, _gens, _n_gens_left, _n_rows_per_syz, _state, _strategy, Matrix::cols(), GB_COMP_NEWDEGREE, initialize0(), s_pair_heap::insert(), Matrix::n_cols(), new_gen(), originalR, p, FreeModule::sub_space(), and PolynomialRing::translate_gbvector_from_vec().
Referenced by create().