Macaulay2 Engine: GB_comp::matrix_remainder
matrix_remainder()
const Matrix * GB_comp::matrix_remainder (const Matrix * m) virtual
Implements GBComputation.
Definition at line 1068 of file gb-homog2.cpp.
 {
   if (m->get_ring() != originalR)
     {
       ERROR("expected matrix over the same ring");
       return 0;
     }
   if (m->n_rows() != _F->rank())
     {
       ERROR("expected matrices to have same number of rows");
       return 0;
     }
   start_computation();
   MatrixConstructor red(m->rows(), m->cols(), m->degree_shift());
   for (int i = 0; i < m->n_cols(); i++)
     {
       ring_elem denom;
       gbvector *f = originalR->translate_gbvector_from_vec(_F, (*m)[i], denom);
       gbvector *fsyz = _GR->gbvector_zero();
       gb_reduce(f, fsyz);
       vec fv = originalR->translate_gbvector_to_vec_denom(_F, f, denom);
       red.set_column(i, fv);
     }
   return red.to_matrix();
 }
References _F, _GR, Matrix::cols(), Matrix::degree_shift(), ERROR(), gb_reduce(), GBRing::gbvector_zero(), Matrix::get_ring(), Matrix::n_cols(), Matrix::n_rows(), originalR, FreeModule::rank(), Matrix::rows(), MatrixConstructor::set_column(), start_computation(), MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_from_vec(), and PolynomialRing::translate_gbvector_to_vec_denom().