Macaulay2 Engine: GB_comp::start_computation
start_computation()
void GB_comp::start_computation () virtual
Implements GBComputation.
Definition at line 794 of file gb-homog2.cpp.
 {
   ComputationStatusCode is_done = COMP_COMPUTING;
   for (;;)
     {
       if (is_done != COMP_COMPUTING) break;
       is_done = computation_is_complete();
       if (is_done != COMP_COMPUTING) break;
       if (system_interrupted())
         {
           is_done = COMP_INTERRUPTED;
           break;
         }
       switch (_state)
         {
           case GB_COMP_NEWDEGREE:
             if (_spairs->n_elems() == 0 && _gens->n_elems() == 0)
               {
                 _state = GB_COMP_DONE;
                 is_done = COMP_DONE;
                 break;
               }
             _this_degree = next_degree();
             if (stop_.stop_after_degree &&
                 _this_degree > stop_.degree_limit->array[0])
               {
                 is_done = COMP_DONE_DEGREE_LIMIT;
                 break;
               }
             if (_use_hilb)
               {
                 if (_hilb_new_elems)
                   {
                     // Recompute h, _hf_diff
                     RingElement *h = compute_hilbert_function();
                     if (h == 0)
                       {
                         is_done = COMP_INTERRUPTED;
                         break;
                       }
                     _hf_diff = (*h) - (*_hf_orig);
                     _hilb_new_elems = false;
                   }
                 _hilb_n_in_degree = hilb_comp::coeff_of(_hf_diff, _this_degree);
                 if (error())
                   {
                     is_done = COMP_ERROR;
                     break;
                   }
                 if (_hilb_n_in_degree == 0) flush_pairs(_this_degree);
               }
             if (M2_gbTrace >= 1)
               {
                 buffer o;
                 o << '{' << _this_degree << '}';
                 o << '(';
                 if (_use_hilb) o << _hilb_n_in_degree << ',';
                 o << _spairs->n_elems() << ')';
                 emit_wrapped(o.str());
               }
             // Set state information for auto reduction, new pairs
             _ar_i = _n_gb;
             _ar_j = _ar_i + 1;
             _np_i = _n_gb;
             _state = GB_COMP_S_PAIRS;
             break;
           case GB_COMP_S_PAIRS:
             if (M2_gbTrace < 2)
               {
                 if (s_pair_step() == SPAIR_DONE) _state = GB_COMP_GENS;
               }
             else
               switch (s_pair_step())
                 {
                   case SPAIR_MINGEN:
                     emit_wrapped("g");
                     break;
                   case SPAIR_GB:
                     emit_wrapped("m");
                     break;
                   case SPAIR_SYZ:
                     emit_wrapped("z");
                     break;
                   case SPAIR_ZERO:
                     emit_wrapped("o");
                     break;
                   case SPAIR_DONE:
                     _state = GB_COMP_GENS;
                     break;
                   default:
                     emit_wrapped("ERROR");
                     break;
                 }
             break;
           case GB_COMP_GENS:
             if (M2_gbTrace < 2)
               {
                 if (gen_step() == SPAIR_DONE) _state = GB_COMP_AUTO_REDUCE;
               }
             else
               switch (gen_step())
                 {
                   case SPAIR_MINGEN:
                     emit_wrapped("g");
                     break;
                   case SPAIR_SYZ:
                     emit_wrapped("z");
                     break;
                   case SPAIR_ZERO:
                     emit_wrapped("o");
                     break;
                   case SPAIR_DONE:
                     _state = GB_COMP_AUTO_REDUCE;
                     break;
                   default:
                     emit_wrapped("ERROR");
                     break;
                 }
             break;
           case GB_COMP_AUTO_REDUCE:
             if (!auto_reduce_step())
               {
                 _state = GB_COMP_NEWPAIRS;
                 if ((_strategy & STRATEGY_SORT) != 0)
                   {
                     gb_sort(
                         _np_i,
                         _n_gb - 1);  // This is the range of elements to sort.
                   }
                 for (int j = _np_i; j < _n_gb; j++) _gb[j]->me = j;
               }
             break;
           case GB_COMP_NEWPAIRS:
             if (!new_pairs_step()) _state = GB_COMP_NEWDEGREE;
             break;
           case GB_COMP_DONE:
             break;
           case GB_COMP_NEED_RESIZE:
             is_done = COMP_NEED_RESIZE;
             break;
         }
     }
   if (M2_gbTrace >= 1) emit_line("");
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << "Number of gb elements       = " << _n_gb << newline;
       o << "Number of gcd=1 pairs       = " << _n_saved_gcd << newline;
       o << "Number of pairs computed    = " << _n_pairs_computed << newline;
       o << "Number of reductions        = " << _n_reductions << newline;
       emit(o.str());
     }
   // _GR->memstats();
   set_status(is_done);
 }
References _ar_i, _ar_j, _gb, _gens, _hf_diff, _hilb_n_in_degree, _hilb_new_elems, _n_gb, _n_pairs_computed, _n_reductions, _n_saved_gcd, _np_i, _spairs, _state, _strategy, _this_degree, _use_hilb, auto_reduce_step(), hilb_comp::coeff_of(), COMP_COMPUTING, COMP_DONE, COMP_DONE_DEGREE_LIMIT, COMP_ERROR, COMP_INTERRUPTED, COMP_NEED_RESIZE, computation_is_complete(), compute_hilbert_function(), StopConditions::degree_limit, emit(), emit_line(), emit_wrapped(), error(), flush_pairs(), GB_COMP_AUTO_REDUCE, GB_COMP_DONE, GB_COMP_GENS, GB_COMP_NEED_RESIZE, GB_COMP_NEWDEGREE, GB_COMP_NEWPAIRS, GB_COMP_S_PAIRS, gb_sort(), gen_step(), M2_gbTrace, s_pair_heap::n_elems(), new_pairs_step(), newline, next_degree(), s_pair_step(), Computation::set_status(), SPAIR_DONE, SPAIR_GB, SPAIR_MINGEN, SPAIR_SYZ, SPAIR_ZERO, Computation::stop_, StopConditions::stop_after_degree, buffer::str(), STRATEGY_SORT, and system_interrupted().
Referenced by contains(), get_change(), get_gb(), get_initial(), get_mingens(), get_parallel_lead_terms(), get_syzygies(), matrix_lift(), and matrix_remainder().