Macaulay2 Engine: GB_comp::gb_reduce
gb_reduce()
void GB_comp::gb_reduce (gbvector *& f, gbvector *& fsyz) private
Definition at line 389 of file gb-homog2.cpp.
 {
   if ((_strategy & STRATEGY_LONGPOLYNOMIALS) != 0)
     {
       gb_geo_reduce(f, fsyz);
       return;
     }
   gbvector head;
   gbvector *result = &head;
   result->next = nullptr;
   exponents_t div_totalexp = newarray_atomic(int, _M->n_vars());
   int count = 0;
   if (M2_gbTrace == 10)
     {
       buffer o;
       o << "reducing ";
       _GR->gbvector_text_out(o, _F, f);
       emit_line(o.str());
     }
   while (f != nullptr)
     {
       Bag *b;
       _GR->gbvector_get_lead_exponents(_F, f, div_totalexp);
       if (originalR->is_quotient_ring() &&
           originalR->get_quotient_monomials()->search_expvector(div_totalexp,
                                                                 b))
         {
           const gbvector *g = originalR->quotient_gbvector(b->basis_elem());
           _GR->gbvector_reduce_lead_term(_F, _Fsyz, head.next, f, fsyz, g, nullptr);
           count++;
           _n_reductions++;
         }
       else if (_monideals[f->comp]->mi_search->search_expvector(div_totalexp,
                                                                 b))
         {
           gb_elem *q = reinterpret_cast<gb_elem *>(b->basis_ptr());
           _GR->gbvector_reduce_lead_term(
               _F, _Fsyz, head.next, f, fsyz, q->f, q->fsyz);
           count++;
           _n_reductions++;
           if (M2_gbTrace == 10)
             {
               buffer o;
               o << "  reduced by ";
               _GR->gbvector_text_out(o, _F, q->f);
               o << newline;
               o << "    giving ";
               _GR->gbvector_text_out(o, _F, f);
               o << newline;
               emit(o.str());
             }
         }
       else
         {
           result->next = f;
           f = f->next;
           result = result->next;
           result->next = nullptr;
         }
     }
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << "." << count;
       emit_wrapped(o.str());
     }
   f = head.next;
   freemem(div_totalexp);
 }
References _F, _Fsyz, _GR, _M, _monideals, _n_reductions, _strategy, int_bag::basis_elem(), int_bag::basis_ptr(), gbvector::comp, emit(), emit_line(), emit_wrapped(), gb_elem::f, freemem(), gb_elem::fsyz, gb_geo_reduce(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_reduce_lead_term(), GBRing::gbvector_text_out(), PolynomialRing::get_quotient_monomials(), PolynomialRing::is_quotient_ring(), M2_gbTrace, Monoid::n_vars(), newarray_atomic, newline, gbvector::next, originalR, PolynomialRing::quotient_gbvector(), MonomialIdeal::search_expvector(), buffer::str(), and STRATEGY_LONGPOLYNOMIALS.
Referenced by contains(), gen_step(), matrix_lift(), matrix_remainder(), and s_pair_step().