Macaulay2 Engine: GB_comp::matrix_lift
matrix_lift()
M2_bool GB_comp::matrix_lift (const Matrix * m, const Matrix ** result_remainder, const Matrix ** result_quotient) virtual
Implements GBComputation.
Definition at line 1097 of file gb-homog2.cpp.
 {
   if (m->get_ring() != originalR)
     {
       ERROR("expected matrix over the same ring");
       *result_remainder = 0;
       *result_quotient = 0;
       return false;
     }
   if (m->n_rows() != _F->rank())
     {
       ERROR("expected matrices to have same number of rows");
       *result_remainder = 0;
       *result_quotient = 0;
       return false;
     }
   start_computation();
   MatrixConstructor mat_remainder(m->rows(), m->cols(), m->degree_shift());
   MatrixConstructor mat_quotient(_Fsyz, 0);
   bool all_zeroes = true;
   for (int i = 0; i < m->n_cols(); i++)
     {
       ring_elem denom;
       gbvector *f = originalR->translate_gbvector_from_vec(_F, (*m)[i], denom);
       gbvector *fsyz = _GR->gbvector_zero();
       gb_reduce(f, fsyz);
       if (f != 0) all_zeroes = false;
       vec fv = originalR->translate_gbvector_to_vec_denom(_F, f, denom);
       _K->negate_to(denom);
       vec fsyzv =
           originalR->translate_gbvector_to_vec_denom(_Fsyz, fsyz, denom);
       mat_remainder.set_column(i, fv);
       mat_quotient.append(fsyzv);
     }
   *result_remainder = mat_remainder.to_matrix();
   *result_quotient = mat_quotient.to_matrix();
   return all_zeroes;
 }
References _F, _Fsyz, _GR, _K, MatrixConstructor::append(), Matrix::cols(), Matrix::degree_shift(), ERROR(), gb_reduce(), GBRing::gbvector_zero(), Matrix::get_ring(), Matrix::n_cols(), Matrix::n_rows(), Ring::negate_to(), originalR, FreeModule::rank(), Matrix::rows(), MatrixConstructor::set_column(), start_computation(), MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_from_vec(), and PolynomialRing::translate_gbvector_to_vec_denom().