Macaulay2 Engine: GB_comp::remove_pair
remove_pair()
void GB_comp::remove_pair (s_pair *& p) private
Definition at line 125 of file gb-homog2.cpp.
 {
   _GR->gbvector_remove(p->f);
   _GR->gbvector_remove(p->fsyz);
   p->first = NULL;
   p->second = NULL;
   p->next = NULL;
   _M->remove(p->lcm);
   freemem(p);
   p = NULL;
 }
References _GR, _M, freemem(), GBRing::gbvector_remove(), p, and Monoid::remove().
Referenced by find_pairs(), flush_pairs(), gen_step(), and s_pair_step().