Macaulay2 Engine: GB_comp::debug_out
debug_out()
void GB_comp::debug_out (s_pair * q) const private
Definition at line 963 of file gb-homog2.cpp.
 {
   if (q == nullptr) return;
   buffer o;
   o << "(" << q->compare_num << " ";
   if (q->first != nullptr)
     o << q->first->me;
   else
     o << ".";
   o << " ";
   if (q->second != nullptr)
     o << q->second->me;
   else
     o << ".";
   o << " ";
   _M->elem_text_out(o, q->lcm);
   o << ") ";
   emit_wrapped(o.str());
 }
References _M, s_pair::compare_num, Monoid::elem_text_out(), emit_wrapped(), s_pair::first, s_pair::lcm, gb_elem::me, s_pair::second, and buffer::str().
Referenced by s_pair_step().