Macaulay2 Engine: GB_comp::create
create()
GB_comp * GB_comp::create (const Matrix * m, M2_bool collect_syz, int n_rows_to_keep, M2_arrayint gb_weights, int strategy, M2_bool use_max_degree, int max_degree) static
Definition at line 112 of file gb-homog2.cpp.
 {
   GB_comp *result = new GB_comp;
   result->initialize(m, collect_syz, n_rows_to_keep, gb_weights, strategy);
   return result;
 }
References GB_comp(), and initialize().
Referenced by GBComputation::choose_gb().