Macaulay2 Engine: GB_comp::gb_geo_reduce
gb_geo_reduce()
void GB_comp::gb_geo_reduce (gbvector *& f, gbvector *& fsyz) private
Definition at line 461 of file gb-homog2.cpp.
 {
   gbvector head;
   gbvector *result = &head;
   result->next = nullptr;
   exponents_t div_totalexp = newarray_atomic(int, _M->n_vars());
   int count = 0;
   gbvectorHeap fb(_GR, _F);
   gbvectorHeap fsyzb(_GR, _Fsyz);
   fb.add(f);
   fsyzb.add(fsyz);
   const gbvector *lead;
   while ((lead = fb.get_lead_term()) != nullptr)
     {
       Bag *b;
       _GR->gbvector_get_lead_exponents(_F, lead, div_totalexp);
       if (originalR->is_quotient_ring() &&
           originalR->get_quotient_monomials()->search_expvector(div_totalexp,
                                                                 b))
         {
           const gbvector *g = originalR->quotient_gbvector(b->basis_elem());
           _GR->reduce_lead_term_heap(_F,
                                      _Fsyz,
                                      lead,
                                      div_totalexp,  // are these two needed
                                      head.next,
                                      fb,
                                      fsyzb,
                                      g,
                                      nullptr);
           count++;
         }
       else if (_monideals[lead->comp]->mi_search->search_expvector(div_totalexp,
                                                                    b))
         {
           gb_elem *q = reinterpret_cast<gb_elem *>(b->basis_ptr());
           _GR->reduce_lead_term_heap(_F,
                                      _Fsyz,
                                      lead,
                                      div_totalexp,
                                      head.next,
                                      fb,
                                      fsyzb,
                                      q->f,
                                      q->fsyz);
           count++;
         }
       else
         {
           result->next = fb.remove_lead_term();
           result = result->next;
           result->next = nullptr;
         }
     }
   if (M2_gbTrace >= 4)
     {
       buffer o;
       o << "." << count;
       emit_wrapped(o.str());
     }
   f = head.next;
   fsyz = fsyzb.value();
   freemem(div_totalexp);
 }
References _F, _Fsyz, _GR, _M, _monideals, gbvectorHeap::add(), int_bag::basis_elem(), int_bag::basis_ptr(), gbvector::comp, emit_wrapped(), gb_elem::f, freemem(), gb_elem::fsyz, GBRing::gbvector_get_lead_exponents(), gbvectorHeap::get_lead_term(), PolynomialRing::get_quotient_monomials(), PolynomialRing::is_quotient_ring(), M2_gbTrace, Monoid::n_vars(), newarray_atomic, gbvector::next, originalR, PolynomialRing::quotient_gbvector(), GBRing::reduce_lead_term_heap(), gbvectorHeap::remove_lead_term(), MonomialIdeal::search_expvector(), buffer::str(), and gbvectorHeap::value().
Referenced by gb_reduce().