Macaulay2 Engine: GB_comp::contains
contains()
int GB_comp::contains (const Matrix * m) virtual
Implements GBComputation.
Definition at line 1140 of file gb-homog2.cpp.
 {
   if (m->get_ring() != originalR)
     {
       ERROR("expected matrix over the same ring");
       return -2;
     }
   // Reduce each column of m one by one.
   start_computation();
   for (int i = 0; i < m->n_cols(); i++)
     {
       ring_elem denom;
       gbvector *f = originalR->translate_gbvector_from_vec(_F, (*m)[i], denom);
       _K->remove(denom);
       gbvector *fsyz = nullptr;
       gb_reduce(f, fsyz);
       _GR->gbvector_remove(fsyz);
       if (f != nullptr)
         {
           _GR->gbvector_remove(f);
           return i;
         }
     }
   return -1;
 }
References _F, _GR, _K, ERROR(), gb_reduce(), GBRing::gbvector_remove(), Matrix::get_ring(), Matrix::n_cols(), originalR, Ring::remove(), start_computation(), and PolynomialRing::translate_gbvector_from_vec().