Macaulay2 Engine: GB_comp::s_pair_step
s_pair_step()
int GB_comp::s_pair_step () private
Definition at line 591 of file gb-homog2.cpp.
 {
   s_pair *p = _spairs->remove();
   if (p == nullptr) return SPAIR_DONE;
   if (p->degree != _this_degree)
     {
       _spairs->put_back(p);
       return SPAIR_DONE;
     }
   if (M2_gbTrace == 100)
     {
       // Traces the computation, in its way
       emit("Computing spair ");
       debug_out(p);
     }
   _n_pairs_computed++;
   compute_s_pair(p);
   gbvector *f = p->f;
   gbvector *fsyz = p->fsyz;
   p->f = nullptr;
   p->fsyz = nullptr;
   remove_pair(p);
   gb_reduce(f, fsyz);
   if (!_GR->gbvector_is_zero(f))
     {
       if (M2_gbTrace == 100)
         {
           buffer o;
           o << "  inserting GB element " << _n_gb;
           _GR->gbvector_text_out(o, _F, f);
           o << newline;
           emit(o.str());
         }
       gb_insert(f, fsyz, 0);
       return SPAIR_GB;
     }
   if (!_GR->gbvector_is_zero(fsyz))
     {
       if (_collect_syz)
         {
           // vec fsyzvec = _GR->gbvector_to_vec(_Fsyz,fsyz);
           _syz.push_back(fsyz);
           _n_syz++;
           return SPAIR_SYZ;
         }
       else
         _GR->gbvector_remove(fsyz);
     }
   return SPAIR_ZERO;
 }
References _collect_syz, _F, _GR, _n_gb, _n_pairs_computed, _n_syz, _spairs, _syz, _this_degree, compute_s_pair(), debug_out(), emit(), gb_insert(), gb_reduce(), GBRing::gbvector_is_zero(), GBRing::gbvector_remove(), GBRing::gbvector_text_out(), M2_gbTrace, newline, p, s_pair_heap::put_back(), s_pair_heap::remove(), remove_pair(), SPAIR_DONE, SPAIR_GB, SPAIR_SYZ, SPAIR_ZERO, and buffer::str().
Referenced by start_computation().