Macaulay2 Engine: GB_comp::gen_step
gen_step()
int GB_comp::gen_step () private
Definition at line 651 of file gb-homog2.cpp.
 {
   s_pair *p = _gens->remove();
   if (p == NULL) return SPAIR_DONE;
   if (p->degree != _this_degree)
     {
       _gens->put_back(p);
       return SPAIR_DONE;
     }
   _n_pairs_computed++;
   _n_gens_left--;
   compute_s_pair(p);
   gbvector *f = p->f;
   gbvector *fsyz = p->fsyz;
   p->f = NULL;
   p->fsyz = NULL;
   remove_pair(p);
   gb_reduce(f, fsyz);
   if (!_GR->gbvector_is_zero(f))
     {
       gb_insert(f, fsyz, 1);  // 1 = minimal generator
       return SPAIR_MINGEN;
     }
   if (!_GR->gbvector_is_zero(fsyz))
     {
       if (_collect_syz)
         {
           // vec fsyzvec = _GR->gbvector_to_vec(_Fsyz,fsyz);
           _syz.push_back(fsyz);
           _n_syz++;
           return SPAIR_SYZ;
         }
       else
         _GR->gbvector_remove(fsyz);
     }
   return SPAIR_ZERO;
 }
References _collect_syz, _gens, _GR, _n_gens_left, _n_pairs_computed, _n_syz, _syz, _this_degree, compute_s_pair(), gb_insert(), gb_reduce(), GBRing::gbvector_is_zero(), GBRing::gbvector_remove(), p, s_pair_heap::put_back(), s_pair_heap::remove(), remove_pair(), SPAIR_DONE, SPAIR_MINGEN, SPAIR_SYZ, and SPAIR_ZERO.
Referenced by start_computation().