Macaulay2 Engine: GB_comp::get_mingens
get_mingens()
const Matrix * GB_comp::get_mingens () virtual
Implements GBComputation.
Definition at line 1013 of file gb-homog2.cpp.
 {
   start_computation();
   MatrixConstructor mat(_F, 0);
   for (int i = 0; i < _gb.size(); i++)
     if (_gb[i]->is_min)
       mat.append(originalR->translate_gbvector_to_vec(_F, _gb[i]->f));
   return mat.to_matrix();
 }
References _F, _gb, MatrixConstructor::append(), originalR, start_computation(), MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().