Macaulay2 Engine: GB_comp::gb_insert
gb_insert()
void GB_comp::gb_insert (gbvector * f, gbvector * fsyz, int ismin) private
Definition at line 557 of file gb-homog2.cpp.
 {
   monomial f_m = _M->make_one();
   gb_elem *p = new gb_elem(f, fsyz, ismin);
   _GR->gbvector_get_lead_monomial(_F, p->f, f_m);
   _GR->gbvector_remove_content(p->f, p->fsyz);
   if (ismin)
     {
       p->is_min = 1;
     }
   if (_M->in_subring(1, f_m)) _n_subring++;
   // insert into p->f->comp->mi_search
   gc_vector<int> vp;
   _M->to_varpower(f_m, vp);
   _monideals[p->f->comp]->mi_search->insert(new Bag(p, vp));
   _n_gb++;
   _gb.push_back(p);
   _M->remove(f_m);
   // Now we must be a bit careful about this next, but we only want one
   // copy of a GB element, since the whole thing can be quite large.
   // Just make sure that when the GB is deleted at the end, that the 'f'
   // field of the gb_elem's is not removed.
   if (_use_hilb)
     {
       _hilb_new_elems = true;
       if (--_hilb_n_in_degree == 0) flush_pairs(_this_degree);
     }
 }
References _F, _gb, _GR, _hilb_n_in_degree, _hilb_new_elems, _M, _monideals, _n_gb, _n_subring, _this_degree, _use_hilb, flush_pairs(), GBRing::gbvector_get_lead_monomial(), GBRing::gbvector_remove_content(), Monoid::in_subring(), Monoid::make_one(), p, Monoid::remove(), and Monoid::to_varpower().
Referenced by gen_step(), and s_pair_step().