Macaulay2 Engine: GB_comp::new_gen
new_gen()
s_pair * GB_comp::new_gen (int i, gbvector * f, ring_elem denom) private
Definition at line 184 of file gb-homog2.cpp.
 {
   gbvector *fsyz;
   if (i < _n_rows_per_syz)
     fsyz = _GR->gbvector_term(_Fsyz, denom, i + 1);
   else
     fsyz = _GR->gbvector_zero();
   if (_GR->gbvector_is_zero(f))
     {
       if (!_GR->gbvector_is_zero(fsyz))
         {
           _syz.push_back(fsyz);
           _n_syz++;
         }
       return nullptr;
     }
   s_pair *result = new s_pair;
   result->next = nullptr;
   result->syz_type = SPAIR_GEN;
   result->degree = weightInfo_->gbvector_weight(f);
   result->compare_num = 0;
   result->first = nullptr;
   result->second = nullptr;
   result->f = f; /* NOTE THAT WE GRAB f */
   result->fsyz = fsyz;
   result->lcm = _M->make_new(result->f->monom);
   return result;
 }
References _Fsyz, _GR, _M, _n_rows_per_syz, _n_syz, _syz, s_pair::compare_num, s_pair::degree, s_pair::f, s_pair::first, s_pair::fsyz, GBRing::gbvector_is_zero(), GBRing::gbvector_term(), GBWeight::gbvector_weight(), GBRing::gbvector_zero(), s_pair::lcm, Monoid::make_new(), gbvector::monom, s_pair::next, s_pair::second, SPAIR_GEN, s_pair::syz_type, and weightInfo_.
Referenced by initialize().