Macaulay2 Engine: GB_comp::compute_s_pair
compute_s_pair()
void GB_comp::compute_s_pair (s_pair * p) private
Definition at line 373 of file gb-homog2.cpp.
 {
   if (p->f == NULL)
     {
       monomial s = _M->make_one();
       _M->divide(p->lcm, p->first->f->monom, s);
       _GR->gbvector_mult_by_term(
           _F, _Fsyz, _GR->one(), s, p->first->f, p->first->fsyz, p->f, p->fsyz);
       if (p->syz_type == SPAIR_PAIR)
         _GR->gbvector_reduce_lead_term(
             _F, _Fsyz, 0, p->f, p->fsyz, p->second->f, p->second->fsyz);
       _M->remove(s);
     }
 }
References _F, _Fsyz, _GR, _M, Monoid::divide(), GBRing::gbvector_mult_by_term(), GBRing::gbvector_reduce_lead_term(), Monoid::make_one(), GBRing::one(), p, Monoid::remove(), and SPAIR_PAIR.
Referenced by gen_step(), and s_pair_step().