Macaulay2 Engine: GB_comp::new_ring_pair
new_ring_pair()
s_pair * GB_comp::new_ring_pair (gb_elem * p, const int * lcm) private
Definition at line 147 of file gb-homog2.cpp.
 {
   s_pair *result = new s_pair;
   result->next = NULL;
   result->syz_type = SPAIR_RING;
   result->degree = weightInfo_->monomial_weight(
       lcm, p->f->comp);  //_M->primary_degree(lcm) +
                          //_F->primary_degree(p->f->comp-1);
   result->compare_num = 0;
   result->first = p;
   result->second = NULL;
   result->f = NULL;
   result->fsyz = NULL;
   result->lcm = _M->make_new(lcm);
   return result;
 }
References _M, s_pair::compare_num, s_pair::degree, s_pair::f, s_pair::first, s_pair::fsyz, s_pair::lcm, Monoid::make_new(), GBWeight::monomial_weight(), s_pair::next, p, s_pair::second, SPAIR_RING, s_pair::syz_type, and weightInfo_.
Referenced by find_pairs(), and new_var_pair().