Macaulay2 Engine: GB_comp::initialize0
initialize0()
void GB_comp::initialize0 (const Matrix * m, int csyz, int nsyz, M2_arrayint gb_weights) private
Definition at line 28 of file gb-homog2.cpp.
 {
   int i;
   const PolynomialRing *R = m->get_ring()->cast_to_PolynomialRing();
   if (R == nullptr)
     {
       ERROR("ring is not a polynomial ring");
       // MES: throw an error here.
       assert(0);
     }
   originalR = R;
   _GR = R->get_gb_ring();
   weightInfo_ = new GBWeight(m->rows(), gb_weights);
   _M = _GR->get_flattened_monoid();
   _K = _GR->get_flattened_coefficients();
   _spairs = new s_pair_heap(_M);
   _gens = new s_pair_heap(_M);
   if (nsyz < 0 || nsyz > m->n_cols()) nsyz = m->n_cols();
   _n_rows_per_syz = nsyz;
   _F = m->rows();
   _ar_i = _ar_j = _np_i = -1;
   _n_gb = _n_subring = 0;
   _n_pairs_computed = _n_saved_gcd = 0;
   _n_gens_left = 0;
   _n_reductions = 0;
   _collect_syz = csyz;
   _is_ideal = (_F->rank() == 1 && csyz == 0);
   if (_GR->is_weyl_algebra()) _is_ideal = false;
   _use_hilb = false;
   _hilb_new_elems = false;
   _hilb_n_in_degree = 0;
   _n_saved_hilb = 0;
   // set local variables for certain time-critical routines
   _this_degree = _F->lowest_primary_degree() - 1;
   for (i = 0; i <= _F->rank(); i++)
     {
       // The 0th one is not used.
       monideal_pair *p = new monideal_pair(originalR);
       _monideals.push_back(p);
     }
 }
References _ar_i, _ar_j, _collect_syz, _F, _gens, _GR, _hilb_n_in_degree, _hilb_new_elems, _is_ideal, _K, _M, _monideals, _n_gb, _n_gens_left, _n_pairs_computed, _n_reductions, _n_rows_per_syz, _n_saved_gcd, _n_saved_hilb, _n_subring, _np_i, _spairs, _this_degree, _use_hilb, Ring::cast_to_PolynomialRing(), ERROR(), GBRing::get_flattened_coefficients(), GBRing::get_flattened_monoid(), PolynomialRing::get_gb_ring(), Matrix::get_ring(), GBRing::is_weyl_algebra(), FreeModule::lowest_primary_degree(), Matrix::n_cols(), originalR, p, FreeModule::rank(), Matrix::rows(), and weightInfo_.
Referenced by initialize().