Macaulay2 Engine: monomial_mask
monomial_mask()
static unsigned long monomial_mask (int nvars, exponents exp) static
Definition at line 37 of file montableZZ.cpp.
 {
   unsigned long result = 0;
   int i, j;
   for (i = 0, j = 0; i < nvars; i++, j++)
     {
       if (j == 8 * sizeof(long)) j = 0;
       if (exp[i] > 0) result |= (1 << j);
     }
   return result;
 }
References mpfr::exp().
Referenced by MonomialTableZZ::find_exact(), MonomialTableZZ::find_exact_monomial(), MonomialTableZZ::find_monomial_divisors(), MonomialTableZZ::find_smallest_coeff_divisor(), MonomialTableZZ::find_term_divisors(), MonomialTableZZ::insert(), and MonomialTableZZ::is_weak_member().