Macaulay2 Engine: FractionField::initialize_frac
initialize_frac()
bool FractionField::initialize_frac (const PolyRingFlat * R) protected
Definition at line 27 of file frac.cpp.
 {
   initialize_ring(
       R->characteristic(), R->get_degree_ring(), R->get_heft_vector());
   R_ = R;
   zeroV = from_long(0);
   oneV = from_long(1);
   minus_oneV = from_long(-1);
   if (R->n_quotients() > 0 ||
       R->getCoefficients()
           ->cast_to_FractionField()  // disallowed in x-relem.cpp
       ||
       R->getMonoid()->numNonTermOrderVariables() >
           0)  // disallowed in x-relem.cpp
     use_gcd_simplify = false;
   else
     use_gcd_simplify = true;
 #ifdef DEVELOPMENT
 #warning "frac simplify: doesn't handle towers of fracs"
 #endif
   declare_field();
   return true;
 }
References Ring::cast_to_FractionField(), Ring::characteristic(), Ring::declare_field(), from_long(), Ring::get_degree_ring(), Ring::get_heft_vector(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), Ring::initialize_ring(), Ring::minus_oneV, PolynomialRing::n_quotients(), Monoid::numNonTermOrderVariables(), Ring::oneV, R_, use_gcd_simplify, and Ring::zeroV.
Referenced by create().