Macaulay2 Engine: FractionField::from_long
from_long()
ring_elem FractionField::from_long (long n) const virtual
Implements Ring.
Definition at line 251 of file frac.cpp.
 {
   frac_elem *f = new_frac_elem();
   f->numer = R_->from_long(n);
   f->denom = R_->from_long(1);
   return FRAC_RINGELEM(f);
 }
References frac_elem::denom, FRAC_RINGELEM, Ring::from_long(), new_frac_elem(), frac_elem::numer, and R_.
Referenced by initialize_frac(), and syzygy().