Macaulay2 Engine: FractionField::syzygy
syzygy()
void FractionField::syzygy (const ring_elem a, const ring_elem b, ring_elem & x, ring_elem & y) const virtual
Implements Ring.
Definition at line 600 of file frac.cpp.
 {
   x = FractionField::from_long(1);
   y = FractionField::divide(a, b);
   y = FractionField::negate(y);
 }
References divide(), from_long(), negate(), and x.