Macaulay2 Engine: FractionField::make_elem
make_elem()
frac_elem * FractionField::make_elem (ring_elem a, ring_elem b) const private
Definition at line 181 of file frac.cpp.
 {
   frac_elem *result = new_frac_elem();
   result->numer = a;
   result->denom = b;
   simplify(result);
   return result;
 }
References frac_elem::denom, new_frac_elem(), frac_elem::numer, and simplify().
Referenced by add(), divide(), fraction(), homogenize(), invert(), mult(), power(), random(), and subtract().