Macaulay2 Engine: FractionField::elem_text_out
elem_text_out()
void FractionField::elem_text_out (buffer & o, const ring_elem f, bool p_one = true, bool p_plus = false, bool p_parens = false) const virtual
Implements Ring.
Definition at line 231 of file frac.cpp.
 {
   frac_elem *f = FRAC_VAL(a);
   int denom_one = R_->is_equal(f->denom, R_->one());
   p_one = p_one || !denom_one;
   p_parens = p_parens || !denom_one;
   R_->elem_text_out(o, f->numer, p_one, p_plus, p_parens);
   if (!denom_one)
     {
       o << "/";
       p_plus = false;
       R_->elem_text_out(o, f->denom, p_one, p_plus, p_parens);
     }
 }
References frac_elem::denom, Ring::elem_text_out(), FRAC_VAL, Ring::is_equal(), frac_elem::numer, Ring::one(), and R_.