Macaulay2 Engine: FractionField::mult
mult()
ring_elem FractionField::mult (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 514 of file frac.cpp.
 {
   frac_elem *f = FRAC_VAL(a);
   frac_elem *g = FRAC_VAL(b);
   ring_elem top = R_->mult(f->numer, g->numer);
   ring_elem bottom = R_->mult(f->denom, g->denom);
   if (R_->is_zero(bottom)) return set_non_unit_frac(f->denom);
   return FRAC_RINGELEM(make_elem(top, bottom));
 }
References frac_elem::denom, FRAC_RINGELEM, FRAC_VAL, Ring::is_zero(), make_elem(), Ring::mult(), frac_elem::numer, R_, and set_non_unit_frac().