Macaulay2 Engine: FractionField::power
power() [1/2]
ring_elem FractionField::power (const ring_elem f, int n) const virtual
Reimplemented from Ring.
Definition at line 524 of file frac.cpp.
 {
   frac_elem *f = FRAC_VAL(a);
   ring_elem top, bottom;
   if (n >= 0)
     {
       top = R_->power(f->numer, n);
       bottom = R_->power(f->denom, n);
       if (R_->is_zero(bottom)) return set_non_unit_frac(f->denom);
     }
   else
     {
       if (R_->is_zero(f->numer))
         {
           throw exc::division_by_zero_error();
         }
       top = R_->power(f->denom, -n);
       bottom = R_->power(f->numer, -n);
       if (R_->is_zero(bottom)) return set_non_unit_frac(f->numer);
     }
   return FRAC_RINGELEM(make_elem(top, bottom));
 }
References frac_elem::denom, FRAC_RINGELEM, FRAC_VAL, Ring::is_zero(), make_elem(), frac_elem::numer, Ring::power(), R_, and set_non_unit_frac().