Macaulay2 Engine: FractionField::eval
eval()
ring_elem FractionField::eval (const RingMap * map, const ring_elem f, int first_var) const virtual
Implements Ring.
Definition at line 611 of file frac.cpp.
 {
   const Ring *S = map->get_ring();
   const frac_elem *f = FRAC_VAL(a);
   ring_elem top = R_->eval(map, f->numer, first_var);
   ring_elem bottom = R_->eval(map, f->denom, first_var);
   if (S->is_zero(bottom))
     {
       throw exc::division_by_zero_error();
       S->remove(bottom);
       top = S->from_long(0);
       bottom = S->from_long(1);
     }
   ring_elem result = S->divide(top, bottom);
   S->remove(top);
   S->remove(bottom);
   return result;
 }
References frac_elem::denom, Ring::divide(), Ring::eval(), FRAC_VAL, Ring::from_long(), RingMap::get_ring(), Ring::is_zero(), frac_elem::numer, R_, and Ring::remove().