Macaulay2 Engine: FractionField::homogenize
homogenize() [1/2]
ring_elem FractionField::homogenize (const ring_elem f, int v, int deg, M2_arrayint wts) const virtual
Reimplemented from Ring.
Definition at line 672 of file frac.cpp.
 {
   int d1, d2, lo1, lo2;
   ring_elem top, bottom;
   frac_elem *result;
   const frac_elem *f = FRAC_VAL(a);
   R_->degree_weights(f->numer, wts, lo1, d1);
   R_->degree_weights(f->denom, wts, lo2, d2);
   if (deg >= d1 - d2)
     {
       top = R_->homogenize(f->numer, v, deg + d2, wts);
       bottom = R_->homogenize(f->denom, v, d2, wts);
       result = make_elem(top, bottom);
     }
   else
     {
       top = R_->homogenize(f->numer, v, d1, wts);
       bottom = R_->homogenize(f->denom, v, -deg + d1, wts);
       result = make_elem(top, bottom);
     }
   return FRAC_RINGELEM(result);
 }
References PolynomialRing::degree_weights(), frac_elem::denom, FRAC_RINGELEM, FRAC_VAL, PolynomialRing::homogenize(), make_elem(), frac_elem::numer, and R_.