Macaulay2 Engine: FractionField::new_frac_elem
new_frac_elem()
frac_elem * FractionField::new_frac_elem () const private
Definition at line 88 of file frac.cpp.
 { return newitem(frac_elem); }
References newitem.
Referenced by copy(), from_int(), from_long(), from_rational(), lower_content(), make_elem(), negate(), promote(), set_non_unit_frac(), and var().