Macaulay2 Engine: FractionField::internal_subtract_to
internal_subtract_to()
void FractionField::internal_subtract_to (ring_elem & f, ring_elem & g) const
Definition at line 436 of file frac.cpp.
 {
   frac_elem *f = FRAC_VAL(a);
   frac_elem *g = FRAC_VAL(b);
   if (R_->is_equal(f->denom, g->denom))
     R_->subtract_to(f->numer, g->numer);
   else
     {
       R_->mult_to(f->numer, g->denom);
       ring_elem tmp = R_->mult(f->denom, g->numer);
       R_->subtract_to(f->numer, tmp);
       R_->mult_to(f->denom, g->denom);
       if (R_->is_zero(f->denom))
         {
           set_non_unit_frac(g->denom);
           return;
         }
     }
   simplify(f);
   remove(b);
   a = FRAC_RINGELEM(f);
 }
References frac_elem::denom, FRAC_RINGELEM, FRAC_VAL, Ring::is_equal(), Ring::is_zero(), Ring::mult(), Ring::mult_to(), frac_elem::numer, R_, remove(), set_non_unit_frac(), simplify(), and Ring::subtract_to().