Macaulay2 Engine: FractionField::lift
lift()
bool FractionField::lift (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 325 of file frac.cpp.
 {
   // Rg = R ---> frac R
   // f is an element of frac R.
   ring_elem
       hdenom;  // used in the case when the denominator can be a unit, but not 1
                // e.g. when this = frac (QQ[x,y,z]).  Is an element of
   if (Rg == R_)
     {
       frac_elem *h = FRAC_VAL(f);
       if (R_->is_equal(h->denom, R_->one()))
         {
           result = R_->copy(h->numer);
           return true;
         }
       else
         {
           if (R_->is_field())
             {
               // XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               // try to lift denominator.  If can, can lift, otherwise not.
               if (R_->lift(R_, h->denom, hdenom))
                 {
                   ring_elem hinv = R_->invert(hdenom);
                   result = R_->mult(hinv, h->numer);
                   return true;
                 }
             }
         }
     }
   return false;
 }
References Ring::copy(), frac_elem::denom, FRAC_VAL, Ring::invert(), Ring::is_equal(), Ring::is_field(), Ring::lift(), Ring::mult(), frac_elem::numer, Ring::one(), and R_.