Macaulay2 Engine: FractionField::random
random()
ring_elem FractionField::random () const virtual
Reimplemented from Ring.
Definition at line 220 of file frac.cpp.
 {
   ring_elem a = R_->random();
   ring_elem b = R_->random();
   if (R_->is_zero(b))
     {
       R_->remove(b);
       b = R_->from_long(1);
     }
   return FRAC_RINGELEM(make_elem(a, b));
 }
References FRAC_RINGELEM, Ring::from_long(), Ring::is_zero(), make_elem(), R_, Ring::random(), and Ring::remove().