Macaulay2 Engine: FractionField::add
add()
ring_elem FractionField::add (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 467 of file frac.cpp.
 {
   const frac_elem *f = FRAC_VAL(a);
   const frac_elem *g = FRAC_VAL(b);
   ring_elem top, bottom;
   if (R_->is_equal(f->denom, g->denom))
     {
       top = R_->add(f->numer, g->numer);
       bottom = R_->copy(f->denom);
     }
   else
     {
       top = R_->mult(f->numer, g->denom);
       ring_elem tmp = R_->mult(f->denom, g->numer);
       R_->add_to(top, tmp);
       bottom = R_->mult(f->denom, g->denom);
       if (R_->is_zero(bottom)) return set_non_unit_frac(f->denom);
     }
   frac_elem *result = make_elem(top, bottom);
   return FRAC_RINGELEM(result);
 }
References Ring::add(), Ring::add_to(), Ring::copy(), frac_elem::denom, FRAC_RINGELEM, FRAC_VAL, Ring::is_equal(), Ring::is_zero(), make_elem(), Ring::mult(), frac_elem::numer, R_, and set_non_unit_frac().