Macaulay2 Engine: FractionField::multi_degree
multi_degree()
bool FractionField::multi_degree (const ring_elem f, monomial d) const virtual
Reimplemented from Ring.
Definition at line 651 of file frac.cpp.
 {
   const frac_elem *f = FRAC_VAL(a);
   bool tophom = R_->multi_degree(f->numer, d);
   monomial e = degree_monoid()->make_one();
   bool bottomhom = R_->multi_degree(f->denom, e);
   degree_monoid()->divide(d, e, d);
   degree_monoid()->remove(e);
   return tophom && bottomhom;
 }
References Ring::degree_monoid(), frac_elem::denom, Monoid::divide(), FRAC_VAL, Monoid::make_one(), PolynomialRing::multi_degree(), frac_elem::numer, R_, and Monoid::remove().