Macaulay2 Engine: FractionField::lower_content
lower_content()
void FractionField::lower_content (ring_elem & c, const ring_elem g) const virtual
Reimplemented from Ring.
Definition at line 190 of file frac.cpp.
 {
   if (!use_gcd_simplify) return;
   if (is_zero(c))
     {
       c = g;
       return;
     }
   frac_elem *cf = FRAC_VAL(c);
   frac_elem *gf = FRAC_VAL(g);
   const RingElement *c1 = RingElement::make_raw(R_, cf->numer);
   const RingElement *c2 = RingElement::make_raw(R_, cf->denom);
   const RingElement *g1 = RingElement::make_raw(R_, gf->numer);
   const RingElement *g2 = RingElement::make_raw(R_, gf->denom);
   c1 = rawGCDRingElement(c1, g1, nullptr, false);
   const RingElement *cc2 = rawGCDRingElement(c2, g2, nullptr, false);
   const RingElement *cc3 = (*c2) * (*g2);
   const RingElement *cc4 = (*cc3) / (*cc2);
   frac_elem *result = new_frac_elem();
   result->numer = c1->get_value();
   result->denom = cc4->get_value();
   c = FRAC_RINGELEM(result);
 }
References frac_elem::denom, FRAC_RINGELEM, FRAC_VAL, RingElement::get_value(), is_zero(), RingElement::make_raw(), new_frac_elem(), frac_elem::numer, R_, rawGCDRingElement(), and use_gcd_simplify.