Macaulay2 Engine: FractionField::copy
copy()
ring_elem FractionField::copy (const ring_elem f) const virtual
Implements Ring.
Definition at line 396 of file frac.cpp.
 {
   frac_elem *f = FRAC_VAL(a);
   frac_elem *g = new_frac_elem();
   g->numer = R_->copy(f->numer);
   g->denom = R_->copy(f->denom);
   return FRAC_RINGELEM(g);
 }
References Ring::copy(), frac_elem::denom, FRAC_RINGELEM, FRAC_VAL, new_frac_elem(), frac_elem::numer, and R_.
Referenced by term().