Macaulay2 Engine: FractionField::coefficient_type
coefficient_type()
Ring::CoefficientType FractionField::coefficient_type () const virtual
Reimplemented from Ring.
Definition at line 17 of file frac.cpp.
 {
   const PolynomialRing *A = R_->cast_to_PolynomialRing();
   assert(A != 0);
   const Ring *K = A->getCoefficientRing();
   if (K->coefficient_type() == COEFF_ZZ) return COEFF_QQ;
   return K->coefficient_type();
 }
References PolynomialRing::cast_to_PolynomialRing(), Ring::COEFF_QQ, Ring::COEFF_ZZ, Ring::coefficient_type(), PolynomialRing::getCoefficientRing(), and R_.