Macaulay2 Engine: FractionField::set_non_unit_frac
set_non_unit_frac()
ring_elem FractionField::set_non_unit_frac (ring_elem top) const private
Definition at line 89 of file frac.cpp.
 {
   // Sets the non unit to be top/1 (which flags an error)
   // flags an error
   // returns 0/1
   frac_elem *f = new_frac_elem();
   f->numer = top;
   f->denom = R_->one();
   set_non_unit(FRAC_RINGELEM(f));
   return zero();
 }
References frac_elem::denom, FRAC_RINGELEM, new_frac_elem(), frac_elem::numer, Ring::one(), R_, Ring::set_non_unit(), and Ring::zero().
Referenced by add(), divide(), internal_add_to(), internal_subtract_to(), mult(), power(), simplify(), and subtract().