Macaulay2 Engine: FractionField::simplify
simplify()
void FractionField::simplify (frac_elem * f) const private
Definition at line 108 of file frac.cpp.
 {
   ring_elem x, y;
   if (use_gcd_simplify)
     {
       y = f->denom;
       if (R_->is_equal(y, R_->one())) return;
       x = f->numer;
       const RingElement *a = RingElement::make_raw(R_, x);
       const RingElement *b = RingElement::make_raw(R_, y);
       const RingElement *c = rawGCDRingElement(a, b, NULL, false);
 #if 0
       // Debugging code
             buffer o;
             o << newline;
             o << "a = ";
             a->text_out(o);
             o << "  b = ";
             b->text_out(o);
             o << " gcd = ";
             c->text_out(o);
             o << newline;
             emit(o.str());
 #endif
       if (!R_->is_equal(c->get_value(), R_->one()))
         {
           f->numer = R_->divide(f->numer, c->get_value());
           f->denom = R_->divide(f->denom, c->get_value());
         }
       // Now, let's take the content of the denominator, and divide the
       // numerator
       // and denominator by this value.
       ring_elem ct = R_->content(
           f->denom, f->numer);  // result is in R_->getCoefficients()
 #if 0
             o.reset();
             o << "f->numer = ";
             R_->elem_text_out(o,f->numer);
             o << "  f->denom = ";
             R_->elem_text_out(o,f->denom);
             o << " ass= ";
             R_->getCoefficients()->elem_text_out(o,ct);
             o << newline;
             emit(o.str());
 #endif
       if (!R_->getCoefficients()->is_equal(ct, R_->getCoefficients()->one()))
         {
           f->numer = R_->divide_by_given_content(f->numer, ct);
           f->denom = R_->divide_by_given_content(f->denom, ct);
         }
     }
   else
     {
       R_->syzygy(f->numer, f->denom, x, y);
       if (R_->is_zero(x))
         {
           R_->remove(x);
           set_non_unit_frac(f->denom);
           f->numer = R_->zero();
           f->denom = R_->one();
           return;
         }
       R_->negate_to(y);
       R_->remove(f->numer);
       R_->remove(f->denom);
       f->numer = y;
       f->denom = x;
     }
 }
References Ring::content(), frac_elem::denom, Ring::divide(), Ring::divide_by_given_content(), Ring::elem_text_out(), emit(), RingElement::get_value(), PolynomialRing::getCoefficients(), Ring::is_equal(), Ring::is_zero(), RingElement::make_raw(), Ring::negate_to(), newline, frac_elem::numer, Ring::one(), R_, rawGCDRingElement(), Ring::remove(), buffer::reset(), set_non_unit_frac(), buffer::str(), Ring::syzygy(), RingElement::text_out(), use_gcd_simplify, x, and Ring::zero().
Referenced by internal_add_to(), internal_subtract_to(), and make_elem().