Macaulay2 Engine: GBMatrix::to_matrix
to_matrix()
Matrix * GBMatrix::to_matrix ()
Definition at line 26 of file Eschreyer.cpp.
 {
   const PolynomialRing *R = F->get_ring()->cast_to_PolynomialRing();
   assert(R != 0);
   const FreeModule *G = FreeModule::make_schreyer(this);
   MatrixConstructor mat(F, G);
   for (int i = 0; i < elems.size(); i++)
     {
       vec v = R->translate_gbvector_to_vec(F, elems[i]);
       mat.set_column(i, v);
     }
   return mat.to_matrix();
 }
References Ring::cast_to_PolynomialRing(), elems, F, G, FreeModule::get_ring(), FreeModule::make_schreyer(), MatrixConstructor::set_column(), MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().
Referenced by GBKernelComputation::calc(), and rawKernelOfGB().