Macaulay2 Engine: GBMatrix::GBMatrix
GBMatrix() [1/2]
GBMatrix::GBMatrix (const Matrix * m)
Definition at line 12 of file Eschreyer.cpp.
                                   : F(m->rows())
 {
   const PolynomialRing *R = F->get_ring()->cast_to_PolynomialRing();
   assert(R != 0);
   for (int i = 0; i < m->n_cols(); i++)
     {
       ring_elem denom;
       gbvector *g = R->translate_gbvector_from_vec(F, m->elem(i), denom);
       append(g);
     }
 }
References append(), Ring::cast_to_PolynomialRing(), Matrix::elem(), F, FreeModule::get_ring(), Matrix::n_cols(), and PolynomialRing::translate_gbvector_from_vec().