Macaulay2 Engine: OverlapTable::insert
insert()
auto OverlapTable::insert (int deg, bool isGenerator, Overlap o) -> void
Definition at line 7 of file OverlapTable.cpp.
 {
   if (M2_gbTrace >= 3)
     {
       std::cout << "overlapTable: inserting deg="
                 << deg
                 << " isGenerator=" << isGenerator
                 << " overlap=" << o
                 << std::endl;
     }
   std::deque<Overlap> emptyDeque;
   auto ret = mOverlapMap.insert(std::make_pair(std::make_pair(deg,isGenerator),
                                                emptyDeque));
   (ret.first)->second.push_back(o);
 }
References M2_gbTrace.
Referenced by NCF4::NCF4(), NCGroebner::NCGroebner(), and TEST().