Macaulay2 Engine: OverlapTable::removeLowestDegree
removeLowestDegree()
auto OverlapTable::removeLowestDegree () -> void
Definition at line 57 of file OverlapTable.cpp.
 {
   auto iter = mOverlapMap.begin();
   if (iter == mOverlapMap.end()) return;
   mOverlapMap.erase(iter);
 }
Referenced by NCF4::compute(), NCGroebner::computeHomogeneous(), and NCGroebner::computeInhomogeneous().