Macaulay2 Engine: ExponentList::var
var()
template<class E , bool L> static void ExponentList< E, L >::var (Exponent v, Exponent e, Vector & result) inline static
Definition at line 98 of file ExponentList.hpp.
   {
     // TODO: decide on 1 or 3
     if (e == 0)
       result = {1};
     else
       result = {3, v, e};
   }
Referenced by EngineMonomial::EngineMonomial(), find_pivot(), Matrix::make_monideal(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), res_comp::skeleton_pairs(), and varpower_monideal().