Macaulay2 Engine: ExponentList::from_expvector
from_expvector()
void varpower::from_expvector (int n, exponents::ConstExponents a, Vector & result) static
Definition at line 74 of file ExponentList.cpp.
 {
   int len = 0;
   for (int i = 0; i < n; i++)
     if (a[i] != 0) len++;
   result.resize(2 * len + 1);
   Exponents result_vp = result.data();
   *result_vp++ = result.size(); // FIXME: reconcile
   for (int i = n - 1; i >= 0; i--)
     if (a[i] != 0)
       {
         *result_vp++ = i;
         *result_vp++ = a[i];
       }
 }
Referenced by MinimalPrimes::alg1_grab_prime(), AssociatedPrimes::ass_prime_generator(), MinimalPrimes::ass_prime_generator(), borel1(), MyIdealConsumer::consume(), RingElement::lead_monom(), PolyRing::list_form(), binomial_ring::monomial_out(), Monoid::to_varpower(), and TowerEvaluator::viewTerm().