Macaulay2 Engine: ExponentList::copy
copy()
template<class E , bool L> static void ExponentList< E, L >::copy (ConstExponents vp, Vector & result) inline static
Definition at line 106 of file ExponentList.hpp.
   {
     std::copy(vp, vp + length(vp), std::back_inserter(result));
   }
References ExponentList< E, L >::length().
Referenced by EngineMonomial::EngineMonomial(), find_pivot(), and iquotient_and_sum().