Macaulay2 Engine: ExponentList::quotient
quotient()
void varpower::quotient (ConstExponents a, ConstExponents b, Vector & result) static
Definition at line 143 of file ExponentList.cpp.
{
  // TODO: should result be cleared?
  result.resize(length(a));  // potential length
  Exponents result_vp = result.data();
  Exponents orig_result_vp = result_vp;
  result_vp++;
  index_varpower i = a;
  index_varpower j = b;
  int va = (i.valid() ? i.var() : -1);
  int vb = (j.valid() ? j.var() : -1);
  for (;;)
    {
      if (va > vb)
        {
          *result_vp++ = va;
          *result_vp++ = i.exponent();
          ++i;
          va = (i.valid() ? i.var() : -1);
        }
      else if (vb > va)
        {
          ++j;
          vb = (j.valid() ? j.var() : -1);
        }
      else
        {
          if (va == -1) break;
          int ea = i.exponent();
          int eb = j.exponent();
          if (ea > eb)
            {
              *result_vp++ = va;
              *result_vp++ = ea - eb;  // overflow cannot occur
            }
          ++i;
          ++j;
          va = (i.valid() ? i.var() : -1);
          vb = (j.valid() ? j.var() : -1);
        }
    }
  *orig_result_vp = static_cast<int>(result_vp - orig_result_vp);
}
References ExponentList< E, L >::length().
Referenced by iquotient_and_sum(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), EngineMonomial::operator/(), MonomialIdeal::quotient(), and res_comp::skeleton_pairs().