Macaulay2 Engine: ExponentList::simple_degree
simple_degree()
template<class E , bool L> static Exponent ExponentList< E, L >::simple_degree (ConstExponents m) inline static
Definition at line 143 of file ExponentList.hpp.
  {
    Exponent deg = 0;
    for (Iterator i = m; i.valid(); ++i) deg += i.exponent();
    return deg;
  }
References ExponentListIterator< E, L >::valid().
Referenced by MinimalPrimes::alg1_min_primes(), iquotient_and_sum(), minimalize_res_varpower_monomials(), minimalize_varpower_monomials(), MonomialIdeal::MonomialIdeal(), MonomialIdeal::MonomialIdeal(), and EngineMonomial::simple_degree().