Macaulay2 Engine: ExponentList::radical
radical()
void varpower::radical (ConstExponents a, Vector & result) static
Definition at line 438 of file ExponentList.cpp.
 {
   // TODO: should result be cleared?
   // length of result is the same as that of a
   result.resize(length(a));
   int *result_vp = result.data();
   *result_vp++ = result.size();
   for (index_varpower i = a; i.valid(); ++i)
     {
       *result_vp++ = i.var();  // var
       *result_vp++ = 1;        // exponent
     }
 }
References ExponentList< E, L >::length(), and ExponentListIterator< E, L >::valid().
Referenced by MonomialIdeal::radical(), and EngineMonomial::radical().