Macaulay2 Engine: ExponentList::compare
compare()
template<class E , bool L> static int ExponentList< E, L >::compare (ConstExponents a, ConstExponents b) inline static
Definition at line 112 of file ExponentList.hpp.
   {
     Exponent alen = length(a++) - 1;
     Exponent blen = length(b++) - 1;
     // TODO: try using std::lexicographical_compare?
     for (size_t i = 0; i < std::min(alen, blen); i++)
       {
         Exponent c = *a++ - *b++;
         if (c == 0) continue;
         return (c > 0 ? GT : LT);
       }
     if (alen == blen) return EQ;
     return (alen > blen ? GT : LT);
   }
References EQ, GT, ExponentList< E, L >::length(), LT, and mpfr::min().
Referenced by PreSPairSorter::compare(), and PreSPairSorter::operator()().