Macaulay2 Engine: ExponentList::elem_text_out
elem_text_out()
template<class E , bool L> static void ExponentList< E, L >::elem_text_out (buffer & o, ConstExponents m, bool p_one = true) inline static
Definition at line 50 of file ExponentList.hpp.
   {
     Iterator i = m;
     if (!i.valid() and p_one) o << "1";
     for (; i.valid(); ++i)
       {
         Exponent v = i.var();
         Exponent e = i.exponent();
         if (v < 26)
           o << char('a' + v);
         else if (v < 52)
           o << char('A' + v - 26);
         else
           o << "x[" << v << "]";
         if (e > 1)
           o << e;
         else if (e < 0)
           o << "^(" << e << ")";
       }
   }
References ExponentListIterator< E, L >::exponent(), ExponentListIterator< E, L >::valid(), and ExponentListIterator< E, L >::var().
Referenced by SchreyerFrame::computeIdealQuotient(), MonomialIdeal::do_node(), and EngineMonomial::text_out().