Macaulay2 Engine: ExponentList::monsyz
monsyz()
void varpower::monsyz (ConstExponents a, ConstExponents b, Vector & sa, Vector & sb) static
Definition at line 242 of file ExponentList.cpp.
 {
   sa.resize(length(a));
   sb.resize(length(b));
   int *result_vp1 = sa.data();
   int *result_vp2 = sa.data();
   int *orig_result_vp1 = result_vp1;
   int *orig_result_vp2 = result_vp2;
   result_vp1++;
   result_vp2++;
   index_varpower i = a;
   index_varpower j = b;
   int va = (i.valid() ? i.var() : -1);
   int vb = (j.valid() ? j.var() : -1);
   for (;;)
     {
       if (va > vb)
         {
           // va should be placed into sb
           *result_vp2++ = va;
           *result_vp2++ = i.exponent();
           ++i;
           va = (i.valid() ? i.var() : -1);
         }
       else if (va < vb)
         {
           // vb should be placed into sa
           *result_vp1++ = vb;
           *result_vp1++ = j.exponent();
           ++j;
           vb = (j.valid() ? j.var() : -1);
         }
       else
         {
           if (va == -1) break;
           int ea = i.exponent();
           int eb = j.exponent();
           if (ea < eb)
             {
               *result_vp1++ = va;
               *result_vp1++ = eb - ea;
             }
           else if (ea > eb)
             {
               *result_vp2++ = va;
               *result_vp2++ = ea - eb;
             }
           ++i;
           ++j;
           va = (i.valid() ? i.var() : -1);
           vb = (j.valid() ? j.var() : -1);
         }
     }
   *orig_result_vp1 = static_cast<int>(result_vp1 - orig_result_vp1);
   *orig_result_vp2 = static_cast<int>(result_vp2 - orig_result_vp2);
 }
References ExponentListIterator< E, L >::exponent(), ExponentList< E, L >::length(), ExponentListIterator< E, L >::valid(), and ExponentListIterator< E, L >::var().
Referenced by EngineMonomial::monsyz().