Macaulay2 Engine: ExponentList::to_expvector
to_expvector()
void varpower::to_expvector (int n, ConstExponents a, exponents::Exponents result) static
Definition at line 61 of file ExponentList.cpp.
 {
   for (int j = 0; j < n; j++) result[j] = 0;
   for (index_varpower i = a; i.valid(); ++i)
     {
       int v = i.var();
       int e = i.exponent();
       assert(v < n);
       result[v] = e;
     }
 }
References ExponentListIterator< E, L >::valid().
Referenced by MonomialIdeal::borel(), FrobbyAlexanderDual(), Monoid::from_varpower(), PolyRing::get_coeff(), IM2_RingElement_term(), MonomialIdeal::is_borel(), GBKernelComputation::new_pairs(), res2_comp::new_pairs(), res_comp::new_pairs(), MonomialIdeal::search(), and res_comp::skeleton_pairs().