Macaulay2 Engine: ExponentList::length
length()
template<class E , bool L> static const Exponent ExponentList< E, L >::length (ConstExponents m) inline static
Definition at line 71 of file ExponentList.hpp.
   {
     if constexpr (L)
       return *m;
     else
       return 2 * *m + 1;
   }
Referenced by ExponentList< E, L >::compare(), SchreyerFrame::computeIdealQuotient(), ExponentList< E, L >::copy(), F4SPairSet::create_pre_spair(), SchreyerFrame::createQuotientElement(), ExponentList< E, L >::erase(), ExponentList< E, L >::gcd(), ExponentList< E, L >::is_equal(), ExponentList< E, L >::is_one(), ExponentList< E, L >::lcm(), ExponentList< E, L >::monsyz(), ExponentList< E, L >::mult(), ExponentList< E, L >::quotient(), ExponentList< E, L >::radical(), ExponentList< E, L >::to_arrayint(), and ExponentList< E, L >::topvar().