Macaulay2 Engine: ExponentList::mult
mult()
void varpower::mult (ConstExponents a, ConstExponents b, Vector & result) static
Definition at line 92 of file ExponentList.cpp.
 {
   // TODO: should result be cleared?
   result.resize(length(a) + length(b));  // potential length
   Exponents result_vp = result.data();
   Exponents orig_result_vp = result_vp;
   result_vp++;
   index_varpower i = a;
   index_varpower j = b;
   // merge the two varpowers to staticVP
   int va = (i.valid() ? i.var() : -1);
   int vb = (j.valid() ? j.var() : -1);
   for (;;)
     {
       if (va > vb)
         {
           *result_vp++ = va;
           *result_vp++ = i.exponent();
           ++i;
           va = (i.valid() ? i.var() : -1);
         }
       else if (vb > va)
         {
           *result_vp++ = vb;
           *result_vp++ = j.exponent();
           ++j;
           vb = (j.valid() ? j.var() : -1);
         }
       else
         {
           if (va == -1) break;
           int z = safe::add(i.exponent(), j.exponent());
           if (z != 0)
             {
               *result_vp++ = va;
               *result_vp++ = z;
             }
           ++i;
           ++j;
           va = (i.valid() ? i.var() : -1);
           vb = (j.valid() ? j.var() : -1);
         }
     }
   int newlen = static_cast<int>(result_vp - orig_result_vp);
   *orig_result_vp = newlen;
   result.resize(newlen);
 }
References safe::add(), ExponentListIterator< E, L >::exponent(), ExponentList< E, L >::length(), ExponentListIterator< E, L >::valid(), and ExponentListIterator< E, L >::var().
Referenced by EngineMonomial::operator*(), and MonomialIdeal::operator*().