Macaulay2 Engine: ExponentList::divides
divides()
bool varpower::divides (ConstExponents a, ConstExponents b) static
Definition at line 211 of file ExponentList.cpp.
 {
   index_varpower i = a;
   index_varpower j = b;
   int va = (i.valid() ? i.var() : -1);
   int vb = (j.valid() ? j.var() : -1);
   for (;;)
     {
       if (va > vb)
         {
           ++i;
           va = (i.valid() ? i.var() : -1);
         }
       else if (va < vb)
         return false;
       else
         {
           if (va == -1) return true;
           int ea = i.exponent();
           int eb = j.exponent();
           if (ea < eb) return false;
           ++i;
           ++j;
           va = (i.valid() ? i.var() : -1);
           vb = (j.valid() ? j.var() : -1);
         }
     }
 }
References ExponentListIterator< E, L >::exponent(), ExponentListIterator< E, L >::valid(), and ExponentListIterator< E, L >::var().
Referenced by iquotient_and_sum().