Macaulay2 Engine: DMat< M2::ARingGFFlint >::fq_zech_mat
fq_zech_mat() [2/2]
const fq_zech_mat_t& DMat< M2::ARingGFFlint >::fq_zech_mat () const inline
Definition at line 117 of file dmat-gf-flint.hpp.
 { return mArray; }
References DMat< ACoeffRing >::mArray.
Referenced by MatrixOps::addMultipleTo(), MatrixOps::mult(), MatrixOps::rowReducedEchelonForm(), solveLowerTriangular< DMatGFFlint >(), solveUpperTriangular< DMatGFFlint >(), and MatrixOps::subtractMultipleTo().