Macaulay2 Engine: rawMonoid
rawMonoid()
const Monoid * rawMonoid (const MonomialOrdering * mo, const Ring * deg_ring, M2_ArrayString names, M2_arrayint degs, M2_arrayint hefts)
Definition at line 16 of file monoid.cpp.
{
  const auto P = deg_ring->cast_to_PolynomialRing();
  if (P == nullptr)
    {
      ERROR("expected polynomial ring");
      return nullptr;
    }
  return Monoid::create(mo,
                        P,
                        M2_ArrayString_to_stdvector(names),
                        M2_arrayint_to_stdvector<int>(degs),
                        M2_arrayint_to_stdvector<int>(hefts));
}
References Ring::cast_to_PolynomialRing(), Monoid::create(), ERROR(), and M2_ArrayString_to_stdvector().