Macaulay2 Engine: IM2_Monoid_make
IM2_Monoid_make()
engine_RawMonoidOrNull IM2_Monoid_make (const MonomialOrdering * mo, M2_ArrayString names, const Ring * deg_ring, M2_arrayint degs, M2_arrayint hefts)
Definition at line 21 of file monoid.cpp.
 {
   const PolynomialRing* P = deg_ring->cast_to_PolynomialRing();
   if (P == 0)
     {
       ERROR("expected polynomial ring");
       return 0;
     }
   return Monoid::create(mo, names, P, degs, hefts);
 }
References Ring::cast_to_PolynomialRing(), Monoid::create(), and ERROR().