Macaulay2 Engine: EigenM2::fill_from_MatrixXmp
fill_from_MatrixXmp() [1/2]
void EigenM2::fill_from_MatrixXmp (const MatrixXmpCCC & orig, LMatrixCCC & result)
Definition at line 302 of file eigen.cpp.
 {
   int numrows = orig.rows();
   int numcols = orig.cols();
   result.resize(numrows, numcols);
   for (int r=0; r<numrows; r++)
     for (int c=0; c<numcols; c++)
       result.ring().set_from_complex_mpfr(result.entry(r,c),
       orig(r,c).real().mpfr_srcptr(),
       orig(r,c).imag().mpfr_srcptr());
 }
References DMat< ACoeffRing >::entry(), DMat< ACoeffRing >::resize(), and DMat< ACoeffRing >::ring().