Macaulay2 Engine: EigenM2::eigenvectors_hermitian
eigenvectors_hermitian()
bool EigenM2::eigenvectors_hermitian (const LMatrixRRR * A, LMatrixRRR * eigenvals, LMatrixRRR * eigenvecs)
Definition at line 528 of file eigen.cpp.
{
   auto old_prec = Real::get_default_prec();
   Real::set_default_prec(A->ring().get_precision());
   MatrixXmpRRR AXmp(A->numRows(), A->numColumns());
   fill_to_MatrixXmp(*A, AXmp);
   Eigen::SelfAdjointEigenSolver<MatrixXmpRRR> es(AXmp);
   fill_from_MatrixXmp(es.eigenvalues(), *eigenvals);
   fill_from_MatrixXmp(es.eigenvectors(), *eigenvecs);
   Real::set_default_prec(old_prec);
   return true;
 }
References fill_from_MatrixXmp(), fill_to_MatrixXmp(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::ring().
Referenced by MatrixOps::eigenvectorsHermitian().