Macaulay2 Engine: EigenM2::fill_to_MatrixXmp
fill_to_MatrixXmp() [2/2]
void EigenM2::fill_to_MatrixXmp (const LMatrixRRR & orig, MatrixXmpRRR & result)
Definition at line 313 of file eigen.cpp.
 {
   for (int r=0; r<orig.numRows(); r++)
     for (int c=0; c<orig.numColumns(); c++)
       result(r,c) = Real(& orig.entry(r,c), false);
 }
References DMat< ACoeffRing >::entry(), DMat< ACoeffRing >::numColumns(), and DMat< ACoeffRing >::numRows().
Referenced by eigenvalues(), eigenvalues_hermitian(), eigenvectors(), eigenvectors_hermitian(), least_squares(), SVD(), and SVD_divide_conquer().