Macaulay2 Engine: EigenM2::fill_from_MatrixXmp
fill_from_MatrixXmp() [2/2]
void EigenM2::fill_from_MatrixXmp (const MatrixXmpRRR & orig, LMatrixRRR & result)
Definition at line 292 of file eigen.cpp.
 {
   int numrows = orig.rows();
   int numcols = orig.cols();
   result.resize(numrows, numcols);
   for (int r=0; r<numrows; r++)
     for (int c=0; c<numcols; c++)
       result.ring().set(result.entry(r,c), * orig(r,c).mpfr_srcptr());
 }
References DMat< ACoeffRing >::entry(), DMat< ACoeffRing >::resize(), and DMat< ACoeffRing >::ring().
Referenced by eigenvalues(), eigenvalues_hermitian(), eigenvectors(), eigenvectors_hermitian(), least_squares(), SVD(), and SVD_divide_conquer().