Macaulay2 Engine: EigenM2::SVD
SVD()
bool EigenM2::SVD (const LMatrixRRR * A, LMatrixRRR * Sigma, LMatrixRRR * U, LMatrixRRR * VT)
Definition at line 349 of file eigen.cpp.
 {
   auto old_prec = Real::get_default_prec();
   Real::set_default_prec(A->ring().get_precision());
   MatrixXmpRRR AXmp(A->numRows(), A->numColumns());
   fill_to_MatrixXmp(*A, AXmp);
   Eigen::JacobiSVD<MatrixXmpRRR> svd(AXmp, Eigen::ComputeThinU | Eigen::ComputeThinV);
   auto& eigenU = svd.matrixU();
   auto& eigenVT = svd.matrixV().adjoint();
   auto& eigenSigma = svd.singularValues();
   fill_from_MatrixXmp(eigenU, *U);
   fill_from_MatrixXmp(eigenVT, *VT);
   fill_from_MatrixXmp(eigenSigma, *Sigma);
   Real::set_default_prec(old_prec);
   return true;
 }
References fill_from_MatrixXmp(), fill_to_MatrixXmp(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::ring().
Referenced by MatrixOps::SVD().