Macaulay2 Engine: EigenM2::fill_to_MatrixXmp
fill_to_MatrixXmp() [1/2]
void EigenM2::fill_to_MatrixXmp (const LMatrixCCC & orig, MatrixXmpCCC & result)
Definition at line 320 of file eigen.cpp.
 {
   for (int r=0; r<orig.numRows(); r++)
     for (int c=0; c<orig.numColumns(); c++)
       result(r,c) = Complex(Real(& orig.entry(r,c).re, false),Real(& orig.entry(r,c).im, false));
 }
References DMat< ACoeffRing >::entry(), DMat< ACoeffRing >::numColumns(), and DMat< ACoeffRing >::numRows().