Macaulay2 Engine: EigenM2::least_squares
least_squares()
bool EigenM2::least_squares (const LMatrixRRR * A, const LMatrixRRR * B, LMatrixRRR * X)
Definition at line 558 of file eigen.cpp.
{
  auto old_prec = Real::get_default_prec();
  Real::set_default_prec(A->ring().get_precision());
  MatrixXmpRRR AXmp(A->numRows(), A->numColumns());
  fill_to_MatrixXmp(*A, AXmp);
  MatrixXmpRRR BXmp(B->numRows(), B->numColumns());
  fill_to_MatrixXmp(*B, BXmp);
  Eigen::BDCSVD<MatrixXmpRRR> svd(AXmp, Eigen::ComputeThinU | Eigen::ComputeThinV);
  fill_from_MatrixXmp(svd.solve(BXmp), *X);
  Real::set_default_prec(old_prec);
  return true;
}
References fill_from_MatrixXmp(), fill_to_MatrixXmp(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::ring().
Referenced by MatrixOps::leastSquares().