Macaulay2 Engine: ARingElementGenerator::nextElement
nextElement()
template<typename RingType > void ARingElementGenerator< RingType >::nextElement (typename RingType::ElementType & result) inline
Definition at line 20 of file ARingTest.hpp.
  {
    getElement<RingType>(mRing, ++mNext, result);
  }
References ARingElementGenerator< RingType >::mNext, and ARingElementGenerator< RingType >::mRing.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), testAdd(), testAxioms(), testDivide(), testMultiply(), testNegate(), testPower(), testReciprocal(), testRingNegateCCC(), testRingNegateCCC(), testRingNegateRR(), testRingNegateRRi(), testRingNegateRRR(), and testSubtract().