Macaulay2 Engine: DMatLinAlg< M2::ARingQQ >::solve
solve()
bool DMatLinAlg< M2::ARingQQ >::solve (const Mat & B1, Mat & X1) inline
Definition at line 137 of file dmat-lu-qq.hpp.
   {
     // This is the version where A = this isn't nec square or full rank...
     // Plan for now (we will see how efficient this version is): put A|B into a
     // single matrix.
     // rref
     // get column rank profile
     // from that, either return false (inconsistent), or copy the correct values
     // into X
     // Too bad flint doesn't do this automatically...
     // 1. copy A, B to flint objects
     // 2. concatenate them
     // 3. rref
     // 4. pivot columns
     // 5. if pivot column is in B columns, return false.
     // 6. otherwise:
     //   resize X
     //   populate X with the solution (only non-zero entries are in pivot
     //   columns
     // 6. copy
     // TODO
     long nrows = mInputMatrix.numRows();
     long ncols = mInputMatrix.numColumns();
     std::vector<size_t> profile;
     Mat AB1(mInputMatrix.ring(), nrows, ncols + B1.numColumns());
     concatenateMatrices<Mat>(mInputMatrix, B1, AB1);
     FlintQQMat AB(AB1);
     fmpq_mat_rref(AB.value(), AB.value());
     findColumnRankProfileFromLU(AB.value(), profile);
     if (profile[profile.size() - 1] >= ncols)
       return false;  // system is inconsistent
     // At this point, we know the solutions.  Should we go through FlintQQMat,
     // or go directly to Mat?
     FlintQQMat X(ncols, B1.numColumns());
     for (long c = 0; c < B1.numColumns(); c++)
       {
         // Fill in this column
         for (long r = 0; r < profile.size(); r++)
           {
             fmpq_set(fmpq_mat_entry(X.value(), profile[r], c),
                      fmpq_mat_entry(AB.value(), r, ncols + c));
           }
       }
     X.toDMat(X1);
     return true;
   }
References DMat< ACoeffRing >::numColumns(), FlintQQMat::toDMat(), and FlintQQMat::value().