Macaulay2 Engine: DMatLinAlg< M2::ARingQQ >::inverse
inverse()
bool DMatLinAlg< M2::ARingQQ >::inverse (Mat & result_inv) inline
Definition at line 199 of file dmat-lu-qq.hpp.
   {
     FlintQQMat A(mInputMatrix);
     // This seems like a lot of fuzzing around to get the inverse of a matrix
     // over QQ...
     // printf("in dmat-lu-qq inverse\n");
     long nrows = A.numRows();
     FlintQQMat inv(nrows, nrows);
     fmpz_t D, den;
     fmpz_mat_t matZZ, invZZ;
     fmpz_init(D);
     fmpz_init(den);
     fmpz_mat_init(matZZ, nrows, nrows);
     fmpz_mat_init(invZZ, nrows, nrows);
     fmpq_mat_get_fmpz_mat_matwise(matZZ, D, A.value());
     int result = fmpz_mat_inv(invZZ, den, matZZ);  // sets invZZ, den
     if (result != 0)
       {
         fmpq_mat_set_fmpz_mat_div_fmpz(inv.value(), invZZ, den);
         fmpq_mat_scalar_mul_fmpz(inv.value(), inv.value(), D);
         inv.toDMat(result_inv);
       }
     fmpz_clear(D);
     fmpz_clear(den);
     fmpz_mat_clear(matZZ);
     fmpz_mat_clear(invZZ);
     return (result != 0);
   }
References FlintQQMat::numRows(), FlintQQMat::toDMat(), and FlintQQMat::value().