Macaulay2 Engine: DMatLinAlg< M2::ARingQQ >::solveInvertible
solveInvertible()
bool DMatLinAlg< M2::ARingQQ >::solveInvertible (const Mat & B1, Mat & X1) inline
Definition at line 186 of file dmat-lu-qq.hpp.
   {
     FlintQQMat A(mInputMatrix);
     FlintQQMat B(B1);
     FlintQQMat X(mInputMatrix.numColumns(), B1.numColumns());
     //    int isfullrank = fmpq_mat_solve_fraction_free(X.value(), A.value(),
     //    B.value());
     int isfullrank = fmpq_mat_solve_dixon(X.value(), A.value(), B.value());
     if (isfullrank == 0) return false;
     X.toDMat(X1);
     return true;
   }
References DMat< ACoeffRing >::numColumns(), FlintQQMat::toDMat(), and FlintQQMat::value().