Macaulay2 Engine: DMatLinAlg< M2::ARingQQ >::kernel
kernel()
size_t DMatLinAlg< M2::ARingQQ >::kernel (Mat & result_nullspace) inline
Definition at line 229 of file dmat-lu-qq.hpp.
   {
     FlintQQMat A(mInputMatrix);
     // printf("in dmat-lu-qq kernel\n");
     fmpz_mat_t matZZ;
     fmpz_mat_t kerZZ;
     fmpz_mat_init(matZZ, A.numRows(), A.numColumns());
     fmpz_mat_init(kerZZ, A.numColumns(), A.numColumns());
     fmpq_mat_get_fmpz_mat_rowwise(matZZ, NULL, A.value());
     long nullity = fmpz_mat_nullspace(kerZZ, matZZ);
     FlintQQMat kerQQ(A.numColumns(), nullity);
     for (long r = 0; r < A.numColumns(); r++)
       for (long c = 0; c < nullity; c++)
         {
           // There is no function which sets an fmpq from an fmpz!
           kerQQ.set_from_fmpz(r, c, fmpz_mat_entry(kerZZ, r, c));
         }
     // fmpq_mat_set_fmpz_mat(kerQQ.value(), kerZZ);
     kerQQ.toDMat(result_nullspace);
     fmpz_mat_clear(matZZ);
     fmpz_mat_clear(kerZZ);
     return nullity;
   }
References FlintQQMat::numColumns(), FlintQQMat::numRows(), FlintQQMat::set_from_fmpz(), FlintQQMat::toDMat(), and FlintQQMat::value().