Macaulay2 Engine: DMatLinAlg< M2::ARingQQ >::columnRankProfile
columnRankProfile()
void DMatLinAlg< M2::ARingQQ >::columnRankProfile (std::vector< size_t > & profile) inline
Definition at line 58 of file dmat-lu-qq.hpp.
   {
     FlintQQMat A(mInputMatrix);
     FlintQQMat B(A.numRows(), A.numColumns());
     fmpq_mat_rref(B.value(), A.value());
     findColumnRankProfileFromLU(B.value(), profile);
   }
References FlintQQMat::numColumns(), FlintQQMat::numRows(), and FlintQQMat::value().