Macaulay2 Engine: EngineMonomial::operator/
operator/()
EngineMonomial * EngineMonomial::operator/ (const EngineMonomial & b) const
Definition at line 130 of file monomial.cpp.
 {
   EngineMonomial *result = new EngineMonomial;
   varpower::quotient(ints(), b.ints(), result->val);
   return result;
 }
References EngineMonomial(), ints(), ExponentList< E, L >::quotient(), and val.