Macaulay2 Engine: EngineMonomial::operator*
operator*()
EngineMonomial * EngineMonomial::operator* (const EngineMonomial & b) const
Definition at line 122 of file monomial.cpp.
 {
   EngineMonomial *result = new EngineMonomial;
   varpower::mult(ints(), b.ints(), result->val);
   if (error()) return 0;
   return result;
 }
References EngineMonomial(), error(), ints(), ExponentList< E, L >::mult(), and val.