Macaulay2 Engine: EngineMonomial::make
make() [3/4]
EngineMonomial * EngineMonomial::make (int v, int e) static
Definition at line 26 of file monomial.cpp.
 {
   EngineMonomial *result = new EngineMonomial(v, e);
   if (error()) return 0;
   return result;
 }
References EngineMonomial(), and error().
Referenced by RingElement::lead_monom(), M2FreeAlgebra::list_form(), PolyRing::list_form(), and SchurRing2::list_form().