Macaulay2 Engine: EngineMonomial::radical
radical()
EngineMonomial * EngineMonomial::radical () const
Definition at line 152 of file monomial.cpp.
 {
   EngineMonomial *result = new EngineMonomial;
   varpower::radical(ints(), result->val);
   return result;
 }
References EngineMonomial(), ints(), ExponentList< E, L >::radical(), and val.