Macaulay2 Engine: EngineMonomial::power
power()
EngineMonomial * EngineMonomial::power (int n) const
Definition at line 144 of file monomial.cpp.
 {
   EngineMonomial *result = new EngineMonomial;
   varpower::power(ints(), n, result->val);
   if (error()) return 0;
   return result;
 }
References EngineMonomial(), error(), ints(), ExponentList< E, L >::power(), and val.