Macaulay2 Engine: EngineMonomial::compare
compare()
int EngineMonomial::compare (const Monoid * M, const EngineMonomial & b) const
Definition at line 76 of file monomial.cpp.
 {
   monomial monom1 = M->make_one();
   monomial monom2 = M->make_one();
   M->from_varpower(ints(), monom1);
   M->from_varpower(b.ints(), monom2);
   int result = M->compare(monom1, monom2);
   M->remove(monom1);
   M->remove(monom2);
   return result;
 }
References Monoid::compare(), Monoid::from_varpower(), ints(), Monoid::make_one(), monom1, monom2, and Monoid::remove().