Macaulay2 Engine: EngineMonomial::make
make() [4/4]
EngineMonomial * EngineMonomial::make (M2_arrayint m) static
Definition at line 33 of file monomial.cpp.
{
  if ((m->len % 2) != 0)
    {
      ERROR("Monomial expected an even number of elements");
      return nullptr;
    }
  for (unsigned int i = 2; i < m->len; i += 2)
    if (m->array[i - 2] <= m->array[i])
      {
        ERROR("Monomial expects variables in descending order");
        return nullptr;
      }
  EngineMonomial *result = new EngineMonomial(m);
  if (error()) return nullptr;
  return result;
}
References EngineMonomial(), error(), and ERROR().