Macaulay2 Engine: EngineMonomial::ints
ints() [1/2]
int * EngineMonomial::ints () inline
Definition at line 38 of file monomial.hpp.
{ return val.data(); }
References val.
Referenced by compare(), divides(), erase(), gcd(), RingElement::get_coeff(), IM2_RingElement_term(), is_equal(), is_one(), lcm(), monsyz(), operator*(), operator/(), power(), radical(), rawColonMonomialIdeal1(), rawSaturateMonomialIdeal1(), and simple_degree().