Macaulay2 Engine: EngineMonomial::divides
divides()
bool EngineMonomial::divides (const Monoid * M, const EngineMonomial & b) const
Definition at line 88 of file monomial.cpp.
 {
   monomial monom1 = M->make_one();
   monomial monom2 = M->make_one();
   M->from_varpower(ints(), monom1);
   M->from_varpower(b.ints(), monom2);
   bool result = M->divides(monom1, monom2);
   M->remove(monom1);
   M->remove(monom2);
   return result;
 }
References Monoid::divides(), Monoid::from_varpower(), ints(), Monoid::make_one(), monom1, monom2, and Monoid::remove().