Macaulay2 Engine: EngineMonomial::gcd
gcd()
EngineMonomial * EngineMonomial::gcd (const EngineMonomial & b) const
Definition at line 114 of file monomial.cpp.
 {
   EngineMonomial *result = new EngineMonomial;
   varpower::gcd(ints(), b.ints(), result->val);
   return result;
 }
References EngineMonomial(), varpower::gcd(), ints(), and val.