Macaulay2 Engine: partition_table::partition
partition()
void partition_table::partition (MonomialIdeal *& I, gc_vector< MonomialIdeal * > & result)
Definition at line 103 of file hilb.cpp.
 {
   int k;
   reset(I->topvar() + 1);
   // Create the sets
   for (Bag& a : *I)
     if (n_sets > 1)
       merge_in(a.monom().raw());
     else
       break;
   if (n_sets == 1)
     {
       result.push_back(I);
       return;
     }
   int this_label = -1;
   n_sets = 0;
   for (k = 0; k < n_vars; k++)
     if (occurs[k] && dad[k] < 0)
       {
         dad[k] = this_label--;
         n_sets++;
       }
   if (n_sets == 1)
     {
       result.push_back(I);
       return;
     }
   int first = result.size();
   for (k = 0; k < n_sets; k++)
     result.push_back(new MonomialIdeal(I->get_ring(), mi_stash));
   // Now partition the monomials
   Bag *b;
   while (I->remove(b))
     {
       const intarray &m = b->monom();
       int v = varpower::topvar(m.raw());
       int loc = -1 - dad[representative(v)];
       result[first + loc]->insert_minimal(b);
     }
   delete I;
 }
References dad, MonomialIdeal::insert_minimal(), merge_in(), mi_stash, int_bag::monom(), n_sets, n_vars, occurs, intarray::raw(), representative(), reset(), MonomialIdeal::size(), MonomialIdeal::topvar(), and varpower::topvar().
Referenced by hilb_comp::hilb_comp(), hilb_comp::next_monideal(), and hilb_comp::recurse().