Macaulay2 Engine: partition_table::merge_in
merge_in() [1/2]
void partition_table::merge_in (const_varpower m) private
Definition at line 81 of file hilb.cpp.
 {
   index_varpower i = m;
   int var1 = i.var();
   occurs[var1] = 1;
   ++i;
   for (; i.valid(); ++i)
     {
       var1 = merge_in(var1, i.var());
       occurs[i.var()] = 1;
     }
 }
References merge_in(), occurs, ExponentListIterator< E, L >::valid(), and ExponentListIterator< E, L >::var().