Macaulay2 Engine: GBRingSkew::mult_by_term1
mult_by_term1()
gbvector * GBRingSkew::mult_by_term1 (const FreeModule * F, const gbvector * f, ring_elem u, const int * monom, int comp) virtual
Implements GBRing.
Definition at line 153 of file gbring.cpp.
 {
   gbvector head;
   gbvector *inresult = &head;
   exponents_t EXP1 = ALLOCATE_EXPONENTS(exp_size);
   exponents_t EXP2 = ALLOCATE_EXPONENTS(exp_size);
   M->to_expvector(m, EXP1);
   for (const gbvector *s = f; s != nullptr; s = s->next)
     {
       gbvector_get_lead_exponents(F, s, EXP2);
       int sign = _skew.mult_sign(EXP1, EXP2);
       if (sign == 0) continue;
       gbvector *t = new_raw_term();
       t->next = nullptr;
       t->comp = s->comp + comp;
       t->coeff = K->mult(c, s->coeff);
       if (sign < 0) K->negate_to(t->coeff);
       M->mult(m, s->monom, t->monom);
       inresult->next = t;
       inresult = inresult->next;
     }
   inresult->next = nullptr;
   return head.next;
 }
References GBRing::_skew, ALLOCATE_EXPONENTS, gbvector::coeff, gbvector::comp, GBRing::exp_size, GBRing::gbvector_get_lead_exponents(), GBRing::K, GBRing::M, gbvector::monom, Ring::mult(), Monoid::mult(), SkewMultiplication::mult_sign(), Ring::negate_to(), GBRing::new_raw_term(), gbvector::next, and Monoid::to_expvector().