Macaulay2 Engine: GBRingSkew::GBRingSkew
GBRingSkew()
GBRingSkew::GBRingSkew (const Ring * K0, const Monoid * M0, SkewMultiplication skew0) protected
Definition at line 127 of file gbring.cpp.
     : GBRing(K0, M0)
 {
   _is_skew = true;
   _skew = skew0;
   int **skew_monoms = newarray(int *, _skew.n_skew_vars());
   exponents_t exp = newarray_atomic_clear(int, M0->n_vars());
   for (int v = 0; v < _skew.n_skew_vars(); v++)
     {
       exp[_skew.skew_variable(v)]++;
       skew_monoms[v] = M0->make_one();
       M0->from_expvector(exp, skew_monoms[v]);
       exp[_skew.skew_variable(v)]--;
     }
   _skew_monoms = skew_monoms;
 }
References GBRing::_is_skew, GBRing::_skew, GBRing::_skew_monoms, mpfr::exp(), Monoid::from_expvector(), Monoid::make_one(), SkewMultiplication::n_skew_vars(), Monoid::n_vars(), newarray, newarray_atomic_clear, and SkewMultiplication::skew_variable().