Macaulay2 Engine: M2FreeAlgebraQuotient::numVars
numVars()
int M2FreeAlgebraQuotient::numVars () const inline
Definition at line 46 of file M2FreeAlgebraQuotient.hpp.
 { return monoid().numVars(); }
References monoid(), and FreeMonoid::numVars().
Referenced by n_vars().