Macaulay2 Engine: M2FreeAlgebraQuotient::from_long
from_long()
ring_elem M2FreeAlgebraQuotient::from_long (long n) const virtual
Implements Ring.
Definition at line 75 of file M2FreeAlgebraQuotient.cpp.
{
  return from_coefficient(coefficientRing()->from_long(n));
}
References coefficientRing(), from_coefficient(), and from_long().
Referenced by create(), and from_long().