Macaulay2 Engine: M2FreeAlgebraQuotient::power
power() [1/2]
ring_elem M2FreeAlgebraQuotient::power (const ring_elem f, int n) const virtual
Reimplemented from Ring.
Definition at line 241 of file M2FreeAlgebraQuotient.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
   auto result = new Poly;
   freeAlgebraQuotient().power(*result,*f,n);
   return ring_elem(reinterpret_cast<void *>(result));
 }
References freeAlgebraQuotient(), ring_elem::get_Poly(), and FreeAlgebraQuotient::power().