Macaulay2 Engine: M2FreeAlgebraQuotient::n_terms
n_terms()
long M2FreeAlgebraQuotient::n_terms (const ring_elem f) const
Definition at line 162 of file M2FreeAlgebraQuotient.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
   return freeAlgebraQuotient().n_terms(*f);
 }
References freeAlgebraQuotient(), ring_elem::get_Poly(), and FreeAlgebraQuotient::n_terms().
Referenced by is_zero().