Macaulay2 Engine: M2FreeAlgebraQuotient::coefficientRing
coefficientRing()
const Ring* M2FreeAlgebraQuotient::coefficientRing () const inline virtual
Implements M2FreeAlgebraOrQuotient.
Definition at line 44 of file M2FreeAlgebraQuotient.hpp.
 { return m2FreeAlgebra().coefficientRing(); }
References M2FreeAlgebra::coefficientRing(), and m2FreeAlgebra().
Referenced by debug_display(), from_int(), from_long(), from_rational(), lift(), and promote().