Macaulay2 Engine: M2FreeAlgebraQuotient::from_coefficient
from_coefficient()
ring_elem M2FreeAlgebraQuotient::from_coefficient (const ring_elem a) const virtual
Implements M2FreeAlgebraOrQuotient.
Definition at line 68 of file M2FreeAlgebraQuotient.cpp.
 {
   auto result = new Poly;
   freeAlgebraQuotient().from_coefficient(*result, a);
   return ring_elem(reinterpret_cast<void *>(result));
 }
References freeAlgebraQuotient(), and FreeAlgebraQuotient::from_coefficient().
Referenced by from_int(), from_long(), from_rational(), and promote().