Macaulay2 Engine: M2FreeAlgebraQuotient::from_int
from_int()
ring_elem M2FreeAlgebraQuotient::from_int (mpz_srcptr n) const virtual
Implements Ring.
Definition at line 80 of file M2FreeAlgebraQuotient.cpp.
{
  return from_coefficient(coefficientRing()->from_int(n));
}
References coefficientRing(), from_coefficient(), and from_int().
Referenced by from_int().