Macaulay2 Engine: M2FreeAlgebraQuotient::add
add()
ring_elem M2FreeAlgebraQuotient::add (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 206 of file M2FreeAlgebraQuotient.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
   auto g = reinterpret_cast<const Poly*>(g1.get_Poly());
   auto result = new Poly;
   freeAlgebraQuotient().add(*result,*f,*g);
   return ring_elem(reinterpret_cast<void *>(result));
 }
References FreeAlgebraQuotient::add(), freeAlgebraQuotient(), and ring_elem::get_Poly().