Macaulay2 Engine: M2FreeAlgebraQuotient::lift
lift()
bool M2FreeAlgebraQuotient::lift (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 122 of file M2FreeAlgebraQuotient.cpp.
 {
   // R is the target ring
   // f1 is an element of 'this'.
   // set result to be the "lift" of f in the ring R, return true if this is possible.
   // otherwise return false.
   // case: R is the coefficient ring of 'this'.
   if (R == coefficientRing())
     {
       auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
       if (f->numTerms() != 1) return false;
       auto i = f->cbegin();
       if (monoid().is_one(i.monom()))
         {
           result = coefficientRing()->copy(i.coeff());
           return true;
         }
       return false;
     }
   if (R == &m2FreeAlgebra())
     {
       // just copy the element into result, considered in the free algebra.
       auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
       auto resultf = new Poly;
       freeAlgebra().copy(*resultf, *f);
       result = ring_elem(reinterpret_cast<void *>(resultf));
       return true;
     }
   // at this point, we can't lift it.
   return false;
 }
References coefficientRing(), Ring::copy(), FreeAlgebra::copy(), freeAlgebra(), ring_elem::get_Poly(), FreeMonoid::is_one(), m2FreeAlgebra(), and monoid().