Macaulay2 Engine: M2FreeAlgebraQuotient::makeTerm
makeTerm() [2/2]
void M2FreeAlgebraQuotient::makeTerm (Poly & result, const ring_elem a, const int * monom) const
Definition at line 291 of file M2FreeAlgebraQuotient.cpp.
 {
   m2FreeAlgebra().makeTerm(result, a, monom);
   freeAlgebraQuotient().normalizeInPlace(result);
 }
References freeAlgebraQuotient(), m2FreeAlgebra(), M2FreeAlgebra::makeTerm(), and FreeAlgebraQuotient::normalizeInPlace().