Macaulay2 Engine: M2FreeAlgebraQuotient::freeAlgebraQuotient
freeAlgebraQuotient()
const FreeAlgebraQuotient& M2FreeAlgebraQuotient::freeAlgebraQuotient () const inline
Definition at line 39 of file M2FreeAlgebraQuotient.hpp.
 { return *mFreeAlgebraQuotient; }
References mFreeAlgebraQuotient.
Referenced by add(), compare_elems(), elem_text_out(), eval(), from_coefficient(), is_equal(), is_homogeneous(), is_unit(), make_SumCollector(), mult(), multi_degree(), n_terms(), negate(), power(), promote(), subtract(), and var().