Macaulay2 Engine: M2FreeAlgebraQuotient::elem_text_out
elem_text_out()
void M2FreeAlgebraQuotient::elem_text_out (buffer & o, const ring_elem f, bool p_one, bool p_plus, bool p_parens) const virtual
Implements Ring.
Definition at line 304 of file M2FreeAlgebraQuotient.cpp.
 {
   auto f = reinterpret_cast<const Poly*>(ff.get_Poly());
   freeAlgebraQuotient().elem_text_out(o,*f,p_one,p_plus,p_parens);
 }
References FreeAlgebraQuotient::elem_text_out(), freeAlgebraQuotient(), and ring_elem::get_Poly().