Macaulay2 Engine: M2FreeAlgebraQuotient::create
create()
M2FreeAlgebraQuotient * M2FreeAlgebraQuotient::create (const M2FreeAlgebra & F, const Matrix * GB, int maxdeg) static
Definition at line 28 of file M2FreeAlgebraQuotient.cpp.
 {
   auto gbElements = copyMatrixToVector(F, GB);
   auto A = std::unique_ptr<FreeAlgebraQuotient> (new FreeAlgebraQuotient(F.freeAlgebra(), gbElements, maxdeg));
   M2FreeAlgebraQuotient* result = new M2FreeAlgebraQuotient(F, std::move(A));
   result->initialize_ring(F.coefficientRing()->characteristic(), F.degreeRing(), {});
   result->zeroV = result->from_long(0);
   result->oneV = result->from_long(1);
   result->minus_oneV = result->from_long(-1);
   return result;
 }
References Ring::characteristic(), M2FreeAlgebra::coefficientRing(), copyMatrixToVector(), M2FreeAlgebra::degreeRing(), M2FreeAlgebra::freeAlgebra(), from_long(), Ring::initialize_ring(), M2FreeAlgebraQuotient(), Ring::minus_oneV, Ring::oneV, and Ring::zeroV.
Referenced by IM2_Ring_quotient(), and rawRingM2FreeAlgebraQuotient().