Macaulay2 Engine: M2FreeAlgebraQuotient::from_rational
from_rational()
bool M2FreeAlgebraQuotient::from_rational (const mpq_srcptr q, ring_elem & result) const virtual
Implements Ring.
Definition at line 85 of file M2FreeAlgebraQuotient.cpp.
 {
   ring_elem cq; // in coeff ring.
   bool worked = coefficientRing()->from_rational(q, cq);
   if (!worked) return false;
   result1 = from_coefficient(cq);
   return true;
 }
References coefficientRing(), from_coefficient(), and Ring::from_rational().