Macaulay2 Engine: M2FreeAlgebraQuotient::m2FreeAlgebra
m2FreeAlgebra()
const M2FreeAlgebra & M2FreeAlgebraQuotient::m2FreeAlgebra () const inline
Definition at line 38 of file M2FreeAlgebraQuotient.hpp.
{ return mM2FreeAlgebra; }
References mM2FreeAlgebra.
Referenced by coefficientRing(), degreeMonoid(), divide(), freeAlgebra(), get_terms(), get_terms(), IM2_RingElement_list_form(), index_of_var(), invert(), lead_coefficient(), lift(), list_form(), monoid(), promote(), and text_out().