Macaulay2 Engine: M2FreeAlgebraQuotient::promote
promote()
bool M2FreeAlgebraQuotient::promote (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 101 of file M2FreeAlgebraQuotient.cpp.
 {
   // std::cout << "called promote NC case" << std::endl;
   // Currently the only case to handle is R = A --> this, and A is the coefficient ring of this.
   if (R == coefficientRing())
     {
       result = from_coefficient(f1);
       return true;
     }
   if (R == &m2FreeAlgebra())
     {
       auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
       auto resultf = new Poly;
       freeAlgebraQuotient().copy(*resultf, *f);
       freeAlgebraQuotient().normalizeInPlace(*resultf);
       result = ring_elem(reinterpret_cast<void *>(resultf));
       return true;
     }
   return false;
 }
References coefficientRing(), FreeAlgebraQuotient::copy(), freeAlgebraQuotient(), from_coefficient(), ring_elem::get_Poly(), m2FreeAlgebra(), and FreeAlgebraQuotient::normalizeInPlace().