Macaulay2 Engine: M2FreeAlgebraQuotient::mult
mult()
ring_elem M2FreeAlgebraQuotient::mult (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 224 of file M2FreeAlgebraQuotient.cpp.
{
  auto f = reinterpret_cast<const Poly*>(f1.get_Poly());
  auto g = reinterpret_cast<const Poly*>(g1.get_Poly());
  auto result = new Poly;
  freeAlgebraQuotient().mult(*result,*f,*g);
  return ring_elem(reinterpret_cast<void *>(result));
}
References freeAlgebraQuotient(), ring_elem::get_Poly(), and FreeAlgebraQuotient::mult().