Macaulay2 Engine: FreeMonoid::degreeMonoid
degreeMonoid()
const Monoid & FreeMonoid::degreeMonoid () const inline
Definition at line 79 of file FreeMonoid.hpp.
{ return * mDegreeRing->getMonoid(); }
References PolynomialRing::getMonoid(), and mDegreeRing.
Referenced by M2FreeAlgebra::degreeMonoid(), M2FreeAlgebraQuotient::degreeMonoid(), FreeAlgebra::degreeMonoid(), FreeAlgebraQuotient::degreeMonoid(), FreeMonoid(), multi_degree(), and ncBasis().