Macaulay2 Engine: FreeMonoid::compare
compare() [1/2]
int FreeMonoid::compare (const Monom & m1, const Monom & m2) const
Definition at line 99 of file FreeMonoid.cpp.
 {
   // order of events:
   // compare weights first
   // then compare word length
   // then compare with lex
   // is this thread-safe?
   //FreeMonoidLogger::logCompare();
   // compare weights first
   for (int j = 1; j <= mNumWeights; ++j)
     {
       if (m1[j] > m2[j]) return GT;
       if (m1[j] < m2[j]) return LT;
     }
   // at this point, the weights are the same.
   // the total length is just mNumWeights + 1 + wordLength, so just
   // compare the total length (i.e. m1[0] and m2[0]
   if (m1.size() > m2.size()) return GT;
   if (m1.size() < m2.size()) return LT;
   // at this stage, they have the same weights and word length, so use lex order
   for (int j = mNumWeights+1; j < m1.size(); ++j)
     {
       if (m1[j] > m2[j]) return LT;
       if (m1[j] < m2[j]) return GT;
     }
   // if we are here, the monomials are the same.
   return EQ;
 }
References EQ, GT, LT, mNumWeights, and Monom::size().
Referenced by NaiveQueueConfiguration::compare(), NaiveDedupQueueConfiguration::compare(), FreeAlgebra::compare_elems(), NaivePolynomialHeap< Queue >::isZero(), PriorityQueuePolynomialHeap::isZero(), MonomEq::operator()(), EntryConfig::operator()(), and MonomSort< T >::operator()().