Macaulay2 Engine: FreeMonoid::wordFromMonom
wordFromMonom()
void FreeMonoid::wordFromMonom (Word & result, const Monom & m) const
Definition at line 287 of file FreeMonoid.cpp.
 {
   // just call the prefix command on the word length of the monom
   result.init(m.begin() + mNumWeights + 1, m.end());
   //wordPrefixFromMonom(result,m,wordLength(m));
 }
References Monom::begin(), Monom::end(), Word::init(), and mNumWeights.
Referenced by constructWordTable(), FreeAlgebra::heft_degree(), FreeAlgebra::lead_word(), and NCF4::processPreRow().