Macaulay2 Engine: FreeMonoid::wordSuffixFromMonom
wordSuffixFromMonom()
void FreeMonoid::wordSuffixFromMonom (Word & result, const Monom & m, int beginIndex) const
Definition at line 299 of file FreeMonoid.cpp.
{
  result.init(m.begin() + mNumWeights + 1 + beginIndex, m.end());
}
References Monom::begin(), Monom::end(), Word::init(), and mNumWeights.
Referenced by FreeAlgebra::lead_word_suffix().