Macaulay2 Engine: FreeMonoid::isEqual
isEqual()
bool FreeMonoid::isEqual (const Monom & m1, const Monom & m2) const
Definition at line 162 of file FreeMonoid.cpp.
 {
   //if (wordLength(m1) != wordLength(m2)) return false;
   return std::equal(m1.begin(),m1.end(),m2.begin(),m2.end());
 }
References Monom::begin(), and Monom::end().
Referenced by MonomHashEqual::operator()().