Macaulay2 Engine: FreeMonoid::weightOfVar
weightOfVar()
int FreeMonoid::weightOfVar (int v, int wt) const inline private
Definition at line 168 of file FreeMonoid.hpp.
 { return mWeightVectors[v+wt*numVars()]; }
References mWeightVectors, and numVars().
Referenced by compare(), setWeights(), and var().