Macaulay2 Engine: FreeMonoid::FreeMonoid
FreeMonoid()
FreeMonoid::FreeMonoid (const std::vector< std::string > & variableNames, const PolynomialRing * degreeRing, const std::vector< int > & degrees, const std::vector< int > & wtvecs, const std::vector< int > & heftVector)
Definition at line 21 of file FreeMonoid.cpp.
  : mVariableNames(variableNames),
    mDegreeRing(degreeRing),
    mDegrees(degrees),
    mWeightVectors(wtvecs),
    mHeftVector(heftVector),
    mNumWeights(wtvecs.size() / variableNames.size())
{
  auto ndegrees = degreeMonoid().n_vars();
  [[maybe_unused]] auto nvars = variableNames.size();
  assert(nvars * ndegrees == mDegrees.size());
  for (const int* i = mDegrees.data(); i != mDegrees.data() + mDegrees.size(); i += ndegrees)
    {
      monomial deg = degreeMonoid().make_one();
      degreeMonoid().from_expvector(i, deg);
      mDegreeOfVar.push_back(deg);
    }
  for (auto deg : mDegreeOfVar)
    mHeftDegrees.push_back(degreeMonoid().degree_weights(deg, mHeftVector));
}
References Monoid::degree_weights(), degreeMonoid(), Monoid::from_expvector(), Monoid::make_one(), mDegreeOfVar, mDegrees, mHeftDegrees, mHeftVector, Monoid::n_vars(), and variableNames().