Macaulay2 Engine: FreeMonoid::is_one
is_one()
bool FreeMonoid::is_one (const Monom & m) const
Definition at line 62 of file FreeMonoid.cpp.
 {
   return m[0] == mNumWeights+1;
 }
References mNumWeights.
Referenced by FreeAlgebra::elem_text_out(), FreeAlgebra::is_unit(), M2FreeAlgebra::lift(), and M2FreeAlgebraQuotient::lift().