Macaulay2 Engine: FreeMonoid::multi_degree
multi_degree()
void FreeMonoid::multi_degree (const Monom & m, monomial already_allocated_degree_vector) const
Definition at line 168 of file FreeMonoid.cpp.
 {
   int* result = already_allocated_degree_vector; // just to use a smaller name...
   degreeMonoid().one(result); // reset value
   auto word_length = wordLength(m);
   auto word_ptr = m + mNumWeights+1;
   for (auto j = 0; j < word_length; j++)
     {
       degreeMonoid().mult(result, mDegreeOfVar[word_ptr[j]], result);
     }
 }
References degreeMonoid(), mDegreeOfVar, mNumWeights, Monoid::mult(), Monoid::one(), and wordLength().
Referenced by FreeAlgebra::is_homogeneous(), and FreeAlgebra::multi_degree().