Macaulay2 Engine: FreeMonoid::wordProductAsMonom
wordProductAsMonom() [1/3]
Monom FreeMonoid::wordProductAsMonom (const Word & left, const Monom & mid, const Word & right, MemoryBlock & memBlock) const
Definition at line 397 of file FreeMonoid.cpp.
 {
   int monomOffset = numWeights() + 1;
   int sz = left.size() + mid.size() + right.size();
   auto rg = memBlock.allocateArray<int>(sz);
   rg.first[0] = sz;
   std::copy(left.begin(), left.end(), rg.first + monomOffset);
   std::copy(mid.begin()+monomOffset, mid.end(), rg.first + left.size() + monomOffset);
   std::copy(right.begin(), right.end(), rg.first + left.size() + mid.size());
   Monom newmon = Monom(rg.first);
   setWeights(newmon);
   return newmon;
 }
References MemoryBlock< T, NSLAB >::allocateArray(), Word::begin(), Monom::begin(), Word::end(), Monom::end(), numWeights(), setWeights(), Word::size(), and Monom::size().