Macaulay2 Engine: FreeMonoid::mult3
mult3()
void FreeMonoid::mult3 (const Monom & m1, const Monom & m2, const Monom & m3, MonomialInserter & result) const
Definition at line 88 of file FreeMonoid.cpp.
 {
   int sz = m1[0] + wordLength(m2) + wordLength(m3);
   result.push_back(sz);
   for (int i=1; i<=mNumWeights; ++i)
     result.push_back(m1[i] + m2[i] + m3[i]);
   result.insert(result.end(),m1.begin()+mNumWeights+1,m1.end());
   result.insert(result.end(),m2.begin()+mNumWeights+1,m2.end());
   result.insert(result.end(),m3.begin()+mNumWeights+1,m3.end());
 }
References Monom::begin(), Monom::end(), mNumWeights, and wordLength().
Referenced by FreeAlgebra::mult_by_term_left_and_right().