Macaulay2 Engine: FreeMonoid::monomInsertFromWord
monomInsertFromWord()
void FreeMonoid::monomInsertFromWord (MonomialInserter & result, const Word & w) const
Definition at line 304 of file FreeMonoid.cpp.
 {
   result.push_back(word.size() + mNumWeights + 1);
   for (int j = 0; j < mNumWeights; ++j)
     result.push_back(0);
   for (auto a : word) result.push_back(a);
   Monom tmpMonom(&*(result.end()-1-mNumWeights-word.size()));
   setWeights(tmpMonom);
 }
References mNumWeights, setWeights(), and word.
Referenced by NCF4::displayF4Matrix(), NCF4::displayFullF4Matrix(), FreeAlgebra::from_word(), FreeAlgebra::mult_by_term_left(), FreeAlgebra::mult_by_term_left_and_right(), FreeAlgebra::mult_by_term_right(), and NCF4::reducedRowToPoly().