Macaulay2 Engine: FreeMonoid::setWeights
setWeights()
void FreeMonoid::setWeights (Monom & m) const private
Definition at line 314 of file FreeMonoid.cpp.
{
  // since Monoms are wrappers to const ints, it seems we need
  // this line so we can set the weights, but I'm not 100% sure
  auto monom = const_cast<int*>(m.begin());
  int word_len = wordLength(m);
  for (int j = 1; j <= mNumWeights; ++j)
      monom[j] = 0;
  // eventually replace both for loops with:
  // word = Word(m)
  //for (int k = 0; k < mNumWeights; ++k)
  //  monom[k+1] = wordWeight(word,iterator to beginning of kth weight)
  for (int j = 0; j < word_len; ++j)
    {
      for (int k = 0; k < mNumWeights; ++k)
        {
          monom[k+1] += weightOfVar(m[mNumWeights+1+j],k);
        }
    }
}
References Monom::begin(), mNumWeights, weightOfVar(), and wordLength().
Referenced by monomInsertFromWord(), wordProductAsMonom(), wordProductAsMonom(), and wordProductAsMonom().