Macaulay2 Engine: FreeMonoid::elem_text_out
elem_text_out()
void FreeMonoid::elem_text_out (buffer & o, const Monom & m1) const
Definition at line 181 of file FreeMonoid.cpp.
 {
   auto word_length = wordLength(m);
   auto word_ptr = m + mNumWeights + 1;
   for (auto j = 0; j < word_length; j++)
     {
       // for now, just output the string.
       int curvar = word_ptr[j];
       int curvarPower = 0;
       o << mVariableNames[curvar];
       while ((j < word_length) && (word_ptr[j] == curvar))
         {
           j++;
           curvarPower++;
         }
       if (curvarPower > 1) o << "^" << curvarPower;
       // back j up one since we went too far looking ahead.
       j--;
     }
 }
References mNumWeights, mVariableNames, and wordLength().
Referenced by NCF4::displayF4Matrix(), NCF4::displayFullF4Matrix(), and FreeAlgebra::elem_text_out().