Macaulay2 Engine: FreeMonoid::mult
mult()
void FreeMonoid::mult (const Monom & m1, const Monom & m2, MonomialInserter & result) const
Definition at line 78 of file FreeMonoid.cpp.
{
  int sz = m1[0] + wordLength(m2);
  result.push_back(sz);
  for (int i=1; i<=mNumWeights; ++i)
    result.push_back(m1[i] + m2[i]);
  result.insert(result.end(),m1.begin()+mNumWeights+1,m1.end());
  result.insert(result.end(),m2.begin()+mNumWeights+1,m2.end());
}
References Monom::begin(), Monom::end(), mNumWeights, and wordLength().
Referenced by FreeAlgebra::mult_by_term_left(), and FreeAlgebra::mult_by_term_right().