Macaulay2 Engine: FreeMonoid::copy
copy()
void FreeMonoid::copy (const Monom & m, MonomialInserter & result) const
Definition at line 73 of file FreeMonoid.cpp.
 {
   result.insert(result.end(),m.begin(),m.end());
 }
References Monom::begin(), and Monom::end().
Referenced by FreeAlgebra::addScalarMultipleOf(), and M2FreeAlgebra::get_terms().