Macaulay2 Engine: Subsets::decode
decode()
void Subsets::decode (size_t val, Subset & result)
Definition at line 96 of file comb.cpp.
 {
   size_t tmp = val;
   size_t subsetSize = result.size();
   assert(val <= binom(mNumElements, subsetSize));
   size_t len = mNumElements;
   for (size_t i = subsetSize; i > 0; i--)
     {
       size_t bit;
       size_t bot = 0;
       while (bit = len % 2, len >>= 1)
         {
           if (binom(bot + len, i) <= tmp)
             {
               bot += len;
               len += bit;
             }
         }
       result[i - 1] = bot;
       tmp -= binom(bot, i);
       len = bot + 1;
     }
   assert(isValid(result));
 }
References binom(), isValid(), and mNumElements.
Referenced by Matrix::koszul(), TEST(), and Matrix::wedge_product().