Macaulay2 Engine: Subsets::encodeBoundary
encodeBoundary()
size_t Subsets::encodeBoundary (size_t index, const Subset & a)
Definition at line 80 of file comb.cpp.
 {
   assert(a.size() <= mMaxSubsetSize);
   assert(isValid(a));
   size_t result = 0;
   for (size_t i = 0; i < e; i++) result += binom(a[i], i + 1);
   for (size_t i = e + 1; i < a.size(); i++) result += binom(a[i], i);
   return result;
 }
References binom(), isValid(), and mMaxSubsetSize.
Referenced by Matrix::koszul(), and TEST().