Macaulay2 Engine: Subsets::increment
increment() [2/2]
bool Subsets::increment (size_t n, Subset & s) static
Definition at line 124 of file comb.cpp.
{
  if (s.size() == 0) return false;
  return increment(n, s.size(), &(s[0]));
#if 0
  size_t p = s.size();
  for (size_t i=0; i<p; i++)
    {
      // Attempt to increment this one element
      if ((i < p-1 && s[i]+1 < s[i+1])
          || (i == p-1 && s[i]+1 < n))
        {
          s[i]++;
          for (size_t j=0; j<i; j++)
            s[j] = j;
          return true;
        }
    }
  return false;
#endif
}
References increment(), and p.
Referenced by FreeModule::exterior(), SchreyerOrder::exterior(), increment(), DetComputation::step(), PfaffianComputation::step(), and TEST().