Macaulay2 Engine: M2::ARingZZGMP::invert
invert()
void M2::ARingZZGMP::invert (ElementType & result, const ElementType & a) const inline
Definition at line 118 of file aring-zz-gmp.hpp.
   {
     if (is_unit(a))
       set(result, a);
     else
       set_zero(result);
   }
References is_unit(), set(), and set_zero().