Macaulay2 Engine: M2::ARingZZGMP::syzygy
syzygy()
void M2::ARingZZGMP::syzygy (const ElementType & a, const ElementType & b, ElementType & x, ElementType & y) const
Definition at line 45 of file aring-zz-gmp.cpp.
 {
   assert(!is_zero(b));
   // First check the special cases a = 0, b = 1, -1.  Other cases: use gcd.
   if (is_zero(a))
     {
       set_from_long(x, 1);
       set_zero(y);
       return;
     }
   if (mpz_cmp_ui(&b, 1) == 0)
     {
       set_from_long(x, 1);
       negate(y, a);
       return;
     }
   if (mpz_cmp_si(&b, -1) == 0)
     {
       set_from_long(x, 1);
       set(y, a);
       return;
     }
   elem g;
   init(g);
   mpz_gcd(&g, &a, &b);
   divide(y, a, g);
   divide(x, b, g);
   if (mpz_sgn(&x) > 0)
     negate(y, y);
   else
     negate(x, x);
   clear(g);
 }
References clear(), divide(), init(), is_zero(), negate(), set(), set_from_long(), set_zero(), and x.