Macaulay2 Engine: M2::mylift
mylift() [7/16]
bool M2::mylift (const ARingRR & R, const ARingCCC & S, ARingRR::ElementType & result_gR, const ARingCCC::ElementType & gS) inline
Definition at line 401 of file aring-translate.hpp.
 {
   auto gS1 = const_cast<ARingRRR::ElementType&>(S.realPartReference(gS));
   R.set_from_BigReal(result_gR, &gS1);
   return (S.real_ring().is_zero(S.imaginaryPartReference(gS)));
 }
References M2::ARingCCC::imaginaryPartReference(), M2::ARingRRR::is_zero(), M2::ARingCCC::real_ring(), M2::ARingCCC::realPartReference(), and M2::ARingRR::set_from_BigReal().