Macaulay2 Engine: M2::mylift
mylift() [12/16]
bool M2::mylift (const ARingRRR & R, const ARingCCC & S, ARingRRR::ElementType & result_gR, const ARingCCC::ElementType & gS) inline
Definition at line 367 of file aring-translate.hpp.
{
  R.set(result_gR, S.realPartReference(gS));
  return (R.is_zero(S.imaginaryPartReference(gS)));
}
References M2::ARingCCC::imaginaryPartReference(), M2::ARingRRR::is_zero(), M2::ARingCCC::realPartReference(), and M2::ARingRRR::set().