Macaulay2 Engine: M2::mylift
mylift() [5/16]
bool M2::mylift (const ARingQQ & R, const ARingRRi & S, ARingQQ::ElementType & result_gR, const ARingRRi::ElementType & gS) inline
Definition at line 481 of file aring-translate.hpp.
 {
     ARingRRR T(S.get_precision());
     ARingRRR::Element gT(T);
     auto gS1 = const_cast<ARingRRi::ElementType&>(gS);
     S.midpoint(gT,gS1);
     bool liftstep = mylift(R,T,result_gR,gT);
     S.diameter(gT,gS1);
     return liftstep && T.is_zero(gT);
 }
References M2::ARingRRi::diameter(), M2::ARingRRi::get_precision(), M2::ARingRRi::midpoint(), mylift(), and T.