Macaulay2 Engine: SolvableAlgebra::create
create() [2/2]
SolvableAlgebra * SolvableAlgebra::create (const Ring * K, const Monoid * M, const Matrix * Q) static private
Definition at line 16 of file solvable.cpp.
 {
   SolvableAlgebra *result = new SolvableAlgebra;
   result->initialize_poly_ring(K, M);
   if (!result->initialize_solvable(Q)) return 0;
   result->gb_ring_ = GBRing::create_SolvableAlgebra(K, M, result);
   return result;
 }
References GBRing::create_SolvableAlgebra(), PolynomialRing::gb_ring_, PolyRing::initialize_poly_ring(), initialize_solvable(), and SolvableAlgebra().
Referenced by create(), and IM2_Ring_solvable_algebra().