Macaulay2 Engine: SkewPolynomialRing::antipode
antipode()
ring_elem SkewPolynomialRing::antipode (const ring_elem f) const virtual
Reimplemented from Ring.
Definition at line 37 of file skewpoly.cpp.
 {
   Nterm head;
   Nterm *inresult = &head;
   exponents_t EXP = ALLOCATE_EXPONENTS(exp_size);
   for (Nterm& s : f)
     {
       M_->to_expvector(s.monom, EXP);
       int deg = skew_.skew_degree(EXP);
       // sign is (-1)^ (binomial(deg,2))
       // deg = 0: sign is 1
       // deg = 1: sign is 1
       // deg = 2: sign is -1
       // deg = 3: sign is -1
       // deg = 4: sign is 1, and so on
       int mod4 = deg % 4;
       int sign = sign4[mod4];
       Nterm *t = new_term();
       t->next = nullptr;
       t->coeff = (sign == 1 ? s.coeff : K_->negate(s.coeff));
       M_->copy(s.monom, t->monom);
       inresult->next = t;
       inresult = inresult->next;
     }
   inresult->next = nullptr;
   return head.next;
 }
References ALLOCATE_EXPONENTS, Nterm::coeff, Monoid::copy(), PolynomialRing::exp_size, PolynomialRing::K_, PolynomialRing::M_, Nterm::monom, Ring::negate(), PolyRing::new_term(), Nterm::next, sign4, PolynomialRing::skew_, SkewMultiplication::skew_degree(), and Monoid::to_expvector().