Macaulay2 Engine: SkewPolynomialRing::create
create()
SkewPolynomialRing * SkewPolynomialRing::create (const Ring * K, const Monoid * M, M2_arrayint skewvars) static
Definition at line 15 of file skewpoly.cpp.
 {
   SkewPolynomialRing *result = new SkewPolynomialRing;
   result->initialize_poly_ring(K, M);
   if (!result->initialize_skew(skewvars)) return nullptr;
   result->gb_ring_ = GBRing::create_SkewPolynomialRing(K, M, result->skew_);
   return result;
 }
References GBRing::create_SkewPolynomialRing(), PolynomialRing::gb_ring_, PolyRing::initialize_poly_ring(), initialize_skew(), PolynomialRing::skew_, and SkewPolynomialRing().
Referenced by IM2_Ring_skew_polyring().