Macaulay2 Engine: interreduction
interreduction()
void interreduction (IntermediateBasis & F)
Definition at line 376 of file franzi-gb.cpp.
 {
   bool changesHappened = true;
   IntermediateBasis::iterator end = F.end();
   unsigned long numChanged = 0;
   while (changesHappened)
     {
       changesHappened = false;
       for (IntermediateBasis::iterator it = F.begin(); it != end;)
         {
           if (reduce(it->second, F, it))
             {
               // we changed it
               numChanged++;
               if (it->second.isZero())
                 {  // reduced an element to 0, remove it from F
                   F.erase(it++);
                 }
               else
                 {
                   ++it;
                 }
               changesHappened = true;
             }
           else
             {
               ++it;
             }
         }
     }
 }
References end(), and reduce().
Referenced by gb().