Macaulay2 Engine: gb
gb()
void gb (IntermediateBasis & F, int n)
Definition at line 409 of file franzi-gb.cpp.
{
  int nextIndex = static_cast<int>(F.size());
  rearrangeBasis(F, -1);
  interreduction(F);
  Pairs B = makeList(F, n);
  // unsigned int countAddPoly = 0;
  // unsigned int numSPoly= 0;
  int interreductionCounter = 0;
  while (!B.empty())
    {
      Pair pair = *(B.begin());
      B.erase(B.begin());
      if (isGoodPair(pair, F, B, n))
        {
          // numSPoly++;
          BRP S = sPolynomial(pair, F, n);
          reduce(S, F);
          if (!S.isZero())
            {
              // countAddPoly++;
              F[nextIndex] = S;
              if (interreductionCounter == 5)
                {
                  interreductionCounter = 0;
                  interreduction(F);
                  B = makeList(F, n);
                }
              else
                {
                  interreductionCounter++;
                  Pairs newList = makeNewPairs(nextIndex, F, n);
                  B.insert(newList.begin(), newList.end());
                }
              nextIndex++;
            }
        }
    }
  interreduction(F);
  // cout << "we computed " << numSPoly << " S Polynomials and added " <<
  // countAddPoly << " of them to the intermediate basis." << endl;
}
References interreduction(), isGoodPair(), BRP::isZero(), makeList(), makeNewPairs(), rearrangeBasis(), reduce(), and sPolynomial().
Referenced by constructWordTable(), GBDeclared::create(), GBDeclared::create(), GBDeclared::GBDeclared(), GBDeclared::GBDeclared(), F4Computation::get_gb(), IM2_GB_force(), ncBasis(), rawGbBoolean(), rawGroebnerWalk(), rawMarkedGB(), and F4toM2Interface::to_M2_MutableMatrix().