Macaulay2 Engine: findDivisor
findDivisor()
IntermediateBasis::const_iterator findDivisor (const BRP & f, const IntermediateBasis & F, const IntermediateBasis::const_iterator itF)
Definition at line 270 of file franzi-gb.cpp.
 {
   IntermediateBasis::const_iterator end = F.end();
   for (IntermediateBasis::const_iterator it = F.begin();
        it != end && !f.isZero();
        ++it)
     {
       if (itF != it)
         {
           if (f.isLeadingReducibleBy(it->second))
             {
               return it;
             }
         }
     }
   return end;
 }
References end(), BRP::isLeadingReducibleBy(), and BRP::isZero().
Referenced by reduceLt().