Macaulay2 Engine: isGoodPair
isGoodPair()
bool isGoodPair (const Pair & pair, const IntermediateBasis & F, const Pairs & B, int n)
Definition at line 192 of file franzi-gb.cpp.
 {
   FunctionPair fp = FunctionPair(pair, F, n);
   if (!fp.good)
     {
       return false;
     }
   // both polynomials are monomials, so their S polynomial reduces to 0
   if (fp.g->size() == 1 && fp.f->size() == 1)
     {
       // cout << "m ";
       return false;
     }
   brMonomial g = fp.g->LT();
   brMonomial f = fp.f->LT();
   if (BRP::isRelativelyPrime(g, f))
     {
       return false;
     }
   int i = pair.i;
   int j = pair.j;
   brMonomial lcm = pair.lcm;
   IntermediateBasis::const_iterator end = F.end();
   for (IntermediateBasis::const_iterator it = F.begin(); it != end; ++it)
     {
       int k = it->first;
       const BRP *K = &(it->second);
       if ((k != i && k != j && BRP::isDivisibleBy(lcm, K->LT()) &&
            !inList(i, k, B, F) && !inList(j, k, B, F)))
         {
           return false;
         }
     }
   // cout << "good pair ";
   return true;
 }
References end(), FunctionPair::f, FunctionPair::g, FunctionPair::good, Pair::i, inList(), BRP::isDivisibleBy(), BRP::isRelativelyPrime(), Pair::j, Pair::lcm, BRP::LT(), and BRP::size().
Referenced by gb().