Macaulay2 Engine: sPolynomial
sPolynomial()
BRP sPolynomial (const Pair & pair, const IntermediateBasis & F, int n)
Definition at line 239 of file franzi-gb.cpp.
 {
   FunctionPair fp = FunctionPair(pair, F, n);
   if (!fp.good)
     {
       return BRP();
     }
   if (pair.i < 0)
     {
       // fp.g = x_i
       // f = ax + b
       BRP b = (fp.f)->remainder(*fp.g);
       return b * *fp.g + b;
     }
   brMonomial f = fp.f->LT();
   brMonomial g = fp.g->LT();
   brMonomial lcm = f | g;
   return *fp.f * (lcm ^ f) + *fp.g * (lcm ^ g);
 }
References FunctionPair::f, FunctionPair::g, FunctionPair::good, Pair::i, BRP::LT(), and mpfr::remainder().
Referenced by gb().