Macaulay2 Engine: reduceLt
reduceLt()
bool reduceLt (BRP & f, const IntermediateBasis & F, const IntermediateBasis::const_iterator itF)
Definition at line 293 of file franzi-gb.cpp.
 {
   bool ret = false;  // true if anything was reduced
   IntermediateBasis::const_iterator it;
   IntermediateBasis::const_iterator end = F.end();
   while (!f.isZero() && (it = findDivisor(f, F, itF)) != end)
     {
       ret = true;
       cancelLeadTerm(f, it->second);
     }
   return ret;
 }
References cancelLeadTerm(), end(), findDivisor(), and BRP::isZero().
Referenced by reduce().