Macaulay2 Engine: reduceTail
reduceTail()
bool reduceTail (BRP & f, const IntermediateBasis & F, const IntermediateBasis::const_iterator itF)
Definition at line 309 of file franzi-gb.cpp.
 {
   IntermediateBasis::const_iterator end = F.end();
   bool ret = false;
   for (IntermediateBasis::const_iterator it = F.begin();
        it != end && !f.isZero();
        ++it)
     {
       if (itF != it)
         {
           if (f.reduceTail(it->second))
             {
               it = F.begin();
               ret = true;
             }
         }
     }
   return ret;
 }
References end(), BRP::isZero(), and BRP::reduceTail().
Referenced by reduce().