Macaulay2 Engine: M2::ARingCCC::set
set()
void M2::ARingCCC::set (ElementType & result, const ElementType & a) const inline
Definition at line 115 of file aring-CCC.hpp.
   {
     mpfr_set(&result.re, &a.re, MPFR_RNDN);
     mpfr_set(&result.im, &a.im, MPFR_RNDN);
   }
References cc_struct::im, and cc_struct::re.
Referenced by copy(), divide(), from_ring_elem(), mult(), M2::mylift(), M2::mypromote(), power(), syzygy(), and to_ring_elem().