Macaulay2 Engine: M2::ARingCCC::mult
mult() [2/2]
void M2::ARingCCC::mult (ElementType & res, const ElementType & a, const RealElementType & b) const inline
Definition at line 275 of file aring-CCC.hpp.
   {
     mpfr_t tmp;
     Element result(*this);
     mpfr_init2(tmp, get_precision());
     // &result.re = &a.re*&b;
     mpfr_mul(tmp, &a.re, &b, MPFR_RNDN);
     mpfr_set(&result.value().re, tmp, MPFR_RNDN);
     // &result.im = &a.im*&b;
     mpfr_mul(tmp, &a.im, &b, MPFR_RNDN);
     mpfr_set(&result.value().im, tmp, MPFR_RNDN);
     set(res, result);
     mpfr_clear(tmp);
   }
References get_precision(), cc_struct::im, cc_struct::re, and set().
Referenced by addMultipleTo(), power(), subtract_multiple(), and TEST().