Macaulay2 Engine: M2::ARingCCC::to_ring_elem
to_ring_elem()
void M2::ARingCCC::to_ring_elem (ring_elem & result, const ElementType & a) const inline
Definition at line 80 of file aring-CCC.hpp.
   {
     cc_ptr res = getmemstructtype(cc_ptr);
     init(*res);
     set(*res, a);
     mpfr_reallocate_limbs(&res->re);
     mpfr_reallocate_limbs(&res->im);
     result = ring_elem(res);
   }
References getmemstructtype, cc_struct::im, init(), mpfr_reallocate_limbs(), cc_struct::re, and set().
Referenced by rawRoots().