Macaulay2 Engine: M2::ARingCCC::increase_norm
increase_norm()
void M2::ARingCCC::increase_norm (gmp_RRmutable norm, const ElementType & a) const inline
Definition at line 556 of file aring-CCC.hpp.
   {
     ARingRRR::ElementType n;
     mRRR.init(n);
     abs(n, a);
     if (mpfr_cmp(&n, norm) > 0) mRRR.set(*norm, n);
     mRRR.clear(n);
   }
References abs(), M2::ARingRRR::clear(), M2::ARingRRR::init(), mRRR, and M2::ARingRRR::set().