Macaulay2 Engine: M2::ARingCCC::abs_squared
abs_squared()
void M2::ARingCCC::abs_squared (ARingRRR::ElementType & result, const ElementType & a) const inline
Definition at line 393 of file aring-CCC.hpp.
   {
     mRRR.mult(result, realPartReference(a), realPartReference(a));
     ARingRRR::Element s(mRRR);
     mRRR.mult(s, imaginaryPartReference(a), imaginaryPartReference(a));
     mRRR.add(result, result, s);
   }
References M2::ARingRRR::add(), imaginaryPartReference(), mRRR, M2::ARingRRR::mult(), and realPartReference().
Referenced by abs().