Macaulay2 Engine: M2::ARingCCC::get_precision
get_precision()
unsigned long M2::ARingCCC::get_precision () const inline
Definition at line 40 of file aring-CCC.hpp.
 { return mRRR.get_precision(); }
References M2::ARingRRR::get_precision(), and mRRR.
Referenced by almostEqual(), divide(), init(), invert(), mult(), text_out(), and toBigComplex().