Macaulay2 Engine: M2::ARingCCC::eval
eval()
void M2::ARingCCC::eval (const RingMap * map, ElementType & f, int first_var, ring_elem & result) const inline
Definition at line 480 of file aring-CCC.hpp.
   {
     gmp_CC_struct g;
     g.re = &f.re;
     g.im = &f.im;
     if (!map->get_ring()->from_BigComplex(&g, result))
       {
         result = map->get_ring()->from_long(0);
         ERROR("cannot map CC value to ring type");
       }
   }
References ERROR(), Ring::from_BigComplex(), Ring::from_long(), RingMap::get_ring(), cc_struct::im, and cc_struct::re.