Macaulay2 Engine: M2::ARingCCC::power_mpz
power_mpz()
void M2::ARingCCC::power_mpz (ElementType & result, const ElementType & a, mpz_srcptr n) const inline
Definition at line 436 of file aring-CCC.hpp.
   {
     std::pair<bool, int> n1 = RingZZ::get_si(n);
     if (n1.first)
       power(result, a, n1.second);
     else
       throw exc::engine_error("exponent too large");
   }
References RingZZ::get_si(), and power().
Referenced by TEST().