Macaulay2 Engine: M2::ARingCCC::init
init()
void M2::ARingCCC::init (ElementType & result) const inline
Definition at line 102 of file aring-CCC.hpp.
   {
     mpfr_init2(&result.re, get_precision());
     mpfr_init2(&result.im, get_precision());
   }
References get_precision(), cc_struct::im, and cc_struct::re.
Referenced by almostEqual(), init_set(), power(), TEST(), testRingNegateCCC(), and to_ring_elem().