Macaulay2 Engine: NCGroebner::createOverlapPoly
createOverlapPoly() [1/2]
auto NCGroebner::createOverlapPoly (const FreeAlgebra & A, const PolyList & polyList, int polyIndex1, int polyIndex2, int overlapIndex) -> Poly* static
Definition at line 351 of file NCGroebner.cpp.
 {
   // here, polyIndex1 and 2 are indices into polyList, and overlapIndex
   // is the index where the overlap starts in the polynomial pointed in
   // by *polyIndex1*.
   Poly* result = new Poly;
   Poly tmp1, tmp2;
   Word prefix, suffix;
   prefix = A.lead_word_prefix(*polyList[polyIndex1], overlapIndex);
   suffix = A.lead_word_suffix(*polyList[polyIndex2], *(polyList[polyIndex1]->cbegin().monom().begin()) - A.monoid().numWeights() - 1 - overlapIndex);
   A.mult_by_term_right(tmp1, *polyList[polyIndex1], A.coefficientRing()->from_long(1), suffix);
   A.mult_by_term_left(tmp2, *polyList[polyIndex2], A.coefficientRing()->from_long(1), prefix);
   A.subtract(*result, tmp1, tmp2);
   return result;
 }
References begin(), prefix(), and suffix().
Referenced by computeHomogeneous(), computeInhomogeneous(), and TEST().