Macaulay2 Engine: NCGroebner::twoSidedReduction
twoSidedReduction() [1/2]
auto NCGroebner::twoSidedReduction (const ConstPolyList & reducees) const -> ConstPolyList
Definition at line 326 of file NCGroebner.cpp.
 {
   ConstPolyList result;
   for (auto i = reducees.cbegin(); i != reducees.cend(); ++i)
     result.push_back(twoSidedReduction(*i));
   return result;
 }
Referenced by computeHomogeneous(), computeInhomogeneous(), and FreeAlgebraQuotient::normalizeInPlace().