Macaulay2 Engine: NCGroebner::autoreduceByLastElement
autoreduceByLastElement()
void NCGroebner::autoreduceByLastElement ()
Definition at line 204 of file NCGroebner.cpp.
 {
   if (mGroebner.size() <= 1) return;
   const Poly& lastPoly = *(mGroebner[mGroebner.size()-1]);
   const Monom& leadMon = lastPoly.cbegin().monom();
   for (auto fPtr = mGroebner.begin(); fPtr != mGroebner.end() - 1; ++fPtr)
   {
     ring_elem foundCoeff = getCoeffOfMonom(**fPtr,leadMon);
     if (!freeAlgebra().coefficientRing()->is_zero(foundCoeff))
     {
       Poly* result = new Poly;
       freeAlgebra().subtractScalarMultipleOf(*result,**fPtr,lastPoly,foundCoeff);
       freeAlgebra().swap(**fPtr,*result);
     }
   }
 }
References freeAlgebra(), getCoeffOfMonom(), mGroebner, FreeAlgebra::subtractScalarMultipleOf(), and FreeAlgebra::swap().
Referenced by computeHomogeneous(), and computeInhomogeneous().