Macaulay2 Engine: NCGroebner::freeAlgebra
freeAlgebra()
const FreeAlgebra & NCGroebner::freeAlgebra () const inline
Definition at line 48 of file NCGroebner.hpp.
{ return mFreeAlgebra; }
References mFreeAlgebra.
Referenced by addToGroebnerBasis(), autoreduceByLastElement(), computeHomogeneous(), computeInhomogeneous(), getCoeffOfMonom(), NCGroebner(), and updateOverlaps().