Macaulay2 Engine: NCGroebner::computeHomogeneous
computeHomogeneous()
void NCGroebner::computeHomogeneous (int softDegreeLimit)
Definition at line 69 of file NCGroebner.cpp.
 {
   size_t n_spairs = 0;
   while (!mOverlapTable.isFinished(softDegreeLimit))
     {
       auto degSet = mOverlapTable.nextDegreeOverlaps();
       auto toBeProcessed = degSet.second;
       if (M2_gbTrace >= 1)
         {
           buffer o;
           o << "[" << degSet.first << "](" << toBeProcessed->size() << ")";
           emit(o.str());
         }
       while(!toBeProcessed->empty())
         {
           auto overlap = toBeProcessed->front();
           //if this is a `real' overlap, and the overlap is not necessary, then move
           //on to the next overlap.
           if (std::get<1>(overlap) != -1 && !isOverlapNecessary(overlap))
             {
               toBeProcessed->pop_front();
               if (M2_gbTrace >= 3)
                 {
                   std::cout << "Reduction avoided using 2nd criterion." << std::endl;
                   std::cout << "table after pop:";
                   mOverlapTable.dump(std::cout,true);
                 }
               // TODO: is this logic correct?  Is the overlap actually skipped?
               continue;
             }
           auto overlapPoly = createOverlapPoly(overlap);
           n_spairs++;
           auto redOverlapPoly = twoSidedReduction(overlapPoly);
           delete overlapPoly;
           if (!freeAlgebra().is_zero(*redOverlapPoly))
             {
               addToGroebnerBasis(redOverlapPoly);
               autoreduceByLastElement();
               updateOverlaps(redOverlapPoly);
             }
           else
             {
               // if reduction is zero
               if (M2_gbTrace >= 4)
                 {
                   std::cout << "Overlap " << overlap << " reduced to zero."
                             << std::endl;
                 }
             }
           toBeProcessed->pop_front();
         }
       // remove the lowest degree overlaps from the overlap table
       mOverlapTable.removeLowestDegree();
     }
   if (M2_gbTrace >= 1)
     {
       buffer o;
       o << "[NCGB] number of spair reductions: " << n_spairs;
       emit_line(o.str());
     }
 }
References addToGroebnerBasis(), autoreduceByLastElement(), createOverlapPoly(), OverlapTable::dump(), emit(), emit_line(), freeAlgebra(), OverlapTable::isFinished(), isOverlapNecessary(), M2_gbTrace, mOverlapTable, OverlapTable::nextDegreeOverlaps(), OverlapTable::removeLowestDegree(), buffer::size(), buffer::str(), twoSidedReduction(), and updateOverlaps().
Referenced by compute().