Macaulay2 Engine: NCGroebner::addToGroebnerBasis
addToGroebnerBasis()
void NCGroebner::addToGroebnerBasis (Poly * toAdd)
Definition at line 197 of file NCGroebner.cpp.
{
  // add in auto-reduction here?
  freeAlgebra().makeMonicInPlace(*toAdd);
  mGroebner.push_back(toAdd);
}
References freeAlgebra(), FreeAlgebra::makeMonicInPlace(), and mGroebner.
Referenced by computeHomogeneous(), and computeInhomogeneous().