Macaulay2 Engine: NCGroebner::NCGroebner
NCGroebner()
NCGroebner::NCGroebner (const FreeAlgebra & A, const ConstPolyList & input, int hardDegreeLimit, int strategy)
Definition at line 20 of file NCGroebner.cpp.
   : mFreeAlgebra(A),
     mInput(input),
     mHeap(makePolynomialHeap(getHeapType(strategy), A)),
     mTopComputedDegree(-1),
     mHardDegreeLimit(hardDegreeLimit)
 {
   if (M2_gbTrace >= 1)
     {
       buffer o;
       o << "[NCGB] reduction heap:  "
         << getHeapName(getHeapType(strategy))
         << newline;
       emit_line(o.str());
     }
   Word tmpWord;
   // process input polynomials
   mIsGraded = true;
   for (auto i = 0; i < mInput.size(); ++i)
     {
       auto d = freeAlgebra().heft_degree(*mInput[i]);
       mGeneratorDegrees.push_back(d.first);
       if (not d.second)
         mIsGraded = false;
       tmpWord = freeAlgebra().lead_word(*mInput[i]);
       mOverlapTable.insert(d.first, // previously: freeAlgebra().monoid().wordHeft(tmpWord),
                            true,
                            std::make_tuple(i,-1,-1,true));
     }
   if (M2_gbTrace >= 1)
     {
       buffer o;
       o << "[NCGB] input is " << (mIsGraded ? "homogeneous" : "inhomogeneous") << newline;
       emit_line(o.str());
     }
 }
References emit_line(), freeAlgebra(), getHeapName(), getHeapType(), FreeAlgebra::heft_degree(), OverlapTable::insert(), FreeAlgebra::lead_word(), M2_gbTrace, mGeneratorDegrees, mInput, mIsGraded, mOverlapTable, newline, and buffer::str().