Macaulay2 Engine: ResGausserQQ::isAllowedCoefficientRing
isAllowedCoefficientRing()
bool ResGausserQQ::isAllowedCoefficientRing (const Ring * K) const virtual
Implements ResGausser.
Definition at line 73 of file res-f4-m2-interface.cpp.
 {
   return K->ringID() == M2::ring_RR or
          (K->isFinitePrimeField() and
           K->characteristic() == Kp1.characteristic());
 }
References M2::ARingZZpFlint::characteristic(), Ring::characteristic(), Ring::isFinitePrimeField(), Kp1, M2::ring_RR, and Ring::ringID().