Macaulay2 Engine: ResGausserQQ::from_ring_elem
from_ring_elem()
void ResGausserQQ::from_ring_elem (CoefficientVector & result, ring_elem numer, ring_elem denom) const virtual
Implements ResGausser.
Definition at line 97 of file res-f4-m2-interface.cpp.
 {
   const M2::ARingZZGMP* Z = globalZZ->get_ARing();
   auto& elems = coefficientVector(result);
   const M2::ARingZZGMP::ElementType& numer1 = Z->from_ring_elem_const(numer);
   const M2::ARingZZGMP::ElementType& denom1 = Z->from_ring_elem_const(denom);
   bool isunit = Z->is_equal(numer1, denom1);
   mpq_t c;
   mpq_init(c);
   mpq_set_num(c, &numer1);
   mpq_set_den(c, &denom1);
   mpq_canonicalize(c);
   FieldElement b;
   b.mDouble = mpq_get_d(c);
   Kp1.set_from_mpq(b.mMod1, c);
   b.mDenominatorSize = (isunit ? 0 : 1);
   elems.push_back(b);
   mpq_clear(c);
 }
References coefficientVector(), M2::ARingZZGMP::from_ring_elem_const(), RingZZ::get_ARing(), globalZZ, M2::ARingZZGMP::is_equal(), Kp1, ResGausserQQ::FieldElement::mDenominatorSize, ResGausserQQ::FieldElement::mDouble, ResGausserQQ::FieldElement::mMod1, and M2::ARingZZpFlint::set_from_mpq().