Macaulay2 Engine: ResGausserQQ::out
out() [1/2]
std::ostream & ResGausserQQ::out (std::ostream & o, CoefficientVector f, int loc) const virtual
Implements ResGausser.
Definition at line 234 of file res-gausser-QQ.cpp.
 {
   if (r.isNull())
     {
       o << "[vector is null!]";
       return o;
     }
   auto& elems = coefficientVector(r);
   out(o, elems[loc]);
   return o;
 }
References coefficientVector(), CoefficientVector::isNull(), and out().