Macaulay2 Engine: ResGausserQQ::debugDisplay
debugDisplay()
std::ostream & ResGausserQQ::debugDisplay (std::ostream & o, CoefficientVector r) const virtual
Implements ResGausser.
Definition at line 247 of file res-gausser-QQ.cpp.
 {
   if (r.isNull()) fprintf(stdout, "vector is null!");
   auto& elems = coefficientVector(r);
   for (int j = 0; j < elems.size(); ++j)
     {
       out(o, r, j);
       o << " ";
     }
   o << std::endl;
   return o;
 }
References coefficientVector(), CoefficientVector::isNull(), and out().