Macaulay2 Engine: ResGausserQQ::out
out() [2/2]
std::ostream & ResGausserQQ::out (std::ostream & o, FieldElement & f) const
Definition at line 227 of file res-gausser-QQ.cpp.
 {
   o << "[" << f.mDouble << "," << Kp1.coerceToLongInteger(f.mMod1) << ","
     << f.mDenominatorSize << "]";
   return o;
 }
References M2::ARingZZpFlint::coerceToLongInteger(), Kp1, ResGausserQQ::FieldElement::mDenominatorSize, ResGausserQQ::FieldElement::mDouble, and ResGausserQQ::FieldElement::mMod1.
Referenced by debugDisplay(), debugDisplayRow(), and out().