Macaulay2 Engine: ResGausserQQ::coefficientVector
coefficientVector() [2/2]
CoefficientVector ResGausserQQ::coefficientVector (std::vector< FieldElement > * vals) const inline private
Definition at line 38 of file res-gausser-QQ.hpp.
   {
     CoefficientVector result;
     result.mValue = vals;
     vals = nullptr;
     return result;
   }
References CoefficientVector::mValue.
Referenced by allocateCoefficientVector(), debugDisplay(), debugDisplayRow(), from_ring_elem(), out(), pushBackElement(), pushBackMinusOne(), pushBackNegatedElement(), pushBackOne(), size(), to_modp_long(), and to_ring_elem().