Macaulay2 Engine: ResGausserQQ::ResGausserQQ
ResGausserQQ()
ResGausserQQ::ResGausserQQ (const Ring * K, size_t p1)
Definition at line 9 of file res-gausser-QQ.cpp.
     : ResGausser(K1), Kp1(p1), mMaxDenominatorSize(1)
 {
   // set RR, ring of ZZ/p too.
   mZero = FieldElement{0.0, 0, 0};
   mOne = FieldElement{1.0, 0, 0};
   mMinusOne = FieldElement{-1.0, 0, 0};
   Kp1.set_zero(mZero.mMod1);
   Kp1.set_from_long(mOne.mMod1, 1);
   Kp1.negate(mMinusOne.mMod1, mOne.mMod1);
 }
References Kp1, mMinusOne, ResGausserQQ::FieldElement::mMod1, mOne, mZero, M2::ARingZZpFlint::negate(), M2::ARingZZpFlint::set_from_long(), and M2::ARingZZpFlint::set_zero().