Macaulay2 Engine: ResGausserQQ::to_ring_elem
to_ring_elem()
ring_elem ResGausserQQ::to_ring_elem (const Ring * K, const CoefficientVector & coeffs, size_t loc) const virtual
Implements ResGausser.
Definition at line 80 of file res-f4-m2-interface.cpp.
 {
   auto& elems = coefficientVector(coeffs);
   ring_elem result;
   if (K->ringID() == M2::ring_RR)
     K->from_double(elems[loc].mDouble, result);
   else if (K == globalZZ)
     {
       result = K->from_long(elems[loc].mDenominatorSize);
     }
   else
     Kp1.to_ring_elem(result, elems[loc].mMod1);
   return result;
 }
References coefficientVector(), Ring::from_double(), Ring::from_long(), globalZZ, Kp1, M2::ring_RR, Ring::ringID(), and M2::ARingZZpFlint::to_ring_elem().