Macaulay2 Engine: DMat< M2::ARingZZ >::columnEnd
columnEnd()
ConstIterator DMat< M2::ARingZZ >::columnEnd (size_t col) const inline
Definition at line 69 of file dmat-zz-flint.hpp.
   {
     return ConstIterator(array() + col + numRows() * numColumns(),
                          numColumns());
   }
References DMat< ACoeffRing >::array(), DMat< ACoeffRing >::numColumns(), and DMat< ACoeffRing >::numRows().