Macaulay2 Engine: buffer::to_string
to_string()
M2_string buffer::to_string ()
Definition at line 17 of file buffer.cpp.
 { return M2_tostringn(_buf, _size); }
References _buf, _size, and M2_tostringn().
Referenced by engineMemory(), IM2_FreeModule_to_string(), IM2_GB_to_string(), IM2_Matrix_to_string(), IM2_Monoid_to_string(), IM2_MutableMatrix_to_string(), IM2_Ring_to_string(), IM2_RingElement_to_string(), IM2_RingMap_to_string(), MonomialIdeal_to_string(), rawHomotopyToString(), rawMutableComplexToString(), rawPathTrackerToString(), rawPointArrayToString(), rawSLEvaluatorToString(), rawSLProgramToString(), and rawStraightLineProgramToString().