Macaulay2 Engine: buffer::reset
reset()
void buffer::reset () inline
Definition at line 34 of file buffer.hpp.
 { _size = 0; }
References _size.
Referenced by LLLoperations::doLLL(), gbA::insert_gb(), gbA::reduce_ZZ(), gbA::replace_gb_element_ZZ(), gbA::show(), gbA::show_mem_usage(), FractionField::simplify(), LocalRing::simplify(), gbA::start_computation(), binomialGB_comp::stats(), gb2_comp::stats(), and HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track().