Macaulay2 Engine: buffer::size
size()
int buffer::size () inline
Definition at line 35 of file buffer.hpp.
{ return _size; }
References _size.
Referenced by MinimalPrimes::alg1_min_primes(), NCF4::compute(), NCGroebner::computeHomogeneous(), NCGroebner::computeInhomogeneous(), gbA::gbelem_text_out(), NCF4::process(), gbA::show(), gbA::show_mem_usage(), SLProgram::text_out(), and PointArray::text_out().