Macaulay2 Engine: sagbi::subduct1
subduct1() [1/2]
Matrix * sagbi::subduct1 (int numparts, const Ring * rawT, const Ring * rawS, const Matrix * m, const RingMap * inclusionAmbient, const RingMap * fullSubstitution, const RingMap * substitutionInclusion, GBComputation * gbI, GBComputation * gbReductionIdeal) static
Definition at line 137 of file sagbi.cpp.
 {
     MatrixConstructor result(m->rows(), m->cols());
     const PolyRing *T = rawT->cast_to_PolyRing();
     const PolyRing *S = rawS->cast_to_PolyRing();
     if ((T == nullptr) || (S == nullptr))
     {
         ERROR("expected polynomial ring");
         return nullptr;
     }
     int nslots = T->getMonoid()->n_slots(numparts);
     for (int i = 0; i < m->n_cols(); i++)
     {
         ring_elem a = m->elem(0, i);
         ring_elem b = subduct1(nslots-2, T, S, S->copy(a),
                         inclusionAmbient,fullSubstitution,substitutionInclusion,
                                  gbI,gbReductionIdeal);
         result.set_entry(0, i, b);
     }
     return result.to_matrix();
 }
References Ring::cast_to_PolyRing(), Matrix::cols(), PolyRing::copy(), Matrix::elem(), ERROR(), Matrix::n_cols(), Matrix::rows(), MatrixConstructor::set_entry(), subduct1(), T, and MatrixConstructor::to_matrix().