Macaulay2 Engine: sagbi::subduct
subduct() [1/2]
Matrix * sagbi::subduct (int numparts, const Matrix * m, const RingMap * phi, GBComputation * J) static
Definition at line 52 of file sagbi.cpp.
 {
   MatrixConstructor result(m->rows(), m->cols());
   const PolyRing *R = m->get_ring()->cast_to_PolyRing();
   if (R == 0)
     {
       ERROR("expected polynomial ring");
       return 0;
     }
   int nslots = R->getMonoid()->n_slots(numparts);
   for (int i = 0; i < m->n_cols(); i++)
     {
       ring_elem a = m->elem(0, i);
       ring_elem b = subduct(nslots, R, R->copy(a), phi, J);
       result.set_entry(0, i, b);
     }
   return result.to_matrix();
 }
References Ring::cast_to_PolyRing(), Matrix::cols(), PolyRing::copy(), Matrix::elem(), ERROR(), Matrix::get_ring(), PolynomialRing::getMonoid(), Matrix::n_cols(), Monoid::n_slots(), Matrix::rows(), MatrixConstructor::set_entry(), subduct(), and MatrixConstructor::to_matrix().