Macaulay2 Engine: sagbi::subduct
subduct() [2/2]
ring_elem sagbi::subduct (int numslots, const PolyRing * R, ring_elem f, const RingMap * phi, GBComputation * J) static
Definition at line 7 of file sagbi.cpp.
 {
   Nterm *f = a;
   Nterm head;
   Nterm *result = &head;
   MatrixConstructor mat(R->make_FreeModule(1), 1);
   while (f != nullptr)
     {
       Nterm *g = f;
       f = f->next;
       g->next = nullptr;
       mat.set_entry(0, 0, g);
       Matrix *m = mat.to_matrix();
       const Matrix *n = J->matrix_remainder(m);
       ring_elem g1 = n->elem(0, 0);
       delete m;
       delete n;
       // Is g1 a monomial in the new variables?
       if (R->in_subring(numslots, g1))
         {
           g->next = f;
           f = g;
           ring_elem phi_g1 = R->eval(phi, g1, 0);
           ring_elem fr = f;
           R->internal_subtract_to(fr, phi_g1);
           f = fr;
         }
       else
         {
           result->next = g;
           result = g;
         }
     }
   result->next = nullptr;
   return head.next;
 }
References Matrix::elem(), PolyRing::eval(), PolyRing::in_subring(), PolyRing::internal_subtract_to(), Ring::make_FreeModule(), GBComputation::matrix_remainder(), Nterm::next, MatrixConstructor::set_entry(), and MatrixConstructor::to_matrix().
Referenced by rawSubduction(), and subduct().