Macaulay2 Engine: sagbi::subduct1
subduct1() [2/2]
ring_elem sagbi::subduct1 (int numslots, const PolyRing * T, const PolyRing * S, ring_elem a, const RingMap * inclusionAmbient, const RingMap * fullSubstitution, const RingMap * substitutionInclusion, GBComputation * gbI, GBComputation * gbReductionIdeal) static
Definition at line 71 of file sagbi.cpp.
 {
     Nterm *f = a;
     ring_elem fr = f;
     MatrixConstructor matT(T->make_FreeModule(1), 1);
     MatrixConstructor matS(S->make_FreeModule(1), 1);
     bool breakFlag = false;
     while ((f != nullptr) && (breakFlag == false))
     {
         // tensorRingg = S#"inclusionAmbient" liftg
         // tesnorRingg = gInT
         ring_elem gInT = S->eval(inclusionAmbient,fr,0);
         // This might be the wrong way to deal with this issue.
         // I don't know what to do, however.
         if(gInT != nullptr)
           {
               // tensorRingLTg = leadTerm tensorRingg
               // tensorRingLTg = LTgInT
               Nterm *LTgInT = gInT;
               LTgInT->next = nullptr;
             // h = tensorRingLTg % (inAIdeal)
             // h = h1
             matT.set_entry(0,0,LTgInT);
             Matrix *m = matT.to_matrix();
             const Matrix *n = gbReductionIdeal->matrix_remainder(m);
             ring_elem h1 = n->elem(0,0);
             delete m;
             delete n;
             ring_elem projectionh = T->eval(substitutionInclusion,h1,0);
             if(projectionh != nullptr)
             {
                 // hSub = (S#"fullSubstitution" h) % I
                 ring_elem hInS = T->eval(fullSubstitution,h1,0);
                 matS.set_entry(0,0,hInS);
                 Matrix *k = matS.to_matrix();
                 const Matrix *l = gbI->matrix_remainder(k);
                 ring_elem h1InS = l->elem(0,0);
                 delete k;
                 delete l;
                 S->internal_subtract_to(fr,h1InS);
                 f = fr;
             }
             else
                 breakFlag = true;
           }
         else
             breakFlag = true;
     }
     return ring_elem(f);
 }
References Matrix::elem(), PolyRing::eval(), PolyRing::internal_subtract_to(), Ring::make_FreeModule(), GBComputation::matrix_remainder(), Nterm::next, MatrixConstructor::set_entry(), T, and MatrixConstructor::to_matrix().
Referenced by rawSubduction1(), and subduct1().