Macaulay2 Engine: Tower::translate
translate()
ring_elem Tower::translate (const PolynomialRing * R, ring_elem fR) const
Definition at line 444 of file tower.cpp.
 {
   // create a TowerPolynomial in the Tower T, return it.
   const Monoid *M = R->getMonoid();
   const Ring *K = R->getCoefficients();
   int nvars = R->n_vars();
   TowerPolynomial result = 0;
   exponents_t exp = new int[nvars];
   for (Nterm& t : fR)
     {
       M->to_expvector(t.monom, exp);
       std::pair<bool, long> res = K->coerceToLongInteger(t.coeff);
       assert(res.first);
       int c1 = static_cast<int>(res.second);
       D->add_term(result, c1, exp);
     }
   delete[] exp;
   return TOWER_RINGELEM(result);
 }
References DRing::add_term(), Ring::coerceToLongInteger(), D, mpfr::exp(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), PolynomialRing::n_vars(), nvars, Monoid::to_expvector(), and TOWER_RINGELEM.