Macaulay2 Engine: Tower::initialize
initialize()
bool Tower::initialize (long charac0, M2_ArrayString names0, const gc_vector< ring_elem > & extensions) protected
Definition at line 15 of file tower.cpp.
 {
   initialize_ring(charac0);
   declare_field();
   names = names0;
   nvars = names->len;
   level = nvars - 1;
   // Translate extensions to poly's
   if (extensions.size() == 0)
     {
       D = DRing::create(charac0, nvars, 0);
     }
   else
     {
       TowerPolynomial* exts = new TowerPolynomial[extensions.size()];
       for (int i = 0; i < extensions.size(); i++)
         exts[i] = reinterpret_cast<TowerPolynomial>(extensions[i].poly_val);
       D = DRing::create(charac0, nvars, exts);
       delete[] exts;
     }
   zeroV = from_long(0);
   oneV = from_long(1);
   minus_oneV = from_long(-1);
   return true;
 }
References DRing::create(), D, Ring::declare_field(), from_long(), Ring::initialize_ring(), level, Ring::minus_oneV, names, nvars, Ring::oneV, and Ring::zeroV.
Referenced by create().