Macaulay2 Engine: Tower::create
create() [3/3]
Tower * Tower::create (int charac, M2_ArrayString names) static
Definition at line 46 of file tower.cpp.
 {
   Tower *result = new Tower;
   VECTOR(ring_elem) extensions;
   if (!result->initialize(charac, names, extensions)) return nullptr;
   return result;
 }
References initialize(), names, Tower(), and VECTOR().
Referenced by rawTowerRing1(), rawTowerRing2(), rawTowerRing3(), and TEST().