Macaulay2 Engine: Tower::create
create() [1/3]
Tower * Tower::create (const Tower * R, gc_vector< ring_elem > & extensions) static
Definition at line 60 of file tower.cpp.
 {
   Tower *result = new Tower;
   if (!result->initialize(R->characteristic(), R->names, extensions)) return nullptr;
   return result;
 }
References Ring::characteristic(), initialize(), names, and Tower().