Macaulay2 Engine: Tower::add
add()
ring_elem Tower::add (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 183 of file tower.cpp.
 {
   TowerPolynomial f1 = TOWER_POLYNOMIAL_VAL(f);
   TowerPolynomial g1 = TOWER_POLYNOMIAL_VAL(g);
   TowerPolynomial h;
   D->set_zero(h);
   D->add(h, f1, g1);
   return TOWER_RINGELEM(h);
 }
References DRing::add(), D, DRing::set_zero(), TOWER_POLYNOMIAL_VAL, and TOWER_RINGELEM.
Referenced by TEST().