Macaulay2 Engine: Tower::random
random()
ring_elem Tower::random () const virtual
Reimplemented from Ring.
Definition at line 242 of file tower.cpp.
 {
   TowerPolynomial f;
   D->set_zero(f);
   D->set_random(f);
   return TOWER_RINGELEM(f);
 }
References D, DRing::set_random(), DRing::set_zero(), and TOWER_RINGELEM.
Referenced by getElement< Tower >(), and TEST().