Macaulay2 Engine: DMatLinAlg< M2::ARingZZpFFPACK >::matrixPLU
matrixPLU()
void DMatLinAlg< M2::ARingZZpFFPACK >::matrixPLU (std::vector< size_t > & P, Mat & L, Mat & U) inline
Definition at line 47 of file dmat-lu-zzp-ffpack.hpp.
   {
     DMatLUinPlace<RingType> C(mLU);
     const Mat& LU = C.LUinPlace();
     LUUtil<RingType>::setUpperLower(LU, L, U);
     P = C.permutation();
   }
References MatrixOps::LU(), DMatLUinPlace< RT >::LUinPlace(), DMatLUinPlace< RT >::permutation(), and LUUtil< RT >::setUpperLower().