Macaulay2 Engine: FreeModule_symm::value
value()
FreeModule* FreeModule_symm::value () inline
Definition at line 366 of file freemod.cpp.
   {
     if (symm1_result == nullptr)
       {
         symm1_result = F->get_ring()->make_FreeModule();
         if (n >= 0)
           {
             symm1_deg = D->make_one();
             symm1(0, n);
             D->remove(symm1_deg);
           }
       }
     return symm1_result;
   }
References D, F, FreeModule::get_ring(), Ring::make_FreeModule(), Monoid::make_one(), n, Monoid::remove(), symm1(), symm1_deg, and symm1_result.
Referenced by FreeModule::symm().