Macaulay2 Engine: FreeModule_symm::symm1
symm1()
void FreeModule_symm::symm1 (int lastn, int pow) const inline
Definition at line 341 of file freemod.cpp.
   {
     if (pow == 0)
       symm1_result->append(symm1_deg);
     else
       {
         for (int i = lastn; i < F->rank(); i++)
           {
             // increase symm1_deg, with e_i
             D->mult(symm1_deg, F->degree(i), symm1_deg);
             symm1(i, pow - 1);
             // decrease symm1_deg back
             D->divide(symm1_deg, F->degree(i), symm1_deg);
           }
       }
   }
References FreeModule::append(), D, FreeModule::degree(), Monoid::divide(), F, Monoid::mult(), mpfr::pow(), FreeModule::rank(), symm1_deg, and symm1_result.
Referenced by value().