Macaulay2 Engine: ReducedGB_Field::remainder
remainder() [2/2]
void ReducedGB_Field::remainder (POLY & f, bool use_denom, ring_elem & denom) virtual
Implements ReducedGB.
Reimplemented in ReducedGB_Field_Local.
Definition at line 100 of file reducedgb-field.cpp.
 {
   gbvector head;
   gbvector *frem = &head;
   frem->next = nullptr;
   POLY h = f;
   exponents_t EXP = ALLOCATE_EXPONENTS(R->exponent_byte_size());
   while (!R->gbvector_is_zero(h.f))
     {
       R->gbvector_get_lead_exponents(F, h.f, EXP);
       int x = h.f->comp;
       Bag *b;
       if (Rideal != nullptr && Rideal->search_expvector(EXP, b))
         {
           const gbvector *g = originalR->quotient_gbvector(b->basis_elem());
           R->gbvector_reduce_lead_term(
               F, Fsyz, head.next, h.f, h.fsyz, g, nullptr, use_denom, denom);
         }
       else
         {
           int w = T->find_divisor(EXP, x);
           if (w >= 0)
             {
               POLY g = polys[w];
               R->gbvector_reduce_lead_term(F,
                                            Fsyz,
                                            head.next,
                                            h.f,
                                            h.fsyz,
                                            g.f,
                                            g.fsyz,
                                            use_denom,
                                            denom);
             }
           else
             {
               frem->next = h.f;
               frem = frem->next;
               h.f = h.f->next;
               frem->next = nullptr;
             }
         }
     }
   h.f = head.next;
   //  R->gbvector_remove_content(h.f, h.fsyz, use_denom, denom);
   f.f = h.f;
   originalR->get_quotient_info()->gbvector_normal_form(
       Fsyz, h.fsyz, use_denom, denom);
   f.fsyz = h.fsyz;
 }
References ALLOCATE_EXPONENTS, int_bag::basis_elem(), gbvector::comp, GBRing::exponent_byte_size(), POLY::f, ReducedGB::F, MonomialTable::find_divisor(), POLY::fsyz, ReducedGB::Fsyz, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), QRingInfo::gbvector_normal_form(), GBRing::gbvector_reduce_lead_term(), PolynomialRing::get_quotient_info(), gbvector::next, ReducedGB::originalR, ReducedGB::polys, PolynomialRing::quotient_gbvector(), ReducedGB::R, Rideal, MonomialIdeal::search_expvector(), T, and x.
Referenced by minimalize().