Macaulay2 Engine: ReducedGB_Field::remainder
remainder() [1/2]
void ReducedGB_Field::remainder (gbvector *& f, bool use_denom, ring_elem & denom) virtual
Implements ReducedGB.
Reimplemented in ReducedGB_Field_Local.
Definition at line 151 of file reducedgb-field.cpp.
 {
   gbvector *zero = nullptr;
   gbvector head;
   gbvector *frem = &head;
   frem->next = nullptr;
   gbvector *h = f;
   exponents_t EXP = ALLOCATE_EXPONENTS(R->exponent_byte_size());
   while (!R->gbvector_is_zero(h))
     {
       R->gbvector_get_lead_exponents(F, h, EXP);
       int x = h->comp;
       Bag *b;
       if (Rideal != nullptr && Rideal->search_expvector(EXP, b))
         {
           const gbvector *g = originalR->quotient_gbvector(b->basis_elem());
           R->gbvector_reduce_lead_term(
               F, Fsyz, head.next, h, zero, g, zero, use_denom, denom);
         }
       else
         {
           int w = T->find_divisor(EXP, x);
           if (w < 0)
             {
               frem->next = h;
               frem = frem->next;
               h = h->next;
               frem->next = nullptr;
             }
           else
             {
               POLY g = polys[w];
               R->gbvector_reduce_lead_term(
                   F, Fsyz, head.next, h, zero, g.f, zero, use_denom, denom);
             }
         }
     }
   h = head.next;
   // R->gbvector_remove_content(h, 0, use_denom, denom);
   f = h;
 }
References ALLOCATE_EXPONENTS, int_bag::basis_elem(), gbvector::comp, GBRing::exponent_byte_size(), POLY::f, ReducedGB::F, MonomialTable::find_divisor(), ReducedGB::Fsyz, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), GBRing::gbvector_reduce_lead_term(), gbvector::next, ReducedGB::originalR, ReducedGB::polys, PolynomialRing::quotient_gbvector(), ReducedGB::R, Rideal, MonomialIdeal::search_expvector(), T, x, and zero.