Macaulay2 Engine: ReducedGB_Field::ReducedGB_Field
ReducedGB_Field()
ReducedGB_Field::ReducedGB_Field (GBRing * R0, const PolynomialRing * originalR0, const FreeModule * F0, const FreeModule * Fsyz0) protected
Definition at line 34 of file reducedgb-field.cpp.
   : ReducedGB(R0, originalR0, F0, Fsyz0), T(nullptr), Rideal(nullptr)
 {
   T = MonomialTable::make(R0->n_vars());
   if (originalR->is_quotient_ring())
     Rideal = originalR->get_quotient_monomials();
 }
References PolynomialRing::get_quotient_monomials(), PolynomialRing::is_quotient_ring(), MonomialTable::make(), GBRing::n_vars(), ReducedGB::originalR, Rideal, and T.