Macaulay2 Engine: TEST
TEST() [14/24]
TEST (ARingZZpFFPACK , create)
Definition at line 164 of file ARingZZpTest.cpp.
 {
   M2::ARingZZpFFPACK R(101);
   EXPECT_EQ(ringName(R), "ZZpFPACK(101,1)");
   testSomeMore(R);
   std::cout << "max modulus for ffpack zzp: "
             << M2::ARingZZpFFPACK::getMaxModulus() << std::endl;
   M2::ARingZZpFFPACK::ElementType a;
   R.init(a);
   R.set_from_long(a, 99);
   R.set_from_long(a, 101);
   R.set_from_long(a, 103);
   R.clear(a);
 }
References M2::ARingZZpFFPACK::clear(), M2::ARingZZpFFPACK::getMaxModulus(), M2::ARingZZpFFPACK::init(), ringName(), M2::ARingZZpFFPACK::set_from_long(), and testSomeMore().