Macaulay2 Engine: TEST
TEST() [5/24]
TEST (ARingZZp , create)
Definition at line 79 of file ARingZZpTest.cpp.
 {
   M2::ARingZZp R(101);
   M2::ARingZZp::ElementType a;
   buffer o;
   ARingElementGenerator<M2::ARingZZp> gen(R);
   R.init(a);
   gen.nextElement(a);
   EXPECT_EQ(ringName(R), "AZZ/101");
   EXPECT_EQ(R.cardinality(), 101);
   EXPECT_EQ(R.characteristic(), 101);
   // Now check what the generator is, as an integer
   R.init(a);
   R.set_var(a, 0);
   R.elem_text_out(o, a, true, true, false);
   std::cout << "generator is " << o.str() << std::endl;
   R.clear(a);
 }
References M2::ARingZZp::cardinality(), M2::ARingZZp::characteristic(), M2::ARingZZp::clear(), M2::ARingZZp::elem_text_out(), M2::ARingZZp::init(), ARingElementGenerator< RingType >::nextElement(), ringName(), M2::ARingZZp::set_var(), and buffer::str().