Macaulay2 Engine: TEST
TEST() [21/24]
TEST (ARingZZpFlint , arithmetic67108859)
Definition at line 347 of file ARingZZpTest.cpp.
 {
   M2::ARingZZpFlint R(67108859);
   testCoerceToLongInteger(R);
   testCoercions(R);
   testNegate(R, ntrials);
   testAdd(R, ntrials);
   testSubtract(R, ntrials);
   testMultiply(R, ntrials);
   testDivide(R, ntrials);
   testReciprocal(R, ntrials);
   testPower(R, ntrials);
   testAxioms(R, ntrials);
 }
References ntrials, testAdd(), testAxioms(), testCoerceToLongInteger(), testCoercions(), testDivide(), testMultiply(), testNegate(), testPower(), testReciprocal(), and testSubtract().