Macaulay2 Engine: getElement< M2::ARingZZpFlint >
getElement< M2::ARingZZpFlint >()
template<> void getElement< M2::ARingZZpFlint > (const M2::ARingZZpFlint & R, int index, M2::ARingZZpFlint::ElementType & result)
Definition at line 281 of file ARingZZpTest.cpp.
{
  if (index < 50)
    R.set_from_long(result, index - 25);
  else
    {
      gmp_ZZ a = getRandomInteger();
      R.set_from_mpz(result, a);
    }
}
References getRandomInteger(), M2::ARingZZpFlint::set_from_long(), and M2::ARingZZpFlint::set_from_mpz().