Macaulay2 Engine: TEST
TEST() [24/24]
TEST (RingZZp , create)
Definition at line 69 of file ARingZZpTest.cpp.
 {
   const Z_mod* R = Z_mod::create(101);
   EXPECT_FALSE(R == 0);
   buffer o;
   o << "Ring being tested: ";
   R->text_out(o);
   fprintf(stdout, "%s\n", o.str());
 }
References Z_mod::create(), buffer::str(), and Z_mod::text_out().