Macaulay2 Engine: getElement< M2::ARingZZpFFPACK >
getElement< M2::ARingZZpFFPACK >()
template<> void getElement< M2::ARingZZpFFPACK > (const M2::ARingZZpFFPACK & R, int index, M2::ARingZZpFFPACK::ElementType & result)
Definition at line 151 of file ARingZZpTest.cpp.
 {
   if (index < 50)
     R.set_from_long(result, index - 25);
   else
     {
       gmp_ZZ a = getRandomInteger();
       R.set_from_mpz(result, a);
     }
 }
References getRandomInteger(), M2::ARingZZpFFPACK::set_from_long(), and M2::ARingZZpFFPACK::set_from_mpz().