Macaulay2 Engine: getElement< M2::ARingZZp >
getElement< M2::ARingZZp >()
template<> void getElement< M2::ARingZZp > (const M2::ARingZZp & R, int index, M2::ARingZZp::ElementType & result)
Definition at line 32 of file ARingZZpTest.cpp.
{
  if (index < 50)
    R.set_from_long(result, index - 25);
  else
    {
      gmp_ZZ a = getRandomInteger();
      R.set_from_mpz(result, a);
    }
}
References getRandomInteger(), M2::ARingZZp::set_from_long(), and M2::ARingZZp::set_from_mpz().