Macaulay2 Engine: TEST
TEST() [6/24]
TEST (ARingZZp , fromStream)
Definition at line 129 of file ARingZZpTest.cpp.
 {
   std::istringstream i("+1234 +345 -235*a");
   M2::ARingZZp R(32003);
   M2::ARingZZp::ElementType a;
   R.init(a);
   while (true)
     {
       while (isspace(i.peek())) i.get();
       if (!isdigit(i.peek()) && i.peek() != '+' && i.peek() != '-') break;
       fromStream(i, R, a);
       buffer o;
       R.elem_text_out(o, a);
       std::cout << o.str() << " peek: " << i.peek() << std::endl;
     }
   R.clear(a);
 }
References M2::ARingZZp::clear(), M2::ARingZZp::elem_text_out(), fromStream(), M2::ARingZZp::init(), and buffer::str().