Macaulay2 Engine: TEST
TEST() [23/24]
TEST (ARingZZpFlint , create)
Definition at line 294 of file ARingZZpTest.cpp.
 {
   M2::ARingZZpFlint R(101);
   EXPECT_EQ(ringName(R), "AZZFlint/101");
   testSomeMore(R);
   M2::ARingZZpFlint::ElementType a;
   R.init(a);
   R.set_from_long(a, 99);
   R.set_from_long(a, 101);
   R.set_from_long(a, 103);
   R.clear(a);
 }
References M2::ARingZZpFlint::clear(), M2::ARingZZpFlint::init(), ringName(), M2::ARingZZpFlint::set_from_long(), and testSomeMore().