Macaulay2 Engine: testRingNegateRRi
testRingNegateRRi()
void testRingNegateRRi (const M2::ARingRRi & R, const M2::ARingRRR & S, int ntrials)
Definition at line 60 of file ARingRRiTest.cpp.
 {
     ARingElementGenerator<M2::ARingRRi> gen(R);
     M2::ARingRRi::ElementType a, b, c;
     R.init(a);
     R.init(b);
     R.init(c);
     M2::ARingRRR::ElementType d;
     S.init(d);
     for (int i = 0; i < ntrials; i++)
     {
         // test: (-a) + (a) == 0
         gen.nextElement(a);
         R.negate(b,a);
         R.add(c,a,b);
         R.midpoint(d,c);
         EXPECT_TRUE(S.is_zero(d));
     }
     S.clear(d);
     R.clear(c);
     R.clear(b);
     R.clear(a);
 }
References M2::ARingRRi::add(), M2::ARingRRi::clear(), M2::ARingRRR::clear(), M2::ARingRRi::init(), M2::ARingRRR::init(), M2::ARingRRR::is_zero(), M2::ARingRRi::midpoint(), M2::ARingRRi::negate(), ARingElementGenerator< RingType >::nextElement(), and ntrials.
Referenced by TEST().