Macaulay2 Engine: TEST
TEST() [7/7]
TEST (ARingRRi , subtract)
Definition at line 119 of file ARingRRiTest.cpp.
 {
   M2::ARingRRi R(100);
   M2::ARingRRR S(100);
   ARingElementGenerator<M2::ARingRRi> gen(R);
   M2::ARingRRi::ElementType a, b, c, e;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(e);
   M2::ARingRRR::ElementType f;
   S.init(f);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (a-b) + (b) == a
       gen.nextElement(a);
       gen.nextElement(b);
       R.subtract(c, a, b);
       R.add(e, c, b);  // should be a
       EXPECT_TRUE(R.is_subset(a,e));
       R.mult(e, a, b);
       R.subtract_multiple(e, a, b);
       R.midpoint(f,e);
       EXPECT_TRUE(S.is_zero(f));
     }
   S.clear(f);
   R.clear(e);
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References M2::ARingRRi::add(), M2::ARingRRi::clear(), M2::ARingRRR::clear(), M2::ARingRRi::init(), M2::ARingRRR::init(), M2::ARingRRi::is_subset(), M2::ARingRRR::is_zero(), M2::ARingRRi::midpoint(), M2::ARingRRi::mult(), ARingElementGenerator< RingType >::nextElement(), ntrials, M2::ARingRRi::subtract(), and M2::ARingRRi::subtract_multiple().