Macaulay2 Engine: TEST
TEST() [4/7]
TEST (ARingRRi , multDivide)
Definition at line 152 of file ARingRRiTest.cpp.
 {
   M2::ARingRRi R(100);
   ARingElementGenerator<M2::ARingRRi> gen(R);
   M2::ARingRRi::ElementType a, b, c, d;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(d);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (a*b) // b == a
       gen.nextElement(a);
       gen.nextElement(b);
       R.mult(c, a, b);
       if (R.is_member(0L,b))
           EXPECT_TRUE(R.is_member(0L,c));
       else
         {
           R.divide(d, c, b);
           EXPECT_TRUE(R.is_subset(a,d));
         }
     }
   R.clear(d);
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References M2::ARingRRi::clear(), M2::ARingRRi::divide(), M2::ARingRRi::init(), M2::ARingRRi::is_member(), M2::ARingRRi::is_subset(), M2::ARingRRi::mult(), ARingElementGenerator< RingType >::nextElement(), and ntrials.