Macaulay2 Engine: TEST
TEST() [1/7]
TEST (ARingRRi , add)
Definition at line 92 of file ARingRRiTest.cpp.
 {
   M2::ARingRRi R(100);
   ARingElementGenerator<M2::ARingRRi> gen(R);
   M2::ARingRRi::ElementType a, b, c, d, e;
   R.init(a);
   R.init(b);
   R.init(c);
   R.init(d);
   R.init(e);
   for (int i = 0; i < ntrials; i++)
     {
       // test: (a+b) + (-b) == a
       gen.nextElement(a);
       gen.nextElement(b);
       R.add(c, a, b);
       R.negate(d, b);
       R.add(e, c, d);  // should be a
       EXPECT_TRUE(R.is_subset(a,e));
     }
   R.clear(e);
   R.clear(d);
   R.clear(c);
   R.clear(b);
   R.clear(a);
 }
References M2::ARingRRi::add(), M2::ARingRRi::clear(), M2::ARingRRi::init(), M2::ARingRRi::is_subset(), M2::ARingRRi::negate(), ARingElementGenerator< RingType >::nextElement(), and ntrials.