Macaulay2 Engine: ERROR
ERROR()
void ERROR (const char * s, ...)
Definition at line 26 of file error.c.
{
  va_list ap;
  if (iserror) fprintf(stderr, "--error message bumped: %s\n", errmsg);
  iserror = 1;
  va_start(ap, s);
  vsprintf(errmsg, s, ap);
  va_end(ap);
}
References errmsg, and iserror.
Referenced by MutableMat< Mat >::add(), binomialGB_comp::add_generators(), MarkedGB::add_marked_elems(), SLProgram::addDivide(), binomial_ring::binomial_ring(), BIBasis::BooleanInvolutiveBasis< MonomType >::BooleanInvolutiveBasis(), check_coeff_ring(), check_var(), checkGaloisFieldInput(), BIBasis::Launcher::CheckMatrix(), GBComputation::choose_gb(), ResolutionComputation::choose_res(), hilb_comp::coeff_of(), coeffMode(), Matrix::coeffs(), MatElementaryOps< DMat< RT > >::column_permute(), KBasis::compute(), Matrix::concat(), SLP< Field >::concatenate(), cond_number_via_svd(), GaussElimComputation::contains(), GB_comp::contains(), binomialGB_comp::contains(), HermiteComputation::contains(), ReducedGB::contains(), SLP< Field >::convert_to_absolute_position(), convertToFactory(), convertToM2(), ChineseRemainder::CRA(), GBDeclared::create(), GBDeclared::create(), GBinhom_comp::create(), binomialGB_comp::create(), gbA::create(), Monoid::create(), SchurRing::create(), PolynomialRing::create_quotient(), SLEvaluatorConcrete< RT >::createHomotopy(), SchurRing::createInfinite(), MutableMat< Mat >::createSLEvaluator(), Ring::declare_field(), PolyRing::degree_of_var(), RingElement::degree_weights(), MutableMat< Mat >::delete_columns(), MutableMat< Mat >::delete_rows(), RingElement::denominator(), Matrix::diff(), FreeModule::direct_sum(), Matrix::direct_sum(), Matrix::divide_by_var(), LLLoperations::doLLL(), Lapack::eigenvalues(), Lapack::eigenvalues_hermitian(), Lapack::eigenvalues_symmetric(), Lapack::eigenvectors(), Lapack::eigenvectors_hermitian(), Lapack::eigenvectors_symmetric(), Matrix::elim_keep(), Matrix::elim_vars(), error_column_bound(), error_row_bound(), M2::ARingRRi::eval(), M2::ARingCC::eval(), M2::ARingCCC::eval(), M2::ARingRR::eval(), M2::ARingRRR::eval(), SLEvaluatorConcrete< RT >::evaluate(), SLP< Field >::evaluate(), SLEvaluatorConcrete< RT >::evaluate(), SLP< Field >::evaluate(), PathTracker::evaluate_slpHxtH(), Matrix::exterior(), Matrix::flip(), fp_LLL(), RingElement::fraction(), PolyRing::gcd(), res2_comp::get_betti(), res_comp::get_betti(), gbres_comp::get_betti(), RingElement::get_coeff(), MarkedGB::get_initial(), F4ResComputation::get_matrix(), ResolutionComputation::get_matrix(), F4ResComputation::get_matrix(), get_norm_start(), GBComputation::get_parallel_lead_terms(), RingElement::get_terms(), SchreyerFrame::getBetti(), Ring::getGenerator(), MonomialOrderings::GRevLex(), PolyRing::homogenize(), Ring::homogenize(), RingElement::homogenize(), RingElement::homogenize(), IM2_Computation_set_stop(), IM2_FreeModule_dual(), IM2_FreeModule_exterior(), IM2_FreeModule_make(), IM2_FreeModule_make_degs(), IM2_FreeModule_make_schreyer(), IM2_FreeModule_submodule(), IM2_FreeModule_symm(), IM2_FreeModule_tensor(), IM2_GB_contains(), IM2_GB_force(), IM2_GB_make(), IM2_GB_matrix_lift(), IM2_GB_set_hilbert_function(), IM2_HermiteNormalForm(), IM2_Matrix_concat(), IM2_Matrix_direct_sum(), IM2_Matrix_exterior(), IM2_Matrix_flip(), IM2_Matrix_get_entry(), IM2_Matrix_Hilbert(), IM2_Matrix_is_equal(), IM2_Matrix_koszul(), IM2_Matrix_lift(), IM2_Matrix_minors(), IM2_Matrix_promote(), IM2_Matrix_remake1(), IM2_Matrix_reshape(), IM2_Matrix_sort_columns(), IM2_Matrix_submatrix(), IM2_Matrix_submatrix1(), IM2_Matrix_symm(), IM2_Matrix_tensor(), IM2_Matrix_transpose(), IM2_MonomialIdeal_borel(), IM2_MonomialIdeal_codim(), IM2_MonomialIdeal_Hilbert(), IM2_MonomialIdeal_intersect(), IM2_MonomialIdeal_is_equal(), IM2_MonomialIdeal_make(), IM2_MonomialIdeal_to_matrix(), IM2_MutableMatrix_column_2by2(), IM2_MutableMatrix_column_operation(), IM2_MutableMatrix_column_permute(), IM2_MutableMatrix_column_scale(), IM2_MutableMatrix_column_swap(), IM2_MutableMatrix_get_entry(), IM2_MutableMatrix_identity(), IM2_MutableMatrix_row_2by2(), IM2_MutableMatrix_row_operation(), IM2_MutableMatrix_row_permute(), IM2_MutableMatrix_row_scale(), IM2_MutableMatrix_row_swap(), IM2_MutableMatrix_set_entry(), IM2_MutableMatrix_sort_columns(), IM2_res_make(), IM2_Resolution_status(), IM2_Resolution_status_level(), IM2_Ring_frac(), IM2_Ring_localization(), IM2_Ring_polyring(), IM2_Ring_quotient(), IM2_Ring_quotient1(), IM2_Ring_schur(), IM2_Ring_skew_polyring(), IM2_Ring_solvable_algebra(), IM2_Ring_weyl_algebra(), IM2_Ring_ZZp(), IM2_RingElement_denominator(), IM2_RingElement_divmod(), IM2_RingElement_fraction(), IM2_RingElement_from_BigComplex(), IM2_RingElement_from_BigReal(), IM2_RingElement_from_Interval(), IM2_RingElement_from_rational(), IM2_RingElement_get_coeff(), IM2_RingElement_homogenize(), IM2_RingElement_homogenize_to_degree(), IM2_RingElement_lead_coeff(), IM2_RingElement_lead_monomial(), IM2_RingElement_lift(), IM2_RingElement_list_form(), IM2_RingElement_make_var(), IM2_RingElement_multidegree(), IM2_RingElement_numerator(), IM2_RingElement_promote(), IM2_RingElement_term(), IM2_RingElement_to_BigComplex(), IM2_RingElement_to_BigReal(), IM2_RingElement_to_Integer(), IM2_RingElement_to_Interval(), IM2_RingElement_to_rational(), IM2_RingMap_eval_matrix(), IM2_RingMap_eval_ringelem(), IM2_SmithNormalForm(), gbA::initialize(), GB_comp::initialize0(), WeylAlgebra::initialize_weyl(), LLLoperations::initializeLLL(), MutableMat< Mat >::insert_columns(), MutableMat< Mat >::insert_rows(), RingElement::invert(), PolyRing::invert(), Tower::invert(), RingElement::is_equal(), SchurRing2::is_valid_partition(), SLP< Field >::jacobian(), KBasis::k_basis(), Matrix::koszul(), Matrix::koszul_monomials(), RingElement::lead_coeff(), RingElement::lead_monom(), Lapack::least_squares(), Lapack::least_squares_deficient(), M2FreeAlgebra::list_form(), SchurRing2::list_form(), Lapack::LU(), Matrix::make(), Matrix::make(), PathTracker::make(), SLP< Field >::make(), PathTracker::make(), Matrix::make(), SLP< Field >::make(), EngineMonomial::make(), PolyRing::make_logical_term(), Matrix::make_monideal(), FreeModule::make_schreyer(), FreeModule::make_schreyer(), Matrix::make_sparse_vecs(), makemonideal(), GaussElimComputation::matrix_lift(), GB_comp::matrix_lift(), binomialGB_comp::matrix_lift(), GBWalker::matrix_lift(), HermiteComputation::matrix_lift(), ReducedGB::matrix_lift(), F4Computation::matrix_lift(), GaussElimComputation::matrix_remainder(), GB_comp::matrix_remainder(), HermiteComputation::matrix_remainder(), ReducedGB::matrix_remainder(), Matrix::minors(), Matrix::minors(), Matrix::module_tensor(), Matrix::monomials(), Matrix::mult(), MutableMat< Mat >::mult(), MutableMat< Mat >::mult(), ncBasis(), NCCoefficientMatrix(), NCCoefficientMatrix(), NCMonomialMatrix(), Matrix::norm(), norm_of_inverse_via_svd(), ntl_LLL(), RingElement::numerator(), RingElement::operator*(), Matrix::operator+(), RingElement::operator+(), Matrix::operator-(), RingElement::operator-(), RingElement::operator/(), outofmem(), outofmem2(), Matrix::pfaffians(), polyListToMatrix(), Ring::power(), PolyRing::power(), Ring::power(), FreeAlgebra::power(), Lapack::QR(), PolyRingQuotient::quotient(), Ring::random(), rawAlexanderDual(), rawAmbientRing(), rawARingGaloisField(), rawARingGaloisField1(), rawARingGaloisFieldFlintBig(), rawARingGaloisFieldFlintZech(), rawARingTower1(), rawARingTower2(), rawARingTower3(), rawARingZZp(), rawAssociateDivisor(), rawCharSeries(), rawColonMonomialIdeal1(), rawColonMonomialIdeal2(), rawConvolve(), rawDenominatorRing(), rawDiff(), rawDiscreteLog(), rawDisplayMatrixStream(), rawDividedPowerRing(), rawEigenvalues(), rawEigenvectors(), rawEvaluateSLP(), rawExtendedGCDRingElement(), rawExtensionDegree(), rawFactorBase(), rawFourierMotzkin(), rawFreeModuleSelectByDegrees(), rawGaloisField(), rawGbBoolean(), rawGBChangeOfBasis(), rawGBGetLeadTerms(), rawGBGetMatrix(), rawGBGetParallelLeadTerms(), rawGBMatrixRemainder(), rawGBMinimalGenerators(), rawGBSyzygies(), rawGCDRingElement(), rawGetPart(), rawGetParts(), rawGRevLexMonomialOrdering(), rawGroebnerWalk(), rawHilbertBasis(), rawHomotopy(), rawHomotopyTrack(), rawIdealOfPoints(), rawIdealReorder(), rawIsLocalUnit(), rawKoszulMonomials(), rawLeastSquares(), rawLiftLocalMatrix(), rawLinAlgAddMult(), rawLinAlgCharPoly(), rawLinAlgDeterminant(), rawLinAlgInverse(), rawLinAlgMinPoly(), rawLinAlgMult(), rawLinAlgNullSpace(), rawLinAlgRank(), rawLinAlgRankProfile(), rawLinAlgRREF(), rawLinAlgSolve(), rawLinAlgSolveInvertible(), rawLinAlgSubMult(), rawLowerP(), rawLU(), rawLUincremental(), rawMarkedGB(), rawMatrixClean(), rawMatrixCRA(), rawMatrixRatConversion(), rawMatrixReadMsolveFile(), rawMatrixReadMsolveString(), rawMaximalIndependentSets(), rawMGB(), rawMinimalBetti(), rawMinors(), rawModuleTensor(), rawMonoid(), rawMonomialMinimalPrimes(), rawMutableMatrixClean(), rawMutableMatrixPromote(), rawMutableMatrixTranspose(), rawNCBasis(), rawNCGroebnerBasisTwoSided(), rawNCReductionTwoSided(), rawPathTracker(), rawPathTrackerPrecookedSLPs(), rawPathTrackerProjective(), rawPointArray(), rawPowerMod(), rawPseudoRemainder(), rawQR(), rawRadicalMonomialIdeal(), rawResolutionBetti(), rawResolutionGetFree(), rawResolutionGetMatrix(), rawResolutionGetMatrix2(), rawResolutionGetMutableMatrix2B(), rawResolutionGetMutableMatrixB(), rawRingElementAntipode(), rawRingElementClean(), rawRingElementCompare(), rawRingElementCRA(), rawRingElementRatConversion(), rawRingM2FreeAlgebra(), rawRingM2FreeAlgebraQuotient(), rawRingMapEvalMutableMatrix(), rawRoots(), rawSaturateMonomialIdeal1(), rawSaturateMonomialIdeal2(), rawSchurDimension(), rawSchurFromPartition(), rawSchurRing1(), rawSchurRing2(), rawSchurSnRing(), rawSchurSnTensorMult(), rawSLEvaluatorEvaluate(), rawSLEvaluatorSpecialize(), rawSLP(), rawStartComputation(), rawSubduction(), rawSubduction1(), rawSVD(), rawTowerRing2(), rawTowerRing3(), rawTowerTranslatePoly(), rawTriangularSolve(), rawWedgeProduct(), rawWeightRange(), rawZZisPrime(), binomialGB_comp::reduce(), gbres_comp::reduce(), PathTracker::refine(), PolyRingQuotient::remainder(), PolyRingQuotient::remainderAndQuotient(), Matrix::remake(), Matrix::remake(), Matrix::reshape(), MatElementaryOps< DMat< RT > >::row_permute(), Monoid::set_degrees(), GBComputation::set_hilbert_function(), gbA::set_hilbert_function(), Ring::set_non_unit(), Monoid::set_overflow_flags(), GBinhom_comp::set_up0(), SLProgram::setOutputPositions(), gbres_comp::setup(), gb2_comp::setup(), SLEvaluatorConcrete< RT >::SLEvaluatorConcrete(), Lapack::solve(), solve_via_lapack(), solve_via_lapack_without_transposition(), res_comp::stop_conditions_ok(), gbres_comp::stop_conditions_ok(), FreeModule::sub_space(), SchreyerOrder::sub_space(), FreeModule::sub_space(), SchreyerOrder::sub_space(), sagbi::subduct(), sagbi::subduct1(), MutableMat< Mat >::submatrix(), MutableMat< Mat >::submatrix(), MutableMat< Mat >::subtract(), Matrix::support(), Lapack::SVD(), Lapack::SVD_divide_conquer(), SymmMatrix::symmetricPower(), FreeModule::tensor(), Matrix::tensor(), ResF4toM2Interface::to_M2_freemodule(), Matrix::top_coefficients(), towerExtendedGCD(), towerGCD(), PathTracker::track(), HomotopyConcrete< RT, Algorithm >::track(), HomotopyConcrete< RT, FixedPrecisionHomotopyAlgorithm >::track(), hilb_comp::value(), Ring::vec_degree_of_var(), and Matrix::zero().