Macaulay2 Engine: error
error()
int error ()
Definition at line 48 of file error.c.
{ return iserror; }
References iserror.
Referenced by gb2_comp::calc_gb(), convertToM2(), gbA::do_computation(), RingMap::eval(), RingMap::eval(), M2::ARingCC::eval(), RingElement::homogenize(), RingElement::homogenize(), IM2_RingElement_divmod(), IM2_RingElement_fraction(), IM2_RingElement_make_var(), EngineMonomial::make(), EngineMonomial::make(), EngineMonomial::make(), EngineMonomial::operator*(), RingElement::operator*(), RingElement::operator+(), RingElement::operator-(), RingElement::operator/(), EngineMonomial::power(), RingElement::power(), RingElement::power(), rawCharSeries(), rawExtendedGCDRingElement(), rawFactorBase(), rawGCDRingElement(), rawPseudoRemainder(), rawStartComputation(), rawWeightRange(), HilbertController::setDegree(), GB_comp::start_computation(), GBinhom_comp::start_computation(), F4GB::start_computation(), TEST(), TEST(), and TEST().