Macaulay2 Engine: gbA::new_gen
new_gen()
gbA::spair * gbA::new_gen (int i, gbvector * f, ring_elem denom) private
Definition at line 224 of file gb-default.cpp.
 {
   gbvector *fsyz;
   if (i < n_rows_per_syz)
     fsyz = R->gbvector_term(_Fsyz, denom, i + 1);
   else
     fsyz = R->gbvector_zero();
   if (R->gbvector_is_zero(f))
     {
       originalR->get_quotient_info()->gbvector_normal_form(_Fsyz, fsyz);
       if (!R->gbvector_is_zero(fsyz))
         {
           // vec fsyzvec = _GR->gbvector_to_vec(_Fsyz,fsyz);
           collect_syzygy(fsyz);
         }
       return NULL;
     }
   POLY g;
   g.f = f;
   g.fsyz = fsyz;
   return spair_make_gen(g);
 }
References _Fsyz, collect_syzygy(), POLY::f, POLY::fsyz, GBRing::gbvector_is_zero(), QRingInfo::gbvector_normal_form(), GBRing::gbvector_term(), GBRing::gbvector_zero(), PolynomialRing::get_quotient_info(), n_rows_per_syz, originalR, R, and spair_make_gen().
Referenced by initialize().