Macaulay2 Engine: gbA::pair_not_needed
pair_not_needed()
bool gbA::pair_not_needed (spair * p, gbelem * m) private
Definition at line 592 of file gb-default.cpp.
 {
   /* Check the criterion: in(m) divides lcm(p).
    * If so: check if lcm(p1,m) == lcm(p)  (if so, return false)
    *        check if lcm(p2,m) == lcm(p)  (if so, return false)
    * If still here, return true.
    */
   int i, first, second;
   bool firstok;
   exponents_t mexp, lcm, p1exp, p2exp;
   if (p->type != SPAIR::SPAIR_SPAIR && p->type != SPAIR::SPAIR_RING)
     return false;
   mexp = m->lead;
   lcm = p->lcm;
   if (gbelem_COMPONENT(m) != spair_COMPONENT(p)) return false;
   first = p->x.pair.i;
   second = p->x.pair.j;
   p1exp = gb[first]->lead;
   p2exp =
       gb[second]->lead; /* If a ring pair, this should index into gb array */
   ncalls++;
   for (i = 0; i < _nvars; i++, nloops++)
     if (mexp[i] > lcm[i]) return false;
   firstok = false;
   for (i = 0; i < _nvars; i++)
     {
       if (mexp[i] == lcm[i]) continue;
       if (p1exp[i] == lcm[i]) continue;
       firstok = true;
       break;
     }
   if (!firstok) return false;
   for (i = 0; i < _nvars; i++)
     {
       if (mexp[i] == lcm[i]) continue;
       if (p2exp[i] == lcm[i]) continue;
       return true;
     }
   return false;
 }
References _nvars, gb, gbelem_COMPONENT(), gbA::gbelem::lead, ncalls, nloops, p, spair_COMPONENT(), and SPAIR_RING.
Referenced by remove_unneeded_pairs().