Macaulay2 Engine: gbA::get_resolved_gb_index
get_resolved_gb_index()
int gbA::get_resolved_gb_index (int i) const private
Definition at line 26 of file gb-default.cpp.
 {
   if (not over_ZZ()) return i;
   int prev = i;
   int next = forwardingZZ[i];
   while (next != -1)
     {
       prev = next;
       next = forwardingZZ[prev];
     }
   if (M2_gbTrace >= 16)
     {
       buffer o;
       o << "resolve(" << i << ") = " << prev << newline;
       std::cout << o.str() << std::endl;
     }
   return prev;
 }
References forwardingZZ, M2_gbTrace, newline, over_ZZ(), and buffer::str().
Referenced by compute_s_pair().