Macaulay2 Engine: gbA::start_computation
start_computation()
void gbA::start_computation () virtual
Implements GBComputation.
Definition at line 2578 of file gb-default.cpp.
 {
   ncalls = 0;
   nloops = 0;
   nsaved_unneeded = 0;
   do_computation();
   if (M2_gbTrace >= 1)
     {
       show_mem_usage();
       if (M2_gbTrace >= 3)
         {
           buffer o;
           emit_line(o.str());
           o.reset();
           o << "#reduction steps = " << stats_nreductions;
           emit_line(o.str());
           o.reset();
           o << "#spairs done = " << stats_npairs;
           emit_line(o.str());
           o.reset();
           o << "ncalls = " << ncalls;
           emit_line(o.str());
           o.reset();
           o << "nloop = " << nloops;
           emit_line(o.str());
           o.reset();
           o << "nsaved = " << nsaved_unneeded;
           emit_line(o.str());
         }
       if (M2_gbTrace >= 15) show();
     }
 }
References do_computation(), emit_line(), M2_gbTrace, ncalls, nloops, nsaved_unneeded, buffer::reset(), show(), show_mem_usage(), stats_npairs, stats_nreductions, and buffer::str().