Macaulay2 Engine: gbA::compute_s_pair
compute_s_pair()
void gbA::compute_s_pair (spair * p) private
Definition at line 1297 of file gb-default.cpp.
 {
   POLY f, g;
   int i, j;
   if (M2_gbTrace >= 5 && M2_gbTrace != 15)
     {
       buffer o;
       spair_text_out(o, p);
       emit_line(o.str());
     }
   if (p->type > SPAIR::SPAIR_SKEW) return;
   R->gbvector_remove(p->lead_of_spoly);
   p->lead_of_spoly = nullptr;
   i = get_resolved_gb_index(p->x.pair.i);
   f = gb[i]->g;
   if (p->type == SPAIR::SPAIR_SKEW)
     {
       const int *mon = R->skew_monomial_var(p->x.pair.j);
       R->gbvector_mult_by_term(
           _F, _Fsyz, R->one(), mon, f.f, f.fsyz, p->f(), p->fsyz());
     }
   else if (p->type == SPAIR::SPAIR_GCD_ZZ)
     {
       j = get_resolved_gb_index(p->x.pair.j);
       g = gb[j]->g;
       R->gbvector_combine_lead_terms_ZZ(
           _F, _Fsyz, f.f, f.fsyz, g.f, g.fsyz, p->f(), p->fsyz());
     }
   else
     {
       j = get_resolved_gb_index(p->x.pair.j);
       g = gb[j]->g;
       R->gbvector_cancel_lead_terms(
           _F, _Fsyz, f.f, f.fsyz, g.f, g.fsyz, p->f(), p->fsyz());
     }
   p->type = SPAIR::SPAIR_ELEM;
   if (M2_gbTrace >= 5 && M2_gbTrace != 15)
     {
       buffer o;
       o << "    ";
       R->gbvector_text_out(o, _F, p->f());
       emit_line(o.str());
     }
 }
References _F, _Fsyz, emit_line(), POLY::f, POLY::fsyz, gb, GBRing::gbvector_cancel_lead_terms(), GBRing::gbvector_combine_lead_terms_ZZ(), GBRing::gbvector_mult_by_term(), GBRing::gbvector_remove(), GBRing::gbvector_text_out(), get_resolved_gb_index(), M2_gbTrace, GBRing::one(), p, R, GBRing::skew_monomial_var(), spair_text_out(), and buffer::str().
Referenced by reduce_kk(), and reduce_ZZ().