Macaulay2 Engine: gbA::minimalize_pairs
minimalize_pairs()
void gbA::minimalize_pairs (spairs & new_set) private
Definition at line 920 of file gb-default.cpp.
 {
   if (over_ZZ())
     minimalize_pairs_ZZ(new_set);
   else
     minimalize_pairs_non_ZZ(new_set);
 }
References minimalize_pairs_non_ZZ(), minimalize_pairs_ZZ(), and over_ZZ().
Referenced by update_pairs().