Macaulay2 Engine: gbA::replace_gb_element_ZZ
replace_gb_element_ZZ()
void gbA::replace_gb_element_ZZ (MonomialTableZZ::mon_term * t) private
Definition at line 2203 of file gb-default.cpp.
 {
   /* Reduce this element as far as possible.  This either removes content,
      makes it monic, or at least negates it so the lead coeff is positive. */
   ring_elem not_used;
   stats_ngb++;
   n_gb++;
   int gbval = t->_val;
   gbelem *g = gb[gbval];
   gb[gbval] = nullptr;
   g->deg = this_degree;  // replace the degree
   g->minlevel |= ELEM_MINGB;
   minimal_gb_valid = false;
   int me = INTSIZE(gb);
   if (is_local_gb)
     R->gbvector_remove_content(g->g.f, g->g.fsyz, false, not_used);
   else
     tail_remainder_ZZ(g->g, this_degree);
   //  tail_remainder_ZZ(g->g,this_degree);
   gb.push_back(g);
   forwardingZZ.push_back(-1);
   forwardingZZ[gbval] = INTSIZE(gb) - 1;
   lookupZZ->change_coefficient(t, g->g.f->coeff.get_mpz(), me);
   if (M2_gbTrace == 15)
     {
       buffer o;
       o << "    retiring g" << gbval << " with new ";
       //      o << "    new ";
       gbelem_text_out(o, INTSIZE(gb) - 1);
       emit_line(o.str());
     }
   else if (M2_gbTrace >= 5)
     {
       const int N = 100;
       char s[N];
       buffer o;
       snprintf(s, N,
               "replacing-inserting element %d (minimal %d replacing %d): ",
               me,
               g->minlevel,
               gbval);
       o << s;
       R->gbvector_text_out(o, _F, g->g.f);
       emit_line(o.str());
       o.reset();
       o << "                          syzygy : ";
       R->gbvector_text_out(o, _Fsyz, g->g.fsyz);
       emit_line(o.str());
     }
   if (!is_local_gb) auto_reduce_by(me);
 }
References _F, _Fsyz, MonomialTableZZ::mon_term::_val, auto_reduce_by(), MonomialTableZZ::change_coefficient(), gbvector::coeff, gbA::gbelem::deg, ELEM_MINGB, emit_line(), POLY::f, forwardingZZ, POLY::fsyz, gbA::gbelem::g, gb, gbelem_text_out(), GBRing::gbvector_remove_content(), GBRing::gbvector_text_out(), ring_elem::get_mpz(), INTSIZE, is_local_gb, lookupZZ, M2_gbTrace, minimal_gb_valid, gbA::gbelem::minlevel, n_gb, R, buffer::reset(), stats_ngb, buffer::str(), tail_remainder_ZZ(), and this_degree.
Referenced by reduce_ZZ().