Macaulay2 Engine: gbA::gbelem_text_out
gbelem_text_out()
void gbA::gbelem_text_out (buffer & o, int i, int nterms = 3) const private
Definition at line 397 of file gb-default.cpp.
 {
   if (!gb[i])
     {
       o << "removed";
     }
   else
     {
       gbelem_type minlevel = gb[i]->minlevel;
       bool ismingen = (minlevel & ELEM_MINGEN);
       bool ismingb = (minlevel & ELEM_MINGB);
       if (ismingb)
         o << "GB elem: ";
       else
         o << "reducer: ";
       o << "g" << i << " = ";
       R->gbvector_text_out(o, _F, gb[i]->g.f, nterms);
       o << " ["
         << "gap " << gb[i]->gap << " size " << gb[i]->size << " deg "
         << gb[i]->deg;
       if (ismingen) o << " mingen";
       o << "]";
     }
 }
References _F, ELEM_MINGB, ELEM_MINGEN, gb, GBRing::gbvector_text_out(), and R.
Referenced by insert_gb(), replace_gb_element_ZZ(), and show().