Macaulay2 Engine: gbA::spair_set_defer
spair_set_defer()
void gbA::spair_set_defer (spair *& p) private
Definition at line 1085 of file gb-default.cpp.
 {
   if (M2_gbTrace == 15)
     {
       emit_line("    deferred by reduction count");
     }
   else if (M2_gbTrace >= 4)
     emit_wrapped("D");
   //  spair_delete(p); // ONLY FOR TESTING!! THIS IS INCORRECT!!
   //  return;
   S->n_in_degree++;
   if (p->type == SPAIR::SPAIR_GEN)
     {
       S->gen_last_deferred->next = p;
       S->gen_last_deferred = p;
       n_gens_left++;
     }
   else
     {
       S->spair_last_deferred->next = p;
       S->spair_last_deferred = p;
     }
 }
References emit_line(), emit_wrapped(), gbA::SPairSet::gen_last_deferred, M2_gbTrace, n_gens_left, gbA::SPairSet::n_in_degree, gbA::spair::next, p, S, SPAIR_GEN, and gbA::SPairSet::spair_last_deferred.
Referenced by reduce_kk(), and reduce_ZZ().