Macaulay2 Engine: gbA::reduce_kk
reduce_kk()
bool gbA::reduce_kk (spair * p) private
Definition at line 1331 of file gb-default.cpp.
 {
   /* Returns false iff we defer computing this spair. */
   /* If false is returned, this routine has grabbed the spair 'p'. */
   int tmf, wt;
   int count = -1;
   exponents_t EXP = ALLOCATE_EXPONENTS(exp_size);
   if (M2_gbTrace == 15)
     {
       buffer o;
       o << "considering ";
       spair_text_out(o, p);
       o << " : ";
       emit_line(o.str());
     }
   compute_s_pair(p); /* Changes the type, possibly */
   while (!R->gbvector_is_zero(p->f()))
     {
       if (count++ > max_reduction_count)
         {
           spair_set_defer(p);
           return false;
         }
       if (M2_gbTrace >= 5)
         {
           if ((wt = weightInfo_->gbvector_weight(p->f(), tmf)) > this_degree)
             {
               buffer o;
               o << "ERROR: degree of polynomial is too high: deg " << wt
                 << " termwt " << tmf << " expectedeg " << this_degree
                 << newline;
               emit(o.str());
             }
         }
       int gap, w;
       R->gbvector_get_lead_exponents(_F, p->f(), EXP);
       int x = p->f()->comp;
       w = find_good_divisor(EXP, x, this_degree, gap);
       // replaced gap, g.
       if (w < 0) break;
       if (gap > 0)
         {
           POLY h;
           h.f = R->gbvector_copy(p->x.f.f);
           h.fsyz = R->gbvector_copy(p->x.f.fsyz);
           insert_gb(h, (p->type == SPAIR::SPAIR_GEN ? ELEM_MINGEN : 0));
         }
       POLY g = gb[w]->g;
       R->gbvector_reduce_lead_term(_F,
                                    _Fsyz,
                                    nullptr,
                                    p->f(),
                                    p->fsyz(), /* modifies these */
                                    g.f,
                                    g.fsyz);
       stats_nreductions++;
       if (M2_gbTrace == 15)
         {
           buffer o;
           o << "    reducing by g" << w;
           o << ", yielding ";
           R->gbvector_text_out(o, _F, p->f(), 3);
           emit_line(o.str());
         }
       if (R->gbvector_is_zero(p->f())) break;
       if (gap > 0)
         {
           p->deg += gap;
           if (M2_gbTrace == 15)
             {
               buffer o;
               o << "    deferring to degree " << p->deg;
               emit_line(o.str());
             }
           spair_set_insert(p);
           return false;
         }
     }
   if (M2_gbTrace >= 4 && M2_gbTrace != 15)
     {
       buffer o;
       o << "." << count;
       emit_wrapped(o.str());
     }
   return true;
 }
References _F, _Fsyz, ALLOCATE_EXPONENTS, compute_s_pair(), ELEM_MINGEN, emit(), emit_line(), emit_wrapped(), exp_size, POLY::f, find_good_divisor(), POLY::fsyz, gb, GBRing::gbvector_copy(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), GBRing::gbvector_reduce_lead_term(), GBRing::gbvector_text_out(), GBWeight::gbvector_weight(), insert_gb(), M2_gbTrace, max_reduction_count, newline, p, R, SPAIR_GEN, spair_set_defer(), spair_set_insert(), spair_text_out(), stats_nreductions, buffer::str(), this_degree, weightInfo_, and x.
Referenced by reduceit().