Macaulay2 Engine: gbA::collect_syzygy
collect_syzygy()
void gbA::collect_syzygy (gbvector * fsyz) private
Definition at line 2096 of file gb-default.cpp.
 {
   _syz.push_back(f);
   n_syz++;
   if (M2_gbTrace >= 10)
     {
       buffer o;
       o << " new syzygy : ";
       R->gbvector_text_out(o, _Fsyz, f, 3);
       emit_line(o.str());
     }
 }
References _Fsyz, _syz, emit_line(), GBRing::gbvector_text_out(), M2_gbTrace, n_syz, R, and buffer::str().
Referenced by new_gen(), and process_spair().