Macaulay2 Engine: gbA::gbelem_make
gbelem_make()
gbA::gbelem * gbA::gbelem_make (gbvector * f, gbvector * fsyz, gbelem_type minlevel, int deg) private
Definition at line 360 of file gb-default.cpp.
 {
   int f_leadweight;
   gbelem *g = reinterpret_cast<gbelem *>(gbelem_stash->new_elem());
   g->g.f = f;
   g->g.fsyz = fsyz;
   g->lead = exponents_make();
   R->gbvector_get_lead_exponents(_F, f, g->lead);
   g->deg = deg;
   weightInfo_->gbvector_weight(f, f_leadweight);  // return value not used
   g->gap = deg - weightInfo_->gbvector_term_weight(f);
   if (f->next == nullptr)  // a monomial.  This is a hack: we should lower the gap
                      // value when we can.
     // the problem though is that this sometimes slows down the computation
     // dramatically.
     g->gap = 0;
   g->size = R->gbvector_n_terms(f);
   g->minlevel = minlevel;
   return g;
 }
References _F, gbA::gbelem::deg, exponents_make(), POLY::f, POLY::fsyz, gbA::gbelem::g, gbA::gbelem::gap, gbelem_stash, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_n_terms(), GBWeight::gbvector_term_weight(), GBWeight::gbvector_weight(), gbA::gbelem::lead, gbA::gbelem::minlevel, stash::new_elem(), gbvector::next, R, gbA::gbelem::size, and weightInfo_.
Referenced by insert_gb().