Macaulay2 Engine: gbA::update_pairs
update_pairs()
void gbA::update_pairs (int id) private
Definition at line 940 of file gb-default.cpp.
 {
   assert(gb[id] != nullptr);
   gbelem *r = gb[id];
   int x = gbelem_COMPONENT(r);
   /* Step 1.  Remove un-needed old pairs */
   remove_unneeded_pairs(id);
   /* Step 2.  Collect new pairs */
   spairs new_set;
   /* Step 2a: */
   if (R->is_skew_commutative())
     {
       for (int i = 0; i < R->n_skew_commutative_vars(); i++)
         if (r->lead[R->skew_variable(i)] > 0)
           {
             spair *s = spair_make_skew(id, i);
             new_set.push_back(s);
           }
     }
   /* Step 2b: pairs from ring elements, or 'in stone' elements */
   for (int i = 0; i < first_gb_element; i++)
     {
       spair *s = spair_make_ring(id, i);
       new_set.push_back(s);
     }
   /* Step 2c. pairs from the vectors themselves */
   /* Loop through the minimal GB elements and form the s-pair */
   for (int i = first_gb_element; i < id; i++)
     {
       gbelem *g = gb[i];
       if (g && (g->minlevel & ELEM_MINGB) && gbelem_COMPONENT(g) == x)
         {
           spair *s = spair_make(id, i);
           new_set.push_back(s);
         }
     }
   /* Step 3. Minimalize this set */
   minimalize_pairs(
       new_set); /* Modifies new_set, inserts minimal pairs into S */
 }
References ELEM_MINGB, first_gb_element, gb, gbelem_COMPONENT(), GBRing::is_skew_commutative(), gbA::gbelem::lead, minimalize_pairs(), gbA::gbelem::minlevel, GBRing::n_skew_commutative_vars(), R, remove_unneeded_pairs(), GBRing::skew_variable(), spair_make(), spair_make_ring(), spair_make_skew(), and x.
Referenced by do_computation().