Macaulay2 Engine: gbA::minimalize_pairs_non_ZZ
minimalize_pairs_non_ZZ()
void gbA::minimalize_pairs_non_ZZ (spairs & new_set) private
Definition at line 760 of file gb-default.cpp.
 {
 #if 0
 //   spairs keep_for_now;
 //   emit("--minimalize pairs--\n");
 //   for (int i=0; i<new_set.size(); i++) {
 //     keep_for_now.push_back(new_set[i]);
 //     debug_spair(new_set[i]);
 //   }
 #endif
   std::stable_sort(new_set.begin(), new_set.end(), spair_sorter(_nvars));
   MonomialTable *montab = MonomialTable::make(_nvars);
   //  array_sort(new_set, (compareFcn)spair_compare, 0);
   spairs::iterator first = new_set.begin();
   spairs::iterator next = first;
   spairs::iterator end = new_set.end();
   for (; first != end; first = next)
     {
       next = first + 1;
       spair *me = *first;
       while (next != end)
         {
           spair *p = *next;
           if (!exponents_equal(_nvars, me->lcm, p->lcm)) break;
           next++;
         }
       /* At this point: [first,next) is the range of equal monomials */
       int inideal = montab->find_divisors(1, me->lcm, 1);
       if (inideal == 0)
         {
           spairs::iterator t = choose_pair(first, next);
           spair *p = *t;
           if (_is_ideal && is_gcd_one_pair(p))
             {
               stats_ngcd1++;
               if ((M2_gbTrace & PRINT_SPAIR_TRACKING) != 0)
                 {
                   buffer o;
                   o << "removing spair because of gcd: ";
                   spair_text_out(o, p);
                   emit_line(o.str());
                 }
               spair_delete(p);
             }
           else
             {
               if (M2_gbTrace >= 4)
                 {
                   buffer o;
                   o << "    new ";
                   spair_text_out(o, p);
                   emit_line(o.str());
                 }
               spair_set_insert(p);
               montab->insert(p->lcm, 1, 0);
             }
           *t = 0;
         }
     }
   delete montab;
   for (spairs::iterator i = new_set.begin(); i != new_set.end(); i++)
     spair_delete(*i);
 }
References _is_ideal, _nvars, choose_pair(), emit_line(), end(), exponents_equal(), MonomialTable::find_divisors(), MonomialTable::insert(), is_gcd_one_pair(), gbA::spair::lcm, M2_gbTrace, MonomialTable::make(), p, PRINT_SPAIR_TRACKING, spair_delete(), spair_set_insert(), spair_text_out(), stats_ngcd1, and buffer::str().
Referenced by minimalize_pairs().