Macaulay2 Engine: gbA::reduce_ZZ
reduce_ZZ()
bool gbA::reduce_ZZ (spair * p) private
Definition at line 1437 of file gb-default.cpp.
 {
   /* Returns false iff we defer computing this spair. */
   /* If false is returned, this routine has grabbed the spair 'p'. */
   int tmf, wt;
   int count = -1;
   exponents_t EXP = ALLOCATE_EXPONENTS(exp_size);
   if (M2_gbTrace == 15)
     {
       buffer o;
       o << "considering ";
       spair_text_out(o, p);
       o << " : ";
       emit_line(o.str());
     }
   compute_s_pair(p); /* Changes the type, possibly */
   while (!R->gbvector_is_zero(p->f()))
     {
       if (count++ > max_reduction_count)
         {
           spair_set_defer(p);
           return false;
         }
       if (M2_gbTrace >= 5)
         {
           if ((wt = weightInfo_->gbvector_weight(p->f(), tmf)) > this_degree)
             {
               buffer o;
               o << "ERROR: degree of polynomial is too high: deg " << wt
                 << " termwt " << tmf << " expectedeg " << this_degree
                 << newline;
               emit(o.str());
             }
         }
       int gap, w;
       R->gbvector_get_lead_exponents(_F, p->f(), EXP);
       int x = p->f()->comp;
       mpz_srcptr c = p->f()->coeff.get_mpz();
       w = find_good_term_divisor_ZZ(c, EXP, x, this_degree, gap);
       // If w < 0, then no divisor was found.  Is there a GB element of
       // the same degree as this one, and with the same exponent vector?
       // If so, use gcdextended to find (g,u,v),
       if (w < 0 || gap > 0)
         {
           MonomialTableZZ::mon_term *t =
               lookupZZ->find_exact_monomial(EXP, x, first_in_degree);
           if (t != nullptr)
             {
               // f <-- u*p+v*f (same with syz versions), need to change lookupZZ
               // too?
               // p <-- c*p-d*f
               gbelem *g = gb[t->_val];
               if (M2_gbTrace >= 10)
                 {
                   buffer o;
                   o << "  swapping with GB element " << t->_val;
                   emit_line(o.str());
                 }
               // If the element p is a generator, then we must assume that now
               // the
               // swapped g is a (possible) minimal generator.
               g->minlevel |= ELEM_MINGB;
               if (p->type == SPAIR::SPAIR_GEN || (g->minlevel & ELEM_MINGEN))
                 {
                   g->minlevel |= ELEM_MINGEN;
                   p->type = SPAIR::SPAIR_GEN;
                 }
               R->gbvector_replace_2by2_ZZ(
                   _F, _Fsyz, p->f(), p->fsyz(), g->g.f, g->g.fsyz);
               // Before continuing, do remainder of g->g
               replace_gb_element_ZZ(t);
               if (M2_gbTrace >= 10)
                 {
                   buffer o;
                   o << "  swap yielded";
                   emit_line(o.str());
                   o.reset();
                   o << "      ";
                   R->gbvector_text_out(o, _F, p->f(), 3);
                   emit_line(o.str());
                   o.reset();
                   o << "      ";
                   R->gbvector_text_out(o, _F, g->g.f, 3);
                   emit_line(o.str());
                 }
               continue;
             }
         }
       if (w < 0) break;
       if (gap > 0)
         {
           POLY h;
           h.f = R->gbvector_copy(p->x.f.f);
           h.fsyz = R->gbvector_copy(p->x.f.fsyz);
           insert_gb(h, (p->type == SPAIR::SPAIR_GEN ? ELEM_MINGEN : 0));
         }
       POLY g = gb[w]->g;
       R->gbvector_reduce_lead_term_ZZ(
           _F, _Fsyz, p->f(), p->fsyz(), g.f, g.fsyz);
       stats_nreductions++;
       if (M2_gbTrace == 15)
         {
           buffer o;
           o << "    reducing by g" << w;
           o << ", yielding ";
           R->gbvector_text_out(o, _F, p->f(), 3);
           emit_line(o.str());
         }
       if (R->gbvector_is_zero(p->f())) break;
       if (gap > 0)
         {
           p->deg += gap;
           if (M2_gbTrace == 15)
             {
               buffer o;
               o << "    deferring to degree " << p->deg;
               emit_line(o.str());
             }
           spair_set_insert(p);
           return false;
         }
     }
   if (M2_gbTrace >= 4 && M2_gbTrace != 15)
     {
       buffer o;
       o << "." << count;
       emit_wrapped(o.str());
     }
   return true;
 }
References _F, _Fsyz, MonomialTableZZ::mon_term::_val, ALLOCATE_EXPONENTS, compute_s_pair(), ELEM_MINGB, ELEM_MINGEN, emit(), emit_line(), emit_wrapped(), exp_size, POLY::f, MonomialTableZZ::find_exact_monomial(), find_good_term_divisor_ZZ(), first_in_degree, POLY::fsyz, gbA::gbelem::g, gb, GBRing::gbvector_copy(), GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), GBRing::gbvector_reduce_lead_term_ZZ(), GBRing::gbvector_replace_2by2_ZZ(), GBRing::gbvector_text_out(), GBWeight::gbvector_weight(), insert_gb(), lookupZZ, M2_gbTrace, max_reduction_count, gbA::gbelem::minlevel, newline, p, R, replace_gb_element_ZZ(), buffer::reset(), SPAIR_GEN, spair_set_defer(), spair_set_insert(), spair_text_out(), stats_nreductions, buffer::str(), this_degree, weightInfo_, and x.
Referenced by reduceit().