Macaulay2 Engine: gbA::tail_remainder_ZZ
tail_remainder_ZZ()
void gbA::tail_remainder_ZZ (POLY & f, int degf) private
Definition at line 1890 of file gb-default.cpp.
 {
   gbvector head;
   gbvector *frem = &head;
   int count = 0;
   POLY h = f;
   exponents_t EXP = ALLOCATE_EXPONENTS(exp_size);
   frem->next = h.f;
   frem = frem->next;
   h.f = h.f->next;
   frem->next = 0;
   while (!R->gbvector_is_zero(h.f))
     {
       int gap;
       R->gbvector_get_lead_exponents(_F, h.f, EXP);
       int x = h.f->comp;
       int w = find_good_monomial_divisor_ZZ(
           h.f->coeff.get_mpz(), EXP, x, degf, gap);
       // replaced gap, g.
       if (w < 0 || gap > 0)
         {
           frem->next = h.f;
           frem = frem->next;
           h.f = h.f->next;
           frem->next = 0;
         }
       else
         {
           POLY g = gb[w]->g;
           if (!R->gbvector_reduce_lead_term_ZZ(
                   _F, _Fsyz, h.f, h.fsyz, g.f, g.fsyz))
             {
               // This term is still there, so we must move it to result.
               frem->next = h.f;
               frem = frem->next;
               h.f = h.f->next;
               frem->next = 0;
             }
           count++;
           //      stats_ntail++;
           if (M2_gbTrace == 15)
             {
               buffer o;
               o << "    tail red by g" << w;
               o << ", yielding ";
               R->gbvector_text_out(o, _F, h.f, 3);
               emit_line(o.str());
             }
         }
     }
   h.f = head.next;
   // Negate these if needed
   if (h.f != 0 && mpz_sgn(h.f->coeff.get_mpz()) < 0)
     {
       R->gbvector_mult_by_coeff_to(h.f, globalZZ->minus_one());
       R->gbvector_mult_by_coeff_to(h.fsyz, globalZZ->minus_one());
     }
   f.f = h.f;
   f.fsyz = h.fsyz;
   if ((M2_gbTrace & PRINT_SPAIR_TRACKING) != 0)
     {
       buffer o;
       o << "number of reduction steps was " << count;
       emit_line(o.str());
     }
   else if (M2_gbTrace >= 4 && M2_gbTrace != 15)
     {
       buffer o;
       o << "," << count;
       emit_wrapped(o.str());
     }
 }
References _F, _Fsyz, ALLOCATE_EXPONENTS, gbvector::coeff, gbvector::comp, emit_line(), emit_wrapped(), exp_size, POLY::f, find_good_monomial_divisor_ZZ(), POLY::fsyz, gb, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), GBRing::gbvector_mult_by_coeff_to(), GBRing::gbvector_reduce_lead_term_ZZ(), GBRing::gbvector_text_out(), ring_elem::get_mpz(), globalZZ, M2_gbTrace, Ring::minus_one(), gbvector::next, PRINT_SPAIR_TRACKING, R, buffer::str(), and x.
Referenced by replace_gb_element_ZZ().