Macaulay2 Engine: gbA::remove_gb
remove_gb()
void gbA::remove_gb () virtual
Implements GBComputation.
Definition at line 257 of file gb-default.cpp.
 {
   // removes all allocated objects
   for (int i = first_gb_element; i < gb.size(); i++)
     if (gb[i])
       {
         R->gbvector_remove(gb[i]->g.f);
         R->gbvector_remove(gb[i]->g.fsyz);
       }
   for (int i = 0; i < gb.size(); i++)
     if (gb[i])
       {
         lcm_stash->delete_elem(gb[i]->lead);
         gbelem_stash->delete_elem(gb[i]);
         gb[i] = nullptr;
       }
   delete minimal_gb;  // will free its own gbvector's.
   for (int i = 0; i < _syz.size(); i++)
     {
       R->gbvector_remove(_syz[i]);
       _syz[i] = nullptr;
     }
   delete lookup;
   delete lookupZZ;
   delete spair_stash;
   delete gbelem_stash;
   delete lcm_stash;
   // Also remove the SPAirSet...
 }
References _syz, stash::delete_elem(), first_gb_element, gb, gbelem_stash, GBRing::gbvector_remove(), lcm_stash, lookup, lookupZZ, minimal_gb, R, and spair_stash.
Referenced by ~gbA().