Macaulay2 Engine: gbA::get_gb
get_gb()
const Matrix * gbA::get_gb () virtual
Implements GBComputation.
Definition at line 2691 of file gb-default.cpp.
{
  minimalize_gb();
  //  fprintf(stderr, "-- done with GB -- \n");
  return minimal_gb->get_gb();
}
References ReducedGB::get_gb(), minimal_gb, and minimalize_gb().
Referenced by get_mingens().