Macaulay2 Engine: gbA::remove_spair_list
remove_spair_list()
void gbA::remove_spair_list (spair *& set) private
Definition at line 989 of file gb-default.cpp.
 {
   while (!set)
     {
       spair *tmp = set;
       set = set->next;
       spair_delete(tmp);
     }
   set = nullptr;
 }
References set(), and spair_delete().
Referenced by remove_SPairSet().