Macaulay2 Engine: gbA::get_mingens
get_mingens()
const Matrix * gbA::get_mingens () virtual
Implements GBComputation.
Definition at line 2686 of file gb-default.cpp.
 {
   if (over_ZZ()) return get_gb();
   MatrixConstructor mat(_F, 0);
   for (VECTOR(gbelem *)::iterator i = gb.begin(); i != gb.end(); i++)
     if ((*i) and ((*i)->minlevel & ELEM_MINGEN))
       mat.append(originalR->translate_gbvector_to_vec(_F, (*i)->g.f));
   return mat.to_matrix();
 }
References _F, MatrixConstructor::append(), ELEM_MINGEN, gb, get_gb(), originalR, over_ZZ(), MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_to_vec(), and VECTOR().