Macaulay2 Engine: gbA::initialize
initialize()
void gbA::initialize (const Matrix * m, int csyz, int nsyz, M2_arrayint gb_weights, int strat, int max_reduction_count0) private
Definition at line 97 of file gb-default.cpp.
 {
   // max_reduction_count: default was 10
   // 1 is best possible for 3-anderbuch!
   // 5 is: (114.64 sec, 494 MB)
   // 10 is best so far (125.33 sec, 527 MB virtual).
   // 50 is faster/smaller than 100, and 1000 was awful, on 3-andersbuch
   ringtable = nullptr;
   ringtableZZ = nullptr;
   first_gb_element = 0;
   max_reduction_count = max_reduction_count0;
   const PolynomialRing *origR = m->get_ring()->cast_to_PolynomialRing();
   if (origR == NULL)
     {
       ERROR("ring is not a polynomial ring");
       // MES: throw an error here.
       assert(0);
     }
   originalR = origR;
   R = origR->get_gb_ring();
   weightInfo_ = new GBWeight(m->rows(), gb_weights0);
   gb_weights = weightInfo_->get_weights();
   _nvars = R->get_flattened_monoid()->n_vars();
   _coeff_type = origR->coefficient_type();
   n_fraction_vars = origR->n_fraction_vars();
   is_local_gb = (origR->getMonoid()->numNonTermOrderVariables() > 0);
   spair_stash = new stash("gbA spairs", sizeof(spair));
   gbelem_stash = new stash("gbA elems", sizeof(gbelem));
   exp_size = EXPONENT_BYTE_SIZE(R->n_vars() + 2);
   lcm_stash = new stash("gbA lead monoms", exp_size);
   if (nsyz < 0 || nsyz > m->n_cols()) nsyz = m->n_cols();
   n_rows_per_syz = nsyz;
   _F = m->rows();
   _Fsyz = m->cols()->sub_space(n_rows_per_syz);
   S = new SPairSet;
   first_in_degree = 0;
   n_syz = 0;
   n_pairs_computed = 0;
   n_gens_left = 0;
   n_subring = 0;
   _strategy = strat;
   _collect_syz = csyz;
   _is_ideal = (_F->rank() == 1 && csyz == 0);
   if (R->is_weyl_algebra()) _is_ideal = false;
   use_hilb = false;
   hilb_new_elems = false;
   hilb_n_in_degree = 0;
   n_saved_hilb = 0;
   hf_orig = nullptr;
   hf_diff = nullptr;
   this_degree = _F->lowest_primary_degree() - 1;
   npairs = 0;
   complete_thru_this_degree = this_degree;
   set_status(COMP_NOT_STARTED);
   stats_nreductions = 0;
   stats_ntail = 0;
   stats_npairs = 0;
   stats_ngb = 0;
   stats_ngcd1 = 0;
   stats_nretired = 0;
   divisor_previous = -1;
   divisor_previous_comp = -1;
   // ZZZZ split
   lookup = 0;
   lookupZZ = 0;
   if (over_ZZ())
     lookupZZ = MonomialTableZZ::make(R->n_vars());
   else
     {
       lookup = MonomialTable::make(R->n_vars());
     }
   minimal_gb = ReducedGB::create(originalR, _F, _Fsyz);
   minimal_gb_valid = true;
   if (originalR->is_quotient_ring())
     {
       ringtable = originalR->get_quotient_MonomialTable();
       ringtableZZ = originalR->get_quotient_MonomialTableZZ();
       first_gb_element = originalR->n_quotients();
       for (int i = 0; i < first_gb_element; i++)
         {
           gbvector *f = const_cast<gbvector *>(originalR->quotient_gbvector(i));
           gbelem *g = gbelem_ring_make(f);
           gb.push_back(g);
           forwardingZZ.push_back(-1);
         }
     }
   for (int i = 0; i < m->n_cols(); i++)
     {
       ring_elem denom;
       gbvector *f = originalR->translate_gbvector_from_vec(_F, (*m)[i], denom);
       spair *p = new_gen(i, f, denom);
       if (p != NULL)
         {
           spair_set_insert(p);
         }
     }
   state = STATE_NEWDEGREE;  // will be changed if hilb fcn is used
   np_i = first_gb_element;
   ar_i = first_gb_element;
   ar_j = ar_i + 1;
   n_gb = first_gb_element;
 }
References _coeff_type, _collect_syz, _F, _Fsyz, _is_ideal, _nvars, _strategy, ar_i, ar_j, Ring::cast_to_PolynomialRing(), PolynomialRing::coefficient_type(), Matrix::cols(), COMP_NOT_STARTED, complete_thru_this_degree, ReducedGB::create(), divisor_previous, divisor_previous_comp, ERROR(), exp_size, EXPONENT_BYTE_SIZE, first_gb_element, first_in_degree, forwardingZZ, gb, gb_weights, gbelem_ring_make(), gbelem_stash, GBRing::get_flattened_monoid(), PolynomialRing::get_gb_ring(), PolynomialRing::get_quotient_MonomialTable(), PolynomialRing::get_quotient_MonomialTableZZ(), Matrix::get_ring(), GBWeight::get_weights(), PolynomialRing::getMonoid(), hf_diff, hf_orig, hilb_n_in_degree, hilb_new_elems, is_local_gb, PolynomialRing::is_quotient_ring(), GBRing::is_weyl_algebra(), lcm_stash, lookup, lookupZZ, FreeModule::lowest_primary_degree(), MonomialTable::make(), MonomialTableZZ::make(), max_reduction_count, minimal_gb, minimal_gb_valid, Matrix::n_cols(), n_fraction_vars, PolynomialRing::n_fraction_vars(), n_gb, n_gens_left, n_pairs_computed, PolynomialRing::n_quotients(), n_rows_per_syz, n_saved_hilb, n_subring, n_syz, GBRing::n_vars(), Monoid::n_vars(), new_gen(), np_i, npairs, Monoid::numNonTermOrderVariables(), originalR, over_ZZ(), p, PolynomialRing::quotient_gbvector(), R, FreeModule::rank(), ringtable, ringtableZZ, Matrix::rows(), S, Computation::set_status(), spair_set_insert(), spair_stash, state, STATE_NEWDEGREE, stats_ngb, stats_ngcd1, stats_npairs, stats_nreductions, stats_nretired, stats_ntail, FreeModule::sub_space(), this_degree, PolynomialRing::translate_gbvector_from_vec(), use_hilb, and weightInfo_.
Referenced by create().