Macaulay2 Engine: gbA::make_lead_term_matrix
make_lead_term_matrix()
Matrix * gbA::make_lead_term_matrix () private
Definition at line 2357 of file gb-default.cpp.
 {
   MatrixConstructor result(_F, 0);
   for (int i = first_gb_element; i < gb.size(); i++)
     {
       gbelem *g = gb[i];
       if (g->minlevel & ELEM_MINGB)
         {
           gbvector *f = g->g.f;
           assert(f != 0);
           // Only grab the lead term, which should be non-null
           gbvector *fnext = f->next;
           f->next = nullptr;
           vec v = originalR->translate_gbvector_to_vec(_F, f);
           f->next = fnext;
           result.append(v);
         }
     }
   return result.to_matrix();
 }
References _F, MatrixConstructor::append(), ELEM_MINGB, POLY::f, first_gb_element, gbA::gbelem::g, gb, gbA::gbelem::minlevel, gbvector::next, originalR, MatrixConstructor::to_matrix(), and PolynomialRing::translate_gbvector_to_vec().
Referenced by do_computation().