Macaulay2 Engine: gbA::remainder_non_ZZ
remainder_non_ZZ()
void gbA::remainder_non_ZZ (POLY & f, int degf, bool use_denom, ring_elem & denom) private
Definition at line 1978 of file gb-default.cpp.
 {
   exponents_t EXP = ALLOCATE_EXPONENTS(exp_size);
   gbvector head;
   gbvector *frem = &head;
   frem->next = nullptr;
   int count = 0;
   POLY h = f;
   while (!R->gbvector_is_zero(h.f))
     {
       int gap;
       R->gbvector_get_lead_exponents(_F, h.f, EXP);
       int x = h.f->comp;
       int w = find_good_divisor(EXP, x, degf, gap);
       // replaced gap, g.
       if (w < 0 || gap > 0)
         {
           frem->next = h.f;
           frem = frem->next;
           h.f = h.f->next;
           frem->next = nullptr;
         }
       else
         {
           POLY g = gb[w]->g;
           R->gbvector_reduce_lead_term(
               _F, _Fsyz, head.next, h.f, h.fsyz, g.f, g.fsyz, use_denom, denom);
           count++;
           //      stats_ntail++;
           if (M2_gbTrace >= 10)
             {
               buffer o;
               o << "  tail reducing by ";
               R->gbvector_text_out(o, _F, g.f, 2);
               o << "\n    giving ";
               R->gbvector_text_out(o, _F, h.f, 3);
               emit_line(o.str());
             }
         }
     }
   h.f = head.next;
   R->gbvector_remove_content(h.f, h.fsyz, use_denom, denom);
   f.f = h.f;
   f.fsyz = h.fsyz;
   if ((M2_gbTrace & PRINT_SPAIR_TRACKING) != 0)
     {
       buffer o;
       o << "number of reduction steps was " << count;
       emit_line(o.str());
     }
   else if (M2_gbTrace >= 4 && M2_gbTrace != 15)
     {
       buffer o;
       o << "," << count;
       emit_wrapped(o.str());
     }
 }
References _F, _Fsyz, ALLOCATE_EXPONENTS, gbvector::comp, emit_line(), emit_wrapped(), exp_size, POLY::f, find_good_divisor(), POLY::fsyz, gb, GBRing::gbvector_get_lead_exponents(), GBRing::gbvector_is_zero(), GBRing::gbvector_reduce_lead_term(), GBRing::gbvector_remove_content(), GBRing::gbvector_text_out(), M2_gbTrace, gbvector::next, PRINT_SPAIR_TRACKING, R, buffer::str(), and x.
Referenced by remainder().