Macaulay2 Engine: gbA::over_ZZ
over_ZZ()
bool gbA::over_ZZ () const inline private
Definition at line 225 of file gb-default.hpp.
 { return _coeff_type == Ring::COEFF_ZZ; }
References _coeff_type, and Ring::COEFF_ZZ.
Referenced by auto_reduce_by(), do_computation(), get_mingens(), get_resolved_gb_index(), initialize(), insert_gb(), minimalize_pairs(), reduceit(), remainder(), remove_unneeded_pairs(), and set_hilbert_function().