Macaulay2 Engine: gbA::spair_set_prepare_next_degree
spair_set_prepare_next_degree()
int gbA::spair_set_prepare_next_degree (int & nextdegree) private
Definition at line 1133 of file gb-default.cpp.
 {
   S->spair_list = 0;
   S->spair_deferred_list.next = 0;
   S->spair_last_deferred = &S->spair_deferred_list;
   S->gen_list = 0;
   S->gen_deferred_list.next = 0;
   S->gen_last_deferred = &S->gen_deferred_list;
   int len = spair_set_determine_next_degree(nextdegree);
   if (len == 0) return 0;
   spair head;
   spair *p;
   head.next = S->heap;
   p = &head;
   while (p->next != 0)
     if (p->next->deg != nextdegree)
       p = p->next;
     else
       {
         spair *tmp = p->next;
         p->next = tmp->next;
         if (tmp->type == SPAIR::SPAIR_GEN)
           {
             tmp->next = S->gen_list;
             S->gen_list = tmp;
           }
         else
           {
             // All other types are on the spair list
             tmp->next = S->spair_list;
             S->spair_list = tmp;
           }
       }
   S->heap = head.next;
   S->n_in_degree = len;
   /* Now sort 'spair_list' and 'gen_list'. */
   spairs_sort(len, S->spair_list);
   spairs_sort(len, S->gen_list);
   //  G->spairs_reverse(S->spair_list);
   //  G->spairs_reverse(S->gen_list);
   return len;
 }
References gbA::SPairSet::gen_deferred_list, gbA::SPairSet::gen_last_deferred, gbA::SPairSet::gen_list, gbA::SPairSet::heap, gbA::SPairSet::n_in_degree, gbA::spair::next, p, S, gbA::SPairSet::spair_deferred_list, SPAIR_GEN, gbA::SPairSet::spair_last_deferred, gbA::SPairSet::spair_list, spair_set_determine_next_degree(), spairs_sort(), and gbA::spair::type.
Referenced by do_computation().