Macaulay2 Engine: gbA::find_good_divisor
find_good_divisor()
int gbA::find_good_divisor (exponents_t e, int x, int degf, int & result_gap) private
Definition at line 1693 of file gb-default.cpp.
 {
   int n = 0;
   int gap;
   int egap = degf - weightInfo_->exponents_weight(e, x);
   VECTOR(MonomialTable::mon_term *) divisors;
   if (!is_local_gb && divisor_previous >= 0 && x == divisor_previous_comp)
     {
       gbelem *tg = gb[divisor_previous];
       gap = tg->gap - egap;
       if (gap <= 0 && exponents_divide(_nvars, tg->lead, e))
         {
           result_gap = 0;
           return divisor_previous;
         }
     }
   /* First search for ring divisors */
   if (ringtable) n += ringtable->find_divisors(-1, e, 1, &divisors);
   /* Next search for GB divisors */
   n += lookup->find_divisors(-1, e, x, &divisors);
   if (M2_gbTrace == 15 && n >= 2)
     {
       gbelem *tg = gb[divisors[n - 1]->_val];
       int sz = tg->size;
       if (sz >= 0)  // was 3, why??
         {
           buffer o;
           o << "    reducers: ";
           for (int j = 0; j < n; j++) o << "g" << divisors[j]->_val << " ";
           emit_line(o.str());
         }
     }
   /* Now find the minimal gap value */
   if (n == 0)
     {
       result_gap = 0;
       return -1;
     }
   if (is_local_gb)
     {
       // new version, under development
       int i = 0;
       int j = divisors[i]->_val;
       gap = gb[j]->gap - egap;
       if (gap < 0) gap = 0;
       while (true)
         {
           int mingap = gap;
           int best = j;
           do
             {
               if (++i == n)
                 {
                   divisor_previous = best;
                   divisor_previous_comp = x;
                   result_gap = mingap;  // a difference between two gaps is no
                                         // longer a "gap"...
                   if (result_gap < 0)
                     result_gap = 0;  // I'm not sure this is needed.
                   return best;
                 }
               j = divisors[i]->_val;
               gap = gb[j]->gap - egap;
               if (gap < 0) gap = 0;
             }
           while (gap >= mingap);  // used to be: (! gap < mingap || gap ==
                                   // mingap && false)
         }
     }
   else
     {
       int newgap;
       int result = divisors[n - 1]->_val;
       gbelem *tg = gb[result];
       gap = tg->gap - egap;
       if (gap <= 0)
         {
           gap = 0;
           int minsz = tg->size;
           for (int i = n - 2; i >= 0; i--)
             {
               int new_val = divisors[i]->_val;
               tg = gb[new_val];
               int sz = tg->size;
               if (sz < minsz)
                 {
                   if (tg->gap <= egap)
                     {
                       minsz = sz;
                       result = new_val;
                     }
                 }
             }
         }
       else
         //    for (i=1; i<n; i++)
         for (int i = n - 2; i >= 0; i--)
           {
             int new_val = divisors[i]->_val;
             tg = gb[new_val];
             newgap = tg->gap - egap;
             if (newgap <= 0)
               {
                 gap = 0;
                 result = new_val;
                 break;
               }
             else if (newgap < gap)
               {
                 result = new_val;
                 gap = newgap;
               }
           }
       divisor_previous = result;
       divisor_previous_comp = x;
       result_gap = gap;
       return result;
     }
 }
References _nvars, divisor_previous, divisor_previous_comp, emit_line(), exponents_divide(), GBWeight::exponents_weight(), MonomialTable::find_divisors(), gbA::gbelem::gap, gb, is_local_gb, gbA::gbelem::lead, lookup, M2_gbTrace, ringtable, gbA::gbelem::size, buffer::str(), VECTOR(), weightInfo_, and x.
Referenced by reduce_kk(), and remainder_non_ZZ().