Macaulay2 Engine: gbA::process_spair
process_spair()
bool gbA::process_spair (spair * p) private
Definition at line 2280 of file gb-default.cpp.
 {
   stats_npairs++;
   if (false and spair_is_retired(p))
     {
       stats_nretired++;
       spair_delete(p);
       return true;
     }
   bool not_deferred = reduceit(p);
   if (!not_deferred) return true;
   gbelem_type minlevel =
       (p->type == SPAIR::SPAIR_GEN ? ELEM_MINGEN : 0) | ELEM_MINGB;
   POLY f = p->x.f;
   p->x.f.f = 0;
   p->x.f.fsyz = 0;
   spair_delete(p);
   if (!R->gbvector_is_zero(f.f))
     {
       insert_gb(f, minlevel);
       if (M2_gbTrace == 3) emit_wrapped("m");
     }
   else
     {
       originalR->get_quotient_info()->gbvector_normal_form(_Fsyz, f.fsyz);
       if (!R->gbvector_is_zero(f.fsyz))
         {
           /* This is a syzygy */
           collect_syzygy(f.fsyz);
           if (M2_gbTrace == 3) emit_wrapped("z");
         }
       else
         {
           if (M2_gbTrace == 3) emit_wrapped("o");
         }
     }
   return true;
 }
References _Fsyz, collect_syzygy(), ELEM_MINGB, ELEM_MINGEN, emit_wrapped(), POLY::f, POLY::fsyz, GBRing::gbvector_is_zero(), QRingInfo::gbvector_normal_form(), PolynomialRing::get_quotient_info(), insert_gb(), M2_gbTrace, originalR, p, R, reduceit(), spair_delete(), SPAIR_GEN, spair_is_retired(), stats_npairs, and stats_nretired.
Referenced by do_computation().