Macaulay2 Engine: gbA::exponents_make
exponents_make()
exponents_t gbA::exponents_make () private
Definition at line 49 of file gb-default.cpp.
 {
   exponents_t result = reinterpret_cast<exponents_t>(lcm_stash->new_elem());
   return result;
 }
References lcm_stash, and stash::new_elem().
Referenced by gbelem_copy(), gbelem_make(), gbelem_ring_make(), spair_make(), spair_make_gen(), and spair_make_skew().