Macaulay2 Engine: gbA::gbelem_copy
gbelem_copy()
gbA::gbelem * gbA::gbelem_copy (gbelem * g) private
Definition at line 384 of file gb-default.cpp.
 {
   gbelem *gnew = reinterpret_cast<gbelem *>(gbelem_stash->new_elem());
   gnew->g.f = R->gbvector_copy(g->g.f);
   gnew->g.fsyz = R->gbvector_copy(g->g.fsyz);
   gnew->lead = exponents_make();
   for (int i = 0; i < _nvars; i++) gnew->lead[i] = g->lead[i];
   gnew->deg = g->deg;
   gnew->minlevel = g->minlevel;
   return g;
 }
References _nvars, gbA::gbelem::deg, exponents_make(), POLY::f, POLY::fsyz, gbA::gbelem::g, gbelem_stash, GBRing::gbvector_copy(), gbA::gbelem::lead, gbA::gbelem::minlevel, stash::new_elem(), and R.