Macaulay2 Engine: gbA::spair_delete
spair_delete()
void gbA::spair_delete (spair *& p) private
Definition at line 434 of file gb-default.cpp.
 {
   if (p == nullptr) return;
   if (p->type == SPAIR::SPAIR_GEN || p->type == SPAIR::SPAIR_ELEM)
     {
       R->gbvector_remove(p->x.f.f);
       R->gbvector_remove(p->x.f.fsyz);
     }
   R->gbvector_remove(p->lead_of_spoly);
   lcm_stash->delete_elem(p->lcm);
   spair_stash->delete_elem(p);
 }
References stash::delete_elem(), GBRing::gbvector_remove(), lcm_stash, p, R, SPAIR_GEN, and spair_stash.
Referenced by flush_pairs(), minimalize_pairs_non_ZZ(), process_spair(), remove_spair_list(), and remove_unneeded_pairs().