Macaulay2 Engine: gbA::spair_node
spair_node()
gbA::spair * gbA::spair_node () private
Definition at line 426 of file gb-default.cpp.
 {
   spair *result = reinterpret_cast<spair *>(spair_stash->new_elem());
   result->next = 0;
   result->lead_of_spoly = 0;
   return result;
 }
References gbA::spair::lead_of_spoly, stash::new_elem(), gbA::spair::next, and spair_stash.
Referenced by spair_make(), spair_make_gen(), and spair_make_skew().