Macaulay2 Engine: gbA::show_mem_usage
show_mem_usage()
void gbA::show_mem_usage ()
Definition at line 2806 of file gb-default.cpp.
 {
   buffer o;
   long nmonoms = 0;
   for (int i = 0; i < gb.size(); i++)
     if (gb[i])
       {
         nmonoms += R->gbvector_n_terms(gb[i]->g.f);
         nmonoms += R->gbvector_n_terms(gb[i]->g.fsyz);
       }
   emit_line(o.str());
   o << "number of (nonminimal) gb elements = " << gb.size();
   emit_line(o.str());
   o.reset();
   o << "number of monomials                = " << nmonoms;
   emit_line(o.str());
 }
References emit_line(), gb, GBRing::gbvector_n_terms(), R, buffer::reset(), and buffer::str().
Referenced by start_computation().