Macaulay2 Engine: gbA::insert_gb
insert_gb()
void gbA::insert_gb (POLY f, gbelem_type minlevel) private
Definition at line 2122 of file gb-default.cpp.
 {
   /* Reduce this element as far as possible.  This either removes content,
      makes it monic, or at least negates it so the lead coeff is positive. */
   ring_elem junk;
   // DEBUG BLOCK  int fwt;
   //  int fdeg = weightInfo_->gbvector_weight(f.f, fwt);
   //  fprintf(stderr, "inserting GB element %d, thisdeg %d deg %d gap %d\n",
   //      gb.size(),
   //      this_degree,
   //      fdeg,
   //      fdeg-fwt);
   if (is_local_gb)
     R->gbvector_remove_content(f.f, f.fsyz, false, junk);
   else
     remainder(f, this_degree, false, junk);
   //  fdeg = weightInfo_->gbvector_weight(f.f, fwt);
   //  fprintf(stderr, "    after remainder deg %d gap %d\n",
   //      fdeg,
   //      fdeg-fwt);
   stats_ngb++;
   // Complete hack for getting bug fix to get test/isSubset.m2 to work again for
   // 1.3:
   // over ZZ, always make gb elements non reducers...
   if (over_ZZ()) minlevel |= ELEM_MINGB;
   gbelem *g = gbelem_make(f.f, f.fsyz, minlevel, this_degree);
   minimal_gb_valid = false;
   int me = INTSIZE(gb);
   gb.push_back(g);
   forwardingZZ.push_back(-1);
   n_gb++;
   int x = g->g.f->comp;
   // In a encoded Schreyer order, the following line might miss subring
   // elements.
   // But it at least won't be incorrect...
   if (R->get_flattened_monoid()->in_subring(1, g->g.f->monom)) n_subring++;
   if (over_ZZ())
     lookupZZ->insert(g->g.f->coeff.get_mpz(), g->lead, x, me);
   else
     lookup->insert(g->lead, x, me);
   if (M2_gbTrace == 15)
     {
       buffer o;
       o << "    new ";
       gbelem_text_out(o, INTSIZE(gb) - 1);
       emit_line(o.str());
     }
   else if (M2_gbTrace >= 5)
     {
       const int N = 100;
       char s[N];
       buffer o;
       snprintf(s, N, "new-inserting element %d (minimal %d): ", me, minlevel);
       o << s;
       R->gbvector_text_out(o, _F, g->g.f);
       emit_line(o.str());
       o.reset();
       o << "                          syzygy : ";
       R->gbvector_text_out(o, _Fsyz, g->g.fsyz);
       emit_line(o.str());
     }
   if (!is_local_gb) auto_reduce_by(me);
   if (use_hilb)
     {
       hilb_new_elems = true;
       if (--hilb_n_in_degree == 0) flush_pairs();
     }
   else
     {
 #ifdef DEVELOPMENT
 #warning "todo: codimension stop condition"
 #endif
       // codim test is set.  Compute the codimension now.
     }
   if (M2_gbTrace >= 10)
     {
       //      lookupZZ->showmontable();
       //      show();
     }
 }
References _F, _Fsyz, auto_reduce_by(), gbvector::coeff, gbvector::comp, ELEM_MINGB, emit_line(), POLY::f, flush_pairs(), forwardingZZ, POLY::fsyz, gbA::gbelem::g, gb, gbelem_make(), gbelem_text_out(), GBRing::gbvector_remove_content(), GBRing::gbvector_text_out(), GBRing::get_flattened_monoid(), ring_elem::get_mpz(), hilb_n_in_degree, hilb_new_elems, Monoid::in_subring(), MonomialTable::insert(), MonomialTableZZ::insert(), INTSIZE, is_local_gb, gbA::gbelem::lead, lookup, lookupZZ, M2_gbTrace, minimal_gb_valid, gbvector::monom, n_gb, n_subring, over_ZZ(), R, remainder(), buffer::reset(), stats_ngb, buffer::str(), this_degree, use_hilb, and x.
Referenced by process_spair(), reduce_kk(), and reduce_ZZ().