Macaulay2 Engine: gbA::spair_make
spair_make()
gbA::spair * gbA::spair_make (int i, int j) private
Definition at line 447 of file gb-default.cpp.
 {
   gbelem *g1 = gb[i];
   gbelem *g2 = gb[j];
   exponents_t exp1 = g1->lead;
   exponents_t exp2 = g2->lead;
   spair *result = spair_node();
   result->next = 0;
   result->type = SPAIR::SPAIR_SPAIR;
   result->lcm = exponents_make();
   exponents_lcm(
       _nvars, g1->deg, exp1, exp2, result->lcm, gb_weights, result->deg);
   if (g2->gap > g1->gap) result->deg += g2->gap - g1->gap;
   result->x.pair.i = i;
   result->x.pair.j = j;
   return result;
 }
References _nvars, gbA::gbelem::deg, gbA::spair::deg, mpfr::exp2(), exponents_lcm(), exponents_make(), gbA::gbelem::gap, gb, gb_weights, gbA::spair::lcm, gbA::gbelem::lead, gbA::spair::next, gbA::spair::pair, spair_node(), gbA::spair::type, and gbA::spair::x.
Referenced by spair_make_gcd_ZZ(), spair_make_ring(), and update_pairs().