Macaulay2 Engine: gbA::auto_reduce_by
auto_reduce_by()
void gbA::auto_reduce_by (int id) private
Definition at line 2055 of file gb-default.cpp.
 {
   /* Loop backwards while degree doesn't change */
   /* Don't change quotient ring elements */
   gbelem *me = gb[id];
   int a = me->gap;  // Only auto reduce those that are of the same degree
                     // and not a higher gap level
   for (int i = INTSIZE(gb) - 1; i >= first_gb_element; i--)
     {
       if (!gb[i]) continue;
       if (i == id) continue;
       gbelem *g = gb[i];
       if (g->deg < me->deg) return;
       if (g->gap < a) continue;
       if (M2_gbTrace >= 10)
         {
           buffer o;
           o << "  auto reduce " << i << " by " << id;
           emit_line(o.str());
         }
       if (over_ZZ())
         {
           R->gbvector_auto_reduce_ZZ(_F,
                                      _Fsyz,
                                      g->g.f,
                                      g->g.fsyz,  // these are modified
                                      me->g.f,
                                      me->g.fsyz);
         }
       else
         {
           R->gbvector_auto_reduce(_F,
                                   _Fsyz,
                                   g->g.f,
                                   g->g.fsyz,  // these are modified
                                   me->g.f,
                                   me->g.fsyz);
         }
     }
 }
References _F, _Fsyz, gbA::gbelem::deg, emit_line(), POLY::f, first_gb_element, POLY::fsyz, gbA::gbelem::g, gbA::gbelem::gap, gb, GBRing::gbvector_auto_reduce(), GBRing::gbvector_auto_reduce_ZZ(), INTSIZE, M2_gbTrace, over_ZZ(), R, and buffer::str().
Referenced by insert_gb(), and replace_gb_element_ZZ().