Macaulay2 Engine: gbA::remove_unneeded_pairs
remove_unneeded_pairs()
void gbA::remove_unneeded_pairs (int id) private
Definition at line 624 of file gb-default.cpp.
 {
   /* Removes all pairs from C->S that are not needed */
   if (over_ZZ()) return;
   spair head;
   spair *p = &head;
   gbelem *m = gb[id];
   head.next = S->heap;
   while (p->next != 0)
     if (pair_not_needed(p->next, m))
       {
         nsaved_unneeded++;
         spair *tmp = p->next;
         p->next = tmp->next;
         tmp->next = 0;
         if (M2_gbTrace >= 10)
           {
             buffer o;
             o << "removing unneeded ";
             spair_text_out(o, tmp);
             emit_line(o.str());
           }
         spair_delete(tmp);
         S->nelems--;
       }
     else
       p = p->next;
   S->heap = head.next;
 }
References emit_line(), gb, gbA::SPairSet::heap, M2_gbTrace, gbA::SPairSet::nelems, gbA::spair::next, nsaved_unneeded, over_ZZ(), p, pair_not_needed(), S, spair_delete(), spair_text_out(), and buffer::str().
Referenced by update_pairs().