Macaulay2 Engine: gbA::set_hilbert_function
set_hilbert_function()
Computation * gbA::set_hilbert_function (const RingElement * h) virtual
Reimplemented from GBComputation.
Definition at line 2650 of file gb-default.cpp.
 {
   // TODO Problems here:
   //  -- check that the ring is correct
   //  -- if the computation has already been started, this will fail
   //     So probably an error should be given, and 0 returned in this case.
   // We may only use the Hilbert function if syzygies are not being collected
   // since otherwise we will miss syzygies
   if (over_ZZ())
     {
       ERROR(
           "cannot use Hilbert function for Groebner basis computation over the "
           "integers");
       return nullptr;
     }
   if (!_collect_syz)
     {
       hf_orig = hf;
       hf_diff = RingElement::make_raw(hf->get_ring(), ZERO_RINGELEM);
       use_hilb = true;
       hilb_new_elems = true;
       state = STATE_HILB;
     }
   return this;
 }
References _collect_syz, ERROR(), RingElement::get_ring(), hf_diff, hf_orig, hilb_new_elems, RingElement::make_raw(), over_ZZ(), state, STATE_HILB, use_hilb, and ZERO_RINGELEM.