Macaulay2 Engine: gbA::reduceit
reduceit()
bool gbA::reduceit (spair * p) private
Definition at line 1568 of file gb-default.cpp.
 {
   if (over_ZZ()) return reduce_ZZ(p);
   return reduce_kk(p);
 }
References over_ZZ(), p, reduce_kk(), and reduce_ZZ().
Referenced by process_spair().