Macaulay2 Engine: gbA::minimalize_gb
minimalize_gb()
void gbA::minimalize_gb () private
Definition at line 2614 of file gb-default.cpp.
 {
   if (minimal_gb_valid) return;
   delete minimal_gb;
   minimal_gb = ReducedGB::create(originalR, _F, _Fsyz);
   VECTOR(POLY) polys;
   for (int i = first_gb_element; i < gb.size(); i++)
     if (gb[i])
       {
         if (gb[i]->minlevel & ELEM_MINGB) polys.push_back(gb[i]->g);
       }
   minimal_gb->minimalize(polys);
   minimal_gb_valid = true;
 }
References _F, _Fsyz, ReducedGB::create(), ELEM_MINGB, first_gb_element, gb, minimal_gb, minimal_gb_valid, ReducedGB::minimalize(), originalR, and VECTOR().
Referenced by contains(), get_change(), get_gb(), get_initial(), get_parallel_lead_terms(), matrix_lift(), and matrix_remainder().