Macaulay2 Engine: gbA::create
create()
gbA * gbA::create (const Matrix * m, M2_bool collect_syz, int n_rows_to_keep, M2_arrayint gb_weights, int strategy, M2_bool use_max_degree, int max_degree, int max_reduction_count) static
Definition at line 55 of file gb-default.cpp.
 {
   const PolynomialRing *origR = m->get_ring()->cast_to_PolynomialRing();
   if (origR == nullptr)
     {
       ERROR("ring is not a polynomial ring");
       return nullptr;
     }
   if (origR->getMonoid()->numInvertibleVariables() > 0)
     {
       ERROR(
           "cannot compute Groebner basis of ideal over a Laurent polynomial "
           "ring, ie. with Inverses=>true");
       return nullptr;
     }
   bool overZZ = origR->coefficient_type() == Ring::COEFF_ZZ;
   bool isLocal = origR->getMonoid()->numNonTermOrderVariables() > 0;
   if (overZZ and isLocal)
     {
       ERROR(
           "Groebner bases in rings over ZZ with variables less than zero are "
           "not yet supported");
       return nullptr;
     }
   gbA *result = new gbA;
   result->initialize(m,
                      collect_syz,
                      n_rows_to_keep,
                      gb_weights,
                      strategy,
                      max_reduction_count);
   return result;
 }
References Ring::cast_to_PolynomialRing(), Ring::COEFF_ZZ, PolynomialRing::coefficient_type(), ERROR(), gb_weights, Matrix::get_ring(), PolynomialRing::getMonoid(), initialize(), max_reduction_count, Monoid::numInvertibleVariables(), and Monoid::numNonTermOrderVariables().
Referenced by GBComputation::choose_gb().