Macaulay2 Engine: gbA::spair_set_lead_spoly
spair_set_lead_spoly()
void gbA::spair_set_lead_spoly (spair * p) private
Definition at line 1260 of file gb-default.cpp.
 {
   gbvector *ltsyz = nullptr;
   POLY f, g;
   if (p->type > SPAIR::SPAIR_SKEW)
     {
       R->gbvector_remove(p->lead_of_spoly);
       p->lead_of_spoly = nullptr;
       return;
     }
   f = gb[p->x.pair.i]->g;
   if (p->type == SPAIR::SPAIR_SKEW)
     {
       const int *mon = R->skew_monomial_var(p->x.pair.j);
       R->gbvector_mult_by_term(
           _F, _Fsyz, R->one(), mon, f.f, nullptr, p->lead_of_spoly, ltsyz);
     }
   else if (p->type == SPAIR::SPAIR_GCD_ZZ)
     {
       g = gb[p->x.pair.j]->g;
       R->gbvector_combine_lead_terms_ZZ(
           _F, _Fsyz, f.f, nullptr, g.f, nullptr, p->lead_of_spoly, ltsyz);
     }
   else
     {
       g = gb[p->x.pair.j]->g;
       R->gbvector_cancel_lead_terms(
           _F, _Fsyz, f.f, nullptr, g.f, nullptr, p->lead_of_spoly, ltsyz);
     }
   if (p->lead_of_spoly != nullptr)
     {
       gbvector *tmp = p->lead_of_spoly->next;
       p->lead_of_spoly->next = nullptr;
       R->gbvector_remove(tmp);
     }
 }
References _F, _Fsyz, POLY::f, gb, GBRing::gbvector_cancel_lead_terms(), GBRing::gbvector_combine_lead_terms_ZZ(), GBRing::gbvector_mult_by_term(), GBRing::gbvector_remove(), GBRing::one(), p, R, and GBRing::skew_monomial_var().
Referenced by spair_set_insert().