Macaulay2 Engine: gbA::spair_make_gen
spair_make_gen()
gbA::spair * gbA::spair_make_gen (POLY f) private
Definition at line 473 of file gb-default.cpp.
 {
   assert(f.f != 0);
   exponents_t exp1 = exponents_make();
   R->gbvector_get_lead_exponents(_F, f.f, exp1);
   int deg = weightInfo_->gbvector_weight(f.f);
   spair *result = spair_node();
   result->next = 0;
   result->type = SPAIR::SPAIR_GEN;
   result->deg = deg;
   result->lcm = exp1;
   result->x.f = f;
   return result;
 }
References _F, gbA::spair::deg, exponents_make(), gbA::spair::f, POLY::f, GBRing::gbvector_get_lead_exponents(), GBWeight::gbvector_weight(), gbA::spair::lcm, gbA::spair::next, R, SPAIR_GEN, spair_node(), gbA::spair::type, weightInfo_, and gbA::spair::x.
Referenced by new_gen().