Macaulay2 Engine: gbA::spair_set_next
spair_set_next()
gbA::spair * gbA::spair_set_next () private
Definition at line 1038 of file gb-default.cpp.
 {
   spair *result = S->spair_list;
   if (result)
     {
       S->spair_list = result->next;
     }
   else
     {
       if (S->spair_deferred_list.next != nullptr)
         {
           if (M2_gbTrace >= 4)
             {
               emit_line("considering deferred pairs: ");
             }
           S->spair_list = S->spair_deferred_list.next;
           S->spair_deferred_list.next = nullptr;
           S->spair_last_deferred = &S->spair_deferred_list;
           result = S->spair_list;
           S->spair_list = result->next;
         }
       else
         {
           // Now do the same for generators
           result = S->gen_list;
           if (result)
             {
               S->gen_list = result->next;
             }
           else
             {
               if (S->gen_deferred_list.next != nullptr)
                 {
                   if (M2_gbTrace >= 4)
                     {
                       emit_line("  deferred gen pairs: ");
                     }
                   S->gen_list = S->gen_deferred_list.next;
                   S->gen_deferred_list.next = nullptr;
                   S->gen_last_deferred = &S->gen_deferred_list;
                   result = S->gen_list;
                   S->gen_list = result->next;
                 }
               else
                 return nullptr;
             }
         }
     }
   result->next = nullptr;
   S->nelems--;
   S->n_in_degree--;
   S->n_computed++;
   if (result->type == SPAIR::SPAIR_GEN) n_gens_left--;
   return result;
 }
References emit_line(), gbA::SPairSet::gen_deferred_list, gbA::SPairSet::gen_last_deferred, gbA::SPairSet::gen_list, M2_gbTrace, gbA::SPairSet::n_computed, n_gens_left, gbA::SPairSet::n_in_degree, gbA::SPairSet::nelems, gbA::spair::next, S, gbA::SPairSet::spair_deferred_list, SPAIR_GEN, gbA::SPairSet::spair_last_deferred, gbA::SPairSet::spair_list, and gbA::spair::type.
Referenced by do_computation(), and flush_pairs().