Macaulay2 Engine: gbA::get_syzygies
get_syzygies()
const Matrix * gbA::get_syzygies () virtual
Implements GBComputation.
Definition at line 2714 of file gb-default.cpp.
 {
   // The (non-minimal) syzygy matrix
   MatrixConstructor mat(_Fsyz, 0);
   for (VECTOR(gbvector *)::iterator i = _syz.begin(); i != _syz.end(); i++)
     if (*i)
       {
         mat.append(originalR->translate_gbvector_to_vec(_Fsyz, *i));
       }
   return mat.to_matrix();
 }
References _Fsyz, _syz, MatrixConstructor::append(), originalR, MatrixConstructor::to_matrix(), PolynomialRing::translate_gbvector_to_vec(), and VECTOR().