Macaulay2 Engine: gbA::find_good_term_divisor_ZZ
find_good_term_divisor_ZZ()
int gbA::find_good_term_divisor_ZZ (mpz_srcptr c, exponents_t e, int x, int degf, int & result_gap) private
Definition at line 1628 of file gb-default.cpp.
 {
   // Get all of the term divisors.
   // Choose one with the smallest gap.
   int i, gap, newgap, egap;
   int n = 0;
   VECTOR(MonomialTableZZ::mon_term *) divisors;
   egap = degf - weightInfo_->exponents_weight(e, x);
   /* First search for ring divisors */
   if (ringtableZZ) n += ringtableZZ->find_term_divisors(-1, c, e, 1, &divisors);
   /* Next search for GB divisors */
   n += lookupZZ->find_term_divisors(-1, c, e, x, &divisors);
   /* Now find the minimal gap value */
   if (n == 0)
     {
       result_gap = 0;
       return -1;
     }
   int result = divisors[n - 1]->_val;
   gbelem *tg = gb[result];
   gap = tg->gap - egap;
   if (gap <= 0)
     gap = 0;
   else
     for (i = n - 2; i >= 0; i--)
       {
         int new_val = divisors[i]->_val;
         tg = gb[new_val];
         newgap = tg->gap - egap;
         if (newgap <= 0)
           {
             gap = 0;
             result = new_val;
             break;
           }
         else if (newgap < gap)
           {
             result = new_val;
             gap = newgap;
           }
       }
   result_gap = gap;
   return result;
 }
References GBWeight::exponents_weight(), MonomialTableZZ::find_term_divisors(), gbA::gbelem::gap, gb, lookupZZ, ringtableZZ, VECTOR(), weightInfo_, and x.
Referenced by reduce_ZZ().