Macaulay2 Engine: gbA::spair_make_skew
spair_make_skew()
gbA::spair * gbA::spair_make_skew (int i, int v) private
Definition at line 489 of file gb-default.cpp.
 {
   spair *result;
   int j;
   gbelem *g1 = gb[i];
   exponents_t exp1 = g1->lead;
   exponents_t exp2 = exponents_make();
   int vvar = R->skew_variable(v);
   for (j = 0; j < _nvars; j++) exp2[j] = 0;
   exp2[vvar] = 2;
   result = spair_node();
   result->next = nullptr;
   result->type = SPAIR::SPAIR_SKEW;
   result->lcm = exp2;
   exponents_lcm(_nvars, g1->deg, exp1, exp2, exp2, gb_weights, result->deg);
   result->x.pair.i = i;
   result->x.pair.j = v;
   return result;
 }
References _nvars, gbA::gbelem::deg, gbA::spair::deg, mpfr::exp2(), exponents_lcm(), exponents_make(), gb, gb_weights, gbA::spair::lcm, gbA::gbelem::lead, gbA::spair::next, gbA::spair::pair, R, GBRing::skew_variable(), spair_node(), gbA::spair::type, and gbA::spair::x.
Referenced by update_pairs().