Macaulay2 Engine: gbA::spair_text_out
spair_text_out()
void gbA::spair_text_out (buffer & o, spair * p) private
Definition at line 519 of file gb-default.cpp.
 {
   const int N = 1000;
   char s[N];  // enough room for all of the non polynomial cases.
   switch (p->type)
     {
       case SPAIR::SPAIR_GCD_ZZ:
         snprintf(s, N, "spairgcd(g%d,g%d)", p->x.pair.j, p->x.pair.i);
         o << s;
         snprintf(s, N, " deg(%d)", p->deg);
         o << s;
         o << " lcm[";
         for (int i = 0; i < _nvars + 2; i++)
           {
             snprintf(s, N, "%d ", p->lcm[i]);
             o << s;
           }
         o << "]";
         break;
       case SPAIR::SPAIR_SPAIR:
         snprintf(s, N, "spair(g%d,g%d):", p->x.pair.j, p->x.pair.i);
         o << s;
         snprintf(s, N, " deg %d", p->deg);
         o << s;
         o << " lcm exponents [";
         for (int i = 0; i < _nvars + 2; i++)
           {
             snprintf(s, N, "%d ", p->lcm[i]);
             o << s;
           }
         o << "]";
         break;
       case SPAIR::SPAIR_GEN:
         o << "generator ";
         R->gbvector_text_out(o, _F, p->f(), 3);
         break;
       case SPAIR::SPAIR_ELEM:
         o << "elem ";
         R->gbvector_text_out(o, _F, p->f(), 3);
         break;
       case SPAIR::SPAIR_RING:
         snprintf(s, N, "rpair(%d,%d)", p->x.pair.i, p->x.pair.j);
         o << s;
         break;
       case SPAIR::SPAIR_SKEW:
         snprintf(s, N, "skewpair(g%d,g%d)", p->x.pair.j, p->x.pair.i);
         o << s;
         break;
       default:
         o << "unknown pair";
         break;
     }
 }
References _F, _nvars, GBRing::gbvector_text_out(), p, R, SPAIR_GEN, and SPAIR_RING.
Referenced by compute_s_pair(), debug_spair(), minimalize_pairs_non_ZZ(), minimalize_pairs_ZZ(), reduce_kk(), reduce_ZZ(), and remove_unneeded_pairs().