Macaulay2 Engine: gbA::minimalize_pairs_ZZ
minimalize_pairs_ZZ()
void gbA::minimalize_pairs_ZZ (spairs & new_set) private
Definition at line 840 of file gb-default.cpp.
 {
   // Prune down the set of spairs to a 'minimal' set.  For each one, we
   // need to add in a "gcd" combination spair as well.
   VECTOR(mpz_srcptr) coeffs;
   VECTOR(mpz_srcptr) coeffs2;
   VECTOR(exponents_t) exps;
   VECTOR(int) comps;
   VECTOR(int) positions;
   coeffs.reserve(gb.size());
   coeffs2.reserve(gb.size());
   exps.reserve(gb.size());
   comps.reserve(gb.size());
   for (VECTOR(spair *)::iterator i = new_set.begin(); i != new_set.end(); i++)
     {
       spair *a = *i;
       exps.push_back(a->lcm);
       comps.push_back(1); /* This is not needed here, as all of these
                              have the same component */
       /* Now get the coefficient */
       /* This is the lcm divided by the lead coeff, but it depends on the kind
        * of spair */
       if (a->type == SPAIR::SPAIR_SKEW)
         {
           coeffs.push_back(globalZZ->one().get_mpz());
           coeffs2.push_back(nullptr);  // will never be referred to below
         }
       else
         {
           /* */
           gbvector *f1 = gb[a->x.pair.i]->g.f;
           gbvector *f2 = gb[a->x.pair.j]->g.f;
           ring_elem u, v;
           globalZZ->syzygy(f1->coeff, f2->coeff, u, v);
           coeffs.push_back(u.get_mpz());
           coeffs2.push_back(v.get_mpz());
           if (mpz_cmpabs_ui(u.get_mpz(), 1) && mpz_cmpabs_ui(v.get_mpz(), 1))
             {
               spair *p2 = spair_make_gcd_ZZ(a->x.pair.i, a->x.pair.j);
               if (M2_gbTrace >= 4)
                 {
                   buffer o;
                   o << "  creating ";
                   spair_text_out(o, p2);
                   emit_line(o.str());
                 }
               spair_set_insert(p2);
             }
         }
     }
   if (_strategy == 0)
     MonomialTableZZ::find_weak_generators(
         _nvars, coeffs, exps, comps, positions);
   else
     MonomialTableZZ::find_weak_generators(
         _nvars, coeffs, exps, comps, positions, true);
   for (VECTOR(int)::iterator i = positions.begin(); i != positions.end(); i++)
     {
       // Insert this spair, and also the corresponding gcd one.
       spair *p = new_set[*i];
       if (M2_gbTrace >= 4)
         {
           buffer o;
           o << "  creating ";
           spair_text_out(o, p);
           emit_line(o.str());
         }
       spair_set_insert(p);
 #if 0
       mpz_ptr u = coeffs[*i];
       mpz_ptr v = coeffs2[*i];
       if (p->type != SPAIR::SPAIR_SKEW && mpz_cmpabs_ui(u,1) && mpz_cmpabs_ui(v,1))
         {
           spair *p2 = spair_make_gcd_ZZ(p->x.pair.i, p->x.pair.j);
           if (M2_gbTrace >= 4)
             {
               buffer o;
               spair_text_out(o, p2);
               emit_line(o.str());
             }
           spair_set_insert(p2);
         }
 #endif
     }
 }
References _nvars, _strategy, gbvector::coeff, emit_line(), MonomialTableZZ::find_weak_generators(), gb, ring_elem::get_mpz(), globalZZ, gbA::spair::lcm, M2_gbTrace, Ring::one(), p, gbA::spair::pair, spair_make_gcd_ZZ(), spair_set_insert(), spair_text_out(), buffer::str(), RingZZ::syzygy(), gbA::spair::type, VECTOR(), and gbA::spair::x.
Referenced by minimalize_pairs().