Macaulay2 Engine: gbA::spair_set_insert
spair_set_insert()
void gbA::spair_set_insert (gbA::spair * p) private
Definition at line 1011 of file gb-default.cpp.
 {
   while (p != 0)
     {
       if (p->type == SPAIR::SPAIR_GEN) n_gens_left++;
       spair_set_lead_spoly(p);
       spair *tmp = p;
       p = p->next;
       S->nelems++;
       tmp->next = S->heap;
       S->heap = tmp;
     }
 }
References gbA::SPairSet::heap, n_gens_left, gbA::SPairSet::nelems, gbA::spair::next, p, S, SPAIR_GEN, and spair_set_lead_spoly().
Referenced by initialize(), minimalize_pairs_non_ZZ(), minimalize_pairs_ZZ(), reduce_kk(), and reduce_ZZ().