Macaulay2 Engine: M2::ARingRRi::addMultipleTo
addMultipleTo()
void M2::ARingRRi::addMultipleTo (ElementType & result, const ElementType & a, const ElementType & b) const inline
Definition at line 182 of file aring-RRi.hpp.
   {
       ElementType ab;
       init(ab);
       mult(ab,a,b);
       add(result,result,ab);
   }
References add(), init(), and mult().