Macaulay2 Engine: M2::ARingRRi::power
power()
void M2::ARingRRi::power (ElementType & result, const ElementType & a, int n) const inline
Definition at line 226 of file aring-RRi.hpp.
   {
     if (n >= 2)
       {
           if (n%2 == 0)
           {
               ElementType b;
               init(b);
               power(b,a,n/2);
               mult(result,b,b);
           }
           else
           {
               ElementType b;
               init(b);
               power(b,a,n-1);
               mult(result,a,b);
           }
       }
     else if (n == 1)
       mpfi_set(&result,&a);
     else if (n == 0)
       mpfi_set_si(&result,1);
     else if (n<0)
         throw 20;
   }
References init(), and mult().
Referenced by TEST().