Macaulay2 Engine: M2::ARingRRi::subtract_multiple
subtract_multiple()
void M2::ARingRRi::subtract_multiple (ElementType & result, const ElementType & a, const ElementType & b) const inline
Definition at line 200 of file aring-RRi.hpp.
   {
     // result -= a*b
     ElementType ab;
     init(ab);
     mult(ab, a, b);
     subtract(result, result, ab);
     clear(ab);
   }
References clear(), init(), mult(), and subtract().
Referenced by TEST().