Macaulay2 Engine: M2::ARingRRi::eval
eval()
void M2::ARingRRi::eval (const RingMap * map, const ElementType & f, int first_var, ring_elem & result) const inline
Definition at line 340 of file aring-RRi.hpp.
   {
       if (!map->get_ring()->from_Interval(&f, result))
       {
            result = map->get_ring()->from_long(0);
            ERROR("cannot coerce RRi value to ring type");
       }
   }
References ERROR(), Ring::from_Interval(), Ring::from_long(), and RingMap::get_ring().