Macaulay2 Engine: M2::ARingRRi::power_mpz
power_mpz()
void M2::ARingRRi::power_mpz (ElementType & result, const ElementType & a, mpz_srcptr n) const inline
Definition at line 254 of file aring-RRi.hpp.
   {
       if (mpz_cmp_si(n,2)>=0)
       {
           mpz_t r;
           mpz_init(r);
           mpz_fdiv_r_ui(r,n,2);
           ElementType b;
           init(b);
           mpz_t m;
           mpz_init(m);
           if (mpz_cmp_si(r,0) == 0)
           {
               mpz_cdiv_q_ui(m,n,2);
               power_mpz(b,a,m);
               mult(result,b,b);
           }
           else
           {
               mpz_sub_ui(m,n,1);
               power_mpz(b,a,m);
               mult(result,a,b);
           }
           mpz_clear(r);
           mpz_clear(m);
       }
       else if (mpz_cmp_si(n,1)==0)
           mpfi_set(&result,&a);
       else if (mpz_cmp_si(n,0)==0)
           mpfi_set_si(&result,1);
       else if (mpz_cmp_si(n,0)<0)
           throw 20;
   }
References init(), and mult().
Referenced by TEST().