Macaulay2 Engine: FlintQQMat::to_fmpq_mat
to_fmpq_mat()
static void FlintQQMat::to_fmpq_mat (const DMatQQ & mat1, fmpq_mat_t result_mat) inline static private
Definition at line 94 of file dmat-qq-interface-flint.hpp.
   {
     DMatQQ& mat = const_cast<DMatQQ&>(mat1);
     for (long r = 0; r < mat.numRows(); r++)
       {
         auto end = mat.rowEnd(r);
         long c = 0;
         for (auto it = mat.rowBegin(r); it != end; ++it, ++c)
           fmpq_set_mpq(fmpq_mat_entry(result_mat, r, c), &(*it));
       }
   }
References end(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::rowBegin(), and DMat< ACoeffRing >::rowEnd().
Referenced by FlintQQMat().