Macaulay2 Engine: FlintQQMat::numColumns
numColumns()
long FlintQQMat::numColumns () const inline
Definition at line 85 of file dmat-qq-interface-flint.hpp.
 { return fmpq_mat_ncols(mMatrix); }
References mMatrix.
Referenced by DMatLinAlg< M2::ARingQQ >::columnRankProfile(), DMatLinAlg< M2::ARingQQ >::kernel(), DMatLinAlg< M2::ARingQQ >::matrixPLU(), and DMatLinAlg< M2::ARingQQ >::rank().