Macaulay2 Engine: FlintQQMat::FlintQQMat
FlintQQMat() [1/2]
FlintQQMat::FlintQQMat (const DMatQQ & mat) inline
Definition at line 66 of file dmat-qq-interface-flint.hpp.
   {
     fmpq_mat_init(mMatrix, mat.numRows(), mat.numColumns());
     to_fmpq_mat(mat, mMatrix);
   }
References mMatrix, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and to_fmpq_mat().