Macaulay2 Engine: rawRandomInteger
rawRandomInteger()
gmp_ZZ rawRandomInteger (gmp_ZZ maxN)
Definition at line 53 of file random.cpp.
 {
   mpz_ptr result = getmemstructtype(mpz_ptr);
   mpz_init(result);
   if (maxN == 0)
     mpz_urandomm(result, state, maxHeight);
   else if (1 != mpz_sgn(maxN))
     {
       mpz_set_si(result, 0);
     }
   else
     mpz_urandomm(result, state, maxN);
   mpz_reallocate_limbs(result);
   return result;
 }
References getmemstructtype, maxHeight, mpz_reallocate_limbs(), and state.
Referenced by getElement< RingZZ >(), getRandomInteger(), RingZZ::random(), M2::ARingZZGMP::random(), and TEST().