Macaulay2 Engine: randomDouble
randomDouble()
double randomDouble ()
Definition at line 125 of file random.cpp.
 {
   mpfr_t val;
   mpfr_init2(val, 53);
   randomMpfr(val);
   double result = mpfr_get_d(val, MPFR_RNDN);
   mpfr_clear(val);
   return result;
 }
References randomMpfr().
Referenced by M2::ARingCC::random(), and M2::ARingRR::random().