Macaulay2 Engine: minimalize_res_varpower_monomials
minimalize_res_varpower_monomials()
void minimalize_res_varpower_monomials (const VECTOR(res_varpower_monomial) & elems, VECTOR(int) & result_minimals, stash * mi_stash = 0)
Definition at line 539 of file res-f4-monlookup.cpp.
 {
   VECTOR(VECTOR(int) *) bins;
   for (int j = 0; j < elems.size(); j++)
     {
       res_varpower_word d = res_varpower_monomials::simple_degree(elems[j]);
       if (d >= bins.size())
         for (int i = INTSIZE(bins); i <= d; i++) bins.push_back(NULL);
       if (bins[d] == NULL) bins[d] = new VECTOR(int);
       bins[d]->push_back(j);
     }
   // Now insert these into a lookup table
   ResF4MonomialLookupTableT<int> M(
       10, mi_stash);  // The 10 is simply a suggested start value
   for (int i = 0; i < bins.size(); i++)
     if (bins[i] != NULL)
       {
         for (VECTOR(int)::iterator j = bins[i]->begin(); j != bins[i]->end();
              j++)
           {
             int k;
             if (!M.find_one_divisor_vp(0, elems[*j], k))
               {
                 M.insert_minimal_vp(0, elems[*j], 0);
                 result_minimals.push_back(*j);
               }
           }
         freemem(bins[i]);
       }
 }
References ResF4MonomialLookupTableT< Key >::find_one_divisor_vp(), freemem(), ResF4MonomialLookupTableT< Key >::insert_minimal_vp(), INTSIZE, res_varpower_monomials::simple_degree(), and VECTOR().