Macaulay2 Engine: ResF4toM2Interface::from_M2_vec
from_M2_vec()
void ResF4toM2Interface::from_M2_vec (const ResPolyRing & R, const FreeModule * F, vec v, ResPolynomial & result) static
Definition at line 43 of file res-f4-m2-interface.cpp.
 {
   const PolynomialRing* origR = F->get_ring()->cast_to_PolynomialRing();
   const Monoid* M = origR->getMonoid();
   ring_elem denom;
   gbvector* f = origR->translate_gbvector_from_vec(F, v, denom);
   GBRing* GR = origR->get_gb_ring();
   int n = GR->gbvector_n_terms(f);
 #if 0
   buffer o;
   o << "input: ";
   GR->gbvector_text_out(o,F,f,-1);
   o << newline;
   emit(o.str());
 #endif
   int* exp = new int[M->n_vars()];
   ElementArray coeffs = R.vectorArithmetic().allocateElementArray();
   // all these pointers (or values) are still in the element f.
   //  auto monoms = std::unique_ptr<res_monomial_word[]>(new res_monomial_word[n
   //  * R.monoid().max_monomial_size()]);
   std::vector<res_monomial_word> monoms(n * R.monoid().max_monomial_size());
   n = 0;
   res_monomial_word* nextmonom = monoms.data();
   for (gbvector* t = f; t != nullptr; t = t->next)
     {
       R.vectorArithmetic().from_ring_elem(
           coeffs, t->coeff, f->coeff);  // note: f->coeff is assumed to be 1 for
                                         // finite fields, but for QQ both of
                                         // these are integers
       M->to_expvector(t->monom, exp);
       R.monoid().from_expvector(
           exp,
           t->comp - 1,
           nextmonom);  // gbvector components are shifted up by one
       nextmonom += R.monoid().monomial_size(nextmonom);
       n++;
     }
   ResPolynomialConstructor::setPolyFromArrays(result, n, coeffs, monoms);
   GR->gbvector_remove(f);
   delete[] exp;
 }
References VectorArithmetic::allocateElementArray(), Ring::cast_to_PolynomialRing(), gbvector::coeff, emit(), mpfr::exp(), ResMonoidDense::from_expvector(), VectorArithmetic::from_ring_elem(), GBRing::gbvector_n_terms(), GBRing::gbvector_remove(), GBRing::gbvector_text_out(), PolynomialRing::get_gb_ring(), FreeModule::get_ring(), PolynomialRing::getMonoid(), ResMonoidDense::max_monomial_size(), ResPolyRing::monoid(), ResMonoidDense::monomial_size(), Monoid::n_vars(), newline, gbvector::next, ResPolynomialConstructor::setPolyFromArrays(), buffer::str(), Monoid::to_expvector(), PolynomialRing::translate_gbvector_from_vec(), and ResPolyRing::vectorArithmetic().