Macaulay2 Engine: ResF4toM2Interface::to_M2_freemodule
to_M2_freemodule() [1/2]
FreeModule * ResF4toM2Interface::to_M2_freemodule (const PolynomialRing * R, const FreeModule * F, SchreyerFrame & C, int lev) static
Definition at line 184 of file res-f4-m2-interface.cpp.
 {
   if (lev < 0 or lev > C.maxLevel())
     {
       ERROR("expected level in the range %d..%d",1,C.maxLevel());
       return nullptr;
     }
   FreeModule* result = new FreeModule(R, 0, true);
   const Monoid* M = R->getMonoid();
   auto& thislevel = C.level(lev);
   const ResSchreyerOrder& S = C.schreyerOrder(lev);
   int* exp = new int[M->n_vars()];
   monomial deg1 = M->degree_monoid()->make_one();
   for (auto i = 0; i < thislevel.size(); ++i)
     {
       component_index comp;
       C.monoid().to_expvector(S.mTotalMonom[i], exp, comp);
       monomial deg = M->degree_monoid()->make_new(F->degree(comp)); // resulting degree of this element
       M->degree_of_expvector(exp, deg1);
       M->degree_monoid()->mult(deg, deg1, deg);
       // Now grab the Schreyer info
       // unpack to exponent vector, then repack into monoid element
       monomial totalmonom = M->make_one();
       M->from_expvector(exp, totalmonom);
       result->append_schreyer(
           deg, totalmonom, static_cast<int>(S.mTieBreaker[i]));
     }
   delete[] exp;
   M->degree_monoid()->remove(deg1);
   return result;
 }
References FreeModule::append_schreyer(), FreeModule::degree(), Monoid::degree_monoid(), Monoid::degree_of_expvector(), ERROR(), mpfr::exp(), Monoid::from_expvector(), PolynomialRing::getMonoid(), SchreyerFrame::level(), Monoid::make_new(), Monoid::make_one(), SchreyerFrame::maxLevel(), SchreyerFrame::monoid(), ResSchreyerOrder::mTieBreaker, ResSchreyerOrder::mTotalMonom, Monoid::mult(), Monoid::n_vars(), Monoid::remove(), SchreyerFrame::schreyerOrder(), and ResMonoidDense::to_expvector().