Macaulay2 Engine: ResF4toM2Interface::to_M2_freemodule
to_M2_freemodule() [2/2]
FreeModule * ResF4toM2Interface::to_M2_freemodule (const PolynomialRing * R, SchreyerFrame & C, int lev) static
Definition at line 297 of file res-f4-m2-interface.cpp.
 {
   FreeModule* result = new FreeModule(R, 0, true);
   if (lev < 0 or lev > C.maxLevel())
     {
       return result;
     }
   const Monoid* M = R->getMonoid();
   auto& thislevel = C.level(lev);
   const ResSchreyerOrder& S = C.schreyerOrder(lev);
   int* exp = new int[M->n_vars()];
   for (auto i = 0; i < thislevel.size(); ++i)
     {
       int d[1];
       d[0] = thislevel[i].mDegree;
       monomial deg = M->degree_monoid()->make_one();
       M->degree_monoid()->from_expvector(d, deg);
       // Now grab the Schreyer info
       // unpack to exponent vector, then repack into monoid element
       monomial totalmonom = M->make_one();
       component_index comp;
       C.monoid().to_expvector(S.mTotalMonom[i], exp, comp);
       M->from_expvector(exp, totalmonom);
       result->append_schreyer(
           deg, totalmonom, static_cast<int>(S.mTieBreaker[i]));
     }
   delete[] exp;
   return result;
 }
References FreeModule::append_schreyer(), Monoid::degree_monoid(), mpfr::exp(), Monoid::from_expvector(), PolynomialRing::getMonoid(), SchreyerFrame::level(), Monoid::make_one(), SchreyerFrame::maxLevel(), SchreyerFrame::monoid(), ResSchreyerOrder::mTieBreaker, ResSchreyerOrder::mTotalMonom, Monoid::n_vars(), SchreyerFrame::schreyerOrder(), and ResMonoidDense::to_expvector().
Referenced by F4ResComputation::get_free().