Macaulay2 Engine: ResF4toM2Interface::to_M2_matrix
to_M2_matrix()
Matrix * ResF4toM2Interface::to_M2_matrix (SchreyerFrame & C, int lev, const FreeModule * tar, const FreeModule * src) static
Definition at line 221 of file res-f4-m2-interface.cpp.
{
  if (lev < 0 or lev > C.maxLevel())
    {
      MatrixConstructor zero(tar, src);
      return zero.to_matrix();
    }
  auto& thislevel = C.level(lev);
  MatrixConstructor result(tar, src);
  int j = 0;
  for (auto i = thislevel.cbegin(); i != thislevel.cend(); ++i, ++j)
    {
      vec v = to_M2_vec(C.ring(), i->mSyzygy, tar);
      result.set_column(j, v);
    }
  return result.to_matrix();
}
References SchreyerFrame::level(), SchreyerFrame::maxLevel(), SchreyerFrame::ring(), MatrixConstructor::set_column(), to_M2_vec(), MatrixConstructor::to_matrix(), and zero.
Referenced by F4ResComputation::get_matrix().