Macaulay2 Engine: ResF4toM2Interface::to_M2_MutableMatrix
to_M2_MutableMatrix() [1/2]
MutableMatrix * ResF4toM2Interface::to_M2_MutableMatrix (SchreyerFrame & C, const Ring * K, int lev, int degree) static
Definition at line 321 of file res-f4-m2-interface.cpp.
 {
   // The ring K should be the coefficient ring of the poly ring of C,
   // OR: if the coefficient ring is QQ, then it can be RR, or a finite field.
   // Now we loop through the elements of degree 'degree' at level 'lev'
   auto& thislevel = C.level(lev);
   int n = 0;
   for (auto p = thislevel.begin(); p != thislevel.end(); ++p)
     {
       if (p->mDegree == degree) n++;
     }
   auto& prevlevel = C.level(lev - 1);
   int* newcomps = new int[prevlevel.size()];
   int nextcomp = 0;
   for (int i = 0; i < prevlevel.size(); i++)
     if (prevlevel[i].mDegree == degree)
       newcomps[i] = nextcomp++;
     else
       newcomps[i] = -1;
   // create the mutable matrix
   MutableMatrix* result = MutableMatrix::zero_matrix(K, nextcomp, n, true);
   // Now loop through the elements at thislevel,
   // and for each, loop through the terms of mSyzygy.
   // if the component x satisfies newcomps[x] >= 0, then place
   // this coeff into the mutable matrix.
   int col = 0;
   for (auto p = thislevel.begin(); p != thislevel.end(); ++p)
     {
       if (p->mDegree != degree) continue;
       auto& f = p->mSyzygy;
       auto end = ResPolynomialIterator(C.ring(), f, 1);
       auto i = ResPolynomialIterator(C.ring(), f);
       for (; i != end; ++i)
         {
           long comp = C.monoid().get_component(i.monomial());
           if (newcomps[comp] >= 0)
             {
               ring_elem a = C.ring().vectorArithmetic().ringElemFromElementArray(
                   f.coeffs, i.coefficient_index());
               result->set_entry(newcomps[comp], col, a);
             }
         }
       ++col;
     }
   delete[] newcomps;
   return result;
 }
References end(), ResMonoidDense::get_component(), SchreyerFrame::level(), SchreyerFrame::monoid(), p, SchreyerFrame::ring(), VectorArithmetic::ringElemFromElementArray(), MutableMatrix::set_entry(), ResPolyRing::vectorArithmetic(), and MutableMatrix::zero_matrix().