Macaulay2 Engine: ResF4toM2Interface::to_M2_vec
to_M2_vec()
vec ResF4toM2Interface::to_M2_vec (const ResPolyRing & R, const ResPolynomial & f, const FreeModule * F) static
Definition at line 240 of file res-f4-m2-interface.cpp.
 {
   const PolynomialRing* origR = F->get_ring()->cast_to_PolynomialRing();
   const Monoid* M = origR->getMonoid();
   monomial m1 = M->make_one();
   Nterm** comps = newarray(Nterm*, F->rank());
   Nterm** last = newarray(Nterm*, F->rank());
   for (int i = 0; i < F->rank(); i++)
     {
       comps[i] = 0;
       last[i] = 0;
     }
   int* exp = new int[M->n_vars()];
   const res_monomial_word* w = f.monoms.data();
   for (int i = 0; i < f.len; i++)
     {
       component_index comp;
       R.monoid().to_expvector(w, exp, comp);
       w = w + R.monoid().monomial_size(w);
       M->from_expvector(exp, m1);
       ring_elem a =
           R.resGausser().to_ring_elem(origR->getCoefficientRing(), f.coeffs, i);
       Nterm* g = origR->make_flat_term(a, m1);
       g->next = 0;
       if (last[comp] == 0)
         {
           comps[comp] = g;
           last[comp] = g;
         }
       else
         {
           last[comp]->next = g;
           last[comp] = g;
         }
     }
   vec result = 0;
   for (int i = 0; i < F->rank(); i++)
     {
       if (comps[i] != 0)
         {
           vec v = origR->make_vec(i, comps[i]);
           origR->add_vec_to(result, v);
           comps[i] = 0;
           last[i] = 0;
         }
     }
   delete[] exp;
   return result;
 }
References Ring::add_vec_to(), Ring::cast_to_PolynomialRing(), ResPolynomial::coeffs, mpfr::exp(), Monoid::from_expvector(), FreeModule::get_ring(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), ResPolynomial::len, PolynomialRing::make_flat_term(), Monoid::make_one(), Ring::make_vec(), ResPolyRing::monoid(), ResMonoidDense::monomial_size(), ResPolynomial::monoms, Monoid::n_vars(), newarray, Nterm::next, FreeModule::rank(), ResPolyRing::resGausser(), ResMonoidDense::to_expvector(), and ResGausser::to_ring_elem().
Referenced by to_M2_matrix().