Macaulay2 Engine: ResF4toM2Interface::to_M2_MutableMatrix
to_M2_MutableMatrix() [2/2]
MutableMatrix * ResF4toM2Interface::to_M2_MutableMatrix (SchreyerFrame & C, const Ring * R, int lev) static
Definition at line 387 of file res-f4-m2-interface.cpp.
 {
   // Ring will be R, which should be a polynomial ring with the same monoid as
   // ring of C.
   const PolynomialRing* RP = R->cast_to_PolynomialRing();
   const Monoid* M = RP->getMonoid();
   const Ring* K = RP->getCoefficientRing();
   if (lev <= 0 or lev > C.maxLevel())
     {
       return MutableMatrix::zero_matrix(
           R,
           0,  // TODO: set this correctly?
           0,  // TODO: set this correctly?  i.e. one of these might be in range,
           // so getting the rank correct might be good.
           true);
     }
   auto& thislevel = C.level(lev);
   int ncols = static_cast<int>(thislevel.size());
   int nrows = static_cast<int>(C.level(lev - 1).size());
   // create the mutable matrix
   MutableMatrix* result = MutableMatrix::zero_matrix(R, nrows, ncols, true);
   //  Nterm **comps = newarray(Nterm *, nrows);
   Nterm** comps = newarray(Nterm*, nrows);
   Nterm** last = newarray(Nterm*, nrows);
   monomial m1 = M->make_one();
   // FIXME: is exp a monomial or exponent vector?
   int* exp = new int[M->n_vars() + 1];
   int j = 0;
   for (auto j1 = thislevel.cbegin(); j1 != thislevel.cend(); ++j1, ++j)
     {
       // Now we create the polynomials for column j
       // into 'comps', 'last'.
       const ResPolynomial& f = (*j1).mSyzygy;
       for (int i = 0; i < nrows; i++)
         {
           comps[i] = nullptr;
           last[i] = nullptr;  // used to easily place monomials in the correct
                               // bin, at the end of the polynomials.
         }
       const res_monomial_word* w = f.monoms.data();
       for (int i = 0; i < f.len; i++)
         {
           component_index comp;
           C.ring().monoid().to_expvector(w, exp, comp);
           w = w + C.ring().monoid().monomial_size(w);
           M->from_expvector(exp, m1);
           ring_elem a = C.gausser().to_ring_elem(K, f.coeffs, i);
           Nterm* g = RP->make_flat_term(a, m1);
           if (g == nullptr) continue;
           g->next = nullptr;
           if (last[comp] == nullptr)
             {
               comps[comp] = g;
               last[comp] = g;
             }
           else
             {
               last[comp]->next = g;
               last[comp] = g;
             }
         }
       // Now we have run through the entire vector, so put it into result
       for (int r = 0; r < nrows; r++) result->set_entry(r, j, comps[r]);
     }
   delete[] exp;
   freemem(comps);
   freemem(last);
   return result;
 }
References Ring::cast_to_PolynomialRing(), ResPolynomial::coeffs, mpfr::exp(), freemem(), Monoid::from_expvector(), SchreyerFrame::gausser(), PolynomialRing::getCoefficientRing(), PolynomialRing::getMonoid(), ResPolynomial::len, SchreyerFrame::level(), PolynomialRing::make_flat_term(), Monoid::make_one(), SchreyerFrame::maxLevel(), ResPolyRing::monoid(), ResMonoidDense::monomial_size(), ResPolynomial::monoms, Monoid::n_vars(), newarray, Nterm::next, SchreyerFrame::ring(), MutableMatrix::set_entry(), ResMonoidDense::to_expvector(), ResGausser::to_ring_elem(), and MutableMatrix::zero_matrix().
Referenced by F4ResComputation::get_matrix(), and F4ResComputation::get_mutable_matrix().