Macaulay2 Engine: MonomialCollectionFixedSize::findOrInsert
findOrInsert()
std::pair< const int *, bool > MonomialCollectionFixedSize::findOrInsert (const int * monom) inline
Definition at line 210 of file monomial-sets.hpp.
  {
    std::pair<int*, int*> mon { mMonomialMemory.alloc(elementSize()) };
    std::copy(monom, monom + elementSize(), mon.first);
    assert(mon.second - mon.first >= elementSize());
    return findOrInsertTopInternedMonomial(mon.first);
  }
References MonomialMemorySpace::alloc(), elementSize(), findOrInsertTopInternedMonomial(), and mMonomialMemory.