Macaulay2 Engine: MonomialCollectionFixedSize::findOrInsertTopInternedMonomial
findOrInsertTopInternedMonomial()
std::pair<const int*, bool> MonomialCollectionFixedSize::findOrInsertTopInternedMonomial (int *& monom) inline
Definition at line 220 of file monomial-sets.hpp.
   {
     // if the monomial is found in the set, then monom is popped
     auto result = mSet.findOrInsert(monom);
     if (not result.second) // i.e. monomial was not needed.
       mMonomialMemory.popLastAlloc(monom);
     return result;
   }
References MonomialSetFixedSize::findOrInsert(), mMonomialMemory, mSet, and MonomialMemorySpace::popLastAlloc().
Referenced by findOrInsert().