Macaulay2 Engine: QuickSorter::sort2
sort2()
template<typename Sorter > void QuickSorter< Sorter >::sort2 (long lo, long hi) private
Definition at line 104 of file monsort.hpp.
 {
   value pivot;
   value t; /* temporary variable for swap */
   if (end > begin)
     {
       long l = begin + 1;
       long r = end;
       swap(elems[begin],
            elems[pivot_index()],
            t); /*** choose arbitrary pivot ***/
       pivot = elems[begin];
       while (l < r)
         {
           if (M->compare(elems[l], pivot) <= 0)
             {
               l++;
             }
           else
             {
               while (l < --r &&
                      M->compare(elems[r], pivot) >=
                          0) /*** skip superfluous swaps ***/
                 ;
               swap(elems[l], elems[r], t);
             }
         }
       l--;
       swap(elems[begin], elems[l], t);
       sort2(begin, l);
       sort2(r, end);
     }
 }
References begin(), end(), pivot_index, and swap.
Referenced by QuickSorter< Sorter >::sort().