Macaulay2 Engine: QuickSorter::sort
sort() [2/2]
template<typename Sorter > void QuickSorter< Sorter >::sort (Sorter * M0, value * elems0, long len0) static
Definition at line 350 of file monsort.hpp.
{
  QuickSorter S(M0, elems0, len0);
  int typ = 1;
  clock_t begin_time = clock();
  switch (typ)
    {
      case 1:
        S.sort2(0, len0);
        break;
      case 2:
        S.sort2depth(0, len0, 1);
        break;
      case 3:
        S.sortC();
        break;
      case 4:
        S.sortD();
        break;
    }
  clock_t end_time = clock();
  long double nsecs = end_time - begin_time;
  nsecs /= CLOCKS_PER_SEC;
  if (M2_gbTrace >= 4)
    fprintf(
        stderr, "sort: len %ld depth %ld time %Lf\n", len0, S.maxdepth, nsecs);
}
References M2_gbTrace, QuickSorter< Sorter >::maxdepth, QuickSorter< Sorter >::sort2(), QuickSorter< Sorter >::sort2depth(), QuickSorter< Sorter >::sortC(), and QuickSorter< Sorter >::sortD().