Macaulay2 Engine: QuickSorter::sort2depth
sort2depth()
template<typename Sorter > void QuickSorter< Sorter >::sort2depth (long lo, long hi, long depth) private
Definition at line 143 of file monsort.hpp.
{
  value pivot;
  value t; /* temporary variable for swap */
  if (depth > maxdepth) maxdepth = depth;
  if (end > begin)
    {
      long l = begin + 1;
      long r = end;
      swap(elems[begin],
           elems[pivot_index()],
           t); /*** choose arbitrary pivot ***/
      pivot = elems[begin];
      while (l < r)
        {
          if (M->compare(elems[l], pivot) <= 0)
            {
              l++;
            }
          else
            {
              while (l < --r &&
                     M->compare(elems[r], pivot) >=
                         0) /*** skip superfluous swaps ***/
                ;
              swap(elems[l], elems[r], t);
            }
        }
      l--;
      swap(elems[begin], elems[l], t);
      sort2depth(begin, l, depth + 1);
      sort2depth(r, end, depth + 1);
    }
}
References begin(), end(), pivot_index, and swap.
Referenced by QuickSorter< Sorter >::sort().