Macaulay2 Engine: fill_from_lapack_upper
fill_from_lapack_upper() [1/2]
void fill_from_lapack_upper (double * lapack_numbers, int numrows, int numcols, DMat< M2::ARingCC > & upper)
Definition at line 113 of file lapack.cpp.
 {
   // At this point, upper should be a zero matrix.
   std::cout << "entering fill_from_lapack_upper " << std::endl;
   assert(MatrixOps::isZero(upper));
 #if 0
   for (int i=0; i< numrows * numcols; ++i)
     std::cout << lapack_numbers[i] << " ";
   std::cout << std::endl;
 #endif
   auto U = upper.rowMajorArray();
   for (size_t c = 0; c < upper.numColumns(); c++)
     {
       std::cout << "doing col " << c << std::endl;
       auto U1 = U;
       for (size_t r = 0; r <= c; r++)
         {
           std::cout << "doing row " << r << std::endl;
           if (r >= upper.numRows()) break;
           double re = lapack_numbers[2 * r];
           double im = lapack_numbers[2 * r + 1];
           upper.ring().set_from_doubles(*U1, re, im);
           U1 += upper.numColumns();
         }
       U++;  // change to next column
       lapack_numbers += 2 * numrows;
     }
   std::cout << "done!" << std::endl;
 }
References MatrixOps::isZero(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::ring(), and DMat< ACoeffRing >::rowMajorArray().