Macaulay2 Engine: fill_from_lapack_upper
fill_from_lapack_upper() [2/2]
void fill_from_lapack_upper (double * lapack_numbers, int numrows, int numcols, DMat< M2::ARingRR > & upper)
Definition at line 79 of file lapack.cpp.
 {
   // At this point, upper should be a zero matrix.
   assert(MatrixOps::isZero(upper));
 #if 0
   for (int i=0; i< numrows * numcols; ++i)
     std::cout << lapack_numbers[i] << " ";
   std::cout << std::endl;
 #endif
   auto U = upper.rowMajorArray();
   for (size_t c = 0; c < upper.numColumns(); c++)
     {
       auto U1 = U;
       for (size_t r = 0; r <= c; r++)
         {
           if (r >= upper.numRows()) break;
           *U1 = lapack_numbers[r];
           U1 += upper.numColumns();
         }
       U++;  // change to next column
       lapack_numbers += numrows;
     }
 }
References MatrixOps::isZero(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and DMat< ACoeffRing >::rowMajorArray().
Referenced by Lapack::QR().