Macaulay2 Engine: fill_lower_and_upper
fill_lower_and_upper() [2/4]
void fill_lower_and_upper (double * lapack_numbers, DMat< M2::ARingCCC > & lower, DMat< M2::ARingCCC > & upper)
Definition at line 198 of file lapack.cpp.
 {
   // At this point, lower and upper should be zero matrices.
   assert(MatrixOps::isZero(lower));
   assert(MatrixOps::isZero(upper));
   auto L = lower.rowMajorArray();
   auto U = upper.rowMajorArray();
   for (size_t c = 0; c < upper.numColumns(); c++)
     {
       auto U1 = U;
       for (size_t r = 0; r <= c; r++)
         {
           if (r >= upper.numRows()) break;
           double re = *lapack_numbers++;
           double im = *lapack_numbers++;
           upper.ring().set_from_doubles(*U1, re, im);
           U1 += upper.numColumns();
         }
       U++;  // change to next column
       if (c < lower.numColumns())
         {
           lower.ring().set_from_long(*L, 1);  // diagonal entry of L should be 1
           L += lower.numColumns();  // pointing to entry right below diagonal
           auto L1 = L;  // will increment by lower.numRows() each loop here
           for (size_t r = c + 1; r < lower.numRows(); r++)
             {
               double re = *lapack_numbers++;
               double im = *lapack_numbers++;
               lower.ring().set_from_doubles(*L1, re, im);
               L1 += lower.numColumns();  // to place next entry.
             }
           L++;  // change to next column
         }
     }
 }
References MatrixOps::isZero(), DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), DMat< ACoeffRing >::ring(), and DMat< ACoeffRing >::rowMajorArray().