Macaulay2 Engine: make_lapack_array
make_lapack_array() [1/4]
double* make_lapack_array (const DMat< M2::ARingCC > & mat)
Definition at line 1765 of file lapack.cpp.
 {
   size_t len = mat.numRows() * mat.numColumns();
   double *result = newarray_atomic(double, 2 * len);
   double *p = result;
   for (size_t c = 0; c < mat.numColumns(); c++)
     {
       auto end = mat.columnEnd(c);
       for (auto a = mat.columnBegin(c); a != end; ++a)
         {
           *p++ = (*a).re;
           *p++ = (*a).im;
         }
     }
   return result;
 }
References DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::columnEnd(), newarray_atomic, DMat< ACoeffRing >::numColumns(), DMat< ACoeffRing >::numRows(), and p.