Macaulay2 Engine: fill_from_lapack_array
fill_from_lapack_array() [3/4]
void fill_from_lapack_array (const double * lapack_array, DMat< M2::ARingRR > & result)
Definition at line 1783 of file lapack.cpp.
 {
   const double *p = lapack_array;
   for (size_t c = 0; c < result.numColumns(); c++)
     {
       auto end = result.columnEnd(c);
       for (auto a = result.columnBegin(c); a != end; ++a) *a = *p++;
     }
 }
References DMat< ACoeffRing >::columnBegin(), DMat< ACoeffRing >::columnEnd(), end(), DMat< ACoeffRing >::numColumns(), and p.