Macaulay2 Engine: MonomialOrderings::GRevLex
GRevLex() [2/3]
MonomialOrdering * MonomialOrderings::GRevLex (const std::vector< int > & wts, int packing) static
Definition at line 162 of file monomial-ordering.cpp.
 {
   MonomialOrdering *result;
   mon_part p;
   enum MonomialOrdering_type typ;
   const int *wts;
   bool all_one = true;
   for (int i = 0; i < degs.size(); i++)
     if (degs[i] <= 0)
       {
         ERROR("grevlex: expected all degrees to be positive");
         return nullptr;
       }
     else if (degs[i] > 1)
       all_one = false;
   if (all_one)
     {
       if (packing == 2)
         typ = MO_GREVLEX2;
       else if (packing == 4)
         typ = MO_GREVLEX4;
       else
         typ = MO_GREVLEX;
       wts = nullptr;
     }
   else
     {
       if (packing == 2)
         typ = MO_GREVLEX2_WTS;
       else if (packing == 4)
         typ = MO_GREVLEX4_WTS;
       else
         typ = MO_GREVLEX_WTS;
       wts = degs.data();
     }
   p = mo_make(typ, degs.size(), wts);
   result = make_mon_order(1);
   result->array[0] = p;
   return result;
 }
References MonomialOrdering::array, ERROR(), make_mon_order(), MO_GREVLEX, MO_GREVLEX2, MO_GREVLEX2_WTS, MO_GREVLEX4, MO_GREVLEX4_WTS, MO_GREVLEX_WTS, mo_make(), p, and mon_part::wts.