Macaulay2 Engine: MonomialOrderings::Weights
Weights()
MonomialOrdering * MonomialOrderings::Weights (const std::vector< int > & wts) static
Definition at line 137 of file monomial-ordering.cpp.
 {
   mon_part p = mo_make(MO_WEIGHTS, wts.size(), wts.data());
   MonomialOrdering *result = make_mon_order(1);
   result->array[0] = p;
   return result;
 }
References MonomialOrdering::array, make_mon_order(), mo_make(), MO_WEIGHTS, p, and mon_part::wts.
Referenced by degreeMonoid().