Macaulay2 Engine: MonomialOrderings::join
join()
MonomialOrdering * MonomialOrderings::join (const std::vector< MonomialOrdering * > & M) static
Definition at line 206 of file monomial-ordering.cpp.
 {
   MonomialOrdering *result;
   const MonomialOrdering *mo;
   int i, j, sum, next;
   int nvars_so_far = 0;
   sum = 0;
   for (i = 0; i < M.size(); i++)
     {
       mo = M[i];
       for (j = 0; j < mo->len; j++)
         if (is_good(mo->array[j])) sum++;
     }
   result = make_mon_order(sum);
   next = 0;
   for (i = 0; i < M.size(); i++)
     {
       mo = M[i];
       for (j = 0; j < mo->len; j++)
         {
           mon_part p = mo->array[j];
           if (!is_good(p)) continue;
           if (p->type != MO_WEIGHTS)
             nvars_so_far += p->nvars;
           else
             {
               /* Shift the weights over by nvars_so_far */
               mon_part q = mo_make(MO_WEIGHTS, nvars_so_far + p->nvars, NULL);
               q->wts = getmemvectortype(int, q->nvars);
               for (j = 0; j < nvars_so_far; j++) q->wts[j] = 0;
               for (; j < q->nvars; j++) q->wts[j] = p->wts[j - nvars_so_far];
               p = q;
             }
           result->array[next++] = p;
         }
     }
   return result;
 }
References MonomialOrdering::array, getmemvectortype, is_good(), MonomialOrdering::len, make_mon_order(), mo_make(), MO_WEIGHTS, p, and mpfr::sum().
Referenced by degreeMonoid(), and TEST().