Macaulay2 Engine: MonomialOrderings::product
product()
MonomialOrdering * MonomialOrderings::product (const std::vector< MonomialOrdering * > & M) static
Definition at line 248 of file monomial-ordering.cpp.
{
  MonomialOrdering *result;
  int i, j, sum, next, offset;
  sum = 0;
  for (i = 0; i < M.size(); i++) sum += M[i]->len;
  result = make_mon_order(sum);
  next = 0;
  offset = 0;
  for (i = 0; i < M.size(); i++)
    {
      int nvars = rawNumberOfVariables(M[i]);
      MonomialOrdering *mo = M2_mo_offset(M[i], offset);
      for (j = 0; j < mo->len; j++) result->array[next++] = mo->array[j];
      offset += nvars;
    }
  return result;
}
References MonomialOrdering::array, MonomialOrdering::len, M2_mo_offset(), make_mon_order(), and rawNumberOfVariables().