Macaulay2 Engine: varpower_monideal
varpower_monideal()
static MonomialIdeal* varpower_monideal (const PolynomialRing * R, const M2_arrayint top, const_varpower vp) static
Definition at line 803 of file monideal.cpp.
 {
   // If m is a varpower monomial, xi1^a1 ... xin^an, create the monomial ideal
   // (xi1^(top[i1]+1-a1), ..., xin^(top[in]+1-an))
   MonomialIdeal *result = new MonomialIdeal(R);
   for (index_varpower i = vp; i.valid(); ++i)
     {
       Bag *b = new Bag();
       varpower::var(
           i.var(), top->array[i.var()] + 1 - i.exponent(), b->monom());
       result->insert(b);
     }
   return result;
 }
References MonomialIdeal::insert(), int_bag::monom(), ExponentListIterator< E, L >::valid(), and ExponentList< E, L >::var().
Referenced by MonomialIdeal::alexander_dual().