Macaulay2 Engine: borel1
borel1()
static void borel1 (gc_vector< Bag * > & result, exponents_t m, int loc, int nvars) static
Definition at line 918 of file monideal.cpp.
{
  if (loc == 0)
    {
      Bag *b = new Bag();
      varpower::from_expvector(nvars, m, b->monom());
      result.push_back(b);
    }
  else
    {
      int a = m[loc];
      for (int i = 0; i <= a; i++)
        {
          borel1(result, m, loc - 1, nvars);
          m[loc]--;
          m[loc - 1]++;
        }
      m[loc] += a + 1;
      m[loc - 1] -= a + 1;
    }
}
References borel1(), ExponentList< E, L >::from_expvector(), and int_bag::monom().
Referenced by MonomialIdeal::borel(), and borel1().