name: Build and deploy engine documentation
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "Macaulay2/M2"
          ref: "development"
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y -n ppa:macaulay2/macaulay2
          sudo apt-get update
          sudo apt-get install -y doxygen libtool-bin libtbb-dev \
               libeigen3-dev libboost-dev libboost-regex-dev \
               libflint-dev libmathicgb-dev libmemtailor-dev libgc-dev \
               libgdbm-dev libflint-arb-dev
      - name: Configure
        run: |
          make -C M2
          cd M2/BUILD && ../configure --with-system-gc --with-system-memtailor \
              --with-system-mathic --with-system-mathicgb
      - name: Build engine documentation
        run: |
          make -C M2/BUILD/Macaulay2/util echoout
          make -C M2/BUILD/Macaulay2/c scc1
          make -C M2/BUILD/Macaulay2/d engine-exports.h.tmp
          make -C M2/BUILD/Macaulay2/e tinydoc
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: M2/BUILD/Macaulay2/e/doc/tinydoc
