Macaulay2 Engine: Table_toArray
Table_toArray()
const void** Table_toArray (Table_T * table, void * end)
Definition at line 128 of file table.c.
 {
   int i, j = 0;
   const void **array;
   struct binding *p;
   assert(table);
   array = (const void **)getmem((2 * table->length + 1) * sizeof(*array));
   for (i = 0; i < table->size; i++)
     for (p = table->buckets[i]; p; p = p->link)
       {
         array[j++] = (const void *)p->key;
         array[j++] = p->value;
       }
   array[j] = end;
   return array;
 }
References end(), getmem(), and p.
Referenced by exponent_table_to_array().