Macaulay2 Engine: Table_new
Table_new()
Table_T* Table_new (int hint, int cmpconst void *x, const void *y, unsigned hashconst void *key)
Definition at line 24 of file table.c.
 {
   T *table;
   int i;
   static int primes[] = {
       509, 509, 1021, 2053, 4093, 8191, 16381, 32771, 65521, INT_MAX};
   assert(hint >= 0);
   for (i = 1; primes[i] < hint; i++)
     ;
   table =
       (T *)getmem(sizeof(*table) + primes[i - 1] * sizeof(table->buckets[0]));
   table->size = primes[i - 1];
   table->cmp = cmp ? cmp : cmpatom;
   table->hash = hash ? hash : hashatom;
   table->buckets = (struct binding **)(table + 1);
   for (i = 0; i < table->size; i++) table->buckets[i] = NULL;
   table->length = 0;
   table->timestamp = 0;
   return table;
 }
References cmpatom(), getmem(), hashatom(), and T.
Referenced by exponent_table_new().