Macaulay2 Engine: newf4::GBF4Computation::initializeWithMatrix
initializeWithMatrix()
void newf4::GBF4Computation::initializeWithMatrix (const Matrix * M)
Definition at line 26 of file GBF4Computation.cpp.
 {
    PolynomialListStreamCollector S(mVectorArithmetic.ring()->characteristic(),
                                    mVariableWeights.size(),  // TODO: is this correct?
                                    1,  // TODO: is this correct??
                                    mInput);
    matrixToStream(M,S);
 }
References Ring::characteristic(), matrixToStream(), mInput, mVariableWeights, mVectorArithmetic, and VectorArithmetic::ring().