Macaulay2 Engine: newf4::GBF4Computation::showInput
showInput()
void newf4::GBF4Computation::showInput () const
Definition at line 50 of file GBF4Computation.cpp.
 {
    const Matrix* M = toMatrix(mFreeModule, mInput);
    buffer o;
    M->text_out(o);
    std::cout << "--- Input Polynomials ---" << std::endl;
    std::cout << o.str() << std::endl;
 }
References mFreeModule, mInput, buffer::str(), Matrix::text_out(), and newf4::toMatrix().