Macaulay2 Engine: M2_ArrayString_to_stdvector
M2_ArrayString_to_stdvector() [2/2]
void M2_ArrayString_to_stdvector (M2_ArrayString strs, std::vector< std::string > & result) inline
Definition at line 25 of file util.hpp.
 {
   result.reserve(strs->len);
   for (auto i = 0; i < strs->len; i++)
     result.push_back(string_M2_to_std(strs->array[i]));
 }
References string_M2_to_std().
Referenced by M2_ArrayString_to_stdvector(), rawARingTower1(), rawARingTower2(), rawMonoid(), and rawRingM2FreeAlgebra().