Macaulay2 Engine: rawMutableMatrixFillRandom
rawMutableMatrixFillRandom()
void rawMutableMatrixFillRandom (MutableMatrix * M, long nelems)
Definition at line 113 of file mutable-matrix.cpp.
 {
   int nrows = static_cast<int>(M->n_rows());
   int ncols = static_cast<int>(M->n_cols());
   const Ring *R = M->get_ring();
   for (long i = 0; i < nelems; i++)
     {
       int r = rawRandomInt(nrows);
       int c = rawRandomInt(ncols);
       ring_elem a = R->random();
       if (!R->is_zero(a)) M->set_entry(r, c, R->random());
     }
 }
References MutableMatrix::get_ring(), Ring::is_zero(), MutableMatrix::n_cols(), MutableMatrix::n_rows(), Ring::random(), rawRandomInt(), and MutableMatrix::set_entry().