Macaulay2 Engine: rawMatrixClean
rawMatrixClean()
const Matrix* rawMatrixClean (gmp_RR epsilon, const Matrix * M)
Definition at line 1026 of file mutable-matrix.cpp.
 {
   try
     {
       if (M->get_ring()->get_precision() == 0)
         {
           ERROR("expected ring over an RR or CC");
           return 0;
         }
       return M->clean(epsilon);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References Matrix::clean(), ERROR(), Ring::get_precision(), and Matrix::get_ring().