Macaulay2 Engine: rawLinAlgMinPoly
rawLinAlgMinPoly()
engine_RawRingElementArrayOrNull rawLinAlgMinPoly (MutableMatrix * A)
Definition at line 977 of file mutable-matrix.cpp.
 {
 #if 1
 #if 0
   const Ring *R = A->get_ring();
   typedef DMat<M2::ARingZZpFFPACK> DMatZZp;
   MutableMat<DMatZZp> *B = A->cast_to_MutableMat<DMatZZp>();
   if (B == 0)
     {
       ERROR("expected a dense mutable matrix over the ffpack finite field");
       return 0;
     }
   typedef M2::ARingZZpFFPACK::ElementType Element;
   typedef std::vector<Element> Polynomial;
   Element *elemsA = B->get_Mat()->array();
   size_t n = B->n_rows();
   Polynomial minpoly(n);
   // the following are uninitialized!  This is scratch space for use in the
   // algorithm, apparently...
   Element *X = new Element[n * (n + 1)];
   size_t *P = new size_t[n];
   // this is in ffpack 2.3 but not in 2.2, and it might be the wrong name now, was MinPoly before
   FFPACK::Protected::Hybrid_KGF_LUK_MinPoly(
        B->get_Mat()->ring().field(), minpoly, n, elemsA, n, X, n, P);
   delete[] P;
   delete[] X;
   for (size_t i = 0; i < minpoly.size(); i++) std::cout << minpoly[i] << " ";
   std::cout << std::endl;
   return convertRingelemsToArray(R, minpoly);
 #else
   return nullptr;
 #endif
 #else
   ERROR("not implemented: configure M2 with --enable-ffpack-fflas");
   return 0;
 #endif
 }
References MutableMatrix::cast_to_MutableMat(), convertRingelemsToArray(), ERROR(), MutableMat< Mat >::get_Mat(), MutableMatrix::get_ring(), and MutableMat< Mat >::n_rows().