Macaulay2 Engine: IM2_MutableMatrix_column_swap
IM2_MutableMatrix_column_swap()
M2_bool IM2_MutableMatrix_column_swap (MutableMatrix * M, int i, int j)
Definition at line 235 of file mutable-matrix.cpp.
 {
   if (i < 0 || j < 0 || i >= M->n_cols() || j >= M->n_cols())
     {
       ERROR("column index out of range");
       return 0;
     }
   M->interchange_columns(i, j);
   return 1;
 }
References ERROR(), MutableMatrix::interchange_columns(), and MutableMatrix::n_cols().