Macaulay2 Engine: IM2_MutableMatrix_row_operation
IM2_MutableMatrix_row_operation()
M2_bool IM2_MutableMatrix_row_operation (MutableMatrix * M, int i, const RingElement * r, int j, M2_bool opposite_mult)
Definition at line 248 of file mutable-matrix.cpp.
 {
   const Ring *R = M->get_ring();
   if (R != r->get_ring())
     {
       ERROR("expected same ring");
       return 0;
     }
   if (i < 0 || j < 0 || i >= M->n_rows() || j >= M->n_rows())
     {
       ERROR("row index out of range");
       return 0;
     }
   M->row_op(i, r->get_value(), j);
   return 1;
 }
References ERROR(), RingElement::get_ring(), MutableMatrix::get_ring(), RingElement::get_value(), MutableMatrix::n_rows(), and MutableMatrix::row_op().