Macaulay2 Engine: rawLeastSquares
rawLeastSquares()
M2_bool rawLeastSquares (MutableMatrix * A, MutableMatrix * b, MutableMatrix * x, M2_bool assume_full_rank)
Definition at line 715 of file mutable-matrix.cpp.
 {
   try
     {
       const Ring *R = A->get_ring();
       if (R != b->get_ring() || R != x->get_ring())
         {
           ERROR("expected matrices with same base ring");
           return false;
         }
       if (A->n_rows() != b->n_rows())
         {
           ERROR("expected matrices with the same number of rows");
           return false;
         }
       return A->least_squares(b, x, assume_full_rank);
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return false;
   }
 }
References ERROR(), MutableMatrix::get_ring(), MutableMatrix::least_squares(), MutableMatrix::n_rows(), and x.