Macaulay2 Engine: IM2_MutableMatrix_get_entry
IM2_MutableMatrix_get_entry()
const RingElement* IM2_MutableMatrix_get_entry (const MutableMatrix * M, int r, int c)
Definition at line 179 of file mutable-matrix.cpp.
 {
   if (r < 0 || r >= M->n_rows())
     {
       ERROR("matrix row index %d out of range 0 .. %d", r, M->n_rows() - 1);
       return 0;
     }
   if (c < 0 || c >= M->n_cols())
     {
       ERROR("matrix column index %d out of range 0 .. %d", c, M->n_cols() - 1);
       return 0;
     }
   ring_elem result;
   M->get_entry(r, c, result);
   return RingElement::make_raw(M->get_ring(), result);
 }
References ERROR(), MutableMatrix::get_entry(), MutableMatrix::get_ring(), RingElement::make_raw(), MutableMatrix::n_cols(), and MutableMatrix::n_rows().