Macaulay2 Engine: IM2_MutableMatrix_column_permute
IM2_MutableMatrix_column_permute()
M2_bool IM2_MutableMatrix_column_permute (MutableMatrix * M, int start, M2_arrayint perm)
Definition at line 437 of file mutable-matrix.cpp.
 {
   size_t ncols = M->n_cols();
   if (start < 0 || start + perm->len > ncols)
     {
       ERROR("column indices out of range");
       return false;
     }
   for (int i = 0; i < perm->len; i++)
     {
       int r = start + perm->array[i];
       if (r < 0 || r >= ncols)
         {
           ERROR("column indices out of range");
           return false;
         }
     }
   return M->column_permute(start, perm);
 }
References MutableMatrix::column_permute(), ERROR(), and MutableMatrix::n_cols().