Macaulay2 Engine: IM2_MutableMatrix_column_operation
IM2_MutableMatrix_column_operation()
M2_bool IM2_MutableMatrix_column_operation (MutableMatrix * M, int i, const RingElement * r, int j, M2_bool opposite_mult)
Definition at line 271 of file mutable-matrix.cpp.
 {
   const Ring *R = M->get_ring();
   if (R != r->get_ring())
     {
       ERROR("expected same ring");
       return 0;
     }
   if (i < 0 || j < 0 || i >= M->n_cols() || j >= M->n_cols())
     {
       ERROR("column index out of range");
       return 0;
     }
   M->column_op(i, r->get_value(), j);
   return 1;
 }
References MutableMatrix::column_op(), ERROR(), RingElement::get_ring(), MutableMatrix::get_ring(), RingElement::get_value(), and MutableMatrix::n_cols().