Macaulay2 Engine: rawMutableMatrixClean
rawMutableMatrixClean()
MutableMatrix* rawMutableMatrixClean (gmp_RR epsilon, MutableMatrix * M)
Definition at line 1053 of file mutable-matrix.cpp.
 {
   /* modifies M in place */
   try
     {
       if (M->get_ring()->get_precision() == 0)
         {
           ERROR("expected ring over an RR or CC");
           return 0;
         }
       M->clean(epsilon);
       return M;
   } catch (const exc::engine_error& e)
     {
       ERROR(e.what());
       return nullptr;
   }
 }
References MutableMatrix::clean(), ERROR(), Ring::get_precision(), and MutableMatrix::get_ring().