Macaulay2 Engine: IM2_MutableMatrix_make
IM2_MutableMatrix_make()
MutableMatrix* IM2_MutableMatrix_make (const Ring * R, int nrows, int ncols, M2_bool prefer_dense)
Definition at line 38 of file mutable-matrix.cpp.
 {
   assert(nrows >= 0);
   assert(ncols >= 0);
   size_t nr = static_cast<size_t>(nrows);
   size_t nc = static_cast<size_t>(ncols);
   //  return R->makeMutableMatrix(nr,nc,is_dense);
   return internMutableMatrix(MutableMatrix::zero_matrix(R, nr, nc, is_dense));
 }
References internMutableMatrix(), and MutableMatrix::zero_matrix().
Referenced by F4GB::show_new_rows_matrix(), and F4toM2Interface::to_M2_MutableMatrix().