Macaulay2 Engine: rawLinAlgSolve
rawLinAlgSolve()
MutableMatrix* rawLinAlgSolve (const MutableMatrix * A, const MutableMatrix * B, int * success)
Returns X s.t. AX = B. Assumptions: A has the same number of rows as B. A doesn't have to be invertible or square. If a usage error occurs, NULL is returned and 'success' is set to 0. In all other cases, 'success' is set to 1. If AX=B has no solutions, then NULL is returned, otherwise a matrix X solving AX=B is returned.
Definition at line 836 of file mutable-matrix.cpp.
 {
   try
     {
       *success = 1;
       MutableMatrix *result = A->solveLinear(B);
       if (result != nullptr)
         {
           return internMutableMatrix(result);
         }
       else
         {
           return nullptr;
         }
   } catch (const exc::engine_error& e)
     {
       *success = 0;
       ERROR(e.what());
       return nullptr;
   }
 }
References ERROR(), internMutableMatrix(), and MutableMatrix::solveLinear().