Macaulay2 Engine: IM2_MutableMatrix_column_2by2
IM2_MutableMatrix_column_2by2()
M2_bool IM2_MutableMatrix_column_2by2 (MutableMatrix * M, int c1, int c2, const RingElement * a1, const RingElement * a2, const RingElement * b1, const RingElement * b2, M2_bool opposite_mult)
Definition at line 352 of file mutable-matrix.cpp.
 {
   const Ring *R = M->get_ring();
   if (a1->get_ring() != R || a2->get_ring() != R || b1->get_ring() != R ||
       b2->get_ring() != R)
     {
       ERROR("expected elements in the same ring");
       return 0;
     }
   return M->column2by2(c1,
                        c2,
                        a1->get_value(),
                        a2->get_value(),
                        b1->get_value(),
                        b2->get_value());
 }
References MutableMatrix::column2by2(), ERROR(), RingElement::get_ring(), MutableMatrix::get_ring(), and RingElement::get_value().