Macaulay2 Engine: Word::init
init()
void Word::init (const int * begin, const int * end) inline
Definition at line 20 of file Word.hpp.
 { mBegin = begin; mEnd = end; mSize = end-begin; }
References begin(), end(), mBegin, mEnd, and mSize.
Referenced by NCF4::findDivisor(), FreeAlgebra::from_word(), WordWithData::init(), FreeMonoid::wordFromMonom(), FreeMonoid::wordPrefixFromMonom(), FreeMonoid::wordSuffixFromMonom(), and WordWithData::WordWithData().