Macaulay2 Engine: Word::begin
begin()
const int* Word::begin () const inline
Definition at line 24 of file Word.hpp.
 { return mBegin; }
References mBegin.
Referenced by WordWithData::begin(), concatenatesTo(), NCF4::createOverlapLeadWord(), NCF4::findPreviousReducerPrefix(), NCF4::findPreviousReducerSuffix(), init(), WordTable::insert(), isPatternPrefix(), WordTable::isPrefixOf(), WordTable::isSuffixOf(), MonomHash::operator()(), MonomHashEqual::operator()(), operator<<(), WordTable::overlaps(), prefix(), NCF4::preRowsFromOverlap(), WordTable::subwordPosition(), WordTable::subwordPositions(), suffix(), TEST(), FreeMonoid::wordProductAsMonom(), and FreeMonoid::wordProductAsWord().