Macaulay2 Engine: Word::size
size()
int Word::size () const inline
Definition at line 26 of file Word.hpp.
 { return mSize; }
References mSize.
Referenced by FreeMonoid::compare(), concatenatesTo(), NCF4::createOverlapLeadWord(), NCF4::findDivisor(), NCF4::findPreviousReducerPrefix(), NCF4::findPreviousReducerSuffix(), WordTable::insert(), isPatternPrefix(), WordTable::isPrefixOf(), WordTable::isSuffixOf(), operator<<(), NCF4::overlapHeft(), NCGroebner::overlapHeft(), WordTable::overlaps(), NCGroebner::overlapWordLength(), NCF4::preRowsFromOverlap(), WordWithData::size(), SuffixTree::splitArc(), WordTable::subwordPosition(), WordTable::subwordPositions(), SuffixTree::subwords(), FreeMonoid::wordProductAsMonom(), and FreeMonoid::wordProductAsWord().