Macaulay2 Engine: ntl_LLL
ntl_LLL()
bool ntl_LLL (MutableMatrix * M, MutableMatrix * U, long numer, long denom, int strategy)
Definition at line 69 of file ntl-interface.cpp.
 {
   int nrows = static_cast<int>(M->n_rows());
   int ncols = static_cast<int>(M->n_cols());
   NTL::ZZ d;
   // Note that the LLL routines all return the rank, but we ignore this return
   // value.
   double delta = static_cast<double>(numer) / static_cast<double>(denom);
   if (M2_gbTrace >= 10) printf("LLL: using strategy %d\n", strategy);
   NTL::mat_ZZ *A = mutableMatrix_to_NTL_mat_ZZ(M);
   NTL::mat_ZZ *V = (U ? mutableMatrix_to_NTL_mat_ZZ(U) : 0);
   switch (strategy)
     {
       case 2:
         if (!V)
           LLL(d, *A, numer, denom);
         else
           LLL(d, *A, *V, numer, denom);
         break;
       case useNTL + GS + useLLL + FP:
         if (!V)
           LLL_FP(*A, delta);
         else
           LLL_FP(*A, *V, delta);
         break;
       case useNTL + GS + useLLL + QP:
       case useNTL + GS + useLLL + QP1:
         if (!V)
           LLL_QP(*A, delta);
         else
           LLL_QP(*A, *V, delta);
         break;
       case useNTL + GS + useLLL + XD:
         if (!V)
           LLL_XD(*A, delta);
         else
           LLL_XD(*A, *V, delta);
         break;
       case useNTL + GS + useLLL + useRR:
         if (!V)
           LLL_RR(*A, delta);
         else
           LLL_RR(*A, *V, delta);
         break;
       case useNTL + GS + useBKZ + FP:
         if (!V)
           BKZ_FP(*A, delta);
         else
           BKZ_FP(*A, *V, delta);
         break;
       case useNTL + GS + useBKZ + QP:
         if (!V)
           BKZ_QP(*A, delta);
         else
           BKZ_QP(*A, *V, delta);
         break;
       case useNTL + GS + useBKZ + QP1:
         if (!V)
           BKZ_QP1(*A, delta);
         else
           BKZ_QP1(*A, *V, delta);
         break;
       case useNTL + GS + useBKZ + XD:
         if (!V)
           BKZ_XD(*A, delta);
         else
           BKZ_XD(*A, *V, delta);
         break;
       case useNTL + GS + useBKZ + useRR:
         if (!V)
           BKZ_RR(*A, delta);
         else
           BKZ_RR(*A, *V, delta);
         break;
       case useNTL + Givens + useLLL + FP:
         if (!V)
           G_LLL_FP(*A, delta);
         else
           G_LLL_FP(*A, *V, delta);
         break;
       case useNTL + Givens + useLLL + QP:
       case useNTL + Givens + useLLL + QP1:
         if (!V)
           G_LLL_QP(*A, delta);
         else
           G_LLL_QP(*A, *V, delta);
         break;
       case useNTL + Givens + useLLL + XD:
         if (!V)
           G_LLL_XD(*A, delta);
         else
           G_LLL_XD(*A, *V, delta);
         break;
       case useNTL + Givens + useLLL + useRR:
         if (!V)
           G_LLL_RR(*A, delta);
         else
           G_LLL_RR(*A, *V, delta);
         break;
       case useNTL + Givens + useBKZ + FP:
         if (!V)
           G_BKZ_FP(*A, delta);
         else
           G_BKZ_FP(*A, *V, delta);
         break;
       case useNTL + Givens + useBKZ + QP:
         if (!V)
           G_BKZ_QP(*A, delta);
         else
           G_BKZ_QP(*A, *V, delta);
         break;
       case useNTL + Givens + useBKZ + QP1:
         if (!V)
           G_BKZ_QP1(*A, delta);
         else
           G_BKZ_QP1(*A, *V, delta);
         break;
       case useNTL + Givens + useBKZ + XD:
         if (!V)
           G_BKZ_XD(*A, delta);
         else
           G_BKZ_XD(*A, *V, delta);
         break;
       case useNTL + Givens + useBKZ + useRR:
         if (!V)
           G_BKZ_RR(*A, delta);
         else
           G_BKZ_RR(*A, *V, delta);
         break;
       default:
         delete A;
         if (V) delete V;
         ERROR("Strategy option to LLL not understood");
         return false;
     }
   /* Put this back into M */
   mpz_t a;
   mpz_init(a);
   for (int j = 0; j < ncols; j++)
     for (int i = 0; i < nrows; i++)
       {
         mat_ZZ_get_entry(A, j, i, a);
         ring_elem b = globalZZ->from_int(a);
         M->set_entry(i, j, b);
       }
   if (U)
     {
       for (int j = 0; j < ncols; j++)
         for (int i = 0; i < ncols; i++)
           {
             mat_ZZ_get_entry(V, j, i, a);
             ring_elem b = globalZZ->from_int(a);
             U->set_entry(i, j, b);
           }
     }
   mpz_clear(a);
   delete A;
   if (V) delete V;
   return true;
 }
References ERROR(), FP, RingZZ::from_int(), Givens, globalZZ, GS, M2_gbTrace, mat_ZZ_get_entry(), mutableMatrix_to_NTL_mat_ZZ(), MutableMatrix::n_cols(), MutableMatrix::n_rows(), QP, QP1, MutableMatrix::set_entry(), useBKZ, useLLL, useNTL, useRR, and XD.
Referenced by rawLLL().