Macaulay2 Engine: mutableMatrix_from_NTL_mat_ZZ
mutableMatrix_from_NTL_mat_ZZ()
MutableMatrix* mutableMatrix_from_NTL_mat_ZZ (const NTL::mat_ZZ * A)
Definition at line 31 of file ntl-interface.cpp.
 {
   // AGAIN: form the TRANSPOSE of A
   size_t ncols = A->NumRows();
   size_t nrows = A->NumCols();
   MutableMatrix *B = MutableMatrix::zero_matrix(globalZZ, nrows, ncols, false);
   mpz_t a;
   mpz_init(a);
   for (size_t i = 0; i < ncols; i++)
     for (size_t j = 0; j < nrows; j++)
       {
         if ((*A)(i + 1, j + 1) != 0)
           {
             mat_ZZ_get_entry(A, i, j, a);
             B->set_entry(j, i, ring_elem(a));
           }
       }
   mpz_clear(a);
   return B;
 }
References globalZZ, mat_ZZ_get_entry(), MutableMatrix::set_entry(), and MutableMatrix::zero_matrix().