Macaulay2 Engine: rawSLPProductGate
rawSLPProductGate()
gmp_ZZ rawSLPProductGate (M2SLProgram * S, M2_arrayint a)
Definition at line 869 of file matrix.cpp.
 {
   return to_gmp_ZZ(S->value().addMProduct(a));
 }
References SLProgram::addMProduct(), to_gmp_ZZ(), and M2SLProgram::value().