Macaulay2 Engine: rawHomotopyToString
rawHomotopyToString()
M2_string rawHomotopyToString (M2Homotopy * H)
Definition at line 798 of file matrix.cpp.
 {
   buffer o;
   H->value().text_out(o);
   return o.to_string();
 }
References Homotopy::text_out(), buffer::to_string(), and M2Homotopy::value().