Macaulay2 Engine: rawSLEvaluatorSpecialize
rawSLEvaluatorSpecialize()
M2SLEvaluator* rawSLEvaluatorSpecialize (M2SLEvaluator * H, const MutableMatrix * parameters)
Definition at line 790 of file matrix.cpp.
 {
   try {
     return new M2SLEvaluator(H->value().specialize(parameters));
   } catch (const exc::engine_error& e) {
     ERROR(e.what());
     return nullptr;
   }
 }
References ERROR(), SLEvaluator::specialize(), and M2SLEvaluator::value().