Macaulay2 Engine: ExponentVector::simple_degree
simple_degree()
template<class E , bool OC> static Exponent ExponentVector< E, OC >::simple_degree (int nvars, ConstExponents a) inline static
Definition at line 185 of file ExponentVector.hpp.
   {
     // TODO: use std::accumulate?
     if (nvars == 0) return 0;
     Exponent sum = a[0];
     if constexpr (OC)
       for (int i = 1; i < nvars; i++)
         sum = safe::add(sum, a[i], "degree overflow");
     else
       for (int i = 1; i < nvars; i++) sum += a[i];
     return sum;
   }
References safe::add(), and mpfr::sum().
Referenced by Monoid::simple_degree(), and TEST().