Macaulay2 Engine: ExponentVector::mult
mult()
template<class E , bool OC> static void ExponentVector< E, OC >::mult (int nvars, ConstExponents a, ConstExponents b, Exponents result) inline static
Definition at line 65 of file ExponentVector.hpp.
   {
     if constexpr (OC)
       for (int i = nvars; i > 0; i--) *result++ = safe::add(*a++, *b++);
     else
       for (int i = nvars; i > 0; i--) *result++ = *a++ + *b++;
   }
References safe::add().
Referenced by KBasis::basis0_multi_graded(), GBRingPoly::mult_by_term1(), TEST(), and ResMonomialSorter::toMonomial().