Macaulay2 Engine: ExponentVector::copy
copy()
template<class E , bool OC> static void ExponentVector< E, OC >::copy (int nvars, ConstExponents a, Exponents result) inline static
Definition at line 39 of file ExponentVector.hpp.
   {
     memcpy(result, a, nvars * sizeof(Exponent));
   }
Referenced by PolyRing::get_logical_coeff(), KBasis::KBasis(), PolyRing::lead_logical_exponents(), PolyRing::make_logical_term(), and TEST().