Macaulay2 Engine: ExponentVector::lex_compare
lex_compare()
template<class E , bool OC> static int ExponentVector< E, OC >::lex_compare (int nvars, ConstExponents a, ConstExponents b) inline static
Definition at line 174 of file ExponentVector.hpp.
   {
     for (int i = 0; i < nvars; i++)
       if (a[i] > b[i])
         return GT;
       else if (a[i] < b[i])
         return LT;
     return EQ;
   }
References EQ, GT, and LT.
Referenced by PolyRing::get_coeff(), PolyRing::get_logical_coeff(), PolyRing::get_terms(), PolyRing::n_logical_terms(), TEST(), and KBasis::try_insert_mg().