Macaulay2 Engine: ExponentVector::quotient
quotient()
template<class E , bool OC> static void ExponentVector< E, OC >::quotient (int nvars, ConstExponents a, ConstExponents b, Exponents result) inline static
Definition at line 124 of file ExponentVector.hpp.
   {
     if constexpr (OC)
       for (int i = nvars; i > 0; i--)
         {
           // TODO: if a,b>=0 always, there would never be an overflow
           assert(*a >= 0 && *b >= 0);
           *result++ = safe::sub_pos(*a++, *b++);
         }
     else
       for (int i = 0; i < nvars; i++)
         {
           Exponent x = *a++;
           Exponent y = *b++;
           *result++ = (x <= y ? 0 : x - y);
         }
   }
References safe::sub_pos(), and x.
Referenced by PolyRing::divide_by_expvector(), and TEST().