Macaulay2 Engine: ExponentVector::lcm
lcm()
template<class E , bool OC> static void ExponentVector< E, OC >::lcm (int nvars, ConstExponents a, ConstExponents b, Exponents result) inline static
Definition at line 160 of file ExponentVector.hpp.
   {
     for (int i = nvars; i > 0; i--)
       {
         Exponent x = *a++;
         Exponent y = *b++;
         *result++ = (x > y ? x : y);
       }
   }
References x.
Referenced by Monoid::lcm(), PolyRing::support(), and TEST().