Macaulay2 Engine: ExponentVector::weight
weight() [1/2]
template<class E , bool OC> static Exponent ExponentVector< E, OC >::weight (int nvars, ConstExponents a, const std::vector< Exponent > & wts) inline static
Definition at line 199 of file ExponentVector.hpp.
   {
     // TODO: use std::inner_product?
     Exponent top = wts.size();
     if (nvars < top) top = nvars;
     if (top == 0) return 0;
     Exponent sum = safe::mult(a[0], wts[0]);
     for (int i = 1; i < top; i++)
       sum = safe::add(sum, safe::mult(a[i], wts[i]), "weight overflow");
     return sum;
   }
References safe::add(), safe::mult(), and mpfr::sum().
Referenced by KBasis::compute(), Monoid::degree_weights(), GBWeight::exponents_weight(), PolyRing::get_part(), PolyRing::homogenize(), KBasis::KBasis(), Monoid::set_degrees(), res2_comp::sort_value(), res_comp::sort_value(), TEST(), and ExponentVector< E, OC >::weight().