Macaulay2 Engine: NaivePolynomialHeap::value
value()
template<template< typename > class Queue> Poly * NaivePolynomialHeap< Queue >::value () inline override virtual
Implements PolynomialHeap.
Definition at line 420 of file NCReduction.cpp.
  {
    Poly* f = new Poly;
    if (mLeadTermSet)
      mQueue.push(mLeadTerm);
    mLeadTermSet = false;
    while (not isZero())
      {
        auto tm = viewLeadTerm();
        mRing.add_to_end(*f, tm.second, tm.first);
        removeLeadTerm();
      }
    addPolynomial(*f);
    return f;
  }
References FreeAlgebra::add_to_end(), NaivePolynomialHeap< Queue >::addPolynomial(), NaivePolynomialHeap< Queue >::isZero(), NaivePolynomialHeap< Queue >::mLeadTerm, NaivePolynomialHeap< Queue >::mLeadTermSet, NaivePolynomialHeap< Queue >::mQueue, NaivePolynomialHeap< Queue >::mRing, NaivePolynomialHeap< Queue >::removeLeadTerm(), and NaivePolynomialHeap< Queue >::viewLeadTerm().