Macaulay2 Engine: NaivePolynomialHeap::addPolynomial
addPolynomial() [1/2]
template<template< typename > class Queue> NaivePolynomialHeap & NaivePolynomialHeap< Queue >::addPolynomial (const Poly & poly) inline override virtual
Implements PolynomialHeap.
Definition at line 339 of file NCReduction.cpp.
  {
    if (mLeadTermSet)
      {
        mQueue.push(mLeadTerm);
        mLeadTermSet = false;
      }
    for (auto i = poly.cbegin(); i != poly.cend(); ++i)
      {
        auto rg = mMonomialSpace.allocateArray<int>(i.monom().size());
        std::copy(i.monom().begin(), i.monom().end(), rg.first);
        mQueue.push(Entry(Monom(rg.first), i.coeff()));
      }
    return *this;
  }
References MemoryBlock::allocateArray(), NaivePolynomialHeap< Queue >::mLeadTerm, NaivePolynomialHeap< Queue >::mLeadTermSet, NaivePolynomialHeap< Queue >::mMonomialSpace, and NaivePolynomialHeap< Queue >::mQueue.
Referenced by NaivePolynomialHeap< Queue >::addPolynomial(), and NaivePolynomialHeap< Queue >::value().