Macaulay2 Engine: NaivePolynomialHeap::isZero
isZero()
template<template< typename > class Queue> bool NaivePolynomialHeap< Queue >::isZero () inline override virtual
Implements PolynomialHeap.
Definition at line 366 of file NCReduction.cpp.
   {
     if (mLeadTermSet) return false;
     if (mQueue.empty()) return true;
     Entry lt = mQueue.pop();
     while (not mQueue.empty())
       {
         Entry e = mQueue.top();
         // this is bad - compare should not be used to check equality
         if (mRing.monoid().compare(e.first, lt.first) == EQ)
           {
             lt.second = mRing.coefficientRing()->add(lt.second, e.second);
             mQueue.pop();
           }
         else
           {
             if (not mRing.coefficientRing()->is_zero(lt.second))
               {
                 mLeadTermSet = true;
                 mLeadTerm = lt;
                 return false;
               }
             else
               lt = mQueue.pop();
           }
       }
     if (not mRing.coefficientRing()->is_zero(lt.second))
       {
         mLeadTermSet = true;
         mLeadTerm = lt;
         return false;
       }
     return true;
   }
References Ring::add(), FreeAlgebra::coefficientRing(), FreeMonoid::compare(), EQ, Ring::is_zero(), NaivePolynomialHeap< Queue >::mLeadTerm, NaivePolynomialHeap< Queue >::mLeadTermSet, FreeAlgebra::monoid(), NaivePolynomialHeap< Queue >::mQueue, and NaivePolynomialHeap< Queue >::mRing.
Referenced by NaivePolynomialHeap< Queue >::removeLeadTerm(), NaivePolynomialHeap< Queue >::value(), and NaivePolynomialHeap< Queue >::viewLeadTerm().