Macaulay2 Engine: GF::eval
eval()
ring_elem GF::eval (const RingMap * map, const ring_elem f, int first_var) const virtual
Implements Ring.
Definition at line 203 of file GF.cpp.
 {
   return map->get_ring()->power(map->elem(first_var), f.get_int());
 }
References RingMap::elem(), ring_elem::get_int(), RingMap::get_ring(), and Ring::power().