Macaulay2 Engine: GF::promote
promote()
bool GF::promote (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 251 of file GF.cpp.
 {
   // Rf = Z/p[x]/F(x) ---> GF(p,n)
   // promotion: need to be able to know the value of 'x'.
   // lift: need to compute (primite_element)^e
   if (Rf != _originalR) return false;
   const Ring *K = _originalR->getCoefficients();
   result = from_long(0);
   int exp[1];
   for (Nterm& t : f)
     {
       std::pair<bool, long> b = K->coerceToLongInteger(t.coeff);
       assert(b.first);
       ring_elem coef = from_long(b.second);
       _originalR->getMonoid()->to_expvector(t.monom, exp);
       // exp[0] is the variable we want.  Notice that since the ring is a
       // quotient,
       // this degree is < n (where Q_ = P^n).
       ring_elem g = power(_x_exponent, exp[0]);
       g = mult(g, coef);
       result = ring_elem(internal_add(result.get_int(), g.get_int()));
     }
   return true;
 }
References _originalR, _x_exponent, Ring::coerceToLongInteger(), mpfr::exp(), from_long(), ring_elem::get_int(), PolynomialRing::getCoefficients(), PolynomialRing::getMonoid(), internal_add(), mult(), power(), and Monoid::to_expvector().