Macaulay2 Engine: GF::power
power() [2/2]
ring_elem GF::power (const ring_elem f, mpz_srcptr n) const virtual
Reimplemented from Ring.
Definition at line 396 of file GF.cpp.
 {
   if (f.get_int() != _ZERO)
     {
       int exp = RingZZ::mod_ui(n, Q1_);
       int m = (f.get_int() * exp) % Q1_; // WARNING TODO: possible overflow! Check!
       if (m <= 0) m += Q1_;
       return ring_elem(m);
     }
   else
     {
       if (mpz_sgn(n) == 0)
         return ring_elem(_ONE);
       else if (mpz_sgn(n) > 0)
         return ring_elem(_ZERO);
       else
         throw exc::division_by_zero_error();
     }
 }
References _ONE, _ZERO, mpfr::exp(), ring_elem::get_int(), RingZZ::mod_ui(), and Q1_.
Referenced by promote().