Macaulay2 Engine: GF::internal_subtract
internal_subtract()
int GF::internal_subtract (int f, int g) const private
Definition at line 349 of file GF.cpp.
{
  if (g == _ZERO) return f;
  if (f == g) return _ZERO;
  int g1 = modulus_add(g, _MINUS_ONE, Q1_);  // f = -g
  return internal_add(f, g1);
}
References _MINUS_ONE, _ZERO, internal_add(), modulus_add(), and Q1_.
Referenced by subtract().