Macaulay2 Engine: GF::from_long
from_long()
ring_elem GF::from_long (long n) const virtual
Implements Ring.
Definition at line 208 of file GF.cpp.
 {
   long m1 = n % characteristic();
   if (m1 < 0) m1 += characteristic();
   int m = static_cast<int>(m1);
   m = _from_int_table[m];
   return ring_elem(m);
 }
References _from_int_table, and Ring::characteristic().
Referenced by from_rational(), initialize_GF(), promote(), and syzygy().