Macaulay2 Engine: GF::create
create()
GF * GF::create (const RingElement * prim) static
Definition at line 127 of file GF.cpp.
 {
   GF *result = new GF;
   if (!result->initialize_GF(prim)) return 0;
   return result;
 }
References GF(), and initialize_GF().
Referenced by rawGaloisField().