Macaulay2 Engine: GF::elem_text_out
elem_text_out()
void GF::elem_text_out (buffer & o, const ring_elem f, bool p_one = true, bool p_plus = false, bool p_parens = false) const virtual
Implements Ring.
Definition at line 187 of file GF.cpp.
{
  if (a.get_int() == _ZERO)
    {
      o << "0";
      return;
    }
  ring_elem h = _originalR->power(_primitive_element->get_value(), a.get_int());
  _originalR->elem_text_out(o, h, p_one, p_plus, p_parens);
  _originalR->remove(h);
}
References _originalR, _primitive_element, _ZERO, Ring::elem_text_out(), ring_elem::get_int(), RingElement::get_value(), Ring::power(), and Ring::remove().