Macaulay2 Engine: GF::lift
lift()
bool GF::lift (const Ring * R, const ring_elem f, ring_elem & result) const virtual
Implements Ring.
Definition at line 279 of file GF.cpp.
 {
   // Rg = Z/p[x]/F(x) ---> GF(p,n)
   // promotion: need to be able to know the value of 'x'.
   // lift: need to compute (primite_element)^e
   if (Rg != _originalR) return false;
   int e = f.get_int();
   if (e == _ZERO)
     result = _originalR->from_long(0);
   else if (e == _ONE)
     result = _originalR->from_long(1);
   else
     result = _originalR->power(_primitive_element->get_value(), e);
   return true;
 }
References _ONE, _originalR, _primitive_element, _ZERO, Ring::from_long(), ring_elem::get_int(), RingElement::get_value(), and Ring::power().