Macaulay2 Engine: GF::initialize_GF
initialize_GF()
bool GF::initialize_GF (const RingElement * prim) protected
Definition at line 39 of file GF.cpp.
 {
   // set the GF ring tables.  Returns false if there is an error.
   _primitive_element = prim;
   _originalR = prim->get_ring()->cast_to_PolynomialRing();
   initialize_ring(_originalR->characteristic(),
                   PolyRing::get_trivial_poly_ring());
   declare_field();
   int i, j;
   if (_originalR->n_quotients() != 1)
     {
       throw exc::engine_error(
           "rawGaloisField expected an element of a quotient ring of the form "
           "ZZ/p[x]/(f)");
     }
   ring_elem f = _originalR->quotient_element(0);
   Nterm *t = f;
   int n = _originalR->getMonoid()->primary_degree(t->monom);
   Q_ = static_cast<int>(characteristic());
   for (i = 1; i < n; i++) Q_ *= static_cast<int>(characteristic());
   Qexp_ = n;
   Q1_ = Q_ - 1;
   _ZERO = 0;
   _ONE = Q1_;
   _MINUS_ONE = (characteristic() == 2 ? _ONE : Q1_ / 2);
   // Get ready to create the 'one_table'
   VECTOR(ring_elem) polys;
   polys.push_back(_originalR->from_long(0));
   ring_elem primelem = prim->get_value();
   polys.push_back(_originalR->copy(primelem));
   ring_elem oneR = _originalR->one();
   _x_exponent = -1;
   ring_elem x = _originalR->var(0);
   if (_originalR->is_equal(primelem, x)) _x_exponent = 1;
   for (i = 2; i < Q_; i++)
     {
       ring_elem g = _originalR->mult(polys[i - 1], primelem);
       polys.push_back(g);
       if (_originalR->is_equal(g, oneR)) break;
       if (_originalR->is_equal(g, x)) _x_exponent = i;
     }
   if (polys.size() != Q_)
     {
       throw exc::engine_error("GF: primitive element expected");
     }
   assert(_x_exponent >= 0);
   // Set 'one_table'.
   _one_table = newarray_atomic(int, Q_);
   _one_table[0] = Q_ - 1;
   for (i = 1; i <= Q_ - 1; i++)
     {
       if (system_interrupted()) return false;
       ring_elem f1 = _originalR->add(polys[i], oneR);
       for (j = 1; j <= Q_ - 1; j++)
         if (_originalR->is_equal(f1, polys[j])) break;
       _one_table[i] = j;
     }
   // Create the Z/P ---> GF(Q) inclusion map
   _from_int_table = newarray_atomic(int, characteristic());
   int a = _ONE;
   _from_int_table[0] = _ZERO;
   for (i = 1; i < characteristic(); i++)
     {
       _from_int_table[i] = a;
       a = _one_table[a];
     }
   zeroV = from_long(0);
   oneV = from_long(1);
   minus_oneV = from_long(-1);
   return true;
 }
References _from_int_table, _MINUS_ONE, _ONE, _one_table, _originalR, _primitive_element, _x_exponent, _ZERO, Ring::add(), Ring::cast_to_PolynomialRing(), Ring::characteristic(), Ring::copy(), Ring::declare_field(), from_long(), Ring::from_long(), RingElement::get_ring(), PolyRing::get_trivial_poly_ring(), RingElement::get_value(), PolynomialRing::getMonoid(), Ring::initialize_ring(), Ring::is_equal(), Ring::minus_oneV, Nterm::monom, Ring::mult(), PolynomialRing::n_quotients(), newarray_atomic, Ring::one(), Ring::oneV, Monoid::primary_degree(), Q1_, Q_, Qexp_, PolynomialRing::quotient_element(), system_interrupted(), PolynomialRing::var(), VECTOR(), x, and Ring::zeroV.
Referenced by create().