Macaulay2 Engine: GF::internal_negate
internal_negate()
int GF::internal_negate (int f) const private
Definition at line 320 of file GF.cpp.
{
  if (f == _ZERO) return _ZERO;
  return f = modulus_add(f, _MINUS_ONE, Q1_);
}
References _MINUS_ONE, _ZERO, modulus_add(), and Q1_.
Referenced by negate(), and syzygy().