Macaulay2 Engine: GF::getRepresentation
getRepresentation()
const RingElement * GF::getRepresentation (const ring_elem & a) const virtual
Reimplemented from Ring.
Definition at line 149 of file GF.cpp.
{
  return RingElement::make_raw(
      _originalR,
      _originalR->power(_primitive_element->get_value(), a.get_int()));
}
References _originalR, _primitive_element, ring_elem::get_int(), RingElement::get_value(), and Ring::power().