Macaulay2 Engine: GF::divide
divide()
ring_elem GF::divide (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 424 of file GF.cpp.
 {
   if (g.get_int() == _ZERO)
     throw exc::division_by_zero_error();
   if (f.get_int() == _ZERO) return ring_elem(_ZERO);
   return modulus_sub(f.get_int(), g.get_int(), Q1_);
 }
References _ZERO, ring_elem::get_int(), modulus_sub(), and Q1_.
Referenced by syzygy().