Macaulay2 Engine: GF::from_rational
from_rational()
bool GF::from_rational (mpq_srcptr q, ring_elem & result) const virtual
Implements Ring.
Definition at line 230 of file GF.cpp.
 {
   // a will be an element of ZZ/p
   ring_elem a;
   bool ok1 = _originalR->getCoefficients()->from_rational(q, a);
   if (not ok1) return false;
   std::pair<bool, long> b =
       _originalR->getCoefficients()->coerceToLongInteger(a);
   if (b.first)
     {
       result = GF::from_long(b.second);
       return true;
     }
   return false;
 }
References _originalR, Ring::coerceToLongInteger(), from_long(), Ring::from_rational(), and PolynomialRing::getCoefficients().