Macaulay2 Engine: GF::mult
mult()
ring_elem GF::mult (const ring_elem f, const ring_elem g) const virtual
Implements Ring.
Definition at line 372 of file GF.cpp.
 {
   if (f.get_int() == _ZERO || g.get_int() == _ZERO) return ring_elem(_ZERO);
   return ring_elem(modulus_add(f.get_int(), g.get_int(), Q1_));
 }
References _ZERO, ring_elem::get_int(), modulus_add(), and Q1_.
Referenced by promote().